.TH maptool 1  "$Date$" "$Revision$" "USER COMMANDS"
.SH NAME
maptool \- parse osm textfile and convert to Navit binfile format
.SH SYNOPSIS
.B maptool \-i planet.osm.pbf planet.bin
[\-h] [\-6] [\-a <level>] [\-c] [\-d <connect string>]
[\-e <phase>] [\-k] [\-M] [\-N] [\-o] [\-P] [\-r <file>] [\-s <phase>]
[\-S <size>] [\-w] [\-W] [\-U] [\-z <level>]

.B bzcat planet.osm.bz2 | maptool planet.bin
.SH DESCRIPTION
maptool reads OSM data and converts it to Navit binfile format.

If you give an input file with \-i, maptool detects the format from the file
name. maptool recognizes
.BR .osm ,
.BR .osm.gz ,
.BR .osm.bz2 ,
.B .pbf
and
.BR .o5m .
The options \-P and \-M are not necessary for these files.

maptool cannot detect the format of data from standard input. For standard
input, maptool assumes OSM XML. The \-P option selects pbf data. The \-M option
selects o5m data.
.SH OPTIONS
.TP
\-h (\-\-help)
display a short help message
.TP
\-6 (\-\-64bit)
set zip 64 bit compression
.TP
\-a (\-\-attr-debug-level) <level>
control which data is included in the debug attribute
.TP
\-c (\-\-dump-coordinates)
dump coordinates after phase 1
.TP
\-d (\-\-db) <connect string>
get osm data out of a postgresql database with osm simple scheme and given connect string
.TP
\-D (\-\-dump)
dump map data to standard output in Navit textfile format
If this option is specified, the output file parameter must be omitted.
.TP
\-e (\-\-end) <phase>
end at specified phase
.TP
\-E (\-\-experimental)
enable experimental features (if available)
.TP
\-i (\-\-input-file) <file>
specify the input file name (OSM), overrules default stdin. maptool detects the
format from the file name suffix
.TP
\-k (\-\-keep-tmpfiles)
do not delete tmp files after processing. useful to reuse them
.TP
\-M (\-\-o5m)
the data from standard input is in o5m format. With \-i, maptool detects the
format, and this option is not necessary
.TP
\-n (\-\-ignore-unknown)
do not output ways and nodes with unknown type
.TP
\-N (\-\-nodes-only)
process only nodes
.TP
\-P (\-\-protobuf)
the data from standard input is in pbf (Protocol Buffer) format. With \-i,
maptool detects the format, and this option is not necessary
.TP
\-r (\-\-rule-file) <file>
read mapping rules from specified file
.TP
\-s (\-\-start) <phase>
start at specified phase
.TP
\-S (\-\-slice-size) <phrase>
limit memory to use for some large internal buffers, in bytes. Default is 1 GB.
Smaller slices reduce peak memory usage, at the cost of increased processing time.
.TP
\-t (\-\-timestamp) <y-m-dTh:m:s>
set zip timestamp
.TP
\-w (\-\-dedupe-ways)
ensure no duplicate ways or nodes. useful when using several input files
.TP
\-W (\-\-ways-only)
process only ways
.TP
\-U (\-\-unknown-country)
add objects with unknown country to index
.TP
\-x (\-\-index-size)
set maximum country index size in bytes
.TP
\-z (\-\-compression-level) <level>
set the compression level
.SH BUGS
Should you find one, please report it :
 http://trac.navit-project.org
.SH AUTHOR
The navit Team - http://www.navit-project.org
.SH SEE ALSO
navit(1)
