void spotify_navit_init();
void spotify_navit (struct navit *nav, int add);
void spotify_set_attr(struct attr **attrs);
void gui_internal_spotify_show_playlist(struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_show_rootlist(struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_toggle (struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_previous_track (struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_next_track (struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_volume_down (struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_volume_up (struct gui_priv *this, struct widget *wm, void *data);
void gui_internal_spotify_volume_toggle (struct gui_priv *this, struct widget *wm, void *data);
