/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_fileformat_2eproto__INCLUDED
#define PROTOBUF_C_fileformat_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _OSMPBF__Blob OSMPBF__Blob;
typedef struct _OSMPBF__BlobHeader OSMPBF__BlobHeader;


/* --- enums --- */


/* --- messages --- */

struct  _OSMPBF__Blob
{
  ProtobufCMessage base;
  protobuf_c_boolean has_raw;
  ProtobufCBinaryData raw;
  protobuf_c_boolean has_raw_size;
  int32_t raw_size;
  protobuf_c_boolean has_zlib_data;
  ProtobufCBinaryData zlib_data;
  protobuf_c_boolean has_lzma_data;
  ProtobufCBinaryData lzma_data;
  protobuf_c_boolean has_obsolete_bzip2_data PROTOBUF_C_DEPRECATED;
  ProtobufCBinaryData obsolete_bzip2_data PROTOBUF_C_DEPRECATED;
};
#define OSMPBF__BLOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&osmpbf__blob__descriptor) \
    , 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL} }


struct  _OSMPBF__BlobHeader
{
  ProtobufCMessage base;
  char *type;
  protobuf_c_boolean has_indexdata;
  ProtobufCBinaryData indexdata;
  int32_t datasize;
};
#define OSMPBF__BLOB_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&osmpbf__blob_header__descriptor) \
    , NULL, 0,{0,NULL}, 0 }


/* OSMPBF__Blob methods */
void   osmpbf__blob__init
                     (OSMPBF__Blob         *message);
size_t osmpbf__blob__get_packed_size
                     (const OSMPBF__Blob   *message);
size_t osmpbf__blob__pack
                     (const OSMPBF__Blob   *message,
                      uint8_t             *out);
size_t osmpbf__blob__pack_to_buffer
                     (const OSMPBF__Blob   *message,
                      ProtobufCBuffer     *buffer);
OSMPBF__Blob *
       osmpbf__blob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   osmpbf__blob__free_unpacked
                     (OSMPBF__Blob *message,
                      ProtobufCAllocator *allocator);
/* OSMPBF__BlobHeader methods */
void   osmpbf__blob_header__init
                     (OSMPBF__BlobHeader         *message);
size_t osmpbf__blob_header__get_packed_size
                     (const OSMPBF__BlobHeader   *message);
size_t osmpbf__blob_header__pack
                     (const OSMPBF__BlobHeader   *message,
                      uint8_t             *out);
size_t osmpbf__blob_header__pack_to_buffer
                     (const OSMPBF__BlobHeader   *message,
                      ProtobufCBuffer     *buffer);
OSMPBF__BlobHeader *
       osmpbf__blob_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   osmpbf__blob_header__free_unpacked
                     (OSMPBF__BlobHeader *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*OSMPBF__Blob_Closure)
                 (const OSMPBF__Blob *message,
                  void *closure_data);
typedef void (*OSMPBF__BlobHeader_Closure)
                 (const OSMPBF__BlobHeader *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor osmpbf__blob__descriptor;
extern const ProtobufCMessageDescriptor osmpbf__blob_header__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_fileformat_2eproto__INCLUDED */
