/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "osmformat.pb-c.h"
void   osmpbf__header_block__init
(OSMPBF__HeaderBlock         *message) {
    static OSMPBF__HeaderBlock init_value = OSMPBF__HEADER_BLOCK__INIT;
    *message = init_value;
}
size_t osmpbf__header_block__get_packed_size
(const OSMPBF__HeaderBlock *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_block__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__header_block__pack
(const OSMPBF__HeaderBlock *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_block__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__header_block__pack_to_buffer
(const OSMPBF__HeaderBlock *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_block__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__HeaderBlock *
osmpbf__header_block__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__HeaderBlock *)
           protobuf_c_message_unpack (&osmpbf__header_block__descriptor,
                                      allocator, len, data);
}
void   osmpbf__header_block__free_unpacked
(OSMPBF__HeaderBlock *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_block__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__header_bbox__init
(OSMPBF__HeaderBBox         *message) {
    static OSMPBF__HeaderBBox init_value = OSMPBF__HEADER_BBOX__INIT;
    *message = init_value;
}
size_t osmpbf__header_bbox__get_packed_size
(const OSMPBF__HeaderBBox *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_bbox__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__header_bbox__pack
(const OSMPBF__HeaderBBox *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_bbox__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__header_bbox__pack_to_buffer
(const OSMPBF__HeaderBBox *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_bbox__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__HeaderBBox *
osmpbf__header_bbox__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__HeaderBBox *)
           protobuf_c_message_unpack (&osmpbf__header_bbox__descriptor,
                                      allocator, len, data);
}
void   osmpbf__header_bbox__free_unpacked
(OSMPBF__HeaderBBox *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__header_bbox__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__primitive_block__init
(OSMPBF__PrimitiveBlock         *message) {
    static OSMPBF__PrimitiveBlock init_value = OSMPBF__PRIMITIVE_BLOCK__INIT;
    *message = init_value;
}
size_t osmpbf__primitive_block__get_packed_size
(const OSMPBF__PrimitiveBlock *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_block__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__primitive_block__pack
(const OSMPBF__PrimitiveBlock *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_block__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__primitive_block__pack_to_buffer
(const OSMPBF__PrimitiveBlock *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_block__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__PrimitiveBlock *
osmpbf__primitive_block__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__PrimitiveBlock *)
           protobuf_c_message_unpack (&osmpbf__primitive_block__descriptor,
                                      allocator, len, data);
}
void   osmpbf__primitive_block__free_unpacked
(OSMPBF__PrimitiveBlock *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_block__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__primitive_group__init
(OSMPBF__PrimitiveGroup         *message) {
    static OSMPBF__PrimitiveGroup init_value = OSMPBF__PRIMITIVE_GROUP__INIT;
    *message = init_value;
}
size_t osmpbf__primitive_group__get_packed_size
(const OSMPBF__PrimitiveGroup *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_group__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__primitive_group__pack
(const OSMPBF__PrimitiveGroup *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_group__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__primitive_group__pack_to_buffer
(const OSMPBF__PrimitiveGroup *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_group__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__PrimitiveGroup *
osmpbf__primitive_group__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__PrimitiveGroup *)
           protobuf_c_message_unpack (&osmpbf__primitive_group__descriptor,
                                      allocator, len, data);
}
void   osmpbf__primitive_group__free_unpacked
(OSMPBF__PrimitiveGroup *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__primitive_group__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__string_table__init
(OSMPBF__StringTable         *message) {
    static OSMPBF__StringTable init_value = OSMPBF__STRING_TABLE__INIT;
    *message = init_value;
}
size_t osmpbf__string_table__get_packed_size
(const OSMPBF__StringTable *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__string_table__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__string_table__pack
(const OSMPBF__StringTable *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__string_table__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__string_table__pack_to_buffer
(const OSMPBF__StringTable *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__string_table__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__StringTable *
osmpbf__string_table__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__StringTable *)
           protobuf_c_message_unpack (&osmpbf__string_table__descriptor,
                                      allocator, len, data);
}
void   osmpbf__string_table__free_unpacked
(OSMPBF__StringTable *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__string_table__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__info__init
(OSMPBF__Info         *message) {
    static OSMPBF__Info init_value = OSMPBF__INFO__INIT;
    *message = init_value;
}
size_t osmpbf__info__get_packed_size
(const OSMPBF__Info *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__info__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__info__pack
(const OSMPBF__Info *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__info__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__info__pack_to_buffer
(const OSMPBF__Info *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__info__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__Info *
osmpbf__info__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__Info *)
           protobuf_c_message_unpack (&osmpbf__info__descriptor,
                                      allocator, len, data);
}
void   osmpbf__info__free_unpacked
(OSMPBF__Info *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__info__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__dense_info__init
(OSMPBF__DenseInfo         *message) {
    static OSMPBF__DenseInfo init_value = OSMPBF__DENSE_INFO__INIT;
    *message = init_value;
}
size_t osmpbf__dense_info__get_packed_size
(const OSMPBF__DenseInfo *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_info__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__dense_info__pack
(const OSMPBF__DenseInfo *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_info__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__dense_info__pack_to_buffer
(const OSMPBF__DenseInfo *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_info__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__DenseInfo *
osmpbf__dense_info__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__DenseInfo *)
           protobuf_c_message_unpack (&osmpbf__dense_info__descriptor,
                                      allocator, len, data);
}
void   osmpbf__dense_info__free_unpacked
(OSMPBF__DenseInfo *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_info__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__change_set__init
(OSMPBF__ChangeSet         *message) {
    static OSMPBF__ChangeSet init_value = OSMPBF__CHANGE_SET__INIT;
    *message = init_value;
}
size_t osmpbf__change_set__get_packed_size
(const OSMPBF__ChangeSet *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__change_set__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__change_set__pack
(const OSMPBF__ChangeSet *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__change_set__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__change_set__pack_to_buffer
(const OSMPBF__ChangeSet *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__change_set__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__ChangeSet *
osmpbf__change_set__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__ChangeSet *)
           protobuf_c_message_unpack (&osmpbf__change_set__descriptor,
                                      allocator, len, data);
}
void   osmpbf__change_set__free_unpacked
(OSMPBF__ChangeSet *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__change_set__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__node__init
(OSMPBF__Node         *message) {
    static OSMPBF__Node init_value = OSMPBF__NODE__INIT;
    *message = init_value;
}
size_t osmpbf__node__get_packed_size
(const OSMPBF__Node *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__node__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__node__pack
(const OSMPBF__Node *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__node__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__node__pack_to_buffer
(const OSMPBF__Node *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__node__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__Node *
osmpbf__node__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__Node *)
           protobuf_c_message_unpack (&osmpbf__node__descriptor,
                                      allocator, len, data);
}
void   osmpbf__node__free_unpacked
(OSMPBF__Node *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__node__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__dense_nodes__init
(OSMPBF__DenseNodes         *message) {
    static OSMPBF__DenseNodes init_value = OSMPBF__DENSE_NODES__INIT;
    *message = init_value;
}
size_t osmpbf__dense_nodes__get_packed_size
(const OSMPBF__DenseNodes *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_nodes__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__dense_nodes__pack
(const OSMPBF__DenseNodes *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_nodes__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__dense_nodes__pack_to_buffer
(const OSMPBF__DenseNodes *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_nodes__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__DenseNodes *
osmpbf__dense_nodes__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__DenseNodes *)
           protobuf_c_message_unpack (&osmpbf__dense_nodes__descriptor,
                                      allocator, len, data);
}
void   osmpbf__dense_nodes__free_unpacked
(OSMPBF__DenseNodes *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__dense_nodes__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__way__init
(OSMPBF__Way         *message) {
    static OSMPBF__Way init_value = OSMPBF__WAY__INIT;
    *message = init_value;
}
size_t osmpbf__way__get_packed_size
(const OSMPBF__Way *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__way__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__way__pack
(const OSMPBF__Way *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__way__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__way__pack_to_buffer
(const OSMPBF__Way *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__way__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__Way *
osmpbf__way__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__Way *)
           protobuf_c_message_unpack (&osmpbf__way__descriptor,
                                      allocator, len, data);
}
void   osmpbf__way__free_unpacked
(OSMPBF__Way *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__way__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   osmpbf__relation__init
(OSMPBF__Relation         *message) {
    static OSMPBF__Relation init_value = OSMPBF__RELATION__INIT;
    *message = init_value;
}
size_t osmpbf__relation__get_packed_size
(const OSMPBF__Relation *message) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__relation__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t osmpbf__relation__pack
(const OSMPBF__Relation *message,
 uint8_t       *out) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__relation__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t osmpbf__relation__pack_to_buffer
(const OSMPBF__Relation *message,
 ProtobufCBuffer *buffer) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__relation__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OSMPBF__Relation *
osmpbf__relation__unpack
(ProtobufCAllocator  *allocator,
 size_t               len,
 const uint8_t       *data) {
    return (OSMPBF__Relation *)
           protobuf_c_message_unpack (&osmpbf__relation__descriptor,
                                      allocator, len, data);
}
void   osmpbf__relation__free_unpacked
(OSMPBF__Relation *message,
 ProtobufCAllocator *allocator) {
    PROTOBUF_C_ASSERT (message->base.descriptor == &osmpbf__relation__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor osmpbf__header_block__field_descriptors[5] = {
    {
        "bbox",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, bbox),
        &osmpbf__header_bbox__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "required_features",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_STRING,
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, n_required_features),
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, required_features),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "optional_features",
        5,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_STRING,
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, n_optional_features),
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, optional_features),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "writingprogram",
        16,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, writingprogram),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "source",
        17,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_STRING,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBlock, source),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__header_block__field_indices_by_name[] = {
    0,   /* field[0] = bbox */
    2,   /* field[2] = optional_features */
    1,   /* field[1] = required_features */
    4,   /* field[4] = source */
    3,   /* field[3] = writingprogram */
};
static const ProtobufCIntRange osmpbf__header_block__number_ranges[3 + 1] = {
    { 1, 0 },
    { 4, 1 },
    { 16, 3 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__header_block__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.HeaderBlock",
    "HeaderBlock",
    "OSMPBF__HeaderBlock",
    "OSMPBF",
    sizeof(OSMPBF__HeaderBlock),
    5,
    osmpbf__header_block__field_descriptors,
    osmpbf__header_block__field_indices_by_name,
    3,  osmpbf__header_block__number_ranges,
    (ProtobufCMessageInit) osmpbf__header_block__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__header_bbox__field_descriptors[4] = {
    {
        "left",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBBox, left),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "right",
        2,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBBox, right),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "top",
        3,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBBox, top),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "bottom",
        4,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__HeaderBBox, bottom),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__header_bbox__field_indices_by_name[] = {
    3,   /* field[3] = bottom */
    0,   /* field[0] = left */
    1,   /* field[1] = right */
    2,   /* field[2] = top */
};
static const ProtobufCIntRange osmpbf__header_bbox__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 4 }
};
const ProtobufCMessageDescriptor osmpbf__header_bbox__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.HeaderBBox",
    "HeaderBBox",
    "OSMPBF__HeaderBBox",
    "OSMPBF",
    sizeof(OSMPBF__HeaderBBox),
    4,
    osmpbf__header_bbox__field_descriptors,
    osmpbf__header_bbox__field_indices_by_name,
    1,  osmpbf__header_bbox__number_ranges,
    (ProtobufCMessageInit) osmpbf__header_bbox__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t osmpbf__primitive_block__granularity__default_value = 100;
static const int64_t osmpbf__primitive_block__lat_offset__default_value = 0;
static const int64_t osmpbf__primitive_block__lon_offset__default_value = 0;
static const int32_t osmpbf__primitive_block__date_granularity__default_value = 1000;
static const ProtobufCFieldDescriptor osmpbf__primitive_block__field_descriptors[6] = {
    {
        "stringtable",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, stringtable),
        &osmpbf__string_table__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "primitivegroup",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, n_primitivegroup),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, primitivegroup),
        &osmpbf__primitive_group__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "granularity",
        17,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, has_granularity),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, granularity),
        NULL,
        &osmpbf__primitive_block__granularity__default_value,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "date_granularity",
        18,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, has_date_granularity),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, date_granularity),
        NULL,
        &osmpbf__primitive_block__date_granularity__default_value,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lat_offset",
        19,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, has_lat_offset),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, lat_offset),
        NULL,
        &osmpbf__primitive_block__lat_offset__default_value,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lon_offset",
        20,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, has_lon_offset),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveBlock, lon_offset),
        NULL,
        &osmpbf__primitive_block__lon_offset__default_value,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__primitive_block__field_indices_by_name[] = {
    3,   /* field[3] = date_granularity */
    2,   /* field[2] = granularity */
    4,   /* field[4] = lat_offset */
    5,   /* field[5] = lon_offset */
    1,   /* field[1] = primitivegroup */
    0,   /* field[0] = stringtable */
};
static const ProtobufCIntRange osmpbf__primitive_block__number_ranges[2 + 1] = {
    { 1, 0 },
    { 17, 2 },
    { 0, 6 }
};
const ProtobufCMessageDescriptor osmpbf__primitive_block__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.PrimitiveBlock",
    "PrimitiveBlock",
    "OSMPBF__PrimitiveBlock",
    "OSMPBF",
    sizeof(OSMPBF__PrimitiveBlock),
    6,
    osmpbf__primitive_block__field_descriptors,
    osmpbf__primitive_block__field_indices_by_name,
    2,  osmpbf__primitive_block__number_ranges,
    (ProtobufCMessageInit) osmpbf__primitive_block__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__primitive_group__field_descriptors[5] = {
    {
        "nodes",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, n_nodes),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, nodes),
        &osmpbf__node__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "dense",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, dense),
        &osmpbf__dense_nodes__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "ways",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, n_ways),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, ways),
        &osmpbf__way__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "relations",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, n_relations),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, relations),
        &osmpbf__relation__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "changesets",
        5,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_MESSAGE,
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, n_changesets),
        PROTOBUF_C_OFFSETOF(OSMPBF__PrimitiveGroup, changesets),
        &osmpbf__change_set__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__primitive_group__field_indices_by_name[] = {
    4,   /* field[4] = changesets */
    1,   /* field[1] = dense */
    0,   /* field[0] = nodes */
    3,   /* field[3] = relations */
    2,   /* field[2] = ways */
};
static const ProtobufCIntRange osmpbf__primitive_group__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__primitive_group__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.PrimitiveGroup",
    "PrimitiveGroup",
    "OSMPBF__PrimitiveGroup",
    "OSMPBF",
    sizeof(OSMPBF__PrimitiveGroup),
    5,
    osmpbf__primitive_group__field_descriptors,
    osmpbf__primitive_group__field_indices_by_name,
    1,  osmpbf__primitive_group__number_ranges,
    (ProtobufCMessageInit) osmpbf__primitive_group__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__string_table__field_descriptors[1] = {
    {
        "s",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_BYTES,
        PROTOBUF_C_OFFSETOF(OSMPBF__StringTable, n_s),
        PROTOBUF_C_OFFSETOF(OSMPBF__StringTable, s),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__string_table__field_indices_by_name[] = {
    0,   /* field[0] = s */
};
static const ProtobufCIntRange osmpbf__string_table__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor osmpbf__string_table__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.StringTable",
    "StringTable",
    "OSMPBF__StringTable",
    "OSMPBF",
    sizeof(OSMPBF__StringTable),
    1,
    osmpbf__string_table__field_descriptors,
    osmpbf__string_table__field_indices_by_name,
    1,  osmpbf__string_table__number_ranges,
    (ProtobufCMessageInit) osmpbf__string_table__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t osmpbf__info__version__default_value = -1;
static const ProtobufCFieldDescriptor osmpbf__info__field_descriptors[5] = {
    {
        "version",
        1,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, has_version),
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, version),
        NULL,
        &osmpbf__info__version__default_value,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "timestamp",
        2,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, has_timestamp),
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, timestamp),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "changeset",
        3,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, has_changeset),
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, changeset),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "uid",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, has_uid),
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, uid),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "user_sid",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, has_user_sid),
        PROTOBUF_C_OFFSETOF(OSMPBF__Info, user_sid),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__info__field_indices_by_name[] = {
    2,   /* field[2] = changeset */
    1,   /* field[1] = timestamp */
    3,   /* field[3] = uid */
    4,   /* field[4] = user_sid */
    0,   /* field[0] = version */
};
static const ProtobufCIntRange osmpbf__info__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__info__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.Info",
    "Info",
    "OSMPBF__Info",
    "OSMPBF",
    sizeof(OSMPBF__Info),
    5,
    osmpbf__info__field_descriptors,
    osmpbf__info__field_indices_by_name,
    1,  osmpbf__info__number_ranges,
    (ProtobufCMessageInit) osmpbf__info__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__dense_info__field_descriptors[5] = {
    {
        "version",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, n_version),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, version),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "timestamp",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, n_timestamp),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, timestamp),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "changeset",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, n_changeset),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, changeset),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "uid",
        4,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, n_uid),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, uid),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "user_sid",
        5,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, n_user_sid),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseInfo, user_sid),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__dense_info__field_indices_by_name[] = {
    2,   /* field[2] = changeset */
    1,   /* field[1] = timestamp */
    3,   /* field[3] = uid */
    4,   /* field[4] = user_sid */
    0,   /* field[0] = version */
};
static const ProtobufCIntRange osmpbf__dense_info__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__dense_info__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.DenseInfo",
    "DenseInfo",
    "OSMPBF__DenseInfo",
    "OSMPBF",
    sizeof(OSMPBF__DenseInfo),
    5,
    osmpbf__dense_info__field_descriptors,
    osmpbf__dense_info__field_indices_by_name,
    1,  osmpbf__dense_info__number_ranges,
    (ProtobufCMessageInit) osmpbf__dense_info__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__change_set__field_descriptors[1] = {
    {
        "id",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_INT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__ChangeSet, id),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__change_set__field_indices_by_name[] = {
    0,   /* field[0] = id */
};
static const ProtobufCIntRange osmpbf__change_set__number_ranges[1 + 1] = {
    { 1, 0 },
    { 0, 1 }
};
const ProtobufCMessageDescriptor osmpbf__change_set__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.ChangeSet",
    "ChangeSet",
    "OSMPBF__ChangeSet",
    "OSMPBF",
    sizeof(OSMPBF__ChangeSet),
    1,
    osmpbf__change_set__field_descriptors,
    osmpbf__change_set__field_indices_by_name,
    1,  osmpbf__change_set__number_ranges,
    (ProtobufCMessageInit) osmpbf__change_set__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__node__field_descriptors[6] = {
    {
        "id",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, id),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "keys",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, n_keys),
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, keys),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "vals",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, n_vals),
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, vals),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "info",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, info),
        &osmpbf__info__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lat",
        8,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, lat),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lon",
        9,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_SINT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Node, lon),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__node__field_indices_by_name[] = {
    0,   /* field[0] = id */
    3,   /* field[3] = info */
    1,   /* field[1] = keys */
    4,   /* field[4] = lat */
    5,   /* field[5] = lon */
    2,   /* field[2] = vals */
};
static const ProtobufCIntRange osmpbf__node__number_ranges[2 + 1] = {
    { 1, 0 },
    { 8, 4 },
    { 0, 6 }
};
const ProtobufCMessageDescriptor osmpbf__node__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.Node",
    "Node",
    "OSMPBF__Node",
    "OSMPBF",
    sizeof(OSMPBF__Node),
    6,
    osmpbf__node__field_descriptors,
    osmpbf__node__field_indices_by_name,
    2,  osmpbf__node__number_ranges,
    (ProtobufCMessageInit) osmpbf__node__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__dense_nodes__field_descriptors[5] = {
    {
        "id",
        1,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, n_id),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, id),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "denseinfo",
        5,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, denseinfo),
        &osmpbf__dense_info__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lat",
        8,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, n_lat),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, lat),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "lon",
        9,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, n_lon),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, lon),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "keys_vals",
        10,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, n_keys_vals),
        PROTOBUF_C_OFFSETOF(OSMPBF__DenseNodes, keys_vals),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__dense_nodes__field_indices_by_name[] = {
    1,   /* field[1] = denseinfo */
    0,   /* field[0] = id */
    4,   /* field[4] = keys_vals */
    2,   /* field[2] = lat */
    3,   /* field[3] = lon */
};
static const ProtobufCIntRange osmpbf__dense_nodes__number_ranges[3 + 1] = {
    { 1, 0 },
    { 5, 1 },
    { 8, 2 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__dense_nodes__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.DenseNodes",
    "DenseNodes",
    "OSMPBF__DenseNodes",
    "OSMPBF",
    sizeof(OSMPBF__DenseNodes),
    5,
    osmpbf__dense_nodes__field_descriptors,
    osmpbf__dense_nodes__field_indices_by_name,
    3,  osmpbf__dense_nodes__number_ranges,
    (ProtobufCMessageInit) osmpbf__dense_nodes__init,
    NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor osmpbf__way__field_descriptors[5] = {
    {
        "id",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_INT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, id),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "keys",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, n_keys),
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, keys),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "vals",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, n_vals),
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, vals),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "info",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, info),
        &osmpbf__info__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "refs",
        8,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, n_refs),
        PROTOBUF_C_OFFSETOF(OSMPBF__Way, refs),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__way__field_indices_by_name[] = {
    0,   /* field[0] = id */
    3,   /* field[3] = info */
    1,   /* field[1] = keys */
    4,   /* field[4] = refs */
    2,   /* field[2] = vals */
};
static const ProtobufCIntRange osmpbf__way__number_ranges[2 + 1] = {
    { 1, 0 },
    { 8, 4 },
    { 0, 5 }
};
const ProtobufCMessageDescriptor osmpbf__way__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.Way",
    "Way",
    "OSMPBF__Way",
    "OSMPBF",
    sizeof(OSMPBF__Way),
    5,
    osmpbf__way__field_descriptors,
    osmpbf__way__field_indices_by_name,
    2,  osmpbf__way__number_ranges,
    (ProtobufCMessageInit) osmpbf__way__init,
    NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue osmpbf__relation__member_type__enum_values_by_number[3] = {
    { "NODE", "OSMPBF__RELATION__MEMBER_TYPE__NODE", 0 },
    { "WAY", "OSMPBF__RELATION__MEMBER_TYPE__WAY", 1 },
    { "RELATION", "OSMPBF__RELATION__MEMBER_TYPE__RELATION", 2 },
};
static const ProtobufCIntRange osmpbf__relation__member_type__value_ranges[] = {
    {0, 0},{0, 3}
};
const ProtobufCEnumValueIndex osmpbf__relation__member_type__enum_values_by_name[3] = {
    { "NODE", 0 },
    { "RELATION", 2 },
    { "WAY", 1 },
};
const ProtobufCEnumDescriptor osmpbf__relation__member_type__descriptor = {
    PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
    "OSMPBF.Relation.MemberType",
    "MemberType",
    "OSMPBF__Relation__MemberType",
    "OSMPBF",
    3,
    osmpbf__relation__member_type__enum_values_by_number,
    3,
    osmpbf__relation__member_type__enum_values_by_name,
    1,
    osmpbf__relation__member_type__value_ranges,
    NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor osmpbf__relation__field_descriptors[7] = {
    {
        "id",
        1,
        PROTOBUF_C_LABEL_REQUIRED,
        PROTOBUF_C_TYPE_INT64,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, id),
        NULL,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "keys",
        2,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, n_keys),
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, keys),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "vals",
        3,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_UINT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, n_vals),
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, vals),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "info",
        4,
        PROTOBUF_C_LABEL_OPTIONAL,
        PROTOBUF_C_TYPE_MESSAGE,
        0,   /* quantifier_offset */
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, info),
        &osmpbf__info__descriptor,
        NULL,
        0,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "roles_sid",
        8,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_INT32,
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, n_roles_sid),
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, roles_sid),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "memids",
        9,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_SINT64,
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, n_memids),
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, memids),
        NULL,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
    {
        "types",
        10,
        PROTOBUF_C_LABEL_REPEATED,
        PROTOBUF_C_TYPE_ENUM,
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, n_types),
        PROTOBUF_C_OFFSETOF(OSMPBF__Relation, types),
        &osmpbf__relation__member_type__descriptor,
        NULL,
        1,            /* packed */
        0,NULL,NULL    /* reserved1,reserved2, etc */
    },
};
static const unsigned osmpbf__relation__field_indices_by_name[] = {
    0,   /* field[0] = id */
    3,   /* field[3] = info */
    1,   /* field[1] = keys */
    5,   /* field[5] = memids */
    4,   /* field[4] = roles_sid */
    6,   /* field[6] = types */
    2,   /* field[2] = vals */
};
static const ProtobufCIntRange osmpbf__relation__number_ranges[2 + 1] = {
    { 1, 0 },
    { 8, 4 },
    { 0, 7 }
};
const ProtobufCMessageDescriptor osmpbf__relation__descriptor = {
    PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
    "OSMPBF.Relation",
    "Relation",
    "OSMPBF__Relation",
    "OSMPBF",
    sizeof(OSMPBF__Relation),
    7,
    osmpbf__relation__field_descriptors,
    osmpbf__relation__field_indices_by_name,
    2,  osmpbf__relation__number_ranges,
    (ProtobufCMessageInit) osmpbf__relation__init,
    NULL,NULL,NULL    /* reserved[123] */
};
