navit: support/libc/abort.c File Reference
abort.c File Reference
#include <windows.h>
Functions
void abort (void)
Function Documentation
void abort (void)
Referenced by _nl_load_domain(), debug_assert_fail(), fh_checkcons(), fh_deleteel(), fh_replacekeydata(), g_slice_free1(), g_slice_free_chain_with_offset(), get_sysdep_segment_value(), mem_error(), navigation_analyze_roundabout(), protobuf_c_out_of_memory_default(), repeated_field_pack_to_buffer(), VASNPRINTF(), and write_item().