navit: support/win32/addwinsock.h File Reference
addwinsock.h File Reference
#include <winsock2.h>
Functions
int inet_aton (const char *cp, struct in_addr *inp)
Function Documentation
int inet_aton (const char * cp, struct in_addr * inp)
Referenced by debug_new(), set_attr_do(), and vehicle_file_open().