navit: atom.c File Reference
atom.c File Reference
#include <glib.h>
#include "atom.h"
Functions
char * atom_lookup (char *name)
char * atom (char *name)
void atom_init (void)
Variables
static GHashTable * atom_hash
Function Documentation
char* atom (char * name)
References atom_hash, atom_lookup(), g_hash_table_insert(), g_strdup(), and NULL.
Referenced by file_create(), and font_freetype_font_new().
void atom_init (void)
References atom_hash, g_hash_table_new(), g_str_equal(), and g_str_hash().
Referenced by main_real().
char* atom_lookup (char * name)
References atom_hash, g_hash_table_lookup(), and NULL.
Referenced by atom().
Variable Documentation
GHashTable* atom_hash static
Referenced by atom(), atom_init(), and atom_lookup().