navit: atom.h File Reference
atom.h File Reference
Functions
char * atom_lookup (char *name)
char * atom (char *name)
void atom_init (void)
Function Documentation
atom()
char* atom (char * name)
References atom_hash, and atom_lookup().
Referenced by file_create(), and font_freetype_font_new().
atom_init()
void atom_init (void)
References atom_hash.
Referenced by main_real().
atom_lookup()
char* atom_lookup (char * name)
References atom_hash.
Referenced by atom().