navit: binding/python/navigation.c File Reference
navigation.c File Reference
#include "common.h"
#include "navigation.h"
Data Structures
struct navigationObject
Functions
static PyObject * navigation_get_map_py (navigationObject *self, PyObject *args)
static PyObject * navigation_getattr_py (PyObject *self, char *name)
static void navigation_destroy_py (navigationObject *self)
PyObject * navigation_py (PyObject *self, PyObject *args)
PyObject * navigation_py_ref (struct navigation *navigation)
Variables
static PyMethodDef navigation_methods []
PyTypeObject navigation_Type
Function Documentation
navigation_destroy_py()
static void navigation_destroy_py (navigationObject * self) static
navigation_get_map_py()
static PyObject* navigation_get_map_py (navigationObject * self, PyObject * args) static
References map_py_ref(), and navigation_get_map().
navigation_getattr_py()
static PyObject* navigation_getattr_py (PyObject * self, char * name) static
References name, and navigation_methods.
navigation_py()
PyObject* navigation_py (PyObject * self, PyObject * args)
References navigation_Type.
navigation_py_ref()
PyObject* navigation_py_ref (struct navigation * navigation)
References navigationObject::navigation, and navigation_Type.
Referenced by python_object_from_attr().
Variable Documentation
navigation_methods
PyMethodDef navigation_methods[] static
Initial value:
= {
    {"get_map", (PyCFunction) navigation_get_map_py, METH_VARARGS },
    {NULL, NULL },
}
Referenced by navigation_getattr_py().
navigation_Type
PyTypeObject navigation_Type
Initial value:
= {
    Obj_HEAD
    .tp_name="navigation",
    .tp_basicsize=sizeof(navigationObject),
    .tp_dealloc=(destructor)navigation_destroy_py,
    .tp_getattr=navigation_getattr_py,
}
Referenced by navigation_py(), and navigation_py_ref().