navit: support/gettext_intl/bindtextdom.c File Reference
bindtextdom.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include "libgnuintl.h"
#include "gettextP.h"
Macros
#define __libc_rwlock_define(CLASS, NAME)
#define __libc_rwlock_wrlock(NAME)
#define __libc_rwlock_unlock(NAME)
#define _nl_default_dirname libintl_nl_default_dirname
#define _nl_domain_bindings libintl_nl_domain_bindings
#define offsetof(type, ident) ((size_t)&(((type*)0)->ident))
#define INTUSE(name) name
#define BINDTEXTDOMAIN libintl_bindtextdomain
#define BIND_TEXTDOMAIN_CODESET libintl_bind_textdomain_codeset
Functions
__libc_rwlock_define (extern, _nl_state_lock attribute_hidden) static void set_binding_values(const char *domainname
if (domainname==NULL||domainname[0]== '\0')
__libc_rwlock_wrlock (_nl_state_lock)
for (binding=_nl_domain_bindings;binding!=NULL;binding=binding->next)
if (binding!=NULL)
else if ((dirnamep==NULL||*dirnamep==NULL)&&(codesetp==NULL||*codesetp==NULL))
if (__builtin_expect(new_binding==NULL, 0))
if (codesetp)
if (_nl_domain_bindings==NULL||strcmp(domainname, _nl_domain_bindings->domainname)< 0)
while (binding->next!=NULL &&strcmp(domainname, binding->next->domainname), 0)
if (modified)
char * BIND_TEXTDOMAIN_CODESET (const char *domainname, const char *codeset)
Variables
const char _nl_default_dirname []
struct binding * _nl_domain_bindings
const char ** dirnamep
const char const char
**codesetp struct binding * binding
int modified = 0
else
struct binding * new_binding
else new_binding dirname = (char *) INTUSE(_nl_default_dirname)
new_binding codeset_cntr = 0
else new_binding codeset = NULL
Macro Definition Documentation
#define __libc_rwlock_define (CLASS, NAME)
#define __libc_rwlock_unlock (NAME)
#define __libc_rwlock_wrlock (NAME)
#define _nl_default_dirname libintl_nl_default_dirname
Referenced by if().
#define _nl_domain_bindings libintl_nl_domain_bindings
Referenced by if().
#define BIND_TEXTDOMAIN_CODESET libintl_bind_textdomain_codeset
#define BINDTEXTDOMAIN libintl_bindtextdomain
#define INTUSE (name) name
Referenced by if().
#define offsetof (type, ident) ((size_t)&(((type*)0)->ident))
Function Documentation
__libc_rwlock_define (extern , _nl_state_lock attribute_hidden) const
__libc_rwlock_wrlock (_nl_state_lock)
char* BIND_TEXTDOMAIN_CODESET (const char * domainname, const char * codeset)
References codeset, and NULL.
for (binding = _nl_domain_bindings; binding != NULL; binding = binding->next)
References binding::domainname, and NULL.
Referenced by callback_call(), ezxml_attr(), ezxml_toxml(), inflateBack(), node_buffer_to_hash(), and png_init_read_transformations().
if (domainname = = NULL || domainname[0] == '\0')
References NULL.
Referenced by _nl_find_msg(), bookmarks_copy_bookmark(), bookmarks_delete_bookmark(), bookmarks_get_bookmark_count(), bookmarks_move_down(), bookmarks_rename_bookmark(), garmin_img_coord_get(), get_int_bool(), get_string(), graphics_qt5_fullscreen(), graphics_sdl_idle(), gui_internal_button_attr_update(), gui_internal_keyboard_hide_native(), gui_internal_table_hide_rows(), gui_internal_table_render(), gui_internal_widget_table_new(), icon_new(), inflate(), inflateEnd(), inflateGetHeader(), inflatePrime(), inflateSetDictionary(), inflateSync(), layer_set_attr_do(), map_rect_get_item_byid_mg(), navigation_update_idle(), navit_set_layout_by_name(), osd_auxmap_draw(), osd_compass_draw(), osd_gps_status_draw(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_odometer_draw(), osd_scale_draw(), osd_speed_cam_draw(), osd_text_draw(), osd_volume_click(), png_build_gamma_table(), png_get_cHRM(), png_handle_sBIT(), png_read_finish_row(), png_read_row(), qt5_espeak_SynthCallback(), raster_PutPixelAlpha(), route_path_add_item_from_graph(), shm_next(), statusbar_route_update(), updatewindow(), and vehicleprofile_update().
if (binding! = NULL)
References __builtin_expect, _nl_default_dirname, binding::codeset, codeset, binding::codeset_cntr, binding::dirname, dirname, dirnamep, INTUSE, and NULL.
else if ((dirnamep==NULL||*dirnamep==NULL)&&(codesetp==NULL||*codesetp==NULL))
References _nl_default_dirname, INTUSE, and NULL.
if (__builtin_expect(new_binding==NULL, 0))
if (codesetp)
References __builtin_expect, binding::codeset, codeset, binding::codeset_cntr, and NULL.
if ()
References _nl_domain_bindings, new_binding, and binding::next.
if (modified)
while (binding->next! = NULL && strcmp (domainname, binding->next->domainname), 0)
Referenced by ezxml_child(), ezxml_pi(), osd_text_draw(), and png_decompress_chunk().
Variable Documentation
const char _nl_default_dirname[]
struct binding* _nl_domain_bindings
const char const char** codesetp struct binding* binding
Referenced by DCIGETTEXT().
else new_binding codeset = NULL
Referenced by _nl_find_domain(), _nl_make_l10nflist(), BIND_TEXTDOMAIN_CODESET(), if(), and locale_charset().
new_binding codeset_cntr = 0
else new_binding dirname = (char *) INTUSE(_nl_default_dirname)
Referenced by DCIGETTEXT(), file_create_caseinsensitive(), and if().
const char** dirnamep
Referenced by if().
else
Initial value:
{
      size_t len = strlen (domainname) + 1
modified = 0
Referenced by SmoothSpect().
struct binding* new_binding
Initial value:
=
        (struct binding *) malloc (offsetof (struct binding, domainname) + len)
Referenced by if().