navit: binding/python/route.c File Reference
route.c File Reference
#include "common.h"
#include "item.h"
#include "coord.h"
#include "route.h"
Data Structures
struct routeObject
Functions
static PyObject * route_get_map_py (routeObject *self, PyObject *args)
static PyObject * route_getattr_py (PyObject *self, char *name)
static void route_destroy_py (routeObject *self)
PyObject * route_py (PyObject *self, PyObject *args)
PyObject * route_py_ref (struct route *route)
Variables
static PyMethodDef route_methods []
PyTypeObject route_Type
Function Documentation
route_destroy_py()
static void route_destroy_py (routeObject * self) static
route_get_map_py()
static PyObject* route_get_map_py (routeObject * self, PyObject * args) static
References map_py_ref(), and route_get_map().
route_getattr_py()
static PyObject* route_getattr_py (PyObject * self, char * name) static
References route_methods.
route_py()
PyObject* route_py (PyObject * self, PyObject * args)
References route_Type.
route_py_ref()
PyObject* route_py_ref (struct route * route)
References routeObject::route, and route_Type.
Referenced by python_object_from_attr().
Variable Documentation
route_methods
PyMethodDef route_methods[] static
Initial value:
= {
    {"get_map", (PyCFunction) route_get_map_py, METH_VARARGS },
    {NULL, NULL },
}
Referenced by route_getattr_py().
route_Type
PyTypeObject route_Type
Initial value:
= {
    Obj_HEAD
    .tp_name="route",
    .tp_basicsize=sizeof(routeObject),
    .tp_dealloc=(destructor)route_destroy_py,
    .tp_getattr=route_getattr_py,
}
Referenced by route_py(), and route_py_ref().