navit: binding/dbus/binding_dbus.c File Reference
binding_dbus.c File Reference
#include <string.h>
#include <dbus/dbus.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include "config.h"
#include "config_.h"
#include "navit.h"
#include "coord.h"
#include "point.h"
#include "plugin.h"
#include "debug.h"
#include "item.h"
#include "xmlconfig.h"
#include "attr.h"
#include "layout.h"
#include "navigation.h"
#include "command.h"
#include "callback.h"
#include "graphics.h"
Data Structures
struct dbus_callback
struct dbus_method
Macros
#define DBUS_API_SUBJECT_TO_CHANGE
Functions
static char * object_new (char *type, void *object)
static void * object_get (const char *path)
static void object_destroy (const char *path, void *object)
static void * resolve_object (const char *opath, char *type)
static void * object_get_from_message_arg (DBusMessageIter *iter, char *type)
static void * object_get_from_message (DBusMessage *message, char *type)
static enum attr_type attr_type_get_from_message (DBusMessageIter *iter)
static void encode_variant_string (DBusMessageIter *iter, char *str)
static void encode_dict_string_variant_string (DBusMessageIter *iter, char *key, char *value)
static int encode_attr (DBusMessageIter *iter1, struct attr *attr)
static DBusHandlerResult empty_reply (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error (DBusConnection *connection, DBusMessage *message, char *error, char *msg)
static DBusHandlerResult dbus_error_invalid_attr_type (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_invalid_parameter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_invalid_object_path (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_invalid_object_path_parameter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_navigation_not_configured (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_traffic_not_configured (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult dbus_error_no_data_available (DBusConnection *connection, DBusMessage *message)
static void dbus_dump_iter (char *prefix, DBusMessageIter *iter)
static void dbus_dump (DBusMessage *message)
static int pcoord_get_from_message (DBusMessage *message, DBusMessageIter *iter, struct pcoord *pc)
static void pcoord_encode (DBusMessageIter *iter, struct pcoord *pc)
static enum attr_type decode_attr_type_from_iter (DBusMessageIter *iter)
static int decode_attr_from_iter (DBusMessageIter *iter, struct attr *attr)
static int decode_attr (DBusMessage *message, struct attr *attr)
static void destroy_attr (struct attr *attr)
static char * get_iter_name (char *type)
static DBusHandlerResult request_attr_iter (DBusConnection *connection, DBusMessage *message, char *type, struct attr_iter *(*func)(void))
static DBusHandlerResult request_attr_iter_destroy (DBusConnection *connection, DBusMessage *message, char *type, void(*func)(struct attr_iter *))
static DBusHandlerResult request_destroy (DBusConnection *connection, DBusMessage *message, char *type, void *data, void(*func)(void *))
static DBusHandlerResult request_dup (DBusConnection *connection, DBusMessage *message, char *type, void *data, void *(*func)(void *))
static DBusHandlerResult request_get_attr (DBusConnection *connection, DBusMessage *message, char *type, void *data, int(*func)(void *data, enum attr_type type, struct attr *attr, struct attr_iter *iter))
static DBusHandlerResult request_command (DBusConnection *connection, DBusMessage *message, char *type, void *data, int(*func)(void *data, enum attr_type type, struct attr *attr, struct attr_iter *iter))
static DBusHandlerResult request_set_add_remove_attr (DBusConnection *connection, DBusMessage *message, char *type, void *data, int(*func)(void *data, struct attr *attr))
static void dbus_callback_emit_signal (struct dbus_callback *dbus_callback)
static void request_callback_destroy_do (struct dbus_callback *data)
static DBusHandlerResult request_callback_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_callback_new (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_config_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_config_attr_iter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_config_attr_iter_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_graphics_get_data (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_gui_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_gui_command (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_graphics_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_layout_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_map_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_map_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_map_dump (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_mapset_attr_iter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_mapset_attr_iter_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_mapset_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navigation_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_osd_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_osd_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_roadprofile_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_roadprofile_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_roadprofile_attr_iter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_roadprofile_attr_iter_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_add_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_remove_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_route_dup (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_draw (DBusConnection *connection, DBusMessage *message)
static int point_get_from_message (DBusMessage *message, DBusMessageIter *iter, struct point *p)
static DBusHandlerResult request_navit_add_message (DBusConnection *connection, DBusMessage *message)
Shows up a message.
static DBusHandlerResult request_navit_set_center (DBusConnection *connection, DBusMessage *message)
Centers the screen on a specified position pc on the world.
static DBusHandlerResult request_navit_set_center_screen (DBusConnection *connection, DBusMessage *message)
Centers the screen on a specified position p shown on the screen.
static DBusHandlerResult request_navit_set_layout (DBusConnection *connection, DBusMessage *message)
Sets the layout to new_layout_name extracted from message.
static DBusHandlerResult request_navit_quit (DBusConnection *connection, DBusMessage *message)
Gracefully exit Navit by registering a one-second callback to allow clean shutdown of the dbus connection.
static DBusHandlerResult request_navit_traffic_export_gpx (DBusConnection *connection, DBusMessage *message)
Exports currently active traffic distortions as a GPX file.
static DBusHandlerResult request_navit_traffic_inject (DBusConnection *connection, DBusMessage *message)
Injects a traffic feed.
static DBusHandlerResult request_navit_zoom (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_zoom_to_route (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_route_export_gpx (DBusConnection *connection, DBusMessage *message)
Exports the current route as a GPX file.
static DBusHandlerResult request_navit_route_export_geojson (DBusConnection *connection, DBusMessage *message)
Exports the current route as a GeoJSON file.
static DBusHandlerResult request_navit_block (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_resize (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_attr_iter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_attr_iter_destroy (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_add_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_remove_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_set_position (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_set_destination (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_clear_destination (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_navit_evaluate (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_search_list_destroy (DBusConnection *connection, DBusMessage *message)
static void request_search_list_common (struct search_list_common *slc, DBusMessageIter *iter4)
static DBusHandlerResult request_search_list_get_result (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_search_list_new (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_search_list_search (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_search_list_select (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_tracking_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_vehicle_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_vehicleprofile_get_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_vehicleprofile_set_attr (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_vehicleprofile_attr_iter (DBusConnection *connection, DBusMessage *message)
static DBusHandlerResult request_vehicleprofile_attr_iter_destroy (DBusConnection *connection, DBusMessage *message)
static char * introspect_path (const char *object)
static char * generate_navitintrospectxml (const char *object)
static DBusHandlerResult navit_handler_func (DBusConnection *connection, DBusMessage *message, void *user_data)
DBusHandlerResult filter (DBusConnection *connection, DBusMessage *message, void *user_data)
static int dbus_cmd_send_signal (struct navit *navit, char *command, struct attr **in, struct attr ***out)
static void dbus_main_navit (struct navit *navit, int added)
void plugin_init (void)
Variables
static DBusConnection * connection
static dbus_uint32_t dbus_serial
static char * service_name = "org.navit_project.navit"
static char * object_path = "/org/navit_project/navit"
char * navitintrospectxml_head1
char * navitintrospectxml_head2
GHashTable * object_hash
GHashTable * object_hash_rev
GHashTable * object_count
struct dbus_method dbus_methods []
static DBusObjectPathVTable dbus_navit_vtable
static struct command_table commands []
Macro Definition Documentation
DBUS_API_SUBJECT_TO_CHANGE
#define DBUS_API_SUBJECT_TO_CHANGE
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
attr_type_get_from_message()
static enum attr_type attr_type_get_from_message (DBusMessageIter * iter) static
References attr_from_name().
Referenced by request_callback_new(), and request_get_attr().
dbus_callback_emit_signal()
static void dbus_callback_emit_signal (struct dbus_callback * dbus_callback) static
References dbus_serial, object_path, service_name, and dbus_callback::signal.
Referenced by request_callback_new().
dbus_cmd_send_signal()
static int dbus_cmd_send_signal (struct navit * navit, char * command, struct attr ** in, struct attr *** out) static
References dbg, dbus_serial, encode_attr(), lvl_debug, object_new(), and service_name.
dbus_dump()
static void dbus_dump (DBusMessage * message) static
References dbus_dump_iter().
dbus_dump_iter()
static void dbus_dump_iter (char * prefix, DBusMessageIter * iter) static
References dbg, and lvl_debug.
Referenced by dbus_dump().
dbus_error()
static DBusHandlerResult dbus_error (DBusConnection * connection, DBusMessage * message, char * error, char * msg) static
Referenced by dbus_error_invalid_attr_type(), dbus_error_invalid_object_path(), dbus_error_invalid_object_path_parameter(), dbus_error_invalid_parameter(), dbus_error_navigation_not_configured(), dbus_error_no_data_available(), dbus_error_traffic_not_configured(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), and request_navit_traffic_export_gpx().
dbus_error_invalid_attr_type()
static DBusHandlerResult dbus_error_invalid_attr_type (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_get_attr().
dbus_error_invalid_object_path()
static DBusHandlerResult dbus_error_invalid_object_path (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_command(), request_destroy(), request_dup(), request_get_attr(), request_graphics_get_data(), request_map_dump(), request_navit_add_message(), request_navit_block(), request_navit_clear_destination(), request_navit_draw(), request_navit_evaluate(), request_navit_quit(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_traffic_export_gpx(), request_navit_traffic_inject(), request_navit_zoom(), request_navit_zoom_to_route(), request_search_list_get_result(), request_search_list_search(), request_search_list_select(), request_set_add_remove_attr(), and request_vehicle_set_attr().
dbus_error_invalid_object_path_parameter()
static DBusHandlerResult dbus_error_invalid_object_path_parameter (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_attr_iter_destroy(), request_navit_attr_iter_destroy(), and request_search_list_new().
dbus_error_invalid_parameter()
static DBusHandlerResult dbus_error_invalid_parameter (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_callback_new(), request_command(), request_graphics_get_data(), request_map_dump(), request_navit_evaluate(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_zoom(), request_search_list_search(), request_search_list_select(), request_set_add_remove_attr(), and request_vehicle_set_attr().
dbus_error_navigation_not_configured()
static DBusHandlerResult dbus_error_navigation_not_configured (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_navit_route_export_geojson(), and request_navit_route_export_gpx().
dbus_error_no_data_available()
static DBusHandlerResult dbus_error_no_data_available (DBusConnection * connection, DBusMessage * message) static
References dbus_error(), and empty_reply().
Referenced by request_get_attr(), request_graphics_get_data(), and request_search_list_get_result().
dbus_error_traffic_not_configured()
static DBusHandlerResult dbus_error_traffic_not_configured (DBusConnection * connection, DBusMessage * message) static
References dbus_error().
Referenced by request_navit_traffic_export_gpx(), and request_navit_traffic_inject().
dbus_main_navit()
static void dbus_main_navit (struct navit * navit, int added) static
References command_add_table_attr(), dbus_serial, navit_add_attr(), object_new(), and service_name.
Referenced by plugin_init().
decode_attr()
static int decode_attr (DBusMessage * message, struct attr * attr) static
References decode_attr_from_iter().
Referenced by request_set_add_remove_attr(), and request_vehicle_set_attr().
decode_attr_from_iter()
static int decode_attr_from_iter (DBusMessageIter * iter, struct attr * attr) static
References dbus_callback::callback, attr::callback, attr::coord_geo, attr::data, dbg, decode_attr_type_from_iter(), coord_geo::lat, coord_geo::lng, lvl_debug, attr::num, attr::numd, object_get(), object_get_from_message_arg(), attr::pcoord, pcoord::pro, attr::str, attr::type, attr::u, pcoord::x, and pcoord::y.
Referenced by decode_attr(), and request_search_list_search().
decode_attr_type_from_iter()
static enum attr_type decode_attr_type_from_iter (DBusMessageIter * iter) static
References attr_from_name(), dbg, and lvl_debug.
Referenced by decode_attr_from_iter(), and request_search_list_select().
destroy_attr()
static void destroy_attr (struct attr * attr) static
References attr::numd, attr::type, and attr::u.
Referenced by request_set_add_remove_attr(), and request_vehicle_set_attr().
empty_reply()
static DBusHandlerResult empty_reply (DBusConnection * connection, DBusMessage * message) static
Referenced by dbus_error_no_data_available(), request_attr_iter_destroy(), request_command(), request_destroy(), request_map_dump(), request_navit_add_message(), request_navit_attr_iter_destroy(), request_navit_block(), request_navit_clear_destination(), request_navit_draw(), request_navit_quit(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_traffic_export_gpx(), request_navit_traffic_inject(), request_navit_zoom(), request_navit_zoom_to_route(), request_search_list_search(), request_search_list_select(), request_set_add_remove_attr(), and request_vehicle_set_attr().
encode_attr()
static int encode_attr (DBusMessageIter * iter1, struct attr * attr) static
References attr_to_name(), attr_to_text(), attr::data, encode_variant_string(), item_to_name(), attr::item_type, name, attr::num, object_new(), attr::pcoord, pcoord::pro, attr::str, attr::type, attr::u, pcoord::x, and pcoord::y.
Referenced by dbus_cmd_send_signal(), and request_get_attr().
encode_dict_string_variant_string()
static void encode_dict_string_variant_string (DBusMessageIter * iter, char * key, char * value) static
References encode_variant_string().
Referenced by request_search_list_common(), and request_search_list_get_result().
encode_variant_string()
static void encode_variant_string (DBusMessageIter * iter, char * str) static
Referenced by encode_attr(), and encode_dict_string_variant_string().
filter()
DBusHandlerResult filter (DBusConnection * connection, DBusMessage * message, void * user_data)
References dbg, and lvl_debug.
generate_navitintrospectxml()
static char* generate_navitintrospectxml (const char * object) static
References dbg, dbus_methods, g_strconcat_printf(), introspect_path(), lvl_debug, navitintrospectxml_head1, navitintrospectxml_head2, service_name, and signature.
Referenced by navit_handler_func().
get_iter_name()
static char* get_iter_name (char * type) static
Referenced by request_attr_iter(), request_attr_iter_destroy(), and request_get_attr().
introspect_path()
static char* introspect_path (const char * object) static
References dbg, lvl_debug, and object_path.
Referenced by generate_navitintrospectxml().
navit_handler_func()
static DBusHandlerResult navit_handler_func (DBusConnection * connection, DBusMessage * message, void * user_data) static
References dbg, dbus_methods, dbus_method::func, generate_navitintrospectxml(), lvl_debug, service_name, and signature.
object_destroy()
static void object_destroy (const char * path, void * object) static
References object_hash, and object_hash_rev.
Referenced by request_attr_iter_destroy(), and request_destroy().
object_get()
static void* object_get (const char * path) static
References object_hash.
Referenced by decode_attr_from_iter(), and resolve_object().
object_get_from_message()
static void* object_get_from_message (DBusMessage * message, char * type) static
References resolve_object().
Referenced by request_command(), request_destroy(), request_dup(), request_get_attr(), request_graphics_get_data(), request_map_dump(), request_navit_add_message(), request_navit_block(), request_navit_clear_destination(), request_navit_draw(), request_navit_evaluate(), request_navit_quit(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_traffic_export_gpx(), request_navit_traffic_inject(), request_navit_zoom(), request_navit_zoom_to_route(), request_search_list_get_result(), request_search_list_search(), request_search_list_select(), request_set_add_remove_attr(), and request_vehicle_set_attr().
object_get_from_message_arg()
static void* object_get_from_message_arg (DBusMessageIter * iter, char * type) static
References resolve_object().
Referenced by decode_attr_from_iter(), request_attr_iter_destroy(), request_get_attr(), request_navit_attr_iter_destroy(), and request_search_list_new().
object_new()
static char* object_new (char * type, void * object) static
References dbg, lvl_debug, object_count, object_hash, object_hash_rev, and object_path.
Referenced by dbus_cmd_send_signal(), dbus_main_navit(), encode_attr(), request_attr_iter(), request_callback_new(), request_dup(), request_navit_attr_iter(), and request_search_list_new().
pcoord_encode()
static void pcoord_encode (DBusMessageIter * iter, struct pcoord * pc) static
References pcoord::pro, pcoord::x, and pcoord::y.
Referenced by request_search_list_get_result().
pcoord_get_from_message()
static int pcoord_get_from_message (DBusMessage * message, DBusMessageIter * iter, struct pcoord * pc) static
Extracts a struct pcoord from a DBus message
Parameters
message The DBus message
iter Sort of pointer that points on that (iii)-object in the message
pc Pointer where the data should get stored
Returns
Returns 1 when everything went right, otherwise 0
References pcoord_parse(), pcoord::pro, projection_mg, pcoord::x, and pcoord::y.
Referenced by request_navit_set_center(), request_navit_set_destination(), and request_navit_set_position().
plugin_init()
void plugin_init (void)
References attr::callback, callback_cast, callback_new_attr_0, config_add_attr(), dbg, dbus_main_navit(), lvl_debug, lvl_error, object_count, object_hash, object_hash_rev, object_path, service_name, attr::type, and attr::u.
point_get_from_message()
static int point_get_from_message (DBusMessage * message, DBusMessageIter * iter, struct point * p) static
Extracts a struct point from a DBus message
Parameters
message The DBus message
iter Sort of pointer that points on that (ii)-object in the message
p Pointer where the data should get stored
Returns
Returns 1 when everything went right, otherwise 0
References dbg, lvl_debug, point::x, and point::y.
Referenced by request_navit_route_export_geojson(), request_navit_set_center_screen(), and request_navit_zoom().
request_attr_iter()
static DBusHandlerResult request_attr_iter (DBusConnection * connection, DBusMessage * message, char * type, struct attr_iter *(*)(void) func) static
References get_iter_name(), and object_new().
Referenced by request_config_attr_iter(), request_mapset_attr_iter(), request_roadprofile_attr_iter(), and request_vehicleprofile_attr_iter().
request_attr_iter_destroy()
static DBusHandlerResult request_attr_iter_destroy (DBusConnection * connection, DBusMessage * message, char * type, void(*)(struct attr_iter *) func) static
References dbus_error_invalid_object_path_parameter(), empty_reply(), get_iter_name(), attr_iter::iter, object_destroy(), and object_get_from_message_arg().
Referenced by request_config_attr_iter_destroy(), request_mapset_attr_iter_destroy(), request_roadprofile_attr_iter_destroy(), and request_vehicleprofile_attr_iter_destroy().
request_callback_destroy()
static DBusHandlerResult request_callback_destroy (DBusConnection * connection, DBusMessage * message) static
References request_callback_destroy_do(), and request_destroy().
request_callback_destroy_do()
static void request_callback_destroy_do (struct dbus_callback * data) static
References dbus_callback::callback, callback_destroy(), and dbus_callback::signal.
Referenced by request_callback_destroy().
request_callback_new()
static DBusHandlerResult request_callback_new (DBusConnection * connection, DBusMessage * message) static
References attr_type_get_from_message(), dbus_callback::callback, callback_cast, callback_new_1, callback_new_attr_1, dbus_callback_emit_signal(), dbus_error_invalid_parameter(), object_new(), dbus_callback::signal, and type.
request_command()
static DBusHandlerResult request_command (DBusConnection * connection, DBusMessage * message, char * type, void * data, int(*)(void *data, enum attr_type type, struct attr *attr, struct attr_iter *iter) func) static
References attr::callback_list, callback_list_call_attr_4, command(), dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), attr_iter::iter, object_get_from_message(), and attr::u.
Referenced by request_gui_command().
request_config_attr_iter()
static DBusHandlerResult request_config_attr_iter (DBusConnection * connection, DBusMessage * message) static
References config_attr_iter_new(), and request_attr_iter().
request_config_attr_iter_destroy()
static DBusHandlerResult request_config_attr_iter_destroy (DBusConnection * connection, DBusMessage * message) static
References config_attr_iter_destroy(), and request_attr_iter_destroy().
request_config_get_attr()
static DBusHandlerResult request_config_get_attr (DBusConnection * connection, DBusMessage * message) static
References config_get_attr(), and request_get_attr().
request_destroy()
static DBusHandlerResult request_destroy (DBusConnection * connection, DBusMessage * message, char * type, void * data, void(*)(void *) func) static
References dbus_error_invalid_object_path(), empty_reply(), object_destroy(), and object_get_from_message().
Referenced by request_callback_destroy(), request_route_destroy(), and request_search_list_destroy().
request_dup()
static DBusHandlerResult request_dup (DBusConnection * connection, DBusMessage * message, char * type, void * data, void *(*)(void *) func) static
References dbus_error_invalid_object_path(), object_get_from_message(), and object_new().
Referenced by request_route_dup().
request_get_attr()
static DBusHandlerResult request_get_attr (DBusConnection * connection, DBusMessage * message, char * type, void * data, int(*)(void *data, enum attr_type type, struct attr *attr, struct attr_iter *iter) func) static
References attr_type_get_from_message(), dbus_error_invalid_attr_type(), dbus_error_invalid_object_path(), dbus_error_no_data_available(), encode_attr(), get_iter_name(), attr_iter::iter, object_get_from_message(), and object_get_from_message_arg().
Referenced by request_config_get_attr(), request_gui_get_attr(), request_layout_get_attr(), request_map_get_attr(), request_mapset_get_attr(), request_navigation_get_attr(), request_navit_get_attr(), request_osd_get_attr(), request_roadprofile_get_attr(), request_route_get_attr(), request_tracking_get_attr(), and request_vehicleprofile_get_attr().
request_graphics_get_data()
static DBusHandlerResult request_graphics_get_data (DBusConnection * connection, DBusMessage * message) static
References graphics_data_image::data, data, dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), dbus_error_no_data_available(), graphics_get_data(), object_get_from_message(), and graphics_data_image::size.
request_graphics_set_attr()
static DBusHandlerResult request_graphics_set_attr (DBusConnection * connection, DBusMessage * message) static
References graphics_set_attr(), and request_set_add_remove_attr().
request_gui_command()
static DBusHandlerResult request_gui_command (DBusConnection * connection, DBusMessage * message) static
References gui_get_attr(), and request_command().
request_gui_get_attr()
static DBusHandlerResult request_gui_get_attr (DBusConnection * connection, DBusMessage * message) static
References gui_get_attr(), and request_get_attr().
request_layout_get_attr()
static DBusHandlerResult request_layout_get_attr (DBusConnection * connection, DBusMessage * message) static
References layout_get_attr(), and request_get_attr().
request_map_dump()
static DBusHandlerResult request_map_dump (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), file, map_dump_filedesc(), and object_get_from_message().
request_map_get_attr()
static DBusHandlerResult request_map_get_attr (DBusConnection * connection, DBusMessage * message) static
References map_get_attr(), and request_get_attr().
request_map_set_attr()
static DBusHandlerResult request_map_set_attr (DBusConnection * connection, DBusMessage * message) static
References map_set_attr(), and request_set_add_remove_attr().
request_mapset_attr_iter()
static DBusHandlerResult request_mapset_attr_iter (DBusConnection * connection, DBusMessage * message) static
References mapset_attr_iter_new(), and request_attr_iter().
request_mapset_attr_iter_destroy()
static DBusHandlerResult request_mapset_attr_iter_destroy (DBusConnection * connection, DBusMessage * message) static
References mapset_attr_iter_destroy(), and request_attr_iter_destroy().
request_mapset_get_attr()
static DBusHandlerResult request_mapset_get_attr (DBusConnection * connection, DBusMessage * message) static
References mapset_get_attr(), and request_get_attr().
request_navigation_get_attr()
static DBusHandlerResult request_navigation_get_attr (DBusConnection * connection, DBusMessage * message) static
References navigation_get_attr(), and request_get_attr().
request_navit_add_attr()
static DBusHandlerResult request_navit_add_attr (DBusConnection * connection, DBusMessage * message) static
References navit_add_attr(), and request_set_add_remove_attr().
request_navit_add_message()
static DBusHandlerResult request_navit_add_message (DBusConnection * connection, DBusMessage * message) static
Shows up a message.
Parameters
connection The DBusConnection object through which message arrived
message The DBusMessage containing the coordinates
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbus_error_invalid_object_path(), empty_reply(), eval::navit, navit_add_message(), and object_get_from_message().
request_navit_attr_iter()
static DBusHandlerResult request_navit_attr_iter (DBusConnection * connection, DBusMessage * message) static
References navit_attr_iter_new(), and object_new().
request_navit_attr_iter_destroy()
static DBusHandlerResult request_navit_attr_iter_destroy (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path_parameter(), empty_reply(), attr_iter::iter, navit_attr_iter_destroy(), and object_get_from_message_arg().
request_navit_block()
static DBusHandlerResult request_navit_block (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), empty_reply(), eval::navit, navit_block(), and object_get_from_message().
request_navit_clear_destination()
static DBusHandlerResult request_navit_clear_destination (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), empty_reply(), eval::navit, navit_set_destination(), and object_get_from_message().
request_navit_draw()
static DBusHandlerResult request_navit_draw (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), empty_reply(), eval::navit, navit_draw(), and object_get_from_message().
request_navit_evaluate()
static DBusHandlerResult request_navit_evaluate (DBusConnection * connection, DBusMessage * message) static
References command(), command_evaluate_to_string(), dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), eval::navit, attr::navit, object_get_from_message(), attr::type, and attr::u.
request_navit_get_attr()
static DBusHandlerResult request_navit_get_attr (DBusConnection * connection, DBusMessage * message) static
References navit_get_attr(), and request_get_attr().
request_navit_quit()
static DBusHandlerResult request_navit_quit (DBusConnection * connection, DBusMessage * message) static
Gracefully exit Navit by registering a one-second callback to allow clean shutdown of the dbus connection.
Parameters
connection The DBusConnection object through which message arrived
message The DBusMessage
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbus_callback::callback, callback_cast, callback_new_1, config_remove_attr(), dbg, dbus_error_invalid_object_path(), empty_reply(), event_add_timeout(), event_main_loop_quit(), lvl_debug, attr::navit, object_get_from_message(), attr::type, and attr::u.
request_navit_remove_attr()
static DBusHandlerResult request_navit_remove_attr (DBusConnection * connection, DBusMessage * message) static
References navit_remove_attr(), and request_set_add_remove_attr().
request_navit_resize()
static DBusHandlerResult request_navit_resize (DBusConnection * connection, DBusMessage * message) static
References dbg, dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), navit::h, lvl_debug, eval::navit, navit_handle_resize(), object_get_from_message(), and navit::w.
request_navit_route_export_geojson()
static DBusHandlerResult request_navit_route_export_geojson (DBusConnection * connection, DBusMessage * message) static
Exports the current route as a GeoJSON file.
Parameters
connection The DBusConnection object through which a message arrived
message The DBusMessage including the 'filename' parameter
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbg, dbus_error(), dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), dbus_error_navigation_not_configured(), empty_reply(), filename, g_strconcat_printf(), item_attr_get(), item_coord_get(), coord_geo::lat, coord_geo::lng, lvl_debug, item::map, map_convert_string_tmp(), map_rect_get_item(), map_rect_new(), navigation_get_map(), eval::navit, navit_get_navigation(), object_get_from_message(), point_get_from_message(), projection_mg, attr::str, transform_to_geo(), and attr::u.
request_navit_route_export_gpx()
static DBusHandlerResult request_navit_route_export_gpx (DBusConnection * connection, DBusMessage * message) static
Exports the current route as a GPX file.
Parameters
connection The DBusConnection object through which a message arrived
message The DBusMessage including the filename parameter
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbg, dbus_error(), dbus_error_invalid_object_path(), dbus_error_navigation_not_configured(), empty_reply(), filename, item_attr_get(), item_coord_get(), item_to_name(), coord_geo::lat, coord_geo::lng, lvl_debug, item::map, map_convert_string_tmp(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), navigation_get_map(), eval::navit, navit_get_navigation(), object_get_from_message(), projection_mg, attr::str, transform_to_geo(), item::type, and attr::u.
request_navit_set_attr()
static DBusHandlerResult request_navit_set_attr (DBusConnection * connection, DBusMessage * message) static
References navit_set_attr(), and request_set_add_remove_attr().
request_navit_set_center()
static DBusHandlerResult request_navit_set_center (DBusConnection * connection, DBusMessage * message) static
Centers the screen on a specified position pc on the world.
Parameters
connection The DBusConnection object through which message arrived
message The DBusMessage containing the coordinates
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), eval::navit, navit_set_center(), object_get_from_message(), and pcoord_get_from_message().
request_navit_set_center_screen()
static DBusHandlerResult request_navit_set_center_screen (DBusConnection * connection, DBusMessage * message) static
Centers the screen on a specified position p shown on the screen.
Parameters
connection The DBusConnection object through which message arrived
message The DBusMessage containing the x and y value
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), eval::navit, navit_set_center_screen(), object_get_from_message(), and point_get_from_message().
request_navit_set_destination()
static DBusHandlerResult request_navit_set_destination (DBusConnection * connection, DBusMessage * message) static
References dbg, dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), description(), empty_reply(), lvl_debug, eval::navit, navit_set_destination(), object_get_from_message(), and pcoord_get_from_message().
request_navit_set_layout()
static DBusHandlerResult request_navit_set_layout (DBusConnection * connection, DBusMessage * message) static
Sets the layout to new_layout_name extracted from message.
Parameters
connection The DBusConnection object through which message arrived
message The DBusMessage containing the name of the layout
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), attr_iter::iter, attr::layout, layout::name, eval::navit, navit_attr_iter_new(), navit_get_attr(), navit_set_attr(), object_get_from_message(), and attr::u.
request_navit_set_position()
static DBusHandlerResult request_navit_set_position (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), eval::navit, navit_set_position(), object_get_from_message(), and pcoord_get_from_message().
request_navit_traffic_export_gpx()
static DBusHandlerResult request_navit_traffic_export_gpx (DBusConnection * connection, DBusMessage * message) static
Exports currently active traffic distortions as a GPX file.
Parameters
connection The DBusConnection object through which a message arrived
message The DBusMessage including the filename parameter
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References AF_ONEWAY, AF_ONEWAYREV, traffic_point::coord, dbg, dbus_error(), dbus_error_invalid_object_path(), dbus_error_traffic_not_configured(), empty_reply(), filename, item_attr_get(), item_attr_rewind(), item_coord_get(), item_coord_rewind(), coord_geo::lat, coord_geo::lng, lvl_debug, eval::navit, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), attr::navit_object, attr::num, object_get_from_message(), projection_mg, traffic_get_stored_messages(), traffic_message_get_items(), transform_to_geo(), attr::u, coord::x, and coord::y.
request_navit_traffic_inject()
static DBusHandlerResult request_navit_traffic_inject (DBusConnection * connection, DBusMessage * message) static
Injects a traffic feed.
Parameters
connection The DBusConnection object through which a message arrived
message The DBusMessage including the filename parameter
Returns
An empty reply if everything went right, otherwise DBUS_HANDLER_RESULT_NOT_YET_HANDLED
References dbg, dbus_error_invalid_object_path(), dbus_error_traffic_not_configured(), empty_reply(), filename, lvl_debug, eval::navit, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), attr::navit_object, object_get_from_message(), traffic_get_messages_from_xml_file(), traffic_process_messages(), and attr::u.
request_navit_zoom()
static DBusHandlerResult request_navit_zoom (DBusConnection * connection, DBusMessage * message) static
References dbg, dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), empty_reply(), lvl_debug, eval::navit, navit_zoom_in(), navit_zoom_out(), object_get_from_message(), p, and point_get_from_message().
request_navit_zoom_to_route()
static DBusHandlerResult request_navit_zoom_to_route (DBusConnection * connection, DBusMessage * message) static
References dbg, dbus_error_invalid_object_path(), empty_reply(), lvl_debug, eval::navit, navit_zoom_to_route(), and object_get_from_message().
request_osd_get_attr()
static DBusHandlerResult request_osd_get_attr (DBusConnection * connection, DBusMessage * message) static
References osd_get_attr(), and request_get_attr().
request_osd_set_attr()
static DBusHandlerResult request_osd_set_attr (DBusConnection * connection, DBusMessage * message) static
References osd_set_attr(), and request_set_add_remove_attr().
request_roadprofile_attr_iter()
static DBusHandlerResult request_roadprofile_attr_iter (DBusConnection * connection, DBusMessage * message) static
References request_attr_iter(), and roadprofile_attr_iter_new().
request_roadprofile_attr_iter_destroy()
static DBusHandlerResult request_roadprofile_attr_iter_destroy (DBusConnection * connection, DBusMessage * message) static
References request_attr_iter_destroy(), and roadprofile_attr_iter_destroy().
request_roadprofile_get_attr()
static DBusHandlerResult request_roadprofile_get_attr (DBusConnection * connection, DBusMessage * message) static
References request_get_attr(), and roadprofile_get_attr().
request_roadprofile_set_attr()
static DBusHandlerResult request_roadprofile_set_attr (DBusConnection * connection, DBusMessage * message) static
References request_set_add_remove_attr(), and roadprofile_set_attr().
request_route_add_attr()
static DBusHandlerResult request_route_add_attr (DBusConnection * connection, DBusMessage * message) static
References request_set_add_remove_attr(), and route_add_attr().
request_route_destroy()
static DBusHandlerResult request_route_destroy (DBusConnection * connection, DBusMessage * message) static
References request_destroy(), and route_destroy().
request_route_dup()
static DBusHandlerResult request_route_dup (DBusConnection * connection, DBusMessage * message) static
References request_dup(), and route_dup().
request_route_get_attr()
static DBusHandlerResult request_route_get_attr (DBusConnection * connection, DBusMessage * message) static
References request_get_attr(), and route_get_attr().
request_route_remove_attr()
static DBusHandlerResult request_route_remove_attr (DBusConnection * connection, DBusMessage * message) static
References request_set_add_remove_attr(), and route_remove_attr().
request_route_set_attr()
static DBusHandlerResult request_route_set_attr (DBusConnection * connection, DBusMessage * message) static
References request_set_add_remove_attr(), and route_set_attr().
request_search_list_common()
static void request_search_list_common (struct search_list_common * slc, DBusMessageIter * iter4) static
References encode_dict_string_variant_string(), search_list_common::postal, and search_list_common::postal_mask.
Referenced by request_search_list_get_result().
request_search_list_destroy()
static DBusHandlerResult request_search_list_destroy (DBusConnection * connection, DBusMessage * message) static
References request_destroy(), and search_list_destroy().
request_search_list_get_result()
static DBusHandlerResult request_search_list_get_result (DBusConnection * connection, DBusMessage * message) static
References search_list_result::c, search_list_country::car, search_list_town::common, search_list_street::common, search_list_house_number::common, search_list_result::country, dbus_error_invalid_object_path(), dbus_error_no_data_available(), search_list_common::district_name, encode_dict_string_variant_string(), search_list_house_number::house_number, search_list_result::house_number, search_list_result::id, search_list_country::iso2, search_list_country::iso3, search_list_country::name, search_list_street::name, object_get_from_message(), pcoord_encode(), request_search_list_common(), search_list_get_result(), search_list_result::street, search_list_result::town, and search_list_common::town_name.
request_search_list_new()
static DBusHandlerResult request_search_list_new (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path_parameter(), object_get_from_message_arg(), object_new(), and search_list_new().
request_search_list_search()
static DBusHandlerResult request_search_list_search (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), decode_attr_from_iter(), empty_reply(), object_get_from_message(), and search_list_search().
request_search_list_select()
static DBusHandlerResult request_search_list_select (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), decode_attr_type_from_iter(), empty_reply(), object_get_from_message(), and search_list_select().
request_set_add_remove_attr()
static DBusHandlerResult request_set_add_remove_attr (DBusConnection * connection, DBusMessage * message, char * type, void * data, int(*)(void *data, struct attr *attr) func) static
References data, dbg, dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), decode_attr(), destroy_attr(), empty_reply(), lvl_error, and object_get_from_message().
Referenced by request_graphics_set_attr(), request_map_set_attr(), request_navit_add_attr(), request_navit_remove_attr(), request_navit_set_attr(), request_osd_set_attr(), request_roadprofile_set_attr(), request_route_add_attr(), request_route_remove_attr(), request_route_set_attr(), and request_vehicleprofile_set_attr().
request_tracking_get_attr()
static DBusHandlerResult request_tracking_get_attr (DBusConnection * connection, DBusMessage * message) static
References request_get_attr(), and tracking_get_attr().
request_vehicle_set_attr()
static DBusHandlerResult request_vehicle_set_attr (DBusConnection * connection, DBusMessage * message) static
References dbus_error_invalid_object_path(), dbus_error_invalid_parameter(), decode_attr(), destroy_attr(), empty_reply(), object_get_from_message(), vehicle, and vehicle_set_attr().
request_vehicleprofile_attr_iter()
static DBusHandlerResult request_vehicleprofile_attr_iter (DBusConnection * connection, DBusMessage * message) static
References request_attr_iter(), and vehicleprofile_attr_iter_new().
request_vehicleprofile_attr_iter_destroy()
static DBusHandlerResult request_vehicleprofile_attr_iter_destroy (DBusConnection * connection, DBusMessage * message) static
References request_attr_iter_destroy(), and vehicleprofile_attr_iter_destroy().
request_vehicleprofile_get_attr()
static DBusHandlerResult request_vehicleprofile_get_attr (DBusConnection * connection, DBusMessage * message) static
References request_get_attr(), and vehicleprofile_get_attr().
request_vehicleprofile_set_attr()
static DBusHandlerResult request_vehicleprofile_set_attr (DBusConnection * connection, DBusMessage * message) static
References request_set_add_remove_attr(), and vehicleprofile_set_attr().
resolve_object()
static void* resolve_object (const char * opath, char * type) static
References config_get_attr(), dbg, attr::graphics, attr::gui, lvl_debug, lvl_error, attr::map, attr::mapset, mapset_get_attr(), attr::navigation, attr::navit, navit_get_attr(), object_get(), object_path, attr::route, attr::tracking, attr::u, attr::vehicle, and attr::vehicleprofile.
Referenced by object_get_from_message(), and object_get_from_message_arg().
Variable Documentation
commands
struct command_table commands[] static
Initial value:
= {
    {"dbus_send_signal",command_cast(dbus_cmd_send_signal)},
}
connection
DBusConnection* connection static
dbus_methods
struct dbus_method dbus_methods[]
Referenced by generate_navitintrospectxml(), and navit_handler_func().
dbus_navit_vtable
DBusObjectPathVTable dbus_navit_vtable static
Initial value:
= {
    NULL,
    navit_handler_func,
    NULL
}
dbus_serial
dbus_uint32_t dbus_serial static
Referenced by dbus_callback_emit_signal(), dbus_cmd_send_signal(), and dbus_main_navit().
navitintrospectxml_head1
char* navitintrospectxml_head1
Initial value:
= "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n"
                                 "\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"
                                 "<node name=\""
Referenced by generate_navitintrospectxml().
navitintrospectxml_head2
char* navitintrospectxml_head2
Initial value:
= "\">\n"
                                 "  <interface name=\"org.freedesktop.DBus.Introspectable\">\n"
                                 "    <method name=\"Introspect\">\n"
                                 "      <arg direction=\"out\" type=\"s\" />\n"
                                 "    </method>\n"
                                 "  </interface>\n"
Referenced by generate_navitintrospectxml().
object_count
GHashTable* object_count
Referenced by object_new(), and plugin_init().
object_hash
GHashTable* object_hash
Referenced by object_destroy(), object_get(), object_new(), and plugin_init().
object_hash_rev
GHashTable* object_hash_rev
Referenced by object_destroy(), object_new(), and plugin_init().
object_path
char* object_path = "/org/navit_project/navit" static
Referenced by dbus_callback_emit_signal(), introspect_path(), object_new(), plugin_init(), and resolve_object().
service_name
char* service_name = "org.navit_project.navit" static
Referenced by dbus_callback_emit_signal(), dbus_cmd_send_signal(), dbus_main_navit(), generate_navitintrospectxml(), navit_handler_func(), plugin_init(), and vehicle_webos_spp_notify().