navit: binding/python/navit.c File Reference
navit.c File Reference
#include "navit.h"
#include "common.h"
#include "item.h"
Data Structures
struct navitObject
Functions
static PyObject * navit_set_attr_py (navitObject *self, PyObject *args)
static PyObject * navit_get_attr_py (navitObject *self, PyObject *args)
static PyObject * navit_set_center_py (navitObject *self, PyObject *args)
static PyObject * navit_set_destination_py (navitObject *self, PyObject *args)
static PyObject * navit_set_position_py (navitObject *self, PyObject *args)
static PyObject * navit_zoom_to_route_py (navitObject *self, PyObject *args)
static PyObject * navit_getattr_py (PyObject *self, char *name)
static void navit_destroy_py (navitObject *self)
PyObject * navit_py (PyObject *self, PyObject *args)
PyObject * navit_py_ref (struct navit *navit)
Variables
static PyMethodDef navit_methods []
PyTypeObject navit_Type
Function Documentation
navit_destroy_py()
static void navit_destroy_py (navitObject * self) static
navit_get_attr_py()
static PyObject * navit_get_attr_py (navitObject * self, PyObject * args) static
References attr_from_name(), dbg, lvl_debug, lvl_error, name, navitObject::navit, navit_get_attr(), and python_object_from_attr().
navit_getattr_py()
static PyObject * navit_getattr_py (PyObject * self, char * name) static
References name, and navit_methods.
navit_py()
PyObject * navit_py (PyObject * self, PyObject * args)
References dbg, lvl_debug, and navit_Type.
navit_py_ref()
PyObject * navit_py_ref (struct navit * navit)
References dbg, lvl_debug, attr::navit, navitObject::navit, and navit_Type.
Referenced by config_navit().
navit_set_attr_py()
static PyObject * navit_set_attr_py (navitObject * self, PyObject * args) static
References attr_py_get(), attr_Type, attr::navit, navit_set_attr(), and navit::self.
navit_set_center_py()
static PyObject * navit_set_center_py (navitObject * self, PyObject * args) static
References navitObject::navit, navit_set_center(), attr::pcoord, pcoord_py_get(), and pcoord_Type.
navit_set_destination_py()
static PyObject * navit_set_destination_py (navitObject * self, PyObject * args) static
References description(), navitObject::navit, navit_set_destination(), attr::pcoord, pcoord_py_get(), and pcoord_Type.
navit_set_position_py()
static PyObject * navit_set_position_py (navitObject * self, PyObject * args) static
References navitObject::navit, navit_set_position(), attr::pcoord, pcoord_py_get(), and pcoord_Type.
navit_zoom_to_route_py()
static PyObject * navit_zoom_to_route_py (navitObject * self, PyObject * args) static
References navitObject::navit, and navit_zoom_to_route().
Variable Documentation
navit_methods
PyMethodDef navit_methods[] static
Initial value:
= {
    {"set_attr", (PyCFunction)navit_set_attr_py, METH_VARARGS},
    {"get_attr", (PyCFunction)navit_get_attr_py, METH_VARARGS},
    {"set_center", (PyCFunction)navit_set_center_py, METH_VARARGS},
    {"set_destination", (PyCFunction)navit_set_destination_py, METH_VARARGS},
    {"set_position", (PyCFunction)navit_set_position_py, METH_VARARGS},
    {"zoom_to_route", (PyCFunction)navit_zoom_to_route_py, METH_VARARGS},
    {NULL, NULL},
}
Referenced by navit_getattr_py().
navit_Type
PyTypeObject navit_Type
Initial value:
= {
    Obj_HEAD,
    .tp_name = "navit",
    .tp_basicsize = sizeof(navitObject),
    .tp_dealloc = (destructor)navit_destroy_py,
    .tp_getattr = navit_getattr_py,
}
Referenced by navit_py(), and navit_py_ref().