navit: binding/win32/binding_win32.c File Reference
binding_win32.c File Reference
#include <string.h>
#include <glib.h>
#include <windows.h>
#include "config.h"
#include "config_.h"
#include "navit.h"
#include "coord.h"
#include "point.h"
#include "plugin.h"
#include "debug.h"
#include "item.h"
#include "xmlconfig.h"
#include "attr.h"
#include "layout.h"
#include "navigation.h"
#include "command.h"
#include "callback.h"
#include "graphics.h"
#include "track.h"
#include "vehicle.h"
#include "vehicleprofile.h"
Data Structures
struct win32_binding_private
Functions
static int win32_cmd_send_signal (struct navit *navit, char *command, struct attr **in, struct attr ***out)
static void win32_wm_copydata (struct win32_binding_private *this, int *hwndSender, COPYDATASTRUCT *cpd)
static void win32_cb_graphics_ready (struct win32_binding_private *this, struct navit *navit)
static void win32_main_navit (struct win32_binding_private *this, struct navit *navit, int added)
void plugin_init (void)
Variables
static struct command_table commands []
Function Documentation
plugin_init()
void plugin_init (void)
References callback_cast, callback_new_attr_1, config_add_attr(), dbg, lvl_debug, callback::type, and win32_main_navit().
win32_cb_graphics_ready()
static void win32_cb_graphics_ready (struct win32_binding_private * this, struct navit * navit) static
References callback_cast, callback_new_attr_1, dbg_assert, graphics_add_callback(), navit_get_graphics(), and win32_wm_copydata().
Referenced by win32_main_navit().
win32_cmd_send_signal()
static int win32_cmd_send_signal (struct navit * navit, char * command, struct attr ** in, struct attr *** out) static
win32_main_navit()
static void win32_main_navit (struct win32_binding_private * this, struct navit * navit, int added) static
References callback_cast, callback_new_attr_1, command_add_table_attr(), commands, dbg, lvl_debug, eval::navit, navit_add_attr(), navit_add_callback(), and win32_cb_graphics_ready().
Referenced by plugin_init().
win32_wm_copydata()
static void win32_wm_copydata (struct win32_binding_private * this, int * hwndSender, COPYDATASTRUCT * cpd) static
References command_evaluate(), dbg, lvl_debug, lvl_error, navit_binding_w32_msg::magic, eval::navit, NAVIT_BINDING_W32_DWDATA, NAVIT_BINDING_W32_MAGIC, NAVIT_BINDING_W32_VERSION, navit_binding_w32_msg::text, and navit_binding_w32_msg::version.
Referenced by win32_cb_graphics_ready().
Variable Documentation
commands
struct command_table commands[] static
Initial value:
= {
    {"win32_send",command_cast(win32_cmd_send_signal)},
}
Referenced by win32_main_navit().