navit: binding/python/attr.c File Reference
attr.c File Reference
#include "common.h"
#include "item.h"
#include "attr.h"
Data Structures
struct attrObject
Functions
static PyObject * attr_func (attrObject *self, PyObject *args)
static PyObject * attr_getattr_py (PyObject *self, char *name)
static void attr_destroy_py (attrObject *self)
struct attr * attr_py_get (PyObject *self)
PyObject * attr_new_py (PyObject *self, PyObject *args)
PyObject * attr_new_py_ref (struct attr *attr)
Variables
static PyMethodDef attr_methods []
PyTypeObject attr_Type
Function Documentation
static void attr_destroy_py (attrObject * self) static
References attr_free().
static PyObject* attr_func (attrObject * self, PyObject * args) static
References file, and NULL.
static PyObject* attr_getattr_py (PyObject * self, char * name) static
References attr_methods.
PyObject* attr_new_py (PyObject * self, PyObject * args)
References attrObject::attr, attr_new_from_text(), name, NULL, attrObject::ref, and value.
PyObject* attr_new_py_ref (struct attr * attr)
References attrObject::attr, and attrObject::ref.
struct attr* attr_py_get (PyObject * self)
Referenced by map_set_attr_py(), and navit_set_attr_py().
Variable Documentation
PyMethodDef attr_methods[] static
Initial value:
= {
        {"func",        (PyCFunction) attr_func, METH_VARARGS },
        {NULL, NULL },
}
Referenced by attr_getattr_py().
PyTypeObject attr_Type
Initial value:
= {
        Obj_HEAD
        .tp_name="attr",
        .tp_basicsize=sizeof(attrObject),
        .tp_dealloc=(destructor)attr_destroy_py,
        .tp_getattr=attr_getattr_py,
}
Referenced by map_set_attr_py(), and navit_set_attr_py().