navit: map/binfile/binfile.c File Reference
binfile.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "config.h"
#include "debug.h"
#include "plugin.h"
#include "projection.h"
#include "item.h"
#include "map.h"
#include "maptype.h"
#include "attr.h"
#include "coord.h"
#include "transform.h"
#include "file.h"
#include "zipfile.h"
#include "linguistics.h"
#include "endianess.h"
#include "callback.h"
#include "types.h"
#include "geom.h"
Data Structures
struct tile
A map tile, a rectangular region of the world.
struct map_download
struct map_priv
Represents the map from a single binfile.
struct map_rect_priv
Implementation-specific map rect data.
struct map_search_priv
Represents a search on a map. This struct represents a search on a map; it is created when starting a search, and is used for retrieving results.
struct binfile_hash_entry
struct duplicate
Functions
static void push_tile (struct map_rect_priv *mr, struct tile *t, int offset, int length)
static void setup_pos (struct map_rect_priv *mr)
static void map_binfile_close (struct map_priv *m)
static int map_binfile_open (struct map_priv *m)
static void map_binfile_destroy (struct map_priv *m)
static void lfh_to_cpu (struct zip_lfh *lfh)
static void cd_to_cpu (struct zip_cd *zcd)
static void eoc_to_cpu (struct zip_eoc *eoc)
static void binfile_check_version (struct map_priv *m)
static struct zip_eoc * binfile_read_eoc (struct file *fi)
static struct zip64_eoc * binfile_read_eoc64 (struct file *fi)
static int binfile_cd_extra (struct zip_cd *cd)
static struct zip_cd * binfile_read_cd (struct map_priv *m, int offset, int len)
static struct zip_cd_ext * binfile_cd_ext (struct zip_cd *cd)
Get the ZIP64 extra field data corresponding to a zip central directory header.
static long long binfile_cd_offset (struct zip_cd *cd)
static struct zip_lfh * binfile_read_lfh (struct file *fi, long long offset)
static unsigned char * binfile_read_content (struct map_priv *m, struct file *fi, long long offset, struct zip_lfh *lfh)
static int binfile_search_cd (struct map_priv *m, int offset, char *name, int partial, int skip)
static void map_destroy_binfile (struct map_priv *m)
static void binfile_coord_rewind (void *priv_data)
static int binfile_coord_left (void *priv_data)
static int binfile_coord_get (void *priv_data, struct coord *c, int count)
static int binfile_coords_left (void *priv_data)
Get nuber of coords left for current item.
static void binfile_attr_rewind (void *priv_data)
static char * binfile_extract (struct map_priv *m, char *dir, char *filename, int partial)
static int binfile_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static guint binfile_hash_entry_hash (gconstpointer key)
static gboolean binfile_hash_entry_equal (gconstpointer a, gconstpointer b)
static int * binfile_item_dup (struct map_priv *m, struct item *item, struct tile *t, int extend)
static int binfile_coord_set (void *priv_data, struct coord *c, int count, enum change_mode mode)
static int binfile_attr_set (void *priv_data, struct attr *attr, enum change_mode mode)
static int pop_tile (struct map_rect_priv *mr)
static int zipfile_to_tile (struct map_priv *m, struct zip_cd *cd, struct tile *t)
static int map_binfile_handle_redirect (struct map_priv *m)
static int map_binfile_http_request (struct map_priv *m, struct attr **attrs)
static long long map_binfile_download_size (struct map_priv *m)
static int map_binfile_http_close (struct map_priv *m)
static struct file * map_binfile_http_range (struct map_priv *m, long long offset, int size)
static unsigned char * map_binfile_download_range (struct map_priv *m, long long offset, int size)
static struct zip_cd * download_cd (struct map_download *download)
static int download_request (struct map_download *download)
static int download_start (struct map_download *download)
static int download_download (struct map_download *download)
static int download_finish (struct map_download *download)
static int download_planet_size (struct map_download *download)
static int download_eoc (struct map_download *download)
static int download_directory_start (struct map_download *download)
static int download_directory_do (struct map_download *download)
static int download_directory_finish (struct map_download *download)
static int download_initial_finish (struct map_download *download)
static void push_zipfile_tile_do (struct map_rect_priv *mr, struct zip_cd *cd, int zipfile, int offset, int length)
static struct zip_cd * download (struct map_priv *m, struct map_rect_priv *mr, struct zip_cd *cd, int zipfile, int offset, int length, int async)
static int push_zipfile_tile (struct map_rect_priv *mr, int zipfile, int offset, int length, int async)
static struct map_rect_priv * map_rect_new_binfile_int (struct map_priv *map, struct map_selection *sel)
static void tile_bbox (char *tile, int len, struct coord_rect *r)
static int map_download_selection_check (struct zip_cd *cd, struct map_selection *sel)
static void map_download_selection (struct map_priv *m, struct map_rect_priv *mr, struct map_selection *sel)
static struct map_rect_priv * map_rect_new_binfile (struct map_priv *map, struct map_selection *sel)
static void write_changes_do (gpointer key, gpointer value, gpointer user_data)
static void write_changes (struct map_priv *m)
static void load_changes (struct map_priv *m)
static void map_rect_destroy_binfile (struct map_rect_priv *mr)
static int selection_contains (struct map_selection *sel, struct coord_rect *r, struct range *mima)
static void map_parse_country_binfile (struct map_rect_priv *mr)
static int map_parse_submap (struct map_rect_priv *mr, int async)
static int push_modified_item (struct map_rect_priv *mr)
static struct item * map_rect_get_item_binfile (struct map_rect_priv *mr)
static struct item * map_rect_get_item_byid_binfile (struct map_rect_priv *mr, int id_hi, int id_lo)
static int binmap_search_by_index (struct map_priv *map, struct item *item, struct map_rect_priv **ret)
static struct map_rect_priv * binmap_search_street_by_place (struct map_priv *map, struct item *town, struct coord *c, struct map_selection *sel, GList **boundaries)
static int binmap_get_estimated_town_size (struct item *town)
static struct map_rect_priv * binmap_search_street_by_estimate (struct map_priv *map, struct item *town, struct coord *c, struct map_selection *sel)
static struct map_rect_priv * binmap_search_housenumber_by_estimate (struct map_priv *map, struct coord *c, struct map_selection *sel)
static int binmap_get_estimated_boundaries (struct item *town, GList **boundaries)
static struct map_search_priv * binmap_search_new (struct map_priv *map, struct item *item, struct attr *search, int partial)
static guint duplicate_hash (gconstpointer key)
static gboolean duplicate_equal (gconstpointer a, gconstpointer b)
static struct duplicate * duplicate_test (struct map_search_priv *msp, struct item *item, enum attr_type attr_type, enum attr_type attr_type2)
Test an item if it's duplicate. If it's not a duplicate, return new struct duplicate to be duplicate_insert()'ed.
static void duplicate_insert (struct map_search_priv *msp, struct duplicate *d)
Insert struct duplicate item into the duplicate hash.
static int duplicate (struct map_search_priv *msp, struct item *item, enum attr_type attr_type, enum attr_type attr_type2)
Check if item is duplicate and update duplicate hash if needed.
static int item_inside_poly_list (struct item *it, GList *l)
static struct item * binmap_search_get_item (struct map_search_priv *map_search)
static void binmap_search_destroy (struct map_search_priv *ms)
static int binmap_get_attr (struct map_priv *m, enum attr_type type, struct attr *attr)
static int binmap_set_attr (struct map_priv *map, struct attr *attr)
static int binfile_get_index (struct map_priv *m)
static int map_binfile_zip_setup (struct map_priv *m, char *filename, int mmap)
static struct map_priv * map_new_binfile (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
register vehicle_gypsy
Variables
static int map_id
static struct item_methods methods_binfile
static struct map_methods map_methods_binfile
Function Documentation
binfile_attr_get()
static int binfile_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References AF_CAR, attr_data_set_le(), ATTR_IS_GROUP, map_rect_priv::attr_last, attr_to_name(), map_rect_priv::attrs, attr::attrs, binfile_extract(), map_priv::cachedir, attr::data, dbg, map_rect_priv::item, map_rect_priv::label, map_rect_priv::label_attr, le32_to_cpu, lvl_debug, map_rect_priv::m, map_priv::map_version, attr::num, tile::pos_attr, tile::pos_attr_start, tile::pos_next, size, attr::str, subtype, map_rect_priv::t, item::type, type, attr::type, attr::u, and map_rect_priv::url.
Referenced by binmap_search_get_item(), map_binfile_open(), map_parse_country_binfile(), and map_parse_submap().
binfile_attr_rewind()
static void binfile_attr_rewind (void * priv_data) static
Parameters
References map_rect_priv::label, map_rect_priv::label_attr, tile::pos_attr, tile::pos_attr_start, and map_rect_priv::t.
Referenced by binmap_search_get_item(), duplicate_test(), map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
binfile_attr_set()
static int binfile_attr_set (void * priv_data, struct attr * attr, enum change_mode mode) static
References attr_data_get(), attr_data_size(), binfile_item_dup(), change_mode_append, change_mode_delete, change_mode_modify, change_mode_prepend, cpu_to_le32, data, dbg, map_rect_priv::item, le32_to_cpu, lvl_debug, lvl_error, map_rect_priv::m, offset, tile::pos, tile::pos_attr, tile::pos_attr_start, tile::pos_coord, tile::pos_coord_start, tile::pos_next, push_tile(), setup_pos(), map_rect_priv::t, attr::type, and tile::zipfile_num.
binfile_cd_ext()
static struct zip_cd_ext* binfile_cd_ext (struct zip_cd * cd) static
Get the ZIP64 extra field data corresponding to a zip central directory header.
Parameters
cd pointer to zip central directory structure
Returns
pointer to ZIP64 extra field, or NULL if not available
References zip_cd_ext::size, zip_cd_ext::tag, zip_extra_header_id_zip64, zip_size_64bit_placeholder, zip_cd::zipcfnl, zip_cd::zipcxtl, and zip_cd::zipofst.
Referenced by binfile_cd_offset(), and download_finish().
binfile_cd_extra()
static int binfile_cd_extra (struct zip_cd * cd) static
References zip_cd::zipcfnl, and zip_cd::zipcxtl.
Referenced by binfile_read_cd(), download_finish(), and map_binfile_zip_setup().
binfile_cd_offset()
static long long binfile_cd_offset (struct zip_cd * cd) static
Parameters
cd pointer to zip central directory structure
Returns
Offset of local file header in zip file. Will use ZIP64 data if present.
References binfile_cd_ext(), zip_cd::zipofst, and zip_cd_ext::zipofst.
Referenced by binfile_extract(), download_finish(), download_request(), and zipfile_to_tile().
binfile_check_version()
static void binfile_check_version (struct map_priv * m) static
References map_priv::check_version, map_priv::fi, file_version(), map_binfile_close(), map_binfile_open(), version(), and map_priv::version.
Referenced by eoc_to_cpu(), and map_rect_new_binfile_int().
binfile_coord_get()
static int binfile_coord_get (void * priv_data, struct coord * c, int count) static
References binfile_coord_left(), c, tile::end, le32_to_cpu, max, tile::pos_coord, and map_rect_priv::t.
Referenced by map_parse_submap().
binfile_coord_left()
static int binfile_coord_left (void * priv_data) inline static
References tile::pos_attr_start, tile::pos_coord, and map_rect_priv::t.
Referenced by binfile_coord_get(), binfile_coords_left(), binmap_search_street_by_place(), and item_inside_poly_list().
binfile_coord_rewind()
static void binfile_coord_rewind (void * priv_data) static
References tile::pos_coord, tile::pos_coord_start, and map_rect_priv::t.
Referenced by duplicate_test(), map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
binfile_coord_set()
static int binfile_coord_set (void * priv_data, struct coord * c, int count, enum change_mode mode) static
References binfile_item_dup(), change_mode_append, change_mode_delete, change_mode_modify, change_mode_prepend, cpu_to_le32, data, dbg, map_rect_priv::item, le32_to_cpu, lvl_debug, map_rect_priv::m, tile::pos, tile::pos_attr, tile::pos_attr_start, tile::pos_coord, tile::pos_coord_start, tile::pos_next, push_tile(), setup_pos(), map_rect_priv::t, coord::x, coord::y, and tile::zipfile_num.
binfile_coords_left()
static int binfile_coords_left (void * priv_data) static
Get nuber of coords left for current item.
Parameters
prv_data
References binfile_coord_left().
binfile_extract()
static char* binfile_extract (struct map_priv * m, char * dir, char * filename, int partial) static
References binfile_cd_offset(), binfile_read_cd(), binfile_read_content(), binfile_read_lfh(), binfile_search_cd(), dbg, map_priv::fi, file_data_free(), file_mkdir(), map_priv::index_offset, lvl_debug, offset, tile::start, zip_cd::zipcfn, zip_cd::zipcfnl, and zip_lfh::zipuncmp.
Referenced by binfile_attr_get().
binfile_get_index()
static int binfile_get_index (struct map_priv * m) static
References binfile_read_cd(), binfile_search_cd(), map_priv::eoc, map_priv::eoc64, map_priv::index_cd, map_priv::index_offset, offset, zip64_eoc::zip64ecsz, zip_cd::zipcfn, zip_cd::zipcfnl, and zip_eoc::zipecsz.
Referenced by map_binfile_zip_setup().
binfile_hash_entry_equal()
static gboolean binfile_hash_entry_equal (gconstpointer a, gconstpointer b) static
References binfile_hash_entry::id, item_id::id_hi, and item_id::id_lo.
Referenced by binfile_item_dup(), and load_changes().
binfile_hash_entry_hash()
static guint binfile_hash_entry_hash (gconstpointer key) static
References binfile_hash_entry::id, item_id::id_hi, item_id::id_lo, and key.
Referenced by binfile_item_dup(), and load_changes().
binfile_item_dup()
static int* binfile_item_dup (struct map_priv * m, struct item * item, struct tile * t, int extend) static
References binfile_hash_entry_equal(), binfile_hash_entry_hash(), map_priv::changes, binfile_hash_entry::data, dbg, binfile_hash_entry::flags, binfile_hash_entry::id, item_id::id_hi, item::id_hi, item_id::id_lo, item::id_lo, le32_to_cpu, lvl_debug, tile::pos, and size.
Referenced by binfile_attr_set(), and binfile_coord_set().
binfile_read_cd()
static struct zip_cd* binfile_read_cd (struct map_priv * m, int offset, int len) static
References binfile_cd_extra(), cd_to_cpu(), dbg, map_priv::eoc, map_priv::eoc64, map_priv::fi, file_data_free(), file_data_read(), LONGLONG_FMT, lvl_debug, zip64_eoc::zip64eofst, zip_cd_sig, zip_cd::zipcensig, and zip_eoc::zipeofst.
Referenced by binfile_extract(), binfile_get_index(), map_binfile_zip_setup(), and map_download_selection().
binfile_read_content()
static unsigned char* binfile_read_content (struct map_priv * m, struct file * fi, long long offset, struct zip_lfh * lfh) static
References dbg, file_data_read(), file_data_read_compressed(), lvl_error, file::name, zip_lfh::zipmthd, zip_lfh::zipsize, zip_lfh::zipuncmp, and zip_lfh::zipxtraln.
Referenced by binfile_extract(), and zipfile_to_tile().
binfile_read_eoc()
static struct zip_eoc* binfile_read_eoc (struct file * fi) static
References dbg, eoc_to_cpu(), file_data_free(), file_data_read(), lvl_debug, lvl_error, file::name, file::size, zip_eoc_sig, and zip_eoc::zipesig.
Referenced by map_binfile_zip_setup().
binfile_read_eoc64()
static struct zip64_eoc* binfile_read_eoc64 (struct file * fi) static
References dbg, file_data_free(), file_data_read(), LONGLONG_HEX_FMT, lvl_debug, lvl_warning, file::name, file::size, zip64_eoc_sig, zip64_eocl_sig, zip64_eoc::zip64ecsz, zip64_eoc::zip64eofst, zip64_eoc::zip64esig, zip64_eocl::zip64lofst, and zip64_eocl::zip64lsig.
Referenced by map_binfile_zip_setup().
binfile_read_lfh()
static struct zip_lfh* binfile_read_lfh (struct file * fi, long long offset) static
References file_data_free(), file_data_read(), lfh_to_cpu(), zip_lfh_sig, and zip_lfh::ziplocsig.
Referenced by binfile_extract(), and zipfile_to_tile().
binfile_search_cd()
static int binfile_search_cd (struct map_priv * m, int offset, char * name, int partial, int skip) static
References dbg, tile::end, map_priv::eoc, map_priv::eoc64, map_priv::fi, file_data_free(), file_data_read(), lvl_debug, offset, map_priv::search_data, map_priv::search_offset, map_priv::search_size, size, zip64_eoc::zip64ecsz, zip64_eoc::zip64eofst, zip_cd::zipccml, zip_cd::zipcfn, zip_cd::zipcfnl, zip_cd::zipcxtl, zip_eoc::zipecsz, and zip_eoc::zipeofst.
Referenced by binfile_extract(), and binfile_get_index().
binmap_get_attr()
static int binmap_get_attr (struct map_priv * m, enum attr_type type, struct attr * attr) static
References map_priv::map_release, map_priv::progress, attr::str, type, attr::type, and attr::u.
binmap_get_estimated_boundaries()
static int binmap_get_estimated_boundaries (struct item * town, GList ** boundaries) static
References binmap_get_estimated_town_size(), c, geom_poly_segment::first, geom_poly_segment_type_way_outer, item_coord_get(), geom_poly_segment::last, size, geom_poly_segment::type, coord::x, and coord::y.
Referenced by binmap_search_new().
binmap_get_estimated_town_size()
static int binmap_get_estimated_town_size (struct item * town) static
References size, and item::type.
Referenced by binmap_get_estimated_boundaries(), and binmap_search_street_by_estimate().
binmap_search_by_index()
static int binmap_search_by_index (struct map_priv * map, struct item * item, struct map_rect_priv ** ret) static
References attr::data, data, item_attr_get(), le32_to_cpu, map_rect_new_binfile_int(), attr::num, push_zipfile_tile(), and attr::u.
Referenced by binmap_search_get_item(), and binmap_search_new().
binmap_search_destroy()
static void binmap_search_destroy (struct map_search_priv * ms) static
References ATTR_IS_STRING, map_search_priv::boundaries, geom_poly_segment_destroy(), map_rect_destroy_binfile(), map_search_priv::mr, map_search_priv::mr_item, map_search_priv::parent_name, map_search_priv::search, map_search_priv::search_results, attr::str, attr::type, and attr::u.
binmap_search_get_item()
static struct item* binmap_search_get_item (struct map_search_priv * map_search) static
References binfile_attr_get(), binfile_attr_rewind(), binmap_search_by_index(), map_search_priv::boundaries, map_selection::c_rect, coord_rect_extend(), dbg, duplicate(), duplicate_insert(), duplicate_test(), map_search_priv::item, item_coord_get(), item_coord_rewind(), item_inside_poly_list(), item_is_district, item_is_street, item_is_town, linguistics_cmp_expand, linguistics_cmp_partial, linguistics_cmp_words, linguistics_compare(), coord_rect::lu, lvl_debug, map_search_priv::map, map_rect_destroy_binfile(), map_rect_get_item_binfile(), map_rect_new_binfile(), map_selection_contains_item_rect(), tile::mode, map_search_priv::mode, map_search_priv::mr, map_search_priv::mr_item, map_search_priv::ms, map_search_priv::parent_name, map_search_priv::partial, item::priv_data, map_search_priv::rect_new, coord_rect::rl, map_search_priv::search, map_rect_priv::sel, attr::str, map_rect_priv::tile_depth, item::type, attr::type, map_selection::u, attr::u, coord::x, and coord::y.
binmap_search_housenumber_by_estimate()
static struct map_rect_priv* binmap_search_housenumber_by_estimate (struct map_priv * map, struct coord * c, struct map_selection * sel) static
References map_selection::c_rect, item_range_all, coord_rect::lu, map_rect_new_binfile(), map_selection::order, map_selection::range, coord_rect::rl, size, map_selection::u, coord::x, and coord::y.
Referenced by binmap_search_new().
binmap_search_new()
static struct map_search_priv* binmap_search_new (struct map_priv * map, struct item * item, struct attr * search, int partial) static
References ATTR_IS_STRING, binmap_get_estimated_boundaries(), binmap_search_by_index(), binmap_search_housenumber_by_estimate(), binmap_search_street_by_estimate(), binmap_search_street_by_place(), map_search_priv::boundaries, map_selection::c_rect, map_rect_priv::country_id, dbg, item::id_hi, item::id_lo, map_search_priv::item, item_attr_get(), item_coord_get(), map_priv::last_searched_town_id_hi, map_priv::last_searched_town_id_lo, linguistics_casefold(), lvl_debug, item::map, map_search_priv::map, map_priv_is(), map_rect_destroy_binfile(), map_rect_get_item_byid_binfile(), map_rect_new_binfile(), map_search_priv::mode, map_search_priv::mr, map_search_priv::mr_item, map_search_priv::ms, map_rect_priv::msp, map_search_priv::parent_name, map_search_priv::partial, map_search_priv::rect_new, map_search_priv::search, attr::str, attr::type, map_selection::u, and attr::u.
binmap_search_street_by_estimate()
static struct map_rect_priv* binmap_search_street_by_estimate (struct map_priv * map, struct item * town, struct coord * c, struct map_selection * sel) static
References binmap_get_estimated_town_size(), map_selection::c_rect, coord_rect::lu, map_rect_new_binfile(), coord_rect::rl, size, map_selection::u, coord::x, and coord::y.
Referenced by binmap_search_new().
binmap_search_street_by_place()
static struct map_rect_priv* binmap_search_street_by_place (struct map_priv * map, struct item * town, struct coord * c, struct map_selection * sel, GList ** boundaries) static
References binfile_coord_left(), c, map_selection::c_rect, coord_rect_extend(), geom_poly_segment::first, geom_poly_segment_type_way_outer, item_attr_get(), item_coord_get(), item_is_poly_place, item_range_all, geom_poly_segment::last, coord_rect::lu, map_rect_destroy_binfile(), map_rect_get_item_binfile(), map_rect_new_binfile(), map_selection::next, map_selection::order, map_selection::range, coord_rect::rl, attr::str, geom_poly_segment::type, map_selection::u, and attr::u.
Referenced by binmap_search_new().
binmap_set_attr()
static int binmap_set_attr (struct map_priv * map, struct attr * attr) static
References map_priv::download_enabled, attr::num, attr::type, and attr::u.
cd_to_cpu()
static void cd_to_cpu (struct zip_cd * zcd) static
References dbg_assert, le16_to_cpu, le32_to_cpu, zip_cd_sig, zip_cd::zipccml, zip_cd::zipccrc, zip_cd::zipcensig, zip_cd::zipcfnl, zip_cd::zipcsiz, zip_cd::zipcunc, zip_cd::zipcxtl, zip_cd::zipdsk, zip_cd::zipext, zip_cd::zipint, and zip_cd::zipofst.
Referenced by binfile_read_cd(), download_finish(), and push_zipfile_tile().
download()
static struct zip_cd* download (struct map_priv * m, struct map_rect_priv * mr, struct zip_cd * cd, int zipfile, int offset, int length, int async) static
References attr::attrs, callback_list_call_attr_0, map_priv::cbl, map_download::cd, dbg, map_priv::download, download_directory_do(), download_directory_finish(), download_directory_start(), download_download(), map_priv::download_enabled, download_eoc(), download_finish(), download_initial_finish(), download_planet_size(), download_start(), map_priv::fi, map_download::file, file_create(), map_priv::filename, length, lvl_debug, lvl_error, map_download::m, map_binfile_open(), map_download::mr, offset, map_download::offset, map_download::progress, map_priv::progress, push_zipfile_tile_do(), map_download::state, map_download::tlength, map_download::toffset, map_download::zip64_eoc, zip64_eoc::zip64ecsz, and map_download::zipfile.
Referenced by map_binfile_zip_setup(), map_download_selection(), map_rect_get_item_binfile(), map_rect_new_binfile(), and push_zipfile_tile().
download_cd()
static struct zip_cd* download_cd (struct map_download * download) static
References map_priv::cde_size, dbg, map_priv::fi, file_data_free(), file_data_read(), lvl_debug, map_download::m, map_binfile_download_range(), zip64_eoc::zip64eofst, and map_download::zipfile.
Referenced by download_start().
download_directory_do()
static int download_directory_do (struct map_download * download) static
References dbg, map_download::file, file_data_read_special(), file_data_write(), map_download::http, lvl_debug, lvl_error, map_download::offset, zip_cd_sig, zip_cd::zipcensig, and zip_cd::zipcunc.
Referenced by download(), and map_binfile_zip_setup().
download_directory_finish()
static int download_directory_finish (struct map_download * download) static
References map_download::http.
Referenced by download(), and map_binfile_zip_setup().
download_directory_start()
static int download_directory_start (struct map_download * download) static
References map_download::http, map_download::m, map_binfile_http_range(), map_download::zip64_eoc, zip64_eoc::zip64ecsz, and zip64_eoc::zip64eofst.
Referenced by download(), and map_binfile_zip_setup().
download_download()
static int download_download (struct map_download * download) static
References data, dbg, map_download::dl_size, download_request(), map_download::file, file_data_read_special(), file_data_write(), map_download::http, map_priv::http, LONGLONG_FMT, lvl_debug, map_download::m, map_binfile_handle_redirect(), map_download::offset, map_download::progress, map_download::read, and size.
Referenced by download().
download_eoc()
static int download_eoc (struct map_download * download) static
References dbg, LONGLONG_FMT, lvl_error, map_download::m, map_binfile_download_range(), map_download::size, map_download::zip64_eoc, zip64_eoc_sig, map_download::zip64_eocl, zip64_eocl_sig, zip64_eoc::zip64esig, zip64_eocl::zip64lsig, map_download::zip_eoc, zip_eoc_sig, and zip_eoc::zipesig.
Referenced by download(), and map_binfile_zip_setup().
download_finish()
static int download_finish (struct map_download * download) static
References binfile_cd_ext(), binfile_cd_extra(), binfile_cd_offset(), map_download::cd, map_download::cd_copy, cd_to_cpu(), map_priv::cde_size, dbg, map_priv::eoc, map_download::file, file_data_flush(), file_data_read(), file_data_remove(), file_data_write(), lvl_debug, map_download::m, map_download::offset, map_download::start_offset, map_download::zip_eoc, zip_cd::zipccrc, zip_lfh::zipcrc, zip_cd::zipcsiz, zip_cd::zipcunc, zip_eoc::zipeofst, map_download::zipfile, zip_lfh::zipfnln, zip_cd::zipofst, zip_cd_ext::zipofst, zip_lfh::zipsize, and zip_lfh::zipuncmp.
Referenced by download().
download_initial_finish()
static int download_initial_finish (struct map_download * download) static
References map_download::cd1offset, map_download::file, file_data_write(), map_download::offset, map_download::zip64_eoc, map_download::zip64_eocl, zip64_eoc::zip64eofst, zip64_eocl::zip64lofst, map_download::zip_eoc, and zip_eoc::zipeofst.
Referenced by download(), and map_binfile_zip_setup().
download_planet_size()
static int download_planet_size (struct map_download * download) static
References dbg, LONGLONG_FMT, lvl_debug, map_download::m, map_binfile_download_size(), and map_download::size.
Referenced by download(), and map_binfile_zip_setup().
download_request()
static int download_request (struct map_download * download) static
References attr::attrs, binfile_cd_offset(), map_download::cd_copy, dbg, map_download::dl_size, map_priv::download_enabled, map_download::http, map_priv::http, LONGLONG_FMT, lvl_debug, lvl_error, map_download::m, map_binfile_http_request(), attr::num, offset, map_download::offset, size, attr::str, attr::u, map_priv::url, zip_cd::zipcsiz, and map_download::zipfile.
Referenced by download_download(), and download_start().
download_start()
static int download_start (struct map_download * download) static
References map_download::cd, map_download::cd_copy, map_priv::cde_size, download_cd(), download_request(), map_download::file, file_data_read(), file_data_remove(), file_size(), map_download::m, offset, map_download::offset, map_download::start_offset, map_download::zip_eoc, and zip_cd::zipcensig.
Referenced by download().
duplicate()
static int duplicate (struct map_search_priv * msp, struct item * item, enum attr_type attr_type, enum attr_type attr_type2) static
Check if item is duplicate and update duplicate hash if needed.
Parameters
msp pointer to private map search data
item item to check
attr_type
attr_type2,optional,allows to check for duplicate combinations of 2 attributes
Returns
0 if item is not a duplicate 1 if item is duplicate or doesn't have required attr_type attribute
References duplicate_insert(), and duplicate_test().
Referenced by binmap_search_get_item().
duplicate_equal()
static gboolean duplicate_equal (gconstpointer a, gconstpointer b) static
References duplicate::c, duplicate::str, coord::x, and coord::y.
Referenced by duplicate_test().
duplicate_hash()
static guint duplicate_hash (gconstpointer key) static
References duplicate::c, key, duplicate::str, coord::x, and coord::y.
Referenced by duplicate_test().
duplicate_insert()
static void duplicate_insert (struct map_search_priv * msp, struct duplicate * d) static
Insert struct duplicate item into the duplicate hash.
Parameters
msp pointer to private map search data
duplicate Duplicate info to insert
References map_search_priv::search_results.
Referenced by binmap_search_get_item(), and duplicate().
duplicate_test()
static struct duplicate* duplicate_test (struct map_search_priv * msp, struct item * item, enum attr_type attr_type, enum attr_type attr_type2) static
Test an item if it's duplicate. If it's not a duplicate, return new struct duplicate to be duplicate_insert()'ed.
Parameters
msp pointer to private map search data
item item to check
attr_type
attr_type2,optional,allows to check for duplicate combinations of 2 attributes returns - pointer to new struct duplicate, if this item is not already exist in hash
NULL if this item already exists in duplicate hash or doesnt have an attr_type attr;
References binfile_attr_rewind(), binfile_coord_rewind(), duplicate::c, duplicate_equal(), duplicate_hash(), item_attr_get(), item_coord_get(), item::priv_data, map_search_priv::search_results, attr::str, duplicate::str, attr::u, coord::x, and coord::y.
Referenced by binmap_search_get_item(), and duplicate().
eoc_to_cpu()
static void eoc_to_cpu (struct zip_eoc * eoc) static
References binfile_check_version(), dbg_assert, le16_to_cpu, le32_to_cpu, zip_eoc_sig, zip_eoc::zipecen, zip_eoc::zipecenn, zip_eoc::zipecoml, zip_eoc::zipecsz, zip_eoc::zipedsk, zip_eoc::zipenum, zip_eoc::zipeofst, and zip_eoc::zipesig.
Referenced by binfile_read_eoc().
item_inside_poly_list()
static int item_inside_poly_list (struct item * it, GList * l) static
References binfile_coord_left(), geom_poly_segment::first, geom_poly_point_inside(), item_coord_get(), item_coord_rewind(), geom_poly_segment::last, p, item::priv_data, coord::x, and coord::y.
Referenced by binmap_search_get_item().
lfh_to_cpu()
static void lfh_to_cpu (struct zip_lfh * lfh) static
References dbg_assert, le16_to_cpu, le32_to_cpu, zip_lfh_sig, zip_lfh::zipcrc, zip_lfh::zipdate, zip_lfh::zipfnln, zip_lfh::zipgenfld, zip_lfh::ziplocsig, zip_lfh::zipmthd, zip_lfh::zipsize, zip_lfh::ziptime, zip_lfh::zipuncmp, zip_lfh::zipver, and zip_lfh::zipxtraln.
Referenced by binfile_read_lfh().
load_changes()
static void load_changes (struct map_priv * m) static
References binfile_hash_entry_equal(), binfile_hash_entry_hash(), map_priv::changes, binfile_hash_entry::data, map_priv::filename, le32_to_cpu, and size.
Referenced by map_new_binfile().
map_binfile_close()
static void map_binfile_close (struct map_priv * m) static
References map_priv::cachedir, map_priv::eoc, map_priv::eoc64, map_priv::fi, file_data_free(), file_destroy(), map_priv::fis, map_priv::index_cd, map_priv::map_release, and zip_eoc::zipedsk.
Referenced by binfile_check_version(), and map_destroy_binfile().
map_binfile_destroy()
static void map_binfile_destroy (struct map_priv * m) static
References map_priv::filename, map_priv::progress, and map_priv::url.
Referenced by map_destroy_binfile(), and map_new_binfile().
map_binfile_download_range()
static unsigned char* map_binfile_download_range (struct map_priv * m, long long offset, int size) static
References dbg, file_data_read_special(), lvl_debug, and map_binfile_http_range().
Referenced by download_cd(), download_eoc(), and map_binfile_zip_setup().
map_binfile_download_size()
static long long map_binfile_download_size (struct map_priv * m) static
References attr::attrs, data, dbg, file_data_read_special(), file_size(), map_priv::http, LONGLONG_FMT, lvl_debug, map_binfile_handle_redirect(), map_binfile_http_request(), attr::num, attr::str, attr::u, and map_priv::url.
Referenced by download_planet_size().
map_binfile_handle_redirect()
static int map_binfile_handle_redirect (struct map_priv * m) static
References dbg, file_destroy(), file_http_header(), map_priv::http, lvl_debug, map_priv::redirect, and map_priv::url.
Referenced by download_download(), and map_binfile_download_size().
map_binfile_http_close()
static int map_binfile_http_close (struct map_priv * m) static
References file_destroy(), and map_priv::http.
Referenced by map_rect_destroy_binfile(), and map_rect_new_binfile_int().
map_binfile_http_range()
static struct file* map_binfile_http_range (struct map_priv * m, long long offset, int size) static
References attr::attrs, map_priv::http, LONGLONG_FMT, map_binfile_http_request(), attr::num, attr::str, attr::u, and map_priv::url.
Referenced by download_directory_start(), and map_binfile_download_range().
map_binfile_http_request()
static int map_binfile_http_request (struct map_priv * m, struct attr ** attrs) static
References file_create(), file_request(), and map_priv::http.
Referenced by download_request(), map_binfile_download_size(), and map_binfile_http_range().
map_binfile_open()
static int map_binfile_open (struct map_priv * m) static
References attr::attrs, binfile_attr_get(), busy_item, map_priv::cachedir, map_priv::check_version, dbg, map_priv::fi, file_create(), file_data_free(), file_data_read(), file_destroy(), file_mmap(), file_version(), map_priv::filename, map_priv::flags, item, le32_to_cpu, lvl_debug, lvl_error, map_binfile_zip_setup(), map_rect_destroy_binfile(), map_rect_get_item_binfile(), map_rect_new_binfile(), map_priv::map_release, map_priv::map_version, attr::num, item::priv_data, attr::str, item::type, attr::u, map_priv::update_available, map_priv::url, map_priv::version, zip64_eoc_sig, zip64_eoc_sig_rev, zip_cd_sig, zip_cd_sig_rev, zip_lfh_sig, zip_lfh_sig_rev, zip_split_sig, and zip_split_sig_rev.
Referenced by binfile_check_version(), download(), and map_new_binfile().
map_binfile_zip_setup()
static int map_binfile_zip_setup (struct map_priv * m, char * filename, int mmap) static
References attr::attrs, binfile_cd_extra(), binfile_get_index(), binfile_read_cd(), binfile_read_eoc(), binfile_read_eoc64(), map_priv::cde_size, dbg, dbg_assert, download(), download_directory_do(), download_directory_finish(), download_directory_start(), download_eoc(), download_initial_finish(), download_planet_size(), map_priv::eoc, map_priv::eoc64, map_priv::fi, map_download::file, file_create(), file_data_free(), file_data_write(), file_mmap(), map_priv::filename, map_priv::fis, map_priv::index_offset, lvl_debug, lvl_error, map_download::m, map_binfile_download_range(), tile::mode, zip64_eoc::zip64ecsz, zip64_eoc::zip64eofst, map_priv::zip_members, zip_cd::zipcunc, zip_cd::zipcxtl, zip_eoc::zipecen, and zip_eoc::zipedsk.
Referenced by map_binfile_open().
map_destroy_binfile()
static void map_destroy_binfile (struct map_priv * m) static
References dbg, map_priv::fi, lvl_debug, map_binfile_close(), and map_binfile_destroy().
map_download_selection()
static void map_download_selection (struct map_priv * m, struct map_rect_priv * mr, struct map_selection * sel) static
References binfile_read_cd(), map_priv::cde_size, download(), map_priv::fi, file_data_free(), map_download_selection_check(), and map_priv::zip_members.
Referenced by map_rect_new_binfile().
map_download_selection_check()
static int map_download_selection_check (struct zip_cd * cd, struct map_selection * sel) static
References map_selection::c_rect, coord_rect_overlap(), map_selection::next, tile_bbox(), map_selection::u, zip_cd::zipcfnl, and zip_cd::zipcunc.
Referenced by map_download_selection().
map_new_binfile()
static struct map_priv* map_new_binfile (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), cbl, map_priv::cbl, map_priv::check_version, data, dbg, map_priv::download_enabled, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_new(), map_priv::filename, map_priv::flags, map_priv::id, load_changes(), lvl_debug, map_binfile_destroy(), map_binfile_open(), map_id, map_methods_binfile, attr::num, attr::str, attr::u, and map_priv::url.
Referenced by plugin_init().
map_parse_country_binfile()
static void map_parse_country_binfile (struct map_rect_priv * mr) static
References binfile_attr_get(), map_rect_priv::country_id, dbg, map_rect_priv::item, linguistics_cmp_partial, linguistics_compare(), lvl_debug, map_rect_priv::msp, attr::num, item::priv_data, push_zipfile_tile(), map_search_priv::search, attr::str, attr::type, and attr::u.
Referenced by map_rect_get_item_binfile().
map_parse_submap()
static int map_parse_submap (struct map_rect_priv * mr, int async) static
References binfile_attr_get(), binfile_coord_get(), dbg, map_priv::eoc, map_rect_priv::item, le16_to_cpu, coord_rect::lu, lvl_debug, map_rect_priv::m, range::max, range::min, attr::num, item::priv_data, push_zipfile_tile(), attr::range, coord_rect::rl, map_rect_priv::sel, selection_contains(), map_rect_priv::t, attr::u, coord::x, coord::y, and tile::zipfile_num.
Referenced by map_rect_get_item_binfile().
map_rect_destroy_binfile()
static void map_rect_destroy_binfile (struct map_rect_priv * mr) static
References dbg, tile::fi, file_data_free(), lvl_debug, map_rect_priv::m, map_binfile_http_close(), pop_tile(), tile::start, map_rect_priv::tiles, map_rect_priv::url, and write_changes().
Referenced by binmap_search_destroy(), binmap_search_get_item(), binmap_search_new(), binmap_search_street_by_place(), and map_binfile_open().
map_rect_get_item_binfile()
static struct item* map_rect_get_item_binfile (struct map_rect_priv * mr) static
References binfile_attr_rewind(), binfile_coord_rewind(), busy_item, map_priv::changes, map_rect_priv::country_id, map_priv::download, download(), tile::end, item::id_hi, item::id_lo, map_rect_priv::item, item_is_town, map_rect_priv::m, map_parse_country_binfile(), map_parse_submap(), tile::mode, pop_tile(), tile::pos, tile::pos_next, push_modified_item(), push_zipfile_tile(), setup_pos(), tile::start, map_rect_priv::status, map_rect_priv::t, item::type, map_priv::zip_members, and tile::zipfile_num.
Referenced by binmap_search_get_item(), binmap_search_street_by_place(), and map_binfile_open().
map_rect_get_item_byid_binfile()
static struct item* map_rect_get_item_byid_binfile (struct map_rect_priv * mr, int id_hi, int id_lo) static
References binfile_attr_rewind(), binfile_coord_rewind(), map_priv::changes, map_priv::eoc, item::id_hi, item::id_lo, map_rect_priv::item, map_rect_priv::m, pop_tile(), tile::pos, push_modified_item(), push_zipfile_tile(), setup_pos(), tile::start, and map_rect_priv::t.
Referenced by binmap_search_new().
map_rect_new_binfile()
static struct map_rect_priv* map_rect_new_binfile (struct map_priv * map, struct map_selection * sel) static
References dbg, map_priv::download, download(), tile::end, map_priv::eoc, tile::fi, map_priv::fi, file_data_read(), lvl_debug, map_download_selection(), map_rect_new_binfile_int(), tile::mode, map_selection::order, push_tile(), file::size, tile::start, map_rect_priv::status, map_priv::url, map_priv::zip_members, and tile::zipfile_num.
Referenced by binmap_search_get_item(), binmap_search_housenumber_by_estimate(), binmap_search_new(), binmap_search_street_by_estimate(), binmap_search_street_by_place(), and map_binfile_open().
map_rect_new_binfile_int()
static struct map_rect_priv* map_rect_new_binfile_int (struct map_priv * map, struct map_selection * sel) static
References binfile_check_version(), dbg, map_priv::fi, item::id_hi, item::id_lo, map_rect_priv::item, lvl_debug, map_rect_priv::m, map_binfile_http_close(), item::meth, methods_binfile, item::priv_data, map_rect_priv::sel, and map_priv::url.
Referenced by binmap_search_by_index(), and map_rect_new_binfile().
plugin_init()
void plugin_init (void)
register vehicle_gypsy
Returns
nothing
References dbg, lvl_debug, lvl_error, and map_new_binfile().
pop_tile()
static int pop_tile (struct map_rect_priv * mr) static
References dbg, map_priv::fi, file_data_free(), lvl_debug, map_rect_priv::m, tile::mode, tile::start, map_rect_priv::t, map_rect_priv::tile_depth, map_rect_priv::tiles, and tile::zipfile_num.
Referenced by map_rect_destroy_binfile(), map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
push_modified_item()
static int push_modified_item (struct map_rect_priv * mr) static
References map_priv::changes, binfile_hash_entry::data, tile::end, item::id_hi, item::id_lo, map_rect_priv::item, le32_to_cpu, map_rect_priv::m, tile::mode, tile::pos, tile::pos_next, push_tile(), tile::start, and tile::zipfile_num.
Referenced by map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
push_tile()
static void push_tile (struct map_rect_priv * mr, struct tile * t, int offset, int length) static
References dbg_assert, tile::end, le32_to_cpu, length, offset, tile::pos, tile::pos_next, tile::start, map_rect_priv::t, map_rect_priv::tile_depth, and map_rect_priv::tiles.
Referenced by binfile_attr_set(), binfile_coord_set(), map_rect_new_binfile(), push_modified_item(), and push_zipfile_tile_do().
push_zipfile_tile()
static int push_zipfile_tile (struct map_rect_priv * mr, int zipfile, int offset, int length, int async) static
References cd_to_cpu(), map_priv::cde_size, dbg, download(), map_priv::eoc, map_priv::eoc64, file::f, map_priv::fi, file_data_read(), LONGLONG_FMT, lvl_debug, map_rect_priv::m, push_zipfile_tile_do(), map_priv::url, zip64_eoc::zip64eofst, zip_cd::zipcunc, and zip_eoc::zipeofst.
Referenced by binmap_search_by_index(), map_parse_country_binfile(), map_parse_submap(), map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
push_zipfile_tile_do()
static void push_zipfile_tile_do (struct map_rect_priv * mr, struct zip_cd * cd, int zipfile, int offset, int length) static
References dbg, file::f, map_priv::fi, file_data_free(), filename, lvl_debug, map_rect_priv::m, push_tile(), zip_cd::zipcfnl, zip_cd::zipcunc, tile::zipfile_num, and zipfile_to_tile().
Referenced by download(), and push_zipfile_tile().
selection_contains()
static int selection_contains (struct map_selection * sel, struct coord_rect * r, struct range * mima) static
References map_selection::c_rect, coord_rect_overlap(), dbg, lvl_debug, range::max, max, range::min, map_selection::next, map_selection::order, and map_selection::u.
Referenced by map_parse_submap().
setup_pos()
static void setup_pos (struct map_rect_priv * mr) static
References dbg, map_rect_priv::item, le32_to_cpu, lvl_debug, map_rect_priv::m, tile::pos, map_rect_priv::pos, tile::pos_attr_start, tile::pos_coord_start, tile::pos_next, size, map_rect_priv::t, and item::type.
Referenced by binfile_attr_set(), binfile_coord_set(), map_rect_get_item_binfile(), and map_rect_get_item_byid_binfile().
tile_bbox()
static void tile_bbox (char * tile, int len, struct coord_rect * r) static
References coord_rect::lu, overlap, coord_rect::rl, world_bbox, WORLD_BOUNDINGBOX_MAX_X, WORLD_BOUNDINGBOX_MAX_Y, WORLD_BOUNDINGBOX_MIN_X, WORLD_BOUNDINGBOX_MIN_Y, coord::x, and coord::y.
Referenced by item_bin_write_clipped(), itembin_nicer_slicer(), map_download_selection_check(), ocean_tile(), and tile_collector_process_tile().
write_changes()
static void write_changes (struct map_priv * m) static
References map_priv::changes, map_priv::filename, and write_changes_do().
Referenced by map_rect_destroy_binfile().
write_changes_do()
static void write_changes_do (gpointer key, gpointer value, gpointer user_data) static
References binfile_hash_entry::data, dbg, binfile_hash_entry::flags, key, le32_to_cpu, and lvl_debug.
Referenced by write_changes().
zipfile_to_tile()
static int zipfile_to_tile (struct map_priv * m, struct zip_cd * cd, struct tile * t) static
References binfile_cd_offset(), binfile_read_content(), binfile_read_lfh(), dbg, tile::end, tile::fi, map_priv::fi, file_data_free(), file_data_read(), map_priv::fis, LONGLONG_HEX_FMT, lvl_debug, tile::mode, tile::start, zip_cd::zipdsk, zip_lfh::zipfnln, and zip_lfh::zipuncmp.
Referenced by push_zipfile_tile_do().
Variable Documentation
map_id
int map_id static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by map_new_binfile().
map_methods_binfile
struct map_methods map_methods_binfile static
Initial value:
= {
    projection_mg,
    "utf-8",
    map_destroy_binfile,
    map_rect_new_binfile,
    map_rect_destroy_binfile,
    map_rect_get_item_binfile,
    map_rect_get_item_byid_binfile,
    binmap_search_new,
    binmap_search_destroy,
    binmap_search_get_item,
    NULL,
    binmap_get_attr,
    binmap_set_attr,
}
Referenced by map_new_binfile().
methods_binfile
struct item_methods methods_binfile static
Initial value:
= {
    binfile_coord_rewind,
    binfile_coord_get,
    binfile_attr_rewind,
    binfile_attr_get,
    NULL,
    binfile_attr_set,
    binfile_coord_set,
    NULL,
    binfile_coords_left,
}
Referenced by map_rect_new_binfile_int().