navit: map/mg/block.c File Reference
block.c File Reference
#include <stdio.h>
#include <string.h>
#include "debug.h"
#include "mg.h"
Data Structures
struct block_index_item
struct block_index
Functions
static unsigned int block_index_item_get_blocknum (struct block_index_item *blk)
static unsigned int block_index_item_get_blocks (struct block_index_item *blk)
static unsigned int block_index_get_blocks (struct block_index *blk)
static unsigned int block_index_get_size (struct block_index *blk)
static unsigned int block_index_get_next (struct block_index *blk)
static struct block_index_item * block_index_get_list (struct block_index *blk)
static struct block * block_get (unsigned char **p)
static struct block * block_get_byid (struct file *file, int id, unsigned char **p_ret)
int block_get_byindex (struct file *file, int idx, struct block_priv *blk)
static void block_setup_tags (struct map_rect_priv *mr)
static void block_rect_same (struct coord_rect *r1, struct coord_rect *r2)
int block_init (struct map_rect_priv *mr)
int block_next_lin (struct map_rect_priv *mr)
int block_next (struct map_rect_priv *mr)
Variables
int block_lin_count
int block_idx_count
int block_active_count
int block_mem
int block_active_mem
struct block_index_item __attribute
Function Documentation
static struct block* block_get (unsigned char ** p) static
Referenced by block_get_byid(), and block_next_lin().
static struct block* block_get_byid (struct file * file, int id, unsigned char ** p_ret) static
References file::begin, block_get(), block_index_get_list(), block_index_get_next(), block_index_get_size(), block_index_item_get_blocknum(), block_mem, and max.
Referenced by block_get_byindex(), and block_next().
int block_get_byindex (struct file * file, int idx, struct block_priv * blk)
References block_priv::b, block_get_byid(), block_get_size(), block_priv::block_start, dbg, block_priv::end, lvl_debug, block_priv::p, and block_priv::p_start.
Referenced by poly_get_byid(), street_search_get_item_street_name(), town_get_byid(), and town_search_get_item().
static unsigned int block_index_get_blocks (struct block_index * blk) inline static
References get_u32(), block_index::p, and p.
static struct block_index_item* block_index_get_list (struct block_index * blk) static
References block_index::p.
Referenced by block_get_byid().
static unsigned int block_index_get_next (struct block_index * blk) inline static
References get_u32(), block_index::p, and p.
Referenced by block_get_byid().
static unsigned int block_index_get_size (struct block_index * blk) inline static
References get_u32(), block_index::p, and p.
Referenced by block_get_byid().
static unsigned int block_index_item_get_blocknum (struct block_index_item * blk) inline static
References get_u32(), block_index_item::p, and p.
Referenced by block_get_byid().
static unsigned int block_index_item_get_blocks (struct block_index_item * blk) inline static
References get_u32(), block_index_item::p, and p.
int block_init (struct map_rect_priv * mr)
References block_bt_priv::b, map_rect_priv::b, block_priv::b_rect, block_priv::binarytree, block_bt_priv::block_count, block_next(), block_priv::block_num, block_setup_tags(), block_priv::bt, map_selection::c_rect, coord_rect_overlap(), map_rect_priv::cur_sel, block_bt_priv::next, NULL, block_bt_priv::p, and map_selection::u.
Referenced by file_next(), map_rect_get_item_mg(), and map_search_setup().
int block_next (struct map_rect_priv * mr)
References block_bt_priv::b, block_priv::b, map_rect_priv::b, block_priv::binarytree, block_active_count, block_active_mem, block_bt_priv::block_count, block_get_blocks(), block_get_byid(), block_get_next(), block_get_r(), block_get_size(), block_idx_count, block_mem, block_next_lin(), block_priv::block_num, block_rect_same(), block_priv::block_start, block_priv::bt, BT_STACK_SIZE, map_selection::c_rect, coord_rect_overlap(), map_rect_priv::cur_sel, dbg, dbg_assert, debug, block_bt_priv::end, block_priv::end, map_rect_priv::file, get_u32(), coord_rect::lu, lvl_debug, block_bt_priv::next, NULL, block_bt_priv::order, block_bt_priv::p, block_priv::p, block_priv::p_start, printf(), block_bt_priv::r_curr, coord_rect::rl, block_bt_priv::stack, block_bt_priv::stackp, map_selection::u, coord::x, and coord::y.
Referenced by block_init(), and map_rect_get_item_mg().
int block_next_lin (struct map_rect_priv * mr)
References block_priv::b, map_rect_priv::b, file::begin, block_active_count, block_active_mem, block_get(), block_get_blocks(), block_get_count(), block_get_r(), block_get_size(), block_lin_count, block_mem, block_priv::block_num, block_priv::block_start, map_selection::c_rect, coord_rect_overlap(), map_rect_priv::cur_sel, dbg, file::end, block_priv::end, map_rect_priv::file, lvl_debug, lvl_info, lvl_warning, block_priv::p, block_priv::p_start, and map_selection::u.
Referenced by block_next(), and street_search_get_item_street_name().
static void block_rect_same (struct coord_rect * r1, struct coord_rect * r2) static
References dbg_assert, coord_rect::lu, coord_rect::rl, coord::x, and coord::y.
Referenced by block_next().
static void block_setup_tags (struct map_rect_priv * mr) static
References map_rect_priv::b, block_priv::b_rect, file::begin, block_priv::binarytree, map_rect_priv::file, get_string(), get_u32_unal(), coord_rect::lu, p, coord_rect::rl, coord::x, and coord::y.
Referenced by block_init().
Variable Documentation
struct block_index_item __attribute
int block_active_count
Referenced by block_next(), block_next_lin(), map_rect_get_item_mg(), and map_rect_new_mg().
int block_active_mem
Referenced by block_next(), block_next_lin(), map_rect_get_item_mg(), and map_rect_new_mg().
int block_idx_count
Referenced by block_next(), map_rect_get_item_mg(), and map_rect_new_mg().
int block_lin_count
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by block_next_lin(), map_rect_get_item_mg(), and map_rect_new_mg().
int block_mem
Referenced by block_get_byid(), block_next(), block_next_lin(), map_rect_get_item_mg(), and map_rect_new_mg().