navit: vehicle/webos/bluetooth.c File Reference
bluetooth.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <errno.h>
#include <sys/time.h>
#include <PDL.h>
#include <SDL.h>
#include "debug.h"
#include "callback.h"
#include "event.h"
#include "cJSON.h"
#include "vehicle_webos.h"
#include "bluetooth.h"
Functions
static void vehicle_webos_spp_init_read (struct vehicle_priv *priv, unsigned int length)
static void mlPDL_ServiceCall_callback (struct callback_list *cbl, char *service, char *parameters)
static void mlPDL_ServiceCall (const char *service, const char *parameters)
static void mlPDL_ServiceCallWithCallback_callback (struct callback_list *cbl, char *service, char *parameters, PDL_ServiceCallbackFunc callback, void *user, PDL_bool removeAfterResponse)
static void mlPDL_ServiceCallWithCallback (const char *service, const char *parameters, PDL_ServiceCallbackFunc callback, void *user, PDL_bool removeAfterResponse)
static void vehicle_webos_init_pdl_locationtracking_callback (struct vehicle_priv *priv, struct callback_list *cbl, int param)
static void vehicle_webos_init_pdl_locationtracking (struct vehicle_priv *priv, int param)
static int vehicle_webos_parse_nmea (struct vehicle_priv *priv, char *buffer)
static void vehicle_webos_spp_handle_read (PDL_ServiceParameters *params, void *user)
static void vehicle_webos_spp_handle_open (PDL_ServiceParameters *params, void *user)
static void vehicle_webos_spp_notify (PDL_ServiceParameters *params, void *user)
static void vehicle_webos_init_bt_gps (struct vehicle_priv *priv, char *addr)
static void vehicle_webos_bt_gap_callback (PDL_ServiceParameters *params, void *param)
int vehicle_webos_bt_open (struct vehicle_priv *priv)
void vehicle_webos_bt_close (struct vehicle_priv *priv)
Variables
static int buffer_size = 128
Function Documentation
static void mlPDL_ServiceCall (const char * service, const char * parameters) static
References callback_cast, callback_list_add(), callback_list_new(), callback_new_3, cbl, dbg, event_call_callback(), g_strdup(), lvl_debug, mlPDL_ServiceCall_callback(), and NULL.
Referenced by vehicle_webos_init_bt_gps(), and vehicle_webos_spp_notify().
static void mlPDL_ServiceCall_callback (struct callback_list * cbl, char * service, char * parameters) static
References callback_list_destroy(), dbg, err(), g_free(), lvl_debug, and lvl_error.
Referenced by mlPDL_ServiceCall().
static void mlPDL_ServiceCallWithCallback (const char * service, const char * parameters, PDL_ServiceCallbackFunc callback, void * user, PDL_bool removeAfterResponse) static
References callback_cast, callback_list_add(), callback_list_new(), callback_new_args(), cbl, dbg, event_call_callback(), g_strdup(), lvl_debug, mlPDL_ServiceCallWithCallback_callback(), and NULL.
Referenced by vehicle_webos_init_bt_gps(), vehicle_webos_spp_init_read(), and vehicle_webos_spp_notify().
static void mlPDL_ServiceCallWithCallback_callback (struct callback_list * cbl, char * service, char * parameters, PDL_ServiceCallbackFunc callback, void * user, PDL_bool removeAfterResponse) static
References callback_list_destroy(), dbg, err(), g_free(), lvl_debug, and lvl_error.
Referenced by mlPDL_ServiceCallWithCallback().
void vehicle_webos_bt_close (struct vehicle_priv * priv)
References dbg, g_free(), lvl_debug, NULL, vehicle_priv::spp_address, and vehicle_priv::spp_instance_id.
Referenced by vehicle_webos_close().
static void vehicle_webos_bt_gap_callback (PDL_ServiceParameters * params, void * param) static
References vehicle_priv::address, c, cJSON_Delete(), cJSON_GetArrayItem(), cJSON_GetArraySize(), cJSON_GetObjectItem(), cJSON_Parse(), dbg, vehicle_priv::device, err(), g_free(), g_strdup(), i, lvl_debug, lvl_error, lvl_info, name, NULL, vehicle_priv::status, cJSON::valuestring, and vehicle_webos_init_bt_gps().
Referenced by vehicle_webos_bt_open().
int vehicle_webos_bt_open (struct vehicle_priv * priv)
References dbg, err(), lvl_debug, lvl_error, vehicle_webos_bt_gap_callback(), and vehicle_webos_close().
Referenced by vehicle_webos_open().
static void vehicle_webos_init_bt_gps (struct vehicle_priv * priv, char * addr) static
References dbg, err(), lvl_debug, lvl_error, mlPDL_ServiceCall(), mlPDL_ServiceCallWithCallback(), vehicle_priv::spp_address, vehicle_webos_close(), and vehicle_webos_spp_notify().
Referenced by vehicle_webos_bt_gap_callback().
static void vehicle_webos_init_pdl_locationtracking (struct vehicle_priv * priv, int param) static
References callback_cast, callback_list_add(), callback_list_new(), callback_new_3, cbl, event_call_callback(), NULL, and vehicle_webos_init_pdl_locationtracking_callback().
Referenced by vehicle_webos_spp_notify().
static void vehicle_webos_init_pdl_locationtracking_callback (struct vehicle_priv * priv, struct callback_list * cbl, int param) static
References callback_list_destroy(), dbg, err(), vehicle_priv::gps_type, GPS_TYPE_INT, GPS_TYPE_NONE, lvl_debug, and lvl_error.
Referenced by vehicle_webos_init_pdl_locationtracking().
static int vehicle_webos_parse_nmea (struct vehicle_priv * priv, char * buffer) static
References vehicle_priv::altitude, attr_position_valid_invalid, attr_position_valid_valid, gps_sat::azimuth, buffer, vehicle_priv::cbt, vehicle_priv::current, vehicle_priv::current_count, dbg, vehicle_priv::delta, gps_sat::elevation, event_add_timeout(), vehicle_priv::file_type, file_type_file, vehicle_priv::fix_time, vehicle_priv::fixday, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, g_ascii_strtod(), g_free(), g_strcasecmp(), g_strconcat(), vehicle_priv::geo, vehicle_priv::hdop, i, coord_geo::lat, lat, coord_geo::lng, lvl_debug, lvl_error, lvl_info, vehicle_priv::magnetic_direction, mktime(), vehicle_priv::next, vehicle_priv::next_count, vehicle_priv::nmea_data, vehicle_priv::nmea_data_buf, NULL, p, gps_sat::prn, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, gps_sat::snr, vehicle_priv::speed, sprintf(), vehicle_priv::status, time(), vehicle_priv::time, vehicle_priv::track, vehicle_priv::valid, vehicle_file_disable_watch(), and vehicle_priv::watch.
Referenced by vehicle_webos_spp_handle_read().
static void vehicle_webos_spp_handle_open (PDL_ServiceParameters * params, void * user) static
References vehicle_priv::buffer, buffer_size, dbg, g_malloc(), vehicle_priv::gps_type, GPS_TYPE_BT, lvl_debug, vehicle_priv::spp_instance_id, and vehicle_webos_spp_init_read().
Referenced by vehicle_webos_spp_notify().
static void vehicle_webos_spp_handle_read (PDL_ServiceParameters * params, void * user) static
References vehicle_priv::buffer, vehicle_priv::buffer_pos, buffer_size, dbg, lvl_debug, lvl_error, NULL, size, vehicle_webos_parse_nmea(), and vehicle_webos_spp_init_read().
Referenced by vehicle_webos_spp_init_read().
static void vehicle_webos_spp_init_read (struct vehicle_priv * priv, unsigned int length) static
References dbg, err(), lvl_error, mlPDL_ServiceCallWithCallback(), vehicle_priv::spp_instance_id, vehicle_webos_close(), and vehicle_webos_spp_handle_read().
Referenced by vehicle_webos_spp_handle_open(), and vehicle_webos_spp_handle_read().
static void vehicle_webos_spp_notify (PDL_ServiceParameters * params, void * user) static
References cJSON_Delete(), cJSON_GetArrayItem(), cJSON_GetObjectItem(), cJSON_Parse(), dbg, vehicle_priv::gps_type, GPS_TYPE_NONE, lvl_debug, lvl_error, lvl_info, lvl_warning, mlPDL_ServiceCall(), mlPDL_ServiceCallWithCallback(), service_name, vehicle_priv::spp_instance_id, cJSON::valuestring, vehicle_webos_init_pdl_locationtracking(), and vehicle_webos_spp_handle_open().
Referenced by vehicle_webos_init_bt_gps().
Variable Documentation
int buffer_size = 128 static
Referenced by vehicle_webos_spp_handle_open(), and vehicle_webos_spp_handle_read().