navit: vehicle/webos/bluetooth.h File Reference
bluetooth.h File Reference
#include "cJSON.h"
Functions
int vehicle_webos_bt_open (struct vehicle_priv *priv)
void vehicle_webos_bt_close (struct vehicle_priv *priv)
Function Documentation
vehicle_webos_bt_close()
void vehicle_webos_bt_close (struct vehicle_priv * priv)
References dbg, lvl_debug, vehicle_priv::spp_address, and vehicle_priv::spp_instance_id.
Referenced by vehicle_webos_close().
vehicle_webos_bt_open()
int vehicle_webos_bt_open (struct vehicle_priv * priv)
References dbg, err(), lvl_debug, lvl_error, vehicle_webos_bt_gap_callback(), and vehicle_webos_close().
Referenced by vehicle_webos_open().