navit: bookmarks.h File Reference
bookmarks.h File Reference
Functions
struct bookmarks * bookmarks_new (struct attr *parent, struct attr **attrs, struct transformation *trans)
void bookmarks_destroy (struct bookmarks *this_)
void bookmarks_add_callback (struct bookmarks *this_, struct callback *cb)
int bookmarks_add_bookmark (struct bookmarks *this_, struct pcoord *c, const char *description)
int bookmarks_cut_bookmark (struct bookmarks *this_, const char *label)
int bookmarks_copy_bookmark (struct bookmarks *this_, const char *label)
int bookmarks_paste_bookmark (struct bookmarks *this_)
int bookmarks_rename_bookmark (struct bookmarks *this_, const char *oldName, const char *newName)
int bookmarks_delete_bookmark (struct bookmarks *this_, const char *label)
struct map * bookmarks_get_map (struct bookmarks *this_)
enum projection bookmarks_get_projection (struct bookmarks *this_)
void bookmarks_move_root (struct bookmarks *this_)
void bookmarks_move_up (struct bookmarks *this_)
int bookmarks_move_down (struct bookmarks *this_, const char *name)
struct item * bookmarks_get_item (struct bookmarks *this_)
int bookmarks_get_bookmark_count (struct bookmarks *this_)
void bookmarks_item_rewind (struct bookmarks *this_)
const char * bookmarks_item_cwd (struct bookmarks *this_)
char * bookmarks_get_user_data_directory (gboolean create)
char * bookmarks_get_destination_file (gboolean create)
void bookmarks_set_center_from_file (struct bookmarks *this_, char *file)
char * bookmarks_get_center_file (gboolean create)
void bookmarks_write_center_to_file (struct bookmarks *this_, char *file)
void bookmarks_append_destinations (struct map *former_destination_map, char *file, struct pcoord *c, int count, enum item_type type, const char *description, int limit)
Function Documentation
int bookmarks_add_bookmark (struct bookmarks * this_, struct pcoord * pc, const char * description)
Record the given set of coordinates as a bookmark
Parameters
navit The navit instance
c The coordinate to store
description A label which allows the user to later identify this bookmark
Returns
nothing
References bookmarks::attr_cbl, bookmarks_clear_hash(), bookmarks_emit_dbus_signal(), bookmarks::bookmarks_list, bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), bookmark_item_priv::c, callback_list_call_attr_0, bookmark_item_priv::children, bookmarks::current, g_list_append(), g_list_first(), g_new0, g_strdup(), bookmark_item_priv::label, NULL, bookmark_item_priv::parent, TRUE, bookmark_item_priv::type, pcoord::x, and pcoord::y.
Referenced by NGQProxyBookmarks::AddBookmark(), NGQProxyBookmarks::AddFolder(), button_bookmark(), gui_gtk_add_bookmark_do(), gui_internal_cmd_add_bookmark_do(), gui_internal_cmd_add_bookmark_folder_do(), gui_internal_cmd_replace_bookmarks_from_waypoints(), and popup_set_bookmark().
void bookmarks_add_callback (struct bookmarks * this_, struct callback * cb)
References bookmarks::attr_cbl, and callback_list_add().
Referenced by gui_gtk_bookmarks_init().
void bookmarks_append_destinations (struct map * former_destination_map, char * former_destination_file, struct pcoord * c, int count, enum item_type type, const char * description, int limit)
Append recent destination(s) item to the former destionations map.
Parameters
former_destination_map
former_destination_file
c coordinates of item point(s). Can be set to NULL when navigation is stopped to remove type_former_itinerary and type_former_itinerary_part items from the file.
count number of points in this item. Set to 0 when navigation is stopped.
type type_former_destination, type_former_itinerary and type_former_itinerary_part are meaningful here
description character string used to identify this destination. If NULL, most recent waypoint at these coordinates will be used to get description.
limit Limits the number of entries in the "backlog". Set to 0 for "infinite"
References _, _GList::data, find_destination_in_list(), free_former_destination(), g_list_append(), g_list_foreach(), g_list_free(), g_list_length(), g_list_nth(), g_new, g_new0, g_strdup(), i, map_projection(), NULL, read_former_destination_map_as_list(), transform_from_to(), type, write_former_destinations(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by navit_add_destination_description(), navit_set_destination(), navit_set_destinations(), and navit_vehicle_update_position().
int bookmarks_copy_bookmark (struct bookmarks * this_, const char * label)
References bookmarks_item_rewind(), bookmark_item_priv::c, bookmark_item_priv::children, bookmarks::clipboard, bookmarks::current, _GList::data, data, FALSE, g_free(), g_list_next, g_strdup(), if(), bookmark_item_priv::item, bookmark_item_priv::iter, bookmark_item_priv::label, NULL, TRUE, and bookmark_item_priv::type.
Referenced by bookmarks_cut_bookmark(), NGQProxyBookmarks::Copy(), and gui_internal_cmd_copy_bookmark().
int bookmarks_cut_bookmark (struct bookmarks * this_, const char * label)
References bookmarks_copy_bookmark(), bookmarks_delete_bookmark(), and FALSE.
Referenced by NGQProxyBookmarks::Cut(), and gui_internal_cmd_cut_bookmark().
int bookmarks_delete_bookmark (struct bookmarks * this_, const char * label)
References bookmarks::attr_cbl, bookmarks_clear_hash(), bookmarks_emit_dbus_signal(), bookmarks_item_rewind(), bookmarks::bookmarks_list, bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), bookmark_item_priv::c, callback_list_call_attr_0, bookmark_item_priv::children, bookmarks::current, _GList::data, data, FALSE, g_list_first(), g_list_next, g_list_remove(), if(), bookmark_item_priv::iter, bookmark_item_priv::label, and NULL.
Referenced by bookmarks_cut_bookmark(), NGQProxyBookmarks::Delete(), gui_internal_cmd_delete_bookmark(), gui_internal_cmd_delete_bookmark_folder(), and gui_internal_cmd_replace_bookmarks_from_waypoints().
void bookmarks_destroy (struct bookmarks * this_)
References bookmarks::attr_cbl, bookmarks::bookmark, bookmarks::bookmark_file, bookmarks_clear_hash(), callback_list_destroy(), bookmarks::clipboard, g_free(), map_destroy(), and bookmarks::working_file.
Referenced by navit_destroy().
int bookmarks_get_bookmark_count (struct bookmarks * this_)
References bookmarks_item_rewind(), bookmarks::current, _GList::data, data, g_list_next, if(), bookmark_item_priv::iter, NULL, and bookmark_item_priv::type.
Referenced by gui_internal_cmd_bookmarks(), gui_internal_cmd_load_bookmarks_as_waypoints(), and gui_internal_cmd_replace_bookmarks_from_waypoints().
char* bookmarks_get_center_file (gboolean create)
References g_strjoin(), navit_get_user_data_directory(), and NULL.
Referenced by navit_destroy(), and navit_init().
char* bookmarks_get_destination_file (gboolean create)
Parameters
create create the directory where the file is stored if it does not exist
Returns
The name of the file used to store destinations with its full path. Should be freed using g_free.
References g_strjoin(), navit_get_user_data_directory(), and NULL.
Referenced by navit_add_destination_description(), navit_former_destinations_active(), navit_set_destination(), navit_set_destinations(), navit_vehicle_update_position(), and read_former_destinations_from_file().
struct item* bookmarks_get_item (struct bookmarks * this_)
References bookmarks::current, _GList::data, g_list_next, item::id_hi, item::id_lo, bookmark_item_priv::iter, map_rect_get_item_byid(), bookmarks::mr, and NULL.
Referenced by Backend::get_bookmarks(), NGQProxyBookmarks::getBookmarks(), gui_internal_cmd_bookmarks(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_replace_bookmarks_from_waypoints(), and NGQProxyBookmarks::setPoint().
struct map* bookmarks_get_map (struct bookmarks * this_)
References bookmarks::bookmark.
Referenced by navit_get_attr().
enum projection bookmarks_get_projection (struct bookmarks * this_)
References bookmarks::bookmark, and map_projection().
Referenced by gui_internal_cmd_bookmarks(), and gui_internal_cmd_load_bookmarks_as_waypoints().
char* bookmarks_get_user_data_directory (gboolean create)
const char* bookmarks_item_cwd (struct bookmarks * this_)
References bookmarks::current, and bookmark_item_priv::label.
Referenced by NGQProxyBookmarks::getBookmarks(), and gui_internal_cmd_bookmarks().
void bookmarks_item_rewind (struct bookmarks * this_)
References bookmark_item_priv::children, bookmarks::current, g_list_first(), and bookmark_item_priv::iter.
Referenced by bookmarks_copy_bookmark(), bookmarks_delete_bookmark(), bookmarks_get_bookmark_count(), bookmarks_move_down(), bookmarks_rename_bookmark(), Backend::get_bookmarks(), NGQProxyBookmarks::getBookmarks(), gui_internal_cmd_bookmarks(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_replace_bookmarks_from_waypoints(), and NGQProxyBookmarks::setPoint().
int bookmarks_move_down (struct bookmarks * this_, const char * name)
References bookmarks_item_rewind(), bookmark_item_priv::children, bookmarks::current, _GList::data, data, dbg, g_list_first(), g_list_length(), g_list_next, if(), bookmark_item_priv::iter, bookmark_item_priv::label, lvl_info, and NULL.
Referenced by bookmarks_load_hash(), gui_internal_cmd_bookmarks(), gui_internal_cmd_replace_bookmarks_from_waypoints(), and NGQProxyBookmarks::moveDown().
void bookmarks_move_root (struct bookmarks * this_)
References bookmark_item_priv::children, bookmarks::current, dbg, g_list_first(), g_list_length(), bookmark_item_priv::iter, lvl_info, and bookmarks::root.
Referenced by bookmarks_load_hash(), gui_internal_cmd_bookmarks(), and NGQProxyBookmarks::moveRoot().
void bookmarks_move_up (struct bookmarks * this_)
References bookmark_item_priv::children, bookmarks::current, bookmark_item_priv::iter, and bookmark_item_priv::parent.
Referenced by gui_internal_cmd_bookmarks(), gui_internal_cmd_delete_bookmark_folder(), and NGQProxyBookmarks::moveUp().
struct bookmarks* bookmarks_new (struct attr * parent, struct attr ** attrs, struct transformation * trans)
References bookmarks::attr_cbl, bookmarks::bookmark, bookmarks::bookmark_file, bookmarks_load_hash(), callback_list_new(), bookmarks::clipboard, data, g_new0, g_strjoin(), map_new(), navit_get_user_data_directory(), NULL, bookmarks::parent, bookmarks::trans, trans, TRUE, type, attr::type, and bookmarks::working_file.
Referenced by navit_new().
int bookmarks_paste_bookmark (struct bookmarks * this_)
References bookmarks::attr_cbl, bookmarks_clear_hash(), bookmarks::bookmarks_hash, bookmarks::bookmarks_list, bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), bookmark_item_priv::c, callback_list_call_attr_0, bookmark_item_priv::children, bookmarks::clipboard, bookmarks::current, FALSE, g_hash_table_insert(), g_list_append(), g_list_first(), g_new0, g_strdup(), bookmark_item_priv::item, bookmark_item_priv::label, bookmark_item_priv::parent, bookmark_item_priv::type, pcoord::x, and pcoord::y.
Referenced by gui_internal_cmd_paste_bookmark(), and NGQProxyBookmarks::Paste().
int bookmarks_rename_bookmark (struct bookmarks * this_, const char * oldName, const char * newName)
References bookmarks::attr_cbl, bookmarks_clear_hash(), bookmarks_item_rewind(), bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), callback_list_call_attr_0, bookmark_item_priv::children, bookmarks::current, _GList::data, data, FALSE, g_free(), g_list_next, g_strdup(), if(), bookmark_item_priv::iter, bookmark_item_priv::label, and NULL.
Referenced by gui_internal_cmd_rename_bookmark_clicked().
void bookmarks_set_center_from_file (struct bookmarks * this_, char * file)
References center, coord_parse(), g_strchomp(), NULL, bookmarks::trans, transform_center(), and transform_get_projection().
Referenced by navit_init().
void bookmarks_write_center_to_file (struct bookmarks * this_, char * file)
References center, coord_print(), perror(), bookmarks::trans, transform_center(), and transform_get_projection().
Referenced by navit_destroy().