navit: maptool/boundaries.c File Reference
boundaries.c File Reference
#include <stdio.h>
#include <string.h>
#include "maptool.h"
Functions
char * osm_tag_value (struct item_bin *ib, char *key)
osmid boundary_relid (struct boundary *b)
static void process_boundaries_member (void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv)
static GList * process_boundaries_setup (FILE *boundaries, struct relations *relations)
GList * boundary_find_matches (GList *l, struct coord *c)
static GList * process_boundaries_insert (GList *list, struct boundary *boundary)
static GList * process_boundaries_finish (GList *boundaries_list)
GList * process_boundaries (FILE *boundaries, FILE *ways)
void free_boundaries (GList *bl)
Function Documentation
GList* boundary_find_matches (GList * l, struct coord * c)
References bbox_contains_coord(), boundary_find_matches(), boundary::children, _GList::data, g_list_concat(), g_list_next, g_list_prepend(), geom_poly_segments_point_inside(), NULL, boundary::r, and boundary::sorted_segments.
Referenced by boundary_find_matches(), and osm_process_town_by_boundary().
osmid boundary_relid (struct boundary * b)
References boundary::ib, item_bin_get_attr(), and NULL.
void free_boundaries (GList * bl)
References boundary::children, _GList::data, geom_poly_segment::first, free_boundaries(), g_free(), g_list_free(), g_list_next, boundary::ib, boundary::iso2, boundary::segments, and boundary::sorted_segments.
Referenced by free_boundaries(), and osm_process_towns().
char* osm_tag_value (struct item_bin * ib, char * key)
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References item_bin_get_attr(), and NULL.
Referenced by osm_process_town_by_boundary_update_attrs(), osm_town_relations_to_poly(), process_associated_streets_setup(), and process_boundaries_setup().
GList* process_boundaries (FILE * boundaries, FILE * ways)
References NULL, process_boundaries_finish(), process_boundaries_setup(), relations_destroy(), relations_new(), and relations_process().
Referenced by osm_process_towns().
static GList* process_boundaries_finish (GList * boundaries_list) static
References bbox_contains_bbox(), bbox_extend(), c, boundary::children, coord_is_equal, boundary::country, _GList::data, geom_poly_segment::first, g_free(), g_list_append(), g_list_next, g_list_remove(), g_list_sort(), g_strdup_printf(), geom_poly_segment_type_way_right_side, geom_poly_segments_sort(), rect::h, boundary::ib, boundary::iso2, item_bin_add_coord(), item_bin_get_relationid(), item_bin_init(), item_bin_write(), geom_poly_segment::last, name, NULL, osm_warning(), printf(), process_boundaries_insert(), boundary::r, boundary::segments, boundary::sorted_segments, tempfile(), test(), and tmp_item_bin.
Referenced by process_boundaries().
static GList* process_boundaries_insert (GList * list, struct boundary * boundary) static
References bbox_contains_bbox(), boundary::children, _GList::data, g_list_next, g_list_prepend(), g_list_remove(), and boundary::r.
Referenced by process_boundaries_finish().
static void process_boundaries_member (void * func_priv, void * relation_priv, struct item_bin * member, void * member_priv) static
References dup(), g_list_prepend(), item_bin_get_attr(), item_bin_to_poly_segment(), long, NULL, and boundary::segments.
Referenced by process_boundaries_setup().
static GList* process_boundaries_setup (FILE * boundaries, struct relations * relations) static
References boundary::admin_centre, country, boundary::country, country_from_iso2(), g_free(), g_list_append(), g_new0, g_strdup(), geom_poly_segment_type_none, geom_poly_segment_type_way_inner, geom_poly_segment_type_way_outer, geom_poly_segment_type_way_unknown, boundary::ib, boundary::iso2, item_bin_dup(), item_bin_get_attr(), item_bin_get_relationid(), NULL, osm_info(), osm_tag_value(), osm_warning(), process_boundaries_member(), processed_relations, read(), read_item(), rel_member_node, rel_member_relation, rel_member_way, RELATION_MEMBER_PARSE_FORMAT, relations_add_relation_member_entry(), and relations_func_new().
Referenced by process_boundaries().