navit: maptool/buffer.c File Reference
buffer.c File Reference
#include "navit_lfs.h"
#include <stdlib.h>
#include "maptool.h"
#include "debug.h"
Functions
void save_buffer (char *filename, struct buffer *b, long long offset)
Saves a buffer to a file.
int load_buffer (char *filename, struct buffer *b, long long offset, long long size)
Loads a buffer from a file.
long long sizeof_buffer (char *filename)
Determines size of buffer for file.
Function Documentation
load_buffer()
int load_buffer (char * filename, struct buffer * b, long long offset, long long size)
Loads a buffer from a file.
This function loads a buffer from a file.
Parameters
filename The name of the while to where the buffer is loaded from.
b Buffer in which file is loaded.
offset
Returns
indicator if operation suceeded
References buffer::base, dbg, dbg_assert, filename, lvl_warning, buffer::malloced, offset, size, and buffer::size.
Referenced by maptool_load_node_table(), osm_count_references(), and osm_resolve_coords_and_split_at_intersections().
save_buffer()
void save_buffer (char * filename, struct buffer * b, long long offset)
Saves a buffer to a file.
This function saves a buffer to a file.
Parameters
filename The name of the while to where the buffer is saved to.
b Buffer which is saved to file.
offset
References buffer::base, dbg_assert, filename, offset, and buffer::size.
Referenced by flush_nodes(), and osm_count_references().
sizeof_buffer()
long long sizeof_buffer (char * filename)
Determines size of buffer for file.
This function determines the size of the buffer required to read a file.
Parameters
filename Name of file for which the required size of the buffer is determined
Returns
required size of buffer
References filename.
Referenced by maptool_load_node_table().