navit: cache.c File Reference
cache.c File Reference
#include "glib_slice.h"
#include <string.h>
#include "debug.h"
#include "cache.h"
Data Structures
struct cache_entry
struct cache_entry_list
struct cache
Functions
static void cache_entry_dump (struct cache *cache, struct cache_entry *entry)
static void cache_list_dump (char *str, struct cache *cache, struct cache_entry_list *list)
static guint cache_hash4 (gconstpointer key)
static guint cache_hash20 (gconstpointer key)
static gboolean cache_equal4 (gconstpointer a, gconstpointer b)
static gboolean cache_equal20 (gconstpointer a, gconstpointer b)
struct cache * cache_new (int id_size, int size)
void cache_resize (struct cache *cache, int size)
static void cache_insert_mru (struct cache *cache, struct cache_entry_list *list, struct cache_entry *entry)
static void cache_remove_from_list (struct cache_entry_list *list, struct cache_entry *entry)
static void cache_remove (struct cache *cache, struct cache_entry *entry)
static struct cache_entry * cache_remove_lru_helper (struct cache_entry_list *list)
static struct cache_entry * cache_remove_lru (struct cache *cache, struct cache_entry_list *list)
void * cache_entry_new (struct cache *cache, void *id, int size)
void cache_entry_destroy (struct cache *cache, void *data)
static struct cache_entry * cache_trim (struct cache *cache, struct cache_entry *entry)
static struct cache_entry * cache_move (struct cache *cache, struct cache_entry_list *old, struct cache_entry_list *new)
static int cache_replace (struct cache *cache)
void cache_flush (struct cache *cache, void *id)
void cache_flush_data (struct cache *cache, void *data)
void * cache_lookup (struct cache *cache, void *id)
void cache_insert (struct cache *cache, void *data)
void * cache_insert_new (struct cache *cache, void *id, int size)
static void cache_stats (struct cache *cache)
void cache_dump (struct cache *cache)
Function Documentation
cache_dump()
void cache_dump (struct cache * cache)
References cache_list_dump(), cache_stats(), dbg, and lvl_debug.
Referenced by cache_replace().
cache_entry_destroy()
void cache_entry_destroy (struct cache * cache, void * data)
References data, dbg, cache::entry_size, cache_entry::id, lvl_debug, and cache_entry::usage.
Referenced by file_data_free().
cache_entry_dump()
static void cache_entry_dump (struct cache * cache, struct cache_entry * entry) static
References dbg, cache_entry::id, cache::id_size, lvl_debug, cache_entry::size, size, and cache_entry::usage.
Referenced by cache_list_dump().
cache_entry_new()
void * cache_entry_new (struct cache * cache, void * id, int size)
References cache::entry_size, cache_entry::id, cache::id_size, cache::misses, cache_entry::size, size, and cache_entry::usage.
Referenced by cache_insert_new().
cache_equal20()
static gboolean cache_equal20 (gconstpointer a, gconstpointer b) static
Referenced by cache_new().
cache_equal4()
static gboolean cache_equal4 (gconstpointer a, gconstpointer b) static
Referenced by cache_new().
cache_flush()
void cache_flush (struct cache * cache, void * id)
References cache_remove(), cache_remove_from_list(), cache::hash, and cache_entry::where.
Referenced by file_data_flush().
cache_flush_data()
void cache_flush_data (struct cache * cache, void * data)
References cache_remove(), cache_remove_from_list(), data, cache::entry_size, and cache_entry::where.
Referenced by file_data_remove().
cache_hash20()
static guint cache_hash20 (gconstpointer key) static
References key.
Referenced by cache_new().
cache_hash4()
static guint cache_hash4 (gconstpointer key) static
References key.
Referenced by cache_new().
cache_insert()
void cache_insert (struct cache * cache, void * data)
References cache_insert_mru(), cache_remove_lru(), cache_replace(), data, dbg, cache::entry_size, cache_entry::id, cache::insert, lvl_debug, and cache::size.
Referenced by cache_insert_new().
cache_insert_mru()
static void cache_insert_mru (struct cache * cache, struct cache_entry_list * list, struct cache_entry * entry) static
References cache_entry_list::first, cache::hash, cache_entry::id, cache_entry_list::last, cache_entry::next, cache_entry::prev, cache_entry::size, cache_entry_list::size, and cache_entry::where.
Referenced by cache_insert(), cache_lookup(), cache_move(), and cache_remove_lru().
cache_insert_new()
void * cache_insert_new (struct cache * cache, void * id, int size)
References cache_entry_new(), cache_insert(), data, and size.
Referenced by file_data_read(), and file_data_read_compressed().
cache_list_dump()
static void cache_list_dump (char * str, struct cache * cache, struct cache_entry_list * list) static
References cache_entry_dump(), dbg, cache_entry_list::first, lvl_debug, cache_entry::next, and cache_entry_list::size.
Referenced by cache_dump().
cache_lookup()
void * cache_lookup (struct cache * cache, void * id)
References cache_insert_mru(), cache_remove(), cache_remove_from_list(), cache_replace(), dbg, cache::hash, cache::hits, cache_entry::id, cache::id_size, cache::insert, lvl_debug, lvl_error, cache_entry::size, cache::size, cache::t1_target, cache_entry::usage, and cache_entry::where.
Referenced by file_data_read(), and file_data_read_compressed().
cache_move()
static struct cache_entry * cache_move (struct cache * cache, struct cache_entry_list * old, struct cache_entry_list * new) static
References cache_insert_mru(), cache_remove_lru(), and cache_trim().
Referenced by cache_replace().
cache_new()
struct cache * cache_new (int id_size, int size)
References cache_equal20(), cache_equal4(), cache_hash20(), cache_hash4(), dbg, cache::entry_size, cache::hash, cache::id_size, lvl_error, cache::size, and size.
Referenced by file_init().
cache_remove()
static void cache_remove (struct cache * cache, struct cache_entry * entry) static
References dbg, cache::hash, cache_entry::id, lvl_debug, and cache_entry::size.
Referenced by cache_flush(), cache_flush_data(), cache_lookup(), and cache_remove_lru().
cache_remove_from_list()
static void cache_remove_from_list (struct cache_entry_list * list, struct cache_entry * entry) static
References cache_entry_list::first, cache_entry_list::last, cache_entry::next, cache_entry::prev, cache_entry::size, and cache_entry_list::size.
Referenced by cache_flush(), cache_flush_data(), and cache_lookup().
cache_remove_lru()
static struct cache_entry * cache_remove_lru (struct cache * cache, struct cache_entry_list * list) static
References cache_insert_mru(), cache_remove(), cache_remove_lru_helper(), dbg, cache_entry::id, cache_entry_list::last, lvl_debug, cache_entry::size, cache_entry_list::size, size, and cache_entry::usage.
Referenced by cache_insert(), and cache_move().
cache_remove_lru_helper()
static struct cache_entry * cache_remove_lru_helper (struct cache_entry_list * list) static
References cache_entry_list::first, cache_entry_list::last, cache_entry::next, cache_entry::prev, cache_entry::size, and cache_entry_list::size.
Referenced by cache_remove_lru().
cache_replace()
static int cache_replace (struct cache * cache) static
References cache_dump(), cache_move(), dbg, exit, lvl_debug, cache::size, and cache::t1_target.
Referenced by cache_insert(), and cache_lookup().
cache_resize()
void cache_resize (struct cache * cache, int size)
References cache::size, and size.
Referenced by file_set_cache_size().
cache_stats()
static void cache_stats (struct cache * cache) static
References dbg, cache::entry_size, cache::hits, cache::id_size, lvl_debug, cache::misses, cache::size, and cache::t1_target.
Referenced by cache_dump().
cache_trim()
static struct cache_entry * cache_trim (struct cache * cache, struct cache_entry * entry) static
References dbg, cache::entry_size, cache::hash, cache_entry::id, lvl_debug, cache_entry::size, and cache::size.
Referenced by cache_move().