navit: cache.h File Reference
cache.h File Reference
Functions
struct cache * cache_new (int id_size, int size)
void cache_resize (struct cache *cache, int size)
void * cache_entry_new (struct cache *cache, void *id, int size)
void cache_entry_destroy (struct cache *cache, void *data)
void * cache_lookup (struct cache *cache, void *id)
void cache_insert (struct cache *cache, void *data)
void * cache_insert_new (struct cache *cache, void *id, int size)
void cache_flush (struct cache *cache, void *id)
void cache_dump (struct cache *cache)
void cache_flush_data (struct cache *cache, void *data)
Function Documentation
cache_dump()
void cache_dump (struct cache * cache)
References cache_list_dump(), cache_stats(), dbg, and lvl_debug.
Referenced by cache_replace().
cache_entry_destroy()
void cache_entry_destroy (struct cache * cache, void * data)
References data, dbg, cache::entry_size, cache_entry::id, lvl_debug, and cache_entry::usage.
Referenced by file_data_free().
cache_entry_new()
void* cache_entry_new (struct cache * cache, void * id, int size)
References cache::entry_size, cache_entry::id, cache::id_size, cache::misses, cache_entry::size, size, and cache_entry::usage.
Referenced by cache_insert_new().
cache_flush()
void cache_flush (struct cache * cache, void * id)
References cache_remove(), cache_remove_from_list(), cache::hash, and cache_entry::where.
Referenced by file_data_flush().
cache_flush_data()
void cache_flush_data (struct cache * cache, void * data)
References cache_remove(), cache_remove_from_list(), data, cache::entry_size, and cache_entry::where.
Referenced by file_data_remove().
cache_insert()
void cache_insert (struct cache * cache, void * data)
References cache_insert_mru(), cache_remove_lru(), cache_replace(), data, dbg, cache::entry_size, cache_entry::id, cache::insert, lvl_debug, and cache::size.
Referenced by cache_insert_new().
cache_insert_new()
void* cache_insert_new (struct cache * cache, void * id, int size)
References cache_entry_new(), cache_insert(), data, and size.
Referenced by file_data_read(), and file_data_read_compressed().
cache_lookup()
void* cache_lookup (struct cache * cache, void * id)
References cache_insert_mru(), cache_remove(), cache_remove_from_list(), cache_replace(), dbg, cache::hash, cache::hits, cache_entry::id, cache::id_size, cache::insert, lvl_debug, lvl_error, cache_entry::size, cache::size, cache::t1_target, cache_entry::usage, and cache_entry::where.
Referenced by file_data_read(), and file_data_read_compressed().
cache_new()
struct cache* cache_new (int id_size, int size)
References cache_equal20(), cache_equal4(), cache_hash20(), cache_hash4(), dbg, cache::entry_size, cache::hash, cache::id_size, lvl_error, cache::size, and size.
Referenced by file_init().
cache_resize()
void cache_resize (struct cache * cache, int size)
References cache::size, and size.
Referenced by file_set_cache_size().