navit: support/libc/calloc.c File Reference
calloc.c File Reference
Functions
void * calloc (int nelem, int size)
Function Documentation
void* calloc (int nelem, int size)
Referenced by _nl_find_msg(), add_def(), allocate(), DBFCreateLL(), DBFOpenLL(), DBFReorderFields(), file_read(), g2n_conv_load(), gmap_rect_new(), if(), ReadVoiceFile(), SHPAllocBuffer(), SHPOpenDiskTree(), SHPOpenLL(), SHPSearchDiskTreeEx(), SHPSetFastModeReadObject(), smc_tree_insert(), standard_calloc(), and zcalloc().