navit: callback.c File Reference
callback.c File Reference
#include <glib.h>
#include <string.h>
#include "item.h"
#include "debug.h"
#include "callback.h"
Data Structures
struct callback
struct callback_list
Functions
struct callback_list * callback_list_new (void)
struct callback * callback_new_attr (void(*func)(void), enum attr_type type, int pcount, void **p)
struct callback * callback_new_attr_args (void(*func)(void), enum attr_type type, int count,...)
struct callback * callback_new (void(*func)(void), int pcount, void **p)
struct callback * callback_new_args (void(*func)(void), int count,...)
void callback_destroy (struct callback *cb)
void callback_set_arg (struct callback *cb, int arg, void *p)
void callback_list_add (struct callback_list *l, struct callback *cb)
struct callback * callback_list_add_new (struct callback_list *l, void(*func)(void), int pcount, void **p)
void callback_list_remove (struct callback_list *l, struct callback *cb)
void callback_list_remove_destroy (struct callback_list *l, struct callback *cb)
void callback_list_add_patch_function (struct callback_list *l, callback_patch patch, void *context)
void callback_call (struct callback *cb, int pcount, void **p)
void callback_call_args (struct callback *cb, int count,...)
void callback_list_call_attr (struct callback_list *l, enum attr_type type, int pcount, void **p)
void callback_list_call_attr_args (struct callback_list *cbl, enum attr_type type, int count,...)
void callback_list_call (struct callback_list *l, int pcount, void **p)
void callback_list_call_args (struct callback_list *cbl, int count,...)
void callback_list_destroy (struct callback_list *l)
Function Documentation
callback_call()
void callback_call (struct callback * cb, int pcount, void ** p)
References dbg, dbg_assert, callback::func, lvl_debug, lvl_error, callback::p, p, and callback::pcount.
Referenced by callback_call_args(), and callback_list_call_attr().
callback_call_args()
void callback_call_args (struct callback * cb, int count, ...)
References callback_call(), and p.
callback_destroy()
void callback_destroy (struct callback * cb)
Referenced by android_search_end(), command_saved_callbacks_changed(), do_draw(), event_sdl_main_loop_run(), graphics_opengl_x11_destroy(), graphics_sdl_idle(), gui_internal_menu_destroy(), gui_internal_search_idle_end(), log_destroy(), navigation_update_done(), navit_destroy(), navit_window_roadbook_destroy(), request_callback_destroy_do(), route_graph_build_done(), route_graph_update(), script_destroy(), traffic_loop(), traffic_process_messages(), traffic_process_messages_int(), vehicle_demo_destroy(), vehicle_destroy(), vehicle_file_close(), vehicle_file_destroy(), vehicle_gpsd_close(), and vehicle_set_cursor().
callback_list_add()
void callback_list_add (struct callback_list * l, struct callback * cb)
References callback_list::list.
Referenced by bookmarks_add_callback(), callback_list_add_new(), command_add_table(), graphics_add_callback(), graphics_svg_debug_new(), gui_internal_add_callback(), map_add_callback(), navigation_register_callback(), navit_add_callback(), navit_object_add_attr(), route_add_attr(), tracking_add_attr(), vehicle_add_attr(), vehicle_add_log(), and vehicle_wince_new().
callback_list_add_new()
struct callback * callback_list_add_new (struct callback_list * l, void(*)(void) func, int pcount, void ** p)
References callback_list_add(), callback_new(), callback::func, p, and callback::pcount.
callback_list_add_patch_function()
void callback_list_add_patch_function (struct callback_list * l, callback_patch patch, void * context)
References callback_list::patch, and callback_list::patch_context.
Referenced by graphics_new().
callback_list_call()
void callback_list_call (struct callback_list * l, int pcount, void ** p)
References callback_list_call_attr(), p, and callback::pcount.
Referenced by callback_list_call_args(), and navigation_call_callbacks().
callback_list_call_args()
void callback_list_call_args (struct callback_list * cbl, int count, ...)
References callback_list_call(), cbl, and p.
callback_list_call_attr()
void callback_list_call_attr (struct callback_list * l, enum attr_type type, int pcount, void ** p)
References callback_call(), callback_list::list, p, callback_list::patch, callback_list::patch_context, callback::pcount, callback::type, and type.
Referenced by callback_list_call(), and callback_list_call_attr_args().
callback_list_call_attr_args()
void callback_list_call_attr_args (struct callback_list * cbl, enum attr_type type, int count, ...)
References callback_list_call_attr(), cbl, p, and type.
callback_list_destroy()
void callback_list_destroy (struct callback_list * l)
References callback_list::list.
Referenced by bookmarks_destroy(), map_destroy(), navigation_destroy(), tracking_destroy(), vehicle_destroy(), and vehicle_new().
callback_list_new()
struct callback_list * callback_list_new (void)
Referenced by bookmarks_new(), graphics_new(), gui_internal_new(), gui_new(), gui_qml_new(), gui_qt5_qml_new(), main_init(), map_new(), navigation_new(), navit_new(), navit_object_add_attr(), osd_new(), route_dup(), route_new(), tracking_new(), vehicle_new(), and vehicle_wince_new().
callback_list_remove()
void callback_list_remove (struct callback_list * l, struct callback * cb)
References callback_list::list.
Referenced by callback_list_remove_destroy(), graphics_remove_callback(), gui_internal_remove_callback(), map_remove_callback(), navigation_unregister_callback(), navit_object_remove_attr(), navit_remove_callback(), route_remove_attr(), tracking_remove_attr(), and vehicle_remove_attr().
callback_list_remove_destroy()
void callback_list_remove_destroy (struct callback_list * l, struct callback * cb)
References callback_list_remove().
callback_new()
struct callback * callback_new (void(*)(void) func, int pcount, void ** p)
References callback_new_attr(), callback::func, p, and callback::pcount.
Referenced by callback_list_add_new(), callback_new_args(), and disable_suspend().
callback_new_args()
struct callback * callback_new_args (void(*)(void) func, int count, ...)
References callback_new(), callback::func, and p.
callback_new_attr()
struct callback * callback_new_attr (void(*)(void) func, enum attr_type type, int pcount, void ** p)
References callback::func, callback::p, p, callback::pcount, callback::type, and type.
Referenced by callback_new(), and callback_new_attr_args().
callback_new_attr_args()
struct callback * callback_new_attr_args (void(*)(void) func, enum attr_type type, int count, ...)
References callback_new_attr(), callback::func, p, and type.
callback_set_arg()
void callback_set_arg (struct callback * cb, int arg, void * p)
References callback::p, p, and callback::pcount.