navit: gui/win32/ceglue.h File Reference
ceglue.h File Reference
Functions
void InitCeGlue (void)
int CeEnableBacklight (int enable)
Variables
BOOL(* SHFullScreenPtr)(HWND hwnd, DWORD state)
Function Documentation
int CeEnableBacklight (int enable)
References _VIDEO_POWER_MANAGEMENT::DPMSVersion, FALSE, L, _VIDEO_POWER_MANAGEMENT::Length, NULL, _VIDEO_POWER_MANAGEMENT::PowerState, QUERYESCSUPPORT, SETPOWERMANAGEMENT, TRUE, VideoPowerOff, and VideoPowerOn.
void InitCeGlue (void)
References BOOL(), NULL, and SHFullScreenPtr.
Referenced by win32_gui_new().
Variable Documentation
BOOL(* SHFullScreenPtr)(HWND hwnd, DWORD state)
Referenced by InitCeGlue().