navit: gui/win32/ceglue.c File Reference
ceglue.c File Reference
#include <windows.h>
#include "ceglue.h"
Data Structures
struct _VIDEO_POWER_MANAGEMENT
Macros
#define QUERYESCSUPPORT 8
#define GETVFRAMEPHYSICAL 6144
#define GETVFRAMELEN 6145
#define DBGDRIVERSTAT 6146
#define SETPOWERMANAGEMENT 6147
#define GETPOWERMANAGEMENT 6148
Typedefs
typedef enum _VIDEO_POWER_STATE VIDEO_POWER_STATE
typedef enum _VIDEO_POWER_STATE * PVIDEO_POWER_STATE
typedef struct
_VIDEO_POWER_MANAGEMENT VIDEO_POWER_MANAGEMENT
typedef struct
_VIDEO_POWER_MANAGEMENT * PVIDEO_POWER_MANAGEMENT
Enumerations
enum _VIDEO_POWER_STATE { VideoPowerOn = 1, VideoPowerStandBy, VideoPowerSuspend, VideoPowerOff }
Functions
void InitCeGlue (void)
int CeEnableBacklight (int enable)
Variables
BOOL FAR(* SHFullScreenPtr)(HWND hwnd, DWORD state) = NULL
Macro Definition Documentation
#define DBGDRIVERSTAT 6146
#define GETPOWERMANAGEMENT 6148
#define GETVFRAMELEN 6145
#define GETVFRAMEPHYSICAL 6144
#define QUERYESCSUPPORT 8
Referenced by CeEnableBacklight().
#define SETPOWERMANAGEMENT 6147
Referenced by CeEnableBacklight().
Typedef Documentation
typedef struct _VIDEO_POWER_MANAGEMENT * PVIDEO_POWER_MANAGEMENT
typedef enum _VIDEO_POWER_STATE * PVIDEO_POWER_STATE
typedef struct _VIDEO_POWER_MANAGEMENT VIDEO_POWER_MANAGEMENT
typedef enum _VIDEO_POWER_STATE VIDEO_POWER_STATE
Enumeration Type Documentation
enum _VIDEO_POWER_STATE
Enumerator
VideoPowerOn
VideoPowerStandBy
VideoPowerSuspend
VideoPowerOff
Function Documentation
int CeEnableBacklight (int enable)
References _VIDEO_POWER_MANAGEMENT::DPMSVersion, FALSE, L, _VIDEO_POWER_MANAGEMENT::Length, NULL, _VIDEO_POWER_MANAGEMENT::PowerState, QUERYESCSUPPORT, SETPOWERMANAGEMENT, TRUE, VideoPowerOff, and VideoPowerOn.
void InitCeGlue (void)
References BOOL(), NULL, and SHFullScreenPtr.
Referenced by win32_gui_new().
Variable Documentation
BOOL FAR(* SHFullScreenPtr)(HWND hwnd, DWORD state) = NULL
Referenced by InitCeGlue().