navit: support/libc/chsize.c File Reference
chsize.c File Reference
#include <windows.h>
Macros
#define WIN32_LEAN_AND_MEAN
Functions
int _chsize (int fd, long size)
int chsize (int fd, long size)
Macro Definition Documentation
#define WIN32_LEAN_AND_MEAN
Function Documentation
int _chsize (int fd, long size)
References BOOL(), and NULL.
Referenced by chsize().
int chsize (int fd, long size)
References _chsize().