navit: vehicle/webos/cJSON.c File Reference
cJSON.c File Reference
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <float.h>
#include <limits.h>
#include <ctype.h>
#include "cJSON.h"
Functions
const char * cJSON_GetErrorPtr ()
static int cJSON_strcasecmp (const char *s1, const char *s2)
static char * cJSON_strdup (const char *str)
void cJSON_InitHooks (cJSON_Hooks *hooks)
static cJSON * cJSON_New_Item (void)
void cJSON_Delete (cJSON *c)
static const char * parse_number (cJSON *item, const char *num)
static char * print_number (cJSON *item)
static const char * parse_string (cJSON *item, const char *str)
static char * print_string_ptr (const char *str)
static char * print_string (cJSON *item)
static const char * parse_value (cJSON *item, const char *value)
static char * print_value (cJSON *item, int depth, int fmt)
static const char * parse_array (cJSON *item, const char *value)
static char * print_array (cJSON *item, int depth, int fmt)
static const char * parse_object (cJSON *item, const char *value)
static char * print_object (cJSON *item, int depth, int fmt)
static const char * skip (const char *in)
cJSON * cJSON_Parse (const char *value)
char * cJSON_Print (cJSON *item)
char * cJSON_PrintUnformatted (cJSON *item)
int cJSON_GetArraySize (cJSON *array)
cJSON * cJSON_GetArrayItem (cJSON *array, int item)
cJSON * cJSON_GetObjectItem (cJSON *object, const char *string)
static void suffix_object (cJSON *prev, cJSON *item)
static cJSON * create_reference (cJSON *item)
void cJSON_AddItemToArray (cJSON *array, cJSON *item)
void cJSON_AddItemToObject (cJSON *object, const char *string, cJSON *item)
void cJSON_AddItemReferenceToArray (cJSON *array, cJSON *item)
void cJSON_AddItemReferenceToObject (cJSON *object, const char *string, cJSON *item)
cJSON * cJSON_DetachItemFromArray (cJSON *array, int which)
void cJSON_DeleteItemFromArray (cJSON *array, int which)
cJSON * cJSON_DetachItemFromObject (cJSON *object, const char *string)
void cJSON_DeleteItemFromObject (cJSON *object, const char *string)
void cJSON_ReplaceItemInArray (cJSON *array, int which, cJSON *newitem)
void cJSON_ReplaceItemInObject (cJSON *object, const char *string, cJSON *newitem)
cJSON * cJSON_CreateNull ()
cJSON * cJSON_CreateTrue ()
cJSON * cJSON_CreateFalse ()
cJSON * cJSON_CreateBool (int b)
cJSON * cJSON_CreateNumber (double num)
cJSON * cJSON_CreateString (const char *string)
cJSON * cJSON_CreateArray ()
cJSON * cJSON_CreateObject ()
cJSON * cJSON_CreateIntArray (int *numbers, int count)
cJSON * cJSON_CreateFloatArray (float *numbers, int count)
cJSON * cJSON_CreateDoubleArray (double *numbers, int count)
cJSON * cJSON_CreateStringArray (const char **strings, int count)
Variables
static const char * ep
static void *(* cJSON_malloc)(size_t sz) = malloc
static void(* cJSON_free)(void *ptr) = free
static const unsigned char firstByteMark [7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC }
Function Documentation
cJSON_AddItemReferenceToArray()
void cJSON_AddItemReferenceToArray (cJSON * array, cJSON * item)
References cJSON_AddItemToArray(), and create_reference().
cJSON_AddItemReferenceToObject()
void cJSON_AddItemReferenceToObject (cJSON * object, const char * string, cJSON * item)
References cJSON_AddItemToObject(), and create_reference().
cJSON_AddItemToArray()
void cJSON_AddItemToArray (cJSON * array, cJSON * item)
References c, cJSON::child, item, cJSON::next, and suffix_object().
Referenced by cJSON_AddItemReferenceToArray(), and cJSON_AddItemToObject().
cJSON_AddItemToObject()
void cJSON_AddItemToObject (cJSON * object, const char * string, cJSON * item)
References cJSON_AddItemToArray(), cJSON_free, cJSON_strdup(), and cJSON::string.
Referenced by cJSON_AddItemReferenceToObject().
cJSON_CreateArray()
cJSON* cJSON_CreateArray (void)
References cJSON_Array, cJSON_New_Item(), item, and cJSON::type.
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), cJSON_CreateIntArray(), and cJSON_CreateStringArray().
cJSON_CreateBool()
cJSON* cJSON_CreateBool (int b)
References cJSON_False, cJSON_New_Item(), cJSON_True, item, and cJSON::type.
cJSON_CreateDoubleArray()
cJSON* cJSON_CreateDoubleArray (double * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), p, and suffix_object().
cJSON_CreateFalse()
cJSON* cJSON_CreateFalse (void)
References cJSON_False, cJSON_New_Item(), item, and cJSON::type.
cJSON_CreateFloatArray()
cJSON* cJSON_CreateFloatArray (float * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), p, and suffix_object().
cJSON_CreateIntArray()
cJSON* cJSON_CreateIntArray (int * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), p, and suffix_object().
cJSON_CreateNull()
cJSON* cJSON_CreateNull (void)
References cJSON_New_Item(), cJSON_NULL, item, and cJSON::type.
cJSON_CreateNumber()
cJSON* cJSON_CreateNumber (double num)
References cJSON_New_Item(), cJSON_Number, item, cJSON::type, cJSON::valuedouble, and cJSON::valueint.
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), and cJSON_CreateIntArray().
cJSON_CreateObject()
cJSON* cJSON_CreateObject (void)
References cJSON_New_Item(), cJSON_Object, item, and cJSON::type.
cJSON_CreateString()
cJSON* cJSON_CreateString (const char * string)
References cJSON_New_Item(), cJSON_strdup(), cJSON_String, item, cJSON::type, and cJSON::valuestring.
Referenced by cJSON_CreateStringArray().
cJSON_CreateStringArray()
cJSON* cJSON_CreateStringArray (const char ** strings, int count)
References cJSON_CreateArray(), cJSON_CreateString(), p, and suffix_object().
cJSON_CreateTrue()
cJSON* cJSON_CreateTrue (void)
References cJSON_New_Item(), cJSON_True, item, and cJSON::type.
cJSON_Delete()
void cJSON_Delete (cJSON * c)
References cJSON::child, cJSON_Delete(), cJSON_free, cJSON_IsReference, cJSON::next, next, cJSON::string, cJSON::type, and cJSON::valuestring.
Referenced by cJSON_Delete(), cJSON_DeleteItemFromArray(), cJSON_DeleteItemFromObject(), cJSON_Parse(), cJSON_ReplaceItemInArray(), vehicle_webos_bt_gap_callback(), and vehicle_webos_spp_notify().
cJSON_DeleteItemFromArray()
void cJSON_DeleteItemFromArray (cJSON * array, int which)
References cJSON_Delete(), and cJSON_DetachItemFromArray().
cJSON_DeleteItemFromObject()
void cJSON_DeleteItemFromObject (cJSON * object, const char * string)
References cJSON_Delete(), and cJSON_DetachItemFromObject().
cJSON_DetachItemFromArray()
cJSON* cJSON_DetachItemFromArray (cJSON * array, int which)
References c, cJSON::child, cJSON::next, and cJSON::prev.
Referenced by cJSON_DeleteItemFromArray(), and cJSON_DetachItemFromObject().
cJSON_DetachItemFromObject()
cJSON* cJSON_DetachItemFromObject (cJSON * object, const char * string)
References c, cJSON_DetachItemFromArray(), cJSON_strcasecmp(), cJSON::next, and cJSON::string.
Referenced by cJSON_DeleteItemFromObject().
cJSON_GetArrayItem()
cJSON* cJSON_GetArrayItem (cJSON * array, int item)
References c, and cJSON::child.
Referenced by vehicle_webos_bt_gap_callback(), and vehicle_webos_spp_notify().
cJSON_GetArraySize()
int cJSON_GetArraySize (cJSON * array)
References c, cJSON::child, and cJSON::next.
Referenced by vehicle_webos_bt_gap_callback().
cJSON_GetErrorPtr()
const char* cJSON_GetErrorPtr (void)
References ep.
cJSON_GetObjectItem()
cJSON* cJSON_GetObjectItem (cJSON * object, const char * string)
References c, cJSON_strcasecmp(), cJSON::next, and cJSON::string.
Referenced by vehicle_webos_bt_gap_callback(), and vehicle_webos_spp_notify().
cJSON_InitHooks()
void cJSON_InitHooks (cJSON_Hooks * hooks)
References cJSON_free, cJSON_malloc, cJSON_Hooks::free_fn, and cJSON_Hooks::malloc_fn.
cJSON_New_Item()
static cJSON* cJSON_New_Item (void) static
References cJSON_malloc.
Referenced by cJSON_CreateArray(), cJSON_CreateBool(), cJSON_CreateFalse(), cJSON_CreateNull(), cJSON_CreateNumber(), cJSON_CreateObject(), cJSON_CreateString(), cJSON_CreateTrue(), cJSON_Parse(), create_reference(), parse_array(), and parse_object().
cJSON_Parse()
cJSON* cJSON_Parse (const char * value)
References c, cJSON_Delete(), cJSON_New_Item(), ep, parse_value(), and skip().
Referenced by vehicle_webos_bt_gap_callback(), and vehicle_webos_spp_notify().
cJSON_Print()
char* cJSON_Print (cJSON * item)
References print_value().
cJSON_PrintUnformatted()
char* cJSON_PrintUnformatted (cJSON * item)
References print_value().
cJSON_ReplaceItemInArray()
void cJSON_ReplaceItemInArray (cJSON * array, int which, cJSON * newitem)
References c, cJSON::child, cJSON_Delete(), cJSON::next, and cJSON::prev.
Referenced by cJSON_ReplaceItemInObject().
cJSON_ReplaceItemInObject()
void cJSON_ReplaceItemInObject (cJSON * object, const char * string, cJSON * newitem)
References c, cJSON_ReplaceItemInArray(), cJSON_strcasecmp(), cJSON_strdup(), cJSON::next, and cJSON::string.
cJSON_strcasecmp()
static int cJSON_strcasecmp (const char * s1, const char * s2) static
References s1.
Referenced by cJSON_DetachItemFromObject(), cJSON_GetObjectItem(), and cJSON_ReplaceItemInObject().
cJSON_strdup()
static char* cJSON_strdup (const char * str) static
References cJSON_malloc.
Referenced by cJSON_AddItemToObject(), cJSON_CreateString(), cJSON_ReplaceItemInObject(), print_string_ptr(), and print_value().
create_reference()
static cJSON* create_reference (cJSON * item) static
References cJSON_IsReference, cJSON_New_Item(), cJSON::next, cJSON::prev, cJSON::string, and cJSON::type.
Referenced by cJSON_AddItemReferenceToArray(), and cJSON_AddItemReferenceToObject().
parse_array()
static const char * parse_array (cJSON * item, const char * value) static
References cJSON::child, cJSON_Array, cJSON_New_Item(), ep, cJSON::next, parse_value(), cJSON::prev, skip(), cJSON::type, and value.
Referenced by parse_value(), and print_string().
parse_number()
static const char* parse_number (cJSON * item, const char * num) static
References cJSON_Number, cJSON::type, cJSON::valuedouble, and cJSON::valueint.
Referenced by parse_value().
parse_object()
static const char * parse_object (cJSON * item, const char * value) static
References cJSON::child, cJSON_New_Item(), cJSON_Object, ep, cJSON::next, parse_string(), parse_value(), cJSON::prev, skip(), cJSON::string, cJSON::type, value, and cJSON::valuestring.
Referenced by parse_value(), and print_string().
parse_string()
static const char* parse_string (cJSON * item, const char * str) static
References cJSON_malloc, cJSON_String, ep, firstByteMark, cJSON::type, and cJSON::valuestring.
Referenced by parse_object(), and parse_value().
parse_value()
static const char * parse_value (cJSON * item, const char * value) static
References cJSON_False, cJSON_NULL, cJSON_True, ep, parse_array(), parse_number(), parse_object(), parse_string(), cJSON::type, value, and cJSON::valueint.
Referenced by cJSON_Parse(), parse_array(), parse_object(), and print_string().
print_array()
static char * print_array (cJSON * item, int depth, int fmt) static
References cJSON::child, cJSON_free, cJSON_malloc, entries, cJSON::next, and print_value().
Referenced by print_string(), and print_value().
print_number()
static char* print_number (cJSON * item) static
References cJSON_malloc, cJSON::valuedouble, and cJSON::valueint.
Referenced by print_value().
print_object()
static char * print_object (cJSON * item, int depth, int fmt) static
References cJSON::child, cJSON_free, cJSON_malloc, entries, cJSON::next, print_string_ptr(), and print_value().
Referenced by print_string(), and print_value().
print_string()
static char* print_string (cJSON * item) static
References parse_array(), parse_object(), parse_value(), print_array(), print_object(), print_string_ptr(), print_value(), value, and cJSON::valuestring.
Referenced by print_value().
print_string_ptr()
static char* print_string_ptr (const char * str) static
References cJSON_malloc, and cJSON_strdup().
Referenced by print_object(), and print_string().
print_value()
static char * print_value (cJSON * item, int depth, int fmt) static
References cJSON_Array, cJSON_False, cJSON_NULL, cJSON_Number, cJSON_Object, cJSON_strdup(), cJSON_String, cJSON_True, print_array(), print_number(), print_object(), print_string(), and cJSON::type.
Referenced by cJSON_Print(), cJSON_PrintUnformatted(), print_array(), print_object(), and print_string().
skip()
static const char* skip (const char * in) static
Referenced by cJSON_Parse(), command_evaluate_single(), eval_conditional(), parse_array(), parse_object(), and traffic_message_remove_item_data().
suffix_object()
static void suffix_object (cJSON * prev, cJSON * item) static
References item, cJSON::next, and cJSON::prev.
Referenced by cJSON_AddItemToArray(), cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), cJSON_CreateIntArray(), and cJSON_CreateStringArray().
Variable Documentation
cJSON_free
void(* cJSON_free) (void *ptr) = free static
Referenced by cJSON_AddItemToObject(), cJSON_Delete(), cJSON_InitHooks(), print_array(), and print_object().
cJSON_malloc
void*(* cJSON_malloc) (size_t sz) = malloc static
Referenced by cJSON_InitHooks(), cJSON_New_Item(), cJSON_strdup(), parse_string(), print_array(), print_number(), print_object(), and print_string_ptr().
ep
const char* ep static
Referenced by cJSON_GetErrorPtr(), cJSON_Parse(), parse_array(), parse_object(), parse_string(), and parse_value().
firstByteMark
const unsigned char firstByteMark[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC } static
Referenced by parse_string().