navit: NGQProxyRoute Class Reference
NGQProxyRoute Class Reference
#include <routeProxy.h>
Public Slots
void addDestination ()
QString getDestinations ()
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Public Member Functions
NGQProxyRoute (struct gui_priv *this_, QObject *parent)
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
int setAttrFunc (struct attr *attr)
struct attr_iter * getIterFunc ()
void dropIterFunc (struct attr_iter *iter)
QList< struct attr > _routeDestinations ()
Protected Member Functions inherited from NGQProxy
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Additional Inherited Members
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Properties inherited from NGQProxy
int itemId
Constructor & Destructor Documentation
NGQProxyRoute::NGQProxyRoute (struct gui_priv * this_, QObject * parent) inline
Member Function Documentation
QList<struct attr> NGQProxyRoute::_routeDestinations () inline protected
References dropIterFunc(), getAttrFunc(), getIterFunc(), eval::iter, and NULL.
Referenced by addDestination(), and getDestinations().
void NGQProxyRoute::addDestination () inline slot
References _routeDestinations(), eval::iter, gui_priv::nav, navit_get_route(), NGQProxy::object, and route_set_destinations().
void NGQProxyRoute::dropIterFunc (struct attr_iter * iter) inline protected virtual
Reimplemented from NGQProxy.
References route_attr_iter_destroy().
Referenced by _routeDestinations().
int NGQProxyRoute::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
References gui_priv::nav, navit_get_route(), NGQProxy::object, and route_get_attr().
Referenced by _routeDestinations().
QString NGQProxyRoute::getDestinations () inline slot
References _routeDestinations(), NGQPoint::coordString, dbg, eval::iter, lvl_debug, and MapPoint.
struct attr_iter* NGQProxyRoute::getIterFunc () inline protected virtual
Reimplemented from NGQProxy.
References route_attr_iter_new().
Referenced by _routeDestinations().
int NGQProxyRoute::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
References gui_priv::nav, navit_get_route(), NGQProxy::object, and route_set_attr().
The documentation for this class was generated from the following file:
gui/qml/routeProxy.h