navit: Qt5EspeakAudioOut Class Reference
Qt5EspeakAudioOut Class Reference
#include <Qt5EspeakAudioOut.h>
Public Slots
void handleStateChanged (QAudio::State newState)
void resume (int state)
Signals
void call_resume (int state)
Public Member Functions
Qt5EspeakAudioOut (int samplerate, const char *category)
~Qt5EspeakAudioOut ()
void addSamples (short *wav, int numsamples)
Private Attributes
QByteArray * data
QBuffer * buffer
QAudioOutput * audio
Detailed Description
Navit, a modular navigation system. Copyright (C) 2017-2017 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Constructor & Destructor Documentation
Qt5EspeakAudioOut()
Qt5EspeakAudioOut::Qt5EspeakAudioOut (int samplerate, const char * category)
Navit, a modular navigation system. Copyright (C) 2017-2017 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References audio, call_resume(), data, dbg, handleStateChanged(), info, lvl_debug, lvl_error, and resume().
~Qt5EspeakAudioOut()
Qt5EspeakAudioOut::~Qt5EspeakAudioOut ()
References audio, buffer, and data.
Member Function Documentation
addSamples()
void Qt5EspeakAudioOut::addSamples (short * wav, int numsamples)
References call_resume(), data, dbg, lvl_debug, and buffer::size.
Referenced by qt5_espeak_SynthCallback().
call_resume
void Qt5EspeakAudioOut::call_resume (int state) signal
Referenced by addSamples(), and Qt5EspeakAudioOut().
handleStateChanged
void Qt5EspeakAudioOut::handleStateChanged (QAudio::State newState) slot
References data, dbg, and lvl_debug.
Referenced by Qt5EspeakAudioOut().
resume
void Qt5EspeakAudioOut::resume (int state) slot
References audio, dbg, and lvl_debug.
Referenced by Qt5EspeakAudioOut().
Field Documentation
audio
QAudioOutput* Qt5EspeakAudioOut::audio private
Referenced by Qt5EspeakAudioOut(), resume(), and ~Qt5EspeakAudioOut().
buffer
QBuffer* Qt5EspeakAudioOut::buffer private
Referenced by ~Qt5EspeakAudioOut().
data
QByteArray* Qt5EspeakAudioOut::data private
Referenced by addSamples(), handleStateChanged(), Qt5EspeakAudioOut(), and ~Qt5EspeakAudioOut().
The documentation for this class was generated from the following files:
speech/qt5_espeak/Qt5EspeakAudioOut.h
speech/qt5_espeak/Qt5EspeakAudioOut.cpp