navit: mapExtract Class Reference
mapExtract Class Reference
Public Member Functions
mapExtract ()
process ()
setBbox ($sx, $sy, $ex, $ey)
setInput ($file)
setInputFD ($fd)
setOutput ($file)
setOutputFD ($fd)
contains_bbox (&$r)
getmercator ($sx, $sy, $ex, $ey)
Data Fields
$input_fd
$output_fd
$fetchBbox
$formats
$worldBbox
Member Function Documentation
contains_bbox()
mapExtract::contains_bbox (& $r)
References $fetchBbox.
Referenced by process().
getmercator()
mapExtract::getmercator ($sx, $sy, $ex, $ey)
References M_PI, and M_PI_4.
Referenced by setBbox().
mapExtract()
mapExtract::mapExtract ()
References $formats, $world_bbox, checksum, data, filename, length, size, type, version, and zip.
process()
mapExtract::process ()
Read through zipheaders
References $offset, $worldBbox, and contains_bbox().
setBbox()
mapExtract::setBbox ($sx, $sy, $ex, $ey)
References getmercator().
setInput()
mapExtract::setInput ($file)
setInputFD()
mapExtract::setInputFD ($fd)
setOutput()
mapExtract::setOutput ($file)
setOutputFD()
mapExtract::setOutputFD ($fd)
Field Documentation
$fetchBbox
mapExtract::$fetchBbox
Referenced by contains_bbox().
$formats
mapExtract::$formats
Referenced by mapExtract().
$input_fd
mapExtract::$input_fd
$output_fd
mapExtract::$output_fd
$worldBbox
mapExtract::$worldBbox
Referenced by process().
The documentation for this class was generated from the following file:
script/mapExtract.class.php