navit: org.navitproject.navit.NavitTimeout Class Reference
org.navitproject.navit.NavitTimeout Class Reference
Data Structures
class TimeoutHandler
Public Member Functions
native void timeoutCallback (long id)
void run ()
void remove ()
Package Functions
NavitTimeout (int timeout, boolean multi, long callbackid)
Private Attributes
final long mEventCallbackid
final int mEventTimeout
final boolean mEventMulti
Static Private Attributes
static final TimeoutHandler handler = new TimeoutHandler()
Constructor & Destructor Documentation
NavitTimeout()
org.navitproject.navit.NavitTimeout.NavitTimeout (int timeout, boolean multi, long callbackid) inline package
References org.navitproject.navit.NavitTimeout.handler, org.navitproject.navit.NavitTimeout.mEventCallbackid, org.navitproject.navit.NavitTimeout.mEventMulti, and org.navitproject.navit.NavitTimeout.mEventTimeout.
Member Function Documentation
remove()
void org.navitproject.navit.NavitTimeout.remove () inline
References org.navitproject.navit.NavitTimeout.handler.
run()
void org.navitproject.navit.NavitTimeout.run () inline
References org.navitproject.navit.NavitTimeout.handler, org.navitproject.navit.NavitTimeout.mEventCallbackid, org.navitproject.navit.NavitTimeout.mEventMulti, org.navitproject.navit.NavitTimeout.mEventTimeout, and org.navitproject.navit.NavitTimeout.timeoutCallback().
timeoutCallback()
native void org.navitproject.navit.NavitTimeout.timeoutCallback (long id)
Referenced by org.navitproject.navit.NavitTimeout.run().
Field Documentation
handler
final TimeoutHandler org.navitproject.navit.NavitTimeout.handler = new TimeoutHandler() static private
Referenced by org.navitproject.navit.NavitTimeout.NavitTimeout(), org.navitproject.navit.NavitTimeout.remove(), and org.navitproject.navit.NavitTimeout.run().
mEventCallbackid
final long org.navitproject.navit.NavitTimeout.mEventCallbackid private
Referenced by org.navitproject.navit.NavitTimeout.NavitTimeout(), and org.navitproject.navit.NavitTimeout.run().
mEventMulti
final boolean org.navitproject.navit.NavitTimeout.mEventMulti private
Referenced by org.navitproject.navit.NavitTimeout.NavitTimeout(), and org.navitproject.navit.NavitTimeout.run().
mEventTimeout
final int org.navitproject.navit.NavitTimeout.mEventTimeout private
Referenced by org.navitproject.navit.NavitTimeout.NavitTimeout(), and org.navitproject.navit.NavitTimeout.run().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitTimeout.java