navit: org.navitproject.navit.FileBrowserActivity Class Reference
org.navitproject.navit.FileBrowserActivity Class Reference
Data Structures
class Item
class ItemFileNameComparator
Public Member Functions
void onCreate (Bundle savedInstanceState)
void onConfigurationChanged (Configuration newConfig)
Static Public Member Functions
static long getFreeSpace (String path)
static String formatBytes (long bytes)
Static Public Attributes
static final String INTENT_ACTION_SELECT_DIR = "ua.com.vassiliev.androidfilebrowser.SELECT_DIRECTORY_ACTION"
static final String INTENT_ACTION_SELECT_FILE = "ua.com.vassiliev.androidfilebrowser.SELECT_FILE_ACTION"
static final String startDirectoryParameter = "ua.com.vassiliev.androidfilebrowser.directoryPath"
static final String returnDirectoryParameter = "ua.com.vassiliev.androidfilebrowser.directoryPathRet"
static final String returnFileParameter = "ua.com.vassiliev.androidfilebrowser.filePathRet"
static final String showCannotReadParameter = "ua.com.vassiliev.androidfilebrowser.showCannotRead"
static final String filterExtension = "ua.com.vassiliev.androidfilebrowser.filterExtension"
Package Attributes
ArrayList< String > pathDirsList = new ArrayList<String>()
ArrayAdapter< Item > adapter
Private Member Functions
void setInitialDirectory ()
void parseDirectoryPath ()
void initializeButtons ()
void loadDirectoryUp ()
void updateCurrentDirectoryTextView ()
void showToast (String message)
void initializeFileListView ()
void returnDirectoryFinishActivity ()
void returnFileFinishActivity (String filePath)
void loadFileList ()
void createFileListAdapter ()
Private Attributes
List< Item > fileList = new ArrayList<Item>()
File path = null
String chosenFile
boolean showHiddenFilesAndDirs = true
boolean directoryShownIsEmpty = false
String filterFileExtension = null
Static Private Attributes
static final String LOGTAG = "F_PATH"
static int currentAction = -1
static final int SELECT_DIRECTORY = 1
static final int SELECT_FILE = 2
Member Function Documentation
void org.navitproject.navit.FileBrowserActivity.createFileListAdapter () inline private
References org.navitproject.navit.FileBrowserActivity.adapter, org.navitproject.navit.FileBrowserActivity.fileList, and int.
static String org.navitproject.navit.FileBrowserActivity.formatBytes (long bytes) inline static
Referenced by org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
static long org.navitproject.navit.FileBrowserActivity.getFreeSpace (String path) inline static
References long.
Referenced by org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
void org.navitproject.navit.FileBrowserActivity.initializeButtons () inline private
References org.navitproject.navit.FileBrowserActivity.currentAction, org.navitproject.navit.FileBrowserActivity.loadDirectoryUp(), org.navitproject.navit.FileBrowserActivity.loadFileList(), org.navitproject.navit.FileBrowserActivity.LOGTAG, org.navitproject.navit.FileBrowserActivity.returnDirectoryFinishActivity(), org.navitproject.navit.FileBrowserActivity.SELECT_DIRECTORY, and org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
void org.navitproject.navit.FileBrowserActivity.initializeFileListView () inline private
References org.navitproject.navit.FileBrowserActivity.chosenFile, org.navitproject.navit.FileBrowserActivity.directoryShownIsEmpty, org.navitproject.navit.FileBrowserActivity.loadFileList(), org.navitproject.navit.FileBrowserActivity.LOGTAG, org.navitproject.navit.FileBrowserActivity.path, org.navitproject.navit.FileBrowserActivity.returnFileFinishActivity(), org.navitproject.navit.FileBrowserActivity.showToast(), and org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
void org.navitproject.navit.FileBrowserActivity.loadDirectoryUp () inline private
References org.navitproject.navit.FileBrowserActivity.path.
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons().
void org.navitproject.navit.FileBrowserActivity.loadFileList () inline private
References org.navitproject.navit.FileBrowserActivity.currentAction, org.navitproject.navit.FileBrowserActivity.fileList, filename, filter(), org.navitproject.navit.FileBrowserActivity.filterFileExtension, i, length, org.navitproject.navit.FileBrowserActivity.LOGTAG, org.navitproject.navit.FileBrowserActivity.path, org.navitproject.navit.FileBrowserActivity.SELECT_DIRECTORY, org.navitproject.navit.FileBrowserActivity.SELECT_FILE, and org.navitproject.navit.FileBrowserActivity.showHiddenFilesAndDirs.
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons(), org.navitproject.navit.FileBrowserActivity.initializeFileListView(), and org.navitproject.navit.FileBrowserActivity.onCreate().
void org.navitproject.navit.FileBrowserActivity.onConfigurationChanged (Configuration newConfig) inline
References org.navitproject.navit.FileBrowserActivity.LOGTAG.
void org.navitproject.navit.FileBrowserActivity.onCreate (Bundle savedInstanceState) inline
References org.navitproject.navit.FileBrowserActivity.currentAction, org.navitproject.navit.FileBrowserActivity.filterExtension, org.navitproject.navit.FileBrowserActivity.filterFileExtension, org.navitproject.navit.FileBrowserActivity.INTENT_ACTION_SELECT_FILE, org.navitproject.navit.FileBrowserActivity.loadFileList(), org.navitproject.navit.FileBrowserActivity.LOGTAG, org.navitproject.navit.FileBrowserActivity.parseDirectoryPath(), org.navitproject.navit.FileBrowserActivity.SELECT_DIRECTORY, org.navitproject.navit.FileBrowserActivity.SELECT_FILE, org.navitproject.navit.FileBrowserActivity.setInitialDirectory(), org.navitproject.navit.FileBrowserActivity.showCannotReadParameter, org.navitproject.navit.FileBrowserActivity.showHiddenFilesAndDirs, and org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
void org.navitproject.navit.FileBrowserActivity.parseDirectoryPath () inline private
References i.
Referenced by org.navitproject.navit.FileBrowserActivity.onCreate().
void org.navitproject.navit.FileBrowserActivity.returnDirectoryFinishActivity () inline private
References org.navitproject.navit.FileBrowserActivity.returnDirectoryParameter.
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons().
void org.navitproject.navit.FileBrowserActivity.returnFileFinishActivity (String filePath) inline private
References org.navitproject.navit.FileBrowserActivity.returnFileParameter.
Referenced by org.navitproject.navit.FileBrowserActivity.initializeFileListView().
void org.navitproject.navit.FileBrowserActivity.setInitialDirectory () inline private
References org.navitproject.navit.FileBrowserActivity.path, and org.navitproject.navit.FileBrowserActivity.startDirectoryParameter.
Referenced by org.navitproject.navit.FileBrowserActivity.onCreate().
void org.navitproject.navit.FileBrowserActivity.showToast (String message) inline private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeFileListView().
void org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView () inline private
References org.navitproject.navit.FileBrowserActivity.formatBytes(), org.navitproject.navit.FileBrowserActivity.getFreeSpace(), i, org.navitproject.navit.FileBrowserActivity.LOGTAG, and org.navitproject.navit.FileBrowserActivity.pathDirsList.
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons(), org.navitproject.navit.FileBrowserActivity.initializeFileListView(), and org.navitproject.navit.FileBrowserActivity.onCreate().
Field Documentation
ArrayAdapter<Item> org.navitproject.navit.FileBrowserActivity.adapter package
Referenced by org.navitproject.navit.FileBrowserActivity.createFileListAdapter().
String org.navitproject.navit.FileBrowserActivity.chosenFile private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeFileListView().
int org.navitproject.navit.FileBrowserActivity.currentAction = -1 static private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons(), org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.onCreate().
boolean org.navitproject.navit.FileBrowserActivity.directoryShownIsEmpty = false private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeFileListView().
List<Item> org.navitproject.navit.FileBrowserActivity.fileList = new ArrayList<Item>() private
Referenced by org.navitproject.navit.FileBrowserActivity.createFileListAdapter(), and org.navitproject.navit.FileBrowserActivity.loadFileList().
final String org.navitproject.navit.FileBrowserActivity.filterExtension = "ua.com.vassiliev.androidfilebrowser.filterExtension" static
Referenced by org.navitproject.navit.FileBrowserActivity.onCreate().
String org.navitproject.navit.FileBrowserActivity.filterFileExtension = null private
Referenced by org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.onCreate().
final String org.navitproject.navit.FileBrowserActivity.INTENT_ACTION_SELECT_DIR = "ua.com.vassiliev.androidfilebrowser.SELECT_DIRECTORY_ACTION" static
Referenced by org.navitproject.navit.Navit.setMapLocation().
final String org.navitproject.navit.FileBrowserActivity.INTENT_ACTION_SELECT_FILE = "ua.com.vassiliev.androidfilebrowser.SELECT_FILE_ACTION" static
Referenced by org.navitproject.navit.FileBrowserActivity.onCreate().
final String org.navitproject.navit.FileBrowserActivity.LOGTAG = "F_PATH" static private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons(), org.navitproject.navit.FileBrowserActivity.initializeFileListView(), org.navitproject.navit.FileBrowserActivity.loadFileList(), org.navitproject.navit.FileBrowserActivity.onConfigurationChanged(), org.navitproject.navit.FileBrowserActivity.onCreate(), and org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
File org.navitproject.navit.FileBrowserActivity.path = null private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeFileListView(), org.navitproject.navit.FileBrowserActivity.loadDirectoryUp(), org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.setInitialDirectory().
ArrayList<String> org.navitproject.navit.FileBrowserActivity.pathDirsList = new ArrayList<String>() package
Referenced by org.navitproject.navit.FileBrowserActivity.updateCurrentDirectoryTextView().
final String org.navitproject.navit.FileBrowserActivity.returnDirectoryParameter = "ua.com.vassiliev.androidfilebrowser.directoryPathRet" static
Referenced by org.navitproject.navit.Navit.onActivityResult(), and org.navitproject.navit.FileBrowserActivity.returnDirectoryFinishActivity().
final String org.navitproject.navit.FileBrowserActivity.returnFileParameter = "ua.com.vassiliev.androidfilebrowser.filePathRet" static
Referenced by org.navitproject.navit.FileBrowserActivity.returnFileFinishActivity().
final int org.navitproject.navit.FileBrowserActivity.SELECT_DIRECTORY = 1 static private
Referenced by org.navitproject.navit.FileBrowserActivity.initializeButtons(), org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.onCreate().
final int org.navitproject.navit.FileBrowserActivity.SELECT_FILE = 2 static private
Referenced by org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.onCreate().
final String org.navitproject.navit.FileBrowserActivity.showCannotReadParameter = "ua.com.vassiliev.androidfilebrowser.showCannotRead" static
Referenced by org.navitproject.navit.FileBrowserActivity.onCreate().
boolean org.navitproject.navit.FileBrowserActivity.showHiddenFilesAndDirs = true private
Referenced by org.navitproject.navit.FileBrowserActivity.loadFileList(), and org.navitproject.navit.FileBrowserActivity.onCreate().
final String org.navitproject.navit.FileBrowserActivity.startDirectoryParameter = "ua.com.vassiliev.androidfilebrowser.directoryPath" static
Referenced by org.navitproject.navit.FileBrowserActivity.setInitialDirectory(), and org.navitproject.navit.Navit.setMapLocation().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/FileBrowserActivity.java