navit: org.navitproject.navit.NavitAppConfig Class Reference
org.navitproject.navit.NavitAppConfig Class Reference
Public Member Functions
void onCreate ()
List< NavitAddress > getLastAddresses ()
void addLastAddress (NavitAddress newAddress)
Private Attributes
List< NavitAddress > mLastAddresses = null
int mLastAddressField
SharedPreferences mSettings
Static Private Attributes
static final int MAX_LAST_ADDRESSES = 10
static final String TAG = "Navit"
Member Function Documentation
addLastAddress()
void org.navitproject.navit.NavitAppConfig.addLastAddress (NavitAddress newAddress) inline
References org.navitproject.navit.NavitAddressSearchActivity.NavitAddress.addr, org.navitproject.navit.NavitAppConfig.getLastAddresses(), org.navitproject.navit.NavitAddressSearchActivity.NavitAddress.lat, org.navitproject.navit.NavitAddressSearchActivity.NavitAddress.lon, and org.navitproject.navit.NavitAppConfig.MAX_LAST_ADDRESSES.
getLastAddresses()
List<NavitAddress> org.navitproject.navit.NavitAppConfig.getLastAddresses () inline
References org.navitproject.navit.NavitAppConfig.mLastAddresses, and org.navitproject.navit.NavitAppConfig.mLastAddressField.
Referenced by org.navitproject.navit.NavitAppConfig.addLastAddress(), and org.navitproject.navit.NavitAddressSearchActivity.onCreate().
onCreate()
void org.navitproject.navit.NavitAppConfig.onCreate () inline
References org.navitproject.navit.Navit.NAVIT_PREFS.
Field Documentation
MAX_LAST_ADDRESSES
final int org.navitproject.navit.NavitAppConfig.MAX_LAST_ADDRESSES = 10 static private
Referenced by org.navitproject.navit.NavitAppConfig.addLastAddress().
mLastAddresses
List<NavitAddress> org.navitproject.navit.NavitAppConfig.mLastAddresses = null private
Referenced by org.navitproject.navit.NavitAppConfig.getLastAddresses().
mLastAddressField
int org.navitproject.navit.NavitAppConfig.mLastAddressField private
Referenced by org.navitproject.navit.NavitAppConfig.getLastAddresses().
mSettings
SharedPreferences org.navitproject.navit.NavitAppConfig.mSettings private
TAG
final String org.navitproject.navit.NavitAppConfig.TAG = "Navit" static private
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitAppConfig.java