navit: Backend Class Reference
Backend Class Reference
#include <backend.h>
Public Slots
void get_maps ()
update the private m_maps list. Expected to be called from QML
void get_pois ()
update the private m_pois list. Expected to be called from QML
void get_bookmarks ()
update the private m_bookmarks list. Expected to be called from QML
void get_vehicles ()
update the private m_vehicles list. Expected to be called from QML
QString get_icon_path ()
returns the icon absolute path
QString get_country_icon (char *country_iso_code)
get the icon that matches the country currently used for searches
void setActivePoi (int index)
set the active POI. Used when clicking on a POI list to display one single POI
void setCurrentBookmark (int index)
set the current bookmark. Used when clicking on a bookmark list to display one single bookmark
void setCurrentVehicle (int index)
set the current vehicle. Used when clicking on a vehicle list to display one single vehicle
void setActivePoiAsDestination ()
set the destination using the currently active POI's coordinates
void updateSearch (QString text)
update the current search results according to new inputs. Currently only works to search for towns
void searchValidateResult (int index)
save the search result for the next search step
void resize (int width, int height)
set the canvas size to use when drawing the map
void setSearchContext (QString text)
void block_draw ()
Signals
void displayMenu (QString source)
void hideMenu ()
void poisChanged ()
void bookmarksChanged ()
void activePoiChanged ()
void currentBookmarkChanged ()
void currentVehicleChanged ()
void mapsChanged ()
void vehiclesChanged ()
void searchResultsChanged ()
void currentCountryChanged ()
void currentCountryIso2Changed ()
void currentTownChanged ()
void currentStreetChanged ()
Public Member Functions
Backend (QObject *parent=0)
void showMenu (struct point *p)
Set some variables and display the main menu.
void set_navit (struct navit *nav)
set a pointer to the struct navit * for local use
void set_engine (QQmlApplicationEngine *engine)
set a pointer to the QQmlApplicationEngine * for local use
QQmlListProperty< QObject > getPois ()
get the POIs as a QList
QQmlListProperty< QObject > getBookmarks ()
get the Bookmarks as a QList
QQmlListProperty< QObject > getMaps ()
get the maps as a QList
QQmlListProperty< QObject > getVehicles ()
get the vehicles as a QList
PoiObject * activePoi ()
BookmarkObject * currentBookmark ()
VehicleObject * currentVehicle ()
QQmlListProperty< QObject > getSearchResults ()
get the search results as a QList
QString currentCountry ()
QString currentCountryIso2 ()
QString currentTown ()
QString currentStreet ()
Data Fields
QList< PoiObject * > pois
QList< BookmarkObject * > bookmarks
QList< MapObject * > maps
QList< MapObject * > vehicles
Properties
QQmlListProperty< QObject > pois
QQmlListProperty< QObject > bookmarks
QQmlListProperty< QObject > maps
QQmlListProperty< QObject > vehicles
PoiObject activePoi
get the active POI. Used when displaying the relevant menu
BookmarkObject currentBookmark
get the current bookmark. Used when displaying the relevant menu
VehicleObject currentVehicle
get the currently selected vehicle. Used when displaying the relevant menu
QQmlListProperty< QObject > searchresults
QString currentCountry
QString currentCountryIso2
QString currentTown
QString currentStreet
Private Member Functions
int filter_pois (struct item *item)
apply search filters on one specific item
void set_default_country ()
set the default country
Private Attributes
struct navit * nav
struct point * p
struct coord_geo g
struct pcoord c
QQmlApplicationEngine * engine
QList< QObject * > _pois
QList< QObject * > _bookmarks
QList< QObject * > _maps
QList< QObject * > _vehicles
PoiObject * m_activePoi
BookmarkObject * m_currentBookmark
VehicleObject * m_currentVehicle
QList< QObject * > _search_results
char * _country_iso2
char * _current_country
char * _current_town
char * _current_street
struct search_param * search
enum attr_type _search_context
Constructor & Destructor Documentation
Backend::Backend (QObject * parent = 0) explicit
References _current_street, _current_town, NULL, search, and set_default_country().
Member Function Documentation
PoiObject* Backend::activePoi ()
void Backend::activePoiChanged () signal
Referenced by setActivePoi().
void Backend::block_draw () slot
References dbg, lvl_debug, nav, and navit_block().
void Backend::bookmarksChanged () signal
Referenced by get_bookmarks().
BookmarkObject* Backend::currentBookmark ()
void Backend::currentBookmarkChanged () signal
Referenced by setCurrentBookmark().
QString Backend::currentCountry ()
void Backend::currentCountryChanged () signal
QString Backend::currentCountryIso2 ()
void Backend::currentCountryIso2Changed () signal
QString Backend::currentStreet ()
void Backend::currentStreetChanged () signal
QString Backend::currentTown ()
void Backend::currentTownChanged () signal
VehicleObject* Backend::currentVehicle ()
void Backend::currentVehicleChanged () signal
Referenced by setCurrentVehicle().
void Backend::displayMenu (QString source) signal
Referenced by searchValidateResult(), and showMenu().
int Backend::filter_pois (struct item * item) private
apply search filters on one specific item
Parameters
struct item * the item to filter
Returns
0 if the item should be discarded, 1 otherwise
References item::type, type, and types.
Referenced by get_pois().
void Backend::get_bookmarks () slot
update the private m_bookmarks list. Expected to be called from QML
Parameters
none
Returns
nothing
References _bookmarks, attr::bookmarks, bookmarks_get_item(), bookmarks_item_rewind(), bookmarksChanged(), dbg, item, item_attr_get(), item_coord_get(), lvl_debug, nav, navit_get_attr(), navit_get_trans(), NULL, pcoord::pro, attr::str, transform_get_projection(), attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
QString Backend::get_country_icon (char * country_iso_code) slot
get the icon that matches the country currently used for searches
Parameters
none
Returns
an absolute path for the country icon
References g_strjoin(), getenv, and NULL.
Referenced by updateSearch().
QString Backend::get_icon_path () slot
returns the icon absolute path
Parameters
none
Returns
the icon absolute path as a QString
References g_strjoin(), getenv, and NULL.
void Backend::get_maps () slot
update the private m_maps list. Expected to be called from QML
Parameters
none
Returns
nothing
References _maps, g_strdup(), g_strdup_printf(), eval::iter, label, attr::map, map_get_attr(), mapsChanged(), nav, navit_attr_iter_new(), navit_get_attr(), NULL, attr::num, attr::str, attr::type, and attr::u.
void Backend::get_pois () slot
update the private m_pois list. Expected to be called from QML
Parameters
none
Returns
nothing
References _pois, map_selection::c_rect, coord_rect_contains(), dbg, filter_pois(), get_icon(), attr::icon, item, item_attr_get(), item_coord_get_pro(), item_to_name(), label, lvl_debug, item::map, map_convert_string(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), map_selection_dup_pro(), map_selection_rect_new(), mapset_close(), mapset_next(), mapset_open(), nav, navit_get_mapset(), navit_get_trans(), poisChanged(), pcoord::pro, attr::str, transform_distance(), transform_get_projection(), transform_scale(), item::type, map_selection::u, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
void Backend::get_vehicles () slot
update the private m_vehicles list. Expected to be called from QML
Parameters
none
Returns
nothing
References _vehicles, dbg, g_strdup(), eval::iter, lvl_debug, nav, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, attr::str, attr::u, attr::vehicle, vehicle_get_attr(), and vehiclesChanged().
QQmlListProperty< QObject > Backend::getBookmarks ()
get the Bookmarks as a QList
Parameters
none
Returns
the bookmarks QList
References _bookmarks.
QQmlListProperty< QObject > Backend::getMaps ()
get the maps as a QList
Parameters
none
Returns
the maps QList
References _maps.
QQmlListProperty< QObject > Backend::getPois ()
get the POIs as a QList
Parameters
none
Returns
the pois QList
References _pois.
QQmlListProperty< QObject > Backend::getSearchResults ()
get the search results as a QList
Parameters
none
Returns
the search results QList
References _search_results.
QQmlListProperty< QObject > Backend::getVehicles ()
get the vehicles as a QList
Parameters
none
Returns
the vehicles QList
References _vehicles.
void Backend::hideMenu () signal
Referenced by setActivePoiAsDestination().
void Backend::mapsChanged () signal
Referenced by get_maps().
void Backend::poisChanged () signal
Referenced by get_pois().
void Backend::resize (int width, int height) slot
set the canvas size to use when drawing the map
Parameters
int width
int height
Returns
nothing
References nav, navit_block(), and navit_handle_resize().
Referenced by setActivePoi(), and setCurrentBookmark().
void Backend::searchResultsChanged () signal
Referenced by updateSearch().
void Backend::searchValidateResult (int index) slot
save the search result for the next search step
Parameters
int index the index of the result in the m_search_results list
Returns
nothing
References _current_country, _current_street, _current_town, _search_context, _search_results, dbg, displayMenu(), g_strdup(), SearchObject::getCoords(), lvl_debug, lvl_error, SearchObject::name, NULL, pcoord::x, and pcoord::y.
void Backend::set_default_country () private
set the default country
Parameters
none returns nothing
References _country_iso2, and _current_country.
Referenced by Backend().
void Backend::set_engine (QQmlApplicationEngine * engine)
set a pointer to the QQmlApplicationEngine * for local use
Parameters
none
Returns
nothing
References engine.
Referenced by gui_qt5_qml_set_graphics().
void Backend::set_navit (struct navit * nav)
set a pointer to the struct navit * for local use
Parameters
none
Returns
nothing
References nav.
Referenced by gui_qt5_qml_set_graphics().
void Backend::setActivePoi (int index) slot
set the active POI. Used when clicking on a POI list to display one single POI
Parameters
int index the index of the POI in the m_pois list
Returns
nothing
References _pois, activePoiChanged(), m_activePoi, nav, navit_set_center(), and resize().
void Backend::setActivePoiAsDestination () slot
set the destination using the currently active POI's coordinates
Parameters
none
Returns
nothing
References PoiObject::coords(), dbg, hideMenu(), lvl_debug, m_activePoi, PoiObject::name, nav, and navit_set_destination().
void Backend::setCurrentBookmark (int index) slot
set the current bookmark. Used when clicking on a bookmark list to display one single bookmark
Parameters
int index the index of the bookmark in the m_bookmarks list
Returns
nothing
References _bookmarks, currentBookmarkChanged(), m_currentBookmark, nav, navit_set_center(), and resize().
void Backend::setCurrentVehicle (int index) slot
set the current vehicle. Used when clicking on a vehicle list to display one single vehicle
Parameters
int index the index of the vehicle in the m_vehicles list
Returns
nothing
References _vehicles, currentVehicleChanged(), and m_currentVehicle.
void Backend::setSearchContext (QString text) slot
References _search_context, dbg, and lvl_error.
void Backend::showMenu (struct point * p)
Set some variables and display the main menu.
Parameters
struct point *p the point coordinate where we clicked on the screen
Returns
nothing
References c, dbg, displayMenu(), g, coord_geo::lat, lvl_debug, nav, navit_block(), navit_get_trans(), navit_set_position(), pcoord::pro, transform_get_projection(), transform_reverse(), transform_to_geo(), point::x, coord::x, pcoord::x, point::y, coord::y, and pcoord::y.
Referenced by gui_qt5_qml_button().
void Backend::updateSearch (QString text) slot
update the current search results according to new inputs. Currently only works to search for towns
Parameters
QString text the text to search for
Returns
nothing
References _country_iso2, _search_context, _search_results, search_param::attr, search_list_result::c, search_list_town::common, search_list_result::country, dbg, search_list_country::flag, g_strdup(), get_country_icon(), label, lvl_debug, lvl_error, search_param::ms, search_list_country::name, search_list_street::name, search_param::nav, nav, navit_get_mapset(), NULL, search_param::partial, search, search_list_get_result(), search_list_new(), search_list_search(), search_param, searchResultsChanged(), search_param::sl, attr::str, search_list_result::street, search_list_result::town, search_list_common::town_name, attr::type, and attr::u.
void Backend::vehiclesChanged () signal
Referenced by get_vehicles().
Field Documentation
QList<QObject *> Backend::_bookmarks private
Referenced by get_bookmarks(), getBookmarks(), and setCurrentBookmark().
char* Backend::_country_iso2 private
Referenced by set_default_country(), and updateSearch().
char* Backend::_current_country private
Referenced by searchValidateResult(), and set_default_country().
char* Backend::_current_street private
Referenced by Backend(), and searchValidateResult().
char* Backend::_current_town private
Referenced by Backend(), and searchValidateResult().
QList<QObject *> Backend::_maps private
Referenced by get_maps(), and getMaps().
QList<QObject *> Backend::_pois private
Referenced by get_pois(), getPois(), and setActivePoi().
enum attr_type Backend::_search_context private
Referenced by searchValidateResult(), setSearchContext(), and updateSearch().
QList<QObject *> Backend::_search_results private
Referenced by getSearchResults(), searchValidateResult(), and updateSearch().
QList<QObject *> Backend::_vehicles private
Referenced by get_vehicles(), getVehicles(), and setCurrentVehicle().
QList< BookmarkObject * > Backend::bookmarks
struct pcoord Backend::c private
Referenced by showMenu().
QQmlApplicationEngine* Backend::engine private
Referenced by set_engine().
struct coord_geo Backend::g private
Referenced by showMenu().
PoiObject* Backend::m_activePoi private
Referenced by setActivePoi(), and setActivePoiAsDestination().
BookmarkObject* Backend::m_currentBookmark private
Referenced by setCurrentBookmark().
VehicleObject* Backend::m_currentVehicle private
Referenced by setCurrentVehicle().
QList< MapObject * > Backend::maps
struct navit* Backend::nav private
Referenced by block_draw(), get_bookmarks(), get_maps(), get_pois(), get_vehicles(), resize(), set_navit(), setActivePoi(), setActivePoiAsDestination(), setCurrentBookmark(), showMenu(), and updateSearch().
struct point* Backend::p private
QList< PoiObject * > Backend::pois
struct search_param* Backend::search private
Referenced by Backend(), and updateSearch().
QList< MapObject * > Backend::vehicles
Property Documentation
PoiObject * Backend::activePoi read
get the active POI. Used when displaying the relevant menu
Parameters
none
Returns
the active POI
QQmlListProperty<QObject> Backend::bookmarks read
BookmarkObject * Backend::currentBookmark read
get the current bookmark. Used when displaying the relevant menu
Parameters
none
Returns
the current bookmark
QString Backend::currentCountry read
QString Backend::currentCountryIso2 read
QString Backend::currentStreet read
QString Backend::currentTown read
VehicleObject * Backend::currentVehicle read
get the currently selected vehicle. Used when displaying the relevant menu
Parameters
none
Returns
the active POI
QQmlListProperty<QObject> Backend::maps read
QQmlListProperty<QObject> Backend::pois read
QQmlListProperty<QObject> Backend::searchresults read
QQmlListProperty<QObject> Backend::vehicles read
The documentation for this class was generated from the following files:
gui/qt5_qml/backend.h
gui/qt5_qml/backend.cpp