navit: org.navitproject.navit.NavitCallbackHandler Class Reference
org.navitproject.navit.NavitCallbackHandler Class Reference
Data Structures
class CallBackHandler
enum CmdType
enum MsgType
Static Package Functions
static void sendCommand (CmdType command)
Static Package Attributes
static final Handler sCallbackHandler = new CallBackHandler()
Static Private Member Functions
static native int callbackMessageChannel (int channel, String s)
static native int callbackCmdChannel (int commandd)
Static Private Attributes
static final String TAG = "CallbackHandler"
static final MsgType[] msg_values = MsgType.values()
Member Function Documentation
callbackCmdChannel()
static native int org.navitproject.navit.NavitCallbackHandler.callbackCmdChannel (int commandd) static private
Referenced by org.navitproject.navit.NavitCallbackHandler.sendCommand().
callbackMessageChannel()
static native int org.navitproject.navit.NavitCallbackHandler.callbackMessageChannel (int channel, String s) static private
Referenced by org.navitproject.navit.NavitCallbackHandler.CallBackHandler.handleMessage().
sendCommand()
static void org.navitproject.navit.NavitCallbackHandler.sendCommand (CmdType command) inline static package
References org.navitproject.navit.NavitCallbackHandler.callbackCmdChannel(), command(), and org.navitproject.navit.NavitCallbackHandler.TAG.
Referenced by org.navitproject.navit.NavitGraphics.NavitView.doZoom(), org.navitproject.navit.Navit.onPause(), org.navitproject.navit.Navit.onResume(), and org.navitproject.navit.Navit.runOptionsItem().
Field Documentation
msg_values
final MsgType [] org.navitproject.navit.NavitCallbackHandler.msg_values = MsgType.values() static private
Referenced by org.navitproject.navit.NavitCallbackHandler.CallBackHandler.handleMessage().
sCallbackHandler
final Handler org.navitproject.navit.NavitCallbackHandler.sCallbackHandler = new CallBackHandler() static package
Referenced by org.navitproject.navit.NavitMapDownloader.deleteMap(), org.navitproject.navit.NavitDialogs.handleMessage(), org.navitproject.navit.Navit.invokeCallbackOnGeo(), org.navitproject.navit.Navit.onActivityResult(), org.navitproject.navit.NavitGraphics.NavitView.onMenuItemClick(), and org.navitproject.navit.Navit.runOptionsItem().
TAG
final String org.navitproject.navit.NavitCallbackHandler.TAG = "CallbackHandler" static private
Referenced by org.navitproject.navit.NavitCallbackHandler.CallBackHandler.handleMessage(), and org.navitproject.navit.NavitCallbackHandler.sendCommand().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitCallbackHandler.java