navit: NGQProxySearch Class Reference
NGQProxySearch Class Reference
#include <searchProxy.h>
Public Slots
void setPointToResult ()
QString searchXml ()
QString countryName ()
void setCountryName (QString countryName)
QString countryISO2 ()
void setCountryISO2 (QString countryISO2)
QString townName ()
void setTownName (QString townName)
QString streetName ()
void setStreetName (QString streetName)
QString searchContext ()
void setSearchContext (QString searchContext)
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Signals
void countryNameSignal (QString)
void countryISO2Signal (QString)
void townNameSignal (QString)
void streetNameSignal (QString)
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Public Member Functions
NGQProxySearch (struct gui_priv *this_, QObject *parent)
~NGQProxySearch ()
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
virtual int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
virtual int setAttrFunc (struct attr *attr)
Protected Member Functions inherited from NGQProxy
virtual struct attr_iter * getIterFunc ()
virtual void dropIterFunc (struct attr_iter *)
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Properties
QString countryName
QString countryISO2
QString townName
QString streetName
QString searchContext
Properties inherited from NGQProxy
int itemId
Private Attributes
struct search_list * sl
QString search_context
QString country_iso2
QString country_name
QString town_name
QString street_name
Additional Inherited Members
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Constructor & Destructor Documentation
NGQProxySearch::NGQProxySearch (struct gui_priv * this_, QObject * parent) inline
References country_default(), country_search_destroy(), country_search_get_item(), country_search_new(), dbg, item, item_attr_get(), lvl_debug, lvl_error, gui_priv::nav, navit_get_mapset(), navit_get_tracking(), NULL, NGQProxy::object, search_context, search_list_get_result(), search_list_new(), search_list_search(), sl, attr::str, tracking_get_attr(), attr::type, and attr::u.
NGQProxySearch::~NGQProxySearch () inline
References search_list_destroy(), and sl.
Member Function Documentation
QString NGQProxySearch::countryISO2 () inline slot
References country_iso2.
Referenced by setCountryISO2().
void NGQProxySearch::countryISO2Signal (QString) signal
Referenced by setCountryISO2().
QString NGQProxySearch::countryName () inline slot
References country_name.
Referenced by setCountryName().
void NGQProxySearch::countryNameSignal (QString) signal
Referenced by setCountryName().
virtual int NGQProxySearch::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
QString NGQProxySearch::searchContext () inline slot
References search_context.
Referenced by setSearchContext().
QString NGQProxySearch::searchXml () inline slot
References NGQProxy::_fieldValueHelper(), search_list_town::common, search_list_result::country, country_name, search_list_common::district_name, entries, search_list_country::iso2, search_list_country::name, search_list_street::name, search_context, search_list_get_result(), search_list_search(), sl, attr::str, search_list_result::street, search_list_result::town, search_list_common::town_name, town_name, attr::type, and attr::u.
virtual int NGQProxySearch::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
void NGQProxySearch::setCountryISO2 (QString countryISO2) inline slot
References country_iso2, countryISO2(), and countryISO2Signal().
Referenced by setCountryName().
void NGQProxySearch::setCountryName (QString countryName) inline slot
References search_list_result::country, country_name, countryName(), countryNameSignal(), search_list_country::iso2, search_list_get_result(), search_list_search(), setCountryISO2(), sl, attr::str, town_name, attr::type, and attr::u.
void NGQProxySearch::setPointToResult () inline slot
References __setNewPoint(), search_list_result::c, country_name, PointOfInterest, search_list_get_result(), search_list_search(), sl, attr::str, town_name, attr::type, and attr::u.
void NGQProxySearch::setSearchContext (QString searchContext) inline slot
References search_context, and searchContext().
void NGQProxySearch::setStreetName (QString streetName) inline slot
References search_list_search(), sl, attr::str, streetName(), streetNameSignal(), attr::type, and attr::u.
void NGQProxySearch::setTownName (QString townName) inline slot
References search_list_search(), sl, attr::str, town_name, townName(), townNameSignal(), attr::type, and attr::u.
QString NGQProxySearch::streetName () inline slot
References street_name.
Referenced by setStreetName().
void NGQProxySearch::streetNameSignal (QString) signal
Referenced by setStreetName().
QString NGQProxySearch::townName () inline slot
References town_name.
Referenced by setTownName().
void NGQProxySearch::townNameSignal (QString) signal
Referenced by setTownName().
Field Documentation
QString NGQProxySearch::country_iso2 private
Referenced by countryISO2(), and setCountryISO2().
QString NGQProxySearch::country_name private
Referenced by countryName(), searchXml(), setCountryName(), and setPointToResult().
QString NGQProxySearch::search_context private
Referenced by NGQProxySearch(), searchContext(), searchXml(), and setSearchContext().
struct search_list* NGQProxySearch::sl private
Referenced by NGQProxySearch(), searchXml(), setCountryName(), setPointToResult(), setStreetName(), setTownName(), and ~NGQProxySearch().
QString NGQProxySearch::street_name private
Referenced by streetName().
QString NGQProxySearch::town_name private
Referenced by searchXml(), setCountryName(), setPointToResult(), setTownName(), and townName().
Property Documentation
QString NGQProxySearch::countryISO2 read write
QString NGQProxySearch::countryName read write
QString NGQProxySearch::searchContext read write
QString NGQProxySearch::streetName read write
QString NGQProxySearch::townName read write
The documentation for this class was generated from the following file:
gui/qml/searchProxy.h