navit: NGQProxyBookmarks Class Reference
NGQProxyBookmarks Class Reference
#include <bookmarksProxy.h>
Public Slots
void moveRoot ()
void moveUp ()
void moveDown (QString path)
QString getBookmarks ()
QString AddFolder (QString description)
QString AddBookmark (QString description)
QString Cut (QString description)
QString Copy (QString description)
QString Paste ()
QString Delete (QString bookmark)
void setPoint (QString bookmark)
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Public Member Functions
NGQProxyBookmarks (struct gui_priv *object, QObject *parent)
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
int setAttrFunc (struct attr *attr)
struct attr_iter * getIterFunc ()
void dropIterFunc (struct attr_iter *iter)
Protected Member Functions inherited from NGQProxy
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Additional Inherited Members
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Properties inherited from NGQProxy
int itemId
Constructor & Destructor Documentation
NGQProxyBookmarks::NGQProxyBookmarks (struct gui_priv * object, QObject * parent) inline
Member Function Documentation
QString NGQProxyBookmarks::AddBookmark (QString description) inline slot
References attr::bookmarks, bookmarks_add_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
QString NGQProxyBookmarks::AddFolder (QString description) inline slot
References attr::bookmarks, bookmarks_add_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
QString NGQProxyBookmarks::Copy (QString description) inline slot
References attr::bookmarks, bookmarks_copy_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
QString NGQProxyBookmarks::Cut (QString description) inline slot
References attr::bookmarks, bookmarks_cut_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
QString NGQProxyBookmarks::Delete (QString bookmark) inline slot
References attr::bookmarks, bookmarks_delete_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
void NGQProxyBookmarks::dropIterFunc (struct attr_iter * iter) inline protected virtual
Reimplemented from NGQProxy.
int NGQProxyBookmarks::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
QString NGQProxyBookmarks::getBookmarks () inline slot
References NGQProxy::_fieldValueHelper(), attr::bookmarks, bookmarks_get_item(), bookmarks_item_cwd(), bookmarks_item_rewind(), dbg, entries, item, item_attr_get(), item_coord_get(), item_to_name(), label, lvl_info, gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, attr::str, item::type, attr::u, coord::x, and coord::y.
struct attr_iter* NGQProxyBookmarks::getIterFunc () inline protected virtual
Reimplemented from NGQProxy.
References NULL.
void NGQProxyBookmarks::moveDown (QString path) inline slot
References attr::bookmarks, bookmarks_move_down(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
void NGQProxyBookmarks::moveRoot () inline slot
References attr::bookmarks, bookmarks_move_root(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
void NGQProxyBookmarks::moveUp () inline slot
References attr::bookmarks, bookmarks_move_up(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
QString NGQProxyBookmarks::Paste () inline slot
References attr::bookmarks, bookmarks_paste_bookmark(), gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, and attr::u.
int NGQProxyBookmarks::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
void NGQProxyBookmarks::setPoint (QString bookmark) inline slot
References Bookmark, attr::bookmarks, bookmarks_get_item(), bookmarks_item_rewind(), gui_priv::currentPoint, dbg, item, item_attr_get(), item_coord_get(), label, lvl_debug, gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, attr::str, item::type, and attr::u.
The documentation for this class was generated from the following file:
gui/qml/bookmarksProxy.h