navit: VehicleObject Class Reference
VehicleObject Class Reference
#include <qml_vehicle.h>
Signals
void nameChanged ()
void activeChanged ()
void vehicleChanged ()
Public Member Functions
VehicleObject (QObject *parent=0)
VehicleObject (const QString &name, const bool &active, struct vehicle *v, QObject *parent=0)
QString name () const
void setName (const QString &name)
bool active () const
void setActive (const bool &active)
struct vehicle * vehicle () const
void setVehicle (struct vehicle *vehicle)
Properties
QString name
bool active
Private Attributes
QString m_name
bool m_active
struct vehicle * m_vehicle
Constructor & Destructor Documentation
VehicleObject() [1/2]
VehicleObject::VehicleObject (QObject * parent = 0)
VehicleObject() [2/2]
VehicleObject::VehicleObject (const QString & name, const bool & active, struct vehicle * v, QObject * parent = 0)
References m_name, and name().
Member Function Documentation
active()
bool VehicleObject::active () const
Referenced by setActive(), and setName().
activeChanged
void VehicleObject::activeChanged () signal
Referenced by setActive().
name()
QString VehicleObject::name () const
Referenced by setName(), and VehicleObject().
nameChanged
void VehicleObject::nameChanged () signal
Referenced by setName().
setActive()
void VehicleObject::setActive (const bool & active)
References active(), activeChanged(), and m_active.
setName()
void VehicleObject::setName (const QString & name)
References active(), m_active, m_name, name(), and nameChanged().
setVehicle()
void VehicleObject::setVehicle (struct vehicle * vehicle)
References m_vehicle, vehicle(), and vehicleChanged().
vehicle()
struct vehicle * VehicleObject::vehicle () const
References m_vehicle.
Referenced by Backend::getSearchResults(), and setVehicle().
vehicleChanged
void VehicleObject::vehicleChanged () signal
Referenced by setVehicle().
Field Documentation
m_active
bool VehicleObject::m_active private
Referenced by setActive(), and setName().
m_name
QString VehicleObject::m_name private
Referenced by setName(), and VehicleObject().
m_vehicle
struct vehicle* VehicleObject::m_vehicle private
Referenced by setVehicle(), and vehicle().
Property Documentation
active
bool VehicleObject::active read write
name
QString VehicleObject::name read write
Referenced by Backend::getSearchResults().
The documentation for this class was generated from the following files:
gui/qt5_qml/qml_vehicle.h
gui/qt5_qml/qml_vehicle.cpp