navit: SearchObject Class Reference
SearchObject Class Reference
#include <qml_search.h>
Signals
void nameChanged ()
void iconChanged ()
Public Member Functions
SearchObject (QObject *parent=0)
SearchObject (const QString &name, const QString &icon, struct pcoord *c, QObject *parent=0)
QString name () const
void setName (const QString &name)
QString icon () const
void setIcon (const QString &icon)
struct pcoord * getCoords () const
Properties
QString name
QString icon
Private Attributes
QString m_name
QString m_icon
struct pcoord * m_c
Constructor & Destructor Documentation
SearchObject::SearchObject (QObject * parent = 0)
SearchObject::SearchObject (const QString & name, const QString & icon, struct pcoord * c, QObject * parent = 0)
Member Function Documentation
struct pcoord * SearchObject::getCoords () const
References m_c.
Referenced by Backend::searchValidateResult().
QString SearchObject::icon () const
Referenced by setIcon().
void SearchObject::iconChanged () signal
Referenced by setIcon().
QString SearchObject::name () const
Referenced by setName().
void SearchObject::nameChanged () signal
Referenced by setName().
void SearchObject::setIcon (const QString & icon)
References icon(), iconChanged(), and m_icon.
void SearchObject::setName (const QString & name)
References m_name, name(), and nameChanged().
Field Documentation
struct pcoord* SearchObject::m_c private
Referenced by getCoords().
QString SearchObject::m_icon private
Referenced by setIcon().
QString SearchObject::m_name private
Referenced by setName().
Property Documentation
QString SearchObject::icon read write
QString SearchObject::name read write
Referenced by Backend::searchValidateResult().
The documentation for this class was generated from the following files:
gui/qt5_qml/qml_search.h
gui/qt5_qml/qml_search.cpp