navit: NGQProxyVehicle Class Reference
NGQProxyVehicle Class Reference
#include <vehicleProxy.h>
Public Member Functions
NGQProxyVehicle (struct gui_priv *object, QObject *parent)
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
int setAttrFunc (struct attr *attr)
struct attr_iter * getIterFunc ()
void dropIterFunc (struct attr_iter *iter)
Protected Member Functions inherited from NGQProxy
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Additional Inherited Members
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Properties inherited from NGQProxy
int itemId
Constructor & Destructor Documentation
NGQProxyVehicle()
NGQProxyVehicle::NGQProxyVehicle (struct gui_priv * object, QObject * parent) inline
Member Function Documentation
dropIterFunc()
void NGQProxyVehicle::dropIterFunc (struct attr_iter * iter) inline protected virtual
Reimplemented from NGQProxy.
References vehicle_attr_iter_destroy().
getAttrFunc()
int NGQProxyVehicle::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
References gui_priv::currVehicle, NGQProxy::object, and vehicle_get_attr().
getIterFunc()
struct attr_iter* NGQProxyVehicle::getIterFunc () inline protected virtual
Reimplemented from NGQProxy.
References vehicle_attr_iter_new().
setAttrFunc()
int NGQProxyVehicle::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
References gui_priv::currVehicle, NGQProxy::object, and vehicle_set_attr().
The documentation for this class was generated from the following file:
gui/qml/vehicleProxy.h