navit: org.navitproject.navit.Navit Class Reference
org.navitproject.navit.Navit Class Reference
Data Structures
class SoftInputRestorer
A Runnable to restore soft input when the user returns to the activity.
Public Member Functions
void removeFileIfExists (String source)
void copyFileIfExists (String source, String destination) throws IOException
void onCreate (Bundle savedInstanceState)
void onResume ()
void onPause ()
void onRequestPermissionsResult (int requestCode, String[] permissions, int[] grantResults)
void setActivityResult (int requestCode, NavitActivityResult ActivityResult)
boolean onPrepareOptionsMenu (Menu menu)
void setKeypressCallback (int kp_cb_id, NavitGraphics ng)
void setMotionCallback (int mo_cb_id, NavitGraphics ng)
NavitGraphics getNavitGraphics ()
void start_targetsearch_from_intent (String target_address)
boolean onOptionsItemSelected (MenuItem item)
void runOptionsItem (int id)
void showMenu ()
int showNativeKeyboard ()
void hideNativeKeyboard ()
boolean onSearchRequested ()
void onDestroy ()
void fullscreen (int fullscreen)
void disableSuspend ()
native void NavitMain (Navit x, String lang, int version, String display_density_string, String path, String path2)
native void NavitDestroy ()
Static Public Member Functions
static Navit getInstance ()
Static Public Attributes
static InputMethodManager mgr = null
static DisplayMetrics metrics = null
static int status_bar_height = 0
static int navigation_bar_height = 0
static int navigation_bar_height_landscape = 0
static int navigation_bar_width = 0
static Boolean show_soft_keyboard = false
static Boolean show_soft_keyboard_now_showing = false
static long last_pressed_menu_key = 0L
static long time_pressed_menu_key = 0L
static final String NAVIT_PREFS = "NavitPrefs"
Protected Member Functions
void onActivityResult (int requestCode, int resultCode, Intent data)
void onPrepareDialog (int id, Dialog dialog)
Dialog onCreateDialog (int id)
Package Functions
String getTstring (int Rid)
void setDestination (float latitude, float longitude, String address)
Static Package Functions
[static initializer]
Package Attributes
Boolean isFullscreen = false
Static Package Attributes
static String map_filename_path = null
static final String NAVIT_DATA_DIR = "/data/data/" + NAVIT_PACKAGE_NAME
Private Member Functions
boolean resourceFileNeedsUpdate (String filename)
boolean extractRes (String resname, String result)
boolean extractAsset (String assetFileName, String output)
void showInfos ()
void parseNavigationURI (String schemeSpecificPart)
void setMapLocation ()
void exit ()
String getLocalizedString (String text)
Private Attributes
NavitDialogs dialogs
PowerManager.WakeLock wl
NavitActivityResult [] ActivityResults
NavitGraphics N_NavitGraphics = null
Static Private Attributes
static int action_bar_default_height = 0
static Intent startup_intent = null
static long startup_intent_timestamp = 0L
static String my_display_density = "mdpi"
static final int NavitDownloaderSelectMap_id = 967
static final int NavitAddressSearch_id = 70
static final int NavitSelectStorage_id = 43
static String NavitLanguage
static Resources NavitResources = null
static final String NAVIT_PACKAGE_NAME = "org.navitproject.navit"
static final String TAG = "Navit"
static final String NAVIT_DATA_SHARE_DIR = NAVIT_DATA_DIR + "/share"
static final int MY_PERMISSIONS_REQUEST_ALL = 101
static NotificationManager nm
static Navit navit
Member Function Documentation
[static initializer]()
org.navitproject.navit.Navit.[static initializer] () inline static package
copyFileIfExists()
void org.navitproject.navit.Navit.copyFileIfExists (String source, String destination) throws IOException inline
Referenced by org.navitproject.navit.NavitBackupTask.doInBackground(), and org.navitproject.navit.NavitRestoreTask.doInBackground().
disableSuspend()
void org.navitproject.navit.Navit.disableSuspend () inline
References org.navitproject.navit.Navit.wl.
exit()
void org.navitproject.navit.Navit.exit () inline private
References org.navitproject.navit.Navit.NavitDestroy(), org.navitproject.navit.Navit.NavitMain(), org.navitproject.navit.NavitVehicle.removeListener(), and version.
Referenced by org.navitproject.navit.Navit.onRequestPermissionsResult(), and org.navitproject.navit.Navit.runOptionsItem().
extractAsset()
boolean org.navitproject.navit.Navit.extractAsset (String assetFileName, String output) inline private
Extract an asset from the apk archive (assets) and save it to a local file
Parameters
output The full path to the output local file
assetFileName The full path of the asset file within the archive
Returns
true if the local file is extracted in output
References org.navitproject.navit.Navit.resourceFileNeedsUpdate().
Referenced by org.navitproject.navit.Navit.onCreate().
extractRes()
boolean org.navitproject.navit.Navit.extractRes (String resname, String result) inline private
Extract a ressource from the apk archive (res/raw) and save it to a local file
Parameters
result The full path to the local file
resname The name of the ressource file in the archive
Returns
true if the local file is extracted in result
References org.navitproject.navit.Navit.resourceFileNeedsUpdate().
Referenced by org.navitproject.navit.Navit.onCreate().
fullscreen()
void org.navitproject.navit.Navit.fullscreen (int fullscreen) inline
References org.navitproject.navit.NavitGraphics.handleResize(), and size.
getInstance()
static Navit org.navitproject.navit.Navit.getInstance () inline static
References org.navitproject.navit.Navit.navit.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.askForMapDeletion(), org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), org.navitproject.navit.NavitDialogs.createDialog(), org.navitproject.navit.NavitMapDownloader.deleteMap(), org.navitproject.navit.NavitDialogs.handleMessage(), org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate(), org.navitproject.navit.NavitAddressSearchActivity.onCreate(), org.navitproject.navit.NavitMapDownloader.readData(), org.navitproject.navit.NavitAddressSearchActivity.receiveAddress(), org.navitproject.navit.NavitMapDownloader.run(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
getLocalizedString()
String org.navitproject.navit.Navit.getLocalizedString (String text) inline private
References org.navitproject.navit.NavitGraphics.CallbackLocalizedString().
Referenced by org.navitproject.navit.Navit.getTstring().
getNavitGraphics()
NavitGraphics org.navitproject.navit.Navit.getNavitGraphics () inline
References org.navitproject.navit.Navit.N_NavitGraphics.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.askForMapDeletion(), org.navitproject.navit.NavitMapDownloader.deleteMap(), and org.navitproject.navit.NavitDialogs.handleMessage().
getTstring()
String org.navitproject.navit.Navit.getTstring (int Rid) inline package
Translates a string from its id in R.strings
Parameters
Rid resource identifier
Returns
translated string
References org.navitproject.navit.Navit.getLocalizedString().
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.askForMapDeletion(), org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), org.navitproject.navit.NavitDialogs.createDialog(), org.navitproject.navit.NavitBackupTask.doInBackground(), org.navitproject.navit.NavitRestoreTask.doInBackground(), org.navitproject.navit.NavitSpeech2.onActivityResult(), org.navitproject.navit.Navit.onActivityResult(), org.navitproject.navit.NavitBackupTask.onCancelled(), org.navitproject.navit.NavitRestoreTask.onCancelled(), org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate(), org.navitproject.navit.NavitAddressSearchActivity.onCreate(), org.navitproject.navit.Navit.onCreate(), org.navitproject.navit.NavitGraphics.NavitView.onCreateContextMenu(), org.navitproject.navit.NavitBackupTask.onPostExecute(), org.navitproject.navit.NavitRestoreTask.onPostExecute(), org.navitproject.navit.NavitBackupTask.onPreExecute(), org.navitproject.navit.NavitRestoreTask.onPreExecute(), org.navitproject.navit.Navit.onPrepareOptionsMenu(), org.navitproject.navit.Navit.onRequestPermissionsResult(), org.navitproject.navit.NavitMapDownloader.readData(), org.navitproject.navit.NavitAddressSearchActivity.receiveAddress(), org.navitproject.navit.NavitMapDownloader.run(), org.navitproject.navit.Navit.setDestination(), org.navitproject.navit.Navit.showInfos(), org.navitproject.navit.Navit.start_targetsearch_from_intent(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
hideNativeKeyboard()
void org.navitproject.navit.Navit.hideNativeKeyboard () inline
Hides the native keyboard or other input method.
Referenced by org.navitproject.navit.Navit.onPause().
NavitDestroy()
native void org.navitproject.navit.Navit.NavitDestroy ()
Referenced by org.navitproject.navit.Navit.exit(), and org.navitproject.navit.Navit.onDestroy().
NavitMain()
native void org.navitproject.navit.Navit.NavitMain (Navit x, String lang, int version, String display_density_string, String path, String path2)
Referenced by org.navitproject.navit.Navit.exit(), and org.navitproject.navit.Navit.onCreate().
onActivityResult()
void org.navitproject.navit.Navit.onActivityResult (int requestCode, int resultCode, Intent data) inline protected
References org.navitproject.navit.NavitGraphics.callback_handler, org.navitproject.navit.NavitGraphics.msg_type.CLB_SET_DESTINATION, org.navitproject.navit.Navit.getTstring(), org.navitproject.navit.NavitDialogs.MSG_START_MAP_DOWNLOAD, org.navitproject.navit.Navit.NavitAddressSearch_id, org.navitproject.navit.Navit.NavitDownloaderSelectMap_id, org.navitproject.navit.Navit.NavitSelectStorage_id, org.navitproject.navit.NavitActivityResult.onActivityResult(), and org.navitproject.navit.FileBrowserActivity.returnDirectoryParameter.
onCreate()
void org.navitproject.navit.Navit.onCreate (Bundle savedInstanceState) inline
Called when the activity is first created.
References org.navitproject.navit.Navit.extractAsset(), org.navitproject.navit.Navit.extractRes(), org.navitproject.navit.Navit.getTstring(), org.navitproject.navit.Navit.map_filename_path, org.navitproject.navit.Navit.metrics, org.navitproject.navit.Navit.mgr, org.navitproject.navit.Navit.my_display_density, org.navitproject.navit.Navit.MY_PERMISSIONS_REQUEST_ALL, org.navitproject.navit.Navit.NavitMain(), startup.pos, org.navitproject.navit.Navit.showInfos(), org.navitproject.navit.Navit.startup_intent, org.navitproject.navit.Navit.startup_intent_timestamp, and org.navitproject.navit.Navit.wl.
onCreateDialog()
Dialog org.navitproject.navit.Navit.onCreateDialog (int id) inline protected
References org.navitproject.navit.NavitDialogs.createDialog().
onDestroy()
void org.navitproject.navit.Navit.onDestroy () inline
References org.navitproject.navit.Navit.NavitDestroy().
onOptionsItemSelected()
boolean org.navitproject.navit.Navit.onOptionsItemSelected (MenuItem item) inline
References org.navitproject.navit.Navit.runOptionsItem().
onPause()
void org.navitproject.navit.Navit.onPause () inline
References org.navitproject.navit.Navit.hideNativeKeyboard().
onPrepareDialog()
void org.navitproject.navit.Navit.onPrepareDialog (int id, Dialog dialog) inline protected
References org.navitproject.navit.NavitDialogs.prepareDialog().
onPrepareOptionsMenu()
boolean org.navitproject.navit.Navit.onPrepareOptionsMenu (Menu menu) inline
References org.navitproject.navit.Navit.getTstring().
onRequestPermissionsResult()
void org.navitproject.navit.Navit.onRequestPermissionsResult (int requestCode, String [] permissions, int [] grantResults) inline
References org.navitproject.navit.Navit.exit(), org.navitproject.navit.Navit.getTstring(), and org.navitproject.navit.Navit.MY_PERMISSIONS_REQUEST_ALL.
onResume()
void org.navitproject.navit.Navit.onResume () inline
References L, org.navitproject.navit.Navit.parseNavigationURI(), and org.navitproject.navit.Navit.startup_intent_timestamp.
onSearchRequested()
boolean org.navitproject.navit.Navit.onSearchRequested () inline
parseNavigationURI()
void org.navitproject.navit.Navit.parseNavigationURI (String schemeSpecificPart) inline private
References org.navitproject.navit.NavitGraphics.callback_handler, org.navitproject.navit.NavitGraphics.msg_type.CLB_SET_DESTINATION, lat, org.navitproject.navit.Navit.N_NavitGraphics, p, and org.navitproject.navit.Navit.start_targetsearch_from_intent().
Referenced by org.navitproject.navit.Navit.onResume().
removeFileIfExists()
void org.navitproject.navit.Navit.removeFileIfExists (String source) inline
Referenced by org.navitproject.navit.NavitRestoreTask.doInBackground().
resourceFileNeedsUpdate()
boolean org.navitproject.navit.Navit.resourceFileNeedsUpdate (String filename) inline private
Check if a specific file needs to be extracted from the apk archive This is based on whether the file already exist, and if so, whether it is older than the archive or not
Parameters
filename The full path to the file
Returns
true if file does not exist, but it can be created at the specified location, we will also return true if the file exist but the apk archive is more recent (probably package was upgraded)
Referenced by org.navitproject.navit.Navit.extractAsset(), and org.navitproject.navit.Navit.extractRes().
runOptionsItem()
void org.navitproject.navit.Navit.runOptionsItem (int id) inline
References org.navitproject.navit.NavitGraphics.callback_handler, org.navitproject.navit.NavitGraphics.msg_type.CLB_CALL_CMD, org.navitproject.navit.NavitGraphics.msg_type.CLB_ZOOM_IN, org.navitproject.navit.NavitGraphics.msg_type.CLB_ZOOM_OUT, org.navitproject.navit.NavitDialogs.DIALOG_BACKUP_RESTORE, org.navitproject.navit.Navit.exit(), org.navitproject.navit.Navit.NavitDownloaderSelectMap_id, and org.navitproject.navit.Navit.setMapLocation().
Referenced by org.navitproject.navit.Navit.onOptionsItemSelected().
setActivityResult()
void org.navitproject.navit.Navit.setActivityResult (int requestCode, NavitActivityResult ActivityResult) inline
Referenced by org.navitproject.navit.NavitSpeech2.NavitSpeech2().
setDestination()
void org.navitproject.navit.Navit.setDestination (float latitude, float longitude, String address) inline package
References org.navitproject.navit.NavitGraphics.callback_handler, org.navitproject.navit.NavitGraphics.msg_type.CLB_SET_DESTINATION, and org.navitproject.navit.Navit.getTstring().
setKeypressCallback()
void org.navitproject.navit.Navit.setKeypressCallback (int kp_cb_id, NavitGraphics ng) inline
Referenced by org.navitproject.navit.NavitGraphics.setKeypressCallback().
setMapLocation()
void org.navitproject.navit.Navit.setMapLocation () inline private
References org.navitproject.navit.FileBrowserActivity.INTENT_ACTION_SELECT_DIR, and org.navitproject.navit.FileBrowserActivity.startDirectoryParameter.
Referenced by org.navitproject.navit.Navit.runOptionsItem().
setMotionCallback()
void org.navitproject.navit.Navit.setMotionCallback (int mo_cb_id, NavitGraphics ng) inline
Referenced by org.navitproject.navit.NavitGraphics.setMotionCallback().
showInfos()
void org.navitproject.navit.Navit.showInfos () inline private
References org.navitproject.navit.Navit.getTstring().
Referenced by org.navitproject.navit.Navit.onCreate().
showMenu()
void org.navitproject.navit.Navit.showMenu () inline
Shows the Options menu.
Calling this method has the same effect as pressing the hardware Menu button, where present, or touching the overflow button in the Action bar.
showNativeKeyboard()
int org.navitproject.navit.Navit.showNativeKeyboard () inline
Shows the native keyboard or other input method.
Referenced by org.navitproject.navit.Navit.SoftInputRestorer.run().
start_targetsearch_from_intent()
void org.navitproject.navit.Navit.start_targetsearch_from_intent (String target_address) inline
References org.navitproject.navit.Navit.getTstring().
Referenced by org.navitproject.navit.Navit.parseNavigationURI().
Field Documentation
action_bar_default_height
int org.navitproject.navit.Navit.action_bar_default_height = 0 static private
ActivityResults
NavitActivityResult [] org.navitproject.navit.Navit.ActivityResults private
dialogs
NavitDialogs org.navitproject.navit.Navit.dialogs private
isFullscreen
Boolean org.navitproject.navit.Navit.isFullscreen = false package
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
last_pressed_menu_key
long org.navitproject.navit.Navit.last_pressed_menu_key = 0L static
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onKeyDown().
map_filename_path
String org.navitproject.navit.Navit.map_filename_path = null static package
Referenced by org.navitproject.navit.NavitMapDownloader.getAvailableMaps(), org.navitproject.navit.NavitDownloadSelectMapActivity.getFreeSpace(), org.navitproject.navit.NavitMapDownloader.NavitMapDownloader(), org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate(), and org.navitproject.navit.Navit.onCreate().
metrics
DisplayMetrics org.navitproject.navit.Navit.metrics = null static
Referenced by org.navitproject.navit.Navit.onCreate(), org.navitproject.navit.NavitGraphics.NavitView.onSizeChanged(), and org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage().
mgr
InputMethodManager org.navitproject.navit.Navit.mgr = null static
Referenced by org.navitproject.navit.Navit.onCreate(), and org.navitproject.navit.NavitGraphics.NavitView.onDraw().
my_display_density
String org.navitproject.navit.Navit.my_display_density = "mdpi" static private
Referenced by org.navitproject.navit.Navit.onCreate().
MY_PERMISSIONS_REQUEST_ALL
final int org.navitproject.navit.Navit.MY_PERMISSIONS_REQUEST_ALL = 101 static private
Referenced by org.navitproject.navit.Navit.onCreate(), and org.navitproject.navit.Navit.onRequestPermissionsResult().
N_NavitGraphics
NavitGraphics org.navitproject.navit.Navit.N_NavitGraphics = null private
Referenced by org.navitproject.navit.Navit.getNavitGraphics(), and org.navitproject.navit.Navit.parseNavigationURI().
navigation_bar_height
int org.navitproject.navit.Navit.navigation_bar_height = 0 static
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
navigation_bar_height_landscape
int org.navitproject.navit.Navit.navigation_bar_height_landscape = 0 static
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
navigation_bar_width
int org.navitproject.navit.Navit.navigation_bar_width = 0 static
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
navit
Navit org.navitproject.navit.Navit.navit static private
Referenced by org.navitproject.navit.Navit.getInstance().
NAVIT_DATA_DIR
final String org.navitproject.navit.Navit.NAVIT_DATA_DIR = "/data/data/" + NAVIT_PACKAGE_NAME static package
Referenced by org.navitproject.navit.NavitBackupTask.doInBackground(), and org.navitproject.navit.NavitRestoreTask.doInBackground().
NAVIT_DATA_SHARE_DIR
final String org.navitproject.navit.Navit.NAVIT_DATA_SHARE_DIR = NAVIT_DATA_DIR + "/share" static private
NAVIT_PACKAGE_NAME
final String org.navitproject.navit.Navit.NAVIT_PACKAGE_NAME = "org.navitproject.navit" static private
NAVIT_PREFS
final String org.navitproject.navit.Navit.NAVIT_PREFS = "NavitPrefs" static
Referenced by org.navitproject.navit.NavitBackupTask.doInBackground(), org.navitproject.navit.NavitRestoreTask.doInBackground(), org.navitproject.navit.NavitAppConfig.onCreate(), org.navitproject.navit.NavitAddressSearchActivity.onCreate(), and org.navitproject.navit.NavitAddressSearchActivity.requestCountryDialog().
NavitAddressSearch_id
final int org.navitproject.navit.Navit.NavitAddressSearch_id = 70 static private
Referenced by org.navitproject.navit.Navit.onActivityResult().
NavitDownloaderSelectMap_id
final int org.navitproject.navit.Navit.NavitDownloaderSelectMap_id = 967 static private
Referenced by org.navitproject.navit.Navit.onActivityResult(), and org.navitproject.navit.Navit.runOptionsItem().
NavitLanguage
String org.navitproject.navit.Navit.NavitLanguage static private
NavitResources
Resources org.navitproject.navit.Navit.NavitResources = null static private
NavitSelectStorage_id
final int org.navitproject.navit.Navit.NavitSelectStorage_id = 43 static private
Referenced by org.navitproject.navit.Navit.onActivityResult().
nm
NotificationManager org.navitproject.navit.Navit.nm static private
show_soft_keyboard
Boolean org.navitproject.navit.Navit.show_soft_keyboard = false static
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onDraw(), and org.navitproject.navit.NavitGraphics.NavitView.onKeyDown().
show_soft_keyboard_now_showing
Boolean org.navitproject.navit.Navit.show_soft_keyboard_now_showing = false static
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onDraw(), and org.navitproject.navit.NavitGraphics.NavitView.onKeyUp().
startup_intent
Intent org.navitproject.navit.Navit.startup_intent = null static private
Referenced by org.navitproject.navit.Navit.onCreate().
startup_intent_timestamp
long org.navitproject.navit.Navit.startup_intent_timestamp = 0L static private
Referenced by org.navitproject.navit.Navit.onCreate(), and org.navitproject.navit.Navit.onResume().
status_bar_height
int org.navitproject.navit.Navit.status_bar_height = 0 static
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
TAG
final String org.navitproject.navit.Navit.TAG = "Navit" static private
time_pressed_menu_key
long org.navitproject.navit.Navit.time_pressed_menu_key = 0L static
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onKeyDown().
wl
PowerManager.WakeLock org.navitproject.navit.Navit.wl private
Referenced by org.navitproject.navit.Navit.disableSuspend(), and org.navitproject.navit.Navit.onCreate().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/Navit.java