navit: org.navitproject.navit.NavitGraphics.NavitView Class Reference
org.navitproject.navit.NavitGraphics.NavitView Class Reference
Public Member Functions
void onWindowFocusChanged (boolean hasWindowFocus)
WindowInsets onApplyWindowInsets (WindowInsets insets)
boolean onMenuItemClick (MenuItem item)
boolean onTouchEvent (MotionEvent event)
boolean onKeyDown (int keyCode, KeyEvent event)
boolean onKeyUp (int keyCode, KeyEvent event)
boolean onKeyMultiple (int keyCode, int count, KeyEvent event)
boolean onTrackballEvent (MotionEvent event)
void run ()
Protected Member Functions
void onCreateContextMenu (ContextMenu menu)
void onDraw (Canvas canvas)
void onSizeChanged (int w, int h, int oldw, int oldh)
Package Functions
NavitView (Context context)
boolean isDrag ()
void doLongpressAction ()
Package Attributes
int mTouchMode = NONE
float mOldDist = 0
PointF mPressedPosition = null
Static Package Attributes
static final int NONE = 0
static final int DRAG = 1
static final int ZOOM = 2
static final int PRESSED = 3
Private Member Functions
void doZoom (MotionEvent event)
float spacing (MotionEvent event)
float spacing (PointF a, PointF b)
Static Private Attributes
static final int MENU_DRIVE_HERE = 1
static final int MENU_VIEW = 2
static final int MENU_CANCEL = 3
Constructor & Destructor Documentation
NavitView()
org.navitproject.navit.NavitGraphics.NavitView.NavitView (Context context) inline package
Referenced by org.navitproject.navit.NavitGraphics.setmActivity().
Member Function Documentation
doLongpressAction()
void org.navitproject.navit.NavitGraphics.NavitView.doLongpressAction () inline package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.run().
doZoom()
void org.navitproject.navit.NavitGraphics.NavitView.doZoom (MotionEvent event) inline private
References org.navitproject.navit.NavitGraphics.callbackMessageChannel(), org.navitproject.navit.NavitGraphics.NavitView.mOldDist, and org.navitproject.navit.NavitGraphics.NavitView.spacing().
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
isDrag()
boolean org.navitproject.navit.NavitGraphics.NavitView.isDrag () inline package
References org.navitproject.navit.NavitGraphics.NavitView.DRAG.
Referenced by org.navitproject.navit.NavitGraphics.workAroundForGuiInternal().
onApplyWindowInsets()
WindowInsets org.navitproject.navit.NavitGraphics.NavitView.onApplyWindowInsets (WindowInsets insets) inline
References org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews(), height, org.navitproject.navit.NavitGraphics.mSizeChangedCallbackID, org.navitproject.navit.NavitGraphics.sizeChangedCallback(), and width.
onCreateContextMenu()
void org.navitproject.navit.NavitGraphics.NavitView.onCreateContextMenu (ContextMenu menu) inline protected
References org.navitproject.navit.NavitGraphics.getCoordForPoint(), org.navitproject.navit.NavitAppConfig.getTstring(), org.navitproject.navit.NavitGraphics.NavitView.mPressedPosition, and org.navitproject.navit.NavitGraphics.NavitView.NONE.
onDraw()
void org.navitproject.navit.NavitGraphics.NavitView.onDraw (Canvas canvas) inline protected
References org.navitproject.navit.NavitGraphics.mDrawBitmap.
onKeyDown()
boolean org.navitproject.navit.NavitGraphics.NavitView.onKeyDown (int keyCode, KeyEvent event) inline
References org.navitproject.navit.NavitGraphics.keypressCallback(), and org.navitproject.navit.NavitGraphics.mKeypressCallbackID.
onKeyMultiple()
boolean org.navitproject.navit.NavitGraphics.NavitView.onKeyMultiple (int keyCode, int count, KeyEvent event) inline
References org.navitproject.navit.NavitGraphics.keypressCallback(), and org.navitproject.navit.NavitGraphics.mKeypressCallbackID.
onKeyUp()
boolean org.navitproject.navit.NavitGraphics.NavitView.onKeyUp (int keyCode, KeyEvent event) inline
References org.navitproject.navit.NavitGraphics.keypressCallback(), org.navitproject.navit.NavitGraphics.mKeypressCallbackID, and org.navitproject.navit.Navit.sShowSoftKeyboardShowing.
onMenuItemClick()
boolean org.navitproject.navit.NavitGraphics.NavitView.onMenuItemClick (MenuItem item) inline
References org.navitproject.navit.NavitGraphics.MsgType.CLB_SET_DISPLAY_DESTINATION, org.navitproject.navit.NavitGraphics.getCoordForPoint(), and org.navitproject.navit.NavitGraphics.NavitView.mPressedPosition.
onSizeChanged()
void org.navitproject.navit.NavitGraphics.NavitView.onSizeChanged (int w, int h, int oldw, int oldh) inline protected
References org.navitproject.navit.NavitGraphics.handleResize(), org.navitproject.navit.NavitGraphics.mDrawBitmap, org.navitproject.navit.NavitGraphics.mDrawCanvas, org.navitproject.navit.NavitGraphics.mSizeChangedCallbackID, org.navitproject.navit.NavitGraphics.sizeChangedCallback(), and org.navitproject.navit.Navit.sMetrics.
onTouchEvent()
boolean org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent (MotionEvent event) inline
References org.navitproject.navit.NavitGraphics.buttonCallback(), org.navitproject.navit.NavitGraphics.NavitView.doZoom(), org.navitproject.navit.NavitGraphics.NavitView.DRAG, org.navitproject.navit.NavitGraphics.mButtonCallbackID, org.navitproject.navit.NavitGraphics.mMotionCallbackID, org.navitproject.navit.NavitGraphics.NavitView.mOldDist, org.navitproject.navit.NavitGraphics.motionCallback(), org.navitproject.navit.NavitGraphics.NavitView.mPressedPosition, org.navitproject.navit.NavitGraphics.NavitView.mTouchMode, org.navitproject.navit.NavitGraphics.NavitView.NONE, org.navitproject.navit.NavitGraphics.NavitView.PRESSED, org.navitproject.navit.NavitGraphics.NavitView.spacing(), and org.navitproject.navit.NavitGraphics.NavitView.ZOOM.
onTrackballEvent()
boolean org.navitproject.navit.NavitGraphics.NavitView.onTrackballEvent (MotionEvent event) inline
References org.navitproject.navit.NavitGraphics.keypressCallback(), and org.navitproject.navit.NavitGraphics.mKeypressCallbackID.
onWindowFocusChanged()
void org.navitproject.navit.NavitGraphics.NavitView.onWindowFocusChanged (boolean hasWindowFocus) inline
References org.navitproject.navit.Navit.sShowSoftKeyboardShowing.
run()
void org.navitproject.navit.NavitGraphics.NavitView.run () inline
References org.navitproject.navit.NavitGraphics.NavitView.doLongpressAction(), org.navitproject.navit.NavitGraphics.NavitView.mTouchMode, org.navitproject.navit.NavitGraphics.NavitView.NONE, and org.navitproject.navit.NavitGraphics.NavitView.PRESSED.
Referenced by org.navitproject.navit.NavitGraphics.adjustSystemBarsTintingViews().
spacing() [1/2]
float org.navitproject.navit.NavitGraphics.NavitView.spacing (MotionEvent event) inline private
Referenced by org.navitproject.navit.NavitGraphics.NavitView.doZoom(), and org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
spacing() [2/2]
float org.navitproject.navit.NavitGraphics.NavitView.spacing (PointF a, PointF b) inline private
Field Documentation
DRAG
final int org.navitproject.navit.NavitGraphics.NavitView.DRAG = 1 static package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.isDrag(), and org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
MENU_CANCEL
final int org.navitproject.navit.NavitGraphics.NavitView.MENU_CANCEL = 3 static private
MENU_DRIVE_HERE
final int org.navitproject.navit.NavitGraphics.NavitView.MENU_DRIVE_HERE = 1 static private
MENU_VIEW
final int org.navitproject.navit.NavitGraphics.NavitView.MENU_VIEW = 2 static private
mOldDist
float org.navitproject.navit.NavitGraphics.NavitView.mOldDist = 0 package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.doZoom(), and org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
mPressedPosition
PointF org.navitproject.navit.NavitGraphics.NavitView.mPressedPosition = null package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onCreateContextMenu(), org.navitproject.navit.NavitGraphics.NavitView.onMenuItemClick(), and org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
mTouchMode
int org.navitproject.navit.NavitGraphics.NavitView.mTouchMode = NONE package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent(), and org.navitproject.navit.NavitGraphics.NavitView.run().
NONE
final int org.navitproject.navit.NavitGraphics.NavitView.NONE = 0 static package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onCreateContextMenu(), org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent(), and org.navitproject.navit.NavitGraphics.NavitView.run().
PRESSED
final int org.navitproject.navit.NavitGraphics.NavitView.PRESSED = 3 static package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent(), and org.navitproject.navit.NavitGraphics.NavitView.run().
ZOOM
final int org.navitproject.navit.NavitGraphics.NavitView.ZOOM = 2 static package
Referenced by org.navitproject.navit.NavitGraphics.NavitView.onTouchEvent().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitGraphics.java