navit: QNavitWidget Class Reference
QNavitWidget Class Reference
#include <QNavitWidget.h>
Public Member Functions
QNavitWidget (struct graphics_priv *my_graphics_priv, QWidget *parent, Qt::WindowFlags flags)
Protected Member Functions
virtual bool event (QEvent *event)
virtual void keyPressEvent (QKeyEvent *event)
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void mouseEvent (int pressed, QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
Private Attributes
struct graphics_priv * graphics_priv
Constructor & Destructor Documentation
QNavitWidget::QNavitWidget (struct graphics_priv * my_graphics_priv, QWidget * parent, Qt::WindowFlags flags)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Member Function Documentation
bool QNavitWidget::event (QEvent * event) protected virtual
References dbg, and lvl_debug.
void QNavitWidget::keyPressEvent (QKeyEvent * event) protected virtual
References callback_list_call_attr_1, graphics_priv::callbacks, dbg, key, lvl_debug, NAVIT_KEY_BACK, NAVIT_KEY_BACKSPACE, NAVIT_KEY_DELETE, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_PAGE_DOWN, NAVIT_KEY_PAGE_UP, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_TAB, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, NAVIT_KEY_ZOOM_OUT, and NULL.
void QNavitWidget::mouseEvent (int pressed, QMouseEvent * event) protected virtual
References callback_list_call_attr_3, graphics_priv::callbacks, GINT_TO_POINTER, point::x, and point::y.
Referenced by mousePressEvent(), and mouseReleaseEvent().
void QNavitWidget::mouseMoveEvent (QMouseEvent * event) protected virtual
References callback_list_call_attr_1, graphics_priv::callbacks, point::x, and point::y.
void QNavitWidget::mousePressEvent (QMouseEvent * event) protected virtual
References mouseEvent().
void QNavitWidget::mouseReleaseEvent (QMouseEvent * event) protected virtual
References mouseEvent().
void QNavitWidget::paintEvent (QPaintEvent * event) protected virtual
References graphics_priv::background_graphics_gc_priv, graphics_gc_priv::brush, dbg, lvl_debug, NULL, graphics_priv::painter, paintOverlays(), graphics_gc_priv::pen, graphics_priv::pixmap, graphics_priv::scroll_x, and graphics_priv::scroll_y.
void QNavitWidget::resizeEvent (QResizeEvent * event) protected virtual
References dbg, height, lvl_debug, NULL, graphics_priv::painter, graphics_priv::pixmap, resize_callback(), graphics_priv::root, size, and width.
void QNavitWidget::wheelEvent (QWheelEvent * event) protected virtual
References callback_list_call_attr_3, graphics_priv::callbacks, dbg, GINT_TO_POINTER, lvl_debug, point::x, and point::y.
Field Documentation
struct graphics_priv* QNavitWidget::graphics_priv private
The documentation for this class was generated from the following files:
graphics/qt5/QNavitWidget.h
graphics/qt5/QNavitWidget.cpp