navit: BookmarkObject Class Reference
BookmarkObject Class Reference
#include <qml_bookmark.h>
Signals
void nameChanged ()
Public Member Functions
BookmarkObject (QObject *parent=0)
BookmarkObject (const QString &name, struct pcoord &coords, QObject *parent=0)
QString name () const
void setName (const QString &name)
struct pcoord coords () const
Properties
QString name
Private Attributes
struct pcoord m_coords
QString m_name
Constructor & Destructor Documentation
BookmarkObject() [1/2]
BookmarkObject::BookmarkObject (QObject * parent = 0)
BookmarkObject() [2/2]
BookmarkObject::BookmarkObject (const QString & name, struct pcoord & coords, QObject * parent = 0)
References m_name, and name().
Member Function Documentation
coords()
struct pcoord BookmarkObject::coords () const
References m_coords.
name()
QString BookmarkObject::name () const
Referenced by BookmarkObject(), and setName().
nameChanged
void BookmarkObject::nameChanged () signal
Referenced by setName().
setName()
void BookmarkObject::setName (const QString & name)
References m_name, name(), and nameChanged().
Field Documentation
m_coords
struct pcoord BookmarkObject::m_coords private
Referenced by coords().
m_name
QString BookmarkObject::m_name private
Referenced by BookmarkObject(), and setName().
Property Documentation
name
QString BookmarkObject::name read write
The documentation for this class was generated from the following files:
gui/qt5_qml/qml_bookmark.h
gui/qt5_qml/qml_bookmark.cpp