navit: RenderArea Class Reference
RenderArea Class Reference
#include <RenderArea.h>
Public Member Functions
RenderArea (struct graphics_priv *priv, QT_QPAINTER_RENDERAREA_PARENT *parent=0, int w=800, int h=800, int overlay=0)
void do_resize (QSize size)
void processClose ()
Data Fields
QPixmap * pixmap
struct callback_list * cbl
struct graphics_priv * gra
Protected Slots
void watchEvent (int fd)
Protected Member Functions
QSize sizeHint () const
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
void mouseEvent (int pressed, QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
void keyPressEvent (QKeyEvent *event)
void closeEvent (QCloseEvent *event)
bool event (QEvent *event)
Protected Attributes
int is_overlay
Detailed Description
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Constructor & Destructor Documentation
RenderArea()
RenderArea::RenderArea (struct graphics_priv * priv, QT_QPAINTER_RENDERAREA_PARENT * parent = 0, int w = 800, int h = 800, int overlay = 0)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References gra, is_overlay, pixmap, and graphics_priv::window_title.
Member Function Documentation
closeEvent()
void RenderArea::closeEvent (QCloseEvent * event) protected
References processClose().
do_resize()
void RenderArea::do_resize (QSize size)
References callback_list_call_attr_2, cbl, dbg, lvl_debug, and pixmap.
Referenced by resizeEvent().
event()
bool RenderArea::event (QEvent * event) protected
References dbg, and lvl_debug.
keyPressEvent()
void RenderArea::keyPressEvent (QKeyEvent * event) protected
References callback_list_call_attr_1, cbl, dbg, lvl_debug, NAVIT_KEY_BACKSPACE, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, and NAVIT_KEY_UP.
mouseEvent()
void RenderArea::mouseEvent (int pressed, QMouseEvent * event) protected
References callback_list_call_attr_3, cbl, point::x, and point::y.
Referenced by mousePressEvent(), and mouseReleaseEvent().
mouseMoveEvent()
void RenderArea::mouseMoveEvent (QMouseEvent * event) protected
References callback_list_call_attr_1, cbl, point::x, and point::y.
mousePressEvent()
void RenderArea::mousePressEvent (QMouseEvent * event) protected
References mouseEvent().
mouseReleaseEvent()
void RenderArea::mouseReleaseEvent (QMouseEvent * event) protected
References mouseEvent().
paintEvent()
void RenderArea::paintEvent (QPaintEvent * event) protected
References gra, and qt_qpainter_draw().
processClose()
void RenderArea::processClose ()
References callback_list_call_attr_0, and cbl.
Referenced by closeEvent().
resizeEvent()
void RenderArea::resizeEvent (QResizeEvent * event) protected
References do_resize(), and is_overlay.
sizeHint()
QSize RenderArea::sizeHint () const protected
References gra, graphics_priv::h, and graphics_priv::w.
watchEvent
void RenderArea::watchEvent (int fd) protected slot
References callback_call_0, event_watch::cb, dbg, event_qt_remove_timeout(), event_watch::fd, and lvl_debug.
wheelEvent()
void RenderArea::wheelEvent (QWheelEvent * event) protected
References callback_list_call_attr_3, cbl, point::x, and point::y.
Field Documentation
cbl
struct callback_list* RenderArea::cbl
Referenced by do_resize(), keyPressEvent(), mouseEvent(), mouseMoveEvent(), processClose(), and wheelEvent().
gra
struct graphics_priv* RenderArea::gra
Referenced by paintEvent(), RenderArea(), and sizeHint().
is_overlay
int RenderArea::is_overlay protected
Referenced by RenderArea(), and resizeEvent().
pixmap
QPixmap* RenderArea::pixmap
Referenced by do_resize(), and RenderArea().
The documentation for this class was generated from the following files:
graphics/qt_qpainter/RenderArea.h
graphics/qt_qpainter/RenderArea.cpp