navit: org.navitproject.navit.NavitMapDownloader Class Reference
org.navitproject.navit.NavitMapDownloader Class Reference
Data Structures
class osm_map_values
Public Member Functions
NavitMapDownloader (int map_id)
void run ()
void stop_thread ()
Static Public Member Functions
static NavitMap[] getAvailableMaps ()
Static Public Attributes
static final osm_map_values[] osm_maps
Protected Member Functions
boolean checkFreeSpace (long needed_bytes)
boolean deleteMap ()
boolean download_osm_map ()
File getDestinationFile ()
boolean downloadData (URLConnection c, long already_read, long real_size_bytes, boolean resume, File outputFile)
URL getDownloadURL ()
long getFreeSpace ()
BufferedInputStream getInputStream (URLConnection c)
File getMapFile ()
File getMapInfoFile ()
BufferedOutputStream getOutputStream (File outputFile, boolean resume)
URLConnection initConnection (URL url)
boolean readData (OutputStream buf, InputStream bif, long already_read, long real_size_bytes)
URL readFileInfo ()
void toast (String message)
void updateProgress (long startTime, long offsetBytes, long readBytes, long maxBytes)
void updateProgress (long positionBytes, long maximumBytes, String infoText)
void writeFileInfo (URLConnection c, long sizeInBytes)
Protected Attributes
int retry_counter = 0
Package Functions
void enableRetry ()
Private Attributes
String map_filename_path
Boolean stop_me = false
osm_map_values map_values
int map_id
long uiLastUpdated = -1
Boolean retryDownload = false
Static Private Attributes
static final int SOCKET_CONNECT_TIMEOUT = 60000
static final int SOCKET_READ_TIMEOUT = 120000
static final int MAP_WRITE_FILE_BUFFER = 1024 * 64
static final int MAP_WRITE_MEM_BUFFER = 1024 * 64
static final int MAP_READ_FILE_BUFFER = 1024 * 64
static final int UPDATE_PROGRESS_TIME_NS = 1000 * 1000000
static final int MAX_RETRIES = 5
static final String TAG = "NavitMapDownloader"
Detailed Description
Author
rikky
Constructor & Destructor Documentation
org.navitproject.navit.NavitMapDownloader.NavitMapDownloader (int map_id) inline
References org.navitproject.navit.Navit.map_filename_path, org.navitproject.navit.NavitMapDownloader.map_id, and org.navitproject.navit.NavitMapDownloader.osm_maps.
Member Function Documentation
boolean org.navitproject.navit.NavitMapDownloader.checkFreeSpace (long needed_bytes) inline protected
References org.navitproject.navit.NavitMapDownloader.getFreeSpace(), org.navitproject.navit.NavitMapDownloader.MAP_WRITE_FILE_BUFFER, org.navitproject.navit.Navit.T(), org.navitproject.navit.NavitMapDownloader.TAG, and org.navitproject.navit.NavitMapDownloader.updateProgress().
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map(), and org.navitproject.navit.NavitMapDownloader.readData().
boolean org.navitproject.navit.NavitMapDownloader.deleteMap () inline protected
References org.navitproject.navit.NavitMapDownloader.getMapFile().
Referenced by org.navitproject.navit.NavitMapDownloader.readData().
boolean org.navitproject.navit.NavitMapDownloader.download_osm_map () inline protected
Parameters
map_values
Returns
References c, org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitMapDownloader.downloadData(), org.navitproject.navit.NavitMapDownloader.getDestinationFile(), org.navitproject.navit.NavitMapDownloader.getDownloadURL(), org.navitproject.navit.NavitMapDownloader.getMapFile(), org.navitproject.navit.NavitMapDownloader.initConnection(), org.navitproject.navit.NavitMapDownloader.readFileInfo(), org.navitproject.navit.NavitMapDownloader.TAG, and org.navitproject.navit.NavitMapDownloader.writeFileInfo().
Referenced by org.navitproject.navit.NavitMapDownloader.run().
boolean org.navitproject.navit.NavitMapDownloader.downloadData (URLConnection c, long already_read, long real_size_bytes, boolean resume, File outputFile) inline protected
References buf, org.navitproject.navit.NavitMapDownloader.getInputStream(), org.navitproject.navit.NavitMapDownloader.getOutputStream(), and org.navitproject.navit.NavitMapDownloader.readData().
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
void org.navitproject.navit.NavitMapDownloader.enableRetry () inline package
Referenced by org.navitproject.navit.NavitMapDownloader.getInputStream(), org.navitproject.navit.NavitMapDownloader.initConnection(), and org.navitproject.navit.NavitMapDownloader.readData().
static NavitMap [] org.navitproject.navit.NavitMapDownloader.getAvailableMaps () inline static
References filename, length, org.navitproject.navit.Navit.map_filename_path, and maps.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.updateDownloadedMaps().
File org.navitproject.navit.NavitMapDownloader.getDestinationFile () inline protected
References org.navitproject.navit.NavitMapDownloader.osm_map_values.map_name, and mkdir().
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
URL org.navitproject.navit.NavitMapDownloader.getDownloadURL () inline protected
References org.navitproject.navit.NavitMapDownloader.osm_map_values.lat1, org.navitproject.navit.NavitMapDownloader.osm_map_values.lat2, org.navitproject.navit.NavitMapDownloader.osm_map_values.lon1, org.navitproject.navit.NavitMapDownloader.osm_map_values.lon2, and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
long org.navitproject.navit.NavitMapDownloader.getFreeSpace () inline protected
Referenced by org.navitproject.navit.NavitMapDownloader.checkFreeSpace().
BufferedInputStream org.navitproject.navit.NavitMapDownloader.getInputStream (URLConnection c) inline protected
References org.navitproject.navit.NavitMapDownloader.enableRetry(), org.navitproject.navit.NavitMapDownloader.getMapInfoFile(), org.navitproject.navit.NavitMapDownloader.MAP_READ_FILE_BUFFER, and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.downloadData().
File org.navitproject.navit.NavitMapDownloader.getMapFile () inline protected
References org.navitproject.navit.NavitMapDownloader.osm_map_values.map_name.
Referenced by org.navitproject.navit.NavitMapDownloader.deleteMap(), and org.navitproject.navit.NavitMapDownloader.download_osm_map().
File org.navitproject.navit.NavitMapDownloader.getMapInfoFile () inline protected
References org.navitproject.navit.NavitMapDownloader.osm_map_values.map_name.
Referenced by org.navitproject.navit.NavitMapDownloader.getInputStream(), org.navitproject.navit.NavitMapDownloader.readFileInfo(), org.navitproject.navit.NavitMapDownloader.run(), and org.navitproject.navit.NavitMapDownloader.writeFileInfo().
BufferedOutputStream org.navitproject.navit.NavitMapDownloader.getOutputStream (File outputFile, boolean resume) inline protected
References buf, and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.downloadData().
URLConnection org.navitproject.navit.NavitMapDownloader.initConnection (URL url) inline protected
References c, org.navitproject.navit.NavitMapDownloader.enableRetry(), org.navitproject.navit.NavitMapDownloader.SOCKET_CONNECT_TIMEOUT, org.navitproject.navit.NavitMapDownloader.SOCKET_READ_TIMEOUT, and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
boolean org.navitproject.navit.NavitMapDownloader.readData (OutputStream buf, InputStream bif, long already_read, long real_size_bytes) inline protected
References buffer, org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitMapDownloader.deleteMap(), org.navitproject.navit.NavitMapDownloader.enableRetry(), org.navitproject.navit.NavitMapDownloader.MAP_WRITE_MEM_BUFFER, org.navitproject.navit.Navit.T(), org.navitproject.navit.NavitMapDownloader.TAG, org.navitproject.navit.NavitMapDownloader.toast(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
Referenced by org.navitproject.navit.NavitMapDownloader.downloadData().
URL org.navitproject.navit.NavitMapDownloader.readFileInfo () inline protected
References org.navitproject.navit.NavitMapDownloader.getMapInfoFile(), and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
void org.navitproject.navit.NavitMapDownloader.run () inline
References org.navitproject.navit.NavitMapDownloader.download_osm_map(), e1, org.navitproject.navit.NavitMapDownloader.osm_map_values.est_size_bytes, org.navitproject.navit.NavitMapDownloader.getMapInfoFile(), org.navitproject.navit.NavitMapDownloader.map_id, org.navitproject.navit.NavitMapDownloader.osm_map_values.map_name, org.navitproject.navit.NavitDialogs.MSG_MAP_DOWNLOAD_FINISHED, org.navitproject.navit.Navit.T(), org.navitproject.navit.NavitMapDownloader.TAG, org.navitproject.navit.NavitMapDownloader.toast(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
void org.navitproject.navit.NavitMapDownloader.stop_thread () inline
References org.navitproject.navit.NavitMapDownloader.TAG.
void org.navitproject.navit.NavitMapDownloader.toast (String message) inline protected
References org.navitproject.navit.NavitDialogs.MSG_TOAST.
Referenced by org.navitproject.navit.NavitMapDownloader.readData(), and org.navitproject.navit.NavitMapDownloader.run().
void org.navitproject.navit.NavitMapDownloader.updateProgress (long startTime, long offsetBytes, long readBytes, long maxBytes) inline protected
References info, int, org.navitproject.navit.NavitMapDownloader.osm_map_values.map_name, org.navitproject.navit.NavitMapDownloader.MAX_RETRIES, org.navitproject.navit.Navit.T(), and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitMapDownloader.readData(), and org.navitproject.navit.NavitMapDownloader.run().
void org.navitproject.navit.NavitMapDownloader.updateProgress (long positionBytes, long maximumBytes, String infoText) inline protected
References org.navitproject.navit.NavitDialogs.DIALOG_MAPDOWNLOAD, and org.navitproject.navit.NavitDialogs.MSG_PROGRESS_BAR.
void org.navitproject.navit.NavitMapDownloader.writeFileInfo (URLConnection c, long sizeInBytes) inline protected
References org.navitproject.navit.NavitMapDownloader.getMapInfoFile(), and org.navitproject.navit.NavitMapDownloader.TAG.
Referenced by org.navitproject.navit.NavitMapDownloader.download_osm_map().
Field Documentation
String org.navitproject.navit.NavitMapDownloader.map_filename_path private
int org.navitproject.navit.NavitMapDownloader.map_id private
Referenced by org.navitproject.navit.NavitMapDownloader.NavitMapDownloader(), and org.navitproject.navit.NavitMapDownloader.run().
final int org.navitproject.navit.NavitMapDownloader.MAP_READ_FILE_BUFFER = 1024 * 64 static private
Referenced by org.navitproject.navit.NavitMapDownloader.getInputStream().
osm_map_values org.navitproject.navit.NavitMapDownloader.map_values private
final int org.navitproject.navit.NavitMapDownloader.MAP_WRITE_FILE_BUFFER = 1024 * 64 static private
Referenced by org.navitproject.navit.NavitMapDownloader.checkFreeSpace().
final int org.navitproject.navit.NavitMapDownloader.MAP_WRITE_MEM_BUFFER = 1024 * 64 static private
Referenced by org.navitproject.navit.NavitMapDownloader.readData().
final int org.navitproject.navit.NavitMapDownloader.MAX_RETRIES = 5 static private
Referenced by org.navitproject.navit.NavitMapDownloader.updateProgress().
final osm_map_values [] org.navitproject.navit.NavitMapDownloader.osm_maps static
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), org.navitproject.navit.NavitDialogs.handleMessage(), org.navitproject.navit.NavitMapDownloader.NavitMapDownloader(), org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), and org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
int org.navitproject.navit.NavitMapDownloader.retry_counter = 0 protected
Boolean org.navitproject.navit.NavitMapDownloader.retryDownload = false private
final int org.navitproject.navit.NavitMapDownloader.SOCKET_CONNECT_TIMEOUT = 60000 static private
Referenced by org.navitproject.navit.NavitMapDownloader.initConnection().
final int org.navitproject.navit.NavitMapDownloader.SOCKET_READ_TIMEOUT = 120000 static private
Referenced by org.navitproject.navit.NavitMapDownloader.initConnection().
Boolean org.navitproject.navit.NavitMapDownloader.stop_me = false private
final String org.navitproject.navit.NavitMapDownloader.TAG = "NavitMapDownloader" static private
Referenced by org.navitproject.navit.NavitMapDownloader.checkFreeSpace(), org.navitproject.navit.NavitMapDownloader.download_osm_map(), org.navitproject.navit.NavitMapDownloader.getDownloadURL(), org.navitproject.navit.NavitMapDownloader.getInputStream(), org.navitproject.navit.NavitMapDownloader.getOutputStream(), org.navitproject.navit.NavitMapDownloader.initConnection(), org.navitproject.navit.NavitMapDownloader.readData(), org.navitproject.navit.NavitMapDownloader.readFileInfo(), org.navitproject.navit.NavitMapDownloader.run(), org.navitproject.navit.NavitMapDownloader.stop_thread(), org.navitproject.navit.NavitMapDownloader.updateProgress(), and org.navitproject.navit.NavitMapDownloader.writeFileInfo().
long org.navitproject.navit.NavitMapDownloader.uiLastUpdated = -1 private
final int org.navitproject.navit.NavitMapDownloader.UPDATE_PROGRESS_TIME_NS = 1000 * 1000000 static private
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitMapDownloader.java