navit: org.navitproject.navit.NavitVehicle.NavitLocationListener Class Reference
org.navitproject.navit.NavitVehicle.NavitLocationListener Class Reference
Public Member Functions
void onLocationChanged (Location location)
void onProviderDisabled (String provider)
void onProviderEnabled (String provider)
void onStatusChanged (String provider, int status, Bundle extras)
void onGpsStatusChanged (int event)
void onReceive (Context context, Intent intent)
Data Fields
boolean precise = false
Member Function Documentation
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onGpsStatusChanged (int event) inline
Called when the status of the GPS changes.
References org.navitproject.navit.NavitVehicle.vehicle_scbid, and org.navitproject.navit.NavitVehicle.VehicleCallback().
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onLocationChanged (Location location) inline
References org.navitproject.navit.NavitVehicle.fastLocationListener, org.navitproject.navit.NavitVehicle.fastProvider, org.navitproject.navit.NavitVehicle.lastLocation, location, org.navitproject.navit.NavitVehicle.NavitLocationListener.precise, org.navitproject.navit.NavitVehicle.vehicle_fcbid, org.navitproject.navit.NavitVehicle.vehicle_pcbid, and org.navitproject.navit.NavitVehicle.VehicleCallback().
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onProviderDisabled (String provider) inline
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onProviderEnabled (String provider) inline
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onReceive (Context context, Intent intent) inline
References org.navitproject.navit.NavitVehicle.GPS_FIX_CHANGE, org.navitproject.navit.NavitVehicle.vehicle_fcbid, and org.navitproject.navit.NavitVehicle.VehicleCallback().
void org.navitproject.navit.NavitVehicle.NavitLocationListener.onStatusChanged (String provider, int status, Bundle extras) inline
Field Documentation
boolean org.navitproject.navit.NavitVehicle.NavitLocationListener.precise = false
Referenced by org.navitproject.navit.NavitVehicle.NavitLocationListener.onLocationChanged().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitVehicle.java