navit: org.navitproject.navit.NavitDownloadSelectMapActivity Class Reference
org.navitproject.navit.NavitDownloadSelectMapActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
boolean onChildClick (ExpandableListView parent, View v, int groupPosition, int childPosition, long id)
Private Member Functions
void updateDownloadedMaps ()
void updateMapsForLocation ()
SimpleExpandableListAdapter createAdapter ()
void askForMapDeletion (final String mapLocation)
Static Private Attributes
static final String MAP_BULLETPOINT = " * "
static SimpleExpandableListAdapter sAdapter = null
static ArrayList< HashMap< String, String > > sDownloadedMapsChilds = null
static ArrayList< HashMap< String, String > > sMapsCurrentPositionChilds = null
static boolean sCurrentLocationKnown = false
static final String TAG = "DownloadSelectMapAct"
Member Function Documentation
askForMapDeletion()
void org.navitproject.navit.NavitDownloadSelectMapActivity.askForMapDeletion (final String mapLocation) inline private
References org.navitproject.navit.NavitMap.mMapName, and org.navitproject.navit.NavitMap.size().
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick().
createAdapter()
SimpleExpandableListAdapter org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter () inline private
References org.navitproject.navit.NavitDownloadSelectMapActivity.MAP_BULLETPOINT, org.navitproject.navit.NavitMapDownloader.osm_maps, org.navitproject.navit.NavitDownloadSelectMapActivity.sDownloadedMapsChilds, and org.navitproject.navit.NavitDownloadSelectMapActivity.sMapsCurrentPositionChilds.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
onChildClick()
boolean org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick (ExpandableListView parent, View v, int groupPosition, int childPosition, long id) inline
References org.navitproject.navit.NavitDownloadSelectMapActivity.askForMapDeletion(), finish(), org.navitproject.navit.NavitMapDownloader.OsmMapValues.mEstSizeBytes, org.navitproject.navit.NavitDialogs.MSG_TOAST_LONG, org.navitproject.navit.NavitMapDownloader.osm_maps, org.navitproject.navit.NavitDownloadSelectMapActivity.sAdapter, org.navitproject.navit.NavitDialogs.sendDialogMessage(), and org.navitproject.navit.NavitDownloadSelectMapActivity.TAG.
onCreate()
void org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate (Bundle savedInstanceState) inline
References org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), finish(), org.navitproject.navit.NavitUtils.getFreeSpace(), org.navitproject.navit.NavitDialogs.MSG_TOAST_LONG, org.navitproject.navit.NavitDownloadSelectMapActivity.sAdapter, org.navitproject.navit.NavitDialogs.sendDialogMessage(), org.navitproject.navit.Navit.sMapFilenamePath, org.navitproject.navit.NavitDownloadSelectMapActivity.TAG, org.navitproject.navit.NavitDownloadSelectMapActivity.updateDownloadedMaps(), and org.navitproject.navit.NavitDownloadSelectMapActivity.updateMapsForLocation().
updateDownloadedMaps()
void org.navitproject.navit.NavitDownloadSelectMapActivity.updateDownloadedMaps () inline private
References org.navitproject.navit.NavitMapDownloader.getAvailableMaps(), and org.navitproject.navit.NavitDownloadSelectMapActivity.sDownloadedMapsChilds.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
updateMapsForLocation()
void org.navitproject.navit.NavitDownloadSelectMapActivity.updateMapsForLocation () inline private
References org.navitproject.navit.NavitMapDownloader.OsmMapValues.isInMap(), org.navitproject.navit.NavitMapDownloader.OsmMapValues.mEstSizeBytes, org.navitproject.navit.NavitMapDownloader.OsmMapValues.mMapName, org.navitproject.navit.NavitMapDownloader.osm_maps, org.navitproject.navit.NavitDownloadSelectMapActivity.sCurrentLocationKnown, org.navitproject.navit.NavitVehicle.sLastLocation, and org.navitproject.navit.NavitDownloadSelectMapActivity.sMapsCurrentPositionChilds.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
Field Documentation
MAP_BULLETPOINT
final String org.navitproject.navit.NavitDownloadSelectMapActivity.MAP_BULLETPOINT = " * " static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter().
sAdapter
SimpleExpandableListAdapter org.navitproject.navit.NavitDownloadSelectMapActivity.sAdapter = null static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), and org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
sCurrentLocationKnown
boolean org.navitproject.navit.NavitDownloadSelectMapActivity.sCurrentLocationKnown = false static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.updateMapsForLocation().
sDownloadedMapsChilds
ArrayList<HashMap<String, String> > org.navitproject.navit.NavitDownloadSelectMapActivity.sDownloadedMapsChilds = null static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), and org.navitproject.navit.NavitDownloadSelectMapActivity.updateDownloadedMaps().
sMapsCurrentPositionChilds
ArrayList<HashMap<String, String> > org.navitproject.navit.NavitDownloadSelectMapActivity.sMapsCurrentPositionChilds = null static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.createAdapter(), and org.navitproject.navit.NavitDownloadSelectMapActivity.updateMapsForLocation().
TAG
final String org.navitproject.navit.NavitDownloadSelectMapActivity.TAG = "DownloadSelectMapAct" static private
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), and org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitDownloadSelectMapActivity.java