navit: NGQProxyGui Class Reference
NGQProxyGui Class Reference
#include <guiProxy.h>
Public Slots
void pushPage (QString page)
QString popPage ()
int lengthPage ()
void backToMap ()
void switchToMenu (struct point *p)
QString iconPath ()
int width ()
void setWidth (int w)
int height ()
void setHeight (int h)
QString commandFunction ()
QString localeName ()
QString langName ()
QString ctryName ()
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Signals
void widthSignal (int)
void heightSignal (int)
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Public Member Functions
NGQProxyGui (struct gui_priv *this_, QObject *parent)
void setNewPoint (struct point *p, NGQPointTypes type)
void setNewPoint (struct coord *c, NGQPointTypes type)
void setNewPoint (struct pcoord *pc, NGQPointTypes type)
void processCommand (QString function)
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
int setAttrFunc (struct attr *attr)
Protected Member Functions inherited from NGQProxy
virtual struct attr_iter * getIterFunc ()
virtual void dropIterFunc (struct attr_iter *)
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Properties
QString iconPath
QString commandFunction
QString localeName
QString langName
QString ctryName
int width
int height
Properties inherited from NGQProxy
int itemId
Private Attributes
QStringList returnPath
QString source
QString function
Additional Inherited Members
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Constructor & Destructor Documentation
NGQProxyGui::NGQProxyGui (struct gui_priv * this_, QObject * parent) inline
References source.
Member Function Documentation
void NGQProxyGui::backToMap () inline slot
References gui_priv::graphicsWidget, and NGQProxy::object.
QString NGQProxyGui::commandFunction () inline slot
QString NGQProxyGui::ctryName () inline slot
int NGQProxyGui::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
References gui_priv::gui, gui_get_attr(), and NGQProxy::object.
int NGQProxyGui::height () inline slot
void NGQProxyGui::heightSignal (int) signal
Referenced by setHeight().
QString NGQProxyGui::iconPath () inline slot
References gui_priv::icon_src, and NGQProxy::object.
QString NGQProxyGui::langName () inline slot
int NGQProxyGui::lengthPage () inline slot
References returnPath.
QString NGQProxyGui::localeName () inline slot
References getenv.
QString NGQProxyGui::popPage () inline slot
References returnPath.
void NGQProxyGui::processCommand (QString function) inline
Referenced by gui_qml_command().
void NGQProxyGui::pushPage (QString page) inline slot
References returnPath.
int NGQProxyGui::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
References gui_priv::gui, gui_set_attr(), and NGQProxy::object.
void NGQProxyGui::setHeight (int h) inline slot
References heightSignal().
void NGQProxyGui::setNewPoint (struct point * p, NGQPointTypes type) inline
References gui_priv::currentPoint, NULL, and NGQProxy::object.
Referenced by __setNewPoint(), and switchToMenu().
void NGQProxyGui::setNewPoint (struct coord * c, NGQPointTypes type) inline
References gui_priv::currentPoint, NULL, and NGQProxy::object.
void NGQProxyGui::setNewPoint (struct pcoord * pc, NGQPointTypes type) inline
References gui_priv::currentPoint, NULL, and NGQProxy::object.
void NGQProxyGui::setWidth (int w) inline slot
References widthSignal().
void NGQProxyGui::switchToMenu (struct point * p) inline slot
References gui_priv::guiWidget, gui_priv::lazy, MapPoint, NGQProxy::object, returnPath, setNewPoint(), and gui_priv::source.
Referenced by gui_qml_button(), and gui_qml_keypress().
int NGQProxyGui::width () inline slot
void NGQProxyGui::widthSignal (int) signal
Referenced by setWidth().
Field Documentation
QString NGQProxyGui::function private
QStringList NGQProxyGui::returnPath private
Referenced by lengthPage(), popPage(), pushPage(), and switchToMenu().
QString NGQProxyGui::source private
Referenced by NGQProxyGui().
Property Documentation
QString NGQProxyGui::commandFunction read
QString NGQProxyGui::ctryName read
int NGQProxyGui::height read write
QString NGQProxyGui::iconPath read
QString NGQProxyGui::langName read
QString NGQProxyGui::localeName read
int NGQProxyGui::width read write
The documentation for this class was generated from the following file:
gui/qml/guiProxy.h