navit: org.navitproject.navit.NavitVehicle Class Reference
org.navitproject.navit.NavitVehicle Class Reference
Data Structures
class NavitLocationListener
Public Member Functions
native void VehicleCallback (int id, Location location)
native void VehicleCallback (int id, int satsInView, int satsUsed)
native void VehicleCallback (int id, int enabled)
Static Public Member Functions
static void removeListener ()
Static Public Attributes
static Location lastLocation = null
Package Functions
NavitVehicle (Context context, int pcbid, int scbid, int fcbid)
Creates a new.
Private Attributes
int vehicle_pcbid
int vehicle_scbid
int vehicle_fcbid
String preciseProvider
String fastProvider
Static Private Attributes
static final String GPS_FIX_CHANGE = "android.location.GPS_FIX_CHANGE"
static LocationManager sLocationManager = null
static Context context = null
static NavitLocationListener preciseLocationListener = null
static NavitLocationListener fastLocationListener = null
Constructor & Destructor Documentation
NavitVehicle()
org.navitproject.navit.NavitVehicle.NavitVehicle (Context context, int pcbid, int scbid, int fcbid) inline package
Creates a new.
NavitVehicle
Parameters
context
pcbid The address of the position callback function called when a location update is received
scbid The address of the status callback function called when a status update is received
fcbid The address of the fix callback function called when a
android.location.GPS_FIX_CHANGE
is received, indicating a change in GPS fix status
References org.navitproject.navit.NavitVehicle.context, and org.navitproject.navit.NavitVehicle.NavitLocationListener.precise.
Member Function Documentation
removeListener()
static void org.navitproject.navit.NavitVehicle.removeListener () inline static
Referenced by org.navitproject.navit.Navit.exit(), and org.navitproject.navit.NavitRestoreTask.onPostExecute().
VehicleCallback() [1/3]
native void org.navitproject.navit.NavitVehicle.VehicleCallback (int id, Location location)
Referenced by org.navitproject.navit.NavitVehicle.NavitLocationListener.onGpsStatusChanged(), org.navitproject.navit.NavitVehicle.NavitLocationListener.onLocationChanged(), and org.navitproject.navit.NavitVehicle.NavitLocationListener.onReceive().
VehicleCallback() [2/3]
native void org.navitproject.navit.NavitVehicle.VehicleCallback (int id, int satsInView, int satsUsed)
VehicleCallback() [3/3]
native void org.navitproject.navit.NavitVehicle.VehicleCallback (int id, int enabled)
Field Documentation
context
Context org.navitproject.navit.NavitVehicle.context = null static private
Referenced by org.navitproject.navit.NavitVehicle.NavitVehicle().
fastLocationListener
NavitLocationListener org.navitproject.navit.NavitVehicle.fastLocationListener = null static private
fastProvider
String org.navitproject.navit.NavitVehicle.fastProvider private
GPS_FIX_CHANGE
final String org.navitproject.navit.NavitVehicle.GPS_FIX_CHANGE = "android.location.GPS_FIX_CHANGE" static private
lastLocation
Location org.navitproject.navit.NavitVehicle.lastLocation = null static
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.updateMapsForLocation().
preciseLocationListener
NavitLocationListener org.navitproject.navit.NavitVehicle.preciseLocationListener = null static private
preciseProvider
String org.navitproject.navit.NavitVehicle.preciseProvider private
sLocationManager
LocationManager org.navitproject.navit.NavitVehicle.sLocationManager = null static private
vehicle_fcbid
int org.navitproject.navit.NavitVehicle.vehicle_fcbid private
vehicle_pcbid
int org.navitproject.navit.NavitVehicle.vehicle_pcbid private
vehicle_scbid
int org.navitproject.navit.NavitVehicle.vehicle_scbid private
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitVehicle.java