navit: NGQProxyNavit Class Reference
NGQProxyNavit Class Reference
#include <navitProxy.h>
Public Slots
void quit ()
void setObjectByName (const QString &attr_name, const QString &attr_value)
QString getAttrList (const QString &attr_name)
QString getDestination ()
void setDestination ()
void stopNavigation ()
QString getPosition ()
void setPosition ()
void setCenter ()
void command (QString command)
Public Slots inherited from NGQProxy
QString getAttr (const QString &attr_name)
void setAttr (const QString &attr_name, const QString &attr_string)
int itemId ()
Public Member Functions
NGQProxyNavit (struct gui_priv *object, QObject *parent)
Public Member Functions inherited from NGQProxy
NGQProxy (struct gui_priv *this_, QObject *parent)
Protected Member Functions
int getAttrFunc (enum attr_type type, struct attr *attr, struct attr_iter *iter)
int setAttrFunc (struct attr *attr)
struct attr_iter * getIterFunc ()
void dropIterFunc (struct attr_iter *iter)
Protected Member Functions inherited from NGQProxy
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
Additional Inherited Members
Signals inherited from NGQProxy
void itemIdSignal (int itemId)
Protected Attributes inherited from NGQProxy
struct gui_priv * object
int _itemId
Properties inherited from NGQProxy
int itemId
Constructor & Destructor Documentation
NGQProxyNavit::NGQProxyNavit (struct gui_priv * object, QObject * parent) inline
Member Function Documentation
void NGQProxyNavit::command (QString command) inline slot
References command_evaluate(), attr::navit, attr::type, and attr::u.
void NGQProxyNavit::dropIterFunc (struct attr_iter * iter) inline protected virtual
Reimplemented from NGQProxy.
References navit_attr_iter_destroy().
Referenced by getAttrList().
int NGQProxyNavit::getAttrFunc (enum attr_type type, struct attr * attr, struct attr_iter * iter) inline protected virtual
Implements NGQProxy.
References gui_priv::nav, navit_get_attr(), and NGQProxy::object.
Referenced by getAttrList(), getDestination(), and getPosition().
QString NGQProxyNavit::getAttrList (const QString & attr_name) inline slot
References NGQProxy::_fieldValueHelper(), NGQProxy::_itemId, attr_from_name(), dbg, dropIterFunc(), entries, NGQProxy::getAttr(), getAttrFunc(), getIterFunc(), NGQStandardItemModel::ItemId, NGQStandardItemModel::ItemName, NGQStandardItemModel::ItemValue, eval::iter, attr::layout, lvl_debug, layout::name, gui_priv::nav, navit_get_attr(), NULL, NGQProxy::object, attr::type, attr::u, attr::vehicle, and gui_priv::vehicleProxy.
QString NGQProxyNavit::getDestination () inline slot
References __setNewPoint(), Destination, getAttrFunc(), NULL, attr::pcoord, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
struct attr_iter* NGQProxyNavit::getIterFunc () inline protected virtual
Reimplemented from NGQProxy.
References navit_attr_iter_new().
Referenced by getAttrList().
QString NGQProxyNavit::getPosition () inline slot
References __setNewPoint(), attr::coord_geo, gui_priv::currVehicle, getAttrFunc(), gui_priv::nav, navit_get_trans(), NULL, NGQProxy::object, Position, pcoord::pro, trans, transform_from_geo(), transform_get_projection(), attr::u, attr::vehicle, and vehicle_get_attr().
void NGQProxyNavit::quit () inline slot
References event_main_loop_quit(), attr::navit, navit_destroy(), attr::type, and attr::u.
Referenced by gui_qml_window_closed().
int NGQProxyNavit::setAttrFunc (struct attr * attr) inline protected virtual
Implements NGQProxy.
References gui_priv::nav, navit_set_attr(), and NGQProxy::object.
void NGQProxyNavit::setCenter () inline slot
References gui_priv::nav, navit_set_center(), and NGQProxy::object.
void NGQProxyNavit::setDestination () inline slot
References gui_priv::nav, navit_set_destination(), and NGQProxy::object.
void NGQProxyNavit::setObjectByName (const QString & attr_name, const QString & attr_value) inline slot
References gui_priv::nav, navit_set_layout_by_name(), navit_set_vehicle_by_name(), and NGQProxy::object.
void NGQProxyNavit::setPosition () inline slot
References gui_priv::nav, navit_set_position(), and NGQProxy::object.
void NGQProxyNavit::stopNavigation () inline slot
References gui_priv::nav, navit_set_destination(), NULL, and NGQProxy::object.
The documentation for this class was generated from the following file:
gui/qml/navitProxy.h