navit: QNavitQuick Class Reference
QNavitQuick Class Reference
#include <QNavitQuick.h>
Public Member Functions
void paint (QPainter *painter)
QNavitQuick (QQuickItem *parent=0)
Q_INVOKABLE void setGraphicContext (GraphicsPriv *gp)
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event)
virtual void keyReleaseEvent (QKeyEvent *event)
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
virtual void mouseEvent (int pressed, QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
Private Attributes
struct graphics_priv * graphics_priv
Constructor & Destructor Documentation
QNavitQuick()
QNavitQuick::QNavitQuick (QQuickItem * parent = 0)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Member Function Documentation
geometryChanged()
void QNavitQuick::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
References dbg, height, lvl_debug, graphics_priv::pixmap, resize_callback(), graphics_priv::root, and width.
keyPressEvent()
void QNavitQuick::keyPressEvent (QKeyEvent * event) protected virtual
References callback_list_call_attr_1, graphics_priv::callbacks, dbg, key, lvl_debug, NAVIT_KEY_BACK, NAVIT_KEY_BACKSPACE, NAVIT_KEY_DELETE, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_PAGE_DOWN, NAVIT_KEY_PAGE_UP, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_TAB, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, and NAVIT_KEY_ZOOM_OUT.
keyReleaseEvent()
void QNavitQuick::keyReleaseEvent (QKeyEvent * event) protected virtual
References dbg, and lvl_debug.
mouseEvent()
void QNavitQuick::mouseEvent (int pressed, QMouseEvent * event) protected virtual
References callback_list_call_attr_3, graphics_priv::callbacks, dbg, lvl_debug, and p.
Referenced by mousePressEvent(), and mouseReleaseEvent().
mouseMoveEvent()
void QNavitQuick::mouseMoveEvent (QMouseEvent * event) protected virtual
References callback_list_call_attr_1, graphics_priv::callbacks, dbg, lvl_debug, and p.
mousePressEvent()
void QNavitQuick::mousePressEvent (QMouseEvent * event) protected virtual
References dbg, lvl_debug, and mouseEvent().
mouseReleaseEvent()
void QNavitQuick::mouseReleaseEvent (QMouseEvent * event) protected virtual
References dbg, lvl_debug, and mouseEvent().
paint()
void QNavitQuick::paint (QPainter * painter)
References graphics_priv::background_graphics_gc_priv, graphics_gc_priv::brush, dbg, graphics_priv::disable, height, lvl_debug, graphics_priv::painter, paintOverlays(), graphics_gc_priv::pen, graphics_priv::pixmap, graphics_priv::scroll_x, graphics_priv::scroll_y, width, graphics_priv::x, and graphics_priv::y.
setGraphicContext()
void QNavitQuick::setGraphicContext (GraphicsPriv * gp)
References dbg, and lvl_debug.
wheelEvent()
void QNavitQuick::wheelEvent (QWheelEvent * event) protected virtual
References callback_list_call_attr_3, graphics_priv::callbacks, dbg, lvl_debug, and p.
Field Documentation
graphics_priv
struct graphics_priv* QNavitQuick::graphics_priv private
The documentation for this class was generated from the following files:
graphics/qt5/QNavitQuick.h
graphics/qt5/QNavitQuick.cpp