navit: NGQPoint Class Reference
NGQPoint Class Reference
#include <ngqpoint.h>
Public Slots
void setNewPoint (QString coord, NGQPointTypes type=PointOfInterest)
QString pointName ()
QString coordString ()
QString pointType ()
QUrl pointUrl ()
QString getInformation ()
QString getPOI (const QString &attr_name)
Public Member Functions
NGQPoint (struct gui_priv *this_, struct point *p, NGQPointTypes type=MapPoint, QObject *parent=NULL)
NGQPoint (struct gui_priv *this_, struct coord *c, NGQPointTypes type=Bookmark, QObject *parent=NULL)
NGQPoint (struct gui_priv *this_, struct pcoord *pc, NGQPointTypes type=Bookmark, QObject *parent=NULL)
NGQPoint (struct gui_priv *this_, struct coord *c, QString name, NGQPointTypes type=Bookmark, QObject *parent=NULL)
struct pcoord * pc ()
Protected Member Functions
QDomElement _fieldValueHelper (QDomDocument doc, QString field, QString value)
QString _coordString ()
QString _coordName ()
void _setUrl (struct item *item)
Properties
QString coordString
QString pointName
QString pointType
QUrl pointUrl
Private Attributes
struct gui_priv * object
NGQPointTypes type
struct coord_geo g
struct coord co
struct pcoord c
struct point p
struct item item
QString name
QString coord
QUrl url
Constructor & Destructor Documentation
NGQPoint() [1/4]
NGQPoint::NGQPoint (struct gui_priv * this_, struct point * p, NGQPointTypes type = MapPoint, QObject * parent = NULL) inline
References _coordName(), _coordString(), c, co, g, item::map, name, gui_priv::nav, navit_get_trans(), object, p, pcoord::pro, transform_get_projection(), transform_reverse(), transform_to_geo(), type, coord::x, pcoord::x, point::x, coord::y, pcoord::y, and point::y.
NGQPoint() [2/4]
NGQPoint::NGQPoint (struct gui_priv * this_, struct coord * c, NGQPointTypes type = Bookmark, QObject * parent = NULL) inline
References _coordName(), _coordString(), c, co, g, item::map, name, gui_priv::nav, navit_get_trans(), object, transform_get_projection(), transform_to_geo(), type, coord::x, pcoord::x, coord::y, and pcoord::y.
NGQPoint() [3/4]
NGQPoint::NGQPoint (struct gui_priv * this_, struct pcoord * pc, NGQPointTypes type = Bookmark, QObject * parent = NULL) inline
References _coordName(), _coordString(), c, co, g, item::map, name, pcoord::pro, transform_to_geo(), type, coord::x, pcoord::x, coord::y, and pcoord::y.
NGQPoint() [4/4]
NGQPoint::NGQPoint (struct gui_priv * this_, struct coord * c, QString name, NGQPointTypes type = Bookmark, QObject * parent = NULL) inline
References _coordString(), c, co, g, item::map, name, gui_priv::nav, navit_get_trans(), object, transform_get_projection(), transform_to_geo(), type, coord::x, pcoord::x, coord::y, and pcoord::y.
Member Function Documentation
_coordName()
QString NGQPoint::_coordName () inline protected
References _setUrl(), c, map_selection::c_rect, co, data, g, item, item_attr_get(), item_range_all, item_to_name(), label, coord_rect::lu, map_convert_free(), map_convert_string(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), mapset_close(), mapset_next(), mapset_open(), gui_priv::nav, navit_get_mapset(), navit_get_trans(), map_selection::next, object, map_selection::order, transformation::pro, map_selection::range, coord_rect::rl, attr::str, street_data_free(), street_get_data(), transform_from_geo(), transform_get_projection(), transform_within_dist_item(), item::type, attr::u, map_selection::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by NGQPoint(), and setNewPoint().
_coordString()
QString NGQPoint::_coordString () inline protected
References g, coord_geo::lat, and coord_geo::lng.
Referenced by NGQPoint(), and setNewPoint().
_fieldValueHelper()
QDomElement NGQPoint::_fieldValueHelper (QDomDocument doc, QString field, QString value) inline protected
References value.
Referenced by getInformation().
_setUrl()
void NGQPoint::_setUrl (struct item * item) inline protected
References item_attr_get(), attr::num64, attr::u, and url.
Referenced by _coordName().
coordString
QString NGQPoint::coordString () inline slot
References coord.
getInformation
QString NGQPoint::getInformation () inline slot
References _fieldValueHelper(), attr_to_name(), attr_to_text(), Bookmark, entries, item::id_hi, item, item_attr_get(), item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), attr::type, and type.
getPOI
QString NGQPoint::getPOI (const QString & attr_name) inline slot
References c, map_selection::c_rect, center, coord_rect_contains(), dbg, entries, get_direction(), gui_priv::gui, gui_get_attr(), item, item_attr_get(), item_coord_get_pro(), item_to_name(), label, lvl_info, map_convert_free(), map_convert_string(), map_projection(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), map_selection_dup_pro(), map_selection_rect_new(), mapset_close(), mapset_next(), mapset_open(), gui_priv::nav, navit_get_mapset(), attr::num, object, pcoord::pro, attr::str, transform_distance(), transform_get_angle_delta(), item::type, attr::u, map_selection::u, pcoord::x, coord::y, and pcoord::y.
pc()
struct pcoord* NGQPoint::pc () inline
References c.
pointName
QString NGQPoint::pointName () inline slot
References name.
pointType
QString NGQPoint::pointType () inline slot
References Bookmark, Destination, MapPoint, PointOfInterest, Position, and type.
pointUrl
QUrl NGQPoint::pointUrl () inline slot
References url.
setNewPoint
void NGQPoint::setNewPoint (QString coord, NGQPointTypes type = PointOfInterest) inline slot
References _coordName(), _coordString(), c, co, g, item::map, name, gui_priv::nav, navit_get_trans(), object, pcoord::pro, transform_get_projection(), transform_to_geo(), type, coord::x, pcoord::x, coord::y, and pcoord::y.
Field Documentation
c
struct pcoord NGQPoint::c private
Referenced by _coordName(), getPOI(), NGQPoint(), pc(), and setNewPoint().
co
struct coord NGQPoint::co private
Referenced by _coordName(), NGQPoint(), and setNewPoint().
coord
QString NGQPoint::coord private
Referenced by coordString().
g
struct coord_geo NGQPoint::g private
Referenced by _coordName(), _coordString(), NGQPoint(), and setNewPoint().
item
struct item NGQPoint::item private
Referenced by _coordName(), getInformation(), and getPOI().
name
QString NGQPoint::name private
Referenced by NGQPoint(), pointName(), and setNewPoint().
object
struct gui_priv* NGQPoint::object private
Referenced by _coordName(), getPOI(), NGQPoint(), and setNewPoint().
p
struct point NGQPoint::p private
Referenced by NGQPoint().
type
NGQPointTypes NGQPoint::type private
Referenced by getInformation(), NGQPoint(), pointType(), and setNewPoint().
url
QUrl NGQPoint::url private
Referenced by _setUrl(), and pointUrl().
Property Documentation
coordString
QString NGQPoint::coordString read
Referenced by NGQProxyRoute::getDestinations().
pointName
QString NGQPoint::pointName read
pointType
QString NGQPoint::pointType read
pointUrl
QUrl NGQPoint::pointUrl read
The documentation for this class was generated from the following file:
gui/qml/ngqpoint.h