navit: MapObject Class Reference
MapObject Class Reference
#include <qml_map.h>
Signals
void nameChanged ()
void activeChanged ()
Public Member Functions
MapObject (QObject *parent=0)
MapObject (const QString &name, const bool &active, QObject *parent=0)
QString name () const
void setName (const QString &name)
bool active () const
void setActive (const bool &active)
Properties
QString name
bool active
Private Attributes
QString m_name
bool m_active
Constructor & Destructor Documentation
MapObject() [1/2]
MapObject::MapObject (QObject * parent = 0)
MapObject() [2/2]
MapObject::MapObject (const QString & name, const bool & active, QObject * parent = 0)
Member Function Documentation
active()
bool MapObject::active () const
References m_active.
activeChanged
void MapObject::activeChanged () signal
Referenced by setActive().
name()
QString MapObject::name () const
References m_name.
nameChanged
void MapObject::nameChanged () signal
Referenced by setName().
setActive()
void MapObject::setActive (const bool & active)
References active, activeChanged(), and m_active.
setName()
void MapObject::setName (const QString & name)
References m_name, name, and nameChanged().
Field Documentation
m_active
bool MapObject::m_active private
Referenced by active(), and setActive().
m_name
QString MapObject::m_name private
Referenced by name(), and setName().
Property Documentation
active
bool MapObject::active read write
Referenced by setActive().
name
QString MapObject::name read write
Referenced by setName().
The documentation for this class was generated from the following files:
gui/qt5_qml/qml_map.h
gui/qt5_qml/qml_map.cpp