navit: org.navitproject.navit.NavitDialogs Class Reference
org.navitproject.navit.NavitDialogs Class Reference
Public Member Functions
void handleMessage (Message msg)
void prepareDialog (int id)
Static Public Member Functions
static void sendDialogMessage (int what, String title, String text, int dialog_num, int value1, int value2)
Static Public Attributes
static final int DIALOG_MAPDOWNLOAD = 1
static final int DIALOG_BACKUP_RESTORE = 2
Package Functions
NavitDialogs (Navit activity)
Dialog createDialog (int id)
Static Package Attributes
static final int MSG_MAP_DOWNLOAD_FINISHED = 0
static final int MSG_PROGRESS_BAR = 1
static final int MSG_TOAST = 2
static final int MSG_TOAST_LONG = 3
static final int MSG_START_MAP_DOWNLOAD = 7
Private Attributes
final String TAG = this.getClass().getName()
ProgressDialog mapdownloader_dialog = null
NavitMapDownloader mapdownloader = null
Navit mActivity
Static Private Attributes
static final int DIALOG_SELECT_BACKUP = 3
static final int MSG_REMOVE_DIALOG_GENERIC = 99
static Handler mHandler
Constructor & Destructor Documentation
NavitDialogs()
org.navitproject.navit.NavitDialogs.NavitDialogs (Navit activity) inline package
Member Function Documentation
createDialog()
Dialog org.navitproject.navit.NavitDialogs.createDialog (int id) inline package
References org.navitproject.navit.NavitDialogs.DIALOG_BACKUP_RESTORE, org.navitproject.navit.NavitDialogs.DIALOG_MAPDOWNLOAD, org.navitproject.navit.NavitDialogs.DIALOG_SELECT_BACKUP, org.navitproject.navit.Navit.getInstance(), org.navitproject.navit.Navit.getTstring(), org.navitproject.navit.NavitDialogs.mActivity, org.navitproject.navit.NavitDialogs.mapdownloader_dialog, and org.navitproject.navit.NavitMapDownloader.stop_thread().
Referenced by org.navitproject.navit.Navit.onCreateDialog().
handleMessage()
void org.navitproject.navit.NavitDialogs.handleMessage (Message msg) inline
References org.navitproject.navit.NavitGraphics.callback_handler, org.navitproject.navit.NavitGraphics.msg_type.CLB_CALL_CMD, org.navitproject.navit.NavitGraphics.msg_type.CLB_LOAD_MAP, org.navitproject.navit.NavitDialogs.DIALOG_MAPDOWNLOAD, org.navitproject.navit.Navit.getInstance(), org.navitproject.navit.Navit.getNavitGraphics(), lat, org.navitproject.navit.NavitMapDownloader.osm_map_values.lat1, org.navitproject.navit.NavitMapDownloader.osm_map_values.lat2, org.navitproject.navit.NavitMapDownloader.osm_map_values.lon1, org.navitproject.navit.NavitMapDownloader.osm_map_values.lon2, org.navitproject.navit.NavitDialogs.MSG_MAP_DOWNLOAD_FINISHED, org.navitproject.navit.NavitDialogs.MSG_PROGRESS_BAR, org.navitproject.navit.NavitDialogs.MSG_REMOVE_DIALOG_GENERIC, org.navitproject.navit.NavitDialogs.MSG_START_MAP_DOWNLOAD, org.navitproject.navit.NavitDialogs.MSG_TOAST, org.navitproject.navit.NavitDialogs.MSG_TOAST_LONG, and org.navitproject.navit.NavitMapDownloader.osm_maps.
prepareDialog()
void org.navitproject.navit.NavitDialogs.prepareDialog (int id) inline
Referenced by org.navitproject.navit.Navit.onPrepareDialog().
sendDialogMessage()
static void org.navitproject.navit.NavitDialogs.sendDialogMessage (int what, String title, String text, int dialog_num, int value1, int value2) inline static
References data.
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate(), org.navitproject.navit.NavitMapDownloader.run(), org.navitproject.navit.NavitMapDownloader.toast(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
Field Documentation
DIALOG_BACKUP_RESTORE
final int org.navitproject.navit.NavitDialogs.DIALOG_BACKUP_RESTORE = 2 static
Referenced by org.navitproject.navit.NavitDialogs.createDialog(), and org.navitproject.navit.Navit.runOptionsItem().
DIALOG_MAPDOWNLOAD
final int org.navitproject.navit.NavitDialogs.DIALOG_MAPDOWNLOAD = 1 static
Referenced by org.navitproject.navit.NavitDialogs.createDialog(), org.navitproject.navit.NavitDialogs.handleMessage(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
DIALOG_SELECT_BACKUP
final int org.navitproject.navit.NavitDialogs.DIALOG_SELECT_BACKUP = 3 static private
Referenced by org.navitproject.navit.NavitDialogs.createDialog().
mActivity
Navit org.navitproject.navit.NavitDialogs.mActivity private
Referenced by org.navitproject.navit.NavitDialogs.createDialog().
mapdownloader
NavitMapDownloader org.navitproject.navit.NavitDialogs.mapdownloader = null private
mapdownloader_dialog
ProgressDialog org.navitproject.navit.NavitDialogs.mapdownloader_dialog = null private
Referenced by org.navitproject.navit.NavitDialogs.createDialog().
mHandler
Handler org.navitproject.navit.NavitDialogs.mHandler static private
MSG_MAP_DOWNLOAD_FINISHED
final int org.navitproject.navit.NavitDialogs.MSG_MAP_DOWNLOAD_FINISHED = 0 static package
Referenced by org.navitproject.navit.NavitDialogs.handleMessage(), and org.navitproject.navit.NavitMapDownloader.run().
MSG_PROGRESS_BAR
final int org.navitproject.navit.NavitDialogs.MSG_PROGRESS_BAR = 1 static package
Referenced by org.navitproject.navit.NavitDialogs.handleMessage(), and org.navitproject.navit.NavitMapDownloader.updateProgress().
MSG_REMOVE_DIALOG_GENERIC
final int org.navitproject.navit.NavitDialogs.MSG_REMOVE_DIALOG_GENERIC = 99 static private
Referenced by org.navitproject.navit.NavitDialogs.handleMessage().
MSG_START_MAP_DOWNLOAD
final int org.navitproject.navit.NavitDialogs.MSG_START_MAP_DOWNLOAD = 7 static package
Referenced by org.navitproject.navit.NavitDialogs.handleMessage(), and org.navitproject.navit.Navit.onActivityResult().
MSG_TOAST
final int org.navitproject.navit.NavitDialogs.MSG_TOAST = 2 static package
Referenced by org.navitproject.navit.NavitDialogs.handleMessage(), and org.navitproject.navit.NavitMapDownloader.toast().
MSG_TOAST_LONG
final int org.navitproject.navit.NavitDialogs.MSG_TOAST_LONG = 3 static package
Referenced by org.navitproject.navit.NavitDialogs.handleMessage(), org.navitproject.navit.NavitDownloadSelectMapActivity.onChildClick(), and org.navitproject.navit.NavitDownloadSelectMapActivity.onCreate().
TAG
final String org.navitproject.navit.NavitDialogs.TAG = this.getClass().getName() private
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitDialogs.java