navit: org.navitproject.navit.NavitUtils Class Reference
org.navitproject.navit.NavitUtils Class Reference
Static Package Functions
static void removeFileIfExists (String source)
static void copyFileIfExists (String source, String destination) throws IOException
Member Function Documentation
copyFileIfExists()
static void org.navitproject.navit.NavitUtils.copyFileIfExists (String source, String destination) throws IOException inline static package
Referenced by org.navitproject.navit.NavitBackupTask.doInBackground(), and org.navitproject.navit.NavitRestoreTask.doInBackground().
removeFileIfExists()
static void org.navitproject.navit.NavitUtils.removeFileIfExists (String source) inline static package
Referenced by org.navitproject.navit.NavitRestoreTask.doInBackground(), and org.navitproject.navit.NavitGraphics.CallBackHandler.handleMessage().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitUtils.java