navit: PoiObject Class Reference
PoiObject Class Reference
#include <qml_poi.h>
Signals
void nameChanged ()
void typeChanged ()
void distanceChanged ()
void iconChanged ()
Public Member Functions
PoiObject (QObject *parent=0)
PoiObject (const QString &name, const QString &type, const int distance, const QString &icon, struct pcoord &coords, QObject *parent=0)
QString name () const
void setName (const QString &name)
QString type () const
void setType (const QString &type)
float distance () const
void setDistance (const int distance)
QString icon () const
void setIcon (const QString &icon)
struct pcoord coords () const
Properties
QString name
QString type
int distance
QString icon
struct pcoord coords
Private Attributes
struct pcoord m_coords
QString m_name
QString m_type
int m_distance
QString m_icon
Constructor & Destructor Documentation
PoiObject() [1/2]
PoiObject::PoiObject (QObject * parent = 0)
PoiObject() [2/2]
PoiObject::PoiObject (const QString & name, const QString & type, const int distance, const QString & icon, struct pcoord & coords, QObject * parent = 0)
Member Function Documentation
coords()
struct pcoord PoiObject::coords () const
References m_icon.
distance()
float PoiObject::distance () const
References m_distance.
distanceChanged
void PoiObject::distanceChanged () signal
Referenced by setDistance().
icon()
QString PoiObject::icon () const
iconChanged
void PoiObject::iconChanged () signal
Referenced by setIcon().
name()
QString PoiObject::name () const
References m_name.
nameChanged
void PoiObject::nameChanged () signal
Referenced by setName().
setDistance()
void PoiObject::setDistance (const int distance)
References distance, distanceChanged(), and m_distance.
setIcon()
void PoiObject::setIcon (const QString & icon)
References icon, iconChanged(), and m_icon.
setName()
void PoiObject::setName (const QString & name)
References m_name, name, and nameChanged().
setType()
void PoiObject::setType (const QString & type)
References m_type, type, and typeChanged().
type()
QString PoiObject::type () const
References m_type.
typeChanged
void PoiObject::typeChanged () signal
Referenced by setType().
Field Documentation
m_coords
struct pcoord PoiObject::m_coords private
m_distance
int PoiObject::m_distance private
Referenced by distance(), and setDistance().
m_icon
QString PoiObject::m_icon private
Referenced by coords(), and setIcon().
m_name
QString PoiObject::m_name private
Referenced by name(), and setName().
m_type
QString PoiObject::m_type private
Referenced by setType(), and type().
Property Documentation
coords
struct pcoord PoiObject::coords
Referenced by Backend::setActivePoi(), and Backend::setActivePoiAsDestination().
distance
int PoiObject::distance read write
Referenced by setDistance().
icon
QString PoiObject::icon read write
Referenced by setIcon().
name
QString PoiObject::name read write
Referenced by Backend::setActivePoiAsDestination(), and setName().
type
QString PoiObject::type read write
Referenced by setType().
The documentation for this class was generated from the following files:
gui/qt5_qml/qml_poi.h
gui/qt5_qml/qml_poi.cpp