navit: org.navitproject.navit.Navit.StartupIntent Class Reference
org.navitproject.navit.Navit.StartupIntent Class Reference
Public Member Functions
StartupIntent (Intent intent)
boolean isRecentEnough ()
Intent getIntent ()
String toString ()
Private Member Functions
long getExpirationTimeMillis ()
Private Attributes
Intent mStartupIntent
long mStartupIntentTimestamp
Detailed Description
Nested class storing the intent that was sent to the main navit activity at startup.
Constructor & Destructor Documentation
StartupIntent()
org.navitproject.navit.Navit.StartupIntent.StartupIntent (Intent intent) inline
Constructor.
Parameters
intent The intent to store in this object
References org.navitproject.navit.Navit.StartupIntent.mStartupIntent, and org.navitproject.navit.Navit.StartupIntent.mStartupIntentTimestamp.
Referenced by org.navitproject.navit.Navit.onCreate(), and org.navitproject.navit.Navit.onNewIntent().
Member Function Documentation
getExpirationTimeMillis()
long org.navitproject.navit.Navit.StartupIntent.getExpirationTimeMillis () inline private
Compute the system time when the stored intent will become invalid.
Returns
The system time for invalidation (in ms)
References L, org.navitproject.navit.Navit.StartupIntent.mStartupIntent, and org.navitproject.navit.Navit.StartupIntent.mStartupIntentTimestamp.
Referenced by org.navitproject.navit.Navit.StartupIntent.isRecentEnough(), and org.navitproject.navit.Navit.StartupIntent.toString().
getIntent()
Intent org.navitproject.navit.Navit.StartupIntent.getIntent () inline
Getter for the encapsulated intent.
Returns
The encapsulated intent
References org.navitproject.navit.Navit.StartupIntent.mStartupIntent.
Referenced by org.navitproject.navit.Navit.buildNotification(), org.navitproject.navit.Navit.onCreate(), and org.navitproject.navit.Navit.onResume().
isRecentEnough()
boolean org.navitproject.navit.Navit.StartupIntent.isRecentEnough () inline
Check if the encapsulated intent still valid or too old.
Returns
true if the encapsulated intent is recent enough
References org.navitproject.navit.Navit.StartupIntent.getExpirationTimeMillis(), and org.navitproject.navit.Navit.StartupIntent.mStartupIntent.
Referenced by org.navitproject.navit.Navit.onResume().
toString()
String org.navitproject.navit.Navit.StartupIntent.toString () inline
Represent this object as a string.
Returns
A string containing the summary of the data we store here
References org.navitproject.navit.Navit.StartupIntent.getExpirationTimeMillis(), and org.navitproject.navit.Navit.StartupIntent.mStartupIntent.
Referenced by org.navitproject.navit.Navit.onCreate(), org.navitproject.navit.Navit.onNewIntent(), and org.navitproject.navit.Navit.onResume().
Field Documentation
mStartupIntent
Intent org.navitproject.navit.Navit.StartupIntent.mStartupIntent private
The intent we store
Referenced by org.navitproject.navit.Navit.StartupIntent.getExpirationTimeMillis(), org.navitproject.navit.Navit.StartupIntent.getIntent(), org.navitproject.navit.Navit.StartupIntent.isRecentEnough(), org.navitproject.navit.Navit.StartupIntent.StartupIntent(), and org.navitproject.navit.Navit.StartupIntent.toString().
mStartupIntentTimestamp
long org.navitproject.navit.Navit.StartupIntent.mStartupIntentTimestamp private
A timestamp (in ms) for when mStartupIntent was recorded
Referenced by org.navitproject.navit.Navit.StartupIntent.getExpirationTimeMillis(), and org.navitproject.navit.Navit.StartupIntent.StartupIntent().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/Navit.java