navit: org.navitproject.navit.NavitWatch Class Reference
org.navitproject.navit.NavitWatch Class Reference
Data Structures
class WatchHandler
Public Member Functions
native void poll (long func, int fd, int cond)
native void watchCallback (long id)
void run ()
void remove ()
Package Functions
NavitWatch (long func, int fd, int cond, long callbackid)
Private Member Functions
void callback ()
Private Attributes
Thread mThread
boolean mRemoved
long mWatchFunc
int mWatchFd
int mWatchCond
long mWatchCallbackid
boolean mCallbackPending
Runnable mCallbackRunnable
Static Private Attributes
static WatchHandler sHandler = new WatchHandler()
Constructor & Destructor Documentation
NavitWatch()
org.navitproject.navit.NavitWatch.NavitWatch (long func, int fd, int cond, long callbackid) inline package
References org.navitproject.navit.NavitWatch.callback(), org.navitproject.navit.NavitWatch.mCallbackRunnable, org.navitproject.navit.NavitWatch.mThread, org.navitproject.navit.NavitWatch.mWatchCallbackid, org.navitproject.navit.NavitWatch.mWatchCond, org.navitproject.navit.NavitWatch.mWatchFd, org.navitproject.navit.NavitWatch.mWatchFunc, and org.navitproject.navit.NavitWatch.run().
Member Function Documentation
callback()
void org.navitproject.navit.NavitWatch.callback () inline private
References org.navitproject.navit.NavitWatch.mCallbackPending, org.navitproject.navit.NavitWatch.mRemoved, org.navitproject.navit.NavitWatch.mWatchCallbackid, and org.navitproject.navit.NavitWatch.watchCallback().
Referenced by org.navitproject.navit.NavitWatch.NavitWatch().
poll()
native void org.navitproject.navit.NavitWatch.poll (long func, int fd, int cond)
Referenced by org.navitproject.navit.NavitWatch.run().
remove()
void org.navitproject.navit.NavitWatch.remove () inline
References org.navitproject.navit.NavitWatch.mRemoved, and org.navitproject.navit.NavitWatch.mThread.
run()
void org.navitproject.navit.NavitWatch.run () inline
References org.navitproject.navit.NavitWatch.mCallbackPending, org.navitproject.navit.NavitWatch.mCallbackRunnable, org.navitproject.navit.NavitWatch.mRemoved, org.navitproject.navit.NavitWatch.mWatchCond, org.navitproject.navit.NavitWatch.mWatchFd, org.navitproject.navit.NavitWatch.mWatchFunc, org.navitproject.navit.NavitWatch.poll(), and org.navitproject.navit.NavitWatch.sHandler.
Referenced by org.navitproject.navit.NavitWatch.NavitWatch().
watchCallback()
native void org.navitproject.navit.NavitWatch.watchCallback (long id)
Referenced by org.navitproject.navit.NavitWatch.callback().
Field Documentation
mCallbackPending
boolean org.navitproject.navit.NavitWatch.mCallbackPending private
Referenced by org.navitproject.navit.NavitWatch.callback(), and org.navitproject.navit.NavitWatch.run().
mCallbackRunnable
Runnable org.navitproject.navit.NavitWatch.mCallbackRunnable private
Referenced by org.navitproject.navit.NavitWatch.NavitWatch(), and org.navitproject.navit.NavitWatch.run().
mRemoved
boolean org.navitproject.navit.NavitWatch.mRemoved private
Referenced by org.navitproject.navit.NavitWatch.callback(), org.navitproject.navit.NavitWatch.remove(), and org.navitproject.navit.NavitWatch.run().
mThread
Thread org.navitproject.navit.NavitWatch.mThread private
Referenced by org.navitproject.navit.NavitWatch.NavitWatch(), and org.navitproject.navit.NavitWatch.remove().
mWatchCallbackid
long org.navitproject.navit.NavitWatch.mWatchCallbackid private
Referenced by org.navitproject.navit.NavitWatch.callback(), and org.navitproject.navit.NavitWatch.NavitWatch().
mWatchCond
int org.navitproject.navit.NavitWatch.mWatchCond private
Referenced by org.navitproject.navit.NavitWatch.NavitWatch(), and org.navitproject.navit.NavitWatch.run().
mWatchFd
int org.navitproject.navit.NavitWatch.mWatchFd private
Referenced by org.navitproject.navit.NavitWatch.NavitWatch(), and org.navitproject.navit.NavitWatch.run().
mWatchFunc
long org.navitproject.navit.NavitWatch.mWatchFunc private
Referenced by org.navitproject.navit.NavitWatch.NavitWatch(), and org.navitproject.navit.NavitWatch.run().
sHandler
WatchHandler org.navitproject.navit.NavitWatch.sHandler = new WatchHandler() static private
Referenced by org.navitproject.navit.NavitWatch.run().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitWatch.java