navit: org.navitproject.navit.NavitAddressSearchActivity Class Reference
org.navitproject.navit.NavitAddressSearchActivity Class Reference
Data Structures
class NavitAddress
Public Member Functions
void receiveAddress (int type, float latitude, float longitude, String address)
void finishAddressSearch ()
native long CallbackStartAddressSearch (int partial_match, String country, String s)
native void CallbackCancelAddressSearch (long handle)
Data Fields
RelativeLayout NavitAddressSearchActivity_layout
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Dialog onCreateDialog (int id)
Package Functions
void executeSearch ()
Package Attributes
ProgressDialog search_results_wait = null
Private Member Functions
int getDrawableID (String resourceName)
void setCountryButtonImage ()
void requestCountryDialog ()
Private Attributes
List< NavitAddress > Addresses_found = null
List< NavitAddress > addresses_shown = null
String mAddressString = ""
boolean mPartialSearch = false
String mCountry
ImageButton mCountryButton
int search_results_towns = 0
int search_results_streets = 0
int search_results_streets_hn = 0
long search_handle = 0
Static Private Attributes
static final String TAG = "NavitAddress"
static final int ADDRESS_RESULT_PROGRESS_MAX = 10
static String last_address_search_string = ""
static Boolean last_address_partial_match = false
static String last_country = ""
Member Function Documentation
native void org.navitproject.navit.NavitAddressSearchActivity.CallbackCancelAddressSearch (long handle)
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
native long org.navitproject.navit.NavitAddressSearchActivity.CallbackStartAddressSearch (int partial_match, String country, String s)
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
void org.navitproject.navit.NavitAddressSearchActivity.executeSearch () inline package
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate().
void org.navitproject.navit.NavitAddressSearchActivity.finishAddressSearch () inline
References org.navitproject.navit.NavitAddressSearchActivity.Addresses_found, org.navitproject.navit.NavitAddressSearchActivity.addresses_shown, finish(), lat, org.navitproject.navit.NavitAddressSearchActivity.mAddressString, and org.navitproject.navit.NavitAddressSearchActivity.search_results_streets.
int org.navitproject.navit.NavitAddressSearchActivity.getDrawableID (String resourceName) inline private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage().
void org.navitproject.navit.NavitAddressSearchActivity.onCreate (Bundle savedInstanceState) inline protected
References org.navitproject.navit.NavitAddressSearchActivity.executeSearch(), finish(), org.navitproject.navit.NavitAddressSearchActivity.last_address_partial_match, org.navitproject.navit.NavitAddressSearchActivity.last_address_search_string, lat, org.navitproject.navit.NavitAddressSearchActivity.mAddressString, org.navitproject.navit.NavitAddressSearchActivity.mCountry, org.navitproject.navit.NavitAddressSearchActivity.mCountryButton, org.navitproject.navit.NavitAddressSearchActivity.mPartialSearch, org.navitproject.navit.Navit.NAVIT_PREFS, org.navitproject.navit.NavitAddressSearchActivity.requestCountryDialog(), and org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage().
Dialog org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog (int id) inline protected
References org.navitproject.navit.NavitAddressSearchActivity.Addresses_found, org.navitproject.navit.NavitAddressSearchActivity.CallbackCancelAddressSearch(), org.navitproject.navit.NavitAddressSearchActivity.CallbackStartAddressSearch(), org.navitproject.navit.NavitAddressSearchActivity.mAddressString, org.navitproject.navit.NavitAddressSearchActivity.mCountry, org.navitproject.navit.NavitAddressSearchActivity.mPartialSearch, org.navitproject.navit.NavitAddressSearchActivity.search_handle, org.navitproject.navit.NavitAddressSearchActivity.search_results_streets, org.navitproject.navit.NavitAddressSearchActivity.search_results_streets_hn, org.navitproject.navit.NavitAddressSearchActivity.search_results_towns, and org.navitproject.navit.NavitAddressSearchActivity.search_results_wait.
void org.navitproject.navit.NavitAddressSearchActivity.receiveAddress (int type, float latitude, float longitude, String address) inline
start a search on the map
References org.navitproject.navit.NavitAddressSearchActivity.ADDRESS_RESULT_PROGRESS_MAX, org.navitproject.navit.NavitAddressSearchActivity.search_results_streets, org.navitproject.navit.NavitAddressSearchActivity.search_results_streets_hn, org.navitproject.navit.NavitAddressSearchActivity.search_results_towns, org.navitproject.navit.Navit.T(), and org.navitproject.navit.NavitAddressSearchActivity.TAG.
void org.navitproject.navit.NavitAddressSearchActivity.requestCountryDialog () inline private
References item, length, org.navitproject.navit.NavitAddressSearchActivity.mCountry, org.navitproject.navit.Navit.NAVIT_PREFS, and org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage().
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate().
void org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage () inline private
References org.navitproject.navit.NavitAddressSearchActivity.getDrawableID(), int, org.navitproject.navit.NavitAddressSearchActivity.mCountry, org.navitproject.navit.Navit.metrics, and size.
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate(), and org.navitproject.navit.NavitAddressSearchActivity.requestCountryDialog().
Field Documentation
final int org.navitproject.navit.NavitAddressSearchActivity.ADDRESS_RESULT_PROGRESS_MAX = 10 static private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.receiveAddress().
List<NavitAddress> org.navitproject.navit.NavitAddressSearchActivity.Addresses_found = null private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.finishAddressSearch(), and org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
List<NavitAddress> org.navitproject.navit.NavitAddressSearchActivity.addresses_shown = null private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.finishAddressSearch().
Boolean org.navitproject.navit.NavitAddressSearchActivity.last_address_partial_match = false static private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate().
String org.navitproject.navit.NavitAddressSearchActivity.last_address_search_string = "" static private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate().
String org.navitproject.navit.NavitAddressSearchActivity.last_country = "" static private
String org.navitproject.navit.NavitAddressSearchActivity.mAddressString = "" private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.finishAddressSearch(), org.navitproject.navit.NavitAddressSearchActivity.onCreate(), and org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
String org.navitproject.navit.NavitAddressSearchActivity.mCountry private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate(), org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog(), org.navitproject.navit.NavitAddressSearchActivity.requestCountryDialog(), and org.navitproject.navit.NavitAddressSearchActivity.setCountryButtonImage().
ImageButton org.navitproject.navit.NavitAddressSearchActivity.mCountryButton private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate().
boolean org.navitproject.navit.NavitAddressSearchActivity.mPartialSearch = false private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreate(), and org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
RelativeLayout org.navitproject.navit.NavitAddressSearchActivity.NavitAddressSearchActivity_layout
long org.navitproject.navit.NavitAddressSearchActivity.search_handle = 0 private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
int org.navitproject.navit.NavitAddressSearchActivity.search_results_streets = 0 private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.finishAddressSearch(), org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog(), and org.navitproject.navit.NavitAddressSearchActivity.receiveAddress().
int org.navitproject.navit.NavitAddressSearchActivity.search_results_streets_hn = 0 private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog(), and org.navitproject.navit.NavitAddressSearchActivity.receiveAddress().
int org.navitproject.navit.NavitAddressSearchActivity.search_results_towns = 0 private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog(), and org.navitproject.navit.NavitAddressSearchActivity.receiveAddress().
ProgressDialog org.navitproject.navit.NavitAddressSearchActivity.search_results_wait = null package
Referenced by org.navitproject.navit.NavitAddressSearchActivity.onCreateDialog().
final String org.navitproject.navit.NavitAddressSearchActivity.TAG = "NavitAddress" static private
Referenced by org.navitproject.navit.NavitAddressSearchActivity.receiveAddress().
The documentation for this class was generated from the following file:
android/src/org/navitproject/navit/NavitAddressSearchActivity.java