navit: QNavitGeoReceiver Class Reference
QNavitGeoReceiver Class Reference
#include <vehicle_qt5.h>
Public Slots
void positionUpdated (const QGeoPositionInfo &info)
void satellitesInUseUpdated (const QList< QGeoSatelliteInfo > &satellites)
void satellitesInViewUpdated (const QList< QGeoSatelliteInfo > &satellites)
Public Member Functions
QNavitGeoReceiver (QObject *parent, struct vehicle_priv *c)
Private Attributes
struct vehicle_priv * priv
Constructor & Destructor Documentation
QNavitGeoReceiver::QNavitGeoReceiver (QObject * parent, struct vehicle_priv * c)
References c, NULL, positionUpdated(), priv, vehicle_priv::satellites, satellitesInUseUpdated(), satellitesInViewUpdated(), and vehicle_priv::source.
Member Function Documentation
void QNavitGeoReceiver::positionUpdated (const QGeoPositionInfo & info) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::geo, vehicle_priv::have_coords, vehicle_priv::height, coord_geo::lat, coord_geo::lng, lvl_debug, priv, vehicle_priv::radius, and vehicle_priv::speed.
Referenced by QNavitGeoReceiver().
void QNavitGeoReceiver::satellitesInUseUpdated (const QList< QGeoSatelliteInfo > & satellites) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, lvl_debug, priv, and vehicle_priv::sats_used.
Referenced by QNavitGeoReceiver().
void QNavitGeoReceiver::satellitesInViewUpdated (const QList< QGeoSatelliteInfo > & satellites) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, lvl_debug, priv, and vehicle_priv::sats.
Referenced by QNavitGeoReceiver().
Field Documentation
struct vehicle_priv* QNavitGeoReceiver::priv private
Referenced by positionUpdated(), QNavitGeoReceiver(), satellitesInUseUpdated(), and satellitesInViewUpdated().
The documentation for this class was generated from the following files:
vehicle/qt5/vehicle_qt5.h
vehicle/qt5/vehicle_qt5.cpp