navit: support/libc/close.c File Reference
close.c File Reference
#include <windows.h>
#include <unistd.h>
Functions
int _close (int fildes)
int close (int fildes)
Function Documentation
int _close (int fildes)
Referenced by close().
int close (int fildes)
References _close().
Referenced by _nl_load_domain(), draw_mode(), ezxml_parse_file(), file_destroy(), gui_gtk_datawindow_new(), LoadSoundFile(), spawn_xkbd(), and vehicle_file_close().