navit: maptool/coastline.c File Reference
coastline.c File Reference
#include "maptool.h"
#include "debug.h"
Data Structures
struct coastline_tile
struct coastline_tile_data
Functions
static int distance_from_ll (struct coord *c, struct rect *bbox)
static struct geom_poly_segment * find_next (struct rect *bbox, GList *segments, struct coord *c, int exclude, struct coord *ci)
static void close_polygon (struct item_bin *ib, struct coord *from, struct coord *to, int dir, struct rect *bbox, int *edges)
static GList * tile_data_to_segments (int *tile_data)
static void tile_collector_process_tile (char *tile, int *tile_data, struct coastline_tile_data *data)
static void ocean_tile (GHashTable *hash, char *tile, char c, osmid wayid, struct item_bin_sink *out)
static void tile_collector_add_siblings (char *tile, struct coastline_tile *ct, struct coastline_tile_data *data)
static int tile_sibling_edges (GHashTable *hash, char *tile, char c)
static void tile_collector_add_siblings2 (char *tile, struct coastline_tile *ct, struct coastline_tile_data *data)
static void foreach_tile_func (gpointer key, gpointer value, gpointer user_data)
static void foreach_tile (struct coastline_tile_data *data, void(*func)(char *, struct coastline_tile *, struct coastline_tile_data *))
static int tile_collector_finish (struct item_bin_sink_func *tile_collector)
static int coastline_processor_process (struct item_bin_sink_func *func, struct item_bin *ib, struct tile_data *tile_data)
static struct item_bin_sink_func * coastline_processor_new (struct item_bin_sink *out)
static void coastline_processor_finish (struct item_bin_sink_func *coastline_processor)
void process_coastlines (FILE *in, FILE *out)
Function Documentation
static void close_polygon (struct item_bin * ib, struct coord * from, struct coord * to, int dir, struct rect * bbox, int * edges) static
References distance_from_ll(), fprintf(), rect::h, i, item_bin_add_coord(), coord::x, and coord::y.
Referenced by tile_collector_process_tile().
static void coastline_processor_finish (struct item_bin_sink_func * coastline_processor) static
References g_free(), item_bin_sink_destroy(), item_bin_sink_func_destroy(), item_bin_sink_func::priv_data, and tile_collector_finish().
Referenced by process_coastlines().
static struct item_bin_sink_func* coastline_processor_new (struct item_bin_sink * out) static
References tile_parameter::attr_to_copy, coastline_processor_process(), g_new0, item_bin_sink_add_func(), item_bin_sink_func_new(), item_bin_sink_new(), tile_parameter::max, tile_parameter::min, tile_parameter::overlap, item_bin_sink_func::priv_data, and tile_collector_new().
Referenced by process_coastlines().
static int coastline_processor_process (struct item_bin_sink_func * func, struct item_bin * ib, struct tile_data * tile_data) static
References c, item_bin::clen, i, item_bin_write_clipped(), and item_bin_sink_func::priv_data.
Referenced by coastline_processor_new().
static int distance_from_ll (struct coord * c, struct rect * bbox) static
References rect::h, coord::x, and coord::y.
Referenced by close_polygon(), find_next(), and tile_collector_process_tile().
static struct geom_poly_segment* find_next (struct rect * bbox, GList * segments, struct coord * c, int exclude, struct coord * ci) static
References _GList::data, dbg, distance_from_ll(), geom_poly_segment::first, g_list_next, i, geom_poly_segment::last, lvl_debug, NULL, coord::x, and coord::y.
Referenced by tile_collector_process_tile().
static void foreach_tile (struct coastline_tile_data * data, void(*)(char *, struct coastline_tile *, struct coastline_tile_data *) func) static
References _GList::data, foreach_tile_func(), g_hash_table_foreach(), g_list_free(), g_list_next, coastline_tile_data::k, NULL, coastline_tile_data::tile_edges, and coastline_tile_data::v.
Referenced by tile_collector_finish().
static void foreach_tile_func (gpointer key, gpointer value, gpointer user_data) static
References data, g_list_prepend(), coastline_tile_data::k, coastline_tile_data::level, and coastline_tile_data::v.
Referenced by foreach_tile().
static void ocean_tile (GHashTable * hash, char * tile, char c, osmid wayid, struct item_bin_sink * out) static
References c, coastline_tile::edges, g_alloca, g_hash_table_insert(), g_hash_table_lookup(), g_new0, g_strdup(), rect::h, init_item(), item_bin_add_attr_longlong(), item_bin_add_attr_string(), item_bin_bbox(), item_bin_init(), item_bin_write_to_sink(), NULL, tile_bbox(), coastline_tile::wayid, wayid, coord::x, and coord::y.
Referenced by tile_collector_add_siblings().
void process_coastlines (FILE * in, FILE * out)
References coastline_processor_finish(), coastline_processor_new(), file_reader_finish(), file_reader_new(), file_writer_finish(), file_writer_new(), item_bin_sink_add_func(), item_bin_sink_destroy(), and item_bin_sink_new().
Referenced by osm_process_coastlines().
static void tile_collector_add_siblings (char * tile, struct coastline_tile * ct, struct coastline_tile_data * data) static
References debug, coastline_tile::edges, edges, fprintf(), ocean_tile(), item_bin_sink_func::priv_data, coastline_tile_data::sink, coastline_tile_data::tile_edges, and coastline_tile::wayid.
Referenced by tile_collector_finish().
static void tile_collector_add_siblings2 (char * tile, struct coastline_tile * ct, struct coastline_tile_data * data) static
References debug, coastline_tile::edges, edges, fprintf(), g_alloca, g_hash_table_insert(), g_hash_table_lookup(), g_new0, g_strdup(), coastline_tile_data::level, coastline_tile_data::tile_edges, tile_sibling_edges(), and coastline_tile::wayid.
Referenced by tile_collector_finish().
static int tile_collector_finish (struct item_bin_sink_func * tile_collector) static
References foreach_tile(), fprintf(), g_free(), g_hash_table_destroy(), g_hash_table_foreach(), g_hash_table_new_full(), g_str_equal(), g_str_hash(), i, item_bin_sink_func_destroy(), coastline_tile_data::level, item_bin_sink_func::priv_data, coastline_tile_data::sink, tile_collector_add_siblings(), tile_collector_add_siblings2(), tile_collector_process_tile(), and coastline_tile_data::tile_edges.
Referenced by coastline_processor_finish().
static void tile_collector_process_tile (char * tile, int * tile_data, struct coastline_tile_data * data) static
References c, item_bin::clen, close_polygon(), coord_is_equal, coord_to_str(), _GList::data, dbg, distance_from_ll(), coastline_tile::edges, edges, find_next(), geom_poly_segment::first, fprintf(), g_free(), g_hash_table_insert(), g_list_foreach(), g_list_free(), g_list_next, g_new0, g_strdup(), g_strdup_printf(), geom_poly_area(), geom_poly_segment_destroy(), geom_poly_segment_type_none, geom_poly_segment_type_way_inner, geom_poly_segment_type_way_outer, geom_poly_segment_type_way_right_side, geom_poly_segments_sort(), rect::h, i, init_item(), item_bin_add_attr_longlong(), item_bin_add_attr_string(), item_bin_add_coord(), item_bin_bbox(), item_bin_get_wayid(), item_bin_init(), item_bin_write_to_sink(), geom_poly_segment::last, item_bin::len, LONGLONG_FMT, lvl_debug, NULL, item_bin_sink_func::priv_data, coastline_tile_data::sink, tile_bbox(), tile_data_to_segments(), coastline_tile_data::tile_edges, geom_poly_segment::type, item_bin::type, coastline_tile::wayid, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by tile_collector_finish().
static GList* tile_data_to_segments (int * tile_data) static
References fprintf(), g_list_prepend(), geom_poly_segment_type_way_right_side, item_bin_to_poly_segment(), item_bin::len, and NULL.
Referenced by tile_collector_process_tile().
static int tile_sibling_edges (GHashTable * hash, char * tile, char c) static
References c, coastline_tile::edges, g_alloca, and g_hash_table_lookup().
Referenced by tile_collector_add_siblings2().