navit: binding/python/common.h File Reference
common.h File Reference
#include "debug.h"
#include <Python.h>
Macros
#define Obj_HEAD PyObject_HEAD_INIT(&PyType_Type)
Functions
PyObject * python_object_from_attr (struct attr *attr)
PyObject * config_py (PyObject *self, PyObject *args)
PyObject * map_py_ref (struct map *map)
PyObject * navigation_py (PyObject *self, PyObject *args)
PyObject * navigation_py_ref (struct navigation *navigation)
PyObject * navit_py (PyObject *self, PyObject *args)
PyObject * navit_py_ref (struct navit *navit)
PyObject * pcoord_py (PyObject *self, PyObject *args)
struct pcoord * pcoord_py_get (PyObject *self)
PyObject * route_py (PyObject *self, PyObject *args)
PyObject * route_py_ref (struct route *route)
PyObject * attr_new_py (PyObject *self, PyObject *args)
PyObject * attr_new_py_ref (struct attr *attr)
struct attr * attr_py_get (PyObject *self)
Variables
PyTypeObject pcoord_Type
PyTypeObject attr_Type
Macro Definition Documentation
Obj_HEAD
#define Obj_HEAD PyObject_HEAD_INIT(&PyType_Type)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
attr_new_py()
PyObject * attr_new_py (PyObject * self, PyObject * args)
References attrObject::attr, attr_new_from_text(), attr_Type, name, attrObject::ref, and value.
attr_new_py_ref()
PyObject * attr_new_py_ref (struct attr * attr)
References attrObject::attr, attr_Type, and attrObject::ref.
attr_py_get()
struct attr * attr_py_get (PyObject * self)
Referenced by map_set_attr_py(), and navit_set_attr_py().
config_py()
PyObject * config_py (PyObject * self, PyObject * args)
References config_Type, dbg, and lvl_debug.
map_py_ref()
PyObject * map_py_ref (struct map * map)
References mapObject::m, map_Type, and mapObject::ref.
Referenced by navigation_get_map_py(), and route_get_map_py().
navigation_py()
PyObject * navigation_py (PyObject * self, PyObject * args)
References navigation_Type.
navigation_py_ref()
PyObject * navigation_py_ref (struct navigation * navigation)
References navigationObject::navigation, and navigation_Type.
Referenced by python_object_from_attr().
navit_py()
PyObject * navit_py (PyObject * self, PyObject * args)
References dbg, lvl_debug, and navit_Type.
navit_py_ref()
PyObject * navit_py_ref (struct navit * navit)
References dbg, lvl_debug, attr::navit, navitObject::navit, and navit_Type.
Referenced by config_navit().
pcoord_py()
PyObject * pcoord_py (PyObject * self, PyObject * args)
References c, coord_parse(), dbg, lvl_debug, pcoordObject::pc, pcoord_Type, pcoord::pro, pcoord::x, and pcoord::y.
pcoord_py_get()
struct pcoord * pcoord_py_get (PyObject * self)
Referenced by navit_set_center_py(), navit_set_destination_py(), and navit_set_position_py().
python_object_from_attr()
PyObject * python_object_from_attr (struct attr * attr)
References attr::navigation, navigation_py_ref(), attr::route, route_py_ref(), attr::type, and attr::u.
Referenced by navit_get_attr_py().
route_py()
PyObject * route_py (PyObject * self, PyObject * args)
References route_Type.
route_py_ref()
PyObject * route_py_ref (struct route * route)
References routeObject::route, and route_Type.
Referenced by python_object_from_attr().
Variable Documentation
attr_Type
PyTypeObject attr_Type extern
Referenced by attr_new_py(), attr_new_py_ref(), map_set_attr_py(), and navit_set_attr_py().
pcoord_Type
PyTypeObject pcoord_Type extern
Referenced by navit_set_center_py(), navit_set_destination_py(), navit_set_position_py(), and pcoord_py().