navit: command.h File Reference
command.h File Reference
Data Structures
struct command_table
Macros
#define command_cast(x) (int (*)(void *, char *, struct attr **, struct attr ***))(x)
Functions
char * command_error_to_text (int err)
Converts an error to human-readable text.
enum attr_type command_evaluate_to_attr (struct attr *attr, char *expr, int *error, struct attr *ret)
void command_evaluate_to_void (struct attr *attr, char *expr, int *error)
char * command_evaluate_to_string (struct attr *attr, char *expr, int *error)
int command_evaluate_to_int (struct attr *attr, char *expr, int *error)
int command_evaluate_to_boolean (struct attr *attr, const char *expr, int *error)
int command_evaluate_to_length (const char *expr, int *error)
void command_evaluate (struct attr *attr, const char *expr)
void command_add_table_attr (struct command_table *table, int count, void *data, struct attr *attr)
void command_add_table (struct callback_list *cbl, struct command_table *table, int count, void *data)
void command_saved_set_cb (struct command_saved *cs, struct callback *cb)
int command_saved_get_int (struct command_saved *cs)
Returns an integer representation of the evaluation result of a saved command.
int command_saved_error (struct command_saved *cs)
struct command_saved * command_saved_attr_new (char *command, struct attr *context, struct callback *cb, int async)
Creates a new saved command.
struct command_saved * command_saved_new (char *command, struct navit *navit, struct callback *cb, int async)
void command_saved_destroy (struct command_saved *cs)
Macro Definition Documentation
command_cast
#define command_cast (x) (int (*)(void *, char *, struct attr **, struct attr ***))(x)
Function Documentation
command_add_table()
void command_add_table (struct callback_list * cbl, struct command_table * table, int count, void * data)
References attr::callback, callback_list_add(), cbl, command_add_table_attr(), data, and attr::u.
Referenced by graphics_android_new(), gui_internal_command_init(), gui_qml_new(), navit_command_add_table(), navit_new(), and osd_rocket_init().
command_add_table_attr()
void command_add_table_attr (struct command_table * table, int count, void * data, struct attr * attr)
References attr::callback, callback_cast, callback_new_attr_3, command_table_call(), data, attr::type, and attr::u.
Referenced by command_add_table(), dbus_main_navit(), and win32_main_navit().
command_error_to_text()
char* command_error_to_text (int err)
Converts an error to human-readable text.
Parameters
err The error code
Returns
A string containing the error description. The caller is responsible for freeing up the string by calling
g_free()
when it is no longer needed.
References eof_reached, err(), illegal_character, illegal_number_format, invalid_type, missing_closing_brace, missing_closing_bracket, missing_closing_parenthesis, missing_colon, missing_double_quote, missing_opening_parenthesis, missing_semicolon, no_error, not_ready, and wrong_type.
Referenced by command_evaluate(), osd_std_config(), and osd_std_reconfigure().
command_evaluate()
void command_evaluate (struct attr * attr, const char * expr)
References context::attr, command_error_to_text(), command_evaluate_single(), dbg, eof_reached, err(), context::error, context::expr, and lvl_error.
Referenced by NGQProxyNavit::command(), gui_internal_button(), gui_internal_cmd2_set(), gui_internal_evaluate(), gui_internal_setup(), j1850_idle(), Java_org_navitproject_navit_NavitCallbackHandler_callbackMessageChannel(), main_real(), osd_cmd_interface_draw(), osd_evaluate_command(), and win32_wm_copydata().
command_evaluate_to_attr()
enum attr_type command_evaluate_to_attr (struct attr * attr, char * expr, int * error, struct attr * ret)
Referenced by gui_internal_set_refresh_callback().
command_evaluate_to_boolean()
int command_evaluate_to_boolean (struct attr * attr, const char * expr, int * error)
References result::attr, command_evaluate_to(), attr::data, context::error, context::expr, get_int(), context::res, resolve(), result_free(), attr::type, and attr::u.
Referenced by eval_postfix(), and gui_internal_html_start().
command_evaluate_to_int()
int command_evaluate_to_int (struct attr * attr, char * expr, int * error)
References command_evaluate_to(), context::error, context::expr, get_int(), context::res, resolve(), and result_free().
command_evaluate_to_length()
int command_evaluate_to_length (const char * expr, int * error)
References command_evaluate_to(), attr::data, context::error, context::expr, context::res, result_free(), attr::type, and attr::u.
Referenced by eval_postfix().
command_evaluate_to_string()
char* command_evaluate_to_string (struct attr * attr, char * expr, int * error)
References command_evaluate_to(), context::error, context::expr, get_string(), context::res, resolve(), and result_free().
Referenced by request_navit_evaluate().
command_evaluate_to_void()
void command_evaluate_to_void (struct attr * attr, char * expr, int * error)
References command_evaluate_to(), context::error, context::expr, context::res, resolve(), and result_free().
Referenced by script_run().
command_saved_attr_new()
struct command_saved* command_saved_attr_new (char * command, struct attr * attr, struct callback * cb, int async)
Creates a new saved command.
Parameters
command The command string
attr The context attribute for the saved command
cb The callback to call whenver the command is re-evaluated
async Whether the saved command should be flagged as asynchronous, causing it to be evaluated in an idle callback
References command_saved::async, callback_cast, callback_new_1, command_saved::cb, command_saved::command, command(), command_register_callbacks(), command_saved_callbacks_changed(), command_saved::context_attr, dbg, command_saved::error, event_add_idle(), lvl_debug, not_ready, command_saved::register_cb, and command_saved::register_ev.
Referenced by command_saved_new(), and script_set_attr_int().
command_saved_destroy()
void command_saved_destroy (struct command_saved * cs)
Referenced by script_destroy(), and script_set_attr_int().
command_saved_error()
int command_saved_error (struct command_saved * cs)
References command_saved::error.
Referenced by osd_std_config(), and osd_std_reconfigure().
command_saved_get_int()
int command_saved_get_int (struct command_saved * cs)
Returns an integer representation of the evaluation result of a saved command.
This function is a wrapper around
get_int()
. It is equivalent to
get_int(&cs->ctx, &cs->res)
. See
get_int()
for a description.
References command_saved::ctx, get_int(), and command_saved::res.
Referenced by osd_std_config(), and osd_std_reconfigure().
command_saved_new()
struct command_saved* command_saved_new (char * command, struct navit * navit, struct callback * cb, int async)
References ATTR_OBJECT, command(), and command_saved_attr_new().
Referenced by osd_set_std_attr().
command_saved_set_cb()
void command_saved_set_cb (struct command_saved * cs, struct callback * cb)
References command_saved::cb.
Referenced by osd_std_config().