navit: support/espeak/compiledict.c File Reference
compiledict.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "translate.h"
Data Structures
struct RGROUP
Macros
#define __cdecl
#define LEN_GROUP_NAME 12
#define N_RULES 2000
#define N_LETTERGP_ITEMS 200
Functions
void Write4Bytes (FILE *f, int value)
int HashDictionary (const char *string)
int isspace2 (unsigned int c)
static const char * LookupMnem2 (MNEM_TAB *table, int value)
char * print_dictionary_flags (unsigned int *flags)
static FILE * fopen_log (const char *fname, const char *access)
static int compile_line (char *linebuf, char *dict_line, int *hash)
static void compile_dictlist_start (void)
static void compile_dictlist_end (FILE *f_out)
static int compile_dictlist_file (const char *path, const char *filename)
static void copy_rule_string (char *string, int *state)
static char * compile_rule (char *input)
static int __cdecl string_sorter (char **a, char **b)
static int __cdecl rgroup_sorter (RGROUP *a, RGROUP *b)
static void output_rule_group (FILE *f_out, int n_rules, char **rules, char *name)
static int compile_lettergroup (char *input, FILE *f_out)
static int compile_dictrules (FILE *f_in, FILE *f_out, char *fname_temp)
int CompileDictionary (const char *dsource, const char *dict_name, FILE *log, char *fname_err, int flags)
Variables
static FILE * f_log = NULL
char * dir_dictionary
static int linenum
static int error_count
static int transpose_offset
static int transpose_min
static int transpose_max
static int text_mode = 0
static int debug_flag = 0
static int hash_counts [N_HASH_DICT]
static char * hash_chains [N_HASH_DICT]
static char letterGroupsDefined [N_LETTER_GROUPS]
MNEM_TAB mnem_flags []
static char rule_cond [80]
static char rule_pre [80]
static char rule_post [80]
static char rule_match [80]
static char rule_phonemes [80]
static char group_name [LEN_GROUP_NAME+1]
Macro Definition Documentation
#define __cdecl
Referenced by compile_dictrules(), and output_rule_group().
#define LEN_GROUP_NAME 12
Referenced by compile_dictrules().
#define N_LETTERGP_ITEMS 200
Referenced by compile_lettergroup().
#define N_RULES 2000
Referenced by compile_dictrules().
Function Documentation
static void compile_dictlist_end (FILE * f_out) static
References f_log, fprintf(), hash_chains, hash_counts, int, length, N_HASH_DICT, NULL, and p.
Referenced by CompileDictionary().
static int compile_dictlist_file (const char * path, const char * filename) static
References buf, compile_line(), error_count, f_log, fprintf(), hash_chains, hash_counts, length, linenum, NULL, p, path_home, sprintf(), and text_mode.
Referenced by CompileDictionary().
static void compile_dictlist_start (void) static
References hash_chains, hash_counts, N_HASH_DICT, NULL, and p.
Referenced by CompileDictionary().
static int compile_dictrules (FILE * f_in, FILE * f_out, char * fname_temp) static
References __cdecl, buf, c, compile_lettergroup(), compile_rule(), error_count, f_log, fopen_log(), fprintf(), isspace2(), LEN_GROUP_NAME, length, RGROUP::length, linenum, N_RULE_GROUP2, N_RULES, NULL, output_rule_group(), p, rgroup_sorter(), RULE_GROUP_END, RULE_GROUP_START, RULE_REPLACEMENTS, SEEK_SET, RGROUP::start, start, utf8_in(), and Write4Bytes().
Referenced by CompileDictionary().
static int compile_lettergroup (char * input, FILE * f_out) static
References error_count, f_log, fprintf(), isspace2(), length, letterGroupsDefined, linenum, N_LETTER_GROUPS, N_LETTERGP_ITEMS, p, RULE_GROUP_END, RULE_GROUP_START, and RULE_LETTERGP2.
Referenced by compile_dictrules().
static int compile_line (char * linebuf, char * dict_line, int * hash) static
References BITNUM_FLAG_ALLCAPS, BITNUM_FLAG_HYPHENATED, BITNUM_FLAG_ONLY_S, BITNUM_FLAG_TEXTMODE, c, c2, DecodePhonemes(), EncodePhonemes(), error_count, f_log, fprintf(), HashDictionary(), isspace2(), Translator::langopts, length, linenum, LookupMnem(), N_WORD_BYTES, NULL, p, phonSWITCH, strncpy0(), text_mode, LANGUAGE_OPTIONS::textmode, translator, transpose_max, transpose_min, transpose_offset, TransposeAlphabet(), utf8_in(), and utf8_out().
Referenced by compile_dictlist_file().
static char* compile_rule (char * input) static
References buf, c, copy_rule_string(), debug_flag, EncodePhonemes(), error_count, f_log, finish(), fprintf(), IsDigit(), linenum, NULL, p, RULE_CONDITION, RULE_LINENUM, RULE_POST, RULE_PRE, sprintf(), and utf8_in().
Referenced by compile_dictrules().
int CompileDictionary (const char * dsource, const char * dict_name, FILE * log, char * fname_err, int flags)
References compile_dictlist_end(), compile_dictlist_file(), compile_dictlist_start(), compile_dictrules(), debug_flag, error_count, f_log, fopen_log(), fprintf(), Translator::langopts, letterGroupsDefined, LANGUAGE_OPTIONS::listx, LoadDictionary(), N_HASH_DICT, NULL, path_home, PATHSEP, phoneme_tab_list, phoneme_tab_number, SEEK_SET, sprintf(), translator, transpose_max, transpose_min, transpose_offset, value, and Write4Bytes().
Referenced by espeak_CompileDictionary(), and main().
static void copy_rule_string (char * string, int * state) static
References c, error_count, f_log, fprintf(), isspace2(), LETTERGP_A, LETTERGP_B, LETTERGP_C, LETTERGP_F, LETTERGP_G, LETTERGP_H, LETTERGP_Y, letterGroupsDefined, linenum, N_LETTER_GROUPS, outbuf, p, RULE_ALT1, RULE_CAPITAL, rule_cond, RULE_DEL_FWD, RULE_DIGIT, RULE_DOUBLE, RULE_ENDING, RULE_IFVERB, RULE_INC_SCORE, RULE_LETTERGP, RULE_LETTERGP2, rule_match, RULE_NO_SUFFIX, RULE_NONALPHA, RULE_NOTVOWEL, RULE_NOVOWELS, rule_post, rule_pre, RULE_SPACE, RULE_SPELLING, RULE_STRESSED, RULE_SYLLABLE, SUFX_B, SUFX_D, SUFX_E, SUFX_F, SUFX_I, SUFX_P, SUFX_Q, SUFX_T, SUFX_V, and value.
Referenced by compile_rule().
static FILE* fopen_log (const char * fname, const char * access) static
References f_log, fprintf(), and NULL.
Referenced by compile_dictrules(), and CompileDictionary().
int HashDictionary (const char * string)
References c.
Referenced by compile_line(), and LookupDict2().
int isspace2 (unsigned int c)
References c2.
Referenced by compile_dictrules(), compile_lettergroup(), compile_line(), copy_rule_string(), and TranslateClause().
static const char* LookupMnem2 (MNEM_TAB * table, int value) static
References MNEM_TAB::mnem, NULL, and MNEM_TAB::value.
Referenced by print_dictionary_flags().
static void output_rule_group (FILE * f_out, int n_rules, char ** rules, char * name) static
References __cdecl, f_log, p, printf(), RULE_PH_COMMON, RULE_PHONEMES, and string_sorter().
Referenced by compile_dictrules().
char* print_dictionary_flags (unsigned int * flags)
References buf, LookupMnem2(), and sprintf().
Referenced by LookupDict2().
static int __cdecl rgroup_sorter (RGROUP * a, RGROUP * b) static
References RGROUP::name, and RGROUP::start.
Referenced by compile_dictrules().
static int __cdecl string_sorter (char ** a, char ** b) static
Referenced by output_rule_group().
void Write4Bytes (FILE * f, int value)
Referenced by compile_dictrules(), and CompileDictionary().
Variable Documentation
int debug_flag = 0 static
Referenced by compile_rule(), and CompileDictionary().
char* dir_dictionary
int error_count static
Referenced by compile_dictlist_file(), compile_dictrules(), compile_lettergroup(), compile_line(), compile_rule(), CompileDictionary(), and copy_rule_string().
FILE* f_log = NULL static
Referenced by compile_dictlist_end(), compile_dictlist_file(), compile_dictrules(), compile_lettergroup(), compile_line(), compile_rule(), CompileDictionary(), copy_rule_string(), fopen_log(), and output_rule_group().
char group_name[LEN_GROUP_NAME+1] static
Referenced by TranslateRules().
char* hash_chains[N_HASH_DICT] static
Referenced by compile_dictlist_end(), compile_dictlist_file(), and compile_dictlist_start().
int hash_counts[N_HASH_DICT] static
Referenced by compile_dictlist_end(), compile_dictlist_file(), and compile_dictlist_start().
char letterGroupsDefined[N_LETTER_GROUPS] static
Referenced by compile_lettergroup(), CompileDictionary(), and copy_rule_string().
int linenum static
Referenced by compile_dictlist_file(), compile_dictrules(), compile_lettergroup(), compile_line(), compile_rule(), copy_rule_string(), and DecodeRule().
MNEM_TAB mnem_flags[]
char rule_cond[80] static
Referenced by copy_rule_string().
char rule_match[80] static
Referenced by copy_rule_string().
char rule_phonemes[80] static
char rule_post[80] static
Referenced by copy_rule_string().
char rule_pre[80] static
Referenced by copy_rule_string().
int text_mode = 0 static
Referenced by compile_dictlist_file(), and compile_line().
int transpose_max static
Referenced by compile_line(), and CompileDictionary().
int transpose_min static
Referenced by compile_line(), and CompileDictionary().
int transpose_offset static
Referenced by compile_line(), and CompileDictionary().