navit: config_.c File Reference
config_.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <signal.h>
#include "debug.h"
#include "item.h"
#include "xmlconfig.h"
#include "callback.h"
#include "navit.h"
#include "config_.h"
#include "file.h"
Data Structures
struct config
struct attr_iter
Functions
struct config * config_get (void)
void config_destroy (struct config *this_)
static void config_terminate (int sig)
static void config_new_int (void)
int config_get_attr (struct config *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
static int config_set_attr_int (struct config *this_, struct attr *attr)
int config_set_attr (struct config *this_, struct attr *attr)
int config_add_attr (struct config *this_, struct attr *attr)
int config_remove_attr (struct config *this_, struct attr *attr)
struct attr_iter * config_attr_iter_new ()
void config_attr_iter_destroy (struct attr_iter *iter)
struct config * config_new (struct attr *parent, struct attr **attrs)
Variables
struct config * config
int config_empty_ok
int configured
struct object_func config_func
Function Documentation
int config_add_attr (struct config * this_, struct attr * attr)
References config, config_new_int(), and navit_object_add_attr().
Referenced by plugin_init().
void config_attr_iter_destroy (struct attr_iter * iter)
References navit_object_attr_iter_destroy().
Referenced by plugin_init(), and request_config_attr_iter_destroy().
struct attr_iter* config_attr_iter_new (void)
References navit_object_attr_iter_new().
Referenced by plugin_init(), and request_config_attr_iter().
void config_destroy (struct config * this_)
References attr_list_free(), exit, and g_free().
Referenced by config_new(), and config_terminate().
struct config* config_get (void)
References config.
Referenced by Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_CallbackMessageChannel(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), and Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry().
int config_get_attr (struct config * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), and NULL.
Referenced by config_navit(), invoke(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_CallbackMessageChannel(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), main_real(), NPP_SetWindow(), plugin_init(), request_config_get_attr(), and resolve_object().
struct config* config_new (struct attr * parent, struct attr ** attrs)
References attr_generic_add_attr_list(), attr_to_name(), config, config_destroy(), config_func, config_new_int(), config_set_attr_int(), configured, dbg, lvl_error, navit_object_ref(), and NULL.
static void config_new_int (void) static
References config_terminate(), g_new0, and signal().
Referenced by config_add_attr(), and config_new().
int config_remove_attr (struct config * this_, struct attr * attr)
References navit_object_remove_attr().
Referenced by gui_internal_cmd2_quit(), and request_navit_quit().
int config_set_attr (struct config * this_, struct attr * attr)
References config_set_attr_int(), and navit_object_set_attr().
static int config_set_attr_int (struct config * this_, struct attr * attr) static
References file_set_cache_size(), attr::num, setenv(), attr::str, attr::type, and attr::u.
Referenced by config_new(), and config_set_attr().
static void config_terminate (int sig) static
References config_destroy(), dbg, and lvl_debug.
Referenced by config_new_int().
Variable Documentation
struct config * config
Referenced by config_add_attr(), config_get(), config_new(), and main_real().
int config_empty_ok
struct object_func config_func
Initial value:
= {
        attr_config,
        (object_func_new)config_new,
        (object_func_get_attr)navit_object_get_attr,
        (object_func_iter_new)navit_object_attr_iter_new,
        (object_func_iter_destroy)navit_object_attr_iter_destroy,
        (object_func_set_attr)config_set_attr,
        (object_func_add_attr)config_add_attr,
        (object_func_remove_attr)navit_object_remove_attr,
        (object_func_init)NULL,
        (object_func_destroy)NULL,
        (object_func_dup)NULL,
        (object_func_ref)navit_object_ref,
        (object_func_unref)navit_object_unref,
}
Referenced by config_new(), and object_func_lookup().
int configured
Referenced by config_new(), and osd_std_click().