navit: country.h File Reference
country.h File Reference
Functions
struct country_search * country_search_new (struct attr *search, int partial)
struct item * country_search_get_item (struct country_search *this_)
struct attr * country_default (void)
void country_search_destroy (struct country_search *this_)
Function Documentation
struct attr* country_default (void)
References country_default_attr, getenv, iso2, NULL, attr::str, attr::type, and attr::u.
Referenced by destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), and NGQProxySearch::NGQProxySearch().
void country_search_destroy (struct country_search * this_)
References g_free(), country_search::search, attr::str, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_destroy(), and NGQProxySearch::NGQProxySearch().
struct item* country_search_get_item (struct country_search * this_)
References country::car, country_search::count, country_search::country, country::id, item::id_lo, country::iso2, country::iso3, country_search::item, match(), country::name, navit_nls_gettext(), NULL, attr::num, country_search::search, attr::type, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_get_item(), and NGQProxySearch::NGQProxySearch().
struct country_search* country_search_new (struct attr * search, int partial)
References country_search::count, country_meth, g_new, item::id_hi, country_search::item, country_search::len, linguistics_casefold(), item::map, item::meth, NULL, country_search::partial, item::priv_data, country_search::search, attr::str, item::type, attr::type, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_new(), and NGQProxySearch::NGQProxySearch().