navit: country.c File Reference
country.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include "debug.h"
#include "item.h"
#include "country.h"
#include "search.h"
#include "linguistics.h"
#include "navit_nls.h"
Data Structures
struct country
struct country_search
Functions
static int country_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
struct country_search * country_search_new (struct attr *search, int partial)
static int match (struct country_search *this_, enum attr_type type, const char *name)
struct item * country_search_get_item (struct country_search *this_)
struct attr * country_default (void)
void country_search_destroy (struct country_search *this_)
Variables
static struct country country []
struct item_methods country_meth
static struct attr country_default_attr
static char iso2 [3]
Function Documentation
static int country_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References country_search::attr_next, country::car, country_search::country, country::id, country::iso2, country::iso3, country::name, navit_nls_gettext(), attr::num, attr::str, attr::type, and attr::u.
struct attr* country_default (void)
References country_default_attr, getenv, iso2, NULL, attr::str, attr::type, and attr::u.
Referenced by destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), and NGQProxySearch::NGQProxySearch().
void country_search_destroy (struct country_search * this_)
References g_free(), country_search::search, attr::str, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_destroy(), and NGQProxySearch::NGQProxySearch().
struct item* country_search_get_item (struct country_search * this_)
References country::car, country_search::count, country_search::country, country::id, item::id_lo, country::iso2, country::iso3, country_search::item, match(), country::name, navit_nls_gettext(), NULL, attr::num, country_search::search, attr::type, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_get_item(), and NGQProxySearch::NGQProxySearch().
struct country_search* country_search_new (struct attr * search, int partial)
References country_search::count, country_meth, g_new, item::id_hi, country_search::item, country_search::len, linguistics_casefold(), item::map, item::meth, NULL, country_search::partial, item::priv_data, country_search::search, attr::str, item::type, attr::type, and attr::u.
Referenced by country_id_from_iso2(), destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), map_search_new(), and NGQProxySearch::NGQProxySearch().
static int match (struct country_search * this_, enum attr_type type, const char * name) static
References linguistics_cmp_expand, linguistics_cmp_partial, linguistics_cmp_words, linguistics_compare(), country_search::partial, country_search::search, attr::str, attr::type, and attr::u.
Referenced by country_search_get_item(), gui_internal_cmd_pois_item_selected(), linguistics_expand_special(), MatchRule(), osm_process_town_by_boundary(), and vehicle_draw_do().
Variable Documentation
struct country country[] static
Referenced by espeak_new(), gui_internal_search(), org.navitproject.navit.Navit::onCreate(), osm_process_town_by_is_in(), process_boundaries_setup(), qt5_espeak_init_language(), town_country_list_insert_if_new(), town_country_new(), and town_search_compare().
struct attr country_default_attr static
Referenced by country_default().
struct item_methods country_meth
Initial value:
= {
        NULL,
        NULL,
        NULL,
        country_attr_get,
}
Referenced by country_search_new().
char iso2[3] static
Referenced by country_default(), and gui_internal_search_town_in_country().