navit: map/csv/csv.c File Reference
csv.c File Reference
#include "config.h"
#include <stdlib.h>
#include <glib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include "debug.h"
#include "plugin.h"
#include "projection.h"
#include "item.h"
#include "map.h"
#include "maptype.h"
#include "attr.h"
#include "transform.h"
#include "file.h"
#include "quadtree.h"
#include "csv.h"
Data Structures
struct quadtree_data
Functions
static int csv_coord_set (void *priv_data, struct coord *c, int count, enum change_mode mode)
static struct item * csv_create_item (struct map_rect_priv *mr, enum item_type it_type)
static void quadtree_item_free (void *mr, struct quadtree_item *qitem)
static void quadtree_item_free_do (void *qitem)
struct quadtree_data * quadtree_data_dup (struct quadtree_data *qdata)
static void save_map_csv (struct map_priv *m)
static void map_destroy_csv (struct map_priv *m)
static void csv_coord_rewind (void *priv_data)
static int csv_coord_get (void *priv_data, struct coord *c, int count)
static void csv_attr_rewind (void *priv_data)
static int csv_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int csv_attr_set (void *priv_data, struct attr *attr, enum change_mode mode)
static int csv_type_set (void *priv_data, enum item_type type)
static void map_csv_debug_dump_hash_item (gpointer key, gpointer value, gpointer user_data)
static void map_csv_debug_dump (struct map_priv *map)
static struct map_rect_priv * map_rect_new_csv (struct map_priv *map, struct map_selection *sel)
static void map_rect_destroy_csv (struct map_rect_priv *mr)
static struct item * map_rect_get_item_csv (struct map_rect_priv *mr)
static struct item * map_rect_get_item_byid_csv (struct map_rect_priv *mr, int id_hi, int id_lo)
static int csv_get_attr (struct map_priv *m, enum attr_type type, struct attr *attr)
static struct map_priv * map_new_csv (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
static int map_id
static const int zoom_max = 18
static struct item_methods methods_csv
static struct map_methods map_methods_csv
Function Documentation
static int csv_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References map_rect_priv::at_iter, map_priv::attr_cnt, quadtree_data::attr_list, map_priv::attr_types, quadtree_item::data, _GList::data, g_list_next, i, map_rect_priv::m, NULL, and map_rect_priv::qitem.
static void csv_attr_rewind (void * priv_data) static
static int csv_attr_set (void * priv_data, struct attr * attr, enum change_mode mode) static
References map_priv::attr_cnt, attr_dup(), attr_free(), quadtree_data::attr_list, map_priv::attr_types, change_mode_append, change_mode_delete, change_mode_modify, change_mode_prepend, quadtree_item::data, _GList::data, map_priv::dirty, g_list_delete_link(), g_list_next, g_list_prepend(), i, map_rect_priv::m, map_rect_priv::qitem, save_map_csv(), type, and attr::type.
static int csv_coord_get (void * priv_data, struct coord * c, int count) static
References map_rect_priv::c.
static void csv_coord_rewind (void * priv_data) static
static int csv_coord_set (void * priv_data, struct coord * c, int count, enum change_mode mode) static
References change_mode_modify, quadtree_item::data, _GList::data, dbg, map_priv::dirty, g_list_next, g_list_remove_link(), g_new0, coord_geo::lat, quadtree_item::latitude, coord_geo::lng, quadtree_item::longitude, lvl_debug, map_rect_priv::m, map_priv::new_items, projection_mg, map_rect_priv::qitem, map_rect_priv::qiter, quadtree_add(), quadtree_data_dup(), quadtree_delete_item(), quadtree_find_item(), quadtree_item::ref_count, save_map_csv(), transform_to_geo(), map_priv::tree_root, coord::x, and coord::y.
static struct item * csv_create_item (struct map_rect_priv * mr, enum item_type it_type) static
References quadtree_data::attr_list, quadtree_item::data, map_priv::dirty, map_priv::flags, g_hash_table_insert(), g_list_prepend(), g_new, g_new0, item::id_hi, item::id_lo, quadtree_data::item, map_rect_priv::item, item_new(), map_priv::item_type, quadtree_item::latitude, quadtree_item::longitude, map_rect_priv::m, item::meth, methods_csv, map_priv::new_items, map_priv::next_item_idx, NULL, item::priv_data, map_rect_priv::qitem, map_priv::qitem_hash, quadtree_item::ref_count, item::type, and zoom_max.
static int csv_get_attr (struct map_priv * m, enum attr_type type, struct attr * attr) static
static int csv_type_set (void * priv_data, enum item_type type) static
References dbg, quadtree_item::deleted, lvl_debug, and map_rect_priv::qitem.
static void map_csv_debug_dump (struct map_priv * map) static
Dump all map data (including deleted items) to the log.
References g_hash_table_foreach(), map_csv_debug_dump_hash_item(), NULL, and map_priv::qitem_hash.
Referenced by map_rect_new_csv().
static void map_csv_debug_dump_hash_item (gpointer key, gpointer value, gpointer user_data) static
References quadtree_item::data, _GList::data, dbg, quadtree_item::deleted, g_list_next, lvl_debug, quadtree_item::ref_count, type, and value.
Referenced by map_csv_debug_dump().
static void map_destroy_csv (struct map_priv * m) static
References map_priv::attr_types, map_priv::charset, dbg, map_priv::filename, g_free(), g_hash_table_destroy(), lvl_debug, map_priv::qitem_hash, quadtree_destroy(), save_map_csv(), and map_priv::tree_root.
static struct map_priv* map_new_csv (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References map_priv::attr_cnt, ATTR_IS_DOUBLE, ATTR_IS_INT, ATTR_IS_STRING, quadtree_data::attr_list, attr_search(), map_priv::attr_types, attr::attr_types, map_priv::charset, map_methods::charset, quadtree_item::data, data, dbg, errno, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_new(), map_priv::filename, map_priv::flags, fp, g_alloca, g_convert(), g_free(), g_hash_table_insert(), g_hash_table_new_full(), g_int_equal(), g_int_hash(), g_list_prepend(), g_new, g_new0, g_realloc(), g_strdup(), map_priv::id, item::id_hi, item::id_lo, quadtree_data::item, item_new(), map_priv::item_type, attr::item_type, quadtree_item::latitude, quadtree_item::longitude, lvl_debug, lvl_error, lvl_info, map_id, map_methods_csv, item::meth, methods_csv, map_priv::next_item_idx, NULL, attr::num, attr::numd, map_priv::qitem_hash, quadtree_add(), quadtree_item_free_do(), quadtree_node_new(), attr::str, strerror(), map_priv::tree_root, item::type, attr::type, attr::u, and zoom_max.
Referenced by plugin_init().
static void map_rect_destroy_csv (struct map_rect_priv * mr) static
References g_free(), map_rect_priv::qitem, map_rect_priv::qiter, quadtree_query_free(), and quadtree_item::ref_count.
static struct item* map_rect_get_item_byid_csv (struct map_rect_priv * mr, int id_hi, int id_lo) static
References quadtree_item::data, g_hash_table_lookup(), map_rect_priv::item, map_rect_priv::m, NULL, item::priv_data, map_rect_priv::qitem, map_priv::qitem_hash, and quadtree_item::ref_count.
static struct item* map_rect_get_item_csv (struct map_rect_priv * mr) static
References map_rect_priv::c, quadtree_item::data, map_rect_priv::item, coord_geo::lat, quadtree_item::latitude, coord_geo::lng, quadtree_item::longitude, NULL, item::priv_data, projection_mg, map_rect_priv::qitem, map_rect_priv::qiter, quadtree_item_next(), quadtree_item::ref_count, and transform_from_geo().
static struct map_rect_priv* map_rect_new_csv (struct map_priv * map, struct map_selection * sel) static
References map_rect_priv::bStarted, map_selection::c_rect, dbg, debug_level_get(), map_priv::flags, g_new0, item::id_hi, item::id_lo, map_rect_priv::item, coord_geo::lat, coord_geo::lng, coord_rect::lu, lvl_debug, map_rect_priv::m, map_csv_debug_dump(), item::meth, methods_csv, NULL, item::priv_data, projection_mg, map_rect_priv::qitem, map_rect_priv::qiter, quadtree_item_free(), quadtree_query(), coord_rect::rl, map_rect_priv::sel, transform_to_geo(), map_priv::tree_root, and map_selection::u.
void plugin_init (void)
References dbg, lvl_debug, and map_new_csv().
struct quadtree_data* quadtree_data_dup (struct quadtree_data * qdata)
References attr_dup(), quadtree_data::attr_list, _GList::data, g_list_next, g_list_prepend(), g_new, g_new0, quadtree_data::id_lo, quadtree_data::item, and quadtree_data::type.
Referenced by csv_coord_set().
static void quadtree_item_free (void * mr, struct quadtree_item * qitem) static
References quadtree_item::data, g_hash_table_remove(), item::id_lo, quadtree_data::item, and map_priv::qitem_hash.
Referenced by map_rect_new_csv(), and save_map_csv().
static void quadtree_item_free_do (void * qitem) static
References attr_free(), quadtree_data::attr_list, quadtree_item::data, _GList::data, data, g_free(), g_list_free(), g_list_next, and quadtree_data::item.
Referenced by map_new_csv().
static void save_map_csv (struct map_priv * m) static
References map_priv::attr_cnt, ATTR_IS_DOUBLE, ATTR_IS_INT, ATTR_IS_STRING, quadtree_data::attr_list, attr_to_name(), map_priv::attr_types, map_priv::charset, quadtree_item::data, _GList::data, dbg, quadtree_item::deleted, map_priv::dirty, map_priv::filename, filename, fp, fprintf(), g_convert(), g_free(), g_list_next, g_strdup(), g_strdup_printf(), i, eval::iter, quadtree_item::latitude, quadtree_item::longitude, lvl_debug, lvl_error, NULL, attr::num, attr::numd, quadtree_item_free(), quadtree_item_next(), quadtree_query(), quadtree_query_free(), rename(), attr::str, map_priv::tree_root, attr::u, and unlink().
Referenced by csv_attr_set(), csv_coord_set(), and map_destroy_csv().
Variable Documentation
int map_id static
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by map_new_csv().
struct map_methods map_methods_csv static
Initial value:
= {
        projection_mg,
        "utf-8",
        map_destroy_csv,
        map_rect_new_csv,
        map_rect_destroy_csv,
        map_rect_get_item_csv,
        map_rect_get_item_byid_csv,
        NULL,
        NULL,
        NULL,
        csv_create_item,
        csv_get_attr,
}
Referenced by map_new_csv().
struct item_methods methods_csv static
Initial value:
= {
        csv_coord_rewind,
        csv_coord_get,
        csv_attr_rewind,
        csv_attr_get,
        NULL,
        csv_attr_set,
        csv_coord_set,
        csv_type_set
}
Referenced by csv_create_item(), map_new_csv(), and map_rect_new_csv().
const int zoom_max = 18 static
Referenced by csv_create_item(), and map_new_csv().