navit: gui/gtk/datawindow.c File Reference
datawindow.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>
#include "debug.h"
#include "callback.h"
#include "param.h"
#include "data_window.h"
#include "gui_gtk.h"
Data Structures
struct datawindow_priv
Functions
static void select_row (GtkTreeView *tree, GtkTreePath *path, GtkTreeViewColumn *column, struct datawindow_priv *win)
static void gui_gtk_datawindow_add (struct datawindow_priv *win, struct param_list *param, int count)
static void gui_gtk_datawindow_mode (struct datawindow_priv *win, int start)
static gboolean gui_gtk_datawindow_delete (GtkWidget *widget, GdkEvent *event, struct datawindow_priv *win)
void gui_gtk_datawindow_destroy (struct datawindow_priv *win)
void gui_gtk_datawindow_set_button (struct datawindow_priv *this_, GtkWidget *btn)
static gboolean keypress (GtkWidget *widget, GdkEventKey *event, struct datawindow_priv *win)
struct datawindow_priv * gui_gtk_datawindow_new (struct gui_priv *gui, const char *name, struct callback *click, struct callback *close, struct datawindow_methods *meth)
Variables
static GValue value
static struct datawindow_methods gui_gtk_datawindow_meth
Function Documentation
static void gui_gtk_datawindow_add (struct datawindow_priv * win, struct param_list * param, int count) static
References i, eval::iter, datawindow_priv::liststore, param_list::name, name, NULL, datawindow_priv::scrolled_window, select_row(), datawindow_priv::sortmodel, datawindow_priv::treeview, types, param_list::value, value, and datawindow_priv::window.
static gboolean gui_gtk_datawindow_delete (GtkWidget * widget, GdkEvent * event, struct datawindow_priv * win) static
References datawindow_priv::button, callback_call_0, datawindow_priv::close, and FALSE.
Referenced by gui_gtk_datawindow_destroy(), gui_gtk_datawindow_new(), and keypress().
void gui_gtk_datawindow_destroy (struct datawindow_priv * win)
References gui_priv::datawindow, datawindow_priv::gui, gui_gtk_datawindow_delete(), NULL, and datawindow_priv::window.
Referenced by roadbook_action().
static void gui_gtk_datawindow_mode (struct datawindow_priv * win, int start) static
References NULL, and datawindow_priv::treeview.
struct datawindow_priv* gui_gtk_datawindow_new (struct gui_priv * gui, const char * name, struct callback * click, struct callback * close, struct datawindow_methods * meth)
References datawindow_priv::click, close(), datawindow_priv::close, gui_priv::datawindow, g_new0, datawindow_priv::gui, gui_gtk_datawindow_delete(), gui_gtk_datawindow_meth, keypress(), NULL, datawindow_priv::scrolled_window, datawindow_priv::treeview, gui_priv::win, and datawindow_priv::window.
void gui_gtk_datawindow_set_button (struct datawindow_priv * this_, GtkWidget * btn)
References datawindow_priv::button.
Referenced by roadbook_action().
static gboolean keypress (GtkWidget * widget, GdkEventKey * event, struct datawindow_priv * win) static
References FALSE, gui_gtk_datawindow_delete(), and datawindow_priv::window.
Referenced by gui_gtk_datawindow_new().
static void select_row (GtkTreeView * tree, GtkTreePath * path, GtkTreeViewColumn * column, struct datawindow_priv * win) static
References callback_call_1, datawindow_priv::click, gui_priv::cols, dbg, i, eval::iter, lvl_debug, and value.
Referenced by destination_address(), and gui_gtk_datawindow_add().
Variable Documentation
struct datawindow_methods gui_gtk_datawindow_meth static
Initial value:
= {
        gui_gtk_datawindow_destroy,
        gui_gtk_datawindow_add,
        gui_gtk_datawindow_mode,
}
Referenced by gui_gtk_datawindow_new().
GValue value static
Referenced by gui_gtk_datawindow_add(), and select_row().