navit: data.h File Reference
data.h File Reference
#include "config.h"
Macros
#define L(x) ({ unsigned char *t=(unsigned char *)&(x); t[0] | (t[1] << 8) | (t[2] << 16) | (t[3] << 24); })
Functions
static unsigned char get_u8 (unsigned char **p)
static unsigned short get_u16 (unsigned char **p)
static unsigned short get_u16_unal (unsigned char **p)
static unsigned int get_u24 (unsigned char **p)
static unsigned int get_u24_unal (unsigned char **p)
static unsigned int get_u32 (unsigned char **p)
static unsigned int get_u32_unal (unsigned char **p)
static char * get_string (unsigned char **p)
Macro Definition Documentation
#define L (x) ({ unsigned char *t=(unsigned char *)&(x); t[0] | (t[1] << 8) | (t[2] << 16) | (t[3] << 24); })
Referenced by adler32(), ApplySpecialAttribute(), ApplySpecialAttribute2(), CalcPitches_Tone(), CeEnableBacklight(), ChangePhonemes(), crc32_combine(), CreateGraphicsWindows(), CreateToolBar(), event_win32_main_loop_quit(), fullscreen(), geod_inv(), get_bits(), inflate(), inflatePrime(), inflateSetDictionary(), initDevice(), IsLetter(), LookupCharName(), LookupDict2(), LookupLetter(), main_init(), MatchRule(), org.navitproject.navit.NavitGraphics.NavitView::onKeyDown(), org.navitproject.navit.Navit::onResume(), png2pnm(), png_build_gamma_table(), png_check_cHRM_fixed(), png_do_read_intrapixel(), png_get_asm_flagmask(), png_get_asm_flags(), png_get_compression_buffer_size(), png_get_mmx_flagmask(), png_get_mmx_rowbytes_threshold(), png_handle_cHRM(), png_handle_gAMA(), png_handle_iCCP(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_zTXt(), png_read_start_row(), png_set_rgb_to_gray_fixed(), png_set_sRGB_gAMA_and_cHRM(), png_zalloc(), poly_get(), SelectTranslator(), SetLetterBits(), SetLetterBitsRange(), towlower2(), TranslateChar(), TranslateLetter(), Unpronouncable(), Unpronouncable_en(), vehicle_wince_available_ports(), WndProc(), and zlibCompileFlags().
Function Documentation
static char* get_string (unsigned char ** p) inline static
static unsigned short get_u16 (unsigned char ** p) inline static
References __bswap_16.
Referenced by get_u24().
static unsigned short get_u16_unal (unsigned char ** p) inline static
Referenced by block_offset_get_block(), block_offset_get_offset(), get_u24_unal(), street_name_get(), street_name_number_get(), street_name_numbers_get(), street_type_get_country(), town_get_data(), and town_search_compare().
static unsigned int get_u24 (unsigned char ** p) inline static
References get_u16().
static unsigned int get_u24_unal (unsigned char ** p) inline static
References get_u16_unal().
static unsigned int get_u32 (unsigned char ** p) inline static
References __bswap_32, and int.
Referenced by block_get_blocks(), block_get_count(), block_get_next(), block_get_r(), block_get_size(), block_index_get_blocks(), block_index_get_next(), block_index_get_size(), block_index_item_get_blocknum(), block_index_item_get_blocks(), block_next(), tree_hdr_get_addr(), tree_hdr_get_low(), tree_hdr_get_size(), tree_hdr_h_get_addr(), tree_hdr_h_get_size(), tree_leaf_h_get_higher(), tree_leaf_h_get_lower(), tree_leaf_h_get_match(), tree_leaf_h_get_value(), and tree_search_next().
static unsigned int get_u32_unal (unsigned char ** p) inline static
Referenced by block_setup_tags(), poly_coord_get(), poly_get_data(), street_header_get_count(), street_name_get(), street_name_numbers_get(), street_name_numbers_get_coord(), street_str_get_nameid(), street_str_get_segid(), town_get_data(), town_search_compare(), tree_hdr_v_get_count(), tree_hdr_v_get_next(), tree_hdr_v_get_unknown(), tree_leaf_v_get_value(), tree_search_next(), and tree_search_next_lin().
static unsigned char get_u8 (unsigned char ** p) inline static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
You should have received a copy of the GNU Library General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by street_name_number_get(), street_name_numbers_get(), and town_get_data().