navit: support/shapefile/dbfopen.c File Reference
dbfopen.c File Reference
#include "shapefil.h"
#include <math.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
Macros
#define CPLsprintf sprintf
#define CPLsnprintf snprintf
#define FALSE 0
#define TRUE 1
#define XBASE_FILEHDR_SZ 32
#define HEADER_RECORD_TERMINATOR 0x0D
#define END_OF_FILE_CHARACTER 0x1A
#define CPL_IGNORE_RET_VAL_INT(x) x
Functions
static void * SfRealloc (void *pMem, int nNewSize)
static void DBFWriteHeader (DBFHandle psDBF)
static int DBFFlushRecord (DBFHandle psDBF)
static int DBFLoadRecord (DBFHandle psDBF, int iRecord)
void SHPAPI_CALL DBFUpdateHeader (DBFHandle psDBF)
void SHPAPI_CALL DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
DBFHandle SHPAPI_CALL DBFOpen (const char *pszFilename, const char *pszAccess)
DBFHandle SHPAPI_CALL DBFOpenLL (const char *pszFilename, const char *pszAccess, SAHooks *psHooks)
void SHPAPI_CALL DBFClose (DBFHandle psDBF)
DBFHandle SHPAPI_CALL DBFCreate (const char *pszFilename)
DBFHandle SHPAPI_CALL DBFCreateEx (const char *pszFilename, const char *pszCodePage)
DBFHandle SHPAPI_CALL DBFCreateLL (const char *pszFilename, const char *pszCodePage, SAHooks *psHooks)
int SHPAPI_CALL DBFAddField (DBFHandle psDBF, const char *pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
static char DBFGetNullCharacter (char chType)
int SHPAPI_CALL DBFAddNativeFieldType (DBFHandle psDBF, const char *pszFieldName, char chType, int nWidth, int nDecimals)
static void * DBFReadAttribute (DBFHandle psDBF, int hEntity, int iField, char chReqType)
int SHPAPI_CALL DBFReadIntegerAttribute (DBFHandle psDBF, int iRecord, int iField)
double SHPAPI_CALL DBFReadDoubleAttribute (DBFHandle psDBF, int iRecord, int iField)
const char SHPAPI_CALL1 * DBFReadStringAttribute (DBFHandle psDBF, int iRecord, int iField){return((const char *) DBFReadAttribute(psDBF, iRecord, iField, 'C')
const char SHPAPI_CALL1 * DBFReadLogicalAttribute (DBFHandle psDBF, int iRecord, int iField){return((const char *) DBFReadAttribute(psDBF, iRecord, iField, 'L')
static int DBFIsValueNULL (char chType, const char *pszValue)
int SHPAPI_CALL DBFIsAttributeNULL (DBFHandle psDBF, int iRecord, int iField)
int SHPAPI_CALL DBFGetFieldCount (DBFHandle psDBF)
int SHPAPI_CALL DBFGetRecordCount (DBFHandle psDBF)
DBFFieldType SHPAPI_CALL DBFGetFieldInfo (DBFHandle psDBF, int iField, char *pszFieldName, int *pnWidth, int *pnDecimals)
static int DBFWriteAttribute (DBFHandle psDBF, int hEntity, int iField, void *pValue)
int SHPAPI_CALL DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void *pValue)
int SHPAPI_CALL DBFWriteDoubleAttribute (DBFHandle psDBF, int iRecord, int iField, double dValue)
int SHPAPI_CALL DBFWriteIntegerAttribute (DBFHandle psDBF, int iRecord, int iField, int nValue)
int SHPAPI_CALL DBFWriteStringAttribute (DBFHandle psDBF, int iRecord, int iField, const char *pszValue)
int SHPAPI_CALL DBFWriteNULLAttribute (DBFHandle psDBF, int iRecord, int iField)
int SHPAPI_CALL DBFWriteLogicalAttribute (DBFHandle psDBF, int iRecord, int iField, const char lValue)
int SHPAPI_CALL DBFWriteTuple (DBFHandle psDBF, int hEntity, void *pRawTuple)
const char SHPAPI_CALL1 * DBFReadTuple (DBFHandle psDBF, int hEntity){if(hEntity< 0||hEntity >=psDBF->nRecords) return(NULL
if (!DBFLoadRecord(psDBF, hEntity)) return NULL
return (const char *)
char SHPAPI_CALL DBFGetNativeFieldType (DBFHandle psDBF, int iField)
static void str_to_upper (char *string)
int SHPAPI_CALL DBFGetFieldIndex (DBFHandle psDBF, const char *pszFieldName)
int SHPAPI_CALL DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
int SHPAPI_CALL DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
const char SHPAPI_CALL1 * DBFGetCodePage (DBFHandle psDBF){if(psDBF==NULL) return NULL;return psDBF->pszCodePage;}int SHPAPI_CALLDBFDeleteField(DBFHandle psDBF, int iField
int SHPAPI_CALL DBFReorderFields (DBFHandle psDBF, int *panMap)
int SHPAPI_CALL DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char *pszFieldName, char chType, int nWidth, int nDecimals)
void SHPAPI_CALL DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Macro Definition Documentation
#define CPL_IGNORE_RET_VAL_INT (x) x
Referenced by DBFClose().
#define CPLsnprintf snprintf
Referenced by DBFWriteAttribute().
#define CPLsprintf sprintf
#define END_OF_FILE_CHARACTER 0x1A
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFFlushRecord(), and DBFWriteHeader().
#define FALSE 0
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFCreateLL(), DBFFlushRecord(), DBFIsRecordDeleted(), DBFIsValueNULL(), DBFLoadRecord(), DBFMarkRecordDeleted(), DBFOpenLL(), DBFReorderFields(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), DBFWriteHeader(), and DBFWriteTuple().
#define HEADER_RECORD_TERMINATOR 0x0D
Referenced by DBFWriteHeader().
#define TRUE 1
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFCreateLL(), DBFFlushRecord(), DBFIsAttributeNULL(), DBFIsRecordDeleted(), DBFIsValueNULL(), DBFLoadRecord(), DBFMarkRecordDeleted(), DBFOpenLL(), DBFReorderFields(), DBFWriteAttribute(), and DBFWriteTuple().
#define XBASE_FILEHDR_SZ 32
Referenced by DBFCreateLL(), DBFOpenLL(), DBFUpdateHeader(), and DBFWriteHeader().
Function Documentation
int SHPAPI_CALL DBFAddField (DBFHandle psDBF, const char * pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
References DBFAddNativeFieldType(), FTLogical, and FTString.
int SHPAPI_CALL DBFAddNativeFieldType (DBFHandle psDBF, const char * pszFieldName, char chType, int nWidth, int nDecimals)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
Referenced by DBFAddField().
int SHPAPI_CALL DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char * pszFieldName, char chType, int nWidth, int nDecimals)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFIsValueNULL(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
void SHPAPI_CALL DBFClose (DBFHandle psDBF)
References DBFInfo::bNoHeader, DBFInfo::bUpdated, CPL_IGNORE_RET_VAL_INT, DBFFlushRecord(), DBFUpdateHeader(), DBFWriteHeader(), SAHooks::FClose, DBFInfo::fp, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, DBFInfo::pszWorkField, and DBFInfo::sHooks.
DBFHandle SHPAPI_CALL DBFCreate (const char * pszFilename)
References DBFCreateEx().
DBFHandle SHPAPI_CALL DBFCreateEx (const char * pszFilename, const char * pszCodePage)
References DBFCreateLL(), and SASetupDefaultHooks().
Referenced by DBFCreate().
DBFHandle SHPAPI_CALL DBFCreateLL (const char * pszFilename, const char * pszCodePage, SAHooks * psHooks)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, calloc(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, fp, SAHooks::FWrite, i, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SAHooks::Remove, DBFInfo::sHooks, TRUE, and XBASE_FILEHDR_SZ.
Referenced by DBFCreateEx().
static int DBFFlushRecord (DBFHandle psDBF) static
References DBFInfo::bCurrentRecordModified, DBFInfo::bWriteEndOfFileChar, END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nCurrentRecord, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, DBFInfo::sHooks, and TRUE.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), DBFLoadRecord(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
const char SHPAPI_CALL1* DBFGetCodePage (DBFHandle psDBF)
References NULL.
int SHPAPI_CALL DBFGetFieldCount (DBFHandle psDBF)
References DBFInfo::nFields.
Referenced by DBFGetFieldIndex(), and map_new_shapefile().
int SHPAPI_CALL DBFGetFieldIndex (DBFHandle psDBF, const char * pszFieldName)
References DBFGetFieldCount(), DBFGetFieldInfo(), i, name, NULL, str_to_upper(), and XBASE_FLDNAME_LEN_READ.
DBFFieldType SHPAPI_CALL DBFGetFieldInfo (DBFHandle psDBF, int iField, char * pszFieldName, int * pnWidth, int * pnDecimals)
References FTDouble, FTInteger, FTInvalid, FTLogical, FTString, i, DBFInfo::nFields, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldSize, DBFInfo::pszHeader, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_READ.
Referenced by attr_resolve(), DBFGetFieldIndex(), process_fields(), and shapefile_attr_get().
char SHPAPI_CALL DBFGetNativeFieldType (DBFHandle psDBF, int iField)
References DBFInfo::pachFieldType.
static char DBFGetNullCharacter (char chType) static
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), and DBFWriteAttribute().
int SHPAPI_CALL DBFGetRecordCount (DBFHandle psDBF)
References DBFInfo::nRecords.
int SHPAPI_CALL DBFIsAttributeNULL (DBFHandle psDBF, int iRecord, int iField)
References DBFIsValueNULL(), DBFReadStringAttribute(), NULL, DBFInfo::pachFieldType, and TRUE.
int SHPAPI_CALL DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
References DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
static int DBFIsValueNULL (char chType, const char * pszValue) static
References FALSE, i, NULL, and TRUE.
Referenced by DBFAlterFieldDefn(), and DBFIsAttributeNULL().
static int DBFLoadRecord (DBFHandle psDBF, int iRecord) static
References DBFFlushRecord(), SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, DBFInfo::nCurrentRecord, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::pszCurrentRecord, SEEK_SET, DBFInfo::sHooks, and TRUE.
Referenced by DBFIsRecordDeleted(), DBFMarkRecordDeleted(), DBFReadAttribute(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
int SHPAPI_CALL DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
References DBFInfo::bCurrentRecordModified, DBFInfo::bUpdated, DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFHandle SHPAPI_CALL DBFOpen (const char * pszFilename, const char * pszAccess)
References DBFOpenLL(), and SASetupDefaultHooks().
Referenced by map_new_shapefile().
DBFHandle SHPAPI_CALL DBFOpenLL (const char * pszFilename, const char * pszAccess, SAHooks * psHooks)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, calloc(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, i, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFOpen().
static void* DBFReadAttribute (DBFHandle psDBF, int hEntity, int iField, char chReqType) static
References SAHooks::Atof, DBFLoadRecord(), DBFInfo::dfDoubleField, DBFInfo::fieldValue, DBFInfo::nFields, DBFInfo::nIntField, DBFInfo::nRecords, NULL, DBFInfo::nWorkFieldLength, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszWorkField, and DBFInfo::sHooks.
Referenced by DBFReadDoubleAttribute(), and DBFReadIntegerAttribute().
double SHPAPI_CALL DBFReadDoubleAttribute (DBFHandle psDBF, int iRecord, int iField)
References DBFReadAttribute(), and NULL.
Referenced by process_fields(), and shapefile_attr_get().
int SHPAPI_CALL DBFReadIntegerAttribute (DBFHandle psDBF, int iRecord, int iField)
References DBFReadAttribute(), and NULL.
Referenced by process_fields(), and shapefile_attr_get().
const char SHPAPI_CALL1* DBFReadLogicalAttribute (DBFHandle psDBF, int iRecord, int iField) const
const char SHPAPI_CALL1* DBFReadStringAttribute (DBFHandle psDBF, int iRecord, int iField) const
Referenced by attr_resolve(), DBFIsAttributeNULL(), process_fields(), and shapefile_attr_get().
const char SHPAPI_CALL1* DBFReadTuple (DBFHandle psDBF, int hEntity) -> nRecords) return(NULL
int SHPAPI_CALL DBFReorderFields (DBFHandle psDBF, int * panMap)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, calloc(), DBFFlushRecord(), DBFUpdateHeader(), FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszHeader, DBFInfo::sHooks, TRUE, and XBASE_FLDHDR_SZ.
void SHPAPI_CALL DBFSetLastModifiedDate (DBFHandle psDBF, int nYYSince1900, int nMM, int nDD)
References DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, and DBFInfo::nUpdateYearSince1900.
Referenced by DBFCreateLL(), and DBFOpenLL().
void SHPAPI_CALL DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
References DBFInfo::bWriteEndOfFileChar.
Referenced by DBFCreateLL(), and DBFOpenLL().
void SHPAPI_CALL DBFUpdateHeader (DBFHandle psDBF)
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFWriteHeader(), SAHooks::FFlush, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::sHooks, and XBASE_FILEHDR_SZ.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), and DBFReorderFields().
static int DBFWriteAttribute (DBFHandle psDBF, int hEntity, int iField, void * pValue) static
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, CPLsnprintf, DBFFlushRecord(), DBFGetNullCharacter(), DBFLoadRecord(), DBFWriteHeader(), FALSE, i, int, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, TRUE, and XBASE_FLD_MAX_WIDTH.
Referenced by DBFWriteDoubleAttribute(), DBFWriteIntegerAttribute(), DBFWriteLogicalAttribute(), DBFWriteNULLAttribute(), and DBFWriteStringAttribute().
int SHPAPI_CALL DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void * pValue)
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, i, int, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, and DBFInfo::pszCurrentRecord.
int SHPAPI_CALL DBFWriteDoubleAttribute (DBFHandle psDBF, int iRecord, int iField, double dValue)
References DBFWriteAttribute().
static void DBFWriteHeader (DBFHandle psDBF) static
References DBFInfo::bNoHeader, DBFInfo::bWriteEndOfFileChar, END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FSeek, SAHooks::FWrite, HEADER_RECORD_TERMINATOR, DBFInfo::iLanguageDriver, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::pszHeader, DBFInfo::sHooks, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFClose(), DBFUpdateHeader(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), and DBFWriteTuple().
int SHPAPI_CALL DBFWriteIntegerAttribute (DBFHandle psDBF, int iRecord, int iField, int nValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteLogicalAttribute (DBFHandle psDBF, int iRecord, int iField, const char lValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteNULLAttribute (DBFHandle psDBF, int iRecord, int iField)
References DBFWriteAttribute(), and NULL.
int SHPAPI_CALL DBFWriteStringAttribute (DBFHandle psDBF, int iRecord, int iField, const char * pszValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteTuple (DBFHandle psDBF, int hEntity, void * pRawTuple)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, i, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
if (! DBFLoadRecordpsDBF, hEntity)
return (const char *)
Referenced by navigation_itm_ways_update(), png_get_cHRM(), png_get_gAMA(), png_get_oFFs(), and png_get_sRGB().
static void* SfRealloc (void * pMem, int nNewSize) static
References NULL.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), and DBFOpenLL().
static void str_to_upper (char * string) static
References i, and int.
Referenced by DBFGetFieldIndex().