navit: destination.h File Reference
destination.h File Reference
Functions
int destination_address (struct navit *nav)
Function Documentation
int destination_address (struct navit * nav)
References _, button_bookmark(), button_destination(), button_map(), changed(), COL_COUNT, country_default(), country_search_destroy(), country_search_get_item(), country_search_new(), dbg, search_param::entry_city, search_param::entry_country, search_param::entry_district, search_param::entry_number, search_param::entry_postal, search_param::entry_street, FALSE, i, item, item_attr_get(), search_param::listbox, search_param::liststore, search_param::liststore2, lvl_error, search_param::ms, search_param::nav, navit_get_mapset(), navit_get_tracking(), NULL, search_param::partial, row_activated(), search_list_new(), search_param, select_row(), search_param::sl, spawn_xkbd(), attr::str, tracking_get_attr(), tree_view_button_release(), search_param::treeview, TRUE, types, and attr::u.
Referenced by destination_action().