navit: gui/gtk/destination.c File Reference
destination.c File Reference
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include "debug.h"
#include "destination.h"
#include "navit.h"
#include "item.h"
#include "coord.h"
#include "track.h"
#include "country.h"
#include "search.h"
#include "projection.h"
#include "navit_nls.h"
#include "bookmarks.h"
Data Structures
struct search_param
Macros
#define COL_COUNT 8
#define MAX_ARGS 8
Functions
static void button_map (GtkWidget *widget, struct search_param *search)
static char * description (struct search_param *search, GtkTreeIter *iter)
static void button_destination (GtkWidget *widget, struct search_param *search)
static void button_bookmark (GtkWidget *widget, struct search_param *search)
static void set_columns (struct search_param *param, int mode)
static void row_activated (GtkWidget *widget, GtkTreePath *p1, GtkTreeViewColumn *c, struct search_param *search)
static void tree_view_button_release (GtkWidget *widget, GdkEventButton *event, struct search_param *search)
static void next_focus (struct search_param *search, GtkWidget *widget)
static void changed (GtkWidget *widget, struct search_param *search)
static void parse_xkbd_args (const char *cmd, char **argv)
static int spawn_xkbd (char *xkbd_path, char *xkbd_str)
int destination_address (struct navit *nav)
Variables
static struct search_param search_param
char ** columns_text []
int kbd_pid
Macro Definition Documentation
#define COL_COUNT 8
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by button_bookmark(), button_destination(), button_map(), changed(), and destination_address().
#define MAX_ARGS 8
Referenced by parse_xkbd_args(), and spawn_xkbd().
Function Documentation
static void button_bookmark (GtkWidget * widget, struct search_param * search) static
References attr::bookmarks, bookmarks_add_bookmark(), c, COL_COUNT, description(), g_free(), eval::iter, search_param::liststore2, search_param::nav, navit_get_attr(), NULL, and attr::u.
Referenced by destination_address().
static void button_destination (GtkWidget * widget, struct search_param * search) static
References c, COL_COUNT, description(), g_free(), eval::iter, search_param::liststore2, search_param::nav, navit_set_destination(), and NULL.
Referenced by destination_address().
static void button_map (GtkWidget * widget, struct search_param * search) static
References c, COL_COUNT, eval::iter, search_param::liststore2, search_param::nav, navit_set_center(), NULL, and search_param::treeview.
Referenced by destination_address().
static void changed (GtkWidget * widget, struct search_param * search) static
References search_param::attr, search_list_result::c, search_list_country::car, COL_COUNT, search_list_town::common, search_list_result::country, dbg, search_list_common::district_name, search_param::entry_city, search_param::entry_country, search_param::entry_number, search_param::entry_postal, search_param::entry_street, FALSE, search_list_country::iso2, search_list_country::iso3, eval::iter, search_param::liststore, search_param::liststore2, lvl_debug, search_list_country::name, search_list_street::name, next_focus(), search_param::partial, search_list_common::postal, printf(), search_list_get_result(), search_list_search(), set_columns(), search_param::sl, attr::str, search_list_result::street, search_list_result::town, search_list_common::town_name, TRUE, attr::type, and attr::u.
Referenced by destination_address(), gui_internal_resize(), map_rect_new_shapefile(), and overlay_resize().
static char* description (struct search_param * search, GtkTreeIter * iter) static
References search_param::attr, g_strdup_printf(), search_param::liststore2, and attr::type.
Referenced by button_bookmark(), button_destination(), gui_internal_cmd_map_download(), main(), navigation_get_map(), navit_cmd_set_destination(), navit_set_destination_py(), navit_vehicle_update_position(), request_navit_set_destination(), route_get_map_helper(), and tracking_get_map().
int destination_address (struct navit * nav)
References _, button_bookmark(), button_destination(), button_map(), changed(), COL_COUNT, country_default(), country_search_destroy(), country_search_get_item(), country_search_new(), dbg, search_param::entry_city, search_param::entry_country, search_param::entry_district, search_param::entry_number, search_param::entry_postal, search_param::entry_street, FALSE, i, item, item_attr_get(), search_param::listbox, search_param::liststore, search_param::liststore2, lvl_error, search_param::ms, search_param::nav, navit_get_mapset(), navit_get_tracking(), NULL, search_param::partial, row_activated(), search_list_new(), search_param, select_row(), search_param::sl, spawn_xkbd(), attr::str, tracking_get_attr(), tree_view_button_release(), search_param::treeview, TRUE, types, and attr::u.
Referenced by destination_action().
static void next_focus (struct search_param * search, GtkWidget * widget) static
References search_param::entry_city, search_param::entry_country, search_param::entry_number, and search_param::entry_street.
Referenced by changed().
static void parse_xkbd_args (const char * cmd, char ** argv) static
References buf, MAX_ARGS, NULL, and p.
Referenced by spawn_xkbd().
static void row_activated (GtkWidget * widget, GtkTreePath * p1, GtkTreeViewColumn * c, struct search_param * search) static
References search_param::attr, dbg, search_param::entry_city, search_param::entry_country, search_param::entry_street, eval::iter, search_param::liststore2, lvl_debug, search_param::partial, attr::str, search_param::treeview, and attr::type.
Referenced by destination_address().
static void set_columns (struct search_param * param, int mode) static
References columns_text, _GList::data, g_list_free(), g_list_next, i, navit_nls_gettext(), NULL, and search_param::treeview.
Referenced by changed().
static int spawn_xkbd (char * xkbd_path, char * xkbd_str) static
References buf, c, close(), dup2(), kbd_pid, MAX_ARGS, NULL, parse_xkbd_args(), perror(), and read().
Referenced by destination_address().
static void tree_view_button_release (GtkWidget * widget, GdkEventButton * event, struct search_param * search) static
References search_param::treeview.
Referenced by destination_address().
Variable Documentation
char** columns_text[]
Initial value:
= {
        (char *[]){_n("Car"),_n("Iso2"),_n("Iso3"),_n("Country"),NULL},
        (char *[]){_n("Car"),_n("Postal"),_n("Town"),_n("District"),NULL},
        (char *[]){_n("Car"),_n("Postal"),_n("Town"),_n("District"),_n("Street"),NULL},
        (char *[]){_n("Car"),_n("Postal"),_n("Town"),_n("District"),_n("Street"),_n("Number"),NULL},
}
Referenced by set_columns().
int kbd_pid
Referenced by spawn_xkbd().
struct search_param search_param static
Referenced by destination_address().