navit: support/espeak/dictionary.c File Reference
dictionary.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>
#include <wchar.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "translate.h"
Macros
#define LOG_TRANSLATE
Functions
char * print_dictionary_flags (unsigned int *flags)
void strncpy0 (char *to, const char *from, int size)
static int reverse_word_bytes (int word)
int LookupMnem (MNEM_TAB *table, char *string)
static void InitGroups (Translator *tr)
int LoadDictionary (Translator *tr, const char *name, int no_error)
int HashDictionary (const char *string)
char * EncodePhonemes (char *p, char *outptr, unsigned char *bad_phoneme)
void DecodePhonemes (const char *inptr, char *outptr)
static void WriteMnemonic (char *phon_out, int *ix, int mnem)
void GetTranslatedPhonemeString (char *phon_out, int n_phon_out)
static int IsLetterGroup (Translator *tr, char *word, int group, int pre)
static int IsLetter (Translator *tr, int letter, int group)
static int IsVowel (Translator *tr, int letter)
static int Unpronouncable_en (Translator *tr, char *word)
int Unpronouncable (Translator *tr, char *word)
static int GetVowelStress (Translator *tr, unsigned char *phonemes, unsigned char *vowel_stress, int *vowel_count, int *stressed_syllable, int control)
void ChangeWordStress (Translator *tr, char *word, int new_stress)
void SetWordStress (Translator *tr, char *output, unsigned int *dictionary_flags, int tonic, int prev_stress)
static char * DecodeRule (const char *group, char *rule)
void AppendPhonemes (Translator *tr, char *string, int size, const char *ph)
static void MatchRule (Translator *tr, char *word[], const char *group, char *rule, MatchRecord *match_out, int word_flags, int dict_flags)
int TranslateRules (Translator *tr, char *p_start, char *phonemes, int ph_size, char *end_phonemes, int word_flags, unsigned int *dict_flags)
void ApplySpecialAttribute2 (Translator *tr, char *phonemes, int dict_flags)
void ApplySpecialAttribute (Translator *tr, char *phonemes, int dict_flags)
int TransposeAlphabet (char *text, int offset, int min, int max)
static const char * LookupDict2 (Translator *tr, const char *word, const char *word2, char *phonetic, unsigned int *flags, int end_flags, WORD_TAB *wtab)
int LookupDictList (Translator *tr, char **wordptr, char *ph_out, unsigned int *flags, int end_flags, WORD_TAB *wtab)
int Lookup (Translator *tr, const char *word, char *ph_out)
int RemoveEnding (Translator *tr, char *word, int end_type, char *word_copy)
Variables
int dictionary_skipwords
char dictionary_name [40]
static const unsigned short diereses_list [7] = {0xe4,0xeb,0xef,0xf6,0xfc,0xff,0}
static unsigned char remove_accent []
static char stress_phonemes []
static const short pairs_ru []
Macro Definition Documentation
#define LOG_TRANSLATE
Function Documentation
void AppendPhonemes (Translator * tr, char * string, int size, const char * ph)
References c, length, n_phoneme_tab, NULL, p, phoneme_tab, phSTRESS, phUNSTRESSED, phVOWEL, type, Translator::word_stressed_count, and Translator::word_vowel_count.
Referenced by TranslateRules(), and TranslateWord().
void ApplySpecialAttribute (Translator * tr, char * phonemes, int dict_flags)
References FLAG_ALT2_TRANS, FLAG_ALT_TRANS, L, PhonemeCode(), PhonemeCode2, phonSCHWA, phonSTRESS_P, phonSTRESS_PREV, and Translator::translator_name.
Referenced by TranslateRules(), and TranslateWord().
void ApplySpecialAttribute2 (Translator * tr, char * phonemes, int dict_flags)
References FLAG_ALT2_TRANS, L, p, PhonemeCode(), phonSTRESS_P, and Translator::translator_name.
Referenced by TranslateWord().
void ChangeWordStress (Translator * tr, char * word, int new_stress)
References GetVowelStress(), N_WORD_PHONEMES, p, phNONSYLLABIC, phoneme_tab, phVOWEL, stress_phonemes, and type.
Referenced by TranslateWord().
void DecodePhonemes (const char * inptr, char * outptr)
References c, PHONEME_TAB::mnemonic, NULL, phoneme_tab, phonSWITCH, phSTRESS, PHONEME_TAB::spect, PHONEME_TAB::std_length, and PHONEME_TAB::type.
Referenced by compile_line(), LookupCharName(), LookupDict2(), LookupSpecial(), MatchRule(), and TranslateWord().
static char* DecodeRule (const char * group, char * rule) static
References buf, c, linenum, p, RULE_CONDITION, RULE_ENDING, RULE_LAST_RULE, RULE_LETTERGP, RULE_LETTERGP2, RULE_LINENUM, RULE_PH_COMMON, RULE_PHONEMES, RULE_POST, RULE_PRE, RULE_SPACE, sprintf(), SUFX_P, and value.
Referenced by MatchRule().
char* EncodePhonemes (char * p, char * outptr, unsigned char * bad_phoneme)
References c, PHONEME_TAB::code, max, PHONEME_TAB::mnemonic, n_phoneme_tab, NULL, p, phINVALID, phoneme_tab, phonSWITCH, and type.
Referenced by compile_line(), compile_rule(), and TranslateWord2().
void GetTranslatedPhonemeString (char * phon_out, int n_phon_out)
References PHONEME_TAB::code, PHONEME_TAB::mnemonic, n_phoneme_list, PHONEME_TAB_LIST::name, PHONEME_LIST::newword, NULL, p, PHONEME_LIST::ph, phoneme_list, phoneme_tab, phoneme_tab_list, phonLENGTHEN, phonSWITCH, phonSYLLABIC, phVOWEL, SFLAG_LENGTHEN, SFLAG_SYLLABLE, PHONEME_LIST::stresslevel, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, PHONEME_LIST::type, and WriteMnemonic().
Referenced by SpeakNextClause().
static int GetVowelStress (Translator * tr, unsigned char * phonemes, unsigned char * vowel_stress, int * vowel_count, int * stressed_syllable, int control) static
References Translator::langopts, N_WORD_PHONEMES, NULL, PHONEME_TAB::phflags, phNONSYLLABIC, phoneme_tab, phonSTRESS_PREV, phonSYLLABIC, phSTRESS, phUNSTRESSED, phVOWEL, PHONEME_TAB::spect, PHONEME_TAB::std_length, LANGUAGE_OPTIONS::stress_flags, and PHONEME_TAB::type.
Referenced by ChangeWordStress(), and SetWordStress().
int HashDictionary (const char * string)
References c.
Referenced by compile_line(), and LookupDict2().
static void InitGroups (Translator * tr) static
References c, c2, Translator::data_dictrules, dictionary_name, fprintf(), Translator::groups1, Translator::groups2, Translator::groups2_count, Translator::groups2_name, Translator::groups2_start, Translator::langopts, Translator::letterGroups, Translator::n_groups2, N_LETTER_GROUPS, NULL, p, LANGUAGE_OPTIONS::replace_chars, reverse_word_bytes(), RULE_GROUP_END, RULE_GROUP_START, RULE_LETTERGP2, and RULE_REPLACEMENTS.
Referenced by LoadDictionary().
static int IsLetter (Translator * tr, int letter, int group) static
References L, Translator::letter_bits, Translator::letter_bits_offset, Translator::letter_groups, NULL, and remove_accent.
Referenced by IsVowel(), MatchRule(), and RemoveEnding().
static int IsLetterGroup (Translator * tr, char * word, int group, int pre) static
References Translator::letterGroups, NULL, p, and RULE_GROUP_END.
Referenced by MatchRule().
static int IsVowel (Translator * tr, int letter) static
References IsLetter().
Referenced by Unpronouncable(), and Unpronouncable_en().
int LoadDictionary (Translator * tr, const char * name, int no_error)
References Alloc(), Translator::data_dictlist, Translator::data_dictrules, Translator::dict_hashtab, dictionary_name, fprintf(), Free(), GetFileLength(), Translator::groups1, InitGroups(), length, N_HASH_DICT, NULL, p, path_home, PATHSEP, reverse_word_bytes(), size, and sprintf().
Referenced by CompileDictionary(), LoadVoice(), and SetTranslator2().
int Lookup (Translator * tr, const char * word, char * ph_out)
References LookupDictList(), and NULL.
Referenced by LookupAccentedLetter(), LookupLetter(), LookupLetter2(), LookupNum2(), LookupNum3(), LookupThousands(), TranslateLetter(), TranslateNumber_1(), TranslateRoman(), TranslateRules(), and TranslateWord().
static const char* LookupDict2 (Translator * tr, const char * word, const char * word2, char * phonetic, unsigned int * flags, int end_flags, WORD_TAB * wtab) static
References Translator::clause_end, DecodePhonemes(), Translator::dict_condition, Translator::dict_hashtab, dictionary_skipwords, Translator::expect_noun, Translator::expect_past, Translator::expect_verb, Translator::expect_verb_s, f_trans, FLAG_ALL_UPPER, FLAG_ALLCAPS, FLAG_ATEND, FLAG_CAPITAL, FLAG_EMPHASIZED2, FLAG_FIRST_UPPER, FLAG_FOUND, FLAG_FOUND_ATTRIBUTES, FLAG_HYPHEN_AFTER, FLAG_HYPHENATED, FLAG_NOUN, FLAG_ONLY, FLAG_ONLY_S, FLAG_PAST, FLAG_SKIPWORDS, FLAG_STEM, FLAG_STRESS_END, FLAG_SUFX, FLAG_SUFX_S, FLAG_TEXTMODE, FLAG_VERB, WORD_TAB::flags, fprintf(), HashDictionary(), L, Translator::langopts, N_WORD_BYTES, N_WORD_PHONEMES, next, NULL, option_phonemes, p, print_dictionary_flags(), SUFX_P, LANGUAGE_OPTIONS::textmode, translator, Translator::transpose_max, Translator::transpose_min, Translator::transpose_offset, and TransposeAlphabet().
Referenced by LookupDictList().
int LookupDictList (Translator * tr, char ** wordptr, char * ph_out, unsigned int * flags, int end_flags, WORD_TAB * wtab)
References c, dictionary_skipwords, f_trans, FLAG_ACCENT, FLAG_ALLOW_TEXTMODE, FLAG_MAX3, FLAG_SKIPWORDS, FLAG_SUFX_E_ADDED, FLAG_TEXTMODE, fprintf(), Translator::langopts, length, LookupAccentedLetter(), LookupDict2(), N_WORD_BYTES, option_phonemes, Translator::phonemes_repeat, Translator::phonemes_repeat_count, sprintf(), strncpy0(), SUFX_D, LANGUAGE_OPTIONS::textmode, utf8_in(), and utf8_nbytes().
Referenced by Lookup(), LookupCharName(), LookupSpecial(), and TranslateWord().
int LookupMnem (MNEM_TAB * table, char * string)
References MNEM_TAB::mnem, NULL, and MNEM_TAB::value.
Referenced by compile_line(), LoadVoice(), ProcessSsmlTag(), ReadClause(), and ReadVoiceFile().
static void MatchRule (Translator * tr, char * word[], const char * group, char * rule, MatchRecord * match_out, int word_flags, int dict_flags) static
References DecodePhonemes(), DecodeRule(), MatchRecord::del_fwd, Translator::dict_condition, MatchRecord::end_type, Translator::expect_verb, f_trans, FLAG_ALT_TRANS, FLAG_FIRST_UPPER, FLAG_HYPHEN, FLAG_HYPHEN_AFTER, FLAG_NO_TRACE, FLAG_SUFFIX_REMOVED, fprintf(), IsDigit(), IsLetter(), IsLetterGroup(), L, Translator::langopts, LETTERGP_VOWEL2, match(), NULL, option_phonemes, p, MatchRecord::phonemes, MatchRecord::points, REPLACED_E, RULE_ALT1, RULE_CAPITAL, RULE_CONDITION, RULE_DEL_FWD, RULE_DIGIT, RULE_DOUBLE, RULE_ENDING, RULE_GROUP_END, RULE_IFVERB, RULE_INC_SCORE, RULE_LETTERGP, RULE_LETTERGP2, RULE_LINENUM, RULE_NO_SUFFIX, RULE_NONALPHA, RULE_NOTVOWEL, RULE_NOVOWELS, RULE_PH_COMMON, RULE_PHONEMES, RULE_POST, RULE_PRE, RULE_SPACE, RULE_STRESSED, RULE_SYLLABLE, LANGUAGE_OPTIONS::tone_numbers, utf8_in(), utf8_in2(), and Translator::word_stressed_count.
Referenced by TranslateRules().
char* print_dictionary_flags (unsigned int * flags)
References buf, LookupMnem2(), and sprintf().
Referenced by LookupDict2().
int RemoveEnding (Translator * tr, char * word, int end_type, char * word_copy)
References Translator::expect_verb, f_trans, FLAG_SUFX, FLAG_SUFX_E_ADDED, FLAG_SUFX_S, fprintf(), i, IsLetter(), LETTERGP_VOWEL2, NULL, option_phonemes, p, REPLACED_E, SUFX_E, SUFX_I, and SUFX_V.
Referenced by TranslateWord().
static int reverse_word_bytes (int word) static
Referenced by InitGroups(), and LoadDictionary().
void SetWordStress (Translator * tr, char * output, unsigned int * dictionary_flags, int tonic, int prev_stress)
References FLAG_STRESS_END2, GetVowelStress(), Translator::langopts, LOPT_IT_LENGTHEN, PHONEME_TAB::mnemonic, n_phoneme_tab, N_WORD_PHONEMES, NULL, p, LANGUAGE_OPTIONS::param, pause_phonemes, PHONEME_TAB::phflags, phLONG, phNONSYLLABIC, phoneme_tab, phonLENGTHEN, phonPAUSE_NOLINK, phonPAUSE_VSHORT, phonSCHWA, phonSYLLABIC, phPAUSE, phSTOP, phSTRESS, phVOWEL, Translator::prev_last_stress, LANGUAGE_OPTIONS::stress_flags, stress_phonemes, LANGUAGE_OPTIONS::stress_rule, PHONEME_TAB::type, type, LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by LookupCharName(), LookupSpecial(), and TranslateWord().
void strncpy0 (char * to, const char * from, int size)
Referenced by compile_line(), ExtractVoiceVariantName(), LoadVoice(), LoadVoiceVariant(), LookupDictList(), main(), ReadVoiceFile(), SelectVoice(), SetVoiceByName(), sync_espeak_Synth_Mark(), and TranslateWord().
int TranslateRules (Translator * tr, char * p_start, char * phonemes, int ph_size, char * end_phonemes, int word_flags, unsigned int * dict_flags)
References AppendPhonemes(), ApplySpecialAttribute(), LANGUAGE_OPTIONS::ascii_language, buf, c, c2, Translator::data_dictrules, MatchRecord::del_fwd, diereses_list, MatchRecord::end_type, f_trans, FLAG_DONT_SWITCH_TRANSLATOR, FLAG_NO_PREFIX, FLAG_NO_TRACE, FLAG_SPELLWORD, fprintf(), group_name, Translator::groups1, Translator::groups2, Translator::groups2_count, Translator::groups2_name, Translator::groups2_start, LANGUAGE_OPTIONS::ideographs, IsAlpha(), IsBracket(), IsDigit(), Translator::langopts, Translator::letter_bits_offset, Lookup(), LookupLetter(), lookupwchar(), LOPT_DIERESES, MatchRule(), N_WORD_BYTES, NULL, option_phonemes, option_sayas, p, LANGUAGE_OPTIONS::param, MatchRecord::phonemes, Translator::phonemes_repeat_count, phonPAUSE_NOLINK, phonSWITCH, MatchRecord::points, pre_pause, remove_accent, REPLACED_E, sprintf(), SUFX_P, LANGUAGE_OPTIONS::tone_numbers, utf8_in(), Translator::word_stressed_count, and Translator::word_vowel_count.
Referenced by LookupCharName(), LookupLetter(), LookupLetter2(), and TranslateWord().
int TransposeAlphabet (char * text, int offset, int min, int max)
References c, c2, offset, p, pairs_ru, utf8_in(), and utf8_out().
Referenced by compile_line(), and LookupDict2().
int Unpronouncable (Translator * tr, char * word)
References c, c1, IsVowel(), L, Translator::langopts, Translator::letter_bits_offset, LOPT_UNPRONOUNCABLE, LANGUAGE_OPTIONS::max_initial_consonants, LANGUAGE_OPTIONS::param, Translator::translator_name, Unpronouncable_en(), and utf8_in().
Referenced by TranslateWord().
static int Unpronouncable_en (Translator * tr, char * word) static
References c, IsAlpha(), IsVowel(), L, NULL, and utf8_in().
Referenced by Unpronouncable().
static void WriteMnemonic (char * phon_out, int * ix, int mnem) static
References c, and option_phoneme_variants.
Referenced by GetTranslatedPhonemeString().
Variable Documentation
char dictionary_name[40]
Referenced by espeak_CompileDictionary(), InitGroups(), LoadDictionary(), LoadVoice(), main(), and NewTranslator().
int dictionary_skipwords
Referenced by LookupDict2(), LookupDictList(), TranslateClause(), TranslateNumber_1(), TranslateWord(), and TranslateWord2().
const unsigned short diereses_list[7] = {0xe4,0xeb,0xef,0xf6,0xfc,0xff,0} static
Referenced by TranslateRules().
const short pairs_ru[] static
Referenced by TransposeAlphabet().
unsigned char remove_accent[] static
Initial value:
= {
'a','a','a','a','a','a','a','c','e','e','e','e','i','i','i','i',
'd','n','o','o','o','o','o', 0, 'o','u','u','u','u','y','t','s',
'a','a','a','a','a','a','a','c','e','e','e','e','i','i','i','i',
'd','n','o','o','o','o','o', 0 ,'o','u','u','u','u','y','t','y',
'a','a','a','a','a','a','c','c','c','c','c','c','c','c','d','d',
'd','d','e','e','e','e','e','e','e','e','e','e','g','g','g','g',
'g','g','g','g','h','h','h','h','i','i','i','i','i','i','i','i',
'i','i','i','i','j','j','k','k','k','l','l','l','l','l','l','l',
'l','l','l','n','n','n','n','n','n','n','n','n','o','o','o','o',
'o','o','o','o','r','r','r','r','r','r','s','s','s','s','s','s',
's','s','t','t','t','t','t','t','u','u','u','u','u','u','u','u',
'u','u','u','u','w','w','y','y','y','z','z','z','z','z','z','s',
'b','b','b','b', 0,  0, 'o','c','c','d','d','d','d','d','e','e',
'e','f','f','g','g','h','i','i','k','k','l','l','m','n','n','o',
'o','o','o','o','p','p','y', 0,  0, 's','s','t','t','t','t','u',
'u','u','v','y','y','z','z','z','z','z','z','z', 0,  0,  0, 'w',
't','t','t','k','d','d','d','l','l','l','n','n','n','a','a','i',
'i','o','o','u','u','u','u','u','u','u','u','u','u','e','a','a',
'a','a','a','a','g','g','g','g','k','k','o','o','o','o','z','z',
'j','d','d','d','g','g','w','w','n','n','a','a','a','a','o','o',
'a','a','a','a','e','e','e','e','i','i','i','i','o','o','o','o',
'r','r','r','r','u','u','u','u','s','s','t','t','y','y','h','h',
'n','d','o','o','z','z','a','a','e','e','o','o','o','o','o','o',
'o','o','y','y','l','n','t','j','d','q','a','c','c','l','t','s',
'z', 0 }
Referenced by IsLetter(), and TranslateRules().
char stress_phonemes[] static
Initial value:
= {phonSTRESS_U, phonSTRESS_D, phonSTRESS_2, phonSTRESS_3,
                phonSTRESS_P, phonSTRESS_P2, phonSTRESS_TONIC}
Referenced by ChangeWordStress(), and SetWordStress().