navit: tools/gpx2navit_txt/src/elementControl.c File Reference
elementControl.c File Reference
#include "gpx2navit_txt.h"
Functions
void startElementControl (parsedata *pdata, const char *element, const char **attr)
void endElementControl (parsedata *pdata, const char *element)
Function Documentation
void endElementControl (parsedata * pdata, const char * element)
This method is kicked by tag end event. It corrects char elements when the element tag has some data, then start to convert when tag is top level tag like <wpt>.
References g2sattr::ageofdgpsdata, parsedata::attr, g2sattr::author, parsedata::bufptr, g2sattr::cmt, g2sattr::copyright, parsedata::databuf, DEBUG, g2sattr::desc, g2sattr::ele, g2sattr::fix, fprintf(), g2sattr::geoidheight, g2sattr::hdop, g2sprop::isFast, g2sprop::isPoint, g2sattr::keywords, g2sattr::license, g2sattr::link, g2sattr::magvar, g2sattr::name, NULL, g2sattr::number, g2sprop::parseRte, g2sprop::parseTrk, g2sprop::parseWpt, parsedata::pattr, g2sattr::pdop, parsedata::prop, g2sattr::sat, setMetadata(), setPath(), setPathData(), setPathInterval(), setWpt(), g2sattr::src, g2sattr::sym, g2sattr::time, g2sattr::type, g2sattr::vdop, wipeAttr(), and g2sattr::year.
Referenced by endElement().
void startElementControl (parsedata * pdata, const char * element, const char ** attr)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References parsedata::attr, g2sattr::author, i, initPathAttr(), g2sattr::lat, g2sattr::lon, g2sattr::maxlat, g2sattr::maxlon, g2sattr::minlat, g2sattr::minlon, g2sprop::parseRte, g2sprop::parseTrk, parsedata::pattr, and parsedata::prop.
Referenced by startElement().