navit: support/libc/errno.h File Reference
errno.h File Reference
Macros
#define EPERM 1 /* Operation not permitted */
#define ENOFILE 2 /* No such file or directory */
#define ENOENT 2
#define ESRCH 3 /* No such process */
#define EINTR 4 /* Interrupted function call */
#define EIO 5 /* Input/output error */
#define ENXIO 6 /* No such device or address */
#define E2BIG 7 /* Arg list too long */
#define ENOEXEC 8 /* Exec format error */
#define EBADF 9 /* Bad file descriptor */
#define ECHILD 10 /* No child processes */
#define EAGAIN 11 /* Resource temporarily unavailable */
#define ENOMEM 12 /* Not enough space */
#define EACCES 13 /* Permission denied */
#define EFAULT 14 /* Bad address */
#define EBUSY 16 /* strerror reports "Resource device" */
#define EEXIST 17 /* File exists */
#define EXDEV 18 /* Improper link (cross-device link?) */
#define ENODEV 19 /* No such device */
#define ENOTDIR 20 /* Not a directory */
#define EISDIR 21 /* Is a directory */
#define EINVAL 22 /* Invalid argument */
#define ENFILE 23 /* Too many open files in system */
#define EMFILE 24 /* Too many open files */
#define ENOTTY 25 /* Inappropriate I/O control operation */
#define EFBIG 27 /* File too large */
#define ENOSPC 28 /* No space left on device */
#define ESPIPE 29 /* Invalid seek (seek on a pipe?) */
#define EROFS 30 /* Read-only file system */
#define EMLINK 31 /* Too many links */
#define EPIPE 32 /* Broken pipe */
#define EDOM 33 /* Domain error (math functions) */
#define ERANGE 34 /* Result too large (possibly too small) */
#define EDEADLOCK 36 /* Resource deadlock avoided (non-Cyg) */
#define EDEADLK 36
#define ENAMETOOLONG 38 /* Filename too long (91 in Cyg?) */
#define ENOLCK 39 /* No locks available (46 in Cyg?) */
#define ENOSYS 40 /* Function not implemented (88 in Cyg?) */
#define ENOTEMPTY 41 /* Directory not empty (90 in Cyg?) */
#define EILSEQ 42 /* Illegal byte sequence */
Functions
int * _errno (void)
char * strerror (int num)
Variables
int errno
Macro Definition Documentation
#define E2BIG 7 /* Arg list too long */
Referenced by _nl_find_msg().
#define EACCES 13 /* Permission denied */
#define EAGAIN 11 /* Resource temporarily unavailable */
#define EBADF 9 /* Bad file descriptor */
#define EBUSY 16 /* strerror reports "Resource device" */
#define ECHILD 10 /* No child processes */
#define EDEADLK 36
#define EDEADLOCK 36 /* Resource deadlock avoided (non-Cyg) */
#define EDOM 33 /* Domain error (math functions) */
#define EEXIST 17 /* File exists */
#define EFAULT 14 /* Bad address */
#define EFBIG 27 /* File too large */
#define EILSEQ 42 /* Illegal byte sequence */
#define EINTR 4 /* Interrupted function call */
Referenced by _nl_load_domain().
#define EINVAL 22 /* Invalid argument */
Referenced by g_parse_long_long(), and VASNPRINTF().
#define EIO 5 /* Input/output error */
#define EISDIR 21 /* Is a directory */
#define EMFILE 24 /* Too many open files */
#define EMLINK 31 /* Too many links */
#define ENAMETOOLONG 38 /* Filename too long (91 in Cyg?) */
#define ENFILE 23 /* Too many open files in system */
#define ENODEV 19 /* No such device */
#define ENOENT 2
Referenced by map_rect_new_textfile().
#define ENOEXEC 8 /* Exec format error */
#define ENOFILE 2 /* No such file or directory */
#define ENOLCK 39 /* No locks available (46 in Cyg?) */
#define ENOMEM 12 /* Not enough space */
Referenced by allocator_memalign(), and VASNPRINTF().
#define ENOSPC 28 /* No space left on device */
#define ENOSYS 40 /* Function not implemented (88 in Cyg?) */
#define ENOTDIR 20 /* Not a directory */
#define ENOTEMPTY 41 /* Directory not empty (90 in Cyg?) */
#define ENOTTY 25 /* Inappropriate I/O control operation */
#define ENXIO 6 /* No such device or address */
#define EPERM 1 /* Operation not permitted */
#define EPIPE 32 /* Broken pipe */
#define ERANGE 34 /* Result too large (possibly too small) */
Referenced by DCIGETTEXT(), g_ascii_strtoll(), and g_parse_long_long().
#define EROFS 30 /* Read-only file system */
#define ESPIPE 29 /* Invalid seek (seek on a pipe?) */
#define ESRCH 3 /* No such process */
#define EXDEV 18 /* Improper link (cross-device link?) */
Function Documentation
int* _errno (void)
char* strerror (int num)
Referenced by allocator_add_slab(), map_new_csv(), map_rect_new_textfile(), navit_mark_navigation_stopped(), SHPCreateLL(), SHPOpenLL(), SHPWriteHeader(), SHPWriteObject(), smc_tree_abort(), vehicle_gpsd_open(), and write_former_destinations().
Variable Documentation
int errno
errno.h included from mingw32ce/../errno.h