navit: support/espeak/espeak_command.h File Reference
espeak_command.h File Reference
#include <unistd.h>
#include "speak_lib.h"
Data Structures
struct t_espeak_text
struct t_espeak_mark
struct t_espeak_character
struct t_espeak_key
struct t_espeak_terminated_msg
struct t_espeak_parameter
struct t_espeak_command
union t_espeak_command::command
Enumerations
enum t_espeak_type {
ET_TEXT, ET_MARK, ET_KEY, ET_CHAR,
ET_PARAMETER, ET_PUNCTUATION_LIST, ET_VOICE_NAME, ET_VOICE_SPEC,
ET_TERMINATED_MSG
}
enum t_command_state { CS_UNDEFINED, CS_PENDING, CS_PROCESSED }
Functions
t_espeak_command * create_espeak_text (const void *text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void *user_data)
t_espeak_command * create_espeak_mark (const void *text, size_t size, const char *index_mark, unsigned int end_position, unsigned int flags, void *user_data)
t_espeak_command * create_espeak_terminated_msg (unsigned int unique_identifier, void *user_data)
t_espeak_command * create_espeak_key (const char *key_name, void *user_data)
t_espeak_command * create_espeak_char (wchar_t character, void *user_data)
t_espeak_command * create_espeak_parameter (espeak_PARAMETER parameter, int value, int relative)
t_espeak_command * create_espeak_punctuation_list (const wchar_t *punctlist)
t_espeak_command * create_espeak_voice_name (const char *name)
t_espeak_command * create_espeak_voice_spec (espeak_VOICE *voice_spec)
void process_espeak_command (t_espeak_command *the_command)
int delete_espeak_command (t_espeak_command *the_command)
void display_espeak_command (t_espeak_command *the_command)
espeak_ERROR sync_espeak_Synth (unsigned int unique_identifier, const void *text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void *user_data)
espeak_ERROR sync_espeak_Synth_Mark (unsigned int unique_identifier, const void *text, size_t size, const char *index_mark, unsigned int end_position, unsigned int flags, void *user_data)
void sync_espeak_Key (const char *key)
void sync_espeak_Char (wchar_t character)
void sync_espeak_SetPunctuationList (const wchar_t *punctlist)
void sync_espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
int sync_espeak_SetVoiceByName (const char *name)
int sync_espeak_SetVoiceByProperties (espeak_VOICE *voice_selector)
espeak_ERROR SetVoiceByName (const char *name)
espeak_ERROR SetVoiceByProperties (espeak_VOICE *voice_selector)
void SetParameter (int parameter, int value, int relative)
int sync_espeak_terminated_msg (unsigned int unique_identifier, void *user_data)
Enumeration Type Documentation
enum t_command_state
Enumerator
CS_UNDEFINED
CS_PENDING
CS_PROCESSED
enum t_espeak_type
Enumerator
ET_TEXT
ET_MARK
ET_KEY
ET_CHAR
ET_PARAMETER
ET_PUNCTUATION_LIST
ET_VOICE_NAME
ET_VOICE_SPEC
ET_TERMINATED_MSG
Function Documentation
t_espeak_command* create_espeak_char (wchar_t character, void * user_data)
Referenced by espeak_Char().
t_espeak_command* create_espeak_key (const char * key_name, void * user_data)
Referenced by espeak_Key().
t_espeak_command* create_espeak_mark (const void * text, size_t size, const char * index_mark, unsigned int end_position, unsigned int flags, void * user_data)
Referenced by espeak_Synth_Mark().
t_espeak_command* create_espeak_parameter (espeak_PARAMETER parameter, int value, int relative)
Referenced by espeak_SetParameter().
t_espeak_command* create_espeak_punctuation_list (const wchar_t * punctlist)
Referenced by espeak_SetPunctuationList().
t_espeak_command* create_espeak_terminated_msg (unsigned int unique_identifier, void * user_data)
Referenced by espeak_Synth(), and espeak_Synth_Mark().
t_espeak_command* create_espeak_text (const void * text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void * user_data)
Referenced by espeak_Synth().
t_espeak_command* create_espeak_voice_name (const char * name)
Referenced by espeak_SetVoiceByName().
t_espeak_command* create_espeak_voice_spec (espeak_VOICE * voice_spec)
Referenced by espeak_SetVoiceByProperties().
int delete_espeak_command (t_espeak_command * the_command)
Referenced by espeak_Char(), espeak_Key(), espeak_SetParameter(), espeak_SetPunctuationList(), espeak_SetVoiceByName(), espeak_SetVoiceByProperties(), espeak_Synth(), and espeak_Synth_Mark().
void display_espeak_command (t_espeak_command * the_command)
void process_espeak_command (t_espeak_command * the_command)
void SetParameter (int parameter, int value, int relative)
Referenced by espeak_Initialize(), espeak_new(), espeak_SetParameter(), LoadMbrolaTable(), and main().
espeak_ERROR SetVoiceByName (const char * name)
Referenced by espeak_Initialize(), espeak_new(), espeak_SetVoiceByName(), main(), and Synthesize().
espeak_ERROR SetVoiceByProperties (espeak_VOICE * voice_selector)
Referenced by espeak_SetVoiceByProperties(), and main().
void sync_espeak_Char (wchar_t character)
References buf, espeakSSML, my_unique_identifier, my_user_data, NULL, sprintf(), and Synthesize().
Referenced by espeak_Char(), and sync_espeak_Key().
void sync_espeak_Key (const char * key)
References my_unique_identifier, my_user_data, NULL, sync_espeak_Char(), Synthesize(), and utf8_in().
Referenced by espeak_Key().
void sync_espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
void sync_espeak_SetPunctuationList (const wchar_t * punctlist)
References my_unique_identifier, my_user_data, N_PUNCTLIST, NULL, and option_punctlist.
Referenced by espeak_SetPunctuationList().
int sync_espeak_SetVoiceByName (const char * name)
int sync_espeak_SetVoiceByProperties (espeak_VOICE * voice_selector)
espeak_ERROR sync_espeak_Synth (unsigned int unique_identifier, const void * text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void * user_data)
References end_character_position, ENTER, InitText(), my_audio, my_unique_identifier, my_user_data, POS_CHARACTER, POS_SENTENCE, POS_WORD, SHOW, SHOW_TIME, skip_characters, skip_sentences, skip_words, skipping_text, Synthesize(), and wave_flush().
Referenced by espeak_Synth().
espeak_ERROR sync_espeak_Synth_Mark (unsigned int unique_identifier, const void * text, size_t size, const char * index_mark, unsigned int end_position, unsigned int flags, void * user_data)
References end_character_position, espeakSSML, InitText(), my_unique_identifier, my_user_data, NULL, SHOW_TIME, skip_marker, skipping_text, strncpy0(), and Synthesize().
Referenced by espeak_Synth_Mark().
int sync_espeak_terminated_msg (unsigned int unique_identifier, void * user_data)