navit: support/espeak/espeak.c File Reference
espeak.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <time.h>
#include <sys/stat.h>
#include "speak_lib.h"
Macros
#define N_PUNCTLIST 100
Functions
int GetFileLength (const char *filename)
void strncpy0 (char *dest, const char *source, int size)
void DisplayVoices (FILE *f_out, char *language)
static void Write4Bytes (FILE *f, int value)
int OpenWavFile (char *path, int rate)
static void CloseWavFile ()
static int SynthCallback (short *wav, int numsamples, espeak_EVENT *events)
int main (int argc, char **argv)
Variables
static const char * help_text
int samplerate
int quiet = 0
unsigned int samples_total = 0
unsigned int samples_split = 0
unsigned int wavefile_count = 0
FILE * f_wavfile = NULL
char filetype [5]
char wavefile [200]
Macro Definition Documentation
#define N_PUNCTLIST 100
Referenced by main(), and sync_espeak_SetPunctuationList().
Function Documentation
static void CloseWavFile () static
References f_wavfile, NULL, startup::pos, SEEK_SET, and Write4Bytes().
Referenced by SynthCallback().
void DisplayVoices (FILE * f_out, char * language)
References espeak_VOICE::age, espeak_ListVoices(), fprintf(), espeak_VOICE::gender, genders, espeak_VOICE::identifier, espeak_VOICE::languages, espeak_VOICE::name, NULL, p, and sprintf().
Referenced by main().
int GetFileLength (const char * filename)
References S_IFDIR, S_IFMT, stat::st_mode, stat::st_size, and stat().
Referenced by main().
int main (int argc, char ** argv)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References AUDIO_OUTPUT_PLAYBACK, AUDIO_OUTPUT_SYNCHRONOUS, c, DisplayVoices(), EE_OK, espeak_CompileDictionary(), espeak_Info(), espeak_Initialize(), espeak_SetParameter(), espeak_SetPhonemeTrace(), espeak_SetPunctuationList(), espeak_SetSynthCallback(), espeak_SetVoiceByName(), espeak_SetVoiceByProperties(), espeak_Synchronize(), espeak_Synth(), espeakCAPITALS, espeakCHARS_8BIT, espeakCHARS_AUTO, espeakENDPAUSE, espeakLINELENGTH, espeakPHONEMES, espeakPITCH, espeakPUNCTUATION, espeakRATE, espeakSSML, espeakVOLUME, espeakWORDGAP, exit, filename, filetype, fprintf(), GetFileLength(), getopt_long(), help_text, espeak_VOICE::languages, max, N_PUNCTLIST, no_argument, NULL, OpenWavFile(), optarg, optind, option_capitals, option_linelength, option_phonemes, option_punctlist, option_punctuation, option_waveout, optional_argument, POS_CHARACTER, printf(), quiet, required_argument, samplerate, samples_split, size, speed, strncpy0(), SynthCallback(), value, and wavefile.
int OpenWavFile (char * path, int rate)
References f_wavfile, NULL, and Write4Bytes().
Referenced by main(), and SynthCallback().
void strncpy0 (char * dest, const char * source, int size)
References NULL.
Referenced by main().
static int SynthCallback (short * wav, int numsamples, espeak_EVENT * events) static
References CloseWavFile(), espeakEVENT_SENTENCE, f_wavfile, filetype, NULL, OpenWavFile(), quiet, samplerate, samples_split, samples_total, sprintf(), espeak_EVENT::type, wavefile, and wavefile_count.
Referenced by espeak_SetSynthCallback(), and main().
static void Write4Bytes (FILE * f, int value) static
Referenced by CloseWavFile(), and OpenWavFile().
Variable Documentation
FILE* f_wavfile = NULL
Referenced by CloseWavFile(), OpenWavFile(), and SynthCallback().
char filetype[5]
Referenced by main(), and SynthCallback().
const char* help_text static
Referenced by main().
int quiet = 0
Referenced by main(), and SynthCallback().
int samplerate
Referenced by DoPause(), DoSample2(), DoSpect(), espeak_Initialize(), LoadMbrolaTable(), LoadSoundFile(), main(), MarkerEvent(), MbrolaTranslate(), SynthCallback(), VoiceReset(), and WavegenFile().
unsigned int samples_split = 0
Referenced by main(), and SynthCallback().
unsigned int samples_total = 0
Referenced by SynthCallback().
char wavefile[200]
Referenced by main(), and SynthCallback().
unsigned int wavefile_count = 0
Referenced by SynthCallback().