navit: support/gettext_intl/eval-plural.h File Reference
eval-plural.h File Reference
Macros
#define STATIC static
Functions
STATIC unsigned long int
internal_function plural_eval (struct expression *pexp, unsigned long int n)
Macro Definition Documentation
#define STATIC static
Function Documentation
STATIC unsigned long int internal_function plural_eval (struct expression * pexp, unsigned long int n)
References expression::args, expression::nargs, expression::num, num, expression::operation, plural_eval(), SIGFPE, and expression::val.
Referenced by plural_eval(), and plural_lookup().