navit: event.h File Reference
event.h File Reference
Data Structures
struct event_methods
Enumerations
enum event_watch_cond { event_watch_cond_read =1 , event_watch_cond_write , event_watch_cond_except }
Functions
void event_main_loop_run (void)
void event_main_loop_quit (void)
int event_main_loop_has_quit (void)
struct event_watch * event_add_watch (int fd, enum event_watch_cond cond, struct callback *cb)
void event_remove_watch (struct event_watch *ev)
struct event_timeout * event_add_timeout (int timeout, int multi, struct callback *cb)
void event_remove_timeout (struct event_timeout *ev)
struct event_idle * event_add_idle (int priority, struct callback *cb)
void event_remove_idle (struct event_idle *ev)
void event_call_callback (struct callback_list *cb)
char const * event_system (void)
int event_request_system (const char *system, const char *requestor)
Enumeration Type Documentation
event_watch_cond
enum event_watch_cond
Enumerator
event_watch_cond_read
event_watch_cond_write
event_watch_cond_except
Function Documentation
event_add_idle()
struct event_idle* event_add_idle (int priority, struct callback * cb)
References event_methods::add_idle, event_idle::cb, and require_method2.
Referenced by command_saved_attr_new(), command_saved_evaluate(), graphics_load_mapset(), gui_internal_search_idle_start(), j1850_idle(), navigation_update(), route_graph_build(), start_search(), traffic_get_map(), traffic_loop(), and traffic_process_messages().
event_add_timeout()
struct event_timeout* event_add_timeout (int timeout, int multi, struct callback * cb)
Add an event timeout
Parameters
the timeout itself in msec
multi 0 means that the timeout will fire only once, 1 means that it will repeat
the callback to call when the timeout expires
Returns
the result of the event_methods.add_timeout() call
References event_methods::add_timeout, event_timeout::cb, event_timeout::multi, and require_method2.
Referenced by event_sdl_main_loop_run(), graphics_qt5_disable_suspend(), graphics_sdl_idle(), gui_internal_motion(), j1850_init_serial_port(), log_new(), messagelist_init(), navit_handle_button(), navit_handle_motion(), osd_cmd_interface_init(), osd_j1850_init(), osd_odometer_init(), osd_stopwatch_init(), pedestrian_setup_tilt(), request_navit_quit(), script_set_attr_int(), traffic_new(), vehicle_demo_new(), vehicle_demo_set_attr_do(), vehicle_file_enable_watch(), vehicle_file_new_file(), vehicle_file_parse(), vehicle_file_restart_fix_timeout(), vehicle_gpsd_open(), vehicle_set_cursor(), vehicle_webos_open(), and vehicle_wince_restart_fix_timeout().
event_add_watch()
struct event_watch* event_add_watch (int fd, enum event_watch_cond cond, struct callback * cb)
References event_methods::add_watch, event_watch::cb, event_watch::fd, and require_method2.
Referenced by graphics_opengl_x11_new(), pedestrian_setup_tilt(), vehicle_file_enable_watch(), and vehicle_gpsd_try_open().
event_call_callback()
void event_call_callback (struct callback_list * cb)
References event_methods::call_callback, event_idle::cb, and require_method.
Referenced by mlPDL_ServiceCall(), mlPDL_ServiceCallWithCallback(), vehicle_webos_init_pdl_locationtracking(), and wince_reader_thread().
event_main_loop_has_quit()
int event_main_loop_has_quit (void)
References has_quit.
Referenced by gui_internal_button(), and gui_internal_keypress().
event_main_loop_quit()
void event_main_loop_quit (void)
References has_quit, and event_methods::main_loop_quit.
Referenced by gui_internal_cmd2_quit(), NGQProxyNavit::quit(), and request_navit_quit().
event_main_loop_run()
void event_main_loop_run (void)
References event_methods::main_loop_run, and require_method.
Referenced by main_real().
event_remove_idle()
void event_remove_idle (struct event_idle * ev)
References event_methods::remove_idle, and require_method.
Referenced by android_search_end(), command_saved_callbacks_changed(), command_saved_evaluate_idle(), do_draw(), gui_internal_search_idle_end(), navigation_update_done(), pedestrian_rocket_idle(), route_graph_build_done(), traffic_loop(), traffic_process_messages(), and traffic_process_messages_int().
event_remove_timeout()
void event_remove_timeout (struct event_timeout * ev)
References event_methods::remove_timeout, and require_method.
Referenced by event_sdl_main_loop_run(), graphics_destroy(), graphics_sdl_idle(), j1850_idle(), log_destroy(), navit_handle_button(), navit_handle_motion(), script_destroy(), script_set_attr_int(), vehicle_demo_destroy(), vehicle_demo_set_attr_do(), vehicle_destroy(), vehicle_file_disable_watch(), vehicle_file_restart_fix_timeout(), vehicle_gpsd_close(), vehicle_gpsd_try_open(), vehicle_set_cursor(), vehicle_webos_close(), and vehicle_wince_restart_fix_timeout().
event_remove_watch()
void event_remove_watch (struct event_watch * ev)
References event_methods::remove_watch, and require_method.
Referenced by graphics_opengl_x11_destroy(), vehicle_file_disable_watch(), and vehicle_gpsd_close().
event_request_system()
int event_request_system (const char * system, const char * requestor)
References dbg, e_requestor, e_system, event_type_new(), and lvl_error.
Referenced by graphics_android_new(), graphics_cocoa_new(), graphics_gd_new(), graphics_gtk_drawing_area_new(), graphics_null_new(), graphics_opengl_new(), graphics_opengl_x11_new(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_svg_debug_new(), graphics_win32_new(), and gui_gtk_new().
event_system()
char const* event_system (void)
References e_system.
Referenced by messagelist_init().