navit: graphics/sdl/event_sdl.c File Reference
event_sdl.c File Reference
#include <glib.h>
#include <poll.h>
#include <SDL/SDL.h>
#include <pthread.h>
#include <signal.h>
#include "config.h"
#include "event.h"
#include "event_sdl.h"
#include "graphics_sdl.h"
#include "debug.h"
#include "callback.h"
#include "plugin.h"
Functions
static void event_sdl_watch_startthread (GPtrArray *)
static void event_sdl_watch_stopthread (void)
static struct event_watch * event_sdl_add_watch (int, enum event_watch_cond, struct callback *)
static void event_sdl_remove_watch (struct event_watch *)
static struct event_timeout * event_sdl_add_timeout (int, int, struct callback *)
static void event_sdl_remove_timeout (struct event_timeout *)
static struct event_idle * event_sdl_add_idle (int, struct callback *)
static void event_sdl_remove_idle (struct event_idle *)
static void event_sdl_call_callback (struct callback_list *)
static Uint32 sdl_timer_callback (Uint32 interval, void *param)
static void event_sdl_main_loop_run (void)
static void event_sdl_main_loop_quit (void)
void event_sdl_watch_thread (GPtrArray *watch_list)
static gint sdl_sort_idle_tasks (gconstpointer parama, gconstpointer paramb)
static struct event_priv * event_sdl_new (struct event_methods *methods)
void event_sdl_register (void)
Variables
static pthread_t sdl_watch_thread = 0
static GPtrArray * sdl_watch_list = NULL
static struct event_methods event_sdl_methods
Function Documentation
event_sdl_add_idle()
static struct event_idle * event_sdl_add_idle (int priority, struct callback * cb) static
References idle_task::cb, dbg, idle_tasks, lvl_debug, idle_task::priority, and sdl_sort_idle_tasks().
event_sdl_add_timeout()
static struct event_timeout * event_sdl_add_timeout (int timeout, int multi, struct callback * cb) static
References event_timeout::cb, dbg, event_timeout::id, lvl_debug, lvl_error, event_timeout::multi, and sdl_timer_callback().
event_sdl_add_watch()
static struct event_watch * event_sdl_add_watch (int fd, enum event_watch_cond cond, struct callback * cb) static
References event_watch::cb, dbg, event_sdl_watch_startthread(), event_sdl_watch_stopthread(), event_watch_cond_except, event_watch_cond_read, event_watch_cond_write, lvl_debug, event_watch::pfd, and sdl_watch_list.
event_sdl_call_callback()
static void event_sdl_call_callback (struct callback_list * cbl) static
References cbl, dbg, and lvl_debug.
event_sdl_main_loop_quit()
static void event_sdl_main_loop_quit (void) static
References quit_event_loop.
event_sdl_main_loop_run()
static void event_sdl_main_loop_run (void) static
References event_sdl_watch_stopthread(), and graphics_sdl_idle().
event_sdl_new()
static struct event_priv* event_sdl_new (struct event_methods * methods) static
References event_sdl_methods, and idle_tasks.
Referenced by event_sdl_register().
event_sdl_register()
void event_sdl_register (void)
References event_sdl_new().
event_sdl_remove_idle()
static void event_sdl_remove_idle (struct event_idle * task) static
References dbg, idle_tasks, and lvl_debug.
event_sdl_remove_timeout()
static void event_sdl_remove_timeout (struct event_timeout * to) static
References dbg, event_timeout::id, lvl_debug, lvl_error, and lvl_info.
event_sdl_remove_watch()
static void event_sdl_remove_watch (struct event_watch * ew) static
References dbg, event_sdl_watch_startthread(), event_sdl_watch_stopthread(), lvl_debug, event_watch::pfd, and sdl_watch_list.
event_sdl_watch_startthread()
static void event_sdl_watch_startthread (GPtrArray * watch_list) static
References dbg, dbg_assert, event_sdl_watch_stopthread(), event_sdl_watch_thread(), lvl_debug, and sdl_watch_thread.
Referenced by event_sdl_add_watch(), and event_sdl_remove_watch().
event_sdl_watch_stopthread()
static void event_sdl_watch_stopthread (void) static
References dbg, lvl_debug, and sdl_watch_thread.
Referenced by event_sdl_add_watch(), event_sdl_main_loop_run(), event_sdl_remove_watch(), and event_sdl_watch_startthread().
event_sdl_watch_thread()
void event_sdl_watch_thread (GPtrArray * watch_list)
References event_watch::cb, dbg, lvl_debug, event_watch::pfd, and callback::type.
Referenced by event_sdl_watch_startthread().
sdl_sort_idle_tasks()
static gint sdl_sort_idle_tasks (gconstpointer parama, gconstpointer paramb) static
References idle_task::priority.
Referenced by event_sdl_add_idle().
sdl_timer_callback()
static Uint32 sdl_timer_callback (Uint32 interval, void * param) static
References event_timeout::cb, dbg, event_timeout::id, lvl_debug, event_timeout::multi, and callback::type.
Referenced by event_sdl_add_timeout().
Variable Documentation
event_sdl_methods
struct event_methods event_sdl_methods static
Initial value:
= {
    event_sdl_main_loop_run,
    event_sdl_main_loop_quit,
    event_sdl_add_watch,
    event_sdl_remove_watch,
    event_sdl_add_timeout,
    event_sdl_remove_timeout,
    event_sdl_add_idle,
    event_sdl_remove_idle,
    event_sdl_call_callback,
}
Referenced by event_sdl_new().
sdl_watch_list
GPtrArray* sdl_watch_list = NULL static
Referenced by event_sdl_add_watch(), event_sdl_remove_watch(), and graphics_sdl_new().
sdl_watch_thread
pthread_t sdl_watch_thread = 0 static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by event_sdl_watch_startthread(), event_sdl_watch_stopthread(), and graphics_sdl_new().