navit: event_glib.c File Reference
event_glib.c File Reference
#include <glib.h>
#include "event.h"
#include "event_glib.h"
#include "debug.h"
#include "callback.h"
#include "plugin.h"
Data Structures
struct event_watch
struct event_timeout
struct event_idle
struct event_priv
Functions
static void event_glib_main_loop_run (void)
static void event_glib_main_loop_quit (void)
static gboolean event_glib_call_watch (GIOChannel *iochan, GIOCondition condition, gpointer t)
static struct event_watch * event_glib_add_watch (int fd, enum event_watch_cond cond, struct callback *cb)
static void event_glib_remove_watch (struct event_watch *ev)
static gboolean event_glib_call_timeout_single (struct event_timeout *ev)
static gboolean event_glib_call_timeout_multi (struct event_timeout *ev)
static struct event_timeout * event_glib_add_timeout (int timeout, int multi, struct callback *cb)
static void event_glib_remove_timeout (struct event_timeout *ev)
static gboolean event_glib_call_idle (struct event_idle *ev)
static struct event_idle * event_glib_add_idle (int priority, struct callback *cb)
static void event_glib_remove_idle (struct event_idle *ev)
static void event_glib_call_callback (struct callback_list *cb)
static struct event_priv * event_glib_new (struct event_methods *meth)
void event_glib_init (void)
Variables
static GMainLoop * loop
static struct event_methods event_glib_methods
Function Documentation
event_glib_add_idle()
static struct event_idle* event_glib_add_idle (int priority, struct callback * cb) static
References event_watch::cb, event_idle::cb, event_glib_call_idle(), and event_idle::source.
event_glib_add_timeout()
static struct event_timeout* event_glib_add_timeout (int timeout, int multi, struct callback * cb) static
References event_watch::cb, event_timeout::cb, event_glib_call_timeout_multi(), event_glib_call_timeout_single(), and event_timeout::source.
event_glib_add_watch()
static struct event_watch* event_glib_add_watch (int fd, enum event_watch_cond cond, struct callback * cb) static
References event_glib_call_watch(), event_watch_cond_except, event_watch_cond_read, event_watch_cond_write, event_watch::iochan, and event_watch::source.
event_glib_call_callback()
static void event_glib_call_callback (struct callback_list * cb) static
event_glib_call_idle()
static gboolean event_glib_call_idle (struct event_idle * ev) static
References callback_call_0, and event_idle::cb.
Referenced by event_glib_add_idle().
event_glib_call_timeout_multi()
static gboolean event_glib_call_timeout_multi (struct event_timeout * ev) static
References callback_call_0, and event_timeout::cb.
Referenced by event_glib_add_timeout().
event_glib_call_timeout_single()
static gboolean event_glib_call_timeout_single (struct event_timeout * ev) static
References callback_call_0, and event_timeout::cb.
Referenced by event_glib_add_timeout().
event_glib_call_watch()
static gboolean event_glib_call_watch (GIOChannel * iochan, GIOCondition condition, gpointer t) static
References callback_call_0, and event_watch::cb.
Referenced by event_glib_add_watch().
event_glib_init()
void event_glib_init (void)
References event_glib_new().
Referenced by main_real().
event_glib_main_loop_quit()
static void event_glib_main_loop_quit (void) static
References loop.
event_glib_main_loop_run()
static void event_glib_main_loop_run (void) static
References loop.
event_glib_new()
static struct event_priv* event_glib_new (struct event_methods * meth) static
References event_glib_methods.
Referenced by event_glib_init().
event_glib_remove_idle()
static void event_glib_remove_idle (struct event_idle * ev) static
References event_idle::source.
event_glib_remove_timeout()
static void event_glib_remove_timeout (struct event_timeout * ev) static
References event_timeout::source.
event_glib_remove_watch()
static void event_glib_remove_watch (struct event_watch * ev) static
References event_watch::iochan, and event_watch::source.
Variable Documentation
event_glib_methods
struct event_methods event_glib_methods static
Initial value:
= {
    event_glib_main_loop_run,
    event_glib_main_loop_quit,
    event_glib_add_watch,
    event_glib_remove_watch,
    event_glib_add_timeout,
    event_glib_remove_timeout,
    event_glib_add_idle,
    event_glib_remove_idle,
    event_glib_call_callback,
}
Referenced by event_glib_new().
loop
GMainLoop* loop static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by event_glib_main_loop_quit(), event_glib_main_loop_run(), and itembin_loop_combiner().