navit: graphics/qt5/event_qt5.cpp File Reference
event_qt5.cpp File Reference
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include "config.h"
#include "navit/callback.h"
#include "navit/color.h"
#include "navit/debug.h"
#include "navit/event.h"
#include "navit/point.h"
#include "navit/graphics.h"
#include "navit/item.h"
#include "navit/keys.h"
#include "navit/navit.h"
#include "navit/plugin.h"
#include "navit/window.h"
#include "event_qt5.h"
#include "event_qt5.moc"
#include "graphics_qt5.h"
#include <QSocketNotifier>
Data Structures
struct event_watch
Functions
static void event_qt5_remove_timeout (struct event_timeout *to)
static void event_qt5_main_loop_run (void)
static void event_qt5_main_loop_quit (void)
static struct event_watch * event_qt5_add_watch (int fd, enum event_watch_cond cond, struct callback *cb)
static void event_qt5_remove_watch (struct event_watch *ev)
static struct event_timeout * event_qt5_add_timeout (int timeout, int multi, struct callback *cb)
static struct event_idle * event_qt5_add_idle (int priority, struct callback *cb)
static void event_qt5_remove_idle (struct event_idle *ev)
static void event_qt5_call_callback (struct callback_list *cb)
static struct event_priv * event_qt5_new (struct event_methods *meth)
void qt5_event_init (void)
Variables
qt5_navit_timer * qt5_timer = NULL
static struct event_methods event_qt5_methods
Function Documentation
static struct event_idle* event_qt5_add_idle (int priority, struct callback * cb) static
References dbg, event_qt5_add_timeout(), and lvl_debug.
static struct event_timeout* event_qt5_add_timeout (int timeout, int multi, struct callback * cb) static
References dbg, g_hash_table_insert(), event_timeout::id, long, lvl_debug, qt5_navit_timer::timer_callback, and qt5_navit_timer::timer_type.
Referenced by event_qt5_add_idle().
static struct event_watch* event_qt5_add_watch (int fd, enum event_watch_cond cond, struct callback * cb) static
References event_watch::cb, dbg, event_watch::fd, g_hash_table_insert(), g_new0, GINT_TO_POINTER, lvl_debug, event_watch::sn, and qt5_navit_timer::watches.
static void event_qt5_call_callback (struct callback_list * cb) static
References dbg, and lvl_debug.
static void event_qt5_main_loop_quit (void) static
References dbg, exit, and lvl_debug.
static void event_qt5_main_loop_run (void) static
References dbg, lvl_debug, navit_app, and NULL.
static struct event_priv* event_qt5_new (struct event_methods * meth) static
References event_qt5_methods, and NULL.
Referenced by qt5_event_init().
static void event_qt5_remove_idle (struct event_idle * ev) static
References dbg, event_qt5_remove_timeout(), and lvl_debug.
static void event_qt5_remove_timeout (struct event_timeout * to) static
References dbg, g_hash_table_remove(), lvl_debug, qt5_navit_timer::timer_callback, and qt5_navit_timer::timer_type.
Referenced by event_qt5_remove_idle(), and qt5_navit_timer::timerEvent().
static void event_qt5_remove_watch (struct event_watch * ev) static
References dbg, event_watch::fd, g_free(), g_hash_table_remove(), GINT_TO_POINTER, lvl_debug, event_watch::sn, and qt5_navit_timer::watches.
void qt5_event_init (void)
References event_qt5_new().
Referenced by plugin_init().
Variable Documentation
struct event_methods event_qt5_methods static
Initial value:
= {
    event_qt5_main_loop_run,
    event_qt5_main_loop_quit,
    event_qt5_add_watch,
    event_qt5_remove_watch,
    event_qt5_add_timeout,
    event_qt5_remove_timeout,
    event_qt5_add_idle,
    event_qt5_remove_idle,
    event_qt5_call_callback,
}
Referenced by event_qt5_new().
qt5_navit_timer* qt5_timer = NULL