navit: event.c File Reference
event.c File Reference
#include <string.h>
#include <stdlib.h>
#include "event.h"
#include "plugin.h"
#include "debug.h"
Macros
#define require_method_helper(m)
#define require_method(m)
#define require_method2(m, r)
Functions
void event_main_loop_run (void)
void event_main_loop_quit (void)
int event_main_loop_has_quit (void)
struct event_watch * event_add_watch (int fd, enum event_watch_cond cond, struct callback *cb)
void event_remove_watch (struct event_watch *ev)
struct event_timeout * event_add_timeout (int timeout, int multi, struct callback *cb)
void event_remove_timeout (struct event_timeout *ev)
struct event_idle * event_add_idle (int priority, struct callback *cb)
void event_remove_idle (struct event_idle *ev)
void event_call_callback (struct callback_list *cb)
char const * event_system (void)
int event_request_system (const char *system, const char *requestor)
Variables
static struct event_methods event_methods
static const char * e_requestor
static const char * e_system
static int has_quit
Macro Definition Documentation
#define require_method (m)
Value:
require_method_helper(m)\
        return;\
        }
Referenced by event_call_callback(), event_main_loop_run(), event_remove_idle(), event_remove_timeout(), and event_remove_watch().
#define require_method2 (m, r)
Value:
require_method_helper(m)\
        return r;\
        }
Referenced by event_add_idle(), event_add_timeout(), and event_add_watch().
#define require_method_helper (m)
Value:
if(!event_methods.m) {\
        dbg(lvl_error, "Can't find event system method %s. Event system is %s%s\n",\
                        #m ,e_system?"set to ":"not set.", e_system?e_system:"");\
Function Documentation
struct event_idle* event_add_idle (int priority, struct callback * cb)
References event_methods::add_idle, NULL, and require_method2.
Referenced by command_saved_attr_new(), command_saved_evaluate(), graphics_load_mapset(), gui_internal_search_idle_start(), j1850_idle(), navigation_update(), pedestrian_cmd_pedestrian_rocket(), route_graph_build(), and start_search().
struct event_timeout* event_add_timeout (int timeout, int multi, struct callback * cb)
Add an event timeout
Parameters
the timeout itself in msec
multi 0 means that the timeout will fire only once, 1 means that it will repeat
the callback to call when the timeout expires
Returns
the result of the event_methods.add_timeout() call
References event_methods::add_timeout, NULL, and require_method2.
Referenced by event_sdl_main_loop_run(), graphics_qt5_disable_suspend(), graphics_sdl_idle(), gui_internal_motion(), j1850_init_serial_port(), log_new(), messagelist_init(), navit_handle_button(), navit_handle_motion(), osd_cmd_interface_init(), osd_j1850_init(), osd_odometer_init(), osd_stopwatch_init(), pedestrian_setup_tilt(), request_navit_quit(), script_set_attr_int(), vehicle_demo_new(), vehicle_demo_set_attr_do(), vehicle_file_enable_watch(), vehicle_file_new_file(), vehicle_file_parse(), vehicle_gpsd_open(), vehicle_set_cursor(), vehicle_webos_open(), and vehicle_webos_parse_nmea().
struct event_watch* event_add_watch (int fd, enum event_watch_cond cond, struct callback * cb)
References event_methods::add_watch, NULL, and require_method2.
Referenced by graphics_opengl_x11_new(), pedestrian_setup_tilt(), vehicle_file_enable_watch(), and vehicle_gpsd_try_open().
void event_call_callback (struct callback_list * cb)
References event_methods::call_callback, and require_method.
Referenced by mlPDL_ServiceCall(), mlPDL_ServiceCallWithCallback(), vehicle_webos_init_pdl_locationtracking(), and wince_reader_thread().
int event_main_loop_has_quit (void)
References has_quit.
Referenced by gui_internal_button(), and gui_internal_keypress().
void event_main_loop_quit (void)
References has_quit, and event_methods::main_loop_quit.
Referenced by gui_internal_cmd2_quit(), NGQProxyNavit::quit(), and request_navit_quit().
void event_main_loop_run (void)
References event_methods::main_loop_run, and require_method.
Referenced by main_real().
void event_remove_idle (struct event_idle * ev)
References event_methods::remove_idle, and require_method.
Referenced by android_search_end(), command_saved_callbacks_changed(), command_saved_evaluate_idle(), do_draw(), gui_internal_search_idle_end(), navigation_update_done(), pedestrian_rocket_idle(), and route_graph_build_done().
void event_remove_timeout (struct event_timeout * ev)
References event_methods::remove_timeout, and require_method.
Referenced by event_sdl_main_loop_run(), graphics_destroy(), graphics_sdl_idle(), j1850_idle(), log_destroy(), navit_handle_button(), navit_handle_motion(), script_destroy(), script_set_attr_int(), vehicle_demo_destroy(), vehicle_demo_set_attr_do(), vehicle_destroy(), vehicle_file_disable_watch(), vehicle_gpsd_close(), vehicle_gpsd_try_open(), vehicle_set_cursor(), and vehicle_webos_close().
void event_remove_watch (struct event_watch * ev)
References event_methods::remove_watch, and require_method.
Referenced by graphics_opengl_x11_destroy(), vehicle_file_disable_watch(), and vehicle_gpsd_close().
int event_request_system (const char * system, const char * requestor)
References dbg, e_requestor, e_system, lvl_error, and void().
Referenced by graphics_android_new(), graphics_cocoa_new(), graphics_gd_new(), graphics_gtk_drawing_area_new(), graphics_null_new(), graphics_opengl_new(), graphics_opengl_x11_new(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_win32_new(), and gui_gtk_new().
char const* event_system (void)
References e_system.
Referenced by messagelist_init().
Variable Documentation
const char* e_requestor static
Referenced by event_request_system().
const char* e_system static
Referenced by event_request_system(), and event_system().
struct event_methods event_methods static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
int has_quit static
Referenced by event_main_loop_has_quit(), and event_main_loop_quit().