navit: support/ezxml/ezxml.c File Reference
ezxml.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <glib.h>
#include "config.h"
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include "ezxml.h"
Data Structures
struct ezxml_root
Macros
#define EZXML_WS "\t\r\n "
#define EZXML_ERRL 128
Typedefs
typedef struct ezxml_root * ezxml_root_t
Functions
ezxml_t ezxml_child (ezxml_t xml, const char *name)
ezxml_t ezxml_idx (ezxml_t xml, int idx)
const char * ezxml_attr (ezxml_t xml, const char *attr)
ezxml_t ezxml_vget (ezxml_t xml, va_list ap)
ezxml_t ezxml_get (ezxml_t xml,...)
const char ** ezxml_pi (ezxml_t xml, const char *target)
ezxml_t ezxml_err (ezxml_root_t root, char *s, const char *err,...)
char * ezxml_decode (char *s, char **ent, char t)
void ezxml_open_tag (ezxml_root_t root, char *name, char **attr)
void ezxml_char_content (ezxml_root_t root, char *s, size_t len, char t)
ezxml_t ezxml_close_tag (ezxml_root_t root, char *name, char *s)
int ezxml_ent_ok (char *name, char *s, char **ent)
void ezxml_proc_inst (ezxml_root_t root, char *s, size_t len)
short ezxml_internal_dtd (ezxml_root_t root, char *s, size_t len)
char * ezxml_str2utf8 (char **s, size_t *len)
void ezxml_free_attr (char **attr)
ezxml_t ezxml_parse_str (char *s, size_t len)
ezxml_t ezxml_parse_fp (FILE *fp)
ezxml_t ezxml_parse_fd (int fd)
ezxml_t ezxml_parse_file (const char *file)
char * ezxml_ampencode (const char *s, size_t len, char **dst, size_t *dlen, size_t *max, short a)
char * ezxml_toxml_r (ezxml_t xml, char **s, size_t *len, size_t *max, size_t start, char ***attr)
char * ezxml_toxml (ezxml_t xml)
void ezxml_free (ezxml_t xml)
const char * ezxml_error (ezxml_t xml)
ezxml_t ezxml_new (const char *name)
ezxml_t ezxml_insert (ezxml_t xml, ezxml_t dest, size_t off)
ezxml_t ezxml_add_child (ezxml_t xml, const char *name, size_t off)
ezxml_t ezxml_set_txt (ezxml_t xml, const char *txt)
ezxml_t ezxml_set_attr (ezxml_t xml, const char *name, const char *value)
ezxml_t ezxml_set_flag (ezxml_t xml, short flag)
ezxml_t ezxml_cut (ezxml_t xml)
Variables
char * EZXML_NIL [] = { NULL }
Macro Definition Documentation
#define EZXML_ERRL 128
Referenced by ezxml_err().
#define EZXML_WS "\t\r\n "
Referenced by ezxml_internal_dtd(), ezxml_parse_str(), and ezxml_proc_inst().
Typedef Documentation
typedef struct ezxml_root* ezxml_root_t
Function Documentation
ezxml_t ezxml_add_child (ezxml_t xml, const char * name, size_t off)
References ezxml::attr, ezxml_insert(), EZXML_NIL, ezxml::name, NULL, and ezxml::txt.
Referenced by ezxml_open_tag().
char* ezxml_ampencode (const char * s, size_t len, char ** dst, size_t * dlen, size_t * max, short a)
References EZXML_BUFSIZE, and sprintf().
Referenced by ezxml_toxml_r().
const char* ezxml_attr (ezxml_t xml, const char * attr)
References ezxml::attr, ezxml_root::attr, for(), i, ezxml::name, NULL, ezxml::parent, and ezxml_root::xml.
Referenced by ezxml_toxml_r().
void ezxml_char_content (ezxml_root_t root, char * s, size_t len, char t)
References ezxml_root::cur, ezxml_root::ent, ezxml_decode(), ezxml_set_flag(), EZXML_TXTM, ezxml::flags, ezxml::name, and ezxml::txt.
Referenced by ezxml_parse_str().
ezxml_t ezxml_child (ezxml_t xml, const char * name)
References ezxml::child, ezxml::name, NULL, ezxml::sibling, and while().
Referenced by ezxml_vget().
ezxml_t ezxml_close_tag (ezxml_root_t root, char * name, char * s)
References ezxml_root::cur, ezxml_err(), ezxml::name, NULL, and ezxml::parent.
Referenced by ezxml_parse_str().
ezxml_t ezxml_cut (ezxml_t xml)
References ezxml::child, ezxml::name, ezxml::next, NULL, ezxml::ordered, ezxml::parent, and ezxml::sibling.
char* ezxml_decode (char * s, char ** ent, char t)
References c.
Referenced by ezxml_char_content(), ezxml_internal_dtd(), and ezxml_parse_str().
int ezxml_ent_ok (char * name, char * s, char ** ent)
References i.
Referenced by ezxml_internal_dtd().
ezxml_t ezxml_err (ezxml_root_t root, char * s, const char * err, ...)
References ezxml_root::err, EZXML_ERRL, g_snprintf(), g_vsnprintf(), ezxml_root::s, and ezxml_root::xml.
Referenced by ezxml_close_tag(), ezxml_internal_dtd(), and ezxml_parse_str().
const char* ezxml_error (ezxml_t xml)
References ezxml::parent.
void ezxml_free (ezxml_t xml)
References ezxml::attr, ezxml_root::attr, ezxml::child, ezxml_root::e, ezxml_root::ent, ezxml_free(), ezxml_free_attr(), EZXML_NAMEM, EZXML_TXTM, ezxml::flags, i, ezxml_root::len, ezxml_root::m, ezxml::name, ezxml::ordered, ezxml::parent, ezxml_root::pi, ezxml_root::s, ezxml::txt, and ezxml_root::u.
Referenced by ezxml_free(), and xml_parse_text().
void ezxml_free_attr (char ** attr)
References EZXML_NAMEM, EZXML_NIL, EZXML_TXTM, and i.
Referenced by ezxml_free(), and ezxml_parse_str().
ezxml_t ezxml_get (ezxml_t xml, ...)
References ezxml_vget().
ezxml_t ezxml_idx (ezxml_t xml, int idx)
References ezxml::next.
Referenced by ezxml_vget().
ezxml_t ezxml_insert (ezxml_t xml, ezxml_t dest, size_t off)
References ezxml::child, ezxml_root::cur, startup::dest, ezxml::name, ezxml::next, NULL, ezxml::off, ezxml::ordered, ezxml::parent, ezxml::sibling, and ezxml_root::xml.
Referenced by ezxml_add_child().
short ezxml_internal_dtd (ezxml_root_t root, char * s, size_t len)
References ezxml_root::attr, c, ezxml_root::ent, ezxml_root::err, ezxml_decode(), ezxml_ent_ok(), ezxml_err(), EZXML_NIL, ezxml_proc_inst(), EZXML_WS, i, NULL, and ezxml_root::standalone.
Referenced by ezxml_parse_str().
ezxml_t ezxml_new (const char * name)
References ezxml::attr, ezxml_root::attr, ezxml_root::cur, ezxml_root::ent, ezxml_root::err, EZXML_NIL, ezxml::name, NULL, ezxml_root::pi, ezxml::txt, and ezxml_root::xml.
Referenced by ezxml_parse_str().
void ezxml_open_tag (ezxml_root_t root, char * name, char ** attr)
References ezxml::attr, ezxml_root::cur, ezxml_add_child(), ezxml::name, name, and ezxml::txt.
Referenced by ezxml_parse_str().
ezxml_t ezxml_parse_fd (int fd)
References ezxml_parse_str(), fstat(), ezxml_root::len, NULL, read(), stat::st_size, and ezxml_root::xml.
Referenced by ezxml_parse_file().
ezxml_t ezxml_parse_file (const char * file)
References close(), ezxml_parse_fd(), O_RDONLY, and open().
ezxml_t ezxml_parse_fp (FILE * fp)
References EZXML_BUFSIZE, ezxml_parse_str(), ezxml_root::len, NULL, and ezxml_root::xml.
ezxml_t ezxml_parse_str (char * s, size_t len)
References ezxml::attr, ezxml_root::attr, ezxml_root::cur, ezxml_root::e, ezxml_root::ent, ezxml_char_content(), ezxml_close_tag(), ezxml_decode(), ezxml_err(), ezxml_free_attr(), ezxml_internal_dtd(), ezxml_new(), EZXML_NIL, ezxml_open_tag(), ezxml_proc_inst(), ezxml_str2utf8(), EZXML_TXTM, EZXML_WS, i, ezxml_root::m, ezxml::name, NULL, ezxml_root::s, ezxml_root::u, and ezxml_root::xml.
Referenced by ezxml_parse_fd(), ezxml_parse_fp(), and xml_parse_text().
const char** ezxml_pi (ezxml_t xml, const char * target)
References EZXML_NIL, i, ezxml::parent, ezxml_root::pi, while(), and ezxml_root::xml.
void ezxml_proc_inst (ezxml_root_t root, char * s, size_t len)
References EZXML_WS, g_strdup(), i, ezxml::name, NULL, ezxml_root::pi, ezxml_root::standalone, and ezxml_root::xml.
Referenced by ezxml_internal_dtd(), and ezxml_parse_str().
ezxml_t ezxml_set_attr (ezxml_t xml, const char * name, const char * value)
References ezxml::attr, c, EZXML_DUP, EZXML_NAMEM, EZXML_NIL, EZXML_TXTM, ezxml::flags, g_strdup(), and NULL.
ezxml_t ezxml_set_flag (ezxml_t xml, short flag)
References ezxml::flags.
Referenced by ezxml_char_content().
ezxml_t ezxml_set_txt (ezxml_t xml, const char * txt)
References EZXML_TXTM, ezxml::flags, NULL, and ezxml::txt.
char* ezxml_str2utf8 (char ** s, size_t * len)
References c, EZXML_BUFSIZE, max, and NULL.
Referenced by ezxml_parse_str().
char* ezxml_toxml (ezxml_t xml)
References ezxml_root::attr, EZXML_BUFSIZE, ezxml_toxml_r(), for(), i, max, ezxml::name, NULL, ezxml::ordered, p, ezxml::parent, ezxml_root::pi, sprintf(), and ezxml_root::xml.
char* ezxml_toxml_r (ezxml_t xml, char ** s, size_t * len, size_t * max, size_t start, char *** attr)
References ezxml::attr, ezxml::child, ezxml_ampencode(), ezxml_attr(), EZXML_BUFSIZE, i, max, ezxml::name, ezxml::off, ezxml::ordered, ezxml::parent, sprintf(), and ezxml::txt.
Referenced by ezxml_toxml().
ezxml_t ezxml_vget (ezxml_t xml, va_list ap)
References ezxml_child(), ezxml_idx(), and name.
Referenced by ezxml_get().
Variable Documentation
char* EZXML_NIL[] = { NULL }
Referenced by ezxml_add_child(), ezxml_free_attr(), ezxml_internal_dtd(), ezxml_new(), ezxml_parse_str(), ezxml_pi(), and ezxml_set_attr().