navit: support/glib/fake.c File Reference
fake.c File Reference
#include "fake.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "gmem.h"
#include "gthreadprivate.h"
#include "glib.h"
#include "galias.h"
#include <stdio.h>
Functions
char * g_convert (const char *in, int len, const char *to_codeset, const char *from_codeset, int *bytes_read, int *bytes_written, void **error)
pthread_mutex_t * g_mutex_new_navit (void)
GPrivate g_private_new_navit ()
void g_get_current_time (GTimeVal *result)
gchar * g_utf8_casefold (const gchar *s, gssize len)
Function Documentation
char* g_convert (const char * in, int len, const char * to_codeset, const char * from_codeset, int * bytes_read, int * bytes_written, void ** error)
References g_strdup().
Referenced by garmin_object_label(), map_convert_string_tmp(), map_new_csv(), map_search_new(), and save_map_csv().
void g_get_current_time (GTimeVal * result)
g_get_current_time:
Returns
: GTimeVal structure in which to store current time.
Equivalent to the UNIX gettimeofday() function, but portable.
References G_GINT64_CONSTANT, g_return_if_fail, gettimeofday(), guint64, NULL, timeval::tv_sec, _GTimeVal::tv_sec, timeval::tv_usec, and _GTimeVal::tv_usec.
Referenced by magazine_cache_update_stamp().
pthread_mutex_t* g_mutex_new_navit (void)
References NULL.
GPrivate g_private_new_navit ()
References fprintf(), key, NULL, and printf().
gchar* g_utf8_casefold (const gchar * s, gssize len)
References g_ascii_strdown().
Referenced by navit_utf8_strcasecmp().