navit: fib-1.1/fib.c File Reference
fib.c File Reference
#include <fib.h>
#include <fibpriv.h>
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
Macros
#define swap(type, a, b)
#define INT_BITS (sizeof(int) * 8)
Functions
static int ceillog2 (unsigned int a)
static void fh_deleteel (struct fibheap *h, struct fibheap_el *x)
static void fh_initheap (struct fibheap *new)
static void fh_destroyheap (struct fibheap *h)
struct fibheap * fh_makekeyheap ()
struct fibheap * fh_makeheap ()
voidcmp fh_setcmp (struct fibheap *h, voidcmp fnct)
void * fh_setneginf (struct fibheap *h, void *data)
struct fibheap * fh_union (struct fibheap *ha, struct fibheap *hb)
void fh_deleteheap (struct fibheap *h)
struct fibheap_el * fh_insertkey (struct fibheap *h, int key, void *data)
int fh_minkey (struct fibheap *h)
int fh_replacekey (struct fibheap *h, struct fibheap_el *x, int key)
void * fh_replacekeydata (struct fibheap *h, struct fibheap_el *x, int key, void *data)
struct fibheap_el * fh_insert (struct fibheap *h, void *data)
void * fh_min (struct fibheap *h)
void * fh_extractmin (struct fibheap *h)
void * fh_replacedata (struct fibheap *h, struct fibheap_el *x, void *data)
void * fh_delete (struct fibheap *h, struct fibheap_el *x)
static struct fibheap_el * fh_extractminel (struct fibheap *h)
static void fh_insertrootlist (struct fibheap *h, struct fibheap_el *x)
static void fh_removerootlist (struct fibheap *h, struct fibheap_el *x)
static void fh_consolidate (struct fibheap *h)
static void fh_heaplink (struct fibheap *h, struct fibheap_el *y, struct fibheap_el *x)
static void fh_cut (struct fibheap *h, struct fibheap_el *x, struct fibheap_el *y)
static void fh_cascading_cut (struct fibheap *h, struct fibheap_el *y)
static struct fibheap_el * fhe_newelem ()
static void fhe_initelem (struct fibheap_el *e)
static void fhe_insertafter (struct fibheap_el *a, struct fibheap_el *b)
static void fhe_insertbefore (struct fibheap_el *a, struct fibheap_el *b)
static struct fibheap_el * fhe_remove (struct fibheap_el *x)
static void fh_checkcons (struct fibheap *h)
static int fh_compare (struct fibheap *h, struct fibheap_el *a, struct fibheap_el *b)
static int fh_comparedata (struct fibheap *h, int key, void *data, struct fibheap_el *b)
static void fh_insertel (struct fibheap *h, struct fibheap_el *x)
Macro Definition Documentation
#define INT_BITS (sizeof(int) * 8)
Referenced by ceillog2().
#define swap (type, a, b)
Value:
do {                    \
            type c;              \
            c = a;               \
                        a = b;          \
                        b = c;          \
                } while (0)             \
Referenced by fh_consolidate().
Function Documentation
static int ceillog2 (unsigned int a) static
References i, and INT_BITS.
Referenced by fh_checkcons().
static void fh_cascading_cut (struct fibheap * h, struct fibheap_el * y) static
References fh_cut(), fibheap_el::fhe_mark, fibheap_el::fhe_p, and NULL.
Referenced by fh_replacekeydata().
static void fh_checkcons (struct fibheap * h) static
References abort(), ceillog2(), fibheap::fh_cons, fibheap::fh_Dl, fibheap::fh_n, and NULL.
Referenced by fh_consolidate().
static int fh_compare (struct fibheap * h, struct fibheap_el * a, struct fibheap_el * b) static
References fibheap::fh_cmp_fnct, fibheap::fh_keys, fibheap_el::fhe_data, and fibheap_el::fhe_key.
Referenced by fh_comparedata(), fh_consolidate(), fh_replacekeydata(), and fh_union().
static int fh_comparedata (struct fibheap * h, int key, void * data, struct fibheap_el * b) static
References data, fh_compare(), fibheap_el::fhe_data, fibheap_el::fhe_key, and key.
Referenced by fh_replacekeydata().
static void fh_consolidate (struct fibheap * h) static
References D, fh_checkcons(), fh_compare(), fibheap::fh_cons, fibheap::fh_Dl, fh_heaplink(), fh_insertrootlist(), fibheap::fh_min, fh_removerootlist(), fibheap::fh_root, fibheap_el::fhe_degree, i, NULL, and swap.
Referenced by fh_extractminel().
static void fh_cut (struct fibheap * h, struct fibheap_el * x, struct fibheap_el * y) static
References fh_insertrootlist(), fibheap_el::fhe_degree, fibheap_el::fhe_mark, fibheap_el::fhe_p, fhe_remove(), and NULL.
Referenced by fh_cascading_cut(), and fh_replacekeydata().
void* fh_delete (struct fibheap * h, struct fibheap_el * x)
References fh_extractmin(), fibheap::fh_keys, fibheap::fh_neginf, fh_replacedata(), fh_replacekey(), and fibheap_el::fhe_data.
Referenced by main().
static void fh_deleteel (struct fibheap * h, struct fibheap_el * x) static
References abort(), data, fh_extractminel(), fibheap::fh_keys, fibheap::fh_neginf, fh_replacedata(), fh_replacekey(), fibheap_el::fhe_data, fibheap_el::fhe_key, and key.
Referenced by fh_replacekeydata().
void fh_deleteheap (struct fibheap * h)
References fh_destroyheap(), fh_extractminel(), fibheap::fh_min, fhe_destroy, and NULL.
Referenced by gui_internal_cmd_pois(), main(), and route_graph_flood().
static void fh_destroyheap (struct fibheap * h) static
References fibheap::fh_cmp_fnct, fibheap::fh_cons, fibheap::fh_neginf, and NULL.
Referenced by fh_deleteheap(), and fh_union().
void* fh_extractmin (struct fibheap * h)
References fh_extractminel(), fibheap::fh_min, fibheap_el::fhe_data, fhe_destroy, and NULL.
Referenced by fh_delete(), gui_internal_cmd_pois(), main(), and route_graph_flood().
static struct fibheap_el* fh_extractminel (struct fibheap * h) static
References fh_consolidate(), fh_insertrootlist(), fibheap::fh_min, fibheap::fh_n, fh_removerootlist(), fibheap_el::fhe_child, fibheap_el::fhe_p, fibheap_el::fhe_right, and NULL.
Referenced by fh_deleteel(), fh_deleteheap(), and fh_extractmin().
static void fh_heaplink (struct fibheap * h, struct fibheap_el * y, struct fibheap_el * x) static
References fibheap_el::fhe_child, fibheap_el::fhe_degree, fhe_insertbefore(), fibheap_el::fhe_mark, fibheap_el::fhe_p, and NULL.
Referenced by fh_consolidate().
static void fh_initheap (struct fibheap * new) static
References NULL.
Referenced by fh_makeheap(), and fh_makekeyheap().
struct fibheap_el* fh_insert (struct fibheap * h, void * data)
References data, fh_insertel(), fibheap_el::fhe_data, fhe_newelem(), and NULL.
Referenced by main().
static void fh_insertel (struct fibheap * h, struct fibheap_el * x) static
References fibheap::fh_cmp_fnct, fh_insertrootlist(), fibheap::fh_keys, fibheap::fh_min, fibheap::fh_n, fibheap_el::fhe_data, fibheap_el::fhe_key, and NULL.
Referenced by fh_insert(), fh_insertkey(), and fh_replacekeydata().
struct fibheap_el* fh_insertkey (struct fibheap * h, int key, void * data)
References data, fh_insertel(), fibheap_el::fhe_data, fibheap_el::fhe_key, fhe_newelem(), key, and NULL.
Referenced by gui_internal_cmd_pois(), main(), and route_graph_flood().
static void fh_insertrootlist (struct fibheap * h, struct fibheap_el * x) static
References fibheap::fh_root, fhe_insertafter(), fibheap_el::fhe_left, fibheap_el::fhe_right, and NULL.
Referenced by fh_consolidate(), fh_cut(), fh_extractminel(), and fh_insertel().
struct fibheap* fh_makeheap (void)
References fh_initheap(), and NULL.
Referenced by main().
struct fibheap* fh_makekeyheap (void)
References fh_initheap(), fibheap::fh_keys, and NULL.
Referenced by gui_internal_cmd_pois(), main(), and route_graph_flood().
void* fh_min (struct fibheap * h)
References fibheap::fh_min, fibheap_el::fhe_data, and NULL.
int fh_minkey (struct fibheap * h)
References fibheap::fh_min, fibheap_el::fhe_key, and NULL.
Referenced by gui_internal_cmd_pois(), and main().
static void fh_removerootlist (struct fibheap * h, struct fibheap_el * x) static
References fibheap::fh_root, fibheap_el::fhe_left, fhe_remove(), and NULL.
Referenced by fh_consolidate(), and fh_extractminel().
void* fh_replacedata (struct fibheap * h, struct fibheap_el * x, void * data)
References fh_replacekeydata(), and fibheap_el::fhe_key.
Referenced by fh_delete(), and fh_deleteel().
int fh_replacekey (struct fibheap * h, struct fibheap_el * x, int key)
References fh_replacekeydata(), fibheap_el::fhe_data, fibheap_el::fhe_key, and void().
Referenced by fh_delete(), fh_deleteel(), main(), and route_graph_flood().
void* fh_replacekeydata (struct fibheap * h, struct fibheap_el * x, int key, void * data)
References abort(), data, fh_cascading_cut(), fh_compare(), fh_comparedata(), fh_cut(), fh_deleteel(), fh_insertel(), fibheap::fh_keys, fibheap::fh_min, fibheap_el::fhe_data, fibheap_el::fhe_key, fibheap_el::fhe_p, key, NULL, and printf().
Referenced by fh_replacedata(), and fh_replacekey().
voidcmp fh_setcmp (struct fibheap * h, voidcmp fnct)
References fibheap::fh_cmp_fnct.
Referenced by main().
void* fh_setneginf (struct fibheap * h, void * data)
References data, and fibheap::fh_neginf.
struct fibheap* fh_union (struct fibheap * ha, struct fibheap * hb)
References fh_compare(), fh_destroyheap(), fibheap::fh_min, fibheap::fh_n, fibheap::fh_root, fibheap_el::fhe_left, fibheap_el::fhe_right, and NULL.
static void fhe_initelem (struct fibheap_el * e) static
References fibheap_el::fhe_child, fibheap_el::fhe_data, fibheap_el::fhe_degree, fibheap_el::fhe_left, fibheap_el::fhe_mark, fibheap_el::fhe_p, fibheap_el::fhe_right, and NULL.
Referenced by fhe_newelem().
static void fhe_insertafter (struct fibheap_el * a, struct fibheap_el * b) static
References fibheap_el::fhe_left, and fibheap_el::fhe_right.
Referenced by fh_insertrootlist(), and fhe_insertbefore().
static void fhe_insertbefore (struct fibheap_el * a, struct fibheap_el * b) static
References fhe_insertafter(), and fibheap_el::fhe_left.
Referenced by fh_heaplink().
static struct fibheap_el* fhe_newelem (void) static
References fhe_initelem(), and NULL.
Referenced by fh_insert(), and fh_insertkey().
static struct fibheap_el* fhe_remove (struct fibheap_el * x) static
References fibheap_el::fhe_child, fibheap_el::fhe_left, fibheap_el::fhe_p, fibheap_el::fhe_right, and NULL.
Referenced by fh_cut(), and fh_removerootlist().