navit: fib-1.1/fib.h File Reference
fib.h File Reference
Typedefs
typedef int(* voidcmp) (void *, void *)
Functions
struct fibheap * fh_makekeyheap (void)
struct fibheap_el * fh_insertkey (struct fibheap *, int, void *)
int fh_minkey (struct fibheap *)
int fh_replacekey (struct fibheap *, struct fibheap_el *, int)
void * fh_replacekeydata (struct fibheap *, struct fibheap_el *, int, void *)
struct fibheap * fh_makeheap (void)
voidcmp fh_setcmp (struct fibheap *, voidcmp)
void * fh_setneginf (struct fibheap *, void *)
struct fibheap_el * fh_insert (struct fibheap *, void *)
void * fh_extractmin (struct fibheap *)
void * fh_min (struct fibheap *)
void * fh_replacedata (struct fibheap *, struct fibheap_el *, void *)
void * fh_delete (struct fibheap *, struct fibheap_el *)
void fh_deleteheap (struct fibheap *)
struct fibheap * fh_union (struct fibheap *, struct fibheap *)
Typedef Documentation
voidcmp
typedef int(* voidcmp) (void *, void *)
Function Documentation
fh_delete()
void* fh_delete (struct fibheap * h, struct fibheap_el * x)
References fh_extractmin(), fibheap::fh_keys, fibheap::fh_neginf, fh_replacedata(), fh_replacekey(), and fibheap_el::fhe_data.
Referenced by main(), and route_graph_point_update().
fh_deleteheap()
void fh_deleteheap (struct fibheap * h)
References fh_destroyheap(), fh_extractminel(), fibheap::fh_min, and fhe_destroy.
Referenced by gui_internal_cmd_pois(), main(), route_graph_destroy(), and traffic_route_flood_graph().
fh_extractmin()
void* fh_extractmin (struct fibheap * h)
References fh_extractminel(), fibheap::fh_min, fibheap_el::fhe_data, and fhe_destroy.
Referenced by fh_delete(), gui_internal_cmd_pois(), main(), route_graph_compute_shortest_path(), route_graph_reset(), and traffic_route_flood_graph().
fh_insert()
struct fibheap_el* fh_insert (struct fibheap * h, void * data)
References data, fh_insertel(), fibheap_el::fhe_data, and fhe_newelem().
Referenced by main().
fh_insertkey()
struct fibheap_el* fh_insertkey (struct fibheap * h, int key, void * data)
References data, fh_insertel(), fibheap_el::fhe_data, fibheap_el::fhe_key, fhe_newelem(), and key.
Referenced by gui_internal_cmd_pois(), main(), route_graph_init(), route_graph_point_update(), and traffic_route_flood_graph().
fh_makeheap()
struct fibheap* fh_makeheap (void)
References fh_initheap().
Referenced by main().
fh_makekeyheap()
struct fibheap* fh_makekeyheap (void)
References fh_initheap(), and fibheap::fh_keys.
Referenced by gui_internal_cmd_pois(), main(), route_graph_build(), and traffic_route_flood_graph().
fh_min()
void* fh_min (struct fibheap * h)
References fibheap::fh_min, and fibheap_el::fhe_data.
Referenced by route_graph_is_path_computed().
fh_minkey()
int fh_minkey (struct fibheap * h)
References fibheap::fh_min, and fibheap_el::fhe_key.
Referenced by gui_internal_cmd_pois(), and main().
fh_replacedata()
void* fh_replacedata (struct fibheap * h, struct fibheap_el * x, void * data)
References data, fh_replacekeydata(), and fibheap_el::fhe_key.
Referenced by fh_delete(), and fh_deleteel().
fh_replacekey()
int fh_replacekey (struct fibheap * h, struct fibheap_el * x, int key)
References fh_replacekeydata(), fibheap_el::fhe_data, fibheap_el::fhe_key, and key.
Referenced by fh_delete(), fh_deleteel(), main(), and traffic_route_flood_graph().
fh_replacekeydata()
void* fh_replacekeydata (struct fibheap * h, struct fibheap_el * x, int key, void * data)
References data, fh_cascading_cut(), fh_compare(), fh_comparedata(), fh_cut(), fh_deleteel(), fh_insertel(), fibheap::fh_keys, fibheap::fh_min, fibheap_el::fhe_data, fibheap_el::fhe_key, fibheap_el::fhe_p, and key.
Referenced by fh_replacedata(), and fh_replacekey().
fh_setcmp()
voidcmp fh_setcmp (struct fibheap * h, voidcmp fnct)
References fibheap::fh_cmp_fnct.
Referenced by main().
fh_setneginf()
void* fh_setneginf (struct fibheap * h, void * data)
References data, and fibheap::fh_neginf.
fh_union()
struct fibheap* fh_union (struct fibheap * ha, struct fibheap * hb)
References fh_compare(), fh_destroyheap(), fibheap::fh_min, fibheap::fh_n, fibheap::fh_root, fibheap_el::fhe_left, and fibheap_el::fhe_right.