navit: fib-1.1/fibtest2.c File Reference
fibtest2.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "fib.h"
Functions
int main (void)
Function Documentation
int main (void)
References fh_deleteheap(), fh_extractmin(), fh_insertkey(), fh_makekeyheap(), fh_minkey(), fh_replacekey(), i, and printf().