navit: support/espeak/fifo.h File Reference
fifo.h File Reference
#include "espeak_command.h"
#include "speak_lib.h"
Functions
void fifo_init ()
espeak_ERROR fifo_add_command (t_espeak_command *c)
espeak_ERROR fifo_add_commands (t_espeak_command *c1, t_espeak_command *c2)
espeak_ERROR fifo_stop ()
int fifo_is_busy ()
void fifo_terminate ()
int fifo_is_command_enabled ()
Function Documentation
espeak_ERROR fifo_add_command (t_espeak_command * c)
Referenced by espeak_Char(), espeak_Key(), espeak_SetParameter(), espeak_SetPunctuationList(), espeak_SetVoiceByName(), and espeak_SetVoiceByProperties().
espeak_ERROR fifo_add_commands (t_espeak_command * c1, t_espeak_command * c2)
Referenced by espeak_Synth(), and espeak_Synth_Mark().
void fifo_init ()
Referenced by espeak_Initialize().
int fifo_is_busy ()
Referenced by espeak_IsPlaying().
int fifo_is_command_enabled ()
Referenced by select_output().
espeak_ERROR fifo_stop ()
Referenced by espeak_Cancel(), and espeak_Terminate().
void fifo_terminate ()
Referenced by espeak_Terminate().