navit: maptool/generated-code/fileformat.pb-c.h File Reference
fileformat.pb-c.h File Reference
#include <google/protobuf-c/protobuf-c.h>
Data Structures
struct _OSMPBF__Blob
struct _OSMPBF__BlobHeader
Macros
#define OSMPBF__BLOB__INIT
#define OSMPBF__BLOB_HEADER__INIT
Typedefs
typedef typedefPROTOBUF_C_BEGIN_DECLS struct _OSMPBF__Blob OSMPBF__Blob
typedef struct _OSMPBF__BlobHeader OSMPBF__BlobHeader
typedef void(* OSMPBF__Blob_Closure) (const OSMPBF__Blob *message, void *closure_data)
typedef void(* OSMPBF__BlobHeader_Closure) (const OSMPBF__BlobHeader *message, void *closure_data)
Functions
void osmpbf__blob__init (OSMPBF__Blob *message)
size_t osmpbf__blob__get_packed_size (const OSMPBF__Blob *message)
size_t osmpbf__blob__pack (const OSMPBF__Blob *message, uint8_t *out)
size_t osmpbf__blob__pack_to_buffer (const OSMPBF__Blob *message, ProtobufCBuffer *buffer)
OSMPBF__Blob * osmpbf__blob__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__blob__free_unpacked (OSMPBF__Blob *message, ProtobufCAllocator *allocator)
void osmpbf__blob_header__init (OSMPBF__BlobHeader *message)
size_t osmpbf__blob_header__get_packed_size (const OSMPBF__BlobHeader *message)
size_t osmpbf__blob_header__pack (const OSMPBF__BlobHeader *message, uint8_t *out)
size_t osmpbf__blob_header__pack_to_buffer (const OSMPBF__BlobHeader *message, ProtobufCBuffer *buffer)
OSMPBF__BlobHeader * osmpbf__blob_header__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__blob_header__free_unpacked (OSMPBF__BlobHeader *message, ProtobufCAllocator *allocator)
Variables
const ProtobufCMessageDescriptor osmpbf__blob__descriptor
const ProtobufCMessageDescriptor osmpbf__blob_header__descriptor
Macro Definition Documentation
OSMPBF__BLOB__INIT
#define OSMPBF__BLOB__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__blob__descriptor) \
    , 0,{0,NULL}, 0,0, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL} }
Referenced by osm_protobufdb_finish_block(), and osmpbf__blob__init().
OSMPBF__BLOB_HEADER__INIT
#define OSMPBF__BLOB_HEADER__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__blob_header__descriptor) \
    , NULL, 0,{0,NULL}, 0 }
Referenced by osm_protobufdb_write_blob(), and osmpbf__blob_header__init().
Typedef Documentation
OSMPBF__Blob
typedef typedefPROTOBUF_C_BEGIN_DECLS struct _OSMPBF__Blob OSMPBF__Blob
OSMPBF__Blob_Closure
typedef void(* OSMPBF__Blob_Closure) (const OSMPBF__Blob *message, void *closure_data)
OSMPBF__BlobHeader
typedef struct _OSMPBF__BlobHeader OSMPBF__BlobHeader
OSMPBF__BlobHeader_Closure
typedef void(* OSMPBF__BlobHeader_Closure) (const OSMPBF__BlobHeader *message, void *closure_data)
Function Documentation
osmpbf__blob__free_unpacked()
void osmpbf__blob__free_unpacked (OSMPBF__Blob * message, ProtobufCAllocator * allocator)
References osmpbf__blob__descriptor, osmpbf__blob_header__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by map_collect_data_osm_protobuf(), osm_protobufdb_finish_block(), and osmpbf__blob__unpack().
osmpbf__blob__get_packed_size()
size_t osmpbf__blob__get_packed_size (const OSMPBF__Blob * message)
References osmpbf__blob__descriptor, osmpbf__blob__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_write_blob(), and osmpbf__blob__init().
osmpbf__blob__init()
void osmpbf__blob__init (OSMPBF__Blob * message)
References osmpbf__blob__get_packed_size(), and OSMPBF__BLOB__INIT.
osmpbf__blob__pack()
size_t osmpbf__blob__pack (const OSMPBF__Blob * message, uint8_t * out)
References osmpbf__blob__descriptor, osmpbf__blob__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_write_blob(), and osmpbf__blob__get_packed_size().
osmpbf__blob__pack_to_buffer()
size_t osmpbf__blob__pack_to_buffer (const OSMPBF__Blob * message, ProtobufCBuffer * buffer)
References osmpbf__blob__descriptor, osmpbf__blob__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__blob__pack().
osmpbf__blob__unpack()
OSMPBF__Blob* osmpbf__blob__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__blob__descriptor, osmpbf__blob__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__blob__pack_to_buffer(), and read_blob().
osmpbf__blob_header__free_unpacked()
void osmpbf__blob_header__free_unpacked (OSMPBF__BlobHeader * message, ProtobufCAllocator * allocator)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by map_collect_data_osm_protobuf(), and osmpbf__blob_header__unpack().
osmpbf__blob_header__get_packed_size()
size_t osmpbf__blob_header__get_packed_size (const OSMPBF__BlobHeader * message)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, osmpbf__blob_header__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_write_blob(), and osmpbf__blob_header__init().
osmpbf__blob_header__init()
void osmpbf__blob_header__init (OSMPBF__BlobHeader * message)
References osmpbf__blob_header__get_packed_size(), and OSMPBF__BLOB_HEADER__INIT.
Referenced by osmpbf__blob__free_unpacked().
osmpbf__blob_header__pack()
size_t osmpbf__blob_header__pack (const OSMPBF__BlobHeader * message, uint8_t * out)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, osmpbf__blob_header__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_write_blob(), and osmpbf__blob_header__get_packed_size().
osmpbf__blob_header__pack_to_buffer()
size_t osmpbf__blob_header__pack_to_buffer (const OSMPBF__BlobHeader * message, ProtobufCBuffer * buffer)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, osmpbf__blob_header__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__blob_header__pack().
osmpbf__blob_header__unpack()
OSMPBF__BlobHeader* osmpbf__blob_header__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__blob_header__descriptor, osmpbf__blob_header__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__blob_header__pack_to_buffer(), and read_header().
Variable Documentation
osmpbf__blob__descriptor
const ProtobufCMessageDescriptor osmpbf__blob__descriptor
Referenced by osmpbf__blob__free_unpacked(), osmpbf__blob__get_packed_size(), osmpbf__blob__pack(), osmpbf__blob__pack_to_buffer(), and osmpbf__blob__unpack().
osmpbf__blob_header__descriptor
const ProtobufCMessageDescriptor osmpbf__blob_header__descriptor
Referenced by osmpbf__blob_header__free_unpacked(), osmpbf__blob_header__get_packed_size(), osmpbf__blob_header__pack(), osmpbf__blob_header__pack_to_buffer(), and osmpbf__blob_header__unpack().