navit: file.h File Reference
file.h File Reference
#include <time.h>
#include "param.h"
#include <stdio.h>
Data Structures
struct file
Macros
#define PATH_MAX 4096
Functions
int file_request (struct file *f, struct attr **options)
char * file_http_header (struct file *f, char *header)
struct file * file_create (char *name, struct attr **options)
int file_is_dir (char *name)
long long file_size (struct file *file)
int file_mkdir (char *name, int pflag)
int file_mmap (struct file *file)
unsigned char * file_data_read (struct file *file, long long offset, int size)
unsigned char * file_data_read_special (struct file *file, int size, int *size_ret)
unsigned char * file_data_read_all (struct file *file)
void file_data_flush (struct file *file, long long offset, int size)
int file_data_write (struct file *file, long long offset, int size, const void *data)
int file_get_contents (char *name, unsigned char **buffer, int *size)
unsigned char * file_data_read_compressed (struct file *file, long long offset, int size, int size_uncomp)
void file_data_free (struct file *file, unsigned char *data)
int file_exists (char const *name)
void file_remap_readonly (struct file *f)
void file_unmap (struct file *f)
void * file_opendir (char *dir)
char * file_readdir (void *hnd)
void file_closedir (void *hnd)
struct file * file_create_caseinsensitive (char *name, struct attr **options)
void file_fsync (struct file *f)
void file_destroy (struct file *f)
struct file_wordexp * file_wordexp_new (const char *pattern)
int file_wordexp_get_count (struct file_wordexp *wexp)
char ** file_wordexp_get_array (struct file_wordexp *wexp)
void file_wordexp_destroy (struct file_wordexp *wexp)
int file_get_param (struct file *file, struct param_list *param, int count)
int file_version (struct file *file, int byname)
void * file_get_os_handle (struct file *file)
int file_set_cache_size (int cache_size)
void file_init (void)
int file_is_reg (char *name)
void file_data_remove (struct file *file, unsigned char *data)
Macro Definition Documentation
#define PATH_MAX 4096
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
You should have received a copy of the GNU Library General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by gmap_new(), and main_init().
Function Documentation
void file_closedir (void * hnd)
Referenced by file_create_caseinsensitive(), and speechd_new().
struct file* file_create (char * name, struct attr ** options)
References atom(), attr_search(), file::cache, dbg, dbg_assert, file::fd, file, g_free(), g_new0, g_strdup(), long, LONGLONG_FMT, lseek(), lvl_debug, file::name, file::name_id, NULL, attr::num, O_BINARY, O_CREAT, O_LARGEFILE, O_RDONLY, O_RDWR, O_TRUNC, open(), SEEK_END, file::size, and attr::u.
Referenced by ch_setup(), download(), file_create_caseinsensitive(), file_get_contents(), map_binfile_http_request(), map_binfile_open(), map_binfile_zip_setup(), map_rect_new_shapefile(), and vehicle_file_destroy().
struct file* file_create_caseinsensitive (char * name, struct attr ** options)
References dirname, file_closedir(), file_create(), file_opendir(), file_readdir(), filename, g_alloca, g_ascii_strcasecmp(), and p.
Referenced by map_new_mg(), tree_search_hv(), and tree_search_init().
void file_data_flush (struct file * file, long long offset, int size)
References file::cache, cache_flush(), dbg, LONGLONG_FMT, lvl_debug, file::name_id, offset, and size.
Referenced by download_finish(), and file_data_write().
void file_data_free (struct file * file, unsigned char * data)
References file::begin, file::cache, cache_entry_destroy(), and g_free().
Referenced by binfile_extract(), binfile_read_cd(), binfile_read_eoc(), binfile_read_eoc64(), binfile_read_lfh(), binfile_search_cd(), download_cd(), file_data_read(), map_binfile_close(), map_binfile_open(), map_binfile_zip_setup(), map_download_selection(), map_rect_destroy_binfile(), map_rect_new_shapefile(), pop_tile(), push_zipfile_tile_do(), and zipfile_to_tile().
unsigned char* file_data_read (struct file * file, long long offset, int size)
References file::begin, file::cache, cache_insert_new(), cache_lookup(), file::fd, file_data_free(), g_malloc(), lseek(), file::name_id, NULL, offset, read(), SEEK_SET, size, and file::special.
Referenced by binfile_read_cd(), binfile_read_content(), binfile_read_eoc(), binfile_read_eoc64(), binfile_read_lfh(), binfile_search_cd(), ch_setup(), download_cd(), download_finish(), download_start(), file_data_read_all(), map_binfile_open(), map_rect_new_binfile(), push_zipfile_tile(), and zipfile_to_tile().
unsigned char* file_data_read_all (struct file * file)
References file_data_read(), and file::size.
Referenced by file_get_contents(), and map_rect_new_shapefile().
unsigned char* file_data_read_compressed (struct file * file, long long offset, int size, int size_uncomp)
References file::cache, cache_insert_new(), cache_lookup(), dbg, file::fd, g_free(), g_malloc(), lseek(), lvl_error, file::name_id, NULL, offset, read(), SEEK_SET, size, uncompress_int(), and Z_OK.
Referenced by binfile_read_content().
unsigned char* file_data_read_special (struct file * file, int size, int * size_ret)
References file::buffer, file::buffer_len, buffer_size, dbg, eof(), file::fd, file_http_header(), file_http_header_end(), file_process_headers(), file_shift_buffer(), g_malloc(), lvl_debug, NULL, read(), file::requests, size, and file::special.
Referenced by download_directory_do(), download_download(), map_binfile_download_range(), and map_binfile_download_size().
void file_data_remove (struct file * file, unsigned char * data)
References file::begin, file::cache, cache_flush_data(), and g_free().
Referenced by download_finish(), and download_start().
int file_data_write (struct file * file, long long offset, int size, const void * data)
References file::fd, file_data_flush(), lseek(), SEEK_SET, file::size, size, and write().
Referenced by download_directory_do(), download_download(), download_finish(), download_initial_finish(), and vehicle_file_destroy().
void file_destroy (struct file * f)
References file::begin, file::buffer, close(), file::fd, file_unmap(), g_free(), g_hash_table_destroy(), file::headers, file::name, NULL, and file::special.
Referenced by file_get_contents(), map_binfile_close(), map_binfile_handle_redirect(), map_binfile_http_close(), map_binfile_open(), map_destroy_mg(), map_rect_new_shapefile(), tree_search_free(), tree_search_hv(), and vehicle_file_destroy().
int file_exists (char const * name)
References stat().
Referenced by espeak_new(), expand_filenames(), main_init(), main_real(), navit_get_user_data_directory(), plugin_new(), vehicle_file_new_file(), and xinclude().
void file_fsync (struct file * f)
References file::fd.
Referenced by vehicle_file_destroy().
int file_get_contents (char * name, unsigned char ** buffer, int * size)
References file::cache, file, file_create(), file_data_read_all(), file_destroy(), and file_size().
Referenced by gui_internal_setup(), image_new_helper(), item_bin_sort_file(), and vehicle_file_io().
void* file_get_os_handle (struct file * file)
References file::fd, and GINT_TO_POINTER.
int file_get_param (struct file * file, struct param_list * param, int count)
char* file_http_header (struct file * f, char * header)
References g_hash_table_lookup(), file::headers, and NULL.
Referenced by file_data_read_special(), and map_binfile_handle_redirect().
void file_init (void)
References cache_new(), dbg, g_hash_table_new(), g_str_equal(), g_str_hash(), and lvl_error.
Referenced by add_plugin(), and main_real().
int file_is_dir (char * name)
References S_ISDIR, stat::st_mode, and stat().
Referenced by file_mkdir().
int file_is_reg (char * name)
References S_ISREG, stat::st_mode, and stat().
Referenced by vehicle_file_open().
int file_mkdir (char * name, int pflag)
References buffer, dbg, file_is_dir(), file_mkdir(), g_alloca, lvl_debug, mkdir(), and next.
Referenced by binfile_extract(), file_mkdir(), log_open(), and navit_get_user_data_directory().
int file_mmap (struct file * file)
References file::begin, dbg_assert, file::end, file::fd, file::mmap_end, mmap_readonly_win32(), file::name, NULL, perror(), and file::size.
Referenced by ch_setup(), map_binfile_open(), map_binfile_zip_setup(), map_new_mg(), tree_search_hv(), and tree_search_init().
void* file_opendir (char * dir)
Referenced by file_create_caseinsensitive(), and speechd_new().
char* file_readdir (void * hnd)
References NULL.
Referenced by file_create_caseinsensitive(), and speechd_new().
void file_remap_readonly (struct file * f)
References file::begin, file::fd, printf(), and file::size.
int file_request (struct file * f, struct attr ** options)
Referenced by map_binfile_http_request().
int file_set_cache_size (int cache_size)
References cache_resize().
Referenced by config_set_attr_int().
long long file_size (struct file * file)
References file::size.
Referenced by ch_setup(), download_start(), file_get_contents(), map_binfile_download_size(), and map_rect_new_shapefile().
void file_unmap (struct file * f)
References file::begin, mmap_unmap_win32(), and file::size.
Referenced by file_destroy().
int file_version (struct file * file, int byname)
References file::begin, file::ctime, dbg, file::end, file::fd, fstat(), lseek(), lvl_debug, file::mmap_end, file::mtime, file::name, SEEK_END, file::size, size, stat::st_ctime, stat::st_mtime, stat(), and file::version.
Referenced by binfile_check_version(), and map_binfile_open().
void file_wordexp_destroy (struct file_wordexp * wexp)
References file_wordexp::err, g_free(), file_wordexp::pattern, file_wordexp::we, and wordfree().
Referenced by graphics_icon_path(), graphics_image_new_scaled_rotated(), log_new(), map_new_binfile(), map_new_csv(), map_new_mg(), map_new_shapefile(), map_new_textfile(), maps_new(), osd_gps_status_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_volume_new(), plugin_new(), and xinclude().
char** file_wordexp_get_array (struct file_wordexp * wexp)
References file_wordexp::err, file_wordexp::pattern, file_wordexp::we, and wordexp_t::we_wordv.
Referenced by graphics_icon_path(), graphics_image_new_scaled_rotated(), log_new(), map_new_binfile(), map_new_csv(), map_new_mg(), map_new_shapefile(), map_new_textfile(), maps_new(), osd_gps_status_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_volume_new(), plugin_new(), and xinclude().
int file_wordexp_get_count (struct file_wordexp * wexp)
References file_wordexp::err, file_wordexp::we, and wordexp_t::we_wordc.
Referenced by graphics_icon_path(), graphics_image_new_scaled_rotated(), log_new(), maps_new(), plugin_new(), and xinclude().
struct file_wordexp* file_wordexp_new (const char * pattern)
References dbg, file_wordexp::err, g_new0, g_strdup(), lvl_debug, file_wordexp::pattern, file_wordexp::we, and wordexp().
Referenced by graphics_icon_path(), graphics_image_new_scaled_rotated(), log_new(), map_new_binfile(), map_new_csv(), map_new_mg(), map_new_shapefile(), map_new_textfile(), maps_new(), osd_gps_status_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_volume_new(), plugin_new(), and xinclude().