navit: maptool/generated-code/fileformat.pb-c.c File Reference
fileformat.pb-c.c File Reference
#include "fileformat.pb-c.h"
Macros
#define PROTOBUF_C_NO_DEPRECATED
Functions
void osmpbf__blob__init (OSMPBF__Blob *message)
size_t osmpbf__blob__get_packed_size (const OSMPBF__Blob *message)
size_t osmpbf__blob__pack (const OSMPBF__Blob *message, uint8_t *out)
size_t osmpbf__blob__pack_to_buffer (const OSMPBF__Blob *message, ProtobufCBuffer *buffer)
OSMPBF__Blob * osmpbf__blob__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__blob__free_unpacked (OSMPBF__Blob *message, ProtobufCAllocator *allocator)
void osmpbf__blob_header__init (OSMPBF__BlobHeader *message)
size_t osmpbf__blob_header__get_packed_size (const OSMPBF__BlobHeader *message)
size_t osmpbf__blob_header__pack (const OSMPBF__BlobHeader *message, uint8_t *out)
size_t osmpbf__blob_header__pack_to_buffer (const OSMPBF__BlobHeader *message, ProtobufCBuffer *buffer)
OSMPBF__BlobHeader * osmpbf__blob_header__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__blob_header__free_unpacked (OSMPBF__BlobHeader *message, ProtobufCAllocator *allocator)
Variables
static const
ProtobufCFieldDescriptor osmpbf__blob__field_descriptors [5]
static const unsigned osmpbf__blob__field_indices_by_name []
static const ProtobufCIntRange osmpbf__blob__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__blob__descriptor
static const
ProtobufCFieldDescriptor osmpbf__blob_header__field_descriptors [3]
static const unsigned osmpbf__blob_header__field_indices_by_name []
static const ProtobufCIntRange osmpbf__blob_header__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__blob_header__descriptor
Macro Definition Documentation
#define PROTOBUF_C_NO_DEPRECATED
Function Documentation
void osmpbf__blob__free_unpacked (OSMPBF__Blob * message, ProtobufCAllocator * allocator)
References osmpbf__blob__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by map_collect_data_osm_protobuf(), and osm_protobufdb_finish_block().
size_t osmpbf__blob__get_packed_size (const OSMPBF__Blob * message)
References osmpbf__blob__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_write_blob().
void osmpbf__blob__init (OSMPBF__Blob * message)
References OSMPBF__BLOB__INIT.
size_t osmpbf__blob__pack (const OSMPBF__Blob * message, uint8_t * out)
References osmpbf__blob__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_write_blob().
size_t osmpbf__blob__pack_to_buffer (const OSMPBF__Blob * message, ProtobufCBuffer * buffer)
References osmpbf__blob__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__Blob* osmpbf__blob__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__blob__descriptor, and protobuf_c_message_unpack().
Referenced by read_blob().
void osmpbf__blob_header__free_unpacked (OSMPBF__BlobHeader * message, ProtobufCAllocator * allocator)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by map_collect_data_osm_protobuf().
size_t osmpbf__blob_header__get_packed_size (const OSMPBF__BlobHeader * message)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_write_blob().
void osmpbf__blob_header__init (OSMPBF__BlobHeader * message)
References OSMPBF__BLOB_HEADER__INIT.
size_t osmpbf__blob_header__pack (const OSMPBF__BlobHeader * message, uint8_t * out)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_write_blob().
size_t osmpbf__blob_header__pack_to_buffer (const OSMPBF__BlobHeader * message, ProtobufCBuffer * buffer)
References _OSMPBF__BlobHeader::base, _ProtobufCMessage::descriptor, osmpbf__blob_header__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__BlobHeader* osmpbf__blob_header__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__blob_header__descriptor, and protobuf_c_message_unpack().
Referenced by read_header().
Variable Documentation
const ProtobufCMessageDescriptor osmpbf__blob__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.Blob",
  "Blob",
  "OSMPBF__Blob",
  "OSMPBF",
  sizeof(OSMPBF__Blob),
  5,
  osmpbf__blob__field_descriptors,
  osmpbf__blob__field_indices_by_name,
  1,  osmpbf__blob__number_ranges,
  (ProtobufCMessageInit) osmpbf__blob__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__blob__free_unpacked(), osmpbf__blob__get_packed_size(), osmpbf__blob__pack(), osmpbf__blob__pack_to_buffer(), and osmpbf__blob__unpack().
const ProtobufCFieldDescriptor osmpbf__blob__field_descriptors[5] static
const unsigned osmpbf__blob__field_indices_by_name[] static
Initial value:
= {
  4,
  3,
  0,
  1,
  2,
}
const ProtobufCIntRange osmpbf__blob__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 5 }
}
const ProtobufCMessageDescriptor osmpbf__blob_header__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.BlobHeader",
  "BlobHeader",
  "OSMPBF__BlobHeader",
  "OSMPBF",
  sizeof(OSMPBF__BlobHeader),
  3,
  osmpbf__blob_header__field_descriptors,
  osmpbf__blob_header__field_indices_by_name,
  1,  osmpbf__blob_header__number_ranges,
  (ProtobufCMessageInit) osmpbf__blob_header__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__blob_header__free_unpacked(), osmpbf__blob_header__get_packed_size(), osmpbf__blob_header__pack(), osmpbf__blob_header__pack_to_buffer(), and osmpbf__blob_header__unpack().
const ProtobufCFieldDescriptor osmpbf__blob_header__field_descriptors[3] static
const unsigned osmpbf__blob_header__field_indices_by_name[] static
Initial value:
= {
  2,
  1,
  0,
}
const ProtobufCIntRange osmpbf__blob_header__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 3 }
}