navit: map/filter/filter.c File Reference
filter.c File Reference
#include "attr.h"
#include "config.h"
#include "coord.h"
#include "debug.h"
#include "endianess.h"
#include "file.h"
#include "item.h"
#include "linguistics.h"
#include "map.h"
#include "maptype.h"
#include "plugin.h"
#include "projection.h"
#include "transform.h"
#include "zipfile.h"
#include <glib.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct filter_entry
struct filter
struct map_priv
Represents the map from a single binfile.
struct map_rect_priv
Implementation-specific map rect data.
struct map_search_priv
Represents a search on a map. This struct represents a search on a map; it is created when starting a search, and is used for retrieving results.
Functions
static enum item_type filter_type (struct map_priv *m, struct item *item)
static void free_filter_entry (struct filter_entry *filter, void *user_data)
static void free_filter (struct filter *filter, void *user_data)
static void free_filters (struct map_priv *m)
static GList * parse_filter (char *filter)
static void parse_filters (struct map_priv *m, char *filter)
static void map_filter_coord_rewind (void *priv_data)
static int map_filter_coord_get (void *priv_data, struct coord *c, int count)
static void map_filter_attr_rewind (void *priv_data)
static int map_filter_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static struct map_rect_priv * map_filter_rect_new (struct map_priv *map, struct map_selection *sel)
static void map_filter_rect_destroy (struct map_rect_priv *mr)
static struct item * map_filter_rect_get_item (struct map_rect_priv *mr)
static struct item * map_filter_rect_get_item_byid (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct map_search_priv * map_filter_search_new (struct map_priv *map, struct item *item, struct attr *search, int partial)
static struct item * map_filter_search_get_item (struct map_search_priv *map_search)
static void map_filter_search_destroy (struct map_search_priv *ms)
static void map_filter_destroy (struct map_priv *m)
static int map_filter_set_attr (struct map_priv *m, struct attr *attr)
static struct map_priv * map_filter_new (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
static struct item_methods methods_filter
static struct map_methods map_methods_filter
Function Documentation
filter_type()
static enum item_type filter_type (struct map_priv * m, struct item * item) static
References filter_entry::cond_attr, filter_entry::cond_str, map_priv::filters, item::id_hi, item::id_lo, item_attr_get(), item_attr_rewind(), filter_entry::last, map_rect_priv::m, filter::new, filter::old, attr::str, item::type, and attr::u.
Referenced by map_filter_rect_get_item(), and map_filter_rect_get_item_byid().
free_filter()
static void free_filter (struct filter * filter, void * user_data) static
References free_filter_entry(), filter::new, and filter::old.
Referenced by free_filters().
free_filter_entry()
static void free_filter_entry (struct filter_entry * filter, void * user_data) static
Referenced by free_filter().
free_filters()
static void free_filters (struct map_priv * m) static
References map_priv::filters, and free_filter().
Referenced by parse_filters().
map_filter_attr_get()
static int map_filter_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References item_attr_get(), and map_rect_priv::parent_item.
map_filter_attr_rewind()
static void map_filter_attr_rewind (void * priv_data) static
References item_attr_rewind(), and map_rect_priv::parent_item.
map_filter_coord_get()
static int map_filter_coord_get (void * priv_data, struct coord * c, int count) static
References c, map_rect_priv::count, item_coord_get(), and map_rect_priv::parent_item.
map_filter_coord_rewind()
static void map_filter_coord_rewind (void * priv_data) static
References item_coord_rewind(), and map_rect_priv::parent_item.
map_filter_destroy()
static void map_filter_destroy (struct map_priv * m) static
References map_destroy(), and map_priv::parent.
map_filter_new()
static struct map_priv * map_filter_new (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), attrs, map_methods_filter, map_new(), meth, map_priv::parent, parse_filters(), subtype, and type.
Referenced by plugin_init().
map_filter_rect_destroy()
static void map_filter_rect_destroy (struct map_rect_priv * mr) static
References map_rect_destroy(), and map_rect_priv::parent.
map_filter_rect_get_item()
static struct item * map_filter_rect_get_item (struct map_rect_priv * mr) static
References filter_type(), item::id_hi, item::id_lo, map_rect_priv::item, map_rect_priv::m, map_rect_get_item(), map_rect_priv::parent, map_rect_priv::parent_item, and item::type.
map_filter_rect_get_item_byid()
static struct item * map_filter_rect_get_item_byid (struct map_rect_priv * mr, int id_hi, int id_lo) static
References dbg, filter_type(), item::id_hi, item::id_lo, map_rect_priv::item, lvl_debug, map_rect_priv::m, map_rect_get_item_byid(), map_rect_priv::parent, map_rect_priv::parent_item, and item::type.
map_filter_rect_new()
static struct map_rect_priv * map_filter_rect_new (struct map_priv * map, struct map_selection * sel) static
References map_rect_priv::item, map_rect_priv::m, map_rect_new(), item::meth, methods_filter, map_rect_priv::parent, item::priv_data, and map_rect_priv::sel.
map_filter_search_destroy()
static void map_filter_search_destroy (struct map_search_priv * ms) static
References dbg, and lvl_debug.
map_filter_search_get_item()
static struct item * map_filter_search_get_item (struct map_search_priv * map_search) static
References dbg, and lvl_debug.
map_filter_search_new()
static struct map_search_priv * map_filter_search_new (struct map_priv * map, struct item * item, struct attr * search, int partial) static
References dbg, and lvl_debug.
map_filter_set_attr()
static int map_filter_set_attr (struct map_priv * m, struct attr * attr) static
References parse_filters(), attr::str, attr::type, and attr::u.
parse_filter()
static GList * parse_filter (char * filter) static
References attr_from_name(), filter_entry::cond_attr, filter_entry::cond_str, item_from_name(), filter_entry::last, and next.
Referenced by parse_filters().
parse_filters()
static void parse_filters (struct map_priv * m, char * filter) static
References map_priv::filters, free_filters(), filter::new, next, filter::old, and parse_filter().
Referenced by map_filter_new(), and map_filter_set_attr().
plugin_init()
void plugin_init (void)
References dbg, lvl_debug, and map_filter_new().
Variable Documentation
map_methods_filter
struct map_methods map_methods_filter static
Initial value:
= {
    projection_mg,
    "utf-8",
    map_filter_destroy,
    map_filter_rect_new,
    map_filter_rect_destroy,
    map_filter_rect_get_item,
    map_filter_rect_get_item_byid,
    map_filter_search_new,
    map_filter_search_destroy,
    map_filter_search_get_item,
    NULL,
    NULL,
    map_filter_set_attr,
}
Referenced by map_filter_new().
methods_filter
struct item_methods methods_filter static
Initial value:
= {
    map_filter_coord_rewind,
    map_filter_coord_get,
    map_filter_attr_rewind,
    map_filter_attr_get,
}
Referenced by map_filter_rect_new().