navit: font/freetype/font_freetype.c File Reference
font_freetype.c File Reference
#include "config.h"
#include <ft2build.h>
#include <glib.h>
#include "point.h"
#include "graphics.h"
#include "debug.h"
#include "plugin.h"
#include "color.h"
#include "atom.h"
#include "font_freetype.h"
Data Structures
struct font_freetype_font
struct font_priv
Macros
#define USE_CACHING 1
#define HAVE_LOOKUP_SCALER 0
#define COLOR_BITDEPTH_OUTPUT 8
#define COL_SHIFT (COLOR_BITDEPTH-COLOR_BITDEPTH_OUTPUT)
Functions
static void font_freetype_get_text_bbox (struct graphics_priv *gr, struct font_freetype_font *font, char *text, int dx, int dy, struct point *ret, int estimate)
static struct font_freetype_text * font_freetype_text_new (char *text, struct font_freetype_font *font, int dx, int dy)
static void font_destroy (struct graphics_font_priv *font)
static void font_freetype_text_destroy (struct font_freetype_text *text)
static FT_Error face_requester (FTC_FaceID face_id, FT_Library library, FT_Pointer request_data, FT_Face *aface)
static struct font_freetype_font * font_freetype_font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *fontfamily, int size, int flags)
static int font_freetype_glyph_get_shadow (struct font_freetype_glyph *g, unsigned char *data, int stride, struct color *foreground, struct color *background)
static int font_freetype_glyph_get_glyph (struct font_freetype_glyph *g, unsigned char *data, int stride, struct color *fg, struct color *bg, struct color *transparent)
static void font_freetype_destroy (void)
static struct font_priv * font_freetype_new (void *meth)
void plugin_init (void)
Variables
static struct font_priv dummy
static FT_Library library
static FTC_Manager manager
static FTC_ImageCache image_cache
static FTC_CMapCache charmap_cache
static FTC_SBitCache sbit_cache
static int library_init = 0
static int library_deinit = 0
static char * fontfamilies []
static struct graphics_font_methods font_methods
static struct font_freetype_methods methods
Macro Definition Documentation
#define COL_SHIFT (COLOR_BITDEPTH-COLOR_BITDEPTH_OUTPUT)
Referenced by font_freetype_glyph_get_glyph(), and font_freetype_glyph_get_shadow().
#define COLOR_BITDEPTH_OUTPUT 8
#define HAVE_LOOKUP_SCALER 0
#define USE_CACHING 1
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
static FT_Error face_requester (FTC_FaceID face_id, FT_Library library, FT_Pointer request_data, FT_Face * aface) static
References dbg, g_free(), g_strdup(), lvl_debug, and lvl_error.
Referenced by font_freetype_font_new().
static void font_destroy (struct graphics_font_priv * font) static
References g_free().
static void font_freetype_destroy (void) static
References library, library_deinit, and manager.
static struct font_freetype_font* font_freetype_font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * fontfamily, int size, int flags) static
Implementation of font_freetype_methods.font_new
References atom(), charmap_cache, font_freetype_font::charmap_index, dbg, face_requester(), font_methods, fontfamilies, g_free(), g_malloc(), g_new, g_strdup(), g_strdup_printf(), getenv, image_cache, library, library_init, lvl_error, lvl_info, manager, name, NULL, sbit_cache, font_freetype_font::scaler, font_freetype_font::size, and size.
static void font_freetype_get_text_bbox (struct graphics_priv * gr, struct font_freetype_font * font, char * text, int dx, int dy, struct point * ret, int estimate) static
References bbox(), charmap_cache, font_freetype_font::charmap_index, g_utf8_get_char(), g_utf8_next_char, g_utf8_strlen(), i, image_cache, manager, NULL, p, font_freetype_font::scaler, font_freetype_font::size, point::x, and point::y.
static int font_freetype_glyph_get_glyph (struct font_freetype_glyph * g, unsigned char * data, int stride, struct color * fg, struct color * bg, struct color * transparent) static
Implementation of font_freetype_methods.get_glyph.
References color::a, color::b, COL_SHIFT, color::g, font_freetype_glyph::h, font_freetype_glyph::pixmap, color::r, and font_freetype_glyph::w.
static int font_freetype_glyph_get_shadow (struct font_freetype_glyph * g, unsigned char * data, int stride, struct color * foreground, struct color * background) static
Implementation of font_freetype_methods.get_shadow.
References color::a, color::b, COL_SHIFT, color::g, font_freetype_glyph::h, font_freetype_glyph::pixmap, color::r, and font_freetype_glyph::w.
static struct font_priv* font_freetype_new (void * meth) static
References dummy, and methods.
Referenced by graphics_gd_new(), graphics_gtk_drawing_area_new_helper(), graphics_opengl_new_helper(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), overlay_new(), and plugin_init().
static void font_freetype_text_destroy (struct font_freetype_text * text) static
References g_free(), font_freetype_text::glyph, font_freetype_text::glyph_count, and i.
static struct font_freetype_text* font_freetype_text_new (char * text, struct font_freetype_font * font, int dx, int dy) static
References charmap_cache, font_freetype_font::charmap_index, font_freetype_glyph::dx, font_freetype_glyph::dy, g_malloc(), g_malloc0(), g_utf8_get_char(), g_utf8_next_char, g_utf8_strlen(), font_freetype_text::glyph, font_freetype_text::glyph_count, font_freetype_glyph::h, image_cache, manager, NULL, p, font_freetype_glyph::pixmap, font_freetype_font::scaler, TRUE, font_freetype_glyph::w, font_freetype_glyph::x, and font_freetype_glyph::y.
void plugin_init (void)
References font_freetype_new().
Variable Documentation
FTC_CMapCache charmap_cache static
Referenced by font_freetype_font_new(), font_freetype_get_text_bbox(), and font_freetype_text_new().
struct font_priv dummy static
Referenced by font_freetype_new().
struct graphics_font_methods font_methods static
Initial value:
= {
        font_destroy
}
Referenced by font_freetype_font_new().
char* fontfamilies[] static
Initial value:
= {
        "Liberation Sans",
        "Arial",
        "NcrBI4nh",
        "luximbi",
        "FreeSans",
        "DejaVu Sans",
        NULL,
}
List of font families to use, in order of preference
Referenced by font_freetype_font_new().
FTC_ImageCache image_cache static
Referenced by font_freetype_font_new(), font_freetype_get_text_bbox(), and font_freetype_text_new().
FT_Library library static
Referenced by font_freetype_destroy(), and font_freetype_font_new().
int library_deinit = 0 static
Referenced by font_freetype_destroy().
int library_init = 0 static
Referenced by font_freetype_font_new().
FTC_Manager manager static
Referenced by font_freetype_destroy(), font_freetype_font_new(), font_freetype_get_text_bbox(), and font_freetype_text_new().
struct font_freetype_methods methods static
Initial value:
= {
        font_freetype_destroy,
        font_freetype_font_new,
        font_freetype_get_text_bbox,
        font_freetype_text_new,
        font_freetype_text_destroy,
        font_freetype_glyph_get_shadow,
        font_freetype_glyph_get_glyph,
}
Referenced by font_freetype_new(), and graphics_sdl_new().
FTC_SBitCache sbit_cache static
Referenced by font_freetype_font_new().