navit: map/garmin/gar2navit.c File Reference
gar2navit.c File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include "item.h"
#include "attr.h"
#include "garmin.h"
#include "gar2navit.h"
#include "g2nbuiltin.h"
Functions
static int add_def (struct gar2nav_conv *conv, int type, unsigned short minid, unsigned short maxid, unsigned int group, char *ntype, char *descr)
static int load_types_file (char *file, struct gar2nav_conv *conv)
struct gar2nav_conv * g2n_conv_load (char *file)
enum item_type g2n_get_type (struct gar2nav_conv *c, unsigned int type, unsigned short id)
char * g2n_get_descr (struct gar2nav_conv *c, int type, unsigned short id)
Function Documentation
static int add_def (struct gar2nav_conv * conv, int type, unsigned short minid, unsigned short maxid, unsigned int group, char * ntype, char * descr) static
References calloc(), gar2navit::descr, dlog, gar2navit::group, gar2navit::id, item_from_name(), gar2navit::maxid, gar2navit::next, gar2navit::ntype, gar2nav_conv::points, gar2nav_conv::polygons, and gar2nav_conv::polylines.
Referenced by load_types_file().
struct gar2nav_conv* g2n_conv_load (char * file)
References c, calloc(), dlog, load_types_file(), and NULL.
Referenced by gmap_new().
char* g2n_get_descr (struct gar2nav_conv * c, int type, unsigned short id)
References gar2navit::descr, dlog, G2N_POINT, G2N_POLYGONE, G2N_POLYLINE, gar2navit::id, gar2navit::maxid, gar2navit::next, NULL, gar2nav_conv::points, gar2nav_conv::polygons, and gar2nav_conv::polylines.
enum item_type g2n_get_type (struct gar2nav_conv * c, unsigned int type, unsigned short id)
References dlog, G2N_KIND_MASK, G2N_KIND_SHIFT, G2N_POINT, G2N_POLYGONE, G2N_POLYLINE, gar2navit::group, gar2navit::id, gar2navit::maxid, gar2navit::next, gar2navit::ntype, NULL, gar2nav_conv::points, gar2nav_conv::polygons, and gar2nav_conv::polylines.
Referenced by garmin_pg2item(), garmin_pl2item(), and garmin_poi2item().
static int load_types_file (char * file, struct gar2nav_conv * conv) static
References add_def(), buf, gar2navit::descr, dlog, fp, gar2navit::group, gar2navit::maxid, gar2navit::ntype, strncasecmp, and type.
Referenced by g2n_conv_load().