navit: map/garmin/gar2navit.h File Reference
gar2navit.h File Reference
Data Structures
struct gar2navit
struct gar2nav_conv
Macros
#define GROUP_RGN1 0
#define GROUP_RGN2 1
#define G2N_POINT 1
#define G2N_POLYLINE 2
#define G2N_POLYGONE 3
#define G2N_KIND_MASK 0xF0000000
#define G2N_KIND_SHIFT 28
#define G2N_RGN1 (GROUP_RGN1<<29)
#define G2N_RGN2 (GROUP_RGN2<<29)
Functions
struct gar2nav_conv * g2n_conv_load (char *file)
enum item_type g2n_get_type (struct gar2nav_conv *c, unsigned int type, unsigned short id)
char * g2n_get_descr (struct gar2nav_conv *c, int type, unsigned short id)
struct gar2nav_conv * g2n_default_conv (void)
Macro Definition Documentation
#define G2N_KIND_MASK 0xF0000000
Referenced by g2n_get_type().
#define G2N_KIND_SHIFT 28
Referenced by g2n_get_type(), garmin_pg2item(), garmin_pl2item(), and garmin_poi2item().
#define G2N_POINT 1
Referenced by g2n_get_descr(), g2n_get_type(), and garmin_poi2item().
#define G2N_POLYGONE 3
Referenced by g2n_get_descr(), g2n_get_type(), and garmin_pg2item().
#define G2N_POLYLINE 2
Referenced by g2n_get_descr(), g2n_get_type(), and garmin_pl2item().
#define G2N_RGN1 (GROUP_RGN1<<29)
#define G2N_RGN2 (GROUP_RGN2<<29)
#define GROUP_RGN1 0
#define GROUP_RGN2 1
Function Documentation
struct gar2nav_conv* g2n_conv_load (char * file)
References c, calloc(), dlog, load_types_file(), and NULL.
Referenced by gmap_new().
struct gar2nav_conv* g2n_default_conv (void)
Referenced by gmap_new().
char* g2n_get_descr (struct gar2nav_conv * c, int type, unsigned short id)
References gar2navit::descr, dlog, G2N_POINT, G2N_POLYGONE, G2N_POLYLINE, gar2navit::id, gar2navit::maxid, gar2navit::next, NULL, gar2nav_conv::points, gar2nav_conv::polygons, and gar2nav_conv::polylines.
enum item_type g2n_get_type (struct gar2nav_conv * c, unsigned int type, unsigned short id)
References dlog, G2N_KIND_MASK, G2N_KIND_SHIFT, G2N_POINT, G2N_POLYGONE, G2N_POLYLINE, gar2navit::group, gar2navit::id, gar2navit::maxid, gar2navit::next, gar2navit::ntype, NULL, gar2nav_conv::points, gar2nav_conv::polygons, and gar2nav_conv::polylines.
Referenced by garmin_pg2item(), garmin_pl2item(), and garmin_poi2item().