navit: map/garmin/garmin.c File Reference
garmin.c File Reference
#include <glib.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "config.h"
#include "plugin.h"
#include "data.h"
#include "projection.h"
#include "item.h"
#include "debug.h"
#include "map.h"
#include "maptype.h"
#include "attr.h"
#include "coord.h"
#include "transform.h"
#include <libgarmin.h>
#include "garmin.h"
#include "gar2navit.h"
Data Structures
struct map_priv
Represents the map from a single binfile.
struct map_rect_priv
struct gscale
struct nl2gl_t
Macros
#define max(a, b) ((a) > (b) ? (a) : (b))
Functions
void logfn (char *file, int line, int level, char *fmt,...)
static int garmin_object_label (struct gobject *o, struct attr *attr)
static int garmin_object_debug (struct gobject *o, struct attr *attr)
static struct map_search_priv * gmap_search_new (struct map_priv *map, struct item *item, struct attr *search, int partial)
static void coord_rewind (void *priv_data)
static void attr_rewind (void *priv_data)
static int point_coord_get (void *priv_data, struct coord *c, int count)
static int coord_is_node (void *priv_data)
static int poly_coord_get (void *priv_data, struct coord *c, int count)
static int point_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int search_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int search_coord_get (void *priv_data, struct coord *c, int count)
static struct item * garmin_poi2item (struct map_rect_priv *mr, struct gobject *o, unsigned short otype)
static struct item * garmin_pl2item (struct map_rect_priv *mr, struct gobject *o, unsigned short otype)
static struct item * garmin_pg2item (struct map_rect_priv *mr, struct gobject *o, unsigned short otype)
static struct item * garmin_srch2item (struct map_rect_priv *mr, struct gobject *o, unsigned short otype)
static struct item * garmin_obj2item (struct map_rect_priv *mr, struct gobject *o)
static struct item * gmap_rect_get_item_byid (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct item * gmap_rect_get_item (struct map_rect_priv *mr)
static int get_level (struct map_selection *sel)
static int garmin_get_selection (struct map_rect_priv *map, struct map_selection *sel)
static struct map_rect_priv * gmap_rect_new (struct map_priv *map, struct map_selection *sel)
static void gmap_rect_destroy (struct map_rect_priv *mr)
static void gmap_search_destroy (struct map_search_priv *ms)
static void gmap_destroy (struct map_priv *m)
static struct map_priv * gmap_new (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
static int map_id
int garmin_debug = 10
static struct gscale mapscales []
static struct item_methods methods_garmin_point
static struct item_methods methods_garmin_poly
static struct item_methods methods_garmin_search
struct nl2gl_t nl2gl_1 []
struct nl2gl_t nl2gl []
static struct map_methods map_methods
Macro Definition Documentation
#define max (a, b) ((a) > (b) ? (a) : (b))
Referenced by AdjustFormants(), attr_new_from_text(), binfile_coord_get(), block_get_byid(), displayitem_draw(), do_draw(), EncodePhonemes(), ezxml_str2utf8(), ezxml_toxml(), ezxml_toxml_r(), graphics_process_selection_item(), inflate_table(), item_bin_add_attr_range(), item_dump_filedesc(), item_order_by_type(), item_range_contains_item(), main(), navit_restrict_to_range(), pedestrian_cmd_pedestrian_rocket(), phase34_process_file(), phase34_process_file_range(), png_build_gamma_table(), protobuf_c_message_unpack(), search_house_number_coordinate(), selection_contains(), tile(), write_countrydir(), WritePitch(), and zip_set_maxnamelen().
Function Documentation
static void attr_rewind (void * priv_data) static
References map_rect_priv::last_attr.
static int coord_is_node (void * priv_data) static
References map_rect_priv::gmap, and map_rect_priv::last_coord.
static void coord_rewind (void * priv_data) static
References map_rect_priv::last_coord.
static int garmin_get_selection (struct map_rect_priv * map, struct map_selection * sel) static
References map_selection::c_rect, map_rect_priv::cobj, dlog, map_priv::g, get_level(), map_rect_priv::gmap, level, coord_rect::lu, item_range::max, map_rect_priv::mpriv, NULL, map_rect_priv::objs, map_selection::range, coord_rect::rl, map_selection::u, coord::x, and coord::y.
Referenced by gmap_rect_new().
static struct item* garmin_obj2item (struct map_rect_priv * mr, struct gobject * o) static
References dlog, garmin_pg2item(), garmin_pl2item(), garmin_poi2item(), garmin_srch2item(), map_rect_priv::item, NULL, and item::type.
Referenced by gmap_rect_get_item(), and gmap_rect_get_item_byid().
static int garmin_object_debug (struct gobject * o, struct attr * attr) static
References dlog, map_rect_priv::label, attr::str, and attr::u.
Referenced by point_attr_get(), and search_attr_get().
static int garmin_object_label (struct gobject * o, struct attr * attr) static
References dlog, g_convert(), map_rect_priv::label, label, NULL, attr::str, and attr::u.
Referenced by point_attr_get(), and search_attr_get().
static struct item* garmin_pg2item (struct map_rect_priv * mr, struct gobject * o, unsigned short otype) static
References map_priv::conv, g2n_get_type(), G2N_KIND_SHIFT, G2N_POLYGONE, map_rect_priv::item, mask, item::meth, methods_garmin_poly, map_rect_priv::mpriv, and item::type.
Referenced by garmin_obj2item().
static struct item* garmin_pl2item (struct map_rect_priv * mr, struct gobject * o, unsigned short otype) static
References map_priv::conv, g2n_get_type(), G2N_KIND_SHIFT, G2N_POLYLINE, map_rect_priv::item, mask, item::meth, methods_garmin_poly, map_rect_priv::mpriv, and item::type.
Referenced by garmin_obj2item().
static struct item* garmin_poi2item (struct map_rect_priv * mr, struct gobject * o, unsigned short otype) static
References map_priv::conv, g2n_get_type(), G2N_KIND_SHIFT, G2N_POINT, map_rect_priv::item, mask, item::meth, methods_garmin_point, map_rect_priv::mpriv, and item::type.
Referenced by garmin_obj2item().
static struct item* garmin_srch2item (struct map_rect_priv * mr, struct gobject * o, unsigned short otype) static
References map_rect_priv::item, item::meth, methods_garmin_search, and item::type.
Referenced by garmin_obj2item().
static int get_level (struct map_selection * sel) static
References map_selection::order.
Referenced by garmin_get_selection().
static void gmap_destroy (struct map_priv * m) static
References dlog, map_priv::filename, and map_priv::g.
static struct map_priv* gmap_new (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), buf, map_priv::conv, data, debug, dlog, map_priv::filename, map_priv::g, g2n_conv_load(), g2n_default_conv(), g_free(), g_new, garmin_debug, map_priv::id, logfn(), map_id, map_methods, NULL, attr::num, PATH_MAX, stat(), attr::str, and attr::u.
Referenced by plugin_init().
static void gmap_rect_destroy (struct map_rect_priv * mr) static
References dlog, map_rect_priv::gmap, map_rect_priv::label, and map_rect_priv::objs.
Referenced by gmap_search_destroy().
static struct item* gmap_rect_get_item (struct map_rect_priv * mr) static
References map_rect_priv::cobj, garmin_obj2item(), item::id_hi, item::id_lo, map_rect_priv::item, NULL, map_rect_priv::objs, item::priv_data, and item::type.
static struct item* gmap_rect_get_item_byid (struct map_rect_priv * mr, int id_hi, int id_lo) static
References dlog, map_priv::g, garmin_obj2item(), item::id_hi, item::id_lo, map_rect_priv::item, map_rect_priv::mpriv, NULL, map_rect_priv::objs, item::priv_data, and item::type.
static struct map_rect_priv* gmap_rect_new (struct map_priv * map, struct map_selection * sel) static
References calloc(), dlog, garmin_get_selection(), map_rect_priv::mpriv, map_selection::next, NULL, and map_selection::order.
static void gmap_search_destroy (struct map_search_priv * ms) static
References gmap_rect_destroy().
static struct map_search_priv* gmap_search_new (struct map_priv * map, struct item * item, struct attr * search, int partial) static
References map_rect_priv::cobj, dlog, map_priv::g, g_new0, map_rect_priv::gmap, map_rect_priv::mpriv, NULL, map_rect_priv::objs, map_rect_priv::search, attr::str, attr::type, and attr::u.
void logfn (char * file, int line, int level, char * fmt, ...)
References debug_vprintf(), garmin_debug, and sprintf().
Referenced by gmap_new().
void plugin_init (void)
References gmap_new().
static int point_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References AF_ONEWAY, AF_SEGMENTED, attr_to_name(), dlog, garmin_object_debug(), garmin_object_label(), map_rect_priv::last_attr, map_rect_priv::last_oattr, attr::num, attr::type, and attr::u.
static int point_coord_get (void * priv_data, struct coord * c, int count) static
References map_rect_priv::gmap, map_rect_priv::last_coord, map_rect_priv::last_itterated, coord::x, and coord::y.
static int poly_coord_get (void * priv_data, struct coord * c, int count) static
References ddlog, map_rect_priv::gmap, map_rect_priv::last_c, map_rect_priv::last_coord, map_rect_priv::last_itterated, coord::x, and coord::y.
static int search_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References AF_ONEWAY, AF_SEGMENTED, attr_to_name(), dlog, garmin_object_debug(), garmin_object_label(), map_rect_priv::label, map_rect_priv::last_attr, map_rect_priv::last_oattr, attr::num, attr::str, attr::type, and attr::u.
static int search_coord_get (void * priv_data, struct coord * c, int count) static
References map_rect_priv::gmap, map_rect_priv::last_coord, map_rect_priv::last_itterated, coord::x, and coord::y.
Variable Documentation
int garmin_debug = 10
Referenced by gmap_new(), and logfn().
int map_id static
Referenced by gmap_new().
struct map_methods map_methods static
Initial value:
= {
        projection_garmin,
        "utf-8",
        gmap_destroy,
        gmap_rect_new,
        gmap_rect_destroy,
        gmap_rect_get_item,
        gmap_rect_get_item_byid,
        gmap_search_new,
        gmap_search_destroy,
        NULL,
}
Referenced by gmap_new().
struct gscale mapscales[] static
struct item_methods methods_garmin_point static
Initial value:
= {
        coord_rewind,
        point_coord_get,
        attr_rewind,
        point_attr_get,
}
Referenced by garmin_poi2item().
struct item_methods methods_garmin_poly static
Initial value:
= {
        coord_rewind,
        poly_coord_get,
        attr_rewind,
        point_attr_get,
        coord_is_node,
}
Referenced by garmin_pg2item(), and garmin_pl2item().
struct item_methods methods_garmin_search static
Initial value:
= {
        coord_rewind,
        search_coord_get,
        attr_rewind,
        search_attr_get,
}
Referenced by garmin_srch2item().
struct nl2gl_t nl2gl[]
Initial value:
= {
        {   .g = 9, .descr = "0-120m", },
        {   .g = 9, .descr = "0-120m", },
        {   .g = 8, .descr = "0-120m", },
        {   .g = 8, .descr = "0-120m", },
        {   .g = 7, .descr = "0-120m", },
        {   .g = 7, .descr = "0-120m", },
        {   .g = 6, .descr = "0-120m", },
        {   .g = 6, .descr = "0-120m", },
        {   .g = 5, .descr = "0-120m", },
        {   .g = 5, .descr = "0-120m", },
        {  .g = 4, .descr = "0-120m", },
        {  .g = 4, .descr = "0-120m", },
        {  .g = 3, .descr = "0-120m", },
        {  .g = 3, .descr = "0-120m", },
        {  .g = 2, .descr = "0-120m", },
        {  .g = 2, .descr = "0-120m", },
        {  .g = 1, .descr = "0-120m", },
        {  .g = 1, .descr = "0-120m", },
        {  .g = 0, .descr = "0-120m", },
}
struct nl2gl_t nl2gl_1[]
Initial value:
= {
        {   .g = 12, .descr = "0-120m", },
        {   .g = 11, .descr = "0-120m", },
        {   .g = 10, .descr = "0-120m", },
        {   .g = 9, .descr = "0-120m", },
        {   .g = 8, .descr = "0-120m", },
        {   .g = 7, .descr = "0-120m", },
        {   .g = 6, .descr = "0-120m", },
        {   .g = 5, .descr = "0-120m", },
        {   .g = 4, .descr = "0-120m", },
        {   .g = 4, .descr = "0-120m", },
        {  .g = 3, .descr = "0-120m", },
        {  .g = 3, .descr = "0-120m", },
        {  .g = 2, .descr = "0-120m", },
        {  .g = 2, .descr = "0-120m", },
        {  .g = 2, .descr = "0-120m", },
        {  .g = 1, .descr = "0-120m", },
        {  .g = 1, .descr = "0-120m", },
        {  .g = 1, .descr = "0-120m", },
        {  .g = 0, .descr = "0-120m", },
}