navit: map/garmin/gentypes.c File Reference
gentypes.c File Reference
#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <unistd.h>
#include "item.h"
#include "gar2navit.h"
Macros
#define dlog(x, y...) fprintf(stderr, ## y)
Functions
static void print_header (FILE *fp)
static int load_types_file (char *file, char *out)
int main (int argc, char **argv)
Macro Definition Documentation
#define dlog (x, y...) fprintf(stderr, ## y)
Referenced by load_types_file().
Function Documentation
static int load_types_file (char * file, char * out) static
References buf, dlog, fp, fprintf(), print_header(), strncasecmp, and type.
Referenced by main().
int main (int argc, char ** argv)
References fprintf(), load_types_file(), and unlink().
static void print_header (FILE * fp) static
References fprintf().
Referenced by load_types_file().