navit: tools/gpx2navit_txt/src/geod_set.c File Reference
geod_set.c File Reference
#include <string.h>
#include "projects.h"
#include "geodesic.h"
#include "emess.h"
Macros
#define _IN_GEOD_SET
Functions
void geod_set (int argc, char **argv)
Macro Definition Documentation
#define _IN_GEOD_SET
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
void geod_set (int argc, char ** argv)
References al12, argc, del_alpha, ellipse, emess(), f2, f4, f64, fr_meter, geod_a, geod_f, geod_for(), geod_inv(), geod_pre(), geod_S, i, lam1, lam2, n_alpha, n_S, name, NULL, onef, phi1, phi2, start, and to_meter.
Referenced by setDefault().