navit: tools/gpx2navit_txt/src/geodesic.h File Reference
geodesic.h File Reference
Data Structures
struct geodesic
Macros
#define GEOD_EXTERN extern
#define geod_a GEODESIC.A
#define lam1 GEODESIC.LAM1
#define phi1 GEODESIC.PHI1
#define al12 GEODESIC.ALPHA12
#define lam2 GEODESIC.LAM2
#define phi2 GEODESIC.PHI2
#define al21 GEODESIC.ALPHA21
#define geod_S GEODESIC.DIST
#define geod_f GEODESIC.FLAT
#define onef GEODESIC.ONEF
#define f2 GEODESIC.FLAT2
#define f4 GEODESIC.FLAT4
#define ff2 GEODESIC.FLAT4
#define f64 GEODESIC.FLAT64
#define ellipse GEODESIC.ELLIPSE
Functions
void geod_set (int, char **)
void geod_for (void)
void geod_pre (void)
void geod_inv (void)
Variables
GEOD_EXTERN struct geodesic GEODESIC
GEOD_EXTERN int n_alpha
GEOD_EXTERN int n_S
GEOD_EXTERN double to_meter
GEOD_EXTERN double fr_meter
GEOD_EXTERN double del_alpha
Macro Definition Documentation
al12
#define al12 GEODESIC.ALPHA12
al21
#define al21 GEODESIC.ALPHA21
ellipse
#define ellipse GEODESIC.ELLIPSE
f2
#define f2 GEODESIC.FLAT2
f4
#define f4 GEODESIC.FLAT4
f64
#define f64 GEODESIC.FLAT64
ff2
#define ff2 GEODESIC.FLAT4
geod_a
#define geod_a GEODESIC.A
GEOD_EXTERN
#define GEOD_EXTERN extern
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
geod_f
#define geod_f GEODESIC.FLAT
geod_S
#define geod_S GEODESIC.DIST
lam1
#define lam1 GEODESIC.LAM1
lam2
#define lam2 GEODESIC.LAM2
onef
#define onef GEODESIC.ONEF
phi1
#define phi1 GEODESIC.PHI1
phi2
#define phi2 GEODESIC.PHI2
Function Documentation
geod_for()
void geod_for (void)
References al12, al21, c1, c2, cosa12, costh1, D, ellipse, geod_a, geod_S, lam1, lam2, M, merid, N, onef, P, phi2, PI, s1, signS, sina12, sind, and sinth1.
Referenced by geod_set().
geod_inv()
void geod_inv (void)
References al12, al21, cosd, D, DTOL, ellipse, f2, f4, f64, geod_a, geod_S, L, lam1, lam2, onef, phi1, phi2, sind, th1, and TWOPI.
Referenced by geod_set(), and getDistanceCore().
geod_pre()
void geod_pre (void)
References al12, c1, c2, cosa12, costh1, D, ellipse, f4, geod_f, M, MERI_TOL, merid, N, onef, P, phi1, s1, signS, sina12, sinth1, and th1.
Referenced by geod_set().
geod_set()
void geod_set (int argc, char ** argv)
References al12, argc, argv, del_alpha, ellipse, emess(), f2, f4, f64, fr_meter, geod_a, geod_f, geod_for(), geod_inv(), geod_pre(), geod_S, lam1, lam2, n_alpha, n_S, name, onef, phi1, phi2, and to_meter.
Referenced by setDefault().
Variable Documentation
del_alpha
GEOD_EXTERN double del_alpha
Referenced by geod_set().
fr_meter
GEOD_EXTERN double fr_meter
Referenced by geod_set().
GEODESIC
GEOD_EXTERN struct geodesic GEODESIC
n_alpha
GEOD_EXTERN int n_alpha
Referenced by geod_set().
n_S
GEOD_EXTERN int n_S
Referenced by geod_set().
to_meter
GEOD_EXTERN double to_meter
Referenced by checkLengthUnit(), geod_set(), and getSpeed().