navit: geom.c File Reference
geom.c File Reference
#include <string.h>
#include <math.h>
#include "geom.h"
Functions
void geom_coord_copy (struct coord *from, struct coord *to, int count, int reverse)
int geom_line_middle (struct coord *p, int count, struct coord *c)
void geom_coord_revert (struct coord *c, int count)
long long geom_poly_area (struct coord *c, int count)
int geom_poly_centroid (struct coord *p, int count, struct coord *c)
int geom_poly_closest_point (struct coord *pl, int count, struct coord *p, struct coord *c)
int geom_poly_point_inside (struct coord *cp, int count, struct coord *c)
GList * geom_poly_segments_insert (GList *list, struct geom_poly_segment *first, struct geom_poly_segment *second, struct geom_poly_segment *third)
void geom_poly_segment_destroy (struct geom_poly_segment *seg)
GList * geom_poly_segments_remove (GList *list, struct geom_poly_segment *seg)
int geom_poly_segment_compatible (struct geom_poly_segment *s1, struct geom_poly_segment *s2, int dir)
GList * geom_poly_segments_sort (GList *in, enum geom_poly_segment_type type)
int geom_poly_segments_point_inside (GList *in, struct coord *c)
static int clipcode (struct coord *p, struct rect *r)
int geom_clip_line_code (struct coord *p1, struct coord *p2, struct rect *r)
int geom_is_inside (struct coord *p, struct rect *r, int edge)
void geom_poly_intersection (struct coord *p1, struct coord *p2, struct rect *r, int edge, struct coord *ret)
void geom_init ()
Function Documentation
static int clipcode (struct coord * p, struct rect * r) static
References rect::h, coord::x, and coord::y.
Referenced by geom_clip_line_code().
int geom_clip_line_code (struct coord * p1, struct coord * p2, struct rect * r)
References clipcode(), rect::h, coord::x, and coord::y.
Referenced by clip_line().
void geom_coord_copy (struct coord * from, struct coord * to, int count, int reverse)
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References i.
Referenced by geom_poly_segments_insert(), and item_bin_to_poly_segment().
void geom_coord_revert (struct coord * c, int count)
References i.
void geom_init (void)
Referenced by main_real().
int geom_is_inside (struct coord * p, struct rect * r, int edge)
References rect::h, coord::x, and coord::y.
Referenced by clip_polygon().
int geom_line_middle (struct coord * p, int count, struct coord * c)
Get coordinates of polyline middle point.
Parameters
in *p array of poly vertex coordinates
in count count of poly vertexes
out *c coordinates of middle point
Returns
number of first vertex of segment containing middle point
References i, length, p, sq, coord::x, font_freetype_glyph::x, coord::y, and font_freetype_glyph::y.
Referenced by process_way2poi(), and search_list_street_new().
long long geom_poly_area (struct coord * c, int count)
References area(), fprintf(), i, long, LONGLONG_FMT, coord::x, and coord::y.
Referenced by geom_poly_segments_sort(), and tile_collector_process_tile().
int geom_poly_centroid (struct coord * p, int count, struct coord * c)
Get poly centroid coordinates.
Parameters
in *p array of poly vertex coordinates
in count count of poly vertexes
out *c coordinates of poly centroid
Returns
1 on success, 0 if poly area is 0
References area(), i, coord::x, and coord::y.
Referenced by process_way2poi().
int geom_poly_closest_point (struct coord * pl, int count, struct coord * p, struct coord * c)
Get coordinates of polyline point c most close to given point p.
Parameters
in *pl array of polyline vertex coordinates
in count count of polyline vertexes
in *p point coordinates
out *c coordinates of polyline point most close to given point.
Returns
first vertex number of polyline segment to which c belongs
References i, coord::x, and coord::y.
Referenced by process_way2poi().
void geom_poly_intersection (struct coord * p1, struct coord * p2, struct rect * r, int edge, struct coord * ret)
References rect::h, coord::x, and coord::y.
Referenced by clip_polygon().
int geom_poly_point_inside (struct coord * cp, int count, struct coord * c)
Check if point is inside polgone.
Parameters
in *cp array of polygon vertex coordinates
in count count of polygon vertexes
in *c point coordinates
Returns
1 - inside, 0 - outside
References coord_print(), fprintf(), printf(), projection_mg, coord::x, and coord::y.
Referenced by geom_poly_segments_point_inside(), item_inside_poly_list(), and process_way2poi().
int geom_poly_segment_compatible (struct geom_poly_segment * s1, struct geom_poly_segment * s2, int dir)
References coord_is_equal, geom_poly_segment::first, geom_poly_segment_type_none, geom_poly_segment_type_way_inner, geom_poly_segment_type_way_left_side, geom_poly_segment_type_way_outer, geom_poly_segment_type_way_right_side, geom_poly_segment_type_way_unknown, geom_poly_segment::last, and geom_poly_segment::type.
Referenced by geom_poly_segments_sort().
void geom_poly_segment_destroy (struct geom_poly_segment * seg)
References geom_poly_segment::first, and g_free().
Referenced by binmap_search_destroy(), geom_poly_segments_remove(), and tile_collector_process_tile().
GList* geom_poly_segments_insert (GList * list, struct geom_poly_segment * first, struct geom_poly_segment * second, struct geom_poly_segment * third)
References coord_is_equal, geom_poly_segment::first, fprintf(), g_list_prepend(), g_new, geom_coord_copy(), geom_poly_segment::last, NULL, startup::pos, geom_poly_segment::type, coord::x, and coord::y.
Referenced by geom_poly_segments_sort().
int geom_poly_segments_point_inside (GList * in, struct coord * c)
References coord_is_equal, _GList::data, geom_poly_segment::first, fprintf(), g_list_next, geom_poly_point_inside(), geom_poly_segment::last, coord::x, and coord::y.
Referenced by boundary_find_matches().
GList* geom_poly_segments_remove (GList * list, struct geom_poly_segment * seg)
References g_list_remove(), and geom_poly_segment_destroy().
Referenced by geom_poly_segments_sort().
GList* geom_poly_segments_sort (GList * in, enum geom_poly_segment_type type)
References area(), coord_is_equal, _GList::data, geom_poly_segment::first, g_list_next, geom_poly_area(), geom_poly_segment_compatible(), geom_poly_segment_type_way_inner, geom_poly_segment_type_way_outer, geom_poly_segment_type_way_right_side, geom_poly_segments_insert(), geom_poly_segments_remove(), geom_poly_segment::last, NULL, and geom_poly_segment::type.
Referenced by process_boundaries_finish(), and tile_collector_process_tile().