navit: support/glib/gerror.h File Reference
gerror.h File Reference
#include <glib/gquark.h>
Data Structures
struct _GError
Macros
#define __G_ERROR_H__
Typedefs
typedef typedefG_BEGIN_DECLS
struct _GError GError
Functions
GError * g_error_new (GQuark domain, gint code, const gchar *format,...) G_GNUC_PRINTF(3
GError GError * g_error_new_literal (GQuark domain, gint code, const gchar *message)
void g_error_free (GError *error)
GError * g_error_copy (const GError *error)
gboolean g_error_matches (const GError *error, GQuark domain, gint code)
void g_set_error (GError **err, GQuark domain, gint code, const gchar *format,...) G_GNUC_PRINTF(4
void void g_set_error_literal (GError **err, GQuark domain, gint code, const gchar *message)
void g_propagate_error (GError **dest, GError *src)
void g_clear_error (GError **err)
void g_prefix_error (GError **err, const gchar *format,...) G_GNUC_PRINTF(2
void void g_propagate_prefixed_error (GError **dest, GError *src, const gchar *format,...) G_GNUC_PRINTF(3
Macro Definition Documentation
#define __G_ERROR_H__
Typedef Documentation
typedef typedefG_BEGIN_DECLS struct _GError GError
Function Documentation
void g_clear_error (GError ** err)
GError* g_error_copy (const GError * error)
void g_error_free (GError * error)
Referenced by gui_gtk_ui_init().
gboolean g_error_matches (const GError * error, GQuark domain, gint code)
GError* g_error_new (GQuark domain, gint code, const gchar * format, ...)
GError GError* g_error_new_literal (GQuark domain, gint code, const gchar * message)
void g_prefix_error (GError ** err, const gchar * format, ...)
void g_propagate_error (GError ** dest, GError * src)
void void g_propagate_prefixed_error (GError ** dest, GError * src, const gchar * format, ...)
void g_set_error (GError ** err, GQuark domain, gint code, const gchar * format, ...)
Referenced by config_load(), find_attribute(), start_element(), and xinclude().
void void g_set_error_literal (GError ** err, GQuark domain, gint code, const gchar * message)
Referenced by g_ucs4_to_utf16(), g_utf16_to_ucs4(), g_utf16_to_utf8(), and g_utf8_to_utf16().