navit: support/xgetopt/getopt_long.c File Reference
getopt_long.c File Reference
#include <stdio.h>
#include <string.h>
#include "getopt_long.h"
Macros
#define BADCH '?'
#define BADARG ':'
#define EMSG ""
Functions
int getopt_long (int argc, char *const argv[], const char *optstring, const struct option *longopts, int *longindex)
Variables
int opterr
int optopt
Macro Definition Documentation
#define BADARG ':'
Referenced by getopt_long().
#define BADCH '?'
Referenced by getopt_long().
#define EMSG ""
Referenced by getopt_long().
Function Documentation
int getopt_long (int argc, char *const argv[], const char * optstring, const struct option * longopts, int * longindex)
References BADARG, BADCH, EMSG, option::flag, fprintf(), i, int, option::name, name, NULL, optarg, opterr, optind, optopt, and option::val.
Referenced by main(), parse_option(), and setOptions().
Variable Documentation
int opterr
Referenced by getopt_long(), and main_real().
int optopt
Referenced by getopt_long(), and main_real().