navit: support/gettext_intl/gettextP.h File Reference
gettextP.h File Reference
#include <stddef.h>
#include "loadinfo.h"
#include "gmo.h"
#include "libgnuintl.h"
Data Structures
struct sysdep_string_desc
struct loaded_domain
struct binding
Macros
#define attribute_hidden = _nl_default_default_domain
#define __builtin_expect(expr, val) (expr)
#define W(flag, data) ((flag) ? SWAP (data) : (data))
#define ZERO 1
#define _INTL_REDIRECT_MACROS
Functions
const char * _nl_locale_name (int category, const char *categoryname)
struct loaded_l10nfile * _nl_find_domain (const char *__dirname, char *__locale, const char *__domainname, struct binding *__domainbinding) internal_function
void _nl_load_domain (struct loaded_l10nfile *__domain, struct binding *__domainbinding) internal_function
void _nl_unload_domain (struct loaded_domain *__domain) internal_function
const char * _nl_init_domain_conv (struct loaded_l10nfile *__domain_file, struct loaded_domain *__domain, struct binding *__domainbinding) internal_function
void _nl_free_domain_conv (struct loaded_domain *__domain) internal_function
char * _nl_find_msg (struct loaded_l10nfile *domain_file, struct binding *domainbinding, const char *msgid, size_t *lengthp) internal_function
char * libintl_dcigettext (const char *__domainname, const char *__msgid1, const char *__msgid2, int __plural, unsigned long int __n, int __category)
Variables
static nls_uint32 nls_uint32 i
int _nl_msg_cat_cntr
Macro Definition Documentation
#define __builtin_expect (expr, val) (expr)
Referenced by _nl_find_msg(), _nl_load_domain(), if(), and read_alias_file().
#define _INTL_REDIRECT_MACROS
const char *_nl_current_default_domain attribute_hidden = _nl_default_default_domain
#define W (flag, data) ((flag) ? SWAP (data) : (data))
Referenced by _nl_find_msg(), and _nl_load_domain().
#define ZERO 1
Function Documentation
struct loaded_l10nfile* _nl_find_domain (const char * __dirname, char * __locale, const char * __domainname, struct binding * __domainbinding)
References _nl_expand_alias(), _nl_explode_name(), _nl_load_domain(), _nl_make_l10nflist(), codeset, loaded_l10nfile::data, loaded_l10nfile::decided, mask, NULL, special, loaded_l10nfile::successor, and XPG_NORM_CODESET.
char* _nl_find_msg (struct loaded_l10nfile * domain_file, struct binding * domainbinding, const char * msgid, size_t * lengthp)
References __builtin_expect, __libc_lock_define_initialized, __libc_lock_lock, __libc_lock_unlock, _nl_free_domain_conv(), _nl_init_domain_conv(), _nl_load_domain(), calloc(), loaded_domain::codeset_cntr, binding::codeset_cntr, loaded_domain::conv_tab, loaded_l10nfile::data, loaded_domain::data, data, loaded_l10nfile::decided, E2BIG, errno, loaded_domain::hash_size, hash_string(), loaded_domain::hash_tab, if(), sysdep_string_desc::length, string_desc::length, loaded_domain::must_swap, loaded_domain::must_swap_hash_tab, loaded_domain::n_sysdep_strings, loaded_domain::nstrings, NULL, string_desc::offset, offsetof, loaded_domain::orig_sysdep_tab, loaded_domain::orig_tab, outbuf, sysdep_string_desc::pointer, loaded_domain::trans_sysdep_tab, loaded_domain::trans_tab, and W.
Referenced by _nl_init_domain_conv().
void _nl_free_domain_conv (struct loaded_domain * __domain)
References loaded_domain::conv_tab, and NULL.
Referenced by _nl_find_msg().
const char* _nl_init_domain_conv (struct loaded_l10nfile * __domain_file, struct loaded_domain * __domain, struct binding * __domainbinding)
References _nl_find_msg(), alloca, binding::codeset, loaded_domain::codeset_cntr, binding::codeset_cntr, loaded_domain::conv_tab, freea, getenv, locale_charset(), mempcpy(), and NULL.
Referenced by _nl_find_msg(), and _nl_load_domain().
void _nl_load_domain (struct loaded_l10nfile * __domain, struct binding * __domainbinding)
References __builtin_expect, _MAGIC, _MAGIC_SWAPPED, _nl_init_domain_conv(), abort(), alloca, close(), loaded_l10nfile::data, loaded_domain::data, data, loaded_l10nfile::decided, EINTR, errno, EXTRACT_PLURAL_EXPRESSION, loaded_l10nfile::filename, freea, fstat(), get_sysdep_segment_value(), loaded_domain::hash_size, hash_string(), loaded_domain::hash_tab, mo_file_header::hash_tab_offset, mo_file_header::hash_tab_size, i, int, sysdep_string_desc::length, sysdep_segment::length, mo_file_header::magic, loaded_domain::malloced, loaded_domain::mmap_size, loaded_domain::must_swap, loaded_domain::must_swap_hash_tab, mo_file_header::n_sysdep_segments, mo_file_header::n_sysdep_strings, loaded_domain::n_sysdep_strings, name, loaded_domain::nplurals, mo_file_header::nstrings, loaded_domain::nstrings, NULL, O_BINARY, O_RDONLY, sysdep_segment::offset, sysdep_string::offset, open(), loaded_domain::orig_sysdep_tab, mo_file_header::orig_sysdep_tab_offset, loaded_domain::orig_tab, mo_file_header::orig_tab_offset, p, loaded_domain::plural, sysdep_string_desc::pointer, read(), mo_file_header::revision, sysdep_string::segments, SEGMENTS_END, size, stat::st_size, mo_file_header::sysdep_segments_offset, loaded_domain::trans_sysdep_tab, mo_file_header::trans_sysdep_tab_offset, loaded_domain::trans_tab, mo_file_header::trans_tab_offset, loaded_domain::use_mmap, and W.
Referenced by _nl_find_domain(), and _nl_find_msg().
const char* _nl_locale_name (int category, const char * categoryname)
References getenv, GetThreadLocale(), NULL, setlocale(), SUBLANG_BENGALI_BANGLADESH, SUBLANG_PUNJABI_PAKISTAN, and SUBLANG_ROMANIAN_MOLDOVA.
Referenced by guess_category_value().
void _nl_unload_domain (struct loaded_domain * __domain)
char* libintl_dcigettext (const char * __domainname, const char * __msgid1, const char * __msgid2, int __plural, unsigned long int __n, int __category)
Variable Documentation
int _nl_msg_cat_cntr
Referenced by __libc_rwlock_define(), and DCIGETTEXT().
nls_uint32 nls_uint32 i static