navit: support/glib/ghash.h File Reference
ghash.h File Reference
#include <glib/gtypes.h>
#include <glib/glist.h>
Data Structures
struct _GHashTableIter
Macros
#define __G_HASH_H__
#define g_hash_table_freeze(hash_table) ((void)0)
#define g_hash_table_thaw(hash_table) ((void)0)
Typedefs
typedef typedefG_BEGIN_DECLS
struct _GHashTable GHashTable
typedef gboolean(* GHRFunc)(gpointer key, gpointer value, gpointer user_data)
typedef struct _GHashTableIter GHashTableIter
Functions
GHashTable * g_hash_table_new (GHashFunc hash_func, GEqualFunc key_equal_func)
GHashTable * g_hash_table_new_full (GHashFunc hash_func, GEqualFunc key_equal_func, GDestroyNotify key_destroy_func, GDestroyNotify value_destroy_func)
void g_hash_table_destroy (GHashTable *hash_table)
void g_hash_table_insert (GHashTable *hash_table, gpointer key, gpointer value)
void g_hash_table_replace (GHashTable *hash_table, gpointer key, gpointer value)
gboolean g_hash_table_remove (GHashTable *hash_table, gconstpointer key)
void g_hash_table_remove_all (GHashTable *hash_table)
gboolean g_hash_table_steal (GHashTable *hash_table, gconstpointer key)
void g_hash_table_steal_all (GHashTable *hash_table)
gpointer g_hash_table_lookup (GHashTable *hash_table, gconstpointer key)
gboolean g_hash_table_lookup_extended (GHashTable *hash_table, gconstpointer lookup_key, gpointer *orig_key, gpointer *value)
void g_hash_table_foreach (GHashTable *hash_table, GHFunc func, gpointer user_data)
gpointer g_hash_table_find (GHashTable *hash_table, GHRFunc predicate, gpointer user_data)
guint g_hash_table_foreach_remove (GHashTable *hash_table, GHRFunc func, gpointer user_data)
guint g_hash_table_foreach_steal (GHashTable *hash_table, GHRFunc func, gpointer user_data)
guint g_hash_table_size (GHashTable *hash_table)
GList * g_hash_table_get_keys (GHashTable *hash_table)
GList * g_hash_table_get_values (GHashTable *hash_table)
void g_hash_table_iter_init (GHashTableIter *iter, GHashTable *hash_table)
gboolean g_hash_table_iter_next (GHashTableIter *iter, gpointer *key, gpointer *value)
GHashTable * g_hash_table_iter_get_hash_table (GHashTableIter *iter)
void g_hash_table_iter_remove (GHashTableIter *iter)
void g_hash_table_iter_steal (GHashTableIter *iter)
GHashTable * g_hash_table_ref (GHashTable *hash_table)
void g_hash_table_unref (GHashTable *hash_table)
gboolean g_str_equal (gconstpointer v1, gconstpointer v2)
guint g_str_hash (gconstpointer v)
gboolean g_int_equal (gconstpointer v1, gconstpointer v2)
guint g_int_hash (gconstpointer v)
guint g_direct_hash (gconstpointer v) G_GNUC_CONST
gboolean g_direct_equal (gconstpointer v1, gconstpointer v2) G_GNUC_CONST
Macro Definition Documentation
#define __G_HASH_H__
#define g_hash_table_freeze (hash_table) ((void)0)
#define g_hash_table_thaw (hash_table) ((void)0)
Typedef Documentation
typedef typedefG_BEGIN_DECLS struct _GHashTable GHashTable
typedef struct _GHashTableIter GHashTableIter
typedef gboolean(* GHRFunc)(gpointer key, gpointer value, gpointer user_data)
Function Documentation
gboolean g_direct_equal (gconstpointer v1, gconstpointer v2)
g_direct_equal: : a key. : a key to compare with .
Compares two gpointer arguments and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using pointers as keys in a GHashTable.
Returns: TRUE if the two keys match.
guint g_direct_hash (gconstpointer v)
g_direct_hash: : a gpointer key
Converts a gpointer to a hash value. It can be passed to g_hash_table_new() as the parameter, when using pointers as keys in a GHashTable.
Returns: a hash value corresponding to the key.
References GPOINTER_TO_UINT.
Referenced by g_hash_table_new_full(), item_hash_hash(), and search_item_hash_hash().
void g_hash_table_destroy (GHashTable * hash_table)
g_hash_table_destroy: : a GHashTable.
Destroys all keys and values in the GHashTable and decrements its reference count by 1. If keys and/or values are dynamically allocated, you should either free them first or create the GHashTable with destroy notifiers using g_hash_table_new_full(). In the latter case the destroy functions you supplied will be called on all keys and values during the destruction phase.
References g_hash_table_remove_all(), g_hash_table_unref(), g_return_if_fail, and NULL.
Referenced by attr_destroy_hash(), binmap_search_destroy(), bookmarks_clear_hash(), bookmarks_store_bookmarks_to_file(), ch_assemble_map(), ch_generate_ddsg(), debug_finished(), file_destroy(), file_process_headers(), graphics_destroy(), graphics_free(), gui_gtk_bookmarks_update(), item_cleanup(), item_destroy_hash(), item_hash_destroy(), linguistics_free(), longest_match_destroy(), map_destroy_csv(), map_rect_destroy_mg(), navit_destroy(), osm_process_towns(), osm_protobufdb_start_group(), plugins_destroy(), relations_destroy(), search_list_get_result(), search_list_search_free(), tile_collector_finish(), and vehicleprofile_free_hash().
gpointer g_hash_table_find (GHashTable * hash_table, GHRFunc predicate, gpointer user_data)
g_hash_table_find: : a GHashTable. : function to test the key/value pairs for a certain property. : user data to pass to the function.
Calls the given function for key/value pairs in the GHashTable until returns TRUE. The function is passed the key and value of each pair, and the given parameter. The hash table may not be modified while iterating over it (you can't add/remove items).
Note, that hash tables are really only optimized for forward lookups, i.e. g_hash_table_lookup(). So code that frequently issues g_hash_table_find() or g_hash_table_foreach() (e.g. in the order of once per every entry in a hash table) should probably be reworked to use additional or different data structures for reverse lookups (keep in mind that an O(n) find/foreach operation issued for all n values in a hash table ends up needing O(n*n) operations).
Return value: The value of the first key/value pair is returned, for which func evaluates to TRUE. If no pair with the requested property is found, NULL is returned.
Since: 2.4
References g_return_val_if_fail, i, _GHashNode::key, _GHashNode::next, NULL, and _GHashNode::value.
void g_hash_table_foreach (GHashTable * hash_table, GHFunc func, gpointer user_data)
g_hash_table_foreach: : a GHashTable. : the function to call for each key/value pair. : user data to pass to the function.
Calls the given function for each of the key/value pairs in the GHashTable. The function is passed the key and value of each pair, and the given parameter. The hash table may not be modified while iterating over it (you can't add/remove items). To remove all items matching a predicate, use g_hash_table_foreach_remove().
See g_hash_table_find() for performance caveats for linear order searches in contrast to g_hash_table_lookup().
References g_return_if_fail, i, _GHashNode::key, _GHashNode::next, NULL, and _GHashNode::value.
Referenced by debug_level_set(), foreach_tile(), g_hash_to_list(), g_hash_to_list_keys(), get_tiles_list(), map_csv_debug_dump(), relations_destroy(), tile_collector_finish(), vehicleprofile_free_hash(), vehicleprofile_update(), and write_changes().
guint g_hash_table_foreach_remove (GHashTable * hash_table, GHRFunc func, gpointer user_data)
g_hash_table_foreach_remove: : a GHashTable. : the function to call for each key/value pair. : user data to pass to the function.
Calls the given function for each key/value pair in the GHashTable. If the function returns TRUE, then the key/value pair is removed from the GHashTable. If you supplied key or value destroy functions when creating the GHashTable, they are used to free the memory allocated for the removed keys and values.
See #GHashTableIterator for an alternative way to loop over the key/value pairs in the hash table.
Return value: the number of key/value pairs removed.
References g_hash_table_foreach_remove_or_steal(), g_return_val_if_fail, NULL, and TRUE.
guint g_hash_table_foreach_steal (GHashTable * hash_table, GHRFunc func, gpointer user_data)
g_hash_table_foreach_steal: : a GHashTable. : the function to call for each key/value pair. : user data to pass to the function.
Calls the given function for each key/value pair in the GHashTable. If the function returns TRUE, then the key/value pair is removed from the GHashTable, but no key or value destroy functions are called.
See #GHashTableIterator for an alternative way to loop over the key/value pairs in the hash table.
Return value: the number of key/value pairs removed.
References FALSE, g_hash_table_foreach_remove_or_steal(), g_return_val_if_fail, and NULL.
GList* g_hash_table_get_keys (GHashTable * hash_table)
g_hash_table_get_keys: : a GHashTable
Retrieves every key inside . The returned data is valid until is modified.
Return value: a GList containing all the keys inside the hash table. The content of the list is owned by the hash table and should not be modified or freed. Use g_list_free() when done using the list.
Since: 2.14
References g_list_prepend(), g_return_val_if_fail, i, _GHashNode::key, _GHashNode::next, and NULL.
GList* g_hash_table_get_values (GHashTable * hash_table)
g_hash_table_get_values: : a GHashTable
Retrieves every value inside . The returned data is valid until is modified.
Return value: a GList containing all the values inside the hash table. The content of the list is owned by the hash table and should not be modified or freed. Use g_list_free() when done using the list.
Since: 2.14
References g_list_prepend(), g_return_val_if_fail, i, _GHashNode::next, NULL, and _GHashNode::value.
void g_hash_table_insert (GHashTable * hash_table, gpointer key, gpointer value)
g_hash_table_insert: : a GHashTable. : a key to insert. : the value to associate with the key.
Inserts a new key and value into a GHashTable.
If the key already exists in the GHashTable its current value is replaced with the new value. If you supplied a when creating the GHashTable, the old value is freed using that function. If you supplied a when creating the GHashTable, the passed key is freed using that function.
References FALSE, and g_hash_table_insert_internal().
Referenced by add_node_to_hash(), add_tile_hash(), atom(), attr_create_hash(), bookmarks_load_hash(), bookmarks_paste_bookmark(), bookmarks_store_bookmarks_to_file(), build_attrmap_line(), build_countrytable(), cache_insert_mru(), cache_trim(), ch_assemble_map(), ch_generate_ddsg(), ch_setup(), csv_create_item(), debug_level_set(), duplicate_insert(), event_qt5_add_timeout(), event_qt5_add_watch(), file_process_headers(), graphics_image_new_scaled_rotated(), gui_gtk_bookmarks_update(), image_new(), item_create_hash(), item_get_default_flags(), item_hash_insert(), linguistics_init(), load_tilesdir(), longest_match_add_match(), map_new_csv(), merge_tile(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), node_buffer_to_hash(), object_new(), ocean_tile(), osm_add_node(), osm_end_way(), osm_protobufdb_string(), overlay_new(), plugin_new(), relations_add_relation_member_entry(), search_add_result(), street_name_get(), string_hash_lookup(), tile_collector_add_siblings2(), tile_collector_process(), tile_collector_process_tile(), tile_extend(), vehicle_add_log(), vehicleprofile_apply_roadprofile(), and write_item_way_subsection_index().
GHashTable* g_hash_table_iter_get_hash_table (GHashTableIter * iter)
g_hash_table_iter_get_hash_table: : an initialized GHashTableIter.
Returns the GHashTable associated with .
Return value: the GHashTable associated with .
Since: 2.16
References g_return_val_if_fail, and NULL.
void g_hash_table_iter_init (GHashTableIter * iter, GHashTable * hash_table)
g_hash_table_iter_init: : an uninitialized GHashTableIter. : a GHashTable.
Initializes a key/value pair iterator and associates it with . Modifying the hash table after calling this function invalidates the returned iterator. |[ GHashTableIter iter; gpointer key, value;
g_hash_table_iter_init (&iter, hash_table); while (g_hash_table_iter_next (&iter, &key, &value)) { / do something with key and value / } ]|
Since: 2.16
References FALSE, g_return_if_fail, RealIter::hash_table, RealIter::node, NULL, RealIter::position, RealIter::pre_advanced, RealIter::prev_node, and RealIter::version.
Referenced by overlay_disable(), and paintOverlays().
gboolean g_hash_table_iter_next (GHashTableIter * iter, gpointer * key, gpointer * value)
g_hash_table_iter_next: : an initialized GHashTableIter. : a location to store the key, or NULL. : a location to store the value, or NULL.
Advances and retrieves the key and/or value that are now pointed to as a result of this advancement. If FALSE is returned, and are not set, and the iterator becomes invalid.
Return value: FALSE if the end of the GHashTable has been reached.
Since: 2.16
References FALSE, g_return_val_if_fail, RealIter::hash_table, _GHashNode::key, _GHashNode::next, RealIter::node, NULL, RealIter::position, RealIter::pre_advanced, RealIter::prev_node, TRUE, _GHashNode::value, and RealIter::version.
Referenced by overlay_disable(), and paintOverlays().
void g_hash_table_iter_remove (GHashTableIter * iter)
g_hash_table_iter_remove(): : an initialized GHashTableIter.
Removes the key/value pair currently pointed to by the iterator from its associated GHashTable. Can only be called after g_hash_table_iter_next() returned TRUE, and cannot be called more than once for the same key/value pair.
If the GHashTable was created using g_hash_table_new_full(), the key and value are freed using the supplied destroy functions, otherwise you have to make sure that any dynamically allocated values are freed yourself.
Since: 2.16
References iter_remove_or_steal(), and TRUE.
void g_hash_table_iter_steal (GHashTableIter * iter)
g_hash_table_iter_steal(): : an initialized GHashTableIter.
Removes the key/value pair currently pointed to by the iterator from its associated GHashTable, without calling the key and value destroy functions. Can only be called after g_hash_table_iter_next() returned TRUE, and cannot be called more than once for the same key/value pair.
Since: 2.16
References FALSE, and iter_remove_or_steal().
gpointer g_hash_table_lookup (GHashTable * hash_table, gconstpointer key)
g_hash_table_lookup: : a GHashTable. : the key to look up.
Looks up a key in a GHashTable. Note that this function cannot distinguish between a key that is not present and one which is present and has the value NULL. If you need this distinction, use g_hash_table_lookup_extended().
Return value: the associated value, or NULL if the key is not found.
References g_hash_table_lookup_node(), g_return_val_if_fail, NULL, and _GHashNode::value.
Referenced by add_node_to_hash(), atom_lookup(), attr_from_name(), bookmarks_store_bookmarks_to_file(), build_attrmap_line(), cache_flush(), cache_lookup(), ch_generate_ddsg(), ch_process_node(), create_tile_hash_list(), debug_level_get(), duplicate_test(), file_http_header(), file_process_headers(), graphics_process_selection_item(), graphics_remove_selection(), gui_gtk_bookmarks_update(), image_new(), item_from_name(), item_get_default_flags(), item_hash_lookup(), linguistics_casefold(), linguistics_get_special(), longest_match_add_key_value(), longest_match_add_match(), map_rect_get_item_byid_csv(), merge_tile(), merge_tiles(), navit_cmd_get_attr_var(), navit_cmd_get_int_var(), object_destroy(), object_get(), object_new(), ocean_tile(), osm_add_node(), osm_end_way(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), osm_update_attr_present(), plugin_new(), push_modified_item(), relations_add_relation_member_entry(), relations_process(), search_add_result(), street_name_get(), string_hash_lookup(), tile_collector_add_siblings2(), tile_collector_process(), tile_data_size(), tile_extend(), tile_sibling_edges(), qt5_navit_timer::timerEvent(), tracking_value(), vehicle_remove_attr(), vehicleprofile_apply_roadprofile(), vehicleprofile_get_roadprofile(), RenderArea::watchEvent(), write_item(), and write_tilesdir().
gboolean g_hash_table_lookup_extended (GHashTable * hash_table, gconstpointer lookup_key, gpointer * orig_key, gpointer * value)
g_hash_table_lookup_extended: : a GHashTable. : the key to look up. : returns the original key. : returns the value associated with the key.
Looks up a key in the GHashTable, returning the original key and the associated value and a gboolean which is TRUE if the key was found. This is useful if you need to free the memory allocated for the original key, for example before calling g_hash_table_remove().
Return value: TRUE if the key was found in the GHashTable.
References FALSE, g_hash_table_lookup_node(), g_return_val_if_fail, _GHashNode::key, NULL, TRUE, and _GHashNode::value.
Referenced by graphics_image_new_scaled_rotated(), image_new(), node_item_get(), osm_protobufdb_string(), qt5_navit_timer::timerEvent(), and write_item_way_subsection_index().
GHashTable* g_hash_table_new (GHashFunc hash_func, GEqualFunc key_equal_func)
g_hash_table_new: : a function to create a hash value from a key. Hash values are used to determine where keys are stored within the GHashTable data structure. The g_direct_hash(), g_int_hash() and g_str_hash() functions are provided for some common types of keys. If hash_func is NULL, g_direct_hash() is used. : a function to check two keys for equality. This is used when looking up keys in the GHashTable. The g_direct_equal(), g_int_equal() and g_str_equal() functions are provided for the most common types of keys. If is NULL, keys are compared directly in a similar fashion to g_direct_equal(), but without the overhead of a function call.
Creates a new GHashTable with a reference count of 1.
Return value: a new GHashTable.
References g_hash_table_new_full(), and NULL.
Referenced by atom_init(), attr_create_hash(), bookmarks_load_hash(), build_attrmap(), build_countrytable(), cache_new(), ch_generate_tiles(), ch_setup(), create_tile_hash(), create_tile_hash_list(), file_init(), graphics_android_new(), graphics_opengl_new(), graphics_qt5_new(), graphics_win32_new(), item_create_hash(), item_get_default_flags(), linguistics_init(), load_tilesdir(), map_rect_new_mg(), navit_cmd_set_int_var(), osm_add_node(), osm_add_way(), osm_protobufdb_start_group(), overlay_new(), parse_option(), phase34(), plugin_init(), plugins_new(), qt5_navit_timer::qt5_navit_timer(), relations_new(), RenderArea::RenderArea(), search_list_get_result(), street_name_get(), string_hash_lookup(), vehicle_new(), and vehicleprofile_clear().
GHashTable* g_hash_table_new_full (GHashFunc hash_func, GEqualFunc key_equal_func, GDestroyNotify key_destroy_func, GDestroyNotify value_destroy_func)
g_hash_table_new_full: : a function to create a hash value from a key. : a function to check two keys for equality. : a function to free the memory allocated for the key used when removing the entry from the GHashTable or NULL if you don't want to supply such a function. : a function to free the memory allocated for the value used when removing the entry from the GHashTable or NULL if you don't want to supply such a function.
Creates a new GHashTable like g_hash_table_new() with a reference count of 1 and allows to specify functions to free the memory allocated for the key and value that get called when removing the entry from the GHashTable.
Return value: a new GHashTable.
References g_direct_hash(), g_new0, g_slice_new, and HASH_TABLE_MIN_SIZE.
Referenced by binfile_item_dup(), bookmarks_store_bookmarks_to_file(), ch_assemble_map(), ch_generate_ddsg(), coord_hash_new(), debug_init(), duplicate_test(), file_process_headers(), g_hash_table_new(), graphics_new(), gui_gtk_bookmarks_update(), item_hash_new(), linguistics_init(), load_changes(), longest_match_new(), map_new_csv(), navit_cmd_set_attr_var(), osm_process_towns(), tile_collector_finish(), and tile_collector_new().
GHashTable* g_hash_table_ref (GHashTable * hash_table)
g_hash_table_ref: : a valid GHashTable.
Atomically increments the reference count of by one. This function is MT-safe and may be called from any thread.
Return value: the passed in GHashTable.
Since: 2.10
References g_atomic_int_add(), g_return_val_if_fail, and NULL.
gboolean g_hash_table_remove (GHashTable * hash_table, gconstpointer key)
g_hash_table_remove: : a GHashTable. : the key to remove.
Removes a key and its associated value from a GHashTable.
If the GHashTable was created using g_hash_table_new_full(), the key and value are freed using the supplied destroy functions, otherwise you have to make sure that any dynamically allocated values are freed yourself.
Return value: TRUE if the key was found and removed from the GHashTable.
References g_hash_table_remove_internal(), and TRUE.
Referenced by cache_remove(), cache_trim(), event_qt5_remove_timeout(), event_qt5_remove_watch(), graphics_destroy(), graphics_remove_selection(), item_hash_remove(), merge_tile(), object_destroy(), quadtree_item_free(), and vehicle_remove_attr().
void g_hash_table_remove_all (GHashTable * hash_table)
g_hash_table_remove_all: : a GHashTable
Removes all keys and their associated values from a GHashTable.
If the GHashTable was created using g_hash_table_new_full(), the keys and values are freed using the supplied destroy functions, otherwise you have to make sure that any dynamically allocated values are freed yourself.
Since: 2.12
References g_hash_table_maybe_resize(), g_hash_table_remove_all_nodes(), g_return_if_fail, NULL, and TRUE.
Referenced by g_hash_table_destroy().
void g_hash_table_replace (GHashTable * hash_table, gpointer key, gpointer value)
g_hash_table_replace: : a GHashTable. : a key to insert. : the value to associate with the key.
Inserts a new key and value into a GHashTable similar to g_hash_table_insert(). The difference is that if the key already exists in the GHashTable, it gets replaced by the new key. If you supplied a when creating the GHashTable, the old value is freed using that function. If you supplied a when creating the GHashTable, the old key is freed using that function.
References g_hash_table_insert_internal(), and TRUE.
Referenced by binfile_item_dup(), load_changes(), and osm_process_towns().
guint g_hash_table_size (GHashTable * hash_table)
g_hash_table_size: : a GHashTable.
Returns the number of elements contained in the GHashTable.
Return value: the number of key/value pairs in the GHashTable.
References g_return_val_if_fail, and NULL.
gboolean g_hash_table_steal (GHashTable * hash_table, gconstpointer key)
g_hash_table_steal: : a GHashTable. : the key to remove.
Removes a key and its associated value from a GHashTable without calling the key and value destroy functions.
Return value: TRUE if the key was found and removed from the GHashTable.
References FALSE, and g_hash_table_remove_internal().
void g_hash_table_steal_all (GHashTable * hash_table)
g_hash_table_steal_all: : a GHashTable.
Removes all keys and their associated values from a GHashTable without calling the key and value destroy functions.
Since: 2.12
References FALSE, g_hash_table_maybe_resize(), g_hash_table_remove_all_nodes(), g_return_if_fail, and NULL.
void g_hash_table_unref (GHashTable * hash_table)
g_hash_table_unref: : a valid GHashTable.
Atomically decrements the reference count of by one. If the reference count drops to 0, all keys and values will be destroyed, and all memory allocated by the hash table is released. This function is MT-safe and may be called from any thread.
Since: 2.10
References g_atomic_int_exchange_and_add(), g_free(), g_hash_table_remove_all_nodes(), g_return_if_fail, g_slice_free, NULL, and TRUE.
Referenced by g_hash_table_destroy().
gboolean g_int_equal (gconstpointer v1, gconstpointer v2)
g_int_equal: : a pointer to a gint key. : a pointer to a gint key to compare with .
Compares the two gint values being pointed to and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using pointers to integers as keys in a GHashTable.
Returns: TRUE if the two keys match.
Referenced by map_new_csv(), and map_rect_new_mg().
guint g_int_hash (gconstpointer v)
g_int_hash: : a pointer to a gint key
Converts a pointer to a gint to a hash value. It can be passed to g_hash_table_new() as the parameter, when using pointers to integers values as keys in a GHashTable.
Returns: a hash value corresponding to the key.
Referenced by map_new_csv(), and map_rect_new_mg().
gboolean g_str_equal (gconstpointer v1, gconstpointer v2)
g_str_equal: : a key : a key to compare with
Compares two strings for byte-by-byte equality and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using strings as keys in a GHashTable.
Returns: TRUE if the two keys match
References gchar.
Referenced by atom_init(), attr_create_hash(), bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), build_attrmap(), build_countrytable(), ch_generate_tiles(), create_tile_hash(), create_tile_hash_list(), debug_init(), duplicate_equal(), file_init(), file_process_headers(), graphics_android_new(), graphics_new(), graphics_opengl_new(), graphics_win32_new(), gui_gtk_bookmarks_update(), item_create_hash(), linguistics_init(), load_tilesdir(), longest_match_new(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), osm_process_towns(), osm_protobufdb_start_group(), phase34(), plugin_init(), plugins_new(), string_hash_lookup(), tile_collector_finish(), and tile_collector_new().
guint g_str_hash (gconstpointer v)
g_str_hash: : a string key
Converts a string to a hash value. It can be passed to g_hash_table_new() as the parameter, when using strings as keys in a GHashTable.
Returns: a hash value corresponding to the key
References p.
Referenced by atom_init(), attr_create_hash(), bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), build_attrmap(), build_countrytable(), ch_generate_tiles(), create_tile_hash(), create_tile_hash_list(), debug_init(), duplicate_hash(), file_init(), file_process_headers(), graphics_android_new(), graphics_new(), graphics_opengl_new(), graphics_win32_new(), gui_gtk_bookmarks_update(), item_create_hash(), linguistics_init(), load_tilesdir(), longest_match_new(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), osm_process_towns(), osm_protobufdb_start_group(), phase34(), plugin_init(), plugins_new(), string_hash_lookup(), tile_collector_finish(), and tile_collector_new().