navit: support/glib/glist.c File Reference
glist.c File Reference
#include "config.h"
#include "glib.h"
#include "galias.h"
#include "galiasdef.c"
Macros
#define _g_list_alloc() g_slice_new (GList)
#define _g_list_alloc0() g_slice_new0 (GList)
#define _g_list_free1(list) g_slice_free (GList, list)
#define __G_LIST_C__
Functions
void g_list_push_allocator (gpointer dummy)
void g_list_pop_allocator (void)
GList * g_list_alloc (void)
void g_list_free (GList *list)
void g_list_free_1 (GList *list)
GList * g_list_append (GList *list, gpointer data)
GList * g_list_prepend (GList *list, gpointer data)
GList * g_list_insert (GList *list, gpointer data, gint position)
GList * g_list_insert_before (GList *list, GList *sibling, gpointer data)
GList * g_list_concat (GList *list1, GList *list2)
GList * g_list_remove (GList *list, gconstpointer data)
GList * g_list_remove_all (GList *list, gconstpointer data)
static GList * _g_list_remove_link (GList *list, GList *link)
GList * g_list_remove_link (GList *list, GList *llink)
GList * g_list_delete_link (GList *list, GList *link_)
GList * g_list_copy (GList *list)
GList * g_list_reverse (GList *list)
GList * g_list_nth (GList *list, guint n)
GList * g_list_nth_prev (GList *list, guint n)
gpointer g_list_nth_data (GList *list, guint n)
GList * g_list_find (GList *list, gconstpointer data)
GList * g_list_find_custom (GList *list, gconstpointer data, GCompareFunc func)
gint g_list_position (GList *list, GList *llink)
gint g_list_index (GList *list, gconstpointer data)
GList * g_list_last (GList *list)
GList * g_list_first (GList *list)
guint g_list_length (GList *list)
void g_list_foreach (GList *list, GFunc func, gpointer user_data)
static GList * g_list_insert_sorted_real (GList *list, gpointer data, GFunc func, gpointer user_data)
GList * g_list_insert_sorted (GList *list, gpointer data, GCompareFunc func)
GList * g_list_insert_sorted_with_data (GList *list, gpointer data, GCompareDataFunc func, gpointer user_data)
static GList * g_list_sort_merge (GList *l1, GList *l2, GFunc compare_func, gpointer user_data)
static GList * g_list_sort_real (GList *list, GFunc compare_func, gpointer user_data)
GList * g_list_sort (GList *list, GCompareFunc compare_func)
GList * g_list_sort_with_data (GList *list, GCompareDataFunc compare_func, gpointer user_data)
Macro Definition Documentation
#define __G_LIST_C__
#define _g_list_alloc () g_slice_new (GList)
Referenced by g_list_append(), g_list_copy(), g_list_insert(), g_list_insert_before(), and g_list_prepend().
#define _g_list_alloc0 () g_slice_new0 (GList)
Referenced by g_list_alloc(), and g_list_insert_sorted_real().
#define _g_list_free1 (list) g_slice_free (GList, list)
Referenced by g_list_delete_link(), g_list_free_1(), g_list_remove(), and g_list_remove_all().
Function Documentation
static GList* _g_list_remove_link (GList * list, GList * link) inline static
References _GList::next, NULL, and _GList::prev.
Referenced by g_list_delete_link(), and g_list_remove_link().
GList* g_list_alloc (void)
References _g_list_alloc0.
Referenced by g_list_insert_before().
GList* g_list_append (GList * list, gpointer data)
g_list_append: : a pointer to a GList : the data for the new element
Adds a new element on to the end of the list.
<note>
The return value is the new start of the list, which may have changed, so make sure you store the new value.
</note>
<note>
Note that g_list_append() has to traverse the entire list to find the end, which is inefficient when adding multiple elements. A common idiom to avoid the inefficiency is to prepend the elements and reverse the list when all elements have been added.
</note>
|[ / Notice that these are initialized to the empty list. / GList *list = NULL, *number_list = NULL;
/ This is a list of strings. / list = g_list_append (list, "first"); list = g_list_append (list, "second");
/ This is a list of integers. / number_list = g_list_append (number_list, GINT_TO_POINTER (27)); number_list = g_list_append (number_list, GINT_TO_POINTER (14)); ]|
Returns: the new start of the GList
References _g_list_alloc, _GList::data, data, g_list_last(), _GList::next, NULL, and _GList::prev.
Referenced by add_aux_tile(), bookmarks_add_bookmark(), bookmarks_append_destinations(), bookmarks_load_hash(), bookmarks_paste_bookmark(), create_buffers(), g_list_insert(), graphics_add_selection(), gui_internal_compute_table_dimensions(), gui_internal_poi_param_clone(), gui_internal_poi_param_set_filter(), gui_internal_widget_append(), item_bin_sink_add_func(), itemgra_add_attr(), itemgra_new(), layer_add_attr(), layout_add_attr(), longest_match_item_new(), longest_match_list_new(), main_real(), map_new_mg(), mapset_add_attr(), navit_add_attr(), navit_add_layout(), navit_add_mapset(), navit_add_vehicle(), navit_nls_add_textdomain(), osd_odometer_new(), parse_filter(), parse_filters(), parse_option(), plugin_new(), process_boundaries_finish(), process_boundaries_setup(), process_turn_restrictions_setup(), read_former_destination_map_as_list(), relations_add_relation_default_entry(), relations_add_relation_member_entry(), route_append_destination(), route_set_destinations(), search_add_result(), search_split_phrases(), set_attr_do(), speech_message_handler(), tile_extend(), and win32_gui_notify().
GList* g_list_concat (GList * list1, GList * list2)
g_list_concat: : a GList : the GList to add to the end of the first GList
Adds the second GList onto the end of the first GList. Note that the elements of the second GList are not copied. They are used directly.
Returns: the start of the new GList
References g_list_last(), _GList::next, and _GList::prev.
Referenced by boundary_find_matches().
GList* g_list_copy (GList * list)
g_list_copy: : a GList
Copies a GList.
<note>
Note that this is a "shallow" copy. If the list elements consist of pointers to data, the pointers are copied but the actual data is not.
</note>
Returns: a copy of
References _g_list_alloc, _GList::data, _GList::next, NULL, and _GList::prev.
Referenced by mapset_dup(), and search_by_address_attr().
GList* g_list_delete_link (GList * list, GList * link_)
g_list_delete_link: : a GList : node to delete from
Removes the node link_ from the list and frees it. Compare this to g_list_remove_link() which removes the node without freeing it.
Returns: the new head of
References _g_list_free1, and _g_list_remove_link().
Referenced by binmap_search_destroy(), csv_attr_set(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), and quadtree_item_next().
GList* g_list_find (GList * list, gconstpointer data)
g_list_find: : a GList : the element data to find
Finds the element in a GList which contains the given data.
Returns: the found GList element, or NULL if it is not found
References _GList::data, and _GList::next.
Referenced by route_previous_destination().
GList* g_list_find_custom (GList * list, gconstpointer data, GCompareFunc func)
g_list_find_custom: : a GList : user data passed to the function : the function to call for each element. It should return 0 when the desired element is found
Finds an element in a GList, using a supplied function to find the desired element. It iterates over the list, calling the given function which should return 0 when the desired element is found. The function takes two gconstpointer arguments, the GList element's data as the first argument and the given user data.
Returns: the found GList element, or NULL if it is not found
References _GList::data, g_return_val_if_fail, _GList::next, and NULL.
GList* g_list_first (GList * list)
g_list_first: : a GList
Gets the first element in a GList.
Returns: the first element in the GList, or NULL if the GList has no elements
References _GList::prev.
Referenced by bookmarks_add_bookmark(), bookmarks_clear_item(), bookmarks_delete_bookmark(), bookmarks_item_rewind(), bookmarks_load_hash(), bookmarks_move_down(), bookmarks_move_root(), bookmarks_paste_bookmark(), bookmarks_store_bookmarks_to_file(), create_tile_hash_list(), find_destination_in_list(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_vehicles_update(), gui_internal_button_attr_update(), gui_internal_cmd_delete_bookmark_folder(), layout_get_cursor(), message_handler(), navit_set_cursors(), navit_set_layout_by_name(), speech_message_handler(), start_speaking(), wave_out(), and write_tilesdir().
void g_list_foreach (GList * list, GFunc func, gpointer user_data)
g_list_foreach: : a GList : the function to call with each element's data : user data to pass to the function
Calls a function for each element of a GList.
References _GList::data, _GList::next, and next.
Referenced by bookmarks_append_destinations(), espeak_destroy(), free_filter(), free_filters(), free_former_destination(), gui_internal_table_pack(), gui_internal_table_render(), longest_match_destroy(), longest_match_list_destroy(), navit_destroy(), process_associated_streets(), process_house_number_interpolations(), route_clear_destinations(), set_attr_do(), and tile_collector_process_tile().
void g_list_free (GList * list)
g_list_free: : a GList
Frees all of the memory used by a GList. The freed elements are returned to the slice allocator.
<note>
If list elements contain dynamically-allocated memory, they should be freed first.
</note>
References g_slice_free_chain, and next.
Referenced by bookmarks_append_destinations(), bookmarks_clear_hash(), callback_list_destroy(), espeak_destroy(), foreach_tile(), free_boundaries(), free_filter(), free_filters(), free_former_destination(), graphics_free(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_vehicles_update(), gui_internal_cmd_position_do(), gui_internal_poi_param_free(), gui_internal_table_pack(), gui_internal_table_render(), gui_internal_widget_children_destroy(), item_bin_sink_destroy(), longest_match_destroy(), longest_match_list_destroy(), main_real(), mapset_destroy(), merge_tiles(), navit_destroy(), osm_process_town_by_boundary(), osm_process_towns(), plugins_destroy(), process_associated_streets(), process_house_number_interpolations(), process_turn_restrictions_finish(), quadtree_item_free_do(), relations_destroy_func(), route_clear_destinations(), search_address_results_free(), search_by_address(), search_by_address_attr(), search_list_search_free(), set_attr_do(), set_columns(), speech_cmdline_search(), speechd_destroy(), speechd_say(), tile_collector_process_tile(), and write_tilesdir().
void g_list_free_1 (GList * list)
g_list_free_1: : a GList element
Frees one GList element. It is usually used after g_list_remove_link().
References _g_list_free1.
gint g_list_index (GList * list, gconstpointer data)
g_list_index: : a GList : the data to find
Gets the position of the element containing the given data (starting from 0).
Returns: the index of the element containing the data, or -1 if the data is not found
References _GList::data, i, and _GList::next.
Referenced by gui_internal_cmd_pois().
GList* g_list_insert (GList * list, gpointer data, gint position)
g_list_insert: : a pointer to a GList : the data for the new element : the position to insert the element. If this is negative, or is larger than the number of elements in the list, the new element is added on to the end of the list.
Inserts a new element into the list at the given position.
Returns: the new start of the GList
References _g_list_alloc, _GList::data, data, g_list_append(), g_list_nth(), g_list_prepend(), _GList::next, and _GList::prev.
GList* g_list_insert_before (GList * list, GList * sibling, gpointer data)
g_list_insert_before: : a pointer to a GList : the list element before which the new element is inserted or NULL to insert at the end of the list : the data for the new element
Inserts a new element into the list before the given position.
Returns: the new start of the GList
References _g_list_alloc, _GList::data, data, g_list_alloc(), g_return_val_if_fail, _GList::next, NULL, and _GList::prev.
GList* g_list_insert_sorted (GList * list, gpointer data, GCompareFunc func)
g_list_insert_sorted: : a pointer to a GList : the data for the new element : the function to compare elements in the list. It should return a number > 0 if the first parameter comes after the second parameter in the sort order.
Inserts a new element into the list, using the given comparison function to determine its position.
Returns: the new start of the GList
References g_list_insert_sorted_real(), and NULL.
Referenced by displaylist_get_clicked_list(), gui_internal_widget_insert_sorted(), and search_by_address_attr().
static GList* g_list_insert_sorted_real (GList * list, gpointer data, GFunc func, gpointer user_data) static
References _g_list_alloc0, cmp(), _GList::data, data, g_return_val_if_fail, _GList::next, NULL, and _GList::prev.
Referenced by g_list_insert_sorted(), and g_list_insert_sorted_with_data().
GList* g_list_insert_sorted_with_data (GList * list, gpointer data, GCompareDataFunc func, gpointer user_data)
g_list_insert_sorted_with_data: : a pointer to a GList : the data for the new element : the function to compare elements in the list. It should return a number > 0 if the first parameter comes after the second parameter in the sort order. : user data to pass to comparison function.
Inserts a new element into the list, using the given comparison function to determine its position.
Returns: the new start of the GList
Since: 2.10
References g_list_insert_sorted_real().
GList* g_list_last (GList * list)
g_list_last: : a GList
Gets the last element in a GList.
Returns: the last element in the GList, or NULL if the GList has no elements
References _GList::next.
Referenced by destination_equal(), g_list_append(), g_list_concat(), gui_internal_cmd_add_bookmark_do(), gui_internal_cmd_add_bookmark_folder_do(), gui_internal_cmd_copy_bookmark(), gui_internal_cmd_cut_bookmark(), gui_internal_cmd_delete_bookmark(), gui_internal_cmd_paste_bookmark(), gui_internal_cmd_rename_bookmark_clicked(), gui_internal_compute_table_dimensions(), gui_internal_highlight(), gui_internal_highlight_do(), gui_internal_html_submit(), gui_internal_keynav_highlight_next(), gui_internal_keypress(), gui_internal_keypress_do(), gui_internal_menu_data(), gui_internal_menu_render(), gui_internal_menu_reset_pack(), gui_internal_poi_param_clone(), gui_internal_prune_menu_count(), gui_internal_prune_menu_do(), gui_internal_search_changed(), gui_internal_search_idle(), gui_internal_top_bar(), merge_tiles(), read_former_destination_map_as_list(), and route_get_dst().
guint g_list_length (GList * list)
g_list_length: : a GList
Gets the number of elements in a GList.
<note>
This function iterates over the whole list to count its elements.
</note>
Returns: the number of elements in the GList
References length, and _GList::next.
Referenced by bookmarks_append_destinations(), bookmarks_load_hash(), bookmarks_move_down(), bookmarks_move_root(), gui_internal_keypress(), merge_tiles(), navit_cmd_int_stack_size(), resize_callback(), route_get_destination_count(), route_graph_update(), route_set_profile(), speech_cmdline_search(), speech_message_handler(), and speechd_say().
GList* g_list_nth (GList * list, guint n)
g_list_nth: : a GList
: the position of the element, counting from 0
Gets the element at the given position in a GList.
Returns: the element, or NULL if the position is off the end of the GList
References _GList::next.
Referenced by bookmarks_append_destinations(), and g_list_insert().
gpointer g_list_nth_data (GList * list, guint n)
g_list_nth_data: : a GList
: the position of the element
Gets the data of the element at the given position.
Returns: the element's data, or NULL if the position is off the end of the GList
References _GList::data, _GList::next, and NULL.
Referenced by route_get_destination_description(), and route_remove_nth_waypoint().
GList* g_list_nth_prev (GList * list, guint n)
g_list_nth_prev: : a GList
: the position of the element, counting from 0
Gets the element
places before .
Returns: the element, or NULL if the position is off the end of the GList
References _GList::prev.
void g_list_pop_allocator (void)
gint g_list_position (GList * list, GList * llink)
g_list_position: : a GList : an element in the GList
Gets the position of the given element in the GList (starting from 0).
Returns: the position of the element in the GList, or -1 if the element is not found
References i, and _GList::next.
Referenced by rm_attr_get().
GList* g_list_prepend (GList * list, gpointer data)
g_list_prepend: : a pointer to a GList : the data for the new element
Adds a new element on to the start of the list.
<note>
The return value is the new start of the list, which may have changed, so make sure you store the new value.
</note>
|[ / Notice that it is initialized to the empty list. / GList *list = NULL; list = g_list_prepend (list, "last"); list = g_list_prepend (list, "first"); ]|
Returns: the new start of the GList
References _g_list_alloc, _GList::data, data, _GList::next, NULL, and _GList::prev.
Referenced by binmap_get_estimated_boundaries(), binmap_search_street_by_place(), boundary_find_matches(), callback_list_add(), csv_attr_set(), csv_create_item(), event_win32_add_timeout(), foreach_tile_func(), g_hash_table_get_keys(), g_hash_table_get_values(), g_list_insert(), geom_poly_segments_insert(), get_tiles_list_func(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_vehicles_update(), gui_internal_top_bar(), gui_internal_widget_prepend(), hash_callback(), hash_callback_key(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), map_new_csv(), navit_cmd_push_int(), osm_process_town_unknown_country(), process_associated_street_member(), process_boundaries_insert(), process_boundaries_member(), process_house_number_interpolation_member(), quadtree_data_dup(), quadtree_find_rect_items(), quadtree_item_next(), quadtree_query(), read_former_destination_map_as_list(), search_by_address_attr(), spawn_process(), speech_cmdline_search(), speechd_new(), tile_data_to_segments(), and town_country_list_insert_if_new().
void g_list_push_allocator (gpointer dummy)
GList* g_list_remove (GList * list, gconstpointer data)
g_list_remove: : a GList : the data of the element to remove
Removes an element from a GList. If two elements contain the same data, only the first is removed. If none of the elements contain the data, the GList is unchanged.
Returns: the new start of the GList
References _g_list_free1, _GList::data, _GList::next, and _GList::prev.
Referenced by bookmarks_delete_bookmark(), callback_list_remove(), event_win32_remove_timeout(), find_destination_in_list(), geom_poly_segments_remove(), graphics_remove_selection(), gui_internal_menu_destroy(), gui_internal_widget_table_clear(), mapset_remove_attr(), plugin_new(), process_boundaries_finish(), process_boundaries_insert(), route_remove_nth_waypoint(), route_remove_waypoint(), run_timer(), spawn_process_info_free(), speech_message_handler(), and wave_out().
GList* g_list_remove_all (GList * list, gconstpointer data)
g_list_remove_all: : a GList : data to remove
Removes all list nodes with data equal to . Returns the new head of the list. Contrast with g_list_remove() which removes only the first node matching the given data.
Returns: new head of
References _g_list_free1, _GList::data, _GList::next, next, and _GList::prev.
Referenced by navit_nls_remove_textdomain().
GList* g_list_remove_link (GList * list, GList * llink)
g_list_remove_link: : a GList : an element in the GList
Removes an element from a GList, without freeing the element. The removed element's prev and next links are set to NULL, so that it becomes a self-contained list with one element.
Returns: the new start of the GList, without the element
References _g_list_remove_link().
Referenced by csv_coord_set(), navit_cmd_int_stack_size(), and navit_cmd_pop_int().
GList* g_list_reverse (GList * list)
g_list_reverse: : a GList
Reverses a GList. It simply switches the next and prev pointers of each element.
Returns: the start of the reversed GList
References _GList::next, NULL, and _GList::prev.
Referenced by read_former_destination_map_as_list().
GList* g_list_sort (GList * list, GCompareFunc compare_func)
g_list_sort: : a GList : the comparison function used to sort the GList. This function is passed the data from 2 elements of the GList and should return 0 if they are equal, a negative value if the first element comes before the second, or a positive value if the first element comes after the second.
Sorts a GList using the given comparison function.
Returns: the start of the sorted GList
References g_list_sort_real(), and NULL.
Referenced by get_tiles_list(), merge_tiles(), and process_boundaries_finish().
static GList* g_list_sort_merge (GList * l1, GList * l2, GFunc compare_func, gpointer user_data) static
References cmp(), _GList::data, _GList::next, NULL, and _GList::prev.
Referenced by g_list_sort_real().
static GList* g_list_sort_real (GList * list, GFunc compare_func, gpointer user_data) static
References g_list_sort_merge(), _GList::next, and NULL.
Referenced by g_list_sort(), and g_list_sort_with_data().
GList* g_list_sort_with_data (GList * list, GCompareDataFunc compare_func, gpointer user_data)
g_list_sort_with_data: : a GList : comparison function : user data to pass to comparison function
Like g_list_sort(), but the comparison function accepts a user data argument.
Returns: the new head of
References g_list_sort_real().