navit: support/wordexp/glob.h File Reference
glob.h File Reference
Data Structures
struct glob_t
Macros
#define GLOB_NOSPACE 1
Functions
int glob (const char *pattern, int flags, int(*errfunc)(const char *epath, int eerrno), glob_t *pglob)
void globfree (glob_t *pglob)
Macro Definition Documentation
#define GLOB_NOSPACE 1
Referenced by glob_recursive().
Function Documentation
int glob (const char * pattern, int flags, int(*)(const char *epath, int eerrno) errfunc, glob_t * pglob)
References glob_t::gl_pathc, glob_t::gl_pathv, glob_recursive(), and NULL.
Referenced by wordexp().
void globfree (glob_t * pglob)
References glob_t::gl_pathc, glob_t::gl_pathv, and i.
Referenced by wordexp().