navit: support/glib/gmem.h File Reference
gmem.h File Reference
#include <glib/gslice.h>
#include <glib/gtypes.h>
Data Structures
struct _GMemVTable
Macros
#define __G_MEM_H__
#define G_MEM_ALIGN GLIB_SIZEOF_LONG
#define g_new(struct_type, n_structs) ((struct_type *) g_malloc (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_new0(struct_type, n_structs) ((struct_type *) g_malloc0 (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_renew(struct_type, mem, n_structs) ((struct_type *) g_realloc ((mem), ((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_try_new(struct_type, n_structs) ((struct_type *) g_try_malloc (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_try_new0(struct_type, n_structs) ((struct_type *) g_try_malloc0 (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_try_renew(struct_type, mem, n_structs) ((struct_type *) g_try_realloc ((mem), ((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_mem_chunk_create(type, pre_alloc, alloc_type)
#define g_chunk_new(type, chunk)
#define g_chunk_new0(type, chunk)
#define g_chunk_free(mem, mem_chunk)
#define G_ALLOC_ONLY 1
#define G_ALLOC_AND_FREE 2
#define G_ALLOCATOR_LIST (1)
#define G_ALLOCATOR_SLIST (2)
#define G_ALLOCATOR_NODE (3)
Typedefs
typedef typedefG_BEGIN_DECLS
struct _GMemVTable GMemVTable
typedef struct _GAllocator GAllocator
typedef struct _GMemChunk GMemChunk
Functions
gpointer g_malloc (gsize n_bytes) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_malloc0 (gsize n_bytes) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_realloc (gpointer mem, gsize n_bytes) G_GNUC_WARN_UNUSED_RESULT
void g_free (gpointer mem)
gpointer g_try_malloc (gsize n_bytes) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_try_malloc0 (gsize n_bytes) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_try_realloc (gpointer mem, gsize n_bytes) G_GNUC_WARN_UNUSED_RESULT
void g_mem_set_vtable (GMemVTable *vtable)
gboolean g_mem_is_system_malloc (void)
void g_mem_profile (void)
GMemChunk * g_mem_chunk_new (const gchar *name, gint atom_size, gsize area_size, gint type)
void g_mem_chunk_destroy (GMemChunk *mem_chunk)
gpointer g_mem_chunk_alloc (GMemChunk *mem_chunk)
gpointer g_mem_chunk_alloc0 (GMemChunk *mem_chunk)
void g_mem_chunk_free (GMemChunk *mem_chunk, gpointer mem)
void g_mem_chunk_clean (GMemChunk *mem_chunk)
void g_mem_chunk_reset (GMemChunk *mem_chunk)
void g_mem_chunk_print (GMemChunk *mem_chunk)
void g_mem_chunk_info (void)
void g_blow_chunks (void)
GAllocator * g_allocator_new (const gchar *name, guint n_preallocs)
void g_allocator_free (GAllocator *allocator)
Variables
GLIB_VAR gboolean g_mem_gc_friendly
GLIB_VAR GMemVTable * glib_mem_profiler_table
Macro Definition Documentation
#define __G_MEM_H__
#define G_ALLOC_AND_FREE 2
#define G_ALLOC_ONLY 1
#define G_ALLOCATOR_LIST (1)
#define G_ALLOCATOR_NODE (3)
#define G_ALLOCATOR_SLIST (2)
#define g_chunk_free (mem, mem_chunk)
Value:
G_STMT_START { \
  g_mem_chunk_free ((mem_chunk), (mem)); \
} G_STMT_END
#define g_chunk_new (type, chunk)
Value:
(\
  (type *) g_mem_chunk_alloc (chunk) \
)
#define g_chunk_new0 (type, chunk)
Value:
(\
  (type *) g_mem_chunk_alloc0 (chunk) \
)
#define G_MEM_ALIGN GLIB_SIZEOF_LONG
#define g_mem_chunk_create (type, pre_alloc, alloc_type)
Value:
(\
  g_mem_chunk_new (#type " mem chunks (" #pre_alloc ")", \
                   sizeof (type), \
                   sizeof (type) * (pre_alloc), \
                   (alloc_type)) \
)
#define g_new (struct_type, n_structs) ((struct_type *) g_malloc (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
Referenced by attr_new_from_text(), binmap_get_estimated_boundaries(), binmap_search_street_by_place(), bookmarks_append_destinations(), convert_to_attrs(), coord_new(), coord_rect_new(), country_search_new(), csv_create_item(), decode_attr_from_iter(), espeak_new(), files_relation_processing_new(), font_freetype_font_new(), font_new(), g_strconcat(), g_strdup(), g_strdupv(), g_strjoin(), g_strjoinv(), g_strndup(), g_strnfill(), g_strsplit(), g_ucs4_to_utf16(), g_utf8_strreverse(), g_utf8_to_ucs4_fast(), g_utf8_to_utf16(), g_vasprintf(), gc_new(), gc_set_dashes(), geom_poly_segments_insert(), get_data(), gmap_new(), graphics_add_selection(), graphics_draw_polygon_clipped(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_projections_init(), gui_gtk_vehicles_update(), gui_internal_cmd2_route_height_profile(), gui_internal_poi_param_clone(), image_create(), item_bin_to_poly_segment(), item_hash_insert(), item_hash_new(), linguistics_casefold(), linguistics_dup_utf8_char(), maneuver_required2(), map_binfile_zip_setup(), map_filter_new(), map_new_csv(), map_new_garmin_img(), map_new_mg(), map_route_occluded_get_buildings(), map_selection_dup_pro(), mapset_open(), maptype_register(), navit_add_former_destinations_from_file(), navit_cmd_push_int(), navit_cmd_set_int_var(), navit_cmd_spawn(), navit_set_destination(), osso_cb_hw_state(), popup_show_item(), quadtree_data_dup(), read_former_destination_map_as_list(), relations_func_new(), relations_member_new(), roadprofile_dup(), route_rect(), search_house_number_coordinate(), search_list_common_dup(), search_list_country_dup(), search_list_result_dup(), search_list_street_new(), search_list_town_new(), search_split_phrases(), set_attr_do(), shell_escape(), spawn_process(), speech_dbus_new(), speechd_new(), speechd_say(), split_string_to_list(), start_element(), and win32_gui_notify().
#define g_new0 (struct_type, n_structs) ((struct_type *) g_malloc0 (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
Referenced by add_aux_tile(), add_menu(), announcement_new(), attr_dup(), attr_generic_add_attr(), attr_generic_prepend_attr(), attr_generic_remove_attr(), attr_generic_set_attr(), attr_list_dup(), attr_new_from_text(), binmap_search_new(), bookmarks_add_bookmark(), bookmarks_append_destinations(), bookmarks_load_hash(), bookmarks_new(), bookmarks_paste_bookmark(), cache_new(), callback_list_new(), circle_new(), coastline_processor_new(), command_new(), command_saved_attr_new(), config_new_int(), create_buffers(), create_destination_window(), csv_coord_set(), csv_create_item(), cursor_new(), download(), event_android_add_timeout(), event_glib_add_idle(), event_glib_add_timeout(), event_glib_add_watch(), event_qt5_add_watch(), event_sdl_add_idle(), event_sdl_add_timeout(), event_sdl_add_watch(), event_sdl_watch_thread(), event_win32_add_timeout(), file_create(), file_wordexp_new(), font_new(), g_hash_table_new_full(), g_hash_table_resize(), g_slice_init_nomessage(), gc_new(), get_data(), gmap_search_new(), graphics_android_new(), graphics_cocoa_new(), graphics_displaylist_new(), graphics_displaylist_open(), graphics_font_new(), graphics_gc_new(), graphics_gd_new(), graphics_gtk_drawing_area_new_helper(), graphics_image_new_scaled_rotated(), graphics_named_font_new(), graphics_new(), graphics_opengl_egl_new(), graphics_opengl_new(), graphics_opengl_new_helper(), graphics_opengl_x11_new(), graphics_overlay_new(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_win32_new_helper(), gui_datawindow_new(), gui_gtk_datawindow_new(), gui_gtk_new(), gui_gtk_statusbar_new(), gui_gtk_ui_new(), gui_internal_add_vehicle_profile(), gui_internal_box_new_with_label(), gui_internal_box_pack(), gui_internal_cmd2_pois(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter_do(), gui_internal_cmd_pois_more(), gui_internal_cmd_pois_selector(), gui_internal_cmd_results_to_map(), gui_internal_compute_table_dimensions(), gui_internal_html_start(), gui_internal_image_new(), gui_internal_keyboard_show_native(), gui_internal_label_font_new(), gui_internal_menu(), gui_internal_new(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), gui_menubar_new(), gui_new(), gui_popup_new(), gui_qml_new(), gui_qt5_qml_new(), image_create(), image_new(), initStatic(), item_bin_sink_func_new(), item_bin_sink_new(), item_new(), itemgra_new(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), layer_new(), layout_attr_iter_new(), layout_new(), log_new(), longest_match_item_new(), longest_match_list_new(), longest_match_new(), make_maneuvers(), map_filter_new(), map_filter_rect_new(), map_new(), map_new_binfile(), map_new_csv(), map_new_shapefile(), map_new_textfile(), map_rect_new(), map_rect_new_binfile_int(), map_rect_new_csv(), map_rect_new_garmin_img(), map_rect_new_mg(), map_rect_new_shapefile(), map_rect_new_textfile(), map_route_occluded_new(), map_route_occluded_rect_new(), map_search_new(), map_search_new_mg(), map_selection_rect_new(), mapset_attr_iter_new(), mapset_new(), mapset_search_new(), menu_add(), message_new(), messagelist_new(), navigation_itm_new(), navigation_itm_ways_update(), navigation_map_new(), navigation_map_rect_new(), navit_add_vehicle(), navit_attr_iter_new(), navit_cmd_get_attr_var(), navit_cmd_get_int_var(), navit_cmd_int_stack_size(), navit_cmd_map_add_curr_pos(), navit_cmd_map_item_set_attr(), navit_cmd_pop_int(), navit_new(), navit_object_attr_iter_new(), ocean_tile(), osd_auxmap_new(), osd_button_new(), osd_cmd_interface_new(), osd_compass_new(), osd_gps_status_new(), osd_image_new(), osd_j1850_new(), osd_marker_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_new(), osd_odometer_new(), osd_rocket_init(), osd_route_guard_new(), osd_scale_new(), osd_speed_cam_new(), osd_speed_warner_new(), osd_stopwatch_new(), osd_text_new(), osd_volume_new(), oti_new(), overlay_new(), parse_filter(), parse_filters(), pedestrian_setup_tilt(), plugin_init(), plugin_new_from_path(), plugins_new(), polygon_new(), polyline_new(), process_boundaries_setup(), process_turn_restrictions_setup(), profile_option_new(), qt5_espeak_new(), quadtree_data_dup(), quadtree_item_next(), quadtree_node_new(), quadtree_query(), read_former_destination_map_as_list(), relations_new(), request_callback_new(), rm_rect_new(), roadprofile_attr_iter_new(), roadprofile_new(), route_attr_iter_new(), route_dup(), route_find_nearest_street(), route_graph_build(), route_map_new_helper(), route_new(), route_path_new(), route_path_new_offroad(), route_set_position_from_tracking(), rp_rect_new(), script_new(), search_list_country_new(), search_list_house_number_dup(), search_list_house_number_new(), search_list_new(), search_list_result_dup(), search_list_street_dup(), search_list_street_new(), search_list_town_dup(), search_list_town_new(), NGQProxy::setAttr(), speech_android_new(), speech_iphone_new(), speechd_new(), text_new(), tile_collector_add_siblings2(), tile_collector_process_tile(), tracking_init_cdf(), tracking_map_new(), tracking_map_rect_new(), tracking_new(), transform_dup(), transform_new(), transform_setup_source_rect(), vehicle_android_new_android(), vehicle_attr_iter_new(), vehicle_demo_new(), vehicle_file_new_file(), vehicle_gpsd_dbus_new(), vehicle_gpsd_new_gpsd(), vehicle_gypsy_new_gypsy(), vehicle_iphone_new(), vehicle_maemo_new_maemo(), vehicle_new(), vehicle_null_new_null(), vehicle_qt5_new_qt5(), vehicle_webos_callback(), vehicle_webos_new(), vehicle_wince_new(), vehicleprofile_attr_iter_new(), vehicleprofile_new(), win32_gui_new(), win32_gui_notify_new(), win32_gui_popup_new(), xi_start_element(), and zip_new().
#define g_renew (struct_type, mem, n_structs) ((struct_type *) g_realloc ((mem), ((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
Referenced by get_font(), longest_match_add_match(), osd_route_guard_init(), and process_turn_restrictions_member().
#define g_try_new (struct_type, n_structs) ((struct_type *) g_try_malloc (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_try_new0 (struct_type, n_structs) ((struct_type *) g_try_malloc0 (((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
#define g_try_renew (struct_type, mem, n_structs) ((struct_type *) g_try_realloc ((mem), ((gsize) sizeof (struct_type)) * ((gsize) (n_structs))))
Typedef Documentation
typedef struct _GAllocator GAllocator
typedef struct _GMemChunk GMemChunk
typedef typedefG_BEGIN_DECLS struct _GMemVTable GMemVTable
Function Documentation
void g_allocator_free (GAllocator * allocator)
GAllocator* g_allocator_new (const gchar * name, guint n_preallocs)
References free_list(), gchar, name, NULL, TRUE, and type.
void g_blow_chunks (void)
void g_free (gpointer mem)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, and glib_mem_vtable.
Referenced by add_menu(), android_search_end(), android_search_idle(), attr_free(), attr_free_content_do(), attr_generic_add_attr(), attr_generic_prepend_attr(), attr_generic_remove_attr(), attr_generic_set_attr(), attr_list_free(), attr_new_from_text(), attr_to_text_ext(), binfile_attr_get(), binfile_extract(), binfile_item_dup(), binmap_search_destroy(), binmap_search_get_item(), binmap_search_new(), bookmarks_clear_item(), bookmarks_copy_bookmark(), bookmarks_destroy(), bookmarks_rename_bookmark(), bookmarks_store_bookmarks_to_file(), build_matches(), button_bookmark(), button_destination(), cache_new(), callback_destroy(), callback_list_destroy(), callback_list_remove_destroy(), ch_assemble_map(), ch_setup(), coastline_processor_finish(), command_evaluate(), command_saved_callbacks_changed(), command_saved_destroy(), command_set_attr(), config_destroy(), coord_destroy(), coord_rect_destroy(), country_search_destroy(), cursor_destroy(), datawindow_destroy(), dbus_cmd_send_signal(), dbus_dump_iter(), dbus_main_navit(), debug_finished(), debug_guard(), debug_init(), debug_new(), decode_attr_from_iter(), destroy_attr(), display_text_draw(), displayitem_draw(), download(), download_directory_do(), download_download(), download_eoc(), download_finish(), download_initial_finish(), download_request(), draw_multiline_osd_text(), dump_coord(), duplicate_test(), encode_attr(), end_element(), espeak_destroy(), espeak_new(), eval_value(), event_glib_call_timeout_single(), event_glib_remove_idle(), event_glib_remove_timeout(), event_glib_remove_watch(), event_qt5_remove_watch(), event_sdl_remove_timeout(), event_sdl_remove_watch(), event_sdl_watch_thread(), event_win32_remove_timeout(), expand_filenames(), face_requester(), file_create(), file_data_free(), file_data_read_compressed(), file_data_remove(), file_destroy(), file_process_headers(), file_wordexp_destroy(), files_relation_processing_destroy(), font_destroy(), font_freetype_font_new(), font_freetype_text_destroy(), Free(), free_boundaries(), free_filter_entry(), free_former_destination(), free_list(), g_ascii_strtod(), g_hash_table_resize(), g_hash_table_unref(), g_set_prgname(), g_slice_free1(), g_slice_free_chain_with_offset(), g_strconcat_printf(), g_strfreev(), gc_destroy(), gc_set_dashes(), geom_poly_segment_destroy(), get_icon(), gmap_new(), graphics_android_new(), graphics_destroy(), graphics_displaylist_close(), graphics_displaylist_destroy(), graphics_displaylist_draw(), graphics_draw_polygon_clipped(), graphics_font_destroy(), graphics_font_destroy_all(), graphics_free(), graphics_gc_destroy(), graphics_image_new_scaled_rotated(), graphics_new(), graphics_opengl_egl_destroy(), graphics_opengl_x11_destroy(), graphics_overlay_new(), graphics_remove_selection(), graphics_sdl_new(), gui_datawindow_new(), gui_gtk_action_activate(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_vehicles_update(), gui_internal_add_attr(), gui_internal_append_attr(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_pois(), gui_internal_cmd2_refresh(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_set(), gui_internal_cmd2_setting_maps(), gui_internal_cmd_add_bookmark_do(), gui_internal_cmd_add_bookmark_folder_do(), gui_internal_cmd_bookmarks(), gui_internal_cmd_debug(), gui_internal_cmd_enter_coord_do(), gui_internal_cmd_escape(), gui_internal_cmd_img(), gui_internal_cmd_log_do(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_match_expand(), gui_internal_cmd_pois(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark_clicked(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_results_to_map(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_cmd_write(), gui_internal_get_match_quality(), gui_internal_html_end(), gui_internal_html_load_href(), gui_internal_html_menu(), gui_internal_html_text(), gui_internal_keyboard_hide_native(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_keypress_do(), gui_internal_label_new_abbrev(), gui_internal_menu_destroy(), gui_internal_onclick(), gui_internal_poi_icon(), gui_internal_poi_param_free(), gui_internal_populate_route_table(), gui_internal_prune_menu_do(), gui_internal_refresh_callback_called(), gui_internal_route_screen_free(), gui_internal_say(), gui_internal_search(), gui_internal_search_cmp(), gui_internal_search_idle(), gui_internal_search_list_set_default_country(), gui_internal_search_town(), gui_internal_search_town_in_country(), gui_internal_select_waypoint(), gui_internal_set(), gui_internal_set_attr(), gui_internal_setup(), gui_internal_table_data_free(), gui_internal_table_pack(), gui_internal_table_render(), gui_internal_text_font_new(), gui_internal_top_bar(), gui_internal_widget_destroy(), gui_menubar_new(), gui_popup_new(), hide_native_keyboard(), house_number_interpolation_clear_current(), image_destroy(), image_free(), image_new(), image_new_helper(), image_new_scaled(), invoke(), item_bin_dump(), item_bin_sink_destroy(), item_bin_sink_func_destroy(), item_bin_sort_compare(), item_bin_sort_file(), item_bin_write_match(), item_hash_destroy(), item_hash_new(), layer_destroy(), layer_new(), layer_set_attr_do(), layout_attr_iter_destroy(), linguistics_compare(), linguistics_expand_special(), linguistics_init(), load_changes(), log_destroy(), log_flush(), longest_match_destroy(), longest_match_item_destroy(), longest_match_list_destroy(), longest_match_new(), main(), main_init(), main_real(), main_setup_environment(), map_binfile_close(), map_binfile_destroy(), map_binfile_download_range(), map_binfile_download_size(), map_binfile_handle_redirect(), map_binfile_http_range(), map_binfile_open(), map_binfile_zip_setup(), map_convert_free(), map_convert_string_tmp(), map_destroy(), map_destroy_csv(), map_destroy_garmin_img(), map_destroy_shapefile(), map_destroy_textfile(), map_filter_destroy(), map_filter_new(), map_filter_rect_destroy(), map_new_csv(), map_new_mg(), map_new_shapefile(), map_new_textfile(), map_rect_destroy(), map_rect_destroy_binfile(), map_rect_destroy_csv(), map_rect_destroy_garmin_img(), map_rect_destroy_mg(), map_rect_destroy_shapefile(), map_rect_destroy_textfile(), map_rect_new(), map_rect_new_shapefile(), map_rect_new_textfile(), map_route_occluded_buildings_free(), map_route_occluded_destroy(), map_route_occluded_rect_destroy(), map_search_cleanup(), map_search_destroy(), map_search_destroy_mg(), map_search_new(), map_search_new_mg(), map_selection_destroy(), maps_new(), mapset_attr_iter_destroy(), mapset_close(), mapset_destroy(), mapset_search_destroy(), menu_add(), merge_tile(), message_cleanup(), message_delete(), mlPDL_ServiceCall_callback(), mlPDL_ServiceCallWithCallback_callback(), navigation_cmd_get_exit_announce(), navigation_destroy(), navigation_destroy_itms_cmds(), navigation_item_destination(), navigation_itm_new(), navigation_itm_ways_clear(), navigation_itm_ways_update(), navigation_map_destroy(), navigation_map_item_attr_get(), navigation_map_rect_destroy(), navit_add_destination_description(), navit_add_former_destinations_from_file(), navit_attr_iter_destroy(), navit_cmd_set_attr_var(), navit_cmd_spawn(), navit_cmd_strjoin(), navit_destroy(), navit_former_destinations_active(), navit_handler_func(), navit_init(), navit_map_progress(), navit_nls_remove_textdomain(), navit_object_attr_iter_destroy(), navit_object_destroy(), navit_set_destination(), navit_set_destinations(), navit_textfile_debug_log(), navit_textfile_debug_log_at(), navit_utf8_strcasecmp(), navit_vehicle_update_position(), notify_destroy(), notify_textchange(), osd_button_new(), osd_button_set_attr(), osd_cmd_interface_set_attr(), osd_compass_draw(), osd_destroy(), osd_gps_status_draw(), osd_image_new(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_new(), osd_odometer_draw(), osd_odometer_from_string(), osd_odometer_new(), osd_odometer_save(), osd_route_guard_destroy(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_warner_draw(), osd_std_config(), osd_std_reconfigure(), osd_text_draw(), osd_text_format_attr(), osd_text_prepare(), osd_text_set_attr(), osd_volume_draw(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), osm_process_towns(), osso_cb_hw_state_idle(), overlay_new(), parse_file(), parse_filters(), parse_option(), pedestrian_draw_arrow(), plugin_destroy(), plugin_get_category(), plugins_destroy(), pngdecode(), popup_printf_cb(), popup_show_attr_val(), popup_traffic_distortion(), private_thread_memory_cleanup(), process_boundaries_finish(), process_boundaries_setup(), process_turn_restrictions_finish(), profile_option_destroy(), qt5_espeak_destroy(), qt5_espeak_init_language(), quadtree_item_free_do(), quadtree_item_next(), quadtree_node_drop_garbage(), quadtree_query_free(), read_former_destinations_from_file(), relations_destroy(), relations_destroy_func(), remove_menu(), request_attr_iter(), request_attr_iter_destroy(), request_callback_destroy_do(), request_get_attr(), resize_ft_buffer(), resolve_object(), result_op(), rm_attr_get(), rm_destroy(), rm_get_item(), rm_rect_destroy(), roadprofile_attr_iter_destroy(), roadprofile_destroy(), route_attr_iter_destroy(), route_calc_selection(), route_destroy(), route_find_nearest_street(), route_free_selection(), route_get_destination_description(), route_graph_destroy(), route_info_free(), route_path_add_item_from_graph(), route_path_destroy(), rp_attr_get(), rp_destroy(), run_timer(), save_map_csv(), save_vehicle_xml(), script_destroy(), sdl_egl_destroy(), sdl_timer_callback(), search_add_result(), search_address_results_free(), search_by_address(), search_by_address_attr(), search_house_number_coordinate(), search_list_common_destroy(), search_list_country_destroy(), search_list_destroy(), search_list_house_number_destroy(), search_list_house_number_new(), search_list_search(), search_list_street_destroy(), search_list_town_destroy(), search_next_house_number_curr_interpol_with_ends(), search_postal_merge_replace(), set_attr_do(), shapefile_attr_get(), show_maneuver(), show_next_maneuvers(), sort_countries(), spawn_process(), spawn_process_compose_cmdline(), spawn_process_info_free(), speech_android_destroy(), speech_android_new(), speech_android_say(), speech_cmdline_search(), speech_dbus_destroy(), speech_iphone_destroy(), speech_message_handler(), speechd_destroy(), speechd_say(), start_element(), start_search(), street_data_free(), street_get_data(), tempfile(), tile_collector_finish(), tile_collector_new(), tile_collector_process_tile(), town_country_destroy(), tracking_destroy(), tracking_flush(), tracking_map_destroy(), tracking_map_item_attr_get(), tracking_map_rect_destroy(), transform_destroy(), transform_setup_source_rect(), vehicle_android_destroy(), vehicle_attr_iter_destroy(), vehicle_demo_destroy(), vehicle_demo_position_attr_get(), vehicle_destroy(), vehicle_file_destroy(), vehicle_file_io(), vehicle_file_open(), vehicle_file_parse(), vehicle_gpsd_callback(), vehicle_gpsd_close(), vehicle_gpsd_dbus_destroy(), vehicle_gpsd_dbus_set_attr_do(), vehicle_gpsd_destroy(), vehicle_gpsd_try_open(), vehicle_gypsy_close(), vehicle_gypsy_destroy(), vehicle_gypsy_try_open(), vehicle_iphone_destroy(), vehicle_log_gpx(), vehicle_log_gpx_add_tag(), vehicle_new(), vehicle_null_destroy(), vehicle_qt5_destroy(), vehicle_set_attr(), vehicle_webos_bt_close(), vehicle_webos_bt_gap_callback(), vehicle_webos_destroy(), vehicle_webos_gps_update(), vehicle_webos_parse_nmea(), vehicle_webos_set_attr_do(), vehicle_wince_destroy(), vehicle_wince_open(), vehicle_wince_parse(), vehicleprofile_attr_iter_destroy(), vehicleprofile_clear(), vehicleprofile_set_attr_do(), write_changes(), write_countrydir(), xdisplay_free(), xi_end_element(), xml_parse_text(), xmlconfig_announce(), xpmdecode(), and zip_destroy().
gpointer g_malloc (gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by Alloc(), attr_dup_content(), binfile_extract(), binfile_item_dup(), create_buffer_with_stride_if_required(), CreateBitmapFromXpm(), display_add(), display_text_draw(), download_start(), duplicate_test(), eval_value(), file_data_read(), file_data_read_compressed(), file_data_read_special(), font_freetype_font_new(), font_freetype_text_new(), g_ascii_strtod(), g_memdup(), g_path_get_basename(), g_slice_alloc(), g_strcompress(), g_strescape(), g_utf16_to_ucs4(), g_utf16_to_utf8(), gc_set_dashes(), gui_gtk_bookmarks_update(), gui_internal_cmd_match_expand(), gui_internal_escape(), gui_internal_label_new_abbrev(), gui_internal_setup(), item_bin_dup(), item_bin_sort_file(), item_get_heightline(), load_changes(), log_set_header(), log_set_trailer(), map_rect_new_shapefile(), map_search_mg_convert_special(), navit_get_attr(), osd_text_draw(), pngdecode(), popup_printf_cb(), replace_suffix(), resize_ft_buffer(), result_set(), route_crossings_get(), rp_rect_new(), search_house_number_interpolation_split(), search_list_country_new(), search_phrase_str(), street_data_dup(), tile_collector_process(), tracking_doupdate_lines(), vehicle_file_new_file(), vehicle_log_binfile(), vehicle_webos_spp_handle_open(), and vehicle_wince_new().
gpointer g_malloc0 (gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by arrows_new(), build_attrmap(), build_attrmap_line(), callback_new_attr(), CreateBitmapFromXpm(), font_freetype_text_new(), icon_new(), image_new(), main(), navit_object_new(), process_associated_streets_setup(), process_house_number_interpolations_setup(), route_path_add_item_from_graph(), route_path_add_line(), thread_memory_from_self(), town_country_new(), and Xpm2bmp_new().
gpointer g_mem_chunk_alloc (GMemChunk * mem_chunk)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_alloc(), and NULL.
gpointer g_mem_chunk_alloc0 (GMemChunk * mem_chunk)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_alloc0(), and NULL.
void g_mem_chunk_clean (GMemChunk * mem_chunk)
void g_mem_chunk_destroy (GMemChunk * mem_chunk)
References g_return_if_fail, g_slice_free, and NULL.
void g_mem_chunk_free (GMemChunk * mem_chunk, gpointer mem)
References _GMemChunk::alloc_size, g_return_if_fail, g_slice_free1(), and NULL.
void g_mem_chunk_info (void)
GMemChunk* g_mem_chunk_new (const gchar * name, gint atom_size, gsize area_size, gint type)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_new, and NULL.
void g_mem_chunk_print (GMemChunk * mem_chunk)
void g_mem_chunk_reset (GMemChunk * mem_chunk)
gboolean g_mem_is_system_malloc (void)
g_mem_is_system_malloc
Checks whether the allocator used by g_malloc() is the system's malloc implementation. If it returns TRUE memory allocated with malloc() can be used interchangeable with memory allocated using g_malloc(). This function is useful for avoiding an extra copy of allocated memory returned by a non-GLib-based API.
A different allocator can be set using g_mem_set_vtable().
Return value: if TRUE, malloc() and g_malloc() can be mixed.
References vtable_set.
Referenced by g_vasprintf().
void g_mem_profile (void)
References FALSE, G_GSIZE_FORMAT, g_mem_init_nomessage(), g_mem_initialized, g_mutex_lock, g_mutex_unlock, g_print(), G_UNLIKELY, gmem_profile_mutex, MEM_PROFILE_TABLE_SIZE, profile_allocs, profile_data, profile_frees, profile_print_locked(), profile_zinit, and TRUE.
Referenced by profiler_calloc(), profiler_malloc(), and profiler_realloc().
void g_mem_set_vtable (GMemVTable * vtable)
References fallback_calloc(), G_STRLOC, g_warning(), glib_mem_vtable, TRUE, and vtable_set.
gpointer g_realloc (gpointer mem, gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by attr_new_from_text(), build_attrmap_line(), command_register_callbacks(), element_add_attr(), linguistics_expand_special(), log_write(), map_new_csv(), navit_add_former_destinations_from_file(), shell_escape(), spawn_process_compose_cmdline(), and street_get_data().
gpointer g_try_malloc (gsize n_bytes)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by g_try_malloc0().
gpointer g_try_malloc0 (gsize n_bytes)
References g_try_malloc().
gpointer g_try_realloc (gpointer mem, gsize n_bytes)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, glib_mem_vtable, and NULL.
Variable Documentation
GLIB_VAR gboolean g_mem_gc_friendly
GLIB_VAR GMemVTable* glib_mem_profiler_table