navit: support/glib/gmem.c File Reference
gmem.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include "glib.h"
#include "gthreadprivate.h"
#include "galias.h"
#include "galiasdef.c"
Data Structures
struct _GMemChunk
Macros
#define MEM_PROFILE_TABLE_SIZE 4096
#define standard_try_malloc standard_malloc
#define standard_try_realloc standard_realloc
#define PROFILE_TABLE(f1, f2, f3) ((((f3) << 2) | ((f2) << 1) | (f1)) * (MEM_PROFILE_TABLE_SIZE + 1))
#define G_ALLOC_ONLY 1
#define G_ALLOC_AND_FREE 2
#define __G_MEM_C__
Typedefs
typedef struct _GAllocator GAllocator
typedef struct _GMemChunk GMemChunk
Enumerations
enum ProfilerJob { PROFILER_FREE = 0, PROFILER_ALLOC = 1, PROFILER_RELOC = 2, PROFILER_ZINIT = 4 }
Functions
static void g_mem_init_nomessage (void)
static gpointer standard_realloc (gpointer mem, gsize n_bytes)
static gpointer standard_malloc (gsize n_bytes)
static void standard_free (gpointer mem)
static gpointer standard_calloc (gsize n_blocks, gsize n_bytes)
gpointer g_malloc (gsize n_bytes)
gpointer g_malloc0 (gsize n_bytes)
gpointer g_realloc (gpointer mem, gsize n_bytes)
void g_free (gpointer mem)
gpointer g_try_malloc (gsize n_bytes)
gpointer g_try_malloc0 (gsize n_bytes)
gpointer g_try_realloc (gpointer mem, gsize n_bytes)
static gpointer fallback_calloc (gsize n_blocks, gsize n_block_bytes)
gboolean g_mem_is_system_malloc (void)
void g_mem_set_vtable (GMemVTable *vtable)
static void profiler_log (ProfilerJob job, gsize n_bytes, gboolean success)
static void profile_print_locked (guint *local_data, gboolean success)
void g_mem_profile (void)
static gpointer profiler_try_malloc (gsize n_bytes)
static gpointer profiler_malloc (gsize n_bytes)
static gpointer profiler_calloc (gsize n_blocks, gsize n_block_bytes)
static void profiler_free (gpointer mem)
static gpointer profiler_try_realloc (gpointer mem, gsize n_bytes)
static gpointer profiler_realloc (gpointer mem, gsize n_bytes)
GMemChunk * g_mem_chunk_new (const gchar *name, gint atom_size, gsize area_size, gint type)
void g_mem_chunk_destroy (GMemChunk *mem_chunk)
gpointer g_mem_chunk_alloc (GMemChunk *mem_chunk)
gpointer g_mem_chunk_alloc0 (GMemChunk *mem_chunk)
void g_mem_chunk_free (GMemChunk *mem_chunk, gpointer mem)
void g_mem_chunk_clean (GMemChunk *mem_chunk)
void g_mem_chunk_reset (GMemChunk *mem_chunk)
void g_mem_chunk_print (GMemChunk *mem_chunk)
void g_mem_chunk_info (void)
void g_blow_chunks (void)
GAllocator * g_allocator_new (const gchar *name, guint n_preallocs)
void g_allocator_free (GAllocator *allocator)
void _g_mem_thread_init_noprivate_nomessage (void)
Variables
static gboolean g_mem_initialized = FALSE
static GMemVTable glib_mem_vtable
static gboolean vtable_set = FALSE
static guint * profile_data = NULL
static gsize profile_allocs = 0
static gsize profile_zinit = 0
static gsize profile_frees = 0
static GMutex * gmem_profile_mutex = NULL
static GMemVTable profiler_table
GMemVTable * glib_mem_profiler_table = &profiler_table
gboolean g_mem_gc_friendly = FALSE
Macro Definition Documentation
#define __G_MEM_C__
#define G_ALLOC_AND_FREE 2
#define G_ALLOC_ONLY 1
#define MEM_PROFILE_TABLE_SIZE 4096
Referenced by g_mem_profile(), profile_print_locked(), and profiler_log().
#define PROFILE_TABLE (f1, f2, f3) ((((f3) << 2) | ((f2) << 1) | (f1)) * (MEM_PROFILE_TABLE_SIZE + 1))
Referenced by profile_print_locked(), and profiler_log().
#define standard_try_malloc standard_malloc
#define standard_try_realloc standard_realloc
Typedef Documentation
typedef struct _GAllocator GAllocator
typedef struct _GMemChunk GMemChunk
Enumeration Type Documentation
enum ProfilerJob
Enumerator
PROFILER_FREE
PROFILER_ALLOC
PROFILER_RELOC
PROFILER_ZINIT
Function Documentation
void _g_mem_thread_init_noprivate_nomessage (void)
References g_mem_init_nomessage(), g_mutex_new, and gmem_profile_mutex.
static gpointer fallback_calloc (gsize n_blocks, gsize n_block_bytes) static
References glib_mem_vtable.
Referenced by g_mem_set_vtable().
void g_allocator_free (GAllocator * allocator)
GAllocator* g_allocator_new (const gchar * name, guint n_preallocs)
References free_list(), gchar, name, NULL, TRUE, and type.
void g_blow_chunks (void)
void g_free (gpointer mem)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, and glib_mem_vtable.
Referenced by add_menu(), android_search_end(), android_search_idle(), attr_free(), attr_free_content_do(), attr_generic_add_attr(), attr_generic_prepend_attr(), attr_generic_remove_attr(), attr_generic_set_attr(), attr_list_free(), attr_new_from_text(), attr_to_text_ext(), binfile_attr_get(), binfile_extract(), binfile_item_dup(), binmap_search_destroy(), binmap_search_get_item(), binmap_search_new(), bookmarks_clear_item(), bookmarks_copy_bookmark(), bookmarks_destroy(), bookmarks_rename_bookmark(), bookmarks_store_bookmarks_to_file(), build_matches(), button_bookmark(), button_destination(), cache_new(), callback_destroy(), callback_list_destroy(), callback_list_remove_destroy(), ch_assemble_map(), ch_setup(), coastline_processor_finish(), command_evaluate(), command_saved_callbacks_changed(), command_saved_destroy(), command_set_attr(), config_destroy(), coord_destroy(), coord_rect_destroy(), country_search_destroy(), cursor_destroy(), datawindow_destroy(), dbus_cmd_send_signal(), dbus_dump_iter(), dbus_main_navit(), debug_finished(), debug_guard(), debug_init(), debug_new(), decode_attr_from_iter(), destroy_attr(), display_text_draw(), displayitem_draw(), download(), download_directory_do(), download_download(), download_eoc(), download_finish(), download_initial_finish(), download_request(), draw_multiline_osd_text(), dump_coord(), duplicate_test(), encode_attr(), end_element(), espeak_destroy(), espeak_new(), eval_value(), event_glib_call_timeout_single(), event_glib_remove_idle(), event_glib_remove_timeout(), event_glib_remove_watch(), event_qt5_remove_watch(), event_sdl_remove_timeout(), event_sdl_remove_watch(), event_sdl_watch_thread(), event_win32_remove_timeout(), expand_filenames(), face_requester(), file_create(), file_data_free(), file_data_read_compressed(), file_data_remove(), file_destroy(), file_process_headers(), file_wordexp_destroy(), files_relation_processing_destroy(), font_destroy(), font_freetype_font_new(), font_freetype_text_destroy(), Free(), free_boundaries(), free_filter_entry(), free_former_destination(), free_list(), g_ascii_strtod(), g_hash_table_resize(), g_hash_table_unref(), g_set_prgname(), g_slice_free1(), g_slice_free_chain_with_offset(), g_strconcat_printf(), g_strfreev(), gc_destroy(), gc_set_dashes(), geom_poly_segment_destroy(), get_icon(), gmap_new(), graphics_android_new(), graphics_destroy(), graphics_displaylist_close(), graphics_displaylist_destroy(), graphics_displaylist_draw(), graphics_draw_polygon_clipped(), graphics_font_destroy(), graphics_font_destroy_all(), graphics_free(), graphics_gc_destroy(), graphics_image_new_scaled_rotated(), graphics_new(), graphics_opengl_egl_destroy(), graphics_opengl_x11_destroy(), graphics_overlay_new(), graphics_remove_selection(), graphics_sdl_new(), gui_datawindow_new(), gui_gtk_action_activate(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_vehicles_update(), gui_internal_add_attr(), gui_internal_append_attr(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_pois(), gui_internal_cmd2_refresh(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_set(), gui_internal_cmd2_setting_maps(), gui_internal_cmd_add_bookmark_do(), gui_internal_cmd_add_bookmark_folder_do(), gui_internal_cmd_bookmarks(), gui_internal_cmd_debug(), gui_internal_cmd_enter_coord_do(), gui_internal_cmd_escape(), gui_internal_cmd_img(), gui_internal_cmd_log_do(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_match_expand(), gui_internal_cmd_pois(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark_clicked(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_results_to_map(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_cmd_write(), gui_internal_get_match_quality(), gui_internal_html_end(), gui_internal_html_load_href(), gui_internal_html_menu(), gui_internal_html_text(), gui_internal_keyboard_hide_native(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_keypress_do(), gui_internal_label_new_abbrev(), gui_internal_menu_destroy(), gui_internal_onclick(), gui_internal_poi_icon(), gui_internal_poi_param_free(), gui_internal_populate_route_table(), gui_internal_prune_menu_do(), gui_internal_refresh_callback_called(), gui_internal_route_screen_free(), gui_internal_say(), gui_internal_search(), gui_internal_search_cmp(), gui_internal_search_idle(), gui_internal_search_list_set_default_country(), gui_internal_search_town(), gui_internal_search_town_in_country(), gui_internal_select_waypoint(), gui_internal_set(), gui_internal_set_attr(), gui_internal_setup(), gui_internal_table_data_free(), gui_internal_table_pack(), gui_internal_table_render(), gui_internal_text_font_new(), gui_internal_top_bar(), gui_internal_widget_destroy(), gui_menubar_new(), gui_popup_new(), hide_native_keyboard(), house_number_interpolation_clear_current(), image_destroy(), image_free(), image_new(), image_new_helper(), image_new_scaled(), invoke(), item_bin_dump(), item_bin_sink_destroy(), item_bin_sink_func_destroy(), item_bin_sort_compare(), item_bin_sort_file(), item_bin_write_match(), item_hash_destroy(), item_hash_new(), layer_destroy(), layer_new(), layer_set_attr_do(), layout_attr_iter_destroy(), linguistics_compare(), linguistics_expand_special(), linguistics_init(), load_changes(), log_destroy(), log_flush(), longest_match_destroy(), longest_match_item_destroy(), longest_match_list_destroy(), longest_match_new(), main(), main_init(), main_real(), main_setup_environment(), map_binfile_close(), map_binfile_destroy(), map_binfile_download_range(), map_binfile_download_size(), map_binfile_handle_redirect(), map_binfile_http_range(), map_binfile_open(), map_binfile_zip_setup(), map_convert_free(), map_convert_string_tmp(), map_destroy(), map_destroy_csv(), map_destroy_garmin_img(), map_destroy_shapefile(), map_destroy_textfile(), map_filter_destroy(), map_filter_new(), map_filter_rect_destroy(), map_new_csv(), map_new_mg(), map_new_shapefile(), map_new_textfile(), map_rect_destroy(), map_rect_destroy_binfile(), map_rect_destroy_csv(), map_rect_destroy_garmin_img(), map_rect_destroy_mg(), map_rect_destroy_shapefile(), map_rect_destroy_textfile(), map_rect_new(), map_rect_new_shapefile(), map_rect_new_textfile(), map_route_occluded_buildings_free(), map_route_occluded_destroy(), map_route_occluded_rect_destroy(), map_search_cleanup(), map_search_destroy(), map_search_destroy_mg(), map_search_new(), map_search_new_mg(), map_selection_destroy(), maps_new(), mapset_attr_iter_destroy(), mapset_close(), mapset_destroy(), mapset_search_destroy(), menu_add(), merge_tile(), message_cleanup(), message_delete(), mlPDL_ServiceCall_callback(), mlPDL_ServiceCallWithCallback_callback(), navigation_cmd_get_exit_announce(), navigation_destroy(), navigation_destroy_itms_cmds(), navigation_item_destination(), navigation_itm_new(), navigation_itm_ways_clear(), navigation_itm_ways_update(), navigation_map_destroy(), navigation_map_item_attr_get(), navigation_map_rect_destroy(), navit_add_destination_description(), navit_add_former_destinations_from_file(), navit_attr_iter_destroy(), navit_cmd_set_attr_var(), navit_cmd_spawn(), navit_cmd_strjoin(), navit_destroy(), navit_former_destinations_active(), navit_handler_func(), navit_init(), navit_map_progress(), navit_nls_remove_textdomain(), navit_object_attr_iter_destroy(), navit_object_destroy(), navit_set_destination(), navit_set_destinations(), navit_textfile_debug_log(), navit_textfile_debug_log_at(), navit_utf8_strcasecmp(), navit_vehicle_update_position(), notify_destroy(), notify_textchange(), osd_button_new(), osd_button_set_attr(), osd_cmd_interface_set_attr(), osd_compass_draw(), osd_destroy(), osd_gps_status_draw(), osd_image_new(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_new(), osd_odometer_draw(), osd_odometer_from_string(), osd_odometer_new(), osd_odometer_save(), osd_route_guard_destroy(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_warner_draw(), osd_std_config(), osd_std_reconfigure(), osd_text_draw(), osd_text_format_attr(), osd_text_prepare(), osd_text_set_attr(), osd_volume_draw(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), osm_process_towns(), osso_cb_hw_state_idle(), overlay_new(), parse_file(), parse_filters(), parse_option(), pedestrian_draw_arrow(), plugin_destroy(), plugin_get_category(), plugins_destroy(), pngdecode(), popup_printf_cb(), popup_show_attr_val(), popup_traffic_distortion(), private_thread_memory_cleanup(), process_boundaries_finish(), process_boundaries_setup(), process_turn_restrictions_finish(), profile_option_destroy(), qt5_espeak_destroy(), qt5_espeak_init_language(), quadtree_item_free_do(), quadtree_item_next(), quadtree_node_drop_garbage(), quadtree_query_free(), read_former_destinations_from_file(), relations_destroy(), relations_destroy_func(), remove_menu(), request_attr_iter(), request_attr_iter_destroy(), request_callback_destroy_do(), request_get_attr(), resize_ft_buffer(), resolve_object(), result_op(), rm_attr_get(), rm_destroy(), rm_get_item(), rm_rect_destroy(), roadprofile_attr_iter_destroy(), roadprofile_destroy(), route_attr_iter_destroy(), route_calc_selection(), route_destroy(), route_find_nearest_street(), route_free_selection(), route_get_destination_description(), route_graph_destroy(), route_info_free(), route_path_add_item_from_graph(), route_path_destroy(), rp_attr_get(), rp_destroy(), run_timer(), save_map_csv(), save_vehicle_xml(), script_destroy(), sdl_egl_destroy(), sdl_timer_callback(), search_add_result(), search_address_results_free(), search_by_address(), search_by_address_attr(), search_house_number_coordinate(), search_list_common_destroy(), search_list_country_destroy(), search_list_destroy(), search_list_house_number_destroy(), search_list_house_number_new(), search_list_search(), search_list_street_destroy(), search_list_town_destroy(), search_next_house_number_curr_interpol_with_ends(), search_postal_merge_replace(), set_attr_do(), shapefile_attr_get(), show_maneuver(), show_next_maneuvers(), sort_countries(), spawn_process(), spawn_process_compose_cmdline(), spawn_process_info_free(), speech_android_destroy(), speech_android_new(), speech_android_say(), speech_cmdline_search(), speech_dbus_destroy(), speech_iphone_destroy(), speech_message_handler(), speechd_destroy(), speechd_say(), start_element(), start_search(), street_data_free(), street_get_data(), tempfile(), tile_collector_finish(), tile_collector_new(), tile_collector_process_tile(), town_country_destroy(), tracking_destroy(), tracking_flush(), tracking_map_destroy(), tracking_map_item_attr_get(), tracking_map_rect_destroy(), transform_destroy(), transform_setup_source_rect(), vehicle_android_destroy(), vehicle_attr_iter_destroy(), vehicle_demo_destroy(), vehicle_demo_position_attr_get(), vehicle_destroy(), vehicle_file_destroy(), vehicle_file_io(), vehicle_file_open(), vehicle_file_parse(), vehicle_gpsd_callback(), vehicle_gpsd_close(), vehicle_gpsd_dbus_destroy(), vehicle_gpsd_dbus_set_attr_do(), vehicle_gpsd_destroy(), vehicle_gpsd_try_open(), vehicle_gypsy_close(), vehicle_gypsy_destroy(), vehicle_gypsy_try_open(), vehicle_iphone_destroy(), vehicle_log_gpx(), vehicle_log_gpx_add_tag(), vehicle_new(), vehicle_null_destroy(), vehicle_qt5_destroy(), vehicle_set_attr(), vehicle_webos_bt_close(), vehicle_webos_bt_gap_callback(), vehicle_webos_destroy(), vehicle_webos_gps_update(), vehicle_webos_parse_nmea(), vehicle_webos_set_attr_do(), vehicle_wince_destroy(), vehicle_wince_open(), vehicle_wince_parse(), vehicleprofile_attr_iter_destroy(), vehicleprofile_clear(), vehicleprofile_set_attr_do(), write_changes(), write_countrydir(), xdisplay_free(), xi_end_element(), xml_parse_text(), xmlconfig_announce(), xpmdecode(), and zip_destroy().
gpointer g_malloc (gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by Alloc(), attr_dup_content(), binfile_extract(), binfile_item_dup(), create_buffer_with_stride_if_required(), CreateBitmapFromXpm(), display_add(), display_text_draw(), download_start(), duplicate_test(), eval_value(), file_data_read(), file_data_read_compressed(), file_data_read_special(), font_freetype_font_new(), font_freetype_text_new(), g_ascii_strtod(), g_memdup(), g_path_get_basename(), g_slice_alloc(), g_strcompress(), g_strescape(), g_utf16_to_ucs4(), g_utf16_to_utf8(), gc_set_dashes(), gui_gtk_bookmarks_update(), gui_internal_cmd_match_expand(), gui_internal_escape(), gui_internal_label_new_abbrev(), gui_internal_setup(), item_bin_dup(), item_bin_sort_file(), item_get_heightline(), load_changes(), log_set_header(), log_set_trailer(), map_rect_new_shapefile(), map_search_mg_convert_special(), navit_get_attr(), osd_text_draw(), pngdecode(), popup_printf_cb(), replace_suffix(), resize_ft_buffer(), result_set(), route_crossings_get(), rp_rect_new(), search_house_number_interpolation_split(), search_list_country_new(), search_phrase_str(), street_data_dup(), tile_collector_process(), tracking_doupdate_lines(), vehicle_file_new_file(), vehicle_log_binfile(), vehicle_webos_spp_handle_open(), and vehicle_wince_new().
gpointer g_malloc0 (gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by arrows_new(), build_attrmap(), build_attrmap_line(), callback_new_attr(), CreateBitmapFromXpm(), font_freetype_text_new(), icon_new(), image_new(), main(), navit_object_new(), process_associated_streets_setup(), process_house_number_interpolations_setup(), route_path_add_item_from_graph(), route_path_add_line(), thread_memory_from_self(), town_country_new(), and Xpm2bmp_new().
gpointer g_mem_chunk_alloc (GMemChunk * mem_chunk)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_alloc(), and NULL.
gpointer g_mem_chunk_alloc0 (GMemChunk * mem_chunk)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_alloc0(), and NULL.
void g_mem_chunk_clean (GMemChunk * mem_chunk)
void g_mem_chunk_destroy (GMemChunk * mem_chunk)
References g_return_if_fail, g_slice_free, and NULL.
void g_mem_chunk_free (GMemChunk * mem_chunk, gpointer mem)
References _GMemChunk::alloc_size, g_return_if_fail, g_slice_free1(), and NULL.
void g_mem_chunk_info (void)
GMemChunk* g_mem_chunk_new (const gchar * name, gint atom_size, gsize area_size, gint type)
References _GMemChunk::alloc_size, g_return_val_if_fail, g_slice_new, and NULL.
void g_mem_chunk_print (GMemChunk * mem_chunk)
void g_mem_chunk_reset (GMemChunk * mem_chunk)
static void g_mem_init_nomessage (void) static
References _g_getenv_nomalloc(), g_mem_gc_friendly, g_mem_initialized, G_N_ELEMENTS, g_parse_debug_string(), gchar, and TRUE.
Referenced by _g_mem_thread_init_noprivate_nomessage(), g_free(), g_malloc(), g_malloc0(), g_mem_profile(), g_realloc(), g_try_malloc(), and g_try_realloc().
gboolean g_mem_is_system_malloc (void)
g_mem_is_system_malloc
Checks whether the allocator used by g_malloc() is the system's malloc implementation. If it returns TRUE memory allocated with malloc() can be used interchangeable with memory allocated using g_malloc(). This function is useful for avoiding an extra copy of allocated memory returned by a non-GLib-based API.
A different allocator can be set using g_mem_set_vtable().
Return value: if TRUE, malloc() and g_malloc() can be mixed.
References vtable_set.
Referenced by g_vasprintf().
void g_mem_profile (void)
References FALSE, G_GSIZE_FORMAT, g_mem_init_nomessage(), g_mem_initialized, g_mutex_lock, g_mutex_unlock, g_print(), G_UNLIKELY, gmem_profile_mutex, MEM_PROFILE_TABLE_SIZE, profile_allocs, profile_data, profile_frees, profile_print_locked(), profile_zinit, and TRUE.
Referenced by profiler_calloc(), profiler_malloc(), and profiler_realloc().
void g_mem_set_vtable (GMemVTable * vtable)
References fallback_calloc(), G_STRLOC, g_warning(), glib_mem_vtable, TRUE, and vtable_set.
gpointer g_realloc (gpointer mem, gsize n_bytes)
References g_error(), G_GSIZE_FORMAT, G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_STRLOC, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by attr_new_from_text(), build_attrmap_line(), command_register_callbacks(), element_add_attr(), linguistics_expand_special(), log_write(), map_new_csv(), navit_add_former_destinations_from_file(), shell_escape(), spawn_process_compose_cmdline(), and street_get_data().
gpointer g_try_malloc (gsize n_bytes)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, glib_mem_vtable, and NULL.
Referenced by g_try_malloc0().
gpointer g_try_malloc0 (gsize n_bytes)
References g_try_malloc().
gpointer g_try_realloc (gpointer mem, gsize n_bytes)
References G_LIKELY, g_mem_init_nomessage(), g_mem_initialized, G_UNLIKELY, glib_mem_vtable, and NULL.
static void profile_print_locked (guint * local_data, gboolean success) static
References FALSE, g_print(), i, MEM_PROFILE_TABLE_SIZE, PROFILE_TABLE, and TRUE.
Referenced by g_mem_profile().
static gpointer profiler_calloc (gsize n_blocks, gsize n_block_bytes) static
References FALSE, g_mem_profile(), p, PROFILER_ALLOC, profiler_log(), PROFILER_ZINIT, standard_calloc(), and TRUE.
static void profiler_free (gpointer mem) static
References FALSE, G_GSIZE_FORMAT, g_warning(), p, PROFILER_FREE, profiler_log(), and TRUE.
static void profiler_log (ProfilerJob job, gsize n_bytes, gboolean success) static
References g_mutex_lock, g_mutex_unlock, gmem_profile_mutex, MEM_PROFILE_TABLE_SIZE, profile_allocs, profile_data, profile_frees, PROFILE_TABLE, profile_zinit, PROFILER_ALLOC, PROFILER_RELOC, PROFILER_ZINIT, and standard_calloc().
Referenced by profiler_calloc(), profiler_free(), profiler_try_malloc(), and profiler_try_realloc().
static gpointer profiler_malloc (gsize n_bytes) static
References g_mem_profile(), and profiler_try_malloc().
static gpointer profiler_realloc (gpointer mem, gsize n_bytes) static
References g_mem_profile(), and profiler_try_realloc().
static gpointer profiler_try_malloc (gsize n_bytes) static
References FALSE, p, PROFILER_ALLOC, profiler_log(), standard_malloc(), and TRUE.
Referenced by profiler_malloc().
static gpointer profiler_try_realloc (gpointer mem, gsize n_bytes) static
References FALSE, G_GSIZE_FORMAT, g_warning(), NULL, p, PROFILER_ALLOC, PROFILER_FREE, profiler_log(), PROFILER_RELOC, standard_realloc(), and TRUE.
Referenced by profiler_realloc().
static gpointer standard_calloc (gsize n_blocks, gsize n_bytes) static
References calloc().
Referenced by profiler_calloc(), and profiler_log().
static void standard_free (gpointer mem) static
static gpointer standard_malloc (gsize n_bytes) static
Referenced by profiler_try_malloc().
static gpointer standard_realloc (gpointer mem, gsize n_bytes) static
Referenced by profiler_try_realloc().
Variable Documentation
gboolean g_mem_gc_friendly = FALSE
Referenced by g_mem_init_nomessage(), g_slice_free1(), and g_slice_free_chain_with_offset().
gboolean g_mem_initialized = FALSE static
Referenced by g_free(), g_malloc(), g_malloc0(), g_mem_init_nomessage(), g_mem_profile(), g_realloc(), g_try_malloc(), and g_try_realloc().
GMemVTable* glib_mem_profiler_table = &profiler_table
GMemVTable glib_mem_vtable static
Initial value:
= {
  standard_malloc,
  standard_realloc,
  standard_free,
  standard_calloc,
  standard_try_malloc,
  standard_try_realloc,
}
Referenced by fallback_calloc(), g_free(), g_malloc(), g_malloc0(), g_mem_set_vtable(), g_realloc(), g_try_malloc(), and g_try_realloc().
GMutex* gmem_profile_mutex = NULL static
Referenced by _g_mem_thread_init_noprivate_nomessage(), g_mem_profile(), and profiler_log().
gsize profile_allocs = 0 static
Referenced by g_mem_profile(), and profiler_log().
guint* profile_data = NULL static
Referenced by g_mem_profile(), and profiler_log().
gsize profile_frees = 0 static
Referenced by g_mem_profile(), and profiler_log().
gsize profile_zinit = 0 static
Referenced by g_mem_profile(), and profiler_log().
GMemVTable profiler_table static
Initial value:
= {
  profiler_malloc,
  profiler_realloc,
  profiler_free,
  profiler_calloc,
  profiler_try_malloc,
  profiler_try_realloc,
}
gboolean vtable_set = FALSE static
Referenced by g_mem_is_system_malloc(), and g_mem_set_vtable().