navit: support/libc/gmtime.c File Reference
gmtime.c File Reference
#include "timeutil.h"
Functions
struct tm * gmtime (const time_t *t)
Function Documentation
struct tm* gmtime (const time_t * t)
References __SYSTEMTIME_to_tm(), and __time_t_to_FILETIME().
Referenced by current_to_iso8601(), o5m_print_version(), osd_text_format_attr(), and vehicle_android_position_callback().