navit: support/glib/gprintf.h File Reference
gprintf.h File Reference
#include <glib.h>
#include <stdio.h>
#include <stdarg.h>
Functions
G_BEGIN_DECLS gint g_printf (gchar const *format,...) G_GNUC_PRINTF(1
G_BEGIN_DECLS gint gint g_fprintf (FILE *file, gchar const *format,...) G_GNUC_PRINTF(2
G_BEGIN_DECLS gint gint gint g_sprintf (gchar *string, gchar const *format,...) G_GNUC_PRINTF(2
G_BEGIN_DECLS gint gint gint gint g_vprintf (gchar const *format, va_list args)
gint g_vfprintf (FILE *file, gchar const *format, va_list args)
gint g_vsprintf (gchar *string, gchar const *format, va_list args)
gint g_vasprintf (gchar **string, gchar const *format, va_list args)
Function Documentation
G_BEGIN_DECLS gint gint g_fprintf (FILE * file, gchar const * format, ...)
G_BEGIN_DECLS gint g_printf (gchar const * format, ...)
G_BEGIN_DECLS gint gint gint g_sprintf (gchar * string, gchar const * format, ...)
gint g_vasprintf (gchar ** string, gchar const * format, va_list args)
g_vasprintf: : the return location for the newly-allocated string. : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the GNU vasprintf() function which supports positional parameters, as specified in the Single Unix Specification. This function is similar to g_vsprintf(), except that it allocates a string to hold the output, instead of putting the output in a buffer you allocate in advance.
Returns: the number of bytes printed.
Since: 2.4
References _g_vsprintf, g_mem_is_system_malloc(), g_new, g_printf_string_upper_bound(), g_return_val_if_fail, g_strndup(), G_VA_COPY, gchar, and NULL.
Referenced by g_strdup_vprintf().
gint g_vfprintf (FILE * file, gchar const * format, va_list args)
References _g_vfprintf, g_return_val_if_fail, and NULL.
Referenced by g_fprintf().
G_BEGIN_DECLS gint gint gint gint g_vprintf (gchar const * format, va_list args)
g_vprintf: : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the standard vprintf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References _g_vprintf, g_return_val_if_fail, and NULL.
Referenced by g_printf().
gint g_vsprintf (gchar * string, gchar const * format, va_list args)
g_vsprintf: : the buffer to hold the output. : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the standard vsprintf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References _g_vsprintf, g_return_val_if_fail, and NULL.
Referenced by g_sprintf().