navit: support/glib/gprintf.c File Reference
gprintf.c File Reference
#include "config.h"
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include "glib.h"
#include "gprintf.h"
#include "gprintfint.h"
#include "galias.h"
#include "galiasdef.c"
Macros
#define _GNU_SOURCE /* For vasprintf */
#define __G_PRINTF_C__
Functions
gint g_printf (gchar const *format,...)
gint g_fprintf (FILE *file, gchar const *format,...)
gint g_sprintf (gchar *string, gchar const *format,...)
gint g_snprintf (gchar *string, gulong n, gchar const *format,...)
gint g_vprintf (gchar const *format, va_list args)
gint g_vfprintf (FILE *file, gchar const *format, va_list args)
gint g_vsprintf (gchar *string, gchar const *format, va_list args)
gint g_vsnprintf (gchar *string, gulong n, gchar const *format, va_list args)
gint g_vasprintf (gchar **string, gchar const *format, va_list args)
Macro Definition Documentation
#define __G_PRINTF_C__
#define _GNU_SOURCE /* For vasprintf */
Function Documentation
gint g_fprintf (FILE * file, gchar const * format, ...)
References g_vfprintf().
gint g_printf (gchar const * format, ...)
g_printf: : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the arguments to insert in the output.
An implementation of the standard printf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References g_vprintf().
gint g_snprintf (gchar * string, gulong n, gchar const * format, ...)
g_snprintf: : the buffer to hold the output.
: the maximum number of bytes to produce (including the terminating nul character). : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the arguments to insert in the output.
A safer form of the standard sprintf() function. The output is guaranteed to not exceed
characters (including the terminating nul character), so it is easy to ensure that a buffer overflow cannot occur.
See also g_strdup_printf().
In versions of GLib prior to 1.2.3, this function may return -1 if the output was truncated, and the truncated string may not be nul-terminated. In versions prior to 1.3.12, this function returns the length of the output string.
The return value of g_snprintf() conforms to the snprintf() function as standardized in ISO C99. Note that this is different from traditional snprintf(), which returns the length of the output string.
The format string may contain positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes which would be produced if the buffer was large enough.
References g_vsnprintf().
Referenced by coord_format(), ezxml_err(), osd_speed_warner_draw(), osd_stopwatch_draw(), and serial_io_init().
gint g_sprintf (gchar * string, gchar const * format, ...)
g_sprintf: : A pointer to a memory buffer to contain the resulting string. It is up to the caller to ensure that the allocated buffer is large enough to hold the formatted result : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the arguments to insert in the output.
An implementation of the standard sprintf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References g_vsprintf().
gint g_vasprintf (gchar ** string, gchar const * format, va_list args)
g_vasprintf: : the return location for the newly-allocated string. : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the GNU vasprintf() function which supports positional parameters, as specified in the Single Unix Specification. This function is similar to g_vsprintf(), except that it allocates a string to hold the output, instead of putting the output in a buffer you allocate in advance.
Returns: the number of bytes printed.
Since: 2.4
References _g_vsprintf, g_mem_is_system_malloc(), g_new, g_printf_string_upper_bound(), g_return_val_if_fail, g_strndup(), G_VA_COPY, gchar, and NULL.
Referenced by g_strdup_vprintf().
gint g_vfprintf (FILE * file, gchar const * format, va_list args)
References _g_vfprintf, g_return_val_if_fail, and NULL.
Referenced by g_fprintf().
gint g_vprintf (gchar const * format, va_list args)
g_vprintf: : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the standard vprintf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References _g_vprintf, g_return_val_if_fail, and NULL.
Referenced by g_printf().
gint g_vsnprintf (gchar * string, gulong n, gchar const * format, va_list args)
g_vsnprintf: : the buffer to hold the output.
: the maximum number of bytes to produce (including the terminating nul character). : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
A safer form of the standard vsprintf() function. The output is guaranteed to not exceed
characters (including the terminating nul character), so it is easy to ensure that a buffer overflow cannot occur.
See also g_strdup_vprintf().
In versions of GLib prior to 1.2.3, this function may return -1 if the output was truncated, and the truncated string may not be nul-terminated. In versions prior to 1.3.12, this function returns the length of the output string.
The return value of g_vsnprintf() conforms to the vsnprintf() function as standardized in ISO C99. Note that this is different from traditional vsnprintf(), which returns the length of the output string.
The format string may contain positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes which would be produced if the buffer was large enough.
References _g_vsnprintf, g_return_val_if_fail, and NULL.
Referenced by ezxml_err(), g_snprintf(), and log_printf().
gint g_vsprintf (gchar * string, gchar const * format, va_list args)
g_vsprintf: : the buffer to hold the output. : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
An implementation of the standard vsprintf() function which supports positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes printed.
Since: 2.2
References _g_vsprintf, g_return_val_if_fail, and NULL.
Referenced by g_sprintf().