navit: graphics/cocoa/graphics_cocoa.m File Reference
graphics_cocoa.m File Reference
#include <glib.h>
#include "config.h"
#include "config_.h"
#include "debug.h"
#include "plugin.h"
#include "point.h"
#include "window.h"
#include "graphics.h"
#include "event.h"
#include "item.h"
#include "callback.h"
#include "color.h"
#include <iconv.h>
#import <Cocoa/Cocoa.h>
Data Structures
class NavitView
struct graphics_priv
struct graphics_gc_priv
struct graphics_font_priv
class NavitViewController
class NavitAppDelegate
class NavitTimer
struct event_idle
Macros
#define USE_UIKIT 0
#define UIView NSView
#define UIViewController NSViewController
#define UIApplicationDelegate NSApplicationDelegate
#define UIWindow NSWindow
#define UIApplication NSApplication
#define UIApplicationMain(a, b, c, d) NSApplicationMain(a,b)
#define UIScreen NSScreen
#define UIEvent NSEvent
#define applicationFrame frame
#define REVERSE_Y 1
Functions
CGContextRef current_context (void)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void font_destroy (struct graphics_font_priv *font)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static struct graphics_font_priv * font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static struct graphics_image_priv * image_new (struct graphics_priv *gra, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void * get_data (struct graphics_priv *this, const char *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void overlay_disable (struct graphics_priv *gr, int disabled)
struct graphics_priv * graphics_cocoa_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
static void event_cocoa_main_loop_run (void)
static struct event_timeout * event_cocoa_add_timeout (int timeout, int multi, struct callback *cb)
static void event_cocoa_remove_timeout (struct event_timeout *ev)
static struct event_idle * event_cocoa_add_idle (int priority, struct callback *cb)
static void event_cocoa_remove_idle (struct event_idle *ev)
static struct event_priv * event_cocoa_new (struct event_methods *meth)
void plugin_init (void)
Variables
static struct graphics_priv * global_graphics_cocoa
iconv_t utf8_macosroman
static struct graphics_font_methods font_methods
static struct graphics_gc_methods gc_methods
static struct graphics_methods graphics_methods
static struct event_methods event_cocoa_methods
Macro Definition Documentation
#define applicationFrame frame
#define REVERSE_Y 1
#define UIApplication NSApplication
#define UIApplicationDelegate NSApplicationDelegate
#define UIApplicationMain (a, b, c, d) NSApplicationMain(a,b)
Referenced by event_cocoa_main_loop_run(), and main().
#define UIEvent NSEvent
#define UIScreen NSScreen
#define UIView NSView
#define UIViewController NSViewController
#define UIWindow NSWindow
#define USE_UIKIT 0
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
CGContextRef current_context (void)
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_priv::cleanup, p, graphics_priv::p, graphics_priv::pclean, point::x, and point::y.
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_priv::layer_context, point::x, and point::y.
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References i, graphics_priv::layer_context, graphics_gc_priv::rgba, graphics_gc_priv::w, point::x, and point::y.
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References dbg, draw_mode_end, and graphics_priv::parent.
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References i, graphics_priv::layer_context, graphics_gc_priv::rgba, point::x, and point::y.
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References dbg, graphics_priv::h, graphics_priv::layer_context, graphics_gc_priv::rgba, graphics_priv::w, point::x, and point::y.
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References graphics_priv::layer_context, graphics_font_priv::name, graphics_gc_priv::rgba, graphics_font_priv::size, utf8_macosroman, point::x, and point::y.
static struct event_idle* event_cocoa_add_idle (int priority, struct callback * cb) static
References event_idle::cb, NavitTimer::cb, dbg, and NavitTimer::timer.
static struct event_timeout* event_cocoa_add_timeout (int timeout, int multi, struct callback * cb) static
References event_timeout::cb, NavitTimer::cb, dbg, and NavitTimer::timer.
static void event_cocoa_main_loop_run (void) static
References dbg, main_argc, main_argv, and UIApplicationMain.
static struct event_priv* event_cocoa_new (struct event_methods * meth) static
References dbg, event_cocoa_methods, and NULL.
Referenced by plugin_init().
static void event_cocoa_remove_idle (struct event_idle * ev) static
static void event_cocoa_remove_timeout (struct event_timeout * ev) static
static void font_destroy (struct graphics_font_priv * font) static
References g_free().
static struct graphics_font_priv* font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * font, int size, int flags) static
References font_methods, g_new0, graphics_font_priv::name, graphics_font_priv::size, and size.
static void gc_destroy (struct graphics_gc_priv * gc) static
References g_free().
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References g_new, gc_methods, and graphics_gc_priv::w.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, color::g, color::r, and graphics_gc_priv::rgba.
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_priv::w.
static void* get_data (struct graphics_priv * this, const char * type) static
References dbg, and NULL.
static void get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate) static
References g_utf8_strlen(), graphics_font_priv::size, point::x, and point::y.
struct graphics_priv* graphics_cocoa_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl)
References cbl, graphics_priv::cbl, dbg, event_request_system(), g_new0, global_graphics_cocoa, graphics_methods, and NULL.
Referenced by plugin_init().
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
static struct graphics_image_priv* image_new (struct graphics_priv * gra, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References dbg, image, NULL, point::x, and point::y.
static void overlay_disable (struct graphics_priv * gr, int disabled) static
References graphics_priv::overlay_disabled.
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References g_new0, graphics_methods, graphics_priv::h, graphics_priv::next, graphics_priv::overlays, p, graphics_priv::p, graphics_priv::parent, graphics_priv::w, and graphics_priv::wraparound.
void plugin_init (void)
References dbg, event_cocoa_new(), and graphics_cocoa_new().
Variable Documentation
struct event_methods event_cocoa_methods static
Initial value:
= {
        event_cocoa_main_loop_run,
        NULL,
        NULL,
        NULL,
        event_cocoa_add_timeout,
        event_cocoa_remove_timeout,
        event_cocoa_add_idle,
        event_cocoa_remove_idle,
        NULL,
}
Referenced by event_cocoa_new().
struct graphics_font_methods font_methods static
Initial value:
= {
        font_destroy
}
Referenced by font_new().
struct graphics_gc_methods gc_methods static
Initial value:
= {
        gc_destroy,
        gc_set_linewidth,
        gc_set_dashes,
        gc_set_foreground,
        gc_set_background,
}
Referenced by gc_new().
struct graphics_priv * global_graphics_cocoa static
Referenced by graphics_cocoa_new().
struct graphics_methods graphics_methods static
Initial value:
= {
        NULL,
        draw_mode,
        draw_lines,
        draw_polygon,
        draw_rectangle,
        NULL,
        draw_text,
        draw_image,
        NULL,
        draw_drag,
        font_new,
        gc_new,
        background_gc,
        overlay_new,
        image_new,
        get_data,
        image_free,
        get_text_bbox,
        overlay_disable,
        NULL,
        NULL,
}
Referenced by graphics_cocoa_new(), and overlay_new().
iconv_t utf8_macosroman
Referenced by draw_text().