navit: graphics.c File Reference
graphics.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <stdio.h>
#include <math.h>
#include "config.h"
#include "debug.h"
#include "string.h"
#include "draw_info.h"
#include "point.h"
#include "graphics.h"
#include "projection.h"
#include "item.h"
#include "xmlconfig.h"
#include "map.h"
#include "coord.h"
#include "transform.h"
#include "plugin.h"
#include "profile.h"
#include "mapset.h"
#include "layout.h"
#include "route.h"
#include "util.h"
#include "callback.h"
#include "file.h"
#include "event.h"
#include "navit.h"
Data Structures
struct graphics
graphics object A graphics object serves as the target for drawing operations. It encapsulates various settings, and a drawing target, such as an image buffer or a window. Currently, in Navit, there is always one main graphics object, which is used to draw the map, and optionally additional graphics objects for overlays.
struct display_context
struct hash_entry
struct displaylist
struct displaylist_icon_cache
struct displayitem_poly_holes
struct displayitem
graphics display item structure
struct circle
struct draw_polyline_shape
struct draw_polyline_context
struct wpoint
struct displaylist_handle
Macros
#define ALLOCA_COORD_LIMIT 16384
maximum amount of coordinates to allocate on stack using g_alloca
#define HASH_SIZE 1024
Enumerations
enum relative_pos {
INSIDE = 0 , LEFT_OF = 1 , RIGHT_OF = 2 , ABOVE = 4 ,
BELOW = 8
}
enum clip_result { CLIPRES_INVISIBLE = 0 , CLIPRES_VISIBLE = 1 , CLIPRES_START_CLIPPED = 2 , CLIPRES_END_CLIPPED = 4 }
Functions
static void circle_to_points (const struct point *center, int diameter, int scale, int start, int len, struct point *res, int *pos, int dir)
Create a set of points on a circle or on a circular arc.
static void graphics_process_selection (struct graphics *gra, struct displaylist *dl)
static void graphics_gc_init (struct graphics *this_)
static int graphics_dpi_scale (struct graphics *gra, int p)
static struct point graphics_dpi_scale_point (struct graphics *gra, struct point *p)
static int graphics_dpi_unscale (struct graphics *gra, int p)
static struct point graphics_dpi_unscale_point (struct graphics *gra, struct point *p)
static void clear_hash (struct displaylist *dl)
static struct hash_entry * get_hash_entry (struct displaylist *dl, enum item_type type)
static struct hash_entry * set_hash_entry (struct displaylist *dl, enum item_type type)
static int graphics_set_attr_do (struct graphics *gra, struct attr *attr)
Sets a generic attribute of the graphics instance.
int graphics_set_attr (struct graphics *gra, struct attr *attr)
Sets an attribute of the graphics instance.
void graphics_set_rect (struct graphics *gra, struct point_rect *pr)
static void graphics_dpi_patch (struct callback_list *l, enum attr_type type, int pcount, void **p, void *context)
unscale coordinates coming from the graphics backend via callback.
struct graphics * graphics_new (struct attr *parent, struct attr **attrs)
int graphics_get_attr (struct graphics *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
Gets an attribute of the graphics instance.
struct graphics * graphics_overlay_new (struct graphics *parent, struct point *p, int w, int h, int wraparound)
Create a new graphics overlay. An overlay is a graphics object that is independent of the main graphics object. When drawing everything to a window, the overlay will be shown on top of the main graphics object. Navit uses overlays for OSD elements and for the vehicle on the map. This allows updating OSD elements and the vehicle without redrawing the map.
void graphics_overlay_resize (struct graphics *this_, struct point *p, int w, int h, int wraparound)
Alters the size, position and wraparound for an overlay.
void graphics_init (struct graphics *this_)
void * graphics_get_data (struct graphics *this_, const char *type)
void graphics_add_callback (struct graphics *this_, struct callback *cb)
void graphics_remove_callback (struct graphics *this_, struct callback *cb)
struct graphics_font * graphics_font_new (struct graphics *gra, int size, int flags)
struct graphics_font * graphics_named_font_new (struct graphics *gra, char *font, int size, int flags)
void graphics_font_destroy (struct graphics_font *gra_font)
void graphics_free (struct graphics *gra)
void graphics_font_destroy_all (struct graphics *gra)
struct graphics_gc * graphics_gc_new (struct graphics *gra)
void graphics_gc_destroy (struct graphics_gc *gc)
static void graphics_convert_color (struct graphics *gra, struct color *in, struct color *out)
void graphics_gc_set_foreground (struct graphics_gc *gc, struct color *c)
void graphics_gc_set_background (struct graphics_gc *gc, struct color *c)
void graphics_gc_set_texture (struct graphics_gc *gc, struct graphics_image *img)
gboolean graphics_gc_has_texture (struct graphics_gc *gc)
void graphics_gc_set_linewidth (struct graphics_gc *gc, int width)
void graphics_gc_set_dashes (struct graphics_gc *gc, int width, int offset, unsigned char dash_list[], int n)
struct graphics_image * graphics_image_new_scaled (struct graphics *gra, char *path, int w, int h)
Create a new image from file path, optionally scaled to w and h pixels.
static void image_new_helper (struct graphics *gra, struct graphics_image *this_, char *path, char *name, int width, int height, int rotate)
struct graphics_image * graphics_image_new_scaled_rotated (struct graphics *gra, char *path, int w, int h, int rotate)
Create a new image from file path, optionally scaled to w and h pixels and rotated.
struct graphics_image * graphics_image_new (struct graphics *gra, char *path)
void graphics_image_free (struct graphics *gra, struct graphics_image *img)
void graphics_draw_mode (struct graphics *this_, enum draw_mode_num mode)
Start or finish a set of drawing operations.
void graphics_draw_lines (struct graphics *this_, struct graphics_gc *gc, struct point *p, int count)
void graphics_draw_circle (struct graphics *this_, struct graphics_gc *gc, struct point *p, int r)
Draw a circle.
void graphics_draw_rectangle (struct graphics *this_, struct graphics_gc *gc, struct point *p, int w, int h)
static void graphics_draw_polygon (struct graphics *gra, struct graphics_gc *gc, struct point *pin, int count_in)
Draw a plain polygon on the display.
static void graphics_draw_polygon_with_holes (struct graphics *gra, struct graphics_gc *gc, struct point *pin, int count_in, int hole_count, int *ccount, struct point **holes)
Draw a plain polygon with holes on the display.
void graphics_draw_rectangle_rounded (struct graphics *this_, struct graphics_gc *gc, struct point *plu, int w, int h, int r, int fill)
void graphics_draw_text (struct graphics *this_, struct graphics_gc *gc1, struct graphics_gc *gc2, struct graphics_font *font, char *text, struct point *p, int dx, int dy)
void graphics_get_text_bbox (struct graphics *this_, struct graphics_font *font, char *text, int dx, int dy, struct point *ret, int estimate)
void graphics_overlay_disable (struct graphics *this_, int disable)
int graphics_is_disabled (struct graphics *this_)
void graphics_draw_image (struct graphics *this_, struct graphics_gc *gc, struct point *p, struct graphics_image *img)
static void graphics_draw_image_warp (struct graphics *this_, struct graphics_gc *gc, struct point *p, int count, struct graphics_image *img)
int graphics_draw_drag (struct graphics *this_, struct point *p)
void graphics_background_gc (struct graphics *this_, struct graphics_gc *gc)
int graphics_show_native_keyboard (struct graphics *this_, struct graphics_keyboard *kbd)
Shows the native on-screen keyboard or other input method.
int graphics_hide_native_keyboard (struct graphics *this_, struct graphics_keyboard *kbd)
Hides the native on-screen keyboard or other input method.
static void xdisplay_free (struct displaylist *dl)
static struct displayitem_poly_holes * display_add_holes (struct item *item, int hole_count, char **p)
add the holes structure into preallocated area after displayitem
static void display_add (struct hash_entry *entry, struct item *item, int count, struct coord *c, char **label, int label_count)
static void label_line (struct graphics *gra, struct graphics_gc *fg, struct graphics_gc *bg, struct graphics_font *font, struct point *p, int count, char *label)
static void display_draw_arrow (struct point *p, navit_float dx, navit_float dy, navit_float width, struct display_context *dc, struct graphics *gra, int filled)
static void display_draw_arrows (struct graphics *gra, struct display_context *dc, struct point *pnt, int count, int *width, int filled)
draw arrows along a multi polygon line
static void display_draw_spike (struct point *p, navit_float dx, navit_float dy, navit_float width, struct display_context *dc, struct graphics *gra)
static void display_draw_spikes (struct graphics *gra, struct display_context *dc, struct point *pnt, int count, int *width, int distance)
draw spikes along a multi polygon line
static int intersection (struct point *a1, int adx, int ady, struct point *b1, int bdx, int bdy, struct point *res)
static int fowler (int dy, int dx)
static void draw_shape_update (struct draw_polyline_shape *shape)
static void draw_shape (struct draw_polyline_context *ctx, struct point *pnt, int wi)
static void draw_point (struct draw_polyline_shape *shape, struct point *src, struct point *dst, int pos)
static void draw_begin (struct draw_polyline_context *ctx, struct point *p)
static int draw_middle (struct draw_polyline_context *ctx, struct point *p)
static void draw_end (struct draw_polyline_context *ctx, struct point *p)
static void draw_init_ctx (struct draw_polyline_context *ctx, int maxpoints)
static void graphics_draw_polyline_as_polygon (struct graphics *gra, struct graphics_gc *gc, struct point *pnt, int count, int *width)
static int relative_pos (struct wpoint *p, struct point_rect *r)
static void clip_line_endoint_to_rect_edge (struct wpoint *p, int rel_pos, int dx, int dy, int dw, struct point_rect *clip_rect)
static int clip_line (struct wpoint *p1, struct wpoint *p2, struct point_rect *clip_rect)
void graphics_draw_polyline_clipped (struct graphics *gra, struct graphics_gc *gc, struct point *pa, int count, int *width, int poly)
Draw polyline on the display.
static int is_inside (struct point *p, struct point_rect *r, int edge)
static void poly_intersection (struct point *p1, struct point *p2, struct point_rect *r, int edge, struct point *ret)
static void graphics_clip_polygon (struct point_rect *r, struct point *in, int count_in, struct point *out, int *count_out)
clip a polygon inside a rectangle
void graphics_draw_polygon_clipped (struct graphics *gra, struct graphics_gc *gc, struct point *pin, int count_in)
Draw a plain polygon on the display.
static void graphics_draw_polygon_with_holes_clipped (struct graphics *gra, struct graphics_gc *gc, struct point *pin, int count_in, int hole_count, int *ccount, struct point **holes)
Draw a plain polygon with holes on the display.
static void display_context_free (struct display_context *dc)
static struct graphics_font * get_font (struct graphics *gra, int size)
void graphics_draw_text_std (struct graphics *this_, int text_size, char *text, struct point *p)
char * graphics_icon_path (const char *icon)
char * graphics_texture_path (const char *texture)
static int limit_count (struct coord *c, int count)
static void multiline_label_draw (struct graphics *gra, struct graphics_gc *fg, struct graphics_gc *bg, struct graphics_font *font, struct point pref, const char *label, int line_spacing)
Draw a multi-line text next to a specified point pref.
static void displayitem_transform_holes (struct transformation *trans, enum projection pro, struct displayitem_poly_holes *in, struct displayitem_poly_holes *out, int mindist)
coordnate transfor hole coordinates
static void displayitem_free_holes (struct displayitem_poly_holes *holes)
free hole structure allocated by displayitem_transform_holes
static void displayitem_draw_polygon (struct display_context *dc, struct graphics *gra, struct point *pa, int count, struct displayitem_poly_holes *holes)
static void displayitem_draw_polyline (struct display_context *dc, struct element *e, struct graphics *gra, struct point *pa, int count, int *width)
static void displayitem_draw_circle (struct displayitem *di, struct display_context *dc, struct element *e, struct graphics *gra, struct point *pa, int count)
static void displayitem_draw_text (struct displayitem *di, struct display_context *dc, struct element *e, struct graphics *gra, struct point *pa, int count, struct displayitem_poly_holes *holes)
static void displayitem_draw_icon (struct displayitem *di, struct display_context *dc, struct element *e, struct graphics *gra, struct point *pa, int count, struct layout *l)
static void displayitem_draw_image (struct displayitem *di, struct display_context *dc, struct graphics *gra, struct point *pa, int count)
static void displayitem_draw (struct displayitem *di, struct layout *l, struct display_context *dc)
Draw a displayitem element.
static void xdisplay_draw_elements (struct graphics *gra, struct displaylist *display_list, struct itemgra *itm, struct layout *l)
void graphics_draw_itemgra (struct graphics *gra, struct itemgra *itm, struct transformation *t, char *label)
static void xdisplay_draw_layer (struct displaylist *display_list, struct graphics *gra, struct layer *lay, int order, struct layout *l)
static void xdisplay_draw (struct displaylist *display_list, struct graphics *gra, struct layout *l, int order)
static void displaylist_update_layers (struct displaylist *displaylist, GList *layers, int order)
static void displaylist_update_hash (struct displaylist *displaylist)
struct map_selection * displaylist_get_selection (struct displaylist *displaylist)
Returns selection structure based on displaylist transform, projection and order. Use this function to get map selection if you are going to fetch complete item data from the map based on displayitem reference.
static int displaylist_cmp_zorder (const struct displayitem *a, const struct displayitem *b)
Compare displayitems based on their zorder values. Use with g_list_insert_sorted to sort less shaded items to be before more shaded ones in the result list.
GList * displaylist_get_clicked_list (struct displaylist *displaylist, struct point *p, int radius)
Returns list of displayitems clicked at given coordinates. The deeper item is in current layout, the deeper it will be in the list.
static void do_draw (struct displaylist *displaylist, int cancel, int flags)
void graphics_displaylist_draw (struct graphics *gra, struct displaylist *displaylist, struct transformation *trans, struct layout *l, int flags)
static void graphics_load_mapset (struct graphics *gra, struct displaylist *displaylist, struct mapset *mapset, struct transformation *trans, struct layout *l, int async, struct callback *cb, int flags)
void graphics_draw (struct graphics *gra, struct displaylist *displaylist, struct mapset *mapset, struct transformation *trans, struct layout *l, int async, struct callback *cb, int flags)
int graphics_draw_cancel (struct graphics *gra, struct displaylist *displaylist)
struct displaylist_handle * graphics_displaylist_open (struct displaylist *displaylist)
struct displayitem * graphics_displaylist_next (struct displaylist_handle *dlh)
void graphics_displaylist_close (struct displaylist_handle *dlh)
struct displaylist * graphics_displaylist_new (void)
void graphics_displaylist_destroy (struct displaylist *displaylist)
struct item * graphics_displayitem_get_item (struct displayitem *di)
int graphics_displayitem_get_z_order (struct displayitem *di)
int graphics_displayitem_get_coord_count (struct displayitem *di)
char * graphics_displayitem_get_label (struct displayitem *di)
int graphics_displayitem_get_displayed (struct displayitem *di)
static int within_dist_point (struct point *p0, struct point *p1, int dist)
static int within_dist_line (struct point *p, struct point *line_p0, struct point *line_p1, int dist)
static int within_dist_polyline (struct point *p, struct point *line_pnt, int count, int dist, int close)
static int within_dist_polygon (struct point *p, struct point *poly_pnt, int count, int dist)
int graphics_displayitem_within_dist (struct displaylist *displaylist, struct displayitem *di, struct point *p, int dist)
static void graphics_process_selection_item (struct displaylist *dl, struct item *item)
void graphics_add_selection (struct graphics *gra, struct item *item, enum item_type type, struct displaylist *dl)
void graphics_remove_selection (struct graphics *gra, struct item *item, enum item_type type, struct displaylist *dl)
void graphics_clear_selection (struct graphics *gra, struct displaylist *dl)
navit_float graphics_get_dpi (struct graphics *gra)
get display resolution in DPI This method returns the native display density in DPI
Variables
struct circle circle64 []
void * route_selection
Macro Definition Documentation
ALLOCA_COORD_LIMIT
#define ALLOCA_COORD_LIMIT 16384
maximum amount of coordinates to allocate on stack using g_alloca
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
HASH_SIZE
#define HASH_SIZE 1024
Enumeration Type Documentation
clip_result
enum clip_result
Enumerator
CLIPRES_INVISIBLE
CLIPRES_VISIBLE
CLIPRES_START_CLIPPED
CLIPRES_END_CLIPPED
relative_pos
enum relative_pos
Enumerator
INSIDE
LEFT_OF
RIGHT_OF
ABOVE
BELOW
Function Documentation
circle_to_points()
static void circle_to_points (const struct point * center, int diameter, int scale, int start, int len, struct point * res, int * pos, int dir) static
Create a set of points on a circle or on a circular arc.
Parameters
center Center point of the circle
diameter Diameter of the circle
scale Unused
start Position of the first point on the circle (in 1/1024th of the circle), -1 being the bottom of the circle, 511 being the top of the circle
len Length of the arc on the circle, relative to start (in 1/1024th of the circle), 514 is half a circle, 1028 is a full circle (or 1027 if first and last points are connected with a line)
[out] res Returned an array of points that will form the resulting circle
[out] pos Index of the last point filled inside array res
dir Direction of the circle (valid values are 1 (counter-clockwise) or -1 (clockwise), other values may lead to unknown result)
References c, center, circle64, fowler(), startup::pos, pcoord::x, point::x, pcoord::y, and point::y.
Referenced by graphics_draw_circle(), and graphics_draw_rectangle_rounded().
clear_hash()
static void clear_hash (struct displaylist * dl) static
References displaylist::hash_entries, HASH_SIZE, and hash_entry::type.
Referenced by displaylist_update_hash().
clip_line()
static int clip_line (struct wpoint * p1, struct wpoint * p2, struct point_rect * clip_rect) static
References clip_line_endoint_to_rect_edge(), CLIPRES_END_CLIPPED, CLIPRES_INVISIBLE, CLIPRES_START_CLIPPED, CLIPRES_VISIBLE, INSIDE, wpoint::w, wpoint::x, and wpoint::y.
Referenced by graphics_draw_polyline_clipped().
clip_line_endoint_to_rect_edge()
static void clip_line_endoint_to_rect_edge (struct wpoint * p, int rel_pos, int dx, int dy, int dw, struct point_rect * clip_rect) static
References ABOVE, BELOW, LEFT_OF, point_rect::lu, p, RIGHT_OF, point_rect::rl, point::x, and point::y.
Referenced by clip_line().
display_add()
static void display_add (struct hash_entry * entry, struct item * item, int count, struct coord * c, char ** label, int label_count) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References displayitem::c, c, poly_hole::coord_count, displayitem::count, dbg, hash_entry::di, display_add_holes(), displayitem::flags, displayitem::holes, displayitem::item, item, item_attr_get(), item_attr_rewind(), displayitem::label, label, lvl_debug, displayitem::next, attr::num, p, attr::poly_hole, attr::u, and displayitem::z_order.
Referenced by do_draw(), and graphics_process_selection_item().
display_add_holes()
static struct displayitem_poly_holes* display_add_holes (struct item * item, int hole_count, char ** p) inline static
add the holes structure into preallocated area after displayitem
Parameters
item to extract holes from
hole_count precounted number of holes
p changeable pointer to buffer. Advanced by the size used
Returns
pointer to newly created holes structure
References displayitem_poly_holes::ccount, poly_hole::coord, poly_hole::coord_count, displayitem_poly_holes::coords, displayitem_poly_holes::count, item_attr_get(), item_attr_rewind(), p, attr::poly_hole, and attr::u.
Referenced by display_add().
display_context_free()
static void display_context_free (struct display_context * dc) static
References display_context::gc, display_context::gc_background, display_context::gra, graphics_gc_destroy(), graphics_image_free(), and display_context::img.
Referenced by graphics_draw_itemgra(), and xdisplay_draw_elements().
display_draw_arrow()
static void display_draw_arrow (struct point * p, navit_float dx, navit_float dy, navit_float width, struct display_context * dc, struct graphics * gra, int filled) static
References display_context::gc, graphics_draw_lines(), graphics_draw_polygon(), p, width, point::x, and point::y.
Referenced by display_draw_arrows().
display_draw_arrows()
static void display_draw_arrows (struct graphics * gra, struct display_context * dc, struct point * pnt, int count, int * width, int filled) static
draw arrows along a multi polygon line
This function draws arrows along a multi polygon line, and scales the arrows according to current view settings by interpolating sizes at given arrow position,
Parameters
gra current graphics instance handle
dc current drawing context
pnt array of points for this polyline
count number of points in pnt
width arrray of integers giving the expexted line width at the corresponding point
filled. True to draw filled arrows, false to draw only line arrows.
References display_draw_arrow(), navit_sqrt, p, width, point::x, and point::y.
Referenced by displayitem_draw().
display_draw_spike()
static void display_draw_spike (struct point * p, navit_float dx, navit_float dy, navit_float width, struct display_context * dc, struct graphics * gra) static
References display_context::gc, graphics_draw_lines(), navit_sqrt, p, width, point::x, and point::y.
Referenced by display_draw_spikes().
display_draw_spikes()
static void display_draw_spikes (struct graphics * gra, struct display_context * dc, struct point * pnt, int count, int * width, int distance) static
draw spikes along a multi polygon line
This function draws spikes along a multi polygon line, and scales the spikes according to current view settings by interpolating sizes at given spike position,
Parameters
gra current graphics instance handle
dc current drawing context
pnt array of points for this polyline
count number of points in pnt
width array of integers giving the expected line width at the corresponding point
distance giving the distance between spikes
References display_draw_spike(), navit_sqrt, p, width, point::x, and point::y.
Referenced by displayitem_draw().
displayitem_draw()
static void displayitem_draw (struct displayitem * di, struct layout * l, struct display_context * dc) static
Draw a displayitem element.
This function will invoke the appropriate draw primitive depending on the type of the element to draw
di The displayitem to draw
l current layout for getting defaults and underground alpha
dc The display_context to use to draw items
References color::a, AF_ONEWAY, AF_ROUNDABOUT, AF_UNDERGROUND, ALLOCA_COORD_LIMIT, element::arrows, displayitem::c, element::color, displayitem_poly_holes::count, displayitem::count, graphics::current_z_order, dbg, display_draw_arrows(), display_draw_spikes(), displayitem_draw_circle(), displayitem_draw_icon(), displayitem_draw_image(), displayitem_draw_polygon(), displayitem_draw_polyline(), displayitem_draw_text(), displayitem_free_holes(), displayitem_transform_holes(), display_context::e, displayitem::flags, display_context::gc, display_context::gra, graphics_gc::gra, graphics_gc_new(), graphics_gc_set_foreground(), displayitem::holes, item_type_is_area, limit, limit_count(), lvl_error, display_context::maxlen, display_context::mindist, displayitem::next, element::oneway, element::polyline, display_context::pro, element::spikes, display_context::trans, transform_point_buf(), display_context::type, element::type, element::u, layout::underground_alpha, UNDERGROUND_ALPHA_, width, and displayitem::z_order.
Referenced by graphics_draw_itemgra(), and xdisplay_draw_elements().
displayitem_draw_circle()
static void displayitem_draw_circle (struct displayitem * di, struct display_context * dc, struct element * e, struct graphics * gra, struct point * pa, int count) inline static
References element::circle, dbg, display_context::gc, display_context::gc_background, get_font(), graphics_gc::gra, graphics_draw_circle(), graphics_gc_new(), graphics_gc_set_foreground(), graphics_gc_set_linewidth(), displayitem::label, lvl_error, multiline_label_draw(), p, element::polyline, element::text_size, element::u, point::x, and point::y.
Referenced by displayitem_draw().
displayitem_draw_icon()
static void displayitem_draw_icon (struct displayitem * di, struct display_context * dc, struct element * e, struct graphics * gra, struct point * pa, int count, struct layout * l) inline static
References dbg, graphics::gc, display_context::gra, graphics_draw_image(), graphics_icon_path(), graphics_image_free(), graphics_image_new_scaled_rotated(), graphics_image::hot, element::icon, layout::icon_h, layout::icon_w, display_context::img, displayitem::item, item_is_custom_poi, displayitem::label, lvl_debug, p, element::u, point::x, and point::y.
Referenced by displayitem_draw().
displayitem_draw_image()
static void displayitem_draw_image (struct displayitem * di, struct display_context * dc, struct graphics * gra, struct point * pa, int count) inline static
References dbg, graphics_methods::draw_image_warp, graphics::gc, graphics_draw_image_warp(), graphics_image_new_scaled_rotated(), display_context::img, displayitem::label, lvl_debug, lvl_error, and graphics::meth.
Referenced by displayitem_draw().
displayitem_draw_polygon()
static void displayitem_draw_polygon (struct display_context * dc, struct graphics * gra, struct point * pa, int count, struct displayitem_poly_holes * holes) inline static
References displayitem_poly_holes::ccount, displayitem_poly_holes::coords, displayitem_poly_holes::count, display_context::e, display_context::gc, graphics_draw_polygon_clipped(), graphics_draw_polygon_with_holes_clipped(), graphics_gc_has_texture(), graphics_gc_set_texture(), graphics_image_new_scaled_rotated(), graphics_texture_path(), element::polygon, and element::u.
Referenced by displayitem_draw().
displayitem_draw_polyline()
static void displayitem_draw_polyline (struct display_context * dc, struct element * e, struct graphics * gra, struct point * pa, int count, int * width) inline static
References display_context::gc, graphics_draw_polyline_clipped(), graphics_gc_set_dashes(), graphics_gc_set_linewidth(), element::polyline, element::u, and width.
Referenced by displayitem_draw().
displayitem_draw_text()
static void displayitem_draw_text (struct displayitem * di, struct display_context * dc, struct element * e, struct graphics * gra, struct point * pa, int count, struct displayitem_poly_holes * holes) inline static
References displayitem_poly_holes::ccount, displayitem_poly_holes::coords, displayitem_poly_holes::count, dbg, display_context::gc, display_context::gc_background, get_font(), graphics_gc::gra, graphics_gc_new(), graphics_gc_set_foreground(), displayitem::label, label_line(), lvl_error, element::text, element::text_size, and element::u.
Referenced by displayitem_draw().
displayitem_free_holes()
static void displayitem_free_holes (struct displayitem_poly_holes * holes) static
free hole structure allocated by displayitem_transform_holes
Parameters
holes structure to deallocate
References displayitem_poly_holes::ccount, displayitem_poly_holes::coords, and displayitem_poly_holes::count.
Referenced by displayitem_draw().
displayitem_transform_holes()
static void displayitem_transform_holes (struct transformation * trans, enum projection pro, struct displayitem_poly_holes * in, struct displayitem_poly_holes * out, int mindist) inline static
coordnate transfor hole coordinates
This function transform a whole set of polygon holes. It therefore allocates memory attached to a displayitem_poly_holes structure and call transform
Parameters
trans transformation to be used
pro projection to be used
in filled holes structure to transform
out structure to place result in. Remember to deallocate!
mindist minimal distance between points
References displayitem_poly_holes::ccount, displayitem_poly_holes::coords, displayitem_poly_holes::count, limit_count(), TRANSFORM_ERR_BUF_SPACE, and transform_point_buf().
Referenced by displayitem_draw().
displaylist_cmp_zorder()
static int displaylist_cmp_zorder (const struct displayitem * a, const struct displayitem * b) static
Compare displayitems based on their zorder values. Use with g_list_insert_sorted to sort less shaded items to be before more shaded ones in the result list.
References displayitem::z_order.
Referenced by displaylist_get_clicked_list().
displaylist_get_clicked_list()
GList* displaylist_get_clicked_list (struct displaylist * displaylist, struct point * p, int radius)
Returns list of displayitems clicked at given coordinates. The deeper item is in current layout, the deeper it will be in the list.
Parameters
displaylist
p clicked point
radius radius of clicked area
Returns
GList of displayitems
References displaylist_handle::di, displaylist_cmp_zorder(), graphics_displayitem_within_dist(), graphics_displaylist_close(), graphics_displaylist_next(), graphics_displaylist_open(), p, and displayitem::z_order.
Referenced by gui_internal_cmd_position_do().
displaylist_get_selection()
struct map_selection* displaylist_get_selection (struct displaylist * displaylist)
Returns selection structure based on displaylist transform, projection and order. Use this function to get map selection if you are going to fetch complete item data from the map based on displayitem reference.
Parameters
displaylist
Returns
Pointer to selection structure
References displaylist::dc, displaylist::order, display_context::pro, display_context::trans, and transform_get_selection().
Referenced by do_draw(), and gui_internal_cmd_position_do().
displaylist_update_hash()
static void displaylist_update_hash (struct displaylist * displaylist) static
References clear_hash(), dbg, displaylist_update_layers(), layout::layers, displaylist::layout, lvl_debug, displaylist::max_offset, and displaylist::order.
Referenced by do_draw().
displaylist_update_layers()
static void displaylist_update_layers (struct displaylist * displaylist, GList * layers, int order) static
References layer::itemgras, layer::ref, set_hash_entry(), itemgra::type, type, and types.
Referenced by displaylist_update_hash().
do_draw()
static void do_draw (struct displaylist * displaylist, int cancel, int flags) static
References ALLOCA_COORD_LIMIT, displaylist::busy, busy_item, callback_call_1, callback_destroy(), displaylist::cb, displaylist::conv, dbg, displaylist::dc, display_add(), displaylist_get_selection(), displaylist_update_hash(), event_remove_idle(), get_hash_entry(), display_context::gra, graphics_displaylist_draw(), graphics_process_selection(), displaylist::idle_cb, displaylist::idle_ev, item, item_attr_get(), item_coord_get_within_selection(), item_coord_rewind(), item_coords_left(), ITEM_ID_ARGS, ITEM_ID_FMT, item_is_custom_poi, item_to_name(), displaylist::layout, displaylist::layout_hashed, lvl_debug, lvl_error, displaylist::m, map_convert_free(), map_convert_string(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_requires_conversion(), map_selection_destroy(), mapset_close(), mapset_next(), mapset_open(), max, display_context::maxlen, displaylist::mr, displaylist::ms, displaylist::msh, displaylist::order, displaylist::order_hashed, display_context::pro, profile, route_selection, displaylist::sel, attr::str, display_context::trans, transform_from_to_count(), transform_get_projection(), item::type, attr::u, and displaylist::workload.
Referenced by draw_aligned_osd_text(), graphics_draw_cancel(), graphics_load_mapset(), osd_gps_status_draw(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), and osd_text_draw().
draw_begin()
static void draw_begin (struct draw_polyline_context * ctx, struct point * p) static
References circle64, draw_polyline_shape::dxw, draw_polyline_shape::dyw, p, draw_polyline_context::ppos, draw_polyline_context::res, draw_polyline_context::shape, draw_polyline_shape::step, circle::x, point::x, circle::y, and point::y.
Referenced by graphics_draw_polyline_as_polygon().
draw_end()
static void draw_end (struct draw_polyline_context * ctx, struct point * p) static
References circle64, draw_polyline_shape::dxw, draw_polyline_shape::dyw, draw_polyline_context::npos, p, draw_polyline_context::prev_shape, draw_polyline_context::res, draw_polyline_shape::step, circle::x, point::x, circle::y, and point::y.
Referenced by graphics_draw_polyline_as_polygon().
draw_init_ctx()
static void draw_init_ctx (struct draw_polyline_context * ctx, int maxpoints) static
References draw_polyline_context::npos, draw_polyline_context::ppos, and draw_polyline_context::prec.
Referenced by graphics_draw_polyline_as_polygon().
draw_middle()
static int draw_middle (struct draw_polyline_context * ctx, struct point * p) static
References dbg, draw_point(), draw_polyline_shape::dx, draw_polyline_shape::dy, draw_polyline_shape::fow, intersection(), lvl_debug, draw_polyline_context::npos, p, startup::pos, draw_polyline_context::ppos, draw_polyline_context::prev_shape, draw_polyline_context::res, and draw_polyline_context::shape.
Referenced by graphics_draw_polyline_as_polygon().
draw_point()
static void draw_point (struct draw_polyline_shape * shape, struct point * src, struct point * dst, int pos) static
References draw_polyline_shape::dxw, draw_polyline_shape::dyw, startup::pos, point::x, and point::y.
Referenced by draw_middle().
draw_shape()
static void draw_shape (struct draw_polyline_context * ctx, struct point * pnt, int wi) static
References dbg, dbg_assert, draw_shape_update(), draw_polyline_shape::dx, draw_polyline_shape::dy, draw_polyline_shape::fow, fowler(), draw_polyline_shape::l, draw_polyline_shape::lscale, lvl_debug, draw_polyline_context::prev_shape, draw_polyline_context::shape, draw_polyline_shape::step, uint_sqrt(), draw_polyline_shape::wi, point::x, and point::y.
Referenced by graphics_draw_polyline_as_polygon().
draw_shape_update()
static void draw_shape_update (struct draw_polyline_shape * shape) static
References draw_polyline_shape::dx, draw_polyline_shape::dxw, draw_polyline_shape::dy, draw_polyline_shape::dyw, draw_polyline_shape::l, draw_polyline_shape::lscale, and draw_polyline_shape::wi.
Referenced by draw_shape().
fowler()
static int fowler (int dy, int dx) static
Referenced by circle_to_points(), and draw_shape().
get_font()
static struct graphics_font* get_font (struct graphics * gra, int size) static
References graphics::font, graphics::font_len, graphics::font_size, graphics_font_new(), and size.
Referenced by displayitem_draw_circle(), displayitem_draw_text(), and graphics_draw_text_std().
get_hash_entry()
static struct hash_entry* get_hash_entry (struct displaylist * dl, enum item_type type) static
References displaylist::hash_entries, HASH_SIZE, displaylist::max_offset, offset, hash_entry::type, and type.
Referenced by do_draw(), and xdisplay_draw_elements().
graphics_add_callback()
void graphics_add_callback (struct graphics * this_, struct callback * cb)
References callback_list_add(), and graphics::cbl.
Referenced by gui_internal_set_graphics(), gui_qml_set_graphics(), gui_qt5_qml_set_graphics(), navit_set_graphics(), osd_button_init(), osd_image_init(), osd_scale_init(), osd_set_keypress(), osd_set_std_graphic(), pedestrian_navit_init(), and win32_cb_graphics_ready().
graphics_add_selection()
void graphics_add_selection (struct graphics * gra, struct item * item, enum item_type type, struct displaylist * dl)
References graphics_process_selection_item(), item, item::priv_data, graphics::selection, and type.
Referenced by gui_internal_cmd_view_on_map().
graphics_background_gc()
void graphics_background_gc (struct graphics * this_, struct graphics_gc * gc)
References graphics_methods::background_gc, graphics::meth, graphics::priv, and graphics_gc::priv.
Referenced by graphics_displaylist_draw(), graphics_init(), osd_set_std_graphic(), and vehicle_draw().
graphics_clear_selection()
void graphics_clear_selection (struct graphics * gra, struct displaylist * dl)
References graphics_remove_selection(), item::priv_data, and graphics::selection.
Referenced by gui_internal_cmd_view_on_map().
graphics_clip_polygon()
static void graphics_clip_polygon (struct point_rect * r, struct point * in, int count_in, struct point * out, int * count_out) static
clip a polygon inside a rectangle
This function clippes a given polygon inside a rectangle. It writes the result into provided buffer.
Parameters
[in] r rectangle to clip into
[in] pin point array of input polygon
[in] count_in number of points in pin
[out] out preallocated buffer of at least count_in *8 +1 points size
[out] count_out size of out number of points, number of points used in out at return
References ALLOCA_COORD_LIMIT, is_inside(), p, and poly_intersection().
Referenced by graphics_draw_polygon_clipped(), and graphics_draw_polygon_with_holes_clipped().
graphics_convert_color()
static void graphics_convert_color (struct graphics * gra, struct color * in, struct color * out) static
References color::b, graphics::brightness, graphics::contrast, color::g, graphics::gamma, graphics_gc::gra, and color::r.
Referenced by graphics_gc_set_background(), and graphics_gc_set_foreground().
graphics_displayitem_get_coord_count()
int graphics_displayitem_get_coord_count (struct displayitem * di)
References displayitem::count.
Referenced by popup_show_item().
graphics_displayitem_get_displayed()
int graphics_displayitem_get_displayed (struct displayitem * di)
Referenced by gui_internal_dbus_signal(), and gui_qml_dbus_signal().
graphics_displayitem_get_item()
struct item* graphics_displayitem_get_item (struct displayitem * di)
Get the map item which given displayitem is based on. NOTE: returned structure doesn't contain any attributes or coordinates. type, map, idhi and idlow seem to be the only useable members.
Parameters
di pointer to displayitem structure
Returns
Pointer to struct item
Author
Martin Schaller (04/2008)
References displayitem::item.
Referenced by gui_internal_cmd_position_do(), gui_internal_dbus_signal(), gui_qml_dbus_signal(), and popup_show_item().
graphics_displayitem_get_label()
char* graphics_displayitem_get_label (struct displayitem * di)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References displayitem::label.
Referenced by popup_show_item().
graphics_displayitem_get_z_order()
int graphics_displayitem_get_z_order (struct displayitem * di)
Get the number of this item as it was last displayed on the screen, dependent of current layout. Items with lower numbers are shaded by items with higher ones when they overlap. Zero means item was not displayed at all. If the item is displayed twice, its topmost occurence is used.
Parameters
di pointer to displayitem structure
Returns
z-order of current item.
References displayitem::z_order.
graphics_displayitem_within_dist()
int graphics_displayitem_within_dist (struct displaylist * displaylist, struct displayitem * di, struct point * p, int dist)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References ALLOCA_COORD_LIMIT, displayitem::c, displayitem::count, displaylist::dc, displayitem::item, display_context::maxlen, p, display_context::pro, display_context::trans, transform_point_buf(), item::type, within_dist_point(), within_dist_polygon(), and within_dist_polyline().
Referenced by displaylist_get_clicked_list(), gui_internal_dbus_signal(), and gui_qml_dbus_signal().
graphics_displaylist_close()
void graphics_displaylist_close (struct displaylist_handle * dlh)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
Referenced by displaylist_get_clicked_list(), gui_internal_cmd_position_do(), gui_internal_dbus_signal(), and gui_qml_dbus_signal().
graphics_displaylist_destroy()
void graphics_displaylist_destroy (struct displaylist * displaylist)
References displaylist::dc, display_context::trans, and transform_destroy().
Referenced by navit_destroy().
graphics_displaylist_draw()
void graphics_displaylist_draw (struct graphics * gra, struct displaylist * displaylist, struct transformation * trans, struct layout * l, int flags)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References callback_list_call_attr_0, graphics::cbl, layout::color, displaylist::dc, graphics::default_font, draw_mode_begin, draw_mode_begin_clear, draw_mode_end, layout::font, graphics::gc, display_context::gra, graphics_background_gc(), graphics_draw_mode(), graphics_draw_rectangle(), graphics_gc_set_background(), graphics_gc_set_foreground(), point_rect::lu, display_context::mindist, layout::order_delta, graphics::r, point_rect::rl, display_context::trans, transform_destroy(), transform_dup(), transform_get_order(), point::x, xdisplay_draw(), and point::y.
Referenced by do_draw(), navit_draw_displaylist(), navit_motion_timeout(), osd_auxmap_draw(), and pedestrian_rocket_idle().
graphics_displaylist_new()
struct displaylist* graphics_displaylist_new (void)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References ALLOCA_COORD_LIMIT, displaylist::dc, and display_context::maxlen.
Referenced by navit_new().
graphics_displaylist_next()
struct displayitem* graphics_displaylist_next (struct displaylist_handle * dlh)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References hash_entry::di, displaylist_handle::di, displaylist_handle::dl, displaylist::hash_entries, HASH_SIZE, displaylist_handle::hashidx, displayitem::next, and hash_entry::type.
Referenced by displaylist_get_clicked_list(), gui_internal_dbus_signal(), and gui_qml_dbus_signal().
graphics_displaylist_open()
struct displaylist_handle* graphics_displaylist_open (struct displaylist * displaylist)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References displaylist_handle::dl.
Referenced by displaylist_get_clicked_list(), gui_internal_cmd_position_do(), gui_internal_dbus_signal(), and gui_qml_dbus_signal().
graphics_dpi_patch()
static void graphics_dpi_patch (struct callback_list * l, enum attr_type type, int pcount, void ** p, void * context) static
unscale coordinates coming from the graphics backend via callback.
Parameters
l pointer to callback list
pcount number of parameters attached to this callback
p list of parameters
context context handed over by callback_list_add_patch_function, gra in this case.
Returns
nothing
References dbg, graphics_dpi_unscale(), graphics_dpi_unscale_point(), lvl_debug, p, type, point::x, and point::y.
Referenced by graphics_new().
graphics_dpi_scale()
static int graphics_dpi_scale (struct graphics * gra, int p) static
References graphics::dpi_factor, and p.
Referenced by graphics_draw_circle(), graphics_draw_rectangle(), graphics_gc_set_dashes(), graphics_gc_set_linewidth(), graphics_named_font_new(), graphics_overlay_new(), graphics_overlay_resize(), and image_new_helper().
graphics_dpi_scale_point()
static struct point graphics_dpi_scale_point (struct graphics * gra, struct point * p) static
Referenced by graphics_draw_circle(), graphics_draw_drag(), graphics_draw_image(), graphics_draw_image_warp(), graphics_draw_lines(), graphics_draw_polygon(), graphics_draw_polygon_with_holes(), graphics_draw_rectangle(), graphics_draw_text(), graphics_overlay_new(), graphics_overlay_resize(), and image_new_helper().
graphics_dpi_unscale()
static int graphics_dpi_unscale (struct graphics * gra, int p) static
References graphics::dpi_factor, and p.
Referenced by graphics_dpi_patch(), and image_new_helper().
graphics_dpi_unscale_point()
static struct point graphics_dpi_unscale_point (struct graphics * gra, struct point * p) static
Referenced by graphics_dpi_patch(), graphics_get_text_bbox(), and image_new_helper().
graphics_draw()
void graphics_draw (struct graphics * gra, struct displaylist * displaylist, struct mapset * mapset, struct transformation * trans, struct layout * l, int async, struct callback * cb, int flags)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_load_mapset().
Referenced by navit_draw_async(), and osd_auxmap_draw().
graphics_draw_cancel()
int graphics_draw_cancel (struct graphics * gra, struct displaylist * displaylist)
References displaylist::busy, and do_draw().
Referenced by navit_block(), navit_destroy(), navit_handle_resize(), and navit_motion_timeout().
graphics_draw_circle()
void graphics_draw_circle (struct graphics * this_, struct graphics_gc * gc, struct point * p, int r)
Draw a circle.
Parameters
this_ The graphics instance on which to draw
gc The graphics context
p The coordinates of the center of the circle
r The radius of the circle
Author
Martin Schaller (04/2008)
References ALLOCA_COORD_LIMIT, circle_to_points(), graphics_methods::draw_circle, graphics_dpi_scale(), graphics_dpi_scale_point(), graphics_draw_lines(), graphics::meth, p, graphics::priv, and graphics_gc::priv.
Referenced by displayitem_draw_circle(), gui_internal_cmd2_route_height_profile(), osd_auxmap_draw(), osd_compass_draw(), and osd_speed_warner_draw().
graphics_draw_drag()
int graphics_draw_drag (struct graphics * this_, struct point * p)
References graphics_methods::draw_drag, graphics_dpi_scale_point(), graphics::meth, p, and graphics::priv.
Referenced by navit_handle_button(), navit_motion_timeout(), and vehicle_draw_do().
graphics_draw_image()
void graphics_draw_image (struct graphics * this_, struct graphics_gc * gc, struct point * p, struct graphics_image * img)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::draw_image, graphics_dpi_scale_point(), graphics::meth, p, graphics::priv, graphics_gc::priv, and graphics_image::priv.
Referenced by displayitem_draw_icon(), gui_internal_image_render(), osd_button_draw(), osd_button_init(), osd_cmd_interface_draw(), osd_gps_status_draw(), osd_image_init(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_speed_warner_draw(), osd_volume_draw(), and pedestrian_draw_arrow().
graphics_draw_image_warp()
static void graphics_draw_image_warp (struct graphics * this_, struct graphics_gc * gc, struct point * p, int count, struct graphics_image * img) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References ALLOCA_COORD_LIMIT, dbg, graphics_methods::draw_image_warp, graphics_dpi_scale_point(), lvl_error, graphics::meth, p, graphics::priv, graphics_gc::priv, and graphics_image::priv.
Referenced by displayitem_draw_image().
graphics_draw_itemgra()
void graphics_draw_itemgra (struct graphics * gra, struct itemgra * itm, struct transformation * t, char * label)
References ALLOCA_COORD_LIMIT, displayitem::c, element::coord, element::coord_count, displayitem::count, dbg, display_context_free(), displayitem_draw(), display_context::e, itemgra::elements, display_context::gc, display_context::gc_background, display_context::gra, displayitem::holes, item::id_hi, item::id_lo, display_context::img, displayitem::item, displayitem::label, label, lvl_error, item::map, display_context::maxlen, display_context::mindist, displayitem::next, display_context::pro, projection_screen, display_context::trans, display_context::type, item::type, coord::x, coord::y, and displayitem::z_order.
Referenced by vehicle_draw_do().
graphics_draw_lines()
void graphics_draw_lines (struct graphics * this_, struct graphics_gc * gc, struct point * p, int count)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References ALLOCA_COORD_LIMIT, graphics_methods::draw_lines, graphics_dpi_scale_point(), graphics::meth, p, graphics::priv, and graphics_gc::priv.
Referenced by display_draw_arrow(), display_draw_spike(), draw_handle(), graphics_draw_circle(), graphics_draw_polyline_clipped(), graphics_draw_rectangle_rounded(), gui_internal_box_render(), gui_internal_cmd2_route_height_profile(), gui_internal_table_render(), and osd_scale_draw().
graphics_draw_mode()
void graphics_draw_mode (struct graphics * this_, enum draw_mode_num mode)
Start or finish a set of drawing operations.
graphics_draw_mode(draw_mode_begin) must be invoked before performing any drawing operations; this allows the graphics driver to perform any necessary setup. graphics_draw_mode(draw_mode_end) must be invoked to finish a set of drawing operations; this will typically clean up drawing resources and display the drawing result.
Parameters
this_ graphics object that is being drawn to
mode specify beginning or end of drawing
Author
Martin Schaller (04/2008)
References graphics_methods::draw_mode, graphics::meth, and graphics::priv.
Referenced by draw_aligned_osd_text(), graphics_displaylist_draw(), gui_internal_button(), gui_internal_cmd2_about(), gui_internal_cmd2_back(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_highlight_do(), gui_internal_highlight_possible_keys(), gui_internal_html_menu(), gui_internal_html_submit(), gui_internal_keypress(), gui_internal_leave(), gui_internal_motion_cb(), gui_internal_route_update(), gui_internal_search_idle(), gui_internal_set_attr(), navit_map_progress(), navit_motion_timeout(), navit_set_attr_do(), osd_auxmap_draw(), osd_button_init(), osd_cmd_interface_draw(), osd_compass_draw(), osd_fill_with_bgcolor(), osd_gps_status_draw(), osd_image_init(), osd_j1850_draw(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_odometer_draw(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_cam_draw(), osd_speed_warner_draw(), osd_stopwatch_draw(), osd_text_draw(), osd_volume_draw(), and vehicle_draw_do().
graphics_draw_polygon()
static void graphics_draw_polygon (struct graphics * gra, struct graphics_gc * gc, struct point * pin, int count_in) static
Draw a plain polygon on the display.
Parameters
gra The graphics instance on which to draw
gc The graphics context
[in] pin An array of points forming the polygon
count_in The number of elements inside pin
References ALLOCA_COORD_LIMIT, graphics_methods::draw_polygon, graphics_dpi_scale_point(), graphics::meth, graphics::priv, and graphics_gc::priv.
Referenced by display_draw_arrow(), graphics_draw_polygon_clipped(), graphics_draw_polygon_with_holes(), graphics_draw_polyline_as_polygon(), and graphics_draw_rectangle_rounded().
graphics_draw_polygon_clipped()
void graphics_draw_polygon_clipped (struct graphics * gra, struct graphics_gc * gc, struct point * pin, int count_in)
Draw a plain polygon on the display.
Parameters
gra The graphics instance on which to draw
gc The graphics context
[in] pin An array of points forming the polygon
count_in The number of elements inside pin
References ALLOCA_COORD_LIMIT, graphics_clip_polygon(), graphics_draw_polygon(), and graphics::r.
Referenced by displayitem_draw_polygon(), and draw_compass().
graphics_draw_polygon_with_holes()
static void graphics_draw_polygon_with_holes (struct graphics * gra, struct graphics_gc * gc, struct point * pin, int count_in, int hole_count, int * ccount, struct point ** holes) static
Draw a plain polygon with holes on the display.
Parameters
gra The graphics instance on which to draw
gc The graphics context
[in] pin An array of points forming the polygon
count_in The number of elements inside pin
hole_count The number of hole polygons to cut out
pcount array of [hole_count] integers giving the number of points per hole
holes array of point arrays for the hole polygons
References ALLOCA_COORD_LIMIT, graphics_methods::draw_polygon_with_holes, graphics_dpi_scale_point(), graphics_draw_polygon(), graphics::meth, graphics::priv, and graphics_gc::priv.
Referenced by graphics_draw_polygon_with_holes_clipped().
graphics_draw_polygon_with_holes_clipped()
static void graphics_draw_polygon_with_holes_clipped (struct graphics * gra, struct graphics_gc * gc, struct point * pin, int count_in, int hole_count, int * ccount, struct point ** holes) static
Draw a plain polygon with holes on the display.
Parameters
gra The graphics instance on which to draw
gc The graphics context
[in] pin An array of points forming the polygon
count_in The number of elements inside pin
hole_count The number of hole polygons to cut out
pcount array of [hole_count] integers giving the number of points per hole
holes array of point arrays for the hole polygons
References ALLOCA_COORD_LIMIT, graphics_clip_polygon(), graphics_draw_polygon_with_holes(), and graphics::r.
Referenced by displayitem_draw_polygon().
graphics_draw_polyline_as_polygon()
static void graphics_draw_polyline_as_polygon (struct graphics * gra, struct graphics_gc * gc, struct point * pnt, int count, int * width) static
References ALLOCA_COORD_LIMIT, draw_begin(), draw_end(), draw_init_ctx(), draw_middle(), draw_shape(), graphics_draw_polygon(), draw_polyline_shape::l, draw_polyline_context::npos, draw_polyline_context::ppos, draw_polyline_context::prev_shape, draw_polyline_context::res, draw_polyline_context::shape, draw_polyline_shape::wi, and width.
Referenced by graphics_draw_polyline_clipped().
graphics_draw_polyline_clipped()
void graphics_draw_polyline_clipped (struct graphics * gra, struct graphics_gc * gc, struct point * pa, int count, int * width, int poly)
Draw polyline on the display.
Polylines are a serie of lines connected to each other.
Parameters
gra The graphics instance on which to draw
gc The graphics context
[in] pin An array of points forming the polygon
count_in The number of elements inside pin
[in] width An array of width matching the line starting from the corresponding pa (if all equal, all lines will have the same width)
poly A boolean indicating whether the polyline should be closed to form a polygon (only the contour of this polygon will be drawn)
References ALLOCA_COORD_LIMIT, clip_line(), CLIPRES_END_CLIPPED, CLIPRES_INVISIBLE, CLIPRES_START_CLIPPED, dbg, graphics_draw_lines(), graphics_draw_polyline_as_polygon(), point_rect::lu, lvl_debug, graphics::r, point_rect::rl, wpoint::w, width, wpoint::x, point::x, wpoint::y, and point::y.
Referenced by displayitem_draw_polyline(), and draw_compass().
graphics_draw_rectangle()
void graphics_draw_rectangle (struct graphics * this_, struct graphics_gc * gc, struct point * p, int w, int h)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::draw_rectangle, graphics_dpi_scale(), graphics_dpi_scale_point(), graphics::meth, p, graphics::priv, and graphics_gc::priv.
Referenced by graphics_displaylist_draw(), graphics_draw_text_std(), gui_internal_background_render(), gui_internal_label_render(), osd_fill_with_bgcolor(), osd_nav_toggle_announcer_draw(), osd_scale_draw(), pedestrian_graphics_postdraw(), and vehicle_draw_do().
graphics_draw_rectangle_rounded()
void graphics_draw_rectangle_rounded (struct graphics * this_, struct graphics_gc * gc, struct point * plu, int w, int h, int r, int fill)
References ALLOCA_COORD_LIMIT, circle_to_points(), graphics_draw_lines(), graphics_draw_polygon(), p, point::x, and point::y.
graphics_draw_text()
void graphics_draw_text (struct graphics * this_, struct graphics_gc * gc1, struct graphics_gc * gc2, struct graphics_font * font, char * text, struct point * p, int dx, int dy)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::draw_text, graphics_dpi_scale_point(), graphics::meth, p, graphics::priv, graphics_font::priv, and graphics_gc::priv.
Referenced by draw_aligned_osd_text(), draw_multiline_osd_text(), graphics_draw_text_std(), gui_internal_label_render(), label_line(), multiline_label_draw(), osd_compass_draw(), osd_j1850_draw(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_warner_draw(), osd_stopwatch_draw(), and osd_text_draw().
graphics_draw_text_std()
void graphics_draw_text_std (struct graphics * this_, int text_size, char * text, struct point * p)
References bbox(), graphics::gc, get_font(), graphics_draw_rectangle(), graphics_draw_text(), graphics_get_text_bbox(), and p.
Referenced by gui_internal_cmd2_route_height_profile(), and navit_map_progress().
graphics_font_destroy()
void graphics_font_destroy (struct graphics_font * gra_font)
References graphics_font_methods::font_destroy, graphics_font::meth, and graphics_font::priv.
graphics_font_destroy_all()
void graphics_font_destroy_all (struct graphics * gra)
Free all loaded fonts. Used when switching layouts.
Parameters
gra The graphics instance
Returns
nothing
Author
Sarah Nordstrom (05/2008)
References graphics::font, graphics_font_methods::font_destroy, graphics::font_len, graphics_font::meth, and graphics_font::priv.
Referenced by graphics_free(), and navit_set_attr_do().
graphics_font_new()
struct graphics_font* graphics_font_new (struct graphics * gra, int size, int flags)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics::default_font, graphics_named_font_new(), and size.
Referenced by get_font(), and gui_internal_apply_config().
graphics_free()
void graphics_free (struct graphics * gra)
Destroy graphics Called when navit exits
Parameters
gra The graphics instance
Returns
nothing
Author
David Tegze (02/2011)
References attr_list_free(), graphics::attrs, graphics::default_font, graphics::font, g_hash_to_list(), graphics::gc, graphics_methods::graphics_destroy, graphics_font_destroy_all(), graphics_gc_destroy(), graphics::image_cache_hash, graphics_methods::image_free, graphics::meth, graphics::parent, graphics::priv, and graphics_image::priv.
Referenced by navit_destroy(), and vehicle_destroy().
graphics_gc_destroy()
void graphics_gc_destroy (struct graphics_gc * gc)
Destroy a graphics context, freeing associated resources.
Parameters
gc context to destroy
Author
Martin Schaller (04/2008)
References graphics_gc_methods::gc_destroy, graphics_gc::meth, and graphics_gc::priv.
Referenced by display_context_free(), graphics_free(), pedestrian_draw_arrow(), pedestrian_graphics_postdraw(), and vehicle_destroy().
graphics_gc_has_texture()
gboolean graphics_gc_has_texture (struct graphics_gc * gc)
Check if graphic context supports textured backgrounds
Parameters
gc Graphics context handle
Returns
true if supported otherwise false.
Author
metalstrolch (04/2020)
References graphics_gc_methods::gc_set_texture, and graphics_gc::meth.
Referenced by displayitem_draw_polygon(), and graphics_gc_set_texture().
graphics_gc_init()
static void graphics_gc_init (struct graphics * this_) static
References COLOR_BACKGROUND_, COLOR_BLACK_, COLOR_WHITE_, graphics::gc, graphics_gc_set_background(), and graphics_gc_set_foreground().
Referenced by graphics_init(), and graphics_set_attr_do().
graphics_gc_new()
struct graphics_gc* graphics_gc_new (struct graphics * gra)
Create a new graphics context.
Parameters
gra associated graphics object for the new context
Returns
new graphics context
Author
Martin Schaller (04/2008)
References graphics_methods::gc_new, graphics_gc::gra, graphics::meth, graphics_gc::meth, graphics::priv, and graphics_gc::priv.
Referenced by displayitem_draw(), displayitem_draw_circle(), displayitem_draw_text(), graphics_init(), gui_internal_box_render(), gui_internal_setup(), gui_internal_table_render(), osd_button_init(), osd_cmd_interface_init(), osd_compass_init(), osd_image_init(), osd_j1850_init(), osd_odometer_init(), osd_route_guard_init(), osd_set_std_graphic(), osd_stopwatch_init(), pedestrian_draw_arrow(), pedestrian_graphics_postdraw(), and vehicle_draw().
graphics_gc_set_background()
void graphics_gc_set_background (struct graphics_gc * gc, struct color * c)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References c, graphics::colormgmt, graphics_gc_methods::gc_set_background, graphics_gc::gra, graphics_convert_color(), graphics_gc::meth, and graphics_gc::priv.
Referenced by graphics_displaylist_draw(), and graphics_gc_init().
graphics_gc_set_dashes()
void graphics_gc_set_dashes (struct graphics_gc * gc, int width, int offset, unsigned char dash_list[], int n)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References color::a, graphics_gc_methods::gc_set_dashes, graphics_gc::gra, graphics_dpi_scale(), graphics_gc::meth, offset, graphics_gc::priv, and width.
Referenced by displayitem_draw_polyline().
graphics_gc_set_foreground()
void graphics_gc_set_foreground (struct graphics_gc * gc, struct color * c)
Set foreground color.
Parameters
gc graphics context to set color for
c color to set
Author
Martin Schaller (04/2008)
References c, graphics::colormgmt, graphics_gc_methods::gc_set_foreground, graphics_gc::gra, graphics_convert_color(), graphics_gc::meth, and graphics_gc::priv.
Referenced by displayitem_draw(), displayitem_draw_circle(), displayitem_draw_text(), graphics_displaylist_draw(), graphics_gc_init(), gui_internal_box_render(), gui_internal_setup(), gui_internal_table_render(), osd_cmd_interface_init(), osd_compass_init(), osd_j1850_init(), osd_odometer_init(), osd_route_guard_init(), osd_set_std_graphic(), osd_stopwatch_init(), pedestrian_draw_arrow(), pedestrian_graphics_postdraw(), and vehicle_draw().
graphics_gc_set_linewidth()
void graphics_gc_set_linewidth (struct graphics_gc * gc, int width)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_gc_methods::gc_set_linewidth, graphics_gc::gra, graphics_dpi_scale(), graphics_gc::meth, graphics_gc::priv, and width.
Referenced by displayitem_draw_circle(), displayitem_draw_polyline(), gui_internal_box_render(), gui_internal_table_render(), osd_cmd_interface_init(), osd_compass_init(), osd_j1850_init(), osd_odometer_init(), osd_route_guard_init(), and osd_stopwatch_init().
graphics_gc_set_texture()
void graphics_gc_set_texture (struct graphics_gc * gc, struct graphics_image * img)
Set textured background to current graphics context.
Parameters
gc Graphics context handle
img Allocated image
Returns
void
Author
metalstrolch (04/2020)
References graphics_gc_methods::gc_set_texture, graphics_gc_has_texture(), graphics_gc::meth, graphics_gc::priv, and graphics_image::priv.
Referenced by displayitem_draw_polygon().
graphics_get_attr()
int graphics_get_attr (struct graphics * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
Gets an attribute of the graphics instance.
This function searches the attribute list of the graphics object for an attribute of a given type and stores it in the attr parameter.
Searching for attr_any or attr_any_xml is supported.
An iterator can be specified to get multiple attributes of the same type: The first call will return the first match from attr; each subsequent call with the same iterator will return the next match. If no more matching attributes are found in either of them, false is returned.
Note that currently this will only return the generic attributes which can be set with graphics_set_attr_do(struct graphics *, struct attr *). Attributes implemented by a graphics plugin cannot be retrieved with this method.
Parameters
this The graphics instance
type The attribute type to search for
attr Points to a
struct attr
which will receive the attribute
iter An iterator. This parameter may be NULL.
Returns
True if a matching attribute was found, false if not.
Author
Martin Schaller (04/2008)
References attr_generic_get_attr(), graphics::attrs, and type.
Referenced by navit_init().
graphics_get_data()
void* graphics_get_data (struct graphics * this_, const char * type)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::get_data, graphics::meth, graphics::priv, and type.
Referenced by gui_gtk_set_graphics(), gui_internal_menu_menu_resize(), gui_internal_resize(), gui_internal_set_graphics(), gui_qml_set_graphics(), gui_qt5_qml_set_graphics(), navit_get_cursor_pnt(), osd_set_std_graphic(), osd_std_calculate_sizes(), pedestrian_graphics_resize(), request_graphics_get_data(), and win32_gui_set_graphics().
graphics_get_dpi()
navit_float graphics_get_dpi (struct graphics * gra)
get display resolution in DPI This method returns the native display density in DPI
Parameters
gra graphics handle
Returns
dpi value. May be fraction therefore double.
References graphics_methods::get_dpi, graphics::meth, and graphics::priv.
Referenced by graphics_new().
graphics_get_text_bbox()
void graphics_get_text_bbox (struct graphics * this_, struct graphics_font * font, char * text, int dx, int dy, struct point * ret, int estimate)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::get_text_bbox, graphics_dpi_unscale_point(), graphics::meth, graphics::priv, and graphics_font::priv.
Referenced by draw_aligned_osd_text(), draw_multiline_osd_text(), graphics_draw_text_std(), gui_internal_label_font_new(), label_line(), osd_cmd_interface_draw(), osd_compass_draw(), osd_j1850_draw(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_cam_draw(), osd_speed_warner_draw(), osd_stopwatch_draw(), and osd_text_draw().
graphics_hide_native_keyboard()
int graphics_hide_native_keyboard (struct graphics * this_, struct graphics_keyboard * kbd)
Hides the native on-screen keyboard or other input method.
This method is a wrapper around the respective method of the graphics plugin.
A call to this function indicates that Navit no longer needs the input method and is about to reclaim any screen real estate it may have previously reserved for the input method.
On platforms that don't support overlapping windows this means that the on-screen input method should be hidden, as it may otherwise obstruct parts of Navit's UI.
On windowed platforms, where on-screen input methods can be displayed alongside Navit or moved around as needed, the graphics driver should instead notify the on-screen method that it is no longer expecting user input, allowing the input method to take the appropriate action.
The graphics plugin must free any data it has stored in
kbd->gra_priv
and reset the pointer to
NULL
to indicate it has done so.
The caller may free
kbd
after this function returns.
Parameters
this The graphics instance
kbd The keyboard instance
Returns
True if the call was successfully passed to the plugin, false if the method is not supported by the plugin
References graphics_methods::hide_native_keyboard, and graphics::meth.
Referenced by gui_internal_keyboard_hide_native().
graphics_icon_path()
char* graphics_icon_path (const char * icon)
References dbg, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), and lvl_debug.
Referenced by displayitem_draw_icon(), geticon(), image_new_scaled(), osd_button_icon_path(), osd_button_new(), osd_cmd_interface_set_attr(), osd_gps_status_new(), osd_image_new(), osd_nav_next_turn_draw(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_draw(), osd_nav_toggle_announcer_new(), osd_navigation_status_draw_do(), osd_navigation_status_new(), osd_volume_new(), and pedestrian_draw_arrow().
graphics_image_free()
void graphics_image_free (struct graphics * gra, struct graphics_image * img)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
Referenced by display_context_free(), displayitem_draw_icon(), gui_internal_button_attr_update(), gui_internal_widget_destroy(), osd_button_draw(), osd_button_init(), osd_cmd_interface_set_attr(), osd_gps_status_draw(), osd_image_init(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_volume_draw(), and pedestrian_draw_arrow().
graphics_image_new()
struct graphics_image* graphics_image_new (struct graphics * gra, char * path)
Create a new image from file path
Parameters
gra the graphics instance
path path of the image to load
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_image_new_scaled_rotated().
Referenced by osd_cmd_interface_set_attr(), osd_image_init(), and pedestrian_draw_arrow().
graphics_image_new_scaled()
struct graphics_image* graphics_image_new_scaled (struct graphics * gra, char * path, int w, int h)
Create a new image from file path, optionally scaled to w and h pixels.
Parameters
gra the graphics instance
path path of the image to load
w width to rescale to, or IMAGE_W_H_UNSET for original width
h height to rescale to, or IMAGE_W_H_UNSET for original height
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_image_new_scaled_rotated().
Referenced by image_new_scaled(), osd_button_draw(), osd_button_init(), osd_button_set_attr(), osd_gps_status_draw(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), and osd_volume_draw().
graphics_image_new_scaled_rotated()
struct graphics_image* graphics_image_new_scaled_rotated (struct graphics * gra, char * path, int w, int h, int rotate)
Create a new image from file path, optionally scaled to w and h pixels and rotated.
Parameters
gra the graphics instance
path path of the image to load
w width to rescale to, or IMAGE_W_H_UNSET for original width
h height to rescale to, or IMAGE_W_H_UNSET for original height
rotate angle to rotate the image, in 90 degree steps (not supported by all plugins).
Returns
<>
Author
Martin Schaller (04/2008)
References dbg, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), graphics_image::height, graphics::image_cache_hash, image_new_helper(), lvl_debug, lvl_error, name, graphics_image::priv, file_wordexp::we, and graphics_image::width.
Referenced by displayitem_draw_icon(), displayitem_draw_image(), displayitem_draw_polygon(), graphics_image_new(), and graphics_image_new_scaled().
graphics_init()
void graphics_init (struct graphics * this_)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics::gc, graphics_background_gc(), graphics_gc_init(), and graphics_gc_new().
Referenced by navit_handle_resize(), and vehicle_draw().
graphics_is_disabled()
int graphics_is_disabled (struct graphics * this_)
References graphics::disabled, and graphics::parent.
Referenced by osd_std_keypress().
graphics_load_mapset()
static void graphics_load_mapset (struct graphics * gra, struct displaylist * displaylist, struct mapset * mapset, struct transformation * trans, struct layout * l, int async, struct callback * cb, int flags) static
References displaylist::busy, callback_cast, callback_new_3, displaylist::cb, dbg, displaylist::dc, do_draw(), event_add_idle(), display_context::gra, displaylist::idle_cb, displaylist::idle_ev, displaylist::layout, lvl_debug, displaylist::ms, displaylist::order, layout::order_delta, displaylist::seq, display_context::trans, transform_destroy(), transform_dup(), transform_get_order(), displaylist::workload, and xdisplay_free().
Referenced by graphics_draw().
graphics_named_font_new()
struct graphics_font* graphics_named_font_new (struct graphics * gra, char * font, int size, int flags)
References graphics_methods::font_new, graphics_dpi_scale(), graphics::meth, graphics_font::meth, graphics::priv, graphics_font::priv, and size.
Referenced by graphics_font_new(), gui_internal_apply_config(), and osd_set_std_graphic().
graphics_new()
struct graphics* graphics_new (struct attr * parent, struct attr ** attrs)
Creates a new graphics object attr type required
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References attr_generic_add_attr(), attr_list_dup(), attr_search(), attr::attrs, graphics::attrs, graphics::brightness, attr::callback_list, callback_list_add_patch_function(), callback_list_call_attr_2, callback_list_new(), graphics::cbl, cbl, graphics::contrast, dbg, graphics::dpi_factor, graphics::font_size, graphics::gamma, graphics_dpi_patch(), graphics_get_dpi(), graphics_set_attr_do(), graphics::image_cache_hash, lvl_error, graphics::meth, navit_get_height(), navit_get_width(), attr::num, graphics::priv, attr::str, attr::type, and attr::u.
graphics_overlay_disable()
void graphics_overlay_disable (struct graphics * this_, int disable)
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics::disabled, graphics::meth, graphics_methods::overlay_disable, and graphics::priv.
Referenced by gui_internal_check_exit(), gui_internal_enter(), navit_handle_button(), navit_motion_timeout(), osd_speed_cam_draw(), osd_std_config(), osd_std_reconfigure(), pedestrian_rocket_idle(), and vehicle_set_cursor().
graphics_overlay_new()
struct graphics* graphics_overlay_new (struct graphics * parent, struct point * p, int w, int h, int wraparound)
Create a new graphics overlay. An overlay is a graphics object that is independent of the main graphics object. When drawing everything to a window, the overlay will be shown on top of the main graphics object. Navit uses overlays for OSD elements and for the vehicle on the map. This allows updating OSD elements and the vehicle without redrawing the map.
Parameters
parent parent graphics context (should be the main graphics context as returned by graphics_new)
p drawing position for the overlay
w width of overlay
h height of overlay
wraparound use wraparound (0/1). If set, position, width and height "wrap around": negative position coordinates wrap around the window, negative width/height specify difference to window width/height.
Returns
new overlay
Author
Martin Schaller (04/2008)
References graphics::dpi_factor, graphics::font_size, graphics_dpi_scale(), graphics_dpi_scale_point(), graphics_set_rect(), graphics::image_cache_hash, point_rect::lu, graphics::meth, p, graphics::parent, graphics::priv, point_rect::rl, point::x, and point::y.
Referenced by osd_set_std_graphic(), and vehicle_draw().
graphics_overlay_resize()
void graphics_overlay_resize (struct graphics * this_, struct point * p, int w, int h, int wraparound)
Alters the size, position and wraparound for an overlay.
Parameters
this_ The overlay's graphics struct
p The new position of the overlay
w The new width of the overlay
h The new height of the overlay
wraparound The new wraparound of the overlay
References graphics_dpi_scale(), graphics_dpi_scale_point(), graphics::meth, graphics_methods::overlay_resize, p, and graphics::priv.
Referenced by osd_std_resize(), and vehicle_draw().
graphics_process_selection()
static void graphics_process_selection (struct graphics * gra, struct displaylist * dl) static
References graphics_process_selection_item(), and graphics::selection.
Referenced by do_draw().
graphics_process_selection_item()
static void graphics_process_selection_item (struct displaylist * dl, struct item * item) static
References displayitem::c, displaylist::conv, displayitem::count, displaylist::dc, display_add(), item::id_hi, item::id_lo, displayitem::item, item, item_attr_get(), item_coord_get(), displayitem::label, item::map, map_convert_free(), map_convert_string(), map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), max, display_context::maxlen, item::priv_data, attr::str, item::type, and attr::u.
Referenced by graphics_add_selection(), and graphics_process_selection().
graphics_remove_callback()
void graphics_remove_callback (struct graphics * this_, struct callback * cb)
References callback_list_remove(), and graphics::cbl.
Referenced by navit_destroy().
graphics_remove_selection()
void graphics_remove_selection (struct graphics * gra, struct item * item, enum item_type type, struct displaylist * dl)
References displayitem::count, displayitem::item, item_is_equal, displayitem::label, graphics::selection, item::type, and type.
Referenced by graphics_clear_selection().
graphics_set_attr()
int graphics_set_attr (struct graphics * gra, struct attr * attr)
Sets an attribute of the graphics instance.
This method first tries to set one of the private attributes implemented by the current graphics plugin. If this fails, it tries to set one of the generic attributes.
If the graphics plugin does not supply a
set_attr
method, this method currently does nothing and returns true, even if the attribute is a generic one.
Parameters
gra The graphics instance
attr The attribute to set
Returns
True if the attribute was successfully set, false otherwise.
References dbg, graphics_set_attr_do(), lvl_debug, graphics::meth, graphics::priv, and graphics_methods::set_attr.
Referenced by NPP_SetWindow(), pedestrian_navit_init(), and request_graphics_set_attr().
graphics_set_attr_do()
static int graphics_set_attr_do (struct graphics * gra, struct attr * attr) static
Sets a generic attribute of the graphics instance.
This will only set one of the supported generic graphics attributes (currently
gamma
,
brightness
,
contrast
or
font_size
) and fail for other attribute types.
To set an attribute provided by a graphics plugin, use graphics_set_attr(struct graphics *, struct attr *) instead.
Parameters
gra The graphics instance
attr The attribute to set
Returns
True if the attribute was set, false if not
References graphics::brightness, graphics::colormgmt, graphics::contrast, graphics::font_size, graphics::gamma, graphics_gc_init(), attr::num, attr::type, and attr::u.
Referenced by graphics_new(), and graphics_set_attr().
graphics_set_rect()
void graphics_set_rect (struct graphics * gra, struct point_rect * pr)
References graphics::r.
Referenced by graphics_overlay_new(), navit_handle_resize(), and osd_auxmap_draw().
graphics_show_native_keyboard()
int graphics_show_native_keyboard (struct graphics * this_, struct graphics_keyboard * kbd)
Shows the native on-screen keyboard or other input method.
This method is a wrapper around the respective method of the graphics plugin.
The caller should populate the
kbd
argument with appropriate
mode
and
lang
members so the graphics plugin can determine the best matching layout.
If an input method is shown, the graphics plugin should try to select the configuration which best matches the specified
mode
. For example, if
mode
specifies a numeric layout, the graphics plugin should select a numeric keyboard layout (if available), or the equivalent for another input method (such as setting stroke recognition to identify strokes as numbers). Likewise, when an alphanumeric-uppercase mode is requested, it should switch to uppercase input.
Implementations should, however, consider that Navit's internal keyboard allows the user to switch modes at will (the only exception being degree mode) and thus must not "lock" the user into a limited layout with no means to switch to a general-purpose one. For example, house number entry in an address search dialog may default to numeric mode, but since some house numbers may contain non-numeric characters, a pure numeric keyboard is suitable only if the user has the option to switch to an alphanumeric layout.
When multiple alphanumeric layouts are available, the graphics plugin should use the
lang
argument to determine the best layout.
When selecting an input method, preference should always be given to the default or last selected input method and configuration if it matches the requested
mode
and
lang
.
If the native input method is going to obstruct parts of Navit's UI, the graphics plugin should set
kbd->w
and
kbd->h
to the height and width to the appropriate value in pixels. A value of -1 indicates that the input method fills the entire available width or height of the space available to Navit. On windowed platforms, where the on-screen input method and Navit's window may be moved relative to each other as needed and can be displayed alongside each other, the graphics plugin should report 0 for both dimensions.
Parameters
this_ The graphics instance
kbd The keyboard instance
Returns
1 if the native keyboard is going to be displayed, 0 if not, -1 if the method is not supported by the plugin
References dbg, lvl_debug, graphics::meth, and graphics_methods::show_native_keyboard.
Referenced by gui_internal_keyboard_show_native().
graphics_texture_path()
char* graphics_texture_path (const char * texture)
References dbg, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), and lvl_debug.
Referenced by displayitem_draw_polygon().
image_new_helper()
static void image_new_helper (struct graphics * gra, struct graphics_image * this_, char * path, char * name, int width, int height, int rotate) static
References dbg, graphics_dpi_scale(), graphics_dpi_scale_point(), graphics_dpi_unscale(), graphics_dpi_unscale_point(), graphics_image::height, height, graphics_image::hot, graphics_methods::image_new, lvl_debug, lvl_info, graphics::meth, graphics_image::meth, name, graphics::priv, graphics_image::priv, graphics_image::width, and width.
Referenced by graphics_image_new_scaled_rotated().
intersection()
static int intersection (struct point * a1, int adx, int ady, struct point * b1, int bdx, int bdy, struct point * res) static
References dbg, lvl_debug, point::x, and point::y.
Referenced by draw_middle(), and transform_reverse_near_far().
is_inside()
static int is_inside (struct point * p, struct point_rect * r, int edge) static
References point_rect::lu, p, point_rect::rl, point::x, and point::y.
Referenced by graphics_clip_polygon().
label_line()
static void label_line (struct graphics * gra, struct graphics_gc * fg, struct graphics_gc * bg, struct graphics_font * font, struct point * p, int count, char * label) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References graphics_methods::get_text_bbox, graphics_draw_text(), graphics_get_text_bbox(), label, point_rect::lu, graphics::meth, p, graphics::r, point::x, and point::y.
Referenced by displayitem_draw_text().
limit_count()
static int limit_count (struct coord * c, int count) static
References c.
Referenced by displayitem_draw(), and displayitem_transform_holes().
multiline_label_draw()
static void multiline_label_draw (struct graphics * gra, struct graphics_gc * fg, struct graphics_gc * bg, struct graphics_font * font, struct point pref, const char * label, int line_spacing) static
Draw a multi-line text next to a specified point pref.
Parameters
gra The graphics instance on which to draw
fg The graphics color to use to draw the text
bg The graphics background color to use to draw the text
font The font to use to draw the text
pref The position to draw the text (draw at the right and vertically aligned relatively to this point)
label The text to draw (may contain '
' for multiline text, if so lines will be stacked vertically)
line_spacing The delta between each line (set its value at to least the font text size, to be readable)
References dbg, graphics_draw_text(), label, lvl_warning, point::x, and point::y.
Referenced by displayitem_draw_circle().
poly_intersection()
static void poly_intersection (struct point * p1, struct point * p2, struct point_rect * r, int edge, struct point * ret) static
References point_rect::lu, point_rect::rl, point::x, and point::y.
Referenced by graphics_clip_polygon().
relative_pos()
static int relative_pos (struct wpoint * p, struct point_rect * r) static
References ABOVE, BELOW, INSIDE, LEFT_OF, point_rect::lu, p, RIGHT_OF, point_rect::rl, point::x, and point::y.
set_hash_entry()
static struct hash_entry* set_hash_entry (struct displaylist * dl, enum item_type type) static
References displaylist::hash_entries, HASH_SIZE, displaylist::max_offset, offset, hash_entry::type, and type.
Referenced by displaylist_update_layers().
within_dist_line()
static int within_dist_line (struct point * p, struct point * line_p0, struct point * line_p1, int dist) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References c1, c2, p, within_dist_point(), point::x, and point::y.
Referenced by within_dist_polyline().
within_dist_point()
static int within_dist_point (struct point * p0, struct point * p1, int dist) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References point::x, and point::y.
Referenced by graphics_displayitem_within_dist(), and within_dist_line().
within_dist_polygon()
static int within_dist_polygon (struct point * p, struct point * poly_pnt, int count, int dist) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References c, p, within_dist_polyline(), point::x, and point::y.
Referenced by graphics_displayitem_within_dist().
within_dist_polyline()
static int within_dist_polyline (struct point * p, struct point * line_pnt, int count, int dist, int close) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References p, and within_dist_line().
Referenced by graphics_displayitem_within_dist(), and within_dist_polygon().
xdisplay_draw()
static void xdisplay_draw (struct displaylist * display_list, struct graphics * gra, struct layout * l, int order) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References layer::active, graphics::current_z_order, layout::layers, layer::ref, and xdisplay_draw_layer().
Referenced by graphics_displaylist_draw().
xdisplay_draw_elements()
static void xdisplay_draw_elements (struct graphics * gra, struct displaylist * display_list, struct itemgra * itm, struct layout * l) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References displaylist::dc, hash_entry::di, display_context_free(), displayitem_draw(), display_context::e, itemgra::elements, get_hash_entry(), display_context::type, itemgra::type, and types.
Referenced by xdisplay_draw_layer().
xdisplay_draw_layer()
static void xdisplay_draw_layer (struct displaylist * display_list, struct graphics * gra, struct layer * lay, int order, struct layout * l) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References layer::itemgras, and xdisplay_draw_elements().
Referenced by xdisplay_draw().
xdisplay_free()
static void xdisplay_free (struct displaylist * dl) static
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
References hash_entry::di, displaylist::hash_entries, HASH_SIZE, displayitem::next, and next.
Referenced by graphics_load_mapset().
Variable Documentation
circle64
struct circle circle64[]
Referenced by circle_to_points(), draw_begin(), and draw_end().
route_selection
void* route_selection extern
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
Referenced by do_draw().