navit: graphics/null/graphics_null.c File Reference
graphics_null.c File Reference
#include <glib.h>
#include "config.h"
#include "item.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "plugin.h"
#include "event.h"
#include "debug.h"
#include "window.h"
#include "callback.h"
Data Structures
struct graphics_priv
struct graphics_font_priv
struct graphics_gc_priv
struct graphics_image_priv
Functions
static void graphics_destroy (struct graphics_priv *gr)
static void font_destroy (struct graphics_font_priv *font)
static struct graphics_font_priv * font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static void resize_callback (int w, int h)
static int graphics_null_fullscreen (struct window *w, int on)
static void graphics_null_disable_suspend (struct window *w)
static void * get_data (struct graphics_priv *this, char const *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void overlay_disable (struct graphics_priv *gr, int disable)
static void overlay_resize (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
static struct graphics_priv * graphics_null_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
static void event_null_main_loop_run (void)
static void event_null_main_loop_quit (void)
static struct event_watch * event_null_add_watch (int h, enum event_watch_cond cond, struct callback *cb)
static void event_null_remove_watch (struct event_watch *ev)
static struct event_timeout * event_null_add_timeout (int timeout, int multi, struct callback *cb)
static void event_null_remove_timeout (struct event_timeout *to)
static struct event_idle * event_null_add_idle (int priority, struct callback *cb)
static void event_null_remove_idle (struct event_idle *ev)
static void event_null_call_callback (struct callback_list *cb)
static struct event_priv * event_null_new (struct event_methods *meth)
void plugin_init (void)
Variables
static struct callback_list * callbacks
static struct graphics_priv graphics_priv
static struct graphics_font_priv graphics_font_priv
static struct graphics_gc_priv graphics_gc_priv
static struct graphics_image_priv graphics_image_priv
static struct graphics_font_methods font_methods
static struct graphics_gc_methods gc_methods
static struct graphics_methods graphics_methods
static struct event_methods event_null_methods
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
static void draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
static void draw_drag (struct graphics_priv * gr, struct point * p) static
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
static struct event_idle* event_null_add_idle (int priority, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static struct event_timeout* event_null_add_timeout (int timeout, int multi, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static struct event_watch* event_null_add_watch (int h, enum event_watch_cond cond, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static void event_null_call_callback (struct callback_list * cb) static
References dbg, and lvl_debug.
static void event_null_main_loop_quit (void) static
References dbg, and lvl_debug.
static void event_null_main_loop_run (void) static
References dbg, and lvl_debug.
static struct event_priv* event_null_new (struct event_methods * meth) static
References event_null_methods, and NULL.
Referenced by plugin_init().
static void event_null_remove_idle (struct event_idle * ev) static
References dbg, and lvl_debug.
static void event_null_remove_timeout (struct event_timeout * to) static
References dbg, and lvl_debug.
static void event_null_remove_watch (struct event_watch * ev) static
References dbg, and lvl_debug.
static void font_destroy (struct graphics_font_priv * font) static
static struct graphics_font_priv* font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * font, int size, int flags) static
References font_methods, and graphics_font_priv.
static void gc_destroy (struct graphics_gc_priv * gc) static
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References gc_methods, and graphics_gc_priv.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
static void* get_data (struct graphics_priv * this, char const * type) static
References window::disable_suspend, window::fullscreen, g_new0, graphics_null_disable_suspend(), graphics_null_fullscreen(), NULL, window::priv, and resize_callback().
static void get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate) static
static void graphics_destroy (struct graphics_priv * gr) static
static void graphics_null_disable_suspend (struct window * w) static
Referenced by get_data().
static int graphics_null_fullscreen (struct window * w, int on) static
Referenced by get_data().
static struct graphics_priv* graphics_null_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), cbl, dbg, event_request_system(), graphics_methods, graphics_priv, lvl_debug, NULL, resize_callback(), attr::str, and attr::u.
Referenced by plugin_init().
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References graphics_image_priv.
static void overlay_disable (struct graphics_priv * gr, int disable) static
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References graphics_methods, and graphics_priv.
static void overlay_resize (struct graphics_priv * gr, struct point * p, int w, int h, int wraparound) static
void plugin_init (void)
References event_null_new(), and graphics_null_new().
static void resize_callback (int w, int h) static
References callback_list_call_attr_2, and GINT_TO_POINTER.
Referenced by get_data(), and graphics_null_new().
Variable Documentation
struct callback_list* callbacks static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
struct event_methods event_null_methods static
Initial value:
= {
        event_null_main_loop_run,
        event_null_main_loop_quit,
        event_null_add_watch,
        event_null_remove_watch,
        event_null_add_timeout,
        event_null_remove_timeout,
        event_null_add_idle,
        event_null_remove_idle,
        event_null_call_callback,
}
Referenced by event_null_new().
struct graphics_font_methods font_methods static
Initial value:
= {
        font_destroy
}
Referenced by font_new().
struct graphics_gc_methods gc_methods static
Initial value:
= {
        gc_destroy,
        gc_set_linewidth,
        gc_set_dashes,
        gc_set_foreground,
        gc_set_background
}
Referenced by gc_new().
struct graphics_font_priv graphics_font_priv static
Referenced by font_new().
struct graphics_gc_priv graphics_gc_priv static
Referenced by gc_new().
struct graphics_image_priv graphics_image_priv static
Referenced by image_new().
struct graphics_methods graphics_methods static
Initial value:
= {
        graphics_destroy,
        draw_mode,
        draw_lines,
        draw_polygon,
        draw_rectangle,
        draw_circle,
        draw_text,
        draw_image,
        NULL,
        draw_drag,
        font_new,
        gc_new,
        background_gc,
        overlay_new,
        image_new,
        get_data,
        image_free,
        get_text_bbox,
        overlay_disable,
        overlay_resize,
        NULL,
        NULL,
}
Referenced by graphics_null_new(), and overlay_new().
struct graphics_priv graphics_priv static
Referenced by graphics_null_new(), graphics_qt5_new(), and overlay_new().