navit: graphics/qt_qpainter/graphics_qt_qpainter.cpp File Reference
graphics_qt_qpainter.cpp File Reference
#include "graphics_qt_qpainter.h"
#include "RenderArea.h"
Data Structures
struct graphics_font_priv
struct graphics_image_priv
Functions
static void overlay_rect (struct graphics_priv *parent, struct graphics_priv *overlay, int clean, QRect *r)
void qt_qpainter_draw (struct graphics_priv *gr, const QRect *r, int paintev)
static void graphics_destroy (struct graphics_priv *gr)
static void font_destroy (struct graphics_font_priv *font)
static struct graphics_font_priv * font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *fontfamily, int size, int flags)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static int fullscreen (struct window *win, int on)
static void disable_suspend (struct window *win)
static void * get_data (struct graphics_priv *this_, const char *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void overlay_disable (struct graphics_priv *gr, int disable)
static int set_attr (struct graphics_priv *gr, struct attr *attr)
static struct graphics_priv * graphics_qt_qpainter_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
register vehicle_gypsy
Variables
static struct graphics_font_methods font_methods
static struct graphics_gc_methods gc_methods
static int argc = 1
static char * argv [] = {NULL,NULL,NULL}
static struct graphics_methods graphics_methods
Function Documentation
background_gc()
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References color::a, color::b, graphics_priv::background_gc, graphics_gc_priv::c, color::g, color::r, and graphics_priv::rgba.
disable_suspend()
static void disable_suspend (struct window * win) static
References graphics_priv::app, and window::priv.
Referenced by get_data().
draw_circle()
static void draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_priv::painter, graphics_gc_priv::pen, point::x, and point::y.
draw_drag()
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_priv::cleanup, p, graphics_priv::p, graphics_priv::pclean, point::x, and point::y.
draw_image()
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_priv::painter, graphics_image_priv::pixmap, point::x, and point::y.
draw_lines()
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_priv::painter, graphics_gc_priv::pen, point::x, and point::y.
draw_mode()
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References graphics_priv::cleanup, dbg, draw_mode_begin, draw_mode_end, graphics_priv::h, lvl_debug, graphics_priv::mode, overlay_new(), overlay_rect(), p, graphics_priv::painter, graphics_priv::parent, qt_qpainter_draw(), color::r, graphics_priv::w, graphics_priv::widget, and graphics_priv::wraparound.
draw_polygon()
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::brush, graphics_priv::painter, graphics_gc_priv::pen, point::x, and point::y.
draw_rectangle()
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_gc_priv::brush, dbg, lvl_debug, graphics_priv::painter, point::x, and point::y.
draw_text()
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References graphics_gc_priv::c, data, font_freetype_glyph::dx, font_freetype_glyph::dy, graphics_font_priv::font, graphics_priv::freetype_methods, font_freetype_methods::get_glyph, font_freetype_methods::get_shadow, font_freetype_text::glyph, font_freetype_text::glyph_count, font_freetype_glyph::h, graphics_priv::painter, graphics_gc_priv::pen, font_freetype_methods::text_destroy, font_freetype_methods::text_new, font_freetype_glyph::w, point::x, font_freetype_glyph::x, point::y, and font_freetype_glyph::y.
font_destroy()
static void font_destroy (struct graphics_font_priv * font) static
font_new()
static struct graphics_font_priv* font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * fontfamily, int size, int flags) static
References graphics_font_priv::font, and font_methods.
fullscreen()
static int fullscreen (struct window * win, int on) static
References window::priv, and graphics_priv::widget.
Referenced by get_data(), graphics_qt5_new(), gui_gtk_new(), gui_internal_get_attr(), gui_internal_new(), gui_internal_set_attr(), gui_internal_set_graphics(), and keypress().
gc_destroy()
static void gc_destroy (struct graphics_gc_priv * gc) static
References graphics_gc_priv::brush, and graphics_gc_priv::pen.
gc_new()
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References graphics_gc_priv::brush, gc_methods, and graphics_gc_priv::pen.
gc_set_background()
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
gc_set_dashes()
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
gc_set_foreground()
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::b, graphics_gc_priv::brush, graphics_gc_priv::c, c, color::g, graphics_gc_priv::pen, and color::r.
gc_set_linewidth()
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_priv::pen.
get_data()
static void* get_data (struct graphics_priv * this_, const char * type) static
References dbg, window::disable_suspend, disable_suspend(), window::fullscreen, fullscreen(), graphics_priv::h, lvl_debug, window::priv, graphics_font_priv::size, graphics_priv::w, and graphics_priv::widget.
get_text_bbox()
static void get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate) static
References graphics_font_priv::font, graphics_priv::h, graphics_priv::painter, graphics_priv::w, point::x, and point::y.
graphics_destroy()
static void graphics_destroy (struct graphics_priv * gr) static
References font_freetype_methods::destroy, graphics_priv::freetype_methods, and graphics_priv::window_title.
graphics_qt_qpainter_new()
static struct graphics_priv* graphics_qt_qpainter_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References graphics_priv::app, argc, argv, attr_search(), cbl, dbg, event_request_system(), graphics_priv::flags, graphics_priv::font_freetype_new, font_freetype_new(), font_freetype_methods::font_new, graphics_methods::font_new, graphics_priv::freetype_methods, font_freetype_methods::get_text_bbox, graphics_methods::get_text_bbox, graphics_methods, graphics_priv::h, lvl_debug, lvl_error, graphics_priv::nav, attr::num, graphics_priv::painter, attr::str, attr::u, graphics_priv::w, graphics_priv::widget, and graphics_priv::window_title.
Referenced by plugin_init().
image_free()
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
References graphics_image_priv::pixmap.
image_new()
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References insert, key, graphics_image_priv::pixmap, point::x, and point::y.
overlay_disable()
static void overlay_disable (struct graphics_priv * gr, int disable) static
References graphics_priv::overlay_disable.
overlay_new()
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References graphics_priv::app, event_watch::cb, dbg, event_qt_remove_timeout(), exit, event_watch::fd, graphics_priv::font_freetype_new, font_freetype_methods::font_new, graphics_methods::font_new, graphics_priv::freetype_methods, font_freetype_methods::get_text_bbox, graphics_methods::get_text_bbox, graphics_methods, event_timeout::id, lvl_debug, event_timeout::multi, graphics_priv::next, graphics_priv::overlays, p, graphics_priv::p, graphics_priv::painter, graphics_priv::parent, event_watch::sn, graphics_priv::widget, and graphics_priv::wraparound.
Referenced by draw_mode().
overlay_rect()
static void overlay_rect (struct graphics_priv * parent, struct graphics_priv * overlay, int clean, QRect * r) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References graphics_priv::p, graphics_priv::pclean, graphics_priv::widget, graphics_priv::wraparound, point::x, and point::y.
Referenced by draw_mode(), and qt_qpainter_draw().
plugin_init()
void plugin_init (void)
register vehicle_gypsy
Returns
nothing
References graphics_qt_qpainter_new().
qt_qpainter_draw()
void qt_qpainter_draw (struct graphics_priv * gr, const QRect * r, int paintev)
References graphics_priv::background_gc, graphics_gc_priv::brush, data, dbg, graphics_font_priv::font, lvl_debug, graphics_priv::next, graphics_priv::overlay, graphics_priv::overlay_disable, overlay_rect(), graphics_priv::overlays, graphics_priv::p, graphics_gc_priv::pen, graphics_priv::pixmap, graphics_priv::rgba, size, graphics_priv::widget, point::x, and point::y.
Referenced by draw_mode(), and RenderArea::paintEvent().
set_attr()
static int set_attr (struct graphics_priv * gr, struct attr * attr) static
References graphics_priv::h, attr::num, graphics_font_priv::size, attr::type, attr::u, graphics_priv::w, and graphics_priv::widget.
Variable Documentation
argc
int argc = 1 static
Referenced by g2n_get_descr(), geod_set(), graphics_opengl_new(), graphics_qt_qpainter_new(), main(), main_real(), and speechd_say().
argv
char* argv[] = {NULL,NULL,NULL} static
Referenced by g2n_get_descr(), graphics_qt_qpainter_new(), main_real(), navit_cmd_spawn(), and speechd_say().
font_methods
struct graphics_font_methods font_methods static
Initial value:
= {
    font_destroy
}
Referenced by font_new().
gc_methods
struct graphics_gc_methods gc_methods static
Initial value:
= {
    gc_destroy,
    gc_set_linewidth,
    gc_set_dashes,
    gc_set_foreground,
    gc_set_background
}
Referenced by gc_new().
graphics_methods
struct graphics_methods graphics_methods static
Initial value:
= {
    graphics_destroy,
    draw_mode,
    draw_lines,
    draw_polygon,
    draw_rectangle,
    draw_circle,
    draw_text,
    draw_image,
    NULL,
    draw_drag,
    font_new,
    gc_new,
    background_gc,
    overlay_new,
    image_new,
    get_data,
    image_free,
    get_text_bbox,
    overlay_disable,
    NULL,
    set_attr,
    NULL,
    NULL,
}
Referenced by graphics_qt_qpainter_new(), and overlay_new().