navit: graphics/opengl/graphics_opengl_x11.c File Reference
graphics_opengl_x11.c File Reference
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <glib.h>
#include "debug.h"
#include "event.h"
#include "callback.h"
#include "graphics_opengl.h"
Data Structures
struct graphics_opengl_window_system
Functions
static void graphics_opengl_x11_destroy (struct graphics_opengl_window_system *x11)
static void * graphics_opengl_get_display (struct graphics_opengl_window_system *x11)
static void * graphics_opengl_get_window (struct graphics_opengl_window_system *x11)
static void graphics_opengl_set_callbacks (struct graphics_opengl_window_system *x11, void *data, void *resize, void *button, void *motion, void *keypress)
static void graphics_opengl_x11_watch (struct graphics_opengl_window_system *x11)
struct
graphics_opengl_window_system * graphics_opengl_x11_new (void *displayname, int w, int h, int depth, struct graphics_opengl_window_system_methods **methods)
Variables
struct
graphics_opengl_window_system_methods graphics_opengl_x11_methods
Function Documentation
static void* graphics_opengl_get_display (struct graphics_opengl_window_system * x11) static
References graphics_opengl_window_system::display.
static void* graphics_opengl_get_window (struct graphics_opengl_window_system * x11) static
References graphics_opengl_window_system::window.
static void graphics_opengl_set_callbacks (struct graphics_opengl_window_system * x11, void * data, void * resize, void * button, void * motion, void * keypress) static
References graphics_opengl_window_system::button, graphics_opengl_window_system::data, data, graphics_opengl_window_system::keypress, keypress(), graphics_opengl_window_system::motion, and graphics_opengl_window_system::resize.
static void graphics_opengl_x11_destroy (struct graphics_opengl_window_system * x11) static
References callback_destroy(), graphics_opengl_window_system::cb, graphics_opengl_window_system::colormap, graphics_opengl_window_system::display, event_remove_watch(), g_free(), graphics_opengl_window_system::watch, and graphics_opengl_window_system::window.
Referenced by graphics_opengl_x11_new().
struct graphics_opengl_window_system* graphics_opengl_x11_new (void * displayname, int w, int h, int depth, struct graphics_opengl_window_system_methods ** methods)
References callback_cast, callback_new_1, graphics_opengl_window_system::cb, graphics_opengl_window_system::colormap, dbg, graphics_opengl_window_system::display, event_add_watch(), event_request_system(), event_watch_cond_read, g_new0, graphics_opengl_x11_destroy(), graphics_opengl_x11_methods, graphics_opengl_x11_watch(), lvl_error, NULL, graphics_opengl_window_system::root_window, graphics_opengl_window_system::screen, graphics_opengl_window_system::visual, graphics_opengl_window_system::watch, and graphics_opengl_window_system::window.
Referenced by get_data().
static void graphics_opengl_x11_watch (struct graphics_opengl_window_system * x11) static
References graphics_opengl_window_system::button, graphics_opengl_window_system::data, dbg, graphics_opengl_window_system::display, lvl_debug, and graphics_opengl_window_system::motion.
Referenced by graphics_opengl_x11_new().
Variable Documentation
struct graphics_opengl_window_system_methods graphics_opengl_x11_methods
Initial value:
= {
        graphics_opengl_x11_destroy,
        graphics_opengl_get_display,
        graphics_opengl_get_window,
        graphics_opengl_set_callbacks,
}
Referenced by graphics_opengl_x11_new().