navit: graphics/win32/graphics_win32.c File Reference
graphics_win32.c File Reference
#include <windows.h>
#include <windowsx.h>
#include <wingdi.h>
#include <glib.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "config.h"
#include "debug.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "callback.h"
#include "plugin.h"
#include "item.h"
#include "window.h"
#include "graphics_win32.h"
#include "xpm2bmp.h"
#include "support/win32/ConvertUTF.h"
#include "profile.h"
#include "keys.h"
#include "png.h"
Data Structures
struct graphics_priv
struct window_priv
struct graphics_image_priv
struct graphics_gc_priv
struct graphics_font_priv
struct event_timeout
Macros
#define STRETCH_HALFTONE 4
#define GET_WHEEL_DELTA_WPARAM(wParam) ((short)HIWORD(wParam))
#define EZ_ATTR_BOLD 1
#define EZ_ATTR_ITALIC 2
#define EZ_ATTR_UNDERLINE 4
#define EZ_ATTR_STRIKEOUT 8
Typedefs
typedef int nXOriginDest
typedef int int nYOriginDest
typedef int int int nWidthDest
typedef int int int int nHeightDest
typedef int int int int HDC hdcSrc
typedef int int int int HDC int nXOriginSrc
typedef int int int int HDC int int nYOriginSrc
typedef int int int int HDC
int int int nWidthSrc
typedef int int int int HDC
int int int int nHeightSrc
typedef int int int int HDC
int int int int BLENDFUNCTION blendFunction
typedef int mode
Functions
typedef BOOL (WINAPI *FP_AlphaBlend)(HDC hdcDest
typedef int (WINAPI *FP_SetStretchBltMode)(HDC dc
HFONT EzCreateFont (HDC hdc, TCHAR *szFaceName, int iDeciPtHeight, int iDeciPtWidth, int iAttributes, BOOL fLogRes)
static void ErrorExit (LPTSTR lpszFunction)
static void create_memory_dc (struct graphics_priv *gr)
static void HandleButtonClick (struct graphics_priv *gra_priv, int updown, int button, long lParam)
static void HandleKeyChar (struct graphics_priv *gra_priv, WPARAM wParam)
static void HandleKeyDown (struct graphics_priv *gra_priv, WPARAM wParam)
static LRESULT CALLBACK WndProc (HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam)
static int fullscreen (struct window *win, int on)
void WINAPI SystemIdleTimerReset (void)
static struct event_timeout * event_win32_add_timeout (int timeout, int multi, struct callback *cb)
static void disable_suspend (struct window *win)
static HANDLE CreateGraphicsWindows (struct graphics_priv *gr, HMENU hMenu)
static void graphics_destroy (struct graphics_priv *gr)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int width, int offset, unsigned char dash_list[], int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static void * get_data (struct graphics_priv *this_, const char *type)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void font_destroy (struct graphics_font_priv *font)
static struct graphics_font_priv * font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *name, int size, int flags)
static int pngdecode (struct graphics_priv *gr, char *name, struct graphics_image_priv *img)
static void pngscale (struct graphics_image_priv *img, struct graphics_priv *gr, int width, int height)
static void pngrender (struct graphics_image_priv *img, struct graphics_priv *gr, int x0, int y0)
static int xpmdecode (char *name, struct graphics_image_priv *img)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *name, int *w, int *h, struct point *hot, int rotation)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static struct graphics_priv * graphics_win32_new_helper (struct graphics_methods *meth)
static void overlay_resize (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static void overlay_disable (struct graphics_priv *gr, int disable)
static void get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void bind_late (struct graphics_priv *gra_priv)
static struct graphics_priv * graphics_win32_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
static void event_win32_main_loop_run (void)
static void event_win32_main_loop_quit (void)
static struct event_watch * event_win32_add_watch (int h, enum event_watch_cond cond, struct callback *cb)
static void event_win32_remove_watch (struct event_watch *ev)
static void run_timer (UINT_PTR idEvent)
static VOID CALLBACK win32_timer_cb (HWND hwnd, UINT uMsg, UINT_PTR idEvent, DWORD dwTime)
static void event_win32_remove_timeout (struct event_timeout *to)
static struct event_idle * event_win32_add_idle (int priority, struct callback *cb)
static void event_win32_remove_idle (struct event_idle *ev)
static void event_win32_call_callback (struct callback_list *cb)
static struct event_priv * event_win32_new (struct event_methods *meth)
void plugin_init (void)
Variables
static HWND g_hwnd = NULL
static const TCHAR g_szClassName [] = {'N','A','V','G','R','A','\0'}
static struct graphics_gc_methods gc_methods
static struct graphics_font_methods font_methods
static struct graphics_methods graphics_methods
static GList * timers
static struct event_methods event_win32_methods
Macro Definition Documentation
#define EZ_ATTR_BOLD 1
Referenced by EzCreateFont().
#define EZ_ATTR_ITALIC 2
Referenced by EzCreateFont().
#define EZ_ATTR_STRIKEOUT 8
Referenced by EzCreateFont().
#define EZ_ATTR_UNDERLINE 4
Referenced by EzCreateFont().
#define GET_WHEEL_DELTA_WPARAM (wParam) ((short)HIWORD(wParam))
#define STRETCH_HALFTONE 4
Referenced by pngscale().
Typedef Documentation
typedef int int int int HDC int int int int BLENDFUNCTION blendFunction
typedef int int int int HDC hdcSrc
typedef int mode
typedef int int int int nHeightDest
typedef int int int int HDC int int int int nHeightSrc
typedef int int int nWidthDest
typedef int int int int HDC int int int nWidthSrc
typedef int nXOriginDest
typedef int int int int HDC int nXOriginSrc
typedef int int nYOriginDest
typedef int int int int HDC int int nYOriginSrc
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References graphics_priv::bg_color, graphics_gc_priv::bg_color, graphics_priv::height, graphics_priv::hMemDC, and graphics_priv::width.
static void bind_late (struct graphics_priv * gra_priv) static
References graphics_priv::AlphaBlend, dbg, graphics_priv::hCoreDll, graphics_priv::hGdi32Dll, graphics_priv::hUser32Dll, lvl_error, lvl_warning, and graphics_priv::SetStretchBltMode.
Referenced by graphics_win32_new().
typedef BOOL (WINAPI * FP_AlphaBlend)
Referenced by _chsize(), initBth(), InitCeGlue(), speech_message_dispatcher(), and wince_reader_thread().
static void create_memory_dc (struct graphics_priv * gr) static
References dbg, graphics_priv::hBitmap, graphics_priv::height, graphics_priv::hMemDC, graphics_priv::hOldBitmap, graphics_priv::hOldPrebuildBitmap, graphics_priv::hPrebuildBitmap, graphics_priv::hPrebuildDC, lvl_debug, NULL, graphics_priv::pPixelData, void(), graphics_priv::width, and graphics_priv::wnd_handle.
Referenced by CreateGraphicsWindows(), overlay_new(), overlay_resize(), and WndProc().
static HANDLE CreateGraphicsWindows (struct graphics_priv * gr, HMENU hMenu) static
References callback_list_call_attr_2, graphics_priv::cbl, create_memory_dc(), dbg, graphics_priv::frame, g_hwnd, g_szClassName, graphics_priv::height, L, lvl_error, NULL, graphics_priv::width, graphics_priv::wnd_handle, graphics_priv::wnd_parent_handle, WndProc(), graphics_priv::x, and graphics_priv::y.
Referenced by draw_mode(), and get_data().
static void disable_suspend (struct window * win) static
References callback_new(), event_win32_add_timeout(), window_priv::hBackLight, NULL, window::priv, and SystemIdleTimerReset().
Referenced by get_data().
static void draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_priv::hMemDC, graphics_gc_priv::hpen, point::x, and point::y.
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_priv::disabled, FALSE, graphics_priv::height, graphics_priv::p, graphics_priv::parent, TRUE, graphics_priv::width, point::x, and point::y.
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_priv::hMemDC, graphics_image_priv::png_pixels, pngrender(), graphics_image_priv::pxpm, point::x, Xpm2bmp_paint(), and point::y.
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_priv::hMemDC, graphics_gc_priv::hpen, i, NULL, point::x, and point::y.
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References graphics_priv::bg_color, CreateGraphicsWindows(), dbg, draw_mode_begin, draw_mode_end, FALSE, graphics_priv::height, graphics_priv::hMemDC, graphics_priv::hOldPrebuildBitmap, graphics_priv::hPrebuildBitmap, graphics_priv::hPrebuildDC, ID_CHILD_GFX, lvl_debug, graphics_priv::mode, NULL, void(), graphics_priv::width, and graphics_priv::wnd_handle.
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References g_alloca, graphics_gc_priv::hbrush, graphics_priv::hMemDC, graphics_gc_priv::hpen, i, point::x, and point::y.
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_gc_priv::hbrush, graphics_priv::hMemDC, graphics_gc_priv::hpen, point::x, and point::y.
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References conversionOK, ConvertUTF8toUTF16(), EzCreateFont(), graphics_gc_priv::fg_alpha, graphics_gc_priv::fg_color, graphics_font_priv::hfont, graphics_priv::hMemDC, lenientConversion, graphics_font_priv::lf, NULL, graphics_font_priv::size, TRUE, graphics_priv::wnd_handle, point::x, and point::y.
static void ErrorExit (LPTSTR lpszFunction) static
References _tprintf, dbg, lvl_error, and NULL.
static struct event_idle* event_win32_add_idle (int priority, struct callback * cb) static
References event_win32_add_timeout().
static struct event_timeout * event_win32_add_timeout (int timeout, int multi, struct callback * cb) static
References event_timeout::cb, dbg, g_list_prepend(), g_new0, lvl_debug, event_timeout::multi, NULL, event_timeout::timer_id, and win32_timer_cb().
Referenced by disable_suspend(), and event_win32_add_idle().
static struct event_watch* event_win32_add_watch (int h, enum event_watch_cond cond, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static void event_win32_call_callback (struct callback_list * cb) static
References g_hwnd.
static void event_win32_main_loop_quit (void) static
References dbg, g_hwnd, L, lvl_debug, and NULL.
static void event_win32_main_loop_run (void) static
References dbg, and lvl_debug.
static struct event_priv* event_win32_new (struct event_methods * meth) static
References event_win32_methods, and NULL.
Referenced by plugin_init().
static void event_win32_remove_idle (struct event_idle * ev) static
References event_win32_remove_timeout().
static void event_win32_remove_timeout (struct event_timeout * to) static
References _GList::data, dbg, g_free(), g_list_next, g_list_remove(), lvl_debug, lvl_error, NULL, event_timeout::timer_id, and timers.
Referenced by event_win32_remove_idle().
static void event_win32_remove_watch (struct event_watch * ev) static
References dbg, and lvl_debug.
HFONT EzCreateFont (HDC hdc, TCHAR * szFaceName, int iDeciPtHeight, int iDeciPtWidth, int iAttributes, BOOL fLogRes)
References EZ_ATTR_BOLD, EZ_ATTR_ITALIC, EZ_ATTR_STRIKEOUT, EZ_ATTR_UNDERLINE, int(), and NULL.
Referenced by draw_text().
static void font_destroy (struct graphics_font_priv * font) static
References g_free(), and graphics_font_priv::hfont.
static struct graphics_font_priv* font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * name, int size, int flags) static
References graphics_font_priv::font, font_methods, g_new, graphics_font_priv::hfont, NULL, graphics_font_priv::size, and size.
static int fullscreen (struct window * win, int on) static
References FALSE, g_hwnd, L, and NULL.
Referenced by get_data().
static void gc_destroy (struct graphics_gc_priv * gc) static
References g_free(), graphics_gc_priv::hbrush, and graphics_gc_priv::hpen.
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References graphics_gc_priv::bg_alpha, graphics_gc_priv::bg_color, graphics_gc_priv::dashed, graphics_gc_priv::fg_alpha, graphics_gc_priv::fg_color, g_new, gc_methods, graphics_gc_priv::gr, graphics_gc_priv::hbrush, graphics_gc_priv::hpen, graphics_gc_priv::hwnd, graphics_gc_priv::line_width, and graphics_priv::wnd_handle.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, graphics_gc_priv::bg_alpha, graphics_gc_priv::bg_color, color::g, graphics_gc_priv::gr, graphics_priv::hMemDC, and color::r.
static void gc_set_dashes (struct graphics_gc_priv * gc, int width, int offset, unsigned char dash_list[], int n) static
References graphics_gc_priv::dashed, graphics_gc_priv::fg_color, graphics_gc_priv::hpen, and graphics_gc_priv::line_width.
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, c, graphics_gc_priv::dashed, graphics_gc_priv::fg_alpha, graphics_gc_priv::fg_color, color::g, graphics_gc_priv::gr, graphics_gc_priv::hbrush, graphics_gc_priv::hpen, graphics_gc_priv::line_width, color::r, and graphics_priv::transparent_color.
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_priv::dashed, graphics_gc_priv::fg_color, graphics_gc_priv::hpen, and graphics_gc_priv::line_width.
static void* get_data (struct graphics_priv * this_, const char * type) static
References CreateGraphicsWindows(), window::disable_suspend, disable_suspend(), window::fullscreen, fullscreen(), g_new0, ID_CHILD_GFX, NULL, window::priv, graphics_priv::window, and graphics_priv::wnd_parent_handle.
static void get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate) static
References dbg, g_utf8_strlen(), lvl_info, graphics_font_priv::size, point::x, and point::y.
static void graphics_destroy (struct graphics_priv * gr) static
References g_free().
static struct graphics_priv* graphics_win32_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), bind_late(), cbl, graphics_priv::cbl, event_request_system(), graphics_priv::frame, g_hash_table_new(), g_str_equal(), g_str_hash(), graphics_win32_new_helper(), graphics_priv::height, graphics_priv::image_cache_hash, graphics_priv::nav, NULL, attr::num, graphics_priv::overlays, graphics_priv::parent, window::priv, attr::u, graphics_priv::width, graphics_priv::window, graphics_priv::x, and graphics_priv::y.
Referenced by plugin_init().
static struct graphics_priv * graphics_win32_new_helper (struct graphics_methods * meth) static
References g_new0, graphics_methods, and graphics_priv::mode.
Referenced by graphics_win32_new(), and overlay_new().
static void HandleButtonClick (struct graphics_priv * gra_priv, int updown, int button, long lParam) static
References callback_list_call_attr_3, and graphics_priv::cbl.
Referenced by WndProc().
static void HandleKeyChar (struct graphics_priv * gra_priv, WPARAM wParam) static
References callback_list_call_attr_1, graphics_priv::cbl, dbg, key, lvl_debug, and NULL.
Referenced by WndProc().
static void HandleKeyDown (struct graphics_priv * gra_priv, WPARAM wParam) static
References callback_list_call_attr_1, graphics_priv::cbl, dbg, int(), key, lvl_debug, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, and NULL.
Referenced by WndProc().
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * name, int * w, int * h, struct point * hot, int rotation) static
References dbg, g_free(), g_hash_table_insert(), g_hash_table_lookup_extended(), g_new0, g_strdup_printf(), graphics_priv::image_cache_hash, lvl_info, lvl_warning, NULL, pngdecode(), pngscale(), and xpmdecode().
typedef int (WINAPI * FP_SetStretchBltMode)
Referenced by EzCreateFont(), and HandleKeyDown().
static void overlay_disable (struct graphics_priv * gr, int disable) static
References dbg, graphics_priv::disable, graphics_priv::disabled, and lvl_debug.
static struct graphics_priv* overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References graphics_priv::AlphaBlend, create_memory_dc(), dbg, graphics_priv::disabled, graphics_win32_new_helper(), graphics_priv::h, graphics_priv::height, height, graphics_priv::hPrebuildDC, image_cache_hash, graphics_priv::image_cache_hash, lvl_debug, next, graphics_priv::overlays, graphics_priv::w, graphics_priv::width, width, graphics_priv::wnd_handle, point::x, and point::y.
static void overlay_resize (struct graphics_priv * gr, struct point * p, int w, int h, int wraparound) static
References create_memory_dc(), dbg, graphics_priv::h, graphics_priv::height, lvl_debug, graphics_priv::p, graphics_priv::w, graphics_priv::width, point::x, and point::y.
void plugin_init (void)
References event_win32_new(), and graphics_win32_new().
static int pngdecode (struct graphics_priv * gr, char * name, struct graphics_image_priv * img) static
References bit_depth, buf, graphics_image_priv::channels, color_type, dbg, FALSE, g_free(), g_malloc(), graphics_image_priv::hBitmap, graphics_image_priv::height, graphics_image_priv::hot, i, info_ptr, lvl_debug, lvl_warning, NULL, png_check_sig(), PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, png_create_info_struct(), png_create_read_struct(), png_destroy_read_struct(), PNG_FILLER_AFTER, png_get_IHDR(), png_get_rowbytes(), png_get_valid(), PNG_INFO_tRNS, png_init_io(), png_jmpbuf, PNG_LIBPNG_VER_STRING, graphics_image_priv::png_pixels, png_read_end(), png_read_image(), png_read_info(), png_read_update_info(), png_set_bgr(), png_set_filler(), png_set_gray_1_2_4_to_8(), png_set_gray_to_rgb(), png_set_packing(), png_set_palette_to_rgb(), png_set_sig_bytes(), png_set_strip_16(), png_set_tRNS_to_alpha(), graphics_image_priv::row_bytes, row_pointers, TRUE, graphics_image_priv::width, point::x, and point::y.
Referenced by image_new().
static void pngrender (struct graphics_image_priv * img, struct graphics_priv * gr, int x0, int y0) static
References graphics_priv::AlphaBlend, graphics_image_priv::channels, graphics_image_priv::hBitmap, graphics_image_priv::height, graphics_priv::hMemDC, NULL, p, graphics_image_priv::png_pixels, void(), and graphics_image_priv::width.
Referenced by draw_image().
static void pngscale (struct graphics_image_priv * img, struct graphics_priv * gr, int width, int height) static
References graphics_image_priv::hBitmap, graphics_image_priv::height, height, graphics_image_priv::hot, NULL, graphics_image_priv::png_pixels, graphics_priv::SetStretchBltMode, STRETCH_HALFTONE, graphics_image_priv::width, width, point::x, and point::y.
Referenced by image_new().
static void run_timer (UINT_PTR idEvent) static
References callback_call_0, event_timeout::cb, _GList::data, dbg, g_free(), g_list_next, g_list_remove(), lvl_error, lvl_info, event_timeout::multi, NULL, event_timeout::timer_id, and timers.
Referenced by win32_timer_cb().
void WINAPI SystemIdleTimerReset (void)
Referenced by disable_suspend(), and WndProc().
static VOID CALLBACK win32_timer_cb (HWND hwnd, UINT uMsg, UINT_PTR idEvent, DWORD dwTime) static
References run_timer().
Referenced by event_win32_add_timeout().
static LRESULT CALLBACK WndProc (HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) static
References color::a, color::b, callback_list_call_0, callback_list_call_attr_1, callback_list_call_attr_2, cbl, graphics_priv::cbl, create_memory_dc(), dbg, graphics_priv::disabled, color::g, graphics_priv::h, HandleButtonClick(), HandleKeyChar(), HandleKeyDown(), window_priv::hBackLight, graphics_priv::height, graphics_priv::hMemDC, graphics_priv::hOldPrebuildBitmap, graphics_priv::hPrebuildBitmap, graphics_priv::hPrebuildDC, L, lvl_debug, graphics_priv::next, NULL, graphics_priv::overlay, graphics_priv::overlays, graphics_priv::p, graphics_priv::pPixelData, window::priv, profile, color::r, SystemIdleTimerReset(), graphics_priv::transparent_color, graphics_priv::w, graphics_priv::width, graphics_priv::window, point::x, graphics_priv::x, point::y, and graphics_priv::y.
Referenced by CreateGraphicsWindows().
static int xpmdecode (char * name, struct graphics_image_priv * img) static
References FALSE, g_free(), graphics_image_priv::height, graphics_image_priv::hot, XPM2BMP_TAG::hotspot_x, XPM2BMP_TAG::hotspot_y, graphics_image_priv::pxpm, XPM2BMP_TAG::size_x, XPM2BMP_TAG::size_y, TRUE, graphics_image_priv::width, point::x, Xpm2bmp_load(), Xpm2bmp_new(), and point::y.
Referenced by image_new().
Variable Documentation
struct event_methods event_win32_methods static
Initial value:
=
{
    event_win32_main_loop_run,
    event_win32_main_loop_quit,
    event_win32_add_watch,
    event_win32_remove_watch,
    event_win32_add_timeout,
    event_win32_remove_timeout,
    event_win32_add_idle,
    event_win32_remove_idle,
    event_win32_call_callback,
}
Referenced by event_win32_new().
struct graphics_font_methods font_methods static
Initial value:
=
{
    font_destroy
}
Referenced by font_new().
HWND g_hwnd = NULL static
Referenced by CreateGraphicsWindows(), event_win32_call_callback(), event_win32_main_loop_quit(), and fullscreen().
const TCHAR g_szClassName[] = {'N','A','V','G','R','A','\0'} static
Referenced by CreateGraphicsWindows().
struct graphics_gc_methods gc_methods static
Initial value:
=
{
    gc_destroy,
    gc_set_linewidth,
    gc_set_dashes,
    gc_set_foreground,
    gc_set_background,
}
Referenced by gc_new().
struct graphics_methods graphics_methods static
Initial value:
=
{
    graphics_destroy,
    draw_mode,
    draw_lines,
    draw_polygon,
    draw_rectangle,
    draw_circle,
    draw_text,
    draw_image,
    NULL,
    draw_drag,
    font_new,
    gc_new,
    background_gc,
    overlay_new,
    image_new,
    get_data,
    NULL,
    get_text_bbox,
    overlay_disable,
    overlay_resize,
        NULL,
        NULL,
}
Referenced by graphics_win32_new_helper().
GList* timers static
Referenced by event_win32_remove_timeout(), and run_timer().