navit: graphics/opengl/graphics_opengl.c File Reference
graphics_opengl.c File Reference
#include <glib.h>
#include <unistd.h>
#include <math.h>
#include <stdio.h>
#include <time.h>
#include "item.h"
#include "attr.h"
#include "config.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "plugin.h"
#include "event.h"
#include "debug.h"
#include "callback.h"
#include "keys.h"
#include "window.h"
#include "navit/font/freetype/font_freetype.h"
#include "graphics_opengl.h"
#include <GL/glut.h>
Data Structures
struct graphics_gc_priv
struct graphics_priv
struct graphics_image_priv
struct mouse_event_queue_element
Macros
#define USE_FLOAT 0
#define REQUIRES_POWER_OF_2 0
#define PIXEL_FORMAT GL_BGRA
#define glOrthof glOrtho
#define USE_FLOAT 1
#define glF(x) x
#define glD(x) x
#define GL_F GL_FLOAT
#define SCREEN_WIDTH 700
#define SCREEN_HEIGHT 700
Typedefs
typedef GLfloat GLf
Functions
void APIENTRY tessBeginCB (GLenum which)
void APIENTRY tessEndCB (void)
void APIENTRY tessErrorCB (GLenum errorCode)
void APIENTRY tessVertexCB (const GLvoid *data)
void APIENTRY tessVertexCB2 (const GLvoid *data)
void APIENTRY tessCombineCB (GLdouble c[3], void *d[4], GLfloat w[4], void **out)
const char * getPrimitiveType (GLenum type)
static struct graphics_priv * graphics_opengl_new_helper (struct graphics_methods *meth)
static void display (void)
static void resize_callback (int w, int h)
static void motion_notify_do (struct graphics_priv *priv, int x, int y)
static void resize_callback_do (struct graphics_priv *priv, int w, int h)
static void glut_close (void)
static void graphics_destroy (struct graphics_priv *gr)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int width, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void set_color (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_array (struct graphics_priv *gr, struct point *p, int count, GLenum mode)
static void draw_rectangle_do (struct graphics_priv *gr, struct point *p, int w, int h)
static void get_overlay_pos (struct graphics_priv *gr, struct point *point_out)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void display_text_draw (struct font_freetype_text *text, struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, int color, struct point *p)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void handle_mouse_queue (void)
static int redraw_screen (struct graphics_priv *gr)
static gboolean redraw_filter (gpointer data)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static int graphics_opengl_fullscreen (struct window *w, int on)
static void graphics_opengl_disable_suspend (struct window *w)
static void * get_data (struct graphics_priv *this, const char *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void overlay_disable (struct graphics_priv *gr, int disable)
static void overlay_resize (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
static void click_notify (int button, int state, int x, int y)
static void motion_notify (int x, int y)
static gboolean graphics_opengl_idle (void *data)
static void ProcessNormalKeys (unsigned char key_in, int x, int y)
static void ProcessSpecialKeys (int key_in, int x, int y)
static struct graphics_priv * graphics_opengl_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
static void event_opengl_main_loop_run (void)
static void event_opengl_main_loop_quit (void)
static struct event_watch * event_opengl_add_watch (int fd, enum event_watch_cond cond, struct callback *cb)
static void event_opengl_remove_watch (struct event_watch *ev)
static struct event_timeout * event_opengl_add_timeout (int timeout, int multi, struct callback *cb)
static void event_opengl_remove_timeout (struct event_timeout *to)
static struct event_idle * event_opengl_add_idle (int priority, struct callback *cb)
static void event_opengl_remove_idle (struct event_idle *ev)
static void event_opengl_call_callback (struct callback_list *cb)
static struct event_priv * event_opengl_new (struct event_methods *meth)
void plugin_init (void)
Variables
struct graphics_gc_priv graphics_gc_priv
static struct graphics_priv * graphics_priv_root
struct graphics_image_priv graphics_image_priv
static const int mouse_event_queue_size = 100
static int mouse_event_queue_begin_idx = 0
static int mouse_event_queue_end_idx = 0
static struct
mouse_event_queue_element mouse_queue [100]
static GHashTable * hImageData
static struct graphics_gc_methods gc_methods
static struct graphics_image_priv image_error
static int tess_count
static struct point tess_array [512]
static GLenum tess_type
static struct graphics_methods graphics_methods
static struct event_methods event_opengl_methods
Macro Definition Documentation
#define GL_F GL_FLOAT
Referenced by draw_array().
#define glD (x) x
#define glF (x) x
Referenced by draw_array(), resize_callback_do(), and set_color().
#define glOrthof glOrtho
Referenced by resize_callback_do().
#define PIXEL_FORMAT GL_BGRA
Referenced by display_text_draw().
#define REQUIRES_POWER_OF_2 0
#define SCREEN_HEIGHT 700
Referenced by graphics_opengl_new().
#define SCREEN_WIDTH 700
Referenced by graphics_opengl_new().
#define USE_FLOAT 0
Navit, a modular navigation system. Copyright (C) 2005-2010 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#define USE_FLOAT 1
Navit, a modular navigation system. Copyright (C) 2005-2010 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Typedef Documentation
typedef GLfloat GLf
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References graphics_priv::background_gc.
static void click_notify (int button, int state, int x, int y) static
References mouse_event_queue_element::button, mouse_event_queue_end_idx, mouse_event_queue_size, mouse_queue, mouse_event_queue_element::state, graphics_priv::width, point::x, mouse_event_queue_element::x, point::y, and mouse_event_queue_element::y.
Referenced by graphics_opengl_new().
static void display (void) static
References graphics_priv::force_redraw, graphics_priv::height, redraw_screen(), resize_callback(), and graphics_priv::width.
Referenced by graphics_opengl_new(), gui_internal_cmd_position_do(), gui_internal_dbus_signal(), gui_qml_dbus_signal(), and popup_display().
static void display_text_draw (struct font_freetype_text * text, struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, int color, struct point * p) static
References color::a, color::b, COLOR_IS_BLACK, COLOR_IS_WHITE, draw_image_es(), font_freetype_glyph::dx, font_freetype_glyph::dy, graphics_gc_priv::fa, graphics_gc_priv::fb, graphics_gc_priv::fg, graphics_gc_priv::fr, graphics_priv::freetype_methods, color::g, g_free(), g_malloc(), font_freetype_methods::get_glyph, font_freetype_methods::get_shadow, font_freetype_text::glyph, font_freetype_text::glyph_count, font_freetype_glyph::h, i, PIXEL_FORMAT, color::r, font_freetype_glyph::w, point::x, font_freetype_glyph::x, point::y, and font_freetype_glyph::y.
Referenced by draw_text().
static void draw_array (struct graphics_priv * gr, struct point * p, int count, GLenum mode) static
References GL_F, glF, i, and graphics_priv::position_location.
Referenced by draw_lines(), draw_polygon(), draw_rectangle_do(), and tessEndCB().
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_priv::p, point::x, and point::y.
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_image_priv::data, graphics_priv::dirty, draw_image_es(), graphics_image_priv::h, graphics_image_priv::hot_x, graphics_image_priv::hot_y, graphics_priv::overlay_enabled, graphics_priv::parent, graphics_image_priv::w, point::x, and point::y.
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::dash_count, graphics_gc_priv::dash_mask, graphics_priv::dirty, draw_array(), graphics_gc_priv::linewidth, graphics_priv::overlay_enabled, graphics_priv::parent, and set_color().
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References graphics_priv::DLid, draw_mode_begin, draw_mode_end, graphics_priv::force_redraw, graphics_priv::mode, graphics_priv::overlay_enabled, graphics_priv::parent, graphics_priv::platform, graphics_priv::platform_methods, redraw_screen(), and graphics_opengl_platform_methods::swap_buffers.
Referenced by overlay_disable().
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_priv::dirty, draw_array(), i, graphics_priv::overlay_enabled, graphics_priv::parent, set_color(), tessBeginCB(), tessCombineCB(), tessEndCB(), and tessVertexCB().
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_priv::dirty, draw_rectangle_do(), graphics_priv::overlay_enabled, graphics_priv::parent, and set_color().
static void draw_rectangle_do (struct graphics_priv * gr, struct point * p, int w, int h) static
References draw_array(), and p.
Referenced by draw_rectangle().
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References dbg, graphics_priv::dirty, display_text_draw(), graphics_priv::freetype_methods, lvl_error, graphics_priv::overlay_enabled, graphics_priv::parent, font_freetype_methods::text_destroy, font_freetype_methods::text_new, point::x, and point::y.
static struct event_idle* event_opengl_add_idle (int priority, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static struct event_timeout* event_opengl_add_timeout (int timeout, int multi, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static struct event_watch* event_opengl_add_watch (int fd, enum event_watch_cond cond, struct callback * cb) static
References dbg, lvl_debug, and NULL.
static void event_opengl_call_callback (struct callback_list * cb) static
References dbg, and lvl_debug.
static void event_opengl_main_loop_quit (void) static
References dbg, and lvl_debug.
static void event_opengl_main_loop_run (void) static
References dbg, and lvl_info.
static struct event_priv* event_opengl_new (struct event_methods * meth) static
References event_opengl_methods, and NULL.
Referenced by plugin_init().
static void event_opengl_remove_idle (struct event_idle * ev) static
References dbg, and lvl_debug.
static void event_opengl_remove_timeout (struct event_timeout * to) static
References dbg, and lvl_debug.
static void event_opengl_remove_watch (struct event_watch * ev) static
References dbg, and lvl_debug.
static void gc_destroy (struct graphics_gc_priv * gc) static
References g_free(), and NULL.
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References g_new0, gc_methods, graphics_gc_priv::gr, and graphics_gc_priv::linewidth.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, graphics_gc_priv::ba, graphics_gc_priv::bb, graphics_gc_priv::bg, graphics_gc_priv::br, color::g, and color::r.
static void gc_set_dashes (struct graphics_gc_priv * gc, int width, int offset, unsigned char * dash_list, int n) static
References graphics_gc_priv::dash_count, graphics_gc_priv::dash_mask, and i.
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, graphics_gc_priv::fa, graphics_gc_priv::fb, graphics_gc_priv::fg, graphics_gc_priv::fr, color::g, and color::r.
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_priv::linewidth, and graphics_priv::w.
static void* get_data (struct graphics_priv * this, const char * type) static
References window::disable_suspend, fprintf(), fragment_src, window::fullscreen, g_new0, graphics_opengl_disable_suspend(), graphics_opengl_egl_new(), graphics_opengl_fullscreen(), graphics_opengl_x11_new(), height, i, load_shader(), motion_notify_do(), NULL, window::priv, resize_callback(), resize_callback_do(), vertex_src, and width.
static void get_overlay_pos (struct graphics_priv * gr, struct point * point_out) static
References graphics_priv::height, NULL, graphics_priv::p, graphics_priv::parent, graphics_priv::width, point::x, and point::y.
Referenced by redraw_screen().
const char * getPrimitiveType (GLenum type)
Referenced by tessBeginCB().
static void glut_close (void) static
References callback_list_call_attr_0, and graphics_priv::cbl.
Referenced by graphics_opengl_new().
static void graphics_destroy (struct graphics_priv * gr) static
References font_freetype_methods::destroy, graphics_priv::freetype_methods, g_free(), and NULL.
static void graphics_opengl_disable_suspend (struct window * w) static
Referenced by get_data().
static int graphics_opengl_fullscreen (struct window * w, int on) static
Referenced by get_data().
static gboolean graphics_opengl_idle (void * data) static
References callback_list_call_attr_2, graphics_priv::cbl, GINT_TO_POINTER, handle_mouse_queue(), graphics_priv::height, TRUE, and graphics_priv::width.
Referenced by graphics_opengl_new().
static struct graphics_priv* graphics_opengl_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References argc, attr_search(), cbl, graphics_priv::cbl, click_notify(), graphics_priv::delay, display(), graphics_priv::DLid, event_request_system(), g_hash_table_new(), g_str_equal(), g_str_hash(), glut_close(), graphics_opengl_idle(), graphics_opengl_new_helper(), graphics_priv::height, height, hImageData, motion_notify(), graphics_priv::nav, NULL, attr::num, graphics_priv::overlay_enabled, ProcessNormalKeys(), ProcessSpecialKeys(), redraw_filter(), resize_callback(), SCREEN_HEIGHT, SCREEN_WIDTH, graphics_priv::timeout, attr::u, graphics_priv::width, and width.
Referenced by plugin_init().
static struct graphics_priv * graphics_opengl_new_helper (struct graphics_methods * meth) static
References font_freetype_new(), graphics_methods::font_new, graphics_priv::freetype_methods, g_new0, graphics_methods::get_text_bbox, graphics_methods, int, NULL, and void().
Referenced by graphics_opengl_new(), and overlay_new().
static void handle_mouse_queue (void) static
References callback_list_call_attr_3, graphics_priv::cbl, graphics_priv::force_redraw, mouse_event_queue_begin_idx, mouse_event_queue_end_idx, mouse_event_queue_size, mouse_queue, point::x, mouse_event_queue_element::x, point::y, and mouse_event_queue_element::y.
Referenced by graphics_opengl_idle().
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References graphics_image_priv::data, data, dbg, g_hash_table_insert(), g_hash_table_lookup(), g_new0, g_strdup(), graphics_image_priv::h, height, hImageData, graphics_image_priv::hot_x, graphics_image_priv::hot_y, i, image, image_error, lvl_error, NULL, palette, graphics_image_priv::path, graphics_image_priv::w, width, point::x, and point::y.
static void motion_notify (int x, int y) static
References motion_notify_do().
Referenced by graphics_opengl_new().
static void motion_notify_do (struct graphics_priv * priv, int x, int y) static
References callback_list_call_attr_1, graphics_priv::cbl, graphics_priv::width, point::x, and point::y.
Referenced by get_data(), and motion_notify().
static void overlay_disable (struct graphics_priv * gr, int disable) static
References draw_mode(), draw_mode_end, graphics_priv::force_redraw, and graphics_priv::overlay_enabled.
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References graphics_priv::DLid, graphics_opengl_new_helper(), graphics_priv::h, height, next, graphics_priv::overlay_autodisabled, graphics_priv::overlay_enabled, graphics_priv::overlays, p, graphics_priv::w, and width.
static void overlay_resize (struct graphics_priv * gr, struct point * p, int w, int h, int wraparound) static
References callback_list_call_attr_2, graphics_priv::cbl, changed(), GINT_TO_POINTER, graphics_priv::height, graphics_priv::overlay_autodisabled, p, graphics_priv::p, graphics_priv::width, and graphics_priv::wraparound.
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
References event_opengl_new(), and graphics_opengl_new().
static void ProcessNormalKeys (unsigned char key_in, int x, int y) static
References callback_list_call_attr_1, graphics_priv::cbl, graphics_priv::force_redraw, key, and NAVIT_KEY_RETURN.
Referenced by graphics_opengl_new().
static void ProcessSpecialKeys (int key_in, int x, int y) static
References callback_list_call_attr_1, graphics_priv::cbl, graphics_priv::force_redraw, key, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, and NAVIT_KEY_ZOOM_OUT.
Referenced by graphics_opengl_new().
static gboolean redraw_filter (gpointer data) static
References graphics_priv::dirty, graphics_priv::overlay_enabled, and redraw_screen().
Referenced by graphics_opengl_new().
static int redraw_screen (struct graphics_priv * gr) static
References graphics_priv::dirty, graphics_priv::DLid, get_overlay_pos(), graphics_priv::next, graphics_priv::overlay, graphics_priv::overlay_enabled, graphics_priv::overlays, TRUE, point::x, and point::y.
Referenced by display(), draw_mode(), and redraw_filter().
static void resize_callback (int w, int h) static
References resize_callback_do().
Referenced by display(), get_data(), and graphics_opengl_new().
static void resize_callback_do (struct graphics_priv * priv, int w, int h) static
References callback_list_call_attr_2, graphics_priv::cbl, GINT_TO_POINTER, glF, glOrthof, graphics_priv::height, and graphics_priv::width.
Referenced by get_data(), and resize_callback().
static void set_color (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References graphics_priv::color_location, graphics_gc_priv::fa, graphics_gc_priv::fb, graphics_gc_priv::fg, graphics_gc_priv::fr, and glF.
Referenced by draw_lines(), draw_polygon(), and draw_rectangle().
void APIENTRY tessBeginCB (GLenum which)
References dbg, getPrimitiveType(), and lvl_debug.
Referenced by draw_polygon().
void APIENTRY tessCombineCB (GLdouble c[3], void * d[4], GLfloat w[4], void ** out)
Referenced by draw_polygon().
void APIENTRY tessEndCB (void)
References dbg, draw_array(), lvl_debug, and tess_array.
Referenced by draw_polygon().
void APIENTRY tessErrorCB (GLenum errorCode)
void APIENTRY tessVertexCB (const GLvoid * data)
References dbg, lvl_debug, lvl_error, ptr, tess_array, tess_count, point::x, and point::y.
Referenced by draw_polygon().
void APIENTRY tessVertexCB2 (const GLvoid * data)
Variable Documentation
struct event_methods event_opengl_methods static
Initial value:
= {
        event_opengl_main_loop_run,
        event_opengl_main_loop_quit,
        event_opengl_add_watch,
        event_opengl_remove_watch,
        event_opengl_add_timeout,
        event_opengl_remove_timeout,
        event_opengl_add_idle,
        event_opengl_remove_idle,
        event_opengl_call_callback,
}
Referenced by event_opengl_new().
struct graphics_gc_methods gc_methods static
Initial value:
= {
        gc_destroy,
        gc_set_linewidth,
        gc_set_dashes,
        gc_set_foreground,
        gc_set_background
}
Referenced by gc_new().
struct graphics_gc_priv graphics_gc_priv
struct graphics_image_priv graphics_image_priv
struct graphics_methods graphics_methods static
Initial value:
= {
        graphics_destroy,
        draw_mode,
        draw_lines,
        draw_polygon,
        draw_rectangle,
        NULL,
        draw_text,
        draw_image,
        NULL,
        draw_drag,
        NULL,
        gc_new,
        background_gc,
        overlay_new,
        image_new,
        get_data,
        image_free,
        NULL,
        overlay_disable,
        overlay_resize,
        NULL,
        NULL,
}
Referenced by graphics_opengl_new_helper().
struct graphics_priv* graphics_priv_root static
GHashTable* hImageData static
Referenced by graphics_opengl_new(), and image_new().
struct graphics_image_priv image_error static
Referenced by image_new().
int mouse_event_queue_begin_idx = 0 static
Referenced by handle_mouse_queue().
int mouse_event_queue_end_idx = 0 static
Referenced by click_notify(), and handle_mouse_queue().
const int mouse_event_queue_size = 100 static
Referenced by click_notify(), and handle_mouse_queue().
struct mouse_event_queue_element mouse_queue[100] static
Referenced by click_notify(), and handle_mouse_queue().
struct point tess_array[512] static
Referenced by tessEndCB(), and tessVertexCB().
int tess_count static
Referenced by tessVertexCB().
GLenum tess_type static