navit: graphics/qt_qpainter/graphics_qt_qpainter.h File Reference
graphics_qt_qpainter.h File Reference
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include "config.h"
#include "navit/point.h"
#include "navit/item.h"
#include "navit/graphics.h"
#include "navit/color.h"
#include "navit/debug.h"
#include "navit/plugin.h"
#include "navit/callback.h"
#include "navit/event.h"
#include "navit/window.h"
#include "navit/keys.h"
#include "navit/navit.h"
#include <qglobal.h>
#include "navit/font/freetype/font_freetype.h"
#include <QResizeEvent>
#include <QApplication>
#include <QPainter>
#include <QPen>
#include <QBrush>
#include <QPixmap>
#include <QWidget>
#include <QPolygonF>
#include <QPixmapCache>
#include <QtGui>
Data Structures
struct graphics_gc_priv
struct graphics_priv
struct event_watch
Macros
#define QT_QPAINTER_USE_FREETYPE 1
#define QT_QPAINTER_USE_EVENT_GLIB 1
#define QT_QPAINTER_RENDERAREA_PARENT QWidget
Functions
void qt_qpainter_draw (struct graphics_priv *gr, const QRect *r, int paintev)
void event_qt_remove_timeout (struct event_timeout *ev)
Macro Definition Documentation
#define QT_QPAINTER_RENDERAREA_PARENT QWidget
#define QT_QPAINTER_USE_EVENT_GLIB 1
#define QT_QPAINTER_USE_FREETYPE 1
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
void event_qt_remove_timeout (struct event_timeout * ev)
void qt_qpainter_draw (struct graphics_priv * gr, const QRect * r, int paintev)
References graphics_priv::background_gc, graphics_gc_priv::brush, data, dbg, i, lvl_debug, graphics_priv::next, NULL, graphics_priv::overlay, graphics_priv::overlay_disable, overlay_rect(), graphics_priv::overlays, graphics_priv::p, graphics_gc_priv::pen, graphics_priv::pixmap, graphics_priv::rgba, size, graphics_priv::widget, point::x, and point::y.
Referenced by draw_mode(), and RenderArea::paintEvent().