navit: graphics/gd/graphics_gd.c File Reference
graphics_gd.c File Reference
#include <glib.h>
#include <gd.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include "config.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "plugin.h"
#include "callback.h"
#include "window.h"
#include "navit.h"
#include "debug.h"
#include "navit/font/freetype/font_freetype.h"
Data Structures
struct shmem_header
struct graphics_priv
struct graphics_gc_priv
struct graphics_image_priv
Functions
static void emit_callback (struct graphics_priv *priv)
static void image_setup (struct graphics_priv *gr)
static struct shmem_header * shm_next (struct graphics_priv *gr)
static void add_overlays (struct graphics_priv *overlay, gdImagePtr im)
static void graphics_destroy (struct graphics_priv *gr)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *name, int *w, int *h, struct point *hot, int rotation)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static void * get_data (struct graphics_priv *this, char *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void overlay_disable (struct graphics_priv *gr, int disable)
static void overlay_resize (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
static void image_create (struct graphics_priv *gr)
static void image_destroy (struct graphics_priv *gr)
static int set_attr_do (struct graphics_priv *gr, struct attr *attr, int init)
static int set_attr (struct graphics_priv *gr, struct attr *attr)
static struct graphics_priv * graphics_gd_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
static struct graphics_gc_methods gc_methods
static struct graphics_methods graphics_methods
Function Documentation
add_overlays()
static void add_overlays (struct graphics_priv * overlay, gdImagePtr im) static
References graphics_priv::background, graphics_gc_priv::color, graphics_priv::h, graphics_priv::im, graphics_priv::next, graphics_priv::p, graphics_priv::w, point::x, graphics_priv::x, point::y, and graphics_priv::y.
Referenced by draw_mode(), and get_data().
background_gc()
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References graphics_priv::background.
draw_circle()
static void draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_gc_priv::color, graphics_priv::flags, graphics_priv::im, graphics_gc_priv::width, point::x, and point::y.
draw_drag()
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References p, graphics_priv::p, point::x, and point::y.
draw_image()
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_priv::im, graphics_image_priv::im, point::x, and point::y.
draw_lines()
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::color, graphics_gc_priv::dash_count, graphics_gc_priv::dash_list, graphics_gc_priv::dash_list_len, graphics_priv::flags, graphics_priv::im, graphics_gc_priv::width, point::x, and point::y.
draw_mode()
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References add_overlays(), graphics_priv::background, graphics_gc_priv::color, data, dbg, draw_mode_begin, draw_mode_end, shmem_header::flag, graphics_priv::flags, shmem_header::h, graphics_priv::h, graphics_priv::im, image_setup(), lvl_debug, lvl_error, next, graphics_priv::overlay, overlay_new(), graphics_priv::overlays, p, graphics_priv::shm_header, shm_next(), size, graphics_priv::sockets, shmem_header::w, graphics_priv::w, and graphics_priv::wraparound.
draw_polygon()
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::color, graphics_priv::flags, and graphics_priv::im.
draw_rectangle()
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_gc_priv::color, graphics_priv::flags, graphics_priv::im, point::x, and point::y.
draw_text()
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References color::a, graphics_gc_priv::color2, font_freetype_glyph::dx, font_freetype_glyph::dy, graphics_priv::freetype_methods, font_freetype_methods::get_glyph, font_freetype_methods::get_shadow, font_freetype_text::glyph, font_freetype_text::glyph_count, shmem_header::h, font_freetype_glyph::h, graphics_priv::im, font_freetype_methods::text_destroy, font_freetype_methods::text_new, shmem_header::w, font_freetype_glyph::w, point::x, font_freetype_glyph::x, point::y, and font_freetype_glyph::y.
emit_callback()
static void emit_callback (struct graphics_priv * priv) static
References callback_list_call_attr_2, graphics_priv::cbl, graphics_priv::h, and graphics_priv::w.
Referenced by graphics_gd_new(), and set_attr_do().
gc_destroy()
static void gc_destroy (struct graphics_gc_priv * gc) static
References graphics_gc_priv::bgcolor, graphics_gc_priv::color, graphics_gc_priv::dash_list, graphics_gc_priv::gr, and graphics_priv::im.
gc_new()
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References graphics_gc_priv::bgcolor, graphics_gc_priv::color, gc_methods, graphics_gc_priv::gr, and graphics_gc_priv::width.
gc_set_background()
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
References color::b, graphics_gc_priv::bgcolor, color::g, graphics_gc_priv::gr, graphics_priv::im, and color::r.
gc_set_dashes()
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
References graphics_gc_priv::dash_count, graphics_gc_priv::dash_list, and graphics_gc_priv::dash_list_len.
gc_set_foreground()
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::b, c, graphics_gc_priv::color, graphics_gc_priv::color2, color::g, graphics_gc_priv::gr, graphics_priv::im, and color::r.
gc_set_linewidth()
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References shmem_header::w, and graphics_gc_priv::width.
get_data()
static void* get_data (struct graphics_priv * this, char * type) static
References add_overlays(), callback_list_call_attr_1, callback_list_call_attr_3, cbl, dbg, graphics_priv::image, lvl_debug, graphics_priv::overlay, graphics_priv::overlays, point::x, and point::y.
graphics_destroy()
static void graphics_destroy (struct graphics_priv * gr) static
References font_freetype_methods::destroy, and graphics_priv::freetype_methods.
graphics_gd_new()
static struct graphics_priv* graphics_gd_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References callback_cast, callback_new_attr_1, graphics_priv::cb, cbl, graphics_priv::cbl, emit_callback(), event_request_system(), font_freetype_new(), font_freetype_methods::font_new, graphics_methods::font_new, graphics_priv::freetype_methods, font_freetype_methods::get_text_bbox, graphics_methods::get_text_bbox, graphics_methods, graphics_priv::h, graphics_priv::im, image_create(), graphics_priv::nav, navit_add_callback(), set_attr_do(), and graphics_priv::w.
Referenced by plugin_init().
image_create()
static void image_create (struct graphics_priv * gr) static
References dbg, graphics_priv::h, graphics_priv::im, image_setup(), lvl_debug, graphics_priv::shm, graphics_priv::shm_header, graphics_priv::shmkey, size, and graphics_priv::w.
Referenced by graphics_gd_new(), and set_attr_do().
image_destroy()
static void image_destroy (struct graphics_priv * gr) static
References graphics_priv::im, graphics_priv::shm, and graphics_priv::shmkey.
Referenced by set_attr_do().
image_free()
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
References graphics_image_priv::im.
image_new()
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * name, int * w, int * h, struct point * hot, int rotation) static
References file, graphics_image_priv::im, point::x, and point::y.
image_setup()
static void image_setup (struct graphics_priv * gr) static
References shmem_header::bpp, shmem_header::flag, shmem_header::h, graphics_priv::h, graphics_priv::im, graphics_priv::shm_header, graphics_priv::shmkey, shmem_header::w, and graphics_priv::w.
Referenced by draw_mode(), and image_create().
overlay_disable()
static void overlay_disable (struct graphics_priv * gr, int disable) static
References dbg, and lvl_debug.
overlay_new()
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References dbg, graphics_priv::flags, font_freetype_new(), graphics_priv::freetype_methods, graphics_methods, shmem_header::h, graphics_priv::h, graphics_priv::im, lvl_debug, graphics_priv::next, graphics_priv::overlay, graphics_priv::overlays, p, graphics_priv::p, shmem_header::w, and graphics_priv::w.
Referenced by draw_mode().
overlay_resize()
static void overlay_resize (struct graphics_priv * gr, struct point * p, int w, int h, int wraparound) static
References dbg, and lvl_debug.
plugin_init()
void plugin_init (void)
References graphics_gd_new().
set_attr()
static int set_attr (struct graphics_priv * gr, struct attr * attr) static
References set_attr_do().
set_attr_do()
static int set_attr_do (struct graphics_priv * gr, struct attr * attr, int init) static
References c, dbg, emit_callback(), graphics_priv::flags, graphics_priv::h, graphics_priv::im, image_create(), image_destroy(), lvl_debug, lvl_error, attr::num, p, graphics_priv::shmkey, graphics_priv::shmoffset, graphics_priv::shmsize, graphics_priv::sockets, attr::str, attr::type, attr::u, and graphics_priv::w.
Referenced by graphics_gd_new(), and set_attr().
shm_next()
struct shmem_header * shm_next (struct graphics_priv * gr) static
References dbg, lvl_debug, next, graphics_priv::shm, graphics_priv::shm_header, graphics_priv::shmoffset, and graphics_priv::shmsize.
Referenced by draw_mode().
Variable Documentation
gc_methods
struct graphics_gc_methods gc_methods static
Initial value:
= {
    gc_destroy,
    gc_set_linewidth,
    gc_set_dashes,
    gc_set_foreground,
    gc_set_background
}
Referenced by gc_new().
graphics_methods
struct graphics_methods graphics_methods static
Initial value:
= {
    graphics_destroy,
    draw_mode,
    draw_lines,
    draw_polygon,
    draw_rectangle,
    draw_circle,
    draw_text,
    draw_image,
    NULL,
    draw_drag,
    NULL,
    gc_new,
    background_gc,
    overlay_new,
    image_new,
    get_data,
    image_free,
    NULL,
    overlay_disable,
    overlay_resize,
    set_attr,
    NULL,
    NULL,
}
Referenced by graphics_gd_new(), and overlay_new().