navit: graphics/android/graphics_android.c File Reference
graphics_android.c File Reference
#include <unistd.h>
#include <glib.h>
#include <poll.h>
#include "config.h"
#include "window.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "item.h"
#include "xmlconfig.h"
#include "plugin.h"
#include "event.h"
#include "debug.h"
#include "callback.h"
#include "android.h"
#include "command.h"
Data Structures
struct graphics_priv
struct graphics_font_priv
struct graphics_gc_priv
struct graphics_image_priv
struct event_timeout
Functions
static int find_class_global (char *name, jclass *ret)
static int find_method (jclass class, char *name, char *args, jmethodID *ret)
static int find_static_method (jclass class, char *name, char *args, jmethodID *ret)
static void graphics_destroy (struct graphics_priv *gr)
static void font_destroy (struct graphics_font_priv *font)
static struct graphics_font_priv * font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static void image_destroy (struct graphics_image_priv *img)
static struct graphics_image_priv * image_new (struct graphics_priv *gra, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void initPaint (struct graphics_priv *gra, struct graphics_gc_priv *gc)
static void draw_lines (struct graphics_priv *gra, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_polygon (struct graphics_priv *gra, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gra, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gra, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_text (struct graphics_priv *gra, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gra, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void draw_image_warp (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, int count, struct graphics_image_priv *img)
static void draw_drag (struct graphics_priv *gra, struct point *p)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_mode (struct graphics_priv *gra, enum draw_mode_num mode)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
Creates a new overlay.
static void * get_data (struct graphics_priv *this, const char *type)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *priv)
static void get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void overlay_disable (struct graphics_priv *gra, int disable)
static void overlay_resize (struct graphics_priv *gra, struct point *pnt, int w, int h, int wraparound)
static int set_attr (struct graphics_priv *gra, struct attr *attr)
int show_native_keyboard (struct graphics_keyboard *kbd)
Displays the native input method.
void hide_native_keyboard (struct graphics_keyboard *kbd)
Hides the native input method and frees associated private data.
static void resize_callback (struct graphics_priv *gra, int w, int h)
static void padding_callback (struct graphics_priv *gra, int left, int top, int right, int bottom)
static void motion_callback (struct graphics_priv *gra, int x, int y)
static void keypress_callback (struct graphics_priv *gra, char *s)
static void button_callback (struct graphics_priv *gra, int pressed, int button, int x, int y)
static int set_activity (jobject graphics)
static int graphics_android_init (struct graphics_priv *ret, struct graphics_priv *parent, struct point *pnt, int w, int h, int wraparound, int use_camera)
Initializes a new Android graphics instance.
static int graphics_android_fullscreen (struct window *win, int on)
static void graphics_android_disable_suspend (struct window *win)
static void graphics_android_cmd_runMenuItem (struct graphics_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
Runs an item from the Android menu.
static void graphics_android_cmd_menu (struct graphics_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
Shows the Android menu.
static struct graphics_priv * graphics_android_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
Creates a new Android graphics instance.
static void event_android_main_loop_run (void)
static void event_android_main_loop_quit (void)
static void do_poll (JNIEnv *env, int fd, int cond)
static struct event_watch * event_android_add_watch (int h, enum event_watch_cond cond, struct callback *cb)
static void event_android_remove_watch (struct event_watch *ev)
static void event_android_remove_timeout (struct event_timeout *priv)
static void event_android_handle_timeout (struct event_timeout *priv)
static struct event_timeout * event_android_add_timeout (int timeout, int multi, struct callback *cb)
static struct event_idle * event_android_add_idle (int priority, struct callback *cb)
static void event_android_remove_idle (struct event_idle *ev)
static void event_android_call_callback (struct callback_list *cb)
static struct event_priv * event_android_new (struct event_methods *meth)
void plugin_init (void)
Variables
static GHashTable * image_cache_hash = NULL
static struct graphics_font_methods font_methods
static struct graphics_gc_methods gc_methods
static struct
graphics_image_methods image_methods
static struct graphics_methods graphics_methods
static jclass NavitClass
static jmethodID Navit_disableSuspend
static jmethodID Navit_exit
static jmethodID Navit_fullscreen
static jmethodID Navit_runOptionsItem
static jmethodID Navit_showMenu
static jmethodID Navit_showNativeKeyboard
static jmethodID Navit_hideNativeKeyboard
static struct command_table commands []
static jclass NavitTimeoutClass
static jmethodID NavitTimeout_init
static jmethodID NavitTimeout_remove
static jclass NavitIdleClass
static jmethodID NavitIdle_init
static jmethodID NavitIdle_remove
static jclass NavitWatchClass
static jmethodID NavitWatch_init
static jmethodID NavitWatch_remove
static struct event_methods event_android_methods
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
static void button_callback (struct graphics_priv * gra, int pressed, int button, int x, int y) static
References callback_list_call_attr_3, graphics_priv::cbl, point::x, and point::y.
Referenced by graphics_android_init().
static void do_poll (JNIEnv * env, int fd, int cond) static
References dbg, event_watch_cond_except, event_watch_cond_read, event_watch_cond_write, and lvl_debug.
Referenced by event_android_add_watch().
static void draw_circle (struct graphics_priv * gra, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_gc_priv::gra, initPaint(), jnienv, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_circle, graphics_priv::Paint, point::x, and point::y.
static void draw_drag (struct graphics_priv * gra, struct point * p) static
References jnienv, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_drag, point::x, and point::y.
static void draw_image (struct graphics_priv * gra, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_image_priv::Bitmap, dbg, graphics_gc_priv::gra, initPaint(), jnienv, lvl_debug, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_image, graphics_priv::Paint, point::x, and point::y.
static void draw_image_warp (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, int count, struct graphics_image_priv * img) static
References graphics_image_priv::Bitmap, dbg, graphics_gc_priv::gra, initPaint(), jnienv, lvl_debug, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_image_warp, graphics_priv::Paint, point::x, and point::y.
static void draw_lines (struct graphics_priv * gra, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::a, graphics_gc_priv::b, graphics_gc_priv::dashes, graphics_gc_priv::g, graphics_gc_priv::gra, i, jnienv, graphics_gc_priv::linewidth, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_polyline, graphics_gc_priv::ndashes, graphics_priv::Paint, graphics_gc_priv::r, point::x, and point::y.
static void draw_mode (struct graphics_priv * gra, enum draw_mode_num mode) static
References jnienv, graphics_priv::NavitGraphics, and graphics_priv::NavitGraphics_draw_mode.
static void draw_polygon (struct graphics_priv * gra, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::a, graphics_gc_priv::b, graphics_gc_priv::g, graphics_gc_priv::gra, i, jnienv, graphics_gc_priv::linewidth, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_polygon, graphics_priv::Paint, graphics_gc_priv::r, point::x, and point::y.
static void draw_rectangle (struct graphics_priv * gra, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_gc_priv::gra, initPaint(), jnienv, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_rectangle, graphics_priv::Paint, point::x, and point::y.
static void draw_text (struct graphics_priv * gra, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References graphics_gc_priv::a, graphics_gc_priv::b, dbg, graphics_gc_priv::g, graphics_gc_priv::gra, initPaint(), jnienv, lvl_debug, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_text, graphics_priv::Paint, graphics_gc_priv::r, graphics_font_priv::size, point::x, and point::y.
static struct event_idle* event_android_add_idle (int priority, struct callback * cb) static
References dbg, event_android_add_timeout(), jnienv, lvl_debug, NavitIdle_init, and NavitIdleClass.
static struct event_timeout* event_android_add_timeout (int timeout, int multi, struct callback * cb) static
References event_timeout::cb, event_android_handle_timeout(), g_new0, event_timeout::handle_timeout, event_timeout::jni_timeout, jnienv, event_timeout::multi, NavitTimeout_init, and NavitTimeoutClass.
Referenced by event_android_add_idle().
static struct event_watch* event_android_add_watch (int h, enum event_watch_cond cond, struct callback * cb) static
References dbg, do_poll(), jnienv, lvl_debug, NavitWatch_init, and NavitWatchClass.
static void event_android_call_callback (struct callback_list * cb) static
References dbg, and lvl_debug.
static void event_android_handle_timeout (struct event_timeout * priv) static
References callback_call_0, event_timeout::cb, event_android_remove_timeout(), and event_timeout::multi.
Referenced by event_android_add_timeout().
static void event_android_main_loop_quit (void) static
References android_activity, dbg, jnienv, lvl_debug, and Navit_exit.
static void event_android_main_loop_run (void) static
References dbg, and lvl_debug.
static struct event_priv* event_android_new (struct event_methods * meth) static
References dbg, event_android_methods, find_class_global(), jnienv, lvl_debug, Navit_disableSuspend, Navit_exit, Navit_fullscreen, Navit_hideNativeKeyboard, Navit_runOptionsItem, Navit_showMenu, Navit_showNativeKeyboard, NavitClass, NavitIdle_init, NavitIdle_remove, NavitIdleClass, NavitTimeout_init, NavitTimeout_remove, NavitTimeoutClass, NavitWatch_init, NavitWatch_remove, NavitWatchClass, and NULL.
Referenced by plugin_init().
static void event_android_remove_idle (struct event_idle * ev) static
References dbg, event_android_remove_timeout(), jnienv, lvl_debug, and NavitIdle_remove.
static void event_android_remove_timeout (struct event_timeout * priv) static
References event_timeout::jni_timeout, jnienv, NavitTimeout_remove, and NULL.
Referenced by event_android_handle_timeout(), and event_android_remove_idle().
static void event_android_remove_watch (struct event_watch * ev) static
References dbg, jnienv, lvl_debug, and NavitWatch_remove.
static int find_class_global (char * name, jclass * ret) static
References dbg, jnienv, and lvl_error.
Referenced by event_android_new(), and graphics_android_init().
static int find_method (jclass class, char * name, char * args, jmethodID * ret) static
References dbg, jnienv, lvl_error, and NULL.
Referenced by graphics_android_init().
static int find_static_method (jclass class, char * name, char * args, jmethodID * ret) static
References dbg, jnienv, lvl_error, and NULL.
Referenced by graphics_android_init().
static void font_destroy (struct graphics_font_priv * font) static
References g_free().
static struct graphics_font_priv* font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * font, int size, int flags) static
References font_methods, g_new0, graphics_font_priv::size, and size.
static void gc_destroy (struct graphics_gc_priv * gc) static
References graphics_gc_priv::dashes, and g_free().
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References graphics_gc_priv::a, graphics_gc_priv::b, graphics_gc_priv::g, g_new0, gc_methods, graphics_gc_priv::gr, graphics_gc_priv::gra, graphics_gc_priv::linewidth, and graphics_gc_priv::r.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
References graphics_gc_priv::dashes, g_free(), g_malloc(), graphics_gc_priv::ndashes, and NULL.
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::a, graphics_gc_priv::a, color::b, graphics_gc_priv::b, color::g, graphics_gc_priv::g, color::r, and graphics_gc_priv::r.
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_priv::linewidth.
static void* get_data (struct graphics_priv * this, const char * type) static
References NULL, graphics_priv::padding, and graphics_priv::win.
static void get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate) static
References g_utf8_strlen(), graphics_font_priv::size, point::x, and point::y.
static void graphics_android_cmd_menu (struct graphics_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
Shows the Android menu.
This is the callback function associated with the
menu()
API function.
Parameters
this The
graohics_prov
structure
function The API function which was called
in Parameters to pass to the API function
out Points to a buffer which will receive a pointer to the output of the command
valid
References android_activity, dbg, jnienv, lvl_debug, and Navit_showMenu.
static void graphics_android_cmd_runMenuItem (struct graphics_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
Runs an item from the Android menu.
This is a callback function which implements multiple API functions.
Parameters
this The
graohics_prov
structure
function The API function which was called
in Parameters to pass to the API function
out Points to a buffer which will receive a pointer to the output of the command
valid
References android_activity, dbg, jnienv, and Navit_runOptionsItem.
static void graphics_android_disable_suspend (struct window * win) static
References android_activity, dbg, jnienv, lvl_debug, and Navit_disableSuspend.
Referenced by graphics_android_new().
static int graphics_android_fullscreen (struct window * win, int on) static
References android_activity, jnienv, and Navit_fullscreen.
Referenced by graphics_android_new().
static int graphics_android_init (struct graphics_priv * ret, struct graphics_priv * parent, struct point * pnt, int w, int h, int wraparound, int use_camera) static
Initializes a new Android graphics instance.
This initializes a new Android graphics instance, which can either be the main view or an overlay.
Parameters
ret The new graphics instance
parent The graphics instance that contains the new instance (
NULL
for the main view)
p The position of the overlay in its parent (
NULL
for the main view)
w The width of the overlay (0 for the main view)
h The height of the overlay (0 for the main view)
wraparound (0 for the main view)
use_camera Whether to use the camera (0 for overlays)
References android_activity, graphics_priv::Bitmap_createScaledBitmap, graphics_priv::Bitmap_getHeight, graphics_priv::Bitmap_getWidth, graphics_priv::BitmapClass, graphics_priv::BitmapFactory_decodeFile, graphics_priv::BitmapFactory_decodeResource, graphics_priv::BitmapFactoryClass, button_callback(), callback_cast, callback_new_1, graphics_priv::Context_getResources, graphics_priv::ContextClass, dbg, find_class_global(), find_method(), find_static_method(), jnienv, keypress_callback(), lvl_debug, lvl_error, motion_callback(), graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_draw_circle, graphics_priv::NavitGraphics_draw_drag, graphics_priv::NavitGraphics_draw_image, graphics_priv::NavitGraphics_draw_image_warp, graphics_priv::NavitGraphics_draw_mode, graphics_priv::NavitGraphics_draw_polygon, graphics_priv::NavitGraphics_draw_polyline, graphics_priv::NavitGraphics_draw_rectangle, graphics_priv::NavitGraphics_draw_text, graphics_priv::NavitGraphics_overlay_disable, graphics_priv::NavitGraphics_overlay_resize, graphics_priv::NavitGraphics_SetCamera, graphics_priv::NavitGraphicsClass, NULL, graphics_priv::packageName, graphics_priv::padding, padding_callback(), graphics_priv::Paint, graphics_priv::Paint_init, graphics_priv::Paint_setARGB, graphics_priv::Paint_setStrokeWidth, graphics_priv::PaintClass, resize_callback(), graphics_priv::Resources, graphics_priv::Resources_getIdentifier, graphics_priv::ResourcesClass, set_activity(), point::x, and point::y.
Referenced by graphics_android_new(), and overlay_new().
static struct graphics_priv* graphics_android_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
Creates a new Android graphics instance.
This method is called when the graphics plugin is initialized. It creates the main view, i.e. the map view. Unless overlay mode is enabled, it also holds any OSD items.
Parameters
nav The navit instance.
meth The methods for the new graphics instance
attrs The attributes for the new graphics instance
cbl The callback list for the new graphics instance
Returns
The new graphics instance
References color::a, attr_search(), color::b, graphics_priv::bgcolor, padding::bottom, attr::callback_list, cbl, graphics_priv::cbl, attr::color, command_add_table(), dbg, window::disable_suspend, event_request_system(), window::fullscreen, color::g, g_free(), g_hash_table_new(), g_new0, g_str_equal(), g_str_hash(), graphics_android_disable_suspend(), graphics_android_fullscreen(), graphics_android_init(), graphics_methods, image_cache_hash, jnienv, padding::left, lvl_debug, navit_object_set_attr(), graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_setBackgroundColor, graphics_priv::NavitGraphicsClass, NULL, attr::num, graphics_priv::padding, window::priv, color::r, padding::right, padding::top, attr::type, attr::u, and graphics_priv::win.
Referenced by plugin_init().
static void graphics_destroy (struct graphics_priv * gr) static
void hide_native_keyboard (struct graphics_keyboard * kbd)
Hides the native input method and frees associated private data.
Parameters
kbd The
struct graphics_keyboard
which was passed to the earlier call to show_native_keyboard(struct graphics_keyboard *). The
gra_priv
member of the struct will be freed by this function.
References android_activity, dbg, g_free(), graphics_keyboard::gra_priv, jnienv, lvl_error, Navit_hideNativeKeyboard, and NULL.
static void image_destroy (struct graphics_image_priv * img) static
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * priv) static
static struct graphics_image_priv* image_new (struct graphics_priv * gra, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References graphics_image_priv::Bitmap, graphics_priv::Bitmap_createScaledBitmap, graphics_priv::Bitmap_getHeight, graphics_priv::Bitmap_getWidth, graphics_priv::BitmapClass, graphics_priv::BitmapFactory_decodeFile, graphics_priv::BitmapFactory_decodeResource, graphics_priv::BitmapFactoryClass, dbg, g_free(), g_new0, g_strdup(), graphics_image_priv::height, graphics_image_priv::hot, jnienv, lvl_debug, lvl_error, lvl_warning, NULL, graphics_priv::packageName, startup::pos, graphics_priv::Resources, graphics_priv::Resources_getIdentifier, graphics_image_priv::width, point::x, and point::y.
static void initPaint (struct graphics_priv * gra, struct graphics_gc_priv * gc) static
References graphics_gc_priv::a, graphics_gc_priv::b, graphics_gc_priv::g, graphics_gc_priv::gra, jnienv, graphics_gc_priv::linewidth, graphics_priv::Paint, graphics_priv::Paint_setARGB, graphics_priv::Paint_setStrokeWidth, and graphics_gc_priv::r.
Referenced by draw_circle(), draw_image(), draw_image_warp(), draw_rectangle(), and draw_text().
static void keypress_callback (struct graphics_priv * gra, char * s) static
References callback_list_call_attr_1, graphics_priv::cbl, dbg, and lvl_debug.
Referenced by graphics_android_init().
static void motion_callback (struct graphics_priv * gra, int x, int y) static
References callback_list_call_attr_1, graphics_priv::cbl, point::x, and point::y.
Referenced by graphics_android_init().
static void overlay_disable (struct graphics_priv * gra, int disable) static
References jnienv, graphics_priv::NavitGraphics, and graphics_priv::NavitGraphics_overlay_disable.
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
Creates a new overlay.
This method creates a graphics instance for a new overlay. If overlay mode is enabled, a separate overlay is created for each OSD item.
Parameters
gr The parent graphics instance, i.e. the one which will contain the overlay.
meth The methods for the new graphics instance
p The position of the overlay in its parent
w The width of the overlay
h The height of the overlay
wraparound
Returns
The graphics instance for the new overlay
References dbg, g_free(), g_new0, graphics_android_init(), graphics_methods, lvl_debug, and NULL.
static void overlay_resize (struct graphics_priv * gra, struct point * pnt, int w, int h, int wraparound) static
References jnienv, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_overlay_resize, point::x, and point::y.
static void padding_callback (struct graphics_priv * gra, int left, int top, int right, int bottom) static
References padding::bottom, dbg, padding::left, lvl_debug, graphics_priv::padding, padding::right, and padding::top.
Referenced by graphics_android_init().
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
References dbg, event_android_new(), graphics_android_new(), and lvl_debug.
static void resize_callback (struct graphics_priv * gra, int w, int h) static
References callback_list_call_attr_2, graphics_priv::cbl, dbg, g_list_length(), and lvl_debug.
Referenced by QNavitQuick::geometryChanged(), graphics_android_init(), and QNavitWidget::resizeEvent().
static int set_activity (jobject graphics) static
References android_activity, dbg, jnienv, lvl_debug, lvl_error, and NULL.
Referenced by graphics_android_init().
static int set_attr (struct graphics_priv * gra, struct attr * attr) static
References color::a, color::b, graphics_priv::bgcolor, attr::color, dbg, color::g, jnienv, lvl_debug, lvl_error, graphics_priv::NavitGraphics, graphics_priv::NavitGraphics_setBackgroundColor, graphics_priv::NavitGraphics_SetCamera, NULL, attr::num, color::r, attr::type, and attr::u.
int show_native_keyboard (struct graphics_keyboard * kbd)
Displays the native input method.
This method decides whether a native on-screen input method, such as a virtual keyboard, needs to be displayed. A typical case in which there is no need for an on-screen input method is if a hardware keyboard is present.
Note that the Android platform lacks reliable means of determining whether an on-screen input method is going to be displayed or how much screen space it is going to occupy. Therefore this method tries to guess these values. They have been tested and found to work correctly with the AOSP keyboard, and are thus expected to be compatible with most on-screen keyboards found on the market, but results may be unexpected with other input methods.
Parameters
kbd A
struct graphics_keyboard
which describes the requirements for the input method and will be populated with the data of the input method before the function returns.
Returns
True if the input method is going to be displayed, false if not.
References android_activity, dbg, graphics_keyboard::h, jnienv, lvl_error, Navit_showNativeKeyboard, NULL, and graphics_keyboard::w.
Variable Documentation
struct command_table commands[] static
Initial value:
= {
        {"map_download_dialog",command_cast(graphics_android_cmd_runMenuItem)},
        {"set_map_location",command_cast(graphics_android_cmd_runMenuItem)},
        {"backup_restore_dialog",command_cast(graphics_android_cmd_runMenuItem)},
        {"menu", command_cast(graphics_android_cmd_menu)},
}
The command table. Each entry consists of an API function name and the callback function which implements this command.
struct event_methods event_android_methods static
Initial value:
= {
        event_android_main_loop_run,
        event_android_main_loop_quit,
        event_android_add_watch,
        event_android_remove_watch,
        event_android_add_timeout,
        event_android_remove_timeout,
        event_android_add_idle,
        event_android_remove_idle,
        event_android_call_callback,
}
Referenced by event_android_new().
struct graphics_font_methods font_methods static
Initial value:
= {
        font_destroy
}
Referenced by font_new().
struct graphics_gc_methods gc_methods static
Initial value:
= {
        gc_destroy,
        gc_set_linewidth,
        gc_set_dashes,
        gc_set_foreground,
        gc_set_background
}
Referenced by gc_new().
struct graphics_methods graphics_methods static
Initial value:
= {
        graphics_destroy,
        draw_mode,
        draw_lines,
        draw_polygon,
        draw_rectangle,
        draw_circle,
        draw_text,
        draw_image,
        draw_image_warp,
        draw_drag,
        font_new,
        gc_new,
        background_gc,
        overlay_new,
        image_new,
        get_data,
        image_free,
        get_text_bbox,
        overlay_disable,
        overlay_resize,
        set_attr,
        show_native_keyboard,
        hide_native_keyboard,
}
Referenced by graphics_android_new(), and overlay_new().
GHashTable* image_cache_hash = NULL static
Referenced by graphics_android_new(), and overlay_new().
struct graphics_image_methods image_methods static
Initial value:
= {
        image_destroy
}
jmethodID Navit_disableSuspend static
Referenced by event_android_new(), and graphics_android_disable_suspend().
jmethodID Navit_exit static
Referenced by event_android_main_loop_quit(), and event_android_new().
jmethodID Navit_fullscreen static
Referenced by event_android_new(), and graphics_android_fullscreen().
jmethodID Navit_hideNativeKeyboard static
Referenced by event_android_new(), and hide_native_keyboard().
jmethodID Navit_runOptionsItem static
Referenced by event_android_new(), and graphics_android_cmd_runMenuItem().
jmethodID Navit_showMenu static
Referenced by event_android_new(), and graphics_android_cmd_menu().
jmethodID Navit_showNativeKeyboard static
Referenced by event_android_new(), and show_native_keyboard().
jclass NavitClass static
Referenced by event_android_new().
jmethodID NavitIdle_init static
Referenced by event_android_add_idle(), and event_android_new().
jmethodID NavitIdle_remove static
Referenced by event_android_new(), and event_android_remove_idle().
jclass NavitIdleClass static
Referenced by event_android_add_idle(), and event_android_new().
jmethodID NavitTimeout_init static
Referenced by event_android_add_timeout(), and event_android_new().
jmethodID NavitTimeout_remove static
Referenced by event_android_new(), and event_android_remove_timeout().
jclass NavitTimeoutClass static
Referenced by event_android_add_timeout(), and event_android_new().
jmethodID NavitWatch_init static
Referenced by event_android_add_watch(), and event_android_new().
jmethodID NavitWatch_remove static
Referenced by event_android_new(), and event_android_remove_watch().
jclass NavitWatchClass static
Referenced by event_android_add_watch(), and event_android_new().