navit: graphics/sdl/graphics_sdl.c File Reference
graphics_sdl.c File Reference
#include <glib.h>
#include <pthread.h>
#include <poll.h>
#include <signal.h>
#include "config.h"
#include "debug.h"
#include "point.h"
#include "graphics.h"
#include "color.h"
#include "plugin.h"
#include "window.h"
#include "navit.h"
#include "keys.h"
#include "item.h"
#include "attr.h"
#include "callback.h"
#include "font/freetype/font_freetype.h"
#include <SDL/SDL.h>
#include <math.h>
#include "raster.h"
#include <event.h>
#include <SDL/SDL_image.h>
#include <alloca.h>
Data Structures
struct graphics_priv
struct graphics_gc_priv
struct graphics_image_priv
Macros
#define DISPLAY_W 800
#define DISPLAY_H 600
#define OVERLAY_MAX 32
Functions
static void graphics_destroy (struct graphics_priv *gr)
static void gc_destroy (struct graphics_gc_priv *gc)
static void gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static struct graphics_gc_priv * gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
static struct graphics_image_priv * image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *name, int *w, int *h, struct point *hot, int rotation)
static void image_free (struct graphics_priv *gr, struct graphics_image_priv *gi)
static void draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void set_pixel (SDL_Surface *surface, int x, int y, Uint8 r2, Uint8 g2, Uint8 b2, Uint8 a2)
static void resize_ft_buffer (unsigned int new_size)
static void display_text_draw (struct font_freetype_text *text, struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, int color, struct point *p)
static void draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static void overlay_disable (struct graphics_priv *gr, int disable)
static struct graphics_priv * overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static int window_fullscreen (struct window *win, int on)
static void * get_data (struct graphics_priv *this, char const *type)
static void draw_drag (struct graphics_priv *gr, struct point *p)
static gboolean graphics_sdl_idle (void *data)
static struct graphics_priv * graphics_sdl_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
unsigned char * ft_buffer = NULL
unsigned int ft_buffer_size = 0
static struct graphics_gc_methods gc_methods
static struct graphics_methods graphics_methods
Macro Definition Documentation
#define DISPLAY_H 600
Referenced by graphics_sdl_new().
#define DISPLAY_W 800
Referenced by graphics_sdl_new().
#define OVERLAY_MAX 32
Referenced by draw_mode(), and overlay_new().
Function Documentation
static void background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References dbg, and lvl_debug.
static void display_text_draw (struct font_freetype_text * text, struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, int color, struct point * p) static
References color::a, color::b, COLOR_IS_BLACK, COLOR_IS_WHITE, font_freetype_glyph::dx, font_freetype_glyph::dy, graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, graphics_priv::freetype_methods, ft_buffer, color::g, font_freetype_methods::get_glyph, font_freetype_methods::get_shadow, font_freetype_text::glyph, font_freetype_text::glyph_count, font_freetype_glyph::h, i, NULL, color::r, resize_ft_buffer(), graphics_priv::screen, set_pixel(), font_freetype_glyph::w, point::x, font_freetype_glyph::x, point::y, and font_freetype_glyph::y.
Referenced by draw_text().
static void draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_priv::aa, graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, graphics_priv::overlay_enable, graphics_priv::overlay_mode, graphics_priv::overlay_parent, raster_aacircle(), raster_circle(), graphics_priv::screen, point::x, and point::y.
Referenced by draw_lines().
static void draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_priv::overlay_x, graphics_priv::overlay_y, point::x, and point::y.
static void draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_image_priv::img, NULL, graphics_priv::overlay_enable, graphics_priv::overlay_parent, graphics_priv::screen, point::x, and point::y.
static void draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_priv::aa, dbg, draw_circle(), draw_polygon(), graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, i, graphics_gc_priv::linewidth, lvl_debug, M_PI, graphics_priv::overlay_enable, graphics_priv::overlay_parent, raster_aaline(), raster_line(), graphics_priv::screen, point::x, and point::y.
static void draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References dbg, graphics_priv::draw_mode, draw_mode_begin, draw_mode_end, i, lvl_debug, NULL, graphics_priv::overlay_array, graphics_priv::overlay_enable, OVERLAY_MAX, graphics_priv::overlay_mode, graphics_priv::overlay_x, graphics_priv::overlay_y, graphics_priv::screen, and graphics_priv::x.
Referenced by overlay_disable().
static void draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_priv::aa, alloca, dbg, graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, i, lvl_debug, graphics_priv::overlay_enable, graphics_priv::overlay_parent, raster_aapolygon(), raster_polygon(), and graphics_priv::screen.
Referenced by draw_lines().
static void draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References dbg, graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, lvl_debug, graphics_priv::overlay_enable, graphics_priv::overlay_parent, raster_rect(), graphics_priv::screen, point::x, and point::y.
static void draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References dbg, display_text_draw(), graphics_priv::freetype_methods, lvl_error, graphics_priv::overlay_enable, graphics_priv::overlay_parent, font_freetype_methods::text_destroy, font_freetype_methods::text_new, point::x, and point::y.
static void gc_destroy (struct graphics_gc_priv * gc) static
References g_free().
static struct graphics_gc_priv* gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References g_new0, gc_methods, graphics_gc_priv::gr, and graphics_gc_priv::linewidth.
static void gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, graphics_gc_priv::back_a, graphics_gc_priv::back_b, graphics_gc_priv::back_g, graphics_gc_priv::back_r, dbg, color::g, lvl_debug, and color::r.
static void gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
static void gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References color::a, color::b, dbg, graphics_gc_priv::fore_a, graphics_gc_priv::fore_b, graphics_gc_priv::fore_g, graphics_gc_priv::fore_r, color::g, lvl_debug, and color::r.
static void gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References dbg, graphics_gc_priv::linewidth, and lvl_debug.
static void* get_data (struct graphics_priv * this, char const * type) static
References window::disable_suspend, window::fullscreen, g_new, NULL, window::priv, and window_fullscreen().
static void graphics_destroy (struct graphics_priv * gr) static
References dbg, font_freetype_methods::destroy, graphics_priv::freetype_methods, ft_buffer, g_free(), lvl_debug, NULL, graphics_priv::overlay_array, graphics_priv::overlay_idx, graphics_priv::overlay_mode, graphics_priv::overlay_parent, and graphics_priv::screen.
static gboolean graphics_sdl_idle (void * data) static
References callback_call_0, callback_cast, callback_destroy(), callback_list_call_0, callback_list_call_attr_1, callback_list_call_attr_2, callback_list_call_attr_3, callback_new_1, idle_task::cb, cbl, graphics_priv::cbl, attr::data, dbg, event_add_timeout(), event_remove_timeout(), event_sdl_watch_stopthread(), FALSE, GINT_TO_POINTER, idle_tasks, if(), lvl_debug, lvl_error, lvl_info, lvl_warning, graphics_priv::nav, navit_destroy(), navit_get_attr(), NAVIT_KEY_BACK, NAVIT_KEY_BACKSPACE, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, NAVIT_KEY_ZOOM_OUT, NULL, idle_task::priority, quit_event_loop, graphics_priv::resize_callback_initial, graphics_priv::screen, TRUE, attr::type, attr::u, attr::vehicle, vehicle_set_attr(), graphics_priv::video_bpp, graphics_priv::video_flags, point::x, and point::y.
Referenced by graphics_sdl_new().
static struct graphics_priv* graphics_sdl_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), idle_task::cb, event_watch::cb, event_timeout::cb, cbl, dbg, dbg_assert, DISPLAY_H, DISPLAY_W, event_request_system(), event_sdl_add_idle(), event_sdl_add_timeout(), event_sdl_add_watch(), event_sdl_call_callback(), event_sdl_main_loop_quit(), event_sdl_main_loop_run(), event_sdl_methods, event_sdl_new(), event_sdl_remove_idle(), event_sdl_remove_timeout(), event_sdl_remove_watch(), event_sdl_watch_startthread(), event_sdl_watch_stopthread(), event_sdl_watch_thread(), event_watch_cond_except, event_watch_cond_read, event_watch_cond_write, event_watch::fd, font_freetype_new(), graphics_methods::font_new, g_free(), g_memmove, g_new0, graphics_methods::get_text_bbox, graphics_methods, graphics_sdl_idle(), event_timeout::id, idle_tasks, int, lvl_debug, lvl_error, lvl_info, methods, event_timeout::multi, NULL, attr::num, orientation, event_watch::pfd, idle_task::priority, quit_event_loop, sdl_sort_idle_tasks(), sdl_timer_callback(), sdl_watch_list, sdl_watch_thread, and attr::u.
Referenced by plugin_init().
static void image_free (struct graphics_priv * gr, struct graphics_image_priv * gi) static
References g_free(), and graphics_image_priv::img.
static struct graphics_image_priv* image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * name, int * w, int * h, struct point * hot, int rotation) static
References dbg, g_free(), g_new0, graphics_image_priv::img, lvl_error, NULL, point::x, and point::y.
static void overlay_disable (struct graphics_priv * gr, int disable) static
References graphics_priv::disable, draw_mode(), draw_mode_end, graphics_priv::overlay_enable, and graphics_priv::overlay_parent.
static struct graphics_priv * overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References dbg, font_freetype_new(), font_freetype_methods::font_new, graphics_methods::font_new, graphics_priv::freetype_methods, g_new0, font_freetype_methods::get_text_bbox, graphics_methods::get_text_bbox, graphics_methods, i, int, lvl_debug, lvl_error, NULL, graphics_priv::overlay_array, graphics_priv::overlay_enable, graphics_priv::overlay_idx, OVERLAY_MAX, graphics_priv::overlay_mode, graphics_priv::overlay_parent, graphics_priv::overlay_x, graphics_priv::overlay_y, graphics_priv::screen, point::x, and point::y.
void plugin_init (void)
References event_sdl_new(), and graphics_sdl_new().
static void resize_ft_buffer (unsigned int new_size) static
References dbg, ft_buffer, ft_buffer_size, g_free(), g_malloc(), and lvl_debug.
Referenced by display_text_draw().
static void set_pixel (SDL_Surface * surface, int x, int y, Uint8 r2, Uint8 g2, Uint8 b2, Uint8 a2) static
Referenced by display_text_draw().
static int window_fullscreen (struct window * win, int on) static
References callback_list_call_attr_2, graphics_priv::cbl, GINT_TO_POINTER, graphics_priv::nav, navit_destroy(), NULL, window::priv, graphics_priv::screen, graphics_priv::video_bpp, and graphics_priv::video_flags.
Referenced by get_data().
Variable Documentation
unsigned char* ft_buffer = NULL
Referenced by display_text_draw(), graphics_destroy(), and resize_ft_buffer().
unsigned int ft_buffer_size = 0
Referenced by resize_ft_buffer().
struct graphics_gc_methods gc_methods static
Initial value:
= {
    gc_destroy,
    gc_set_linewidth,
    gc_set_dashes,
    gc_set_foreground,
    gc_set_background
}
Referenced by gc_new().
struct graphics_methods graphics_methods static
Initial value:
= {
    graphics_destroy,
    draw_mode,
    draw_lines,
    draw_polygon,
    draw_rectangle,
    NULL ,
    draw_text,
    draw_image,
    NULL,
    draw_drag,
    NULL,
    gc_new,
    background_gc,
    overlay_new,
    image_new,
    get_data,
    image_free,
    NULL,
    overlay_disable,
    NULL,
    NULL,
        NULL,
        NULL,
}
Referenced by graphics_sdl_new(), and overlay_new().