navit: graphics/opengl/graphics_opengl_egl.c File Reference
graphics_opengl_egl.c File Reference
#include "config.h"
#include <GLES/gl.h>
#include <GLES/egl.h>
#include <glib.h>
#include "graphics_opengl.h"
#include "debug.h"
Data Structures
struct graphics_opengl_platform
Functions
static void graphics_opengl_egl_destroy (struct graphics_opengl_platform *egl)
static void graphics_opengl_egl_swap_buffers (struct graphics_opengl_platform *egl)
struct graphics_opengl_platform * graphics_opengl_egl_new (void *display, void *window, struct graphics_opengl_platform_methods **methods)
Variables
static EGLint attributeList []
EGLint aEGLContextAttributes []
struct graphics_opengl_platform_methods graphics_opengl_egl_methods
Function Documentation
graphics_opengl_egl_destroy()
static void graphics_opengl_egl_destroy (struct graphics_opengl_platform * egl) static
Referenced by graphics_opengl_egl_new().
graphics_opengl_egl_new()
struct graphics_opengl_platform* graphics_opengl_egl_new (void * display, void * window, struct graphics_opengl_platform_methods ** methods)
References aEGLContextAttributes, attributeList, graphics_opengl_platform::config, graphics_opengl_platform::context, dbg, graphics_opengl_platform::egldisplay, graphics_opengl_platform::eglwindow, graphics_opengl_egl_destroy(), graphics_opengl_egl_methods, lvl_debug, and lvl_error.
Referenced by get_data().
graphics_opengl_egl_swap_buffers()
static void graphics_opengl_egl_swap_buffers (struct graphics_opengl_platform * egl) static
References graphics_opengl_platform::egldisplay, and graphics_opengl_platform::eglwindow.
Variable Documentation
aEGLContextAttributes
EGLint aEGLContextAttributes[]
Initial value:
= {
    EGL_NONE
}
Referenced by graphics_opengl_egl_new().
attributeList
EGLint attributeList[] static
Initial value:
= {
    EGL_RED_SIZE, 8,
    EGL_ALPHA_SIZE, 8,
    EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
    EGL_NONE
}
Referenced by graphics_opengl_egl_new().
graphics_opengl_egl_methods
struct graphics_opengl_platform_methods graphics_opengl_egl_methods
Initial value:
= {
    graphics_opengl_egl_destroy,
    graphics_opengl_egl_swap_buffers,
}
Referenced by graphics_opengl_egl_new().