navit: graphics/svg_debug/graphics_svg_debug.c File Reference
graphics_svg_debug.c File Reference
#include "color.h"
#include <glib.h>
#include "config.h"
#include <gio/gio.h>
#include <pthread.h>
#include <poll.h>
#include <signal.h>
#include "debug.h"
#include "point.h"
#include "graphics.h"
#include "plugin.h"
#include "window.h"
#include "navit.h"
#include "keys.h"
#include "item.h"
#include "attr.h"
#include "event.h"
#include "callback.h"
#include "util.h"
Data Structures
struct graphics_priv
struct graphics_font_priv
struct graphics_gc_priv
struct graphics_image_priv
Functions
static void svg_debug_graphics_destroy (struct graphics_priv *gr)
static void svg_debug_font_destroy (struct graphics_font_priv *this)
void svg_debug_get_text_bbox (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
static void resize_callback_do (struct graphics_priv *gr, int w, int h)
static struct graphics_font_priv * svg_debug_font_new (struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
static void svg_debug_gc_destroy (struct graphics_gc_priv *gc)
static void svg_debug_gc_set_linewidth (struct graphics_gc_priv *gc, int w)
static void svg_debug_gc_set_dashes (struct graphics_gc_priv *gc, int w, int offset, unsigned char *dash_list, int n)
static void svg_debug_gc_set_foreground (struct graphics_gc_priv *gc, struct color *c)
static void svg_debug_gc_set_background (struct graphics_gc_priv *gc, struct color *c)
static void svg_debug_gc_set_texture (struct graphics_gc_priv *gc, struct graphics_image_priv *img)
static struct graphics_gc_priv * svg_debug_gc_new (struct graphics_priv *gr, struct graphics_gc_methods *meth)
void svg_debug_image_destroy (struct graphics_image_priv *img)
static struct graphics_image_priv * svg_debug_image_new (struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
static void svg_debug_draw_lines (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void svg_debug_draw_polygon (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
static void svg_debug_draw_rectangle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
static void svg_debug_draw_circle (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
static void svg_debug_draw_text (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
static void svg_debug_draw_image (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
static void svg_debug_draw_drag (struct graphics_priv *gr, struct point *p)
static void svg_debug_background_gc (struct graphics_priv *gr, struct graphics_gc_priv *gc)
static void svg_debug_draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static void graphics_svg_debug_overlay_draw_mode (struct graphics_priv *gr, enum draw_mode_num mode)
static struct graphics_priv * graphics_svg_debug_overlay_new (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
static int graphics_svg_debug_fullscreen (struct window *win, int on)
static gboolean graphics_svg_debug_idle (void *data)
static void graphics_svg_debug_disable_suspend (struct window *w)
static void * svg_debug_get_data (struct graphics_priv *this, char const *type)
static void svg_debug_image_free (struct graphics_priv *gr, struct graphics_image_priv *img)
static void graphics_svg_debug_overlay_disable (struct graphics_priv *gr, int disable)
static void graphics_svg_debug_overlay_resize (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
static struct graphics_priv * graphics_svg_debug_new (struct navit *nav, struct graphics_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
Variables
static struct graphics_font_methods font_methods
static struct graphics_gc_methods gc_methods
static struct graphics_image_methods image_methods
static struct graphics_methods graphics_methods
Function Documentation
graphics_svg_debug_disable_suspend()
static void graphics_svg_debug_disable_suspend (struct window * w) static
References graphics_methods::get_data, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, and graphics_priv::w.
Referenced by svg_debug_get_data().
graphics_svg_debug_fullscreen()
static int graphics_svg_debug_fullscreen (struct window * win, int on) static
References graphics_methods::get_data, window::priv, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, and graphics_priv::win.
Referenced by svg_debug_get_data().
graphics_svg_debug_idle()
static gboolean graphics_svg_debug_idle (void * data) static
References callback_list_call_attr_2, graphics_priv::cbl, data, graphics_priv::height, and graphics_priv::width.
Referenced by graphics_svg_debug_new().
graphics_svg_debug_new()
static struct graphics_priv* graphics_svg_debug_new (struct navit * nav, struct graphics_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), attr::attrs, graphics_methods::background_gc, callback_cast, callback_list_add(), callback_list_call_attr_2, callback_new_attr_1, cbl, dbg, graphics_methods::draw_circle, graphics_methods::draw_drag, graphics_methods::draw_image, graphics_methods::draw_image_warp, graphics_methods::draw_lines, graphics_methods::draw_polygon, graphics_methods::draw_polygon_with_holes, graphics_methods::draw_rectangle, graphics_methods::draw_text, event_request_system(), graphics_methods::font_new, graphics_methods::gc_new, graphics_methods::get_dpi, graphics_methods::get_text_bbox, graphics_methods::graphics_destroy, graphics_methods, graphics_svg_debug_idle(), height, graphics_methods::hide_native_keyboard, graphics_methods::image_free, graphics_methods::image_new, lvl_debug, lvl_error, attr::num, graphics_methods::overlay_disable, graphics_methods::overlay_new, graphics_methods::overlay_resize, resize_callback_do(), graphics_methods::set_attr, graphics_methods::show_native_keyboard, attr::str, attr::u, and width.
Referenced by plugin_init().
graphics_svg_debug_overlay_disable()
static void graphics_svg_debug_overlay_disable (struct graphics_priv * gr, int disable) static
graphics_svg_debug_overlay_draw_mode()
static void graphics_svg_debug_overlay_draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
Referenced by graphics_svg_debug_overlay_new().
graphics_svg_debug_overlay_new()
static struct graphics_priv * graphics_svg_debug_overlay_new (struct graphics_priv * gr, struct graphics_methods * meth, struct point * p, int w, int h, int wraparound) static
References graphics_methods::draw_mode, graphics_methods, and graphics_svg_debug_overlay_draw_mode().
graphics_svg_debug_overlay_resize()
static void graphics_svg_debug_overlay_resize (struct graphics_priv * gr, struct point * p, int w, int h, int wraparound) static
plugin_init()
void plugin_init (void)
References dbg, graphics_svg_debug_new(), and lvl_error.
resize_callback_do()
static void resize_callback_do (struct graphics_priv * gr, int w, int h) static
References dbg, graphics_priv::height, lvl_debug, and graphics_priv::width.
Referenced by graphics_svg_debug_new().
svg_debug_background_gc()
static void svg_debug_background_gc (struct graphics_priv * gr, struct graphics_gc_priv * gc) static
References graphics_methods::background_gc, graphics_gc_priv::graphics_gc_priv_proxy, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_circle()
static void svg_debug_draw_circle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int r) static
References graphics_methods::draw_circle, graphics_gc_priv::fg, graphics_gc_priv::graphics_gc_priv_proxy, graphics_priv::outfile, p, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_drag()
static void svg_debug_draw_drag (struct graphics_priv * gr, struct point * p) static
References graphics_methods::draw_drag, p, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_image()
static void svg_debug_draw_image (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct point * p, struct graphics_image_priv * img) static
References graphics_image_priv::data, graphics_methods::draw_image, graphics_image_priv::graphics_image_priv_proxy, graphics_image_priv::h, graphics_priv::outfile, p, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, and graphics_image_priv::w.
svg_debug_draw_lines()
static void svg_debug_draw_lines (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_gc_priv::dashed, graphics_methods::draw_lines, graphics_gc_priv::fg, graphics_gc_priv::graphics_gc_priv_proxy, graphics_gc_priv::is_dashed, graphics_gc_priv::linewidth, graphics_priv::outfile, p, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_mode()
static void svg_debug_draw_mode (struct graphics_priv * gr, enum draw_mode_num mode) static
References dbg, graphics_methods::draw_mode, draw_mode_begin, draw_mode_end, filename, graphics_priv::frame, graphics_priv::height, lvl_debug, graphics_priv::outfile, graphics_priv::outputdir, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, and graphics_priv::width.
svg_debug_draw_polygon()
static void svg_debug_draw_polygon (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int count) static
References graphics_methods::draw_polygon, graphics_gc_priv::fg, graphics_gc_priv::graphics_gc_priv_proxy, graphics_priv::outfile, p, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_rectangle()
static void svg_debug_draw_rectangle (struct graphics_priv * gr, struct graphics_gc_priv * gc, struct point * p, int w, int h) static
References graphics_methods::draw_rectangle, graphics_gc_priv::fg, graphics_gc_priv::graphics_gc_priv_proxy, graphics_priv::outfile, p, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_draw_text()
static void svg_debug_draw_text (struct graphics_priv * gr, struct graphics_gc_priv * fg, struct graphics_gc_priv * bg, struct graphics_font_priv * font, char * text, struct point * p, int dx, int dy) static
References graphics_methods::draw_text, graphics_gc_priv::fg, graphics_font_priv::graphics_font_proxy, graphics_gc_priv::graphics_gc_priv_proxy, graphics_priv::outfile, p, graphics_font::priv, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, and graphics_font_priv::size.
svg_debug_font_destroy()
static void svg_debug_font_destroy (struct graphics_font_priv * this) static
References dbg, and lvl_debug.
svg_debug_font_new()
static struct graphics_font_priv* svg_debug_font_new (struct graphics_priv * gr, struct graphics_font_methods * meth, char * font, int size, int flags) static
References graphics_font_priv::font, font_methods, graphics_methods::font_new, graphics_font_priv::graphics_font_proxy, graphics_font::meth, graphics_font::priv, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, graphics_font_priv::size, and size.
svg_debug_gc_destroy()
static void svg_debug_gc_destroy (struct graphics_gc_priv * gc) static
References graphics_gc_methods::gc_destroy, graphics_gc_priv::graphics_gc_methods_proxy, and graphics_gc_priv::graphics_gc_priv_proxy.
svg_debug_gc_new()
static struct graphics_gc_priv* svg_debug_gc_new (struct graphics_priv * gr, struct graphics_gc_methods * meth) static
References gc_methods, graphics_methods::gc_new, graphics_gc_priv::gr, graphics_gc_priv::graphics_gc_methods_proxy, graphics_gc_priv::graphics_gc_priv_proxy, graphics_gc_priv::is_dashed, graphics_gc_priv::linewidth, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_gc_set_background()
static void svg_debug_gc_set_background (struct graphics_gc_priv * gc, struct color * c) static
References graphics_gc_priv::bg, c, graphics_gc_methods::gc_set_foreground, graphics_gc_priv::graphics_gc_methods_proxy, and graphics_gc_priv::graphics_gc_priv_proxy.
svg_debug_gc_set_dashes()
static void svg_debug_gc_set_dashes (struct graphics_gc_priv * gc, int w, int offset, unsigned char * dash_list, int n) static
References graphics_gc_priv::dashed, graphics_gc_methods::gc_set_dashes, graphics_gc_priv::graphics_gc_methods_proxy, graphics_gc_priv::graphics_gc_priv_proxy, graphics_gc_priv::is_dashed, and offset.
svg_debug_gc_set_foreground()
static void svg_debug_gc_set_foreground (struct graphics_gc_priv * gc, struct color * c) static
References c, graphics_gc_priv::fg, graphics_gc_methods::gc_set_foreground, graphics_gc_priv::graphics_gc_methods_proxy, and graphics_gc_priv::graphics_gc_priv_proxy.
svg_debug_gc_set_linewidth()
static void svg_debug_gc_set_linewidth (struct graphics_gc_priv * gc, int w) static
References graphics_gc_methods::gc_set_linewidth, graphics_gc_priv::graphics_gc_methods_proxy, graphics_gc_priv::graphics_gc_priv_proxy, and graphics_gc_priv::linewidth.
svg_debug_gc_set_texture()
static void svg_debug_gc_set_texture (struct graphics_gc_priv * gc, struct graphics_image_priv * img) static
svg_debug_get_data()
static void* svg_debug_get_data (struct graphics_priv * this, char const * type) static
References window::disable_suspend, window::fullscreen, graphics_svg_debug_disable_suspend(), graphics_svg_debug_fullscreen(), window::priv, and type.
svg_debug_get_text_bbox()
void svg_debug_get_text_bbox (struct graphics_priv * gr, struct graphics_font_priv * font, char * text, int dx, int dy, struct point * ret, int estimate)
References graphics_font_priv::font, graphics_methods::get_text_bbox, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_graphics_destroy()
static void svg_debug_graphics_destroy (struct graphics_priv * gr) static
svg_debug_image_destroy()
void svg_debug_image_destroy (struct graphics_image_priv * img)
svg_debug_image_free()
static void svg_debug_image_free (struct graphics_priv * gr, struct graphics_image_priv * img) static
References graphics_image_priv::data, dbg, graphics_image_priv::graphics_image_methods_proxy, graphics_image_priv::graphics_image_priv_proxy, graphics_image_methods::image_destroy, graphics_methods::image_free, lvl_debug, graphics_priv::proxy_graphics_methods, and graphics_priv::proxy_priv.
svg_debug_image_new()
static struct graphics_image_priv* svg_debug_image_new (struct graphics_priv * gr, struct graphics_image_methods * meth, char * path, int * w, int * h, struct point * hot, int rotation) static
References graphics_image_priv::data, dbg, graphics_image_priv::graphics_image_methods_proxy, graphics_image_priv::graphics_image_priv_proxy, graphics_image_priv::h, image_methods, graphics_methods::image_new, lvl_debug, lvl_error, graphics_priv::proxy_graphics_methods, graphics_priv::proxy_priv, strtolower(), and graphics_image_priv::w.
Variable Documentation
font_methods
struct graphics_font_methods font_methods static
Initial value:
= { .font_destroy =
        svg_debug_font_destroy,
}
Referenced by svg_debug_font_new().
gc_methods
struct graphics_gc_methods gc_methods static
Initial value:
= { .gc_destroy =
        svg_debug_gc_destroy, .gc_set_linewidth = svg_debug_gc_set_linewidth,
                              .gc_set_dashes = svg_debug_gc_set_dashes, .gc_set_foreground =
                                          svg_debug_gc_set_foreground, .gc_set_background =
                                                  svg_debug_gc_set_background, .gc_set_texture =
                                                          svg_debug_gc_set_texture,
}
Referenced by svg_debug_gc_new().
graphics_methods
struct graphics_methods graphics_methods static
Referenced by graphics_svg_debug_new(), and graphics_svg_debug_overlay_new().
image_methods
struct graphics_image_methods image_methods static
Initial value:
= { .image_destroy =
        svg_debug_image_destroy,
}
Referenced by svg_debug_image_new().