navit: graphics/opengl/graphics_opengl.h File Reference
graphics_opengl.h File Reference
Data Structures
struct graphics_opengl_window_system_methods
struct graphics_opengl_platform_methods
Functions
struct
graphics_opengl_window_system * graphics_opengl_x11_new (void *displayname, int w, int h, int depth, struct graphics_opengl_window_system_methods **methods)
struct graphics_opengl_platform * graphics_opengl_egl_new (void *display, void *window, struct graphics_opengl_platform_methods **methods)
Function Documentation
struct graphics_opengl_platform* graphics_opengl_egl_new (void * display, void * window, struct graphics_opengl_platform_methods ** methods)
References aEGLContextAttributes, attributeList, graphics_opengl_platform::config, graphics_opengl_platform::context, dbg, graphics_opengl_platform::egldisplay, graphics_opengl_platform::eglwindow, g_new0, graphics_opengl_egl_destroy(), graphics_opengl_egl_methods, lvl_debug, lvl_error, and NULL.
Referenced by get_data().
struct graphics_opengl_window_system* graphics_opengl_x11_new (void * displayname, int w, int h, int depth, struct graphics_opengl_window_system_methods ** methods)
References callback_cast, callback_new_1, graphics_opengl_window_system::cb, graphics_opengl_window_system::colormap, dbg, graphics_opengl_window_system::display, event_add_watch(), event_request_system(), event_watch_cond_read, g_new0, graphics_opengl_x11_destroy(), graphics_opengl_x11_methods, graphics_opengl_x11_watch(), lvl_error, NULL, graphics_opengl_window_system::root_window, graphics_opengl_window_system::screen, graphics_opengl_window_system::visual, graphics_opengl_window_system::watch, and graphics_opengl_window_system::window.
Referenced by get_data().