navit: Vehicle QT5
Vehicle QT5
vehicle plugins
The Vehicle to gain position data from qt5.
Functions
static void vehicle_qt5_destroy (struct vehicle_priv *priv)
Free the null_vehicle.
static int vehicle_qt5_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Provide the outside with information.
static int vehicle_qt5_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_qt5_new_qt5 (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Create null_vehicle.
void plugin_init (void)
register vehicle_null
QNavitGeoReceiver::QNavitGeoReceiver (QObject *parent, struct vehicle_priv *c)
Variables
struct vehicle_methods vehicle_null_methods
Public Slots
void QNavitGeoReceiver::satellitesInUseUpdated (const QList< QGeoSatelliteInfo > &satellites)
void QNavitGeoReceiver::satellitesInViewUpdated (const QList< QGeoSatelliteInfo > &satellites)
void QNavitGeoReceiver::positionUpdated (const QGeoPositionInfo &info)
Detailed Description
The Vehicle to gain position data from qt5.
Function Documentation
void plugin_init (void)
register vehicle_null
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_qt5_new_qt5().
QNavitGeoReceiver::QNavitGeoReceiver (QObject * parent, struct vehicle_priv * c)
References c, QNavitGeoReceiver::positionUpdated(), QNavitGeoReceiver::priv, vehicle_priv::satellites, QNavitGeoReceiver::satellitesInUseUpdated(), QNavitGeoReceiver::satellitesInViewUpdated(), and vehicle_priv::source.
static void vehicle_qt5_destroy (struct vehicle_priv * priv) static
Free the null_vehicle.
Parameters
priv
Returns
nothing
References dbg, lvl_debug, vehicle_priv::receiver, and vehicle_priv::source.
static struct vehicle_priv* vehicle_qt5_new_qt5 (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Create null_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References vehicle_priv::attrs, vehicle_priv::cbl, cbl, dbg, lvl_debug, lvl_error, vehicle_priv::receiver, vehicle_priv::satellites, vehicle_priv::source, and vehicle_null_methods.
Referenced by plugin_init().
static int vehicle_qt5_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Provide the outside with information.
Parameters
priv
type TODO: What can this be?
attr
Returns
true/false
References active, attr_search(), attr_to_name(), vehicle_priv::attrs, attr::coord_geo, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::have_coords, vehicle_priv::height, lvl_debug, attr::num, attr::numd, vehicle_priv::radius, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
static int vehicle_qt5_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References callback_list_call_attr_0, vehicle_priv::cbl, attr::coord_geo, vehicle_priv::direction, vehicle_priv::geo, vehicle_priv::have_coords, attr::numd, vehicle_priv::speed, attr::type, and attr::u.
Variable Documentation
struct vehicle_methods vehicle_null_methods
Initial value:
= {
    vehicle_qt5_destroy,
    vehicle_qt5_position_attr_get,
    vehicle_qt5_set_attr,
}
Referenced by vehicle_qt5_new_qt5().
Public Slots
void QNavitGeoReceiver::positionUpdated (const QGeoPositionInfo & info) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::geo, vehicle_priv::have_coords, vehicle_priv::height, coord_geo::lat, coord_geo::lng, lvl_debug, QNavitGeoReceiver::priv, vehicle_priv::radius, and vehicle_priv::speed.
Referenced by QNavitGeoReceiver::QNavitGeoReceiver().
void QNavitGeoReceiver::satellitesInUseUpdated (const QList< QGeoSatelliteInfo > & satellites) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, lvl_debug, QNavitGeoReceiver::priv, and vehicle_priv::sats_used.
Referenced by QNavitGeoReceiver::QNavitGeoReceiver().
void QNavitGeoReceiver::satellitesInViewUpdated (const QList< QGeoSatelliteInfo > & satellites) slot
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, lvl_debug, QNavitGeoReceiver::priv, and vehicle_priv::sats.
Referenced by QNavitGeoReceiver::QNavitGeoReceiver().