navit: Plugins
Plugins
A interface to handle all plugins inside navit.
Modules
vehicle plugins
Generic components of the vehicle object.
Data Structures
struct plugin
struct plugins
Functions
static struct plugin * plugin_new_from_path (char *plugin)
int plugin_load (struct plugin *pl)
char * plugin_get_name (struct plugin *pl)
int plugin_get_active (struct plugin *pl)
void plugin_set_active (struct plugin *pl, int active)
void plugin_set_lazy (struct plugin *pl, int lazy)
static void plugin_set_ondemand (struct plugin *pl, int ondemand)
void plugin_call_init (struct plugin *pl)
void plugin_unload (struct plugin *pl)
void plugin_destroy (struct plugin *pl)
struct plugins * plugins_new (struct attr *in, struct attr **out)
struct plugin * plugin_new (struct attr *parent, struct attr **attrs)
int plugins_init (struct plugins *pls)
void plugins_destroy (struct plugins *pls)
static void * find_by_name (enum plugin_category category, const char *name)
void * plugin_get_category (enum plugin_category category, const char *category_name, const char *name)
Variables
int plugin::active
int plugin::lazy
int plugin::ondemand
char * plugin::name
void(* plugin::init)(void)
GHashTable * plugins::hash
GList * plugins::list
struct plugins * pls
Detailed Description
A interface to handle all plugins inside navit.
Function Documentation
find_by_name()
static void* find_by_name (enum plugin_category category, const char * name) static
Referenced by plugin_get_category().
plugin_call_init()
void plugin_call_init (struct plugin * pl)
References plugin::init.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
plugin_destroy()
void plugin_destroy (struct plugin * pl)
Referenced by plugins_destroy().
plugin_get_active()
int plugin_get_active (struct plugin * pl)
References plugin::active.
Referenced by plugin_get_category(), and plugins_init().
plugin_get_category()
void* plugin_get_category (enum plugin_category category, const char * category_name, const char * name)
References dbg, filename, find_by_name(), list, lvl_debug, plugin::name, pls, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
plugin_get_name()
char* plugin_get_name (struct plugin * pl)
References plugin::name.
Referenced by plugin_new().
plugin_load()
int plugin_load (struct plugin * pl)
References dbg, plugin::init, plugin::lazy, lvl_debug, lvl_error, and plugin::name.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
plugin_new()
struct plugin* plugin_new (struct attr * parent, struct attr ** attrs)
References plugin::active, attr_search(), dbg, file_exists(), file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), hash, plugin::lazy, list, lvl_debug, lvl_error, lvl_info, plugin::name, attr::num, plugin::ondemand, pls, plugin_call_init(), plugin_get_name(), plugin_load(), plugin_new_from_path(), plugin_set_active(), plugin_set_lazy(), plugin_set_ondemand(), attr::plugins, attr::str, attr::u, and file_wordexp::we.
Referenced by add_plugin().
plugin_new_from_path()
static struct plugin* plugin_new_from_path (char * plugin) static
References plugin::name.
Referenced by plugin_new().
plugin_set_active()
void plugin_set_active (struct plugin * pl, int active)
References plugin::active.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
plugin_set_lazy()
void plugin_set_lazy (struct plugin * pl, int lazy)
References plugin::lazy, and plugin::ondemand.
Referenced by plugin_new().
plugin_set_ondemand()
static void plugin_set_ondemand (struct plugin * pl, int ondemand) static
References plugin::ondemand.
Referenced by plugin_new().
plugin_unload()
void plugin_unload (struct plugin * pl)
Referenced by plugins_destroy().
plugins_destroy()
void plugins_destroy (struct plugins * pls)
References hash, list, plugin_destroy(), and plugin_unload().
plugins_init()
int plugins_init (struct plugins * pls)
References dbg, list, lvl_error, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
Referenced by maptool_init().
plugins_new()
struct plugins* plugins_new (struct attr * in, struct attr ** out)
References hash, and pls.
Referenced by add_plugin().
Variable Documentation
active
int plugin::active
Referenced by plugin_get_active(), plugin_new(), and plugin_set_active().
hash
GHashTable* plugins::hash
Referenced by plugin_new(), plugins_destroy(), and plugins_new().
init
void(* plugin::init) (void)
Referenced by plugin_call_init(), and plugin_load().
lazy
int plugin::lazy
Referenced by plugin_load(), plugin_new(), and plugin_set_lazy().
list
GList* plugins::list
Referenced by plugin_get_category(), plugin_new(), plugins_destroy(), and plugins_init().
name
char* plugin::name
Referenced by plugin_get_category(), plugin_get_name(), plugin_load(), plugin_new(), and plugin_new_from_path().
ondemand
int plugin::ondemand
Referenced by plugin_new(), plugin_set_lazy(), and plugin_set_ondemand().
pls
struct plugins * pls
Referenced by plugin_get_category(), plugin_new(), and plugins_new().