navit: Vehicle WinCE
Vehicle WinCE
Plugins » vehicle plugins
The Vehicle to gain position data from WinCE.
Data Structures
struct gps_sat
struct vehicle_priv
Macros
#define SwitchToThread() Sleep(0)
#define W2A(lpw)
#define A2W(lpa)
Typedefs
typedef int(WINAPI * PFN_BthSetMode) (DWORD pBthMode)
typedef int(WINAPI * PFN_BthGetMode) (DWORD *pBthMode)
Enumerations
enum file_type {
file_type_pipe = 1, file_type_device, file_type_file, file_type_socket,
file_type_serial, file_type_pipe = 1, file_type_device, file_type_file,
file_type_socket
}
Functions
static void vehicle_wince_disable_watch (struct vehicle_priv *priv)
static void vehicle_wince_enable_watch (struct vehicle_priv *priv)
static int vehicle_wince_parse (struct vehicle_priv *priv, char *buffer)
static int vehicle_wince_open (struct vehicle_priv *priv)
static void vehicle_wince_close (struct vehicle_priv *priv)
static void initBth (struct vehicle_priv *priv)
static int initDevice (struct vehicle_priv *priv)
static int read_win32 (struct vehicle_priv *priv, char *buffer, size_t size)
static DWORD WINAPI wince_reader_thread (LPVOID lParam)
static int vehicle_wince_available_ports (void)
static void vehicle_wince_fix_timeout_cb (struct vehicle_priv *priv)
This is a callback function, called when the fix timeout is done. Set the position to invalid.
static void vehicle_wince_restart_fix_timeout (struct vehicle_priv *priv)
Cancel previous fix timeout event and add a new one.
static void vehicle_wince_io (struct vehicle_priv *priv)
static void vehicle_wince_destroy (struct vehicle_priv *priv)
Frees the wince_vehicle.
static int vehicle_wince_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Retrieves a vehicle attribute.
static int vehicle_wince_sat_attr_get (void *priv_data, enum attr_type type, struct attr *attr)
static struct vehicle_priv * vehicle_wince_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Creates a new wince_vehicle.
void plugin_init (void)
Registers the vehicle_wince plugin.
Variables
char * _convert = NULL
wchar_t * _wconvert = NULL
static int buffer_size = 1024
struct callback_list * vehicle_priv::priv_cbl
int vehicle_priv::is_running
int vehicle_priv::thread_up
HANDLE vehicle_priv::m_hGPSDevice
HANDLE vehicle_priv::m_hGPSThread
DWORD vehicle_priv::m_dwGPSThread
char * vehicle_priv::read_buffer
int vehicle_priv::read_buffer_pos
int vehicle_priv::baudrate
HMODULE vehicle_priv::hBthDll
PFN_BthSetMode vehicle_priv::BthSetMode
int vehicle_priv::has_data
GMutex vehicle_priv::lock
static struct item_methods vehicle_wince_sat_methods
struct vehicle_methods vehicle_wince_methods
Detailed Description
The Vehicle to gain position data from WinCE.
Macro Definition Documentation
A2W
#define A2W (lpa)
Value:
(\
        ((LPCSTR)lpa == NULL) ? NULL : (\
                _wconvert = alloca(strlen(lpa)*2+1),  mbstowcs(_wconvert, lpa, strlen(lpa) * 2 + 1), _wconvert) )
Referenced by initDevice().
SwitchToThread
#define SwitchToThread () Sleep(0)
Referenced by vehicle_wince_disable_watch().
W2A
#define W2A (lpw)
Value:
(\
        ((LPCSTR)lpw == NULL) ? NULL : (\
                _convert = alloca(wcslen(lpw)+1),  wcstombs(_convert, lpw, wcslen(lpw) + 1), _convert) )
Referenced by vehicle_wince_available_ports().
Typedef Documentation
PFN_BthGetMode
typedef int(WINAPI * PFN_BthGetMode) (DWORD *pBthMode)
PFN_BthSetMode
typedef int(WINAPI * PFN_BthSetMode) (DWORD pBthMode)
Enumeration Type Documentation
file_type
enum file_type
Enumerator
file_type_pipe
file_type_device
file_type_file
file_type_socket
file_type_serial
file_type_pipe
file_type_device
file_type_file
file_type_socket
Function Documentation
initBth()
static void initBth (struct vehicle_priv * priv) static
References vehicle_priv::BthSetMode, dbg, vehicle_priv::hBthDll, lvl_debug, lvl_error, and lvl_warning.
Referenced by vehicle_wince_new().
initDevice()
static int initDevice (struct vehicle_priv * priv) static
References A2W, vehicle_priv::baudrate, dbg, vehicle_priv::file_type, file_type_device, IOCTL_SERVICE_REFRESH, IOCTL_SERVICE_START, vehicle_priv::is_running, L, lvl_debug, lvl_error, vehicle_priv::m_hGPSDevice, vehicle_priv::source, and vehicle_priv::thread_up.
Referenced by wince_reader_thread().
plugin_init()
void plugin_init (void)
Registers the vehicle_wince plugin.
register vehicle_gypsy
References attr::callback, callback_cast, callback_new_attr_0, config_add_attr(), dbg, lvl_debug, lvl_info, osso_navit(), attr::u, and vehicle_wince_new().
read_win32()
static int read_win32 (struct vehicle_priv * priv, char * buffer, size_t size) static
References buffer_size, vehicle_priv::has_data, vehicle_priv::lock, vehicle_priv::read_buffer, and vehicle_priv::read_buffer_pos.
Referenced by vehicle_wince_io().
vehicle_wince_available_ports()
static int vehicle_wince_available_ports (void) static
References dbg, L, lvl_debug, and W2A.
Referenced by vehicle_wince_open().
vehicle_wince_close()
static void vehicle_wince_close (struct vehicle_priv * priv) static
References dbg, and lvl_debug.
Referenced by vehicle_wince_destroy(), and vehicle_wince_io().
vehicle_wince_destroy()
static void vehicle_wince_destroy (struct vehicle_priv * priv) static
Frees the wince_vehicle.
Parameters
priv vehicle_priv structure for the vehicle
References vehicle_priv::BthSetMode, vehicle_priv::buffer, vehicle_priv::hBthDll, vehicle_priv::read_buffer, vehicle_priv::source, vehicle_wince_close(), and vehicle_wince_disable_watch().
Referenced by vehicle_wince_new().
vehicle_wince_disable_watch()
static void vehicle_wince_disable_watch (struct vehicle_priv * priv) static
References dbg, vehicle_priv::is_running, lvl_debug, vehicle_priv::m_hGPSThread, SwitchToThread, and vehicle_priv::thread_up.
Referenced by vehicle_wince_destroy(), vehicle_wince_enable_watch(), and vehicle_wince_io().
vehicle_wince_enable_watch()
static void vehicle_wince_enable_watch (struct vehicle_priv * priv) static
References dbg, vehicle_priv::is_running, vehicle_priv::lock, lvl_debug, vehicle_priv::m_dwGPSThread, vehicle_priv::m_hGPSThread, vehicle_wince_disable_watch(), and wince_reader_thread().
Referenced by vehicle_wince_new().
vehicle_wince_fix_timeout_cb()
static void vehicle_wince_fix_timeout_cb (struct vehicle_priv * priv) static
This is a callback function, called when the fix timeout is done. Set the position to invalid.
Parameters
priv Pointer on the private data of the plugin
References attr_position_valid_invalid, callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::ev_fix_timeout, and vehicle_priv::valid.
Referenced by vehicle_wince_new().
vehicle_wince_io()
static void vehicle_wince_io (struct vehicle_priv * priv) static
References vehicle_priv::buffer, vehicle_priv::buffer_pos, buffer_size, callback_list_call_attr_0, vehicle_priv::cbl, dbg, exit, vehicle_priv::file_type, file_type_file, lvl_debug, lvl_error, lvl_info, vehicle_priv::on_eof, read_win32(), size, vehicle_wince_close(), vehicle_wince_disable_watch(), vehicle_wince_open(), and vehicle_wince_parse().
Referenced by vehicle_wince_new().
vehicle_wince_new()
static struct vehicle_priv* vehicle_wince_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Creates a new wince_vehicle.
Parameters
meth ?
cbl ?
attrs ?
Returns
vehicle_priv
References attr_search(), vehicle_priv::attrs, attr::attrs, vehicle_priv::baudrate, vehicle_priv::buffer, buffer_size, callback_cast, callback_list_add(), callback_list_new(), callback_new_1, vehicle_priv::cb_fix_timeout, vehicle_priv::cbl, cbl, vehicle_priv::checksum_ignore, dbg, vehicle_priv::ev_fix_timeout, vehicle_priv::fd, vehicle_priv::file_type, file_type_device, file_type_file, vehicle_priv::fixtime, item::id_hi, item::id_lo, initBth(), lvl_debug, lvl_error, item::meth, attr::num, vehicle_priv::on_eof, vehicle_priv::priv_cbl, item::priv_data, vehicle_priv::read_buffer, vehicle_priv::sat_item, vehicle_priv::source, attr::str, vehicle_priv::time, item::type, attr::u, vehicle_wince_destroy(), vehicle_wince_enable_watch(), vehicle_wince_fix_timeout_cb(), vehicle_wince_io(), vehicle_wince_methods, vehicle_wince_open(), and vehicle_wince_sat_methods.
Referenced by plugin_init().
vehicle_wince_open()
static int vehicle_wince_open (struct vehicle_priv * priv) static
References dbg, lvl_debug, vehicle_priv::source, and vehicle_wince_available_ports().
Referenced by vehicle_wince_io(), and vehicle_wince_new().
vehicle_wince_parse()
static int vehicle_wince_parse (struct vehicle_priv * priv, char * buffer) static
References attr_position_valid_invalid, attr_position_valid_valid, gps_sat::azimuth, vehicle_priv::buffer, vehicle_priv::checksum_ignore, vehicle_priv::current, vehicle_priv::current_count, dbg, vehicle_priv::direction, gps_sat::elevation, vehicle_priv::fixday, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, coord_geo::lat, lat, coord_geo::lng, lvl_debug, lvl_error, lvl_info, vehicle_priv::magnetic_direction, vehicle_priv::next, vehicle_priv::next_count, vehicle_priv::nmea_data, vehicle_priv::nmea_data_buf, p, gps_sat::prn, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, gps_sat::snr, vehicle_priv::speed, vehicle_priv::status, vehicle_priv::valid, and vehicle_wince_restart_fix_timeout().
Referenced by vehicle_wince_io().
vehicle_wince_position_attr_get()
static int vehicle_wince_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Retrieves a vehicle attribute.
Parameters
priv vehicle_priv structure for the vehicle
type The attribute type to retrieve
attr Points to an attr structure that will receive the attribute data
Returns
True for success, false for failure
References attr::coord_geo, vehicle_priv::current_count, dbg, vehicle_priv::direction, vehicle_priv::fixday, vehicle_priv::fixiso8601, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, item::id_lo, attr::item, lvl_debug, vehicle_priv::magnetic_direction, vehicle_priv::nmea_data, attr::num, attr::numd, vehicle_priv::sat_item, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, vehicle_priv::speed, vehicle_priv::status, attr::str, type, attr::type, attr::u, and vehicle_priv::valid.
vehicle_wince_restart_fix_timeout()
static void vehicle_wince_restart_fix_timeout (struct vehicle_priv * priv) static
Cancel previous fix timeout event and add a new one.
Parameters
priv Pointer on the private data of the plugin
References vehicle_priv::cb_fix_timeout, vehicle_priv::ev_fix_timeout, event_add_timeout(), and event_remove_timeout().
Referenced by vehicle_wince_parse().
vehicle_wince_sat_attr_get()
static int vehicle_wince_sat_attr_get (void * priv_data, enum attr_type type, struct attr * attr) static
References gps_sat::azimuth, vehicle_priv::current, vehicle_priv::current_count, gps_sat::elevation, item::id_lo, attr::num, gps_sat::prn, vehicle_priv::sat_item, gps_sat::snr, type, attr::type, and attr::u.
wince_reader_thread()
static DWORD WINAPI wince_reader_thread (LPVOID lParam) static
References buffer_size, bytes_read, dbg, event_call_callback(), vehicle_priv::file_type, file_type_file, vehicle_priv::has_data, initDevice(), vehicle_priv::is_running, vehicle_priv::lock, lvl_debug, lvl_error, vehicle_priv::m_hGPSDevice, vehicle_priv::priv_cbl, vehicle_priv::read_buffer, vehicle_priv::read_buffer_pos, vehicle_priv::source, vehicle_priv::status, and vehicle_priv::thread_up.
Referenced by vehicle_wince_enable_watch().
Variable Documentation
_convert
char* _convert = NULL
_wconvert
wchar_t* _wconvert = NULL
baudrate
int vehicle_priv::baudrate
BthSetMode
PFN_BthSetMode vehicle_priv::BthSetMode
Referenced by initBth(), and vehicle_wince_destroy().
buffer_size
int buffer_size = 1024 static
Referenced by read_win32(), vehicle_wince_io(), vehicle_wince_new(), and wince_reader_thread().
has_data
int vehicle_priv::has_data
Referenced by read_win32(), and wince_reader_thread().
hBthDll
HMODULE vehicle_priv::hBthDll
Referenced by initBth(), and vehicle_wince_destroy().
is_running
int vehicle_priv::is_running
Referenced by initDevice(), vehicle_wince_disable_watch(), vehicle_wince_enable_watch(), and wince_reader_thread().
lock
GMutex vehicle_priv::lock
Referenced by read_win32(), vehicle_wince_enable_watch(), and wince_reader_thread().
m_dwGPSThread
DWORD vehicle_priv::m_dwGPSThread
Referenced by vehicle_wince_enable_watch().
m_hGPSDevice
HANDLE vehicle_priv::m_hGPSDevice
Referenced by initDevice(), and wince_reader_thread().
m_hGPSThread
HANDLE vehicle_priv::m_hGPSThread
Referenced by vehicle_wince_disable_watch(), and vehicle_wince_enable_watch().
priv_cbl
struct callback_list* vehicle_priv::priv_cbl
Referenced by vehicle_wince_new(), and wince_reader_thread().
read_buffer
char* vehicle_priv::read_buffer
Referenced by read_win32(), vehicle_wince_destroy(), vehicle_wince_new(), and wince_reader_thread().
read_buffer_pos
int vehicle_priv::read_buffer_pos
Referenced by read_win32(), and wince_reader_thread().
thread_up
int vehicle_priv::thread_up
Referenced by initDevice(), vehicle_wince_disable_watch(), and wince_reader_thread().
vehicle_wince_methods
struct vehicle_methods vehicle_wince_methods
Initial value:
= {
    vehicle_wince_destroy,
    vehicle_wince_position_attr_get,
    NULL,
}
Referenced by vehicle_wince_new().
vehicle_wince_sat_methods
struct item_methods vehicle_wince_sat_methods static
Initial value:
= {
    NULL,
    NULL,
    NULL,
    vehicle_wince_sat_attr_get,
    NULL,
    NULL,
    NULL,
    NULL,
}
Referenced by vehicle_wince_new().