navit: Vehicle Null
Vehicle Null
Plugins » vehicle plugins
A dummy Vehicle to have a null movement.
Data Structures
struct vehicle_priv
Functions
static void vehicle_null_destroy (struct vehicle_priv *priv)
Free the null_vehicle.
static int vehicle_null_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Provide the outside with information.
static int vehicle_null_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_null_new_null (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Create null_vehicle.
void plugin_init (void)
register vehicle_null
Variables
int vehicle_priv::have_coords
struct vehicle_methods vehicle_null_methods
Detailed Description
A dummy Vehicle to have a null movement.
Function Documentation
plugin_init()
void plugin_init (void)
register vehicle_null
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_null_new_null().
vehicle_null_destroy()
static void vehicle_null_destroy (struct vehicle_priv * priv) static
Free the null_vehicle.
Parameters
priv
Returns
nothing
References dbg, and lvl_debug.
vehicle_null_new_null()
static struct vehicle_priv* vehicle_null_new_null (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Create null_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References vehicle_priv::cbl, dbg, lvl_debug, and vehicle_null_methods.
Referenced by plugin_init().
vehicle_null_position_attr_get()
static int vehicle_null_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Provide the outside with information.
Parameters
priv
type TODO: What can this be?
attr
Returns
true/false
References attr_to_name(), attr::coord_geo, dbg, vehicle_priv::direction, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::have_coords, vehicle_priv::height, lvl_debug, attr::numd, vehicle_priv::radius, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
vehicle_null_set_attr()
static int vehicle_null_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References callback_list_call_attr_0, vehicle_priv::cbl, attr::coord_geo, vehicle_priv::direction, vehicle_priv::geo, vehicle_priv::have_coords, attr::numd, vehicle_priv::speed, attr::type, and attr::u.
Variable Documentation
have_coords
int vehicle_priv::have_coords
Referenced by QNavitGeoReceiver::positionUpdated(), vehicle_null_position_attr_get(), vehicle_null_set_attr(), vehicle_qt5_position_attr_get(), and vehicle_qt5_set_attr().
vehicle_null_methods
struct vehicle_methods vehicle_null_methods
Initial value:
= {
    vehicle_null_destroy,
    vehicle_null_position_attr_get,
    vehicle_null_set_attr,
}
Referenced by vehicle_null_new_null().