navit: Vehicle gypsy
Vehicle gypsy
Plugins » vehicle plugins
The Vehicle to gain position data from gypsy. gypsy uses dbus signals Tim Niemeyer reddo.nosp@m.g@ma.nosp@m.sters.nosp@m.word.nosp@m..de
Data Structures
struct vehicle_priv
Macros
#define DEFAULT_RETRY_INTERVAL 10
#define MIN_RETRY_INTERVAL 1
Functions
static void vehicle_gypsy_fixstatus_changed (GypsyDevice *device, gint fixstatus, gpointer userdata)
When the fixstatus has changed, this function get called.
static void vehicle_gypsy_position_changed (GypsyPosition *position, GypsyPositionFields fields_set, int timestamp, double latitude, double longitude, double altitude, gpointer userdata)
When the position has changed, this function get called.
static void vehicle_gypsy_satellite_changed (GypsySatellite *satellite, GPtrArray *satellites, gpointer userdata)
Everytime any Sat-Details are changed, this function get called.
static void vehicle_gypsy_course_changed (GypsyCourse *course, GypsyCourseFields fields, int timestamp, double speed, double direction, double climb, gpointer userdata)
When the course or speed has changed, this function get called.
static gboolean vehicle_gypsy_try_open (gpointer *data)
Attempt to open the gypsy device.
static void vehicle_gypsy_open (struct vehicle_priv *priv)
Open a connection to gypsy. Will re-try the connection if it fails.
static void vehicle_gypsy_close (struct vehicle_priv *priv)
Stop retry timer; Free alloced memory.
static void vehicle_gypsy_destroy (struct vehicle_priv *priv)
Free the gypsy_vehicle.
static int vehicle_gypsy_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Provide the outside with information.
static struct vehicle_priv * vehicle_gypsy_new_gypsy (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Create gypsy_vehicle.
void plugin_init (void)
register vehicle_gypsy
Variables
GypsyControl * vehicle_priv::control
GypsyPosition * vehicle_priv::position
GypsyDevice * vehicle_priv::device
GypsyCourse * vehicle_priv::course
GypsySatellite * vehicle_priv::satellite
char * vehicle_priv::path
guint vehicle_priv::retry_timer
int vehicle_priv::have_cords
static struct vehicle_priv * vehicle_last
struct vehicle_methods vehicle_gypsy_methods
Detailed Description
The Vehicle to gain position data from gypsy. gypsy uses dbus signals Tim Niemeyer reddo.nosp@m.g@ma.nosp@m.sters.nosp@m.word.nosp@m..de
Date
2008-2009
Macro Definition Documentation
DEFAULT_RETRY_INTERVAL
#define DEFAULT_RETRY_INTERVAL 10
Referenced by vehicle_gypsy_new_gypsy().
MIN_RETRY_INTERVAL
#define MIN_RETRY_INTERVAL 1
Referenced by vehicle_gypsy_new_gypsy().
Function Documentation
plugin_init()
void plugin_init (void)
register vehicle_gypsy
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_gypsy_new_gypsy().
vehicle_gypsy_close()
static void vehicle_gypsy_close (struct vehicle_priv * priv) static
Stop retry timer; Free alloced memory.
Parameters
priv
Returns
nothing
References vehicle_priv::control, vehicle_priv::course, vehicle_priv::device, vehicle_priv::path, vehicle_priv::position, vehicle_priv::retry_timer, and vehicle_priv::satellite.
Referenced by vehicle_gypsy_destroy().
vehicle_gypsy_course_changed()
static void vehicle_gypsy_course_changed (GypsyCourse * course, GypsyCourseFields fields, int timestamp, double speed, double direction, double climb, gpointer userdata) static
When the course or speed has changed, this function get called.
Only speed and direction are used!
If we get any new information, we have to call the global callback.
Parameters
course The GypsyCourse
fields Bitmask indicating what field was set
timestamp the time since Unix Epoch
speed
direction
climb
userdata
Returns
nothing
References callback_list_call_attr_0, vehicle_priv::cb, vehicle_priv::cbl, vehicle_priv::direction, vehicle_priv::speed, and vehicle_last.
Referenced by vehicle_gypsy_try_open().
vehicle_gypsy_destroy()
static void vehicle_gypsy_destroy (struct vehicle_priv * priv) static
Free the gypsy_vehicle.
Parameters
priv
Returns
nothing
References vehicle_priv::source, and vehicle_gypsy_close().
vehicle_gypsy_fixstatus_changed()
static void vehicle_gypsy_fixstatus_changed (GypsyDevice * device, gint fixstatus, gpointer userdata) static
When the fixstatus has changed, this function get called.
fixstatus can be one of this: GYPSY_DEVICE_FIX_STATUS_INVALID = 0 GYPSY_DEVICE_FIX_STATUS_NONE = 1 GYPSY_DEVICE_FIX_STATUS_2D = 2 GYPSY_DEVICE_FIX_STATUS_3D = 3
Anytime this functions get called, we have to call the global callback.
Parameters
device The GypsyDevice
fixstatus The fisstatus 0, 1, 2 or 3
userdata
Returns
nothing
References callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::fix_type, and vehicle_last.
Referenced by vehicle_gypsy_try_open().
vehicle_gypsy_new_gypsy()
static struct vehicle_priv* vehicle_gypsy_new_gypsy (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Create gypsy_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References attr_search(), vehicle_priv::attrs, vehicle_priv::cbl, eval::conn, dbg, DEFAULT_RETRY_INTERVAL, vehicle_priv::have_cords, lvl_debug, lvl_error, MIN_RETRY_INTERVAL, attr::num, vehicle_priv::path, vehicle_priv::retry_interval, vehicle_priv::source, attr::str, attr::u, vehicle_gypsy_methods, and vehicle_gypsy_open().
Referenced by plugin_init().
vehicle_gypsy_open()
static void vehicle_gypsy_open (struct vehicle_priv * priv) static
Open a connection to gypsy. Will re-try the connection if it fails.
Parameters
priv
Returns
nothing
References vehicle_priv::retry_timer, and vehicle_gypsy_try_open().
Referenced by vehicle_gypsy_new_gypsy().
vehicle_gypsy_position_attr_get()
static int vehicle_gypsy_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Provide the outside with information.
Parameters
priv
type TODO: What can this be?
attr
Returns
true/false
References active, attr_search(), vehicle_priv::attrs, attr::coord_geo, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::have_cords, vehicle_priv::height, attr::num, attr::numd, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
vehicle_gypsy_position_changed()
static void vehicle_gypsy_position_changed (GypsyPosition * position, GypsyPositionFields fields_set, int timestamp, double latitude, double longitude, double altitude, gpointer userdata) static
When the position has changed, this function get called.
The fields_set can hold: GYPSY_POSITION_FIELDS_NONE = 1 << 0, GYPSY_POSITION_FIELDS_LATITUDE = 1 << 1, GYPSY_POSITION_FIELDS_LONGITUDE = 1 << 2, GYPSY_POSITION_FIELDS_ALTITUDE = 1 << 3
If we get any new information, we have to call the global callback.
Parameters
position The GypsyPosition
fields_set Bitmask indicating what field was set
timestamp the time since Unix Epoch
latitude
longitude
altitude
userdata
Returns
nothing
References vehicle_priv::altitude, callback_list_call_attr_0, vehicle_priv::cb, vehicle_priv::cbl, vehicle_priv::fix_time, vehicle_priv::geo, vehicle_priv::have_cords, vehicle_priv::height, coord_geo::lat, coord_geo::lng, and vehicle_last.
Referenced by vehicle_gypsy_try_open().
vehicle_gypsy_satellite_changed()
static void vehicle_gypsy_satellite_changed (GypsySatellite * satellite, GPtrArray * satellites, gpointer userdata) static
Everytime any Sat-Details are changed, this function get called.
Going through all Sats, counting those wich are in use.
Anytime this functions get called, we have to call the global callback.
Parameters
satellite The GypsySatellite
satellites An GPtrArray wich hold information of all sats
userdata
Returns
nothing
References callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::sats, vehicle_priv::sats_used, and vehicle_last.
Referenced by vehicle_gypsy_try_open().
vehicle_gypsy_try_open()
static gboolean vehicle_gypsy_try_open (gpointer * data) static
Attempt to open the gypsy device.
Tells gypsy wich functions to call when anything occours.
Parameters
data
Returns
TRUE to try again; FALSE if retry not required
References vehicle_priv::control, vehicle_priv::course, dbg, vehicle_priv::device, lvl_debug, vehicle_priv::path, vehicle_priv::position, vehicle_priv::satellite, vehicle_priv::source, vehicle_gypsy_course_changed(), vehicle_gypsy_fixstatus_changed(), vehicle_gypsy_position_changed(), vehicle_gypsy_satellite_changed(), and vehicle_last.
Referenced by vehicle_gypsy_open().
Variable Documentation
control
GypsyControl* vehicle_priv::control
Referenced by vehicle_gypsy_close(), vehicle_gypsy_try_open(), vehicle_maemo_destroy(), and vehicle_maemo_open().
course
GypsyCourse* vehicle_priv::course
Referenced by vehicle_gypsy_close(), and vehicle_gypsy_try_open().
device
GypsyDevice* vehicle_priv::device
Referenced by vehicle_gypsy_close(), vehicle_gypsy_try_open(), vehicle_maemo_destroy(), vehicle_maemo_open(), and vehicle_webos_bt_gap_callback().
have_cords
int vehicle_priv::have_cords
Referenced by vehicle_gypsy_new_gypsy(), vehicle_gypsy_position_attr_get(), and vehicle_gypsy_position_changed().
path
char* vehicle_priv::path
Referenced by vehicle_gypsy_close(), vehicle_gypsy_new_gypsy(), and vehicle_gypsy_try_open().
position
GypsyPosition* vehicle_priv::position
Referenced by vehicle_gypsy_close(), and vehicle_gypsy_try_open().
retry_timer
guint vehicle_priv::retry_timer
Referenced by vehicle_gypsy_close(), and vehicle_gypsy_open().
satellite
GypsySatellite* vehicle_priv::satellite
Referenced by vehicle_gypsy_close(), and vehicle_gypsy_try_open().
vehicle_gypsy_methods
struct vehicle_methods vehicle_gypsy_methods
Initial value:
= {
    vehicle_gypsy_destroy,
    vehicle_gypsy_position_attr_get,
}
Referenced by vehicle_gypsy_new_gypsy().
vehicle_last
struct vehicle_priv * vehicle_last static
Referenced by vehicle_gypsy_course_changed(), vehicle_gypsy_fixstatus_changed(), vehicle_gypsy_position_changed(), vehicle_gypsy_satellite_changed(), and vehicle_gypsy_try_open().