navit: Vehicle Gpsd DBus
Vehicle Gpsd DBus
Plugins » vehicle plugins
The Vehicle to gain position data from Gpsd over DBus.
Data Structures
struct vehicle_priv
Functions
static void vehicle_gpsd_dbus_close (struct vehicle_priv *priv)
static DBusHandlerResult vehicle_gpsd_dbus_filter (DBusConnection *connection, DBusMessage *message, void *user_data)
static int vehicle_gpsd_dbus_open (struct vehicle_priv *priv)
static void vehicle_gpsd_dbus_destroy (struct vehicle_priv *priv)
static int vehicle_gpsd_dbus_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_gpsd_dbus_set_attr_do (struct vehicle_priv *priv, struct attr *attr, int init)
static int vehicle_gpsd_dbus_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_gpsd_dbus_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
static char * vehicle_gpsd_dbus_prefix ="gpsd_dbus:"
char * vehicle_priv::address
int vehicle_priv::flags
DBusConnection * vehicle_priv::connection
double vehicle_priv::time
double vehicle_priv::track
double vehicle_priv::altitude
static struct vehicle_methods vehicle_gpsd_methods
Detailed Description
The Vehicle to gain position data from Gpsd over DBus.
Function Documentation
plugin_init()
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
This function is called once on startup.
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
The plugin entry point.
register vehicle_gypsy
Returns
nothing
References dbg, lvl_debug, and vehicle_gpsd_dbus_new().
vehicle_gpsd_dbus_close()
static void vehicle_gpsd_dbus_close (struct vehicle_priv * priv) static
References vehicle_priv::connection.
Referenced by vehicle_gpsd_dbus_destroy(), vehicle_gpsd_dbus_open(), and vehicle_gpsd_dbus_set_attr_do().
vehicle_gpsd_dbus_destroy()
static void vehicle_gpsd_dbus_destroy (struct vehicle_priv * priv) static
References vehicle_priv::source, and vehicle_gpsd_dbus_close().
vehicle_gpsd_dbus_filter()
static DBusHandlerResult vehicle_gpsd_dbus_filter (DBusConnection * connection, DBusMessage * message, void * user_data) static
References vehicle_priv::altitude, callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::fix_time, vehicle_priv::flags, vehicle_priv::geo, coord_geo::lat, coord_geo::lng, vehicle_priv::speed, vehicle_priv::time, and vehicle_priv::track.
Referenced by vehicle_gpsd_dbus_open().
vehicle_gpsd_dbus_new()
static struct vehicle_priv* vehicle_gpsd_dbus_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References vehicle_priv::attrs, cbl, vehicle_priv::cbl, vehicle_gpsd_dbus_open(), vehicle_gpsd_dbus_set_attr_do(), and vehicle_gpsd_methods.
Referenced by plugin_init().
vehicle_gpsd_dbus_open()
static int vehicle_gpsd_dbus_open (struct vehicle_priv * priv) static
References vehicle_priv::address, vehicle_priv::connection, dbg, lvl_error, vehicle_gpsd_dbus_close(), and vehicle_gpsd_dbus_filter().
Referenced by vehicle_gpsd_dbus_new(), and vehicle_gpsd_dbus_set_attr_do().
vehicle_gpsd_dbus_position_attr_get()
static int vehicle_gpsd_dbus_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References vehicle_priv::altitude, attr::coord_geo, vehicle_priv::fix_time, vehicle_priv::fixiso8601, vehicle_priv::geo, attr::numd, vehicle_priv::speed, attr::str, vehicle_priv::track, attr::type, type, and attr::u.
vehicle_gpsd_dbus_set_attr()
static int vehicle_gpsd_dbus_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References vehicle_gpsd_dbus_set_attr_do().
vehicle_gpsd_dbus_set_attr_do()
static int vehicle_gpsd_dbus_set_attr_do (struct vehicle_priv * priv, struct attr * attr, int init) static
References vehicle_priv::address, dbg, vehicle_priv::flags, lvl_error, attr::num, vehicle_priv::source, attr::str, attr::type, attr::u, vehicle_gpsd_dbus_close(), vehicle_gpsd_dbus_open(), and vehicle_gpsd_dbus_prefix.
Referenced by vehicle_gpsd_dbus_new(), and vehicle_gpsd_dbus_set_attr().
Variable Documentation
address
char* vehicle_priv::address
Referenced by vehicle_gpsd_dbus_open(), and vehicle_gpsd_dbus_set_attr_do().
altitude
double vehicle_priv::altitude
Referenced by print_location(), vehicle_gpsd_dbus_filter(), vehicle_gpsd_dbus_position_attr_get(), and vehicle_gypsy_position_changed().
connection
DBusConnection* vehicle_priv::connection
Referenced by vehicle_gpsd_dbus_close(), and vehicle_gpsd_dbus_open().
flags
int vehicle_priv::flags
Referenced by vehicle_gpsd_dbus_filter(), and vehicle_gpsd_dbus_set_attr_do().
time
double vehicle_priv::time
track
double vehicle_priv::track
Referenced by vehicle_gpsd_dbus_filter(), and vehicle_gpsd_dbus_position_attr_get().
vehicle_gpsd_dbus_prefix
char* vehicle_gpsd_dbus_prefix ="gpsd_dbus:" static
Referenced by vehicle_gpsd_dbus_set_attr_do().
vehicle_gpsd_methods
struct vehicle_methods vehicle_gpsd_methods static
Initial value:
= {
    vehicle_gpsd_dbus_destroy,
    vehicle_gpsd_dbus_position_attr_get,
    vehicle_gpsd_dbus_set_attr,
}
Referenced by vehicle_gpsd_dbus_new().