navit: support/glib/gslice.c File Reference
gslice.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "gmem.h"
#include "gthreadprivate.h"
#include "glib.h"
#include "galias.h"
#include <stdio.h>
#include "galiasdef.c"
Data Structures
struct _ChunkLink
struct _SlabInfo
struct Magazine
struct ThreadMemory
struct SliceConfig
struct Allocator
struct SmcEntry
struct SmcBranch
Macros
#define LARGEALIGNMENT (256)
#define P2ALIGNMENT (2 * sizeof (gsize)) /* fits 2 pointers (assumed to be 2 * GLIB_SIZEOF_SIZE_T below) */
#define ALIGN(size, base) ((base) * (gsize) (((size) + (base) - 1) / (base)))
#define NATIVE_MALLOC_PADDING 0 /* per-page padding left for native malloc(3) see [1] */
#define SLAB_INFO_SIZE P2ALIGN (sizeof (SlabInfo) + NATIVE_MALLOC_PADDING)
#define MAX_MAGAZINE_SIZE (256) /* see [3] and allocator_get_magazine_threshold() for this */
#define MIN_MAGAZINE_SIZE (4)
#define MAX_STAMP_COUNTER (7) /* distributes the load of gettimeofday() */
#define MAX_SLAB_CHUNK_SIZE(al) (((al)->max_page_size - SLAB_INFO_SIZE) / 8) /* we want at last 8 chunks per page, see [4] */
#define MAX_SLAB_INDEX(al) (SLAB_INDEX (al, MAX_SLAB_CHUNK_SIZE (al)) + 1)
#define SLAB_INDEX(al, asize) ((asize) / P2ALIGNMENT - 1) /* asize must be P2ALIGNMENT aligned */
#define SLAB_CHUNK_SIZE(al, ix) (((ix) + 1) * P2ALIGNMENT)
#define SLAB_BPAGE_SIZE(al, csz) (8 * (csz) + SLAB_INFO_SIZE)
#define P2ALIGN(size) ALIGN (size, P2ALIGNMENT)
#define mem_assert(cond) do { if (G_LIKELY (cond)) ; else mem_error ("assertion failed: %s", #cond); } while (0)
#define magazine_chain_prev(mc) ((mc)->data)
#define magazine_chain_stamp(mc) ((mc)->next->data)
#define magazine_chain_uint_stamp(mc) GPOINTER_TO_UINT ((mc)->next->data)
#define magazine_chain_next(mc) ((mc)->next->next->data)
#define magazine_chain_count(mc) ((mc)->next->next->next->data)
#define SMC_TRUNK_COUNT (4093 /* 16381 */) /* prime, to distribute trunk collisions (big, allocated just once) */
#define SMC_BRANCH_COUNT (511) /* prime, to distribute branch collisions */
#define SMC_TRUNK_EXTENT (SMC_BRANCH_COUNT * 2039) /* key adress space per trunk, should distribute uniformly across BRANCH_COUNT */
#define SMC_TRUNK_HASH(k) ((k / SMC_TRUNK_EXTENT) % SMC_TRUNK_COUNT) /* generate new trunk hash per megabyte (roughly) */
#define SMC_BRANCH_HASH(k) (k % SMC_BRANCH_COUNT)
#define __G_SLICE_C__
Typedefs
typedef struct _ChunkLink ChunkLink
typedef struct _SlabInfo SlabInfo
typedef struct _CachedMagazine CachedMagazine
typedef size_t SmcKType
typedef size_t SmcVType
Functions
static void mem_error (const char *format,...) G_GNUC_PRINTF(1
static gpointer slab_allocator_alloc_chunk (gsize chunk_size)
static void slab_allocator_free_chunk (gsize chunk_size, gpointer mem)
static void private_thread_memory_cleanup (gpointer data)
static gpointer allocator_memalign (gsize alignment, gsize memsize)
static void allocator_memfree (gsize memsize, gpointer mem)
static void magazine_cache_update_stamp (void)
static gsize allocator_get_magazine_threshold (Allocator *allocator, guint ix)
static void smc_notify_alloc (void *pointer, size_t size)
static int smc_notify_free (void *pointer, size_t size)
void g_slice_set_config (GSliceConfig ckey, gint64 value)
gint64 g_slice_get_config (GSliceConfig ckey)
gint64 * g_slice_get_config_state (GSliceConfig ckey, gint64 address, guint *n_values)
static void slice_config_init (SliceConfig *config)
static void g_slice_init_nomessage (void)
static guint allocator_categorize (gsize aligned_chunk_size)
void _g_slice_thread_init_nomessage (void)
static void g_mutex_lock_a (GMutex *mutex, guint *contention_counter)
static ThreadMemory * thread_memory_from_self (void)
static ChunkLink * magazine_chain_pop_head (ChunkLink **magazine_chunks)
static ChunkLink * magazine_chain_prepare_fields (ChunkLink *magazine_chunks)
static void magazine_cache_trim (Allocator *allocator, guint ix, guint stamp)
static void magazine_cache_push_magazine (guint ix, ChunkLink *magazine_chunks, gsize count)
static ChunkLink * magazine_cache_pop_magazine (guint ix, gsize *countp)
static void thread_memory_magazine1_reload (ThreadMemory *tmem, guint ix)
static void thread_memory_magazine2_unload (ThreadMemory *tmem, guint ix)
static void thread_memory_swap_magazines (ThreadMemory *tmem, guint ix)
static gboolean thread_memory_magazine1_is_empty (ThreadMemory *tmem, guint ix)
static gboolean thread_memory_magazine2_is_full (ThreadMemory *tmem, guint ix)
static gpointer thread_memory_magazine1_alloc (ThreadMemory *tmem, guint ix)
static void thread_memory_magazine2_free (ThreadMemory *tmem, guint ix, gpointer mem)
gpointer g_slice_alloc (gsize mem_size)
gpointer g_slice_alloc0 (gsize mem_size)
gpointer g_slice_copy (gsize mem_size, gconstpointer mem_block)
void g_slice_free1 (gsize mem_size, gpointer mem_block)
void g_slice_free_chain_with_offset (gsize mem_size, gpointer mem_chain, gsize next_offset)
static void allocator_slab_stack_push (Allocator *allocator, guint ix, SlabInfo *sinfo)
static gsize allocator_aligned_page_size (Allocator *allocator, gsize n_bytes)
static void allocator_add_slab (Allocator *allocator, guint ix, gsize chunk_size)
static void smc_tree_insert (SmcKType key, SmcVType value)
static gboolean smc_tree_lookup (SmcKType key, SmcVType *value_p)
static gboolean smc_tree_remove (SmcKType key)
static void smc_tree_abort (int errval)
static SmcEntry * smc_tree_branch_grow_L (SmcBranch *branch, unsigned int index)
static SmcEntry * smc_tree_branch_lookup_nearest_L (SmcBranch *branch, SmcKType key)
Variables
static GPrivate * private_thread_memory = NULL
static gsize sys_page_size = 0
static gsize sys_valignment = ((32*1024*1024))
static guint8 * virtual_mem = 0
static Allocator allocator [1] = { { 0, }, }
static SliceConfig slice_config
static GMutex * smc_tree_mutex = NULL
static GTrashStack * compat_valloc_trash = NULL
static SmcBranch ** smc_tree_root = NULL
Macro Definition Documentation
#define __G_SLICE_C__
#define ALIGN (size, base) ((base) * (gsize) (((size) + (base) - 1) / (base)))
Referenced by allocator_memalign().
#define LARGEALIGNMENT (256)
Referenced by g_slice_init_nomessage().
#define magazine_chain_count (mc) ((mc)->next->next->next->data)
Referenced by magazine_cache_pop_magazine(), magazine_cache_push_magazine(), and magazine_cache_trim().
#define magazine_chain_next (mc) ((mc)->next->next->data)
Referenced by magazine_cache_pop_magazine(), magazine_cache_push_magazine(), and magazine_cache_trim().
#define magazine_chain_prev (mc) ((mc)->data)
Referenced by magazine_cache_pop_magazine(), magazine_cache_push_magazine(), and magazine_cache_trim().
#define magazine_chain_stamp (mc) ((mc)->next->data)
Referenced by magazine_cache_pop_magazine(), magazine_cache_push_magazine(), and magazine_cache_trim().
#define magazine_chain_uint_stamp (mc) GPOINTER_TO_UINT ((mc)->next->data)
Referenced by magazine_cache_trim().
#define MAX_MAGAZINE_SIZE (256) /* see [3] and allocator_get_magazine_threshold() for this */
Referenced by g_mutex_lock_a().
#define MAX_SLAB_CHUNK_SIZE (al) (((al)->max_page_size - SLAB_INFO_SIZE) / 8) /* we want at last 8 chunks per page, see [4] */
Referenced by allocator_categorize(), and g_slice_init_nomessage().
#define MAX_SLAB_INDEX (al) (SLAB_INDEX (al, MAX_SLAB_CHUNK_SIZE (al)) + 1)
Referenced by g_slice_get_config(), g_slice_init_nomessage(), private_thread_memory_cleanup(), and thread_memory_from_self().
#define MAX_STAMP_COUNTER (7) /* distributes the load of gettimeofday() */
Referenced by g_slice_init_nomessage(), and magazine_cache_update_stamp().
#define mem_assert (cond) do { if (G_LIKELY (cond)) ; else mem_error ("assertion failed: %s", #cond); } while (0)
Referenced by allocator_add_slab(), allocator_memalign(), allocator_memfree(), g_slice_init_nomessage(), slab_allocator_free_chunk(), smc_tree_branch_grow_L(), and thread_memory_magazine1_reload().
#define MIN_MAGAZINE_SIZE (4)
Referenced by allocator_get_magazine_threshold(), g_slice_init_nomessage(), and private_thread_memory_cleanup().
#define NATIVE_MALLOC_PADDING 0 /* per-page padding left for native malloc(3) see [1] */
Referenced by allocator_add_slab().
#define P2ALIGN (size) ALIGN (size, P2ALIGNMENT)
Referenced by g_slice_alloc(), g_slice_free1(), and g_slice_free_chain_with_offset().
#define P2ALIGNMENT (2 * sizeof (gsize)) /* fits 2 pointers (assumed to be 2 * GLIB_SIZEOF_SIZE_T below) */
Referenced by allocator_add_slab().
#define SLAB_BPAGE_SIZE (al, csz) (8 * (csz) + SLAB_INFO_SIZE)
Referenced by allocator_add_slab(), and slab_allocator_free_chunk().
#define SLAB_CHUNK_SIZE (al, ix) (((ix) + 1) * P2ALIGNMENT)
Referenced by allocator_get_magazine_threshold(), g_slice_get_config_state(), magazine_cache_pop_magazine(), magazine_cache_trim(), and private_thread_memory_cleanup().
#define SLAB_INDEX (al, asize) ((asize) / P2ALIGNMENT - 1) /* asize must be P2ALIGNMENT aligned */
Referenced by g_slice_alloc(), g_slice_free1(), g_slice_free_chain_with_offset(), slab_allocator_alloc_chunk(), and slab_allocator_free_chunk().
#define SLAB_INFO_SIZE P2ALIGN (sizeof (SlabInfo) + NATIVE_MALLOC_PADDING)
Referenced by allocator_add_slab(), and slab_allocator_free_chunk().
#define SMC_BRANCH_COUNT (511) /* prime, to distribute branch collisions */
Referenced by smc_tree_insert().
#define SMC_BRANCH_HASH (k) (k % SMC_BRANCH_COUNT)
Referenced by smc_tree_insert(), smc_tree_lookup(), and smc_tree_remove().
#define SMC_TRUNK_COUNT (4093 /* 16381 */) /* prime, to distribute trunk collisions (big, allocated just once) */
Referenced by smc_tree_insert().
#define SMC_TRUNK_EXTENT (SMC_BRANCH_COUNT * 2039) /* key adress space per trunk, should distribute uniformly across BRANCH_COUNT */
#define SMC_TRUNK_HASH (k) ((k / SMC_TRUNK_EXTENT) % SMC_TRUNK_COUNT) /* generate new trunk hash per megabyte (roughly) */
Referenced by smc_tree_insert(), smc_tree_lookup(), and smc_tree_remove().
Typedef Documentation
typedef struct _CachedMagazine CachedMagazine
typedef struct _ChunkLink ChunkLink
typedef struct _SlabInfo SlabInfo
typedef size_t SmcKType
typedef size_t SmcVType
Function Documentation
void _g_slice_thread_init_nomessage (void)
References Allocator::config, SliceConfig::debug_blocks, g_mutex_new, g_private_new, g_slice_init_nomessage(), Allocator::magazine_mutex, private_thread_memory_cleanup(), and Allocator::slab_mutex.
Referenced by main(), and main_real().
static void allocator_add_slab (Allocator * allocator, guint ix, gsize chunk_size) static
References allocator_aligned_page_size(), allocator_memalign(), allocator_slab_stack_push(), chunk, _SlabInfo::chunks, Allocator::color_accu, SliceConfig::color_increment, Allocator::config, errno, gchar, i, mem_assert, mem_error(), _SlabInfo::n_allocated, NATIVE_MALLOC_PADDING, _ChunkLink::next, NULL, P2ALIGNMENT, SLAB_BPAGE_SIZE, SLAB_INFO_SIZE, and strerror().
Referenced by slab_allocator_alloc_chunk().
static gsize allocator_aligned_page_size (Allocator * allocator, gsize n_bytes) static
References g_bit_storage(), MAX, and Allocator::min_page_size.
Referenced by allocator_add_slab(), and slab_allocator_free_chunk().
static guint allocator_categorize (gsize aligned_chunk_size) inline static
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, Allocator::config, G_LIKELY, g_slice_init_nomessage(), and MAX_SLAB_CHUNK_SIZE.
Referenced by g_slice_alloc(), g_slice_free1(), and g_slice_free_chain_with_offset().
static gsize allocator_get_magazine_threshold (Allocator * allocator, guint ix) inline static
References Allocator::contention_counters, G_UNLIKELY, MAX, Allocator::max_page_size, MIN_MAGAZINE_SIZE, and SLAB_CHUNK_SIZE.
Referenced by g_slice_get_config_state(), magazine_cache_pop_magazine(), and thread_memory_magazine2_is_full().
static gpointer allocator_memalign (gsize alignment, gsize memsize) static
References ALIGN, ENOMEM, err(), errno, g_trash_stack_pop(), g_trash_stack_push(), i, mem_assert, NULL, and sys_page_size.
Referenced by allocator_add_slab().
static void allocator_memfree (gsize memsize, gpointer mem) static
References g_trash_stack_push(), and mem_assert.
Referenced by slab_allocator_free_chunk().
static void allocator_slab_stack_push (Allocator * allocator, guint ix, SlabInfo * sinfo) static
References _SlabInfo::next, next, _SlabInfo::prev, and Allocator::slab_stack.
Referenced by allocator_add_slab(), and slab_allocator_free_chunk().
static void g_mutex_lock_a (GMutex * mutex, guint * contention_counter) inline static
References FALSE, g_mutex_lock, g_mutex_trylock, MAX, MAX_MAGAZINE_SIZE, MIN, Allocator::mutex_counter, and TRUE.
Referenced by magazine_cache_pop_magazine().
gpointer g_slice_alloc (gsize mem_size)
References allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, G_LIKELY, g_malloc(), g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_alloc_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_alloc(), thread_memory_from_self(), thread_memory_magazine1_alloc(), thread_memory_magazine1_is_empty(), thread_memory_magazine1_reload(), and thread_memory_swap_magazines().
Referenced by g_mem_chunk_alloc(), g_slice_alloc0(), and g_slice_copy().
gpointer g_slice_alloc0 (gsize mem_size)
References g_slice_alloc().
Referenced by cache_entry_new(), cache_trim(), g_mem_chunk_alloc0(), and route_graph_add_segment().
gpointer g_slice_copy (gsize mem_size, gconstpointer mem_block)
References g_slice_alloc().
void g_slice_free1 (gsize mem_size, gpointer mem_block)
References abort(), allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, g_free(), G_LIKELY, g_mem_gc_friendly, g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_free_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_free(), thread_memory_from_self(), thread_memory_magazine2_free(), thread_memory_magazine2_is_full(), thread_memory_magazine2_unload(), and thread_memory_swap_magazines().
Referenced by cache_remove(), cache_trim(), g_mem_chunk_free(), and route_graph_free_segments().
void g_slice_free_chain_with_offset (gsize mem_size, gpointer mem_chain, gsize next_offset)
References abort(), allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, g_free(), G_LIKELY, g_mem_gc_friendly, g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_free_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_free(), thread_memory_from_self(), thread_memory_magazine2_free(), thread_memory_magazine2_is_full(), thread_memory_magazine2_unload(), and thread_memory_swap_magazines().
gint64 g_slice_get_config (GSliceConfig ckey)
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, SliceConfig::color_increment, G_SLICE_CONFIG_ALWAYS_MALLOC, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_CHUNK_SIZES, G_SLICE_CONFIG_COLOR_INCREMENT, G_SLICE_CONFIG_WORKING_SET_MSECS, MAX_SLAB_INDEX, and SliceConfig::working_set_msecs.
gint64* g_slice_get_config_state (GSliceConfig ckey, gint64 address, guint * n_values)
References allocator_get_magazine_threshold(), Allocator::contention_counters, g_memdup(), g_return_val_if_fail, G_SLICE_CONFIG_CONTENTION_COUNTER, gint64, i, NULL, and SLAB_CHUNK_SIZE.
static void g_slice_init_nomessage (void) static
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, Allocator::color_accu, Allocator::config, Allocator::contention_counters, g_new0, LARGEALIGNMENT, Allocator::last_stamp, magazine_cache_update_stamp(), Allocator::magazine_mutex, Allocator::magazines, MAX, Allocator::max_page_size, MAX_SLAB_CHUNK_SIZE, Allocator::max_slab_chunk_size_for_magazine_cache, MAX_SLAB_INDEX, MAX_STAMP_COUNTER, mem_assert, MIN, MIN_MAGAZINE_SIZE, Allocator::min_page_size, Allocator::mutex_counter, NULL, printf(), Allocator::slab_mutex, Allocator::slab_stack, slice_config_init(), Allocator::stamp_counter, and sys_page_size.
Referenced by _g_slice_thread_init_nomessage(), and allocator_categorize().
void g_slice_set_config (GSliceConfig ckey, gint64 value)
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, SliceConfig::color_increment, g_return_if_fail, G_SLICE_CONFIG_ALWAYS_MALLOC, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_COLOR_INCREMENT, G_SLICE_CONFIG_WORKING_SET_MSECS, value, and SliceConfig::working_set_msecs.
static ChunkLink* magazine_cache_pop_magazine (guint ix, gsize * countp) static
References allocator_get_magazine_threshold(), chunk, Allocator::contention_counters, _ChunkLink::data, g_mutex_lock, g_mutex_lock_a(), g_mutex_unlock, i, magazine_chain_count, magazine_chain_next, magazine_chain_prev, magazine_chain_stamp, Allocator::magazine_mutex, Allocator::magazines, _ChunkLink::next, next, NULL, slab_allocator_alloc_chunk(), SLAB_CHUNK_SIZE, and Allocator::slab_mutex.
Referenced by thread_memory_magazine1_reload().
static void magazine_cache_push_magazine (guint ix, ChunkLink * magazine_chunks, gsize count) static
References g_mutex_lock, GUINT_TO_POINTER, Allocator::last_stamp, magazine_cache_trim(), magazine_cache_update_stamp(), magazine_chain_count, magazine_chain_next, magazine_chain_prepare_fields(), magazine_chain_prev, magazine_chain_stamp, Allocator::magazine_mutex, Allocator::magazines, and next.
Referenced by private_thread_memory_cleanup(), and thread_memory_magazine2_unload().
static void magazine_cache_trim (Allocator * allocator, guint ix, guint stamp) static
References ABS, chunk, Allocator::config, g_mutex_lock, g_mutex_unlock, magazine_chain_count, magazine_chain_next, magazine_chain_pop_head(), magazine_chain_prev, magazine_chain_stamp, magazine_chain_uint_stamp, Allocator::magazine_mutex, Allocator::magazines, next, NULL, slab_allocator_free_chunk(), SLAB_CHUNK_SIZE, Allocator::slab_mutex, and SliceConfig::working_set_msecs.
Referenced by magazine_cache_push_magazine().
static void magazine_cache_update_stamp (void) inline static
References g_get_current_time(), Allocator::last_stamp, MAX_STAMP_COUNTER, Allocator::stamp_counter, _GTimeVal::tv_sec, and _GTimeVal::tv_usec.
Referenced by g_slice_init_nomessage(), and magazine_cache_push_magazine().
static ChunkLink* magazine_chain_pop_head (ChunkLink ** magazine_chunks) inline static
References chunk, G_UNLIKELY, and _ChunkLink::next.
Referenced by magazine_cache_trim(), magazine_chain_prepare_fields(), private_thread_memory_cleanup(), and thread_memory_magazine1_alloc().
static ChunkLink* magazine_chain_prepare_fields (ChunkLink * magazine_chunks) inline static
References magazine_chain_pop_head(), and _ChunkLink::next.
Referenced by magazine_cache_push_magazine().
static void mem_error (const char * format, ...) static
References abort(), fprintf(), g_get_prgname(), and vfprintf().
Referenced by allocator_add_slab(), and smc_tree_abort().
static void private_thread_memory_cleanup (gpointer data) static
References chunk, Magazine::chunks, Magazine::count, data, g_free(), g_mutex_lock, g_mutex_unlock, ThreadMemory::magazine1, ThreadMemory::magazine2, magazine_cache_push_magazine(), magazine_chain_pop_head(), MAX_SLAB_INDEX, MIN_MAGAZINE_SIZE, slab_allocator_free_chunk(), SLAB_CHUNK_SIZE, and Allocator::slab_mutex.
Referenced by _g_slice_thread_init_nomessage().
static gpointer slab_allocator_alloc_chunk (gsize chunk_size) static
References allocator_add_slab(), chunk, _SlabInfo::chunks, _SlabInfo::n_allocated, _ChunkLink::next, _SlabInfo::next, SLAB_INDEX, and Allocator::slab_stack.
Referenced by g_slice_alloc(), and magazine_cache_pop_magazine().
static void slab_allocator_free_chunk (gsize chunk_size, gpointer mem) static
References allocator_aligned_page_size(), allocator_memfree(), allocator_slab_stack_push(), chunk, _SlabInfo::chunks, mem_assert, _SlabInfo::n_allocated, _ChunkLink::next, _SlabInfo::next, next, NULL, _SlabInfo::prev, SLAB_BPAGE_SIZE, SLAB_INDEX, SLAB_INFO_SIZE, and Allocator::slab_stack.
Referenced by g_slice_free1(), g_slice_free_chain_with_offset(), magazine_cache_trim(), and private_thread_memory_cleanup().
static void slice_config_init (SliceConfig * config) static
References _g_getenv_nomalloc(), SliceConfig::always_malloc, SliceConfig::debug_blocks, G_N_ELEMENTS, g_parse_debug_string(), gchar, slice_config, and TRUE.
Referenced by g_slice_init_nomessage().
static void smc_notify_alloc (void * pointer, size_t size) static
References smc_tree_insert().
Referenced by g_slice_alloc().
static int smc_notify_free (void * pointer, size_t size) static
References fprintf(), G_GSIZE_FORMAT, smc_tree_lookup(), and smc_tree_remove().
Referenced by g_slice_free1(), and g_slice_free_chain_with_offset().
static void smc_tree_abort (int errval) static
References mem_error(), and strerror().
Referenced by smc_tree_branch_grow_L(), and smc_tree_insert().
static SmcEntry* smc_tree_branch_grow_L (SmcBranch * branch, unsigned int index) inline static
References SmcBranch::entries, errno, g_memmove, mem_assert, n_entries, SmcBranch::n_entries, and smc_tree_abort().
Referenced by smc_tree_insert().
static SmcEntry* smc_tree_branch_lookup_nearest_L (SmcBranch * branch, SmcKType key) inline static
References cmp(), SmcBranch::entries, i, SmcEntry::key, and SmcBranch::n_entries.
Referenced by smc_tree_insert(), smc_tree_lookup(), and smc_tree_remove().
static void smc_tree_insert (SmcKType key, SmcVType value) static
References calloc(), entries, errno, g_mutex_lock, g_mutex_unlock, key, SmcEntry::key, n_entries, SMC_BRANCH_COUNT, SMC_BRANCH_HASH, smc_tree_abort(), smc_tree_branch_grow_L(), smc_tree_branch_lookup_nearest_L(), SMC_TRUNK_COUNT, SMC_TRUNK_HASH, SmcEntry::value, and value.
Referenced by smc_notify_alloc().
static gboolean smc_tree_lookup (SmcKType key, SmcVType * value_p) static
References entries, FALSE, g_mutex_lock, g_mutex_unlock, SmcEntry::key, n_entries, NULL, SMC_BRANCH_HASH, smc_tree_branch_lookup_nearest_L(), SMC_TRUNK_HASH, TRUE, and SmcEntry::value.
Referenced by smc_notify_free().
static gboolean smc_tree_remove (SmcKType key) static
References SmcBranch::entries, entries, FALSE, g_memmove, g_mutex_lock, g_mutex_unlock, i, SmcEntry::key, n_entries, SmcBranch::n_entries, NULL, SMC_BRANCH_HASH, smc_tree_branch_lookup_nearest_L(), SMC_TRUNK_HASH, and TRUE.
Referenced by smc_notify_free().
static ThreadMemory* thread_memory_from_self (void) inline static
References g_malloc0(), g_mutex_lock, g_mutex_unlock, g_private_get, g_private_set, g_thread_supported, G_UNLIKELY, ThreadMemory::magazine1, ThreadMemory::magazine2, MAX_SLAB_INDEX, NULL, and Allocator::slab_mutex.
Referenced by g_slice_alloc(), g_slice_free1(), and g_slice_free_chain_with_offset().
static gpointer thread_memory_magazine1_alloc (ThreadMemory * tmem, guint ix) inline static
References chunk, Magazine::chunks, Magazine::count, G_LIKELY, ThreadMemory::magazine1, and magazine_chain_pop_head().
Referenced by g_slice_alloc().
static gboolean thread_memory_magazine1_is_empty (ThreadMemory * tmem, guint ix) inline static
References Magazine::chunks, ThreadMemory::magazine1, and NULL.
Referenced by g_slice_alloc().
static void thread_memory_magazine1_reload (ThreadMemory * tmem, guint ix) static
References Magazine::chunks, Magazine::count, ThreadMemory::magazine1, magazine_cache_pop_magazine(), mem_assert, and NULL.
Referenced by g_slice_alloc().
static void thread_memory_magazine2_free (ThreadMemory * tmem, guint ix, gpointer mem) inline static
References chunk, Magazine::chunks, Magazine::count, _ChunkLink::data, ThreadMemory::magazine2, _ChunkLink::next, and NULL.
Referenced by g_slice_free1(), and g_slice_free_chain_with_offset().
static gboolean thread_memory_magazine2_is_full (ThreadMemory * tmem, guint ix) inline static
References allocator_get_magazine_threshold(), Magazine::count, and ThreadMemory::magazine2.
Referenced by g_slice_free1(), and g_slice_free_chain_with_offset().
static void thread_memory_magazine2_unload (ThreadMemory * tmem, guint ix) static
References Magazine::chunks, Magazine::count, ThreadMemory::magazine2, magazine_cache_push_magazine(), and NULL.
Referenced by g_slice_free1(), and g_slice_free_chain_with_offset().
static void thread_memory_swap_magazines (ThreadMemory * tmem, guint ix) inline static
References ThreadMemory::magazine1, and ThreadMemory::magazine2.
Referenced by g_slice_alloc(), g_slice_free1(), and g_slice_free_chain_with_offset().
Variable Documentation
Allocator allocator[1] = { { 0, }, } static
GTrashStack* compat_valloc_trash = NULL static
GPrivate* private_thread_memory = NULL static
SliceConfig slice_config static
Initial value:
= {
  FALSE,
  FALSE,
  FALSE,
  15 * 1000,
  1,
}
Referenced by slice_config_init().
GMutex* smc_tree_mutex = NULL static
SmcBranch** smc_tree_root = NULL static
gsize sys_page_size = 0 static
Referenced by allocator_memalign(), and g_slice_init_nomessage().
gsize sys_valignment = ((32*1024*1024)) static
guint8* virtual_mem = 0 static