navit: support/glib/gslice.h File Reference
gslice.h File Reference
#include <glib/gtypes.h>
Macros
#define __G_SLICE_H__
#define g_slice_new(type) ((type*) g_slice_alloc (sizeof (type)))
#define g_slice_new0(type) ((type*) g_slice_alloc0 (sizeof (type)))
#define g_slice_dup(type, mem)
#define g_slice_free(type, mem)
#define g_slice_free_chain(type, mem_chain, next)
Enumerations
enum GSliceConfig {
G_SLICE_CONFIG_ALWAYS_MALLOC = 1, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_WORKING_SET_MSECS, G_SLICE_CONFIG_COLOR_INCREMENT,
G_SLICE_CONFIG_CHUNK_SIZES, G_SLICE_CONFIG_CONTENTION_COUNTER
}
Functions
G_BEGIN_DECLS gpointer g_slice_alloc (gsize block_size) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_slice_alloc0 (gsize block_size) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
gpointer g_slice_copy (gsize block_size, gconstpointer mem_block) G_GNUC_MALLOC G_GNUC_ALLOC_SIZE(1)
void g_slice_free1 (gsize block_size, gpointer mem_block)
void g_slice_free_chain_with_offset (gsize block_size, gpointer mem_chain, gsize next_offset)
void g_slice_set_config (GSliceConfig ckey, gint64 value)
gint64 g_slice_get_config (GSliceConfig ckey)
gint64 * g_slice_get_config_state (GSliceConfig ckey, gint64 address, guint *n_values)
Macro Definition Documentation
#define __G_SLICE_H__
#define g_slice_dup (type, mem)
Value:
(1 ? (type*) g_slice_copy (sizeof (type), (mem))              \
     : ((void) ((type*) 0 == (mem)), (type*) 0))
#define g_slice_free (type, mem)
Value:
do {    \
  if (1) g_slice_free1 (sizeof (type), (mem));                  \
  else   (void) ((type*) 0 == (mem));                           \
} while (0)
Referenced by coord_slice_free(), edge_hash_slice_free(), g_hash_table_remove_node(), g_hash_table_unref(), g_mem_chunk_destroy(), item_id_slice_free(), iter_remove_or_steal(), and route_graph_free_points().
#define g_slice_free_chain (type, mem_chain, next)
Value:
do {    \
  if (1) g_slice_free_chain_with_offset (sizeof (type),         \
                 (mem_chain), G_STRUCT_OFFSET (type, next));    \
  else   (void) ((type*) 0 == (mem_chain));                     \
} while (0)
Referenced by g_list_free(), and g_slist_free().
#define g_slice_new (type) ((type*) g_slice_alloc (sizeof (type)))
Referenced by add_node_to_hash(), ch_assemble_map(), ch_generate_ddsg(), g_error_new_valist(), g_hash_table_insert_internal(), g_hash_table_new_full(), and g_mem_chunk_new().
#define g_slice_new0 (type) ((type*) g_slice_alloc0 (sizeof (type)))
Referenced by route_graph_point_new().
Enumeration Type Documentation
enum GSliceConfig
Enumerator
G_SLICE_CONFIG_ALWAYS_MALLOC
G_SLICE_CONFIG_BYPASS_MAGAZINES
G_SLICE_CONFIG_WORKING_SET_MSECS
G_SLICE_CONFIG_COLOR_INCREMENT
G_SLICE_CONFIG_CHUNK_SIZES
G_SLICE_CONFIG_CONTENTION_COUNTER
Function Documentation
G_BEGIN_DECLS gpointer g_slice_alloc (gsize block_size)
References allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, G_LIKELY, g_malloc(), g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_alloc_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_alloc(), thread_memory_from_self(), thread_memory_magazine1_alloc(), thread_memory_magazine1_is_empty(), thread_memory_magazine1_reload(), and thread_memory_swap_magazines().
Referenced by g_mem_chunk_alloc(), g_slice_alloc0(), and g_slice_copy().
gpointer g_slice_alloc0 (gsize block_size)
References g_slice_alloc().
Referenced by cache_entry_new(), cache_trim(), g_mem_chunk_alloc0(), and route_graph_add_segment().
gpointer g_slice_copy (gsize block_size, gconstpointer mem_block)
References g_slice_alloc().
void g_slice_free1 (gsize block_size, gpointer mem_block)
References abort(), allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, g_free(), G_LIKELY, g_mem_gc_friendly, g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_free_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_free(), thread_memory_from_self(), thread_memory_magazine2_free(), thread_memory_magazine2_is_full(), thread_memory_magazine2_unload(), and thread_memory_swap_magazines().
Referenced by cache_remove(), cache_trim(), g_mem_chunk_free(), and route_graph_free_segments().
void g_slice_free_chain_with_offset (gsize block_size, gpointer mem_chain, gsize next_offset)
References abort(), allocator_categorize(), Allocator::config, SliceConfig::debug_blocks, g_free(), G_LIKELY, g_mem_gc_friendly, g_mutex_lock, g_mutex_unlock, G_UNLIKELY, P2ALIGN, slab_allocator_free_chunk(), SLAB_INDEX, Allocator::slab_mutex, smc_notify_free(), thread_memory_from_self(), thread_memory_magazine2_free(), thread_memory_magazine2_is_full(), thread_memory_magazine2_unload(), and thread_memory_swap_magazines().
gint64 g_slice_get_config (GSliceConfig ckey)
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, SliceConfig::color_increment, G_SLICE_CONFIG_ALWAYS_MALLOC, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_CHUNK_SIZES, G_SLICE_CONFIG_COLOR_INCREMENT, G_SLICE_CONFIG_WORKING_SET_MSECS, MAX_SLAB_INDEX, and SliceConfig::working_set_msecs.
gint64* g_slice_get_config_state (GSliceConfig ckey, gint64 address, guint * n_values)
References allocator_get_magazine_threshold(), Allocator::contention_counters, g_memdup(), g_return_val_if_fail, G_SLICE_CONFIG_CONTENTION_COUNTER, gint64, i, NULL, and SLAB_CHUNK_SIZE.
void g_slice_set_config (GSliceConfig ckey, gint64 value)
References SliceConfig::always_malloc, SliceConfig::bypass_magazines, SliceConfig::color_increment, g_return_if_fail, G_SLICE_CONFIG_ALWAYS_MALLOC, G_SLICE_CONFIG_BYPASS_MAGAZINES, G_SLICE_CONFIG_COLOR_INCREMENT, G_SLICE_CONFIG_WORKING_SET_MSECS, value, and SliceConfig::working_set_msecs.