navit: support/glib/gstring.c File Reference
gstring.c File Reference
#include "config.h"
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "glib.h"
#include "gprintf.h"
#include "galias.h"
#include "galiasdef.c"
Macros
#define __G_STRING_C__
Functions
gboolean g_str_equal (gconstpointer v1, gconstpointer v2)
guint g_str_hash (gconstpointer v)
Macro Definition Documentation
#define __G_STRING_C__
Function Documentation
gboolean g_str_equal (gconstpointer v1, gconstpointer v2)
g_str_equal: : a key : a key to compare with
Compares two strings for byte-by-byte equality and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using strings as keys in a GHashTable.
Returns: TRUE if the two keys match
References gchar.
Referenced by atom_init(), attr_create_hash(), bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), build_attrmap(), build_countrytable(), ch_generate_tiles(), create_tile_hash(), create_tile_hash_list(), debug_init(), duplicate_equal(), file_init(), file_process_headers(), graphics_android_new(), graphics_new(), graphics_opengl_new(), graphics_win32_new(), gui_gtk_bookmarks_update(), item_create_hash(), linguistics_init(), load_tilesdir(), longest_match_new(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), osm_process_towns(), osm_protobufdb_start_group(), phase34(), plugin_init(), plugins_new(), string_hash_lookup(), tile_collector_finish(), and tile_collector_new().
guint g_str_hash (gconstpointer v)
g_str_hash: : a string key
Converts a string to a hash value. It can be passed to g_hash_table_new() as the parameter, when using strings as keys in a GHashTable.
Returns: a hash value corresponding to the key
References p.
Referenced by atom_init(), attr_create_hash(), bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), build_attrmap(), build_countrytable(), ch_generate_tiles(), create_tile_hash(), create_tile_hash_list(), debug_init(), duplicate_hash(), file_init(), file_process_headers(), graphics_android_new(), graphics_new(), graphics_opengl_new(), graphics_win32_new(), gui_gtk_bookmarks_update(), item_create_hash(), linguistics_init(), load_tilesdir(), longest_match_new(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), osm_process_towns(), osm_protobufdb_start_group(), phase34(), plugin_init(), plugins_new(), string_hash_lookup(), tile_collector_finish(), and tile_collector_new().