navit: support/glib/gstrfuncs.c File Reference
gstrfuncs.c File Reference
#include "config.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include <errno.h>
#include <ctype.h>
#include <signal.h>
#include "glib.h"
#include "gprintf.h"
#include "gprintfint.h"
#include "glibintl.h"
#include "galias.h"
#include "gslist.h"
#include "galiasdef.c"
Macros
#define _GNU_SOURCE /* For stpcpy */
#define ISSPACE(c)
#define ISUPPER(c) ((c) >= 'A' && (c) <= 'Z')
#define ISLOWER(c) ((c) >= 'a' && (c) <= 'z')
#define ISALPHA(c) (ISUPPER (c) || ISLOWER (c))
#define TOUPPER(c) (ISLOWER (c) ? (c) - 'a' + 'A' : (c))
#define TOLOWER(c) (ISUPPER (c) ? (c) - 'A' + 'a' : (c))
#define __G_STRFUNCS_C__
Functions
gchar * g_strdup (const gchar *str)
gpointer g_memdup (gconstpointer mem, guint byte_size)
gchar * g_strndup (const gchar *str, gsize n)
gchar * g_strnfill (gsize length, gchar fill_char)
gchar * g_stpcpy (gchar *dest, const gchar *src)
gchar * g_strdup_vprintf (const gchar *format, va_list args)
gchar * g_strdup_printf (const gchar *format,...)
gchar * g_strconcat (const gchar *string1,...)
gdouble g_strtod (const gchar *nptr, gchar **endptr)
gdouble g_ascii_strtod (const gchar *nptr, gchar **endptr)
gchar * g_ascii_dtostr (gchar *buffer, gint buf_len, gdouble d)
gchar * g_ascii_formatd (gchar *buffer, gint buf_len, const gchar *format, gdouble d)
static guint64 g_parse_long_long (const gchar *nptr, const gchar **endptr, guint base, gboolean *negative)
guint64 g_ascii_strtoull (const gchar *nptr, gchar **endptr, guint base)
gint64 g_ascii_strtoll (const gchar *nptr, gchar **endptr, guint base)
gsize g_strlcpy (gchar *dest, const gchar *src, gsize dest_size)
gsize g_strlcat (gchar *dest, const gchar *src, gsize dest_size)
gchar * g_ascii_strdown (const gchar *str, gssize len)
gchar * g_ascii_strup (const gchar *str, gssize len)
gchar * g_strdown (gchar *string)
gchar * g_strup (gchar *string)
gchar * g_strreverse (gchar *string)
gchar g_ascii_tolower (gchar c)
gchar g_ascii_toupper (gchar c)
int g_ascii_digit_value (gchar c)
int g_ascii_xdigit_value (gchar c)
gint g_ascii_strcasecmp (const gchar *s1, const gchar *s2)
gint g_ascii_strncasecmp (const gchar *s1, const gchar *s2, gsize n)
gint g_strcasecmp (const gchar *s1, const gchar *s2)
gint g_strncasecmp (const gchar *s1, const gchar *s2, guint n)
gchar * g_strdelimit (gchar *string, const gchar *delimiters, gchar new_delim)
gchar * g_strcanon (gchar *string, const gchar *valid_chars, gchar substitutor)
gchar * g_strcompress (const gchar *source)
gchar * g_strescape (const gchar *source, const gchar *exceptions)
gchar * g_strchug (gchar *string)
gchar * g_strchomp (gchar *string)
gchar ** g_strsplit (const gchar *string, const gchar *delimiter, gint max_tokens)
void g_strfreev (gchar **str_array)
gchar ** g_strdupv (gchar **str_array)
gchar * g_strjoinv (const gchar *separator, gchar **str_array)
gchar * g_strjoin (const gchar *separator,...)
gchar * g_strstr_len (const gchar *haystack, gssize haystack_len, const gchar *needle)
gchar * g_strrstr (const gchar *haystack, const gchar *needle)
gchar * g_strrstr_len (const gchar *haystack, gssize haystack_len, const gchar *needle)
guint g_strv_length (gchar **str_array)
Variables
static const guint16 ascii_table_data [256]
const guint16 *const g_ascii_table = ascii_table_data
Macro Definition Documentation
#define __G_STRFUNCS_C__
#define _GNU_SOURCE /* For stpcpy */
#define ISALPHA (c) (ISUPPER (c) || ISLOWER (c))
Referenced by g_parse_long_long().
#define ISLOWER (c) ((c) >= 'a' && (c) <= 'z')
#define ISSPACE (c)
Value:
((c) == ' ' || (c) == '\f' || (c) == '\n' || \
                                 (c) == '\r' || (c) == '\t' || (c) == '\v')
Referenced by g_parse_long_long().
#define ISUPPER (c) ((c) >= 'A' && (c) <= 'Z')
#define TOLOWER (c) (ISUPPER (c) ? (c) - 'A' + 'a' : (c))
Referenced by g_ascii_strcasecmp(), and g_ascii_strncasecmp().
#define TOUPPER (c) (ISLOWER (c) ? (c) - 'a' + 'A' : (c))
Referenced by g_parse_long_long().
Function Documentation
int g_ascii_digit_value (gchar c)
g_ascii_digit_value: : an ASCII character.
Determines the numeric value of a character as a decimal digit. Differs from g_unichar_digit_value() because it takes a char, so there's no worry about sign extension if characters are signed.
Return value: If is a decimal digit (according to g_ascii_isdigit()), its numeric value. Otherwise, -1.
References g_ascii_isdigit.
Referenced by g_ascii_xdigit_value().
gchar* g_ascii_dtostr (gchar * buffer, gint buf_len, gdouble d)
g_ascii_dtostr: : A buffer to place the resulting string in : The length of the buffer. : The gdouble to convert
Converts a gdouble to a string, using the '.' as decimal point.
This functions generates enough precision that converting the string back using g_ascii_strtod() gives the same machine-number (on machines with IEEE compatible 64bit doubles). It is guaranteed that the size of the resulting string will never be larger than bytes.
Return value: The pointer to the buffer with the converted string.
References g_ascii_formatd().
gchar* g_ascii_formatd (gchar * buffer, gint buf_len, const gchar * format, gdouble d)
g_ascii_formatd: : A buffer to place the resulting string in : The length of the buffer. : The printf()-style format to use for the code to use for converting. : The gdouble to convert
Converts a gdouble to a string, using the '.' as decimal point. To format the number you pass in a printf()-style format string. Allowed conversion specifiers are 'e', 'E', 'f', 'F', 'g' and 'G'.
If you just want to want to serialize the value into a string, use g_ascii_dtostr().
Return value: The pointer to the buffer with the converted string.
References _g_snprintf, buffer, lconv::decimal_point, g_ascii_isspace, g_assert, g_return_val_if_fail, gchar, localeconv(), NULL, and p.
Referenced by g_ascii_dtostr().
gint g_ascii_strcasecmp (const gchar * s1, const gchar * s2)
g_ascii_strcasecmp: : string to compare with . : string to compare with .
Compare two strings, ignoring the case of ASCII characters.
Unlike the BSD strcasecmp() function, this only recognizes standard ASCII letters and ignores the locale, treating all non-ASCII bytes as if they are not letters.
This function should be used only on strings that are known to be in encodings where the bytes corresponding to ASCII letters always represent themselves. This includes UTF-8 and the ISO-8859-* charsets, but not for instance double-byte encodings like the Windows Codepage 932, where the trailing bytes of double-byte characters include all ASCII letters. If you compare two CP932 strings using this function, you will get false matches.
Return value: 0 if the strings match, a negative value if < , or a positive value if > .
References c1, c2, g_return_val_if_fail, NULL, and TOLOWER.
Referenced by attr_new_from_text(), file_create_caseinsensitive(), find_attr(), find_attribute(), find_boolean(), find_by_name(), gui_internal_html_end(), gui_internal_html_start(), linguistics_search(), maptype_get(), search_match(), start_element(), vehicle_file_new_file(), vehicle_file_parse(), vehicle_wince_parse(), xi_end_element(), xi_start_element(), and xinclude().
gchar* g_ascii_strdown (const gchar * str, gssize len)
g_ascii_strdown: : a string. : length of in bytes, or -1 if is nul-terminated.
Converts all upper case ASCII letters to lower case ASCII letters.
Return value: a newly-allocated string, with all the upper case characters in converted to lower case, with semantics that exactly match g_ascii_tolower(). (Note that this is unlike the old g_strdown(), which modified the string in place.)
References g_ascii_tolower(), g_return_val_if_fail, g_strndup(), gchar, and NULL.
Referenced by g_utf8_casefold().
gint g_ascii_strncasecmp (const gchar * s1, const gchar * s2, gsize n)
g_ascii_strncasecmp: : string to compare with . : string to compare with .
: number of characters to compare.
Compare and , ignoring the case of ASCII characters and any characters after the first
in each string.
Unlike the BSD strcasecmp() function, this only recognizes standard ASCII letters and ignores the locale, treating all non-ASCII characters as if they are not letters.
The same warning as in g_ascii_strcasecmp() applies: Use this function only on strings known to be in encodings where bytes corresponding to ASCII letters always represent themselves.
Return value: 0 if the strings match, a negative value if < , or a positive value if > .
References c1, c2, g_return_val_if_fail, NULL, and TOLOWER.
Referenced by gui_internal_cmd2_network_info(), plugin_get_category(), search_match(), and speech_cmdline_search().
gdouble g_ascii_strtod (const gchar * nptr, gchar ** endptr)
g_ascii_strtod: : the string to convert to a numeric value. : if non-NULL, it returns the character after the last character used in the conversion.
Converts a string to a gdouble value.
This function behaves like the standard strtod() function does in the C locale. It does this without actually changing the current locale, since that would not be thread-safe. A limitation of the implementation is that this function will still accept localized versions of infinities and NANs.
This function is typically used when reading configuration files or other non-user input that should be locale independent. To handle input from the user you should normally use the locale-sensitive system strtod() function.
To convert from a gdouble to a string in a locale-insensitive way, use g_ascii_dtostr().
If the correct value would cause overflow, plus or minus HUGE_VAL is returned (according to the sign of the value), and ERANGE is stored in errno. If the correct value would cause underflow, zero is returned and ERANGE is stored in errno.
This function resets errno before calling strtod() so that you can reliably detect overflow and underflow.
Return value: the gdouble value.
References c, lconv::decimal_point, errno, g_ascii_isdigit, g_ascii_isspace, g_ascii_isxdigit, g_assert, g_free(), g_malloc(), g_return_val_if_fail, gchar, localeconv(), NULL, and p.
Referenced by g_strtod(), vehicle_file_parse(), vehicle_webos_parse_nmea(), and vehicle_wince_parse().
gint64 g_ascii_strtoll (const gchar * nptr, gchar ** endptr, guint base)
g_ascii_strtoll: : the string to convert to a numeric value. : if non-NULL, it returns the character after the last character used in the conversion. : to be used for the conversion, 2..36 or 0
Converts a string to a gint64 value. This function behaves like the standard strtoll() function does in the C locale. It does this without actually changing the current locale, since that would not be thread-safe.
This function is typically used when reading configuration files or other non-user input that should be locale independent. To handle input from the user you should normally use the locale-sensitive system strtoll() function.
If the correct value would cause overflow, G_MAXINT64 or G_MININT64 is returned, and ERANGE is stored in errno. If the base is outside the valid range, zero is returned, and EINVAL is stored in errno. If the string conversion fails, zero is returned, and returns (if is non-NULL).
Return value: the gint64 value or zero on error.
Since: 2.12
References ERANGE, errno, G_MAXINT64, G_MININT64, g_parse_long_long(), gchar, gint64, and guint64.
guint64 g_ascii_strtoull (const gchar * nptr, gchar ** endptr, guint base)
g_ascii_strtoull: : the string to convert to a numeric value. : if non-NULL, it returns the character after the last character used in the conversion. : to be used for the conversion, 2..36 or 0
Converts a string to a guint64 value. This function behaves like the standard strtoull() function does in the C locale. It does this without actually changing the current locale, since that would not be thread-safe.
This function is typically used when reading configuration files or other non-user input that should be locale independent. To handle input from the user you should normally use the locale-sensitive system strtoull() function.
If the correct value would cause overflow, G_MAXUINT64 is returned, and ERANGE is stored in errno. If the base is outside the valid range, zero is returned, and EINVAL is stored in errno. If the string conversion fails, zero is returned, and returns (if is non-NULL).
Return value: the guint64 value or zero on error.
Since: 2.2
References g_parse_long_long(), gchar, and guint64.
Referenced by attr_new_from_text(), and convert_number().
gchar* g_ascii_strup (const gchar * str, gssize len)
g_ascii_strup: : a string. : length of in bytes, or -1 if is nul-terminated.
Converts all lower case ASCII letters to upper case ASCII letters.
Return value: a newly allocated string, with all the lower case characters in converted to upper case, with semantics that exactly match g_ascii_toupper(). (Note that this is unlike the old g_strup(), which modified the string in place.)
References g_ascii_toupper(), g_return_val_if_fail, g_strndup(), gchar, and NULL.
Referenced by gui_internal_cmd_enter_coord_do(), and gui_internal_keyboard_init_mode().
gchar g_ascii_tolower (gchar c)
g_ascii_tolower: : any character.
Convert a character to ASCII lower case.
Unlike the standard C library tolower() function, this only recognizes standard ASCII letters and ignores the locale, returning all non-ASCII characters unchanged, even if they are lower case letters in a particular character set. Also unlike the standard library function, this takes and returns a char, not an int, so don't call it on EOF but no need to worry about casting to guchar before passing a possibly non-ASCII character in.
Return value: the result of converting to lower case. If is not an ASCII upper case letter, is returned unchanged.
References c, and g_ascii_isupper.
Referenced by g_ascii_strdown().
gchar g_ascii_toupper (gchar c)
g_ascii_toupper: : any character.
Convert a character to ASCII upper case.
Unlike the standard C library toupper() function, this only recognizes standard ASCII letters and ignores the locale, returning all non-ASCII characters unchanged, even if they are upper case letters in a particular character set. Also unlike the standard library function, this takes and returns a char, not an int, so don't call it on EOF but no need to worry about casting to guchar before passing a possibly non-ASCII character in.
Return value: the result of converting to upper case. If is not an ASCII lower case letter, is returned unchanged.
References c, and g_ascii_islower.
Referenced by g_ascii_strup().
int g_ascii_xdigit_value (gchar c)
g_ascii_xdigit_value: : an ASCII character.
Determines the numeric value of a character as a hexidecimal digit. Differs from g_unichar_xdigit_value() because it takes a char, so there's no worry about sign extension if characters are signed.
Return value: If is a hex digit (according to g_ascii_isxdigit()), its numeric value. Otherwise, -1.
References g_ascii_digit_value().
gpointer g_memdup (gconstpointer mem, guint byte_size)
References g_malloc(), and NULL.
Referenced by g_slice_get_config_state(), and gui_internal_poi_param_clone().
static guint64 g_parse_long_long (const gchar * nptr, const gchar ** endptr, guint base, gboolean * negative) static
References c, EINVAL, ERANGE, errno, FALSE, G_MAXUINT64, g_return_val_if_fail, G_UNLIKELY, gchar, guint64, ISALPHA, ISSPACE, NULL, TOUPPER, and TRUE.
Referenced by g_ascii_strtoll(), and g_ascii_strtoull().
gchar* g_stpcpy (gchar * dest, const gchar * src)
g_stpcpy: : destination buffer. : source string.
Copies a nul-terminated string into the dest buffer, include the trailing nul, and return a pointer to the trailing nul byte. This is useful for concatenating multiple strings together without having to repeatedly scan for the end.
Return value: a pointer to trailing nul byte.
References startup::dest, g_return_val_if_fail, gchar, NULL, and stpcpy().
Referenced by g_strconcat(), g_strjoin(), g_strjoinv(), navit_get_attr(), and osd_text_draw().
gchar* g_strcanon (gchar * string, const gchar * valid_chars, gchar substitutor)
References c, g_return_val_if_fail, gchar, and NULL.
gint g_strcasecmp (const gchar * s1, const gchar * s2)
g_strcasecmp: : a string. : a string to compare with .
A case-insensitive string comparison, corresponding to the standard strcasecmp() function on platforms which support it.
Return value: 0 if the strings match, a negative value if < , or a positive value if > .
Deprecated:2.2: See g_strncasecmp() for a discussion of why this function is deprecated and how to replace it.
References c1, c2, g_return_val_if_fail, NULL, s1, s2, and strcasecmp().
Referenced by vehicle_webos_parse_nmea(), vehicle_wince_new(), and vehicle_wince_parse().
gchar* g_strchomp (gchar * string)
References g_ascii_isspace, g_return_val_if_fail, and NULL.
Referenced by bookmarks_set_center_from_file().
gchar* g_strchug (gchar * string)
References g_ascii_isspace, g_memmove, g_return_val_if_fail, gchar, NULL, and start.
gchar* g_strcompress (const gchar * source)
References startup::dest, g_malloc(), g_warning(), gchar, p, and source.
gchar* g_strconcat (const gchar * string1, ...)
References g_new, g_stpcpy(), gchar, NULL, and ptr.
Referenced by bookmarks_store_bookmarks_to_file(), g_strconcat_printf(), gui_internal_onclick(), process_house_number_interpolation_member(), start_element(), vehicle_file_parse(), vehicle_gpsd_callback(), vehicle_gpsd_new_gpsd(), vehicle_webos_parse_nmea(), and vehicle_wince_parse().
gchar* g_strdelimit (gchar * string, const gchar * delimiters, gchar new_delim)
References c, g_return_val_if_fail, G_STR_DELIMITERS, gchar, and NULL.
gchar* g_strdown (gchar * string)
g_strdown: : the string to convert.
Converts a string to lower case.
Return value: the string
Deprecated:2.2: This function is totally broken for the reasons discussed in the g_strncasecmp() docs - use g_ascii_strdown() or g_utf8_strdown() instead.
References g_return_val_if_fail, gchar, and NULL.
gchar* g_strdup (const gchar * str)
References g_new, gchar, length, and NULL.
Referenced by add_aux_tile(), add_menu(), atom(), attr_new_from_text(), attr_to_text_ext(), binfile_extract(), binmap_search_new(), bookmarks_add_bookmark(), bookmarks_append_destinations(), bookmarks_copy_bookmark(), bookmarks_load_hash(), bookmarks_paste_bookmark(), bookmarks_rename_bookmark(), bookmarks_store_bookmarks_to_file(), build_attrmap(), build_countrytable(), build_match(), build_matches(), command_call_function(), command_error_to_text(), command_evaluate(), command_saved_attr_new(), current_to_iso8601(), cursor_new(), debug_init(), debug_level_set(), debug_new(), download_request(), espeak_new(), espeak_say(), expand_filenames(), expand_variables(), ezxml_proc_inst(), ezxml_set_attr(), face_requester(), file_create(), file_process_headers(), file_wordexp_new(), find_attr_dup(), font_freetype_font_new(), format_speed(), g_convert(), g_path_get_basename(), g_set_prgname(), g_strdupv(), g_strjoin(), g_strjoinv(), g_strsplit(), get_icon(), Backend::get_maps(), Backend::get_vehicles(), graphics_displaylist_draw(), graphics_gtk_drawing_area_new(), graphics_icon_path(), graphics_qt5_new(), graphics_qt_qpainter_new(), gui_gtk_bookmarks_update(), gui_gtk_ui_new(), gui_internal_add_attr(), gui_internal_box_new_with_label(), gui_internal_button_font_new_with_callback(), gui_internal_cmd2_refresh(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_img(), gui_internal_cmd_map_download(), gui_internal_cmd_match_expand(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attributes(), gui_internal_compose_item_address_string(), gui_internal_create_resultlist_entry(), gui_internal_html_end(), gui_internal_html_load_href(), gui_internal_html_menu(), gui_internal_html_text(), gui_internal_keyboard_key(), gui_internal_keyboard_show_native(), gui_internal_keypress_do(), gui_internal_label_font_new(), gui_internal_new(), gui_internal_onclick(), gui_internal_poi_icon(), gui_internal_prune_menu_do(), gui_internal_refresh_callback_called(), gui_internal_search(), gui_internal_search_idle(), gui_internal_search_list_set_default_country(), gui_internal_search_town_in_country(), gui_internal_set_attr(), gui_internal_text_font_new(), gui_internal_top_bar(), gui_qml_new(), housenumber_search_setup(), image_new(), image_new_helper(), introspect_path(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_CallbackMessageChannel(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), layer_set_attr_do(), layout_new(), linguistics_expand_special(), log_new(), longest_match_add_match(), main_init(), main_real(), main_setup_environment(), map_binfile_handle_redirect(), map_binfile_open(), map_binfile_zip_setup(), map_convert_dup(), map_new_binfile(), map_new_csv(), map_new_garmin_img(), map_new_mg(), map_new_shapefile(), map_new_textfile(), map_rect_new_textfile(), map_search_setup(), maps_new(), maptype_register(), message_new(), mlPDL_ServiceCall(), mlPDL_ServiceCallWithCallback(), model_poi(), nav_status_to_text(), navigation_cmd_get_exit_announce(), navigation_item_destination(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), navit_nls_add_textdomain(), navit_window_roadbook_update(), ocean_tile(), osd_cmd_interface_init(), osd_cmd_interface_new(), osd_cmd_interface_set_attr(), osd_gps_status_new(), osd_nav_toggle_announcer_new(), osd_odometer_from_string(), osd_odometer_new(), osd_route_guard_new(), osd_set_std_attr(), osd_speed_cam_new(), osd_speed_warner_new(), osd_text_draw(), osd_text_format_attr(), osd_text_new(), osd_text_prepare(), osd_text_set_attr(), osd_volume_new(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), parse_file(), parse_filter(), parse_filters(), parse_option(), plugin_new_from_path(), process_associated_street_member(), process_boundaries_setup(), process_fields(), process_house_number_interpolation_member(), qt5_espeak_init_espeak(), qt5_espeak_init_language(), read_former_destination_map_as_list(), request_callback_new(), request_navit_route_export_geojson(), route_calc_selection(), route_get_destination_description(), rp_attr_get(), save_map_csv(), search_add_result(), search_fix_spaces(), search_house_number_interpolation_split(), search_list_country_dup(), search_list_country_new(), search_list_search(), search_next_house_number_curr_interpol_with_ends(), search_postal_merge(), Backend::searchValidateResult(), select_announced_destinations(), set_attr_do(), setenv(), shapefile_attr_get(), show_maneuver(), show_next_maneuvers(), speech_android_say(), speechd_new(), speechd_say(), split_string_to_list(), start_element(), string_hash_lookup(), tile_collector_add_siblings2(), tile_collector_process(), tile_collector_process_tile(), Backend::updateSearch(), urldecode(), vehicle_file_new_file(), vehicle_file_open(), vehicle_gpsd_dbus_set_attr_do(), vehicle_gpsd_new_gpsd(), vehicle_gpsd_try_open(), vehicle_gypsy_new_gypsy(), vehicle_gypsy_try_open(), vehicle_log_gpx_add_tag(), vehicle_maemo_new_maemo(), vehicle_new(), vehicle_set_attr(), vehicle_webos_bt_gap_callback(), vehicle_webos_set_attr_do(), vehicle_wince_new(), vehicle_wince_open(), vehicleprofile_set_attr_do(), wordexp(), xi_start_element(), xml_parse_text(), and xmlconfig_announce().
gchar* g_strdup_printf (const gchar * format, ...)
References buffer, g_strdup_vprintf(), and gchar.
Referenced by add_menu(), android_search_idle(), attr_to_text_ext(), binfile_extract(), coord_to_str(), coordinates_geo(), current_to_iso8601(), dbus_cmd_send_signal(), dbus_dump_iter(), dbus_main_navit(), debug_malloc(), description(), displayitem_draw(), download(), download_request(), espeak_new(), expand_filenames(), flags_to_text(), font_freetype_font_new(), format_distance(), format_float_0(), format_speed(), format_time(), generate_navitintrospectxml(), get_distance_str(), get_icon(), get_iter_name(), Backend::get_maps(), graphics_icon_path(), graphics_image_new_scaled_rotated(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_vehicles_update(), gui_internal_add_vehicle_profile(), gui_internal_append_attr(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_maps(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord_do(), gui_internal_cmd_escape(), gui_internal_cmd_img(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_cmd_write(), gui_internal_keypress_do(), gui_internal_poi_icon(), gui_internal_populate_route_table(), gui_internal_say(), gui_internal_search(), gui_internal_search_idle(), gui_internal_select_waypoint(), gui_internal_top_bar(), image_new(), image_new_helper(), invoke(), load_changes(), main(), main_setup_environment(), maneuver_required2(), map_binfile_http_range(), map_new_mg(), map_new_shapefile(), map_rect_new_shapefile(), map_rect_new_textfile(), map_search_setup(), nav_status_to_text(), navigation_cmd_get_exit_announce(), navigation_item_destination(), navigation_map_item_attr_get(), navit_handler_func(), navit_map_progress(), navit_textfile_debug_log(), navit_textfile_debug_log_at(), navit_window_roadbook_update(), object_new(), osd_button_icon_path(), osd_gps_status_draw(), osd_j1850_new(), osd_nav_next_turn_draw(), osd_nav_toggle_announcer_draw(), osd_navigation_status_draw_do(), osd_odometer_draw(), osd_odometer_new(), osd_odometer_save(), osd_odometer_to_string(), osd_text_draw(), osd_text_format_attr(), osd_volume_draw(), osm_process_towns(), parse_file(), pedestrian_log(), process_boundaries_finish(), process_fields(), qt5_espeak_init_espeak(), request_navit_route_export_geojson(), resolve_object(), result_op(), rm_attr_get(), route_get_destination_description(), rp_attr_get(), save_map_csv(), search_list_country_new(), search_next_house_number_curr_interpol_with_ends(), shapefile_attr_get(), show_maneuver(), show_next_maneuvers(), sort_countries(), speechd_say(), tempfile_name(), tile_collector_process_tile(), town_display_label(), town_str(), tracking_map_item_attr_get(), vehicle_demo_position_attr_get(), vehicle_log_gpx(), vehicle_log_gpx_add_tag(), vehicle_log_textfile(), and write_changes().
gchar* g_strdup_vprintf (const gchar * format, va_list args)
References g_vasprintf(), gchar, and NULL.
Referenced by g_error_new_valist(), g_strconcat_printf(), g_strdup_printf(), navit_textfile_debug_log(), navit_textfile_debug_log_at(), and popup_printf_cb().
gchar** g_strdupv (gchar ** str_array)
g_strdupv: : NULL-terminated array of strings.
Copies NULL-terminated array of strings. The copy is a deep copy; the new array should be freed by first freeing each string, then the array itself. g_strfreev() does this for you. If called on a NULL value, g_strdupv() simply returns NULL.
Return value: a new NULL-terminated array of strings.
References g_new, g_strdup(), gchar, i, and NULL.
gchar* g_strescape (const gchar * source, const gchar * exceptions)
References startup::dest, g_malloc(), g_return_val_if_fail, gchar, NULL, and p.
void g_strfreev (gchar ** str_array)
g_strfreev: : a NULL-terminated array of strings to free.
Frees a NULL-terminated array of strings, and the array itself. If called on a NULL value, g_strfreev() simply returns.
References g_free(), i, and NULL.
Referenced by android_search_end(), and speechd_say().
gchar* g_strjoin (const gchar * separator, ...)
References g_new, g_stpcpy(), g_strdup(), gchar, NULL, and ptr.
Referenced by bookmarks_get_center_file(), bookmarks_get_destination_file(), bookmarks_new(), Backend::get_country_icon(), Backend::get_icon_path(), gui_internal_compose_item_address_string(), gui_internal_set(), gui_internal_setup(), gui_qml_new(), main_real(), navit_cmd_strjoin(), plugin_get_category(), and popup_traffic_distortion().
gchar* g_strjoinv (const gchar * separator, gchar ** str_array)
References g_new, g_return_val_if_fail, g_stpcpy(), g_strdup(), gchar, i, NULL, and ptr.
Referenced by main(), spawn_process(), and town_display_label().
gsize g_strlcat (gchar * dest, const gchar * src, gsize dest_size)
References startup::dest, g_return_val_if_fail, gchar, and NULL.
gsize g_strlcpy (gchar * dest, const gchar * src, gsize dest_size)
References c, startup::dest, g_return_val_if_fail, gchar, and NULL.
Referenced by attr_strings_save(), linguistics_casefold(), linguistics_dup_utf8_char(), linguistics_get_special(), main(), osm_add_tag(), osm_update_attr_present(), process_associated_streets_setup(), relation_add_tag(), shell_escape(), and write_countrydir().
gint g_strncasecmp (const gchar * s1, const gchar * s2, guint n)
g_strncasecmp: : a string. : a string to compare with .
: the maximum number of characters to compare.
A case-insensitive string comparison, corresponding to the standard strncasecmp() function on platforms which support it. It is similar to g_strcasecmp() except it only compares the first
characters of the strings.
Return value: 0 if the strings match, a negative value if < , or a positive value if > .
Deprecated:2.2: The problem with g_strncasecmp() is that it does the comparison by calling toupper()/tolower(). These functions are locale-specific and operate on single bytes. However, it is impossible to handle things correctly from an I18N standpoint by operating on bytes, since characters may be multibyte. Thus g_strncasecmp() is broken if your string is guaranteed to be ASCII, since it's locale-sensitive, and it's broken if your string is localized, since it doesn't work on many encodings at all, including UTF-8, EUC-JP, etc.
There are therefore two replacement functions: g_ascii_strncasecmp(), which only works on ASCII and is not locale-sensitive, and g_utf8_casefold(), which is good for case-insensitive sorting of UTF-8.
References c1, c2, g_return_val_if_fail, NULL, s1, s2, and strncasecmp.
gchar* g_strndup (const gchar * str, gsize n)
g_strndup: : the string to duplicate
: the maximum number of bytes to copy from
Duplicates the first
bytes of a string, returning a newly-allocated buffer
+ 1 bytes long which will always be nul-terminated. If is less than
bytes long the buffer is padded with nuls. If is NULL it returns NULL. The returned value should be freed when no longer needed.
<note>
To copy a number of characters from a UTF-8 encoded string, use g_utf8_strncpy() instead.
</note>
Returns: a newly-allocated buffer containing the first
bytes of , nul-terminated
References g_new, gchar, and NULL.
Referenced by g_ascii_strdown(), g_ascii_strup(), g_strsplit(), g_vasprintf(), graphics_image_new_scaled_rotated(), and gui_internal_html_text().
gchar* g_strnfill (gsize length, gchar fill_char)
g_strnfill: : the length of the new string : the byte to fill the string with
Creates a new string bytes long filled with . The returned string should be freed when no longer needed.
Returns: a newly-allocated string filled the
References g_new, gchar, and length.
gchar* g_strreverse (gchar * string)
References c, g_return_val_if_fail, gchar, and NULL.
gchar* g_strrstr (const gchar * haystack, const gchar * needle)
g_strrstr: : a nul-terminated string. : the nul-terminated string to search for.
Searches the string for the last occurrence of the string .
Return value: a pointer to the found occurrence, or NULL if not found.
References g_return_val_if_fail, gchar, i, next, NULL, and p.
Referenced by g_strrstr_len(), gui_internal_find_next_possible_key(), gui_internal_highlight_possible_keys(), gui_internal_poi_icon(), and plugin_get_category().
gchar* g_strrstr_len (const gchar * haystack, gssize haystack_len, const gchar * needle)
g_strrstr_len: : a nul-terminated string. : the maximum length of . : the nul-terminated string to search for.
Searches the string for the last occurrence of the string , limiting the length of the search to .
Return value: a pointer to the found occurrence, or NULL if not found.
References g_return_val_if_fail, g_strrstr(), gchar, i, next, NULL, and p.
Referenced by g_utf8_strrchr().
gchar** g_strsplit (const gchar * string, const gchar * delimiter, gint max_tokens)
g_strsplit: : a string to split. : a string which specifies the places at which to split the string. The delimiter is not included in any of the resulting strings, unless is reached. : the maximum number of pieces to split into. If this is less than 1, the string is split completely.
Splits a string into a maximum of pieces, using the given . If is reached, the remainder of is appended to the last token.
As a special case, the result of splitting the empty string "" is an empty vector, not a vector containing a single string. The reason for this special case is that being able to represent a empty vector is typically more useful than consistent handling of empty elements. If you do need to represent empty elements, you'll need to check for the empty string before calling g_strsplit().
Return value: a newly-allocated NULL-terminated array of strings. Use g_strfreev() to free it.
References G_MAXINT, g_new, g_return_val_if_fail, g_slist_free(), g_slist_prepend(), g_strdup(), g_strndup(), gchar, and NULL.
Referenced by draw_multiline_osd_text(), speechd_say(), and start_search().
gchar* g_strstr_len (const gchar * haystack, gssize haystack_len, const gchar * needle)
g_strstr_len: : a string. : the maximum length of . Note that -1 is a valid length, if is nul-terminated, meaning it will search through the whole string. : the string to search for.
Searches the string for the first occurrence of the string , limiting the length of the search to .
Return value: a pointer to the found occurrence, or NULL if not found.
References g_return_val_if_fail, gchar, i, next, NULL, and p.
Referenced by g_utf8_strchr().
gdouble g_strtod (const gchar * nptr, gchar ** endptr)
g_strtod: : the string to convert to a numeric value. : if non-NULL, it returns the character after the last character used in the conversion.
Converts a string to a gdouble value. It calls the standard strtod() function to handle the conversion, but if the string is not completely converted it attempts the conversion again with g_ascii_strtod(), and returns the best match.
This function should seldomly be used. The normal situation when reading numbers not for human consumption is to use g_ascii_strtod(). Only when you know that you must expect both locale formatted and C formatted numbers should you use this. Make sure that you don't pass strings such as comma separated lists of values, since the commas may be interpreted as a decimal point in some locales, causing unexpected results.
Return value: the gdouble value.
References g_ascii_strtod(), g_return_val_if_fail, gchar, and NULL.
gchar* g_strup (gchar * string)
g_strup: : the string to convert.
Converts a string to upper case.
Return value: the string
Deprecated:2.2: This function is totally broken for the reasons discussed in the g_strncasecmp() docs - use g_ascii_strup() or g_utf8_strup() instead.
References g_return_val_if_fail, gchar, and NULL.
guint g_strv_length (gchar ** str_array)
g_strv_length: : a NULL-terminated array of strings.
Returns the length of the given NULL-terminated string array .
Return value: length of .
Since: 2.6
References g_return_val_if_fail, i, and NULL.
Referenced by speechd_say().
Variable Documentation
const guint16 ascii_table_data[256] static
Initial value:
= {
  0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004,
  0x004, 0x104, 0x104, 0x004, 0x104, 0x104, 0x004, 0x004,
  0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004,
  0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004, 0x004,
  0x140, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0,
  0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0,
  0x459, 0x459, 0x459, 0x459, 0x459, 0x459, 0x459, 0x459,
  0x459, 0x459, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0,
  0x0d0, 0x653, 0x653, 0x653, 0x653, 0x653, 0x653, 0x253,
  0x253, 0x253, 0x253, 0x253, 0x253, 0x253, 0x253, 0x253,
  0x253, 0x253, 0x253, 0x253, 0x253, 0x253, 0x253, 0x253,
  0x253, 0x253, 0x253, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x0d0,
  0x0d0, 0x473, 0x473, 0x473, 0x473, 0x473, 0x473, 0x073,
  0x073, 0x073, 0x073, 0x073, 0x073, 0x073, 0x073, 0x073,
  0x073, 0x073, 0x073, 0x073, 0x073, 0x073, 0x073, 0x073,
  0x073, 0x073, 0x073, 0x0d0, 0x0d0, 0x0d0, 0x0d0, 0x004
}
const guint16* const g_ascii_table = ascii_table_data