navit: support/glib/gthreadprivate.h File Reference
gthreadprivate.h File Reference
Macros
#define g_system_thread_equal_simple(thread1, thread2) ((thread1).dummy_pointer == (thread2).dummy_pointer)
#define g_system_thread_assign(dest, src) ((dest).dummy_pointer = (src).dummy_pointer)
#define g_system_thread_equal(thread1, thread2)
Functions
void g_thread_init_glib (void)
G_GNUC_INTERNAL void _g_mem_thread_init_noprivate_nomessage (void)
G_GNUC_INTERNAL void _g_slice_thread_init_nomessage (void)
G_GNUC_INTERNAL void _g_messages_thread_init_nomessage (void)
G_GNUC_INTERNAL void _g_convert_thread_init (void)
G_GNUC_INTERNAL void _g_rand_thread_init (void)
G_GNUC_INTERNAL void _g_main_thread_init (void)
G_GNUC_INTERNAL void _g_atomic_thread_init (void)
G_GNUC_INTERNAL void _g_utils_thread_init (void)
Macro Definition Documentation
#define g_system_thread_assign (dest, src) ((dest).dummy_pointer = (src).dummy_pointer)
#define g_system_thread_equal (thread1, thread2)
Value:
(g_thread_functions_for_glib_use.thread_equal ?                         \
   g_thread_functions_for_glib_use.thread_equal (&(thread1), &(thread2)) :\
   g_system_thread_equal_simple((thread1), (thread2)))
#define g_system_thread_equal_simple (thread1, thread2) ((thread1).dummy_pointer == (thread2).dummy_pointer)
Function Documentation
G_GNUC_INTERNAL void _g_atomic_thread_init (void)
References g_mutex_new.
G_GNUC_INTERNAL void _g_convert_thread_init (void)
G_GNUC_INTERNAL void _g_main_thread_init (void)
G_GNUC_INTERNAL void _g_mem_thread_init_noprivate_nomessage (void)
References g_mem_init_nomessage(), g_mutex_new, and gmem_profile_mutex.
G_GNUC_INTERNAL void _g_messages_thread_init_nomessage (void)
G_GNUC_INTERNAL void _g_rand_thread_init (void)
G_GNUC_INTERNAL void _g_slice_thread_init_nomessage (void)
References Allocator::config, SliceConfig::debug_blocks, g_mutex_new, g_private_new, g_slice_init_nomessage(), Allocator::magazine_mutex, private_thread_memory_cleanup(), and Allocator::slab_mutex.
Referenced by main(), and main_real().
G_GNUC_INTERNAL void _g_utils_thread_init (void)
void g_thread_init_glib (void)