navit: gui/internal/gui_internal.c File Reference
gui_internal.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <glib.h>
#include <time.h>
#include "config.h"
#include "item.h"
#include "xmlconfig.h"
#include "file.h"
#include "navit.h"
#include "navit_nls.h"
#include "gui.h"
#include "coord.h"
#include "point.h"
#include "plugin.h"
#include "graphics.h"
#include "transform.h"
#include "color.h"
#include "map.h"
#include "callback.h"
#include "vehicle.h"
#include "vehicleprofile.h"
#include "window.h"
#include "config_.h"
#include "keys.h"
#include "mapset.h"
#include "route.h"
#include "navit/search.h"
#include "track.h"
#include "country.h"
#include "event.h"
#include "navigation.h"
#include "gui_internal.h"
#include "command.h"
#include "util.h"
#include "bookmarks.h"
#include "linguistics.h"
#include "debug.h"
#include "fib.h"
#include "types.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_bookmark.h"
#include "gui_internal_menu.h"
#include "gui_internal_search.h"
#include "gui_internal_gesture.h"
#include "gui_internal_poi.h"
#include "gui_internal_command.h"
#include "gui_internal_keyboard.h"
Data Structures
struct vehicle_and_profilename
Functions
static void gui_internal_cmd_view_in_browser (struct gui_priv *this, struct widget *wm, void *data)
static int gui_internal_is_active_vehicle (struct gui_priv *this, struct vehicle *vehicle)
static struct graphics_image * image_new_scaled (struct gui_priv *this, const char *name, int w, int h)
Displays an image scaled to a specific size.
struct graphics_image * image_new_xs (struct gui_priv *this, const char *name)
Displays an image scaled to xs (extra small) size.
struct graphics_image * image_new_s (struct gui_priv *this, const char *name)
Displays an image scaled to s (small) size.
struct graphics_image * image_new_l (struct gui_priv *this, const char *name)
Displays an image scaled to l (large) size.
static int gui_internal_button_attr_update (struct gui_priv *this, struct widget *w)
static void gui_internal_button_attr_callback (struct gui_priv *this, struct widget *w)
static void gui_internal_button_attr_pressed (struct gui_priv *this, struct widget *w, void *data)
struct widget * gui_internal_button_navit_attr_new (struct gui_priv *this, const char *text, enum flags flags, struct attr *on, struct attr *off)
struct widget * gui_internal_button_map_attr_new (struct gui_priv *this, const char *text, enum flags flags, struct map *map, struct attr *on, struct attr *off, int deflt)
static void gui_internal_motion_cb (struct gui_priv *this)
static void gui_internal_call_highlighted (struct gui_priv *this)
void gui_internal_say (struct gui_priv *this, struct widget *w, int questionmark)
void gui_internal_back (struct gui_priv *this, struct widget *w, void *data)
void gui_internal_cmd_return (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_main_menu (struct gui_priv *this, struct widget *wm, void *data)
struct widget * gui_internal_time_help (struct gui_priv *this)
void gui_internal_apply_config (struct gui_priv *this)
static void gui_internal_cmd_set_destination (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_insert_destination_do (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_select_waypoint (struct gui_priv *this, const char *title, const char *hint, struct widget *wm_, void(*cmd)(struct gui_priv *priv, struct widget *widget, void *data), void *data)
static void gui_internal_cmd_insert_destination (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_set_position (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_call_linked_on_finish (struct gui_priv *this, struct widget *wm, void *data)
Generic notification function for Editable widgets to call Another widget notification function when Enter is pressed in editable field. The Editable widget should have data member pointing to the Another widget.
struct widget * gui_internal_keyboard (struct gui_priv *this, int mode)
Creates a keyboard widget.
struct widget * gui_internal_keyboard_show_native (struct gui_priv *this, struct widget *w, int mode, char *lang)
Shows the platform's native on-screen keyboard or other input method.
static void gui_internal_cmd_delete_bookmark (struct gui_priv *this, struct widget *wm, void *data)
char * removecase (char *s)
static void gui_internal_cmd_view_on_map (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_view_attribute_details (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_view_attributes (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_results_to_map (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_results_map_clean (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_delete_waypoint (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_position_do (struct gui_priv *this, struct pcoord *pc_in, struct coord_geo *g_in, struct widget *wm, const char *name, int flags)
Displays the commands available for a location.
void gui_internal_cmd_position (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_bookmarks (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_keynav_highlight_next (struct gui_priv *this, int dx, int dy, int rotary)
Move keyboard focus to the next widget.
static int gui_internal_keynav_find_next (struct widget *wi, struct widget *current_highlight, struct widget **result)
static int gui_internal_keynav_find_prev (struct widget *wi, struct widget *current_highlight, struct widget **result)
static struct widget * gui_internal_keynav_find_next_sensitive_child (struct widget *wi)
void gui_internal_keypress_do (struct gui_priv *this, char *key)
char * gui_internal_cmd_match_expand (char *pattern, struct attr **in)
static int gui_internal_match (const char *pattern, const char *string)
int gui_internal_set (char *remove, char *add)
static void gui_internal_window_closed (struct gui_priv *this)
static void gui_internal_cmd_map_download_do (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_map_download (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_set_active_vehicle (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_show_satellite_status (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_cmd_show_nmea_data (struct gui_priv *this, struct widget *wm, void *data)
static void save_vehicle_xml (struct vehicle *v)
static void gui_internal_cmd_set_active_profile (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_add_vehicle_profile (struct gui_priv *this, struct widget *parent, struct vehicle *v, struct vehicleprofile *profile)
void gui_internal_menu_vehicle_settings (struct gui_priv *this, struct vehicle *v, char *name)
void gui_internal_cmd_vehicle_settings (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_motion (void *data, struct point *p)
void gui_internal_evaluate (struct gui_priv *this, const char *command)
void gui_internal_enter (struct gui_priv *this, int ignore)
void gui_internal_leave (struct gui_priv *this)
void gui_internal_set_click_coord (struct gui_priv *this, struct point *p)
static void gui_internal_set_position_coord (struct gui_priv *this)
void gui_internal_enter_setup (struct gui_priv *this)
void gui_internal_cmd_menu (struct gui_priv *this, int ignore, char *href)
static void gui_internal_cmd_log_do (struct gui_priv *this, struct widget *widget)
void gui_internal_cmd_log_clicked (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_check_exit (struct gui_priv *this)
static int gui_internal_get_attr (struct gui_priv *this, enum attr_type type, struct attr *attr)
static int gui_internal_add_attr (struct gui_priv *this, struct attr *attr)
static int gui_internal_set_attr (struct gui_priv *this, struct attr *attr)
static void gui_internal_dbus_signal (struct gui_priv *this, struct point *p)
static int gui_internal_coordinate_parse (char *s, char plus, char minus, double *x)
Converts one geo coordinate in human readable form to double value.
static void gui_internal_cmd_enter_coord_do (struct gui_priv *this, struct widget *widget)
void gui_internal_cmd_enter_coord_clicked (struct gui_priv *this, struct widget *widget, void *data)
static void gui_internal_button (void *data, int pressed, int button, struct point *p)
Handles mouse clicks and scroll wheel movement.
static void gui_internal_setup (struct gui_priv *this)
static void gui_internal_resize (void *data, int w, int h)
static void gui_internal_keynav_point (struct widget *w, int dx, int dy, struct point *p)
static void gui_internal_keynav_find_closest (struct widget *wi, struct point *p, int dx, int dy, int *distance, struct widget **result)
static void gui_internal_keypress (void *data, char *key)
static int gui_internal_set_graphics (struct gui_priv *this, struct graphics *gra)
static void gui_internal_disable_suspend (struct gui_priv *this)
static void gui_internal_add_callback (struct gui_priv *priv, struct callback *cb)
static void gui_internal_remove_callback (struct gui_priv *priv, struct callback *cb)
static enum flags gui_internal_get_flags (struct widget *widget)
static void gui_internal_set_flags (struct widget *widget, enum flags flags)
static int gui_internal_get_state (struct widget *widget)
static void gui_internal_set_state (struct widget *widget, int state)
static void gui_internal_set_func (struct widget *widget, void(*func)(struct gui_priv *priv, struct widget *widget, void *data))
static void gui_internal_set_data (struct widget *widget, void *data)
static void gui_internal_set_default_background (struct gui_priv *this, struct widget *widget)
int line_intersection (struct coord *a1, struct coord *a2, struct coord *b1, struct coord *b2, struct coord *res)
finds the intersection point of 2 lines
struct heightline * item_get_heightline (struct item *item)
void gui_internal_route_update (struct gui_priv *this, struct navit *navit, struct vehicle *v)
Called when the route is updated.
void gui_internal_route_screen_free (struct gui_priv *this_, struct widget *w)
Called when the route screen is closed (deallocated).
void gui_internal_populate_route_table (struct gui_priv *this, struct navit *navit)
Populates the route table with route information.
static struct gui_priv * gui_internal_new (struct navit *nav, struct gui_methods *meth, struct attr **attrs, struct gui *gui)
void plugin_init (void)
Variables
const int LARGE_PROFILE =0
const int MEDIUM_PROFILE =1
const int SMALL_PROFILE =2
static struct gui_config_settings config_profiles []
struct gui_methods gui_internal_methods
static struct gui_internal_methods gui_internal_methods_ext
static struct
gui_internal_widget_methods gui_internal_widget_methods
Function Documentation
static int gui_internal_add_attr (struct gui_priv * this, struct attr * attr) static
References g_free(), g_strdup(), attr::str, attr::type, and attr::u.
static void gui_internal_add_callback (struct gui_priv * priv, struct callback * cb) static
References callback_list_add(), and gui_priv::cbl.
static void gui_internal_add_vehicle_profile (struct gui_priv * this, struct widget * parent, struct vehicle * v, struct vehicleprofile * profile) static
Adds the vehicle profile to the GUI, allowing the user to pick a profile for the currently selected vehicle.
References _, _n, active, attr_search(), dbg, flags_fill, g_new0, g_strdup_printf(), gravity_left_center, gui_internal_button_new_with_callback(), gui_internal_cmd_set_active_profile(), gui_internal_widget_append(), image_new_xs(), label, lvl_debug, lvl_error, name, NULL, orientation_horizontal, vehicle_and_profilename::profilename, attr::str, attr::u, vehicle_and_profilename::vehicle, and vehicle_get_attr().
Referenced by gui_internal_menu_vehicle_settings().
void gui_internal_apply_config (struct gui_priv * this)
Applies the configuration values to this based on the settings specified in the configuration file (this->config) and the most approriate default profile based on screen resolution.
This function should be run after this->root is setup and could be rerun after the window is resized.
Author
Steve Singer ssing.nosp@m.er_p.nosp@m.g@sym.nosp@m.pati.nosp@m.co.ca (09/2008)
References dbg, gui_config_settings::font_size, graphics_font_new(), graphics_named_font_new(), i, gui_config_settings::icon_l, gui_config_settings::icon_s, gui_config_settings::icon_xs, LARGE_PROFILE, lvl_debug, MEDIUM_PROFILE, SMALL_PROFILE, and gui_config_settings::spacing.
Referenced by gui_internal_cmd2(), and gui_internal_menu().
void gui_internal_back (struct gui_priv * this, struct widget * w, void * data)
References gui_internal_prune_menu_count().
Referenced by gui_internal_cmd2_back(), gui_internal_cmd_pois_more(), gui_internal_keypress(), gui_internal_menu(), and gui_internal_search().
static void gui_internal_button (void * data, int pressed, int button, struct point * p) static
Handles mouse clicks and scroll wheel movement.
Author
Martin Schaller (04/2008), Stefan Klumpp (04/2008)
References command_evaluate(), data, dbg, draw_mode_begin, draw_mode_end, event_main_loop_has_quit(), graphics_draw_mode(), gui_internal_call_highlighted(), gui_internal_check_exit(), gui_internal_cmd_menu(), gui_internal_dbus_signal(), gui_internal_gesture_do(), gui_internal_gesture_get_vector(), gui_internal_gesture_ring_add(), gui_internal_gesture_ring_clear(), gui_internal_highlight(), gui_internal_set_click_coord(), gui_internal_set_position_coord(), lvl_debug, navit_handle_button(), NULL, and p.
Referenced by gui_internal_set_graphics().
static void gui_internal_button_attr_callback (struct gui_priv * this, struct widget * w) static
References gui_internal_button_attr_update(), and gui_internal_widget_render().
Referenced by gui_internal_button_map_attr_new(), and gui_internal_button_navit_attr_new().
static void gui_internal_button_attr_pressed (struct gui_priv * this, struct widget * w, void * data) static
References gui_internal_button_attr_update(), widget::instance, widget::is_on, widget::off, widget::on, and widget::set_attr.
Referenced by gui_internal_button_map_attr_new(), and gui_internal_button_navit_attr_new().
static int gui_internal_button_attr_update (struct gui_priv * this, struct widget * w) static
References widget::children, widget::data, attr::data, widget::deflt, g_list_first(), widget::get_attr, graphics_image_free(), if(), image_new_xs(), widget::img, widget::instance, widget::is_on, NULL, widget::off, widget::on, widget::redraw, widget::state, STATE_SENSITIVE, attr::type, and attr::u.
Referenced by gui_internal_button_attr_callback(), gui_internal_button_attr_pressed(), gui_internal_button_map_attr_new(), and gui_internal_button_navit_attr_new().
struct widget* gui_internal_button_map_attr_new (struct gui_priv * this, const char * text, enum flags flags , struct map * map, struct attr * on, struct attr * off, int deflt)
References callback_cast, callback_new_attr_2, widget::cb, widget::deflt, widget::get_attr, gui_internal_button_attr_callback(), gui_internal_button_attr_pressed(), gui_internal_button_attr_update(), gui_internal_button_new_with_callback(), image, image_new_xs(), widget::instance, int, map_add_callback(), map_get_attr(), map_remove_callback(), map_set_attr(), NULL, widget::off, widget::on, widget::redraw, widget::remove_cb, widget::set_attr, attr::type, and void().
Referenced by gui_internal_cmd2_setting_maps(), and gui_internal_cmd_map_download().
struct widget* gui_internal_button_navit_attr_new (struct gui_priv * this, const char * text, enum flags flags , struct attr * on, struct attr * off)
References callback_cast, callback_new_attr_2, widget::cb, widget::get_attr, gui_internal_button_attr_callback(), gui_internal_button_attr_pressed(), gui_internal_button_attr_update(), gui_internal_button_new_with_callback(), image, image_new_xs(), widget::instance, int, navit_add_callback(), navit_get_attr(), navit_remove_callback(), navit_set_attr(), NULL, widget::off, widget::on, widget::remove_cb, widget::set_attr, attr::type, and void().
Referenced by gui_internal_cmd2_setting_layout(), and gui_internal_cmd2_setting_rules().
static void gui_internal_call_highlighted (struct gui_priv * this) static
References gui_internal_reason_click.
Referenced by gui_internal_button(), and gui_internal_keypress().
void gui_internal_call_linked_on_finish (struct gui_priv * this, struct widget * wm, void * data)
Generic notification function for Editable widgets to call Another widget notification function when Enter is pressed in editable field. The Editable widget should have data member pointing to the Another widget.
References widget::data, data, widget::func, gui_internal_reason_keypress_finish, widget::reason, and widget::w.
Referenced by gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_enter_coord(), gui_internal_cmd_log(), and gui_internal_cmd_rename_bookmark().
void gui_internal_check_exit (struct gui_priv * this)
References graphics_overlay_disable(), gui_internal_search_idle_end(), gui_internal_search_list_destroy(), navit_block(), navit_draw(), and navit_draw_displaylist().
Referenced by gui_internal_button(), gui_internal_cmd2_back(), gui_internal_cmd2_back_to_map(), gui_internal_cmd_bookmarks(), gui_internal_cmd_log_do(), and gui_internal_keypress().
void gui_internal_cmd_bookmarks (struct gui_priv * this, struct widget * wm, void * data)
The "Bookmarks" section of the OSD
References _, widget::background, background, attr::bookmarks, bookmarks_get_bookmark_count(), bookmarks_get_item(), bookmarks_get_projection(), bookmarks_item_cwd(), bookmarks_item_rewind(), bookmarks_move_down(), bookmarks_move_root(), bookmarks_move_up(), widget::c, widget::data, dbg, flags_expand, flags_fill, g_free(), g_strdup(), g_strdup_printf(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_check_exit(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_delete_bookmark_folder(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_paste_bookmark(), gui_internal_cmd_position(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_prune_menu_count(), gui_internal_widget_append(), gui_internal_widget_destroy(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), image_new_xs(), item, item_attr_get(), item_coord_get(), lvl_info, item::map, map_convert_string_tmp(), widget::name, navit_get_attr(), navit_get_destination_count(), NULL, orientation_horizontal, orientation_vertical, widget::prefix, pcoord::pro, row, attr::str, widget::text, item::type, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_bookmarks(), and gui_internal_cmd_bookmarks().
static void gui_internal_cmd_delete_bookmark (struct gui_priv * this, struct widget * wm, void * data) static
References attr::bookmarks, bookmarks_delete_bookmark(), g_list_last(), g_list_previous, gui_internal_prune_menu(), navit_get_attr(), NULL, widget::text, and attr::u.
Referenced by gui_internal_cmd_position_do().
static void gui_internal_cmd_delete_waypoint (struct gui_priv * this, struct widget * wm, void * data) static
References g_alloca, gui_internal_prune_menu(), i, widget::item, item, item_coord_get_pro(), item_is_equal_id, item::map, map_rect_destroy(), map_rect_get_item(), map_rect_new(), navit_get_destination_count(), navit_get_destinations(), navit_set_destinations(), NULL, pcoord::pro, projection_mg, item::type, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd_position_do().
void gui_internal_cmd_enter_coord_clicked (struct gui_priv * this, struct widget * widget, void * data)
References widget::data, dbg, gui_internal_cmd_enter_coord_do(), and lvl_debug.
Referenced by gui_internal_cmd_enter_coord().
static void gui_internal_cmd_enter_coord_do (struct gui_priv * this, struct widget * widget) static
References widget::c, dbg, g_ascii_strup(), g_free(), g_strdup_printf(), gui_internal_cmd_position(), gui_internal_coordinate_parse(), lat, lvl_debug, NULL, pcoord_parse(), projection_mg, and widget::text.
Referenced by gui_internal_cmd_enter_coord_clicked().
static void gui_internal_cmd_insert_destination (struct gui_priv * this, struct widget * wm, void * data) static
References _, gui_internal_cmd_insert_destination_do(), and gui_internal_select_waypoint().
Referenced by gui_internal_cmd_position_do().
static void gui_internal_cmd_insert_destination_do (struct gui_priv * this, struct widget * wm, void * data) static
References widget::c, data, widget::datai, g_alloca, gui_internal_prune_menu(), i, name, navit_add_destination_description(), navit_get_destination_count(), navit_get_destinations(), navit_set_destinations(), NULL, and startup::pos.
Referenced by gui_internal_cmd_insert_destination().
void gui_internal_cmd_log_clicked (struct gui_priv * this, struct widget * widget, void * data)
References widget::data, and gui_internal_cmd_log_do().
Referenced by gui_internal_cmd_log().
static void gui_internal_cmd_log_do (struct gui_priv * this, struct widget * widget) static
References g_free(), gui_internal_check_exit(), gui_internal_prune_menu(), navit_textfile_debug_log(), navit_textfile_debug_log_at(), NULL, and widget::text.
Referenced by gui_internal_cmd_log_clicked().
void gui_internal_cmd_main_menu (struct gui_priv * this, struct widget * wm, void * data)
References gui_internal_html_main_menu(), gui_internal_prune_menu(), menu_data::href, widget::menu_data, and widget::w.
Referenced by gui_internal_top_bar().
void gui_internal_cmd_map_download (struct gui_priv * this, struct widget * wm, void * data)
References _, bbox(), data, dbg, description(), flags_expand, flags_fill, g_free(), g_strdup(), g_strdup_printf(), gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_button_map_attr_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), lvl_debug, widget::name, NULL, attr::num, orientation_horizontal, orientation_vertical, widget::prefix, size, widget::spy, attr::type, attr::u, and widget::w.
Referenced by gui_internal_cmd2_setting_maps(), and gui_internal_cmd_map_download().
static void gui_internal_cmd_map_download_do (struct gui_priv * this, struct widget * wm, void * data) static
References _, map_selection::c_rect, data, dbg, flags_expand, flags_fill, g_free(), g_strdup_printf(), gravity_top_center, gui_internal_box_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), item, coord_geo::lat, coord_geo::lng, coord_rect::lu, lvl_info, map_rect_destroy(), map_rect_get_item(), map_rect_new(), item_range::max, widget::name, map_selection::next, NULL, map_selection::order, orientation_vertical, widget::prefix, projection_mg, map_selection::range, coord_rect::rl, widget::spy, widget::text, transform_from_geo(), map_selection::u, and widget::w.
Referenced by gui_internal_cmd_map_download().
char* gui_internal_cmd_match_expand (char * pattern, struct attr ** in)
References attr_to_text(), g_free(), g_malloc(), g_strdup(), NULL, and p.
Referenced by gui_internal_cmd2_set().
void gui_internal_cmd_menu (struct gui_priv * this, int ignore, char * href)
References dbg, gui_internal_enter(), gui_internal_enter_setup(), gui_internal_html_load_href(), gui_internal_html_main_menu(), and lvl_debug.
Referenced by gui_internal_button(), gui_internal_cmd_menu2(), and gui_internal_keypress().
void gui_internal_cmd_position (struct gui_priv * this, struct widget * wm, void * data)
References widget::c, widget::data, gui_internal_cmd_position_do(), gui_internal_cmd_set_destination(), gui_internal_search_house_number_in_street(), gui_internal_search_town_in_country(), widget::name, NULL, and widget::text.
Referenced by gui_internal_cmd2_waypoints(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord_do(), gui_internal_cmd_formerdests(), gui_internal_cmd_pois_item(), gui_internal_create_resultlist_entry(), and gui_internal_populate_route_table().
void gui_internal_cmd_position_do (struct gui_priv * this, struct pcoord * pc_in, struct coord_geo * g_in, struct widget * wm, const char * name, int flags)
Displays the commands available for a location.
This displays the available commands for the given location in a dialog from which the user can choose an action. The location can be supplied either in projected coordinates via the
pc_in
argument or in WGS84 coordinates (i.e. latitude and longitude in degrees) via the
g_in
argument. One of these must be supplied, the other should be
NULL
.
Parameters
this The internal GUI instance
pc_in Projected coordinates of the position
g_in WGS84 coordinates of the position
wm
name The display name for the position
flags Flags specifying the operations available from the GUI
References _, widget::c, widget::data, _GList::data, widget::data_free, dbg, display(), displaylist_get_clicked_list(), displaylist_get_selection(), flags_expand, flags_fill, g_free(), g_free_func, g_list_free(), g_list_next, g_strdup(), graphics_displayitem_get_item(), graphics_displaylist_close(), graphics_displaylist_open(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_button_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_copy_bookmark(), gui_internal_cmd_cut_bookmark(), gui_internal_cmd_delete_bookmark(), gui_internal_cmd_delete_waypoint(), gui_internal_cmd_insert_destination(), gui_internal_cmd_paste_bookmark(), gui_internal_cmd_pois(), gui_internal_cmd_pois_item(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_results_map_clean(), gui_internal_cmd_results_to_map(), gui_internal_cmd_set_destination(), gui_internal_cmd_set_position(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_cmd_view_on_map(), gui_internal_coordinates(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_search_house_number_in_street(), gui_internal_search_street_in_town(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), item::id_hi, item::id_lo, image_new_xs(), widget::item, item, item_attr_get(), item_to_name(), lvl_info, item::map, map_convert_string_tmp(), map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), map_selection_destroy(), widget::name, navit_get_attr(), navit_get_destination_count(), navit_get_displaylist(), navit_get_trans(), NULL, orientation_horizontal, orientation_vertical, pcoord::pro, attr::projection, row, widget::selection_id, attr::str, widget::text, attr::text, trans, transform(), transform_from_geo(), transform_to_geo(), item::type, attr::u, attr::vehicle, vehicle_get_attr(), widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_position(), and gui_internal_cmd_position().
static void gui_internal_cmd_results_map_clean (struct gui_priv * this, struct widget * wm, void * data) static
References gui_internal_cmd_results_to_map(), gui_internal_prune_menu(), navit_draw(), and NULL.
Referenced by gui_internal_cmd_position_do().
static void gui_internal_cmd_results_to_map (struct gui_priv * this, struct widget * wm, void * data) static
References attr::attr_types, attrmap, attr::attrs, widget::c, c, change_mode_modify, widget::children, coord_rect_extend(), _GList::data, dbg, g_free(), g_list_next, g_new0, gui_internal_prune_menu(), i, item, item_attr_set(), item_coord_set(), item_type_set(), coord_rect::lu, lvl_info, lvl_warning, attr::map, map_new(), map_rect_create_item(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), mapset_add_attr(), mapset_get_map_by_name(), widget::name, navit_get_mapset(), navit_set_attr(), navit_zoom_to_rect(), NULL, attr::num, widget::parent, coord_rect::rl, attr::str, attr::type, widget::type, types, attr::u, widget::w, widget_table, widget_table_row, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd_position_do(), and gui_internal_cmd_results_map_clean().
void gui_internal_cmd_return (struct gui_priv * this, struct widget * wm, void * data)
References widget::data, and gui_internal_prune_menu().
Referenced by gui_internal_top_bar().
static void gui_internal_cmd_set_active_profile (struct gui_priv * this, struct widget * wm, void * data) static
Reacts to a button press that changes a vehicle's active profile.
See Also
gui_internal_add_vehicle_profile
References data, dbg, gui_internal_is_active_vehicle(), gui_internal_menu_vehicle_settings(), gui_internal_prune_menu_count(), lvl_debug, lvl_error, navit_set_attr(), navit_set_vehicleprofile_name(), NULL, vehicle_and_profilename::profilename, save_vehicle_xml(), attr::str, attr::type, attr::u, attr::vehicle, vehicle_and_profilename::vehicle, vehicle_get_attr(), and vehicle_set_attr().
Referenced by gui_internal_add_vehicle_profile().
static void gui_internal_cmd_set_active_vehicle (struct gui_priv * this, struct widget * wm, void * data) static
References widget::data, and navit_set_attr().
Referenced by gui_internal_menu_vehicle_settings().
static void gui_internal_cmd_set_destination (struct gui_priv * this, struct widget * wm, void * data) static
References widget::c, data, dbg, gui_internal_prune_menu(), lvl_info, name, navit_set_attr(), navit_set_destination(), navit_zoom_to_route(), NULL, attr::num, pcoord::pro, attr::type, attr::u, pcoord::x, and pcoord::y.
Referenced by gui_internal_cmd_position(), and gui_internal_cmd_position_do().
static void gui_internal_cmd_set_position (struct gui_priv * this, struct widget * wm, void * data) static
References widget::c, gui_internal_prune_menu(), navit_set_attr(), navit_set_position(), NULL, attr::type, attr::u, and attr::vehicle.
Referenced by gui_internal_cmd_position_do().
static void gui_internal_cmd_show_nmea_data (struct gui_priv * this, struct widget * wm, void * data) static
References _, widget::data, flags_expand, flags_fill, gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_menu(), gui_internal_menu_data(), gui_internal_menu_render(), gui_internal_text_new(), gui_internal_widget_append(), NULL, orientation_vertical, menu_data::redisplay, menu_data::redisplay_widget, attr::str, attr::u, vehicle_get_attr(), and widget::w.
Referenced by gui_internal_menu_vehicle_settings().
static void gui_internal_cmd_show_satellite_status (struct gui_priv * this, struct widget * wm, void * data) static
References _, widget::data, flags_expand, flags_fill, g_free(), g_strdup(), g_strdup_printf(), gravity_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_data(), gui_internal_menu_render(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), i, attr::item, item_attr_get(), NULL, attr::num, orientation_vertical, menu_data::redisplay, menu_data::redisplay_widget, row, types, attr::u, vehicle_get_attr(), and widget::w.
Referenced by gui_internal_menu_vehicle_settings().
void gui_internal_cmd_vehicle_settings (struct gui_priv * this, struct widget * wm, void * data)
References widget::data, gui_internal_menu_vehicle_settings(), and widget::text.
Referenced by gui_internal_cmd2_setting_vehicle().
static void gui_internal_cmd_view_attribute_details (struct gui_priv * this, struct widget * wm, void * data) static
References _, widget::datai, flags_expand, flags_fill, g_free(), g_strdup_printf(), gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_view_in_browser(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), i, item::id_hi, item::id_lo, image_new_xs(), widget::item, item, item_attr_get(), LONGLONG_FMT, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), widget::name, NULL, attr::num64, orientation_horizontal, orientation_vertical, attr::text, attr::type, attr::u, and widget::w.
Referenced by gui_internal_cmd_view_attributes().
static void gui_internal_cmd_view_attributes (struct gui_priv * this, struct widget * wm, void * data) static
References _, attr_to_name(), attr_to_text(), widget::datai, dbg, flags_expand, flags_fill, g_free(), g_strdup(), g_strdup_printf(), gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_button_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_view_attribute_details(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), item::id_hi, item::id_lo, widget::item, item, item_attr_get(), item_to_name(), lvl_info, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), widget::name, NULL, orientation_horizontal, orientation_vertical, attr::text, item::type, attr::type, and widget::w.
Referenced by gui_internal_cmd_position_do().
static void gui_internal_cmd_view_in_browser (struct gui_priv * this, struct widget * wm, void * data) static
References dbg, g_free(), g_strdup_printf(), item::id_hi, item::id_lo, widget::item, item, item_attr_get(), lvl_error, lvl_info, item::map, map_convert_string_tmp(), map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), widget::name, NULL, attr::str, and attr::u.
Referenced by gui_internal_cmd_position_do(), and gui_internal_cmd_view_attribute_details().
static void gui_internal_cmd_view_on_map (struct gui_priv * this, struct widget * wm, void * data) static
References widget::c, graphics_add_selection(), graphics_clear_selection(), gui_internal_prune_menu(), widget::item, navit_set_center(), NULL, item::type, and type.
Referenced by gui_internal_cmd_position_do().
static int gui_internal_coordinate_parse (char * s, char plus, char minus, double * x) static
Converts one geo coordinate in human readable form to double value.
Author
Martin Bruns (05/2012), mdankov
References dbg, lvl_debug, and NULL.
Referenced by gui_internal_cmd_enter_coord_do().
static void gui_internal_dbus_signal (struct gui_priv * this, struct point * p) static
References attr_generic_add_attr(), attr_list_free(), attr::callback_list, callback_list_call_attr_4, display(), graphics_displayitem_get_displayed(), graphics_displayitem_get_item(), graphics_displayitem_within_dist(), graphics_displaylist_close(), graphics_displaylist_next(), graphics_displaylist_open(), item::id_hi, item::id_lo, item_attr_get(), item_is_point, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), navit_get_attr(), navit_get_displaylist(), NULL, and attr::u.
Referenced by gui_internal_button().
static void gui_internal_disable_suspend (struct gui_priv * this) static
void gui_internal_enter (struct gui_priv * this, int ignore)
References background, graphics_overlay_disable(), and navit_block().
Referenced by gui_internal_cmd2(), gui_internal_cmd_log(), and gui_internal_cmd_menu().
void gui_internal_enter_setup (struct gui_priv * this)
References gui_internal_set_position_coord().
Referenced by gui_internal_cmd2(), gui_internal_cmd_log(), and gui_internal_cmd_menu().
void gui_internal_evaluate (struct gui_priv * this, const char * command)
References command_evaluate().
Referenced by gui_internal_html_command(), gui_internal_html_submit(), and gui_internal_html_text().
static int gui_internal_get_attr (struct gui_priv * this, enum attr_type type, struct attr * attr) static
References fullscreen(), attr::navit, NULL, attr::num, type, attr::type, and attr::u.
static enum flags gui_internal_get_flags (struct widget * widget) static
References widget::flags.
static int gui_internal_get_state (struct widget * widget) static
References widget::state.
static int gui_internal_is_active_vehicle (struct gui_priv * this, struct vehicle * vehicle) static
Figures out whether the given vehicle is the active vehicle.
Returns
true if the vehicle is active, false otherwise.
References navit_get_attr(), NULL, attr::u, attr::vehicle, and vehicle.
Referenced by gui_internal_cmd_set_active_profile(), and gui_internal_menu_vehicle_settings().
struct widget* gui_internal_keyboard (struct gui_priv * this, int mode)
Creates a keyboard widget.
This function creates a widget to display the internal GUI keyboard.
The
mode
argument specifies the type of keyboard which should initially be displayed. Refer to vkbd_mode for a list of possible modes and their meaning.
Parameters
this The internal GUI instance
mode The mode for the keyboard
Returns
A new keyboard widget
Referenced by gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_enter_coord(), gui_internal_cmd_log(), gui_internal_cmd_pois_filter(), gui_internal_cmd_rename_bookmark(), gui_internal_html_menu(), and gui_internal_search().
struct widget* gui_internal_keyboard_show_native (struct gui_priv * this, struct widget * w, int mode, char * lang)
Shows the platform's native on-screen keyboard or other input method.
This method is a wrapper around the corresponding method of the graphics plugin, which takes care of all platform-specific details. In particular, it is up to the graphics plugin to determine how to handle the request: it may show its on-screen keyboard or another input method (such as stroke recognition). It may choose to simply ignore the request, which will typically occur when a hardware keyboard (or other hardware input) is available.
The platform's native input method may obstruct parts of Navit's UI. To prevent parts of the UI from becoming unreachable, this method will insert an empty box widget in the appropriate size at the appropriate position, provided the graphics plugin reports the correct values. Otherwise a zero-size widget is inserted. If the graphics driver decides not to display an on-screen input method, no widget will be created and the return value will be
NULL
.
The widget's
wfree
function, to be called when the widget is destroyed, will be used to hide the platform keyboard when it is no longer needed.
Parameters
this The internal GUI instance
w The parent of the widget requiring text input
mode The requested keyboard mode
lang The language for text input, used to select a keyboard layout
Returns
The placeholder widget for the on-screen keyboard, may be
NULL
Referenced by gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_enter_coord(), gui_internal_cmd_log(), gui_internal_cmd_pois_filter(), gui_internal_cmd_rename_bookmark(), gui_internal_html_menu(), and gui_internal_search().
static void gui_internal_keynav_find_closest (struct widget * wi, struct point * p, int dx, int dy, int * distance, struct widget ** result) static
References widget::children, _GList::data, dbg, g_list_next, gui_internal_keynav_point(), widget::h, lvl_debug, widget::p, widget::state, STATE_SENSITIVE, widget::w, point::x, and point::y.
Referenced by gui_internal_keynav_highlight_next().
static int gui_internal_keynav_find_next (struct widget * wi, struct widget * current_highlight, struct widget ** result) static
References widget::children, _GList::data, g_list_next, and gui_internal_keynav_find_next_sensitive_child().
Referenced by gui_internal_keynav_highlight_next().
static struct widget * gui_internal_keynav_find_next_sensitive_child (struct widget * wi) static
References widget::children, _GList::data, g_list_next, NULL, widget::state, STATE_OFFSCREEN, and STATE_SENSITIVE.
Referenced by gui_internal_keynav_find_next().
static int gui_internal_keynav_find_prev (struct widget * wi, struct widget * current_highlight, struct widget ** result) static
References widget::children, _GList::data, g_list_next, widget::state, STATE_OFFSCREEN, and STATE_SENSITIVE.
Referenced by gui_internal_keynav_highlight_next().
static void gui_internal_keynav_highlight_next (struct gui_priv * this, int dx, int dy, int rotary) static
Move keyboard focus to the next widget.
Move keyboard focus to the appropriate next widget, depending on the direction of focus movement.
Parameters
this GUI context
this dx horizontal movement (-1=left, +1=right), unless rotary==1
this dy vertical movement (+1=up, -1=down)
rotary (0/1) input from rotary encoder - dx indicates forwards/backwards movement through all widgets
References _GList::data, dbg, g_list_last(), gui_internal_highlight_do(), gui_internal_keynav_find_closest(), gui_internal_keynav_find_next(), gui_internal_keynav_find_prev(), gui_internal_keynav_point(), gui_internal_say(), lvl_debug, NULL, point::x, and point::y.
Referenced by gui_internal_keypress().
static void gui_internal_keynav_point (struct widget * w, int dx, int dy, struct point * p) static
References widget::h, widget::p, widget::w, point::x, and point::y.
Referenced by gui_internal_keynav_find_closest(), and gui_internal_keynav_highlight_next().
static void gui_internal_keypress (void * data, char * key) static
References _GList::data, data, draw_mode_begin, draw_mode_end, event_main_loop_has_quit(), g_list_last(), g_list_length(), graphics_draw_mode(), gui_internal_back(), gui_internal_call_highlighted(), gui_internal_check_exit(), gui_internal_cmd_menu(), gui_internal_keynav_highlight_next(), gui_internal_keypress_do(), gui_internal_prune_menu(), gui_internal_set_click_coord(), gui_priv::h, navit_get_trans(), NAVIT_KEY_BACK, NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_MENU, NAVIT_KEY_PAGE_DOWN, NAVIT_KEY_PAGE_UP, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, NAVIT_KEY_ZOOM_OUT, navit_set_center_screen(), navit_zoom_in(), navit_zoom_out(), NULL, transform_get_size(), gui_priv::w, point::x, and point::y.
Referenced by gui_internal_set_graphics().
void gui_internal_keypress_do (struct gui_priv * this, char * key)
References widget::data, _GList::data, dbg, widget::func, g_free(), g_list_last(), g_strdup(), g_strdup_printf(), g_utf8_prev_char(), gui_internal_find_widget(), gui_internal_highlight(), gui_internal_keyboard_to_lower_case(), gui_internal_keyboard_to_upper_case(), gui_internal_menu_data(), gui_internal_reason_keypress, gui_internal_reason_keypress_finish, gui_internal_widget_render(), gui_internal_widget_table_top_row(), widget::h, lvl_debug, lvl_info, NAVIT_KEY_BACKSPACE, NAVIT_KEY_RETURN, NULL, widget::p, widget::reason, menu_data::search_list, widget::state, STATE_CLEAR, STATE_EDIT, widget::text, widget::w, point::x, and point::y.
Referenced by gui_internal_cmd_keypress(), and gui_internal_keypress().
void gui_internal_leave (struct gui_priv * this)
References draw_mode_end, and graphics_draw_mode().
Referenced by gui_internal_cmd_log().
static int gui_internal_match (const char * pattern, const char * string) static
References p.
Referenced by gui_internal_set().
void gui_internal_menu_vehicle_settings (struct gui_priv * this, struct vehicle * v, char * name)
References _, callback_list_call_attr_2, cbl, _GList::data, flags_expand, flags_fill, g_list_next, gravity_left, gravity_left_center, gravity_top_center, gui_internal_add_vehicle_profile(), gui_internal_button_new_with_callback(), gui_internal_cmd_set_active_vehicle(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_is_active_vehicle(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), image_new_xs(), navit_get_vehicleprofiles(), NULL, orientation_horizontal, orientation_vertical, profile, row, vehicle_get_attr(), and widget::w.
Referenced by gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_set_active_profile(), and gui_internal_cmd_vehicle_settings().
static void gui_internal_motion (void * data, struct point * p) static
References callback_cast, callback_new_1, widget::children, gui_priv::current, data, event_add_timeout(), gui_internal_motion_cb(), gui_priv::motion_timeout_callback, gui_priv::motion_timeout_event, gui_priv::nav, navit_handle_motion(), p, gui_priv::pressed, and gui_priv::root.
Referenced by gui_internal_set_graphics().
static void gui_internal_motion_cb (struct gui_priv * this) static
References table_data::bottom_row, scroll_buttons::button_box, widget::data, _GList::data, draw_mode_begin, draw_mode_end, graphics_draw_mode(), gui_internal_gesture_get_vector(), gui_internal_gesture_ring_add(), gui_internal_highlight(), gui_internal_table_hide_rows(), gui_internal_widget_render(), gui_internal_widget_table_next_row(), gui_internal_widget_table_prev_row(), widget::h, NULL, widget::p, widget::parent, table_data::scroll_buttons, widget::state, STATE_SCROLLABLE, table_data::top_row, widget::type, widget_table, widget_table_row, and point::y.
Referenced by gui_internal_motion().
static struct gui_priv* gui_internal_new (struct navit * nav, struct gui_methods * meth, struct attr ** attrs, struct gui * gui) static
References attr_search(), background_color, callback_list_new(), cbl, attr::color, data, fullscreen(), g_new0, g_strdup(), navit::gui, attr::gui, gui_internal_command_init(), gui_internal_methods, gui_internal_methods_ext, gui_internal_widget_methods, NULL, attr::num, attr::str, and attr::u.
Referenced by plugin_init().
void gui_internal_populate_route_table (struct gui_priv * this, struct navit * navit)
Populates the route table with route information.
Parameters
this The gui context
navit The navit object
References attr_format_default, attr_format_with_units, attr_to_text_ext(), widget::c, widget::data, _GList::data, flags_fill, widget::func, g_free(), g_strdup_printf(), gravity_left, gui_internal_cmd_position(), gui_internal_label_new(), gui_internal_widget_append(), gui_internal_widget_table_clear(), gui_internal_widget_table_row_new(), gui_internal_widget_table_set_top_row(), gui_internal_widget_table_top_row(), item::id_hi, item::id_lo, widget::item, item, item_attr_get(), item_coord_get(), label, length, item::map, map_convert_string_tmp(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), navigation_get_map(), navit_get_attr(), navit_get_navigation(), NULL, orientation_horizontal, pcoord::pro, attr::route, route_get_attr(), route_data::route_table, row, widget::state, STATE_SENSITIVE, attr::str, time(), attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_route_description(), and gui_internal_route_update().
static void gui_internal_remove_callback (struct gui_priv * priv, struct callback * cb) static
References callback_list_remove(), and gui_priv::cbl.
static void gui_internal_resize (void * data, int w, int h) static
References changed(), widget::children, data, dbg, gui_priv::gra, graphics_get_data(), gui_internal_html_main_menu(), gui_internal_menu_render(), gui_internal_setup(), gui_priv::h, widget::h, lvl_debug, gui_priv::nav, navit_handle_resize(), gui_priv::root, gui_priv::w, and widget::w.
Referenced by gui_internal_set_graphics().
void gui_internal_route_screen_free (struct gui_priv * this_, struct widget * w)
Called when the route screen is closed (deallocated).
The main purpose of this function is to remove the widgets from references route_data because those widgets are about to be freed.
References g_free(), NULL, gui_priv::route_data, route_data::route_showing, and route_data::route_table.
Referenced by gui_internal_cmd2_route_description().
void gui_internal_route_update (struct gui_priv * this, struct navit * navit, struct vehicle * v)
Called when the route is updated.
References draw_mode_begin, draw_mode_end, graphics_draw_mode(), gui_internal_menu_render(), gui_internal_populate_route_table(), and route_data::route_showing.
Referenced by gui_internal_cmd2_route_description().
void gui_internal_say (struct gui_priv * this, struct widget * w, int questionmark)
References g_free(), g_strdup_printf(), widget::name, navit_say(), widget::speech, and widget::text.
Referenced by gui_internal_keynav_highlight_next(), gui_internal_menu_render(), and gui_internal_prune_menu_do().
void gui_internal_select_waypoint (struct gui_priv * this, const char * title, const char * hint, struct widget * wm_, void(*)(struct gui_priv *priv, struct widget *widget, void *data) cmd, void * data)
References _, widget::c, widget::datai, flags_expand, flags_fill, g_free(), g_strdup_printf(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), i, image_new_xs(), widget::item, item, item_attr_get(), item_coord_get(), item::map, map_convert_string_tmp(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), navit_get_destination_count(), navit_get_route(), NULL, orientation_horizontal, orientation_vertical, pcoord::pro, route_get_map(), row, attr::str, item::type, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_waypoints(), and gui_internal_cmd_insert_destination().
int gui_internal_set (char * remove, char * add)
References dbg, fprintf(), g_free(), g_strjoin(), gui_internal_match(), lvl_debug, navit_get_user_data_directory(), NULL, rename(), size, TRUE, and unlink().
Referenced by gui_internal_cmd2_set().
static int gui_internal_set_attr (struct gui_priv * this, struct attr * attr) static
References attr_to_name(), dbg, draw_mode_begin, draw_mode_end, fullscreen(), g_free(), g_strdup(), graphics_draw_mode(), lvl_error, attr::num, attr::str, attr::type, and attr::u.
void gui_internal_set_click_coord (struct gui_priv * this, struct point * p)
References attr_dup(), attr_free(), attr::coord_geo, dbg, lvl_debug, navit_get_trans(), NULL, trans, transform_get_projection(), transform_reverse(), transform_to_geo(), attr::type, attr::u, coord::x, and coord::y.
Referenced by gui_internal_button(), gui_internal_cmd_log(), and gui_internal_keypress().
static void gui_internal_set_data (struct widget * widget, void * data) static
References widget::data, and data.
static void gui_internal_set_default_background (struct gui_priv * this, struct widget * widget) static
References widget::background, and background.
static void gui_internal_set_flags (struct widget * widget, enum flags flags) static
References widget::flags.
static void gui_internal_set_func (struct widget * widget, void(*)(struct gui_priv *priv, struct widget *widget, void *data) func) static
References widget::func.
static int gui_internal_set_graphics (struct gui_priv * this, struct graphics * gra) static
References callback_cast, callback_new_attr_1, dbg, window::fullscreen, fullscreen(), graphics_add_callback(), graphics_get_data(), gui_internal_button(), gui_internal_keypress(), gui_internal_motion(), gui_internal_resize(), gui_internal_setup(), gui_internal_window_closed(), lvl_error, navit_get_ready(), navit_get_trans(), navit_ignore_graphics_events(), trans, and transform_get_size().
static void gui_internal_set_position_coord (struct gui_priv * this) static
References attr_dup(), attr_free(), attr::coord_geo, navit_get_attr(), navit_get_trans(), NULL, trans, transform_from_geo(), transform_get_projection(), attr::u, attr::vehicle, vehicle_get_attr(), coord::x, and coord::y.
Referenced by gui_internal_button(), and gui_internal_enter_setup().
static void gui_internal_set_state (struct widget * widget, int state) static
References widget::state.
static void gui_internal_setup (struct gui_priv * this) static
References background, background_color, buffer, command(), command_evaluate(), file_get_contents(), g_free(), g_malloc(), g_strjoin(), graphics_gc_new(), graphics_gc_set_foreground(), navit_get_user_data_directory(), NULL, size, and TRUE.
Referenced by gui_internal_resize(), and gui_internal_set_graphics().
struct widget* gui_internal_time_help (struct gui_priv * this)
References _, widget::bb, widget::bl, widget::br, widget::bt, flags_fill, gravity_center, gravity_right_center, gravity_right_top, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_label_new(), gui_internal_widget_append(), image_new_l(), localtime(), NULL, orientation_horizontal, orientation_vertical, widget::spx, time(), and widget::w.
Referenced by gui_internal_menu().
static void gui_internal_window_closed (struct gui_priv * this) static
References gui_internal_cmd2_quit(), and NULL.
Referenced by gui_internal_set_graphics().
struct graphics_image* image_new_l (struct gui_priv * this, const char * name)
Displays an image scaled to l (large) size.
Parameters
this Our gui context
name image name
Returns
image_struct Ptr to scaled image struct or NULL if not scaled or found
References image_new_scaled().
Referenced by gui_internal_time_help(), and html_image().
struct graphics_image* image_new_s (struct gui_priv * this, const char * name)
Displays an image scaled to s (small) size.
Parameters
this Our gui context
name image name
Returns
image_struct Ptr to scaled image struct or NULL if not scaled or found
References image_new_scaled().
Referenced by gui_internal_cmd_pois_selector(), gui_internal_top_bar(), and html_image().
static struct graphics_image* image_new_scaled (struct gui_priv * this, const char * name, int w, int h) static
Displays an image scaled to a specific size.
Searches for scaleable and pre-scaled image
Parameters
this Our gui context
name image name
w desired width of image
h desired height of image
Returns
image_struct Ptr to scaled image struct or NULL if not scaled or found
References dbg, g_free(), graphics_icon_path(), graphics_image_new_scaled(), lvl_debug, lvl_error, and NULL.
Referenced by image_new_l(), image_new_s(), and image_new_xs().
struct graphics_image* image_new_xs (struct gui_priv * this, const char * name)
Displays an image scaled to xs (extra small) size.
This image size can be too small to click it on some devices.
Parameters
this Our gui context
name image name
Returns
image_struct Ptr to scaled image struct or NULL if not scaled or found
References image_new_scaled().
Referenced by gui_internal_add_vehicle_profile(), gui_internal_button_attr_update(), gui_internal_button_map_attr_new(), gui_internal_button_navit_attr_new(), gui_internal_cmd2_about(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_log(), gui_internal_cmd_pois_filter(), gui_internal_cmd_pois_item(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_view_attribute_details(), gui_internal_create_resultlist_entry(), gui_internal_menu_vehicle_settings(), gui_internal_poi_icon(), gui_internal_scroll_buttons_init(), gui_internal_search(), gui_internal_select_waypoint(), and html_image().
struct heightline* item_get_heightline (struct item * item)
References heightline::bbox, street_data::c, heightline::c, coord_rect_extend(), street_data::count, heightline::count, g_malloc(), heightline::height, height, i, item_attr_get(), coord_rect::lu, NULL, coord_rect::rl, attr::str, street_data_free(), street_get_data(), and attr::u.
Referenced by gui_internal_cmd2_route_height_profile().
int line_intersection (struct coord * a1, struct coord * a2, struct coord * b1, struct coord * b2, struct coord * res)
finds the intersection point of 2 lines
Parameters
coord a1, a2, b1, b2 : coords of the start and end of the first and the second line
coord res, will become the coords of the intersection if found
Returns
: TRUE if intersection found, otherwise FALSE
References dbg, FALSE, lvl_info, TRUE, coord::x, and coord::y.
Referenced by gui_internal_cmd2_route_height_profile().
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
References gui_internal_new().
char* removecase (char * s)
Get a utf-8 string, return the same prepared for case insensitive search. Result should be g_free()d after use.
References linguistics_casefold().
Referenced by gui_internal_cmd_pois_item_selected(), gui_internal_poi_param_set_filter(), and gui_internal_search_cmp().
static void save_vehicle_xml (struct vehicle * v) static
References ATTR_IS_OBJECT, attr_to_name(), attr_to_text(), g_free(), eval::iter, NULL, printf(), attr::type, vehicle_attr_iter_destroy(), vehicle_attr_iter_new(), and vehicle_get_attr().
Referenced by gui_internal_cmd_set_active_profile().
Variable Documentation
struct gui_config_settings config_profiles[] static
Initial value:
={
      {545,32,48,96,10}
    , {300,32,48,64,3}
      ,{200,16,32,48,2}
}
The default config profiles.
[0] => LARGE_PROFILE (screens 640 in one dimension) [1] => MEDIUM PROFILE (screens larger than 320 in one dimension [2] => Small profile (default)
struct gui_methods gui_internal_methods
Initial value:
= {
        NULL,
        NULL,
        gui_internal_set_graphics,
        NULL,
        NULL,
        NULL,
        gui_internal_disable_suspend,
        gui_internal_get_attr,
        gui_internal_add_attr,
        gui_internal_set_attr,
}
Referenced by gui_internal_new().
struct gui_internal_methods gui_internal_methods_ext static
Initial value:
= {
        gui_internal_add_callback,
        gui_internal_remove_callback,
        gui_internal_menu_render,
        image_new_xs,
        image_new_l,
}
Referenced by gui_internal_new().
struct gui_internal_widget_methods gui_internal_widget_methods static
Initial value:
= {
        gui_internal_widget_append,
        gui_internal_button_new,
        gui_internal_button_new_with_callback,
        gui_internal_box_new,
        gui_internal_label_new,
        gui_internal_image_new,
        gui_internal_keyboard,
        gui_internal_menu,
        gui_internal_get_flags,
        gui_internal_set_flags,
        gui_internal_get_state,
        gui_internal_set_state,
        gui_internal_set_func,
        gui_internal_set_data,
        gui_internal_set_default_background,
}
Referenced by gui_internal_new().
const int LARGE_PROFILE =0
Navit, a modular navigation system. Copyright (C) 2005-2010 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. Indexes into the config_profiles array.
Referenced by gui_internal_apply_config().
const int MEDIUM_PROFILE =1
Referenced by gui_internal_apply_config().
const int SMALL_PROFILE =2
Referenced by gui_internal_apply_config().