navit: gui/gtk/gui_gtk_statusbar.c File Reference
gui_gtk_statusbar.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <gtk/gtk.h>
#include "item.h"
#include "coord.h"
#include "debug.h"
#include "vehicle.h"
#include "callback.h"
#include "route.h"
#include "transform.h"
#include "navit.h"
#include "map.h"
#include "navigation.h"
#include "gui_gtk.h"
#include "navit_nls.h"
Data Structures
struct statusbar_priv
Functions
static const char * status_fix2str (int type)
static void statusbar_route_update (struct statusbar_priv *this, struct navit *navit, struct vehicle *v)
struct statusbar_priv * gui_gtk_statusbar_new (struct gui_priv *gui)
Function Documentation
struct statusbar_priv* gui_gtk_statusbar_new (struct gui_priv * gui)
References _, callback_cast, callback_new_attr_1, FALSE, g_new0, statusbar_priv::gps, statusbar_priv::gui, statusbar_priv::hbox, gui_priv::nav, navit_add_callback(), statusbar_route_update(), TRUE, gui_priv::vbox, and statusbar_priv::vehicle_cb.
static const char* status_fix2str (int type) static
References _.
Referenced by statusbar_route_update().
static void statusbar_route_update (struct statusbar_priv * this, struct navit * navit, struct vehicle * v) static
References _, attr::coord_geo, DEGREES_MINUTES_SECONDS, FALSE, FEET_PER_METER, if(), item_attr_get(), KILOMETERS_TO_MILES, coord_geo::lat, lat, coord_geo::lng, localtime(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), navigation_get_map(), navit_get_attr(), navit_get_navigation(), NULL, attr::num, attr::numd, sprintf(), status_fix2str(), time(), TRUE, attr::u, and vehicle_get_attr().
Referenced by gui_gtk_statusbar_new().