navit: gui/internal/gui_internal_gesture.c File Reference
gui_internal_gesture.c File Reference
#include <glib.h>
#include <stdlib.h>
#include "config.h"
#include <sys/time.h>
#include "color.h"
#include "coord.h"
#include "point.h"
#include "callback.h"
#include "graphics.h"
#include "debug.h"
#include "navit.h"
#include "types.h"
#include "navit_nls.h"
#include "event.h"
#include "search.h"
#include "country.h"
#include "track.h"
#include "gui_internal.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_menu.h"
#include "gui_internal_gesture.h"
Functions
void gui_internal_gesture_ring_clear (struct gui_priv *this)
static struct gesture_elem * gui_internal_gesture_ring_get (struct gui_priv *this, int i)
void gui_internal_gesture_ring_add (struct gui_priv *this, struct point *p)
int gui_internal_gesture_get_vector (struct gui_priv *this, long long msec, struct point *p0, int *dx, int *dy)
int gui_internal_gesture_do (struct gui_priv *this)
Function Documentation
int gui_internal_gesture_do (struct gui_priv * this)
References widget::data, dbg, gui_internal_gesture_get_vector(), gui_internal_table_button_next(), gui_internal_table_button_prev(), lvl_debug, NULL, widget::parent, STATE_HIGHLIGHTED, widget::type, and widget_table.
Referenced by gui_internal_button().
int gui_internal_gesture_get_vector (struct gui_priv * this, long long msec, struct point * p0, int * dx, int * dy)
References dbg, gui_internal_gesture_ring_get(), i, LONGLONG_FMT, lvl_info, NULL, point::x, and point::y.
Referenced by gui_internal_button(), gui_internal_gesture_do(), and gui_internal_motion_cb().
void gui_internal_gesture_ring_add (struct gui_priv * this, struct point * p)
References dbg, GESTURE_RINGSIZE, gettimeofday(), long, LONGLONG_FMT, lvl_info, NULL, p, timeval::tv_sec, timeval::tv_usec, point::x, and point::y.
Referenced by gui_internal_button(), and gui_internal_motion_cb().
void gui_internal_gesture_ring_clear (struct gui_priv * this)
Referenced by gui_internal_button().
static struct gesture_elem* gui_internal_gesture_ring_get (struct gui_priv * this, int i) static
References GESTURE_RINGSIZE, and NULL.
Referenced by gui_internal_gesture_get_vector().