navit: gui/internal/gui_internal_poi.c File Reference
gui_internal_poi.c File Reference
#include <glib.h>
#include <stdlib.h>
#include "color.h"
#include "coord.h"
#include "point.h"
#include "callback.h"
#include "graphics.h"
#include "debug.h"
#include "navit.h"
#include "navit_nls.h"
#include "item.h"
#include "xmlconfig.h"
#include "map.h"
#include "mapset.h"
#include "layout.h"
#include "route.h"
#include "transform.h"
#include "linguistics.h"
#include "fib.h"
#include "util.h"
#include "gui_internal.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_menu.h"
#include "gui_internal_keyboard.h"
#include "gui_internal_poi.h"
Data Structures
struct item_data
struct selector
Functions
static struct graphics_image * gui_internal_poi_icon (struct gui_priv *this, struct item *item)
Get icon for given POI type.
void gui_internal_poi_param_free (void *p)
Free poi_param structure.
static struct poi_param * gui_internal_poi_param_clone (struct poi_param *p)
Clone poi_param structure.
void gui_internal_poi_param_set_filter (struct poi_param *param, char *text)
Set POIs filter data in poi_param structure.
static struct widget * gui_internal_cmd_pois_selector (struct gui_priv *this, struct pcoord *c, int pagenb)
static void format_dist (int dist, char *distbuf)
Widget to display POI item.
struct widget * gui_internal_cmd_pois_item (struct gui_priv *this, struct coord *center, struct item *item, struct coord *c, struct route *route, int dist, char *name)
char * gui_internal_compose_item_address_string (struct item *item, int prependPostal)
Get string representation of item address suitable for doing search and for display in POI list.
static int gui_internal_cmd_pois_item_selected (struct poi_param *param, struct item *item)
static void gui_internal_cmd_pois_more (struct gui_priv *this, struct widget *wm, void *data)
Event handler for POIs list "more" element.
static void gui_internal_cmd_pois_filter_do (struct gui_priv *this, struct widget *wm, void *data)
Event to apply POIs text filter.
static void gui_internal_cmd_pois_filter_changed (struct gui_priv *this, struct widget *wm, void *data)
POIs filter dialog. Event to handle '' '
' keys pressed.
void gui_internal_cmd_pois_filter (struct gui_priv *this, struct widget *wm, void *data)
POIs filter dialog.
void gui_internal_cmd_pois (struct gui_priv *this, struct widget *wm, void *data)
Do POI search specified by poi_param and display POIs found.
Variables
static enum item_type selectors_BankTypes [] ={type_poi_bank,type_poi_bank, type_poi_atm,type_poi_atm, type_none}
static enum item_type selectors_FuelTypes [] ={type_poi_fuel,type_poi_fuel,type_none}
static enum item_type selectors_BusTrainTypes []
static enum item_type selectors_HotelTypes []
static enum item_type selectors_RestaurantTypes []
static enum item_type selectors_ShoppingTypes []
static enum item_type selectors_ServiceTypes []
static enum item_type selectors_ParkingTypes [] ={type_poi_car_parking,type_poi_car_parking,type_none}
static enum item_type selectors_LandFeaturesTypes []
static enum item_type selectors_OtherTypes []
struct selector selectors []
Function Documentation
static void format_dist (int dist, char * distbuf) static
Widget to display POI item.
Parameters
this pointer to gui context
center reference to the standing point where angle to be counted from
item POI item reference
c POI coordinates
dist precomputed distance to POI (or -1 if it's not to be displayed)
name POI name
Returns
Pointer to new widget.
References sprintf().
Referenced by gui_internal_cmd_pois_item().
void gui_internal_cmd_pois (struct gui_priv * this, struct widget * wm, void * data)
Do POI search specified by poi_param and display POIs found.
Parameters
this The graphics context.
wm called widget.
data event data, reference to poi_param or NULL.
References _, poi_param::AddressFilterType, widget::background, background, table_data::bottom_row, item_data::c, widget::c, c, map_selection::c_rect, widget::children, coord_rect_contains(), poi_param::count, widget::data, _GList::data, data, widget::data_free, widget::datai, dbg, poi_param::dist, item_data::dist, fh_deleteheap(), fh_extractmin(), fh_insertkey(), fh_makekeyheap(), fh_minkey(), poi_param::filter, poi_param::filterstr, flags_expand, flags_fill, widget::func, g_free(), g_list_index(), g_new0, g_strdup(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_pois_more(), gui_internal_cmd_pois_selector(), gui_internal_compose_item_address_string(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_poi_param_clone(), gui_internal_poi_param_free(), gui_internal_table_button_next(), gui_internal_widget_append(), gui_internal_widget_prepend(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), i, item_data::item, item, item_attr_get(), item_attr_rewind(), item_coord_get_pro(), key, item_data::label, label, lvl_debug, item::map, map_convert_string(), map_convert_string_tmp(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), map_selection_dup_pro(), map_selection_rect_new(), mapset_close(), mapset_next(), mapset_open(), selector::name, navit_get_attr(), navit_get_mapset(), scroll_buttons::next_button, NULL, attr::num, orientation_horizontal, orientation_vertical, poi_param::pagenb, pcoord::pro, attr::route, route_get_attr(), route_status_path_done_incremental, route_status_path_done_new, row, table_data::scroll_buttons, poi_param::sel, poi_param::selnb, widget::state, STATE_SENSITIVE, attr::str, table_data::top_row, transform_distance(), transform_scale(), item::type, map_selection::u, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_pois(), gui_internal_cmd_pois_filter_do(), gui_internal_cmd_pois_more(), gui_internal_cmd_pois_selector(), and gui_internal_cmd_position_do().
void gui_internal_cmd_pois_filter (struct gui_priv * this, struct widget * wm, void * data)
POIs filter dialog.
Parameters
this The graphics context.
wm called widget.
data event data.
References widget::background, background, widget::c, widget::data, widget::flags, flags_expand, flags_fill, widget::func, g_strdup(), getenv, gravity_center, gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_cmd_pois_filter_changed(), gui_internal_cmd_pois_filter_do(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), widget::name, NULL, orientation_horizontal, orientation_vertical, widget::state, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_FLAG_2, and widget::w.
Referenced by gui_internal_cmd_pois_selector().
static void gui_internal_cmd_pois_filter_changed (struct gui_priv * this, struct widget * wm, void * data) static
POIs filter dialog. Event to handle '' '
' keys pressed.
References gui_internal_cmd_pois_filter_do(), gui_internal_reason_keypress_finish, widget::reason, and widget::text.
Referenced by gui_internal_cmd_pois_filter().
static void gui_internal_cmd_pois_filter_do (struct gui_priv * this, struct widget * wm, void * data) static
Event to apply POIs text filter.
Parameters
this The graphics context.
wm called widget.
data event data (pointer to editor widget containg filter text).
References poi_param::AddressFilterType, widget::data, data, g_new0, gui_internal_cmd_pois(), gui_internal_poi_param_clone(), gui_internal_poi_param_free(), gui_internal_poi_param_set_filter(), widget::name, poi_param::pagenb, widget::text, and widget::w.
Referenced by gui_internal_cmd_pois_filter(), and gui_internal_cmd_pois_filter_changed().
struct widget* gui_internal_cmd_pois_item (struct gui_priv * this, struct coord * center, struct item * item, struct coord * c, struct route * route, int dist, char * name)
References widget::data, widget::datai, flags_fill, format_dist(), widget::func, g_free(), g_strdup(), g_strdup_printf(), get_compass_direction(), gravity_left_center, gui_internal_button_new_with_callback(), gui_internal_cmd_position(), gui_internal_poi_icon(), image_new_xs(), widget::item, item, item_to_name(), widget::name, NULL, orientation_horizontal, route_get_distances(), widget::state, STATE_SENSITIVE, widget::text, transform_get_angle_delta(), item::type, and type.
Referenced by gui_internal_cmd_pois(), and gui_internal_cmd_position_do().
static int gui_internal_cmd_pois_item_selected (struct poi_param * param, struct item * item) static
References poi_param::AddressFilterType, _GList::data, poi_param::filter, g_free(), g_list_next, g_strdup(), g_strdup_printf(), g_utf8_strchr(), gui_internal_compose_item_address_string(), i, item_attr_get(), item_to_name(), linguistics_expand_special(), item::map, map_convert_string_tmp(), match(), NULL, removecase(), poi_param::sel, poi_param::selnb, attr::str, item::type, type, selector::types, types, and attr::u.
Referenced by gui_internal_cmd_pois().
static void gui_internal_cmd_pois_more (struct gui_priv * this, struct widget * wm, void * data) static
Event handler for POIs list "more" element.
Parameters
this The graphics context.
wm called widget.
data event data.
References widget::c, widget::data, widget::data_free, g_new0, gui_internal_back(), gui_internal_cmd_pois(), NULL, and widget::w.
Referenced by gui_internal_cmd_pois().
static struct widget* gui_internal_cmd_pois_selector (struct gui_priv * this, struct pcoord * c, int pagenb) static
References widget::background, background, widget::bt, widget::c, c, widget::cols, widget::data_free, poi_param::dist, poi_param::filter, poi_param::filterstr, flags_fill, g_new0, gravity_left_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_poi_param_free(), gui_internal_widget_append(), gui_internal_widget_pack(), widget::h, i, image_new_s(), nrows, NULL, orientation_horizontal_vertical, orientation_vertical, p, poi_param::pagenb, poi_param::sel, selectors, poi_param::selnb, and widget::w.
Referenced by gui_internal_cmd_pois().
char* gui_internal_compose_item_address_string (struct item * item, int prependPostal)
Get string representation of item address suitable for doing search and for display in POI list.
Parameters
item reference to item.
Returns
Pointer to string representation of address. To be g_free()d after use.
References g_strdup(), g_strjoin(), item_attr_get(), item::map, map_convert_string_tmp(), NULL, attr::str, and attr::u.
Referenced by gui_internal_cmd_pois(), and gui_internal_cmd_pois_item_selected().
static struct graphics_image* gui_internal_poi_icon (struct gui_priv * this, struct item * item) static
Get icon for given POI type.
Parameters
this pointer to gui context
type POI type
Returns
Pointer to graphics_image object, or NULL if no picture available.
References _GList::data, dbg, element::element_icon, g_free(), g_list_next, g_strdup(), g_strdup_printf(), g_strrstr(), element::icon, item::id_hi, item::id_lo, image_new_xs(), item_attr_get(), item_is_custom_poi, item_to_name(), attr::layer, layout::layers, attr::layout, lvl_debug, item::map, map_convert_string_tmp(), map_rect_get_item_byid(), map_rect_new(), navit_get_attr(), NULL, element::src, attr::str, element::type, item::type, types, element::u, and attr::u.
Referenced by gui_internal_cmd_pois_item().
static struct poi_param* gui_internal_poi_param_clone (struct poi_param * p) static
Clone poi_param structure.
Parameters
p reference to the object to be cloned.
Returns
Cloned object reference.
References _GList::data, poi_param::filter, poi_param::filterstr, g_list_append(), g_list_last(), g_list_next, g_memdup(), g_new, and NULL.
Referenced by gui_internal_cmd_pois(), and gui_internal_cmd_pois_filter_do().
void gui_internal_poi_param_free (void * p)
Free poi_param structure.
Parameters
p reference to the object to be freed.
References g_free(), and g_list_free().
Referenced by gui_internal_cmd2_pois(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter_do(), and gui_internal_cmd_pois_selector().
void gui_internal_poi_param_set_filter (struct poi_param * param, char * text)
Set POIs filter data in poi_param structure.
Parameters
param poi_param structure with unset filter data.
text filter text.
References poi_param::filter, poi_param::filterstr, g_list_append(), g_utf8_strchr(), removecase(), s1, and s2.
Referenced by gui_internal_cmd2_pois(), and gui_internal_cmd_pois_filter_do().
Variable Documentation
struct selector selectors[]
Initial value:
={
        {"bank","Bank",selectors_BankTypes},
        {"fuel","Fuel",selectors_FuelTypes},
        {"bus_stop","Bus&Train",selectors_BusTrainTypes},
        {"hotel","Hotel",selectors_HotelTypes},
        {"restaurant","Restaurant",selectors_RestaurantTypes},
        {"shopping","Shopping",selectors_ShoppingTypes},
        {"hospital","Service",selectors_ServiceTypes},
        {"parking","Parking",selectors_ParkingTypes},
        {"peak","Land Features",selectors_LandFeaturesTypes},
        {"unknown","Other",selectors_OtherTypes},
}
Referenced by gui_internal_cmd_pois_selector().
enum item_type selectors_BankTypes[] ={type_poi_bank,type_poi_bank, type_poi_atm,type_poi_atm, type_none} static
enum item_type selectors_BusTrainTypes[] static
Initial value:
={type_poi_rail_station,type_poi_rail_station,
    type_poi_rail_halt,type_poi_rail_tram_stop,type_poi_bus_station,type_poi_bus_stop,type_none}
enum item_type selectors_FuelTypes[] ={type_poi_fuel,type_poi_fuel,type_none} static
enum item_type selectors_HotelTypes[] static
Initial value:
={type_poi_hotel,type_poi_camp_rv,type_poi_camping,type_poi_camping,
    type_poi_resort,type_poi_resort,type_poi_motel,type_poi_hostel,type_none}
enum item_type selectors_LandFeaturesTypes[] static
Initial value:
={type_poi_land_feature,type_poi_rock,type_poi_dam,type_poi_dam,
    type_poi_peak,type_poi_peak,type_none}
enum item_type selectors_OtherTypes[] static
Initial value:
={type_point_unspecified,type_poi_land_feature-1,type_poi_rock+1,type_poi_fuel-1,
    type_poi_marina+1,type_poi_shopping-1,type_poi_shopping+1,type_poi_car_parking-1,type_poi_car_parking+1,
    type_poi_bar-1,type_poi_bank+1,type_poi_dam-1,type_poi_dam+1,type_poi_information-1,type_poi_information+1,
    type_poi_mall-1,type_poi_mall+1,type_poi_personal_service-1,type_poi_pharmacy+1,type_poi_repair_service-1,
    type_poi_repair_service+1,type_poi_restaurant-1,type_poi_restaurant+1,type_poi_restroom-1,type_poi_restroom+1,
    type_poi_shop_grocery-1,type_poi_shop_grocery+1,type_poi_peak-1,type_poi_peak+1,type_poi_motel-1,type_poi_hostel+1,
    type_poi_shop_butcher-1,type_poi_shop_baker+1,type_poi_shop_fruit-1,type_poi_shop_fruit+1,type_poi_shop_beverages-1,
    type_poi_shop_beverages+1,type_poi_pub-1,type_poi_atm+1,type_line-1,type_none}
enum item_type selectors_ParkingTypes[] ={type_poi_car_parking,type_poi_car_parking,type_none} static
enum item_type selectors_RestaurantTypes[] static
Initial value:
={type_poi_bar,type_poi_picnic,type_poi_burgerking,type_poi_fastfood,
    type_poi_restaurant,type_poi_restaurant,type_poi_cafe,type_poi_cafe,type_poi_pub,type_poi_pub,type_none}
enum item_type selectors_ServiceTypes[] static
Initial value:
={type_poi_marina,type_poi_marina,type_poi_hospital,type_poi_hospital,
    type_poi_public_utilities,type_poi_public_utilities,type_poi_police,type_poi_autoservice,type_poi_information,
    type_poi_information,type_poi_pharmacy,type_poi_pharmacy,type_poi_personal_service,type_poi_repair_service,
    type_poi_restroom,type_poi_restroom,type_none}
enum item_type selectors_ShoppingTypes[] static
Initial value:
={type_poi_mall,type_poi_mall,type_poi_shop_grocery,type_poi_shop_grocery,
    type_poi_shopping,type_poi_shopping,type_poi_shop_butcher,type_poi_shop_baker,type_poi_shop_fruit,
    type_poi_shop_fruit,type_poi_shop_beverages,type_poi_shop_beverages,type_none}