navit: gui/internal/gui_internal_html.c File Reference
gui_internal_html.c File Reference
#include <glib.h>
#include <stdlib.h>
#include <ctype.h>
#include "callback.h"
#include "debug.h"
#include "coord.h"
#include "point.h"
#include "color.h"
#include "graphics.h"
#include "xmlconfig.h"
#include "navit_nls.h"
#include "gui.h"
#include "command.h"
#include "gui_internal.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_keyboard.h"
#include "gui_internal_menu.h"
Data Structures
struct form
struct html_tag_map
struct div_flags_map
Functions
static const char * find_attr (const char **names, const char **values, const char *name)
static char * find_attr_dup (const char **names, const char **values, const char *name)
void gui_internal_html_main_menu (struct gui_priv *this)
static void gui_internal_html_command (struct gui_priv *this, struct widget *w, void *data)
static void gui_internal_html_submit_set (struct gui_priv *this, struct widget *w, struct form *form)
static void gui_internal_html_submit (struct gui_priv *this, struct widget *w, void *data)
void gui_internal_html_load_href (struct gui_priv *this, char *href, int replace)
void gui_internal_html_href (struct gui_priv *this, struct widget *w, void *data)
static enum flags div_flag (const char **names, const char **values, char *name)
static enum flags div_flags (const char **names, const char **values)
static struct widget * html_image (struct gui_priv *this, const char **names, const char **values)
static void gui_internal_html_start (xml_context *dummy, const char *tag_name, const char **names, const char **values, void *data, GError **error)
static void gui_internal_html_end (xml_context *dummy, const char *tag_name, void *data, GError **error)
static void gui_internal_refresh_callback_called (struct gui_priv *this, struct menu_data *menu_data)
static void gui_internal_set_refresh_callback (struct gui_priv *this, char *cond)
static void gui_internal_html_text (xml_context *dummy, const char *text, gsize len, void *data, GError **error)
void gui_internal_html_parse_text (struct gui_priv *this, char *doc)
void gui_internal_html_menu (struct gui_priv *this, const char *document, char *anchor)
Variables
struct html_tag_map html_tag_map []
struct div_flags_map div_flags_map []
Function Documentation
static enum flags div_flag (const char ** names, const char ** values, char * name) static
References div_flags_map, find_attr(), i, and value.
Referenced by div_flags().
static enum flags div_flags (const char ** names, const char ** values) static
References div_flag().
Referenced by gui_internal_html_start().
static const char* find_attr (const char ** names, const char ** values, const char * name) static
References g_ascii_strcasecmp(), NULL, and XML_ATTR_DISTANCE.
Referenced by div_flag(), find_attr_dup(), gui_internal_html_start(), and html_image().
static char* find_attr_dup (const char ** names, const char ** values, const char * name) static
References find_attr(), and g_strdup().
Referenced by gui_internal_html_start().
static void gui_internal_html_command (struct gui_priv * this, struct widget * w, void * data) static
References widget::command, and gui_internal_evaluate().
Referenced by gui_internal_html_end().
static void gui_internal_html_end (xml_context * dummy, const char * tag_name, void * data, GError ** error) static
References data, g_ascii_strcasecmp(), g_free(), g_strdup(), gui_internal_html_command(), gui_internal_html_href(), gui_internal_widget_append(), NULL, and STATE_SENSITIVE.
Referenced by gui_internal_html_parse_text().
void gui_internal_html_href (struct gui_priv * this, struct widget * w, void * data)
References widget::command, and gui_internal_html_load_href().
Referenced by gui_internal_html_end().
void gui_internal_html_load_href (struct gui_priv * this, char * href, int replace)
References dbg, g_free(), g_strdup(), gui_internal_html_menu(), gui_internal_prune_menu_count(), and lvl_debug.
Referenced by gui_internal_cmd2_refresh(), gui_internal_cmd_menu(), gui_internal_cmd_menu2(), gui_internal_html_href(), gui_internal_html_main_menu(), gui_internal_prune_menu_do(), and gui_internal_refresh_callback_called().
void gui_internal_html_main_menu (struct gui_priv * this)
References gui_internal_html_load_href(), gui_internal_prune_menu(), and NULL.
Referenced by gui_internal_cmd_main_menu(), gui_internal_cmd_menu(), and gui_internal_resize().
void gui_internal_html_menu (struct gui_priv * this, const char * document, char * anchor)
References callback_list_call_attr_2, cbl, draw_mode_begin, draw_mode_end, flags_expand, flags_fill, g_free(), g_strdup(), getenv, graphics_draw_mode(), gravity_center, gui_internal_html_parse_text(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_menu_render(), gui_internal_widget_append(), NULL, orientation_vertical, and VKBD_FLAG_2.
Referenced by gui_internal_html_load_href().
void gui_internal_html_parse_text (struct gui_priv * this, char * doc)
References gui_internal_html_end(), gui_internal_html_start(), gui_internal_html_text(), and xml_parse_text().
Referenced by gui_internal_cmd_img(), gui_internal_cmd_write(), and gui_internal_html_menu().
static void gui_internal_html_start (xml_context * dummy, const char * tag_name, const char ** names, const char ** values, void * data, GError ** error) static
References background, command_evaluate_to_boolean(), data, div_flags(), find_attr(), find_attr_dup(), g_ascii_strcasecmp(), g_new0, gui_internal_box_new(), gui_internal_html_submit(), gui_internal_label_new(), html_image(), html_tag_map, i, NULL, form::onsubmit, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, html_tag_map::tag, type, and value.
Referenced by gui_internal_html_parse_text().
static void gui_internal_html_submit (struct gui_priv * this, struct widget * w, void * data) static
References _GList::data, dbg, draw_mode_begin, draw_mode_end, widget::form, g_list_last(), graphics_draw_mode(), gui_internal_evaluate(), gui_internal_highlight_do(), gui_internal_html_submit_set(), gui_internal_menu_render(), lvl_debug, NULL, and form::onsubmit.
Referenced by gui_internal_html_start().
static void gui_internal_html_submit_set (struct gui_priv * this, struct widget * w, struct form * form) static
References attr_free(), attr_new_from_text(), widget::children, _GList::data, widget::form, g_list_next, gui_set_attr(), widget::name, widget::text, and attr::u.
Referenced by gui_internal_html_submit().
static void gui_internal_html_text (xml_context * dummy, const char * text, gsize len, void * data, GError ** error) static
References _, data, dbg, flags_expand, flags_fill, g_free(), g_strdup(), g_strndup(), gchar, gravity_center, gravity_left_top, gui_internal_box_new(), gui_internal_evaluate(), gui_internal_menu(), gui_internal_menu_data(), gui_internal_set_refresh_callback(), gui_internal_text_font_new(), gui_internal_text_new(), gui_internal_widget_append(), menu_data::href, lvl_debug, orientation_horizontal, orientation_horizontal_vertical, orientation_vertical, strcasecmp(), and widget::w.
Referenced by gui_internal_html_parse_text().
static void gui_internal_refresh_callback_called (struct gui_priv * this, struct menu_data * menu_data) static
References g_free(), g_strdup(), gui_internal_html_load_href(), gui_internal_menu_data(), and menu_data::href.
Referenced by gui_internal_set_refresh_callback().
static void gui_internal_set_refresh_callback (struct gui_priv * this, char * cond) static
References object_func::add_attr, attr::callback, callback_cast, callback_new_attr_2, command_evaluate_to_attr(), dbg, gui_internal_menu_data(), gui_internal_refresh_callback_called(), lvl_error, lvl_info, NULL, object_func_lookup(), menu_data::refresh_callback, type, attr::type, and attr::u.
Referenced by gui_internal_html_text().
static struct widget* html_image (struct gui_priv * this, const char ** names, const char ** values) static
References find_attr(), gui_internal_image_new(), image_new_l(), image_new_s(), image_new_xs(), NULL, size, and strcasecmp().
Referenced by gui_internal_html_start().
Variable Documentation
struct div_flags_map div_flags_map[]
Initial value:
= {
        {"gravity","none",gravity_none},
        {"gravity","left",gravity_left},
        {"gravity","xcenter",gravity_xcenter},
        {"gravity","right",gravity_right},
        {"gravity","top",gravity_top},
        {"gravity","ycenter",gravity_ycenter},
        {"gravity","bottom",gravity_bottom},
        {"gravity","left_top",gravity_left_top},
        {"gravity","top_center",gravity_top_center},
        {"gravity","right_top",gravity_right_top},
        {"gravity","left_center",gravity_left_center},
        {"gravity","center",gravity_center},
        {"gravity","right_center",gravity_right_center},
        {"gravity","left_bottom",gravity_left_bottom},
        {"gravity","bottom_center",gravity_bottom_center},
        {"gravity","right_bottom",gravity_right_bottom},
        {"expand","1",flags_expand},
        {"fill","1",flags_fill},
        {"orientation","horizontal",orientation_horizontal},
        {"orientation","vertical",orientation_vertical},
        {"orientation","horizontal_vertical",orientation_horizontal_vertical},
}
Referenced by div_flag().
struct html_tag_map html_tag_map[]
Initial value:
= {
        {"a",html_tag_a},
        {"h1",html_tag_h1},
        {"html",html_tag_html},
        {"img",html_tag_img},
        {"script",html_tag_script},
        {"form",html_tag_form},
        {"input",html_tag_input},
        {"div",html_tag_div},
}
Referenced by gui_internal_html_start().