navit: gui/internal/gui_internal_html.h File Reference
gui_internal_html.h File Reference
Functions
void gui_internal_html_main_menu (struct gui_priv *this)
void gui_internal_html_load_href (struct gui_priv *this, char *href, int replace)
void gui_internal_html_href (struct gui_priv *this, struct widget *w, void *data)
void gui_internal_html_parse_text (struct gui_priv *this, char *doc)
void gui_internal_html_menu (struct gui_priv *this, const char *document, char *anchor)
Function Documentation
void gui_internal_html_href (struct gui_priv * this, struct widget * w, void * data)
References widget::command, and gui_internal_html_load_href().
Referenced by gui_internal_html_end().
void gui_internal_html_load_href (struct gui_priv * this, char * href, int replace)
References dbg, g_free(), g_strdup(), gui_internal_html_menu(), gui_internal_prune_menu_count(), and lvl_debug.
Referenced by gui_internal_cmd2_refresh(), gui_internal_cmd_menu(), gui_internal_cmd_menu2(), gui_internal_html_href(), gui_internal_html_main_menu(), gui_internal_prune_menu_do(), and gui_internal_refresh_callback_called().
void gui_internal_html_main_menu (struct gui_priv * this)
References gui_internal_html_load_href(), gui_internal_prune_menu(), and NULL.
Referenced by gui_internal_cmd_main_menu(), gui_internal_cmd_menu(), and gui_internal_resize().
void gui_internal_html_menu (struct gui_priv * this, const char * document, char * anchor)
References callback_list_call_attr_2, cbl, draw_mode_begin, draw_mode_end, flags_expand, flags_fill, g_free(), g_strdup(), getenv, graphics_draw_mode(), gravity_center, gui_internal_html_parse_text(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_menu_render(), gui_internal_widget_append(), NULL, orientation_vertical, and VKBD_FLAG_2.
Referenced by gui_internal_html_load_href().
void gui_internal_html_parse_text (struct gui_priv * this, char * doc)
References gui_internal_html_end(), gui_internal_html_start(), gui_internal_html_text(), and xml_parse_text().
Referenced by gui_internal_cmd_img(), gui_internal_cmd_write(), and gui_internal_html_menu().