navit: gui/internal/gui_internal_search.c File Reference
gui_internal_search.c File Reference
#include <glib.h>
#include <stdlib.h>
#include "config.h"
#include "color.h"
#include "coord.h"
#include "point.h"
#include "callback.h"
#include "graphics.h"
#include "debug.h"
#include "navit.h"
#include "navit_nls.h"
#include "event.h"
#include "search.h"
#include "country.h"
#include "track.h"
#include "linguistics.h"
#include "gui_internal.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_menu.h"
#include "gui_internal_keyboard.h"
#include "gui_internal_search.h"
Functions
static void gui_internal_search_country (struct gui_priv *this, struct widget *widget, void *data)
static void gui_internal_search_town (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_search_street (struct gui_priv *this, struct widget *widget, void *data)
static void gui_internal_search_house_number (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_search_idle_end (struct gui_priv *this)
static int gui_internal_search_cmp (gconstpointer _a, gconstpointer _b)
static char * postal_str (struct search_list_result *res, int level)
static char * get_string_from_attr_list (struct attr **attrs, enum attr_type type, char *dflt)
static char * district_str (struct search_list_result *res, int level, enum attr_type district, char *dflt)
static char * town_display_label (struct search_list_result *res, int level, int flags)
static void gui_internal_find_next_possible_key (char *search_text, char *wm_name, char *possible_keys, char *item_name)
static void gui_internal_highlight_possible_keys (struct gui_priv *this, char *possible_keys)
static int gui_internal_get_match_quality (char *item_name, char *search_text, int is_house_number_without_street)
static struct widget * gui_internal_create_resultlist_entry (struct gui_priv *this, struct search_list_result *res, char *result_main_label, char *result_sublabel, void *param, char *widget_name, struct item *item)
static void gui_internal_search_idle (struct gui_priv *this, char *wm_name, struct widget *search_list, void *param)
static void gui_internal_search_idle_start (struct gui_priv *this, char *wm_name, struct widget *search_list, void *param)
static void gui_internal_search_changed (struct gui_priv *this, struct widget *wm, void *data)
static void gui_internal_search_list_set_default_country (struct gui_priv *this)
static void gui_internal_search_list_new (struct gui_priv *this)
void gui_internal_search_list_destroy (struct gui_priv *this)
void gui_internal_search (struct gui_priv *this, const char *what, const char *type, int flags)
void gui_internal_search_house_number_in_street (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_search_street_in_town (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_search_town_in_country (struct gui_priv *this, struct widget *widget)
Variables
char possible_keys_incremental_search [256] =""
List of possible next keys/characters given the current result list of the incremental search.
Function Documentation
district_str()
static char* district_str (struct search_list_result * res, int level, enum attr_type district, char * dflt) static
References search_list_common::attrs, search_list_town::common, search_list_street::common, search_list_house_number::common, get_string_from_attr_list(), search_list_result::house_number, search_list_result::street, and search_list_result::town.
Referenced by town_display_label().
get_string_from_attr_list()
static char* get_string_from_attr_list (struct attr ** attrs, enum attr_type type, char * dflt) static
References attr_generic_get_attr(), attr::attrs, attr::str, type, and attr::u.
Referenced by district_str().
gui_internal_create_resultlist_entry()
static struct widget* gui_internal_create_resultlist_entry (struct gui_priv * this, struct search_list_result * res, char * result_main_label, char * result_sublabel, void * param, char * widget_name, struct item * item) static
References widget::c, search_list_result::c, search_list_result::country, widget::data, search_list_country::flag, flags_fill, widget::func, gravity_left_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_position(), gui_internal_image_new(), gui_internal_label_font_new(), gui_internal_label_new(), gui_internal_widget_append(), search_list_result::id, image_new_xs(), widget::item, item, widget::name, orientation_horizontal, orientation_vertical, widget::selection_id, widget::speech, widget::state, and STATE_SENSITIVE.
Referenced by gui_internal_search_idle().
gui_internal_find_next_possible_key()
static void gui_internal_find_next_possible_key (char * search_text, char * wm_name, char * possible_keys, char * item_name) static
References dbg, linguistics_expand_special(), and lvl_info.
Referenced by gui_internal_search_idle().
gui_internal_get_match_quality()
static int gui_internal_get_match_quality (char * item_name, char * search_text, int is_house_number_without_street) static
References dbg, linguistics_casefold(), linguistics_expand_special(), LINGUISTICS_WORD_SEPARATORS_ASCII, lvl_debug, and p.
Referenced by gui_internal_search_idle().
gui_internal_highlight_possible_keys()
static void gui_internal_highlight_possible_keys (struct gui_priv * this, char * possible_keys) static
References widget::children, widget::data, widget::data_free, draw_mode_begin, draw_mode_end, graphics_draw_mode(), gui_internal_highlight_do(), gui_internal_menu_data(), gui_internal_widget_render(), menu_data::keyboard, widget::state, STATE_CLEAR, STATE_HIGHLIGHTED, STATE_INVISIBLE, STATE_SELECTED, and STATE_SENSITIVE.
Referenced by gui_internal_search_changed(), and gui_internal_search_idle().
gui_internal_search()
void gui_internal_search (struct gui_priv * this, const char * what, const char * type, int flags)
References widget::background, country, widget::flags, flags_expand, flags_fill, widget::func, gravity_center, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_back(), gui_internal_box_new(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_data(), gui_internal_menu_render(), gui_internal_search_changed(), gui_internal_search_country(), gui_internal_search_house_number(), gui_internal_search_list_new(), gui_internal_search_street(), gui_internal_search_town(), gui_internal_widget_append(), gui_internal_widget_table_new(), image_new_xs(), widget::name, orientation_horizontal, orientation_vertical, menu_data::search_list, widget::state, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, strtolower(), type, VKBD_FLAG_2, VKBD_NUMERIC, and widget::w.
Referenced by gui_internal_cmd2_town(), gui_internal_search_country(), gui_internal_search_house_number(), gui_internal_search_house_number_in_street(), gui_internal_search_street(), gui_internal_search_street_in_town(), gui_internal_search_town(), and gui_internal_search_town_in_country().
gui_internal_search_changed()
static void gui_internal_search_changed (struct gui_priv * this, struct widget * wm, void * data) static
References dbg, gui_internal_highlight_possible_keys(), gui_internal_menu_data(), gui_internal_search_idle_end(), gui_internal_search_idle_start(), gui_internal_widget_render(), gui_internal_widget_table_clear(), lvl_debug, widget::name, possible_keys_incremental_search, menu_data::search_list, search_list_search(), attr::str, widget::text, attr::type, and attr::u.
Referenced by gui_internal_search().
gui_internal_search_cmp()
static int gui_internal_search_cmp (gconstpointer _a, gconstpointer _b) static
References widget::datai, dbg, lvl_debug, removecase(), widget::text, widget::type, and widget_table_row.
Referenced by gui_internal_search_idle().
gui_internal_search_country()
static void gui_internal_search_country (struct gui_priv * this, struct widget * widget, void * data) static
References _, gui_internal_prune_menu_count(), and gui_internal_search().
Referenced by gui_internal_search().
gui_internal_search_house_number()
static void gui_internal_search_house_number (struct gui_priv * this, struct widget * widget, void * data) static
References _, gui_internal_search(), and search_list_select().
Referenced by gui_internal_search().
gui_internal_search_house_number_in_street()
void gui_internal_search_house_number_in_street (struct gui_priv * this, struct widget * widget, void * data)
References _, dbg, gui_internal_search(), lvl_info, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position(), and gui_internal_cmd_position_do().
gui_internal_search_idle()
static void gui_internal_search_idle (struct gui_priv * this, char * wm_name, struct widget * search_list, void * param) static
References search_list_country::common, search_list_town::common, search_list_street::common, search_list_result::country, widget::datai, dbg, dbg_assert, draw_mode_begin, draw_mode_end, flags_fill, graphics_draw_mode(), gravity_left, gui_internal_create_resultlist_entry(), gui_internal_find_next_possible_key(), gui_internal_find_widget(), gui_internal_get_match_quality(), gui_internal_highlight_possible_keys(), gui_internal_search_cmp(), gui_internal_search_idle_end(), gui_internal_widget_append(), gui_internal_widget_insert_sorted(), gui_internal_widget_pack(), gui_internal_widget_render(), gui_internal_widget_table_row_new(), search_list_house_number::house_number, search_list_result::house_number, search_list_common::item, lvl_error, search_list_country::name, search_list_street::name, orientation_horizontal, possible_keys_incremental_search, search_list_get_result(), STATE_EDIT, search_list_result::street, widget::text, search_list_result::town, town_display_label(), and search_list_common::town_name.
Referenced by gui_internal_search_idle_start().
gui_internal_search_idle_end()
void gui_internal_search_idle_end (struct gui_priv * this)
References callback_destroy(), and event_remove_idle().
Referenced by gui_internal_check_exit(), gui_internal_menu(), gui_internal_prune_menu_do(), gui_internal_search_changed(), and gui_internal_search_idle().
gui_internal_search_idle_start()
static void gui_internal_search_idle_start (struct gui_priv * this, char * wm_name, struct widget * search_list, void * param) static
References callback_call_0, callback_cast, callback_new_4, event_add_idle(), and gui_internal_search_idle().
Referenced by gui_internal_search_changed().
gui_internal_search_list_destroy()
void gui_internal_search_list_destroy (struct gui_priv * this)
References search_list_destroy().
Referenced by gui_internal_check_exit().
gui_internal_search_list_new()
static void gui_internal_search_list_new (struct gui_priv * this) static
References gui_internal_search_list_set_default_country(), navit_get_mapset(), and search_list_new().
Referenced by gui_internal_search().
gui_internal_search_list_set_default_country()
static void gui_internal_search_list_set_default_country (struct gui_priv * this) static
References country_default(), country_search_destroy(), country_search_get_item(), country_search_new(), dbg, item, item_attr_get(), lvl_debug, lvl_error, navit_get_tracking(), search_list_get_result(), search_list_search(), attr::str, tracking_get_attr(), attr::type, and attr::u.
Referenced by gui_internal_search_list_new().
gui_internal_search_street()
static void gui_internal_search_street (struct gui_priv * this, struct widget * widget, void * data) static
References _, gui_internal_search(), and search_list_select().
Referenced by gui_internal_search().
gui_internal_search_street_in_town()
void gui_internal_search_street_in_town (struct gui_priv * this, struct widget * widget, void * data)
References _, dbg, gui_internal_search(), lvl_info, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position_do().
gui_internal_search_town()
static void gui_internal_search_town (struct gui_priv * this, struct widget * wm, void * data) static
References _, gui_internal_search(), and search_list_select().
Referenced by gui_internal_search().
gui_internal_search_town_in_country()
void gui_internal_search_town_in_country (struct gui_priv * this, struct widget * widget)
References dbg, gui_internal_search(), iso2, lvl_info, widget::name, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position().
postal_str()
static char* postal_str (struct search_list_result * res, int level) static
References search_list_town::common, search_list_street::common, search_list_house_number::common, search_list_result::house_number, search_list_common::postal, search_list_common::postal_mask, search_list_result::street, and search_list_result::town.
Referenced by town_display_label().
town_display_label()
static char* town_display_label (struct search_list_result * res, int level, int flags) static
References search_list_town::common, search_list_common::county_name, district_str(), postal_str(), and search_list_result::town.
Referenced by gui_internal_search_idle().
Variable Documentation
possible_keys_incremental_search
char possible_keys_incremental_search[256] =""
List of possible next keys/characters given the current result list of the incremental search.
Referenced by gui_internal_search_changed(), and gui_internal_search_idle().