navit: gui.c File Reference
gui.c File Reference
#include <glib.h>
#include <string.h>
#include "debug.h"
#include "callback.h"
#include "gui.h"
#include "menu.h"
#include "data_window.h"
#include "item.h"
#include "plugin.h"
Data Structures
struct gui
Functions
struct gui * gui_new (struct attr *parent, struct attr **attrs)
int gui_get_attr (struct gui *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int gui_set_attr (struct gui *this_, struct attr *attr)
int gui_add_attr (struct gui *this_, struct attr *attr)
struct menu * gui_menubar_new (struct gui *gui)
struct menu * gui_popup_new (struct gui *gui)
struct datawindow * gui_datawindow_new (struct gui *gui, const char *name, struct callback *click, struct callback *close)
int gui_add_bookmark (struct gui *gui, struct pcoord *c, char *description)
int gui_set_graphics (struct gui *this_, struct graphics *gra)
void gui_disable_suspend (struct gui *this_)
int gui_has_main_loop (struct gui *this_)
int gui_run_main_loop (struct gui *this_)
Function Documentation
int gui_add_attr (struct gui * this_, struct attr * attr)
References gui_methods::add_attr, gui::meth, and gui::priv.
int gui_add_bookmark (struct gui * gui, struct pcoord * c, char * description)
References gui_methods::add_bookmark, dbg, lvl_info, gui::meth, and gui::priv.
Referenced by popup_set_bookmark().
struct datawindow* gui_datawindow_new (struct gui * gui, const char * name, struct callback * click, struct callback * close)
References gui_methods::datawindow_new, g_free(), g_new0, datawindow::meth, gui::meth, NULL, gui::priv, and datawindow::priv.
Referenced by navit_window_roadbook_new().
void gui_disable_suspend (struct gui * this_)
References gui_methods::disable_suspend, gui::meth, and gui::priv.
Referenced by navit_disable_suspend().
int gui_get_attr (struct gui * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), gui::attrs, gui_methods::get_attr, gui::meth, NULL, gui::parent, gui::priv, and attr::type.
Referenced by NGQProxyGui::getAttrFunc(), NGQPoint::getPOI(), navit_init(), request_gui_command(), and request_gui_get_attr().
int gui_has_main_loop (struct gui * this_)
References gui::meth, and gui_methods::run_main_loop.
Referenced by gui_run_main_loop(), and navit_set_gui().
struct menu* gui_menubar_new (struct gui * gui)
References g_free(), g_new0, gui_methods::menubar_new, menu::meth, gui::meth, NULL, gui::priv, and menu::priv.
struct gui* gui_new (struct attr * parent, struct attr ** attrs)
References attr_generic_add_attr(), attr_list_dup(), attr_search(), gui::attrs, attr::attrs, attr::callback_list, callback_list_new(), g_new0, gui::meth, attr::navit, NULL, gui::parent, gui::priv, attr::str, attr::type, and attr::u.
struct menu* gui_popup_new (struct gui * gui)
References g_free(), g_new0, menu::meth, gui::meth, NULL, gui_methods::popup_new, gui::priv, and menu::priv.
Referenced by popup().
int gui_run_main_loop (struct gui * this_)
References gui_has_main_loop(), gui::meth, gui::priv, and gui_methods::run_main_loop.
int gui_set_attr (struct gui * this_, struct attr * attr)
References attr_generic_set_attr(), gui::attrs, gui::meth, gui::priv, and gui_methods::set_attr.
Referenced by gui_internal_html_submit_set(), and NGQProxyGui::setAttrFunc().
int gui_set_graphics (struct gui * this_, struct graphics * gra)
References dbg, lvl_error, gui::meth, gui::priv, and gui_methods::set_graphics.
Referenced by navit_init().