navit: gui/win32/gui_win32.c File Reference
gui_win32.c File Reference
#include <stdlib.h>
#include <process.h>
#include <windows.h>
#include <glib.h>
#include "config.h"
#include "plugin.h"
#include "gui.h"
#include "graphics_win32.h"
#include "point.h"
#include "menu.h"
#include "item.h"
#include "attr.h"
#include "callback.h"
#include <commctrl.h>
#include "debug.h"
#include "util.h"
#include "navit.h"
#include "navit_nls.h"
Macros
#define GET_WHEEL_DELTA_WPARAM(wParam) ((short)HIWORD(wParam))
Functions
static void CreateToolBar (HWND hwnd)
static void window_layout (HWND hwnd)
static LRESULT CALLBACK WndProc (HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam)
static HANDLE CreateWin32Window (void)
static int win32_gui_set_graphics (struct gui_priv *this_, struct graphics *gra)
static void win32_gui_add_bookmark_do (struct gui_priv *gui)
static int win32_gui_add_bookmark (struct gui_priv *gui, struct pcoord *c, char *description)
static struct menu_priv * add_menu (struct menu_priv *menu, struct menu_methods *meth, char *name, enum menu_type type, struct callback *cb)
static void set_toggle (struct menu_priv *menu, int active)
static int get_toggle (struct menu_priv *menu)
static void popup_activate (struct menu_priv *menu)
static void popup_deactivate (struct menu_priv *menu)
static struct menu_priv * win32_gui_popup_new (struct gui_priv *this_, struct menu_methods *meth)
static struct gui_priv * win32_gui_new (struct navit *nav, struct gui_methods *meth, struct attr **attrs)
void plugin_init (void)
Variables
const TCHAR g_szClassName [] = TEXT("navit_gui_class")
static UINT_PTR menu_id = 0
static struct menu_methods menu_methods
struct gui_methods win32_gui_methods
Macro Definition Documentation
#define GET_WHEEL_DELTA_WPARAM (wParam) ((short)HIWORD(wParam))
Referenced by WndProc().
Function Documentation
static struct menu_priv* add_menu (struct menu_priv * menu, struct menu_methods * meth, char * name, enum menu_type type, struct callback * cb) static
References menu_priv::cb, g_new0, menu_priv::hMenu, menu_id, menu_methods, menu_type_submenu, and NULL.
static void CreateToolBar (HWND hwnd) static
References ID_CHILD_TOOLBAR, ID_DISPLAY_ORIENT, ID_DISPLAY_REFRESH, ID_DISPLAY_ZOOMIN, ID_DISPLAY_ZOOMOUT, ID_FILE_EXIT, IDB_NAVITTOOLBAR, L, and NULL.
Referenced by WndProc().
static HANDLE CreateWin32Window (void) static
References g_szClassName, gui_priv::hwnd, IDI_NAVIT, NULL, TRUE, and WndProc().
Referenced by win32_gui_new().
static int get_toggle (struct menu_priv * menu) static
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
References win32_gui_new().
static void popup_activate (struct menu_priv * menu) static
References menu_priv::hMenu, NULL, and menu_priv::wnd_handle.
Referenced by win32_gui_popup_new().
static void popup_deactivate (struct menu_priv * menu) static
References menu_priv::hMenu.
static void set_toggle (struct menu_priv * menu, int active) static
static int win32_gui_add_bookmark (struct gui_priv * gui, struct pcoord * c, char * description) static
static void win32_gui_add_bookmark_do (struct gui_priv * gui) static
static struct gui_priv* win32_gui_new (struct navit * nav, struct gui_methods * meth, struct attr ** attrs) static
References CreateWin32Window(), exit, FALSE, g_new0, g_szClassName, gui_priv::hwnd, InitCeGlue(), gui_priv::nav, NULL, and win32_gui_methods.
Referenced by plugin_init().
static struct menu_priv* win32_gui_popup_new (struct gui_priv * this_, struct menu_methods * meth) static
References menu_priv::cb, FALSE, g_new0, menu_priv::hMenu, gui_priv::hwnd, menu_id, menu_methods, NULL, menu_methods::popup, popup_activate(), POPUP_MENU_OFFSET, printf(), TRUE, and menu_priv::wnd_handle.
static int win32_gui_set_graphics (struct gui_priv * this_, struct graphics * gra) static
References graphics_get_data(), and gui_priv::hwnd.
static void window_layout (HWND hwnd) static
References dbg, ID_CHILD_GFX, ID_CHILD_TOOLBAR, lvl_debug, and TRUE.
Referenced by WndProc().
static LRESULT CALLBACK WndProc (HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) static
References callback_call_0, menu_priv::cb, CreateToolBar(), dbg, GET_WHEEL_DELTA_WPARAM, gui_priv::h, ID_DISPLAY_CURSOR, ID_DISPLAY_ORIENT, ID_DISPLAY_REFRESH, ID_DISPLAY_ZOOMIN, ID_DISPLAY_ZOOMOUT, ID_FILE_EXIT, ID_STUFF_GO, L, lvl_error, gui_priv::nav, navit_draw(), navit_get_trans(), navit_set_attr(), navit_set_center_screen(), navit_zoom_in(), navit_zoom_out(), NULL, attr::num, POPUP_MENU_OFFSET, printf(), transform_get_size(), attr::type, attr::u, gui_priv::w, window_layout(), point::x, and point::y.
Referenced by CreateWin32Window().
Variable Documentation
const TCHAR g_szClassName[] = TEXT("navit_gui_class")
Referenced by CreateWin32Window(), main(), startThread(), and win32_gui_new().
UINT_PTR menu_id = 0 static
Referenced by add_menu(), and win32_gui_popup_new().
static struct menu_methods menu_methods static
Initial value:
= {
        add_menu,
        set_toggle,
        get_toggle,
}
Referenced by add_menu(), and win32_gui_popup_new().
struct gui_methods win32_gui_methods
Initial value:
= {
        NULL,
        win32_gui_popup_new,
        win32_gui_set_graphics,
        NULL,
        NULL,
        win32_gui_add_bookmark,
}
Referenced by win32_gui_new().