navit: gui/gtk/gui_gtk_poi.h File Reference
gui_gtk_poi.h File Reference
Functions
void gtk_gui_poi (struct navit *nav)
Create the POI search UI window and connect objects to functions.
Function Documentation
gtk_gui_poi()
void gtk_gui_poi (struct navit * nav)
Create the POI search UI window and connect objects to functions.
Parameters
nav The navit instance
References _, gtk_poi_search::button_destination, button_destination_clicked(), gtk_poi_search::button_map, button_map_clicked(), gtk_poi_search::button_visit, button_visit_clicked(), category_list_model(), gtk_poi_search::entry_distance, gtk_poi_search, gtk_poi_search::label_distance, gtk_poi_search::nav, navit_get_attr(), navit_populate_search_results_map(), attr::num, gtk_poi_search::store_cat, gtk_poi_search::store_cat_sorted, gtk_poi_search::store_poi, gtk_poi_search::store_poi_sorted, gtk_poi_search::treeview_cat, gtk_poi_search::treeview_poi, treeview_poi_changed(), treeview_poi_reload(), and attr::u.
Referenced by poi_search_action().