navit: gui/internal/gui_internal_command.h File Reference
gui_internal_command.h File Reference
Functions
char * gui_internal_coordinates (struct pcoord *pc, char sep)
Converts a coordinate pair to its WGS84 string representation.
void gui_internal_cmd2_quit (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
void gui_internal_command_init (struct gui_priv *this, struct attr **attrs)
Function Documentation
void gui_internal_cmd2_quit (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid)
References config_remove_attr(), event_main_loop_quit(), gui_internal_prune_menu(), attr::navit, NULL, attr::type, and attr::u.
Referenced by gui_internal_window_closed().
void gui_internal_command_init (struct gui_priv * this, struct attr ** attrs)
References attr_search(), attr::callback_list, command_add_table(), NULL, and attr::u.
Referenced by gui_internal_new().
char* gui_internal_coordinates (struct pcoord * pc, char sep)
Converts a coordinate pair to its WGS84 string representation.
This function takes a coordinate pair, transforms it to WGS84 and converts it to a string of the form
45°28'0" N 9°11'26" E
.
Parameters
gc A coordinate pair
sep The separator character to insert between latitude and longitude
Returns
The coordinates as a formatted string
References coordinates_geo(), pcoord::pro, transform_to_geo(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd_position_do().