navit: gui/internal/gui_internal_search.h File Reference
gui_internal_search.h File Reference
Functions
void gui_internal_search_idle_end (struct gui_priv *this)
void gui_internal_search_list_destroy (struct gui_priv *this)
void gui_internal_search (struct gui_priv *this, const char *what, const char *type, int flags)
void gui_internal_search_house_number_in_street (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_search_street_in_town (struct gui_priv *this, struct widget *widget, void *data)
void gui_internal_search_town_in_country (struct gui_priv *this, struct widget *widget)
Function Documentation
void gui_internal_search (struct gui_priv * this, const char * what, const char * type, int flags)
References widget::background, background, country, widget::flags, flags_expand, flags_fill, widget::func, g_free(), g_strdup(), g_strdup_printf(), getenv, gravity_center, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_back(), gui_internal_box_new(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_data(), gui_internal_menu_render(), gui_internal_search_changed(), gui_internal_search_country(), gui_internal_search_house_number(), gui_internal_search_list_new(), gui_internal_search_street(), gui_internal_search_town(), gui_internal_widget_append(), gui_internal_widget_table_new(), image_new_xs(), widget::name, NULL, orientation_horizontal, orientation_vertical, menu_data::search_list, widget::state, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, strtolower(), VKBD_FLAG_2, VKBD_NUMERIC, and widget::w.
Referenced by gui_internal_cmd2_town(), gui_internal_search_country(), gui_internal_search_house_number(), gui_internal_search_house_number_in_street(), gui_internal_search_street(), gui_internal_search_street_in_town(), gui_internal_search_town(), and gui_internal_search_town_in_country().
void gui_internal_search_house_number_in_street (struct gui_priv * this, struct widget * widget, void * data)
References _, dbg, gui_internal_search(), lvl_info, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position(), and gui_internal_cmd_position_do().
void gui_internal_search_idle_end (struct gui_priv * this)
References callback_destroy(), event_remove_idle(), and NULL.
Referenced by gui_internal_check_exit(), gui_internal_menu(), gui_internal_prune_menu_do(), gui_internal_search_changed(), and gui_internal_search_idle().
void gui_internal_search_list_destroy (struct gui_priv * this)
References NULL, and search_list_destroy().
Referenced by gui_internal_check_exit().
void gui_internal_search_street_in_town (struct gui_priv * this, struct widget * widget, void * data)
References _, dbg, gui_internal_search(), lvl_info, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position_do().
void gui_internal_search_town_in_country (struct gui_priv * this, struct widget * widget)
References dbg, g_free(), g_strdup(), gui_internal_search(), iso2, lvl_info, widget::name, search_list_select(), and widget::selection_id.
Referenced by gui_internal_cmd_position().