navit: gui/gtk/gui_gtk_poi.c File Reference
gui_gtk_poi.c File Reference
#include <stdlib.h>
#include <gtk/gtk.h>
#include "gui_gtk_poi.h"
#include "popup.h"
#include "debug.h"
#include "navit_nls.h"
#include "coord.h"
#include "point.h"
#include "callback.h"
#include "graphics.h"
#include "navit.h"
#include "item.h"
#include "map.h"
#include "mapset.h"
#include "transform.h"
#include "attr.h"
#include "util.h"
#include "navigation.h"
Data Structures
struct gtk_poi_search
Functions
static GdkPixbuf * geticon (const char *name)
static GtkTreeModel * category_list_model (struct gtk_poi_search *search)
static GtkTreeModel * model_poi (struct gtk_poi_search *search)
static void treeview_poi_changed (GtkWidget *widget, struct gtk_poi_search *search)
static void treeview_poi_reload (GtkWidget *widget, struct gtk_poi_search *search)
static void button_destination_clicked (GtkWidget *widget, struct gtk_poi_search *search)
static void button_map_clicked (GtkWidget *widget, struct gtk_poi_search *search)
static void button_visit_clicked (GtkWidget *widget, struct gtk_poi_search *search)
void gtk_gui_poi (struct navit *nav)
Variables
static struct gtk_poi_search gtk_poi_search
Function Documentation
button_destination_clicked()
static void button_destination_clicked (GtkWidget * widget, struct gtk_poi_search * search) static
Set the selected POI as destination.
References _, dbg, label, lat, lvl_debug, gtk_poi_search::nav, navit_set_destination(), pcoord::pro, gtk_poi_search::store_cat_sorted, gtk_poi_search::store_poi_sorted, gtk_poi_search::treeview_cat, gtk_poi_search::treeview_poi, pcoord::x, and pcoord::y.
Referenced by gtk_gui_poi().
button_map_clicked()
static void button_map_clicked (GtkWidget * widget, struct gtk_poi_search * search) static
References _, dbg, lat, lvl_debug, gtk_poi_search::nav, navit_set_center(), pcoord::pro, gtk_poi_search::store_poi_sorted, gtk_poi_search::treeview_poi, pcoord::x, and pcoord::y.
Referenced by gtk_gui_poi().
button_visit_clicked()
static void button_visit_clicked (GtkWidget * widget, struct gtk_poi_search * search) static
Set POI as the first "visit before".
References _, dbg, lat, lvl_debug, gtk_poi_search::nav, popup_set_visitbefore(), pcoord::pro, gtk_poi_search::store_poi_sorted, gtk_poi_search::treeview_poi, pcoord::x, and pcoord::y.
Referenced by gtk_gui_poi().
category_list_model()
static GtkTreeModel* category_list_model (struct gtk_poi_search * search) static
Build the category list model with icons.
References _, geticon(), gtk_poi_search::store_cat, and gtk_poi_search::store_cat_sorted.
Referenced by gtk_gui_poi().
geticon()
static GdkPixbuf* geticon (const char * name) static
References dbg, graphics_icon_path(), and lvl_error.
Referenced by category_list_model().
gtk_gui_poi()
void gtk_gui_poi (struct navit * nav)
Create UI and connect objects to functions.
References _, gtk_poi_search::button_destination, button_destination_clicked(), gtk_poi_search::button_map, button_map_clicked(), gtk_poi_search::button_visit, button_visit_clicked(), category_list_model(), gtk_poi_search::entry_distance, gtk_poi_search, gtk_poi_search::label_distance, gtk_poi_search::nav, navit_get_attr(), attr::num, gtk_poi_search::store_cat, gtk_poi_search::store_cat_sorted, gtk_poi_search::store_poi, gtk_poi_search::store_poi_sorted, gtk_poi_search::treeview_cat, gtk_poi_search::treeview_poi, treeview_poi_changed(), treeview_poi_reload(), and attr::u.
Referenced by poi_search_action().
model_poi()
static GtkTreeModel* model_poi (struct gtk_poi_search * search) static
Construct model of POIs from map information.
If the user has selected imperial, translate idist from meters to feet. We convert to feet only, and not miles, because the code sorts on the numeric value of the distance, so it doesn't like two different units. Currently, the distance is an int. Can it be made a float? Possible future enhancement?
References _, gtk_poi_search::entry_distance, FEET_PER_METER, get_compass_direction(), item, item_attr_get(), item_coord_get(), item_from_name(), gtk_poi_search::label_distance, map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), map_selection_dup_pro(), map_selection_rect_new(), mapset_close(), mapset_next(), mapset_open(), METERS_TO_MILES, gtk_poi_search::nav, navit_get_attr(), navit_get_height(), navit_get_mapset(), navit_get_trans(), navit_get_width(), attr::num, pcoord::pro, projection_mg, gtk_poi_search::selected_cat, gtk_poi_search::store_poi, gtk_poi_search::store_poi_sorted, attr::str, transform_distance(), transform_get_angle_delta(), transform_get_projection(), transform_reverse(), transform_scale(), item::type, attr::u, point::x, coord::x, pcoord::x, point::y, coord::y, and pcoord::y.
Referenced by treeview_poi_reload().
treeview_poi_changed()
static void treeview_poi_changed (GtkWidget * widget, struct gtk_poi_search * search) static
Enable button if there is a selected row.
References gtk_poi_search::button_destination, gtk_poi_search::button_map, gtk_poi_search::button_visit, gtk_poi_search::store_cat_sorted, and gtk_poi_search::treeview_cat.
Referenced by gtk_gui_poi().
treeview_poi_reload()
static void treeview_poi_reload (GtkWidget * widget, struct gtk_poi_search * search) static
Reload the POI list and disable buttons.
References gtk_poi_search::button_destination, gtk_poi_search::button_map, gtk_poi_search::button_visit, model_poi(), gtk_poi_search::selected_cat, gtk_poi_search::store_cat_sorted, gtk_poi_search::treeview_cat, and gtk_poi_search::treeview_poi.
Referenced by gtk_gui_poi().
Variable Documentation
gtk_poi_search
struct gtk_poi_search gtk_poi_search static
Referenced by gtk_gui_poi().