navit: gui/internal/gui_internal_menu.h File Reference
gui_internal_menu.h File Reference
Functions
void gui_internal_prune_menu (struct gui_priv *this, struct widget *w)
void gui_internal_prune_menu_count (struct gui_priv *this, int count, int render)
struct widget * gui_internal_menu (struct gui_priv *this, const char *label)
Initializes a GUI screen.
struct menu_data * gui_internal_menu_data (struct gui_priv *this)
void gui_internal_menu_reset_pack (struct gui_priv *this)
void gui_internal_menu_render (struct gui_priv *this)
struct widget * gui_internal_top_bar (struct gui_priv *this)
Function Documentation
struct widget* gui_internal_menu (struct gui_priv * this, const char * label)
Initializes a GUI screen.
This method initializes the internal GUI's screen on which all other elements (such as HTML menus, dialogs or others) are displayed.
It sets up a view hierarchy, which includes a title bar and a client area to hold widgets defined by the caller.
Parameters
this The GUI instance
label The label to display in the top bar
Returns
The container for caller-defined widgets
References _, widget::background, background, widget::bb, widget::bl, padding::bottom, widget::br, widget::bt, menu_data::button_bar, dbg, widget::flags, flags_expand, flags_fill, widget::func, g_new0, graphics_get_data(), gravity_center, gravity_left_center, gravity_right_center, gui_internal_apply_config(), gui_internal_back(), gui_internal_box_new(), gui_internal_box_new_with_label(), gui_internal_button_label(), gui_internal_search_idle_end(), gui_internal_time_help(), gui_internal_top_bar(), gui_internal_widget_append(), gui_internal_widget_pack(), gui_internal_widget_reset_pack(), widget::h, padding::left, lvl_info, lvl_warning, widget::menu_data, NULL, orientation_horizontal, orientation_horizontal_vertical, orientation_vertical, widget::p, padding::right, widget::spx, widget::state, STATE_SENSITIVE, padding::top, widget::w, point::x, and point::y.
Referenced by gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_description(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_rules(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_log(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_html_text(), gui_internal_menu_vehicle_settings(), gui_internal_search(), and gui_internal_select_waypoint().
struct menu_data* gui_internal_menu_data (struct gui_priv * this)
References _GList::data, g_list_last(), and widget::menu_data.
Referenced by gui_internal_button_label(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_highlight_possible_keys(), gui_internal_html_text(), gui_internal_keyboard_do(), gui_internal_keyboard_show_native(), gui_internal_keyboard_to_lower_case(), gui_internal_keyboard_to_upper_case(), gui_internal_keypress_do(), gui_internal_refresh_callback_called(), gui_internal_search(), gui_internal_search_changed(), and gui_internal_set_refresh_callback().
void gui_internal_menu_render (struct gui_priv * this)
References _GList::data, g_list_last(), gui_internal_say(), gui_internal_widget_pack(), and gui_internal_widget_render().
Referenced by gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_description(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_rules(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_log(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_html_menu(), gui_internal_html_submit(), gui_internal_keyboard_do(), gui_internal_menu_vehicle_settings(), gui_internal_resize(), gui_internal_route_update(), gui_internal_search(), gui_internal_select_waypoint(), gui_internal_table_button_next(), and gui_internal_table_button_prev().
void gui_internal_menu_reset_pack (struct gui_priv * this)
References _GList::data, g_list_last(), and gui_internal_widget_reset_pack().
Referenced by gui_internal_keyboard_do().
void gui_internal_prune_menu (struct gui_priv * this, struct widget * w)
References gui_internal_prune_menu_do().
Referenced by gui_internal_cmd2_back_to_map(), gui_internal_cmd2_quit(), gui_internal_cmd_add_bookmark_do(), gui_internal_cmd_add_bookmark_folder_do(), gui_internal_cmd_copy_bookmark(), gui_internal_cmd_cut_bookmark(), gui_internal_cmd_delete_bookmark(), gui_internal_cmd_delete_bookmark_folder(), gui_internal_cmd_delete_waypoint(), gui_internal_cmd_insert_destination_do(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_log_do(), gui_internal_cmd_main_menu(), gui_internal_cmd_paste_bookmark(), gui_internal_cmd_rename_bookmark_clicked(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_results_map_clean(), gui_internal_cmd_results_to_map(), gui_internal_cmd_return(), gui_internal_cmd_set_destination(), gui_internal_cmd_set_position(), gui_internal_cmd_view_on_map(), gui_internal_html_main_menu(), and gui_internal_keypress().
void gui_internal_prune_menu_count (struct gui_priv * this, int count, int render)
References _GList::data, g_list_last(), g_list_previous, gui_internal_prune_menu_do(), NULL, and widget::w.
Referenced by gui_internal_back(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_set_active_profile(), gui_internal_html_load_href(), and gui_internal_search_country().
struct widget* gui_internal_top_bar (struct gui_priv * this)
References _, widget::background, background, widget::bb, widget::bl, widget::br, widget::bt, widget::data, dbg, widget::flags, flags_expand, flags_fill, widget::foreground, widget::func, g_free(), g_list_last(), g_list_next, g_list_prepend(), g_list_previous, g_strdup(), g_strdup_printf(), gravity_center, gravity_left_center, gravity_right_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_main_menu(), gui_internal_cmd_return(), gui_internal_label_new(), gui_internal_label_new_abbrev(), gui_internal_widget_append(), gui_internal_widget_destroy(), gui_internal_widget_pack(), image_new_s(), lvl_debug, NULL, orientation_horizontal, orientation_vertical, widget::speech, widget::spx, widget::state, STATE_SENSITIVE, widget::text, version, widget::w, and width.
Referenced by gui_internal_menu().