navit: gui/internal/gui_internal_poi.h File Reference
gui_internal_poi.h File Reference
Data Structures
struct poi_param
Functions
void gui_internal_poi_param_free (void *p)
Free poi_param structure.
void gui_internal_poi_param_set_filter (struct poi_param *param, char *text)
Set POIs filter data in poi_param structure.
struct widget * gui_internal_cmd_pois_item (struct gui_priv *this, struct coord *center, struct item *item, struct coord *c, struct route *route, int dist, char *name)
char * gui_internal_compose_item_address_string (struct item *item, int prependPostal)
Get string representation of item address suitable for doing search and for display in POI list.
void gui_internal_cmd_pois_filter (struct gui_priv *this, struct widget *wm, void *data)
POIs filter dialog.
void gui_internal_cmd_pois (struct gui_priv *this, struct widget *wm, void *data)
Do POI search specified by poi_param and display POIs found.
Function Documentation
void gui_internal_cmd_pois (struct gui_priv * this, struct widget * wm, void * data)
Do POI search specified by poi_param and display POIs found.
Parameters
this The graphics context.
wm called widget.
data event data, reference to poi_param or NULL.
References _, poi_param::AddressFilterType, widget::background, background, table_data::bottom_row, item_data::c, widget::c, c, map_selection::c_rect, widget::children, coord_rect_contains(), poi_param::count, widget::data, _GList::data, data, widget::data_free, widget::datai, dbg, poi_param::dist, item_data::dist, fh_deleteheap(), fh_extractmin(), fh_insertkey(), fh_makekeyheap(), fh_minkey(), poi_param::filter, poi_param::filterstr, flags_expand, flags_fill, widget::func, g_free(), g_list_index(), g_new0, g_strdup(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_pois_more(), gui_internal_cmd_pois_selector(), gui_internal_compose_item_address_string(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_poi_param_clone(), gui_internal_poi_param_free(), gui_internal_table_button_next(), gui_internal_widget_append(), gui_internal_widget_prepend(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), i, item_data::item, item, item_attr_get(), item_attr_rewind(), item_coord_get_pro(), key, item_data::label, label, lvl_debug, item::map, map_convert_string(), map_convert_string_tmp(), map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), map_selection_dup_pro(), map_selection_rect_new(), mapset_close(), mapset_next(), mapset_open(), selector::name, navit_get_attr(), navit_get_mapset(), scroll_buttons::next_button, NULL, attr::num, orientation_horizontal, orientation_vertical, poi_param::pagenb, pcoord::pro, attr::route, route_get_attr(), route_status_path_done_incremental, route_status_path_done_new, row, table_data::scroll_buttons, poi_param::sel, poi_param::selnb, widget::state, STATE_SENSITIVE, attr::str, table_data::top_row, transform_distance(), transform_scale(), item::type, map_selection::u, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2_pois(), gui_internal_cmd_pois_filter_do(), gui_internal_cmd_pois_more(), gui_internal_cmd_pois_selector(), and gui_internal_cmd_position_do().
void gui_internal_cmd_pois_filter (struct gui_priv * this, struct widget * wm, void * data)
POIs filter dialog.
Parameters
this The graphics context.
wm called widget.
data event data.
References widget::background, background, widget::c, widget::data, widget::flags, flags_expand, flags_fill, widget::func, g_strdup(), getenv, gravity_center, gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_cmd_pois_filter_changed(), gui_internal_cmd_pois_filter_do(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), widget::name, NULL, orientation_horizontal, orientation_vertical, widget::state, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_FLAG_2, and widget::w.
Referenced by gui_internal_cmd_pois_selector().
struct widget* gui_internal_cmd_pois_item (struct gui_priv * this, struct coord * center, struct item * item, struct coord * c, struct route * route, int dist, char * name)
References widget::data, widget::datai, flags_fill, format_dist(), widget::func, g_free(), g_strdup(), g_strdup_printf(), get_compass_direction(), gravity_left_center, gui_internal_button_new_with_callback(), gui_internal_cmd_position(), gui_internal_poi_icon(), image_new_xs(), widget::item, item, item_to_name(), widget::name, NULL, orientation_horizontal, route_get_distances(), widget::state, STATE_SENSITIVE, widget::text, transform_get_angle_delta(), item::type, and type.
Referenced by gui_internal_cmd_pois(), and gui_internal_cmd_position_do().
char* gui_internal_compose_item_address_string (struct item * item, int prependPostal)
Get string representation of item address suitable for doing search and for display in POI list.
Parameters
item reference to item.
Returns
Pointer to string representation of address. To be g_free()d after use.
References g_strdup(), g_strjoin(), item_attr_get(), item::map, map_convert_string_tmp(), NULL, attr::str, and attr::u.
Referenced by gui_internal_cmd_pois(), and gui_internal_cmd_pois_item_selected().
void gui_internal_poi_param_free (void * p)
Free poi_param structure.
Parameters
p reference to the object to be freed.
References g_free(), and g_list_free().
Referenced by gui_internal_cmd2_pois(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter_do(), and gui_internal_cmd_pois_selector().
void gui_internal_poi_param_set_filter (struct poi_param * param, char * text)
Set POIs filter data in poi_param structure.
Parameters
param poi_param structure with unset filter data.
text filter text.
References poi_param::filter, poi_param::filterstr, g_list_append(), g_utf8_strchr(), removecase(), s1, and s2.
Referenced by gui_internal_cmd2_pois(), and gui_internal_cmd_pois_filter_do().