navit: gui/internal/gui_internal_gesture.h File Reference
gui_internal_gesture.h File Reference
Functions
void gui_internal_gesture_ring_clear (struct gui_priv *this)
void gui_internal_gesture_ring_add (struct gui_priv *this, struct point *p)
int gui_internal_gesture_get_vector (struct gui_priv *this, long long msec, struct point *p0, int *dx, int *dy)
int gui_internal_gesture_do (struct gui_priv *this)
Function Documentation
int gui_internal_gesture_do (struct gui_priv * this)
References widget::data, dbg, gui_internal_gesture_get_vector(), gui_internal_table_button_next(), gui_internal_table_button_prev(), lvl_debug, widget::parent, STATE_HIGHLIGHTED, widget::type, and widget_table.
Referenced by gui_internal_button().
int gui_internal_gesture_get_vector (struct gui_priv * this, long long msec, struct point * p0, int * dx, int * dy)
References dbg, gui_internal_gesture_ring_get(), LONGLONG_FMT, lvl_info, point::x, and point::y.
Referenced by gui_internal_button(), gui_internal_gesture_do(), and gui_internal_motion_cb().
void gui_internal_gesture_ring_add (struct gui_priv * this, struct point * p)
References dbg, GESTURE_RINGSIZE, LONGLONG_FMT, lvl_info, p, point::x, and point::y.
Referenced by gui_internal_button(), and gui_internal_motion_cb().
void gui_internal_gesture_ring_clear (struct gui_priv * this)
Referenced by gui_internal_button().