navit: gui/qt5_qml/gui_qt5_qml.cpp File Reference
gui_qt5_qml.cpp File Reference
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <glib.h>
#include "item.h"
#include "attr.h"
#include "bookmarks.h"
#include "callback.h"
#include "color.h"
#include "command.h"
#include "config.h"
#include "coord.h"
#include "country.h"
#include "debug.h"
#include "event.h"
#include "point.h"
#include "graphics.h"
#include "gui.h"
#include "keys.h"
#include "map.h"
#include "mapset.h"
#include "navit.h"
#include "plugin.h"
#include "route.h"
#include "search.h"
#include "track.h"
#include "transform.h"
#include "vehicle.h"
#include "xmlconfig.h"
#include "layout.h"
#include "backend.h"
Data Structures
struct gui_priv
Functions
static void gui_qt5_qml_button (void *data, int pressed, int button, struct point *p)
static void gui_qt5_qml_motion (void *data, struct point *p)
static void gui_qt5_qml_resize (void *data, int w, int h)
static void gui_qml_keypress (void *data, char *key)
static int gui_qt5_qml_set_graphics (struct gui_priv *gui_priv, struct graphics *gra)
static int gui_qt5_qml_get_attr (struct gui_priv *gui_priv, enum attr_type type, struct attr *attr)
static int gui_qt5_qml_set_attr (struct gui_priv *gui_priv, struct attr *attr)
static struct gui_priv * gui_qt5_qml_new (struct navit *nav, struct gui_methods *meth, struct attr **attrs, struct gui *gui)
void plugin_init (void)
Variables
struct gui_methods gui_qt5_qml_methods
Function Documentation
static void gui_qml_keypress (void * data, char * key) static
References dbg, gui_priv::h, lvl_debug, gui_priv::nav, navit_get_trans(), NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_MENU, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, NAVIT_KEY_ZOOM_OUT, navit_set_center_screen(), navit_zoom_in(), navit_zoom_out(), NULL, transform_get_size(), gui_priv::w, point::x, and point::y.
Referenced by gui_qt5_qml_set_graphics().
static void gui_qt5_qml_button (void * data, int pressed, int button, struct point * p) static
References gui_priv::backend, dbg, lvl_debug, gui_priv::menu_on_map_click, gui_priv::nav, navit_handle_button(), NULL, and Backend::showMenu().
Referenced by gui_qt5_qml_set_graphics().
static int gui_qt5_qml_get_attr (struct gui_priv * gui_priv, enum attr_type type, struct attr * attr) static
References dbg, and lvl_debug.
static void gui_qt5_qml_motion (void * data, struct point * p) static
References dbg, lvl_debug, gui_priv::nav, navit_handle_motion(), point::x, and point::y.
Referenced by gui_qt5_qml_set_graphics().
static struct gui_priv* gui_qt5_qml_new (struct navit * nav, struct gui_methods * meth, struct attr ** attrs, struct gui * gui) static
References attr_search(), gui_priv::attributes, callback_list_new(), gui_priv::callbacks, dbg, g_new0, gui_priv::gui, attr::gui, gui_qt5_qml_methods, lvl_debug, gui_priv::menu_on_map_click, gui_priv::nav, NULL, attr::num, attr::type, and attr::u.
Referenced by plugin_init().
static void gui_qt5_qml_resize (void * data, int w, int h) static
References dbg, lvl_debug, gui_priv::nav, and navit_handle_resize().
Referenced by gui_qt5_qml_set_graphics().
static int gui_qt5_qml_set_attr (struct gui_priv * gui_priv, struct attr * attr) static
References dbg, and lvl_debug.
static int gui_qt5_qml_set_graphics (struct gui_priv * gui_priv, struct graphics * gra) static
References gui_priv::backend, gui_priv::button_cb, callback_cast, callback_new_attr_1, dbg, gui_priv::engine, gui_priv::gra, graphics_add_callback(), graphics_get_data(), gui_qml_keypress(), gui_qt5_qml_button(), gui_qt5_qml_motion(), gui_qt5_qml_resize(), gui_priv::h, gui_priv::keypress_cb, gui_priv::loader, lvl_debug, lvl_error, gui_priv::motion_cb, gui_priv::nav, navit_draw(), navit_get_trans(), navit_ignore_graphics_events(), NULL, gui_priv::resize_cb, Backend::set_engine(), Backend::set_navit(), trans, transform_get_size(), gui_priv::w, and gui_priv::win.
void plugin_init (void)
References gui_qt5_qml_new().
Variable Documentation
struct gui_methods gui_qt5_qml_methods
Initial value:
= {
    NULL,
    NULL,
    gui_qt5_qml_set_graphics,
    NULL,
    NULL,
    NULL,
    NULL,
    gui_qt5_qml_get_attr,
    NULL,
    gui_qt5_qml_set_attr,
}
Referenced by gui_qt5_qml_new().