navit: gui/internal/gui_internal_widget.h File Reference
gui_internal_widget.h File Reference
Data Structures
struct widget
struct scroll_buttons
struct table_data
A structure to store information about a table.
struct table_column_desc
Enumerations
enum gui_internal_reason { gui_internal_reason_click =1, gui_internal_reason_keypress, gui_internal_reason_keypress_finish }
Functions
struct widget * gui_internal_label_font_new (struct gui_priv *this, const char *text, int font)
struct widget * gui_internal_label_new (struct gui_priv *this, const char *text)
struct widget * gui_internal_label_new_abbrev (struct gui_priv *this, const char *text, int maxwidth)
struct widget * gui_internal_image_new (struct gui_priv *this, struct graphics_image *image)
struct widget * gui_internal_text_font_new (struct gui_priv *this, const char *text, int font, enum flags flags)
Creates a text box.
struct widget * gui_internal_text_new (struct gui_priv *this, const char *text, enum flags flags)
struct widget * gui_internal_button_font_new_with_callback (struct gui_priv *this, const char *text, int font, struct graphics_image *image, enum flags flags, void(*func)(struct gui_priv *priv, struct widget *widget, void *data), void *data)
struct widget * gui_internal_button_new_with_callback (struct gui_priv *this, const char *text, struct graphics_image *image, enum flags flags, void(*func)(struct gui_priv *priv, struct widget *widget, void *data), void *data)
struct widget * gui_internal_button_new (struct gui_priv *this, const char *text, struct graphics_image *image, enum flags flags)
struct widget * gui_internal_find_widget (struct widget *wi, struct point *p, int flags)
void gui_internal_highlight_do (struct gui_priv *this, struct widget *found)
void gui_internal_highlight (struct gui_priv *this)
struct widget * gui_internal_box_new_with_label (struct gui_priv *this, enum flags flags, const char *label)
struct widget * gui_internal_box_new (struct gui_priv *this, enum flags flags)
void gui_internal_widget_reset_pack (struct gui_priv *this, struct widget *w)
void gui_internal_widget_append (struct widget *parent, struct widget *child)
Adds a child widget to a parent widget, making it the last child.
void gui_internal_widget_prepend (struct widget *parent, struct widget *child)
Adds a child widget to a parent widget, making it the first child.
void gui_internal_widget_insert_sorted (struct widget *parent, struct widget *child, GCompareFunc func)
Adds a child widget to a parent widget.
void gui_internal_widget_children_destroy (struct gui_priv *this, struct widget *w)
Destroys all child widgets.
void gui_internal_widget_destroy (struct gui_priv *this, struct widget *w)
Destroys a widget.
void gui_internal_widget_render (struct gui_priv *this, struct widget *w)
void gui_internal_widget_pack (struct gui_priv *this, struct widget *w)
struct widget * gui_internal_button_label (struct gui_priv *this, const char *label, int mode)
struct widget * gui_internal_widget_table_new (struct gui_priv *this, enum flags flags, int buttons)
Creates a new table widget.
void gui_internal_widget_table_clear (struct gui_priv *this, struct widget *table)
Clears all the rows from the table.
GList * gui_internal_widget_table_next_row (GList *row)
Moves GList pointer to the next table row, skipping other table children (button box, for example).
GList * gui_internal_widget_table_prev_row (GList *row)
Moves GList pointer to the previous table row, skipping other table children (button box, for example).
GList * gui_internal_widget_table_first_row (GList *row)
Moves GList pointer to the first table row, skipping other table children (button box, for example).
GList * gui_internal_widget_table_top_row (struct gui_priv *this, struct widget *table)
Gets GList pointer to the table row drawn on the top of the screen.
GList * gui_internal_widget_table_set_top_row (struct gui_priv *this, struct widget *table, struct widget *row)
Sets internal top row pointer of the table to point to a given row widget.
struct widget * gui_internal_widget_table_row_new (struct gui_priv *this, enum flags flags)
Creates a new table_row widget.
void gui_internal_table_pack (struct gui_priv *this, struct widget *w)
Computes the height and width for the table.
void gui_internal_table_hide_rows (struct table_data *table_data)
Invalidates coordinates for previously rendered table widget rows.
void gui_internal_table_render (struct gui_priv *this, struct widget *w)
Renders a table widget.
void gui_internal_table_button_next (struct gui_priv *this, struct widget *wm, void *data)
Handles the 'next page' table event.
void gui_internal_table_button_prev (struct gui_priv *this, struct widget *wm, void *data)
Handles the 'previous page' table event.
void gui_internal_table_data_free (void *p)
Deallocates a table_data structure.
Enumeration Type Documentation
enum gui_internal_reason
Enumerator
gui_internal_reason_click
gui_internal_reason_keypress
gui_internal_reason_keypress_finish
Function Documentation
struct widget* gui_internal_box_new (struct gui_priv * this, enum flags flags)
References gui_internal_box_new_with_label(), and NULL.
Referenced by gui_internal_button_font_new_with_callback(), gui_internal_button_label(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_description(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_rules(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_log(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_pois_selector(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_create_resultlist_entry(), gui_internal_html_start(), gui_internal_html_text(), gui_internal_keyboard_do(), gui_internal_keyboard_show_native(), gui_internal_menu(), gui_internal_scroll_buttons_init(), gui_internal_search(), gui_internal_select_waypoint(), gui_internal_text_font_new(), gui_internal_time_help(), and gui_internal_top_bar().
struct widget* gui_internal_box_new_with_label (struct gui_priv * this, enum flags flags, const char * label)
References widget::flags, g_new0, g_strdup(), widget::text, widget::type, and widget_box.
Referenced by gui_internal_box_new(), and gui_internal_menu().
struct widget* gui_internal_button_font_new_with_callback (struct gui_priv * this, const char * text, int font, struct graphics_image * image, enum flags flags, void(*)(struct gui_priv *priv, struct widget *widget, void *data) func, void * data)
References widget::data, data, flags_swap, widget::func, g_strdup(), gravity_center, gui_internal_box_new(), gui_internal_image_new(), gui_internal_text_font_new(), gui_internal_widget_append(), NULL, orientation_vertical, widget::speech, widget::state, and STATE_SENSITIVE.
Referenced by gui_internal_button_new_with_callback(), and gui_internal_keyboard_key_data().
struct widget* gui_internal_button_label (struct gui_priv * this, const char * label, int mode)
References widget::bb, widget::bl, widget::border, widget::br, widget::bt, menu_data::button_bar, widget::foreground, gravity_right_center, gui_internal_box_new(), gui_internal_label_new(), gui_internal_menu_data(), gui_internal_widget_append(), gui_internal_widget_prepend(), and orientation_vertical.
Referenced by gui_internal_menu().
struct widget* gui_internal_button_new (struct gui_priv * this, const char * text, struct graphics_image * image, enum flags flags)
References gui_internal_button_new_with_callback(), and NULL.
Referenced by gui_internal_cmd_position_do(), and gui_internal_cmd_view_attributes().
struct widget* gui_internal_button_new_with_callback (struct gui_priv * this, const char * text, struct graphics_image * image, enum flags flags, void(*)(struct gui_priv *priv, struct widget *widget, void *data) func, void * data)
References widget::func, and gui_internal_button_font_new_with_callback().
Referenced by gui_internal_add_vehicle_profile(), gui_internal_button_map_attr_new(), gui_internal_button_navit_attr_new(), gui_internal_button_new(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_map_download(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_selector(), gui_internal_cmd_position_do(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_create_resultlist_entry(), gui_internal_menu_vehicle_settings(), gui_internal_scroll_buttons_init(), gui_internal_select_waypoint(), gui_internal_time_help(), and gui_internal_top_bar().
struct widget* gui_internal_find_widget (struct widget * wi, struct point * p, int flags)
References widget::children, _GList::data, g_list_next, gui_internal_find_widget(), widget::h, NULL, widget::p, widget::state, widget::w, point::x, and point::y.
Referenced by gui_internal_find_widget(), gui_internal_highlight(), gui_internal_keypress_do(), and gui_internal_search_idle().
void gui_internal_highlight (struct gui_priv * this)
References _GList::data, g_list_last(), gui_internal_find_widget(), gui_internal_highlight_do(), gui_internal_widget_render(), NULL, widget::state, STATE_EDIT, STATE_EDITABLE, and STATE_SENSITIVE.
Referenced by gui_internal_button(), gui_internal_keyboard_do(), gui_internal_keypress_do(), and gui_internal_motion_cb().
void gui_internal_highlight_do (struct gui_priv * this, struct widget * found)
References _GList::data, dbg, draw_mode_begin, draw_mode_end, g_list_last(), graphics_draw_mode(), gui_internal_widget_render(), widget::h, lvl_debug, NULL, widget::p, STATE_HIGHLIGHTED, widget::w, point::x, and point::y.
Referenced by gui_internal_highlight(), gui_internal_highlight_possible_keys(), gui_internal_html_submit(), and gui_internal_keynav_highlight_next().
struct widget* gui_internal_image_new (struct gui_priv * this, struct graphics_image * image)
References g_new0, widget::h, graphics_image::height, image, widget::img, widget::type, widget::w, widget_image, and graphics_image::width.
Referenced by gui_internal_button_font_new_with_callback(), gui_internal_cmd2_about(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_enter_coord(), gui_internal_cmd_log(), gui_internal_cmd_pois_filter(), gui_internal_cmd_rename_bookmark(), gui_internal_create_resultlist_entry(), gui_internal_search(), and html_image().
struct widget* gui_internal_label_font_new (struct gui_priv * this, const char * text, int font)
References widget::flags, widget::font_idx, widget::foreground, g_new0, g_strdup(), graphics_get_text_bbox(), gravity_center, widget::h, widget::text, widget::text_background, widget::texth, widget::textw, widget::type, widget::w, widget_label, point::x, and point::y.
Referenced by gui_internal_create_resultlist_entry(), gui_internal_keyboard_do(), gui_internal_label_new(), and gui_internal_text_font_new().
struct widget* gui_internal_label_new (struct gui_priv * this, const char * text)
References gui_internal_label_font_new().
Referenced by gui_internal_button_label(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_enter_coord(), gui_internal_cmd_log(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_satellite_status(), gui_internal_create_resultlist_entry(), gui_internal_html_start(), gui_internal_keyboard_do(), gui_internal_label_new_abbrev(), gui_internal_populate_route_table(), gui_internal_search(), gui_internal_select_waypoint(), gui_internal_time_help(), and gui_internal_top_bar().
struct widget* gui_internal_label_new_abbrev (struct gui_priv * this, const char * text, int maxwidth)
References g_free(), g_malloc(), g_utf8_find_prev_char(), gui_internal_label_new(), gui_internal_widget_destroy(), i, NULL, p, widget::text, and widget::w.
Referenced by gui_internal_top_bar().
void gui_internal_table_button_next (struct gui_priv * this, struct widget * wm, void * data)
Handles the 'next page' table event.
A callback function that is invoked when the 'next page' button is pressed to advance the contents of a table widget.
Parameters
this The graphics context.
wm The button widget that was pressed.
data
References table_data::bottom_row, widget::data, g_list_next, gui_internal_menu_render(), gui_internal_table_hide_rows(), NULL, widget::state, STATE_HIGHLIGHTED, table_data::top_row, widget::type, and widget_table.
Referenced by gui_internal_cmd_pois(), gui_internal_gesture_do(), and gui_internal_scroll_buttons_init().
void gui_internal_table_button_prev (struct gui_priv * this, struct widget * wm, void * data)
Handles the 'previous page' table event.
A callback function that is invoked when the 'previous page' button is pressed to go back in the contents of a table widget.
Parameters
this The graphics context.
wm The button widget that was pressed.
References scroll_buttons::button_box, widget::data, _GList::data, data, g_list_previous, gui_internal_menu_render(), gui_internal_table_hide_rows(), widget::h, NULL, widget::p, table_data::scroll_buttons, widget::state, STATE_HIGHLIGHTED, table_data::top_row, widget::type, widget::w, widget_table, and point::y.
Referenced by gui_internal_gesture_do(), and gui_internal_scroll_buttons_init().
void gui_internal_table_data_free (void * p)
Deallocates a table_data structure.
Note
button_box and its children (next_button,prev_button) have their memory managed by the table itself.
Parameters
p The table_data structure
References g_free().
Referenced by gui_internal_widget_table_new().
void gui_internal_table_hide_rows (struct table_data * table_data)
Invalidates coordinates for previously rendered table widget rows.
Parameters
table_data Data from the table object.
References table_data::bottom_row, _GList::data, g_list_next, widget::h, if(), widget::p, table_data::top_row, widget::type, widget::w, widget_table_row, point::x, and point::y.
Referenced by gui_internal_motion_cb(), gui_internal_table_button_next(), gui_internal_table_button_prev(), and gui_internal_table_render().
void gui_internal_table_pack (struct gui_priv * this, struct widget * w)
Computes the height and width for the table.
The height and width are computed to display all cells in the table at the requested height/width.
Parameters
this The graphics context
w The widget to pack.
References scroll_buttons::button_box, widget::c, widget::children, widget::data, _GList::data, g_free(), g_list_foreach(), g_list_free(), g_list_next, gui_internal_compute_table_dimensions(), gui_internal_widget_pack(), widget::h, table_column_desc::height, height, NULL, table_data::scroll_buttons, widget::w, table_column_desc::width, width, pcoord::x, and pcoord::y.
Referenced by gui_internal_widget_pack().
void gui_internal_table_render (struct gui_priv * this, struct widget * w)
Renders a table widget.
Parameters
this The graphics context
w The table widget to render.
References table_data::bottom_row, scroll_buttons::button_box, scroll_buttons::button_box_hide, widget::children, widget::data, _GList::data, dbg_assert, g_free(), g_list_foreach(), g_list_free(), g_list_next, gui_internal_compute_table_dimensions(), gui_internal_table_hide_rows(), gui_internal_widget_pack(), gui_internal_widget_render(), widget::h, if(), scroll_buttons::next_button, NULL, widget::p, scroll_buttons::prev_button, row, table_data::scroll_buttons, widget::state, STATE_INVISIBLE, STATE_OFFSCREEN, STATE_SENSITIVE, table_data::top_row, widget::w, point::x, and point::y.
Referenced by gui_internal_widget_render().
struct widget* gui_internal_text_font_new (struct gui_priv * this, const char * text, int font, enum flags flags)
Creates a text box.
A text box is a widget that renders a text string containing newlines. The string will be broken up into label widgets at each newline with a vertical layout.
Parameters
this The internal GUI instance
text The text to be displayed in the text box
font The font to use for the text
flags
References g_free(), g_strdup(), gui_internal_box_new(), gui_internal_label_font_new(), gui_internal_widget_append(), gui_internal_widget_pack(), NULL, and s2.
Referenced by gui_internal_button_font_new_with_callback(), gui_internal_html_text(), and gui_internal_text_new().
struct widget* gui_internal_text_new (struct gui_priv * this, const char * text, enum flags flags)
References gui_internal_text_font_new().
Referenced by gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_show_nmea_data(), and gui_internal_html_text().
void gui_internal_widget_append (struct widget * parent, struct widget * child)
Adds a child widget to a parent widget, making it the last child.
Parameters
parent The parent widget
child The child widget
References widget::background, widget::children, g_list_append(), and widget::parent.
Referenced by gui_internal_add_vehicle_profile(), gui_internal_button_font_new_with_callback(), gui_internal_button_label(), gui_internal_cmd2_about(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_route_description(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_rules(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_bookmarks(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_cmd_log(), gui_internal_cmd_map_download(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois(), gui_internal_cmd_pois_filter(), gui_internal_cmd_pois_selector(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_show_nmea_data(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_create_resultlist_entry(), gui_internal_html_end(), gui_internal_html_menu(), gui_internal_html_text(), gui_internal_keyboard_do(), gui_internal_keyboard_key_data(), gui_internal_keyboard_show_native(), gui_internal_menu(), gui_internal_menu_vehicle_settings(), gui_internal_populate_route_table(), gui_internal_scroll_buttons_init(), gui_internal_search(), gui_internal_search_idle(), gui_internal_select_waypoint(), gui_internal_text_font_new(), gui_internal_time_help(), gui_internal_top_bar(), and gui_internal_widget_table_new().
void gui_internal_widget_children_destroy (struct gui_priv * this, struct widget * w)
Destroys all child widgets.
This function is recursive, destroying all widgets in the child hierarchy of
w
.
Parameters
this The internal GUI instance
w The widget whose children are to be destroyed
References widget::children, _GList::data, g_list_free(), g_list_next, gui_internal_widget_destroy(), and NULL.
Referenced by gui_internal_keyboard_do(), and gui_internal_widget_destroy().
void gui_internal_widget_destroy (struct gui_priv * this, struct widget * w)
Destroys a widget.
This function also takes care of recursively destroying the entire child widget hierarchy of
w
prior to destroying
w
itself.
Parameters
this The internal GUI instance
w The widget to destroy
References widget::cb, widget::command, widget::data, widget::data_free, g_free(), graphics_image_free(), gui_internal_widget_children_destroy(), widget::img, widget::instance, widget::name, NULL, widget::prefix, widget::remove_cb, widget::speech, widget::text, and widget::wfree.
Referenced by gui_internal_cmd_bookmarks(), gui_internal_label_new_abbrev(), gui_internal_menu_destroy(), gui_internal_top_bar(), gui_internal_widget_children_destroy(), and gui_internal_widget_table_clear().
void gui_internal_widget_insert_sorted (struct widget * parent, struct widget * child, GCompareFunc func)
Adds a child widget to a parent widget.
Placement of the child widget among its siblings depends on the comparison function
func
.
Parameters
parent The parent widget
child The child widget
func The comparison function
References widget::background, widget::children, g_list_insert_sorted(), and widget::parent.
Referenced by gui_internal_search_idle().
void gui_internal_widget_pack (struct gui_priv * this, struct widget * w)
References gui_internal_box_pack(), gui_internal_table_pack(), widget::type, widget_box, and widget_table.
Referenced by gui_internal_box_pack(), gui_internal_cmd_pois_selector(), gui_internal_compute_table_dimensions(), gui_internal_keyboard_do(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_scroll_buttons_init(), gui_internal_search_idle(), gui_internal_table_pack(), gui_internal_table_render(), gui_internal_text_font_new(), and gui_internal_top_bar().
void gui_internal_widget_prepend (struct widget * parent, struct widget * child)
Adds a child widget to a parent widget, making it the first child.
Parameters
parent The parent widget
child The child widget
References widget::background, widget::children, g_list_prepend(), and widget::parent.
Referenced by gui_internal_button_label(), gui_internal_cmd_formerdests(), and gui_internal_cmd_pois().
void gui_internal_widget_render (struct gui_priv * this, struct widget * w)
References gui_internal_box_render(), gui_internal_image_render(), gui_internal_label_render(), gui_internal_table_render(), widget::p, widget::state, STATE_INVISIBLE, widget::type, widget_box, widget_image, widget_label, widget_table, point::x, and point::y.
Referenced by gui_internal_box_render(), gui_internal_button_attr_callback(), gui_internal_highlight(), gui_internal_highlight_do(), gui_internal_highlight_possible_keys(), gui_internal_keyboard_do(), gui_internal_keypress_do(), gui_internal_menu_render(), gui_internal_motion_cb(), gui_internal_prune_menu_do(), gui_internal_search_changed(), gui_internal_search_idle(), and gui_internal_table_render().
void gui_internal_widget_reset_pack (struct gui_priv * this, struct widget * w)
References widget::children, _GList::data, g_list_next, gui_internal_widget_reset_pack(), widget::h, widget::packed, and widget::w.
Referenced by gui_internal_menu(), gui_internal_menu_reset_pack(), and gui_internal_widget_reset_pack().
void gui_internal_widget_table_clear (struct gui_priv * this, struct widget * table)
Clears all the rows from the table.
This function removes all rows from a table. New rows can later be added to the table.
Parameters
this The internal GUI instance
table The table widget
References table_data::bottom_row, scroll_buttons::button_box, widget::children, widget::data, _GList::data, g_list_next, g_list_remove(), gui_internal_widget_destroy(), eval::iter, NULL, table_data::scroll_buttons, and table_data::top_row.
Referenced by gui_internal_populate_route_table(), and gui_internal_search_changed().
GList* gui_internal_widget_table_first_row (GList * row)
Moves GList pointer to the first table row, skipping other table children (button box, for example).
Parameters
row GList pointer into the children list
Returns
GList pointer to the first row in the children list, or NULL if table is empty.
References _GList::data, gui_internal_widget_table_next_row(), NULL, row, and widget_table_row.
Referenced by gui_internal_widget_table_set_top_row(), and gui_internal_widget_table_top_row().
struct widget* gui_internal_widget_table_new (struct gui_priv * this, enum flags flags , int buttons)
Creates a new table widget.
Creates and returns a new table widget. This function will setup next/previous buttons as children.
Parameters
this The graphics context.
flags widget sizing flags.
Returns
The newly created widget
References widget::background, background, scroll_buttons::button_box, widget::data, data, widget::data_free, widget::flags, g_new0, gui_internal_scroll_buttons_init(), gui_internal_table_data_free(), gui_internal_widget_append(), if(), NULL, table_data::scroll_buttons, widget::state, STATE_SCROLLABLE, widget::type, and widget_table.
Referenced by gui_internal_cmd2_route_description(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_pois(), gui_internal_cmd_position_do(), gui_internal_cmd_show_satellite_status(), gui_internal_menu_vehicle_settings(), gui_internal_search(), and gui_internal_select_waypoint().
GList* gui_internal_widget_table_next_row (GList * row)
Moves GList pointer to the next table row, skipping other table children (button box, for example).
Parameters
row GList pointer into the children list
Returns
GList pointer to the next row in the children list, or NULL if there are no any rows left.
References _GList::data, g_list_next, NULL, row, and widget_table_row.
Referenced by gui_internal_motion_cb(), and gui_internal_widget_table_first_row().
GList* gui_internal_widget_table_prev_row (GList * row)
Moves GList pointer to the previous table row, skipping other table children (button box, for example).
Parameters
row GList pointer into the children list
Returns
GList pointer to the previous row in the children list, or NULL if there are no any rows left.
References _GList::data, g_list_previous, NULL, row, and widget_table_row.
Referenced by gui_internal_motion_cb().
struct widget* gui_internal_widget_table_row_new (struct gui_priv * this, enum flags flags)
Creates a new table_row widget.
Parameters
this The graphics context
flags Sizing flags for the row
Returns
The new table_row widget.
References widget::flags, g_new0, widget::type, and widget_table_row.
Referenced by gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_pois(), gui_internal_cmd_position_do(), gui_internal_cmd_show_satellite_status(), gui_internal_menu_vehicle_settings(), gui_internal_populate_route_table(), gui_internal_search_idle(), and gui_internal_select_waypoint().
GList* gui_internal_widget_table_set_top_row (struct gui_priv * this, struct widget * table, struct widget * row)
Sets internal top row pointer of the table to point to a given row widget.
Returns
GList pointer to the top row in the children list of the table.
References widget::children, widget::data, _GList::data, g_list_next, gui_internal_widget_table_first_row(), NULL, table_data::top_row, widget::type, and widget_table.
Referenced by gui_internal_populate_route_table().
GList* gui_internal_widget_table_top_row (struct gui_priv * this, struct widget * table)
Gets GList pointer to the table row drawn on the top of the screen.
Returns
GList pointer to the top row in the children list, or NULL.
References widget::data, gui_internal_widget_table_first_row(), NULL, table_data::top_row, widget::type, and widget_table.
Referenced by gui_internal_keypress_do(), and gui_internal_populate_route_table().