navit: gui/gtk/gui_gtk_window.c File Reference
gui_gtk_window.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <locale.h>
#include <gdk/gdkkeysyms.h>
#include <X11/XF86keysym.h>
#include <gtk/gtk.h>
#include "config.h"
#include "item.h"
#include "xmlconfig.h"
#include "navit.h"
#include "debug.h"
#include "gui.h"
#include "coord.h"
#include "point.h"
#include "plugin.h"
#include "graphics.h"
#include "gui_gtk.h"
#include "transform.h"
#include "callback.h"
#include "layout.h"
#include "vehicle.h"
#include "map.h"
#include "event.h"
#include "bookmarks.h"
#include "route.h"
#include "navit_nls.h"
Data Structures
struct action_cb_data
struct gui_menu_info
Macros
#define GDK_Book XF86XK_Book
#define GDK_Calendar XF86XK_Calendar
#define KEY_ZOOM_IN GDK_Book
#define KEY_ZOOM_OUT GDK_Calendar
#define KEY_UP GDK_Up
#define KEY_DOWN GDK_Down
#define KEY_LEFT GDK_Left
#define KEY_RIGHT GDK_Right
Functions
static gboolean keypress (GtkWidget *widget, GdkEventKey *event, struct gui_priv *this)
static int gui_gtk_set_graphics (struct gui_priv *this, struct graphics *gra)
static void gui_gtk_route_callback (struct gui_priv *gui)
static void gui_gtk_add_bookmark_do (struct gui_priv *gui)
static int gui_gtk_add_bookmark (struct gui_priv *gui, struct pcoord *c, char *description)
static gboolean gui_gtk_delete (GtkWidget *widget, GdkEvent *event, struct navit *nav)
static void gui_gtk_toggle_init (struct gui_priv *this)
static void gui_gtk_action_activate (GtkAction *action, struct action_cb_data *data)
static void gui_gtk_del_menu (struct gui_priv *this, struct gui_menu_info *meninfo)
static struct gui_menu_info gui_gtk_add_menu (struct gui_priv *this, char *name, char *label, char *path, int submenu, struct action_cb_data *data)
static void gui_gtk_action_toggled (GtkToggleAction *action, struct action_cb_data *data)
static void gui_gtk_add_toggle_menu (struct gui_priv *this, char *name, char *label, char *path, struct action_cb_data *data, gboolean active)
static void gui_gtk_action_changed (GtkRadioAction *action, GtkRadioAction *current, struct action_cb_data *data)
static struct gui_menu_info gui_gtk_add_radio_menu (struct gui_priv *this, char *name, char *label, char *path, struct action_cb_data *data, GSList **g)
static void gui_gtk_layouts_init (struct gui_priv *this)
static void gui_gtk_projections_init (struct gui_priv *this)
static void gui_gtk_vehicles_update (struct gui_priv *this)
static void gui_gtk_vehicles_init (struct gui_priv *this)
static void gui_gtk_maps_init (struct gui_priv *this)
static void gui_gtk_destinations_update (struct gui_priv *this)
static void gui_gtk_destinations_init (struct gui_priv *this)
static void gui_gtk_bookmarks_update (struct gui_priv *this)
static void gui_gtk_bookmarks_init (struct gui_priv *this)
static void gui_gtk_init (struct gui_priv *this, struct navit *nav)
static struct gui_priv * gui_gtk_new (struct navit *nav, struct gui_methods *meth, struct attr **attrs, struct gui *gui)
void plugin_init (void)
Variables
struct gui_methods gui_gtk_methods
static int gtk_argc
static char ** gtk_argv ={NULL}
Macro Definition Documentation
#define GDK_Book XF86XK_Book
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#define GDK_Calendar XF86XK_Calendar
#define KEY_DOWN GDK_Down
Referenced by keypress().
#define KEY_LEFT GDK_Left
Referenced by keypress().
#define KEY_RIGHT GDK_Right
Referenced by keypress().
#define KEY_UP GDK_Up
Referenced by keypress().
#define KEY_ZOOM_IN GDK_Book
Referenced by keypress().
#define KEY_ZOOM_OUT GDK_Calendar
Referenced by keypress().
Function Documentation
static void gui_gtk_action_activate (GtkAction * action, struct action_cb_data * data) static
References action_cb_data::attr, g_free(), action_cb_data::gui, label, gui_priv::nav, navit_set_destination(), NULL, attr::pcoord, attr::type, and attr::u.
Referenced by gui_gtk_add_menu().
static void gui_gtk_action_changed (GtkRadioAction * action, GtkRadioAction * current, struct action_cb_data * data) static
References action_cb_data::attr, action_cb_data::gui, gui_priv::nav, and navit_set_attr().
Referenced by gui_gtk_add_radio_menu().
static void gui_gtk_action_toggled (GtkToggleAction * action, struct action_cb_data * data) static
References action_cb_data::attr, action_cb_data::gui, attr::map, map_set_attr(), gui_priv::nav, navit_draw(), attr::num, attr::type, and attr::u.
Referenced by gui_gtk_add_toggle_menu().
static int gui_gtk_add_bookmark (struct gui_priv * gui, struct pcoord * c, char * description) static
References _, c, gui_priv::dialog_coord, gui_priv::dialog_entry, gui_priv::dialog_win, FALSE, gui_gtk_add_bookmark_do(), label, TRUE, and gui_priv::win.
static void gui_gtk_add_bookmark_do (struct gui_priv * gui) static
References attr::bookmarks, bookmarks_add_bookmark(), gui_priv::dialog_coord, gui_priv::dialog_entry, gui_priv::dialog_win, gui_priv::nav, navit_get_attr(), NULL, and attr::u.
Referenced by gui_gtk_add_bookmark().
static struct gui_menu_info gui_gtk_add_menu (struct gui_priv * this, char * name, char * label, char * path, int submenu, struct action_cb_data * data) static
References gui_menu_info::action, data, FALSE, gui_gtk_action_activate(), label, gui_menu_info::merge_id, name, and NULL.
Referenced by gui_gtk_bookmarks_update(), and gui_gtk_destinations_update().
static struct gui_menu_info gui_gtk_add_radio_menu (struct gui_priv * this, char * name, char * label, char * path, struct action_cb_data * data, GSList ** g) static
References gui_menu_info::action, FALSE, gui_gtk_action_changed(), label, gui_menu_info::merge_id, name, and NULL.
Referenced by gui_gtk_layouts_init(), gui_gtk_projections_init(), and gui_gtk_vehicles_update().
static void gui_gtk_add_toggle_menu (struct gui_priv * this, char * name, char * label, char * path, struct action_cb_data * data, gboolean active) static
References FALSE, gui_gtk_action_toggled(), and NULL.
Referenced by gui_gtk_maps_init().
static void gui_gtk_bookmarks_init (struct gui_priv * this) static
References attr::bookmarks, bookmarks_add_callback(), callback_cast, callback_new_attr_1, gui_gtk_bookmarks_update(), navit_get_attr(), NULL, and attr::u.
Referenced by gui_gtk_init().
static void gui_gtk_bookmarks_update (struct gui_priv * this) static
References action_cb_data::attr, _GList::data, data, g_free(), g_hash_table_destroy(), g_hash_table_insert(), g_hash_table_lookup(), g_hash_table_new_full(), g_list_first(), g_list_free(), g_list_next, g_list_prepend(), g_malloc(), g_new, g_str_equal(), g_str_hash(), g_strdup(), g_strdup_printf(), action_cb_data::gui, gui_gtk_add_menu(), gui_gtk_del_menu(), item, item_attr_get(), item_coord_get(), label, attr::map, map_rect_get_item(), map_rect_new(), name, navit_get_attr(), NULL, attr::pcoord, pcoord::pro, projection_mg, attr::str, item::type, attr::type, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_gtk_bookmarks_init().
static void gui_gtk_del_menu (struct gui_priv * this, struct gui_menu_info * meninfo) static
References gui_menu_info::action, and gui_menu_info::merge_id.
Referenced by gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), and gui_gtk_vehicles_update().
static gboolean gui_gtk_delete (GtkWidget * widget, GdkEvent * event, struct navit * nav) static
References exit, navit_destroy(), and TRUE.
Referenced by gui_gtk_new().
static void gui_gtk_destinations_init (struct gui_priv * this) static
References callback_cast, callback_new_attr_1, gui_gtk_destinations_update(), and navit_add_callback().
Referenced by gui_gtk_init().
static void gui_gtk_destinations_update (struct gui_priv * this) static
References action_cb_data::attr, _GList::data, data, g_free(), g_list_first(), g_list_free(), g_list_next, g_list_prepend(), g_new, g_strdup_printf(), action_cb_data::gui, gui_gtk_add_menu(), gui_gtk_del_menu(), item, item_attr_get(), item_coord_get(), label, attr::map, map_rect_destroy(), map_rect_get_item(), map_rect_new(), name, navit_get_attr(), NULL, attr::pcoord, pcoord::pro, projection_mg, attr::str, item::type, attr::type, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_gtk_destinations_init().
static void gui_gtk_init (struct gui_priv * this, struct navit * nav) static
References attr::callback, callback_cast, callback_new_attr_1, gui_gtk_bookmarks_init(), gui_gtk_destinations_init(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_projections_init(), gui_gtk_route_callback(), gui_gtk_toggle_init(), gui_gtk_vehicles_init(), navit_get_attr(), NULL, attr::route, route_add_attr(), attr::type, and attr::u.
Referenced by gui_gtk_new().
static void gui_gtk_layouts_init (struct gui_priv * this) static
References action_cb_data::attr, data, g_free(), g_new, g_strdup_printf(), action_cb_data::gui, gui_gtk_add_radio_menu(), eval::iter, attr::layout, layout::name, name, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), attr::type, and attr::u.
Referenced by gui_gtk_init().
static void gui_gtk_maps_init (struct gui_priv * this) static
References action_cb_data::attr, g_free(), g_new, g_strdup_printf(), action_cb_data::gui, gui_gtk_add_toggle_menu(), eval::iter, label, attr::map, map_get_attr(), name, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, attr::num, attr::str, attr::type, and attr::u.
Referenced by gui_gtk_init().
static struct gui_priv* gui_gtk_new (struct navit * nav, struct gui_methods * meth, struct attr ** attrs, struct gui * gui) static
References attr_search(), callback_cast, callback_new_attr_1, event_request_system(), FALSE, fullscreen(), g_new0, getenv, gui_gtk_delete(), gui_gtk_init(), gui_gtk_methods, gui_gtk_statusbar_new(), gui_gtk_ui_init(), gui_priv::h, navit_add_callback(), NULL, attr::num, attr::u, and gui_priv::w.
Referenced by plugin_init().
static void gui_gtk_projections_init (struct gui_priv * this) static
References action_cb_data::attr, data, g_new, action_cb_data::gui, gui_gtk_add_radio_menu(), attr::projection, projection_garmin, projection_mg, attr::type, and attr::u.
Referenced by gui_gtk_init().
static void gui_gtk_route_callback (struct gui_priv * gui) static
References gui_priv::nav, navit_get_attr(), NULL, attr::num, attr::route, route_get_attr(), attr::u, and gui_priv::ui_manager.
Referenced by gui_gtk_init().
static int gui_gtk_set_graphics (struct gui_priv * this, struct graphics * gra) static
References graphics_get_data(), keypress(), and TRUE.
static void gui_gtk_toggle_init (struct gui_priv * this) static
References dbg, lvl_error, lvl_warning, navit_get_attr(), NULL, attr::num, and attr::u.
Referenced by gui_gtk_init().
static void gui_gtk_vehicles_init (struct gui_priv * this) static
References callback_cast, callback_new_attr_1, gui_gtk_vehicles_update(), and navit_add_callback().
Referenced by gui_gtk_init().
static void gui_gtk_vehicles_update (struct gui_priv * this) static
References action_cb_data::attr, _GList::data, data, dbg, g_free(), g_list_first(), g_list_free(), g_list_next, g_list_prepend(), g_new, g_strdup_printf(), action_cb_data::gui, gui_gtk_add_radio_menu(), gui_gtk_del_menu(), eval::iter, lvl_debug, name, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, attr::str, attr::type, attr::u, attr::vehicle, and vehicle_get_attr().
Referenced by gui_gtk_vehicles_init().
static gboolean keypress (GtkWidget * widget, GdkEventKey * event, struct gui_priv * this) static
References dbg, FALSE, fullscreen(), KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_UP, KEY_ZOOM_IN, KEY_ZOOM_OUT, lvl_debug, M_PI, navit_draw(), navit_get_trans(), navit_set_center(), navit_set_center_screen(), navit_zoom_in(), navit_zoom_out(), NULL, p, pcoord::pro, projection_mg, transform_center(), transform_get_distance(), transform_get_hog(), transform_get_pitch(), transform_get_size(), transform_get_yaw(), transform_set_distance(), transform_set_hog(), transform_set_pitch(), transform_set_yaw(), TRUE, point::x, coord::x, pcoord::x, point::y, coord::y, and pcoord::y.
Referenced by gui_gtk_set_graphics().
void plugin_init (void)
References gtk_argc, gtk_argv, gui_gtk_new(), LC_NUMERIC, and setlocale().
Variable Documentation
int gtk_argc static
Referenced by plugin_init().
char** gtk_argv ={NULL} static
Referenced by plugin_init().
struct gui_methods gui_gtk_methods
Initial value:
= {
        NULL,
        gui_gtk_popup_new,
        gui_gtk_set_graphics,
        NULL,
        gui_gtk_datawindow_new,
        gui_gtk_add_bookmark,
}
Referenced by gui_gtk_new().