navit: gui/internal/gui_internal_bookmark.h File Reference
gui_internal_bookmark.h File Reference
Functions
void gui_internal_cmd_add_bookmark2 (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_add_bookmark_folder2 (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_rename_bookmark (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_cut_bookmark (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_copy_bookmark (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_paste_bookmark (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_delete_bookmark_folder (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_load_bookmarks_as_waypoints (struct gui_priv *this, struct widget *wm, void *data)
void gui_internal_cmd_replace_bookmarks_from_waypoints (struct gui_priv *this, struct widget *wm, void *data)
Function Documentation
gui_internal_cmd_add_bookmark2()
void gui_internal_cmd_add_bookmark2 (struct gui_priv * this, struct widget * wm, void * data)
References _, widget::background, widget::c, widget::data, data, widget::flags, flags_expand, flags_fill, widget::func, gravity_left_center, gravity_left_top, gui_internal_box_new(), gui_internal_call_linked_on_finish(), gui_internal_cmd_add_bookmark_clicked(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), name, orientation_horizontal, orientation_vertical, widget::state, STATE_CLEAR, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_FLAG_2, and widget::w.
Referenced by gui_internal_cmd_position_do().
gui_internal_cmd_add_bookmark_folder2()
void gui_internal_cmd_add_bookmark_folder2 (struct gui_priv * this, struct widget * wm, void * data)
References _, widget::background, widget::c, widget::data, data, widget::flags, flags_expand, flags_fill, widget::func, gravity_left_center, gravity_left_top, gui_internal_box_new(), gui_internal_call_linked_on_finish(), gui_internal_cmd_add_bookmark_folder_clicked(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), name, orientation_horizontal, orientation_vertical, widget::state, STATE_CLEAR, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_FLAG_2, and widget::w.
Referenced by gui_internal_cmd_bookmarks().
gui_internal_cmd_copy_bookmark()
void gui_internal_cmd_copy_bookmark (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_copy_bookmark(), gui_internal_prune_menu(), navit_get_attr(), widget::text, and attr::u.
Referenced by gui_internal_cmd_position_do().
gui_internal_cmd_cut_bookmark()
void gui_internal_cmd_cut_bookmark (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_cut_bookmark(), gui_internal_prune_menu(), navit_get_attr(), widget::text, and attr::u.
Referenced by gui_internal_cmd_position_do().
gui_internal_cmd_delete_bookmark_folder()
void gui_internal_cmd_delete_bookmark_folder (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_delete_bookmark(), bookmarks_move_up(), gui_internal_prune_menu(), navit_get_attr(), widget::prefix, and attr::u.
Referenced by gui_internal_cmd_bookmarks().
gui_internal_cmd_load_bookmarks_as_waypoints()
void gui_internal_cmd_load_bookmarks_as_waypoints (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_get_bookmark_count(), bookmarks_get_item(), bookmarks_get_projection(), bookmarks_item_rewind(), gui_internal_prune_menu(), item, item_attr_get(), item_coord_get(), navit_add_destination_description(), navit_get_attr(), navit_set_attr(), navit_set_destination(), navit_set_destinations(), navit_zoom_to_route(), attr::num, widget::prefix, pcoord::pro, attr::str, item::type, attr::type, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd_bookmarks().
gui_internal_cmd_paste_bookmark()
void gui_internal_cmd_paste_bookmark (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_paste_bookmark(), gui_internal_prune_menu(), navit_get_attr(), and attr::u.
Referenced by gui_internal_cmd_bookmarks(), and gui_internal_cmd_position_do().
gui_internal_cmd_rename_bookmark()
void gui_internal_cmd_rename_bookmark (struct gui_priv * this, struct widget * wm, void * data)
References _, widget::background, widget::c, widget::data, widget::flags, flags_expand, flags_fill, widget::func, gravity_left_center, gravity_left_top, gui_internal_box_new(), gui_internal_call_linked_on_finish(), gui_internal_cmd_rename_bookmark_clicked(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), widget::name, name, orientation_horizontal, orientation_vertical, widget::state, STATE_CLEAR, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, widget::text, VKBD_FLAG_2, and widget::w.
Referenced by gui_internal_cmd_position_do().
gui_internal_cmd_replace_bookmarks_from_waypoints()
void gui_internal_cmd_replace_bookmarks_from_waypoints (struct gui_priv * this, struct widget * wm, void * data)
References attr::bookmarks, bookmarks_add_bookmark(), bookmarks_delete_bookmark(), bookmarks_get_bookmark_count(), bookmarks_get_item(), bookmarks_item_rewind(), bookmarks_move_down(), gui_internal_prune_menu(), item, item_attr_get(), navit_get_attr(), navit_get_destination_count(), navit_get_destination_description(), navit_get_destinations(), widget::prefix, attr::str, item::type, and attr::u.
Referenced by gui_internal_cmd_bookmarks().