navit: gui/internal/gui_internal_command.c File Reference
gui_internal_command.c File Reference
#include <glib.h>
#include <stdlib.h>
#include <math.h>
#include "config.h"
#include "color.h"
#include "coord.h"
#include "point.h"
#include "callback.h"
#include "graphics.h"
#include "debug.h"
#include "navit.h"
#include "navit_nls.h"
#include "command.h"
#include "attr.h"
#include "xmlconfig.h"
#include "event.h"
#include "config_.h"
#include "map.h"
#include "mapset.h"
#include "transform.h"
#include "search.h"
#include "route.h"
#include "vehicle.h"
#include "vehicleprofile.h"
#include "layout.h"
#include "util.h"
#include "gui_internal.h"
#include "gui_internal_widget.h"
#include "gui_internal_priv.h"
#include "gui_internal_html.h"
#include "gui_internal_menu.h"
#include "gui_internal_keyboard.h"
#include "gui_internal_search.h"
#include "gui_internal_poi.h"
#include "gui_internal_command.h"
Enumerations
enum escape_mode {
escape_mode_none =0, escape_mode_string =1, escape_mode_quote =2, escape_mode_html =4,
escape_mode_html_quote =8, escape_mode_html_apos =16
}
Functions
static char * coordinates_geo (const struct coord_geo *gc, char sep)
Converts a WGS84 coordinate pair to its string representation.
char * gui_internal_coordinates (struct pcoord *pc, char sep)
Converts a coordinate pair to its WGS84 string representation.
static char * gui_internal_escape (enum escape_mode mode, char *in)
static void gui_internal_cmd_escape (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_about (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_waypoints (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd_enter_coord (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_town (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_setting_vehicle (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_setting_rules (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_setting_maps (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_setting_layout (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_route_height_profile (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_route_description (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_pois (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_locale (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_network_info (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
display basic networking information
static void gui_internal_cmd_formerdests (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_bookmarks (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_abort_navigation (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_back (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_back_to_map (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_get_data (struct gui_priv *priv, char *command, struct attr **in, struct attr ***out)
static void gui_internal_cmd_log (struct gui_priv *this)
static void gui_internal_cmd_menu2 (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_position (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd_redraw_map (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_refresh (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2_set (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
void gui_internal_cmd2_quit (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static char * gui_internal_append_attr (char *str, enum escape_mode mode, char *pre, struct attr *attr, char *post)
static void gui_internal_cmd_write (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_onclick (struct attr ***in, char **onclick, char *set)
static void gui_internal_cmd_img (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd_debug (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
static void gui_internal_cmd2 (struct gui_priv *this, char *function, struct attr **in, struct attr ***out, int *valid)
void gui_internal_command_init (struct gui_priv *this, struct attr **attrs)
Variables
char * version
static struct command_table commands []
Enumeration Type Documentation
enum escape_mode
Enumerator
escape_mode_none
escape_mode_string
escape_mode_quote
escape_mode_html
escape_mode_html_quote
escape_mode_html_apos
Function Documentation
static char* coordinates_geo (const struct coord_geo * gc, char sep) static
Converts a WGS84 coordinate pair to its string representation.
This function takes a coordinate pair with latitude and longitude in degrees and converts them to a string of the form
45°28'0" N 9°11'26" E
.
Parameters
gc A WGS84 coordinate pair
sep The separator character to insert between latitude and longitude
Returns
The coordinates as a formatted string
References g_strdup_printf(), coord_geo::lat, and coord_geo::lng.
Referenced by gui_internal_append_attr(), and gui_internal_coordinates().
static char* gui_internal_append_attr (char * str, enum escape_mode mode, char * pre, struct attr * attr, char * post) static
References ATTR_IS_COORD_GEO, ATTR_IS_INT, ATTR_IS_STRING, attr_to_name(), attr::coord_geo, coordinates_geo(), g_free(), g_strconcat_printf(), g_strdup_printf(), gui_internal_escape(), NULL, attr::num, attr::str, attr::type, and attr::u.
Referenced by gui_internal_cmd_img(), gui_internal_cmd_write(), and gui_internal_onclick().
static void gui_internal_cmd2 (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References ATTR_IS_INT, draw_mode_end, graphics_draw_mode(), gui_internal_apply_config(), gui_internal_cmd2_about(), gui_internal_cmd2_bookmarks(), gui_internal_cmd2_locale(), gui_internal_cmd2_network_info(), gui_internal_cmd2_pois(), gui_internal_cmd2_position(), gui_internal_cmd2_route_description(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_rules(), gui_internal_cmd2_setting_vehicle(), gui_internal_cmd2_town(), gui_internal_cmd2_waypoints(), gui_internal_cmd_enter_coord(), gui_internal_cmd_formerdests(), gui_internal_enter(), gui_internal_enter_setup(), attr::num, type, and attr::u.
static void gui_internal_cmd2_abort_navigation (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References navit_set_destination(), and NULL.
static void gui_internal_cmd2_about (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, draw_mode_begin, draw_mode_end, widget::flags, flags_expand, flags_fill, g_free(), g_strdup_printf(), graphics_draw_mode(), gravity_bottom_center, gravity_top_center, gui_internal_box_new(), gui_internal_image_new(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), image_new_xs(), orientation_horizontal, orientation_vertical, widget::spx, widget::text, version, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_back (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References draw_mode_begin, draw_mode_end, graphics_draw_mode(), gui_internal_back(), gui_internal_check_exit(), and NULL.
static void gui_internal_cmd2_back_to_map (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References gui_internal_check_exit(), gui_internal_prune_menu(), and NULL.
static void gui_internal_cmd2_bookmarks (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References ATTR_IS_STRING, gui_internal_cmd_bookmarks(), NULL, attr::str, type, and attr::u.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_locale (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, draw_mode_begin, draw_mode_end, widget::flags, flags_expand, flags_fill, g_free(), g_strdup_printf(), getenv, graphics_draw_mode(), gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), NULL, orientation_horizontal, orientation_vertical, widget::spx, widget::text, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_network_info (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
display basic networking information
Returns
nothing
This function displays basic networking information, currently only the interface name and the associated IP address(es). Currently only works on non Windows systems.
References _, dbg, draw_mode_begin, draw_mode_end, widget::flags, flags_expand, flags_fill, g_ascii_strncasecmp(), g_free(), g_strdup_printf(), graphics_draw_mode(), gravity_bottom_center, gravity_top_center, gui_internal_box_new(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), lvl_error, orientation_horizontal, orientation_vertical, widget::spx, widget::text, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_pois (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References poi_param::AddressFilterType, ATTR_IS_COORD_GEO, ATTR_IS_INT, ATTR_IS_STRING, widget::c, attr::coord_geo, dbg, g_free(), g_new0, gui_internal_cmd_pois(), gui_internal_poi_param_free(), gui_internal_poi_param_set_filter(), lvl_debug, navit_get_attr(), NULL, attr::num, pcoord::pro, attr::projection, attr::str, transform_from_geo(), type, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_position (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, ATTR_IS_COORD_GEO, ATTR_IS_INT, ATTR_IS_STRING, attr::coord_geo, dbg, gui_internal_cmd_position_do(), lvl_debug, name, NULL, attr::num, attr::str, type, and attr::u.
Referenced by gui_internal_cmd2().
void gui_internal_cmd2_quit (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid)
References config_remove_attr(), event_main_loop_quit(), gui_internal_prune_menu(), attr::navit, NULL, attr::type, and attr::u.
Referenced by gui_internal_window_closed().
static void gui_internal_cmd2_refresh (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References g_free(), g_strdup(), and gui_internal_html_load_href().
static void gui_internal_cmd2_route_description (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
Register the callback on vehicle updates.
References _, callback_cast, callback_new_attr_1, flags_expand, flags_fill, gravity_left_top, gui_internal_box_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_populate_route_table(), gui_internal_route_screen_free(), gui_internal_route_update(), gui_internal_widget_append(), gui_internal_widget_table_new(), navit_add_callback(), orientation_vertical, route_data::route_showing, route_data::route_table, widget::spx, widget::w, and widget::wfree.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_route_height_profile (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, heightline::bbox, heightline::c, diagram_point::c, c, map_selection::c_rect, coord_rect_extend(), coord_rect_overlap(), heightline::count, dbg, FALSE, widget::flags, flags_expand, flags_fill, widget::foreground, g_free(), g_new, g_strdup_printf(), graphics_draw_circle(), graphics_draw_lines(), gravity_bottom_center, gravity_left_top, gui_internal_box_new(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), widget::h, heightline::height, i, item_coord_get(), item_get_heightline(), line_intersection(), coord_rect::lu, lvl_debug, lvl_info, map_get_attr(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), mapset_close(), mapset_next(), mapset_open(), item_range::max, navit_get_mapset(), navit_get_route(), map_selection::next, heightline::next, diagram_point::next, NULL, map_selection::order, orientation_horizontal, orientation_vertical, widget::p, projection_mg, map_selection::range, coord_rect::rl, route_get_map(), attr::str, widget::text, attr::text, transform_distance(), TRUE, item::type, map_selection::u, attr::u, widget::w, point::x, coord::x, point::y, and coord::y.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_set (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References ATTR_IS_STRING, command(), command_evaluate(), dbg, g_free(), gui_internal_cmd_match_expand(), gui_internal_set(), lvl_debug, lvl_error, NULL, attr::str, type, and attr::u.
static void gui_internal_cmd2_setting_layout (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, flags_expand, flags_fill, gravity_left, gravity_left_center, gravity_top_center, gui_internal_button_navit_attr_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), eval::iter, attr::layout, layout::name, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, orientation_horizontal, orientation_vertical, row, attr::u, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_setting_maps (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, flags_expand, flags_fill, g_free(), g_strdup(), g_strdup_printf(), gravity_left, gravity_left_center, gravity_left_top, gui_internal_button_map_attr_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_map_download(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), image_new_xs(), eval::iter, label, attr::map, map_get_attr(), navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, attr::num, orientation_horizontal, orientation_vertical, row, attr::str, attr::type, attr::u, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_setting_rules (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, flags_expand, flags_fill, gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_button_navit_attr_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_widget_append(), attr::num, orientation_horizontal, orientation_vertical, widget::spy, attr::type, attr::u, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_setting_vehicle (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, flags_expand, flags_fill, g_strdup(), gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_vehicle_settings(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_menu_vehicle_settings(), gui_internal_widget_append(), image_new_xs(), eval::iter, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), NULL, orientation_horizontal, orientation_vertical, widget::spy, attr::str, widget::text, attr::u, attr::vehicle, vehicle_get_attr(), and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_town (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, gui_internal_search(), and search_list_select().
Referenced by gui_internal_cmd2().
static void gui_internal_cmd2_waypoints (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, gui_internal_cmd_position(), gui_internal_select_waypoint(), and NULL.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd_debug (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References attr_to_name(), attr_to_text(), dbg, g_free(), lvl_debug, NULL, and attr::str.
static void gui_internal_cmd_enter_coord (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, widget::background, background, widget::data, widget::flags, flags_expand, flags_fill, widget::func, gravity_center, gravity_left_center, gravity_top_center, gui_internal_box_new(), gui_internal_call_linked_on_finish(), gui_internal_cmd_enter_coord_clicked(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_text_new(), gui_internal_widget_append(), image_new_xs(), NULL, orientation_horizontal, orientation_vertical, row, widget::state, STATE_CLEAR, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_DEGREE, and widget::w.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd_escape (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References attr_dup(), attr_generic_add_attr(), ATTR_IS_INT, ATTR_IS_STRING, dbg, escape_mode_string, g_free(), g_strdup_printf(), gui_internal_escape(), lvl_debug, lvl_error, attr::str, type, attr::type, and attr::u.
static void gui_internal_cmd_formerdests (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References _, widget::background, background, widget::c, widget::data, flags_expand, flags_fill, g_strdup(), gravity_left, gravity_left_center, gravity_left_top, gravity_top_center, gui_internal_box_new(), gui_internal_button_new_with_callback(), gui_internal_cmd_position(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_prune_menu_count(), gui_internal_text_new(), gui_internal_widget_append(), gui_internal_widget_prepend(), gui_internal_widget_table_new(), gui_internal_widget_table_row_new(), image_new_xs(), item, item_attr_get(), item_coord_get(), attr::map, map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), widget::name, navit_get_attr(), NULL, orientation_horizontal, orientation_vertical, widget::prefix, pcoord::pro, row, widget::spy, attr::str, widget::text, item::type, attr::u, widget::w, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd2().
static void gui_internal_cmd_img (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References ATTR_IS_STRING, dbg, escape_mode_html, escape_mode_html_apos, escape_mode_string, g_free(), g_strconcat_printf(), g_strdup(), g_strdup_printf(), gui_internal_append_attr(), gui_internal_escape(), gui_internal_html_parse_text(), gui_internal_onclick(), lvl_debug, lvl_error, NULL, and attr::str.
static void gui_internal_cmd_log (struct gui_priv * this) static
References _, widget::background, background, widget::data, widget::flags, flags_expand, flags_fill, widget::func, getenv, gravity_left_center, gravity_left_top, gui_internal_box_new(), gui_internal_call_linked_on_finish(), gui_internal_cmd_log_clicked(), gui_internal_enter(), gui_internal_enter_setup(), gui_internal_image_new(), gui_internal_keyboard(), gui_internal_keyboard_init_mode(), gui_internal_keyboard_show_native(), gui_internal_label_new(), gui_internal_leave(), gui_internal_menu(), gui_internal_menu_render(), gui_internal_set_click_coord(), gui_internal_widget_append(), image_new_xs(), NULL, orientation_horizontal, orientation_vertical, widget::state, STATE_CLEAR, STATE_EDIT, STATE_EDITABLE, STATE_SENSITIVE, VKBD_FLAG_2, and widget::w.
static void gui_internal_cmd_menu2 (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References ATTR_IS_INT, ATTR_IS_STRING, gui_internal_cmd_menu(), gui_internal_html_load_href(), i, NULL, attr::num, attr::str, type, and attr::u.
static void gui_internal_cmd_redraw_map (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References widget::redraw.
static void gui_internal_cmd_write (struct gui_priv * this, char * function, struct attr ** in, struct attr *** out, int * valid) static
References dbg, escape_mode_none, g_free(), g_strdup_printf(), gui_internal_append_attr(), gui_internal_html_parse_text(), lvl_debug, NULL, and attr::str.
void gui_internal_command_init (struct gui_priv * this, struct attr ** attrs)
References attr_search(), attr::callback_list, command_add_table(), NULL, and attr::u.
Referenced by gui_internal_new().
char* gui_internal_coordinates (struct pcoord * pc, char sep)
Converts a coordinate pair to its WGS84 string representation.
This function takes a coordinate pair, transforms it to WGS84 and converts it to a string of the form
45°28'0" N 9°11'26" E
.
Parameters
gc A coordinate pair
sep The separator character to insert between latitude and longitude
Returns
The coordinates as a formatted string
References coordinates_geo(), pcoord::pro, transform_to_geo(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_internal_cmd_position_do().
static char* gui_internal_escape (enum escape_mode mode, char * in) static
References escape_mode_html_apos, escape_mode_html_quote, escape_mode_quote, escape_mode_string, and g_malloc().
Referenced by gui_internal_append_attr(), gui_internal_cmd_escape(), gui_internal_cmd_img(), and gui_internal_onclick().
static void gui_internal_get_data (struct gui_priv * priv, char * command, struct attr ** in, struct attr *** out) static
References attr_generic_add_attr(), and gui_priv::data.
static void gui_internal_onclick (struct attr *** in, char ** onclick, char * set) static
References ATTR_IS_STRING, c, dbg, escape_mode_string, g_free(), g_strconcat(), g_strconcat_printf(), g_strdup(), gui_internal_append_attr(), gui_internal_escape(), i, lvl_error, NULL, and attr::str.
Referenced by gui_internal_cmd_img().
Variable Documentation
struct command_table commands[] static
char* version
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by gui_internal_cmd2_about().