navit: gui/gtk/gui_gtk_action.c File Reference
gui_gtk_action.c File Reference
#include <string.h>
#include <gtk/gtk.h>
#include "navit.h"
#include "gui_gtk.h"
#include "menu.h"
#include "coord.h"
#include "item.h"
#include "attr.h"
#include "callback.h"
#include "debug.h"
#include "destination.h"
#include "navit_nls.h"
#include "gui_gtk_poi.h"
#include <stdlib.h>
#include "point.h"
#include "transform.h"
Data Structures
struct menu_priv
Functions
static void zoom_in_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void zoom_out_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void refresh_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
void gui_gtk_datawindow_set_button (struct datawindow_priv *this_, GtkWidget *btn)
void gui_gtk_datawindow_destroy (struct datawindow_priv *win)
static void roadbook_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void autozoom_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void cursor_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void tracking_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void follow_vehicle_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
Toggles the ability to follow the vehicle at the cursor. Suitable for use in the GTK menu as below.
static void orient_north_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void window_fullscreen_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void info_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void route_clear_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void poi_search_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void destination_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void quit_action (GtkWidget *w, struct gui_priv *gui, void *dummy)
static void register_my_stock_icons (void)
static void activate (void *dummy, struct menu_priv *menu)
static struct menu_priv * add_menu (struct menu_priv *menu, struct menu_methods *meth, char *name, enum menu_type type, struct callback *cb)
static void remove_menu (struct menu_priv *item, int recursive)
static void set_toggle (struct menu_priv *menu, int active)
static int get_toggle (struct menu_priv *menu)
static void popup_deactivate (GtkWidget *widget, struct menu_priv *menu)
static void popup_activate (struct menu_priv *menu)
void gui_gtk_ui_init (struct gui_priv *this)
static struct menu_priv * gui_gtk_ui_new (struct gui_priv *this, struct menu_methods *meth, char *path, int popup, GtkWidget **widget_ret)
struct menu_priv * gui_gtk_popup_new (struct gui_priv *this, struct menu_methods *meth)
Variables
static GtkActionEntry entries []
static guint n_entries = G_N_ELEMENTS (entries)
static GtkToggleActionEntry toggleentries []
static guint n_toggleentries = G_N_ELEMENTS (toggleentries)
static GtkActionEntry debug_entries []
static guint n_debug_entries = G_N_ELEMENTS (debug_entries)
static const char * cursor_xpm []
static const char * north_xpm []
static const char * flag_xpm []
struct {
gchar * stockid
const char ** icon_xpm
} stock_icons []
static gint n_stock_icons = G_N_ELEMENTS (stock_icons)
static char layout []
static struct menu_methods menu_methods
Function Documentation
activate()
static void activate (void * dummy, struct menu_priv * menu) static
References callback_call_0, and menu_priv::cb.
Referenced by add_menu().
add_menu()
static struct menu_priv* add_menu (struct menu_priv * menu, struct menu_methods * meth, char * name, enum menu_type type, struct callback * cb) static
References menu_priv::action, activate(), menu_priv::cb, menu_priv::child, gui_priv::dyn_counter, gui_priv::dyn_group, menu_priv::gui, menu_priv::handler_id, menu_methods, menu_type_submenu, menu_type_toggle, menu_priv::merge_id, menu_priv::path, menu_priv::sibling, menu_priv::type, and gui_priv::ui_manager.
Referenced by get_toggle().
autozoom_action()
static void autozoom_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::nav, navit_set_attr(), attr::num, attr::type, and attr::u.
cursor_action()
static void cursor_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References dbg, lvl_error, gui_priv::nav, navit_set_attr(), attr::num, attr::type, and attr::u.
destination_action()
static void destination_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References destination_address(), and gui_priv::nav.
follow_vehicle_action()
static void follow_vehicle_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
Toggles the ability to follow the vehicle at the cursor. Suitable for use in the GTK menu as below.
Parameters
GtkWidget is the generic storage type for widgets.
gui The gui. I think, I'm new here.
dummy Ignore the pointer behind the curtain.
Returns
void
References dbg, lvl_error, gui_priv::nav, navit_set_attr(), attr::num, attr::type, and attr::u.
get_toggle()
static int get_toggle (struct menu_priv * menu) static
References menu_priv::action, add_menu(), and set_toggle().
gui_gtk_datawindow_destroy()
void gui_gtk_datawindow_destroy (struct datawindow_priv * win)
References gui_priv::datawindow, datawindow_priv::gui, gui_gtk_datawindow_delete(), and datawindow_priv::window.
Referenced by refresh_action(), and roadbook_action().
gui_gtk_datawindow_set_button()
void gui_gtk_datawindow_set_button (struct datawindow_priv * this_, GtkWidget * btn)
References datawindow_priv::button.
Referenced by refresh_action(), and roadbook_action().
gui_gtk_popup_new()
struct menu_priv* gui_gtk_popup_new (struct gui_priv * this, struct menu_methods * meth)
References gui_gtk_ui_new().
gui_gtk_ui_init()
void gui_gtk_ui_init (struct gui_priv * this)
References debug_entries, entries, n_debug_entries, n_entries, n_toggleentries, navit_get_attr(), attr::num, register_my_stock_icons(), toggleentries, and attr::u.
Referenced by gui_gtk_new().
gui_gtk_ui_new()
static struct menu_priv* gui_gtk_ui_new (struct gui_priv * this, struct menu_methods * meth, char * path, int popup, GtkWidget ** widget_ret) static
References menu_priv::gui, gui_gtk_menubar_new(), menu_methods, menu_priv::path, menu_methods::popup, popup_activate(), and menu_priv::widget.
Referenced by gui_gtk_popup_new().
info_action()
static void info_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References dbg, lvl_debug, gui_priv::nav, navit_get_trans(), transform_get_size(), transform_reverse(), point::x, coord::x, point::y, and coord::y.
orient_north_action()
static void orient_north_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References dbg, lvl_error, gui_priv::nav, navit_set_attr(), attr::num, attr::type, and attr::u.
poi_search_action()
static void poi_search_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gtk_gui_poi(), and gui_priv::nav.
popup_activate()
static void popup_activate (struct menu_priv * menu) static
References menu_priv::gui, menu_priv::handler_id, menu_priv::path, popup_deactivate(), gui_priv::ui_manager, and menu_priv::widget.
Referenced by gui_gtk_ui_new().
popup_deactivate()
static void popup_deactivate (GtkWidget * widget, struct menu_priv * menu) static
References menu_priv::handler_id, and remove_menu().
Referenced by popup_activate().
quit_action()
static void quit_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References exit, gui_priv::nav, and navit_destroy().
refresh_action()
static void refresh_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_gtk_datawindow_destroy(), gui_gtk_datawindow_set_button(), gui_priv::nav, and navit_draw().
register_my_stock_icons()
static void register_my_stock_icons (void) static
References icon_xpm, n_stock_icons, stock_icons, and stockid.
Referenced by gui_gtk_ui_init().
remove_menu()
static void remove_menu (struct menu_priv * item, int recursive) static
References menu_priv::action, menu_priv::child, gui_priv::dyn_group, menu_priv::gui, menu_priv::handler_id, menu_priv::merge_id, next, menu_priv::path, menu_priv::sibling, and gui_priv::ui_manager.
Referenced by popup_deactivate().
roadbook_action()
static void roadbook_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::datawindow, gui_gtk_datawindow_destroy(), gui_gtk_datawindow_set_button(), gui_priv::nav, and navit_window_roadbook_new().
route_clear_action()
static void route_clear_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::nav, and navit_set_destination().
set_toggle()
static void set_toggle (struct menu_priv * menu, int active) static
References menu_priv::action.
Referenced by get_toggle().
tracking_action()
static void tracking_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References dbg, lvl_error, gui_priv::nav, navit_set_attr(), attr::num, attr::type, and attr::u.
window_fullscreen_action()
static void window_fullscreen_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::win.
zoom_in_action()
static void zoom_in_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::nav, and navit_zoom_in().
zoom_out_action()
static void zoom_out_action (GtkWidget * w, struct gui_priv * gui, void * dummy) static
References gui_priv::nav, and navit_zoom_out().
Variable Documentation
cursor_xpm
const char* cursor_xpm[] static
Initial value:
= {
    "22 22 2 1",
    "   c None",
    ".  c #0000FF",
    "                      ",
    "                      ",
    "                      ",
    "          ..          ",
    "        ..  ..        ",
    "      ..      ..      ",
    "     .          .     ",
    "     .          .     ",
    "    .        ... .    ",
    "    .     ... .  .    ",
    "   .   ...   .    .   ",
    "   . ..     .     .   ",
    "    .      .     .    ",
    "    .     .      .    ",
    "     .   .      .     ",
    "     .  .       .     ",
    "      ..      ..      ",
    "        ..  ..        ",
    "          ..          ",
    "                      ",
    "                      ",
    "                      "
}
debug_entries
GtkActionEntry debug_entries[] static
Initial value:
= {
    { "DataMenuAction", NULL, _n("Data") },
}
Referenced by gui_gtk_ui_init().
entries
GtkActionEntry entries[] static
Initial value:
= {
    { "DisplayMenuAction", NULL, _n("_Display") },
    { "RouteMenuAction", NULL, _n("_Route") },
    { "FormerDestinationMenuAction", NULL, _n("_Former Destinations") },
    { "BookmarkMenuAction", NULL, _n("_Bookmarks") },
    { "MapMenuAction", NULL, _n("_Map") },
    { "LayoutMenuAction", NULL, _n("_Layout") },
    { "ProjectionMenuAction", NULL, _n("_Projection") },
    { "VehicleMenuAction", NULL, _n("_Vehicle") },
    { "ZoomOutAction", GTK_STOCK_ZOOM_OUT, _n("Zoom_Out"), "<control>minus", _n("Decrease zoom level"), G_CALLBACK(zoom_out_action) },
    { "ZoomInAction", GTK_STOCK_ZOOM_IN, _n("Zoom_In"), "<control>plus", _n("Increase zoom level"), G_CALLBACK(zoom_in_action) },
    { "RefreshAction", GTK_STOCK_REFRESH, _n("_Recalculate"), "<control>R", _n("Redraw map"), G_CALLBACK(refresh_action) },
    { "InfoAction", NULL, _n("_Info"), NULL, NULL, G_CALLBACK(info_action) },
    { "DestinationAction", "flag_icon", _n("Set _destination"), "<control>D", _n("Opens address search dialog"), G_CALLBACK(destination_action) },
    { "POIAction", "flag_icon", _n("_POI search"), "<control>P", _n("Opens POI search dialog"), G_CALLBACK(poi_search_action) },
    { "RouteClearAction", NULL, _n("_Stop Navigation"), "<control>S", NULL, G_CALLBACK(route_clear_action) },
    { "Test", NULL, _n("Test"), NULL, NULL, G_CALLBACK(destination_action) },
    { "QuitAction", GTK_STOCK_QUIT, _n("_Quit"), "<control>Q",_n("Quit the application"), G_CALLBACK (quit_action) }
}
Referenced by org.navitproject.navit.NavitRestoreTask::doInBackground(), NGQProxyNavit::getAttrList(), NGQProxyBookmarks::getBookmarks(), NGQPoint::getInformation(), NGQPoint::getPOI(), gui_gtk_ui_init(), print_array(), print_object(), and NGQProxySearch::searchXml().
flag_xpm
const char* flag_xpm[] static
Initial value:
= {
    "22 22 2 1",
    "   c None",
    "+  c #000000",
    "+++++++               ",
    "+   +++++++++         ",
    "+   +++   +++++++++   ",
    "+   +++   +++   +++   ",
    "++++      +++   +++   ",
    "++++   +++      +++   ",
    "++++   +++   +++  +   ",
    "+   ++++++   +++  +   ",
    "+   +++   ++++++  +   ",
    "+   +++   +++   +++   ",
    "++++      +++   +++   ",
    "++++   +++      +++   ",
    "++++++++++   +++  +   ",
    "+      +++++++++  +   ",
    "+            ++++++   ",
    "+                     ",
    "+                     ",
    "+                     ",
    "+                     ",
    "+                     ",
    "+                     ",
    "+                     "
}
icon_xpm
const char** icon_xpm
Referenced by register_my_stock_icons().
layout
char layout[] static
Referenced by navit_add_layout(), and navit_update_current_layout().
menu_methods
static struct menu_methods menu_methods static
Initial value:
= {
    add_menu,
    set_toggle,
    get_toggle,
}
Referenced by add_menu(), and gui_gtk_ui_new().
n_debug_entries
guint n_debug_entries = G_N_ELEMENTS (debug_entries) static
Referenced by gui_gtk_ui_init().
n_entries
guint n_entries = G_N_ELEMENTS (entries) static
Referenced by gui_gtk_ui_init().
n_stock_icons
gint n_stock_icons = G_N_ELEMENTS (stock_icons) static
Referenced by register_my_stock_icons().
n_toggleentries
guint n_toggleentries = G_N_ELEMENTS (toggleentries) static
Referenced by gui_gtk_ui_init().
north_xpm
const char* north_xpm[] static
Initial value:
= {
    "22 22 2 1",
    "   c None",
    ".  c #000000",
    "                      ",
    "                      ",
    "           .          ",
    "          ...         ",
    "         . . .        ",
    "        .  .  .       ",
    "           .          ",
    "     ....  .  ....    ",
    "     ....  .  ....    ",
    "      .... .   ..     ",
    "      .. ..    ..     ",
    "      ..  ..   ..     ",
    "      ..   ..  ..     ",
    "      ..    .. ..     ",
    "      ..   . ....     ",
    "     ....  .  ....    ",
    "     ....  .  ....    ",
    "           .          ",
    "           .          ",
    "           .          ",
    "                      ",
    "                      "
}
stock_icons
struct { ... } stock_icons[]
Initial value:
= {
    {"cursor_icon", cursor_xpm },
    {"orientation_icon", north_xpm },
    {"flag_icon", flag_xpm }
}
Referenced by register_my_stock_icons().
stockid
gchar* stockid
Referenced by register_my_stock_icons().
toggleentries
GtkToggleActionEntry toggleentries[] static
Initial value:
= {
    { "CursorAction", "cursor_icon",_n("Show position _cursor"), NULL, NULL, G_CALLBACK(cursor_action),TRUE },
    { "TrackingAction", NULL,_n("_Lock on Road"), NULL, NULL, G_CALLBACK(tracking_action),TRUE },
    { "FollowVehicleAction", NULL,_n("_Follow Vehicle"), NULL, NULL, G_CALLBACK(follow_vehicle_action),TRUE },
    { "OrientationAction", "orientation_icon", _n("_Keep orientation to the North"), NULL, _n("Switches map orientation to the north or the vehicle"), G_CALLBACK(orient_north_action),FALSE },
    { "RoadbookAction", GTK_STOCK_JUSTIFY_FILL, _n("_Roadbook"), "<control>B", _n("Show/hide route description"), G_CALLBACK(roadbook_action), FALSE },
    { "AutozoomAction", GTK_STOCK_ZOOM_FIT, _n("_Autozoom"), "<control>A", _n("Enable/disable automatic zoom level changing"), G_CALLBACK(autozoom_action), FALSE },
    { "FullscreenAction", NULL, _n("_Fullscreen"), "<control>F", NULL, G_CALLBACK(window_fullscreen_action), FALSE }
}
Referenced by gui_gtk_ui_init().