navit: gui/qml/gui_qml.cpp File Reference
gui_qml.cpp File Reference
#include <glib.h>
#include <QtCore>
#include <QtGui>
#include <QtDeclarative>
#include <QtXml>
#include "config.h"
#include "plugin.h"
#include "item.h"
#include "attr.h"
#include "xmlconfig.h"
#include "color.h"
#include "gui.h"
#include "callback.h"
#include "debug.h"
#include "navit.h"
#include "point.h"
#include "graphics.h"
#include "event.h"
#include "map.h"
#include "coord.h"
#include "vehicle.h"
#include "transform.h"
#include "mapset.h"
#include "route.h"
#include "country.h"
#include "track.h"
#include "search.h"
#include "bookmarks.h"
#include "command.h"
#include "keys.h"
#include "layout.h"
#include "proxy.h"
#include "ngqpoint.h"
#include "searchProxy.h"
#include "routeProxy.h"
#include "bookmarksProxy.h"
#include "vehicleProxy.h"
#include "navitProxy.h"
#include "guiProxy.h"
#include "gui_qml.moc"
Data Structures
struct gui_priv
class NGQMainWindow
Functions
static void gui_qml_dbus_signal (struct gui_priv *this_, struct point *p)
static void gui_qml_button (void *data, int pressed, int button, struct point *p)
static void gui_qml_motion (void *data, struct point *p)
static void gui_qml_resize (void *data, int w, int h)
static void gui_qml_keypress (void *data, char *key)
static void gui_qml_window_closed (struct gui_priv *data)
static int gui_qml_set_graphics (struct gui_priv *this_, struct graphics *gra)
static int gui_qml_get_attr (struct gui_priv *this_, enum attr_type type, struct attr *attr)
static int gui_qml_set_attr (struct gui_priv *this_, struct attr *attr)
static void gui_qml_command (struct gui_priv *this_, char *function, struct attr **in, struct attr ***out, int *valid)
static struct gui_priv * gui_qml_new (struct navit *nav, struct gui_methods *meth, struct attr **attrs, struct gui *gui)
void plugin_init (void)
Variables
static int argc =1
static char * argv [] ={(char *)"navit",NULL}
struct gui_methods gui_qml_methods
static struct command_table commands []
Function Documentation
static void gui_qml_button (void * data, int pressed, int button, struct point * p) static
References dbg, gui_qml_dbus_signal(), gui_priv::guiProxy, lvl_debug, gui_priv::menu_on_map_click, gui_priv::nav, navit_handle_button(), NULL, gui_priv::signal_on_map_click, and NGQProxyGui::switchToMenu().
Referenced by gui_qml_set_graphics().
static void gui_qml_command (struct gui_priv * this_, char * function, struct attr ** in, struct attr *** out, int * valid) static
References gui_priv::guiProxy, and NGQProxyGui::processCommand().
static void gui_qml_dbus_signal (struct gui_priv * this_, struct point * p) static
References attr::callback_list, callback_list_call_attr_4, display(), graphics_displayitem_get_displayed(), graphics_displayitem_get_item(), graphics_displayitem_within_dist(), graphics_displaylist_close(), graphics_displaylist_next(), graphics_displaylist_open(), item::id_hi, item::id_lo, item_attr_get(), item_is_point, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), gui_priv::nav, navit_get_attr(), navit_get_displaylist(), NULL, attr::type, and attr::u.
Referenced by gui_qml_button().
static int gui_qml_get_attr (struct gui_priv * this_, enum attr_type type, struct attr * attr) static
References gui_priv::fullscreen, attr::num, gui_priv::pitch, gui_priv::radius, gui_priv::skin, attr::str, type, attr::type, and attr::u.
static void gui_qml_keypress (void * data, char * key) static
References gui_priv::guiProxy, gui_priv::h, gui_priv::nav, navit_get_trans(), NAVIT_KEY_DOWN, NAVIT_KEY_LEFT, NAVIT_KEY_MENU, NAVIT_KEY_RETURN, NAVIT_KEY_RIGHT, NAVIT_KEY_UP, NAVIT_KEY_ZOOM_IN, NAVIT_KEY_ZOOM_OUT, navit_set_center_screen(), navit_zoom_in(), navit_zoom_out(), NULL, NGQProxyGui::switchToMenu(), transform_get_size(), gui_priv::w, point::x, and point::y.
Referenced by gui_qml_set_graphics().
static void gui_qml_motion (void * data, struct point * p) static
References gui_priv::nav, and navit_handle_motion().
Referenced by gui_qml_set_graphics().
static struct gui_priv* gui_qml_new (struct navit * nav, struct gui_methods * meth, struct attr ** attrs, struct gui * gui) static
References attr_search(), attr::callback_list, callback_list_new(), gui_priv::cbl, command_add_table(), gui_priv::fullscreen, g_new0, g_strdup(), g_strjoin(), getenv, gui_priv::gui, attr::gui, gui_qml_methods, gui_priv::h, gui_priv::icon_src, gui_priv::lazy, gui_priv::menu_on_map_click, gui_priv::nav, navit_ignore_graphics_events(), NULL, attr::num, gui_priv::pitch, gui_priv::radius, gui_priv::self, gui_priv::signal_on_map_click, gui_priv::skin, gui_priv::source, attr::str, attr::type, attr::u, and gui_priv::w.
Referenced by plugin_init().
static void gui_qml_resize (void * data, int w, int h) static
References gui_priv::nav, and navit_handle_resize().
Referenced by gui_qml_set_graphics().
static int gui_qml_set_attr (struct gui_priv * this_, struct attr * attr) static
References attr_to_name(), dbg, gui_priv::fullscreen, lvl_error, gui_priv::mainWindow, attr::num, gui_priv::pitch, gui_priv::radius, attr::type, and attr::u.
static int gui_qml_set_graphics (struct gui_priv * this_, struct graphics * gra) static
References gui_priv::app, argc, argv, gui_priv::bookmarksProxy, gui_priv::button_cb, callback_cast, callback_new_attr_1, gui_priv::currentPoint, dbg, exit, gui_priv::fullscreen, getenv, gui_priv::gra, graphics_add_callback(), graphics_get_data(), gui_priv::graphicsWidget, gui_qml_button(), gui_qml_keypress(), gui_qml_motion(), gui_qml_resize(), gui_qml_window_closed(), gui_priv::guiProxy, gui_priv::guiWidget, gui_priv::h, gui_priv::keypress_cb, lvl_error, gui_priv::mainWindow, gui_priv::motion_cb, gui_priv::nav, navit_draw(), gui_priv::navitProxy, NGQMainWindow::NGQMainWindow(), NULL, gui_priv::resize_cb, gui_priv::routeProxy, gui_priv::searchProxy, gui_priv::skin, gui_priv::source, gui_priv::switcherWidget, gui_priv::vehicleProxy, gui_priv::w, and gui_priv::window_closed_cb.
static void gui_qml_window_closed (struct gui_priv * data) static
References gui_priv::navitProxy, and NGQProxyNavit::quit().
Referenced by gui_qml_set_graphics().
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
References gui_qml_new().
Variable Documentation
int argc =1 static
Referenced by gui_qml_set_graphics().
char* argv[] ={(char *)"navit",NULL} static
Referenced by gui_qml_set_graphics().
struct command_table commands[] static
Initial value:
= {
        {"*",command_cast(gui_qml_command)},
}
struct gui_methods gui_qml_methods
Initial value:
= {
        NULL,
        NULL,
    gui_qml_set_graphics,
        NULL,
        NULL,
        NULL,
        NULL,
        gui_qml_get_attr,
        NULL,
        gui_qml_set_attr,
}
Referenced by gui_qml_new().