navit: gui/gtk/gui_gtk.h File Reference
gui_gtk.h File Reference
#include "coord.h"
Data Structures
struct gui_priv
Functions
void gui_gtk_ui_init (struct gui_priv *this)
struct menu_priv * gui_gtk_menubar_new (struct gui_priv *gui, struct menu_methods *meth)
struct statusbar_priv * gui_gtk_statusbar_new (struct gui_priv *gui)
struct menu_priv * gui_gtk_popup_new (struct gui_priv *gui, struct menu_methods *meth)
struct datawindow_priv * gui_gtk_datawindow_new (struct gui_priv *gui, const char *name, struct callback *click, struct callback *close, struct datawindow_methods *meth)
void gui_gtk_datawindow_destroy (struct datawindow_priv *win)
void gui_gtk_datawindow_set_button (struct datawindow_priv *this_, GtkWidget *btn)
Function Documentation
void gui_gtk_datawindow_destroy (struct datawindow_priv * win)
struct datawindow_priv* gui_gtk_datawindow_new (struct gui_priv * gui, const char * name, struct callback * click, struct callback * close, struct datawindow_methods * meth)
References datawindow_priv::click, close(), datawindow_priv::close, gui_priv::datawindow, g_new0, datawindow_priv::gui, gui_gtk_datawindow_delete(), gui_gtk_datawindow_meth, keypress(), NULL, datawindow_priv::scrolled_window, datawindow_priv::treeview, gui_priv::win, and datawindow_priv::window.
void gui_gtk_datawindow_set_button (struct datawindow_priv * this_, GtkWidget * btn)
struct menu_priv* gui_gtk_menubar_new (struct gui_priv * gui, struct menu_methods * meth)
struct menu_priv* gui_gtk_popup_new (struct gui_priv * gui, struct menu_methods * meth)
References gui_gtk_ui_new(), and NULL.
struct statusbar_priv* gui_gtk_statusbar_new (struct gui_priv * gui)
References _, callback_cast, callback_new_attr_1, FALSE, g_new0, statusbar_priv::gps, statusbar_priv::gui, statusbar_priv::hbox, gui_priv::nav, navit_add_callback(), statusbar_route_update(), TRUE, gui_priv::vbox, and statusbar_priv::vehicle_cb.
void gui_gtk_ui_init (struct gui_priv * this)
References debug_entries, entries, g_error_free(), g_message(), n_debug_entries, n_entries, n_toggleentries, navit_get_attr(), NULL, attr::num, register_my_stock_icons(), toggleentries, and attr::u.
Referenced by gui_gtk_new().