navit: support/glib/gunicode.h File Reference
gunicode.h File Reference
#include <glib/gerror.h>
#include <glib/gtypes.h>
Macros
#define __G_UNICODE_H__
#define g_utf8_next_char(p) (char *)((p) + g_utf8_skip[*(const guchar *)(p)])
Typedefs
typedef guint16 gunichar2
Enumerations
enum GUnicodeType {
G_UNICODE_CONTROL, G_UNICODE_FORMAT, G_UNICODE_UNASSIGNED, G_UNICODE_PRIVATE_USE,
G_UNICODE_SURROGATE, G_UNICODE_LOWERCASE_LETTER, G_UNICODE_MODIFIER_LETTER, G_UNICODE_OTHER_LETTER,
G_UNICODE_TITLECASE_LETTER, G_UNICODE_UPPERCASE_LETTER, G_UNICODE_COMBINING_MARK, G_UNICODE_ENCLOSING_MARK,
G_UNICODE_NON_SPACING_MARK, G_UNICODE_DECIMAL_NUMBER, G_UNICODE_LETTER_NUMBER, G_UNICODE_OTHER_NUMBER,
G_UNICODE_CONNECT_PUNCTUATION, G_UNICODE_DASH_PUNCTUATION, G_UNICODE_CLOSE_PUNCTUATION, G_UNICODE_FINAL_PUNCTUATION,
G_UNICODE_INITIAL_PUNCTUATION, G_UNICODE_OTHER_PUNCTUATION, G_UNICODE_OPEN_PUNCTUATION, G_UNICODE_CURRENCY_SYMBOL,
G_UNICODE_MODIFIER_SYMBOL, G_UNICODE_MATH_SYMBOL, G_UNICODE_OTHER_SYMBOL, G_UNICODE_LINE_SEPARATOR,
G_UNICODE_PARAGRAPH_SEPARATOR, G_UNICODE_SPACE_SEPARATOR
}
enum GUnicodeBreakType {
G_UNICODE_BREAK_MANDATORY, G_UNICODE_BREAK_CARRIAGE_RETURN, G_UNICODE_BREAK_LINE_FEED, G_UNICODE_BREAK_COMBINING_MARK,
G_UNICODE_BREAK_SURROGATE, G_UNICODE_BREAK_ZERO_WIDTH_SPACE, G_UNICODE_BREAK_INSEPARABLE, G_UNICODE_BREAK_NON_BREAKING_GLUE,
G_UNICODE_BREAK_CONTINGENT, G_UNICODE_BREAK_SPACE, G_UNICODE_BREAK_AFTER, G_UNICODE_BREAK_BEFORE,
G_UNICODE_BREAK_BEFORE_AND_AFTER, G_UNICODE_BREAK_HYPHEN, G_UNICODE_BREAK_NON_STARTER, G_UNICODE_BREAK_OPEN_PUNCTUATION,
G_UNICODE_BREAK_CLOSE_PUNCTUATION, G_UNICODE_BREAK_QUOTATION, G_UNICODE_BREAK_EXCLAMATION, G_UNICODE_BREAK_IDEOGRAPHIC,
G_UNICODE_BREAK_NUMERIC, G_UNICODE_BREAK_INFIX_SEPARATOR, G_UNICODE_BREAK_SYMBOL, G_UNICODE_BREAK_ALPHABETIC,
G_UNICODE_BREAK_PREFIX, G_UNICODE_BREAK_POSTFIX, G_UNICODE_BREAK_COMPLEX_CONTEXT, G_UNICODE_BREAK_AMBIGUOUS,
G_UNICODE_BREAK_UNKNOWN, G_UNICODE_BREAK_NEXT_LINE, G_UNICODE_BREAK_WORD_JOINER, G_UNICODE_BREAK_HANGUL_L_JAMO,
G_UNICODE_BREAK_HANGUL_V_JAMO, G_UNICODE_BREAK_HANGUL_T_JAMO, G_UNICODE_BREAK_HANGUL_LV_SYLLABLE, G_UNICODE_BREAK_HANGUL_LVT_SYLLABLE
}
enum GUnicodeScript {
G_UNICODE_SCRIPT_INVALID_CODE = -1, G_UNICODE_SCRIPT_COMMON = 0, G_UNICODE_SCRIPT_INHERITED, G_UNICODE_SCRIPT_ARABIC,
G_UNICODE_SCRIPT_ARMENIAN, G_UNICODE_SCRIPT_BENGALI, G_UNICODE_SCRIPT_BOPOMOFO, G_UNICODE_SCRIPT_CHEROKEE,
G_UNICODE_SCRIPT_COPTIC, G_UNICODE_SCRIPT_CYRILLIC, G_UNICODE_SCRIPT_DESERET, G_UNICODE_SCRIPT_DEVANAGARI,
G_UNICODE_SCRIPT_ETHIOPIC, G_UNICODE_SCRIPT_GEORGIAN, G_UNICODE_SCRIPT_GOTHIC, G_UNICODE_SCRIPT_GREEK,
G_UNICODE_SCRIPT_GUJARATI, G_UNICODE_SCRIPT_GURMUKHI, G_UNICODE_SCRIPT_HAN, G_UNICODE_SCRIPT_HANGUL,
G_UNICODE_SCRIPT_HEBREW, G_UNICODE_SCRIPT_HIRAGANA, G_UNICODE_SCRIPT_KANNADA, G_UNICODE_SCRIPT_KATAKANA,
G_UNICODE_SCRIPT_KHMER, G_UNICODE_SCRIPT_LAO, G_UNICODE_SCRIPT_LATIN, G_UNICODE_SCRIPT_MALAYALAM,
G_UNICODE_SCRIPT_MONGOLIAN, G_UNICODE_SCRIPT_MYANMAR, G_UNICODE_SCRIPT_OGHAM, G_UNICODE_SCRIPT_OLD_ITALIC,
G_UNICODE_SCRIPT_ORIYA, G_UNICODE_SCRIPT_RUNIC, G_UNICODE_SCRIPT_SINHALA, G_UNICODE_SCRIPT_SYRIAC,
G_UNICODE_SCRIPT_TAMIL, G_UNICODE_SCRIPT_TELUGU, G_UNICODE_SCRIPT_THAANA, G_UNICODE_SCRIPT_THAI,
G_UNICODE_SCRIPT_TIBETAN, G_UNICODE_SCRIPT_CANADIAN_ABORIGINAL, G_UNICODE_SCRIPT_YI, G_UNICODE_SCRIPT_TAGALOG,
G_UNICODE_SCRIPT_HANUNOO, G_UNICODE_SCRIPT_BUHID, G_UNICODE_SCRIPT_TAGBANWA, G_UNICODE_SCRIPT_BRAILLE,
G_UNICODE_SCRIPT_CYPRIOT, G_UNICODE_SCRIPT_LIMBU, G_UNICODE_SCRIPT_OSMANYA, G_UNICODE_SCRIPT_SHAVIAN,
G_UNICODE_SCRIPT_LINEAR_B, G_UNICODE_SCRIPT_TAI_LE, G_UNICODE_SCRIPT_UGARITIC, G_UNICODE_SCRIPT_NEW_TAI_LUE,
G_UNICODE_SCRIPT_BUGINESE, G_UNICODE_SCRIPT_GLAGOLITIC, G_UNICODE_SCRIPT_TIFINAGH, G_UNICODE_SCRIPT_SYLOTI_NAGRI,
G_UNICODE_SCRIPT_OLD_PERSIAN, G_UNICODE_SCRIPT_KHAROSHTHI, G_UNICODE_SCRIPT_UNKNOWN, G_UNICODE_SCRIPT_BALINESE,
G_UNICODE_SCRIPT_CUNEIFORM, G_UNICODE_SCRIPT_PHOENICIAN, G_UNICODE_SCRIPT_PHAGS_PA, G_UNICODE_SCRIPT_NKO,
G_UNICODE_SCRIPT_KAYAH_LI, G_UNICODE_SCRIPT_LEPCHA, G_UNICODE_SCRIPT_REJANG, G_UNICODE_SCRIPT_SUNDANESE,
G_UNICODE_SCRIPT_SAURASHTRA, G_UNICODE_SCRIPT_CHAM, G_UNICODE_SCRIPT_OL_CHIKI, G_UNICODE_SCRIPT_VAI,
G_UNICODE_SCRIPT_CARIAN, G_UNICODE_SCRIPT_LYCIAN, G_UNICODE_SCRIPT_LYDIAN
}
enum GNormalizeMode {
G_NORMALIZE_DEFAULT, G_NORMALIZE_NFD = G_NORMALIZE_DEFAULT, G_NORMALIZE_DEFAULT_COMPOSE, G_NORMALIZE_NFC = G_NORMALIZE_DEFAULT_COMPOSE,
G_NORMALIZE_ALL, G_NORMALIZE_NFKD = G_NORMALIZE_ALL, G_NORMALIZE_ALL_COMPOSE, G_NORMALIZE_NFKC = G_NORMALIZE_ALL_COMPOSE
}
Functions
gboolean g_get_charset (G_CONST_RETURN char **charset)
gboolean g_unichar_isalnum (gunichar c) G_GNUC_CONST
gboolean g_unichar_isalpha (gunichar c) G_GNUC_CONST
gboolean g_unichar_iscntrl (gunichar c) G_GNUC_CONST
gboolean g_unichar_isdigit (gunichar c) G_GNUC_CONST
gboolean g_unichar_isgraph (gunichar c) G_GNUC_CONST
gboolean g_unichar_islower (gunichar c) G_GNUC_CONST
gboolean g_unichar_isprint (gunichar c) G_GNUC_CONST
gboolean g_unichar_ispunct (gunichar c) G_GNUC_CONST
gboolean g_unichar_isspace (gunichar c) G_GNUC_CONST
gboolean g_unichar_isupper (gunichar c) G_GNUC_CONST
gboolean g_unichar_isxdigit (gunichar c) G_GNUC_CONST
gboolean g_unichar_istitle (gunichar c) G_GNUC_CONST
gboolean g_unichar_isdefined (gunichar c) G_GNUC_CONST
gboolean g_unichar_iswide (gunichar c) G_GNUC_CONST
gboolean g_unichar_iswide_cjk (gunichar c) G_GNUC_CONST
gboolean g_unichar_iszerowidth (gunichar c) G_GNUC_CONST
gboolean g_unichar_ismark (gunichar c) G_GNUC_CONST
gunichar g_unichar_toupper (gunichar c) G_GNUC_CONST
gunichar g_unichar_tolower (gunichar c) G_GNUC_CONST
gunichar g_unichar_totitle (gunichar c) G_GNUC_CONST
gint g_unichar_digit_value (gunichar c) G_GNUC_CONST
gint g_unichar_xdigit_value (gunichar c) G_GNUC_CONST
GUnicodeType g_unichar_type (gunichar c) G_GNUC_CONST
GUnicodeBreakType g_unichar_break_type (gunichar c) G_GNUC_CONST
gint g_unichar_combining_class (gunichar uc) G_GNUC_CONST
void g_unicode_canonical_ordering (gunichar *string, gsize len)
gunichar * g_unicode_canonical_decomposition (gunichar ch, gsize *result_len) G_GNUC_MALLOC
gunichar g_utf8_get_char (const gchar *p) G_GNUC_PURE
gunichar g_utf8_get_char_validated (const gchar *p, gssize max_len) G_GNUC_PURE
gchar * g_utf8_offset_to_pointer (const gchar *str, glong offset) G_GNUC_PURE
glong g_utf8_pointer_to_offset (const gchar *str, const gchar *pos) G_GNUC_PURE
gchar * g_utf8_prev_char (const gchar *p) G_GNUC_PURE
gchar * g_utf8_find_next_char (const gchar *p, const gchar *end) G_GNUC_PURE
gchar * g_utf8_find_prev_char (const gchar *str, const gchar *p) G_GNUC_PURE
glong g_utf8_strlen (const gchar *p, gssize max) G_GNUC_PURE
gchar * g_utf8_strncpy (gchar *dest, const gchar *src, gsize n)
gchar * g_utf8_strchr (const gchar *p, gssize len, gunichar c)
gchar * g_utf8_strrchr (const gchar *p, gssize len, gunichar c)
gchar * g_utf8_strreverse (const gchar *str, gssize len)
gunichar2 * g_utf8_to_utf16 (const gchar *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gunichar * g_utf8_to_ucs4 (const gchar *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gunichar * g_utf8_to_ucs4_fast (const gchar *str, glong len, glong *items_written) G_GNUC_MALLOC
gunichar * g_utf16_to_ucs4 (const gunichar2 *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gchar * g_utf16_to_utf8 (const gunichar2 *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gunichar2 * g_ucs4_to_utf16 (const gunichar *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gchar * g_ucs4_to_utf8 (const gunichar *str, glong len, glong *items_read, glong *items_written, GError **error) G_GNUC_MALLOC
gint g_unichar_to_utf8 (gunichar c, gchar *outbuf)
gboolean g_utf8_validate (const gchar *str, gssize max_len, const gchar **end)
gboolean g_unichar_validate (gunichar ch) G_GNUC_CONST
gchar * g_utf8_strup (const gchar *str, gssize len) G_GNUC_MALLOC
gchar * g_utf8_strdown (const gchar *str, gssize len) G_GNUC_MALLOC
gchar * g_utf8_casefold (const gchar *str, gssize len) G_GNUC_MALLOC
gchar * g_utf8_normalize (const gchar *str, gssize len, GNormalizeMode mode) G_GNUC_MALLOC
gint g_utf8_collate (const gchar *str1, const gchar *str2) G_GNUC_PURE
gchar * g_utf8_collate_key (const gchar *str, gssize len) G_GNUC_MALLOC
gchar * g_utf8_collate_key_for_filename (const gchar *str, gssize len) G_GNUC_MALLOC
gboolean g_unichar_get_mirror_char (gunichar ch, gunichar *mirrored_ch)
GUnicodeScript g_unichar_get_script (gunichar ch) G_GNUC_CONST
gchar * _g_utf8_make_valid (const gchar *name)
Variables
G_BEGIN_DECLS typedef guint32 gunichar
GLIB_VAR const gchar *const g_utf8_skip
Macro Definition Documentation
#define __G_UNICODE_H__
#define g_utf8_next_char (p) (char *)((p) + g_utf8_skip[*(const guchar *)(p)])
Referenced by font_freetype_get_text_bbox(), font_freetype_text_new(), g_utf8_offset_to_pointer(), g_utf8_pointer_to_offset(), g_utf8_strlen(), g_utf8_strncpy(), g_utf8_to_ucs4_fast(), and g_utf8_to_utf16().
Typedef Documentation
typedef guint16 gunichar2
Enumeration Type Documentation
enum GNormalizeMode
Enumerator
G_NORMALIZE_DEFAULT
G_NORMALIZE_NFD
G_NORMALIZE_DEFAULT_COMPOSE
G_NORMALIZE_NFC
G_NORMALIZE_ALL
G_NORMALIZE_NFKD
G_NORMALIZE_ALL_COMPOSE
G_NORMALIZE_NFKC
enum GUnicodeBreakType
Enumerator
G_UNICODE_BREAK_MANDATORY
G_UNICODE_BREAK_CARRIAGE_RETURN
G_UNICODE_BREAK_LINE_FEED
G_UNICODE_BREAK_COMBINING_MARK
G_UNICODE_BREAK_SURROGATE
G_UNICODE_BREAK_ZERO_WIDTH_SPACE
G_UNICODE_BREAK_INSEPARABLE
G_UNICODE_BREAK_NON_BREAKING_GLUE
G_UNICODE_BREAK_CONTINGENT
G_UNICODE_BREAK_SPACE
G_UNICODE_BREAK_AFTER
G_UNICODE_BREAK_BEFORE
G_UNICODE_BREAK_BEFORE_AND_AFTER
G_UNICODE_BREAK_HYPHEN
G_UNICODE_BREAK_NON_STARTER
G_UNICODE_BREAK_OPEN_PUNCTUATION
G_UNICODE_BREAK_CLOSE_PUNCTUATION
G_UNICODE_BREAK_QUOTATION
G_UNICODE_BREAK_EXCLAMATION
G_UNICODE_BREAK_IDEOGRAPHIC
G_UNICODE_BREAK_NUMERIC
G_UNICODE_BREAK_INFIX_SEPARATOR
G_UNICODE_BREAK_SYMBOL
G_UNICODE_BREAK_ALPHABETIC
G_UNICODE_BREAK_PREFIX
G_UNICODE_BREAK_POSTFIX
G_UNICODE_BREAK_COMPLEX_CONTEXT
G_UNICODE_BREAK_AMBIGUOUS
G_UNICODE_BREAK_UNKNOWN
G_UNICODE_BREAK_NEXT_LINE
G_UNICODE_BREAK_WORD_JOINER
G_UNICODE_BREAK_HANGUL_L_JAMO
G_UNICODE_BREAK_HANGUL_V_JAMO
G_UNICODE_BREAK_HANGUL_T_JAMO
G_UNICODE_BREAK_HANGUL_LV_SYLLABLE
G_UNICODE_BREAK_HANGUL_LVT_SYLLABLE
enum GUnicodeScript
Enumerator
G_UNICODE_SCRIPT_INVALID_CODE
G_UNICODE_SCRIPT_COMMON
G_UNICODE_SCRIPT_INHERITED
G_UNICODE_SCRIPT_ARABIC
G_UNICODE_SCRIPT_ARMENIAN
G_UNICODE_SCRIPT_BENGALI
G_UNICODE_SCRIPT_BOPOMOFO
G_UNICODE_SCRIPT_CHEROKEE
G_UNICODE_SCRIPT_COPTIC
G_UNICODE_SCRIPT_CYRILLIC
G_UNICODE_SCRIPT_DESERET
G_UNICODE_SCRIPT_DEVANAGARI
G_UNICODE_SCRIPT_ETHIOPIC
G_UNICODE_SCRIPT_GEORGIAN
G_UNICODE_SCRIPT_GOTHIC
G_UNICODE_SCRIPT_GREEK
G_UNICODE_SCRIPT_GUJARATI
G_UNICODE_SCRIPT_GURMUKHI
G_UNICODE_SCRIPT_HAN
G_UNICODE_SCRIPT_HANGUL
G_UNICODE_SCRIPT_HEBREW
G_UNICODE_SCRIPT_HIRAGANA
G_UNICODE_SCRIPT_KANNADA
G_UNICODE_SCRIPT_KATAKANA
G_UNICODE_SCRIPT_KHMER
G_UNICODE_SCRIPT_LAO
G_UNICODE_SCRIPT_LATIN
G_UNICODE_SCRIPT_MALAYALAM
G_UNICODE_SCRIPT_MONGOLIAN
G_UNICODE_SCRIPT_MYANMAR
G_UNICODE_SCRIPT_OGHAM
G_UNICODE_SCRIPT_OLD_ITALIC
G_UNICODE_SCRIPT_ORIYA
G_UNICODE_SCRIPT_RUNIC
G_UNICODE_SCRIPT_SINHALA
G_UNICODE_SCRIPT_SYRIAC
G_UNICODE_SCRIPT_TAMIL
G_UNICODE_SCRIPT_TELUGU
G_UNICODE_SCRIPT_THAANA
G_UNICODE_SCRIPT_THAI
G_UNICODE_SCRIPT_TIBETAN
G_UNICODE_SCRIPT_CANADIAN_ABORIGINAL
G_UNICODE_SCRIPT_YI
G_UNICODE_SCRIPT_TAGALOG
G_UNICODE_SCRIPT_HANUNOO
G_UNICODE_SCRIPT_BUHID
G_UNICODE_SCRIPT_TAGBANWA
G_UNICODE_SCRIPT_BRAILLE
G_UNICODE_SCRIPT_CYPRIOT
G_UNICODE_SCRIPT_LIMBU
G_UNICODE_SCRIPT_OSMANYA
G_UNICODE_SCRIPT_SHAVIAN
G_UNICODE_SCRIPT_LINEAR_B
G_UNICODE_SCRIPT_TAI_LE
G_UNICODE_SCRIPT_UGARITIC
G_UNICODE_SCRIPT_NEW_TAI_LUE
G_UNICODE_SCRIPT_BUGINESE
G_UNICODE_SCRIPT_GLAGOLITIC
G_UNICODE_SCRIPT_TIFINAGH
G_UNICODE_SCRIPT_SYLOTI_NAGRI
G_UNICODE_SCRIPT_OLD_PERSIAN
G_UNICODE_SCRIPT_KHAROSHTHI
G_UNICODE_SCRIPT_UNKNOWN
G_UNICODE_SCRIPT_BALINESE
G_UNICODE_SCRIPT_CUNEIFORM
G_UNICODE_SCRIPT_PHOENICIAN
G_UNICODE_SCRIPT_PHAGS_PA
G_UNICODE_SCRIPT_NKO
G_UNICODE_SCRIPT_KAYAH_LI
G_UNICODE_SCRIPT_LEPCHA
G_UNICODE_SCRIPT_REJANG
G_UNICODE_SCRIPT_SUNDANESE
G_UNICODE_SCRIPT_SAURASHTRA
G_UNICODE_SCRIPT_CHAM
G_UNICODE_SCRIPT_OL_CHIKI
G_UNICODE_SCRIPT_VAI
G_UNICODE_SCRIPT_CARIAN
G_UNICODE_SCRIPT_LYCIAN
G_UNICODE_SCRIPT_LYDIAN
enum GUnicodeType
Enumerator
G_UNICODE_CONTROL
G_UNICODE_FORMAT
G_UNICODE_UNASSIGNED
G_UNICODE_PRIVATE_USE
G_UNICODE_SURROGATE
G_UNICODE_LOWERCASE_LETTER
G_UNICODE_MODIFIER_LETTER
G_UNICODE_OTHER_LETTER
G_UNICODE_TITLECASE_LETTER
G_UNICODE_UPPERCASE_LETTER
G_UNICODE_COMBINING_MARK
G_UNICODE_ENCLOSING_MARK
G_UNICODE_NON_SPACING_MARK
G_UNICODE_DECIMAL_NUMBER
G_UNICODE_LETTER_NUMBER
G_UNICODE_OTHER_NUMBER
G_UNICODE_CONNECT_PUNCTUATION
G_UNICODE_DASH_PUNCTUATION
G_UNICODE_CLOSE_PUNCTUATION
G_UNICODE_FINAL_PUNCTUATION
G_UNICODE_INITIAL_PUNCTUATION
G_UNICODE_OTHER_PUNCTUATION
G_UNICODE_OPEN_PUNCTUATION
G_UNICODE_CURRENCY_SYMBOL
G_UNICODE_MODIFIER_SYMBOL
G_UNICODE_MATH_SYMBOL
G_UNICODE_OTHER_SYMBOL
G_UNICODE_LINE_SEPARATOR
G_UNICODE_PARAGRAPH_SEPARATOR
G_UNICODE_SPACE_SEPARATOR
Function Documentation
gchar* _g_utf8_make_valid (const gchar * name)
gboolean g_get_charset (G_CONST_RETURN char ** charset)
gunichar2* g_ucs4_to_utf16 (const gunichar * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_ucs4_to_utf16: : a UCS-4 encoded string : the maximum length (number of characters) of to use. If < 0, then the string is nul-terminated. : location to store number of bytes read, or NULL. If an error occurs then the index of the invalid input is stored here. : location to store number of <type>gunichar2</type> written, or NULL. The value stored here does not include the trailing 0. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UCS-4 to UTF-16. A 0 character will be added to the result after the converted text.
Return value: a pointer to a newly allocated UTF-16 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, g_new, g_set_error_literal(), gunichar, i, and NULL.
gchar* g_ucs4_to_utf8 (const gunichar * str, glong len, glong * items_read, glong * items_written, GError ** error)
GUnicodeBreakType g_unichar_break_type (gunichar c)
gint g_unichar_combining_class (gunichar uc)
gint g_unichar_digit_value (gunichar c)
gboolean g_unichar_get_mirror_char (gunichar ch, gunichar * mirrored_ch)
GUnicodeScript g_unichar_get_script (gunichar ch)
gboolean g_unichar_isalnum (gunichar c)
gboolean g_unichar_isalpha (gunichar c)
gboolean g_unichar_iscntrl (gunichar c)
gboolean g_unichar_isdefined (gunichar c)
gboolean g_unichar_isdigit (gunichar c)
gboolean g_unichar_isgraph (gunichar c)
gboolean g_unichar_islower (gunichar c)
gboolean g_unichar_ismark (gunichar c)
gboolean g_unichar_isprint (gunichar c)
gboolean g_unichar_ispunct (gunichar c)
gboolean g_unichar_isspace (gunichar c)
gboolean g_unichar_istitle (gunichar c)
gboolean g_unichar_isupper (gunichar c)
gboolean g_unichar_iswide (gunichar c)
gboolean g_unichar_iswide_cjk (gunichar c)
gboolean g_unichar_isxdigit (gunichar c)
gboolean g_unichar_iszerowidth (gunichar c)
gint g_unichar_to_utf8 (gunichar c, gchar * outbuf)
g_unichar_to_utf8: : a Unicode character code : output buffer, must have at least 6 bytes of space. If NULL, the length will be computed and returned and nothing will be written to .
Converts a single character to UTF-8.
Return value: number of bytes written
References i.
Referenced by g_utf16_to_utf8(), g_utf8_strchr(), g_utf8_strrchr(), and keypress().
gunichar g_unichar_tolower (gunichar c)
gunichar g_unichar_totitle (gunichar c)
gunichar g_unichar_toupper (gunichar c)
GUnicodeType g_unichar_type (gunichar c)
gboolean g_unichar_validate (gunichar ch)
g_unichar_validate: : a Unicode character
Checks whether is a valid Unicode character. Some possible integer values of will not be valid. 0 is considered a valid character, though it's normally a string terminator.
Return value: TRUE if is a valid Unicode character
References UNICODE_VALID.
gint g_unichar_xdigit_value (gunichar c)
gunichar* g_unicode_canonical_decomposition (gunichar ch, gsize * result_len)
void g_unicode_canonical_ordering (gunichar * string, gsize len)
gunichar* g_utf16_to_ucs4 (const gunichar2 * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf16_to_ucs4: : a UTF-16 encoded string : the maximum length (number of <type>gunichar2</type>) of to use. If < 0, then the string is nul-terminated. : location to store number of words read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of characters written, or NULL. The value stored here does not include the trailing 0 character. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-16 to UCS-4. The result will be nul-terminated.
Return value: a pointer to a newly allocated UCS-4 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, c, g_malloc(), g_return_val_if_fail, g_set_error_literal(), gchar, gunichar, NULL, and SURROGATE_VALUE.
gchar* g_utf16_to_utf8 (const gunichar2 * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf16_to_utf8: : a UTF-16 encoded string : the maximum length (number of <type>gunichar2</type>) of to use. If < 0, then the string is nul-terminated. : location to store number of words read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of bytes written, or NULL. The value stored here does not include the trailing 0 byte. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-16 to UTF-8. The result will be terminated with a 0 byte.
Note that the input is expected to be already in native endianness, an initial byte-order-mark character is not handled specially. g_convert() can be used to convert a byte buffer of UTF-16 data of ambiguous endianess.
Return value: a pointer to a newly allocated UTF-8 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, c, g_malloc(), g_return_val_if_fail, g_set_error_literal(), g_unichar_to_utf8(), gchar, gunichar, NULL, SURROGATE_VALUE, and UTF8_LENGTH.
gchar* g_utf8_casefold (const gchar * str, gssize len)
References g_ascii_strdown().
Referenced by navit_utf8_strcasecmp().
gint g_utf8_collate (const gchar * str1, const gchar * str2)
gchar* g_utf8_collate_key (const gchar * str, gssize len)
gchar* g_utf8_collate_key_for_filename (const gchar * str, gssize len)
gchar* g_utf8_find_next_char (const gchar * p, const gchar * end)
g_utf8_find_next_char: : a pointer to a position within a UTF-8 encoded string : a pointer to the byte following the end of the string, or NULL to indicate that the string is nul-terminated.
Finds the start of the next UTF-8 character in the string after .
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte.
Return value: a pointer to the found character or NULL
References gchar, NULL, and p.
Referenced by linguistics_casefold(), linguistics_dup_utf8_char(), linguistics_expand_special(), and linguistics_get_special().
gchar* g_utf8_find_prev_char (const gchar * str, const gchar * p)
Referenced by gui_internal_label_new_abbrev().
gunichar g_utf8_get_char (const gchar * p)
g_utf8_get_char: : a pointer to Unicode character encoded as UTF-8
Converts a sequence of bytes encoded as UTF-8 to a Unicode character. If does not point to a valid UTF-8 encoded character, results are undefined. If you are not sure that the bytes are complete valid Unicode characters, you should use g_utf8_get_char_validated() instead.
Return value: the resulting character
References c, gunichar, i, mask, UTF8_COMPUTE, and UTF8_GET.
Referenced by font_freetype_get_text_bbox(), font_freetype_text_new(), and g_utf8_to_utf16().
gunichar g_utf8_get_char_validated (const gchar * p, gssize max_len)
g_utf8_get_char_validated: : a pointer to Unicode character encoded as UTF-8 : the maximum number of bytes to read, or -1, for no maximum or if is nul-terminated
Convert a sequence of bytes encoded as UTF-8 to a Unicode character. This function checks for incomplete characters, for invalid characters such as characters that are out of the range of Unicode, and for overlong encodings of valid characters.
Return value: the resulting character. If points to a partial sequence at the end of a string that could begin a valid character (or if is zero), returns (gunichar)-2; otherwise, if does not point to a valid UTF-8 encoded Unicode character, returns (gunichar)-1.
References g_utf8_get_char_extended(), gunichar, and UNICODE_VALID.
gchar* g_utf8_normalize (const gchar * str, gssize len, GNormalizeMode mode)
gchar* g_utf8_offset_to_pointer (const gchar * str, glong offset)
g_utf8_offset_to_pointer: : a UTF-8 encoded string : a character offset within
Converts from an integer character offset to a pointer to a position within the string.
Since 2.10, this function allows to pass a negative to step backwards. It is usually worth stepping backwards from the end instead of forwards if is in the last fourth of the string, since moving forward is about 3 times faster than moving backward.
Return value: the resulting pointer
References g_utf8_next_char, g_utf8_pointer_to_offset(), gchar, offset, and s1.
glong g_utf8_pointer_to_offset (const gchar * str, const gchar * pos)
g_utf8_pointer_to_offset: : a UTF-8 encoded string : a pointer to a position within
Converts from a pointer to position within a string to a integer character offset.
Since 2.10, this function allows to be before , and returns a negative offset in this case.
Return value: the resulting character offset
References g_utf8_next_char, gchar, and offset.
Referenced by g_utf8_offset_to_pointer().
gchar* g_utf8_prev_char (const gchar * p)
g_utf8_prev_char: : a pointer to a position within a UTF-8 encoded string
Finds the previous UTF-8 character in the string before .
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte. If might be the first character of the string, you must use g_utf8_find_prev_char() instead.
Return value: a pointer to the found character.
References gchar, p, and TRUE.
Referenced by gui_internal_keypress_do().
gchar* g_utf8_strchr (const gchar * p, gssize len, gunichar c)
Referenced by gui_internal_cmd_pois_item_selected(), and gui_internal_poi_param_set_filter().
gchar* g_utf8_strdown (const gchar * str, gssize len)
glong g_utf8_strlen (const gchar * p, gssize max)
g_utf8_strlen: : pointer to the start of a UTF-8 encoded string. : the maximum number of bytes to examine. If is less than 0, then the string is assumed to be nul-terminated. If is 0, will not be examined and may be NULL.
Returns the length of the string in characters.
Return value: the length of the string in characters
References g_return_val_if_fail, g_utf8_next_char, gchar, NULL, p, and start.
Referenced by font_freetype_get_text_bbox(), font_freetype_text_new(), g_utf8_strlen_force_link(), get_text_bbox(), and gui_internal_search_changed().
gchar* g_utf8_strncpy (gchar * dest, const gchar * src, gsize n)
g_utf8_strncpy: : buffer to fill with characters from : UTF-8 encoded string
: character count
Like the standard C strncpy() function, but copies a given number of characters instead of a given number of bytes. The string must be valid UTF-8 encoded text. (Use g_utf8_validate() on all text before trying to use UTF-8 utility functions with it.)
Return value:
References startup::dest, g_utf8_next_char, and gchar.
gchar* g_utf8_strrchr (const gchar * p, gssize len, gunichar c)
Referenced by graphics_image_new_scaled_rotated().
gchar* g_utf8_strreverse (const gchar * str, gssize len)
g_utf8_strreverse: : a UTF-8 encoded string : the maximum length of to use, in bytes. If < 0, then the string is nul-terminated.
Reverses a UTF-8 string. must be valid UTF-8 encoded text. (Use g_utf8_validate() on all text before trying to use UTF-8 utility functions with it.)
This function is intended for programmatic uses of reversed strings. It pays no attention to decomposed characters, combining marks, byte order marks, directional indicators (LRM, LRO, etc) and similar characters which might need special handling when reversing a string for display purposes.
Note that unlike g_strreverse(), this function returns newly-allocated memory, which should be freed with g_free() when no longer needed.
Returns: a newly-allocated string which is the reverse of .
Since: 2.2
References g_new, g_utf8_skip, gchar, p, and skip().
gchar* g_utf8_strup (const gchar * str, gssize len)
gunichar* g_utf8_to_ucs4 (const gchar * str, glong len, glong * items_read, glong * items_written, GError ** error)
gunichar* g_utf8_to_ucs4_fast (const gchar * str, glong len, glong * items_written)
g_utf8_to_ucs4_fast: : a UTF-8 encoded string : the maximum length of to use, in bytes. If < 0, then the string is nul-terminated. : location to store the number of characters in the result, or NULL.
Convert a string from UTF-8 to a 32-bit fixed width representation as UCS-4, assuming valid UTF-8 input. This function is roughly twice as fast as g_utf8_to_ucs4() but does no error checking on the input.
Return value: a pointer to a newly allocated UCS-4 string. This value must be freed with g_free().
References g_new, g_return_val_if_fail, g_utf8_next_char, gchar, gunichar, i, NULL, and p.
gunichar2* g_utf8_to_utf16 (const gchar * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf8_to_utf16: : a UTF-8 encoded string : the maximum length (number of characters) of to use. If < 0, then the string is nul-terminated. : location to store number of bytes read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of <type>gunichar2</type> written, or NULL. The value stored here does not include the trailing 0. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-8 to UTF-16. A 0 character will be added to the result after the converted text.
Return value: a pointer to a newly allocated UTF-16 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, g_new, g_return_val_if_fail, g_set_error_literal(), g_utf8_get_char(), g_utf8_get_char_extended(), g_utf8_next_char, gchar, gunichar, i, and NULL.
gboolean g_utf8_validate (const gchar * str, gssize max_len, const gchar ** end)
Variable Documentation
GLIB_VAR const gchar* const g_utf8_skip
G_BEGIN_DECLS typedef guint32 gunichar
Referenced by fast_validate(), fast_validate_len(), g_ucs4_to_utf16(), g_utf16_to_ucs4(), g_utf16_to_utf8(), g_utf8_get_char(), g_utf8_get_char_extended(), g_utf8_get_char_validated(), g_utf8_to_ucs4_fast(), and g_utf8_to_utf16().