navit: support/glib/gutf8.c File Reference
gutf8.c File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include "glib.h"
#include "galiasdef.c"
Macros
#define UTF8_COMPUTE(Char, Mask, Len)
#define UTF8_LENGTH(Char)
#define UTF8_GET(Result, Chars, Count, Mask, Len)
#define UNICODE_VALID(Char)
#define SURROGATE_VALUE(h, l) (((h) - 0xd800) * 0x400 + (l) - 0xdc00 + 0x10000)
#define CONTINUATION_CHAR
#define __G_UTF8_C__
Functions
gchar * g_utf8_find_prev_char (const char *str, const char *p)
gchar * g_utf8_find_next_char (const gchar *p, const gchar *end)
gchar * g_utf8_prev_char (const gchar *p)
glong g_utf8_strlen (const gchar *p, gssize max)
gunichar g_utf8_get_char (const gchar *p)
gchar * g_utf8_offset_to_pointer (const gchar *str, glong offset)
glong g_utf8_pointer_to_offset (const gchar *str, const gchar *pos)
gchar * g_utf8_strncpy (gchar *dest, const gchar *src, gsize n)
int g_unichar_to_utf8 (gunichar c, gchar *outbuf)
gchar * g_utf8_strchr (const char *p, gssize len, gunichar c)
gchar * g_utf8_strrchr (const char *p, gssize len, gunichar c)
static gunichar g_utf8_get_char_extended (const gchar *p, gssize max_len)
gunichar g_utf8_get_char_validated (const gchar *p, gssize max_len)
gunichar * g_utf8_to_ucs4_fast (const gchar *str, glong len, glong *items_written)
gchar * g_utf16_to_utf8 (const gunichar2 *str, glong len, glong *items_read, glong *items_written, GError **error)
gunichar * g_utf16_to_ucs4 (const gunichar2 *str, glong len, glong *items_read, glong *items_written, GError **error)
gunichar2 * g_utf8_to_utf16 (const gchar *str, glong len, glong *items_read, glong *items_written, GError **error)
gunichar2 * g_ucs4_to_utf16 (const gunichar *str, glong len, glong *items_read, glong *items_written, GError **error)
static const gchar * fast_validate (const char *str)
static const gchar * fast_validate_len (const char *str, gssize max_len)
gboolean g_utf8_validate (const char *str, gssize max_len, const gchar **end)
gboolean g_unichar_validate (gunichar ch)
gchar * g_utf8_strreverse (const gchar *str, gssize len)
Variables
static const gchar utf8_skip_data [256]
const gchar *const g_utf8_skip = utf8_skip_data
Macro Definition Documentation
#define __G_UTF8_C__
#define CONTINUATION_CHAR
Value:
G_STMT_START {                                     \
  if ((*(guchar *)p & 0xc0) != 0x80) /* 10xxxxxx */ \
    goto error;                                     \
  val <<= 6;                                        \
  val |= (*(guchar *)p) & 0x3f;                     \
 } G_STMT_END
Referenced by fast_validate(), and fast_validate_len().
#define SURROGATE_VALUE (h, l) (((h) - 0xd800) * 0x400 + (l) - 0xdc00 + 0x10000)
Referenced by g_utf16_to_ucs4(), and g_utf16_to_utf8().
#define UNICODE_VALID (Char)
Value:
((Char) < 0x110000 &&                     \
     (((Char) & 0xFFFFF800) != 0xD800) &&     \
     ((Char) < 0xFDD0 || (Char) > 0xFDEF) &&  \
     ((Char) & 0xFFFE) != 0xFFFE)
Referenced by fast_validate(), fast_validate_len(), g_unichar_validate(), and g_utf8_get_char_validated().
#define UTF8_COMPUTE (Char, Mask, Len)
Referenced by g_utf8_get_char().
#define UTF8_GET (Result, Chars, Count, Mask, Len)
Value:
(Result) = (Chars)[0] & (Mask);                                       \
  for ((Count) = 1; (Count) < (Len); ++(Count))                               \
    {                                                                         \
      if (((Chars)[(Count)] & 0xc0) != 0x80)                                  \
        {                                                                     \
          (Result) = -1;                                                      \
          break;                                                              \
        }                                                                     \
      (Result) <<= 6;                                                         \
      (Result) |= ((Chars)[(Count)] & 0x3f);                                  \
    }
Referenced by g_utf8_get_char().
#define UTF8_LENGTH (Char)
Value:
((Char) < 0x80 ? 1 :                 \
   ((Char) < 0x800 ? 2 :               \
    ((Char) < 0x10000 ? 3 :            \
     ((Char) < 0x200000 ? 4 :          \
      ((Char) < 0x4000000 ? 5 : 6)))))
Referenced by g_utf16_to_utf8(), and g_utf8_get_char_extended().
Function Documentation
static const gchar* fast_validate (const char * str) static
References CONTINUATION_CHAR, G_UNLIKELY, gchar, gunichar, p, and UNICODE_VALID.
Referenced by g_utf8_validate().
static const gchar* fast_validate_len (const char * str, gssize max_len) static
References CONTINUATION_CHAR, g_assert, G_UNLIKELY, gchar, gunichar, p, and UNICODE_VALID.
Referenced by g_utf8_validate().
gunichar2* g_ucs4_to_utf16 (const gunichar * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_ucs4_to_utf16: : a UCS-4 encoded string : the maximum length (number of characters) of to use. If < 0, then the string is nul-terminated. : location to store number of bytes read, or NULL. If an error occurs then the index of the invalid input is stored here. : location to store number of <type>gunichar2</type> written, or NULL. The value stored here does not include the trailing 0. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UCS-4 to UTF-16. A 0 character will be added to the result after the converted text.
Return value: a pointer to a newly allocated UTF-16 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, g_new, g_set_error_literal(), gunichar, i, and NULL.
int g_unichar_to_utf8 (gunichar c, gchar * outbuf)
g_unichar_to_utf8: : a Unicode character code : output buffer, must have at least 6 bytes of space. If NULL, the length will be computed and returned and nothing will be written to .
Converts a single character to UTF-8.
Return value: number of bytes written
References i.
Referenced by g_utf16_to_utf8(), g_utf8_strchr(), g_utf8_strrchr(), and keypress().
gboolean g_unichar_validate (gunichar ch)
g_unichar_validate: : a Unicode character
Checks whether is a valid Unicode character. Some possible integer values of will not be valid. 0 is considered a valid character, though it's normally a string terminator.
Return value: TRUE if is a valid Unicode character
References UNICODE_VALID.
gunichar* g_utf16_to_ucs4 (const gunichar2 * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf16_to_ucs4: : a UTF-16 encoded string : the maximum length (number of <type>gunichar2</type>) of to use. If < 0, then the string is nul-terminated. : location to store number of words read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of characters written, or NULL. The value stored here does not include the trailing 0 character. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-16 to UCS-4. The result will be nul-terminated.
Return value: a pointer to a newly allocated UCS-4 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, c, g_malloc(), g_return_val_if_fail, g_set_error_literal(), gchar, gunichar, NULL, and SURROGATE_VALUE.
gchar* g_utf16_to_utf8 (const gunichar2 * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf16_to_utf8: : a UTF-16 encoded string : the maximum length (number of <type>gunichar2</type>) of to use. If < 0, then the string is nul-terminated. : location to store number of words read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of bytes written, or NULL. The value stored here does not include the trailing 0 byte. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-16 to UTF-8. The result will be terminated with a 0 byte.
Note that the input is expected to be already in native endianness, an initial byte-order-mark character is not handled specially. g_convert() can be used to convert a byte buffer of UTF-16 data of ambiguous endianess.
Return value: a pointer to a newly allocated UTF-8 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, c, g_malloc(), g_return_val_if_fail, g_set_error_literal(), g_unichar_to_utf8(), gchar, gunichar, NULL, SURROGATE_VALUE, and UTF8_LENGTH.
gchar* g_utf8_find_next_char (const gchar * p, const gchar * end)
g_utf8_find_next_char: : a pointer to a position within a UTF-8 encoded string : a pointer to the byte following the end of the string, or NULL to indicate that the string is nul-terminated.
Finds the start of the next UTF-8 character in the string after .
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte.
Return value: a pointer to the found character or NULL
References gchar, NULL, and p.
Referenced by linguistics_casefold(), linguistics_dup_utf8_char(), linguistics_expand_special(), and linguistics_get_special().
gchar* g_utf8_find_prev_char (const char * str, const char * p)
g_utf8_find_prev_char: : pointer to the beginning of a UTF-8 encoded string : pointer to some position within
Given a position with a UTF-8 encoded string , find the start of the previous UTF-8 character starting before . Returns NULL if no UTF-8 characters are present in before .
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte.
Return value: a pointer to the found character or NULL.
References gchar, NULL, and p.
gunichar g_utf8_get_char (const gchar * p)
g_utf8_get_char: : a pointer to Unicode character encoded as UTF-8
Converts a sequence of bytes encoded as UTF-8 to a Unicode character. If does not point to a valid UTF-8 encoded character, results are undefined. If you are not sure that the bytes are complete valid Unicode characters, you should use g_utf8_get_char_validated() instead.
Return value: the resulting character
References c, gunichar, i, mask, UTF8_COMPUTE, and UTF8_GET.
Referenced by font_freetype_get_text_bbox(), font_freetype_text_new(), and g_utf8_to_utf16().
static gunichar g_utf8_get_char_extended (const gchar * p, gssize max_len) inline static
References gunichar, i, and UTF8_LENGTH.
Referenced by g_utf8_get_char_validated(), and g_utf8_to_utf16().
gunichar g_utf8_get_char_validated (const gchar * p, gssize max_len)
g_utf8_get_char_validated: : a pointer to Unicode character encoded as UTF-8 : the maximum number of bytes to read, or -1, for no maximum or if is nul-terminated
Convert a sequence of bytes encoded as UTF-8 to a Unicode character. This function checks for incomplete characters, for invalid characters such as characters that are out of the range of Unicode, and for overlong encodings of valid characters.
Return value: the resulting character. If points to a partial sequence at the end of a string that could begin a valid character (or if is zero), returns (gunichar)-2; otherwise, if does not point to a valid UTF-8 encoded Unicode character, returns (gunichar)-1.
References g_utf8_get_char_extended(), gunichar, and UNICODE_VALID.
gchar* g_utf8_offset_to_pointer (const gchar * str, glong offset)
g_utf8_offset_to_pointer: : a UTF-8 encoded string : a character offset within
Converts from an integer character offset to a pointer to a position within the string.
Since 2.10, this function allows to pass a negative to step backwards. It is usually worth stepping backwards from the end instead of forwards if is in the last fourth of the string, since moving forward is about 3 times faster than moving backward.
Return value: the resulting pointer
References g_utf8_next_char, g_utf8_pointer_to_offset(), gchar, offset, and s1.
glong g_utf8_pointer_to_offset (const gchar * str, const gchar * pos)
g_utf8_pointer_to_offset: : a UTF-8 encoded string : a pointer to a position within
Converts from a pointer to position within a string to a integer character offset.
Since 2.10, this function allows to be before , and returns a negative offset in this case.
Return value: the resulting character offset
References g_utf8_next_char, gchar, and offset.
Referenced by g_utf8_offset_to_pointer().
gchar* g_utf8_prev_char (const gchar * p)
g_utf8_prev_char: : a pointer to a position within a UTF-8 encoded string
Finds the previous UTF-8 character in the string before .
does not have to be at the beginning of a UTF-8 character. No check is made to see if the character found is actually valid other than it starts with an appropriate byte. If might be the first character of the string, you must use g_utf8_find_prev_char() instead.
Return value: a pointer to the found character.
References gchar, p, and TRUE.
Referenced by gui_internal_keypress_do().
gchar* g_utf8_strchr (const char * p, gssize len, gunichar c)
g_utf8_strchr: : a nul-terminated UTF-8 encoded string : the maximum length of : a Unicode character
Finds the leftmost occurrence of the given Unicode character in a UTF-8 encoded string, while limiting the search to bytes. If is -1, allow unbounded search.
Return value: NULL if the string does not contain the character, otherwise, a pointer to the start of the leftmost occurrence of the character in the string.
References g_strstr_len(), g_unichar_to_utf8(), and gchar.
glong g_utf8_strlen (const gchar * p, gssize max)
g_utf8_strlen: : pointer to the start of a UTF-8 encoded string. : the maximum number of bytes to examine. If is less than 0, then the string is assumed to be nul-terminated. If is 0, will not be examined and may be NULL.
Returns the length of the string in characters.
Return value: the length of the string in characters
References g_return_val_if_fail, g_utf8_next_char, gchar, NULL, p, and start.
Referenced by font_freetype_get_text_bbox(), font_freetype_text_new(), g_utf8_strlen_force_link(), get_text_bbox(), and gui_internal_search_changed().
gchar* g_utf8_strncpy (gchar * dest, const gchar * src, gsize n)
g_utf8_strncpy: : buffer to fill with characters from : UTF-8 encoded string
: character count
Like the standard C strncpy() function, but copies a given number of characters instead of a given number of bytes. The string must be valid UTF-8 encoded text. (Use g_utf8_validate() on all text before trying to use UTF-8 utility functions with it.)
Return value:
References startup::dest, g_utf8_next_char, and gchar.
gchar* g_utf8_strrchr (const char * p, gssize len, gunichar c)
g_utf8_strrchr: : a nul-terminated UTF-8 encoded string : the maximum length of : a Unicode character
Find the rightmost occurrence of the given Unicode character in a UTF-8 encoded string, while limiting the search to bytes. If is -1, allow unbounded search.
Return value: NULL if the string does not contain the character, otherwise, a pointer to the start of the rightmost occurrence of the character in the string.
References g_strrstr_len(), g_unichar_to_utf8(), and gchar.
gchar* g_utf8_strreverse (const gchar * str, gssize len)
g_utf8_strreverse: : a UTF-8 encoded string : the maximum length of to use, in bytes. If < 0, then the string is nul-terminated.
Reverses a UTF-8 string. must be valid UTF-8 encoded text. (Use g_utf8_validate() on all text before trying to use UTF-8 utility functions with it.)
This function is intended for programmatic uses of reversed strings. It pays no attention to decomposed characters, combining marks, byte order marks, directional indicators (LRM, LRO, etc) and similar characters which might need special handling when reversing a string for display purposes.
Note that unlike g_strreverse(), this function returns newly-allocated memory, which should be freed with g_free() when no longer needed.
Returns: a newly-allocated string which is the reverse of .
Since: 2.2
References g_new, g_utf8_skip, gchar, p, and skip().
gunichar* g_utf8_to_ucs4_fast (const gchar * str, glong len, glong * items_written)
g_utf8_to_ucs4_fast: : a UTF-8 encoded string : the maximum length of to use, in bytes. If < 0, then the string is nul-terminated. : location to store the number of characters in the result, or NULL.
Convert a string from UTF-8 to a 32-bit fixed width representation as UCS-4, assuming valid UTF-8 input. This function is roughly twice as fast as g_utf8_to_ucs4() but does no error checking on the input.
Return value: a pointer to a newly allocated UCS-4 string. This value must be freed with g_free().
References g_new, g_return_val_if_fail, g_utf8_next_char, gchar, gunichar, i, NULL, and p.
gunichar2* g_utf8_to_utf16 (const gchar * str, glong len, glong * items_read, glong * items_written, GError ** error)
g_utf8_to_utf16: : a UTF-8 encoded string : the maximum length (number of characters) of to use. If < 0, then the string is nul-terminated. : location to store number of bytes read, or NULL. If NULL, then G_CONVERT_ERROR_PARTIAL_INPUT will be returned in case contains a trailing partial character. If an error occurs then the index of the invalid input is stored here. : location to store number of <type>gunichar2</type> written, or NULL. The value stored here does not include the trailing 0. : location to store the error occuring, or NULL to ignore errors. Any of the errors in #GConvertError other than G_CONVERT_ERROR_NO_CONVERSION may occur.
Convert a string from UTF-8 to UTF-16. A 0 character will be added to the result after the converted text.
Return value: a pointer to a newly allocated UTF-16 string. This value must be freed with g_free(). If an error occurs, NULL will be returned and set.
References _, g_new, g_return_val_if_fail, g_set_error_literal(), g_utf8_get_char(), g_utf8_get_char_extended(), g_utf8_next_char, gchar, gunichar, i, and NULL.
gboolean g_utf8_validate (const char * str, gssize max_len, const gchar ** end)
g_utf8_validate: : a pointer to character data : max bytes to validate, or -1 to go until NUL : return location for end of valid data
Validates UTF-8 encoded text. is the text to validate; if is nul-terminated, then can be -1, otherwise should be the number of bytes to validate. If is non-NULL, then the end of the valid range will be stored there (i.e. the start of the first invalid character if some bytes were invalid, or the end of the text being validated otherwise).
Note that g_utf8_validate() returns FALSE if is positive and NUL is met before bytes have been read.
Returns TRUE if all of was valid. Many GLib and GTK+ routines <emphasis>require</emphasis> valid UTF-8 as input; so data read from a file or the network should be checked with g_utf8_validate() before doing anything else with it.
Return value: TRUE if the text was valid UTF-8
References FALSE, fast_validate(), fast_validate_len(), gchar, p, and TRUE.
Variable Documentation
const gchar* const g_utf8_skip = utf8_skip_data
Referenced by g_utf8_strreverse().
const gchar utf8_skip_data[256] static
Initial value:
= {
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
  2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,6,6,1,1
}