navit: support/glib/gutils.h File Reference
gutils.h File Reference
#include <glib/gtypes.h>
#include <stdarg.h>
Data Structures
struct _GDebugKey
struct _GTrashStack
Macros
#define __G_UTILS_H__
#define G_DIR_SEPARATOR '/'
#define G_DIR_SEPARATOR_S "/"
#define G_IS_DIR_SEPARATOR(c) ((c) == G_DIR_SEPARATOR)
#define G_SEARCHPATH_SEPARATOR ':'
#define G_SEARCHPATH_SEPARATOR_S ":"
#define G_VA_COPY(ap1, ap2) ((ap1) = (ap2))
#define inline /* don't inline, then */
#define G_INLINE_FUNC
#define g_dirname g_path_get_dirname
#define ATEXIT(proc) g_ATEXIT(proc)
#define GLIB_CHECK_VERSION(major, minor, micro)
#define G_WIN32_DLLMAIN_FOR_DLL_NAME(static, dll_name)
Typedefs
typedef struct _GDebugKey GDebugKey
typedef void(* GVoidFunc)(void)
typedef struct _GTrashStack GTrashStack
Enumerations
enum GUserDirectory {
G_USER_DIRECTORY_DESKTOP, G_USER_DIRECTORY_DOCUMENTS, G_USER_DIRECTORY_DOWNLOAD, G_USER_DIRECTORY_MUSIC,
G_USER_DIRECTORY_PICTURES, G_USER_DIRECTORY_PUBLIC_SHARE, G_USER_DIRECTORY_TEMPLATES, G_USER_DIRECTORY_VIDEOS,
G_USER_N_DIRECTORIES
}
Functions
G_CONST_RETURN gchar * g_get_user_name (void)
G_CONST_RETURN gchar * g_get_real_name (void)
G_CONST_RETURN gchar * g_get_home_dir (void)
G_CONST_RETURN gchar * g_get_tmp_dir (void)
G_CONST_RETURN gchar * g_get_host_name (void)
gchar * g_get_prgname (void)
void g_set_prgname (const gchar *prgname)
G_CONST_RETURN gchar * g_get_application_name (void)
void g_set_application_name (const gchar *application_name)
void g_reload_user_special_dirs_cache (void)
G_CONST_RETURN gchar * g_get_user_data_dir (void)
G_CONST_RETURN gchar * g_get_user_config_dir (void)
G_CONST_RETURN gchar * g_get_user_cache_dir (void)
G_CONST_RETURN gchar
*G_CONST_RETURN * g_get_system_data_dirs (void)
G_CONST_RETURN gchar
*G_CONST_RETURN * g_get_system_config_dirs (void)
G_CONST_RETURN gchar
*G_CONST_RETURN * g_get_language_names (void)
G_CONST_RETURN gchar * g_get_user_special_dir (GUserDirectory directory)
guint g_parse_debug_string (const gchar *string, const GDebugKey *keys, guint nkeys)
gint g_snprintf (gchar *string, gulong n, gchar const *format,...) G_GNUC_PRINTF(3
gint gint g_vsnprintf (gchar *string, gulong n, gchar const *format, va_list args)
gboolean g_path_is_absolute (const gchar *file_name)
G_CONST_RETURN gchar * g_path_skip_root (const gchar *file_name)
G_CONST_RETURN gchar * g_basename (const gchar *file_name)
gchar * g_get_current_dir (void)
gchar * g_path_get_basename (const gchar *file_name) G_GNUC_MALLOC
gchar * g_path_get_dirname (const gchar *file_name) G_GNUC_MALLOC
void g_nullify_pointer (gpointer *nullify_location)
G_CONST_RETURN gchar * g_getenv (const gchar *variable)
gboolean g_setenv (const gchar *variable, const gchar *value, gboolean overwrite)
void g_unsetenv (const gchar *variable)
gchar ** g_listenv (void)
const gchar * _g_getenv_nomalloc (const gchar *variable, gchar buffer[1024])
void g_atexit (GVoidFunc func)
gchar * g_find_program_in_path (const gchar *program)
G_INLINE_FUNC gint g_bit_nth_lsf (gulong mask, gint nth_bit) G_GNUC_CONST
G_INLINE_FUNC gint g_bit_nth_msf (gulong mask, gint nth_bit) G_GNUC_CONST
G_INLINE_FUNC guint g_bit_storage (gulong number) G_GNUC_CONST
G_INLINE_FUNC void g_trash_stack_push (GTrashStack **stack_p, gpointer data_p)
G_INLINE_FUNC gpointer g_trash_stack_pop (GTrashStack **stack_p)
G_INLINE_FUNC gpointer g_trash_stack_peek (GTrashStack **stack_p)
G_INLINE_FUNC guint g_trash_stack_height (GTrashStack **stack_p)
const gchar * glib_check_version (guint required_major, guint required_minor, guint required_micro)
Variables
GLIB_VAR const guint glib_major_version
GLIB_VAR const guint glib_minor_version
GLIB_VAR const guint glib_micro_version
GLIB_VAR const guint glib_interface_age
GLIB_VAR const guint glib_binary_age
Macro Definition Documentation
#define __G_UTILS_H__
#define ATEXIT (proc) g_ATEXIT(proc)
#define G_DIR_SEPARATOR '/'
#define G_DIR_SEPARATOR_S "/"
Referenced by g_path_get_basename(), and osd_button_icon_path().
#define g_dirname g_path_get_dirname
#define G_INLINE_FUNC
#define G_IS_DIR_SEPARATOR (c) ((c) == G_DIR_SEPARATOR)
Referenced by g_path_get_basename().
#define G_SEARCHPATH_SEPARATOR ':'
#define G_SEARCHPATH_SEPARATOR_S ":"
#define G_VA_COPY (ap1, ap2) ((ap1) = (ap2))
#define G_WIN32_DLLMAIN_FOR_DLL_NAME (static, dll_name)
#define GLIB_CHECK_VERSION (major, minor, micro)
Value:
(GLIB_MAJOR_VERSION > (major) || \
     (GLIB_MAJOR_VERSION == (major) && GLIB_MINOR_VERSION > (minor)) || \
     (GLIB_MAJOR_VERSION == (major) && GLIB_MINOR_VERSION == (minor) && \
      GLIB_MICRO_VERSION >= (micro)))
#define inline /* don't inline, then */
Typedef Documentation
typedef struct _GDebugKey GDebugKey
typedef struct _GTrashStack GTrashStack
typedef void(* GVoidFunc)(void)
Enumeration Type Documentation
enum GUserDirectory
GUserDirectory: : the user's Desktop directory : the user's Documents directory : the user's Downloads directory : the user's Music directory : the user's Pictures directory : the user's shared directory : the user's Templates directory : the user's Movies directory : the number of enum values
These are logical ids for special directories which are defined depending on the platform used. You should use g_get_user_special_dir() to retrieve the full path associated to the logical id.
The GUserDirectory enumeration can be extended at later date. Not every platform has a directory for every logical id in this enumeration.
Since: 2.14
Enumerator
G_USER_DIRECTORY_DESKTOP
G_USER_DIRECTORY_DOCUMENTS
G_USER_DIRECTORY_DOWNLOAD
G_USER_DIRECTORY_MUSIC
G_USER_DIRECTORY_PICTURES
G_USER_DIRECTORY_PUBLIC_SHARE
G_USER_DIRECTORY_TEMPLATES
G_USER_DIRECTORY_VIDEOS
G_USER_N_DIRECTORIES
Function Documentation
const gchar* _g_getenv_nomalloc (const gchar * variable, gchar buffer[1024])
Referenced by g_mem_init_nomessage(), and slice_config_init().
void g_atexit (GVoidFunc func)
G_CONST_RETURN gchar* g_basename (const gchar * file_name)
G_INLINE_FUNC gint g_bit_nth_lsf (gulong mask, gint nth_bit)
G_INLINE_FUNC gint g_bit_nth_msf (gulong mask, gint nth_bit)
G_INLINE_FUNC guint g_bit_storage (gulong number)
Referenced by allocator_aligned_page_size().
gchar* g_find_program_in_path (const gchar * program)
G_CONST_RETURN gchar* g_get_application_name (void)
gchar* g_get_current_dir (void)
G_CONST_RETURN gchar* g_get_home_dir (void)
G_CONST_RETURN gchar* g_get_host_name (void)
G_CONST_RETURN gchar* G_CONST_RETURN* g_get_language_names (void)
gchar* g_get_prgname (void)
g_get_prgname:
Gets the name of the program. This name should <emphasis>not</emphasis> be localized, contrast with g_get_application_name(). (If you are using GDK or GTK+ the program name is set in gdk_init(), which is called by gtk_init(). The program name is found by taking the last component of <literal>argv[0]</literal>.)
Returns: the name of the program. The returned string belongs to GLib and must not be modified or freed.
References gchar, and NULL.
Referenced by mem_error().
G_CONST_RETURN gchar* g_get_real_name (void)
G_CONST_RETURN gchar* G_CONST_RETURN* g_get_system_config_dirs (void)
G_CONST_RETURN gchar* G_CONST_RETURN* g_get_system_data_dirs (void)
G_CONST_RETURN gchar* g_get_tmp_dir (void)
G_CONST_RETURN gchar* g_get_user_cache_dir (void)
G_CONST_RETURN gchar* g_get_user_config_dir (void)
G_CONST_RETURN gchar* g_get_user_data_dir (void)
G_CONST_RETURN gchar* g_get_user_name (void)
G_CONST_RETURN gchar* g_get_user_special_dir (GUserDirectory directory)
G_CONST_RETURN gchar* g_getenv (const gchar * variable)
gchar** g_listenv (void)
void g_nullify_pointer (gpointer * nullify_location)
guint g_parse_debug_string (const gchar * string, const GDebugKey * keys, guint nkeys)
Referenced by g_mem_init_nomessage(), and slice_config_init().
gchar* g_path_get_basename (const gchar * file_name)
g_path_get_basename: : the name of the file.
Gets the last component of the filename. If ends with a directory separator it gets the component before the last slash. If consists only of directory separators (and on Windows, possibly a drive letter), a single separator is returned. If is empty, it gets ".".
Return value: a newly allocated string containing the last component of the filename.
References g_ascii_isalpha, G_DIR_SEPARATOR_S, G_IS_DIR_SEPARATOR, g_malloc(), g_return_val_if_fail, g_strdup(), gchar, and NULL.
gchar* g_path_get_dirname (const gchar * file_name)
gboolean g_path_is_absolute (const gchar * file_name)
G_CONST_RETURN gchar* g_path_skip_root (const gchar * file_name)
void g_reload_user_special_dirs_cache (void)
void g_set_application_name (const gchar * application_name)
void g_set_prgname (const gchar * prgname)
g_set_prgname: : the name of the program.
Sets the name of the program. This name should <emphasis>not</emphasis> be localized, contrast with g_set_application_name(). Note that for thread-safety reasons this function can only be called once.
References g_free(), G_LOCK, g_strdup(), and G_UNLOCK.
gboolean g_setenv (const gchar * variable, const gchar * value, gboolean overwrite)
gint g_snprintf (gchar * string, gulong n, gchar const * format, ...)
G_INLINE_FUNC guint g_trash_stack_height (GTrashStack ** stack_p)
G_INLINE_FUNC gpointer g_trash_stack_peek (GTrashStack ** stack_p)
G_INLINE_FUNC gpointer g_trash_stack_pop (GTrashStack ** stack_p)
Referenced by allocator_memalign().
G_INLINE_FUNC void g_trash_stack_push (GTrashStack ** stack_p, gpointer data_p)
Referenced by allocator_memalign(), and allocator_memfree().
void g_unsetenv (const gchar * variable)
gint gint g_vsnprintf (gchar * string, gulong n, gchar const * format, va_list args)
g_vsnprintf: : the buffer to hold the output.
: the maximum number of bytes to produce (including the terminating nul character). : a standard printf() format string, but notice <link linkend="string-precision">string precision pitfalls</link>. : the list of arguments to insert in the output.
A safer form of the standard vsprintf() function. The output is guaranteed to not exceed
characters (including the terminating nul character), so it is easy to ensure that a buffer overflow cannot occur.
See also g_strdup_vprintf().
In versions of GLib prior to 1.2.3, this function may return -1 if the output was truncated, and the truncated string may not be nul-terminated. In versions prior to 1.3.12, this function returns the length of the output string.
The return value of g_vsnprintf() conforms to the vsnprintf() function as standardized in ISO C99. Note that this is different from traditional vsnprintf(), which returns the length of the output string.
The format string may contain positional parameters, as specified in the Single Unix Specification.
Returns: the number of bytes which would be produced if the buffer was large enough.
References _g_vsnprintf, g_return_val_if_fail, and NULL.
Referenced by ezxml_err(), g_snprintf(), and log_printf().
const gchar* glib_check_version (guint required_major, guint required_minor, guint required_micro)
Variable Documentation
GLIB_VAR const guint glib_binary_age
GLIB_VAR const guint glib_interface_age
GLIB_VAR const guint glib_major_version
GLIB_VAR const guint glib_micro_version
GLIB_VAR const guint glib_minor_version