navit: support/glib/gutils.c File Reference
gutils.c File Reference
#include "config.h"
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <locale.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include "glib.h"
#include "gprintfint.h"
#include "gthreadprivate.h"
#include "glibintl.h"
#include "galias.h"
#include "galiasdef.c"
Macros
#define G_IMPLEMENT_INLINES 1
#define __G_UTILS_C__
#define G_PATH_LENGTH 2048
#define __G_UTILS_C__
Functions
gchar * g_path_get_basename (const gchar *file_name)
G_LOCK_DEFINE_STATIC (g_prgname)
gchar * g_get_prgname (void)
void g_set_prgname (const gchar *prgname)
guint g_direct_hash (gconstpointer v)
gboolean g_direct_equal (gconstpointer v1, gconstpointer v2)
gboolean g_int_equal (gconstpointer v1, gconstpointer v2)
guint g_int_hash (gconstpointer v)
Variables
static gchar * g_prgname = NULL
Macro Definition Documentation
#define __G_UTILS_C__
#define __G_UTILS_C__
#define G_IMPLEMENT_INLINES 1
#define G_PATH_LENGTH 2048
Function Documentation
gboolean g_direct_equal (gconstpointer v1, gconstpointer v2)
g_direct_equal: : a key. : a key to compare with .
Compares two gpointer arguments and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using pointers as keys in a GHashTable.
Returns: TRUE if the two keys match.
guint g_direct_hash (gconstpointer v)
g_direct_hash: : a gpointer key
Converts a gpointer to a hash value. It can be passed to g_hash_table_new() as the parameter, when using pointers as keys in a GHashTable.
Returns: a hash value corresponding to the key.
References GPOINTER_TO_UINT.
Referenced by g_hash_table_new_full(), item_hash_hash(), and search_item_hash_hash().
gchar* g_get_prgname (void)
g_get_prgname:
Gets the name of the program. This name should <emphasis>not</emphasis> be localized, contrast with g_get_application_name(). (If you are using GDK or GTK+ the program name is set in gdk_init(), which is called by gtk_init(). The program name is found by taking the last component of <literal>argv[0]</literal>.)
Returns: the name of the program. The returned string belongs to GLib and must not be modified or freed.
References gchar, and NULL.
Referenced by mem_error().
gboolean g_int_equal (gconstpointer v1, gconstpointer v2)
g_int_equal: : a pointer to a gint key. : a pointer to a gint key to compare with .
Compares the two gint values being pointed to and returns TRUE if they are equal. It can be passed to g_hash_table_new() as the parameter, when using pointers to integers as keys in a GHashTable.
Returns: TRUE if the two keys match.
Referenced by map_new_csv(), and map_rect_new_mg().
guint g_int_hash (gconstpointer v)
g_int_hash: : a pointer to a gint key
Converts a pointer to a gint to a hash value. It can be passed to g_hash_table_new() as the parameter, when using pointers to integers values as keys in a GHashTable.
Returns: a hash value corresponding to the key.
Referenced by map_new_csv(), and map_rect_new_mg().
G_LOCK_DEFINE_STATIC (g_prgname)
gchar* g_path_get_basename (const gchar * file_name)
g_path_get_basename: : the name of the file.
Gets the last component of the filename. If ends with a directory separator it gets the component before the last slash. If consists only of directory separators (and on Windows, possibly a drive letter), a single separator is returned. If is empty, it gets ".".
Return value: a newly allocated string containing the last component of the filename.
References g_ascii_isalpha, G_DIR_SEPARATOR_S, G_IS_DIR_SEPARATOR, g_malloc(), g_return_val_if_fail, g_strdup(), gchar, and NULL.
void g_set_prgname (const gchar * prgname)
g_set_prgname: : the name of the program.
Sets the name of the program. This name should <emphasis>not</emphasis> be localized, contrast with g_set_application_name(). Note that for thread-safety reasons this function can only be called once.
References g_free(), G_LOCK, g_strdup(), and G_UNLOCK.
Variable Documentation
gchar* g_prgname = NULL static