navit: NavitTimer Class Reference
NavitTimer Class Reference
Instance Methods
(void) - onTimer:
Data Fields
struct callback * cb
NSTimer * timer
Method Documentation
onTimer:
- (void) onTimer: (NSTimer*) theTimer
Field Documentation
cb
- (struct callback*) cb
Referenced by event_cocoa_add_idle(), and event_cocoa_add_timeout().
timer
- (NSTimer*) timer
Referenced by event_cocoa_add_idle(), and event_cocoa_add_timeout().
The documentation for this class was generated from the following file:
graphics/cocoa/graphics_cocoa.m