navit: support/espeak/intonation.c File Reference
intonation.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <string.h>
#include <wctype.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Data Structures
struct SYLLABLE
struct TONE_HEAD
struct TONE_NUCLEUS
Macros
#define SYL_RISE 1
#define SYL_EMPHASIS 2
#define SYL_END_CLAUSE 4
#define PITCHfall 0
#define PITCHrise 1
#define PITCHfrise 2
#define PITCHfrise2 4
#define PITCHrisefall 6
#define N_TONE_HEAD_TABLE 13
#define N_TONE_NUCLEUS_TABLE 13
#define T_EMPH 1
#define SECONDARY 3
#define PRIMARY 4
#define PRIMARY_STRESSED 6
#define PRIMARY_LAST 7
Functions
static void count_pitch_vowels (int start, int end, int clause_end)
static int count_increments (int ix, int end_ix, int min_stress)
static void set_pitch (SYLLABLE *syl, int base, int drop)
static int calc_pitch_segment (int ix, int end_ix, TONE_HEAD *th, TONE_NUCLEUS *tn, int min_stress, int continuing)
static int calc_pitch_segment2 (int ix, int end_ix, int start_p, int end_p, int min_stress)
static int calc_pitches (int start, int end, int head_tone, int nucleus_tone)
static void CalcPitches_Tone (Translator *tr, int clause_tone)
void CalcPitches (Translator *tr, int clause_type)
Variables
static SYLLABLE * syllable_tab
static int tone_pitch_env
unsigned char env_fall [128]
unsigned char env_rise [128]
unsigned char env_frise [128]
static unsigned char env_r_frise [128]
static unsigned char env_frise2 [128]
static unsigned char env_r_frise2 [128]
static unsigned char env_risefall [128]
static unsigned char env_rise2 [128]
static unsigned char env_fall2 [128]
static unsigned char env_fallrise3 [128]
static unsigned char env_fallrise4 [128]
static unsigned char env_risefallrise [128]
unsigned char * envelope_data [18]
static int drops_0 [8] = {0x400,0x400,0x700,0x700,0x700,0xa00,0x1800,0x0e00}
static short oflow [] = {0, 20, 12, 4, 0}
static short oflow_emf [] = {5, 24, 15, 10, 5}
static short oflow_less [] = {3, 19, 12, 7, 2}
static TONE_HEAD tone_head_table [N_TONE_HEAD_TABLE]
static TONE_NUCLEUS tone_nucleus_table [N_TONE_NUCLEUS_TABLE]
unsigned char punctuation_to_tone [INTONATION_TYPES][PUNCT_INTONATIONS]
static int min_drop [] = {0x300,0x300,0x400,0x400,0x900,0x900,0x900,0xb00}
static int number_pre
static int number_body
static int number_tail
static int last_primary
static int tone_posn
static int tone_posn2
static int no_tonic
Macro Definition Documentation
#define N_TONE_HEAD_TABLE 13
#define N_TONE_NUCLEUS_TABLE 13
#define PITCHfall 0
Referenced by CalcLengths(), CalcPitches(), DoPitch(), and MakePhonemeList().
#define PITCHfrise 2
#define PITCHfrise2 4
#define PITCHrise 1
Referenced by CalcLengths(), and CalcPitches().
#define PITCHrisefall 6
#define PRIMARY 4
Referenced by calc_pitch_segment(), calc_pitches(), and count_pitch_vowels().
#define PRIMARY_LAST 7
Referenced by count_increments(), and count_pitch_vowels().
#define PRIMARY_STRESSED 6
Referenced by calc_pitch_segment(), and calc_pitches().
#define SECONDARY 3
Referenced by calc_pitch_segment().
#define SYL_EMPHASIS 2
Referenced by calc_pitches(), and CalcPitches().
#define SYL_END_CLAUSE 4
Referenced by CalcPitches().
#define SYL_RISE 1
Referenced by CalcPitches(), and set_pitch().
#define T_EMPH 1
Referenced by calc_pitches().
Function Documentation
static int calc_pitch_segment (int ix, int end_ix, TONE_HEAD * th, TONE_NUCLEUS * tn, int min_stress, int continuing) static
References TONE_NUCLEUS::backwards, TONE_HEAD::body_drops, TONE_HEAD::body_end, TONE_HEAD::body_lower_u, TONE_HEAD::body_max_steps, TONE_HEAD::body_start, count_increments(), TONE_HEAD::n_overflow, TONE_HEAD::overflow, PRIMARY, PRIMARY_STRESSED, SECONDARY, set_pitch(), and SYLLABLE::stress.
Referenced by calc_pitches().
static int calc_pitch_segment2 (int ix, int end_ix, int start_p, int end_p, int min_stress) static
References count_increments(), min_drop, set_pitch(), and SYLLABLE::stress.
Referenced by calc_pitches().
static int calc_pitches (int start, int end, int head_tone, int nucleus_tone) static
References calc_pitch_segment(), calc_pitch_segment2(), SYLLABLE::env, SYLLABLE::flags, TONE_NUCLEUS::flags, no_tonic, number_pre, number_tail, OPTION_EMPHASIZE_PENULTIMATE, option_tone_flags, TONE_NUCLEUS::pitch_env0, TONE_NUCLEUS::pitch_env1, TONE_HEAD::pre_end, TONE_HEAD::pre_start, PRIMARY, PRIMARY_STRESSED, set_pitch(), start, SYLLABLE::stress, SYL_EMPHASIS, T_EMPH, TONE_NUCLEUS::tail_end, TONE_NUCLEUS::tail_start, tone_pitch_env, tone_posn, tone_posn2, TONE_NUCLEUS::tonic_max0, TONE_NUCLEUS::tonic_max1, TONE_NUCLEUS::tonic_min0, and TONE_NUCLEUS::tonic_min1.
Referenced by CalcPitches().
void CalcPitches (Translator * tr, int clause_type)
References calc_pitches(), CalcPitches_Tone(), PHONEME_TAB::code, count_pitch_vowels(), PHONEME_TAB::end_type, SYLLABLE::env, PHONEME_LIST::env, SYLLABLE::flags, LANGUAGE_OPTIONS::intonation_group, INTONATION_TYPES, Translator::langopts, N_PHONEME_LIST, n_phoneme_list, SYLLABLE::nextph_type, no_tonic, p, PHONEME_LIST::ph, phoneme_list, phoneme_tab, phonPAUSE_CLAUSE, SYLLABLE::pitch1, PHONEME_LIST::pitch1, SYLLABLE::pitch2, PHONEME_LIST::pitch2, PITCHfall, PITCHrise, Translator::punct_to_tone, SFLAG_SYLLABLE, PHONEME_TAB::start_type, SYLLABLE::stress, PHONEME_LIST::stresslevel, SYL_EMPHASIS, SYL_END_CLAUSE, SYL_RISE, PHONEME_LIST::synthflags, LANGUAGE_OPTIONS::tone_language, PHONEME_LIST::tone_ph, and PHONEME_LIST::type.
Referenced by SpeakNextClause().
static void CalcPitches_Tone (Translator * tr, int clause_tone) static
References PHONEME_TAB::end_type, L, PHONEME_TAB::mnemonic, n_phoneme_list, PHONEME_LIST::newword, p, PHONEME_LIST::ph, phonDEFAULTTONE, phoneme_list, phoneme_tab, PhonemeCode(), PhonemeCode2, phonPAUSE, phPAUSE, phVOWEL, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, SFLAG_SYLLABLE, PHONEME_TAB::start_type, PHONEME_TAB::std_length, PHONEME_LIST::stresslevel, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, Translator::translator_name, and PHONEME_LIST::type.
Referenced by CalcPitches().
static int count_increments (int ix, int end_ix, int min_stress) static
References PRIMARY_LAST, and SYLLABLE::stress.
Referenced by calc_pitch_segment(), and calc_pitch_segment2().
static void count_pitch_vowels (int start, int end, int clause_end) static
References last_primary, no_tonic, number_body, number_pre, number_tail, PRIMARY, PRIMARY_LAST, start, SYLLABLE::stress, tone_posn, and tone_posn2.
Referenced by CalcPitches().
static void set_pitch (SYLLABLE * syl, int base, int drop) static
References SYLLABLE::flags, SYLLABLE::pitch1, SYLLABLE::pitch2, and SYL_RISE.
Referenced by calc_pitch_segment(), calc_pitch_segment2(), and calc_pitches().
Variable Documentation
int drops_0[8] = {0x400,0x400,0x700,0x700,0x700,0xa00,0x1800,0x0e00} static
unsigned char env_fall[128]
Initial value:
= {
 0xff, 0xfd, 0xfa, 0xf8, 0xf6, 0xf4, 0xf2, 0xf0, 0xee, 0xec, 0xea, 0xe8, 0xe6, 0xe4, 0xe2, 0xe0,
 0xde, 0xdc, 0xda, 0xd8, 0xd6, 0xd4, 0xd2, 0xd0, 0xce, 0xcc, 0xca, 0xc8, 0xc6, 0xc4, 0xc2, 0xc0,
 0xbe, 0xbc, 0xba, 0xb8, 0xb6, 0xb4, 0xb2, 0xb0, 0xae, 0xac, 0xaa, 0xa8, 0xa6, 0xa4, 0xa2, 0xa0,
 0x9e, 0x9c, 0x9a, 0x98, 0x96, 0x94, 0x92, 0x90, 0x8e, 0x8c, 0x8a, 0x88, 0x86, 0x84, 0x82, 0x80,
 0x7e, 0x7c, 0x7a, 0x78, 0x76, 0x74, 0x72, 0x70, 0x6e, 0x6c, 0x6a, 0x68, 0x66, 0x64, 0x62, 0x60,
 0x5e, 0x5c, 0x5a, 0x58, 0x56, 0x54, 0x52, 0x50, 0x4e, 0x4c, 0x4a, 0x48, 0x46, 0x44, 0x42, 0x40,
 0x3e, 0x3c, 0x3a, 0x38, 0x36, 0x34, 0x32, 0x30, 0x2e, 0x2c, 0x2a, 0x28, 0x26, 0x24, 0x22, 0x20,
 0x1e, 0x1c, 0x1a, 0x18, 0x16, 0x14, 0x12, 0x10, 0x0e, 0x0c, 0x0a, 0x08, 0x06, 0x04, 0x02, 0x00 }
Referenced by SetPitch().
unsigned char env_fall2[128] static
Initial value:
= {
 0xfe, 0xfe, 0xfd, 0xfd, 0xfc, 0xfb, 0xfb, 0xfa, 0xfa, 0xf9, 0xf8, 0xf8, 0xf7, 0xf7, 0xf6, 0xf6,
 0xf5, 0xf4, 0xf4, 0xf3, 0xf3, 0xf2, 0xf2, 0xf1, 0xf0, 0xf0, 0xef, 0xee, 0xee, 0xed, 0xec, 0xeb,
 0xea, 0xea, 0xe9, 0xe8, 0xe7, 0xe6, 0xe5, 0xe4, 0xe3, 0xe2, 0xe1, 0xe0, 0xde, 0xdd, 0xdc, 0xdb,
 0xd9, 0xd8, 0xd6, 0xd5, 0xd3, 0xd2, 0xd0, 0xce, 0xcc, 0xcb, 0xc9, 0xc7, 0xc5, 0xc3, 0xc0, 0xbe,
 0xbc, 0xb9, 0xb7, 0xb5, 0xb2, 0xaf, 0xad, 0xaa, 0xa7, 0xa4, 0xa1, 0x9e, 0x9a, 0x97, 0x94, 0x90,
 0x8d, 0x89, 0x85, 0x81, 0x7d, 0x79, 0x75, 0x71, 0x6d, 0x68, 0x64, 0x61, 0x5e, 0x5b, 0x57, 0x54,
 0x51, 0x4d, 0x4a, 0x46, 0x43, 0x40, 0x3c, 0x39, 0x35, 0x32, 0x2e, 0x2a, 0x27, 0x23, 0x1f, 0x1c,
 0x18, 0x14, 0x11, 0x0d, 0x0b, 0x09, 0x07, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00 }
unsigned char env_fallrise3[128] static
Initial value:
= {
 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0xfd, 0xfc, 0xfa, 0xf8, 0xf6, 0xf4, 0xf1, 0xee, 0xeb,
 0xe8, 0xe5, 0xe1, 0xde, 0xda, 0xd6, 0xd2, 0xcd, 0xc9, 0xc4, 0xbf, 0xba, 0xb6, 0xb0, 0xab, 0xa6,
 0xa1, 0x9c, 0x96, 0x91, 0x8b, 0x86, 0x80, 0x7b, 0x75, 0x6f, 0x6a, 0x64, 0x5f, 0x59, 0x54, 0x4f,
 0x49, 0x44, 0x3f, 0x3a, 0x35, 0x30, 0x2b, 0x26, 0x22, 0x1d, 0x19, 0x15, 0x11, 0x0d, 0x0a, 0x07,
 0x04, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x04, 0x05,
 0x07, 0x09, 0x0b, 0x0d, 0x10, 0x12, 0x15, 0x18, 0x1b, 0x1e, 0x22, 0x25, 0x29, 0x2d, 0x31, 0x35,
 0x3a, 0x3e, 0x43, 0x48, 0x4c, 0x51, 0x57, 0x5b, 0x5e, 0x62, 0x65, 0x68, 0x6b, 0x6e, 0x71, 0x74,
 0x76, 0x78, 0x7b, 0x7c, 0x7e, 0x80, 0x81, 0x82, 0x83, 0x83, 0x84, 0x84, 0x83, 0x83, 0x82, 0x81 }
unsigned char env_fallrise4[128] static
Initial value:
= {
 0x72, 0x72, 0x71, 0x71, 0x70, 0x6f, 0x6d, 0x6c, 0x6a, 0x68, 0x66, 0x64, 0x61, 0x5f, 0x5c, 0x5a,
 0x57, 0x54, 0x51, 0x4e, 0x4b, 0x48, 0x45, 0x42, 0x3f, 0x3b, 0x38, 0x35, 0x32, 0x2f, 0x2c, 0x29,
 0x26, 0x23, 0x20, 0x1d, 0x1b, 0x18, 0x16, 0x14, 0x12, 0x10, 0x0e, 0x0c, 0x0b, 0x0a, 0x09, 0x08,
 0x07, 0x07, 0x07, 0x07, 0x07, 0x06, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x05, 0x06,
 0x07, 0x07, 0x08, 0x09, 0x0a, 0x0c, 0x0d, 0x0f, 0x10, 0x12, 0x14, 0x16, 0x18, 0x1b, 0x1d, 0x20,
 0x23, 0x26, 0x29, 0x2c, 0x2f, 0x33, 0x37, 0x3b, 0x3f, 0x43, 0x47, 0x4c, 0x51, 0x56, 0x5b, 0x60,
 0x65, 0x6a, 0x6f, 0x74, 0x79, 0x7f, 0x84, 0x89, 0x8f, 0x95, 0x9b, 0xa1, 0xa7, 0xad, 0xb3, 0xba,
 0xc0, 0xc7, 0xce, 0xd5, 0xdc, 0xe3, 0xea, 0xf1, 0xf5, 0xf7, 0xfa, 0xfc, 0xfd, 0xfe, 0xff, 0xff }
unsigned char env_frise[128]
Initial value:
= {
 0xff, 0xf4, 0xea, 0xe0, 0xd6, 0xcc, 0xc3, 0xba, 0xb1, 0xa8, 0x9f, 0x97, 0x8f, 0x87, 0x7f, 0x78,
 0x71, 0x6a, 0x63, 0x5c, 0x56, 0x50, 0x4a, 0x44, 0x3f, 0x39, 0x34, 0x2f, 0x2b, 0x26, 0x22, 0x1e,
 0x1a, 0x17, 0x13, 0x10, 0x0d, 0x0b, 0x08, 0x06, 0x04, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x07, 0x08, 0x0a, 0x0c, 0x0e, 0x10, 0x13, 0x15, 0x17,
 0x1a, 0x1d, 0x1f, 0x22, 0x25, 0x28, 0x2c, 0x2e, 0x30, 0x32, 0x34, 0x36, 0x39, 0x3b, 0x3d, 0x40,
 0x42, 0x45, 0x47, 0x4a, 0x4c, 0x4f, 0x51, 0x54, 0x57, 0x5a, 0x5d, 0x5f, 0x62, 0x65, 0x68, 0x6b,
 0x6e, 0x71, 0x74, 0x78, 0x7b, 0x7e, 0x81, 0x85, 0x88, 0x8b, 0x8f, 0x92, 0x96, 0x99, 0x9d, 0xa0,
 0xa4, 0xa8, 0xac, 0xaf, 0xb3, 0xb7, 0xbb, 0xbf, 0xc3, 0xc7, 0xcb, 0xcf, 0xd3, 0xd7, 0xdb, 0xe0 }
unsigned char env_frise2[128] static
Initial value:
= {
 0xff, 0xf9, 0xf4, 0xee, 0xe9, 0xe4, 0xdf, 0xda, 0xd5, 0xd0, 0xcb, 0xc6, 0xc1, 0xbd, 0xb8, 0xb3,
 0xaf, 0xaa, 0xa6, 0xa1, 0x9d, 0x99, 0x95, 0x90, 0x8c, 0x88, 0x84, 0x80, 0x7d, 0x79, 0x75, 0x71,
 0x6e, 0x6a, 0x67, 0x63, 0x60, 0x5d, 0x59, 0x56, 0x53, 0x50, 0x4d, 0x4a, 0x47, 0x44, 0x41, 0x3e,
 0x3c, 0x39, 0x37, 0x34, 0x32, 0x2f, 0x2d, 0x2b, 0x28, 0x26, 0x24, 0x22, 0x20, 0x1e, 0x1c, 0x1a,
 0x19, 0x17, 0x15, 0x14, 0x12, 0x11, 0x0f, 0x0e, 0x0d, 0x0c, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05,
 0x05, 0x04, 0x03, 0x02, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x02, 0x03, 0x04, 0x04, 0x05, 0x06, 0x07, 0x08,
 0x09, 0x0a, 0x0b, 0x0c, 0x0e, 0x0f, 0x10, 0x12, 0x13, 0x15, 0x17, 0x18, 0x1a, 0x1c, 0x1e, 0x20 }
unsigned char env_r_frise[128] static
Initial value:
= {
 0xcf, 0xcc, 0xc9, 0xc6, 0xc3, 0xc0, 0xbd, 0xb9, 0xb4, 0xb0, 0xab, 0xa7, 0xa2, 0x9c, 0x97, 0x92,
 0x8c, 0x86, 0x81, 0x7b, 0x75, 0x6f, 0x69, 0x63, 0x5d, 0x57, 0x50, 0x4a, 0x44, 0x3e, 0x38, 0x33,
 0x2d, 0x27, 0x22, 0x1c, 0x17, 0x12, 0x0d, 0x08, 0x04, 0x02, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00,
 0x00, 0x01, 0x01, 0x02, 0x03, 0x04, 0x05, 0x07, 0x08, 0x0a, 0x0c, 0x0d, 0x0f, 0x12, 0x14, 0x16,
 0x19, 0x1b, 0x1e, 0x21, 0x24, 0x27, 0x2a, 0x2d, 0x30, 0x34, 0x36, 0x38, 0x3a, 0x3c, 0x3f, 0x41,
 0x43, 0x46, 0x48, 0x4b, 0x4d, 0x50, 0x52, 0x55, 0x58, 0x5a, 0x5d, 0x60, 0x63, 0x66, 0x69, 0x6c,
 0x6f, 0x72, 0x75, 0x78, 0x7b, 0x7e, 0x81, 0x85, 0x88, 0x8b, 0x8f, 0x92, 0x96, 0x99, 0x9d, 0xa0,
 0xa4, 0xa8, 0xac, 0xaf, 0xb3, 0xb7, 0xbb, 0xbf, 0xc3, 0xc7, 0xcb, 0xcf, 0xd3, 0xd7, 0xdb, 0xe0 }
unsigned char env_r_frise2[128] static
Initial value:
= {
 0xd0, 0xce, 0xcd, 0xcc, 0xca, 0xc8, 0xc7, 0xc5, 0xc3, 0xc1, 0xc0, 0xbd, 0xbb, 0xb8, 0xb5, 0xb3,
 0xb0, 0xad, 0xaa, 0xa7, 0xa3, 0xa0, 0x9d, 0x99, 0x96, 0x92, 0x8f, 0x8b, 0x87, 0x84, 0x80, 0x7c,
 0x78, 0x74, 0x70, 0x6d, 0x69, 0x65, 0x61, 0x5d, 0x59, 0x55, 0x51, 0x4d, 0x4a, 0x46, 0x42, 0x3e,
 0x3b, 0x37, 0x34, 0x31, 0x2f, 0x2d, 0x2a, 0x28, 0x26, 0x24, 0x22, 0x20, 0x1e, 0x1c, 0x1a, 0x19,
 0x17, 0x15, 0x14, 0x12, 0x11, 0x0f, 0x0e, 0x0d, 0x0c, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05, 0x05,
 0x04, 0x03, 0x02, 0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x02, 0x02, 0x03, 0x04, 0x04, 0x05, 0x06, 0x07, 0x08,
 0x09, 0x0a, 0x0b, 0x0c, 0x0e, 0x0f, 0x10, 0x12, 0x13, 0x15, 0x17, 0x18, 0x1a, 0x1c, 0x1e, 0x20 }
unsigned char env_rise[128]
Initial value:
= {
 0x00, 0x02, 0x04, 0x06, 0x08, 0x0a, 0x0c, 0x0e, 0x10, 0x12, 0x14, 0x16, 0x18, 0x1a, 0x1c, 0x1e,
 0x20, 0x22, 0x24, 0x26, 0x28, 0x2a, 0x2c, 0x2e, 0x30, 0x32, 0x34, 0x36, 0x38, 0x3a, 0x3c, 0x3e,
 0x40, 0x42, 0x44, 0x46, 0x48, 0x4a, 0x4c, 0x4e, 0x50, 0x52, 0x54, 0x56, 0x58, 0x5a, 0x5c, 0x5e,
 0x60, 0x62, 0x64, 0x66, 0x68, 0x6a, 0x6c, 0x6e, 0x70, 0x72, 0x74, 0x76, 0x78, 0x7a, 0x7c, 0x7e,
 0x80, 0x82, 0x84, 0x86, 0x88, 0x8a, 0x8c, 0x8e, 0x90, 0x92, 0x94, 0x96, 0x98, 0x9a, 0x9c, 0x9e,
 0xa0, 0xa2, 0xa4, 0xa6, 0xa8, 0xaa, 0xac, 0xae, 0xb0, 0xb2, 0xb4, 0xb6, 0xb8, 0xba, 0xbc, 0xbe,
 0xc0, 0xc2, 0xc4, 0xc6, 0xc8, 0xca, 0xcc, 0xce, 0xd0, 0xd2, 0xd4, 0xd6, 0xd8, 0xda, 0xdc, 0xde,
 0xe0, 0xe2, 0xe4, 0xe6, 0xe8, 0xea, 0xec, 0xee, 0xf0, 0xf2, 0xf4, 0xf6, 0xf8, 0xfa, 0xfd, 0xff }
unsigned char env_rise2[128] static
Initial value:
= {
 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x02, 0x02, 0x03, 0x03, 0x04, 0x04, 0x05, 0x06, 0x06,
 0x07, 0x08, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14,
 0x16, 0x17, 0x18, 0x19, 0x1b, 0x1c, 0x1d, 0x1f, 0x20, 0x22, 0x23, 0x25, 0x26, 0x28, 0x29, 0x2b,
 0x2d, 0x2f, 0x30, 0x32, 0x34, 0x36, 0x38, 0x3a, 0x3c, 0x3e, 0x40, 0x42, 0x44, 0x47, 0x49, 0x4b,
 0x4e, 0x50, 0x52, 0x55, 0x57, 0x5a, 0x5d, 0x5f, 0x62, 0x65, 0x67, 0x6a, 0x6d, 0x70, 0x73, 0x76,
 0x79, 0x7c, 0x7f, 0x82, 0x86, 0x89, 0x8c, 0x90, 0x93, 0x96, 0x9a, 0x9d, 0xa0, 0xa3, 0xa6, 0xa9,
 0xac, 0xaf, 0xb2, 0xb5, 0xb8, 0xbb, 0xbe, 0xc1, 0xc4, 0xc7, 0xca, 0xcd, 0xd0, 0xd3, 0xd6, 0xd9,
 0xdc, 0xdf, 0xe2, 0xe4, 0xe7, 0xe9, 0xec, 0xee, 0xf0, 0xf2, 0xf4, 0xf6, 0xf8, 0xfa, 0xfb, 0xfd }
unsigned char env_risefall[128] static
Initial value:
= {
 0x98, 0x99, 0x99, 0x9a, 0x9c, 0x9d, 0x9f, 0xa1, 0xa4, 0xa7, 0xa9, 0xac, 0xb0, 0xb3, 0xb6, 0xba,
 0xbe, 0xc1, 0xc5, 0xc9, 0xcd, 0xd1, 0xd4, 0xd8, 0xdc, 0xdf, 0xe3, 0xe6, 0xea, 0xed, 0xf0, 0xf2,
 0xf5, 0xf7, 0xf9, 0xfb, 0xfc, 0xfd, 0xfe, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, 0xfd,
 0xfb, 0xfa, 0xf8, 0xf6, 0xf3, 0xf1, 0xee, 0xec, 0xe9, 0xe6, 0xe4, 0xe0, 0xdd, 0xda, 0xd7, 0xd3,
 0xd0, 0xcc, 0xc8, 0xc4, 0xc0, 0xbc, 0xb8, 0xb4, 0xb0, 0xac, 0xa7, 0xa3, 0x9f, 0x9a, 0x96, 0x91,
 0x8d, 0x88, 0x84, 0x7f, 0x7b, 0x76, 0x72, 0x6d, 0x69, 0x65, 0x60, 0x5c, 0x58, 0x54, 0x50, 0x4c,
 0x48, 0x44, 0x40, 0x3c, 0x39, 0x35, 0x32, 0x2f, 0x2b, 0x28, 0x26, 0x23, 0x20, 0x1d, 0x1a, 0x17,
 0x15, 0x12, 0x0f, 0x0d, 0x0a, 0x08, 0x07, 0x05, 0x03, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00 }
unsigned char env_risefallrise[128] static
Initial value:
= {
 0x7f, 0x7f, 0x7f, 0x80, 0x81, 0x83, 0x84, 0x87, 0x89, 0x8c, 0x8f, 0x92, 0x96, 0x99, 0x9d, 0xa1,
 0xa5, 0xaa, 0xae, 0xb2, 0xb7, 0xbb, 0xc0, 0xc5, 0xc9, 0xcd, 0xd2, 0xd6, 0xda, 0xde, 0xe2, 0xe6,
 0xea, 0xed, 0xf0, 0xf3, 0xf5, 0xf8, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xfe, 0xfd, 0xfc, 0xfb, 0xf9,
 0xf7, 0xf4, 0xf0, 0xec, 0xe7, 0xe2, 0xdc, 0xd5, 0xce, 0xc6, 0xbd, 0xb4, 0xa9, 0x9e, 0x92, 0x88,
 0x82, 0x7d, 0x77, 0x72, 0x6c, 0x66, 0x60, 0x5a, 0x54, 0x4e, 0x49, 0x42, 0x3c, 0x37, 0x32, 0x2d,
 0x28, 0x24, 0x1f, 0x1b, 0x18, 0x14, 0x11, 0x0e, 0x0c, 0x09, 0x07, 0x06, 0x05, 0x04, 0x04, 0x04,
 0x04, 0x05, 0x06, 0x08, 0x0a, 0x0d, 0x10, 0x14, 0x18, 0x1d, 0x23, 0x29, 0x2f, 0x37, 0x3e, 0x47,
 0x50, 0x5a, 0x64, 0x70, 0x7c, 0x83, 0x85, 0x88, 0x8a, 0x8c, 0x8e, 0x8f, 0x91, 0x92, 0x93, 0x93 }
unsigned char* envelope_data[18]
Initial value:
= {
        env_fall,
        env_rise,
        env_frise,  env_r_frise,
        env_frise2, env_r_frise2,
        env_risefall, env_risefall,
        env_fallrise3, env_fallrise3,
        env_fallrise4, env_fallrise4,
        env_fall2, env_fall2,
        env_rise2, env_rise2,
        env_risefallrise, env_risefallrise
 }
Referenced by CalcLengths(), DoPitch(), Generate(), and WritePitch().
int last_primary static
Referenced by count_pitch_vowels().
int min_drop[] = {0x300,0x300,0x400,0x400,0x900,0x900,0x900,0xb00} static
Referenced by calc_pitch_segment2(), and CalcLengths().
int no_tonic static
Referenced by calc_pitches(), CalcPitches(), and count_pitch_vowels().
int number_body static
Referenced by count_pitch_vowels().
int number_pre static
Referenced by calc_pitches(), and count_pitch_vowels().
int number_tail static
Referenced by calc_pitches(), and count_pitch_vowels().
short oflow[] = {0, 20, 12, 4, 0} static
short oflow_emf[] = {5, 24, 15, 10, 5} static
short oflow_less[] = {3, 19, 12, 7, 2} static
unsigned char punctuation_to_tone[INTONATION_TYPES][PUNCT_INTONATIONS]
Initial value:
= {
        {0,1,2,3,0,4},
        {0,1,2,3,0,4},
        {5,6,2,3,0,4},
        {5,7,1,3,0,4},
        {8,9,10,3,0,0},
        {8,8,10,3,0,0},
        {11,11,11,11,0,0},
        {12,12,12,12,0,0}
}
Referenced by NewTranslator().
SYLLABLE* syllable_tab static
TONE_HEAD tone_head_table[N_TONE_HEAD_TABLE] static
Initial value:
= {
   {20, 25,   34, 22,  drops_0, 3, 3,   5, oflow},
   {20, 25,   34, 20,  drops_0, 3, 3,   5, oflow},
   {20, 25,   34, 20,  drops_0, 3, 3,   5, oflow},
   {20, 25,   36, 22,  drops_0, 3, 4,   5, oflow_emf},
   {20, 25,   34, 22,  drops_0, 3, 3,   5, oflow},
   {20, 25,   32, 24,  drops_0, 4, 3,   5, oflow_less},
   {20, 25,   32, 24,  drops_0, 4, 3,   5, oflow_less},
   {20, 25,   32, 24,  drops_0, 4, 3,   5, oflow_less},
   {20, 25,   34, 22,  drops_0, 3, 3,   5, oflow},
   {20, 25,   34, 20,  drops_0, 3, 3,   5, oflow},
   {20, 25,   34, 22,  drops_0, 3, 3,   5, oflow},
   {15, 18,   18, 14,  drops_0, 3, 3,   5, oflow_less},
   {20, 25,   24, 22,  drops_0, 3, 3,   5, oflow_less},
}
TONE_NUCLEUS tone_nucleus_table[N_TONE_NUCLEUS_TABLE] static
Initial value:
= {
   {PITCHfall,   30, 5,  PITCHfall,   32, 9, NULL, 12, 7, 0},
   {PITCHfrise,  35, 8,  PITCHfrise2, 35,10, NULL, 15, 23, 0},
   {PITCHfrise,  39,10,  PITCHfrise2, 36,10, NULL, 15, 28, 0},
   {PITCHfall,   41, 4,  PITCHfall,   41,35, NULL, 35, 4, T_EMPH},
   {PITCHfall,   38, 2,  PITCHfall,   42,30, NULL, 15, 5, 0},
   {PITCHfall,   28, 5,  PITCHfall,   28, 9, NULL, 12, 7, 0},
   {PITCHfrise,  30, 8,  PITCHfrise2, 30,10, NULL, 13, 20, 0},
   {PITCHfrise2, 28, 7,  PITCHfall,   29,14, NULL, 14, 8, 0},
   {PITCHrise,   30,20,  PITCHfall,   19,14, NULL, 20, 26, 0},
   {PITCHfrise,  35,11,  PITCHfrise2, 32,10, NULL, 19, 24, 0},
   {PITCHfrise,  39,15,  PITCHfall,   28,14, NULL, 20, 36, 0},
   {PITCHfall,   28, 6,  PITCHfall,   28,10, NULL, 12, 6, 0},
   {PITCHfall,   35, 9,  PITCHfall,   35,12, NULL, 16, 10, 0},
}
int tone_pitch_env static
Referenced by calc_pitches().
int tone_posn static
Referenced by calc_pitches(), and count_pitch_vowels().
int tone_posn2 static
Referenced by calc_pitches(), and count_pitch_vowels().