navit: item.c File Reference
item.c File Reference
#include <stdio.h>
#include <string.h>
#include <glib.h>
#include "coord.h"
#include "debug.h"
#include "item.h"
#include "map.h"
#include "transform.h"
#include "item_def.h"
Data Structures
struct item_name
struct default_flags
struct item_hash
Macros
#define ITEM2(x, y) ITEM(y)
#define ITEM(x) { type_##x, #x },
Functions
void item_create_hash (void)
void item_destroy_hash (void)
int * item_get_default_flags (enum item_type type)
void item_cleanup (void)
void item_coord_rewind (struct item *it)
Resets the "coordinate pointer" of an item.
int item_coord_get (struct item *it, struct coord *c, int count)
Gets the next coordinates from an item.
int item_coords_left (struct item *it)
Gets the number of coordinates left for this item.
int item_coord_set (struct item *it, struct coord *c, int count, enum change_mode mode)
Sets coordinates of an item.
int item_coord_get_within_selection (struct item *it, struct coord *c, int count, struct map_selection *sel)
Get coordinates within selection This function returns the coordinates of an item if at least one coordinate of that item is inside the selection. If the given buffer is too small, it returns the buffer size if at least one coordinate intersects with the selection, otherwise it returnes 0.
int item_coord_get_within_range (struct item *i, struct coord *c, int max, struct coord *start, struct coord *end)
Gets all the coordinates of an item within a specified range.
int item_coord_get_pro (struct item *it, struct coord *c, int count, enum projection to)
Gets the next coordinates from an item and reprojects them.
int item_coord_is_node (struct item *it)
Whether the current coordinates of an item correspond to a node.
void item_attr_rewind (struct item *it)
Resets the "attribute pointer" of an item.
int item_attr_get (struct item *it, enum attr_type attr_type, struct attr *attr)
Gets the next matching attribute from an item.
int item_attr_set (struct item *it, struct attr *attr, enum change_mode mode)
Sets an attribute of an item.
int item_type_set (struct item *it, enum item_type type)
Sets the type of a map item.
struct item * item_new (char *type, int zoom)
enum item_type item_from_name (const char *name)
char * item_to_name (enum item_type item)
static guint item_hash_hash (gconstpointer key)
static gboolean item_hash_equal (gconstpointer a, gconstpointer b)
unsigned int item_id_hash (const void *key)
int item_id_equal (const void *a, const void *b)
void item_id_from_ptr (struct item *item, void *id)
Derive item id_lo and id_hi from pointer, considering pointer could be 32 or 64 bit wide but both ids are 32 bit.
struct item_hash * item_hash_new (void)
void item_hash_insert (struct item_hash *h, struct item *item, void *val)
int item_hash_remove (struct item_hash *h, struct item *item)
void * item_hash_lookup (struct item_hash *h, struct item *item)
void item_hash_destroy (struct item_hash *h)
int item_range_intersects_range (struct item_range *range1, struct item_range *range2)
int item_range_contains_item (struct item_range *range, enum item_type type)
void item_dump_attr (struct item *item, struct map *map, FILE *out)
void item_dump_filedesc (struct item *item, struct map *map, FILE *out)
Variables
struct item_range item_range_all = { type_none, type_last }
struct item busy_item
An item indicating that the map driver is busy fetching more items.
struct default_flags default_flags2 []
struct item_name item_names []
static GHashTable * default_flags_hash
static GHashTable * item_hash
Macro Definition Documentation
ITEM
#define ITEM (x) { type_##x, #x },
ITEM2
#define ITEM2 (x, y) ITEM(y)
Function Documentation
item_attr_get()
int item_attr_get (struct item * it, enum attr_type attr_type attr_type , struct attr * attr)
Gets the next matching attribute from an item.
This function returns the next attribute matching attr_type from an item and advances the "attribute pointer" accordingly, so that at the next call the next attribute will be returned.
IMPORTANT: Unless you are iterating over attributes, or operating on a “fresh” item (from which no other code has had a chance to retrieve an attribute), be sure to call item_attr_rewind(struct item *) before each call to this method. Not doing so may result in unpredictable behavior, i.e. attributes not being found if the attribute pointer is already past the requested attribute (which depends on the physical ordering of attributes and on the last attribute retrieved from the item).
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
[in] it The map item whose attribute to retrieve. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
[in] attr_type The attribute type to retrieve, or attr_any to retrieve the next attribute
[out] attr Receives the attribute retrieved
Returns
True on success, false on failure
References item_methods::item_attr_get, item::meth, and item::priv_data.
Referenced by NGQPoint::_coordName(), NGQPoint::_setUrl(), binmap_search_by_index(), binmap_search_new(), binmap_search_street_by_place(), bookmarks_load_hash(), country_id_from_iso2(), destination_address(), display_add(), display_add_holes(), do_draw(), duplicate_test(), filter_type(), Backend::get_bookmarks(), get_icon(), Backend::get_pois(), NGQProxyBookmarks::getBookmarks(), NGQPoint::getInformation(), NGQPoint::getPOI(), graphics_process_selection_item(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_pois(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_position_do(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_show_satellite_status(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_compose_item_address_string(), gui_internal_dbus_signal(), gui_internal_poi_icon(), gui_internal_populate_route_table(), gui_internal_search_list_set_default_country(), gui_internal_select_waypoint(), gui_qml_dbus_signal(), housenumber_attr_get(), item_dump_attr(), item_get_heightline(), Java_org_navitproject_navit_NavitGraphics_getDefaultCountry(), map_filter_attr_get(), map_route_occluded_attr_get(), map_search_setup(), model_poi(), navigation_get_attr(), navigation_itm_new(), navigation_itm_update(), navigation_itm_ways_update(), navigation_update_idle(), navigation_way_init(), navit_speak(), navit_window_roadbook_update(), NGQProxySearch::NGQProxySearch(), osd_route_guard_init(), osd_speed_cam_draw(), osd_text_draw(), phase1_map(), popup_show_attrs(), read_former_destination_map_as_list(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_traffic_export_gpx(), route_get_destination_description(), route_graph_add_street(), route_graph_add_traffic_distortion(), search_list_common_new(), search_list_country_new(), search_list_get_result(), search_list_house_number_new(), search_list_street_new(), search_list_town_new(), search_next_interpolated_house_number(), NGQProxyBookmarks::setPoint(), statusbar_route_update(), street_get_data(), street_name_attr_get(), tm_find_item(), tracking_get_attr(), traffic_location_match_attributes(), traffic_location_populate_route_graph(), traffic_message_restore_segments(), traffic_point_match_attributes(), and traffic_point_match_segment_attributes().
item_attr_rewind()
void item_attr_rewind (struct item * it)
Resets the "attribute pointer" of an item.
This function resets the "attribute pointer" of an item to point to the first attribute, so that at the next call to item_attr_get() the first attribute will be returned.
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The map item whose pointer is to be reset. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
References item_methods::item_attr_rewind, item::meth, and item::priv_data.
Referenced by display_add(), display_add_holes(), filter_type(), gui_internal_cmd_pois(), map_filter_attr_rewind(), map_route_occluded_attr_rewind(), request_navit_traffic_export_gpx(), route_graph_add_street(), route_graph_add_traffic_distortion(), tm_find_item(), traffic_location_match_attributes(), traffic_location_populate_route_graph(), traffic_message_restore_segments(), traffic_point_match_attributes(), and traffic_point_match_segment_attributes().
item_attr_set()
int item_attr_set (struct item * it, struct attr * attr, enum change_mode mode)
Sets an attribute of an item.
This function supports different modes:
change_mode_delete: Deletes the attribute
change_mode_modify: Replaces an attribute
change_mode_append: Appends an attribute
change_mode_prepend: Prepends an attribute
TODO which attribute is deleted/modified? The last one retrieved, the next one, the first matching one?
TODO where are attributes appended/prepended? Beginning/end or current position?
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The map item whose coordinates to retrieve. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
attr TODO new attr, also store for old attr (delete/modify)? Required in delete mode (type of attr to delete)?
mode The change mode, see description
References item_methods::item_attr_set, item::meth, and item::priv_data.
Referenced by navit_cmd_map_item_set_attr(), and navit_populate_search_results_map().
item_cleanup()
void item_cleanup (void)
References default_flags_hash.
item_coord_get()
int item_coord_get (struct item * it, struct coord * c, int count)
Gets the next coordinates from an item.
This function returns a list of coordinates from an item and advances the "coordinate pointer" by the number of coordinates returned, so that at the next call the next coordinates will be returned.
Coordinates are stored in the projection of the item's map. If you need them in a different projection, call item_coord_get_pro() instead.
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The map item whose coordinates to retrieve. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
c Points to a buffer that will receive the coordinates. The buffer must be at least count * sizeof(struct coord) bytes in size.
count The number of coordinates to retrieve. Attempts to read past the end are handled gracefully and only the available number of coordinates is returned.
Returns
The number of coordinates actually retrieved and stored in c
References c, item_methods::item_coord_get, item::meth, and item::priv_data.
Referenced by binmap_get_estimated_boundaries(), binmap_search_get_item(), binmap_search_new(), binmap_search_street_by_place(), bookmarks_load_hash(), duplicate_test(), Backend::get_bookmarks(), NGQProxyBookmarks::getBookmarks(), graphics_process_selection_item(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd_bookmarks(), gui_internal_cmd_formerdests(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_populate_route_table(), gui_internal_select_waypoint(), item_coord_get_pro(), item_coord_get_within_range(), item_coord_get_within_selection(), item_dump_filedesc(), item_inside_poly_list(), map_filter_coord_get(), map_route_occluded_bbox(), map_selection_contains_item_rect(), model_poi(), navigation_itm_new(), navigation_way_get_max_delta(), navigation_way_init(), navit_add_former_destinations_from_file(), navit_zoom_to_route(), osd_route_guard_init(), osd_speed_cam_draw(), pedestrian_draw_arrows(), phase1_map(), popup_show_item(), popup_traffic_distortion(), read_former_destination_map_as_list(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_traffic_export_gpx(), route_graph_add_street(), route_graph_add_traffic_distortion(), route_graph_add_turn_restriction(), route_graph_remove_traffic_distortion(), search_house_number_coordinate(), search_list_street_new(), search_list_town_new(), NGQProxyBookmarks::setPoint(), street_get_data(), traffic_location_get_matching_points(), traffic_location_populate_route_graph(), traffic_message_restore_segments(), and vehicle_demo_timer().
item_coord_get_pro()
int item_coord_get_pro (struct item * it, struct coord * c, int count, enum projection to)
Gets the next coordinates from an item and reprojects them.
This function returns a list of coordinates from an item and advances the "coordinate pointer" by the number of coordinates returned, so that at the next call the next coordinates will be returned.
Parameters
it The map item whose coordinates to retrieve. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
c Points to a buffer that will receive the coordinates. The buffer must be at least count * sizeof(struct coord) bytes in size.
count The number of coordinates to retrieve. Attempts to read past the end are handled gracefully and only the available number of coordinates is returned.
projection The projection into which the coordinates will be transformed
Returns
The number of coordinates actually retrieved and stored in c
References c, item_coord_get(), item::map, map_projection(), and transform_from_to().
Referenced by Backend::get_pois(), NGQPoint::getPOI(), gui_internal_cmd_delete_waypoint(), and gui_internal_cmd_pois().
item_coord_get_within_range()
int item_coord_get_within_range (struct item * i, struct coord * c, int max, struct coord * start, struct coord * end)
Gets all the coordinates of an item within a specified range.
This will get all the coordinates of the item i, starting with start and ending with end, and return them in c, up to max coordinates.
If i does not contain the coordinates in start, no coordinates are retrieved and zero is returned.
If i contains the coordinates in start but not those in end, all coordinates beginning with start are retrieved, ending with the last coordinate of i or after max coordinates have been retrieved, whichever occurs first.
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
@important Make sure that c points to a buffer large enough to hold max coordinates!
Parameters
i The item to get the coordinates of
c Pointer to memory allocated for holding the coordinates
max Maximum number of coordinates to return
start First coordinate to get
end Last coordinate to get
Returns
The number of coordinates stored in c
References c, c1, item::id_hi, item::id_lo, item_coord_get(), item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), max, p, coord::x, and coord::y.
Referenced by route_path_add_item_from_graph(), and traffic_message_add_segments().
item_coord_get_within_selection()
int item_coord_get_within_selection (struct item * it, struct coord * c, int count, struct map_selection * sel)
Get coordinates within selection This function returns the coordinates of an item if at least one coordinate of that item is inside the selection. If the given buffer is too small, it returns the buffer size if at least one coordinate intersects with the selection, otherwise it returnes 0.
If the return value equals count, the content of c is undefined.
Parameters
it requested item
c preallocated buffer for the result
count number of coordinates in c
sel current map selection
Returns
number of coordinates read to c, or count if out of space, or 0 if not intersecting, or <0 on read error.
References bbox(), c, map_selection::c_rect, item_coord_get(), coord_rect::lu, map_selection::next, coord_rect::rl, map_selection::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by do_draw().
item_coord_is_node()
int item_coord_is_node (struct item * it)
Whether the current coordinates of an item correspond to a node.
TODO which coordinates? Last retrieved or next (to be) retrieved?
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The item
Returns
True on success, false on failure
References item_methods::item_coord_is_node, item::meth, and item::priv_data.
Referenced by route_graph_add_street(), and traffic_location_populate_route_graph().
item_coord_rewind()
void item_coord_rewind (struct item * it)
Resets the "coordinate pointer" of an item.
This function resets the "coordinate pointer" of an item to point to the first coordinate pair, so that at the next call to item_coord_get() the first coordinates will be returned.
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The map item whose pointer is to be reset. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
References item_methods::item_coord_rewind, item::meth, and item::priv_data.
Referenced by binmap_search_get_item(), do_draw(), item_inside_poly_list(), map_filter_coord_rewind(), map_route_occluded_coord_rewind(), navigation_way_get_max_delta(), request_navit_traffic_export_gpx(), route_graph_add_street(), route_graph_add_traffic_distortion(), route_graph_add_turn_restriction(), route_graph_remove_traffic_distortion(), search_house_number_coordinate(), traffic_location_populate_route_graph(), and traffic_message_restore_segments().
item_coord_set()
int item_coord_set (struct item * it, struct coord * c, int count, enum change_mode mode)
Sets coordinates of an item.
This function supports different modes:
change_mode_delete: Deletes the specified number of coordinates
change_mode_modify: Replaces existing coordinates with new ones
change_mode_append: Appends new coordinates
change_mode_prepend: Prepends new coordinates
TODO which coordinates are deleted/modified? Starting from the last coordinate retrieved, or the one after, or...?
TODO what if count in delete or modify mode is bigger then the number of coordinates left?
TODO where are coordinates appended/prepended? Beginning/end or current position?
This function is not safe to call after destroying the item's map rect, and doing so may cause errors with some map implementations.
Parameters
it The map item whose coordinates to retrieve. This must be the active item, i.e. the last one retrieved from the map_rect. There can only be one active item per map_rect.
c TODO new coordinates, also store for old coordinates (delete/modify)? Required in delete mode?
count TODO number of coordinates to add, delete or modify?
mode The change mode, see description
References c, item_methods::item_coord_set, item::meth, and item::priv_data.
Referenced by navit_cmd_map_add_curr_pos(), and navit_populate_search_results_map().
item_coords_left()
int item_coords_left (struct item * it)
Gets the number of coordinates left for this item.
This function returnes the number of coordinates left to get for this item. It does not change the "coordinates pointer".
Parameters
it The map item
Returns
The number of coordinates left. -1 if not supported by the actual map.
References item_methods::item_coords_left, item::meth, and item::priv_data.
Referenced by do_draw().
item_create_hash()
void item_create_hash (void)
References item_names, and name.
Referenced by config_load().
item_destroy_hash()
void item_destroy_hash (void)
Referenced by config_load().
item_dump_attr()
void item_dump_attr (struct item * item, struct map * map, FILE * out)
References attr_to_name(), attr_to_text(), item_attr_get(), item_to_name(), attr::type, and item::type.
Referenced by item_dump_filedesc().
item_dump_filedesc()
void item_dump_filedesc (struct item * item, struct map * map, FILE * out)
References item_coord_get(), item_dump_attr(), max, item::type, coord::x, and coord::y.
Referenced by map_dump_filedesc(), and popup_item_dump().
item_from_name()
enum item_type item_from_name (const char * name)
References item_names, and name.
Referenced by add_def(), attr_new_from_text(), build_attrmap_line(), item_type_from_road_type(), map_rect_get_item_shapefile(), map_rect_get_item_textfile(), model_poi(), navit_cmd_map_add_curr_pos(), parse_filter(), traffic_message_restore_segments(), and xmlconfig_announce().
item_get_default_flags()
int * item_get_default_flags (enum item_type type)
References default_flags2, default_flags_hash, and type.
Referenced by map_resolve_coords_and_split_at_intersections(), osm_end_way(), popup_show_item(), route_find_nearest_street(), route_graph_add_street(), street_get(), street_get_data(), tracking_doupdate_lines(), traffic_location_populate_route_graph(), traffic_message_restore_segments(), and vehicleprofile_apply_roadprofile().
item_hash_destroy()
void item_hash_destroy (struct item_hash * h)
References item_hash::h.
Referenced by navigation_destroy(), and route_path_destroy().
item_hash_equal()
static gboolean item_hash_equal (gconstpointer a, gconstpointer b) static
References item_is_equal.
Referenced by item_hash_new().
item_hash_hash()
static guint item_hash_hash (gconstpointer key) static
References item::id_hi, item::id_lo, key, and item::map.
Referenced by item_hash_new().
item_hash_insert()
void item_hash_insert (struct item_hash * h, struct item * item, void * val)
References dbg, item_hash::h, item::id_hi, item::id_lo, and lvl_info.
Referenced by navigation_itm_new(), and route_path_add_item_from_graph().
item_hash_lookup()
void * item_hash_lookup (struct item_hash * h, struct item * item)
References item_hash::h.
Referenced by navigation_update_idle(), route_contains(), and route_path_add_item_from_graph().
item_hash_new()
struct item_hash * item_hash_new (void)
References item_hash::h, item_hash_equal(), and item_hash_hash().
Referenced by navigation_new(), route_path_new(), and route_path_new_offroad().
item_hash_remove()
int item_hash_remove (struct item_hash * h, struct item * item)
References dbg, item_hash::h, item::id_hi, item::id_lo, and lvl_info.
Referenced by navigation_destroy_itms_cmds(), and route_extract_segment_from_path().
item_id_equal()
int item_id_equal (const void * a, const void * b)
References item_id::id_hi, and item_id::id_lo.
item_id_from_ptr()
void item_id_from_ptr (struct item * item, void * id)
Derive item id_lo and id_hi from pointer, considering pointer could be 32 or 64 bit wide but both ids are 32 bit.
Parameters
it reference to the item.
id pointer to derive item id from.
Returns
Nothing.
References item::id_hi, and item::id_lo.
Referenced by rm_get_item().
item_id_hash()
unsigned int item_id_hash (const void * key)
References item_id::id_hi, and key.
item_new()
struct item * item_new (char * type, int zoom)
Referenced by csv_create_item(), and map_new_csv().
item_range_contains_item()
int item_range_contains_item (struct item_range * range, enum item_type type)
References max, range::min, and type.
Referenced by map_selection_contains_item().
item_range_intersects_range()
int item_range_intersects_range (struct item_range * range1, struct item_range * range2)
References item_range::max.
Referenced by map_selection_contains_item_range().
item_to_name()
char * item_to_name (enum item_type item)
References item_names, and item_name::name.
Referenced by NGQPoint::_coordName(), attr_to_text_ext(), do_draw(), encode_attr(), Backend::get_pois(), NGQProxyBookmarks::getBookmarks(), NGQPoint::getPOI(), gui_internal_cmd_pois_item(), gui_internal_cmd_pois_item_selected(), gui_internal_cmd_position_do(), gui_internal_cmd_view_attributes(), gui_internal_poi_icon(), is_turn_allowed(), item_bin_dump(), item_dump_attr(), maneuver_required2(), map_route_occluded_get_item(), map_search_setup(), navigation_analyze_roundabout(), navigation_itm_ways_update(), navigation_map_item_attr_get(), navit_zoom_to_route(), osd_nav_next_turn_draw(), osd_text_draw(), popup_show_item(), request_navit_route_export_gpx(), route_get_destination_description(), route_graph_add_turn_restriction(), route_graph_process_restriction_segment(), search_house_number_coordinate(), tm_item_dump_to_file(), traffic_dump_messages_to_xml(), traffic_message_dump_to_stderr(), vehicleprofile_apply_roadprofile(), vehicleprofile_debug_roadprofile(), and write_former_destinations().
item_type_set()
int item_type_set (struct item * it, enum item_type type)
Sets the type of a map item.
Parameters
it The item
type The new type for the item. Setting it to type_none is expected to delete item from the map.
Returns
Non-zero if this action is supported by the map and type is set successfully, 0 on error.
References item_methods::item_type_set, item::meth, item::priv_data, and type.
Referenced by navit_populate_search_results_map(), and tm_item_unref().
Variable Documentation
busy_item
struct item busy_item
An item indicating that the map driver is busy fetching more items.
This is a “magic” item which may be returned by one of the query methods of a map driver. Receiving this item means that the map driver is currently busy fetching more items, and they can be retrieved at a later point in time.
Referenced by do_draw(), map_binfile_open(), and map_rect_get_item_binfile().
default_flags2
struct default_flags default_flags2[]
Referenced by item_get_default_flags().
default_flags_hash
GHashTable* default_flags_hash static
Referenced by item_cleanup(), and item_get_default_flags().
item_hash
GHashTable* item_hash static
item_names
struct item_name item_names[]
Initial value:
= {
#define ITEM2(x,y)
#define ITEM(x)
}
Referenced by item_create_hash(), item_from_name(), and item_to_name().
item_range_all
struct item_range item_range_all = { type_none, type_last }
Referenced by NGQPoint::_coordName(), binmap_search_housenumber_by_estimate(), binmap_search_street_by_place(), map_selection_rect_new(), navigation_itm_new(), and transform_get_selection().