navit: maptool/itembin_buffer.c File Reference
itembin_buffer.c File Reference
#include <string.h>
#include <stdlib.h>
#include "maptool.h"
#include "debug.h"
Functions
struct node_item * read_node_item (FILE *in)
struct item_bin * read_item (FILE *in)
struct item_bin * read_item_range (FILE *in, int *min, int *max)
struct item_bin * init_item (enum item_type type)
Variables
static char misc_item_buffer [20000000]
struct item_bin * tmp_item_bin =(struct item_bin *)(void *)misc_item_buffer
static struct node_item * tmp_node_item =(struct node_item *)(void *)misc_item_buffer
Function Documentation
struct item_bin* init_item (enum item_type type)
References item_bin_init(), and misc_item_buffer.
Referenced by ch_process_node(), index_country_add(), index_init(), index_submap_add(), ocean_tile(), osm_end_node(), osm_end_way(), osm_town_relations_to_poly(), phase1_map(), tile_collector_process_tile(), and write_tilesdir().
struct item_bin* read_item (FILE * in)
References bytes_read, dbg_assert, item_bin_read(), item_bin::len, misc_item_buffer, and NULL.
Referenced by ch_copy_to_tiles(), ch_generate_ddsg(), dump(), file_reader_finish(), load_countries(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), phase34_process_file(), process_associated_streets_setup(), process_binfile(), process_boundaries_setup(), process_house_number_interpolations_setup(), process_turn_restrictions_setup(), process_way2poi(), read_item_range(), ref_ways(), relations_process(), and resolve_ways().
struct item_bin* read_item_range (FILE * in, int * min, int * max)
References range::max, range::min, NULL, and read_item().
Referenced by phase34_process_file_range().
struct node_item* read_node_item (FILE * in)
References NULL, and tmp_node_item.
Referenced by relations_process().
Variable Documentation
char misc_item_buffer[20000000] static
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.Buffer for temporarily storing an item.
Referenced by init_item(), and read_item().
struct item_bin* tmp_item_bin =(struct item_bin *)(void *)misc_item_buffer
An item_bin for temporary use.
Referenced by osm_add_member(), osm_add_relation(), osm_end_relation(), process_boundaries_finish(), process_turn_restrictions_finish(), and relation_add_tag().
struct node_item* tmp_node_item =(struct node_item *)(void *)misc_item_buffer static
A node_item for temporary use.
Referenced by read_node_item().