navit: maptool/itembin.c File Reference
itembin.c File Reference
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include "maptool.h"
#include "linguistics.h"
#include "file.h"
#include "debug.h"
Data Structures
struct population_table
Functions
int item_bin_read (struct item_bin *ib, FILE *in)
void item_bin_set_type (struct item_bin *ib, enum item_type type)
void item_bin_init (struct item_bin *ib, enum item_type type)
void item_bin_add_coord (struct item_bin *ib, struct coord *coords_to_add, int count)
void item_bin_add_coord_reverse (struct item_bin *ib, struct coord *c, int count)
void item_bin_bbox (struct item_bin *ib, struct rect *r)
void item_bin_copy_coord (struct item_bin *ib, struct item_bin *from, int dir)
void item_bin_copy_attr (struct item_bin *ib, struct item_bin *from, enum attr_type attr)
void item_bin_add_coord_rect (struct item_bin *ib, struct rect *r)
int attr_bin_write_data (struct attr_bin *ab, enum attr_type type, void *data, int size)
int attr_bin_write_attr (struct attr_bin *ab, struct attr *attr)
void item_bin_add_attr_data (struct item_bin *ib, enum attr_type type, void *data, int size)
void item_bin_add_attr (struct item_bin *ib, struct attr *attr)
void item_bin_remove_attr (struct item_bin *ib, void *ptr)
void item_bin_add_attr_int (struct item_bin *ib, enum attr_type type, int val)
void * item_bin_get_attr (struct item_bin *ib, enum attr_type type, void *last)
struct attr_bin * item_bin_get_attr_bin (struct item_bin *ib, enum attr_type type, void *last)
struct attr_bin * item_bin_get_attr_bin_last (struct item_bin *ib)
void item_bin_add_attr_longlong (struct item_bin *ib, enum attr_type type, long long val)
void item_bin_add_attr_string (struct item_bin *ib, enum attr_type type, char *str)
void item_bin_add_attr_range (struct item_bin *ib, enum attr_type type, short min, short max)
void item_bin_write (struct item_bin *ib, FILE *out)
struct item_bin * item_bin_dup (struct item_bin *ib)
void item_bin_write_clipped (struct item_bin *ib, struct tile_parameter *param, struct item_bin_sink *out)
static char * coord_to_str (struct coord *c)
static void dump_coord (struct coord *c, FILE *out)
void item_bin_dump (struct item_bin *ib, FILE *out)
void dump_itembin (struct item_bin *ib)
void item_bin_set_type_by_population (struct item_bin *ib, int population)
void item_bin_write_match (struct item_bin *ib, enum attr_type type, enum attr_type match, int maxdepth, FILE *out)
static int item_bin_sort_compare (const void *p1, const void *p2)
int item_bin_sort_file (char *in_file, char *out_file, struct rect *r, int *size)
struct geom_poly_segment * item_bin_to_poly_segment (struct item_bin *ib, int type)
void clip_line (struct item_bin *ib, struct rect *r, struct tile_parameter *param, struct item_bin_sink *out)
void clip_polygon (struct item_bin *ib, struct rect *r, struct tile_parameter *param, struct item_bin_sink *out)
Variables
static struct population_table town_population []
static struct population_table district_population []
Function Documentation
int attr_bin_write_attr (struct attr_bin * ab, struct attr * attr)
References attr_bin_write_data(), attr_data_get(), attr_data_size(), and attr::type.
Referenced by item_bin_add_attr().
int attr_bin_write_data (struct attr_bin * ab, enum attr_type type, void * data, int size)
References attr_bin::len, attr_bin::type, and type.
Referenced by attr_bin_write_attr(), and item_bin_add_attr_data().
void clip_line (struct item_bin * ib, struct rect * r, struct tile_parameter * param, struct item_bin_sink * out)
References tile_parameter::attr_to_copy, item_bin::clen, g_alloca, geom_clip_line_code(), i, item_bin_add_coord(), item_bin_copy_attr(), item_bin_init(), item_bin_write_clipped(), item_bin::len, item_bin::type, coord::x, and coord::y.
Referenced by item_bin_write_clipped().
void clip_polygon (struct item_bin * ib, struct rect * r, struct tile_parameter * param, struct item_bin_sink * out)
References tile_parameter::attr_to_copy, item_bin::clen, g_alloca, geom_is_inside(), geom_poly_intersection(), i, item_bin_add_coord(), item_bin_copy_attr(), item_bin_init(), item_bin_write_clipped(), item_bin::len, p, and item_bin::type.
Referenced by item_bin_write_clipped().
static char* coord_to_str (struct coord * c) static
References g_strdup_printf(), coord::x, and coord::y.
Referenced by dump_coord(), and tile_collector_process_tile().
static void dump_coord (struct coord * c, FILE * out) static
References coord_to_str(), fprintf(), and g_free().
Referenced by item_bin_dump().
void dump_itembin (struct item_bin * ib)
References item_bin_dump().
Referenced by dump(), and write_item().
void item_bin_add_attr (struct item_bin * ib, struct attr * attr)
References attr_bin_write_attr(), ATTR_IS_GROUP, attr::attrs, i, item_bin::len, attr_bin::len, size, attr_bin::type, attr::type, and attr::u.
Referenced by index_init(), item_bin_add_attr_int(), item_bin_add_attr_longlong(), item_bin_add_attr_range(), item_bin_add_attr_string(), osm_add_member(), osm_process_towns(), and phase1_map().
void item_bin_add_attr_data (struct item_bin * ib, enum attr_type type, void * data, int size)
References attr_bin_write_data(), and item_bin::len.
Referenced by ch_process_node(), and item_bin_copy_attr().
void item_bin_add_attr_int (struct item_bin * ib, enum attr_type type, int val)
References item_bin_add_attr(), attr::num, type, attr::type, and attr::u.
Referenced by index_country_add(), index_submap_add(), osm_end_way(), and write_tilesdir().
void item_bin_add_attr_longlong (struct item_bin * ib, enum attr_type type, long long val)
References item_bin_add_attr(), attr::num64, type, attr::type, and attr::u.
Referenced by ocean_tile(), osm_add_relation(), osm_end_node(), osm_end_way(), osm_town_relations_to_poly(), relations_process(), and tile_collector_process_tile().
void item_bin_add_attr_range (struct item_bin * ib, enum attr_type type, short min, short max)
References item_bin_add_attr(), range::max, max, range::min, attr::range, type, attr::type, and attr::u.
Referenced by index_submap_add(), process_turn_restrictions_finish(), and write_tilesdir().
void item_bin_add_attr_string (struct item_bin * ib, enum attr_type type, char * str)
References item_bin_add_attr(), attr::str, type, attr::type, and attr::u.
Referenced by index_country_add(), item_bin_write_match(), ocean_tile(), osm_end_node(), osm_end_way(), osm_town_relations_to_poly(), process_associated_street_member(), process_house_number_interpolation_member(), relation_add_tag(), and tile_collector_process_tile().
void item_bin_add_coord (struct item_bin * ib, struct coord * coords_to_add, int count)
References item_bin::clen, and item_bin::len.
Referenced by ch_process_node(), clip_line(), clip_polygon(), close_polygon(), item_bin_add_coord_rect(), item_bin_add_coord_reverse(), item_bin_bbox(), item_bin_copy_coord(), osm_end_node(), osm_end_way(), osm_town_relations_to_poly(), phase1_map(), process_boundaries_finish(), process_turn_restrictions_finish(), relations_process(), and tile_collector_process_tile().
void item_bin_add_coord_rect (struct item_bin * ib, struct rect * r)
References rect::h, and item_bin_add_coord().
Referenced by index_submap_add(), and write_tilesdir().
void item_bin_add_coord_reverse (struct item_bin * ib, struct coord * c, int count)
References i, and item_bin_add_coord().
void item_bin_bbox (struct item_bin * ib, struct rect * r)
References rect::h, item_bin_add_coord(), coord::x, and coord::y.
Referenced by ocean_tile(), and tile_collector_process_tile().
void item_bin_copy_attr (struct item_bin * ib, struct item_bin * from, enum attr_type attr)
References item_bin_add_attr_data(), item_bin_get_attr_bin(), item_bin_get_wayid(), attr_bin::len, NULL, and attr_bin::type.
Referenced by clip_line(), and clip_polygon().
void item_bin_copy_coord (struct item_bin * ib, struct item_bin * from, int dir)
References c, item_bin::clen, i, and item_bin_add_coord().
void item_bin_dump (struct item_bin * ib, FILE * out)
References attr_data_set(), attr_to_name(), attr_to_text(), c, item_bin::clen, dump_coord(), fprintf(), g_free(), i, item_to_name(), item_bin::len, attr_bin::len, NULL, attr::str, item_bin::type, attr_bin::type, and attr::type.
Referenced by dump_itembin().
struct item_bin* item_bin_dup (struct item_bin * ib)
References g_malloc(), and item_bin::len.
Referenced by osm_process_towns(), and process_boundaries_setup().
void* item_bin_get_attr (struct item_bin * ib, enum attr_type type, void * last)
References item_bin::len, attr_bin::len, NULL, and attr_bin::type.
Referenced by boundary_relid(), item_bin_get_nodeid_from_attr(), item_bin_get_relationid(), item_bin_get_wayid(), item_bin_write_match(), osm_process_town_by_boundary_update_attrs(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), osm_process_towns(), osm_tag_value(), process_associated_street_member(), process_boundaries_member(), process_boundaries_setup(), process_house_number_interpolation_member(), relations_process(), and search_relation_member().
struct attr_bin* item_bin_get_attr_bin (struct item_bin * ib, enum attr_type type, void * last)
References item_bin::len, attr_bin::len, NULL, and attr_bin::type.
Referenced by item_bin_copy_attr(), item_bin_sort_compare(), phase34_process_file(), and write_countrydir().
struct attr_bin* item_bin_get_attr_bin_last (struct item_bin * ib)
References item_bin::len, attr_bin::len, and NULL.
Referenced by item_bin_sort_compare(), and write_countrydir().
void item_bin_init (struct item_bin * ib, enum item_type type)
References item_bin::clen, item_bin_set_type(), and item_bin::len.
Referenced by clip_line(), clip_polygon(), init_item(), ocean_tile(), osm_add_relation(), process_boundaries_finish(), process_turn_restrictions_finish(), relations_process(), and tile_collector_process_tile().
int item_bin_read (struct item_bin * ib, FILE * in)
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References item_bin::len.
Referenced by read_item(), and write_countrydir().
void item_bin_remove_attr (struct item_bin * ib, void * ptr)
References item_bin::len, and attr_bin::len.
Referenced by item_bin_write_match(), osm_process_towns(), and write_countrydir().
void item_bin_set_type (struct item_bin * ib, enum item_type type)
References item_bin::type, and type.
Referenced by item_bin_init(), and item_bin_set_type_by_population().
void item_bin_set_type_by_population (struct item_bin * ib, int population)
References district_population, i, item_bin_set_type(), item_is_district, town_population, and type.
Referenced by osm_end_node().
static int item_bin_sort_compare (const void * p1, const void * p2) static
References item_bin::clen, dbg_assert, fprintf(), g_free(), item_bin_get_attr_bin(), item_bin_get_attr_bin_last(), linguistics_casefold(), NULL, s1, s2, and attr_bin::type.
Referenced by item_bin_sort_file().
int item_bin_sort_file (char * in_file, char * out_file, struct rect * r, int * size)
References bbox_extend(), buffer, c, item_bin::clen, dbg_assert, file_get_contents(), g_free(), g_malloc(), rect::h, item_bin_sort_compare(), item_bin::len, and p.
Referenced by sort_countries().
struct geom_poly_segment* item_bin_to_poly_segment (struct item_bin * ib, int type)
References item_bin::clen, geom_poly_segment::first, g_new, geom_coord_copy(), int, geom_poly_segment::last, geom_poly_segment::type, and type.
Referenced by process_boundaries_member(), and tile_data_to_segments().
void item_bin_write (struct item_bin * ib, FILE * out)
References dbg_assert, and item_bin::len.
Referenced by ch_process_node(), file_writer_process(), index_country_add(), index_init(), item_bin_write_match(), osm_end_node(), osm_end_relation(), osm_end_way(), osm_town_relations_to_poly(), phase1_map(), process_associated_street_member(), process_binfile(), process_boundaries_finish(), process_house_number_interpolation_member(), process_turn_restrictions_finish(), relation_func_writethrough(), resolve_ways(), write_countrydir(), and write_tilesdir().
void item_bin_write_clipped (struct item_bin * ib, struct tile_parameter * param, struct item_bin_sink * out)
References bbox(), tile_data::buffer, item_bin::clen, clip_line(), clip_polygon(), i, tile_data::item_bbox, item_bin_write_to_sink(), tile_parameter::max, tile_parameter::min, NULL, tile_parameter::overlap, tile(), tile_data::tile_bbox, tile_bbox(), tile_data::tile_depth, and item_bin::type.
Referenced by clip_line(), clip_polygon(), and coastline_processor_process().
void item_bin_write_match (struct item_bin * ib, enum attr_type type, enum attr_type match, int maxdepth, FILE * out)
References bbox_extend(), c, item_bin::clen, g_free(), rect::h, i, item_bin_add_attr_string(), item_bin_get_attr(), item_bin_remove_attr(), item_bin_write(), item_bin::len, linguistics_expand_special(), linguistics_next_word(), linguistics_search(), NULL, overlap, and tile().
Referenced by osm_process_towns().
Variable Documentation
struct population_table district_population[] static
Initial value:
= {
        {type_district_label_0e0,0},
        {type_district_label_1e0,1},
        {type_district_label_2e0,2},
        {type_district_label_5e0,5},
        {type_district_label_1e1,10},
        {type_district_label_2e1,20},
        {type_district_label_5e1,50},
        {type_district_label_1e2,100},
        {type_district_label_2e2,200},
        {type_district_label_5e2,500},
        {type_district_label_1e3,1000},
        {type_district_label_2e3,2000},
        {type_district_label_5e3,5000},
        {type_district_label_1e4,10000},
        {type_district_label_2e4,20000},
        {type_district_label_5e4,50000},
        {type_district_label_1e5,100000},
        {type_district_label_2e5,200000},
        {type_district_label_5e5,500000},
        {type_district_label_1e6,1000000},
        {type_district_label_2e6,2000000},
        {type_district_label_5e6,5000000},
        {type_district_label_1e7,10000000},
}
Referenced by item_bin_set_type_by_population().
struct population_table town_population[] static
Initial value:
= {
        {type_town_label_0e0,0},
        {type_town_label_1e0,1},
        {type_town_label_2e0,2},
        {type_town_label_5e0,5},
        {type_town_label_1e1,10},
        {type_town_label_2e1,20},
        {type_town_label_5e1,50},
        {type_town_label_1e2,100},
        {type_town_label_2e2,200},
        {type_town_label_5e2,500},
        {type_town_label_1e3,1000},
        {type_town_label_2e3,2000},
        {type_town_label_5e3,5000},
        {type_town_label_1e4,10000},
        {type_town_label_2e4,20000},
        {type_town_label_5e4,50000},
        {type_town_label_1e5,100000},
        {type_town_label_2e5,200000},
        {type_town_label_5e5,500000},
        {type_town_label_1e6,1000000},
        {type_town_label_2e6,2000000},
        {type_town_label_5e6,5000000},
        {type_town_label_1e7,10000000},
}
Referenced by item_bin_set_type_by_population().