navit: tools/latlon2bookmark/latlon2bookmark.c File Reference
latlon2bookmark.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. this program is free software, please use it as you like. i am not a programmer, so please have this code reviewed to make sure it has nog bugs or ill side efects. use at your own risk compile it with: gcc -l m -o latlon2bookmark latlon2bookmark.c Credits for this work goes to edje in navit
References argc, command(), description(), err(), errormode, exit, fprintf(), g_free(), g_malloc0(), g_strjoinv(), g_strlcpy(), g_szClassName, getopt(), i, lat, M_PI, M_PI_4, navit_binding_w32_msg::magic, message_handler(), NAVIT_BINDING_W32_DWDATA, NAVIT_BINDING_W32_MAGIC, NAVIT_BINDING_W32_VERSION, NULL, optarg, optind, print_usage(), printf(), navit_binding_w32_msg::text, and navit_binding_w32_msg::version.