navit: layout.c File Reference
layout.c File Reference
#include <glib.h>
#include <string.h>
#include "item.h"
#include "attr.h"
#include "xmlconfig.h"
#include "layout.h"
#include "coord.h"
#include "debug.h"
#include "navit.h"
Data Structures
struct attr_iter
Functions
struct layout * layout_new (struct attr *parent, struct attr **attrs)
Create a new layout object and attach it to a navit parent.
struct attr_iter * layout_attr_iter_new (void *unused)
void layout_attr_iter_destroy (struct attr_iter *iter)
int layout_get_attr (struct layout *layout, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int layout_add_attr (struct layout *layout, struct attr *attr)
struct cursor * layout_get_cursor (struct layout *this_, char *name)
struct cursor * cursor_new (struct attr *parent, struct attr **attrs)
void cursor_destroy (struct cursor *this_)
int cursor_add_attr (struct cursor *this_, struct attr *attr)
static int layer_set_attr_do (struct layer *l, struct attr *attr, int init)
struct layer * layer_new (struct attr *parent, struct attr **attrs)
int layer_get_attr (struct layer *layer, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int layer_add_attr (struct layer *layer, struct attr *attr)
int layer_set_attr (struct layer *layer, struct attr *attr)
static void layer_destroy (struct layer *layer)
struct itemgra * itemgra_new (struct attr *parent, struct attr **attrs)
int itemgra_add_attr (struct itemgra *itemgra, struct attr *attr)
static void element_set_oneway (struct element *e, struct attr **attrs)
static void element_set_color (struct element *e, struct attr **attrs)
static void element_set_background_color (struct color *c, struct attr **attrs)
static void element_set_text_size (struct element *e, struct attr **attrs)
static void element_set_arrows_width (struct element *e, struct attr **attrs)
static void element_set_polyline_width (struct element *e, struct attr **attrs)
static void element_set_polyline_directed (struct element *e, struct attr **attrs)
static void element_set_polyline_dash (struct element *e, struct attr **attrs)
static void element_set_polyline_offset (struct element *e, struct attr **attrs)
static void element_set_circle_width (struct element *e, struct attr **attrs)
static void element_set_circle_radius (struct element *e, struct attr **attrs)
struct polygon * polygon_new (struct attr *parent, struct attr **attrs)
struct polyline * polyline_new (struct attr *parent, struct attr **attrs)
struct circle * circle_new (struct attr *parent, struct attr **attrs)
struct text * text_new (struct attr *parent, struct attr **attrs)
struct icon * icon_new (struct attr *parent, struct attr **attrs)
struct image * image_new (struct attr *parent, struct attr **attrs)
struct arrows * arrows_new (struct attr *parent, struct attr **attrs)
int element_add_attr (struct element *e, struct attr *attr)
Variables
struct object_func layout_func
struct object_func layer_func
Function Documentation
arrows_new()
struct arrows* arrows_new (struct attr * parent, struct attr ** attrs)
References element::arrows, element::element_arrows, element_set_arrows_width(), element_set_color(), element_set_oneway(), and element::type.
circle_new()
struct circle* circle_new (struct attr * parent, struct attr ** attrs)
References element::circle, element::color, COLOR_BLACK_, COLOR_WHITE_, element_set_background_color(), element_set_circle_radius(), element_set_circle_width(), element_set_color(), element_set_oneway(), element_set_text_size(), element::type, and element::u.
cursor_add_attr()
int cursor_add_attr (struct cursor * this_, struct attr * attr)
References attr_generic_add_attr(), cursor::attrs, and attr::type.
Referenced by osd_marker_init().
cursor_destroy()
void cursor_destroy (struct cursor * this_)
References cursor::name, and cursor::sequence_range.
cursor_new()
struct cursor* cursor_new (struct attr * parent, struct attr ** attrs)
References attr_search(), cursor::attrs, dbg, cursor::h, cursor::interval, lvl_info, range::max, range::min, name, attr::range, cursor::sequence_range, attr::u, and cursor::w.
Referenced by osd_marker_init().
element_add_attr()
int element_add_attr (struct element * e, struct attr * attr)
References attr::coord, element::coord, element::coord_count, attr::type, and attr::u.
Referenced by osd_marker_init().
element_set_arrows_width()
static void element_set_arrows_width (struct element * e, struct attr ** attrs) static
References element::arrows, attr_search(), attr::attrs, element::u, and width.
Referenced by arrows_new().
element_set_background_color()
static void element_set_background_color (struct color * c, struct attr ** attrs) static
References attr_search(), attr::attrs, c, and attr::color.
Referenced by circle_new(), and text_new().
element_set_circle_radius()
static void element_set_circle_radius (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, element::circle, attr::num, attr::u, and element::u.
Referenced by circle_new().
element_set_circle_width()
static void element_set_circle_width (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, element::circle, element::u, and width.
Referenced by circle_new().
element_set_color()
static void element_set_color (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, attr::color, and element::color.
Referenced by arrows_new(), circle_new(), polygon_new(), polyline_new(), and text_new().
element_set_oneway()
static void element_set_oneway (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, attr::num, element::oneway, and attr::u.
Referenced by arrows_new(), circle_new(), polygon_new(), polyline_new(), and text_new().
element_set_polyline_dash()
static void element_set_polyline_dash (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, attr::dash, element::polyline, and element::u.
Referenced by polyline_new().
element_set_polyline_directed()
static void element_set_polyline_directed (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, attr::num, element::polyline, attr::u, and element::u.
Referenced by polyline_new().
element_set_polyline_offset()
static void element_set_polyline_offset (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, offset, element::polyline, and element::u.
Referenced by polyline_new().
element_set_polyline_width()
static void element_set_polyline_width (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, element::polyline, element::u, and width.
Referenced by polyline_new().
element_set_text_size()
static void element_set_text_size (struct element * e, struct attr ** attrs) static
References attr_search(), attr::attrs, attr::num, element::text_size, and attr::u.
Referenced by circle_new(), and text_new().
icon_new()
struct icon* icon_new (struct attr * parent, struct attr ** attrs)
References attr_search(), attr::attrs, attr::icon, element::icon, attr::num, attr::str, element::type, attr::u, and element::u.
image_new()
struct image* image_new (struct attr * parent, struct attr ** attrs)
References element::element_image, and element::type.
itemgra_add_attr()
int itemgra_add_attr (struct itemgra * itemgra, struct attr * attr)
References attr_to_name(), dbg, attr::element, itemgra::elements, lvl_error, attr::type, and attr::u.
Referenced by osd_marker_init().
itemgra_new()
struct itemgra* itemgra_new (struct attr * parent, struct attr ** attrs)
References itemgra::angle_range, attr_search(), attr::item_types, range::max, range::min, attr::range, itemgra::type, type, and attr::u.
Referenced by osd_marker_init().
layer_add_attr()
int layer_add_attr (struct layer * layer, struct attr * attr)
References attr::itemgra, layer::itemgras, attr::type, and attr::u.
layer_destroy()
static void layer_destroy (struct layer * layer) static
References attr_list_free(), and layer::name.
layer_get_attr()
int layer_get_attr (struct layer * layer, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References layer::active, layer::details, layer::name, attr::num, attr::str, attr::type, type, and attr::u.
layer_new()
struct layer* layer_new (struct attr * parent, struct attr ** attrs)
References layer::active, dbg, layer_func, layer_set_attr_do(), lvl_error, layer::name, layer::navit, and navit_object_ref().
layer_set_attr()
int layer_set_attr (struct layer * layer, struct attr * attr)
References layer_set_attr_do().
layer_set_attr_do()
static int layer_set_attr_do (struct layer * l, struct attr * attr, int init) static
References layer::active, dbg, layer::details, attr_iter::iter, lvl_error, layer::name, layer::navit, navit_object_ref(), navit_object_unref(), attr::num, layer::ref, attr::str, attr::type, and attr::u.
Referenced by layer_new(), and layer_set_attr().
layout_add_attr()
int layout_add_attr (struct layout * layout, struct attr * attr)
References attr_generic_add_attr(), attr::cursor, layout::cursors, attr::layer, layout::layers, attr::type, and attr::u.
layout_attr_iter_destroy()
void layout_attr_iter_destroy (struct attr_iter * iter)
References attr_iter::iter.
layout_attr_iter_new()
struct attr_iter* layout_attr_iter_new (void * unused)
layout_get_attr()
int layout_get_attr (struct layout * layout, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References layout::active, attr::cursor, layout::cursors, layout::dayname, attr_iter::iter, attr::layer, layout::layers, layout::name, layout::nightname, attr::num, attr::str, attr::type, type, and attr::u.
Referenced by navit_add_layout(), and request_layout_get_attr().
layout_get_cursor()
struct cursor* layout_get_cursor (struct layout * this_, char * name)
Searchs the layout for a cursor with the given name.
Parameters
layout The layout
name The name
Returns
A pointer to cursor with the given name or the name default or NULL.
Author
Ralph Sennhauser (10/2009)
References c, layout::cursors, and name.
Referenced by navit_set_cursors().
layout_new()
struct layout* layout_new (struct attr * parent, struct attr ** attrs)
Create a new layout object and attach it to a navit parent.
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Parameters
parent The parent for this layout (a navit attr)
attrs An array of attributes that for this layout
Returns
The newly created layout object
References layout::active, attr_search(), attr::attrs, attr::color, layout::color, COLOR_BACKGROUND_, layout::dayname, dbg, layout::font, layout::icon_h, layout::icon_w, layout_func, lvl_warning, layout::name, eval::navit, layout::navit, navit_get_layout_by_name(), navit_object_ref(), layout::nightname, attr::num, layout::order_delta, attr::str, attr::u, layout::underground_alpha, and UNDERGROUND_ALPHA_.
polygon_new()
struct polygon* polygon_new (struct attr * parent, struct attr ** attrs)
References attr_search(), attr::attrs, element_set_color(), element_set_oneway(), attr::num, attr::polygon, element::polygon, attr::str, element::type, attr::u, and element::u.
polyline_new()
struct polyline* polyline_new (struct attr * parent, struct attr ** attrs)
References element::element_polyline, element_set_color(), element_set_oneway(), element_set_polyline_dash(), element_set_polyline_directed(), element_set_polyline_offset(), element_set_polyline_width(), element::polyline, and element::type.
text_new()
struct text* text_new (struct attr * parent, struct attr ** attrs)
References element::color, COLOR_BLACK_, COLOR_WHITE_, element_set_background_color(), element_set_color(), element_set_oneway(), element_set_text_size(), element::text, element::type, and element::u.
Variable Documentation
layer_func
struct object_func layer_func
Initial value:
= {
    attr_layer,
    (object_func_new)layer_new,
    (object_func_get_attr)layer_get_attr,
    (object_func_iter_new)NULL,
    (object_func_iter_destroy)NULL,
    (object_func_set_attr)layer_set_attr,
    (object_func_add_attr)layer_add_attr,
    (object_func_remove_attr)NULL,
    (object_func_init)NULL,
    (object_func_destroy)layer_destroy,
    (object_func_dup)NULL,
    (object_func_ref)navit_object_ref,
    (object_func_unref)navit_object_unref,
}
Referenced by layer_new(), and object_func_lookup().
layout_func
struct object_func layout_func
Initial value:
= {
    attr_layout,
    (object_func_new)layout_new,
    (object_func_get_attr)layout_get_attr,
    (object_func_iter_new)layout_attr_iter_new,
    (object_func_iter_destroy)layout_attr_iter_destroy,
    (object_func_set_attr)NULL,
    (object_func_add_attr)layout_add_attr,
    (object_func_remove_attr)NULL,
    (object_func_init)NULL,
    (object_func_destroy)NULL,
    (object_func_dup)NULL,
    (object_func_ref)navit_object_ref,
    (object_func_unref)navit_object_unref,
}
Referenced by layout_new(), and object_func_lookup().