navit: support/libc/libc.h File Reference
libc.h File Reference
Macros
#define _GNU_SOURCE 1
Functions
void * popen (const char *command, const char *type)
int pclose (void *stream)
char * getenv (const char *)
int setenv (const char *name, const char *value, int overwrite)
void raise (int signal)
char * setlocale (int category, const char *locale)
struct lconv * localeconv (void)
int signal (int signum, void *handler)
Macro Definition Documentation
#define _GNU_SOURCE 1
Function Documentation
char* getenv (const char *)
References envnames, envvars, i, MAXENV, and NULL.
struct lconv* localeconv (void)
References localedata.
Referenced by g_ascii_formatd(), and g_ascii_strtod().
int pclose (void * stream)
void* popen (const char * command, const char * type)
void raise (int signal)
int setenv (const char * name, const char * value, int overwrite)
References envnames, envvars, g_strdup(), i, MAXENV, and NULL.
Referenced by config_set_attr_int(), Java_org_navitproject_navit_Navit_NavitMain(), main(), main_init(), main_setup_environment(), and parse_file().
char* setlocale (int category, const char * locale)
Referenced by _nl_locale_name(), espeak_Initialize(), initialise(), locale_charset(), main(), main_init(), navit_nls_main_init(), and plugin_init().
int signal (int signum, void * handler)