navit: support/libc/libc.c File Reference
libc.c File Reference
#include "locale.h"
#include <stdlib.h>
#include <string.h>
Macros
#define MAXENV 32
Functions
static void cleanup_libc (void)
char * getenv (const char *name)
int setenv (const char *name, const char *value, int overwrite)
int unsetenv (const char *name)
char * getcwd (char *buf, int size)
char * getwd (char *buf)
char * strtok_r (char *str, const char *delim, char **saveptr)
void perror (const char *x)
void raise (int signal)
void * popen (void)
int pclose (FILE *stream)
void rewind (void)
int GetThreadLocale (void)
int signal (int signum, int handler)
char * setlocale (int category, const char *locale)
struct lconv * localeconv (void)
unsigned int alarm (unsigned int seconds)
char * strerror (int num)
Variables
int errno
static char * envnames [MAXENV]
static char * envvars [MAXENV]
static struct lconv localedata ={"."}
Macro Definition Documentation
#define MAXENV 32
Referenced by cleanup_libc(), getenv(), setenv(), and unsetenv().
Function Documentation
unsigned int alarm (unsigned int seconds)
Referenced by sig_alrm_do(), sig_alrm_end(), and zip_write_directory().
static void cleanup_libc (void) static
References envnames, envvars, i, and MAXENV.
char* getcwd (char * buf, int size)
char* getenv (const char * name)
References envnames, envvars, i, MAXENV, and NULL.
int GetThreadLocale (void)
Referenced by _nl_locale_name().
char* getwd (char * buf)
struct lconv* localeconv (void)
References localedata.
Referenced by g_ascii_formatd(), and g_ascii_strtod().
int pclose (FILE * stream)
Referenced by get_data(), map_rect_destroy_textfile(), map_rect_get_item_byid_textfile(), map_rect_get_item_textfile(), and vehicle_file_close().
void perror (const char * x)
Referenced by bookmarks_write_center_to_file(), file_mmap(), and spawn_xkbd().
void* popen (void)
Referenced by get_data(), map_rect_get_item_byid_textfile(), map_rect_get_item_textfile(), map_rect_new_textfile(), and vehicle_file_open().
void raise (int signal)
void rewind (void)
int setenv (const char * name, const char * value, int overwrite)
References envnames, envvars, g_strdup(), i, MAXENV, and NULL.
Referenced by config_set_attr_int(), Java_org_navitproject_navit_Navit_NavitMain(), main(), main_init(), main_setup_environment(), and parse_file().
char* setlocale (int category, const char * locale)
Referenced by _nl_locale_name(), espeak_Initialize(), initialise(), locale_charset(), main(), main_init(), navit_nls_main_init(), and plugin_init().
int signal (int signum, int handler)
Referenced by config_new_int(), debug_init(), debug_level_set(), request_callback_new(), and sig_alrm_do().
char* strerror (int num)
Referenced by allocator_add_slab(), map_new_csv(), map_rect_new_textfile(), navit_mark_navigation_stopped(), SHPCreateLL(), SHPOpenLL(), SHPWriteHeader(), SHPWriteObject(), smc_tree_abort(), vehicle_gpsd_open(), and write_former_destinations().
char* strtok_r (char * str, const char * delim, char ** saveptr)
int unsetenv (const char * name)
References envnames, envvars, i, MAXENV, and NULL.
Referenced by parse_file().
Variable Documentation
char* envnames[MAXENV] static
Referenced by cleanup_libc(), getenv(), setenv(), and unsetenv().
char* envvars[MAXENV] static
Referenced by cleanup_libc(), getenv(), setenv(), and unsetenv().
int errno
errno.h included from mingw32ce/../errno.h
Referenced by _nl_find_msg(), _nl_load_domain(), allocator_add_slab(), allocator_memalign(), DCIGETTEXT(), g_ascii_strtod(), g_ascii_strtoll(), g_parse_long_long(), map_new_csv(), map_rect_new_textfile(), navit_mark_navigation_stopped(), pedestrian_setup_tilt(), SHPCreateLL(), SHPOpenLL(), SHPWriteHeader(), SHPWriteObject(), smc_tree_branch_grow_L(), smc_tree_insert(), VASNPRINTF(), vehicle_gpsd_open(), and write_former_destinations().
struct lconv localedata ={"."} static
Referenced by localeconv().