navit: support/gettext_intl/libgnuintl.h File Reference
libgnuintl.h File Reference
#include "config.h"
#include <locale.h>
#include <stdio.h>
#include <stddef.h>
#include <varargs.h>
Macros
#define LC_MESSAGES 1729
#define __USE_GNU_GETTEXT 1
#define __GNU_GETTEXT_SUPPORTED_REVISION(major) ((major) == 0 ? 1 : -1)
#define _INTL_REDIRECT_MACROS
#define _INTL_ASM(cname)
#define gettext libintl_gettext
#define dgettext libintl_dgettext
#define dcgettext libintl_dcgettext
#define ngettext libintl_ngettext
#define dngettext libintl_dngettext
#define dcngettext libintl_dcngettext
#define textdomain libintl_textdomain
#define bindtextdomain libintl_bindtextdomain
#define bind_textdomain_codeset libintl_bind_textdomain_codeset
#define fprintf libintl_fprintf
#define vfprintf libintl_vfprintf
#define printf libintl_printf
#define vprintf libintl_vprintf
#define sprintf libintl_sprintf
#define vsprintf libintl_vsprintf
#define libintl_set_relocation_prefix libintl_set_relocation_prefix
Functions
char * gettext (const char *__msgid) _INTL_ASM(libintl_gettext)
char * dgettext (const char *__domainname, const char *__msgid) _INTL_ASM(libintl_dgettext)
char * dcgettext (const char *__domainname, const char *__msgid, int __category) _INTL_ASM(libintl_dcgettext)
char * ngettext (const char *__msgid1, const char *__msgid2, unsigned long int __n) _INTL_ASM(libintl_ngettext)
char * dngettext (const char *__domainname, const char *__msgid1, const char *__msgid2, unsigned long int __n) _INTL_ASM(libintl_dngettext)
char * dcngettext (const char *__domainname, const char *__msgid1, const char *__msgid2, unsigned long int __n, int __category) _INTL_ASM(libintl_dcngettext)
char * textdomain (const char *__domainname) _INTL_ASM(libintl_textdomain)
char * bindtextdomain (const char *__domainname, const char *__dirname) _INTL_ASM(libintl_bindtextdomain)
char * bind_textdomain_codeset (const char *__domainname, const char *__codeset) _INTL_ASM(libintl_bind_textdomain_codeset)
int fprintf (FILE *, const char *,...)
int vfprintf (FILE *, const char *, va_list)
int printf (const char *,...)
int vprintf (const char *, va_list)
int sprintf (char *, const char *,...)
int vsprintf (char *, const char *, va_list)
void libintl_set_relocation_prefix (const char *orig_prefix, const char *curr_prefix)
Macro Definition Documentation
#define __GNU_GETTEXT_SUPPORTED_REVISION (major) ((major) == 0 ? 1 : -1)
#define __USE_GNU_GETTEXT 1
#define _INTL_ASM (cname)
#define _INTL_REDIRECT_MACROS
#define bind_textdomain_codeset libintl_bind_textdomain_codeset
Referenced by navit_nls_add_textdomain().
#define bindtextdomain libintl_bindtextdomain
Referenced by navit_nls_add_textdomain().
#define dcgettext libintl_dcgettext
#define dcngettext libintl_dcngettext
#define dgettext libintl_dgettext
Referenced by navit_nls_gettext().
#define dngettext libintl_dngettext
Referenced by navit_nls_ngettext().
#define fprintf libintl_fprintf
#define gettext libintl_gettext
#define LC_MESSAGES 1729
Referenced by category_to_name(), DCIGETTEXT(), DGETTEXT(), DNGETTEXT(), GETTEXT(), navit_nls_main_init(), and NGETTEXT().
#define libintl_set_relocation_prefix libintl_set_relocation_prefix
#define ngettext libintl_ngettext
#define printf libintl_printf
#define sprintf libintl_sprintf
#define textdomain libintl_textdomain
Referenced by navit_nls_main_init().
#define vfprintf libintl_vfprintf
#define vprintf libintl_vprintf
#define vsprintf libintl_vsprintf
Function Documentation
char* bind_textdomain_codeset (const char * __domainname, const char * __codeset)
char* bindtextdomain (const char * __domainname, const char * __dirname)
char* dcgettext (const char * __domainname, const char * __msgid, int __category)
char* dcngettext (const char * __domainname, const char * __msgid1, const char * __msgid2, unsigned long int __n, int __category)
char* dgettext (const char * __domainname, const char * __msgid)
char* dngettext (const char * __domainname, const char * __msgid1, const char * __msgid2, unsigned long int __n)
int fprintf (FILE * , const char * , ...)
Referenced by _nl_log_untranslated(), add_aux_tile(), add_tile_hash(), Alloc(), alloc_failed_warning(), allocate(), bookmarks_store_bookmarks_to_file(), cache_lookup(), ch_assemble_map(), ch_generate_ddsg(), ch_process_node(), charHandle(), checkPath(), close_polygon(), compile_dictlist_end(), compile_dictlist_file(), compile_dictrules(), compile_lettergroup(), compile_line(), compile_rule(), CompileDictionary(), ConvertUTF16toUTF32(), coord_print(), copy_rule_string(), create_tile_hash_list(), debug_dump_mallocs(), debug_free(), debug_set_logfile(), debug_vprintf(), DisplayVoices(), dump_coord(), endElementControl(), err(), exit_with_error(), extend_buffer(), flush_nodes(), fopen_log(), g_private_new_navit(), geom_poly_area(), geom_poly_point_inside(), geom_poly_segments_insert(), geom_poly_segments_point_inside(), get_data(), getopt_long(), getProperty(), graphics_opengl_new(), gui_internal_set(), hasMethod(), hasProperty(), InitGroups(), initialise(), intersect(), invalidate(), invoke(), invokeDefault(), item_bin_dump(), item_bin_sort_compare(), item_dump_attr(), item_dump_filedesc(), j1850_idle(), load_buffer(), load_types_file(), LoadDictionary(), LoadSoundFile(), LoadVoice(), LookupDict2(), LookupDictList(), main(), main_real(), map_collect_data_osm(), map_collect_data_osm_o5m(), map_resolve_coords_and_split_at_intersections(), map_route_occluded_check_buildings(), map_route_occluded_coord_get(), maptool_assemble_map(), MatchRule(), mem_error(), merge_tile(), merge_tiles(), navit_mark_navigation_stopped(), node_item_find_index_in_ordered_list(), NP_GetValue(), NPP_GetValue(), NPP_New(), NPP_SetWindow(), osd_odometer_save(), osm_add_nd(), osm_add_node(), osm_add_way(), osm_count_references(), osm_end_node(), osm_end_way(), osm_logv(), osm_process_towns(), osm_protobufdb_load(), osm_read_input_data(), osm_xml_get_attribute(), parse_member(), parse_option(), parse_pixel_line_values(), parseMain(), phase5(), png2pnm(), png_default_error(), png_default_warning(), png_handle_cHRM(), png_handle_gAMA(), png_handle_sRGB(), popup_traffic_distortion(), print_header(), printIdentifier(), process_slice(), process_turn_restrictions_dump_coord(), process_turn_restrictions_finish(), protobuf_c_out_of_memory_default(), ReadPhFile(), relation_add_tag(), RemoveEnding(), removeProperty(), repeated_field_pack_to_buffer(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), save_map_csv(), setDefault(), setMetadata(), setOptions(), setPath(), SetPitch(), setProperty(), SetSynth(), setup_pos(), setWpt(), smc_notify_free(), SpeakNextClause(), start_phase(), tile_collector_add_siblings(), tile_collector_add_siblings2(), tile_collector_finish(), tile_collector_process_tile(), tile_data_to_segments(), tile_extend(), TranslateRules(), TranslateWord(), usage(), version(), write_former_destinations(), write_item(), write_item_way_subsection(), write_tilesdir(), write_zipmember(), and zip_open().
char* gettext (const char * __msgid)
void libintl_set_relocation_prefix (const char * orig_prefix, const char * curr_prefix)
char* ngettext (const char * __msgid1, const char * __msgid2, unsigned long int __n)
int printf (const char * , ...)
Referenced by block_next(), build_attrmap_line(), ch_generate_sgr(), ch_process_nodes(), ch_setup(), changed(), checkEllpsUnit(), checkLengthUnit(), command(), create_framebuffer_texture(), CreateBitmapFromXpm(), dump_hex(), dump_hex_r(), dump_label_data(), dump_point(), dump_poly(), endElement(), failToWriteAttrRep(), fh_replacekeydata(), file_next(), file_read(), file_remap_readonly(), g_private_new_navit(), g_slice_init_nomessage(), garmin_img_attr_get(), garmin_img_coord_get(), geom_poly_point_inside(), get_tag(), graphics_opengl_new(), load_tilesdir(), main(), main_init(), main_real(), map_collect_data_osm_o5m(), map_collect_data_osm_protobuf(), map_destroy_garmin_img(), map_destroy_mg(), map_rect_get_item_garmin_img(), map_rect_new(), map_rect_new_garmin_img(), NPP_New(), o5m_print_end(), o5m_print_start(), o5m_print_version(), output_rule_group(), parse_color_values(), print_escaped(), print_usage(), process_boundaries_finish(), process_dense(), process_osmdata(), process_relation(), process_tag(), process_way(), raster_hline(), route_crossings_get(), route_graph_add_segment(), route_graph_flood(), route_graph_point_new(), route_path_new(), route_rect(), route_set_position_from_tracking(), save_vehicle_xml(), setDefault(), showStats(), startElement(), street_get(), sub_next(), town_get(), town_get_data(), transform_print_deg(), win32_gui_popup_new(), and WndProc().
int sprintf (char * , const char * , ...)
Referenced by AnnouncePunctuation(), button_destination_clicked(), ch_copy_to_tiles(), ch_create_tempfiles(), ch_generate_sgr(), compile_dictlist_file(), compile_rule(), CompileDictionary(), debug_timestamp(), debug_vprintf(), DecodeRule(), DisplayVoices(), espeak_ListVoices(), espeak_new(), ExtractVoiceVariantName(), ezxml_ampencode(), ezxml_toxml(), ezxml_toxml_r(), filter_type(), format_dist(), get_compass_direction(), get_direction(), get_string(), getDistance(), GetVoices(), house_number_next(), info_action(), init_path(), load_countries(), LoadConfig(), LoadDictionary(), LoadMbrolaTable(), LoadSoundFile(), LoadVoice(), locale_charset(), logfn(), longest_match_add_key_value(), LookupAccentedLetter(), LookupCharName(), LookupDictList(), LookupLetter(), LookupNum2(), LookupNum3(), LookupSpecial(), LookupThousands(), map_binfile_zip_setup(), MbrolaTranslate(), nmea_chksum(), osd_speed_cam_draw(), osm_protobufdb_start_file(), param_add_dec(), param_add_hex(), param_add_hex_sig(), pedestrian_graphics_resize(), popup_set_bookmark(), popup_set_destination(), popup_set_visitbefore(), popup_show_visitbefore(), popup_traffic_distortion_delay(), popup_traffic_distortion_speed(), print_dictionary_flags(), print_number(), print_string_ptr(), ProcessParamStack(), ProcessSsmlTag(), profile_timer(), ReadClause(), ReadPhFile(), ReadVoiceFile(), relation_add_tag(), remove_countryfiles(), SelectVoice(), SelectVoiceByName(), sigsegv(), statusbar_route_update(), street_attr_get(), street_name_number_next(), sync_espeak_Char(), SynthCallback(), tempfile_rename(), tempfile_unlink(), town_attr_get(), TranslateLetter(), TranslateNumber_1(), TranslateRoman(), TranslateRules(), TranslateWord(), tree_search_hv(), tree_search_init(), vehicle_file_position_attr_get(), vehicle_webos_parse_nmea(), vehicle_wince_position_attr_get(), WavegenFile(), WritePitch(), and xmlconfig_announce().
char* textdomain (const char * __domainname)
int vfprintf (FILE * , const char * , va_list)
Referenced by libintl_vfprintf(), and mem_error().
int vprintf (const char * , va_list)
int vsprintf (char * , const char * , va_list)
Referenced by libintl_vsprintf().