navit: support/gettext_intl/loadinfo.h File Reference
loadinfo.h File Reference
Data Structures
struct loaded_l10nfile
Macros
#define internal_function
#define __builtin_expect(expr, val) (expr)
#define PATH_SEPARATOR ':'
#define CEN_REVISION 1
#define CEN_SPONSOR 2
#define CEN_SPECIAL 4
#define XPG_NORM_CODESET 8
#define XPG_CODESET 16
#define TERRITORY 32
#define CEN_AUDIENCE 64
#define XPG_MODIFIER 128
#define CEN_SPECIFIC (CEN_REVISION|CEN_SPONSOR|CEN_SPECIAL|CEN_AUDIENCE)
#define XPG_SPECIFIC (XPG_CODESET|XPG_NORM_CODESET|XPG_MODIFIER)
Functions
const char * _nl_normalize_codeset (const char *codeset, size_t name_len)
struct loaded_l10nfile * _nl_make_l10nflist (struct loaded_l10nfile **l10nfile_list, const char *dirlist, size_t dirlist_len, int mask, const char *language, const char *territory, const char *codeset, const char *normalized_codeset, const char *modifier, const char *special, const char *sponsor, const char *revision, const char *filename, int do_allocate)
const char * _nl_expand_alias (const char *name)
int _nl_explode_name (char *name, const char **language, const char **modifier, const char **territory, const char **codeset, const char **normalized_codeset, const char **special, const char **sponsor, const char **revision)
char * _nl_find_language (const char *name)
Macro Definition Documentation
#define __builtin_expect (expr, val) (expr)
#define CEN_AUDIENCE 64
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define CEN_REVISION 1
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define CEN_SPECIAL 4
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define CEN_SPECIFIC (CEN_REVISION|CEN_SPONSOR|CEN_SPECIAL|CEN_AUDIENCE)
Referenced by _nl_make_l10nflist().
#define CEN_SPONSOR 2
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define internal_function
#define PATH_SEPARATOR ':'
Referenced by _nl_expand_alias(), and _nl_make_l10nflist().
#define TERRITORY 32
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define XPG_CODESET 16
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define XPG_MODIFIER 128
Referenced by _nl_explode_name(), and _nl_make_l10nflist().
#define XPG_NORM_CODESET 8
Referenced by _nl_explode_name(), _nl_find_domain(), and _nl_make_l10nflist().
#define XPG_SPECIFIC (XPG_CODESET|XPG_NORM_CODESET|XPG_MODIFIER)
Referenced by _nl_make_l10nflist().
Function Documentation
const char* _nl_expand_alias (const char * name)
References __libc_lock_lock, __libc_lock_unlock, alias_map::alias, alias_compare(), bsearch(), int, LOCALE_ALIAS_PATH, name, nmap, NULL, PATH_SEPARATOR, read_alias_file(), start, and alias_map::value.
Referenced by _nl_find_domain().
int _nl_explode_name (char * name, const char ** language, const char ** modifier, const char ** territory, const char ** codeset, const char ** normalized_codeset, const char ** special, const char ** sponsor, const char ** revision)
References _nl_find_language(), _nl_normalize_codeset(), CEN_AUDIENCE, CEN_REVISION, CEN_SPECIAL, CEN_SPONSOR, mask, name, NULL, TERRITORY, XPG_CODESET, XPG_MODIFIER, and XPG_NORM_CODESET.
Referenced by _nl_find_domain().
char* _nl_find_language (const char * name)
References name.
Referenced by _nl_explode_name().
struct loaded_l10nfile* _nl_make_l10nflist (struct loaded_l10nfile ** l10nfile_list, const char * dirlist, size_t dirlist_len, int mask, const char * language, const char * territory, const char * codeset, const char * normalized_codeset, const char * modifier, const char * special, const char * sponsor, const char * revision, const char * filename, int do_allocate)
References __argz_count, __argz_next, __argz_stringify, _nl_make_l10nflist(), CEN_AUDIENCE, CEN_REVISION, CEN_SPECIAL, CEN_SPECIFIC, CEN_SPONSOR, codeset, loaded_l10nfile::data, loaded_l10nfile::decided, entries, loaded_l10nfile::filename, filename, IS_ABSOLUTE_PATH, loaded_l10nfile::next, NULL, PATH_SEPARATOR, special, stpcpy(), loaded_l10nfile::successor, TERRITORY, XPG_CODESET, XPG_MODIFIER, XPG_NORM_CODESET, and XPG_SPECIFIC.
Referenced by _nl_find_domain(), and _nl_make_l10nflist().
const char* _nl_normalize_codeset (const char * codeset, size_t name_len)
References NULL, and stpcpy().
Referenced by _nl_explode_name().