navit: support/libc/localtime.c File Reference
localtime.c File Reference
#include "timeutil.h"
Functions
struct tm * localtime (const time_t *timer)
Function Documentation
struct tm* localtime (const time_t * timer)
References __FILETIME_to_ll(), __ll_to_FILETIME(), __SYSTEMTIME_to_tm(), and __time_t_to_FILETIME().
Referenced by gui_internal_time_help(), osd_text_format_attr(), statusbar_route_update(), and strftime_localtime().