navit: support/libc/lseek.c File Reference
lseek.c File Reference
#include <windows.h>
#include <unistd.h>
Functions
long _lseek (int fildes, long offset, int whence)
long lseek (int fildes, long offset, int whence)
Function Documentation
long _lseek (int fildes, long offset, int whence)
References NULL, SEEK_CUR, SEEK_END, and SEEK_SET.
Referenced by lseek().
long lseek (int fildes, long offset, int whence)
References _lseek().
Referenced by file_create(), file_data_read(), file_data_read_compressed(), file_data_write(), and file_version().