navit: main.h File Reference
main.h File Reference
Functions
struct iter * main_iter_new (void)
void main_iter_destroy (struct iter *iter)
struct navit * main_get_navit (struct iter *iter)
void main_add_navit (struct navit *nav)
void main_remove_navit (struct navit *nav)
int main_add_attr (struct attr *attr)
int main_remove_attr (struct attr *attr)
void main_init (const char *program)
void main_init_nls (void)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Main
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. this program is free software, please use it as you like. i am not a programmer, so please have this code reviewed to make sure it has nog bugs or ill side efects. use at your own risk compile it with: gcc -l m -o latlon2bookmark latlon2bookmark.c Credits for this work goes to edje in navit
References _g_slice_thread_init_nomessage(), argc, maptool_osm::associated_streets, AUDIO_OUTPUT_PLAYBACK, AUDIO_OUTPUT_SYNCHRONOUS, buffer::base, c, chdir(), closeProp(), CloseWaveFile(), command(), CompileDictionary(), maptool_params::compression_level, maptool_params::countries_loaded, createProp(), current_to_iso8601(), dbg, description(), dictionary_name, DisplayVoices(), DoVoiceChange(), maptool_params::dump, EE_OK, maptool_params::end, err(), errormode, espeak_CompileDictionary(), espeak_Info(), espeak_Initialize(), espeak_SetParameter(), espeak_SetPhonemeTrace(), espeak_SetPunctuationList(), espeak_SetSynthCallback(), espeak_SetVoiceByName(), espeak_SetVoiceByProperties(), espeak_Synchronize(), espeak_Synth(), espeakCAPITALS, espeakCHARS_8BIT, espeakCHARS_AUTO, espeakENDPAUSE, espeakLINELENGTH, espeakPHONEMES, espeakPITCH, espeakPUNCTUATION, espeakRATE, espeakSSML, espeakVOLUME, espeakWORDGAP, exit, exit_with_error(), experimental, experimental_feature_description, f_trans, filename, files_relation_processing_destroy(), files_relation_processing_new(), filetype, fprintf(), g_free(), g_malloc0(), g_strdup_printf(), g_strjoinv(), g_strlcpy(), g_szClassName, Generate(), GetFileLength(), getopt(), getopt_long(), gettimeofday(), option::has_arg, help_text, maptool_osm::house_number_interpolations, i, init_path(), initialise(), InitText(), maptool_params::input, maptool_params::input_file, maptool_params::keep_tmpfiles, espeak_VOICE::languages, lat, LC_ALL, maptool_osm::line2poi, linguistics_init(), load_types_file(), LoadVoice(), long, M_PI, M_PI_4, navit_binding_w32_msg::magic, main_init(), main_real(), buffer::malloced, maptool_assemble_map(), maptool_dump(), maptool_generate_tiles(), maptool_init(), maptool_load_countries(), maptool_load_node_table(), maptool_load_tilesdir(), max, maptool_params::max_index_size, mbrola_name, message_handler(), n_phoneme_list, N_PUNCTLIST, name, NAVIT_BINDING_W32_DWDATA, NAVIT_BINDING_W32_MAGIC, NAVIT_BINDING_W32_VERSION, g2sprop::needsStats, no_argument, maptool_params::node_table_loaded, NULL, OpenWaveFile(), OpenWavFile(), optarg, optind, option_capitals, option_endpause, option_linelength, option_multibyte, option_phoneme_input, option_phonemes, option_punctlist, option_punctuation, option_quiet, option_ssml, option_waveout, option_wordgap, optional_argument, maptool_params::osm, osm_count_references(), osm_process_coastlines(), osm_process_towns(), osm_process_turn_restrictions(), osm_process_way2poi(), osm_protobufdb_load(), osm_read_input_data(), osm_resolve_coords_and_split_at_intersections(), p, parse_option(), parseMain(), path_home, phase, phoneme_list, POS_CHARACTER, print_usage(), printf(), process_associated_streets(), process_binfile(), process_house_number_interpolations(), maptool_params::process_nodes, maptool_params::process_relations, maptool_params::process_ways, maptool_params::protobufdb, maptool_params::protobufdb_operation, quiet, required_argument, maptool_params::result, maptool_params::rule_file, samplerate, samples_split, setenv(), setlocale(), setOptions(), SetParameter(), SetVoiceByName(), SetVoiceByProperties(), showStats(), size, buffer::size, sort_countries(), SpeakNextClause(), speed, maptool_params::start, start_brk, start_phase(), start_ts, strncpy0(), suffixes, SynthCallback(), SynthOnTimer(), tempfile(), tempfile_unlink(), navit_binding_w32_msg::text, maptool_params::tilesdir_loaded, maptool_params::timestamp, unlink(), usage(), option::val, value, navit_binding_w32_msg::version, version_string, voice, wavefile, WavegenFile(), WavegenInitSound(), and maptool_params::ways_split.
int main_add_attr (struct attr * attr)
void main_add_navit (struct navit * nav)
struct navit* main_get_navit (struct iter * iter)
void main_init (const char * program)
References _, callback_list_new(), file_exists(), filename, g_free(), g_strdup(), getcwd, getenv, L, LC_ALL, LC_NUMERIC, main_setup_environment(), NULL, PATH_MAX, printf(), setenv(), setlocale(), and spawn_process_init().
Referenced by main(), and main_real().
void main_init_nls (void)
void main_iter_destroy (struct iter * iter)
struct iter* main_iter_new (void)
int main_remove_attr (struct attr * attr)
void main_remove_navit (struct navit * nav)