moduledatadir=$(pkglibdir)/data
modulegraphicsdir=$(pkglibdir)/graphics
moduleguidir=$(pkglibdir)/gui
modulespeechdir=$(pkglibdir)/speech
moduleosddir=$(pkglibdir)/osd
modulevehicledir=$(pkglibdir)/vehicle
pkgdocdir=$(pkgdatadir)
xpmdir=$(pkgdatadir)/xpm
