/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "map.h"

void
Mappel_Test(Mappel _obj, CORBA_Environment * ev)
{
   ORBit_c_stub_invoke(_obj, &Mappel__iinterface.methods, 0, NULL, NULL, NULL,
		       ev, Mappel__classid, G_STRUCT_OFFSET(POA_Mappel__epv,
							    Test),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Mappel_Test);

}

Map
Map_mapString(Map _obj, const CORBA_char * astring, CORBA_double * anum,
	      CORBA_Environment * ev)
{
   Map _ORBIT_retval;
   gpointer _args[2];

   _args[0] = (gpointer) & astring;
   _args[1] = &anum;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 0, &_ORBIT_retval,
		       _args, NULL, ev, Map__classid,
		       G_STRUCT_OFFSET(POA_Map__epv, mapString),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_mapString);

   return _ORBIT_retval;
}

void
Map_doNothing(Map _obj, CORBA_Environment * ev)
{
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 1, NULL, NULL, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv,
							 doNothing),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_doNothing);

}

void
Map_doOneWay(Map _obj, const CORBA_char * ignore, CORBA_Environment * ev)
{
   gpointer _args[1];

   _args[0] = (gpointer) & ignore;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 2, NULL, _args, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv,
							 doOneWay),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_doOneWay);

}

void
Map_PlaceFlag(Map _obj, CORBA_Environment * ev)
{
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 3, NULL, NULL, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv,
							 PlaceFlag),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_PlaceFlag);

}

PointObj
Map_PointFromCoord(Map _obj, const CORBA_char * coord, CORBA_Environment * ev)
{
   PointObj _ORBIT_retval;
   gpointer _args[1];

   _args[0] = (gpointer) & coord;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 4, &_ORBIT_retval,
		       _args, NULL, ev, Map__classid,
		       G_STRUCT_OFFSET(POA_Map__epv, PointFromCoord),
		       (ORBitSmallSkeleton)
		       _ORBIT_skel_small_Map_PointFromCoord);

   return _ORBIT_retval;
}

void
Map_View(Map _obj, const PointObj * where, CORBA_Environment * ev)
{
   gpointer _args[1];

   _args[0] = (gpointer) where;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 5, NULL, _args, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv, View),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_View);

}

void
Map_ViewAll(Map _obj, const PointObjSequence * where, CORBA_Environment * ev)
{
   gpointer _args[1];

   _args[0] = (gpointer) where;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 6, NULL, _args, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv,
							 ViewAll),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_ViewAll);

}

void
Map_Route(Map _obj, const PointObj * src, const PointObj * dst,
	  CORBA_Environment * ev)
{
   gpointer _args[2];

   _args[0] = (gpointer) src;
   _args[1] = (gpointer) dst;
   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 7, NULL, _args, NULL,
		       ev, Map__classid, G_STRUCT_OFFSET(POA_Map__epv, Route),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_Route);

}

Mappel
Map_Get(Map _obj, CORBA_Environment * ev)
{
   Mappel _ORBIT_retval;

   ORBit_c_stub_invoke(_obj, &Map__iinterface.methods, 8, &_ORBIT_retval,
		       NULL, NULL, ev, Map__classid,
		       G_STRUCT_OFFSET(POA_Map__epv, Get),
		       (ORBitSmallSkeleton) _ORBIT_skel_small_Map_Get);

   return _ORBIT_retval;
}
