navit: map/mg/map.c File Reference
map.c File Reference
#include "config.h"
#include "debug.h"
#include "maptype.h"
#include "mg.h"
#include "plugin.h"
#include <stdio.h>
#include <string.h>
Data Structures
struct country_isonum
Functions
struct map_priv * map_new_mg (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
int mg_country_from_isonum (int isonum)
int mg_country_to_isonum (int country)
int mg_country_postal_len (int country)
static char * mg_country_postal_prefix (int isonum)
static int file_next (struct map_rect_priv *mr)
static void map_destroy_mg (struct map_priv *m)
struct map_rect_priv * map_rect_new_mg (struct map_priv *map, struct map_selection *sel)
static struct item * map_rect_get_item_mg (struct map_rect_priv *mr)
struct item * map_rect_get_item_byid_mg (struct map_rect_priv *mr, int id_hi, int id_lo)
void map_rect_destroy_mg (struct map_rect_priv *mr)
static char * map_search_mg_convert_special (char *str)
static int map_search_setup (struct map_rect_priv *mr)
static void map_search_cleanup (struct map_rect_priv *mr)
static struct item * map_search_get_item_mg (struct map_search_priv *ms)
static struct map_search_priv * map_search_new_mg (struct map_priv *map, struct item *item, struct attr *search, int partial)
static void map_search_destroy_mg (struct map_search_priv *ms)
void plugin_init (void)
Variables
GList * maps
static struct country_isonum country_isonums []
static int map_id
static char * file []
struct item_range town_ranges []
struct item_range street_ranges []
struct item_range poly_ranges []
int block_lin_count
int block_idx_count
int block_active_count
int block_mem
int block_active_mem
static struct map_methods map_methods_mg
Function Documentation
file_next()
static int file_next (struct map_rect_priv * mr) static
References block_init(), map_rect_priv::cur_sel, map_rect_priv::current_file, debug, map_priv::file, map_rect_priv::file, file_end, file_street_str, file_strname_stn, file_town_twn, map_rect_priv::m, map_selection_contains_item_range(), poly_ranges, street_ranges, town_ranges, and map_rect_priv::xsel.
Referenced by map_rect_get_item_mg(), and map_rect_new_mg().
map_destroy_mg()
static void map_destroy_mg (struct map_priv * m) static
References map_priv::file, file_destroy(), and file_end.
map_new_mg()
struct map_priv * map_new_mg (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl)
References attr_search(), attrs, data, dbg, map_priv::dirname, map_priv::file, file_border_ply, file_create_caseinsensitive(), file_end, file_height_ply, file_mmap(), file_sea_ply, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_new(), filename, map_priv::id, lvl_error, map_id, map_methods_mg, maps, and meth.
Referenced by plugin_init().
map_rect_destroy_mg()
void map_rect_destroy_mg (struct map_rect_priv * mr)
References map_rect_priv::block_hash, and file_end.
Referenced by map_search_destroy_mg(), and map_search_setup().
map_rect_get_item_byid_mg()
struct item * map_rect_get_item_byid_mg (struct map_rect_priv * mr, int id_hi, int id_lo)
References map_rect_priv::current_file, file_street_str, file_strname_stn, file_town_twn, item::id_hi, item::id_lo, map_rect_priv::item, map_rect_priv::poly, poly_get_byid(), map_rect_priv::street, street_get_byid(), street_name_get_byid(), map_rect_priv::town, and town_get_byid().
Referenced by housenumber_attr_get(), map_search_setup(), and street_name_attr_get().
map_rect_get_item_mg()
static struct item * map_rect_get_item_mg (struct map_rect_priv * mr) static
References block_active_count, block_active_mem, block_idx_count, block_init(), block_lin_count, block_mem, block_next(), map_rect_priv::cur_sel, map_rect_priv::current_file, dbg, file_border_ply, file_bridge_ply, file_build_ply, file_end, file_golf_ply, file_natpark_ply, file_nature_ply, file_next(), file_other_ply, file_rail_ply, file_sea_ply, file_street_str, file_town_twn, file_water_ply, file_woodland_ply, map_rect_priv::item, lvl_debug, map_selection::next, map_rect_priv::poly, poly_get(), map_rect_priv::street, street_get(), map_rect_priv::town, and town_get().
map_rect_new_mg()
struct map_rect_priv * map_rect_new_mg (struct map_priv * map, struct map_selection * sel)
References block_active_count, block_active_mem, map_rect_priv::block_hash, block_idx_count, block_lin_count, block_mem, map_rect_priv::current_file, file_end, file_next(), map_rect_priv::m, map_selection::next, map_rect_priv::sel, and map_rect_priv::xsel.
Referenced by map_search_new_mg(), and map_search_setup().
map_search_cleanup()
static void map_search_cleanup (struct map_rect_priv * mr) static
References map_rect_priv::search_blk_count, map_rect_priv::search_blk_off, map_rect_priv::search_block, map_rect_priv::search_linear, map_rect_priv::search_p, map_rect_priv::search_str, tree_search_free(), and map_rect_priv::ts.
Referenced by map_search_destroy_mg(), and map_search_get_item_mg().
map_search_destroy_mg()
static void map_search_destroy_mg (struct map_search_priv * ms) static
References attr_free(), dbg, lvl_debug, map_rect_destroy_mg(), map_search_cleanup(), map_rect_priv::search_attr, and map_rect_priv::search_mr_tmp.
map_search_get_item_mg()
static struct item * map_search_get_item_mg (struct map_search_priv * ms) static
References attr_to_name(), dbg, housenumber_search_get_item(), lvl_error, map_search_cleanup(), map_search_get_item_mg(), map_search_setup(), map_rect_priv::search_type_next, street_search_get_item(), and town_search_get_item().
Referenced by map_search_get_item_mg().
map_search_mg_convert_special()
static char * map_search_mg_convert_special (char * str) static
References c, dbg, and lvl_debug.
Referenced by map_search_setup().
map_search_new_mg()
static struct map_search_priv * map_search_new_mg (struct map_priv * map, struct item * item, struct attr * search, int partial) static
References attr_dup(), attr_to_name(), dbg, item::id_lo, map_rect_priv::item, lvl_debug, lvl_warning, map_rect_priv::m, map_rect_new_mg(), map_search_setup(), map_rect_priv::search, map_rect_priv::search_attr, map_rect_priv::search_item, map_rect_priv::search_mr_tmp, map_rect_priv::search_partial, and map_rect_priv::search_type_next.
map_search_setup()
static int map_search_setup (struct map_rect_priv * mr) static
References attr_to_name(), block_init(), map_rect_priv::current_file, dbg, map_priv::dirname, map_priv::file, map_rect_priv::file, file_strname_stn, file_town_twn, housenumber_search_setup(), item::id_hi, item::id_lo, attr::item, item_attr_get(), item_to_name(), lvl_debug, lvl_error, map_rect_priv::m, item::map, map_priv_is(), map_rect_destroy_mg(), map_rect_get_item_byid_mg(), map_rect_new_mg(), map_search_mg_convert_special(), maps, mg_country_from_isonum(), mg_country_postal_prefix(), map_rect_priv::search_attr, map_rect_priv::search_country, map_rect_priv::search_item, map_rect_priv::search_str, attr::str, tree_search_init(), map_rect_priv::ts, item::type, and attr::u.
Referenced by map_search_get_item_mg(), and map_search_new_mg().
mg_country_from_isonum()
int mg_country_from_isonum (int isonum)
References country_isonum::country, and country_isonums.
Referenced by map_search_setup().
mg_country_postal_len()
int mg_country_postal_len (int country)
References country_isonums, and country_isonum::postal_len.
Referenced by town_attr_get().
mg_country_postal_prefix()
static char * mg_country_postal_prefix (int isonum) static
References country_isonums, and country_isonum::postal_prefix.
Referenced by map_search_setup().
mg_country_to_isonum()
int mg_country_to_isonum (int country)
References country_isonums, and country_isonum::isonum.
Referenced by street_attr_get().
plugin_init()
void plugin_init (void)
References map_new_mg().
Variable Documentation
block_active_count
int block_active_count
Referenced by map_rect_get_item_mg(), and map_rect_new_mg().
block_active_mem
int block_active_mem
Referenced by map_rect_get_item_mg(), and map_rect_new_mg().
block_idx_count
int block_idx_count
Referenced by map_rect_get_item_mg(), and map_rect_new_mg().
block_lin_count
int block_lin_count extern
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by block_next_lin(), map_rect_get_item_mg(), and map_rect_new_mg().
block_mem
int block_mem
Referenced by map_rect_get_item_mg(), and map_rect_new_mg().
country_isonums
struct country_isonum country_isonums[] static
Referenced by mg_country_from_isonum(), mg_country_postal_len(), mg_country_postal_prefix(), and mg_country_to_isonum().
file
char* file[] static
Initial value:
= {
    [file_border_ply] = "border.ply",
    [file_bridge_ply] = "bridge.ply",
    [file_build_ply] = "build.ply",
    [file_golf_ply] = "golf.ply",
    [file_height_ply] = "height.ply",
    [file_natpark_ply] = "natpark.ply",
    [file_nature_ply] = "nature.ply",
    [file_other_ply] = "other.ply",
    [file_rail_ply] = "rail.ply",
    [file_sea_ply] = "sea.ply",
    [file_street_bti] = "street.bti",
    [file_street_str] = "street.str",
    [file_strname_stn] = "strname.stn",
    [file_town_twn] = "town.twn",
    [file_tunnel_ply] = "tunnel.ply",
    [file_water_ply] = "water.ply",
    [file_woodland_ply] = "woodland.ply",
}
map_id
int map_id static
Referenced by map_new_mg().
map_methods_mg
struct map_methods map_methods_mg static
Initial value:
= {
    projection_mg,
    "iso8859-1",
    map_destroy_mg,
    map_rect_new_mg,
    map_rect_destroy_mg,
    map_rect_get_item_mg,
    map_rect_get_item_byid_mg,
    map_search_new_mg,
    map_search_destroy_mg,
    map_search_get_item_mg,
}
Referenced by map_new_mg().
maps
GList* maps
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by org.navitproject.navit.NavitMapDownloader::getAvailableMaps(), map_new_mg(), map_search_setup(), navit_destroy(), and phase1_map().
poly_ranges
struct item_range poly_ranges[]
Initial value:
= {
    {type_border_country, type_water_line },
    {type_street_unkn,    type_street_unkn},
    {type_area,           type_last       },
}
Referenced by file_next().
street_ranges
struct item_range street_ranges[]
Initial value:
= {
    {type_street_nopass, type_street_unkn},
}
Referenced by file_next().
town_ranges
struct item_range town_ranges[]
Initial value:
= {
    {type_town_label, type_port_label},
}
Referenced by file_next().