navit: map.h File Reference
map.h File Reference
Contains exported functions / structures for map.c.
#include "coord.h"
#include "point.h"
#include "layer.h"
#include "debug.h"
Data Structures
struct map_selection
Used to select data from a map.
struct map_methods
Holds all functions a map plugin has to implement to be useable.
Macros
#define WORLD_BOUNDINGBOX_MIN_X -20000000
#define WORLD_BOUNDINGBOX_MAX_X 20000000
#define WORLD_BOUNDINGBOX_MIN_Y -20000000
#define WORLD_BOUNDINGBOX_MAX_Y 20000000
Functions
struct map * map_new (struct attr *parent, struct attr **attrs)
Opens a new map.
struct map * map_ref (struct map *m)
void map_unref (struct map *m)
int map_get_attr (struct map *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
Gets an attribute from a map.
int map_set_attr (struct map *this_, struct attr *attr)
Sets an attribute of a map.
void map_add_callback (struct map *this_, struct callback *cb)
Registers a new callback for attribute-change.
void map_remove_callback (struct map *this_, struct callback *cb)
Removes a callback from the list of attribute-change callbacks.
int map_requires_conversion (struct map *this_)
Checks if strings from a map have to be converted.
char * map_convert_string_tmp (struct map *this_, char *str)
Converts a string from a map into a temporary allocated buffer. Conversion is not performed and original string is returned if map doesn't require conversion. So lifetime of returned value is very limited.
char * map_convert_string (struct map *this_, char *str)
Converts a string from a map.
char * map_convert_dup (char *str)
void map_convert_free (char *str)
Frees the memory allocated for a converted string.
enum projection map_projection (struct map *this_)
Returns the projection of a map.
void map_set_projection (struct map *this_, enum projection pro)
Sets the projection of a map.
void map_destroy (struct map *m)
Destroys an opened map.
struct map_rect * map_rect_new (struct map *m, struct map_selection *sel)
Creates a new map rect.
struct item * map_rect_get_item (struct map_rect *mr)
Gets the next item from a map rect.
struct item * map_rect_get_item_byid (struct map_rect *mr, int id_hi, int id_lo)
Returns the item specified by the ID.
struct item * map_rect_create_item (struct map_rect *mr, enum item_type type_)
void map_rect_destroy (struct map_rect *mr)
Destroys a map rect.
struct map_search * map_search_new (struct map *m, struct item *item, struct attr *search_attr, int partial)
Starts a search on a map.
struct item * map_search_get_item (struct map_search *this_)
Returns an item from a map search.
void map_search_destroy (struct map_search *this_)
Destroys a map search struct.
struct map_selection * map_selection_rect_new (struct pcoord *center, int distance, int order)
Creates a new rectangular map selection.
struct map_selection * map_selection_dup_pro (struct map_selection *sel, enum projection from, enum projection to)
Duplicates a map selection, transforming coordinates.
struct map_selection * map_selection_dup (struct map_selection *sel)
Duplicates a map selection.
void map_selection_destroy (struct map_selection *sel)
Destroys a map selection.
int map_selection_contains_item_rect (struct map_selection *sel, struct item *item)
Checks if a selection contains a rectangle containing an item.
int map_selection_contains_item_range (struct map_selection *sel, int follow, struct item_range *range, int count)
Checks if a selection contains a item range.
int map_selection_contains_item (struct map_selection *sel, int follow, enum item_type type)
Checks if a selection contains a item.
int map_priv_is (struct map *map, struct map_priv *priv)
Checks if a pointer points to the private data of a map.
void map_dump_filedesc (struct map *map, FILE *out)
void map_dump_file (struct map *map, const char *file)
void map_dump (struct map *map)
void map_destroy_do (struct map *m)
struct maps * maps_new (struct attr *parent, struct attr **attrs)
Detailed Description
Contains exported functions / structures for map.c.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
You should have received a copy of the GNU Library General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
This file contains code that works together with map.c and that is exported to other modules.
Function Documentation
void map_add_callback (struct map * this_, struct callback * cb)
Registers a new callback for attribute-change.
This function registers a new callback function that should be called if the attributes of the map change.
Parameters
this_ The map to associate the callback with
cb The callback to add
References map::attr_cbl.
void map_convert_free (char * str)
Frees the memory allocated for a converted string.
Parameters
str The string to be freed
char* map_convert_string (struct map * this_, char * str)
Converts a string from a map.
Parameters
this_ The map the string to be converted is from
str The string to be converted
Returns
The converted string. It has to be map_convert_free()d after use.
References map_convert_string_tmp().
Referenced by Backend::get_pois().
char* map_convert_string_tmp (struct map * this_, char * str)
Converts a string from a map into a temporary allocated buffer. Conversion is not performed and original string is returned if map doesn't require conversion. So lifetime of returned value is very limited.
Parameters
this_ The map the string to be converted is from
str The string to be converted
Returns
The converted string. Don't care about it after use.
References map_methods::charset, and map::meth.
Referenced by map_convert_string().
void map_destroy (struct map * m)
Destroys an opened map.
Parameters
m The map to be destroyed
References map::attr_cbl, map_methods::map_destroy, map::meth, and map::priv.
Referenced by map_new().
int map_get_attr (struct map * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
Gets an attribute from a map.
Parameters
this_ The map the attribute should be read from
type The type of the attribute to be read
attr Pointer to an attrib-structure where the attribute should be written to
iter (NOT IMPLEMENTED) Used to iterate through all attributes of a type. Set this to NULL to get the first attribute, set this to an attr_iter to get the next attribute
Returns
True if the attribute type was found, false if not
References map::meth, and map::priv.
Referenced by Backend::get_maps(), mapset_get_map_by_name(), mapset_next(), and mapset_search_get_item().
struct map* map_new (struct attr * parent, struct attr ** attrs)
Opens a new map.
This function opens a new map based on the attributes passed. This function takes the attribute "attr_type" to determine which type of map to open and passes all attributes to the map plugin's function that was specified in the plugin_register_new_map_type()-call.
Note that every plugin should accept an attribute of type "attr_data" to be passed with the filename of the map to be opened as value.
Parameters
attrs Attributes specifying which map to open, see description
Returns
The opened map or NULL on failure
References map::attr_cbl, map_destroy(), map::meth, and map::priv.
int map_priv_is (struct map * map, struct map_priv * priv)
Checks if a pointer points to the private data of a map.
Parameters
map The map whose private data should be checked.
priv The private data that should be checked.
Returns
True if priv is the private data of map
References map::priv.
enum projection map_projection (struct map * this_)
Returns the projection of a map.
Parameters
this_ The map to return the projection of
Returns
The projection of the map
References map::meth, and map_methods::pro.
Referenced by Backend::get_pois().
void map_rect_destroy (struct map_rect * mr)
Destroys a map rect.
Parameters
mr The map rect to be destroyed
References map_rect::m, map_methods::map_rect_destroy, map::meth, and map_rect::priv.
Referenced by Backend::get_pois(), and route_get_destination_description().
struct item* map_rect_get_item (struct map_rect * mr)
Gets the next item from a map rect.
Returns an item from a map rect and advances the "item pointer" one step further, so that at the next call the next item is returned. Returns NULL if there are no more items.
Parameters
mr The map rect to return an item from
Returns
An item from the map rect
References map_rect::m, item::map, map_methods::map_rect_get_item, map::meth, and map_rect::priv.
Referenced by Backend::get_pois().
struct item* map_rect_get_item_byid (struct map_rect * mr, int id_hi, int id_lo)
Returns the item specified by the ID.
Parameters
mr The map rect to search for the item
id_hi High part of the ID to be found
id_lo Low part of the ID to be found
Returns
The item with the specified ID or NULL if not found
References map_rect::m, item::map, map_methods::map_rect_get_item_byid, map::meth, and map_rect::priv.
Referenced by route_get_destination_description().
struct map_rect* map_rect_new (struct map * m, struct map_selection * sel)
Creates a new map rect.
This creates a new map rect, which can be used to retrieve items from a map. If sel is a linked-list of selections, all of them will be used. If you pass NULL as sel, this means "get me the whole map".
Parameters
m The map to build the rect on
sel Map selection to choose the rectangle - may be NULL, see description
Returns
A new map rect
References map_rect::m, map_methods::map_rect_new, map::meth, map::priv, and map_rect::priv.
Referenced by Backend::get_pois(), and route_get_destination_description().
void map_remove_callback (struct map * this_, struct callback * cb)
Removes a callback from the list of attribute-change callbacks.
This function removes one callback from the list of callbacks functions that should be called when attributes of the map change.
Parameters
this_ The map to remove the callback from
cb The callback to remove
References map::attr_cbl.
int map_requires_conversion (struct map * this_)
Checks if strings from a map have to be converted.
Parameters
this_ Map to be checked for the need to convert strings
Returns
True if strings from the map have to be converted, false otherwise
References map_methods::charset, and map::meth.
void map_search_destroy (struct map_search * this_)
Destroys a map search struct.
Parameters
this_ The map search struct to be destroyed
References map_methods::charset, map_methods::map_search_destroy, and map::meth.
Referenced by mapset_search_destroy(), and mapset_search_get_item().
struct item* map_search_get_item (struct map_search * this_)
Returns an item from a map search.
This returns an item of the result of a search on a map and advances the "item pointer" one step, so that at the next call the next item will be returned. If there are no more items in the result NULL is returned.
Parameters
this_ Map search struct of the search
Returns
One item of the result
References item::map, map_methods::map_search_get_item, and map::meth.
Referenced by mapset_search_get_item().
struct map_search* map_search_new (struct map * m, struct item * item, struct attr * search_attr, int partial)
Starts a search on a map.
This function starts a search on a map. What attributes one can search for depends on the map plugin.
The OSM/binfile plugin currently supports: attr_town_name, attr_street_name The MG plugin currently supports: ttr_town_postal, attr_town_name, attr_street_name
If you enable partial matches bear in mind that the search matches only the begin of the strings - a search for a street named "street" would match to "streetfoo", but not to "somestreet". Search is case insensitive.
The item passed to this function specifies a "superior item" to "search within" - e.g. a town in which we want to search for a street, or a country in which to search for a town.
Please also note that the search for countries is not handled by map plugins but by navit internally - have a look into country.c for details. Because of that every map plugin has to accept a country item to be passed as "superior item".
Note: If you change something here, please make sure to also update the documentation of mapset_search_new() in mapset.c!
Parameters
m The map that should be searched
item Specifies a superior item to "search within" (see description)
search_attr Attribute specifying what to search for. See description.
partial Set this to true to also have partial matches. See description.
Returns
A new map search struct for this search
References map_methods::charset, map_methods::map_search_new, map::meth, and map::priv.
Referenced by mapset_search_get_item().
int map_selection_contains_item (struct map_selection * sel, int follow, enum item_type type)
Checks if a selection contains a item.
This function checks if a selection contains a item type
Parameters
sel The selection to be checked
follow Whether the next pointer of the selection should be followed
item The item type to be checked
Returns
True if there is a match, false otherwise
References map_selection::next, and map_selection::range.
int map_selection_contains_item_range (struct map_selection * sel, int follow, struct item_range * range, int count)
Checks if a selection contains a item range.
This function checks if a selection contains at least one of the items in range
Parameters
sel The selection to be checked
follow Whether the next pointer of the selection should be followed
ranges The item ranges to be checked the number of elements in ranges
Returns
True if there is a match, false otherwise
References map_selection::next, and map_selection::range.
int map_selection_contains_item_rect (struct map_selection * sel, struct item * item)
Checks if a selection contains a rectangle containing an item.
This function checks if a selection contains a rectangle which exactly contains an item. The rectangle is automatically built around the given item.
Parameters
sel The selection to be checked
item The item that the rectangle should be built around
Returns
True if the rectangle is within the selection, false otherwise
void map_selection_destroy (struct map_selection * sel)
Destroys a map selection.
Parameters
sel The map selection to be destroyed
References map_selection::next.
Referenced by Backend::get_pois().
struct map_selection* map_selection_dup (struct map_selection * sel)
Duplicates a map selection.
Parameters
sel The map selection to duplicate
Returns
The duplicated map selection
References map_selection_dup_pro().
struct map_selection* map_selection_dup_pro (struct map_selection * sel, enum projection from, enum projection to)
Duplicates a map selection, transforming coordinates.
This duplicates a map selection and at the same time transforms the internal coordinates of the selection from one projection to another.
Parameters
sel The map selection to be duplicated
from The projection used for the selection at the moment
to The projection that should be used for the duplicated selection
Returns
A duplicated, transformed map selection
References map_selection::c_rect, and map_selection::next.
Referenced by Backend::get_pois(), and map_selection_dup().
struct map_selection* map_selection_rect_new (struct pcoord * center, int distance, int order)
Creates a new rectangular map selection.
Parameters
center Coordinates of the center of the new rectangle
distance Distance of the rectangle's borders from the center
order Desired order of the new selection
Returns
The new map selection
References map_selection::c_rect, map_selection::order, map_selection::range, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by Backend::get_pois().
int map_set_attr (struct map * this_, struct attr * attr)
Sets an attribute of a map.
This sets an attribute of a map, overwriting an attribute of the same type if it already exists. This function also calls all the callbacks that are registred to be called when attributes change.
Parameters
this_ The map to set the attribute of
attr The attribute to set
Returns
True if the attr could be set, false otherwise
References map::attr_cbl, map::meth, and map::priv.
void map_set_projection (struct map * this_, enum projection pro)
Sets the projection of a map.
Parameters
this_ The map to set the projection of
pro The projection to be set
References map::meth, and map_methods::pro.