navit: maps.c File Reference
maps.c File Reference
#include <glib.h>
#include "item.h"
#include "debug.h"
#include "file.h"
#include "map.h"
#include "mapset.h"
#include "xmlconfig.h"
Functions
struct maps * maps_new (struct attr *parent, struct attr **attrs)
Variables
struct object_func maps_func
Function Documentation
struct maps* maps_new (struct attr * parent, struct attr ** attrs)
References attr_generic_add_attr(), attr_list_dup(), attr_list_free(), attr_search(), data, dbg, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), g_free(), g_strdup(), i, lvl_debug, lvl_error, attr::map, map_new(), attr::mapset, mapset_add_attr(), name, attr::navit_object, navit_object_unref(), NULL, attr::str, attr::type, and attr::u.
Variable Documentation
struct object_func maps_func
Initial value:
= {
        attr_maps,
        (object_func_new)maps_new,
        (object_func_get_attr)NULL,
        (object_func_iter_new)NULL,
        (object_func_iter_destroy)NULL,
        (object_func_set_attr)NULL,
        (object_func_add_attr)NULL,
        (object_func_remove_attr)NULL,
        (object_func_init)NULL,
        (object_func_destroy)NULL,
        (object_func_dup)NULL,
        (object_func_ref)NULL,
        (object_func_unref)NULL,
}
Referenced by object_func_lookup().