navit: maptype.c File Reference
maptype.c File Reference
#include <glib.h>
#include "debug.h"
#include "projection.h"
#include "item.h"
#include "map.h"
#include "maptype.h"
Functions
void maptype_register (char *name, struct map_priv *(*map_new)(struct map_methods *meth, char *data, char **charset, enum projection *pro))
struct maptype * maptype_get (const char *name)
Variables
static struct maptype * maptype_root
Function Documentation
struct maptype* maptype_get (const char * name)
References g_ascii_strcasecmp(), maptype_root, maptype::name, maptype::next, and NULL.
void maptype_register (char * name, struct map_priv *(*)(struct map_methods *meth, char *data, char **charset, enum projection *pro) map_new)
References g_new, g_strdup(), maptype::map_new, map_new(), maptype_root, maptype::name, and maptype::next.
Variable Documentation
struct maptype* maptype_root static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by maptype_get(), and maptype_register().