navit: maptool/misc.c File Reference
misc.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <assert.h>
#include <string.h>
#include <signal.h>
#include <stdio.h>
#include <math.h>
#include <getopt.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <zlib.h>
#include "file.h"
#include "item.h"
#include "map.h"
#include "main.h"
#include "config.h"
#include "zipfile.h"
#include "linguistics.h"
#include "plugin.h"
#include "maptool.h"
Macros
#define _FILE_OFFSET_BITS 64
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
#define phase1_coord_max 16384
Functions
void bbox_extend (struct coord *c, struct rect *r)
void bbox (struct coord *c, int count, struct rect *r)
int contains_bbox (int xl, int yl, int xh, int yh, struct rect *r)
int bbox_contains_coord (struct rect *r, struct coord *c)
int bbox_contains_bbox (struct rect *out, struct rect *in)
long long bbox_area (struct rect const *r)
void phase1_map (GList *maps, FILE *out_ways, FILE *out_nodes)
int item_order_by_type (enum item_type type)
static int filter_unknown (struct item_bin *ib)
static void phase34_process_file (struct tile_info *info, FILE *in, FILE *reference)
static void phase34_process_file_range (struct tile_info *info, FILE *in, FILE *reference)
static int phase34 (struct tile_info *info, struct zip_info *zip_info, FILE **in, FILE **reference, int in_count, int with_range)
void dump (FILE *in)
int phase4 (FILE **in, int in_count, int with_range, char *suffix, FILE *tilesdir_out, struct zip_info *zip_info)
static int process_slice (FILE **in, FILE **reference, int in_count, int with_range, long long size, char *suffix, struct zip_info *zip_info)
int phase5 (FILE **in, FILE **references, int in_count, int with_range, char *suffix, struct zip_info *zip_info)
void process_binfile (FILE *in, FILE *out)
void add_aux_tiles (char *name, struct zip_info *info)
Variables
struct rect world_bbox
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE
phase1_coord_max
#define phase1_coord_max 16384
Function Documentation
add_aux_tiles()
void add_aux_tiles (char * name, struct zip_info * info)
References add_aux_tile(), info, and name.
Referenced by maptool_assemble_map().
bbox()
void bbox (struct coord * c, int count, struct rect * r)
References bbox_extend(), c, and rect::h.
Referenced by close_polygon(), distance_from_ll(), draw_multiline_osd_text(), find_next(), font_freetype_get_text_bbox(), graphics_draw_text_std(), gui_internal_cmd_map_download(), item_bin_write_clipped(), item_coord_get_within_selection(), itembin_disassemble(), itembin_nicer_slicer(), map_route_occluded_bbox(), ocean_tile(), osd_cmd_interface_draw(), osd_compass_draw(), osd_j1850_draw(), osd_route_guard_draw(), osd_scale_draw(), osd_speed_cam_draw(), osd_speed_warner_draw(), osd_stopwatch_draw(), process_multipolygons_finish(), tile_collector_process_tile(), and tile_write_item_minmax().
bbox_area()
long long bbox_area (struct rect const * r)
References rect::h, coord::x, and coord::y.
bbox_contains_bbox()
int bbox_contains_bbox (struct rect * out, struct rect * in)
References rect::h, coord::x, and coord::y.
Referenced by process_boundaries_insert().
bbox_contains_coord()
int bbox_contains_coord (struct rect * r, struct coord * c)
References c, rect::h, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by boundary_find_matches(), and process_multipolygons_finish().
bbox_extend()
void bbox_extend (struct coord * c, struct rect * r)
References c, rect::h, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by bbox(), item_bin_sort_file(), item_bin_write_match(), load_countries(), process_boundaries_finish(), and process_turn_restrictions_member().
contains_bbox()
int contains_bbox (int xl, int yl, int xh, int yh, struct rect * r)
References rect::h, coord::x, and coord::y.
Referenced by tile().
dump()
void dump (FILE * in)
References dump_itembin(), filter_unknown(), and read_item().
filter_unknown()
static int filter_unknown (struct item_bin * ib) inline static
References ignore_unknown, and item_bin::type.
Referenced by dump(), phase34_process_file(), and phase34_process_file_range().
item_order_by_type()
int item_order_by_type (enum item_type type)
References experimental, max, and type.
Referenced by phase34_process_file(), and process_turn_restrictions_member().
phase1_map()
void phase1_map (GList * maps, FILE * out_ways, FILE * out_nodes)
References init_item(), item, item_attr_get(), item_bin_add_attr(), item_bin_add_coord(), item_bin_write(), item_coord_get(), map_convert_free(), map_convert_string(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), maps, phase1_coord_max, attr::str, attr::type, item::type, and attr::u.
Referenced by osm_read_input_data().
phase34()
static int phase34 (struct tile_info * info, struct zip_info * zip_info, FILE ** in, FILE ** reference, int in_count, int with_range) static
References bytes_read, info, merge_tiles(), phase34_process_file(), phase34_process_file_range(), processed_nodes, processed_nodes_out, processed_relations, processed_tiles, processed_ways, sig_alrm(), sig_alrm_end(), tile_hash, and write_tilesdir().
Referenced by phase4(), and process_slice().
phase34_process_file()
static void phase34_process_file (struct tile_info * info, FILE * in, FILE * reference) static
References filter_unknown(), info, item_bin_get_attr_bin(), item_order_by_type(), max, processed_nodes, processed_ways, read_item(), tile_write_item_minmax(), and item_bin::type.
Referenced by phase34().
phase34_process_file_range()
static void phase34_process_file_range (struct tile_info * info, FILE * in, FILE * reference) static
References filter_unknown(), info, max, processed_nodes, processed_ways, read_item_range(), tile_write_item_minmax(), and item_bin::type.
Referenced by phase34().
phase4()
int phase4 (FILE ** in, int in_count, int with_range, char * suffix, FILE * tilesdir_out, struct zip_info * zip_info)
References info, phase34(), suffix, and tile_info::tilesdir_out.
Referenced by maptool_generate_tiles().
phase5()
int phase5 (FILE ** in, FILE ** references, int in_count, int with_range, char * suffix, struct zip_info * zip_info)
References create_tile_hash(), LONGLONG_FMT, tile_head::next, tile_head::process, process_slice(), size, slice_size, slices, tile_head_root, tile_head::total_size, zip_get_zipnum(), zip_set_zipnum(), and tile_head::zipnum.
Referenced by maptool_assemble_map().
process_binfile()
void process_binfile (FILE * in, FILE * out)
References item_bin_write(), and read_item().
Referenced by main().
process_slice()
static int process_slice (FILE ** in, FILE ** reference, int in_count, int with_range, long long size, char * suffix, struct zip_info * zip_info) static
References dbg_assert, exit, info, tile_head::name, tile_head::next, phase34(), tile_head::process, size, suffix, tile_head_root, tile_head::total_size, tile_head::total_size_used, write_zipmember(), tile_head::zip_data, zip_get_index(), and zip_get_maxnamelen().
Referenced by phase5().
Variable Documentation
world_bbox
struct rect world_bbox
Initial value:
= {
    { WORLD_BOUNDINGBOX_MIN_X, WORLD_BOUNDINGBOX_MIN_Y},
    { WORLD_BOUNDINGBOX_MAX_X, WORLD_BOUNDINGBOX_MAX_Y},
}
Referenced by sort_countries(), tile(), tile_bbox(), and write_tilesdir().