navit: maptool/maptool.c File Reference
maptool.c File Reference
#include "config.h"
#include "navit_lfs.h"
#include <stdlib.h>
#include <glib.h>
#include <assert.h>
#include <string.h>
#include <signal.h>
#include <stdio.h>
#include <math.h>
#include <errno.h>
#include <getopt.h>
#include <unistd.h>
#include <sys/time.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <zlib.h>
#include "file.h"
#include "item.h"
#include "map.h"
#include "main.h"
#include "zipfile.h"
#include "linguistics.h"
#include "plugin.h"
#include "util.h"
#include "maptool.h"
Data Structures
struct maptool_params
Macros
#define SLIZE_SIZE_DEFAULT_GB 1
Functions
static int assafe_lltoa (long long n, int maxlen, char *buf)
static int assafe_strcp2buf (char *str, int maxlen, char *buf)
static void progress_time (void)
static void progress_memory (void)
static void sig_alrm_do (int sig)
void sig_alrm (int sig)
void sig_alrm_end (void)
static struct files_relation_processing * files_relation_processing_new (FILE *line2poi, char *suffix)
static void files_relation_processing_destroy (struct files_relation_processing *files_relproc, char *suffix)
static void add_plugin (char *path)
static void maptool_init (FILE *rule_file)
static void usage (void)
static int parse_option (struct maptool_params *p, char **argv, int argc, int *option_index)
static int start_phase (struct maptool_params *p, char *str)
static void exit_with_error (char *error_message)
static void osm_read_input_data (struct maptool_params *p, char *suffix)
static void osm_count_references (struct maptool_params *p, char *suffix, int clear)
static void osm_resolve_coords_and_split_at_intersections (struct maptool_params *p, char *suffix)
static void osm_process_way2poi (struct maptool_params *p, char *suffix)
static void osm_process_coastlines (struct maptool_params *p, char *suffix)
static void osm_process_turn_restrictions (struct maptool_params *p, char *suffix)
static void osm_process_multipolygons (struct maptool_params *p, char *suffix)
static void maptool_dump (struct maptool_params *p, char *suffix)
static void maptool_generate_tiles (struct maptool_params *p, char *suffix, char **filenames, int filename_count, int first, char *suffix0)
static void maptool_assemble_map (struct maptool_params *p, char *suffix, char **filenames, char **referencenames, int filename_count, int first, int last, char *suffix0)
static void maptool_load_node_table (struct maptool_params *p, int last)
static void maptool_load_countries (struct maptool_params *p)
static void maptool_load_tilesdir (struct maptool_params *p, char *suffix)
int main (int argc, char **argv)
Variables
long long slice_size =SLIZE_SIZE_DEFAULT_GB*1024ll*1024*1024
int attr_debug_level =1
int ignore_unknown = 0
int thread_count =8
GHashTable * dedupe_ways_hash
int phase
int slices
int unknown_country
char ch_suffix [] ="r"
char * experimental_feature_description
int experimental
struct buffer node_buffer
int processed_nodes
int processed_nodes_out
int processed_ways
int processed_relations
int processed_tiles
int overlap =1
int bytes_read
static long start_brk
static struct timespec start_ts
static struct plugins * plugins
int debug_ref =0
Macro Definition Documentation
SLIZE_SIZE_DEFAULT_GB
#define SLIZE_SIZE_DEFAULT_GB 1
Referenced by usage().
Function Documentation
add_plugin()
static void add_plugin (char * path) static
References attr::attrs, file_init(), plugin_new(), attr::plugins, plugins, plugins_new(), attr::str, and attr::u.
Referenced by parse_option().
assafe_lltoa()
static int assafe_lltoa (long long n, int maxlen, char * buf) static
References c.
Referenced by progress_memory(), progress_time(), and sig_alrm_do().
assafe_strcp2buf()
static int assafe_strcp2buf (char * str, int maxlen, char * buf) static
Referenced by progress_memory(), progress_time(), and sig_alrm_do().
exit_with_error()
static void exit_with_error (char * error_message) static
References exit.
Referenced by main(), and osm_read_input_data().
files_relation_processing_destroy()
static void files_relation_processing_destroy (struct files_relation_processing * files_relproc, char * suffix) static
References files_relation_processing::nodes2_in, files_relation_processing::nodes2_out, files_relation_processing::nodes_in, files_relation_processing::nodes_out, tempfile_rename(), files_relation_processing::ways_in, and files_relation_processing::ways_out.
Referenced by main().
files_relation_processing_new()
static struct files_relation_processing* files_relation_processing_new (FILE * line2poi, char * suffix) static
References files_relation_processing::nodes2_in, files_relation_processing::nodes2_out, files_relation_processing::nodes_in, files_relation_processing::nodes_out, tempfile(), files_relation_processing::ways_in, and files_relation_processing::ways_out.
Referenced by main().
main()
int main (int argc, char ** argv)
References maptool_osm::associated_streets, buffer::base, maptool_params::compression_level, maptool_params::countries_loaded, current_to_iso8601(), maptool_params::dump, maptool_params::end, exit, exit_with_error(), experimental, experimental_feature_description, files_relation_processing_destroy(), files_relation_processing_new(), maptool_osm::house_number_interpolations, maptool_params::input, maptool_params::input_file, maptool_params::keep_tmpfiles, maptool_osm::line2poi, linguistics_init(), main_init(), buffer::malloced, maptool_assemble_map(), maptool_dump(), maptool_generate_tiles(), maptool_init(), maptool_load_countries(), maptool_load_node_table(), maptool_load_tilesdir(), maptool_params::max_index_size, maptool_params::node_table_loaded, maptool_params::osm, osm_count_references(), osm_process_coastlines(), osm_process_multipolygons(), osm_process_towns(), osm_process_turn_restrictions(), osm_process_way2poi(), osm_protobufdb_load(), osm_read_input_data(), osm_resolve_coords_and_split_at_intersections(), parse_option(), phase, process_associated_streets(), process_binfile(), process_house_number_interpolations(), maptool_params::process_nodes, maptool_params::process_relations, maptool_params::process_ways, maptool_params::protobufdb, maptool_params::protobufdb_operation, maptool_params::result, maptool_params::rule_file, buffer::size, sort_countries(), maptool_params::start, start_brk, start_phase(), start_ts, suffixes, tempfile(), tempfile_unlink(), maptool_params::tilesdir_loaded, maptool_params::timestamp, usage(), maptool_params::ways_split, and maptool_params::zip64.
maptool_assemble_map()
static void maptool_assemble_map (struct maptool_params * p, char * suffix, char ** filenames, char ** referencenames, int filename_count, int first, int last, char * suffix0) static
References add_aux_tiles(), ch_assemble_map(), ch_suffix, maptool_params::compression_level, exit, index_init(), maptool_params::keep_tmpfiles, map_information_attrs, maptool_params::max_index_size, phase5(), remove_countryfiles(), maptool_params::result, attr::str, tempfile(), tempfile_name(), tempfile_unlink(), maptool_params::timestamp, attr::type, attr::u, maptool_params::url, write_aux_tiles(), write_countrydir(), maptool_params::zip64, zip_close(), zip_get_zipnum(), zip_new(), zip_open(), zip_set_compression_level(), zip_set_maxnamelen(), zip_set_timestamp(), zip_set_zip64(), zip_set_zipnum(), zip_write_directory(), zip_write_index(), and zip_info::zipnum.
Referenced by main().
maptool_dump()
static void maptool_dump (struct maptool_params * p, char * suffix) static
References maptool_params::dump, maptool_params::process_nodes, maptool_params::process_relations, maptool_params::process_ways, and tempfile().
Referenced by main().
maptool_generate_tiles()
static void maptool_generate_tiles (struct maptool_params * p, char * suffix, char ** filenames, int filename_count, int first, char * suffix0) static
References ch_generate_tiles(), ch_suffix, phase4(), tempfile(), maptool_params::timestamp, maptool_params::zip64, zip_get_zipnum(), zip_new(), zip_set_timestamp(), zip_set_zip64(), zip_set_zipnum(), and zip_info::zipnum.
Referenced by main().
maptool_init()
static void maptool_init (FILE * rule_file) static
References osm_init(), and plugins_init().
Referenced by main().
maptool_load_countries()
static void maptool_load_countries (struct maptool_params * p) static
References maptool_params::countries_loaded, and load_countries().
Referenced by main().
maptool_load_node_table()
static void maptool_load_node_table (struct maptool_params * p, int last) static
References load_buffer(), maptool_params::node_table_loaded, sizeof_buffer(), slice_size, and slices.
Referenced by main().
maptool_load_tilesdir()
static void maptool_load_tilesdir (struct maptool_params * p, char * suffix) static
References load_tilesdir(), tempfile(), and maptool_params::tilesdir_loaded.
Referenced by main().
osm_count_references()
static void osm_count_references (struct maptool_params * p, char * suffix, int clear) static
References clear_node_item_buffer(), maptool_params::keep_tmpfiles, load_buffer(), ref_ways(), resolve_ways(), save_buffer(), slice_size, slices, tempfile(), tempfile_rename(), and tempfile_unlink().
Referenced by main().
osm_process_coastlines()
static void osm_process_coastlines (struct maptool_params * p, char * suffix) static
References process_coastlines(), and tempfile().
Referenced by main().
osm_process_multipolygons()
static void osm_process_multipolygons (struct maptool_params * p, char * suffix) static
References maptool_params::keep_tmpfiles, maptool_osm::multipolygons, maptool_params::osm, process_multipolygons(), tempfile(), tempfile_unlink(), and maptool_params::ways_split.
Referenced by main().
osm_process_turn_restrictions()
static void osm_process_turn_restrictions (struct maptool_params * p, char * suffix) static
References maptool_params::keep_tmpfiles, maptool_params::osm, process_turn_restrictions(), tempfile(), tempfile_unlink(), maptool_osm::turn_restrictions, and maptool_params::ways_split.
Referenced by main().
osm_process_way2poi()
static void osm_process_way2poi (struct maptool_params * p, char * suffix) static
References process_way2poi(), and tempfile().
Referenced by main().
osm_read_input_data()
static void osm_read_input_data (struct maptool_params * p, char * suffix) static
References maptool_osm::associated_streets, maptool_osm::boundaries, maptool_params::dbstr, exit, exit_with_error(), flush_nodes(), maptool_osm::house_number_interpolations, maptool_params::input_file, maptool_osm::line2poi, map_collect_data_osm(), map_collect_data_osm_db(), map_collect_data_osm_o5m(), map_collect_data_osm_protobuf(), map_destroy(), maptool_params::map_handles, maptool_osm::multipolygons, maptool_osm::nodes, maptool_params::o5m, maptool_params::osm, phase1_map(), maptool_osm::poly2poi, maptool_params::process_nodes, maptool_params::process_relations, maptool_params::process_ways, maptool_params::protobuf, buffer::size, tempfile(), maptool_osm::towns, maptool_osm::turn_restrictions, and maptool_osm::ways.
Referenced by main().
osm_resolve_coords_and_split_at_intersections()
static void osm_resolve_coords_and_split_at_intersections (struct maptool_params * p, char * suffix) static
References maptool_params::keep_tmpfiles, load_buffer(), map_resolve_coords_and_split_at_intersections(), slice_size, slices, tempfile(), tempfile_rename(), tempfile_unlink(), and maptool_params::ways_split.
Referenced by main().
parse_option()
static int parse_option (struct maptool_params * p, char ** argv, int argc, int * option_index) static
References add_plugin(), attr_debug_level, attr_from_line(), attr_new_from_text(), attr::attrs, c, maptool_params::compression_level, maptool_params::dbstr, dedupe_ways_hash, maptool_params::dump, maptool_params::dump_coordinates, maptool_params::end, exit, experimental, ignore_unknown, maptool_params::input, maptool_params::input_file, maptool_params::keep_tmpfiles, maptool_params::map_handles, map_new(), maptool_params::max_index_size, maptool_params::o5m, startup::pos, maptool_params::process_nodes, maptool_params::process_relations, maptool_params::process_ways, maptool_params::protobuf, maptool_params::protobufdb, maptool_params::protobufdb_operation, maptool_params::rule_file, slice_size, maptool_params::start, thread_count, maptool_params::timestamp, unknown_country, maptool_params::url, and maptool_params::zip64.
Referenced by main().
progress_memory()
static void progress_memory (void) static
References assafe_lltoa(), assafe_strcp2buf(), dbg, lvl_warning, startup::pos, and start_brk.
Referenced by sig_alrm_do(), and start_phase().
progress_time()
static void progress_time (void) static
References assafe_lltoa(), assafe_strcp2buf(), dbg, lvl_warning, startup::pos, and start_ts.
Referenced by sig_alrm_do(), and start_phase().
sig_alrm()
void sig_alrm (int sig)
References sig_alrm_do().
Referenced by map_collect_data_osm(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), osm_protobufdb_load(), phase34(), process_multipolygons(), process_turn_restrictions(), and zip_write_directory().
sig_alrm_do()
static void sig_alrm_do (int sig) static
References assafe_lltoa(), assafe_strcp2buf(), dbg, lvl_warning, phase, startup::pos, processed_nodes, processed_nodes_out, processed_relations, processed_tiles, processed_ways, progress_memory(), and progress_time().
Referenced by sig_alrm().
sig_alrm_end()
void sig_alrm_end (void)
Referenced by map_collect_data_osm(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), phase34(), process_multipolygons(), and process_turn_restrictions().
start_phase()
static int start_phase (struct maptool_params * p, char * str) static
References maptool_params::end, phase, progress_memory(), progress_time(), and maptool_params::start.
Referenced by main().
usage()
static void usage (void) static
References exit, experimental_feature_description, and SLIZE_SIZE_DEFAULT_GB.
Referenced by main().
Variable Documentation
attr_debug_level
int attr_debug_level =1
Referenced by osm_add_tag(), and parse_option().
bytes_read
int bytes_read
Referenced by osm_process_towns(), phase34(), read_item(), and wince_reader_thread().
ch_suffix
char ch_suffix[] ="r"
Referenced by maptool_assemble_map(), and maptool_generate_tiles().
debug_ref
int debug_ref =0
dedupe_ways_hash
GHashTable* dedupe_ways_hash
Referenced by osm_end_way(), and parse_option().
experimental
int experimental
Indicates if experimental features (if available) were enabled.
Referenced by item_order_by_type(), main(), and parse_option().
experimental_feature_description
char* experimental_feature_description
Initial value:
=
    "Move coastline data to order 6 tiles. Makes map look more smooth, but may affect drawing/searching performance."
Textual description of available experimental features, or NULL (=none available).
Referenced by main(), and usage().
ignore_unknown
int ignore_unknown = 0
Referenced by filter_unknown(), and parse_option().
node_buffer
struct buffer node_buffer
Initial value:
= {
    64*1024*1024,
}
Referenced by allocate_node_item_in_buffer(), clear_node_item_buffer(), flush_nodes(), node_buffer_to_hash(), node_item_find_index_in_ordered_list(), node_item_get(), osm_add_node(), and remove_last_node_item_from_buffer().
overlap
int overlap =1
Referenced by index_submap_add(), item_bin_write_match(), itembin_nicer_slicer(), process_turn_restrictions_finish(), tile_bbox(), tile_write_item_minmax(), and write_countrydir().
phase
int phase
Referenced by CreateBitmapFromXpm(), main(), sig_alrm_do(), and start_phase().
plugins
struct plugins* plugins static
Referenced by add_plugin().
processed_nodes
int processed_nodes
Referenced by map_collect_data_osm(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), osm_protobufdb_load(), phase34(), phase34_process_file(), phase34_process_file_range(), and sig_alrm_do().
processed_nodes_out
int processed_nodes_out
Referenced by map_resolve_coords_and_split_at_intersections(), osm_end_node(), osm_process_towns(), phase34(), and sig_alrm_do().
processed_relations
int processed_relations
Referenced by map_collect_data_osm(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), osm_protobufdb_load(), phase34(), process_boundaries_setup(), process_multipolygons(), process_multipolygons_finish(), process_multipolygons_setup_worker(), process_turn_restrictions(), process_turn_restrictions_finish(), process_turn_restrictions_setup_worker(), and sig_alrm_do().
processed_tiles
int processed_tiles
Referenced by map_resolve_coords_and_split_at_intersections(), merge_tiles(), osm_process_towns(), phase34(), sig_alrm_do(), tile_extend(), and write_tilesdir().
processed_ways
int processed_ways
Referenced by map_collect_data_osm(), map_resolve_coords_and_split_at_intersections(), osm_process_towns(), osm_protobufdb_load(), phase34(), phase34_process_file(), phase34_process_file_range(), process_multipolygons(), process_multipolygons_member(), process_turn_restrictions(), sig_alrm_do(), and write_item_way_subsection().
slice_size
long long slice_size =SLIZE_SIZE_DEFAULT_GB*1024ll*1024*1024
Referenced by allocate_node_item_in_buffer(), flush_nodes(), maptool_load_node_table(), osm_count_references(), osm_resolve_coords_and_split_at_intersections(), parse_option(), and phase5().
slices
int slices
Referenced by flush_nodes(), maptool_load_node_table(), osm_count_references(), osm_resolve_coords_and_split_at_intersections(), and phase5().
start_brk
long start_brk static
Referenced by main(), and progress_memory().
start_ts
struct timespec start_ts static
Referenced by main(), and progress_time().
thread_count
int thread_count =8
Referenced by parse_option(), process_multipolygons(), process_multipolygons_setup(), process_turn_restrictions(), and process_turn_restrictions_setup().
unknown_country
int unknown_country
Referenced by osm_process_towns(), and parse_option().