navit: support/espeak/mbrolib.h File Reference
mbrolib.h File Reference
Data Structures
struct mbrolib_parameter
struct mbrolib_voice
Typedefs
typedef void *(t_mbrolib_init)(int)
typedef const mbrolib_voice **(t_mbrolib_list_voices)(void *)
typedef MBROLIB_ERROR(t_mbrolib_set_voice)(void *, const char *)
typedef MBROLIB_ERROR(t_mbrolib_get_parameter)(void *, mbrolib_parameter *)
typedef MBROLIB_ERROR(t_mbrolib_set_parameter)(void *, const mbrolib_parameter *)
typedef MBROLIB_ERROR(t_mbrolib_write)(void *, const char *, size_t)
typedef MBROLIB_ERROR(t_mbrolib_read)(void *, short *, int, int *)
typedef void(t_mbrolib_flush)(void *)
typedef MBROLIB_ERROR(t_mbrolib_terminate)(void *)
Enumerations
enum MBROLIB_ERROR {
MBROLIB_OK =0, MBROLIB_DATABASE_NOT_INSTALLED, MBROLIB_INVAL, MBROLIB_OUT_OF_MEMORY,
MBROLIB_OUT_OF_RANGE, MBROLIB_READ_ERROR, MBROLIB_WRITE_ERROR
}
enum MBROLIB_GENDER { MBROLIB_FEMALE, MBROLIB_MALE }
Functions
void * mbrolib_init (int sample_rate)
const mbrolib_voice ** mbrolib_list_voices (void *the_handle)
MBROLIB_ERROR mbrolib_set_voice (void *the_handle, const char *the_name)
MBROLIB_ERROR mbrolib_get_parameter (void *the_handle, mbrolib_parameter *the_parameter)
MBROLIB_ERROR mbrolib_set_parameter (void *the_handle, const mbrolib_parameter *the_parameter)
MBROLIB_ERROR mbrolib_write (void *the_handle, const char *the_mbrola_phonemes, size_t the_size)
MBROLIB_ERROR mbrolib_read (void *the_handle, short *the_samples, int the_max_size, int *the_read_size)
void mbrolib_flush (void *the_handle)
MBROLIB_ERROR mbrolib_terminate (void *the_handle)
Typedef Documentation
typedef void(t_mbrolib_flush)(void *)
typedef MBROLIB_ERROR(t_mbrolib_get_parameter)(void *, mbrolib_parameter *)
typedef void*(t_mbrolib_init)(int)
typedef const mbrolib_voice**(t_mbrolib_list_voices)(void *)
typedef MBROLIB_ERROR(t_mbrolib_read)(void *, short *, int, int *)
typedef MBROLIB_ERROR(t_mbrolib_set_parameter)(void *, const mbrolib_parameter *)
typedef MBROLIB_ERROR(t_mbrolib_set_voice)(void *, const char *)
typedef MBROLIB_ERROR(t_mbrolib_terminate)(void *)
typedef MBROLIB_ERROR(t_mbrolib_write)(void *, const char *, size_t)
Enumeration Type Documentation
enum MBROLIB_ERROR
Returned errors
Enumerator
MBROLIB_OK
MBROLIB_DATABASE_NOT_INSTALLED
MBROLIB_INVAL
MBROLIB_OUT_OF_MEMORY
MBROLIB_OUT_OF_RANGE
MBROLIB_READ_ERROR
MBROLIB_WRITE_ERROR
enum MBROLIB_GENDER
Gender
Enumerator
MBROLIB_FEMALE
MBROLIB_MALE
Function Documentation
void mbrolib_flush (void * the_handle)
Flush
Parameters
the_handle.
MBROLIB_ERROR mbrolib_get_parameter (void * the_handle, mbrolib_parameter * the_parameter)
Get the current database parameters. The caller supplies a pointer to an already allocated structure.
Parameters
the_handle previously given by mbrolib_init.
the_parameters pointer to the structure.
Returns
error code (MBROLIB_OK, MBROLIB_INVAL).
Referenced by LoadMbrolaTable().
void* mbrolib_init (int sample_rate)
Initialization, returns a new handle. First function.
Parameters
the_sample_rate output rate in Hz (for example 22050). If 0, keep the original database rate.
Returns
handle (or NULL if error).
Referenced by LoadMbrolaTable().
const mbrolib_voice** mbrolib_list_voices (void * the_handle)
Returns the list of the installed mbrola databases. The databases are searched according to the MBROLA_PATH environment variable if set, or under a default path otherwise (see MBROLA_PATH in mbrolib.c).
An array of voices is returned. The last item is set to NULL. The caller must not free the returned items or the array.
Parameters
the_handle previously given by mbrolib_init.
Returns
An array of voices.
MBROLIB_ERROR mbrolib_read (void * the_handle, short * the_samples, int the_max_size, int * the_read_size)
Read n bytes of the output samples.
Parameters
the_handle.
the_samples (raw audio data, 16bits, mono).
the_size max number of int16 to read.
the_size number of int16 read.
Returns
error code (MBROLIB_OK, MBROLIB_INVAL, MBROLIB_READ_ERROR).
MBROLIB_ERROR mbrolib_set_parameter (void * the_handle, const mbrolib_parameter * the_parameter)
Set the database parameters using the supplied data.
Parameters
the_handle previously given by mbrolib_init.
the_parameters pointer to the wished parameters.
Returns
error code (MBROLIB_OK, MBROLIB_INVAL).
Referenced by LoadMbrolaTable().
MBROLIB_ERROR mbrolib_set_voice (void * the_handle, const char * the_name)
Set voice
Parameters
the_handle.
the_database (for example, "en1").
Returns
error code (MBROLIB_OK, MBROLIB_DATABASE_NOT_INSTALLED, MBROLIB_INVAL).
Referenced by LoadMbrolaTable().
MBROLIB_ERROR mbrolib_terminate (void * the_handle)
Release the handle
Parameters
the_handle.
Returns
error code (MBROLIB_OK, MBROLIB_INVAL).
MBROLIB_ERROR mbrolib_write (void * the_handle, const char * the_mbrola_phonemes, size_t the_size)
Write the mbrola phonemes in the internal buffer.
Parameters
the_handle.
the_mbrola_phonemes.
the_size in bytes.
Returns
error code (MBROLIB_OK, MBROLIB_INVAL, MBROLIB_WRITE_ERROR, MBROLIB_READ_ERROR).