navit: menu.h File Reference
menu.h File Reference
Data Structures
struct menu_methods
struct menu
Enumerations
enum menu_type { menu_type_submenu, menu_type_menu, menu_type_toggle }
Functions
struct menu * menu_add (struct menu *menu, char *name, enum menu_type type, struct callback *cb)
void menu_popup (struct menu *menu)
Enumeration Type Documentation
enum menu_type
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
You should have received a copy of the GNU Library General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Enumerator
menu_type_submenu
menu_type_menu
menu_type_toggle
Function Documentation
struct menu* menu_add (struct menu * menu, char * name, enum menu_type type, struct callback * cb)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References menu_methods::add, g_free(), g_new0, menu::meth, NULL, and menu::priv.
Referenced by popup_printf_cb().
void menu_popup (struct menu * menu)
References menu::meth, menu_methods::popup, and menu::priv.
Referenced by popup().