navit: messages.h File Reference
messages.h File Reference
Data Structures
struct message
Functions
int message_new (struct messagelist *this_, const char *message)
int message_delete (struct messagelist *this_, int mid)
struct messagelist * messagelist_new (struct attr **attrs)
void messagelist_init (struct messagelist *this_)
struct message * message_get (struct messagelist *this_)
Function Documentation
int message_delete (struct messagelist * this_, int mid)
References g_free(), message::id, messagelist::messages, message::next, NULL, and message::text.
struct message* message_get (struct messagelist * this_)
References messagelist::messages.
Referenced by navit_get_messages().
int message_new (struct messagelist * this_, const char * message)
References g_new0, g_strdup(), message::id, messagelist::last_mid, messagelist::messages, message::next, NULL, message::text, time(), and message::time.
Referenced by navit_add_message().
void messagelist_init (struct messagelist * this_)
References callback_cast, callback_new_1, event_add_timeout(), event_system(), message_cleanup(), messagelist::msg_cleanup_cb, and messagelist::msg_cleanup_to.
Referenced by navit_init().
struct messagelist* messagelist_new (struct attr ** attrs)
References attr_generic_get_attr(), g_new0, NULL, attr::num, and attr::u.
Referenced by navit_new().