navit: support/libc/mkdir.c File Reference
mkdir.c File Reference
#include <windows.h>
#include <io.h>
Functions
int _mkdir (const char *dirname)
int mkdir (const char *dirname)
Function Documentation
int _mkdir (const char * dirname)
References NULL.
Referenced by mkdir().
int mkdir (const char * dirname)
References _mkdir().
Referenced by file_mkdir(), org.navitproject.navit.NavitMapDownloader::getDestinationFile(), and log_new().