navit: eval Namespace Reference
eval Namespace Reference
Variables
tuple bus = dbus.SessionBus()
tuple conn
tuple iface = dbus.Interface(conn, dbus_interface='org.navit_project.navit')
tuple iter = iface.attr_iter()
tuple navit = bus.get_object('org.navit_project.navit', conn.get_attr_wi('navit',iter)[1])
tuple navit_iface = dbus.Interface(navit, dbus_interface='org.navit_project.navit.navit')
Variable Documentation
tuple eval.bus = dbus.SessionBus()
tuple eval.conn
Initial value:
 = bus.get_object('org.navit_project.navit',
                        '/org/navit_project/navit')
Referenced by speechd_destroy(), speechd_new(), speechd_say(), and vehicle_gypsy_new_gypsy().
tuple eval.iface = dbus.Interface(conn, dbus_interface='org.navit_project.navit')
tuple eval.iter = iface.attr_iter()
Referenced by NGQProxyRoute._routeDestinations(), NGQProxyRoute.addDestination(), button_bookmark(), button_destination(), button_destination_clicked(), button_map(), button_map_clicked(), button_visit_clicked(), category_list_model(), changed(), command_evaluate_single(), dbus_dump(), decode_attr(), eval_postfix(), Backend.get_maps(), Backend.get_vehicles(), NGQProxyNavit.getAttrList(), NGQProxyRoute.getDestinations(), gui_gtk_datawindow_add(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_vehicles_update(), gui_internal_cmd2_setting_layout(), gui_internal_cmd2_setting_maps(), gui_internal_cmd2_setting_vehicle(), gui_internal_widget_table_clear(), layer_set_attr_do(), model_poi(), navit_set_vehicle_by_name(), overlay_disable(), paintOverlays(), pedestrian_navit_init(), plugin_init(), request_attr_iter_destroy(), request_callback_new(), request_command(), request_get_attr(), request_map_dump(), request_navit_add_message(), request_navit_attr_iter_destroy(), request_navit_block(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_zoom(), request_navit_zoom_to_route(), request_search_list_get_result(), request_search_list_new(), request_search_list_search(), request_search_list_select(), row_activated(), save_map_csv(), save_vehicle_xml(), select_row(), treeview_poi_changed(), treeview_poi_reload(), vehicleprofile_apply_attrs(), vehicleprofile_apply_roadprofile(), and vehicleprofile_update().
tuple eval.navit = bus.get_object('org.navit_project.navit', conn.get_attr_wi('navit',iter)[1])
Referenced by navit_py_ref(), request_navit_add_message(), request_navit_block(), request_navit_clear_destination(), request_navit_draw(), request_navit_evaluate(), request_navit_resize(), request_navit_route_export_geojson(), request_navit_route_export_gpx(), request_navit_set_center(), request_navit_set_center_screen(), request_navit_set_destination(), request_navit_set_layout(), request_navit_set_position(), request_navit_zoom(), request_navit_zoom_to_route(), win32_main_navit(), and win32_wm_copydata().
tuple eval.navit_iface = dbus.Interface(navit, dbus_interface='org.navit_project.navit.navit')