navit: startup Namespace Reference
startup Namespace Reference
Variables
tuple pos = navit.pcoord("5023.7493 N 00730.2898 E",1)
tuple dest = navit.pcoord("5023.6604 N 00729.8500 E",1)
tuple inst = navit.config()
Variable Documentation
tuple startup.dest = navit.pcoord("5023.6604 N 00729.8500 E",1)
Referenced by ezxml_insert(), g_stpcpy(), g_strcompress(), g_strescape(), g_strlcat(), g_strlcpy(), g_utf8_strncpy(), linguistics_casefold(), read_former_destination_map_as_list(), uncompress_int(), and write_former_destinations().
tuple startup.inst = navit.config()
tuple startup.pos = navit.pcoord("5023.7493 N 00730.2898 E",1)
Referenced by attr_from_line(), attr_new_from_text(), bookmarks_load_hash(), ch_process(), CloseWaveFile(), CloseWavFile(), draw_circle(), expand_filenames(), expand_variables(), filter_type(), geom_poly_segments_insert(), get_strings_ref(), get_tag(), org.navitproject.navit.NavitGraphics.NavitView.getFloatValue(), gui_internal_cmd_insert_destination_do(), image_new(), iso8601_to_secs(), log_flush(), org.navitproject.navit.Navit.onCreate(), osd_text_format_attr(), osd_text_split(), osm_protobufdb_modify_node(), osm_protobufdb_modify_relation(), osm_protobufdb_modify_way(), osm_xml_decode_entities(), osm_xml_get_attribute(), parse_filters(), parse_line(), parse_option(), progress_memory(), progress_time(), route_contains(), route_destination_reached(), route_find_nearest_street(), route_get_pos(), route_graph_update(), route_path_new(), route_path_update_done(), route_path_update_flags(), route_previous_destination(), route_set_position_from_tracking(), search_house_number_interpolation_split(), sig_alrm_do(), str_replace(), street_get_coord(), vehicle_demo_timer(), and vehicle_gpsd_callback().