navit: navit_nls.h File Reference
navit_nls.h File Reference
Macros
#define _(STRING) navit_nls_gettext(STRING)
#define gettext_noop(String) String
#define _n(STRING) gettext_noop(STRING)
#define __NAVIT_NLS_H__
Functions
char * navit_nls_add_textdomain (const char *package, const char *dir)
void navit_nls_remove_textdomain (const char *package)
const char * navit_nls_gettext (const char *msgid)
const char * navit_nls_ngettext (const char *msgid, const char *msgid_plural, unsigned long int n)
void navit_nls_main_init (void)
Macro Definition Documentation
_
#define _ (STRING) navit_nls_gettext(STRING)
__NAVIT_NLS_H__
#define __NAVIT_NLS_H__
_n
#define _n (STRING) gettext_noop(STRING)
gettext_noop
#define gettext_noop (String) String
Function Documentation
navit_nls_add_textdomain()
char* navit_nls_add_textdomain (const char * package, const char * dir)
Referenced by navit_nls_main_init().
navit_nls_gettext()
const char* navit_nls_gettext (const char * msgid)
Referenced by command_call_function(), country_attr_get(), Java_org_navitproject_navit_NavitAppConfig_callbackLocalizedString(), Java_org_navitproject_navit_NavitGraphics_getAllCountries(), and set_columns().
navit_nls_main_init()
void navit_nls_main_init (void)
References navit_nls_add_textdomain().
Referenced by main_real().
navit_nls_ngettext()
const char* navit_nls_ngettext (const char * msgid, const char * msgid_plural, unsigned long int n)
Referenced by get_distance_str().
navit_nls_remove_textdomain()
void navit_nls_remove_textdomain (const char * package)