navit: navit_nls.c File Reference
navit_nls.c File Reference
#include "config.h"
#include "debug.h"
#include <glib.h>
#include <navit_nls.h>
#include <stdlib.h>
#include <libintl.h>
Functions
char * navit_nls_add_textdomain (const char *package, const char *dir)
void navit_nls_remove_textdomain (const char *package)
const char * navit_nls_gettext (const char *msgid)
const char * navit_nls_ngettext (const char *msgid, const char *msgid_plural, unsigned long int n)
void navit_nls_main_init (void)
Function Documentation
char* navit_nls_add_textdomain (const char * package, const char * dir)
References bind_textdomain_codeset, bindtextdomain, g_list_append(), g_strdup(), and NULL.
Referenced by navit_nls_main_init().
const char* navit_nls_gettext (const char * msgid)
References _GList::data, dgettext, g_list_next, and i.
Referenced by command_call_function(), country_attr_get(), country_search_get_item(), Java_org_navitproject_navit_NavitGraphics_CallbackLocalizedString(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), and set_columns().
void navit_nls_main_init (void)
References getenv, LC_MESSAGES, navit_nls_add_textdomain(), setlocale(), and textdomain.
Referenced by main_real().
const char* navit_nls_ngettext (const char * msgid, const char * msgid_plural, unsigned long int n)
References _GList::data, dngettext, g_list_next, and i.
Referenced by get_distance_str().
void navit_nls_remove_textdomain (const char * package)
References _GList::data, g_free(), g_list_next, g_list_remove_all(), and i.