navit: gui/qml/navitProxy.h File Reference
navitProxy.h File Reference
#include "navitProxy.moc"
Data Structures
class NGQProxyNavit
Functions
void __setNewPoint (struct gui_priv *this_, struct coord *c, NGQPointTypes type)
Function Documentation
void __setNewPoint (struct gui_priv * this_, struct coord * c, NGQPointTypes type)
References gui_priv::guiProxy, and NGQProxyGui::setNewPoint().
Referenced by NGQProxyNavit::getDestination(), and NGQProxyNavit::getPosition().