navit: support/espeak/numbers.c File Reference
numbers.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>
#include <wchar.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Data Structures
struct ACCENTS
Macros
#define M_NAME 0
#define M_SMALLCAP 1
#define M_TURNED 2
#define M_REVERSED 3
#define M_CURL 4
#define M_ACUTE 5
#define M_BREVE 6
#define M_CARON 7
#define M_CEDILLA 8
#define M_CIRCUMFLEX 9
#define M_DIAERESIS 10
#define M_DOUBLE_ACUTE 11
#define M_DOT_ABOVE 12
#define M_GRAVE 13
#define M_MACRON 14
#define M_OGONEK 15
#define M_RING 16
#define M_STROKE 17
#define M_TILDE 18
#define M_BAR 19
#define M_RETROFLEX 20
#define M_HOOK 21
#define M_MIDDLE_DOT M_DOT_ABOVE
#define M_IMPLOSIVE M_HOOK
#define CAPITAL 0
#define LETTER(ch, mod1, mod2) (ch-59)+(mod1 << 6)+(mod2 << 11)
#define LIGATURE(ch1, ch2, mod1) (ch1-59)+((ch2-59) << 6)+(mod1 << 12)+0x8000
#define L_ALPHA 60
#define L_SCHWA 61
#define L_OPEN_E 62
#define L_GAMMA 63
#define L_IOTA 64
#define L_OE 65
#define L_OMEGA 66
#define L_PHI 67
#define L_ESH 68
#define L_UPSILON 69
#define L_EZH 70
#define L_GLOTTAL 71
#define L_RTAP 72
Functions
static int LookupLetter2 (Translator *tr, unsigned int letter, char *ph_buf)
void LookupAccentedLetter (Translator *tr, unsigned int letter, char *ph_buf)
void LookupLetter (Translator *tr, unsigned int letter, int next_byte, char *ph_buf1)
int TranslateLetter (Translator *tr, char *word, char *phonemes, int control, int word_length)
void SetSpellingStress (Translator *tr, char *phonemes, int control, int n_chars)
int TranslateRoman (Translator *tr, char *word, char *ph_out)
static const char * M_Variant (int value)
static int LookupThousands (Translator *tr, int value, int thousandplex, char *ph_out)
static int LookupNum2 (Translator *tr, int value, int control, char *ph_out)
static int LookupNum3 (Translator *tr, int value, char *ph_out, int suppress_null, int thousandplex, int control)
static int TranslateNumber_1 (Translator *tr, char *word, char *ph_out, unsigned int *flags, int wflags)
int TranslateNumber (Translator *tr, char *word1, char *ph_out, unsigned int *flags, int wflags)
Variables
static ACCENTS accents_tab []
static const short non_ascii_tab []
static const unsigned short letter_accents_0e0 []
static const unsigned short letter_accents_250 []
static char ph_ordinal2 [12]
Macro Definition Documentation
#define CAPITAL 0
#define L_ALPHA 60
#define L_ESH 68
#define L_EZH 70
#define L_GAMMA 63
#define L_GLOTTAL 71
#define L_IOTA 64
#define L_OE 65
#define L_OMEGA 66
#define L_OPEN_E 62
#define L_PHI 67
#define L_RTAP 72
#define L_SCHWA 61
#define L_UPSILON 69
#define LETTER (ch, mod1, mod2) (ch-59)+(mod1 << 6)+(mod2 << 11)
#define LIGATURE (ch1, ch2, mod1) (ch1-59)+((ch2-59) << 6)+(mod1 << 12)+0x8000
#define M_ACUTE 5
#define M_BAR 19
#define M_BREVE 6
#define M_CARON 7
#define M_CEDILLA 8
#define M_CIRCUMFLEX 9
#define M_CURL 4
#define M_DIAERESIS 10
#define M_DOT_ABOVE 12
#define M_DOUBLE_ACUTE 11
#define M_GRAVE 13
#define M_HOOK 21
#define M_IMPLOSIVE M_HOOK
#define M_MACRON 14
#define M_MIDDLE_DOT M_DOT_ABOVE
#define M_NAME 0
#define M_OGONEK 15
#define M_RETROFLEX 20
#define M_REVERSED 3
#define M_RING 16
#define M_SMALLCAP 1
#define M_STROKE 17
#define M_TILDE 18
#define M_TURNED 2
Function Documentation
void LookupAccentedLetter (Translator * tr, unsigned int letter, char * ph_buf)
References LANGUAGE_OPTIONS::accents, ACCENTS::flags, Translator::langopts, letter_accents_0e0, letter_accents_250, Lookup(), LookupLetter2(), name, non_ascii_tab, phonPAUSE_VSHORT, phonSTRESS_2, phonSTRESS_P, and sprintf().
Referenced by LookupDictList(), and LookupLetter().
void LookupLetter (Translator * tr, unsigned int letter, int next_byte, char * ph_buf1)
References FLAG_NO_TRACE, L, Lookup(), LookupAccentedLetter(), NULL, p, phoneme_tab, voice_t::phoneme_tab_ix, phonSTRESS_P, phonSWITCH, phSTRESS, ptr, RULE_SPELLING, SelectPhonemeTable(), SetTranslator2(), sprintf(), TranslateRules(), translator2, Translator::translator_name, type, utf8_out(), and voice.
Referenced by TranslateLetter(), and TranslateRules().
static int LookupLetter2 (Translator * tr, unsigned int letter, char * ph_buf) static
References Lookup(), NULL, TranslateRules(), and utf8_out().
Referenced by LookupAccentedLetter().
static int LookupNum2 (Translator * tr, int value, int control, char * ph_out) static
References int, Translator::langopts, Lookup(), NUM_VIGESIMAL, LANGUAGE_OPTIONS::numbers, ph_ordinal2, phoneme_tab, phonSTRESS_3, phonSTRESS_P, phSTRESS, phVOWEL, sprintf(), PHONEME_TAB::type, type, and units.
Referenced by LookupNum3(), and TranslateNumber_1().
static int LookupNum3 (Translator * tr, int value, char * ph_out, int suppress_null, int thousandplex, int control) static
References Translator::langopts, Lookup(), LookupNum2(), LookupThousands(), LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, phonPAUSE_NOLINK, and sprintf().
Referenced by TranslateNumber_1().
static int LookupThousands (Translator * tr, int value, int thousandplex, char * ph_out) static
References Lookup(), M_Variant(), and sprintf().
Referenced by LookupNum3(), and TranslateNumber_1().
static const char* M_Variant (int value) static
References Translator::langopts, LANGUAGE_OPTIONS::numbers2, and translator.
Referenced by LookupThousands(), and TranslateNumber_1().
void SetSpellingStress (Translator * tr, char * phonemes, int control, int n_chars)
References buf, c, Translator::langopts, N_WORD_PHONEMES, phonPAUSE, phonPAUSE_NOLINK, phonPAUSE_SHORT, phonSTRESS_3, phonSTRESS_P, and LANGUAGE_OPTIONS::spelling_stress.
Referenced by TranslateWord().
int TranslateLetter (Translator * tr, char * word, char * phonemes, int control, int word_length)
References LANGUAGE_OPTIONS::accents, L, Translator::langopts, Lookup(), LookupLetter(), N_WORD_PHONEMES, option_phonemes, voice_t::phoneme_tab_ix, phonPAUSE_VSHORT, phonSWITCH, SelectPhonemeTable(), SetTranslator2(), sprintf(), towlower2(), translator2, Translator::translator_name, utf8_in(), and voice.
Referenced by TranslateWord().
int TranslateNumber (Translator * tr, char * word1, char * ph_out, unsigned int * flags, int wflags)
References Translator::langopts, LANGUAGE_OPTIONS::numbers, option_sayas, SAYAS_DIGITS1, and TranslateNumber_1().
Referenced by TranslateRoman(), and TranslateWord().
static int TranslateNumber_1 (Translator * tr, char * word, char * ph_out, unsigned int * flags, int wflags) static
References c, LANGUAGE_OPTIONS::decimal_sep, dictionary_skipwords, FLAG_FOUND, FLAG_SKIPWORDS, Translator::langopts, Lookup(), LookupNum2(), LookupNum3(), LookupThousands(), M_Variant(), N_WORD_PHONEMES, NUM_NOPAUSE, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, p, ph_ordinal2, phonPAUSE_NOLINK, phonSWITCH, sprintf(), suffix, LANGUAGE_OPTIONS::thousands_sep, utf8_in(), and value.
Referenced by TranslateNumber().
int TranslateRoman (Translator * tr, char * word, char * ph_out)
References c, Translator::langopts, Lookup(), LANGUAGE_OPTIONS::max_roman, N_WORD_BYTES, NULL, NUM_ROMAN_AFTER, LANGUAGE_OPTIONS::numbers, p, sprintf(), TranslateNumber(), and value.
Referenced by TranslateWord().
Variable Documentation
ACCENTS accents_tab[] static
Initial value:
= {
{"_lig", 1},
{"_smc", 1},
{"_tur", 1},
{"_rev", 1},
{"_crl", 0},
{"_acu", 0},
{"_brv", 0},
{"_hac", 0},
{"_ced", 0},
{"_cir", 0},
{"_dia", 0},
{"_ac2", 0},
{"_dot", 0},
{"_grv", 0},
{"_mcn", 0},
{"_ogo", 0},
{"_rng", 0},
{"_stk", 0},
{"_tld", 0},
{"_bar", 0},
{"_rfx", 0},
{"_hok", 0},
}
const unsigned short letter_accents_0e0[] static
Referenced by LookupAccentedLetter().
const unsigned short letter_accents_250[] static
Referenced by LookupAccentedLetter().
const short non_ascii_tab[] static
Initial value:
= {
    0, 0x3b1, 0x259, 0x25b, 0x3b3, 0x3b9, 0x153, 0x3c9,
0x3c6, 0x283, 0x3c5, 0x292, 0x294, 0x27e }
Referenced by LookupAccentedLetter().
char ph_ordinal2[12] static
Referenced by LookupNum2(), and TranslateNumber_1().