navit: support/libc/open.c File Reference
open.c File Reference
#include <windows.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
Functions
static int vwopen (const wchar_t *wpath, int oflag, va_list ap)
static int vopen (const char *path, int oflag, va_list ap)
int _open (const char *path, int oflag,...)
int open (const char *path, int oflag,...)
int _wopen (const wchar_t *path, int oflag,...)
Function Documentation
int _open (const char * path, int oflag, ...)
References vopen().
int _wopen (const wchar_t * path, int oflag, ...)
References vwopen().
int open (const char * path, int oflag, ...)
References vopen().
Referenced by _nl_load_domain(), ezxml_parse_file(), file_create(), j1850_init_serial_port(), pedestrian_setup_tilt(), plugin_init(), and vehicle_file_open().
static int vopen (const char * path, int oflag, va_list ap) static
References vwopen().
Referenced by _open(), and open().
static int vwopen (const wchar_t * wpath, int oflag, va_list ap) static
References NULL, O_APPEND, O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, S_IREAD, and S_IWRITE.
Referenced by _wopen(), and vopen().