navit: maptool/osm_relations.c File Reference
osm_relations.c File Reference
#include <stdio.h>
#include <string.h>
#include "maptool.h"
#include "attr.h"
Data Structures
struct relations
struct relations_func
struct relations_member
Functions
static guint relations_member_hash (gconstpointer key)
static gboolean relations_member_equal (gconstpointer a, gconstpointer b)
struct relations * relations_new (void)
struct relations_func * relations_func_new (void(*func)(void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv), void *func_priv)
static struct relations_member * relations_member_new (struct relations_func *func, void *relation_priv, void *member_priv, osmid id)
void relations_add_relation_member_entry (struct relations *rel, struct relations_func *func, void *relation_priv, void *member_priv, enum relation_member_type type, osmid id)
void relations_add_relation_default_entry (struct relations *rel, struct relations_func *func)
void relations_process (struct relations *rel, FILE *nodes, FILE *ways)
static void relations_destroy_func (void *key, GList *l, void *data)
void relations_destroy (struct relations *relations)
Function Documentation
void relations_add_relation_default_entry (struct relations * rel, struct relations_func * func)
References relations::default_members, g_list_append(), NULL, and relations_member_new().
Referenced by process_associated_streets_setup(), and process_house_number_interpolations_setup().
void relations_add_relation_member_entry (struct relations * rel, struct relations_func * func, void * relation_priv, void * member_priv, enum relation_member_type type, osmid id)
References g_hash_table_insert(), g_hash_table_lookup(), g_list_append(), relations::member_hash, and relations_member_new().
Referenced by process_associated_streets_setup(), process_boundaries_setup(), process_house_number_interpolations_setup(), and process_turn_restrictions_setup().
void relations_destroy (struct relations * relations)
References g_free(), g_hash_table_destroy(), g_hash_table_foreach(), i, relations::member_hash, NULL, and relations_destroy_func().
Referenced by process_associated_streets(), process_boundaries(), process_house_number_interpolations(), and process_turn_restrictions().
static void relations_destroy_func (void * key, GList * l, void * data) static
References _GList::data, g_free(), g_list_free(), and g_list_next.
Referenced by relations_destroy().
struct relations_func* relations_func_new (void(*)(void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv) func, void * func_priv)
References relations_func::func, relations_func::func_priv, and g_new.
Referenced by process_associated_streets_setup(), process_boundaries_setup(), process_house_number_interpolations_setup(), and process_turn_restrictions_setup().
static gboolean relations_member_equal (gconstpointer a, gconstpointer b) static
References relations_member::memberid.
Referenced by relations_new().
static guint relations_member_hash (gconstpointer key) static
References key, and relations_member::memberid.
Referenced by relations_new().
static struct relations_member* relations_member_new (struct relations_func * func, void * relation_priv, void * member_priv, osmid id) static
References relations_member::func, g_new, relations_member::member_priv, relations_member::memberid, and relations_member::relation_priv.
Referenced by relations_add_relation_default_entry(), and relations_add_relation_member_entry().
struct relations* relations_new (void)
References g_hash_table_new(), g_new0, i, relations::member_hash, relations_member_equal(), and relations_member_hash().
Referenced by process_associated_streets(), process_boundaries(), process_house_number_interpolations(), and process_turn_restrictions().
void relations_process (struct relations * rel, FILE * nodes, FILE * ways)
References node_item::c, c, _GList::data, relations::default_members, relations_func::func, relations_member::func, relations_func::func_priv, g_hash_table_lookup(), g_list_next, item_bin_add_attr_longlong(), item_bin_add_coord(), item_bin_get_attr(), item_bin_init(), relations::member_hash, relations_member::member_priv, node_item::nd_id, NULL, read_item(), read_node_item(), and relations_member::relation_priv.
Referenced by process_associated_streets(), process_boundaries(), process_house_number_interpolations(), and process_turn_restrictions().