navit: maptool/osm.c File Reference
osm.c File Reference
#include "navit_lfs.h"
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <ctype.h>
#include "maptool.h"
#include "debug.h"
#include "linguistics.h"
#include "country.h"
#include "file.h"
#include "profile.h"
#include "types.h"
#include "transform.h"
Data Structures
struct attr_mapping
struct country_table
struct town_country
struct relation_member
struct associated_street
struct process_relation_member_func_priv
struct house_number_interpolation
struct turn_restriction
Macros
#define M_PI 3.14159265358979323846
#define M_PI_4 0.785398163397448309616
#define MAX_COORD_COUNT 65536
#define REF_MARKER (1ull << 30)
#define REF_MASK (3ull << 30)
#define IS_REF(c) (((c).x & REF_MASK)==REF_MARKER)
#define GET_REF(c) ((((osmid)(c).x & ~REF_MARKER)<<31) + (c).y)
#define SET_REF(c, ref) do { (c).x = REF_MARKER | ((osmid)(ref)>>31); (c).y = (osmid)(ref) & 0x7fffffffull; } while(0)
#define MAX_TOWN_ADMIN_LEVELS 11
Enumerations
enum attr_strings_type {
attr_string_phone, attr_string_fax, attr_string_email, attr_string_url,
attr_string_district_name, attr_string_street_name, attr_string_street_name_systematic, attr_string_street_name_systematic_nat,
attr_string_street_name_systematic_int, attr_string_ref, attr_string_exit_to, attr_string_street_destination,
attr_string_street_destination_forward, attr_string_street_destination_backward, attr_string_house_number, attr_string_label,
attr_string_postal, attr_string_population, attr_string_county_name, attr_string_last
}
Functions
static void nodes_ref_item_bin (struct item_bin *ib)
static int attr_longest_match (struct attr_mapping **mapping, int mapping_count, enum item_type *types, int types_count)
static void attr_longest_match_clear (void)
static void build_attrmap_line (char *line)
static void build_attrmap (FILE *rule_file)
static void build_countrytable (void)
static void osm_logv (char *prefix, char *objtype, osmid id, int cont, struct coord_geo *geo, char *fmt, va_list ap)
void osm_warning (char *type, osmid id, int cont, char *fmt,...)
void osm_info (char *type, osmid id, int cont, char *fmt,...)
static void itembin_warning (struct item_bin *ib, int cont, char *fmt,...)
static void attr_strings_clear (void)
static void attr_strings_save (enum attr_strings_type id, char *str)
static osmid item_bin_get_nodeid_from_attr (struct item_bin *ib, enum attr_type attr_type)
osmid item_bin_get_nodeid (struct item_bin *ib)
osmid item_bin_get_wayid (struct item_bin *ib)
osmid item_bin_get_relationid (struct item_bin *ib)
osmid item_bin_get_id (struct item_bin *ib)
static void relation_add_tag (char *k, char *v)
static int access_value (char *v)
static void osm_update_attr_present (char *k, char *v)
void osm_add_tag (char *k, char *v)
static void extend_buffer (struct buffer *b)
static void node_buffer_to_hash (void)
void flush_nodes (int final)
static struct node_item * allocate_node_item_in_buffer (void)
static void remove_last_node_item_from_buffer (void)
void osm_add_node (osmid id, double lat, double lon)
void clear_node_item_buffer (void)
static long long node_item_find_index_in_ordered_list (osmid id)
static struct node_item * node_item_get (osmid id)
void osm_add_way (osmid id)
void osm_add_relation (osmid id)
static int country_id_from_iso2 (char *iso)
static struct country_table * country_from_countryid (int id)
struct country_table * country_from_iso2 (char *iso)
void osm_end_relation (struct maptool_osm *osm)
void osm_add_member (enum relation_member_type type, osmid ref, char *role)
void osm_end_way (struct maptool_osm *osm)
void osm_end_node (struct maptool_osm *osm)
static struct town_country * town_country_new (struct country_table *country)
static void town_country_destroy (struct town_country *tc)
static struct town_country * town_country_list_insert_if_new (GList **town_country_list, struct country_table *country)
static GList * osm_process_town_unknown_country (void)
static char * osm_process_town_get_town_name_from_is_in (struct item_bin *ib, GHashTable *town_hash)
static GList * osm_process_town_by_is_in (struct item_bin *ib)
static void osm_process_town_by_boundary_update_attrs (struct item_bin *town, struct town_country *tc, GList *matches)
static GList * osm_process_town_by_boundary (GList *bl, struct item_bin *town, struct coord *c)
static void osm_town_relations_to_poly (GList *boundaries, FILE *towns_poly)
void osm_process_towns (FILE *in, FILE *boundaries, FILE *ways, char *suffix)
void sort_countries (int keep_tmpfiles)
static void parse_relation_member_string (char *relation_member_string, struct relation_member *memb)
static int search_relation_member (struct item_bin *ib, char *role, struct relation_member *memb, int *min_count)
static void process_associated_street_member (void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv_unused)
static void process_house_number_interpolation_member (void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv_unused)
static void relation_func_writethrough (void *func_priv, void *relation_priv_unused, struct item_bin *member, void *member_priv_unused)
static void process_associated_streets_setup (FILE *in, struct relations *relations, struct process_relation_member_func_priv *fp)
void process_associated_streets (FILE *in, struct files_relation_processing *files_relproc)
static void process_house_number_interpolations_setup (FILE *in, struct relations *relations, struct process_relation_member_func_priv *fp)
void process_house_number_interpolations (FILE *in, struct files_relation_processing *files_relproc)
static void process_turn_restrictions_member (void *func_priv, void *relation_priv, struct item_bin *member, void *member_priv)
static void process_turn_restrictions_fromto (struct turn_restriction *t, int type, struct coord **c)
static void process_turn_restrictions_dump_coord (struct coord *c, int count)
static void process_turn_restrictions_finish (GList *tr, FILE *out)
static GList * process_turn_restrictions_setup (FILE *in, struct relations *relations)
void process_turn_restrictions (FILE *in, FILE *coords, FILE *ways, FILE *ways_index, FILE *out)
static void node_ref_way (osmid node)
void osm_add_nd (osmid ref)
static void write_item_way_subsection_index (FILE *out, FILE *out_index, FILE *out_graph, struct item_bin *orig, long long *last_id)
static void write_item_way_subsection (FILE *out, FILE *out_index, FILE *out_graph, struct item_bin *orig, int first, int last, long long *last_id)
void ref_ways (FILE *in)
void resolve_ways (FILE *in, FILE *out)
void process_way2poi (FILE *in, FILE *out, int type)
int map_resolve_coords_and_split_at_intersections (FILE *in, FILE *out, FILE *out_index, FILE *out_graph, FILE *out_coastline, int final)
static void index_country_add (struct zip_info *info, int country_id, char *first_key, char *last_key, char *tile, char *filename, int size, FILE *out)
void write_countrydir (struct zip_info *zip_info, int max_index_size)
void load_countries (void)
void remove_countryfiles (void)
void osm_init (FILE *rule_file)
Variables
static int in_way
static int in_node
static int in_relation
osmid nodeid
osmid wayid
static GHashTable * attr_hash
static GHashTable * country_table_hash
static char * attr_present
static int attr_present_count
static struct item_bin item
int maxspeed_attr_value
char debug_attr_buffer [BUFFER_SIZE]
int flags [4]
int flagsa [4]
int flags_attr_value
struct attr_bin osmid_attr
long long osmid_attr_value
char is_in_buffer [BUFFER_SIZE]
char attr_strings_buffer [BUFFER_SIZE *16]
int attr_strings_buffer_free_offset
struct coord coord_buffer [MAX_COORD_COUNT]
static struct attr_mapping ** attr_mapping_node
static int attr_mapping_node_count
static struct attr_mapping ** attr_mapping_way
static int attr_mapping_way_count
static struct attr_mapping ** attr_mapping_way2poi
static int attr_mapping_way2poi_count
static struct attr_mapping ** attr_mapping_rel2poly_place
static int attr_mapping_rel2poly_place_count
char * attr_strings [attr_string_last]
char * osm_types [] ={"unknown","node","way","relation"}
struct country_table country_table []
static char * attrmap
static int node_is_tagged
int coord_count
static struct node_item * current_node
osmid id_last_node
GHashTable * node_hash
GHashTable * way_hash
char relation_type [BUFFER_SIZE]
char iso_code [BUFFER_SIZE]
int boundary
Macro Definition Documentation
#define GET_REF (c) ((((osmid)(c).x & ~REF_MARKER)<<31) + (c).y)
Referenced by map_resolve_coords_and_split_at_intersections(), nodes_ref_item_bin(), osm_end_way(), and resolve_ways().
#define IS_REF (c) (((c).x & REF_MASK)==REF_MARKER)
Referenced by map_resolve_coords_and_split_at_intersections(), process_turn_restrictions_member(), and resolve_ways().
#define M_PI 3.14159265358979323846
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by draw_circle(), draw_lines(), getmercator(), mapExtract::getmercator(), keypress(), main(), navit_get_cursor_pnt(), osd_compass_draw(), osm_add_node(), transform_cart_to_geo(), transform_from_geo(), transform_get_angle_delta(), transform_project(), transform_rotate(), transform_scale(), transform_setup_matrix(), transform_to_geo(), and transform_utm_to_geo().
#define M_PI_4 0.785398163397448309616
Referenced by getmercator(), mapExtract::getmercator(), main(), osm_add_node(), and transform_from_geo().
#define MAX_COORD_COUNT 65536
Referenced by osm_add_nd().
#define MAX_TOWN_ADMIN_LEVELS 11
Referenced by osm_process_towns().
#define REF_MARKER (1ull << 30)
#define REF_MASK (3ull << 30)
#define SET_REF (c, ref) do { (c).x = REF_MARKER | ((osmid)(ref)>>31); (c).y = (osmid)(ref) & 0x7fffffffull; } while(0)
Referenced by osm_add_nd().
Enumeration Type Documentation
enum attr_strings_type
Enumerator
attr_string_phone
attr_string_fax
attr_string_email
attr_string_url
attr_string_district_name
attr_string_street_name
attr_string_street_name_systematic
attr_string_street_name_systematic_nat
attr_string_street_name_systematic_int
attr_string_ref
attr_string_exit_to
attr_string_street_destination
attr_string_street_destination_forward
attr_string_street_destination_backward
attr_string_house_number
attr_string_label
attr_string_postal
attr_string_population
attr_string_county_name
attr_string_last
Function Documentation
static int access_value (char * v) static
Referenced by osm_add_tag().
static struct node_item* allocate_node_item_in_buffer (void) static
References buffer::base, extend_buffer(), flush_nodes(), buffer::malloced, node_buffer, buffer::size, and slice_size.
Referenced by osm_add_node().
static int attr_longest_match (struct attr_mapping ** mapping, int mapping_count, enum item_type * types, int types_count) static
References attr_present, attr_mapping::attr_present_idx, attr_mapping::attr_present_idx_count, i, and attr_mapping::type.
Referenced by osm_end_node(), osm_end_relation(), and osm_end_way().
static void attr_longest_match_clear (void) static
References attr_present, and attr_present_count.
Referenced by osm_end_node(), osm_end_relation(), and osm_end_way().
static void attr_strings_clear (void) static
References attr_strings, and attr_strings_buffer_free_offset.
Referenced by osm_add_node(), and osm_add_way().
static void attr_strings_save (enum attr_strings_type id, char * str) static
References attr_strings, attr_strings_buffer, attr_strings_buffer_free_offset, dbg_assert, and g_strlcpy().
Referenced by osm_add_tag().
static void build_attrmap (FILE * rule_file) static
References attr_hash, attr_present, attr_present_count, attrmap, build_attrmap_line(), g_hash_table_new(), g_malloc0(), g_str_equal(), g_str_hash(), g_strdup(), and p.
Referenced by osm_init().
static void build_attrmap_line (char * line) static
References attr_hash, attr_mapping_node_count, attr_mapping_rel2poly_place_count, attr_mapping_way2poi_count, attr_mapping_way_count, attr_present_count, attr_mapping::attr_present_idx, attr_mapping::attr_present_idx_count, g_hash_table_insert(), g_hash_table_lookup(), g_malloc0(), g_realloc(), i, item_from_name(), item_is_poly_place, NULL, p, printf(), and attr_mapping::type.
Referenced by build_attrmap().
static void build_countrytable (void) static
References country_table, country_table_hash, g_hash_table_insert(), g_hash_table_new(), g_str_equal(), g_str_hash(), g_strdup(), i, and NULL.
Referenced by osm_init().
void clear_node_item_buffer (void)
References buffer::base, node_buffer, node_item::ref_way, and buffer::size.
Referenced by osm_count_references().
static struct country_table* country_from_countryid (int id) static
References country_table, country_table::countryid, i, and NULL.
Referenced by country_from_iso2(), and osm_process_town_unknown_country().
struct country_table* country_from_iso2 (char * iso)
References country_from_countryid(), and country_id_from_iso2().
Referenced by process_boundaries_setup().
static int country_id_from_iso2 (char * iso) static
References country_search_destroy(), country_search_get_item(), country_search_new(), item, item_attr_get(), attr::num, country_search::search, attr::str, attr::type, and attr::u.
Referenced by country_from_iso2().
static void extend_buffer (struct buffer * b) static
References buffer::base, exit, fprintf(), buffer::malloced, buffer::malloced_step, and NULL.
Referenced by allocate_node_item_in_buffer().
void flush_nodes (int final)
References fprintf(), node_buffer, save_buffer(), buffer::size, slice_size, and slices.
Referenced by allocate_node_item_in_buffer(), and osm_read_input_data().
static void index_country_add (struct zip_info * info, int country_id, char * first_key, char * last_key, char * tile, char * filename, int size, FILE * out) static
References add_aux_tile(), init_item(), item_bin_add_attr_int(), item_bin_add_attr_string(), item_bin_write(), and num.
Referenced by write_countrydir().
osmid item_bin_get_id (struct item_bin * ib)
References item_bin_get_nodeid(), item_bin_get_relationid(), item_bin_get_wayid(), and item_bin::type.
Referenced by tile_extend().
osmid item_bin_get_nodeid (struct item_bin * ib)
References item_bin_get_nodeid_from_attr().
Referenced by item_bin_get_id(), and itembin_warning().
static osmid item_bin_get_nodeid_from_attr (struct item_bin * ib, enum attr_type attr_type) static
References item_bin_get_attr(), and NULL.
Referenced by item_bin_get_nodeid(), and process_house_number_interpolations_setup().
osmid item_bin_get_relationid (struct item_bin * ib)
References item_bin_get_attr(), and NULL.
Referenced by item_bin_get_id(), itembin_warning(), process_associated_streets_setup(), process_boundaries_finish(), process_boundaries_setup(), and process_turn_restrictions_setup().
osmid item_bin_get_wayid (struct item_bin * ib)
References item_bin_get_attr(), and NULL.
Referenced by item_bin_copy_attr(), item_bin_get_id(), itembin_warning(), map_resolve_coords_and_split_at_intersections(), process_house_number_interpolations_setup(), process_way2poi(), tile_collector_process_tile(), and write_item_way_subsection_index().
static void itembin_warning (struct item_bin * ib, int cont, char * fmt, ...) static
References c, item_bin_get_nodeid(), item_bin_get_relationid(), item_bin_get_wayid(), NULL, osm_logv(), projection_mg, transform_to_geo(), and type.
Referenced by osm_process_towns().
void load_countries (void)
References bbox_extend(), item_bin::clen, country_table, country_table::countryid, filename, rect::h, i, item_bin::len, country_table::r, read_item(), SEEK_END, country_table::size, and sprintf().
Referenced by maptool_load_countries().
int map_resolve_coords_and_split_at_intersections (FILE * in, FILE * out, FILE * out_index, FILE * out_graph, FILE * out_coastline, int final)
References node_item::c, c, item_bin::clen, fprintf(), GET_REF, i, IS_REF, item_bin_get_wayid(), item_get_default_flags(), item_bin::len, node_item_get(), NULL, osm_warning(), processed_nodes, processed_nodes_out, processed_relations, processed_tiles, processed_ways, read_item(), node_item::ref_way, sig_alrm(), sig_alrm_end(), item_bin::type, and write_item_way_subsection().
Referenced by osm_resolve_coords_and_split_at_intersections().
static void node_buffer_to_hash (void) static
References buffer::base, for(), g_hash_table_insert(), i, long, node_item::nd_id, node_buffer, node_hash, and buffer::size.
Referenced by osm_add_node().
static long long node_item_find_index_in_ordered_list (osmid id) static
References buffer::base, fprintf(), node_item::nd_id, node_buffer, node_count, and buffer::size.
Referenced by node_item_get().
static struct node_item* node_item_get (osmid id) static
References buffer::base, g_hash_table_lookup_extended(), node_buffer, node_hash, node_item_find_index_in_ordered_list(), and NULL.
Referenced by map_resolve_coords_and_split_at_intersections(), node_ref_way(), and resolve_ways().
static void node_ref_way (osmid node) static
References node_item_get(), and node_item::ref_way.
Referenced by nodes_ref_item_bin().
static void nodes_ref_item_bin (struct item_bin * ib) static
References item_bin::clen, GET_REF, i, and node_ref_way().
Referenced by osm_end_way(), and ref_ways().
void osm_add_member (enum relation_member_type type, osmid ref, char * role)
References BUFFER_SIZE, item_bin_add_attr(), RELATION_MEMBER_PRINT_FORMAT, attr::str, tmp_item_bin, and attr::u.
Referenced by map_collect_data_osm_o5m(), parse_member(), and process_relation().
void osm_add_nd (osmid ref)
References coord_buffer, coord_count, exit, fprintf(), MAX_COORD_COUNT, and SET_REF.
Referenced by map_collect_data_osm_o5m(), parse_nd(), and process_way().
void osm_add_node (osmid id, double lat, double lon)
References allocate_node_item_in_buffer(), attr_strings_clear(), buffer::base, node_item::c, dbg_assert, debug_attr_buffer, fprintf(), g_hash_table_insert(), g_hash_table_lookup(), g_hash_table_new(), id_last_node, in_node, is_in_buffer, attr_bin::len, M_PI, M_PI_4, node_item::nd_id, node_buffer, node_buffer_to_hash(), node_hash, NODE_ID_BITS, node_is_tagged, nodeid, NULL, osmid_attr, osmid_attr_value, OSMID_FMT, node_item::ref_way, remove_last_node_item_from_buffer(), item::type, attr_bin::type, coord::x, and coord::y.
Referenced by map_collect_data_osm_o5m(), parse_node(), and process_dense().
void osm_add_relation (osmid id)
References debug_attr_buffer, in_relation, item_bin_add_attr_longlong(), item_bin_init(), osmid_attr_value, and tmp_item_bin.
Referenced by map_collect_data_osm_o5m(), parse_relation(), and process_relation().
void osm_add_tag (char * k, char * v)
Sometimes there is no is_in tag, only is_in:country. I put this here so it can be overwritten by the previous if clause if there IS an is_in tag.
Ireland uses the place_county OSM tag to describe what county a town is in. This would be equivalent to is_in: Town; Locality; Country A real world example would be Node: Moycullen (52234625) The tag is processed as Moycullen; Galway; Ireland where Galway is the county
References access_value(), AF_BIKE, AF_CAR, AF_DANGEROUS_GOODS, AF_DELIVERY_TRUCK, AF_EMERGENCY_VEHICLES, AF_HIGH_OCCUPANCY_CAR, AF_HIGH_OCCUPANCY_CAR_ONLY, AF_HORSE, AF_MOPED, AF_MOTORCYCLE, AF_ONEWAY, AF_ONEWAYREV, AF_PEDESTRIAN, AF_PUBLIC_BUS, AF_ROUNDABOUT, AF_ROUNDABOUT_VALID, AF_SPEED_LIMIT, AF_TAXI, AF_THROUGH_TRAFFIC_LIMIT, AF_TOLL, AF_TRANSPORT_TRUCK, AF_UNDERGROUND, attr_debug_level, attr_string_county_name, attr_string_district_name, attr_string_email, attr_string_exit_to, attr_string_fax, attr_string_house_number, attr_string_label, attr_string_phone, attr_string_population, attr_string_postal, attr_string_ref, attr_string_street_destination, attr_string_street_destination_backward, attr_string_street_destination_forward, attr_string_street_name, attr_string_street_name_systematic, attr_string_street_name_systematic_int, attr_string_street_name_systematic_nat, attr_strings, attr_strings_save(), debug_attr_buffer, flagsa, g_strlcpy(), in_relation, in_way, int, is_in_buffer, maxspeed_attr_value, node_is_tagged, osm_update_attr_present(), relation_add_tag(), and strcasecmp().
Referenced by map_collect_data_osm_o5m(), parse_tag(), and process_tag().
void osm_add_way (osmid id)
References attr_strings_clear(), coord_count, debug_attr_buffer, flags_attr_value, flagsa, fprintf(), g_hash_table_new(), in_way, maxspeed_attr_value, NULL, osmid_attr_value, OSMID_FMT, item::type, way_hash, and wayid.
Referenced by map_collect_data_osm_o5m(), parse_way(), and process_way().
void osm_end_node (struct maptool_osm * osm)
References attr_longest_match(), attr_longest_match_clear(), attr_mapping_node_count, attr_string_county_name, attr_string_email, attr_string_exit_to, attr_string_fax, attr_string_house_number, attr_string_label, attr_string_phone, attr_string_population, attr_string_postal, attr_string_ref, attr_string_street_name, attr_string_url, attr_strings, node_item::c, dbg_assert, debug_attr_buffer, fprintf(), i, ignore_unknown, in_node, init_item(), is_in_buffer, item_bin_add_attr_longlong(), item_bin_add_attr_string(), item_bin_add_coord(), item_bin_set_type_by_population(), item_bin_write(), item_is_district, item_is_town, node_is_tagged, nodeid, maptool_osm::nodes, osmid_attr_value, OSMID_FMT, processed_nodes_out, maptool_osm::towns, item_bin::type, and types.
Referenced by map_collect_data_osm(), map_collect_data_osm_o5m(), and process_dense().
void osm_end_relation (struct maptool_osm * osm)
References maptool_osm::associated_streets, attr_longest_match(), attr_longest_match_clear(), attr_mapping_rel2poly_place_count, maptool_osm::boundaries, in_relation, item_bin_write(), tmp_item_bin, maptool_osm::turn_restrictions, item_bin::type, and type.
Referenced by map_collect_data_osm(), map_collect_data_osm_o5m(), and process_relation().
void osm_end_way (struct maptool_osm * osm)
References attr_longest_match(), attr_longest_match_clear(), attr_mapping_way2poi_count, attr_mapping_way_count, attr_string_county_name, attr_string_district_name, attr_string_email, attr_string_fax, attr_string_house_number, attr_string_label, attr_string_phone, attr_string_street_destination, attr_string_street_destination_backward, attr_string_street_destination_forward, attr_string_street_name, attr_string_street_name_systematic, attr_string_street_name_systematic_nat, attr_string_url, attr_strings, coord_buffer, coord_count, dbg_assert, debug_attr_buffer, dedupe_ways_hash, flags_attr_value, flagsa, fprintf(), g_hash_table_insert(), g_hash_table_lookup(), GET_REF, maptool_osm::house_number_interpolations, i, ignore_unknown, in_way, init_item(), item_bin_add_attr_int(), item_bin_add_attr_longlong(), item_bin_add_attr_string(), item_bin_add_coord(), item_bin_write(), item_get_default_flags(), maptool_osm::line2poi, maxspeed_attr_value, nodes_ref_item_bin(), osmid_attr_value, OSMID_FMT, maptool_osm::poly2poi, types, wayid, and maptool_osm::ways.
Referenced by map_collect_data_osm(), map_collect_data_osm_o5m(), and process_way().
void osm_info (char * type, osmid id, int cont, char * fmt, ...)
References NULL, and osm_logv().
Referenced by process_boundaries_setup().
void osm_init (FILE * rule_file)
References build_attrmap(), and build_countrytable().
Referenced by maptool_init().
static void osm_logv (char * prefix, char * objtype, osmid id, int cont, struct coord_geo * geo, char * fmt, va_list ap) static
References fprintf(), coord_geo::lat, coord_geo::lng, and OSMID_FMT.
Referenced by itembin_warning(), osm_info(), and osm_warning().
static GList* osm_process_town_by_boundary (GList * bl, struct item_bin * town, struct coord * c) static
Find country which town belongs to. Find town administrative hierarchy attributes.
Parameters
in bl list of administrative boundaries (data is struct boundary *)
in town item_bin structure holding town information
in c town center coordinates
Returns
refernce to the list of town_country structures
References boundary_find_matches(), boundary::country, _GList::data, g_list_free(), g_list_next, match(), NULL, osm_process_town_by_boundary_update_attrs(), and town_country_list_insert_if_new().
Referenced by osm_process_towns().
static void osm_process_town_by_boundary_update_attrs (struct item_bin * town, struct town_country * tc, GList * matches) static
Update town attributes based on its administrative parents.
Parameters
in town town initial item_bin data
in/out tc town_country structure holding country information and town attributes to add to town item_bin
in matches list of administrative boundaries the town belongs to (data is struct boundary *)
Returns
nothing
References boundary::admin_centre, country_table::admin_levels, town_country::attrs, town_country::country, _GList::data, g_list_next, boundary::ib, item_bin_get_attr(), name, nodeid, NULL, osm_tag_value(), attr::str, item_bin::type, attr::type, and attr::u.
Referenced by osm_process_town_by_boundary().
static GList* osm_process_town_by_is_in (struct item_bin * ib) static
Find list of countries which town or district belongs to.
Parameters
in ib pointer to item_bin structure holding town information
Returns
refernce to a list of struct town_country* the town belongs to
References buf, country, country_table_hash, dup(), g_free(), g_hash_table_lookup(), g_strdup(), item_bin_get_attr(), NULL, and town_country_list_insert_if_new().
Referenced by osm_process_towns().
static char* osm_process_town_get_town_name_from_is_in (struct item_bin * ib, GHashTable * town_hash) static
Get town name from district is_in attribute if possible.
Parameters
in ib pointer to item_bin structure holding district information
in town_hash hash of all town names
Returns
refernce to a list of struct town_country* the town belongs to
References buf, dup(), g_free(), g_hash_table_lookup(), g_strdup(), item_bin_get_attr(), and NULL.
Referenced by osm_process_towns().
static GList* osm_process_town_unknown_country (void) static
References country_from_countryid(), g_list_prepend(), NULL, town_country_new(), and unknown.
Referenced by osm_process_towns().
void osm_process_towns (FILE * in, FILE * boundaries, FILE * ways, char * suffix)
References town_country::attrs, bytes_read, c, town_country::country, country_table::countryid, _GList::data, dup(), country_table::file, fprintf(), free_boundaries(), g_free(), g_hash_table_destroy(), g_hash_table_new_full(), g_hash_table_replace(), g_list_free(), g_list_next, g_str_equal(), g_str_hash(), g_strdup_printf(), i, item_bin_add_attr(), item_bin_dup(), item_bin_get_attr(), item_bin_remove_attr(), item_bin_write_match(), item_is_district, itembin_warning(), item_bin::len, MAX_TOWN_ADMIN_LEVELS, name, nodeid, NULL, osm_process_town_by_boundary(), osm_process_town_by_is_in(), osm_process_town_get_town_name_from_is_in(), osm_process_town_unknown_country(), osm_town_relations_to_poly(), process_boundaries(), processed_nodes, processed_nodes_out, processed_relations, processed_tiles, processed_ways, read_item(), SEEK_SET, sig_alrm(), sig_alrm_end(), attr::str, tempfile(), town_country_destroy(), attr::type, attr::u, and unknown_country.
Referenced by main().
static void osm_town_relations_to_poly (GList * boundaries, FILE * towns_poly) static
References boundary::children, coord_is_equal, _GList::data, geom_poly_segment::first, g_list_next, geom_poly_segment_type_way_outer, geom_poly_segment_type_way_unknown, boundary::ib, init_item(), item_bin_add_attr_longlong(), item_bin_add_attr_string(), item_bin_add_coord(), item_bin_write(), item_is_poly_place, geom_poly_segment::last, osm_tag_value(), boundary::sorted_segments, geom_poly_segment::type, and item_bin::type.
Referenced by osm_process_towns().
static void osm_update_attr_present (char * k, char * v) static
References attr_hash, attr_present, attr_present_count, BUFFER_SIZE, dbg_assert, g_hash_table_lookup(), g_strlcpy(), and p.
Referenced by osm_add_tag(), and relation_add_tag().
void osm_warning (char * type, osmid id, int cont, char * fmt, ...)
References NULL, and osm_logv().
Referenced by map_resolve_coords_and_split_at_intersections(), process_boundaries_finish(), process_boundaries_setup(), process_turn_restrictions_finish(), process_turn_restrictions_setup(), process_way2poi(), and relation_add_tag().
static void parse_relation_member_string (char * relation_member_string, struct relation_member * memb) static
References relation_member::id, RELATION_MEMBER_PARSE_FORMAT, relation_member::role, and relation_member::type.
Referenced by search_relation_member().
static void process_associated_street_member (void * func_priv, void * relation_priv, struct item_bin * member, void * member_priv_unused) static
References process_relation_member_func_priv::allocations, fp, g_list_prepend(), g_strdup(), item_bin_add_attr_string(), item_bin_get_attr(), item_bin_write(), item_is_street, name, associated_street::name, NULL, process_relation_member_func_priv::out, and item_bin::type.
Referenced by process_associated_streets_setup().
void process_associated_streets (FILE * in, struct files_relation_processing * files_relproc)
References process_relation_member_func_priv::allocations, g_list_foreach(), g_list_free(), files_relation_processing::nodes2_in, files_relation_processing::nodes2_out, files_relation_processing::nodes_in, files_relation_processing::nodes_out, NULL, process_relation_member_func_priv::out, process_associated_streets_setup(), relations_destroy(), relations_new(), relations_process(), SEEK_SET, files_relation_processing::ways_in, and files_relation_processing::ways_out.
Referenced by main().
static void process_associated_streets_setup (FILE * in, struct relations * relations, struct process_relation_member_func_priv * fp) static
References g_malloc0(), g_strlcpy(), relation_member::id, item_bin_get_relationid(), name, associated_street::name, NULL, osm_tag_value(), process_relation_member_func_priv::out, process_associated_street_member(), read_item(), rel_member_way, relation_func_writethrough(), relations_add_relation_default_entry(), relations_add_relation_member_entry(), relations_func_new(), associated_street::relid, search_relation_member(), SEEK_SET, and relation_member::type.
Referenced by process_associated_streets().
static void process_house_number_interpolation_member (void * func_priv, void * relation_priv, struct item_bin * member, void * member_priv_unused) static
References process_relation_member_func_priv::allocations, fp, g_list_prepend(), g_strconcat(), g_strdup(), house_number_interpolation::house_number_first_node, house_number_interpolation::house_number_last_node, item_bin_add_attr_string(), item_bin_get_attr(), item_bin_write(), nodeid, house_number_interpolation::nodeid_first_node, NULL, process_relation_member_func_priv::out, house_number_interpolation::street_name, and item_bin::type.
Referenced by process_house_number_interpolations_setup().
void process_house_number_interpolations (FILE * in, struct files_relation_processing * files_relproc)
References process_relation_member_func_priv::allocations, g_list_foreach(), g_list_free(), files_relation_processing::nodes2_in, files_relation_processing::nodes2_out, files_relation_processing::nodes_in, files_relation_processing::nodes_out, NULL, process_relation_member_func_priv::out, process_house_number_interpolations_setup(), relations_destroy(), relations_new(), relations_process(), SEEK_SET, files_relation_processing::ways_in, and files_relation_processing::ways_out.
Referenced by main().
static void process_house_number_interpolations_setup (FILE * in, struct relations * relations, struct process_relation_member_func_priv * fp) static
References dbg_assert, g_malloc0(), item_bin_get_nodeid_from_attr(), item_bin_get_wayid(), house_number_interpolation::nodeid_first_node, house_number_interpolation::nodeid_last_node, NULL, process_relation_member_func_priv::out, process_house_number_interpolation_member(), read_item(), rel_member_node, rel_member_way, relation_func_writethrough(), relations_add_relation_default_entry(), relations_add_relation_member_entry(), relations_func_new(), SEEK_SET, and house_number_interpolation::wayid.
Referenced by process_house_number_interpolations().
void process_turn_restrictions (FILE * in, FILE * coords, FILE * ways, FILE * ways_index, FILE * out)
References process_turn_restrictions_finish(), process_turn_restrictions_setup(), relations_destroy(), relations_new(), relations_process(), and SEEK_SET.
Referenced by osm_process_turn_restrictions().
static void process_turn_restrictions_dump_coord (struct coord * c, int count) static
References fprintf(), i, coord::x, and coord::y.
Referenced by process_turn_restrictions_finish().
static void process_turn_restrictions_finish (GList * tr, FILE * out) static
References turn_restriction::c, turn_restriction::c_count, _GList::data, fprintf(), g_free(), g_list_free(), g_list_next, item_bin_add_attr_range(), item_bin_add_coord(), item_bin_init(), item_bin_write(), NULL, turn_restriction::order, osm_warning(), overlap, process_turn_restrictions_dump_coord(), process_turn_restrictions_fromto(), turn_restriction::r, turn_restriction::relid, tile(), tmp_item_bin, and turn_restriction::type.
Referenced by process_turn_restrictions().
static void process_turn_restrictions_fromto (struct turn_restriction * t, int type, struct coord ** c) static
References turn_restriction::c, turn_restriction::c_count, coord_is_equal, i, and type.
Referenced by process_turn_restrictions_finish().
static void process_turn_restrictions_member (void * func_priv, void * relation_priv, struct item_bin * member, void * member_priv) static
References bbox_extend(), turn_restriction::c, turn_restriction::c_count, item_bin::clen, g_renew, rect::h, i, IS_REF, item_order_by_type(), long, turn_restriction::order, turn_restriction::r, item_bin::type, and type.
Referenced by process_turn_restrictions_setup().
static GList* process_turn_restrictions_setup (FILE * in, struct relations * relations) static
References g_list_append(), g_new0, relation_member::id, item_bin_get_relationid(), NULL, turn_restriction::order, osm_types, osm_warning(), process_turn_restrictions_member(), turn_restriction::r, read_item(), rel_member_node, rel_member_way, relations_add_relation_member_entry(), relations_func_new(), turn_restriction::relid, search_relation_member(), SEEK_SET, item_bin::type, relation_member::type, and turn_restriction::type.
Referenced by process_turn_restrictions().
void process_way2poi (FILE * in, FILE * out, int type)
Get POI coordinates from area/line coordinates.
Parameters
in *in input file with area/line coordinates.
in *out output file with POI coordinates
in type input file original contents type: type_line or type_area
Returns
nothing
References c1, c2, item_bin::clen, geom_line_middle(), geom_poly_centroid(), geom_poly_closest_point(), geom_poly_point_inside(), item_bin_get_wayid(), NULL, osm_warning(), read_item(), item_bin::type, and write_item_way_subsection().
Referenced by osm_process_way2poi().
void ref_ways (FILE * in)
References nodes_ref_item_bin(), read_item(), and SEEK_SET.
Referenced by osm_count_references().
static void relation_add_tag (char * k, char * v) static
References fprintf(), g_alloca, g_strlcpy(), item_bin_add_attr_string(), osm_update_attr_present(), osm_warning(), osmid_attr_value, sprintf(), tmp_item_bin, and item_bin::type.
Referenced by osm_add_tag().
static void relation_func_writethrough (void * func_priv, void * relation_priv_unused, struct item_bin * member, void * member_priv_unused) static
References item_bin_write().
Referenced by process_associated_streets_setup(), and process_house_number_interpolations_setup().
void remove_countryfiles (void)
References country_table, country_table::countryid, filename, i, country_table::nparts, country_table::size, sprintf(), tempfile_unlink(), and unlink().
Referenced by maptool_assemble_map().
static void remove_last_node_item_from_buffer (void) static
References node_buffer, and buffer::size.
Referenced by osm_add_node().
void resolve_ways (FILE * in, FILE * out)
References node_item::c, c, item_bin::clen, GET_REF, i, IS_REF, item_bin_write(), node_item_get(), read_item(), SEEK_SET, coord::x, and coord::y.
Referenced by osm_count_references().
static int search_relation_member (struct item_bin * ib, char * role, struct relation_member * memb, int * min_count) static
References item_bin_get_attr(), NULL, parse_relation_member_string(), and relation_member::role.
Referenced by process_associated_streets_setup(), and process_turn_restrictions_setup().
void sort_countries (int keep_tmpfiles)
References country_table, country_table::countryid, country_table::file, g_free(), g_strdup_printf(), i, item_bin_sort_file(), NULL, country_table::r, country_table::size, unlink(), and world_bbox.
Referenced by main().
static void town_country_destroy (struct town_country * tc) static
References g_free().
Referenced by osm_process_towns().
static struct town_country* town_country_list_insert_if_new (GList ** town_country_list, struct country_table * country) static
Insert a new record into the list of town info structures, if there's no such entry.
Parameters
in/out town_country_list pointer to GList* of town_country structures.
in country country to add the town to
Returns
refernce to then new town_country structure added to the list, or NULL if GList already had an entry for the country given
References country, _GList::data, g_list_next, g_list_prepend(), NULL, and town_country_new().
Referenced by osm_process_town_by_boundary(), and osm_process_town_by_is_in().
static struct town_country* town_country_new (struct country_table * country) static
References country, town_country::country, and g_malloc0().
Referenced by osm_process_town_unknown_country(), and town_country_list_insert_if_new().
void write_countrydir (struct zip_info * zip_info, int max_index_size)
References ATTR_IS_STRING, country_table, country_table::countryid, filename, g_free(), g_strlcpy(), i, index_country_add(), item_bin_get_attr_bin(), item_bin_get_attr_bin_last(), item_bin_read(), item_bin_remove_attr(), item_bin_write(), key, item_bin::len, max, country_table::nparts, NULL, overlap, country_table::r, country_table::size, tempfile(), tempfile_name(), tile(), attr_bin::type, and zip_get_index().
Referenced by maptool_assemble_map().
static void write_item_way_subsection (FILE * out, FILE * out_index, FILE * out_graph, struct item_bin * orig, int first, int last, long long * last_id) static
References item_bin::clen, dbg_assert, fprintf(), item_bin::len, processed_ways, item_bin::type, type, and write_item_way_subsection_index().
Referenced by map_resolve_coords_and_split_at_intersections(), and process_way2poi().
static void write_item_way_subsection_index (FILE * out, FILE * out_index, FILE * out_graph, struct item_bin * orig, long long * last_id) static
References dbg_assert, g_hash_table_insert(), g_hash_table_lookup_extended(), item_bin_get_wayid(), NULL, and way_hash.
Referenced by write_item_way_subsection().
Variable Documentation
static GHashTable * attr_hash static
Referenced by build_attrmap(), build_attrmap_line(), and osm_update_attr_present().
struct attr_mapping** attr_mapping_node static
int attr_mapping_node_count static
Referenced by build_attrmap_line(), and osm_end_node().
struct attr_mapping** attr_mapping_rel2poly_place static
int attr_mapping_rel2poly_place_count static
Referenced by build_attrmap_line(), and osm_end_relation().
struct attr_mapping** attr_mapping_way static
struct attr_mapping** attr_mapping_way2poi static
int attr_mapping_way2poi_count static
Referenced by build_attrmap_line(), and osm_end_way().
int attr_mapping_way_count static
Referenced by build_attrmap_line(), and osm_end_way().
char* attr_present static
Referenced by attr_longest_match(), attr_longest_match_clear(), build_attrmap(), and osm_update_attr_present().
int attr_present_count static
Referenced by attr_longest_match_clear(), build_attrmap(), build_attrmap_line(), and osm_update_attr_present().
char* attr_strings[attr_string_last]
Referenced by attr_strings_clear(), attr_strings_save(), osm_add_tag(), osm_end_node(), and osm_end_way().
char attr_strings_buffer[BUFFER_SIZE *16]
Referenced by attr_strings_save().
int attr_strings_buffer_free_offset
Referenced by attr_strings_clear(), and attr_strings_save().
char* attrmap static
Referenced by build_attrmap(), and gui_internal_cmd_results_to_map().
int boundary
struct coord coord_buffer[MAX_COORD_COUNT]
Referenced by osm_add_nd(), and osm_end_way().
int coord_count
Referenced by osm_add_nd(), osm_add_way(), and osm_end_way().
struct country_table country_table[]
Referenced by build_countrytable(), country_from_countryid(), load_countries(), remove_countryfiles(), sort_countries(), and write_countrydir().
GHashTable * country_table_hash static
Referenced by build_countrytable(), and osm_process_town_by_is_in().
struct node_item* current_node static
The node currently being processed.
char debug_attr_buffer[BUFFER_SIZE]
Referenced by osm_add_node(), osm_add_relation(), osm_add_tag(), osm_add_way(), osm_end_node(), and osm_end_way().
int flags[4]
int flags_attr_value
Referenced by osm_add_way(), and osm_end_way().
int flagsa[4]
Referenced by osm_add_tag(), osm_add_way(), and osm_end_way().
osmid id_last_node
ID of the last node processed.
Referenced by osm_add_node().
int in_node static
Referenced by osm_add_node(), and osm_end_node().
int in_relation static
Referenced by osm_add_relation(), osm_add_tag(), and osm_end_relation().
int in_way static
Referenced by osm_add_tag(), osm_add_way(), and osm_end_way().
char is_in_buffer[BUFFER_SIZE]
Referenced by osm_add_node(), osm_add_tag(), and osm_end_node().
char iso_code[BUFFER_SIZE]
struct item_bin item static
Referenced by bookmarks_load_hash(), bookmarks_store_bookmarks_to_file(), cJSON_AddItemToArray(), cJSON_CreateArray(), cJSON_CreateBool(), cJSON_CreateFalse(), cJSON_CreateNull(), cJSON_CreateNumber(), cJSON_CreateObject(), cJSON_CreateString(), cJSON_CreateTrue(), country_id_from_iso2(), destination_address(), display_add(), do_draw(), Backend::get_bookmarks(), get_item_seg_coords(), Backend::get_pois(), NGQProxyBookmarks::getBookmarks(), graphics_add_selection(), graphics_process_selection_item(), gui_gtk_bookmarks_update(), gui_gtk_destinations_update(), gui_internal_cmd_bookmarks(), gui_internal_cmd_delete_waypoint(), gui_internal_cmd_formerdests(), gui_internal_cmd_load_bookmarks_as_waypoints(), gui_internal_cmd_map_download_do(), gui_internal_cmd_pois(), gui_internal_cmd_pois_item(), gui_internal_cmd_position_do(), gui_internal_cmd_replace_bookmarks_from_waypoints(), gui_internal_cmd_results_to_map(), gui_internal_cmd_view_attribute_details(), gui_internal_cmd_view_attributes(), gui_internal_cmd_view_in_browser(), gui_internal_create_resultlist_entry(), gui_internal_populate_route_table(), gui_internal_search_list_set_default_country(), gui_internal_select_waypoint(), item_hash_insert(), map_binfile_open(), map_dump_filedesc(), map_search_new_mg(), mapset_search_new(), model_poi(), navigation_get_attr(), navit_add_former_destinations_from_file(), navit_speak(), navit_window_roadbook_update(), navit_zoom_to_route(), NGQProxySearch::NGQProxySearch(), osd_speed_warner_draw(), phase1_map(), popup_show_item(), quadtree_add(), read_former_destination_map_as_list(), org.navitproject.navit.NavitAddressSearchActivity::requestCountryDialog(), route_find_nearest_street(), route_get_destination_description(), route_graph_build_idle(), route_graph_set_traffic_distortion(), route_process_street_graph(), route_process_traffic_distortion(), route_process_turn_restriction(), search_list_country_new(), search_list_house_number_new(), search_list_street_new(), search_list_town_new(), NGQProxyBookmarks::setPoint(), street_get_data(), street_search_get_item(), suffix_object(), tracking_doupdate_lines(), and tracking_get_attr().
int maxspeed_attr_value
Referenced by osm_add_tag(), osm_add_way(), and osm_end_way().
GHashTable* node_hash
Referenced by node_buffer_to_hash(), node_item_get(), and osm_add_node().
int node_is_tagged static
Referenced by osm_add_node(), osm_add_tag(), and osm_end_node().
osmid nodeid
Referenced by ch_assemble_map(), osm_add_node(), osm_end_node(), osm_process_town_by_boundary_update_attrs(), osm_process_towns(), and process_house_number_interpolation_member().
char* osm_types[] ={"unknown","node","way","relation"}
Referenced by process_turn_restrictions_setup().
struct attr_bin osmid_attr
Referenced by osm_add_node().
long long osmid_attr_value
Referenced by osm_add_node(), osm_add_relation(), osm_add_way(), osm_end_node(), osm_end_way(), and relation_add_tag().
char relation_type[BUFFER_SIZE]
GHashTable * way_hash
Referenced by osm_add_way(), and write_item_way_subsection_index().
osmid wayid
Referenced by ocean_tile(), osm_add_way(), and osm_end_way().