navit: maptool/osm_protobuf.c File Reference
osm_protobuf.c File Reference
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <time.h>
#include <zlib.h>
#include "maptool.h"
#include "debug.h"
#include "linguistics.h"
#include "file.h"
#include "generated-code/fileformat.pb-c.h"
#include "generated-code/osmformat.pb-c.h"
Macros
#define MAX_HEADER_LENGTH 1024 * 64
#define MAX_BLOB_LENGTH 1024 * 1024 * 32
#define SANITY_CHECK_LENGTH(length, max_length)
Functions
static OSMPBF__BlobHeader * read_header (FILE *f)
static OSMPBF__Blob * read_blob (OSMPBF__BlobHeader *header, FILE *f, unsigned char *buffer)
static unsigned char * uncompress_blob (OSMPBF__Blob *blob)
static int get_string (char *buffer, int buffer_size, OSMPBF__PrimitiveBlock *primitive_block, int id, int escape)
static void process_osmheader (OSMPBF__Blob *blob, unsigned char *data)
static void process_tag (OSMPBF__PrimitiveBlock *primitive_block, int key, int val)
static void process_dense (OSMPBF__PrimitiveBlock *primitive_block, OSMPBF__DenseNodes *dense, struct maptool_osm *osm)
static void process_way (OSMPBF__PrimitiveBlock *primitive_block, OSMPBF__Way *way, struct maptool_osm *osm)
static void process_relation (OSMPBF__PrimitiveBlock *primitive_block, OSMPBF__Relation *relation, struct maptool_osm *osm)
static void process_osmdata (OSMPBF__Blob *blob, unsigned char *data, struct maptool_osm *osm)
int map_collect_data_osm_protobuf (FILE *in, struct maptool_osm *osm)
Variables
static double latlon_scale =10000000.0
Macro Definition Documentation
#define MAX_BLOB_LENGTH 1024 * 1024 * 32
Referenced by map_collect_data_osm_protobuf(), and read_blob().
#define MAX_HEADER_LENGTH 1024 * 64
Referenced by read_header().
#define SANITY_CHECK_LENGTH (length, max_length)
Value:
if (length > max_length){                                          \
        fprintf(stderr,"Not a valid protobuf file. "               \
                        "Invalid block size in input: %d, max is %d. \n",  \
                                length, max_length);                       \
        return NULL;                                                   \
        }
Referenced by read_blob(), and read_header().
Function Documentation
static int get_string (char * buffer, int buffer_size, OSMPBF__PrimitiveBlock * primitive_block, int id, int escape) static
References buffer, _ProtobufCBinaryData::data, data, i, o5m::id, if(), _ProtobufCBinaryData::len, p, _OSMPBF__StringTable::s, sprintf(), and _OSMPBF__PrimitiveBlock::stringtable.
Referenced by process_relation(), and process_tag().
int map_collect_data_osm_protobuf (FILE * in, struct maptool_osm * osm)
References data, MAX_BLOB_LENGTH, osmpbf__blob__free_unpacked(), osmpbf__blob_header__free_unpacked(), printf(), process_osmdata(), process_osmheader(), protobuf_c_system_allocator, read_blob(), read_header(), _OSMPBF__BlobHeader::type, and uncompress_blob().
Referenced by osm_read_input_data().
static void process_dense (OSMPBF__PrimitiveBlock * primitive_block, OSMPBF__DenseNodes * dense, struct maptool_osm * osm) static
References _OSMPBF__DenseInfo::changeset, _OSMPBF__DenseNodes::denseinfo, i, _OSMPBF__DenseNodes::id, _OSMPBF__DenseNodes::keys_vals, _OSMPBF__DenseNodes::lat, lat, latlon_scale, _OSMPBF__DenseNodes::lon, _OSMPBF__DenseNodes::n_id, osm_add_node(), osm_end_node(), printf(), process_tag(), _OSMPBF__DenseInfo::timestamp, _OSMPBF__DenseInfo::uid, _OSMPBF__DenseInfo::user_sid, and _OSMPBF__DenseInfo::version.
Referenced by process_osmdata().
static void process_osmdata (OSMPBF__Blob * blob, unsigned char * data, struct maptool_osm * osm) static
References _OSMPBF__PrimitiveGroup::dense, i, _OSMPBF__PrimitiveGroup::n_changesets, _OSMPBF__PrimitiveGroup::n_nodes, _OSMPBF__PrimitiveBlock::n_primitivegroup, _OSMPBF__PrimitiveGroup::n_relations, _OSMPBF__PrimitiveGroup::n_ways, osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_block__unpack(), _OSMPBF__PrimitiveBlock::primitivegroup, printf(), process_dense(), process_relation(), process_way(), protobuf_c_system_allocator, _OSMPBF__PrimitiveGroup::relations, and _OSMPBF__PrimitiveGroup::ways.
Referenced by map_collect_data_osm_protobuf().
static void process_osmheader (OSMPBF__Blob * blob, unsigned char * data) static
References osmpbf__header_block__free_unpacked(), osmpbf__header_block__unpack(), and protobuf_c_system_allocator.
Referenced by map_collect_data_osm_protobuf().
static void process_relation (OSMPBF__PrimitiveBlock * primitive_block, OSMPBF__Relation * relation, struct maptool_osm * osm) static
References get_string(), i, _OSMPBF__Relation::id, _OSMPBF__Relation::info, _OSMPBF__Relation::keys, _OSMPBF__Relation::memids, _OSMPBF__Relation::n_keys, _OSMPBF__Relation::n_roles_sid, osm_add_member(), osm_add_relation(), osm_end_relation(), printf(), process_tag(), _OSMPBF__Relation::roles_sid, _OSMPBF__Relation::types, and _OSMPBF__Relation::vals.
Referenced by process_osmdata().
static void process_tag (OSMPBF__PrimitiveBlock * primitive_block, int key, int val) static
References get_string(), osm_add_tag(), and printf().
Referenced by process_dense(), process_relation(), and process_way().
static void process_way (OSMPBF__PrimitiveBlock * primitive_block, OSMPBF__Way * way, struct maptool_osm * osm) static
References i, _OSMPBF__Way::id, _OSMPBF__Way::info, _OSMPBF__Way::keys, _OSMPBF__Way::n_keys, _OSMPBF__Way::n_refs, osm_add_nd(), osm_add_way(), osm_end_way(), printf(), process_tag(), _OSMPBF__Way::refs, and _OSMPBF__Way::vals.
Referenced by process_osmdata().
static OSMPBF__Blob* read_blob (OSMPBF__BlobHeader * header, FILE * f, unsigned char * buffer) static
References _OSMPBF__BlobHeader::datasize, MAX_BLOB_LENGTH, NULL, osmpbf__blob__unpack(), protobuf_c_system_allocator, and SANITY_CHECK_LENGTH.
Referenced by map_collect_data_osm_protobuf().
static OSMPBF__BlobHeader* read_header (FILE * f) static
References alloca, buffer, MAX_HEADER_LENGTH, NULL, osmpbf__blob_header__unpack(), protobuf_c_system_allocator, and SANITY_CHECK_LENGTH.
Referenced by map_collect_data_osm_protobuf().
static unsigned char* uncompress_blob (OSMPBF__Blob * blob) static
References z_stream_s::avail_in, z_stream_s::avail_out, inflate(), inflateEnd(), inflateInit, z_stream_s::next_in, z_stream_s::next_out, NULL, z_stream_s::opaque, Z_NO_FLUSH, Z_NULL, Z_OK, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by map_collect_data_osm_protobuf().
Variable Documentation
double latlon_scale =10000000.0 static
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by process_dense().