navit: maptool/osm_xml.c File Reference
osm_xml.c File Reference
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include "maptool.h"
Data Structures
struct entity
Functions
int osm_xml_get_attribute (char *xml, char *attribute, char *buffer, int buffer_size)
void osm_xml_decode_entities (char *buffer)
static int parse_tag (char *p)
static int parse_node (char *p)
static int parse_way (char *p)
static int parse_relation (char *p)
static int parse_member (char *p)
static int parse_nd (char *p)
static int xml_declaration_in_line (char *buffer)
int map_collect_data_osm (FILE *in, struct maptool_osm *osm)
Variables
static struct entity entities []
Function Documentation
int map_collect_data_osm (FILE * in, struct maptool_osm * osm)
References BUFFER_SIZE, exit, fprintf(), osm_end_node(), osm_end_relation(), osm_end_way(), p, parse_member(), parse_nd(), parse_node(), parse_relation(), parse_tag(), parse_way(), processed_nodes, processed_relations, processed_ways, sig_alrm(), sig_alrm_end(), size, and xml_declaration_in_line().
Referenced by osm_read_input_data().
void osm_xml_decode_entities (char * buffer)
References buffer, entity::c, entities, i, and startup::pos.
Referenced by osm_protobufdb_parse_info(), osm_protobufdb_parse_tag(), and parse_tag().
int osm_xml_get_attribute (char * xml, char * attribute, char * buffer, int buffer_size)
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References fprintf(), g_alloca, i, and startup::pos.
Referenced by osm_protobufdb_parse_info(), osm_protobufdb_parse_member(), osm_protobufdb_parse_nd(), osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), osm_protobufdb_parse_tag(), osm_protobufdb_parse_way(), parse_member(), parse_nd(), parse_node(), parse_relation(), parse_tag(), and parse_way().
static int parse_member (char * p) static
References BUFFER_SIZE, fprintf(), osm_add_member(), osm_xml_get_attribute(), rel_member_node, rel_member_relation, rel_member_way, and type.
Referenced by map_collect_data_osm().
static int parse_nd (char * p) static
References BUFFER_SIZE, osm_add_nd(), and osm_xml_get_attribute().
Referenced by map_collect_data_osm().
static int parse_node (char * p) static
References BUFFER_SIZE, osm_add_node(), and osm_xml_get_attribute().
Referenced by map_collect_data_osm().
static int parse_relation (char * p) static
References BUFFER_SIZE, osm_add_relation(), and osm_xml_get_attribute().
Referenced by map_collect_data_osm().
static int parse_tag (char * p) static
References BUFFER_SIZE, osm_add_tag(), osm_xml_decode_entities(), and osm_xml_get_attribute().
Referenced by map_collect_data_osm().
static int parse_way (char * p) static
References BUFFER_SIZE, osm_add_way(), and osm_xml_get_attribute().
Referenced by map_collect_data_osm().
static int xml_declaration_in_line (char * buffer) static
Referenced by map_collect_data_osm().
Variable Documentation
struct entity entities[] static
Initial value:
= {
        {"&quot;",'"'},
        {"&apos;",'\''},
        {"&amp;",'&'},
        {"&lt;",'<'},
        {"&gt;",'>'},
        {"&#34;",'"'},
        {"&#39;",'\''},
        {"&#38;",'&'},
        {"&#60;",'<'},
        {"&#62;",'>'},
        {"&#123;",'{'},
        {"&#125;",'}'},
}
Referenced by osm_xml_decode_entities().