navit: maptool/osm_protobufdb.c File Reference
osm_protobufdb.c File Reference
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <time.h>
#include <zlib.h>
#include "maptool.h"
#include "debug.h"
#include "linguistics.h"
#include "file.h"
#include "generated-code/fileformat.pb-c.h"
#include "generated-code/osmformat.pb-c.h"
Data Structures
struct db_config
struct osm_protobufdb_context
Macros
#define insert(struct, member, pos)
Functions
static int osm_protobufdb_write_blob (OSMPBF__Blob *blob, FILE *out)
static int osm_protobufdb_finish_block (struct osm_protobufdb_context *ctx)
static int osm_protobufdb_start_block (struct osm_protobufdb_context *ctx, int blocknum)
static int osm_protobufdb_start_group (struct osm_protobufdb_context *ctx, int groupnum)
static int osm_protobufdb_insert_node (long long id, OSMPBF__PrimitiveGroup *pg)
static void osm_protobufdb_modify_node (OSMPBF__Node *node, OSMPBF__Info *info, int pos, OSMPBF__PrimitiveGroup *pg)
static int osm_protobufdb_insert_way (long long id, OSMPBF__PrimitiveGroup *pg)
static void osm_protobufdb_modify_way (OSMPBF__Way *way, OSMPBF__Info *info, int pos, OSMPBF__PrimitiveGroup *pg)
static int osm_protobufdb_insert_relation (long long id, OSMPBF__PrimitiveGroup *pg)
static void osm_protobufdb_modify_relation (OSMPBF__Relation *relation, OSMPBF__Info *info, int pos, OSMPBF__PrimitiveGroup *pg)
static int osm_protobufdb_string (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_finish_file (struct osm_protobufdb_context *ctx)
static int osm_protobufdb_start_file (struct osm_protobufdb_context *ctx, int type, int num)
static void test (void)
static void finish (void)
static long long osm_protobufdb_timestamp (char *str)
static void osm_protobufdb_parse_info (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_parse_node (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_end_node (struct osm_protobufdb_context *ctx)
static int osm_protobufdb_parse_way (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_end_way (struct osm_protobufdb_context *ctx)
static int osm_protobufdb_parse_relation (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_end_relation (struct osm_protobufdb_context *ctx)
static int osm_protobufdb_parse_tag (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_parse_nd (struct osm_protobufdb_context *ctx, char *str)
static int osm_protobufdb_parse_member (struct osm_protobufdb_context *ctx, char *str)
int osm_protobufdb_load (FILE *in, char *dir)
Variables
static double latlon_scale =10000000.0
struct db_config db_config
struct osm_protobufdb_context context
Macro Definition Documentation
#define insert (struct, member, pos)
Value:
{\
    int n=struct->n_##member; \
    int s=sizeof(struct->member[0]); \
        struct->member=realloc(struct->member, (n+1)*s); \
        memmove(&struct->member[n+1], &struct->member[n], (pos-n)*s); \
        memset(&struct->member[n], 0, s); \
        struct->n_##member++;\
}
Referenced by image_new(), osm_protobufdb_insert_node(), osm_protobufdb_insert_relation(), and osm_protobufdb_insert_way().
Function Documentation
static void finish (void) static
References osm_protobufdb_finish_file().
Referenced by org.navitproject.navit.NavitDownloadSelectMapActivity::askForMapDeletion(), compile_rule(), org.navitproject.navit.NavitAddressSearchActivity::finishAddressSearch(), org.navitproject.navit.NavitDownloadSelectMapActivity::onChildClick(), org.navitproject.navit.NavitDownloadSelectMapActivity::onCreate(), org.navitproject.navit.NavitAddressSearchActivity::onCreate(), and osm_protobufdb_load().
static int osm_protobufdb_end_node (struct osm_protobufdb_context * ctx) static
References osm_protobufdb_context::i, _OSMPBF__Node::id, osm_protobufdb_context::in_node, osm_protobufdb_context::n, offset, osm_protobufdb_insert_node(), osm_protobufdb_modify_node(), p, and osm_protobufdb_context::pg.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_end_relation (struct osm_protobufdb_context * ctx) static
References osm_protobufdb_context::i, _OSMPBF__Relation::id, osm_protobufdb_context::in_node, osm_protobufdb_insert_relation(), osm_protobufdb_modify_relation(), p, osm_protobufdb_context::pg, and osm_protobufdb_context::r.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_end_way (struct osm_protobufdb_context * ctx) static
References osm_protobufdb_context::i, _OSMPBF__Way::id, osm_protobufdb_context::in_way, osm_protobufdb_insert_way(), osm_protobufdb_modify_way(), p, osm_protobufdb_context::pg, and osm_protobufdb_context::w.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_finish_block (struct osm_protobufdb_context * ctx) static
References osm_protobufdb_context::active_block, osm_protobufdb_context::current_block, osm_protobufdb_context::f, NULL, osm_protobufdb_write_blob(), osmpbf__blob__free_unpacked(), OSMPBF__BLOB__INIT, osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_block__pack(), osm_protobufdb_context::pb, and protobuf_c_system_allocator.
Referenced by osm_protobufdb_finish_file(), and osm_protobufdb_start_block().
static int osm_protobufdb_finish_file (struct osm_protobufdb_context * ctx) static
References osm_protobufdb_context::current_file, osm_protobufdb_context::f, NULL, and osm_protobufdb_finish_block().
Referenced by finish(), and osm_protobufdb_start_file().
static int osm_protobufdb_insert_node (long long id, OSMPBF__PrimitiveGroup * pg) static
References insert, _OSMPBF__PrimitiveGroup::n_nodes, nodes, _OSMPBF__PrimitiveGroup::nodes, OSMPBF__NODE__INIT, and p.
Referenced by osm_protobufdb_end_node().
static int osm_protobufdb_insert_relation (long long id, OSMPBF__PrimitiveGroup * pg) static
References insert, _OSMPBF__PrimitiveGroup::n_relations, OSMPBF__RELATION__INIT, p, and _OSMPBF__PrimitiveGroup::relations.
Referenced by osm_protobufdb_end_relation().
static int osm_protobufdb_insert_way (long long id, OSMPBF__PrimitiveGroup * pg) static
References insert, _OSMPBF__PrimitiveGroup::n_ways, OSMPBF__WAY__INIT, p, and _OSMPBF__PrimitiveGroup::ways.
Referenced by osm_protobufdb_end_way().
int osm_protobufdb_load (FILE * in, char * dir)
References BUFFER_SIZE, finish(), fprintf(), osm_protobufdb_end_node(), osm_protobufdb_end_relation(), osm_protobufdb_end_way(), osm_protobufdb_parse_member(), osm_protobufdb_parse_nd(), osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), osm_protobufdb_parse_tag(), osm_protobufdb_parse_way(), p, processed_nodes, processed_relations, processed_ways, sig_alrm(), size, and test().
Referenced by main().
static void osm_protobufdb_modify_node (OSMPBF__Node * node, OSMPBF__Info * info, int pos, OSMPBF__PrimitiveGroup * pg) static
References _OSMPBF__Node::info, info, _OSMPBF__Node::keys, _OSMPBF__PrimitiveGroup::nodes, NULL, osmpbf__info__free_unpacked(), startup::pos, protobuf_c_system_allocator, and _OSMPBF__Node::vals.
Referenced by osm_protobufdb_end_node().
static void osm_protobufdb_modify_relation (OSMPBF__Relation * relation, OSMPBF__Info * info, int pos, OSMPBF__PrimitiveGroup * pg) static
References i, _OSMPBF__Relation::info, info, _OSMPBF__Relation::keys, _OSMPBF__Relation::memids, _OSMPBF__Relation::n_memids, NULL, osmpbf__info__free_unpacked(), startup::pos, protobuf_c_system_allocator, _OSMPBF__PrimitiveGroup::relations, _OSMPBF__Relation::roles_sid, _OSMPBF__Relation::types, and _OSMPBF__Relation::vals.
Referenced by osm_protobufdb_end_relation().
static void osm_protobufdb_modify_way (OSMPBF__Way * way, OSMPBF__Info * info, int pos, OSMPBF__PrimitiveGroup * pg) static
References i, _OSMPBF__Way::info, info, _OSMPBF__Way::keys, _OSMPBF__Way::n_refs, NULL, osmpbf__info__free_unpacked(), startup::pos, protobuf_c_system_allocator, _OSMPBF__Way::refs, _OSMPBF__Way::vals, and _OSMPBF__PrimitiveGroup::ways.
Referenced by osm_protobufdb_end_way().
static void osm_protobufdb_parse_info (struct osm_protobufdb_context * ctx, char * str) static
References _OSMPBF__Info::changeset, _OSMPBF__Info::has_changeset, _OSMPBF__Info::has_timestamp, _OSMPBF__Info::has_uid, _OSMPBF__Info::has_user_sid, _OSMPBF__Info::has_version, osm_protobufdb_context::i, osm_protobufdb_string(), osm_protobufdb_timestamp(), osm_xml_decode_entities(), osm_xml_get_attribute(), OSMPBF__INFO__INIT, _OSMPBF__Info::timestamp, _OSMPBF__Info::uid, _OSMPBF__Info::user_sid, version, and _OSMPBF__Info::version.
Referenced by osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), and osm_protobufdb_parse_way().
static int osm_protobufdb_parse_member (struct osm_protobufdb_context * ctx, char * str) static
References BUFFER_SIZE, osm_protobufdb_context::in_relation, _OSMPBF__Relation::memids, _OSMPBF__Relation::n_memids, _OSMPBF__Relation::n_roles_sid, _OSMPBF__Relation::n_types, osm_protobufdb_string(), osm_xml_get_attribute(), osm_protobufdb_context::r, _OSMPBF__Relation::roles_sid, type, and _OSMPBF__Relation::types.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_parse_nd (struct osm_protobufdb_context * ctx, char * str) static
References BUFFER_SIZE, osm_protobufdb_context::in_way, _OSMPBF__Way::n_refs, osm_xml_get_attribute(), _OSMPBF__Way::refs, and osm_protobufdb_context::w.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_parse_node (struct osm_protobufdb_context * ctx, char * str) static
References _OSMPBF__Node::id, osm_protobufdb_context::in_node, _OSMPBF__Node::lat, lat, latlon_scale, _OSMPBF__Node::lon, osm_protobufdb_context::n, db_config::node_ids_per_blob, db_config::node_ids_per_file, db_config::node_ids_per_group, osm_protobufdb_parse_info(), osm_protobufdb_start_block(), osm_protobufdb_start_file(), osm_protobufdb_start_group(), osm_xml_get_attribute(), and OSMPBF__NODE__INIT.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_parse_relation (struct osm_protobufdb_context * ctx, char * str) static
References _OSMPBF__Relation::id, osm_protobufdb_context::in_relation, osm_protobufdb_parse_info(), osm_protobufdb_start_block(), osm_protobufdb_start_file(), osm_protobufdb_start_group(), osm_xml_get_attribute(), OSMPBF__RELATION__INIT, osm_protobufdb_context::r, db_config::relation_ids_per_blob, db_config::relation_ids_per_file, and db_config::relation_ids_per_group.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_parse_tag (struct osm_protobufdb_context * ctx, char * str) static
References BUFFER_SIZE, osm_protobufdb_context::in_node, osm_protobufdb_context::in_relation, osm_protobufdb_context::in_way, _OSMPBF__Node::keys, _OSMPBF__Way::keys, _OSMPBF__Relation::keys, osm_protobufdb_context::n, _OSMPBF__Node::n_keys, _OSMPBF__Way::n_keys, _OSMPBF__Relation::n_keys, _OSMPBF__Node::n_vals, _OSMPBF__Way::n_vals, _OSMPBF__Relation::n_vals, osm_protobufdb_string(), osm_xml_decode_entities(), osm_xml_get_attribute(), osm_protobufdb_context::r, _OSMPBF__Node::vals, _OSMPBF__Way::vals, _OSMPBF__Relation::vals, and osm_protobufdb_context::w.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_parse_way (struct osm_protobufdb_context * ctx, char * str) static
References _OSMPBF__Way::id, osm_protobufdb_context::in_way, osm_protobufdb_parse_info(), osm_protobufdb_start_block(), osm_protobufdb_start_file(), osm_protobufdb_start_group(), osm_xml_get_attribute(), OSMPBF__WAY__INIT, osm_protobufdb_context::w, db_config::way_ids_per_blob, db_config::way_ids_per_file, and db_config::way_ids_per_group.
Referenced by osm_protobufdb_load().
static int osm_protobufdb_start_block (struct osm_protobufdb_context * ctx, int blocknum) static
References osm_protobufdb_context::active_block, osm_protobufdb_finish_block(), OSMPBF__PRIMITIVE_BLOCK__INIT, OSMPBF__STRING_TABLE__INIT, osm_protobufdb_context::pb, st, osm_protobufdb_context::st, and _OSMPBF__PrimitiveBlock::stringtable.
Referenced by osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), and osm_protobufdb_parse_way().
static int osm_protobufdb_start_file (struct osm_protobufdb_context * ctx, int type, int num) static
References osm_protobufdb_context::active_block, osm_protobufdb_context::current_block, osm_protobufdb_context::current_file, osm_protobufdb_context::f, name, num, osm_protobufdb_finish_file(), and sprintf().
Referenced by osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), and osm_protobufdb_parse_way().
static int osm_protobufdb_start_group (struct osm_protobufdb_context * ctx, int groupnum) static
References g_hash_table_destroy(), g_hash_table_new(), g_str_equal(), g_str_hash(), _OSMPBF__PrimitiveBlock::n_primitivegroup, OSMPBF__PRIMITIVE_GROUP__INIT, osm_protobufdb_context::pb, osm_protobufdb_context::pg, _OSMPBF__PrimitiveBlock::primitivegroup, and osm_protobufdb_context::string_hash.
Referenced by osm_protobufdb_parse_node(), osm_protobufdb_parse_relation(), and osm_protobufdb_parse_way().
static int osm_protobufdb_string (struct osm_protobufdb_context * ctx, char * str) static
References _ProtobufCBinaryData::data, g_hash_table_insert(), g_hash_table_lookup_extended(), _ProtobufCBinaryData::len, _OSMPBF__StringTable::n_s, NULL, _OSMPBF__StringTable::s, st, osm_protobufdb_context::st, osm_protobufdb_context::string_hash, and value.
Referenced by osm_protobufdb_parse_info(), osm_protobufdb_parse_member(), and osm_protobufdb_parse_tag().
static long long osm_protobufdb_timestamp (char * str) static
Referenced by osm_protobufdb_parse_info().
static int osm_protobufdb_write_blob (OSMPBF__Blob * blob, FILE * out) static
References alloca, buffer, _OSMPBF__BlobHeader::datasize, osmpbf__blob__get_packed_size(), osmpbf__blob__pack(), osmpbf__blob_header__get_packed_size(), OSMPBF__BLOB_HEADER__INIT, osmpbf__blob_header__pack(), and _OSMPBF__BlobHeader::type.
Referenced by osm_protobufdb_finish_block().
static void test (void) static
References _OSMPBF__DenseInfo::changeset, data, _OSMPBF__DenseNodes::id, _OSMPBF__DenseNodes::lat, lat, _OSMPBF__DenseNodes::lon, _OSMPBF__DenseInfo::n_changeset, _OSMPBF__DenseNodes::n_id, _OSMPBF__DenseNodes::n_lat, _OSMPBF__DenseNodes::n_lon, _OSMPBF__DenseInfo::n_timestamp, _OSMPBF__DenseInfo::n_uid, _OSMPBF__DenseInfo::n_user_sid, _OSMPBF__DenseInfo::n_version, OSMPBF__DENSE_INFO__INIT, OSMPBF__DENSE_NODES__INIT, p, st, _OSMPBF__DenseInfo::timestamp, _OSMPBF__DenseInfo::uid, _OSMPBF__DenseInfo::user_sid, version, and _OSMPBF__DenseInfo::version.
Referenced by osm_protobufdb_load(), and process_boundaries_finish().
Variable Documentation
struct osm_protobufdb_context context
Referenced by org.navitproject.navit.NavitBackupTask::NavitBackupTask(), org.navitproject.navit.NavitRestoreTask::NavitRestoreTask(), parse_file(), and xml_parse_text().
struct db_config db_config
Initial value:
= {
        200000, 30000, 500,
         40000,  1000,  30,
         10000,   500,  20,
}
double latlon_scale =10000000.0 static
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by osm_protobufdb_parse_node().