navit: maptool/osm_o5m.c File Reference
osm_o5m.c File Reference
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "maptool.h"
Data Structures
struct o5m
struct string_table
Macros
#define buffer_end(o, x) ((o)->buffer_start+(x) > (o)->buffer_end && !fill_buffer((o), (x)))
Functions
static int fill_buffer (struct o5m *o, int min)
static unsigned long long get_uval (unsigned char **p)
static long long get_sval (unsigned char **p)
static void get_strings (struct string_table *st, unsigned char **p, char **s1, char **s2)
static void get_strings_ref (struct string_table *st, int ref, char **s1, char **s2)
static void print_escaped (char *s)
static void o5m_reset (struct o5m *o)
static void o5m_print_start (struct o5m *o, int c)
static void o5m_print_version (struct o5m *o, int tags)
static void o5m_print_end (char c)
int map_collect_data_osm_o5m (FILE *in, struct maptool_osm *osm)
Variables
static int print
static char * types [] = {"node","way","relation"}
static struct string_table st
static double latlon_scale =10000000.0
Macro Definition Documentation
buffer_end
#define buffer_end (o, x) ((o)->buffer_start+(x) > (o)->buffer_end && !fill_buffer((o), (x)))
Function Documentation
fill_buffer()
static int fill_buffer (struct o5m * o, int min) static
References o5m::buffer, o5m::buffer_end, buffer_end, o5m::buffer_size, o5m::buffer_start, and o5m::in.
Referenced by map_collect_data_osm_o5m().
get_strings()
static void get_strings (struct string_table * st, unsigned char ** p, char ** s1, char ** s2) static
References p, string_table::pos, s1, st, and string_table::strings.
Referenced by map_collect_data_osm_o5m().
get_strings_ref()
static void get_strings_ref (struct string_table * st, int ref, char ** s1, char ** s2) static
References startup::pos, string_table::pos, s1, st, and string_table::strings.
Referenced by map_collect_data_osm_o5m().
get_sval()
static long long get_sval (unsigned char ** p) static
References get_uval(), and p.
Referenced by map_collect_data_osm_o5m().
get_uval()
static unsigned long long get_uval (unsigned char ** p) static
References c, and shift.
Referenced by get_sval(), and map_collect_data_osm_o5m().
map_collect_data_osm_o5m()
int map_collect_data_osm_o5m (FILE * in, struct maptool_osm * osm)
References o5m::buffer, o5m::buffer_end, buffer_end, o5m::buffer_size, o5m::buffer_start, c, o5m::changeset, o5m::error, fill_buffer(), get_strings(), get_strings_ref(), get_sval(), get_uval(), o5m::id, o5m::in, o5m::lat, latlon_scale, o5m::lon, LONGLONG_FMT, o5m_print_end(), o5m_print_start(), o5m_print_version(), o5m_reset(), osm_add_member(), osm_add_nd(), osm_add_node(), osm_add_relation(), osm_add_tag(), osm_add_way(), osm_end_node(), osm_end_relation(), osm_end_way(), print, print_escaped(), o5m::rid, st, o5m::timestamp, types, o5m::uid, o5m::user, and o5m::version.
Referenced by osm_read_input_data().
o5m_print_end()
static void o5m_print_end (char c) static
References c, and types.
Referenced by map_collect_data_osm_o5m().
o5m_print_start()
static void o5m_print_start (struct o5m * o, int c) static
References c, o5m::id, LONGLONG_FMT, and types.
Referenced by map_collect_data_osm_o5m().
o5m_print_version()
static void o5m_print_version (struct o5m * o, int tags) static
References o5m::changeset, LONGLONG_FMT, print_escaped(), o5m::timestamp, o5m::uid, o5m::user, and o5m::version.
Referenced by map_collect_data_osm_o5m().
o5m_reset()
static void o5m_reset (struct o5m * o) static
References o5m::changeset, o5m::id, o5m::lat, o5m::lon, o5m::rid, and o5m::timestamp.
Referenced by map_collect_data_osm_o5m().
print_escaped()
static void print_escaped (char * s) static
Referenced by map_collect_data_osm_o5m(), and o5m_print_version().
Variable Documentation
latlon_scale
double latlon_scale =10000000.0 static
Referenced by map_collect_data_osm_o5m().
print
int print static
Referenced by map_collect_data_osm_o5m().
st
struct string_table st static
Referenced by file_version(), get_strings(), get_strings_ref(), gmap_new(), map_collect_data_osm_o5m(), osm_protobufdb_start_block(), and osm_protobufdb_string().
types
char* types[] = {"node","way","relation"} static
Referenced by map_collect_data_osm_o5m(), o5m_print_end(), and o5m_print_start().