navit: maptool/generated-code/osmformat.pb-c.c File Reference
osmformat.pb-c.c File Reference
#include "osmformat.pb-c.h"
Macros
#define PROTOBUF_C_NO_DEPRECATED
Functions
void osmpbf__header_block__init (OSMPBF__HeaderBlock *message)
size_t osmpbf__header_block__get_packed_size (const OSMPBF__HeaderBlock *message)
size_t osmpbf__header_block__pack (const OSMPBF__HeaderBlock *message, uint8_t *out)
size_t osmpbf__header_block__pack_to_buffer (const OSMPBF__HeaderBlock *message, ProtobufCBuffer *buffer)
OSMPBF__HeaderBlock * osmpbf__header_block__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__header_block__free_unpacked (OSMPBF__HeaderBlock *message, ProtobufCAllocator *allocator)
void osmpbf__header_bbox__init (OSMPBF__HeaderBBox *message)
size_t osmpbf__header_bbox__get_packed_size (const OSMPBF__HeaderBBox *message)
size_t osmpbf__header_bbox__pack (const OSMPBF__HeaderBBox *message, uint8_t *out)
size_t osmpbf__header_bbox__pack_to_buffer (const OSMPBF__HeaderBBox *message, ProtobufCBuffer *buffer)
OSMPBF__HeaderBBox * osmpbf__header_bbox__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__header_bbox__free_unpacked (OSMPBF__HeaderBBox *message, ProtobufCAllocator *allocator)
void osmpbf__primitive_block__init (OSMPBF__PrimitiveBlock *message)
size_t osmpbf__primitive_block__get_packed_size (const OSMPBF__PrimitiveBlock *message)
size_t osmpbf__primitive_block__pack (const OSMPBF__PrimitiveBlock *message, uint8_t *out)
size_t osmpbf__primitive_block__pack_to_buffer (const OSMPBF__PrimitiveBlock *message, ProtobufCBuffer *buffer)
OSMPBF__PrimitiveBlock * osmpbf__primitive_block__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__primitive_block__free_unpacked (OSMPBF__PrimitiveBlock *message, ProtobufCAllocator *allocator)
void osmpbf__primitive_group__init (OSMPBF__PrimitiveGroup *message)
size_t osmpbf__primitive_group__get_packed_size (const OSMPBF__PrimitiveGroup *message)
size_t osmpbf__primitive_group__pack (const OSMPBF__PrimitiveGroup *message, uint8_t *out)
size_t osmpbf__primitive_group__pack_to_buffer (const OSMPBF__PrimitiveGroup *message, ProtobufCBuffer *buffer)
OSMPBF__PrimitiveGroup * osmpbf__primitive_group__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__primitive_group__free_unpacked (OSMPBF__PrimitiveGroup *message, ProtobufCAllocator *allocator)
void osmpbf__string_table__init (OSMPBF__StringTable *message)
size_t osmpbf__string_table__get_packed_size (const OSMPBF__StringTable *message)
size_t osmpbf__string_table__pack (const OSMPBF__StringTable *message, uint8_t *out)
size_t osmpbf__string_table__pack_to_buffer (const OSMPBF__StringTable *message, ProtobufCBuffer *buffer)
OSMPBF__StringTable * osmpbf__string_table__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__string_table__free_unpacked (OSMPBF__StringTable *message, ProtobufCAllocator *allocator)
void osmpbf__info__init (OSMPBF__Info *message)
size_t osmpbf__info__get_packed_size (const OSMPBF__Info *message)
size_t osmpbf__info__pack (const OSMPBF__Info *message, uint8_t *out)
size_t osmpbf__info__pack_to_buffer (const OSMPBF__Info *message, ProtobufCBuffer *buffer)
OSMPBF__Info * osmpbf__info__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__info__free_unpacked (OSMPBF__Info *message, ProtobufCAllocator *allocator)
void osmpbf__dense_info__init (OSMPBF__DenseInfo *message)
size_t osmpbf__dense_info__get_packed_size (const OSMPBF__DenseInfo *message)
size_t osmpbf__dense_info__pack (const OSMPBF__DenseInfo *message, uint8_t *out)
size_t osmpbf__dense_info__pack_to_buffer (const OSMPBF__DenseInfo *message, ProtobufCBuffer *buffer)
OSMPBF__DenseInfo * osmpbf__dense_info__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__dense_info__free_unpacked (OSMPBF__DenseInfo *message, ProtobufCAllocator *allocator)
void osmpbf__change_set__init (OSMPBF__ChangeSet *message)
size_t osmpbf__change_set__get_packed_size (const OSMPBF__ChangeSet *message)
size_t osmpbf__change_set__pack (const OSMPBF__ChangeSet *message, uint8_t *out)
size_t osmpbf__change_set__pack_to_buffer (const OSMPBF__ChangeSet *message, ProtobufCBuffer *buffer)
OSMPBF__ChangeSet * osmpbf__change_set__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__change_set__free_unpacked (OSMPBF__ChangeSet *message, ProtobufCAllocator *allocator)
void osmpbf__node__init (OSMPBF__Node *message)
size_t osmpbf__node__get_packed_size (const OSMPBF__Node *message)
size_t osmpbf__node__pack (const OSMPBF__Node *message, uint8_t *out)
size_t osmpbf__node__pack_to_buffer (const OSMPBF__Node *message, ProtobufCBuffer *buffer)
OSMPBF__Node * osmpbf__node__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__node__free_unpacked (OSMPBF__Node *message, ProtobufCAllocator *allocator)
void osmpbf__dense_nodes__init (OSMPBF__DenseNodes *message)
size_t osmpbf__dense_nodes__get_packed_size (const OSMPBF__DenseNodes *message)
size_t osmpbf__dense_nodes__pack (const OSMPBF__DenseNodes *message, uint8_t *out)
size_t osmpbf__dense_nodes__pack_to_buffer (const OSMPBF__DenseNodes *message, ProtobufCBuffer *buffer)
OSMPBF__DenseNodes * osmpbf__dense_nodes__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__dense_nodes__free_unpacked (OSMPBF__DenseNodes *message, ProtobufCAllocator *allocator)
void osmpbf__way__init (OSMPBF__Way *message)
size_t osmpbf__way__get_packed_size (const OSMPBF__Way *message)
size_t osmpbf__way__pack (const OSMPBF__Way *message, uint8_t *out)
size_t osmpbf__way__pack_to_buffer (const OSMPBF__Way *message, ProtobufCBuffer *buffer)
OSMPBF__Way * osmpbf__way__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__way__free_unpacked (OSMPBF__Way *message, ProtobufCAllocator *allocator)
void osmpbf__relation__init (OSMPBF__Relation *message)
size_t osmpbf__relation__get_packed_size (const OSMPBF__Relation *message)
size_t osmpbf__relation__pack (const OSMPBF__Relation *message, uint8_t *out)
size_t osmpbf__relation__pack_to_buffer (const OSMPBF__Relation *message, ProtobufCBuffer *buffer)
OSMPBF__Relation * osmpbf__relation__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__relation__free_unpacked (OSMPBF__Relation *message, ProtobufCAllocator *allocator)
Variables
static const
ProtobufCFieldDescriptor osmpbf__header_block__field_descriptors [5]
static const unsigned osmpbf__header_block__field_indices_by_name []
static const ProtobufCIntRange osmpbf__header_block__number_ranges [3+1]
const ProtobufCMessageDescriptor osmpbf__header_block__descriptor
static const
ProtobufCFieldDescriptor osmpbf__header_bbox__field_descriptors [4]
static const unsigned osmpbf__header_bbox__field_indices_by_name []
static const ProtobufCIntRange osmpbf__header_bbox__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__header_bbox__descriptor
static const int32_t osmpbf__primitive_block__granularity__default_value = 100
static const int64_t osmpbf__primitive_block__lat_offset__default_value = 0
static const int64_t osmpbf__primitive_block__lon_offset__default_value = 0
static const int32_t osmpbf__primitive_block__date_granularity__default_value = 1000
static const
ProtobufCFieldDescriptor osmpbf__primitive_block__field_descriptors [6]
static const unsigned osmpbf__primitive_block__field_indices_by_name []
static const ProtobufCIntRange osmpbf__primitive_block__number_ranges [2+1]
const ProtobufCMessageDescriptor osmpbf__primitive_block__descriptor
static const
ProtobufCFieldDescriptor osmpbf__primitive_group__field_descriptors [5]
static const unsigned osmpbf__primitive_group__field_indices_by_name []
static const ProtobufCIntRange osmpbf__primitive_group__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__primitive_group__descriptor
static const
ProtobufCFieldDescriptor osmpbf__string_table__field_descriptors [1]
static const unsigned osmpbf__string_table__field_indices_by_name []
static const ProtobufCIntRange osmpbf__string_table__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__string_table__descriptor
static const int32_t osmpbf__info__version__default_value = -1
static const
ProtobufCFieldDescriptor osmpbf__info__field_descriptors [5]
static const unsigned osmpbf__info__field_indices_by_name []
static const ProtobufCIntRange osmpbf__info__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__info__descriptor
static const
ProtobufCFieldDescriptor osmpbf__dense_info__field_descriptors [5]
static const unsigned osmpbf__dense_info__field_indices_by_name []
static const ProtobufCIntRange osmpbf__dense_info__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__dense_info__descriptor
static const
ProtobufCFieldDescriptor osmpbf__change_set__field_descriptors [1]
static const unsigned osmpbf__change_set__field_indices_by_name []
static const ProtobufCIntRange osmpbf__change_set__number_ranges [1+1]
const ProtobufCMessageDescriptor osmpbf__change_set__descriptor
static const
ProtobufCFieldDescriptor osmpbf__node__field_descriptors [6]
static const unsigned osmpbf__node__field_indices_by_name []
static const ProtobufCIntRange osmpbf__node__number_ranges [2+1]
const ProtobufCMessageDescriptor osmpbf__node__descriptor
static const
ProtobufCFieldDescriptor osmpbf__dense_nodes__field_descriptors [5]
static const unsigned osmpbf__dense_nodes__field_indices_by_name []
static const ProtobufCIntRange osmpbf__dense_nodes__number_ranges [3+1]
const ProtobufCMessageDescriptor osmpbf__dense_nodes__descriptor
static const
ProtobufCFieldDescriptor osmpbf__way__field_descriptors [5]
static const unsigned osmpbf__way__field_indices_by_name []
static const ProtobufCIntRange osmpbf__way__number_ranges [2+1]
const ProtobufCMessageDescriptor osmpbf__way__descriptor
const ProtobufCEnumValue osmpbf__relation__member_type__enum_values_by_number [3]
static const ProtobufCIntRange osmpbf__relation__member_type__value_ranges []
const ProtobufCEnumValueIndex osmpbf__relation__member_type__enum_values_by_name [3]
const ProtobufCEnumDescriptor osmpbf__relation__member_type__descriptor
static const
ProtobufCFieldDescriptor osmpbf__relation__field_descriptors [7]
static const unsigned osmpbf__relation__field_indices_by_name []
static const ProtobufCIntRange osmpbf__relation__number_ranges [2+1]
const ProtobufCMessageDescriptor osmpbf__relation__descriptor
Macro Definition Documentation
#define PROTOBUF_C_NO_DEPRECATED
Function Documentation
void osmpbf__change_set__free_unpacked (OSMPBF__ChangeSet * message, ProtobufCAllocator * allocator)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__change_set__get_packed_size (const OSMPBF__ChangeSet * message)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__change_set__init (OSMPBF__ChangeSet * message)
References OSMPBF__CHANGE_SET__INIT.
size_t osmpbf__change_set__pack (const OSMPBF__ChangeSet * message, uint8_t * out)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__change_set__pack_to_buffer (const OSMPBF__ChangeSet * message, ProtobufCBuffer * buffer)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__ChangeSet* osmpbf__change_set__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__change_set__descriptor, and protobuf_c_message_unpack().
void osmpbf__dense_info__free_unpacked (OSMPBF__DenseInfo * message, ProtobufCAllocator * allocator)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__dense_info__get_packed_size (const OSMPBF__DenseInfo * message)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__dense_info__init (OSMPBF__DenseInfo * message)
References OSMPBF__DENSE_INFO__INIT.
size_t osmpbf__dense_info__pack (const OSMPBF__DenseInfo * message, uint8_t * out)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__dense_info__pack_to_buffer (const OSMPBF__DenseInfo * message, ProtobufCBuffer * buffer)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__DenseInfo* osmpbf__dense_info__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__dense_info__descriptor, and protobuf_c_message_unpack().
void osmpbf__dense_nodes__free_unpacked (OSMPBF__DenseNodes * message, ProtobufCAllocator * allocator)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__dense_nodes__get_packed_size (const OSMPBF__DenseNodes * message)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__dense_nodes__init (OSMPBF__DenseNodes * message)
References OSMPBF__DENSE_NODES__INIT.
size_t osmpbf__dense_nodes__pack (const OSMPBF__DenseNodes * message, uint8_t * out)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__dense_nodes__pack_to_buffer (const OSMPBF__DenseNodes * message, ProtobufCBuffer * buffer)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__DenseNodes* osmpbf__dense_nodes__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__dense_nodes__descriptor, and protobuf_c_message_unpack().
void osmpbf__header_bbox__free_unpacked (OSMPBF__HeaderBBox * message, ProtobufCAllocator * allocator)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__header_bbox__get_packed_size (const OSMPBF__HeaderBBox * message)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__header_bbox__init (OSMPBF__HeaderBBox * message)
References OSMPBF__HEADER_BBOX__INIT.
size_t osmpbf__header_bbox__pack (const OSMPBF__HeaderBBox * message, uint8_t * out)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__header_bbox__pack_to_buffer (const OSMPBF__HeaderBBox * message, ProtobufCBuffer * buffer)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__HeaderBBox* osmpbf__header_bbox__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__header_bbox__descriptor, and protobuf_c_message_unpack().
void osmpbf__header_block__free_unpacked (OSMPBF__HeaderBlock * message, ProtobufCAllocator * allocator)
References osmpbf__header_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by process_osmheader().
size_t osmpbf__header_block__get_packed_size (const OSMPBF__HeaderBlock * message)
References osmpbf__header_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__header_block__init (OSMPBF__HeaderBlock * message)
References OSMPBF__HEADER_BLOCK__INIT.
size_t osmpbf__header_block__pack (const OSMPBF__HeaderBlock * message, uint8_t * out)
References osmpbf__header_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__header_block__pack_to_buffer (const OSMPBF__HeaderBlock * message, ProtobufCBuffer * buffer)
References osmpbf__header_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__HeaderBlock* osmpbf__header_block__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__header_block__descriptor, and protobuf_c_message_unpack().
Referenced by process_osmheader().
void osmpbf__info__free_unpacked (OSMPBF__Info * message, ProtobufCAllocator * allocator)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osm_protobufdb_modify_node(), osm_protobufdb_modify_relation(), and osm_protobufdb_modify_way().
size_t osmpbf__info__get_packed_size (const OSMPBF__Info * message)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__info__init (OSMPBF__Info * message)
References OSMPBF__INFO__INIT.
size_t osmpbf__info__pack (const OSMPBF__Info * message, uint8_t * out)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__info__pack_to_buffer (const OSMPBF__Info * message, ProtobufCBuffer * buffer)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__Info* osmpbf__info__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__info__descriptor, and protobuf_c_message_unpack().
void osmpbf__node__free_unpacked (OSMPBF__Node * message, ProtobufCAllocator * allocator)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__node__get_packed_size (const OSMPBF__Node * message)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__node__init (OSMPBF__Node * message)
References OSMPBF__NODE__INIT.
size_t osmpbf__node__pack (const OSMPBF__Node * message, uint8_t * out)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__node__pack_to_buffer (const OSMPBF__Node * message, ProtobufCBuffer * buffer)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__Node* osmpbf__node__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__node__descriptor, and protobuf_c_message_unpack().
void osmpbf__primitive_block__free_unpacked (OSMPBF__PrimitiveBlock * message, ProtobufCAllocator * allocator)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osm_protobufdb_finish_block(), and process_osmdata().
size_t osmpbf__primitive_block__get_packed_size (const OSMPBF__PrimitiveBlock * message)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_finish_block().
void osmpbf__primitive_block__init (OSMPBF__PrimitiveBlock * message)
References OSMPBF__PRIMITIVE_BLOCK__INIT.
size_t osmpbf__primitive_block__pack (const OSMPBF__PrimitiveBlock * message, uint8_t * out)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_finish_block().
size_t osmpbf__primitive_block__pack_to_buffer (const OSMPBF__PrimitiveBlock * message, ProtobufCBuffer * buffer)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__PrimitiveBlock* osmpbf__primitive_block__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__primitive_block__descriptor, and protobuf_c_message_unpack().
Referenced by process_osmdata().
void osmpbf__primitive_group__free_unpacked (OSMPBF__PrimitiveGroup * message, ProtobufCAllocator * allocator)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__primitive_group__get_packed_size (const OSMPBF__PrimitiveGroup * message)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__primitive_group__init (OSMPBF__PrimitiveGroup * message)
References OSMPBF__PRIMITIVE_GROUP__INIT.
size_t osmpbf__primitive_group__pack (const OSMPBF__PrimitiveGroup * message, uint8_t * out)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__primitive_group__pack_to_buffer (const OSMPBF__PrimitiveGroup * message, ProtobufCBuffer * buffer)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__PrimitiveGroup* osmpbf__primitive_group__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__primitive_group__descriptor, and protobuf_c_message_unpack().
void osmpbf__relation__free_unpacked (OSMPBF__Relation * message, ProtobufCAllocator * allocator)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__relation__get_packed_size (const OSMPBF__Relation * message)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__relation__init (OSMPBF__Relation * message)
References OSMPBF__RELATION__INIT.
size_t osmpbf__relation__pack (const OSMPBF__Relation * message, uint8_t * out)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__relation__pack_to_buffer (const OSMPBF__Relation * message, ProtobufCBuffer * buffer)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__Relation* osmpbf__relation__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__relation__descriptor, and protobuf_c_message_unpack().
void osmpbf__string_table__free_unpacked (OSMPBF__StringTable * message, ProtobufCAllocator * allocator)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__string_table__get_packed_size (const OSMPBF__StringTable * message)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__string_table__init (OSMPBF__StringTable * message)
References OSMPBF__STRING_TABLE__INIT.
size_t osmpbf__string_table__pack (const OSMPBF__StringTable * message, uint8_t * out)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__string_table__pack_to_buffer (const OSMPBF__StringTable * message, ProtobufCBuffer * buffer)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__StringTable* osmpbf__string_table__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__string_table__descriptor, and protobuf_c_message_unpack().
void osmpbf__way__free_unpacked (OSMPBF__Way * message, ProtobufCAllocator * allocator)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
size_t osmpbf__way__get_packed_size (const OSMPBF__Way * message)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
void osmpbf__way__init (OSMPBF__Way * message)
References OSMPBF__WAY__INIT.
size_t osmpbf__way__pack (const OSMPBF__Way * message, uint8_t * out)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
size_t osmpbf__way__pack_to_buffer (const OSMPBF__Way * message, ProtobufCBuffer * buffer)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
OSMPBF__Way* osmpbf__way__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__way__descriptor, and protobuf_c_message_unpack().
Variable Documentation
const ProtobufCMessageDescriptor osmpbf__change_set__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.ChangeSet",
  "ChangeSet",
  "OSMPBF__ChangeSet",
  "OSMPBF",
  sizeof(OSMPBF__ChangeSet),
  1,
  osmpbf__change_set__field_descriptors,
  osmpbf__change_set__field_indices_by_name,
  1,  osmpbf__change_set__number_ranges,
  (ProtobufCMessageInit) osmpbf__change_set__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__change_set__free_unpacked(), osmpbf__change_set__get_packed_size(), osmpbf__change_set__pack(), osmpbf__change_set__pack_to_buffer(), and osmpbf__change_set__unpack().
const ProtobufCFieldDescriptor osmpbf__change_set__field_descriptors[1] static
Initial value:
=
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,
    PROTOBUF_C_OFFSETOF(OSMPBF__ChangeSet, id),
    NULL,
    NULL,
    0,
    0,NULL,NULL
  },
}
const unsigned osmpbf__change_set__field_indices_by_name[] static
Initial value:
= {
  0,
}
const ProtobufCIntRange osmpbf__change_set__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 1 }
}
const ProtobufCMessageDescriptor osmpbf__dense_info__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.DenseInfo",
  "DenseInfo",
  "OSMPBF__DenseInfo",
  "OSMPBF",
  sizeof(OSMPBF__DenseInfo),
  5,
  osmpbf__dense_info__field_descriptors,
  osmpbf__dense_info__field_indices_by_name,
  1,  osmpbf__dense_info__number_ranges,
  (ProtobufCMessageInit) osmpbf__dense_info__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__dense_info__free_unpacked(), osmpbf__dense_info__get_packed_size(), osmpbf__dense_info__pack(), osmpbf__dense_info__pack_to_buffer(), and osmpbf__dense_info__unpack().
const ProtobufCFieldDescriptor osmpbf__dense_info__field_descriptors[5] static
const unsigned osmpbf__dense_info__field_indices_by_name[] static
Initial value:
= {
  2,
  1,
  3,
  4,
  0,
}
const ProtobufCIntRange osmpbf__dense_info__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 5 }
}
const ProtobufCMessageDescriptor osmpbf__dense_nodes__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.DenseNodes",
  "DenseNodes",
  "OSMPBF__DenseNodes",
  "OSMPBF",
  sizeof(OSMPBF__DenseNodes),
  5,
  osmpbf__dense_nodes__field_descriptors,
  osmpbf__dense_nodes__field_indices_by_name,
  3,  osmpbf__dense_nodes__number_ranges,
  (ProtobufCMessageInit) osmpbf__dense_nodes__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__dense_nodes__free_unpacked(), osmpbf__dense_nodes__get_packed_size(), osmpbf__dense_nodes__pack(), osmpbf__dense_nodes__pack_to_buffer(), and osmpbf__dense_nodes__unpack().
const ProtobufCFieldDescriptor osmpbf__dense_nodes__field_descriptors[5] static
const unsigned osmpbf__dense_nodes__field_indices_by_name[] static
Initial value:
= {
  1,
  0,
  4,
  2,
  3,
}
const ProtobufCIntRange osmpbf__dense_nodes__number_ranges[3+1] static
Initial value:
=
{
  { 1, 0 },
  { 5, 1 },
  { 8, 2 },
  { 0, 5 }
}
const ProtobufCMessageDescriptor osmpbf__header_bbox__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.HeaderBBox",
  "HeaderBBox",
  "OSMPBF__HeaderBBox",
  "OSMPBF",
  sizeof(OSMPBF__HeaderBBox),
  4,
  osmpbf__header_bbox__field_descriptors,
  osmpbf__header_bbox__field_indices_by_name,
  1,  osmpbf__header_bbox__number_ranges,
  (ProtobufCMessageInit) osmpbf__header_bbox__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__header_bbox__free_unpacked(), osmpbf__header_bbox__get_packed_size(), osmpbf__header_bbox__pack(), osmpbf__header_bbox__pack_to_buffer(), and osmpbf__header_bbox__unpack().
const ProtobufCFieldDescriptor osmpbf__header_bbox__field_descriptors[4] static
const unsigned osmpbf__header_bbox__field_indices_by_name[] static
Initial value:
= {
  3,
  0,
  1,
  2,
}
const ProtobufCIntRange osmpbf__header_bbox__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 4 }
}
const ProtobufCMessageDescriptor osmpbf__header_block__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.HeaderBlock",
  "HeaderBlock",
  "OSMPBF__HeaderBlock",
  "OSMPBF",
  sizeof(OSMPBF__HeaderBlock),
  5,
  osmpbf__header_block__field_descriptors,
  osmpbf__header_block__field_indices_by_name,
  3,  osmpbf__header_block__number_ranges,
  (ProtobufCMessageInit) osmpbf__header_block__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__header_block__free_unpacked(), osmpbf__header_block__get_packed_size(), osmpbf__header_block__pack(), osmpbf__header_block__pack_to_buffer(), and osmpbf__header_block__unpack().
const ProtobufCFieldDescriptor osmpbf__header_block__field_descriptors[5] static
const unsigned osmpbf__header_block__field_indices_by_name[] static
Initial value:
= {
  0,
  2,
  1,
  4,
  3,
}
const ProtobufCIntRange osmpbf__header_block__number_ranges[3+1] static
Initial value:
=
{
  { 1, 0 },
  { 4, 1 },
  { 16, 3 },
  { 0, 5 }
}
const ProtobufCMessageDescriptor osmpbf__info__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.Info",
  "Info",
  "OSMPBF__Info",
  "OSMPBF",
  sizeof(OSMPBF__Info),
  5,
  osmpbf__info__field_descriptors,
  osmpbf__info__field_indices_by_name,
  1,  osmpbf__info__number_ranges,
  (ProtobufCMessageInit) osmpbf__info__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__info__free_unpacked(), osmpbf__info__get_packed_size(), osmpbf__info__pack(), osmpbf__info__pack_to_buffer(), and osmpbf__info__unpack().
const ProtobufCFieldDescriptor osmpbf__info__field_descriptors[5] static
const unsigned osmpbf__info__field_indices_by_name[] static
Initial value:
= {
  2,
  1,
  3,
  4,
  0,
}
const ProtobufCIntRange osmpbf__info__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 5 }
}
const int32_t osmpbf__info__version__default_value = -1 static
const ProtobufCMessageDescriptor osmpbf__node__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.Node",
  "Node",
  "OSMPBF__Node",
  "OSMPBF",
  sizeof(OSMPBF__Node),
  6,
  osmpbf__node__field_descriptors,
  osmpbf__node__field_indices_by_name,
  2,  osmpbf__node__number_ranges,
  (ProtobufCMessageInit) osmpbf__node__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__node__free_unpacked(), osmpbf__node__get_packed_size(), osmpbf__node__pack(), osmpbf__node__pack_to_buffer(), and osmpbf__node__unpack().
const ProtobufCFieldDescriptor osmpbf__node__field_descriptors[6] static
const unsigned osmpbf__node__field_indices_by_name[] static
Initial value:
= {
  0,
  3,
  1,
  4,
  5,
  2,
}
const ProtobufCIntRange osmpbf__node__number_ranges[2+1] static
Initial value:
=
{
  { 1, 0 },
  { 8, 4 },
  { 0, 6 }
}
const int32_t osmpbf__primitive_block__date_granularity__default_value = 1000 static
const ProtobufCMessageDescriptor osmpbf__primitive_block__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.PrimitiveBlock",
  "PrimitiveBlock",
  "OSMPBF__PrimitiveBlock",
  "OSMPBF",
  sizeof(OSMPBF__PrimitiveBlock),
  6,
  osmpbf__primitive_block__field_descriptors,
  osmpbf__primitive_block__field_indices_by_name,
  2,  osmpbf__primitive_block__number_ranges,
  (ProtobufCMessageInit) osmpbf__primitive_block__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_block__pack(), osmpbf__primitive_block__pack_to_buffer(), and osmpbf__primitive_block__unpack().
const ProtobufCFieldDescriptor osmpbf__primitive_block__field_descriptors[6] static
const unsigned osmpbf__primitive_block__field_indices_by_name[] static
Initial value:
= {
  3,
  2,
  4,
  5,
  1,
  0,
}
const int32_t osmpbf__primitive_block__granularity__default_value = 100 static
const int64_t osmpbf__primitive_block__lat_offset__default_value = 0 static
const int64_t osmpbf__primitive_block__lon_offset__default_value = 0 static
const ProtobufCIntRange osmpbf__primitive_block__number_ranges[2+1] static
Initial value:
=
{
  { 1, 0 },
  { 17, 2 },
  { 0, 6 }
}
const ProtobufCMessageDescriptor osmpbf__primitive_group__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.PrimitiveGroup",
  "PrimitiveGroup",
  "OSMPBF__PrimitiveGroup",
  "OSMPBF",
  sizeof(OSMPBF__PrimitiveGroup),
  5,
  osmpbf__primitive_group__field_descriptors,
  osmpbf__primitive_group__field_indices_by_name,
  1,  osmpbf__primitive_group__number_ranges,
  (ProtobufCMessageInit) osmpbf__primitive_group__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__primitive_group__free_unpacked(), osmpbf__primitive_group__get_packed_size(), osmpbf__primitive_group__pack(), osmpbf__primitive_group__pack_to_buffer(), and osmpbf__primitive_group__unpack().
const ProtobufCFieldDescriptor osmpbf__primitive_group__field_descriptors[5] static
const unsigned osmpbf__primitive_group__field_indices_by_name[] static
Initial value:
= {
  4,
  1,
  0,
  3,
  2,
}
const ProtobufCIntRange osmpbf__primitive_group__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 5 }
}
const ProtobufCMessageDescriptor osmpbf__relation__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.Relation",
  "Relation",
  "OSMPBF__Relation",
  "OSMPBF",
  sizeof(OSMPBF__Relation),
  7,
  osmpbf__relation__field_descriptors,
  osmpbf__relation__field_indices_by_name,
  2,  osmpbf__relation__number_ranges,
  (ProtobufCMessageInit) osmpbf__relation__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__relation__free_unpacked(), osmpbf__relation__get_packed_size(), osmpbf__relation__pack(), osmpbf__relation__pack_to_buffer(), and osmpbf__relation__unpack().
const ProtobufCFieldDescriptor osmpbf__relation__field_descriptors[7] static
const unsigned osmpbf__relation__field_indices_by_name[] static
Initial value:
= {
  0,
  3,
  1,
  5,
  4,
  6,
  2,
}
const ProtobufCEnumDescriptor osmpbf__relation__member_type__descriptor
Initial value:
=
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "OSMPBF.Relation.MemberType",
  "MemberType",
  "OSMPBF__Relation__MemberType",
  "OSMPBF",
  3,
  osmpbf__relation__member_type__enum_values_by_number,
  3,
  osmpbf__relation__member_type__enum_values_by_name,
  1,
  osmpbf__relation__member_type__value_ranges,
  NULL,NULL,NULL,NULL
}
const ProtobufCEnumValueIndex osmpbf__relation__member_type__enum_values_by_name[3]
Initial value:
=
{
  { "NODE", 0 },
  { "RELATION", 2 },
  { "WAY", 1 },
}
const ProtobufCEnumValue osmpbf__relation__member_type__enum_values_by_number[3]
Initial value:
=
{
  { "NODE", "OSMPBF__RELATION__MEMBER_TYPE__NODE", 0 },
  { "WAY", "OSMPBF__RELATION__MEMBER_TYPE__WAY", 1 },
  { "RELATION", "OSMPBF__RELATION__MEMBER_TYPE__RELATION", 2 },
}
const ProtobufCIntRange osmpbf__relation__member_type__value_ranges[] static
Initial value:
= {
{0, 0},{0, 3}
}
const ProtobufCIntRange osmpbf__relation__number_ranges[2+1] static
Initial value:
=
{
  { 1, 0 },
  { 8, 4 },
  { 0, 7 }
}
const ProtobufCMessageDescriptor osmpbf__string_table__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.StringTable",
  "StringTable",
  "OSMPBF__StringTable",
  "OSMPBF",
  sizeof(OSMPBF__StringTable),
  1,
  osmpbf__string_table__field_descriptors,
  osmpbf__string_table__field_indices_by_name,
  1,  osmpbf__string_table__number_ranges,
  (ProtobufCMessageInit) osmpbf__string_table__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__string_table__free_unpacked(), osmpbf__string_table__get_packed_size(), osmpbf__string_table__pack(), osmpbf__string_table__pack_to_buffer(), and osmpbf__string_table__unpack().
const ProtobufCFieldDescriptor osmpbf__string_table__field_descriptors[1] static
Initial value:
=
{
  {
    "s",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(OSMPBF__StringTable, n_s),
    PROTOBUF_C_OFFSETOF(OSMPBF__StringTable, s),
    NULL,
    NULL,
    0,
    0,NULL,NULL
  },
}
const unsigned osmpbf__string_table__field_indices_by_name[] static
Initial value:
= {
  0,
}
const ProtobufCIntRange osmpbf__string_table__number_ranges[1+1] static
Initial value:
=
{
  { 1, 0 },
  { 0, 1 }
}
const ProtobufCMessageDescriptor osmpbf__way__descriptor
Initial value:
=
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "OSMPBF.Way",
  "Way",
  "OSMPBF__Way",
  "OSMPBF",
  sizeof(OSMPBF__Way),
  5,
  osmpbf__way__field_descriptors,
  osmpbf__way__field_indices_by_name,
  2,  osmpbf__way__number_ranges,
  (ProtobufCMessageInit) osmpbf__way__init,
  NULL,NULL,NULL
}
Referenced by osmpbf__way__free_unpacked(), osmpbf__way__get_packed_size(), osmpbf__way__pack(), osmpbf__way__pack_to_buffer(), and osmpbf__way__unpack().
const ProtobufCFieldDescriptor osmpbf__way__field_descriptors[5] static
const unsigned osmpbf__way__field_indices_by_name[] static
Initial value:
= {
  0,
  3,
  1,
  4,
  2,
}
const ProtobufCIntRange osmpbf__way__number_ranges[2+1] static
Initial value:
=
{
  { 1, 0 },
  { 8, 4 },
  { 0, 5 }
}