navit: maptool/generated-code/osmformat.pb-c.h File Reference
osmformat.pb-c.h File Reference
#include <google/protobuf-c/protobuf-c.h>
Data Structures
struct _OSMPBF__HeaderBlock
struct _OSMPBF__HeaderBBox
struct _OSMPBF__PrimitiveBlock
struct _OSMPBF__PrimitiveGroup
struct _OSMPBF__StringTable
struct _OSMPBF__Info
struct _OSMPBF__DenseInfo
struct _OSMPBF__ChangeSet
struct _OSMPBF__Node
struct _OSMPBF__DenseNodes
struct _OSMPBF__Way
struct _OSMPBF__Relation
Macros
#define OSMPBF__HEADER_BLOCK__INIT
#define OSMPBF__HEADER_BBOX__INIT
#define OSMPBF__PRIMITIVE_BLOCK__INIT
#define OSMPBF__PRIMITIVE_GROUP__INIT
#define OSMPBF__STRING_TABLE__INIT
#define OSMPBF__INFO__INIT
#define OSMPBF__DENSE_INFO__INIT
#define OSMPBF__CHANGE_SET__INIT
#define OSMPBF__NODE__INIT
#define OSMPBF__DENSE_NODES__INIT
#define OSMPBF__WAY__INIT
#define OSMPBF__RELATION__INIT
Typedefs
typedef typedefPROTOBUF_C_BEGIN_DECLS struct _OSMPBF__HeaderBlock OSMPBF__HeaderBlock
typedef struct _OSMPBF__HeaderBBox OSMPBF__HeaderBBox
typedef struct _OSMPBF__PrimitiveBlock OSMPBF__PrimitiveBlock
typedef struct _OSMPBF__PrimitiveGroup OSMPBF__PrimitiveGroup
typedef struct _OSMPBF__StringTable OSMPBF__StringTable
typedef struct _OSMPBF__Info OSMPBF__Info
typedef struct _OSMPBF__DenseInfo OSMPBF__DenseInfo
typedef struct _OSMPBF__ChangeSet OSMPBF__ChangeSet
typedef struct _OSMPBF__Node OSMPBF__Node
typedef struct _OSMPBF__DenseNodes OSMPBF__DenseNodes
typedef struct _OSMPBF__Way OSMPBF__Way
typedef struct _OSMPBF__Relation OSMPBF__Relation
typedef enum _OSMPBF__Relation__MemberType OSMPBF__Relation__MemberType
typedef void(* OSMPBF__HeaderBlock_Closure) (const OSMPBF__HeaderBlock *message, void *closure_data)
typedef void(* OSMPBF__HeaderBBox_Closure) (const OSMPBF__HeaderBBox *message, void *closure_data)
typedef void(* OSMPBF__PrimitiveBlock_Closure) (const OSMPBF__PrimitiveBlock *message, void *closure_data)
typedef void(* OSMPBF__PrimitiveGroup_Closure) (const OSMPBF__PrimitiveGroup *message, void *closure_data)
typedef void(* OSMPBF__StringTable_Closure) (const OSMPBF__StringTable *message, void *closure_data)
typedef void(* OSMPBF__Info_Closure) (const OSMPBF__Info *message, void *closure_data)
typedef void(* OSMPBF__DenseInfo_Closure) (const OSMPBF__DenseInfo *message, void *closure_data)
typedef void(* OSMPBF__ChangeSet_Closure) (const OSMPBF__ChangeSet *message, void *closure_data)
typedef void(* OSMPBF__Node_Closure) (const OSMPBF__Node *message, void *closure_data)
typedef void(* OSMPBF__DenseNodes_Closure) (const OSMPBF__DenseNodes *message, void *closure_data)
typedef void(* OSMPBF__Way_Closure) (const OSMPBF__Way *message, void *closure_data)
typedef void(* OSMPBF__Relation_Closure) (const OSMPBF__Relation *message, void *closure_data)
Enumerations
enum _OSMPBF__Relation__MemberType { OSMPBF__RELATION__MEMBER_TYPE__NODE = 0, OSMPBF__RELATION__MEMBER_TYPE__WAY = 1, OSMPBF__RELATION__MEMBER_TYPE__RELATION = 2 }
Functions
void osmpbf__header_block__init (OSMPBF__HeaderBlock *message)
size_t osmpbf__header_block__get_packed_size (const OSMPBF__HeaderBlock *message)
size_t osmpbf__header_block__pack (const OSMPBF__HeaderBlock *message, uint8_t *out)
size_t osmpbf__header_block__pack_to_buffer (const OSMPBF__HeaderBlock *message, ProtobufCBuffer *buffer)
OSMPBF__HeaderBlock * osmpbf__header_block__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__header_block__free_unpacked (OSMPBF__HeaderBlock *message, ProtobufCAllocator *allocator)
void osmpbf__header_bbox__init (OSMPBF__HeaderBBox *message)
size_t osmpbf__header_bbox__get_packed_size (const OSMPBF__HeaderBBox *message)
size_t osmpbf__header_bbox__pack (const OSMPBF__HeaderBBox *message, uint8_t *out)
size_t osmpbf__header_bbox__pack_to_buffer (const OSMPBF__HeaderBBox *message, ProtobufCBuffer *buffer)
OSMPBF__HeaderBBox * osmpbf__header_bbox__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__header_bbox__free_unpacked (OSMPBF__HeaderBBox *message, ProtobufCAllocator *allocator)
void osmpbf__primitive_block__init (OSMPBF__PrimitiveBlock *message)
size_t osmpbf__primitive_block__get_packed_size (const OSMPBF__PrimitiveBlock *message)
size_t osmpbf__primitive_block__pack (const OSMPBF__PrimitiveBlock *message, uint8_t *out)
size_t osmpbf__primitive_block__pack_to_buffer (const OSMPBF__PrimitiveBlock *message, ProtobufCBuffer *buffer)
OSMPBF__PrimitiveBlock * osmpbf__primitive_block__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__primitive_block__free_unpacked (OSMPBF__PrimitiveBlock *message, ProtobufCAllocator *allocator)
void osmpbf__primitive_group__init (OSMPBF__PrimitiveGroup *message)
size_t osmpbf__primitive_group__get_packed_size (const OSMPBF__PrimitiveGroup *message)
size_t osmpbf__primitive_group__pack (const OSMPBF__PrimitiveGroup *message, uint8_t *out)
size_t osmpbf__primitive_group__pack_to_buffer (const OSMPBF__PrimitiveGroup *message, ProtobufCBuffer *buffer)
OSMPBF__PrimitiveGroup * osmpbf__primitive_group__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__primitive_group__free_unpacked (OSMPBF__PrimitiveGroup *message, ProtobufCAllocator *allocator)
void osmpbf__string_table__init (OSMPBF__StringTable *message)
size_t osmpbf__string_table__get_packed_size (const OSMPBF__StringTable *message)
size_t osmpbf__string_table__pack (const OSMPBF__StringTable *message, uint8_t *out)
size_t osmpbf__string_table__pack_to_buffer (const OSMPBF__StringTable *message, ProtobufCBuffer *buffer)
OSMPBF__StringTable * osmpbf__string_table__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__string_table__free_unpacked (OSMPBF__StringTable *message, ProtobufCAllocator *allocator)
void osmpbf__info__init (OSMPBF__Info *message)
size_t osmpbf__info__get_packed_size (const OSMPBF__Info *message)
size_t osmpbf__info__pack (const OSMPBF__Info *message, uint8_t *out)
size_t osmpbf__info__pack_to_buffer (const OSMPBF__Info *message, ProtobufCBuffer *buffer)
OSMPBF__Info * osmpbf__info__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__info__free_unpacked (OSMPBF__Info *message, ProtobufCAllocator *allocator)
void osmpbf__dense_info__init (OSMPBF__DenseInfo *message)
size_t osmpbf__dense_info__get_packed_size (const OSMPBF__DenseInfo *message)
size_t osmpbf__dense_info__pack (const OSMPBF__DenseInfo *message, uint8_t *out)
size_t osmpbf__dense_info__pack_to_buffer (const OSMPBF__DenseInfo *message, ProtobufCBuffer *buffer)
OSMPBF__DenseInfo * osmpbf__dense_info__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__dense_info__free_unpacked (OSMPBF__DenseInfo *message, ProtobufCAllocator *allocator)
void osmpbf__change_set__init (OSMPBF__ChangeSet *message)
size_t osmpbf__change_set__get_packed_size (const OSMPBF__ChangeSet *message)
size_t osmpbf__change_set__pack (const OSMPBF__ChangeSet *message, uint8_t *out)
size_t osmpbf__change_set__pack_to_buffer (const OSMPBF__ChangeSet *message, ProtobufCBuffer *buffer)
OSMPBF__ChangeSet * osmpbf__change_set__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__change_set__free_unpacked (OSMPBF__ChangeSet *message, ProtobufCAllocator *allocator)
void osmpbf__node__init (OSMPBF__Node *message)
size_t osmpbf__node__get_packed_size (const OSMPBF__Node *message)
size_t osmpbf__node__pack (const OSMPBF__Node *message, uint8_t *out)
size_t osmpbf__node__pack_to_buffer (const OSMPBF__Node *message, ProtobufCBuffer *buffer)
OSMPBF__Node * osmpbf__node__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__node__free_unpacked (OSMPBF__Node *message, ProtobufCAllocator *allocator)
void osmpbf__dense_nodes__init (OSMPBF__DenseNodes *message)
size_t osmpbf__dense_nodes__get_packed_size (const OSMPBF__DenseNodes *message)
size_t osmpbf__dense_nodes__pack (const OSMPBF__DenseNodes *message, uint8_t *out)
size_t osmpbf__dense_nodes__pack_to_buffer (const OSMPBF__DenseNodes *message, ProtobufCBuffer *buffer)
OSMPBF__DenseNodes * osmpbf__dense_nodes__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__dense_nodes__free_unpacked (OSMPBF__DenseNodes *message, ProtobufCAllocator *allocator)
void osmpbf__way__init (OSMPBF__Way *message)
size_t osmpbf__way__get_packed_size (const OSMPBF__Way *message)
size_t osmpbf__way__pack (const OSMPBF__Way *message, uint8_t *out)
size_t osmpbf__way__pack_to_buffer (const OSMPBF__Way *message, ProtobufCBuffer *buffer)
OSMPBF__Way * osmpbf__way__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__way__free_unpacked (OSMPBF__Way *message, ProtobufCAllocator *allocator)
void osmpbf__relation__init (OSMPBF__Relation *message)
size_t osmpbf__relation__get_packed_size (const OSMPBF__Relation *message)
size_t osmpbf__relation__pack (const OSMPBF__Relation *message, uint8_t *out)
size_t osmpbf__relation__pack_to_buffer (const OSMPBF__Relation *message, ProtobufCBuffer *buffer)
OSMPBF__Relation * osmpbf__relation__unpack (ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void osmpbf__relation__free_unpacked (OSMPBF__Relation *message, ProtobufCAllocator *allocator)
Variables
const ProtobufCMessageDescriptor osmpbf__header_block__descriptor
const ProtobufCMessageDescriptor osmpbf__header_bbox__descriptor
const ProtobufCMessageDescriptor osmpbf__primitive_block__descriptor
const ProtobufCMessageDescriptor osmpbf__primitive_group__descriptor
const ProtobufCMessageDescriptor osmpbf__string_table__descriptor
const ProtobufCMessageDescriptor osmpbf__info__descriptor
const ProtobufCMessageDescriptor osmpbf__dense_info__descriptor
const ProtobufCMessageDescriptor osmpbf__change_set__descriptor
const ProtobufCMessageDescriptor osmpbf__node__descriptor
const ProtobufCMessageDescriptor osmpbf__dense_nodes__descriptor
const ProtobufCMessageDescriptor osmpbf__way__descriptor
const ProtobufCMessageDescriptor osmpbf__relation__descriptor
const ProtobufCEnumDescriptor osmpbf__relation__member_type__descriptor
Macro Definition Documentation
OSMPBF__CHANGE_SET__INIT
#define OSMPBF__CHANGE_SET__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__change_set__descriptor) \
    , 0 }
Referenced by osmpbf__change_set__init().
OSMPBF__DENSE_INFO__INIT
#define OSMPBF__DENSE_INFO__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__dense_info__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }
Referenced by osm_protobufdb_start_group(), and osmpbf__dense_info__init().
OSMPBF__DENSE_NODES__INIT
#define OSMPBF__DENSE_NODES__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__dense_nodes__descriptor) \
    , 0,NULL, NULL, 0,NULL, 0,NULL, 0,NULL }
Referenced by osm_protobufdb_start_group(), and osmpbf__dense_nodes__init().
OSMPBF__HEADER_BBOX__INIT
#define OSMPBF__HEADER_BBOX__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__header_bbox__descriptor) \
    , 0, 0, 0, 0 }
Referenced by osmpbf__header_bbox__init().
OSMPBF__HEADER_BLOCK__INIT
#define OSMPBF__HEADER_BLOCK__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__header_block__descriptor) \
    , NULL, 0,NULL, 0,NULL, NULL, NULL }
Referenced by osmpbf__header_block__init().
OSMPBF__INFO__INIT
#define OSMPBF__INFO__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__info__descriptor) \
    , 0,-1, 0,0, 0,0, 0,0, 0,0 }
Referenced by osm_protobufdb_parse_info(), and osmpbf__info__init().
OSMPBF__NODE__INIT
#define OSMPBF__NODE__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__node__descriptor) \
    , 0, 0,NULL, 0,NULL, NULL, 0, 0 }
Referenced by osm_protobufdb_insert_node(), osm_protobufdb_parse_node(), and osmpbf__node__init().
OSMPBF__PRIMITIVE_BLOCK__INIT
#define OSMPBF__PRIMITIVE_BLOCK__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__primitive_block__descriptor) \
    , NULL, 0,NULL, 0,100, 0,0, 0,0, 0,1000 }
Referenced by osm_protobufdb_start_block(), and osmpbf__primitive_block__init().
OSMPBF__PRIMITIVE_GROUP__INIT
#define OSMPBF__PRIMITIVE_GROUP__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__primitive_group__descriptor) \
    , 0,NULL, NULL, 0,NULL, 0,NULL, 0,NULL }
Referenced by osm_protobufdb_start_group(), and osmpbf__primitive_group__init().
OSMPBF__RELATION__INIT
#define OSMPBF__RELATION__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__relation__descriptor) \
    , 0, 0,NULL, 0,NULL, NULL, 0,NULL, 0,NULL, 0,NULL }
Referenced by osm_protobufdb_insert_relation(), osm_protobufdb_parse_relation(), and osmpbf__relation__init().
OSMPBF__STRING_TABLE__INIT
#define OSMPBF__STRING_TABLE__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__string_table__descriptor) \
    , 0,NULL }
Referenced by osm_protobufdb_start_block(), and osmpbf__string_table__init().
OSMPBF__WAY__INIT
#define OSMPBF__WAY__INIT
Value:
{ PROTOBUF_C_MESSAGE_INIT (&osmpbf__way__descriptor) \
    , 0, 0,NULL, 0,NULL, NULL, 0,NULL }
Referenced by osm_protobufdb_insert_way(), osm_protobufdb_parse_way(), and osmpbf__way__init().
Typedef Documentation
OSMPBF__ChangeSet
typedef struct _OSMPBF__ChangeSet OSMPBF__ChangeSet
OSMPBF__ChangeSet_Closure
typedef void(* OSMPBF__ChangeSet_Closure) (const OSMPBF__ChangeSet *message, void *closure_data)
OSMPBF__DenseInfo
typedef struct _OSMPBF__DenseInfo OSMPBF__DenseInfo
OSMPBF__DenseInfo_Closure
typedef void(* OSMPBF__DenseInfo_Closure) (const OSMPBF__DenseInfo *message, void *closure_data)
OSMPBF__DenseNodes
typedef struct _OSMPBF__DenseNodes OSMPBF__DenseNodes
OSMPBF__DenseNodes_Closure
typedef void(* OSMPBF__DenseNodes_Closure) (const OSMPBF__DenseNodes *message, void *closure_data)
OSMPBF__HeaderBBox
typedef struct _OSMPBF__HeaderBBox OSMPBF__HeaderBBox
OSMPBF__HeaderBBox_Closure
typedef void(* OSMPBF__HeaderBBox_Closure) (const OSMPBF__HeaderBBox *message, void *closure_data)
OSMPBF__HeaderBlock
typedef typedefPROTOBUF_C_BEGIN_DECLS struct _OSMPBF__HeaderBlock OSMPBF__HeaderBlock
OSMPBF__HeaderBlock_Closure
typedef void(* OSMPBF__HeaderBlock_Closure) (const OSMPBF__HeaderBlock *message, void *closure_data)
OSMPBF__Info
typedef struct _OSMPBF__Info OSMPBF__Info
OSMPBF__Info_Closure
typedef void(* OSMPBF__Info_Closure) (const OSMPBF__Info *message, void *closure_data)
OSMPBF__Node
typedef struct _OSMPBF__Node OSMPBF__Node
OSMPBF__Node_Closure
typedef void(* OSMPBF__Node_Closure) (const OSMPBF__Node *message, void *closure_data)
OSMPBF__PrimitiveBlock
typedef struct _OSMPBF__PrimitiveBlock OSMPBF__PrimitiveBlock
OSMPBF__PrimitiveBlock_Closure
typedef void(* OSMPBF__PrimitiveBlock_Closure) (const OSMPBF__PrimitiveBlock *message, void *closure_data)
OSMPBF__PrimitiveGroup
typedef struct _OSMPBF__PrimitiveGroup OSMPBF__PrimitiveGroup
OSMPBF__PrimitiveGroup_Closure
typedef void(* OSMPBF__PrimitiveGroup_Closure) (const OSMPBF__PrimitiveGroup *message, void *closure_data)
OSMPBF__Relation
typedef struct _OSMPBF__Relation OSMPBF__Relation
OSMPBF__Relation__MemberType
typedef enum _OSMPBF__Relation__MemberType OSMPBF__Relation__MemberType
OSMPBF__Relation_Closure
typedef void(* OSMPBF__Relation_Closure) (const OSMPBF__Relation *message, void *closure_data)
OSMPBF__StringTable
typedef struct _OSMPBF__StringTable OSMPBF__StringTable
OSMPBF__StringTable_Closure
typedef void(* OSMPBF__StringTable_Closure) (const OSMPBF__StringTable *message, void *closure_data)
OSMPBF__Way
typedef struct _OSMPBF__Way OSMPBF__Way
OSMPBF__Way_Closure
typedef void(* OSMPBF__Way_Closure) (const OSMPBF__Way *message, void *closure_data)
Enumeration Type Documentation
_OSMPBF__Relation__MemberType
enum _OSMPBF__Relation__MemberType
Enumerator
OSMPBF__RELATION__MEMBER_TYPE__NODE
OSMPBF__RELATION__MEMBER_TYPE__WAY
OSMPBF__RELATION__MEMBER_TYPE__RELATION
Function Documentation
osmpbf__change_set__free_unpacked()
void osmpbf__change_set__free_unpacked (OSMPBF__ChangeSet * message, ProtobufCAllocator * allocator)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, osmpbf__node__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__change_set__unpack().
osmpbf__change_set__get_packed_size()
size_t osmpbf__change_set__get_packed_size (const OSMPBF__ChangeSet * message)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, osmpbf__change_set__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__change_set__init().
osmpbf__change_set__init()
void osmpbf__change_set__init (OSMPBF__ChangeSet * message)
References osmpbf__change_set__get_packed_size(), and OSMPBF__CHANGE_SET__INIT.
Referenced by osmpbf__dense_info__free_unpacked().
osmpbf__change_set__pack()
size_t osmpbf__change_set__pack (const OSMPBF__ChangeSet * message, uint8_t * out)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, osmpbf__change_set__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__change_set__get_packed_size().
osmpbf__change_set__pack_to_buffer()
size_t osmpbf__change_set__pack_to_buffer (const OSMPBF__ChangeSet * message, ProtobufCBuffer * buffer)
References _OSMPBF__ChangeSet::base, _ProtobufCMessage::descriptor, osmpbf__change_set__descriptor, osmpbf__change_set__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__change_set__pack().
osmpbf__change_set__unpack()
OSMPBF__ChangeSet* osmpbf__change_set__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__change_set__descriptor, osmpbf__change_set__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__change_set__pack_to_buffer().
osmpbf__dense_info__free_unpacked()
void osmpbf__dense_info__free_unpacked (OSMPBF__DenseInfo * message, ProtobufCAllocator * allocator)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__change_set__init(), osmpbf__dense_info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__dense_info__unpack().
osmpbf__dense_info__get_packed_size()
size_t osmpbf__dense_info__get_packed_size (const OSMPBF__DenseInfo * message)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, osmpbf__dense_info__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__dense_info__init().
osmpbf__dense_info__init()
void osmpbf__dense_info__init (OSMPBF__DenseInfo * message)
References osmpbf__dense_info__get_packed_size(), and OSMPBF__DENSE_INFO__INIT.
Referenced by osmpbf__info__free_unpacked().
osmpbf__dense_info__pack()
size_t osmpbf__dense_info__pack (const OSMPBF__DenseInfo * message, uint8_t * out)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, osmpbf__dense_info__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__dense_info__get_packed_size().
osmpbf__dense_info__pack_to_buffer()
size_t osmpbf__dense_info__pack_to_buffer (const OSMPBF__DenseInfo * message, ProtobufCBuffer * buffer)
References _OSMPBF__DenseInfo::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__descriptor, osmpbf__dense_info__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__dense_info__pack().
osmpbf__dense_info__unpack()
OSMPBF__DenseInfo* osmpbf__dense_info__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__dense_info__descriptor, osmpbf__dense_info__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__dense_info__pack_to_buffer().
osmpbf__dense_nodes__free_unpacked()
void osmpbf__dense_nodes__free_unpacked (OSMPBF__DenseNodes * message, ProtobufCAllocator * allocator)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, osmpbf__way__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__dense_nodes__unpack().
osmpbf__dense_nodes__get_packed_size()
size_t osmpbf__dense_nodes__get_packed_size (const OSMPBF__DenseNodes * message)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, osmpbf__dense_nodes__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__dense_nodes__init().
osmpbf__dense_nodes__init()
void osmpbf__dense_nodes__init (OSMPBF__DenseNodes * message)
References osmpbf__dense_nodes__get_packed_size(), and OSMPBF__DENSE_NODES__INIT.
Referenced by osmpbf__node__free_unpacked().
osmpbf__dense_nodes__pack()
size_t osmpbf__dense_nodes__pack (const OSMPBF__DenseNodes * message, uint8_t * out)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, osmpbf__dense_nodes__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__dense_nodes__get_packed_size().
osmpbf__dense_nodes__pack_to_buffer()
size_t osmpbf__dense_nodes__pack_to_buffer (const OSMPBF__DenseNodes * message, ProtobufCBuffer * buffer)
References _OSMPBF__DenseNodes::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__descriptor, osmpbf__dense_nodes__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__dense_nodes__pack().
osmpbf__dense_nodes__unpack()
OSMPBF__DenseNodes* osmpbf__dense_nodes__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__dense_nodes__descriptor, osmpbf__dense_nodes__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__dense_nodes__pack_to_buffer().
osmpbf__header_bbox__free_unpacked()
void osmpbf__header_bbox__free_unpacked (OSMPBF__HeaderBBox * message, ProtobufCAllocator * allocator)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, osmpbf__primitive_block__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__header_bbox__unpack().
osmpbf__header_bbox__get_packed_size()
size_t osmpbf__header_bbox__get_packed_size (const OSMPBF__HeaderBBox * message)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, osmpbf__header_bbox__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__header_bbox__init().
osmpbf__header_bbox__init()
void osmpbf__header_bbox__init (OSMPBF__HeaderBBox * message)
References osmpbf__header_bbox__get_packed_size(), and OSMPBF__HEADER_BBOX__INIT.
Referenced by osmpbf__header_block__free_unpacked().
osmpbf__header_bbox__pack()
size_t osmpbf__header_bbox__pack (const OSMPBF__HeaderBBox * message, uint8_t * out)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, osmpbf__header_bbox__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__header_bbox__get_packed_size().
osmpbf__header_bbox__pack_to_buffer()
size_t osmpbf__header_bbox__pack_to_buffer (const OSMPBF__HeaderBBox * message, ProtobufCBuffer * buffer)
References _OSMPBF__HeaderBBox::base, _ProtobufCMessage::descriptor, osmpbf__header_bbox__descriptor, osmpbf__header_bbox__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__header_bbox__pack().
osmpbf__header_bbox__unpack()
OSMPBF__HeaderBBox* osmpbf__header_bbox__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__header_bbox__descriptor, osmpbf__header_bbox__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__header_bbox__pack_to_buffer().
osmpbf__header_block__free_unpacked()
void osmpbf__header_block__free_unpacked (OSMPBF__HeaderBlock * message, ProtobufCAllocator * allocator)
References osmpbf__header_bbox__init(), osmpbf__header_block__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__header_block__unpack(), and process_osmheader().
osmpbf__header_block__get_packed_size()
size_t osmpbf__header_block__get_packed_size (const OSMPBF__HeaderBlock * message)
References osmpbf__header_block__descriptor, osmpbf__header_block__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__header_block__init().
osmpbf__header_block__init()
void osmpbf__header_block__init (OSMPBF__HeaderBlock * message)
References osmpbf__header_block__get_packed_size(), and OSMPBF__HEADER_BLOCK__INIT.
osmpbf__header_block__pack()
size_t osmpbf__header_block__pack (const OSMPBF__HeaderBlock * message, uint8_t * out)
References osmpbf__header_block__descriptor, osmpbf__header_block__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__header_block__get_packed_size().
osmpbf__header_block__pack_to_buffer()
size_t osmpbf__header_block__pack_to_buffer (const OSMPBF__HeaderBlock * message, ProtobufCBuffer * buffer)
References osmpbf__header_block__descriptor, osmpbf__header_block__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__header_block__pack().
osmpbf__header_block__unpack()
OSMPBF__HeaderBlock* osmpbf__header_block__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__header_block__descriptor, osmpbf__header_block__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__header_block__pack_to_buffer(), and process_osmheader().
osmpbf__info__free_unpacked()
void osmpbf__info__free_unpacked (OSMPBF__Info * message, ProtobufCAllocator * allocator)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__dense_info__init(), osmpbf__info__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osm_protobufdb_modify_node(), osm_protobufdb_modify_relation(), osm_protobufdb_modify_way(), and osmpbf__info__unpack().
osmpbf__info__get_packed_size()
size_t osmpbf__info__get_packed_size (const OSMPBF__Info * message)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, osmpbf__info__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__info__init().
osmpbf__info__init()
void osmpbf__info__init (OSMPBF__Info * message)
References osmpbf__info__get_packed_size(), and OSMPBF__INFO__INIT.
Referenced by osmpbf__string_table__free_unpacked().
osmpbf__info__pack()
size_t osmpbf__info__pack (const OSMPBF__Info * message, uint8_t * out)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, osmpbf__info__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__info__get_packed_size().
osmpbf__info__pack_to_buffer()
size_t osmpbf__info__pack_to_buffer (const OSMPBF__Info * message, ProtobufCBuffer * buffer)
References _OSMPBF__Info::base, _ProtobufCMessage::descriptor, osmpbf__info__descriptor, osmpbf__info__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__info__pack().
osmpbf__info__unpack()
OSMPBF__Info* osmpbf__info__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__info__descriptor, osmpbf__info__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__info__pack_to_buffer().
osmpbf__node__free_unpacked()
void osmpbf__node__free_unpacked (OSMPBF__Node * message, ProtobufCAllocator * allocator)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__dense_nodes__init(), osmpbf__node__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__node__unpack().
osmpbf__node__get_packed_size()
size_t osmpbf__node__get_packed_size (const OSMPBF__Node * message)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, osmpbf__node__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__node__init().
osmpbf__node__init()
void osmpbf__node__init (OSMPBF__Node * message)
References osmpbf__node__get_packed_size(), and OSMPBF__NODE__INIT.
Referenced by osmpbf__change_set__free_unpacked().
osmpbf__node__pack()
size_t osmpbf__node__pack (const OSMPBF__Node * message, uint8_t * out)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, osmpbf__node__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__node__get_packed_size().
osmpbf__node__pack_to_buffer()
size_t osmpbf__node__pack_to_buffer (const OSMPBF__Node * message, ProtobufCBuffer * buffer)
References _OSMPBF__Node::base, _ProtobufCMessage::descriptor, osmpbf__node__descriptor, osmpbf__node__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__node__pack().
osmpbf__node__unpack()
OSMPBF__Node* osmpbf__node__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__node__descriptor, osmpbf__node__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__node__pack_to_buffer().
osmpbf__primitive_block__free_unpacked()
void osmpbf__primitive_block__free_unpacked (OSMPBF__PrimitiveBlock * message, ProtobufCAllocator * allocator)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, osmpbf__primitive_group__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osm_protobufdb_finish_block(), osmpbf__primitive_block__unpack(), and process_osmdata().
osmpbf__primitive_block__get_packed_size()
size_t osmpbf__primitive_block__get_packed_size (const OSMPBF__PrimitiveBlock * message)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, osmpbf__primitive_block__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osm_protobufdb_finish_block(), and osmpbf__primitive_block__init().
osmpbf__primitive_block__init()
void osmpbf__primitive_block__init (OSMPBF__PrimitiveBlock * message)
References osmpbf__primitive_block__get_packed_size(), and OSMPBF__PRIMITIVE_BLOCK__INIT.
Referenced by osmpbf__header_bbox__free_unpacked().
osmpbf__primitive_block__pack()
size_t osmpbf__primitive_block__pack (const OSMPBF__PrimitiveBlock * message, uint8_t * out)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, osmpbf__primitive_block__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osm_protobufdb_finish_block(), and osmpbf__primitive_block__get_packed_size().
osmpbf__primitive_block__pack_to_buffer()
size_t osmpbf__primitive_block__pack_to_buffer (const OSMPBF__PrimitiveBlock * message, ProtobufCBuffer * buffer)
References _OSMPBF__PrimitiveBlock::base, _ProtobufCMessage::descriptor, osmpbf__primitive_block__descriptor, osmpbf__primitive_block__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__primitive_block__pack().
osmpbf__primitive_block__unpack()
OSMPBF__PrimitiveBlock* osmpbf__primitive_block__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__primitive_block__descriptor, osmpbf__primitive_block__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__primitive_block__pack_to_buffer(), and process_osmdata().
osmpbf__primitive_group__free_unpacked()
void osmpbf__primitive_group__free_unpacked (OSMPBF__PrimitiveGroup * message, ProtobufCAllocator * allocator)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, osmpbf__string_table__init(), PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__primitive_group__unpack().
osmpbf__primitive_group__get_packed_size()
size_t osmpbf__primitive_group__get_packed_size (const OSMPBF__PrimitiveGroup * message)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, osmpbf__primitive_group__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__primitive_group__init().
osmpbf__primitive_group__init()
void osmpbf__primitive_group__init (OSMPBF__PrimitiveGroup * message)
References osmpbf__primitive_group__get_packed_size(), and OSMPBF__PRIMITIVE_GROUP__INIT.
Referenced by osmpbf__primitive_block__free_unpacked().
osmpbf__primitive_group__pack()
size_t osmpbf__primitive_group__pack (const OSMPBF__PrimitiveGroup * message, uint8_t * out)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, osmpbf__primitive_group__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__primitive_group__get_packed_size().
osmpbf__primitive_group__pack_to_buffer()
size_t osmpbf__primitive_group__pack_to_buffer (const OSMPBF__PrimitiveGroup * message, ProtobufCBuffer * buffer)
References _OSMPBF__PrimitiveGroup::base, _ProtobufCMessage::descriptor, osmpbf__primitive_group__descriptor, osmpbf__primitive_group__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__primitive_group__pack().
osmpbf__primitive_group__unpack()
OSMPBF__PrimitiveGroup* osmpbf__primitive_group__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__primitive_group__descriptor, osmpbf__primitive_group__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__primitive_group__pack_to_buffer().
osmpbf__relation__free_unpacked()
void osmpbf__relation__free_unpacked (OSMPBF__Relation * message, ProtobufCAllocator * allocator)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__relation__unpack().
osmpbf__relation__get_packed_size()
size_t osmpbf__relation__get_packed_size (const OSMPBF__Relation * message)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, osmpbf__relation__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__relation__init().
osmpbf__relation__init()
void osmpbf__relation__init (OSMPBF__Relation * message)
References osmpbf__relation__get_packed_size(), and OSMPBF__RELATION__INIT.
Referenced by osmpbf__way__free_unpacked().
osmpbf__relation__pack()
size_t osmpbf__relation__pack (const OSMPBF__Relation * message, uint8_t * out)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, osmpbf__relation__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__relation__get_packed_size().
osmpbf__relation__pack_to_buffer()
size_t osmpbf__relation__pack_to_buffer (const OSMPBF__Relation * message, ProtobufCBuffer * buffer)
References _OSMPBF__Relation::base, _ProtobufCMessage::descriptor, osmpbf__relation__descriptor, osmpbf__relation__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__relation__pack().
osmpbf__relation__unpack()
OSMPBF__Relation* osmpbf__relation__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__relation__descriptor, osmpbf__relation__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__relation__pack_to_buffer().
osmpbf__string_table__free_unpacked()
void osmpbf__string_table__free_unpacked (OSMPBF__StringTable * message, ProtobufCAllocator * allocator)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__info__init(), osmpbf__string_table__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__string_table__unpack().
osmpbf__string_table__get_packed_size()
size_t osmpbf__string_table__get_packed_size (const OSMPBF__StringTable * message)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, osmpbf__string_table__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__string_table__init().
osmpbf__string_table__init()
void osmpbf__string_table__init (OSMPBF__StringTable * message)
References osmpbf__string_table__get_packed_size(), and OSMPBF__STRING_TABLE__INIT.
Referenced by osmpbf__primitive_group__free_unpacked().
osmpbf__string_table__pack()
size_t osmpbf__string_table__pack (const OSMPBF__StringTable * message, uint8_t * out)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, osmpbf__string_table__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__string_table__get_packed_size().
osmpbf__string_table__pack_to_buffer()
size_t osmpbf__string_table__pack_to_buffer (const OSMPBF__StringTable * message, ProtobufCBuffer * buffer)
References _OSMPBF__StringTable::base, _ProtobufCMessage::descriptor, osmpbf__string_table__descriptor, osmpbf__string_table__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__string_table__pack().
osmpbf__string_table__unpack()
OSMPBF__StringTable* osmpbf__string_table__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__string_table__descriptor, osmpbf__string_table__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__string_table__pack_to_buffer().
osmpbf__way__free_unpacked()
void osmpbf__way__free_unpacked (OSMPBF__Way * message, ProtobufCAllocator * allocator)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__relation__init(), osmpbf__way__descriptor, PROTOBUF_C_ASSERT, and protobuf_c_message_free_unpacked().
Referenced by osmpbf__way__unpack().
osmpbf__way__get_packed_size()
size_t osmpbf__way__get_packed_size (const OSMPBF__Way * message)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, osmpbf__way__pack(), PROTOBUF_C_ASSERT, and protobuf_c_message_get_packed_size().
Referenced by osmpbf__way__init().
osmpbf__way__init()
void osmpbf__way__init (OSMPBF__Way * message)
References osmpbf__way__get_packed_size(), and OSMPBF__WAY__INIT.
Referenced by osmpbf__dense_nodes__free_unpacked().
osmpbf__way__pack()
size_t osmpbf__way__pack (const OSMPBF__Way * message, uint8_t * out)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, osmpbf__way__pack_to_buffer(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack().
Referenced by osmpbf__way__get_packed_size().
osmpbf__way__pack_to_buffer()
size_t osmpbf__way__pack_to_buffer (const OSMPBF__Way * message, ProtobufCBuffer * buffer)
References _OSMPBF__Way::base, _ProtobufCMessage::descriptor, osmpbf__way__descriptor, osmpbf__way__unpack(), PROTOBUF_C_ASSERT, and protobuf_c_message_pack_to_buffer().
Referenced by osmpbf__way__pack().
osmpbf__way__unpack()
OSMPBF__Way* osmpbf__way__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References osmpbf__way__descriptor, osmpbf__way__free_unpacked(), and protobuf_c_message_unpack().
Referenced by osmpbf__way__pack_to_buffer().
Variable Documentation
osmpbf__change_set__descriptor
const ProtobufCMessageDescriptor osmpbf__change_set__descriptor
Referenced by osmpbf__change_set__free_unpacked(), osmpbf__change_set__get_packed_size(), osmpbf__change_set__pack(), osmpbf__change_set__pack_to_buffer(), and osmpbf__change_set__unpack().
osmpbf__dense_info__descriptor
const ProtobufCMessageDescriptor osmpbf__dense_info__descriptor
Referenced by osmpbf__dense_info__free_unpacked(), osmpbf__dense_info__get_packed_size(), osmpbf__dense_info__pack(), osmpbf__dense_info__pack_to_buffer(), and osmpbf__dense_info__unpack().
osmpbf__dense_nodes__descriptor
const ProtobufCMessageDescriptor osmpbf__dense_nodes__descriptor
Referenced by osmpbf__dense_nodes__free_unpacked(), osmpbf__dense_nodes__get_packed_size(), osmpbf__dense_nodes__pack(), osmpbf__dense_nodes__pack_to_buffer(), and osmpbf__dense_nodes__unpack().
osmpbf__header_bbox__descriptor
const ProtobufCMessageDescriptor osmpbf__header_bbox__descriptor
Referenced by osmpbf__header_bbox__free_unpacked(), osmpbf__header_bbox__get_packed_size(), osmpbf__header_bbox__pack(), osmpbf__header_bbox__pack_to_buffer(), and osmpbf__header_bbox__unpack().
osmpbf__header_block__descriptor
const ProtobufCMessageDescriptor osmpbf__header_block__descriptor
Referenced by osmpbf__header_block__free_unpacked(), osmpbf__header_block__get_packed_size(), osmpbf__header_block__pack(), osmpbf__header_block__pack_to_buffer(), and osmpbf__header_block__unpack().
osmpbf__info__descriptor
const ProtobufCMessageDescriptor osmpbf__info__descriptor
Referenced by osmpbf__info__free_unpacked(), osmpbf__info__get_packed_size(), osmpbf__info__pack(), osmpbf__info__pack_to_buffer(), and osmpbf__info__unpack().
osmpbf__node__descriptor
const ProtobufCMessageDescriptor osmpbf__node__descriptor
Referenced by osmpbf__node__free_unpacked(), osmpbf__node__get_packed_size(), osmpbf__node__pack(), osmpbf__node__pack_to_buffer(), and osmpbf__node__unpack().
osmpbf__primitive_block__descriptor
const ProtobufCMessageDescriptor osmpbf__primitive_block__descriptor
Referenced by osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_block__pack(), osmpbf__primitive_block__pack_to_buffer(), and osmpbf__primitive_block__unpack().
osmpbf__primitive_group__descriptor
const ProtobufCMessageDescriptor osmpbf__primitive_group__descriptor
Referenced by osmpbf__primitive_group__free_unpacked(), osmpbf__primitive_group__get_packed_size(), osmpbf__primitive_group__pack(), osmpbf__primitive_group__pack_to_buffer(), and osmpbf__primitive_group__unpack().
osmpbf__relation__descriptor
const ProtobufCMessageDescriptor osmpbf__relation__descriptor
Referenced by osmpbf__relation__free_unpacked(), osmpbf__relation__get_packed_size(), osmpbf__relation__pack(), osmpbf__relation__pack_to_buffer(), and osmpbf__relation__unpack().
osmpbf__relation__member_type__descriptor
const ProtobufCEnumDescriptor osmpbf__relation__member_type__descriptor
osmpbf__string_table__descriptor
const ProtobufCMessageDescriptor osmpbf__string_table__descriptor
Referenced by osmpbf__string_table__free_unpacked(), osmpbf__string_table__get_packed_size(), osmpbf__string_table__pack(), osmpbf__string_table__pack_to_buffer(), and osmpbf__string_table__unpack().
osmpbf__way__descriptor
const ProtobufCMessageDescriptor osmpbf__way__descriptor
Referenced by osmpbf__way__free_unpacked(), osmpbf__way__get_packed_size(), osmpbf__way__pack(), osmpbf__way__pack_to_buffer(), and osmpbf__way__unpack().