navit: autoload/osso/osso.c File Reference
osso.c File Reference
#include <libosso.h>
#include <stdlib.h>
#include "config.h"
#include "debug.h"
#include "item.h"
#include "attr.h"
#include "navit.h"
#include "plugin.h"
#include "callback.h"
#include "config_.h"
Data Structures
struct cb_hw_state_trail
Functions
static void osso_display_on (struct navit *this_)
static gboolean osso_cb_hw_state_idle (struct cb_hw_state_trail *params)
static void osso_cb_hw_state (osso_hw_state_t *state, gpointer data)
static void osso_navit (struct navit *nav, int add)
void plugin_init (void)
void plugin_deinit (void)
Variables
static osso_context_t * osso_context
static struct attr callback = { attr_callback }
char * version
Function Documentation
static void osso_cb_hw_state (osso_hw_state_t * state, gpointer data) static
Handle osso events
Parameters
state Osso hardware state
Parameters
data ptr to private data
Returns
nothing
References g_new, cb_hw_state_trail::nav, osso_cb_hw_state_idle(), params, and cb_hw_state_trail::state.
Referenced by osso_navit().
static gboolean osso_cb_hw_state_idle (struct cb_hw_state_trail * params) static
References dbg, FALSE, g_free(), lvl_debug, cb_hw_state_trail::nav, navit_destroy(), and cb_hw_state_trail::state.
Referenced by osso_cb_hw_state().
static void osso_display_on (struct navit * this_) static
References dbg, err(), lvl_warning, and osso_context.
Referenced by osso_navit().
static void osso_navit (struct navit * nav, int add) static
References callback_cast, callback_new_attr_0, dbg, lvl_debug, lvl_error, navit_add_callback(), NULL, osso_cb_hw_state(), osso_context, osso_display_on(), TRUE, and version.
Referenced by plugin_init().
void plugin_deinit (void)
References osso_context.
void plugin_init (void)
Description: Initialisation of vehicle_file plugin
Variable Documentation
struct attr callback = { attr_callback } static
Referenced by navit_init(), request_callback_new(), and request_navit_quit().
osso_context_t* osso_context static
Referenced by osso_display_on(), osso_navit(), and plugin_deinit().
void version
Shows a version
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by binfile_check_version(), index_init(), Java_org_navitproject_navit_Navit_NavitMain(), LoadPhData(), mapExtract::mapExtract(), org.navitproject.navit.NavitSpeech::NavitSpeech(), osm_protobufdb_parse_info(), osso_navit(), and test().