navit: param.c File Reference
param.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "param.h"
Functions
void param_add_string (const char *name, const char *value, struct param_list **param, int *count)
void param_add_dec (const char *name, unsigned long value, struct param_list **param, int *count)
void param_add_hex (const char *name, unsigned long value, struct param_list **param, int *count)
void param_add_hex_sig (const char *name, long value, struct param_list **param, int *count)
Function Documentation
param_add_dec()
void param_add_dec (const char * name, unsigned long value, struct param_list ** param, int * count)
References name, param_add_string(), and value.
param_add_hex()
void param_add_hex (const char * name, unsigned long value, struct param_list ** param, int * count)
References name, param_add_string(), and value.
param_add_hex_sig()
void param_add_hex_sig (const char * name, long value, struct param_list ** param, int * count)
References name, param_add_string(), and value.
param_add_string()
void param_add_string (const char * name, const char * value, struct param_list ** param, int * count)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References name, and value.
Referenced by param_add_dec(), param_add_hex(), and param_add_hex_sig().