navit: tools/gpx2navit_txt/src/parser.c File Reference
parser.c File Reference
#include "gpx2navit_txt.h"
Functions
void charHandle (void *userdata, const XML_Char *data, int length)
void startElement (void *userdata, const char *element, const char **attr)
void endElement (void *userdata, const char *element)
void parseMain (g2sprop *prop)
Function Documentation
void charHandle (void * userdata, const XML_Char * data, int length)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
a handler to parse charctor data on expat
References parsedata::bufptr, parsedata::databuf, DATABUFSIZE, DEBUG, fprintf(), i, length, and NULL.
Referenced by parseMain().
void endElement (void * userdata, const char * element)
a handler when a element ends
References parsedata::current, parsedata::depth, endElementControl(), i, parent::name, parsedata::parent, parent::parentptr, printf(), parsedata::prop, and g2sprop::verbose.
Referenced by parseMain().
void parseMain (g2sprop * prop)
References BUFFSIZE, charHandle(), closeParsedata(), createParsedata(), endElement(), ERR_CANNOTOPEN, ERR_OUTOFMEMORY, ERR_PARSEERROR, ERR_READERROR, exit, parsedata::fp, fp, fprintf(), int, NULL, g2sprop::output, parser, parsedata::prop, g2sprop::sourcefile, and startElement().
Referenced by main().
void startElement (void * userdata, const char * element, const char ** attr)
a handler when a element starts
References parsedata::current, parsedata::depth, i, parent::name, parsedata::parent, parent::parentptr, printf(), parsedata::prop, startElementControl(), and g2sprop::verbose.
Referenced by parseMain().