navit: binding/python/pcoord.c File Reference
pcoord.c File Reference
#include "common.h"
#include "coord.h"
Data Structures
struct pcoordObject
Functions
static PyObject * pcoord_func (pcoordObject *self, PyObject *args)
static PyObject * pcoord_getattr_py (PyObject *self, char *name)
static void pcoord_destroy_py (pcoordObject *self)
PyObject * pcoord_py (PyObject *self, PyObject *args)
struct pcoord * pcoord_py_get (PyObject *self)
Variables
static PyMethodDef pcoord_methods []
PyTypeObject pcoord_Type
Function Documentation
pcoord_destroy_py()
static void pcoord_destroy_py (pcoordObject * self) static
pcoord_func()
static PyObject * pcoord_func (pcoordObject * self, PyObject * args) static
pcoord_getattr_py()
static PyObject * pcoord_getattr_py (PyObject * self, char * name) static
References name, and pcoord_methods.
pcoord_py()
PyObject * pcoord_py (PyObject * self, PyObject * args)
References c, coord_parse(), dbg, lvl_debug, pcoordObject::pc, pcoord_Type, pcoord::pro, pcoord::x, and pcoord::y.
pcoord_py_get()
struct pcoord * pcoord_py_get (PyObject * self)
Referenced by navit_set_center_py(), navit_set_destination_py(), and navit_set_position_py().
Variable Documentation
pcoord_methods
PyMethodDef pcoord_methods[] static
Initial value:
= {
    {"func", (PyCFunction)pcoord_func, METH_VARARGS},
    {NULL, NULL},
}
Referenced by pcoord_getattr_py().
pcoord_Type
PyTypeObject pcoord_Type
Initial value:
= {
    Obj_HEAD,
    .tp_name = "pcoord",
    .tp_basicsize = sizeof(pcoordObject),
    .tp_dealloc = (destructor)pcoord_destroy_py,
    .tp_getattr = pcoord_getattr_py,
}
Referenced by navit_set_center_py(), navit_set_destination_py(), navit_set_position_py(), and pcoord_py().