navit: plugin/pedestrian/pedestrian.c File Reference
pedestrian.c File Reference
#include <math.h>
#include <stdio.h>
#include <glib.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#include <errno.h>
#include <sys/ioctl.h>
#include "config.h"
#include <navit/item.h>
#include <navit/xmlconfig.h>
#include <navit/main.h>
#include <navit/debug.h>
#include <navit/point.h>
#include <navit/graphics.h>
#include <navit/transform.h>
#include <navit/map.h>
#include <navit/navit.h>
#include <navit/callback.h>
#include <navit/file.h>
#include <navit/color.h>
#include <navit/route.h>
#include <navit/plugin.h>
#include <navit/layout.h>
#include <navit/mapset.h>
#include <navit/osd.h>
#include <navit/event.h>
#include <navit/command.h>
#include <navit/config_.h>
#include <navit/vehicle.h>
Data Structures
struct pedestrian
struct rocket
struct marker
struct map_priv
Represents the map from a single binfile.
struct map_rect_priv
struct building
struct tilt_data
Macros
#define DEBUG_COORD_GET
Functions
static void pedestrian_rocket_idle (struct rocket *rocket)
static void pedestrian_cmd_pedestrian_rocket (struct rocket *rocket)
static void osd_rocket_init (struct navit *nav)
static void osd_marker_draw (struct marker *this, struct navit *nav)
static void osd_marker_init (struct marker *this, struct navit *nav)
static struct osd_priv * osd_marker_new (struct navit *nav, struct osd_methods *meth, struct attr **attrs)
static int map_route_occluded_bbox (struct map *map, struct coord_rect *bbox)
static void map_route_occluded_buildings_free (void)
static void map_route_occluded_get_buildings (struct mapset *mapset, struct coord_rect *r)
static int side (struct coord *l0, struct coord *l1, struct coord *p)
static void map_route_occluded_check_buildings (struct coord *c0)
static int intersect (struct coord *p1, struct coord *p2, struct coord *p3, struct coord *p4, struct coord *i)
static int is_visible_line (struct coord *c0, struct coord *c1, struct coord *c2)
static void map_route_occluded_coord_rewind (void *priv_data)
static void map_route_occluded_attr_rewind (void *priv_data)
static int map_route_occluded_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int coord_next (struct map_rect_priv *mr, struct coord *c)
static int map_route_occluded_coord_get (void *priv_data, struct coord *c, int count)
static void map_route_occluded_destroy (struct map_priv *priv)
static struct map_rect_priv * map_route_occluded_rect_new (struct map_priv *priv, struct map_selection *sel)
static void map_route_occluded_rect_destroy (struct map_rect_priv *mr)
static struct item * map_route_occluded_get_item (struct map_rect_priv *mr)
static struct item * map_route_occluded_get_item_byid (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct map_priv * map_route_occluded_new (struct map_methods *meth, struct attr **attrs)
static void pedestrian_graphics_resize (struct graphics *gra, int w, int h)
static void pedestrian_draw_arrow (struct graphics *gra, char *name, int x, int y)
static void pedestrian_draw_arrows (struct graphics *gra)
static void pedestrian_graphics_postdraw (struct graphics *gra)
void pedestrian_write_tilt (int fd, int axis)
void pedestrian_read_tilt (int fd, struct navit *nav, struct tilt_data *data)
void pedestrian_write_tilt_timer (int fd, struct tilt_data *data)
void pedestrian_setup_tilt (struct navit *nav)
static void pedestrian_log (char **logstr)
static void pedestrian_navit_init (struct navit *nav)
static void pedestrian_navit (struct navit *nav, int add)
void plugin_init (void)
The plugin entry point.
Variables
static struct map * global_map
int orientation
int orientation_old
struct pedestrian pedestrian_data
int sensors_locked
struct attr initial_layout main_layout
static struct command_table commands []
static struct building * buildings
FILE * debug
FILE * debug2
static struct item_methods methods_route_occluded_item
static int no_recurse
static struct map_methods map_route_occluded_methods
Macro Definition Documentation
#define DEBUG_COORD_GET
Function Documentation
static int coord_next (struct map_rect_priv * mr, struct coord * c) static
References street_data::c, street_data::count, map_rect_priv::idx, and map_rect_priv::sd.
Referenced by map_route_occluded_coord_get().
static int intersect (struct coord * p1, struct coord * p2, struct coord * p3, struct coord * p4, struct coord * i) static
References dbg, debug2, fprintf(), lvl_debug, attr::num, coord::x, and coord::y.
Referenced by is_visible_line(), and SHPRewindObject().
static int is_visible_line (struct coord * c0, struct coord * c1, struct coord * c2) static
References buildings, dbg, intersect(), lvl_debug, building::next, building::right, side(), coord::x, and coord::y.
Referenced by map_route_occluded_coord_get().
static int map_route_occluded_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References dbg, item_attr_get(), lvl_debug, and map_rect_priv::route_item.
static void map_route_occluded_attr_rewind (void * priv_data) static
References dbg, item_attr_rewind(), lvl_debug, and map_rect_priv::route_item.
static int map_route_occluded_bbox (struct map * map, struct coord_rect * bbox) static
References coord_rect_extend(), i, attr::item, item_coord_get(), coord_rect::lu, map_rect_destroy(), map_rect_get_item(), map_rect_new(), NULL, and coord_rect::rl.
Referenced by map_route_occluded_rect_new().
static void map_route_occluded_buildings_free (void) static
References buildings, g_free(), building::next, next, NULL, building::sd, and street_data_free().
Referenced by map_route_occluded_get_buildings().
static void map_route_occluded_check_buildings (struct coord * c0) static
References buildings, street_data::c, c, street_data::count, dbg, fprintf(), i, lvl_debug, building::next, building::right, building::sd, side(), coord::x, and coord::y.
Referenced by map_route_occluded_coord_get().
static int map_route_occluded_coord_get (void * priv_data, struct coord * c, int count) static
References street_data::c, map_rect_priv::c0, map_rect_priv::c_next, map_rect_priv::c_next_base, map_rect_priv::c_out, map_rect_priv::checked, coord_next(), street_data::count, dbg, dbg_assert, debug, map_rect_priv::first, fprintf(), item::id_lo, map_rect_priv::idx, map_rect_priv::idx_base, is_visible_line(), street_data::item, map_rect_priv::last, map_rect_priv::lseg, map_rect_priv::lseg_base, map_rect_priv::lseg_done, map_rect_priv::lseg_done_base, lvl_debug, map_route_occluded_check_buildings(), map_rect_priv::route_item_done, map_rect_priv::sd, coord::x, and coord::y.
Referenced by map_route_occluded_get_item().
static void map_route_occluded_coord_rewind (void * priv_data) static
References map_rect_priv::c_next, map_rect_priv::c_next_base, dbg, map_rect_priv::first, map_rect_priv::idx, map_rect_priv::idx_base, item_coord_rewind(), map_rect_priv::last, map_rect_priv::lseg, map_rect_priv::lseg_base, map_rect_priv::lseg_done, map_rect_priv::lseg_done_base, lvl_debug, and map_rect_priv::route_item.
Referenced by map_route_occluded_get_item().
static void map_route_occluded_destroy (struct map_priv * priv) static
References g_free().
static void map_route_occluded_get_buildings (struct mapset * mapset, struct coord_rect * r) static
References buildings, map_selection::c_rect, g_new, item::id_hi, item::id_lo, attr::item, attr::map, map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_route_occluded_buildings_free(), mapset_next(), mapset_open(), item_range::max, map_selection::next, building::next, NULL, map_selection::order, map_selection::range, building::sd, street_get_data(), item::type, and map_selection::u.
Referenced by map_route_occluded_rect_new().
static struct item* map_route_occluded_get_item (struct map_rect_priv * mr) static
References dbg, item::id_lo, map_rect_priv::item, item_to_name(), map_rect_priv::last, lvl_debug, map_rect_get_item(), map_route_occluded_coord_get(), map_route_occluded_coord_rewind(), NULL, map_rect_priv::route_item, map_rect_priv::route_item_done, map_rect_priv::route_map_rect, map_rect_priv::sd, street_data_free(), street_get_data(), and item::type.
Referenced by map_route_occluded_get_item_byid().
static struct item* map_route_occluded_get_item_byid (struct map_rect_priv * mr, int id_hi, int id_lo) static
References map_route_occluded_get_item(), and NULL.
static struct map_priv* map_route_occluded_new (struct map_methods * meth, struct attr ** attrs) static
References attr_search(), dbg, g_new0, lvl_debug, map_route_occluded_methods, attr::navit, map_priv::navit, NULL, and attr::u.
Referenced by plugin_init().
static void map_route_occluded_rect_destroy (struct map_rect_priv * mr) static
References debug, debug2, g_free(), map_dump_file(), map_rect_destroy(), NULL, map_rect_priv::route_map_rect, map_rect_priv::sd, and street_data_free().
static struct map_rect_priv* map_route_occluded_rect_new (struct map_priv * priv, struct map_selection * sel) static
References dbg, debug, debug2, g_new0, item::id_lo, map_rect_priv::item, map_rect_priv::last, map_rect_priv::lseg_done_base, lvl_debug, attr::map, map_dump_file(), map_rect_new(), map_route_occluded_bbox(), map_route_occluded_get_buildings(), attr::mapset, item::meth, methods_route_occluded_item, map_rect_priv::mpriv, map_priv::navit, navit_get_attr(), NULL, item::priv_data, attr::route, route_get_attr(), map_rect_priv::route_item_done, map_rect_priv::route_map_rect, and attr::u.
static void osd_marker_draw (struct marker * this, struct navit * nav) static
References dbg, attr::graphics, lvl_debug, navit_get_attr(), NULL, attr::u, point::x, and point::y.
Referenced by osd_marker_init().
static void osd_marker_init (struct marker * this, struct navit * nav) static
References attr_free(), attr_new_from_text(), attr::color, coord_new_from_attrs(), attr::cursor, cursor_add_attr(), cursor_new(), attr::element, element_add_attr(), attr::itemgra, itemgra_add_attr(), itemgra_new(), NULL, osd_marker_draw(), polygon_new(), and attr::u.
Referenced by osd_marker_new().
static struct osd_priv* osd_marker_new (struct navit * nav, struct osd_methods * meth, struct attr ** attrs) static
References callback_cast, callback_new_attr_1, g_new0, navit_add_callback(), and osd_marker_init().
Referenced by plugin_init().
static void osd_rocket_init (struct navit * nav) static
References rocket::callback, callback_cast, attr::callback_list, callback_new_1, command_add_table(), dbg, g_new0, rocket::layout, attr::layout, lvl_debug, rocket::navit, navit_get_attr(), NULL, pedestrian_rocket_idle(), and attr::u.
Referenced by pedestrian_navit_init().
static void pedestrian_cmd_pedestrian_rocket (struct rocket * rocket) static
References rocket::a, rocket::callback, attr::displaylist, rocket::dl, event_add_idle(), rocket::g, rocket::gra, attr::graphics, graphics_displaylist_draw(), graphics_draw(), graphics_overlay_disable(), rocket::hog, i, rocket::idle, rocket::layout, attr::mapset, max, rocket::ms, rocket::navit, navit_get_attr(), NULL, sensors_locked, rocket::t, rocket::trans, trans, transform_get_scale(), transform_set_hog(), transform_set_order_base(), transform_set_scale(), transform_setup_source_rect(), attr::transformation, attr::u, rocket::v, and rocket::vscale.
static void pedestrian_draw_arrow (struct graphics * gra, char * name, int x, int y) static
References g_free(), graphics_draw_image(), graphics_gc_destroy(), graphics_gc_new(), graphics_gc_set_foreground(), graphics_icon_path(), graphics_image_free(), graphics_image_new(), point::x, and point::y.
Referenced by pedestrian_draw_arrows().
static void pedestrian_draw_arrows (struct graphics * gra) static
References center, dbg, pedestrian::h, attr::item, item_coord_get(), lvl_debug, attr::map, map_rect_destroy(), map_rect_get_item(), map_rect_new(), pedestrian::nav, navit_get_attr(), navit_get_trans(), NULL, orientation, pedestrian_data, pedestrian_draw_arrow(), attr::route, route_get_attr(), transform_get_angle_delta(), transform_get_center(), item::type, attr::u, pedestrian::w, and pedestrian::yaw.
Referenced by pedestrian_graphics_postdraw().
static void pedestrian_graphics_postdraw (struct graphics * gra) static
References graphics_draw_rectangle(), graphics_gc_destroy(), graphics_gc_new(), graphics_gc_set_foreground(), pedestrian_draw_arrows(), point::x, and point::y.
Referenced by pedestrian_navit_init().
static void pedestrian_graphics_resize (struct graphics * gra, int w, int h) static
References graphics_get_data(), pedestrian::h, int, pedestrian_data, sprintf(), and pedestrian::w.
Referenced by pedestrian_navit_init().
static void pedestrian_log (char ** logstr) static
References g_strdup_printf(), and vehicle_log_gpx_add_tag().
Referenced by pedestrian_navit_init().
static void pedestrian_navit (struct navit * nav, int add) static
References attr::callback, callback_cast, callback_new_attr_0, dbg, lvl_debug, navit_add_attr(), pedestrian_navit_init(), attr::type, and attr::u.
Referenced by plugin_init().
static void pedestrian_navit_init (struct navit * nav) static
References android_activity, android_find_class_global(), attr_to_name(), attr::callback, callback_cast, callback_new_1, callback_new_attr_0, callback_new_attr_1, callback_new_attr_2, dbg, attr::graphics, graphics_add_callback(), graphics_set_attr(), eval::iter, jnienv, attr::layout, lvl_debug, main_layout, attr::map, map_new(), map_set_attr(), attr::mapset, mapset_add_attr(), layout::name, pedestrian::nav, navit_attr_iter_destroy(), navit_attr_iter_new(), navit_get_attr(), navit_get_trans(), navit_set_attr(), NULL, attr::num, osd_rocket_init(), pedestrian_data, pedestrian_graphics_postdraw(), pedestrian_graphics_resize(), pedestrian_log(), pedestrian_setup_tilt(), attr::route, route_get_attr(), trans, transform_set_distance(), transform_set_hog(), transform_set_pitch(), transform_set_roll(), transform_set_scale(), transform_set_scales(), attr::type, attr::u, attr::vehicle, and vehicle_add_attr().
Referenced by pedestrian_navit(), and plugin_init().
void pedestrian_read_tilt (int fd, struct navit * nav, struct tilt_data * data)
References tilt_data::axis, tilt_data::buffer, dbg, tilt_data::len, lvl_debug, navit_get_attr(), NULL, pedestrian_write_tilt(), read(), trans, transform_set_pitch(), transform_set_roll(), attr::transformation, and attr::u.
Referenced by pedestrian_setup_tilt().
static void pedestrian_rocket_idle (struct rocket * rocket) static
References rocket::a, dbg, rocket::dl, event_remove_idle(), rocket::g, rocket::gra, graphics_displaylist_draw(), graphics_overlay_disable(), rocket::hog, rocket::idle, rocket::layout, lvl_debug, rocket::navit, navit_draw(), navit_set_attr(), NULL, attr::num, sensors_locked, rocket::t, rocket::trans, transform_get_scale(), transform_set_hog(), transform_set_order_base(), transform_set_scale(), attr::type, attr::u, rocket::v, and rocket::vscale.
Referenced by osd_rocket_init().
void pedestrian_setup_tilt (struct navit * nav)
References B19200, callback_cast, callback_new_2, callback_new_3, attr::data, dbg, errno, event_add_timeout(), event_add_watch(), event_watch_cond_read, g_new0, lvl_error, O_RDWR, open(), pedestrian_read_tilt(), pedestrian_write_tilt(), pedestrian_write_tilt_timer(), and read().
Referenced by pedestrian_navit_init().
void pedestrian_write_tilt (int fd, int axis)
References dbg, lvl_debug, and write().
Referenced by pedestrian_read_tilt(), pedestrian_setup_tilt(), and pedestrian_write_tilt_timer().
void pedestrian_write_tilt_timer (int fd, struct tilt_data * data)
References tilt_data::axis, and pedestrian_write_tilt().
Referenced by pedestrian_setup_tilt().
void plugin_init (void)
The plugin entry point.
Description: Initialisation of vehicle_file plugin
Returns
nothing
The plugin entry point
References android_activity, android_find_class_global(), attr::callback, callback_cast, callback_new_attr_0, config_add_attr(), config_attr_iter_destroy(), config_attr_iter_new(), config_get_attr(), dbg, eval::iter, jnienv, lvl_error, map_route_occluded_new(), attr::navit, NULL, osd_marker_new(), pedestrian_navit(), pedestrian_navit_init(), attr::type, and attr::u.
static int side (struct coord * l0, struct coord * l1, struct coord * p) static
References coord::x, and coord::y.
Referenced by is_visible_line(), and map_route_occluded_check_buildings().
Variable Documentation
struct building * buildings static
Referenced by is_visible_line(), map_route_occluded_buildings_free(), map_route_occluded_check_buildings(), and map_route_occluded_get_buildings().
struct command_table commands[] static
Initial value:
= {
        {"pedestrian_rocket",command_cast(pedestrian_cmd_pedestrian_rocket)},
}
FILE* debug
Referenced by block_next(), debug_new(), file_next(), gmap_new(), housenumber_search_setup(), map_route_occluded_coord_get(), map_route_occluded_rect_destroy(), map_route_occluded_rect_new(), street_coord_get(), tile_collector_add_siblings(), and tile_collector_add_siblings2().
FILE * debug2
Referenced by intersect(), map_route_occluded_rect_destroy(), and map_route_occluded_rect_new().
struct map* global_map static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
struct attr initial_layout main_layout
Referenced by pedestrian_navit_init().
struct map_methods map_route_occluded_methods static
Initial value:
= {
        projection_mg,
        "utf-8",
        map_route_occluded_destroy,
        map_route_occluded_rect_new,
        map_route_occluded_rect_destroy,
        map_route_occluded_get_item,
        map_route_occluded_get_item_byid,
        NULL,
        NULL,
        NULL,
}
Referenced by map_route_occluded_new().
struct item_methods methods_route_occluded_item static
Initial value:
= {
        map_route_occluded_coord_rewind,
        map_route_occluded_coord_get,
        map_route_occluded_attr_rewind,
        map_route_occluded_attr_get,
}
Referenced by map_route_occluded_rect_new().
int no_recurse static
int orientation
Referenced by graphics_sdl_new(), gui_internal_box_pack(), and pedestrian_draw_arrows().
int orientation_old
struct pedestrian pedestrian_data
Referenced by pedestrian_draw_arrows(), pedestrian_graphics_resize(), and pedestrian_navit_init().
int sensors_locked
Referenced by pedestrian_cmd_pedestrian_rocket(), and pedestrian_rocket_idle().