navit: support/espeak/phonemelist.c File Reference
phonemelist.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "translate.h"
Functions
static int ChangePhonemes (Translator *tr, PHONEME_LIST2 *phlist, int n_ph, int index, PHONEME_TAB *ph, CHANGEPH *ch)
static int SubstitutePhonemes (Translator *tr, PHONEME_LIST2 *plist_out)
void MakePhonemeList (Translator *tr, int post_pause, int start_sentence)
Variables
const unsigned char pause_phonemes [8] = {0, phonPAUSE_VSHORT, phonPAUSE_SHORT, phonPAUSE, phonPAUSE_LONG, phonGLOTTALSTOP, phonPAUSE_LONG, phonPAUSE_LONG}
int n_ph_list2
PHONEME_LIST2 ph_list2 [N_PHONEME_LIST]
Function Documentation
static int ChangePhonemes (Translator * tr, PHONEME_LIST2 * phlist, int n_ph, int index, PHONEME_TAB * ph, CHANGEPH * ch) static
References ChangePhonemes_ru(), L, and Translator::translator_name.
Referenced by SubstitutePhonemes().
void MakePhonemeList (Translator * tr, int post_pause, int start_sentence)
References PHONEME_TAB::alternative_ph, PHONEME_LIST::amp, PHONEME_TAB::code, PHONEME_LIST::env, Translator::langopts, PHONEME_LIST::length, PHONEME_TAB::link_out, LOPT_REDUCE, LOPT_REDUCE_T, LOPT_REGRESSIVE_VOICING, PHONEME_TAB::mnemonic, n_ph_list2, N_PHONEME_LIST, n_phoneme_list, PHONEME_LIST::newword, next, NULL, option_wordgap, LANGUAGE_OPTIONS::param, pause_phonemes, PHONEME_LIST::ph, ph_list2, phALTERNATIVE, phAPPENDPH, phBEFORE_R, phBEFORENOTVOWEL, phBEFORENOTVOWEL2, phBEFOREPAUSE, phBEFOREVOWEL, phBEFOREVOWELPAUSE, PHONEME_LIST2::phcode, PHONEME_TAB::phflags, phFRICATIVE, phLIQUID, phNASAL, phoneme_list, phoneme_tab, phonPAUSE, phonPAUSE_LONG, phonPAUSE_NOLINK, phonPAUSE_SHORT, phonPAUSE_VSHORT, phonSWITCH, phonT_REDUCED, phPAUSE, phRHOTIC, phSTOP, phSWITCHVOICING, phVFRICATIVE, phVOICED, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PITCHfall, PHONEME_LIST::prepause, PHONEME_TAB::reduce_to, SelectPhonemeTable(), SFLAG_DICTIONARY, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_PROMOTE_STRESS, SFLAG_SWITCHED_LANG, SFLAG_SYLLABLE, PHONEME_LIST::sourceix, PHONEME_LIST2::sourceix, PHONEME_TAB::std_length, PHONEME_LIST2::stress, LANGUAGE_OPTIONS::stress_flags, PHONEME_LIST::stresslevel, SubstitutePhonemes(), PHONEME_LIST::synthflags, PHONEME_LIST2::synthflags, PHONEME_LIST2::tone_number, PHONEME_LIST::tone_ph, PHONEME_TAB::type, type, PHONEME_LIST::type, voicing, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by TranslateClause().
static int SubstitutePhonemes (Translator * tr, PHONEME_LIST2 * plist_out) static
References ChangePhonemes(), CHANGEPH::flags, Translator::langopts, n_ph_list2, N_PHONEME_LIST, n_replace_phonemes, CHANGEPH::n_vowels, REPLACE_PHONEMES::new_ph, next, NULL, REPLACE_PHONEMES::old_ph, PHONEME_LIST2::phcode, PHONEME_TAB::phflags, LANGUAGE_OPTIONS::phoneme_change, phoneme_tab, phonSWITCH, phPAUSE, phUNSTRESSED, phVOWEL, replace_phonemes, SFLAG_DICTIONARY, PHONEME_LIST2::sourceix, PHONEME_LIST2::stress, CHANGEPH::stress, CHANGEPH::stress_highest, PHONEME_TAB::type, REPLACE_PHONEMES::type, CHANGEPH::vowel_stressed, and CHANGEPH::vowel_this.
Referenced by MakePhonemeList().
Variable Documentation
int n_ph_list2
Referenced by MakePhonemeList(), SubstitutePhonemes(), TranslateClause(), and TranslateWord2().
const unsigned char pause_phonemes[8] = {0, phonPAUSE_VSHORT, phonPAUSE_SHORT, phonPAUSE, phonPAUSE_LONG, phonGLOTTALSTOP, phonPAUSE_LONG, phonPAUSE_LONG}
Referenced by MakePhonemeList(), and SetWordStress().
PHONEME_LIST2 ph_list2[N_PHONEME_LIST]
Referenced by MakePhonemeList().