navit: plugin.c File Reference
plugin.c File Reference
#include <string.h>
#include <glib.h>
#include "config.h"
#include "plugin.h"
#include "file.h"
#include "item.h"
#include "debug.h"
Data Structures
struct plugin
struct plugins
Macros
#define PLUGIN_C
Functions
static struct plugin * plugin_new_from_path (char *plugin)
int plugin_load (struct plugin *pl)
char * plugin_get_name (struct plugin *pl)
int plugin_get_active (struct plugin *pl)
void plugin_set_active (struct plugin *pl, int active)
void plugin_set_lazy (struct plugin *pl, int lazy)
static void plugin_set_ondemand (struct plugin *pl, int ondemand)
void plugin_call_init (struct plugin *pl)
void plugin_unload (struct plugin *pl)
void plugin_destroy (struct plugin *pl)
struct plugins * plugins_new (void)
struct plugin * plugin_new (struct attr *parent, struct attr **attrs)
void plugins_init (struct plugins *pls)
void plugins_destroy (struct plugins *pls)
static void * find_by_name (enum plugin_category category, const char *name)
void * plugin_get_category (enum plugin_category category, const char *category_name, const char *name)
Variables
struct plugins * pls
Macro Definition Documentation
#define PLUGIN_C
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
static void* find_by_name (enum plugin_category category, const char * name) static
References _GList::data, g_ascii_strcasecmp(), g_list_next, and NULL.
Referenced by plugin_get_category().
void plugin_call_init (struct plugin * pl)
References plugin::init.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
void plugin_destroy (struct plugin * pl)
References g_free().
Referenced by plugins_destroy().
int plugin_get_active (struct plugin * pl)
References plugin::active.
Referenced by plugin_get_category(), and plugins_init().
void* plugin_get_category (enum plugin_category category, const char * category_name, const char * name)
References _GList::data, dbg, find_by_name(), g_ascii_strncasecmp(), g_free(), g_list_next, g_strjoin(), g_strrstr(), plugins::list, lvl_debug, plugin::name, NULL, pls, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
char* plugin_get_name (struct plugin * pl)
References plugin::name.
Referenced by plugin_new().
int plugin_load (struct plugin * pl)
References dbg, plugin::init, plugin::lazy, lvl_debug, lvl_error, and plugin::name.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
struct plugin* plugin_new (struct attr * parent, struct attr ** attrs)
References active, attr_search(), dbg, file_exists(), file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), g_hash_table_insert(), g_hash_table_lookup(), g_list_append(), g_list_remove(), plugins::hash, i, plugins::list, lvl_debug, lvl_error, lvl_info, name, NULL, attr::num, pls, plugin_call_init(), plugin_get_name(), plugin_load(), plugin_new_from_path(), plugin_set_active(), plugin_set_lazy(), plugin_set_ondemand(), attr::plugins, attr::str, attr::u, and file_wordexp::we.
Referenced by add_plugin().
static struct plugin* plugin_new_from_path (char * plugin) static
References g_new0, g_strdup(), plugin::name, and NULL.
Referenced by plugin_new().
void plugin_set_active (struct plugin * pl, int active)
References active, and plugin::active.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
void plugin_set_lazy (struct plugin * pl, int lazy)
References plugin::lazy.
Referenced by plugin_new().
static void plugin_set_ondemand (struct plugin * pl, int ondemand) static
References plugin::ondemand.
Referenced by plugin_new().
void plugin_unload (struct plugin * pl)
References NULL.
Referenced by plugins_destroy().
void plugins_destroy (struct plugins * pls)
References _GList::data, g_free(), g_hash_table_destroy(), g_list_free(), plugins::hash, plugins::list, plugin_destroy(), and plugin_unload().
void plugins_init (struct plugins * pls)
References _GList::data, dbg, g_list_next, plugins::list, lvl_error, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
Referenced by maptool_init().
struct plugins* plugins_new (void)
References g_hash_table_new(), g_new0, g_str_equal(), g_str_hash(), plugins::hash, and pls.
Referenced by add_plugin().
Variable Documentation
struct plugins * pls
Referenced by plugin_get_category(), plugin_new(), and plugins_new().