navit: plugin.h File Reference
plugin.h File Reference
#include "plugin_def.h"
Macros
#define PLUGIN_PROTO(name,...) void name(__VA_ARGS__)
#define PLUGIN_FUNC1(name, t1, p1)
#define PLUGIN_FUNC3(name, t1, p1, t2, p2, t3, p3)
#define PLUGIN_FUNC4(name, t1, p1, t2, p2, t3, p3, t4, p4)
#define PLUGIN_CATEGORY(category, newargs)
#define plugin_module_cat3(pre, mod, post) pre##mod##post
#define plugin_module_cat2(pre, mod, post) plugin_module_cat3(pre,mod,post)
#define plugin_module_cat(pre, post) plugin_module_cat2(pre,MODULE,post)
#define plugin_init plugin_module_cat(module_,_init)
Enumerations
enum plugin_category {
plugin_category_graphics, plugin_category_gui, plugin_category_map, plugin_category_osd,
plugin_category_speech, plugin_category_vehicle, plugin_category_event, plugin_category_font,
plugin_category_last
}
All existing plugin categories.
Functions
void plugin_init (void)
The plugin entry point.
int plugin_load (struct plugin *pl)
char * plugin_get_name (struct plugin *pl)
int plugin_get_active (struct plugin *pl)
void plugin_set_active (struct plugin *pl, int active)
void plugin_set_lazy (struct plugin *pl, int lazy)
void plugin_call_init (struct plugin *pl)
void plugin_unload (struct plugin *pl)
void plugin_destroy (struct plugin *pl)
struct plugins * plugins_new (void)
struct plugin * plugin_new (struct attr *parent, struct attr **attrs)
void plugins_init (struct plugins *pls)
void plugins_destroy (struct plugins *pls)
void * plugin_get_category (enum plugin_category category, const char *category_name, const char *name)
Macro Definition Documentation
#define PLUGIN_CATEGORY (category, newargs)
Value:
struct category##_priv; \
struct category##_methods; \
void plugin_register_category_##category(const char *name, struct category##_priv *(*new_) newargs); \
void *plugin_get_category_##category(const char *name);
#define PLUGIN_FUNC1 (name, t1, p1)
Value:
void plugin_register_##name(void(*func)(t1 p1));        \
void plugin_call_##name(t1 p1);
#define PLUGIN_FUNC3 (name, t1, p1, t2, p2, t3, p3)
Value:
void plugin_register_##name(void(*func)(t1 p1,t2 p2,t3 p3));    \
void plugin_call_##name(t1 p1,t2 p2,t3 p3);
#define PLUGIN_FUNC4 (name, t1, p1, t2, p2, t3, p3, t4, p4)
Value:
void plugin_register_##name(void(*func)(t1 p1,t2 p2,t3 p3,t4 p4));      \
void plugin_call_##name(t1 p1,t2 p2,t3 p3,t4 p4);
#define plugin_init plugin_module_cat(module_,_init)
#define plugin_module_cat (pre, post) plugin_module_cat2(pre,MODULE,post)
#define plugin_module_cat2 (pre, mod, post) plugin_module_cat3(pre,mod,post)
#define plugin_module_cat3 (pre, mod, post) pre##mod##post
#define PLUGIN_PROTO (name, ...) void name(__VA_ARGS__)
Enumeration Type Documentation
enum plugin_category
All existing plugin categories.
Plugins are grouped into categories. Plugins within one category offer the same functionality (GUI, graphics, map etc.). Consequently the category determines the API offered by a plugin.
Enumerator
plugin_category_graphics
Category for plugins which implement a graphics backend.
plugin_category_gui
Category for plugins which implement a GUI frontend.
plugin_category_map
Category for plugins which implement a driver for providing/loading map data.
plugin_category_osd
Category for plugins which implement an OSD.
plugin_category_speech
Category for plugins which implement speech output.
plugin_category_vehicle
Category for plugins which supply position data (typically from a GPS receiver).
plugin_category_event
Category for plugins which implement/wrap an event subsystem.
plugin_category_font
Category for plugins which load fonts.
plugin_category_last
Dummy for last entry.
Function Documentation
void plugin_call_init (struct plugin * pl)
References plugin::init.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
void plugin_destroy (struct plugin * pl)
References g_free().
Referenced by plugins_destroy().
int plugin_get_active (struct plugin * pl)
References plugin::active.
Referenced by plugin_get_category(), and plugins_init().
void* plugin_get_category (enum plugin_category category, const char * category_name, const char * name)
References _GList::data, dbg, find_by_name(), g_ascii_strncasecmp(), g_free(), g_list_next, g_strjoin(), g_strrstr(), plugins::list, lvl_debug, plugin::name, NULL, pls, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
char* plugin_get_name (struct plugin * pl)
References plugin::name.
Referenced by plugin_new().
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References android_activity, android_find_class_global(), attr::callback, callback_cast, callback_new_attr_0, callback_new_attr_1, config_add_attr(), config_attr_iter_destroy(), config_attr_iter_new(), config_get_attr(), dbg, dbus_main_navit(), espeak_new(), event_android_new(), event_cocoa_new(), event_null_new(), event_opengl_new(), event_sdl_new(), event_win32_new(), font_freetype_new(), g_hash_table_new(), g_new0, g_str_equal(), g_str_hash(), gmap_new(), graphics_android_new(), graphics_cocoa_new(), graphics_gd_new(), graphics_gtk_drawing_area_new(), graphics_null_new(), graphics_opengl_new(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_win32_new(), gtk_argc, gtk_argv, gui_gtk_new(), gui_internal_new(), gui_qml_new(), gui_qt5_qml_new(), eval::iter, jnienv, LC_NUMERIC, lvl_debug, lvl_error, lvl_info, map_filter_new(), map_new_binfile(), map_new_csv(), map_new_garmin_img(), map_new_mg(), map_new_shapefile(), map_new_textfile(), map_route_occluded_new(), attr::navit, NULL, O_RDONLY, object_count, object_hash, object_hash_rev, object_path, open(), osd_auxmap_new(), osd_button_new(), osd_cmd_interface_new(), osd_compass_new(), osd_gps_status_new(), osd_image_new(), osd_j1850_new(), osd_marker_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_odometer_new(), osd_route_guard_new(), osd_scale_new(), osd_speed_cam_new(), osd_speed_warner_new(), osd_stopwatch_new(), osd_text_new(), osd_volume_new(), osso_navit(), pedestrian_navit(), pedestrian_navit_init(), qt5_espeak_new(), qt5_event_init(), read(), service_name, setlocale(), size, speech_android_new(), speech_dbus_new(), speech_iphone_new(), speechd_new(), attr::type, attr::u, vehicle_android_new_android(), vehicle_demo_new(), vehicle_file_new_file(), vehicle_gpsd_dbus_new(), vehicle_gpsd_new_gpsd(), vehicle_gypsy_new_gypsy(), vehicle_iphone_new(), vehicle_maemo_new_maemo(), vehicle_null_new_null(), vehicle_qt5_new_qt5(), vehicle_webos_new(), vehicle_wince_new(), win32_gui_new(), and win32_main_navit().
int plugin_load (struct plugin * pl)
References dbg, plugin::init, plugin::lazy, lvl_debug, lvl_error, and plugin::name.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
struct plugin* plugin_new (struct attr * parent, struct attr ** attrs)
References active, attr_search(), dbg, file_exists(), file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_get_count(), file_wordexp_new(), g_hash_table_insert(), g_hash_table_lookup(), g_list_append(), g_list_remove(), plugins::hash, i, plugins::list, lvl_debug, lvl_error, lvl_info, name, NULL, attr::num, pls, plugin_call_init(), plugin_get_name(), plugin_load(), plugin_new_from_path(), plugin_set_active(), plugin_set_lazy(), plugin_set_ondemand(), attr::plugins, attr::str, attr::u, and file_wordexp::we.
Referenced by add_plugin().
void plugin_set_active (struct plugin * pl, int active)
References active, and plugin::active.
Referenced by plugin_get_category(), plugin_new(), and plugins_init().
void plugin_set_lazy (struct plugin * pl, int lazy)
References plugin::lazy.
Referenced by plugin_new().
void plugin_unload (struct plugin * pl)
References NULL.
Referenced by plugins_destroy().
void plugins_destroy (struct plugins * pls)
References _GList::data, g_free(), g_hash_table_destroy(), g_list_free(), plugins::hash, plugins::list, plugin_destroy(), and plugin_unload().
void plugins_init (struct plugins * pls)
References _GList::data, dbg, g_list_next, plugins::list, lvl_error, plugin_call_init(), plugin_get_active(), plugin_load(), and plugin_set_active().
Referenced by maptool_init().
struct plugins* plugins_new (void)
References g_hash_table_new(), g_new0, g_str_equal(), g_str_hash(), plugins::hash, and pls.
Referenced by add_plugin().