navit: support/gettext_intl/plural-exp.h File Reference
plural-exp.h File Reference
Data Structures
struct expression
struct parse_args
Macros
#define internal_function
#define attribute_hidden
#define FREE_EXPRESSION free_plural_expression
#define PLURAL_PARSE parse_plural_expression
#define GERMANIC_PLURAL germanic_plural
#define EXTRACT_PLURAL_EXPRESSION extract_plural_expression
Functions
void FREE_EXPRESSION (struct expression *exp) internal_function
int PLURAL_PARSE (void *arg)
void EXTRACT_PLURAL_EXPRESSION (const char *nullentry, struct expression **pluralp, unsigned long int *npluralsp) internal_function
unsigned long int plural_eval (struct expression *pexp, unsigned long int n)
Variables
struct expression GERMANIC_PLURAL attribute_hidden
Macro Definition Documentation
#define attribute_hidden
#define EXTRACT_PLURAL_EXPRESSION extract_plural_expression
Referenced by _nl_load_domain().
#define FREE_EXPRESSION free_plural_expression
#define GERMANIC_PLURAL germanic_plural
#define internal_function
#define PLURAL_PARSE parse_plural_expression
Function Documentation
void EXTRACT_PLURAL_EXPRESSION (const char * nullentry, struct expression ** pluralp, unsigned long int * npluralsp)
References parse_args::cp, GERMANIC_PLURAL, INIT_GERMANIC_PLURAL, NULL, PLURAL_PARSE(), and parse_args::res.
void FREE_EXPRESSION (struct expression * exp)
References expression::args, expression::nargs, NULL, and expression::val.
Referenced by new_exp().
unsigned long int plural_eval (struct expression * pexp, unsigned long int n)
References expression::args, expression::nargs, expression::num, num, expression::operation, plural_eval(), SIGFPE, and expression::val.
Referenced by plural_eval(), and plural_lookup().
int PLURAL_PARSE (void * arg)
Referenced by EXTRACT_PLURAL_EXPRESSION().
Variable Documentation
struct expression GERMANIC_PLURAL attribute_hidden