navit: support/libpng/pngerror.c File Reference
pngerror.c File Reference
#include "png.h"
Macros
#define PNG_INTERNAL
#define isnonalpha(c) ((c) < 65 || (c) > 122 || ((c) > 90 && (c) < 97))
#define PNG_MAX_ERROR_TEXT 64
Functions
static void png_default_error PNGARG ((png_structp png_ptr, png_const_charp error_message))
static void png_default_warning PNGARG ((png_structp png_ptr, png_const_charp warning_message))
void PNGAPI png_error (png_structp png_ptr, png_const_charp error_message)
void PNGAPI png_warning (png_structp png_ptr, png_const_charp warning_message)
static void png_format_buffer (png_structp png_ptr, png_charp buffer, png_const_charp error_message)
void PNGAPI png_chunk_error (png_structp png_ptr, png_const_charp error_message)
void PNGAPI png_chunk_warning (png_structp png_ptr, png_const_charp warning_message)
static void png_default_error (png_structp png_ptr, png_const_charp error_message)
static void png_default_warning (png_structp png_ptr, png_const_charp warning_message)
void PNGAPI png_set_error_fn (png_structp png_ptr, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warning_fn)
png_voidp PNGAPI png_get_error_ptr (png_structp png_ptr)
void PNGAPI png_set_strip_error_numbers (png_structp png_ptr, png_uint_32 strip_mode)
Variables
static PNG_CONST char png_digit [16]
Macro Definition Documentation
#define isnonalpha (c) ((c) < 65 || (c) > 122 || ((c) > 90 && (c) < 97))
Referenced by png_format_buffer().
#define PNG_INTERNAL
#define PNG_MAX_ERROR_TEXT 64
Referenced by png_chunk_error(), png_chunk_warning(), and png_format_buffer().
Function Documentation
void PNGAPI png_chunk_error (png_structp png_ptr, png_const_charp error_message)
References NULL, png_error(), png_format_buffer(), and PNG_MAX_ERROR_TEXT.
Referenced by png_check_chunk_name(), png_crc_finish(), png_handle_PLTE(), and png_handle_unknown().
void PNGAPI png_chunk_warning (png_structp png_ptr, png_const_charp warning_message)
References NULL, png_format_buffer(), PNG_MAX_ERROR_TEXT, and png_warning().
Referenced by png_crc_finish(), and png_handle_PLTE().
static void png_default_error (png_structp png_ptr, png_const_charp error_message) static
References error_message, fprintf(), png_struct_def::jmpbuf, offset, PNG_ABORT, png_memcpy, png_sizeof, and PNG_STRING_NEWLINE.
Referenced by png_error().
static void png_default_warning (png_structp png_ptr, png_const_charp warning_message) static
References fprintf(), offset, PNG_STRING_NEWLINE, and warning_message.
Referenced by png_warning().
void PNGAPI png_error (png_structp png_ptr, png_const_charp error_message)
References error_message, i, NULL, offset, and png_default_error().
Referenced by png_chunk_error(), png_create_read_struct_2(), png_decompress_chunk(), png_default_read_data(), png_do_read_transformations(), png_get_IHDR(), png_get_uint_31(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_IHDR(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_zTXt(), png_malloc(), png_malloc_default(), png_memcpy_check(), png_memset_check(), png_read_data(), png_read_end(), png_read_finish_row(), png_read_image(), png_read_info(), png_read_init_2(), png_read_init_3(), png_read_png(), png_read_row(), png_read_start_row(), png_set_IHDR(), png_set_PLTE(), png_set_sig_bytes(), and png_set_text().
static void png_format_buffer (png_structp png_ptr, png_charp buffer, png_const_charp error_message) static
References c, isnonalpha, NULL, PNG_MAX_ERROR_TEXT, and png_memcpy.
Referenced by png_chunk_error(), and png_chunk_warning().
png_voidp PNGAPI png_get_error_ptr (png_structp png_ptr)
References NULL.
void PNGAPI png_set_error_fn (png_structp png_ptr, png_voidp error_ptr, png_error_ptr error_fn, png_error_ptr warning_fn)
References error_fn, error_ptr, NULL, and warning_fn.
Referenced by png_create_read_struct_2().
void PNGAPI png_set_strip_error_numbers (png_structp png_ptr, png_uint_32 strip_mode)
References NULL, and strip_mode.
void PNGAPI png_warning (png_structp png_ptr, png_const_charp warning_message)
References NULL, offset, and png_default_warning().
Referenced by png_check_cHRM_fixed(), png_chunk_warning(), png_create_read_struct_2(), png_data_freer(), png_decompress_chunk(), png_do_read_transformations(), png_get_IHDR(), png_handle_bKGD(), png_handle_cHRM(), png_handle_gAMA(), png_handle_hIST(), png_handle_iCCP(), png_handle_IEND(), png_handle_oFFs(), png_handle_pCAL(), png_handle_pHYs(), png_handle_PLTE(), png_handle_sBIT(), png_handle_sCAL(), png_handle_sPLT(), png_handle_sRGB(), png_handle_tEXt(), png_handle_tIME(), png_handle_tRNS(), png_handle_unknown(), png_handle_zTXt(), png_read_filter_row(), png_read_finish_row(), png_read_init_2(), png_read_init_3(), png_read_row(), png_read_update_info(), png_set_background(), png_set_crc_action(), png_set_gAMA(), png_set_gAMA_fixed(), png_set_hIST(), png_set_iCCP(), png_set_IHDR(), png_set_pCAL(), png_set_PLTE(), png_set_read_fn(), png_set_read_user_transform_fn(), png_set_rgb_to_gray_fixed(), png_set_sPLT(), png_set_text_2(), png_set_tRNS(), png_set_unknown_chunks(), png_set_user_transform_info(), and png_zalloc().
static void png_default_error PNGARG ((png_structp png_ptr, png_const_charp error_message)) static
static void png_default_warning PNGARG ((png_structp png_ptr, png_const_charp warning_message)) static
Variable Documentation
PNG_CONST char png_digit[16] static
Initial value:
= {
   '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'A', 'B', 'C', 'D', 'E', 'F'
}