navit: support/libpng/pngm2pnm.c File Reference
pngm2pnm.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "png.h"
Macros
#define BOOL unsigned char
#define TRUE (BOOL) 1
#define FALSE (BOOL) 0
#define PNG_DEBUG 0
Functions
int main (int argc, char *argv[])
void usage ()
BOOL png2pnm (FILE *png_file, FILE *pnm_file, FILE *alpha_file, BOOL raw, BOOL alpha)
Macro Definition Documentation
#define BOOL unsigned char
Referenced by main().
#define FALSE (BOOL) 0
Referenced by main(), and png2pnm().
#define PNG_DEBUG 0
#define TRUE (BOOL) 1
Referenced by main(), and png2pnm().
Function Documentation
int main (int argc, char * argv[])
References argc, BOOL, exit, FALSE, fprintf(), NULL, O_BINARY, png2pnm(), setmode(), TRUE, and usage().
BOOL png2pnm (FILE * png_file, FILE * pnm_file, FILE * alpha_file, BOOL raw, BOOL alpha)
References bit_depth, buf, png_struct_def::channels, color_type, exit, FALSE, file_gamma, fprintf(), height, i, info_ptr, L, long, NULL, png_check_sig(), PNG_COLOR_TYPE_GRAY, PNG_COLOR_TYPE_GRAY_ALPHA, PNG_COLOR_TYPE_PALETTE, PNG_COLOR_TYPE_RGB, PNG_COLOR_TYPE_RGB_ALPHA, png_create_info_struct(), png_create_read_struct(), png_destroy_read_struct(), png_get_gAMA(), png_get_IHDR(), png_get_rowbytes(), png_get_valid(), PNG_INFO_tRNS, png_init_io(), png_jmpbuf, PNG_LIBPNG_VER_STRING, png_read_end(), png_read_image(), png_read_info(), png_read_update_info(), png_set_expand(), png_set_gamma(), png_set_gray_to_rgb(), png_set_sig_bytes(), png_set_strip_16(), row, row_pointers, TRUE, and width.
Referenced by main().
void usage (void)
References fprintf().
Referenced by main().