navit: support/libpng/pngrio.c File Reference
pngrio.c File Reference
#include "png.h"
Macros
#define PNG_INTERNAL
Functions
void png_read_data (png_structp png_ptr, png_bytep data, png_size_t length)
void PNGAPI png_default_read_data (png_structp png_ptr, png_bytep data, png_size_t length)
void PNGAPI png_set_read_fn (png_structp png_ptr, png_voidp io_ptr, png_rw_ptr read_data_fn)
Macro Definition Documentation
#define PNG_INTERNAL
Function Documentation
void PNGAPI png_default_read_data (png_structp png_ptr, png_bytep data, png_size_t length)
References length, NULL, and png_error().
Referenced by png_set_read_fn().
void png_read_data (png_structp png_ptr, png_bytep data, png_size_t length)
References data, length, NULL, png_debug1, and png_error().
Referenced by png_crc_error(), png_crc_read(), png_read_chunk_header(), png_read_finish_row(), and png_read_info().
void PNGAPI png_set_read_fn (png_structp png_ptr, png_voidp io_ptr, png_rw_ptr read_data_fn)
References io_ptr, NULL, png_default_read_data(), png_warning(), and read_data_fn.
Referenced by png_create_read_struct_2(), and png_read_init_3().