navit: map/mg/poly.c File Reference
poly.c File Reference
#include <string.h>
#include "debug.h"
#include "mg.h"
Functions
static void poly_coord_rewind (void *priv_data)
static int poly_coord_get (void *priv_data, struct coord *c, int count)
static void poly_attr_rewind (void *priv_data)
static int poly_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static void poly_get_data (struct poly_priv *poly, unsigned char **p)
int poly_get (struct map_rect_priv *mr, struct poly_priv *poly, struct item *item)
int poly_get_byid (struct map_rect_priv *mr, struct poly_priv *poly, int id_hi, int id_lo, struct item *item)
Variables
static struct item_methods poly_meth
Function Documentation
static int poly_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References poly_priv::attr_next, poly_priv::name, attr::str, attr::type, and attr::u.
static void poly_attr_rewind (void * priv_data) static
References poly_priv::aidx.
static int poly_coord_get (void * priv_data, struct coord * c, int count) static
References get_u32_unal(), poly_priv::p, poly_priv::subpoly_next, coord::x, and coord::y.
static void poly_coord_rewind (void * priv_data) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References poly_priv::p, and poly_priv::subpoly_start.
int poly_get (struct map_rect_priv * mr, struct poly_priv * poly, struct item * item)
References poly_priv::attr_next, block_priv::b, map_rect_priv::b, file::begin, block_get_count(), block_priv::block_num, poly_priv::c, map_selection::c_rect, coord_rect_overlap(), poly_priv::count, poly_priv::count_sum, map_rect_priv::cur_sel, map_rect_priv::current_file, dbg, block_priv::end, map_rect_priv::file, item::id_hi, item::id_lo, L, coord_rect::lu, lvl_debug, lvl_error, map_selection_contains_item(), item::meth, poly_priv::name, map_selection::order, poly_priv::order, poly_priv::p, block_priv::p, block_priv::p_start, poly_get_data(), poly_meth, poly_priv::poly_next, poly_priv::poly_num, poly_priv::polys, item::priv_data, coord_rect::rl, poly_priv::subpoly_next, poly_priv::subpoly_num, poly_priv::subpoly_num_all, poly_priv::subpoly_start, item::type, poly_priv::type, map_selection::u, coord::x, and coord::y.
Referenced by map_rect_get_item_mg(), and poly_get_byid().
int poly_get_byid (struct map_rect_priv * mr, struct poly_priv * poly, int id_hi, int id_lo, struct item * item)
References map_rect_priv::b, block_get_byindex(), map_rect_priv::current_file, map_priv::file, map_rect_priv::m, and poly_get().
Referenced by map_rect_get_item_byid_mg().
static void poly_get_data (struct poly_priv * poly, unsigned char ** p) static
References poly_priv::c, poly_priv::count, poly_priv::count_sum, get_u32_unal(), int, poly_priv::name, poly_priv::order, poly_priv::polys, poly_priv::type, coord::x, and coord::y.
Referenced by poly_get().
Variable Documentation
struct item_methods poly_meth static
Initial value:
= {
        poly_coord_rewind,
        poly_coord_get,
        poly_attr_rewind,
        poly_attr_get,
}
Referenced by poly_get().