navit: popup.c File Reference
popup.c File Reference
#include "config.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <glib.h>
#include "popup.h"
#include "debug.h"
#include "navit.h"
#include "coord.h"
#include "gui.h"
#include "menu.h"
#include "point.h"
#include "transform.h"
#include "projection.h"
#include "item.h"
#include "map.h"
#include "graphics.h"
#include "callback.h"
#include "route.h"
#include "navit_nls.h"
#include "bookmarks.h"
Macros
#define popup_printf(menu, type,...) popup_printf_cb(menu, type, NULL, __VA_ARGS__)
Functions
static void popup_traffic_distortion (struct item *item, char *attr)
static void popup_traffic_distortion_blocked (struct item *item)
static void popup_traffic_distortion_speed (struct item *item, int maxspeed)
static void popup_traffic_distortion_delay (struct item *item, int delay)
static void popup_set_destination (struct navit *nav, struct pcoord *pc)
void popup_set_visitbefore (struct navit *nav, struct pcoord *pc, int visitbefore)
static void popup_set_bookmark (struct navit *nav, struct pcoord *pc)
static void popup_set_position (struct navit *nav, struct pcoord *pc)
static void * popup_printf_cb (void *menu, enum menu_type type, struct callback *cb, const char *fmt,...)
static void popup_show_visitbefore (struct navit *nav, struct pcoord *pc, void *menu)
static void popup_show_attr_val (struct map *map, void *menu, struct attr *attr)
static void popup_show_attrs (struct map *map, void *menu, struct item *item)
static void popup_item_dump (struct item *item)
static void popup_show_item (struct navit *nav, void *popup, struct displayitem *di)
static void popup_display (struct navit *nav, void *popup, struct point *p)
void popup (struct navit *nav, int button, struct point *p)
Variables
void * vehicle
static struct pcoord c
Macro Definition Documentation
#define popup_printf (menu, type, ...) popup_printf_cb(menu, type, NULL, __VA_ARGS__)
Referenced by popup(), popup_show_attr_val(), popup_show_item(), and popup_show_visitbefore().
Function Documentation
void popup (struct navit * nav, int button, struct point * p)
References _, c, callback_cast, callback_new_2, dbg, DEGREES_MINUTES_SECONDS, gui_popup_new(), coord_geo::lat, coord_geo::lng, lvl_debug, menu_popup(), menu_type_menu, menu_type_submenu, navit_get_gui(), navit_get_trans(), popup(), popup_display(), popup_printf, popup_printf_cb(), popup_set_bookmark(), popup_set_destination(), popup_set_position(), popup_show_visitbefore(), pcoord::pro, transform_get_projection(), transform_reverse(), transform_to_geo(), point::x, coord::x, pcoord::x, point::y, coord::y, and pcoord::y.
Referenced by navit_handle_button(), navit_popup(), and popup().
static void popup_display (struct navit * nav, void * popup, struct point * p) static
References display(), graphics_displayitem_within_dist(), graphics_displaylist_close(), graphics_displaylist_next(), graphics_displaylist_open(), navit_get_displaylist(), and popup_show_item().
Referenced by popup().
static void popup_item_dump (struct item * item) static
References dbg, item::id_hi, item::id_lo, item_dump_filedesc(), lvl_debug, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), and NULL.
Referenced by popup_show_item().
static void* popup_printf_cb (void * menu, enum menu_type type, struct callback * cb, const char * fmt, ...) static
References dbg, g_free(), g_malloc(), g_strdup_vprintf(), gchar, lvl_debug, and menu_add().
Referenced by popup(), popup_show_item(), and popup_show_visitbefore().
static void popup_set_bookmark (struct navit * nav, struct pcoord * pc) static
References attr::bookmarks, bookmarks_add_bookmark(), DEGREES_MINUTES_SECONDS, gui_add_bookmark(), coord_geo::lat, coord_geo::lng, navit_get_attr(), navit_get_gui(), NULL, pcoord::pro, sprintf(), transform_to_geo(), attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by popup(), and popup_show_item().
static void popup_set_destination (struct navit * nav, struct pcoord * pc) static
References DEGREES_MINUTES_SECONDS, coord_geo::lat, coord_geo::lng, navit_get_trans(), navit_set_destination(), sprintf(), transform_get_projection(), transform_to_geo(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by popup(), and popup_show_item().
static void popup_set_position (struct navit * nav, struct pcoord * pc) static
References dbg, lvl_debug, and navit_set_position().
Referenced by popup(), and popup_show_item().
void popup_set_visitbefore (struct navit * nav, struct pcoord * pc, int visitbefore)
References _, g_alloca, i, navit_add_destination_description(), navit_get_destination_count(), navit_get_destinations(), navit_set_destinations(), and sprintf().
Referenced by button_visit_clicked(), and popup_show_visitbefore().
static void popup_show_attr_val (struct map * map, void * menu, struct attr * attr) static
References attr_to_name(), attr_to_text(), g_free(), menu_type_menu, popup_printf, and attr::type.
Referenced by popup_show_attrs().
static void popup_show_attrs (struct map * map, void * menu, struct item * item) static
References item_attr_get(), and popup_show_attr_val().
Referenced by popup_show_item().
static void popup_show_item (struct navit * nav, void * popup, struct displayitem * di) static
References _, c, callback_cast, callback_new_1, callback_new_2, dbg, dbg_assert, g_new, graphics_displayitem_get_coord_count(), graphics_displayitem_get_item(), graphics_displayitem_get_label(), i, item::id_hi, item::id_lo, item, item_coord_get(), item_get_default_flags(), item_to_name(), label, lvl_debug, item::map, map_get_attr(), map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), menu_type_menu, menu_type_submenu, navit_get_trans(), NULL, popup_item_dump(), popup_printf, popup_printf_cb(), popup_set_bookmark(), popup_set_destination(), popup_set_position(), popup_show_attrs(), popup_traffic_distortion_blocked(), popup_traffic_distortion_delay(), popup_traffic_distortion_speed(), pcoord::pro, attr::str, transform_get_projection(), item::type, attr::u, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by popup_display().
static void popup_show_visitbefore (struct navit * nav, struct pcoord * pc, void * menu) static
References _, callback_cast, callback_new_3, i, menu_type_menu, menu_type_submenu, navit_get_destination_count(), popup_printf, popup_printf_cb(), popup_set_visitbefore(), and sprintf().
Referenced by popup().
static void popup_traffic_distortion (struct item * item, char * attr) static
Navit, a modular navigation system. Copyright (C) 2005-2008, 2010 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, fprintf(), g_free(), g_strjoin(), item::id_hi, item::id_lo, item_coord_get(), lvl_error, item::map, map_rect_get_item_byid(), map_rect_new(), navit_get_user_data_directory(), NULL, TRUE, coord::x, and coord::y.
Referenced by popup_traffic_distortion_blocked(), popup_traffic_distortion_delay(), and popup_traffic_distortion_speed().
static void popup_traffic_distortion_blocked (struct item * item) static
References dbg, lvl_debug, and popup_traffic_distortion().
Referenced by popup_show_item().
static void popup_traffic_distortion_delay (struct item * item, int delay) static
References popup_traffic_distortion(), and sprintf().
Referenced by popup_show_item().
static void popup_traffic_distortion_speed (struct item * item, int maxspeed) static
References popup_traffic_distortion(), and sprintf().
Referenced by popup_show_item().
Variable Documentation
struct pcoord c static
Referenced by add_node_to_hash(), AppendPhonemes(), assafe_lltoa(), attrcopy_utf8(), bbox(), binfile_coord_get(), binmap_get_estimated_boundaries(), binmap_search_street_by_place(), bookmarks_emit_dbus_signal(), button_bookmark(), button_destination(), button_map(), ch_generate_ddsg(), cJSON_AddItemToArray(), cJSON_DetachItemFromArray(), cJSON_DetachItemFromObject(), cJSON_GetArrayItem(), cJSON_GetArraySize(), cJSON_GetObjectItem(), cJSON_Parse(), cJSON_ReplaceItemInArray(), cJSON_ReplaceItemInObject(), coastline_processor_process(), compile_dictrules(), compile_line(), compile_rule(), coord_hash(), coord_new(), coord_parse(), copy_rule_string(), createParsedata(), DecodePhonemes(), DecodeRule(), displayitem_draw(), org.navitproject.navit.NavitMapDownloader::download_osm_map(), draw_circle(), dump_hex(), dump_hex_r(), EmbeddedCommand(), EncodePhonemes(), espeak_Char(), espeak_Key(), espeak_SetParameter(), espeak_SetPunctuationList(), espeak_SetVoiceByName(), espeak_SetVoiceByProperties(), ezxml_decode(), ezxml_internal_dtd(), ezxml_set_attr(), ezxml_str2utf8(), g2n_conv_load(), g_ascii_strtod(), g_ascii_tolower(), g_ascii_toupper(), g_parse_long_long(), g_printf_string_upper_bound(), g_strcanon(), g_strdelimit(), g_strlcpy(), g_strreverse(), g_utf16_to_ucs4(), g_utf16_to_utf8(), g_utf8_get_char(), gc_set_foreground(), get_charset_aliases(), get_uval(), GetC(), GetC_get(), GetC_unget(), getopt(), gui_gtk_add_bookmark(), gui_internal_cmd2_route_height_profile(), gui_internal_cmd_pois(), gui_internal_cmd_pois_selector(), gui_internal_cmd_results_to_map(), gui_internal_onclick(), HashDictionary(), org.navitproject.navit.NavitMapDownloader::initConnection(), InitGroups(), item_bin_copy_coord(), item_bin_dump(), item_bin_sort_file(), item_bin_write_match(), itembin_warning(), latin1_tolower(), layout_get_cursor(), load_tilesdir(), LookupDictList(), LookupPhonemeString(), main(), map_collect_data_osm_o5m(), map_resolve_coords_and_split_at_intersections(), map_route_occluded_check_buildings(), map_search_mg_convert_special(), map_selection_contains_item_rect(), navigation_itm_ways_clear(), navigation_way_get_max_delta(), navigation_way_init(), navit_add_former_destinations_from_file(), navit_get_attr(), navit_projection_set(), navit_set_center(), navit_set_cursors(), navit_set_destination(), navit_zoom_to_route(), ocean_tile(), osd_route_guard_init(), osm_process_towns(), parse_option(), PlayWave(), png_64bit_product(), png_do_gamma(), png_do_unshift(), png_format_buffer(), png_read_filter_row(), popup(), popup_show_item(), PRINTF_PARSE(), process_boundaries_finish(), process_triangles(), ProcessSsmlTag(), QNavitGeoReceiver::QNavitGeoReceiver(), Read4Bytes(), read_former_destination_map_as_list(), relations_process(), resolve_ways(), route_find_nearest_street(), route_graph_update(), route_path_add_item_from_graph(), route_path_destroy(), route_process_street_graph(), route_process_traffic_distortion(), route_set_position_from_tracking(), search_fix_spaces(), search_house_number_coordinate(), set_attr_do(), SetLetterBits(), SetLetterVowel(), SetSpellingStress(), spawn_xkbd(), street_get_data(), strncmp_len(), tile_collector_process_tile(), tile_sibling_edges(), tracking_map_item_attr_get(), transform_correct_projection(), transform_distance_garmin(), transform_project_onto_view_plane(), transform_rotate(), transform_set_center(), transform_setup_source_rect(), transform_shift_by_center_and_scale(), transform_z_clip(), TranslateClause(), TranslateNumber_1(), TranslateRoman(), TranslateRules(), TransposeAlphabet(), UngetC(), Unpronouncable(), Unpronouncable_en(), utf8_nbytes(), utf8_out(), vehicle_demo_timer(), vehicle_webos_bt_gap_callback(), Wavegen(), within_dist_polygon(), write_former_destinations(), WriteMnemonic(), xpointer_test(), and xpointer_xpointer_match().
void* vehicle
Referenced by gui_internal_is_active_vehicle(), and request_vehicle_set_attr().