navit: popup.h File Reference
popup.h File Reference
Functions
void popup (struct navit *nav, int button, struct point *p)
void popup_set_visitbefore (struct navit *nav, struct pcoord *pc, int visitbefore)
Function Documentation
popup()
void popup (struct navit * nav, int button, struct point * p)
References _, c, callback_cast, callback_new_2, dbg, DEGREES_MINUTES_SECONDS, gui_popup_new(), coord_geo::lat, coord_geo::lng, lvl_debug, menu_popup(), menu_type_menu, menu_type_submenu, nav, navit_get_gui(), navit_get_trans(), p, popup(), popup_display(), popup_printf, popup_printf_cb(), popup_set_bookmark(), popup_set_destination(), popup_set_position(), popup_show_visitbefore(), pcoord::pro, transform_get_projection(), transform_reverse(), transform_to_geo(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by gui_gtk_ui_new(), navit_handle_button(), navit_popup(), popup(), popup_display(), and popup_show_item().
popup_set_visitbefore()
void popup_set_visitbefore (struct navit * nav, struct pcoord * pc, int visitbefore)
References _, nav, navit_add_destination_description(), navit_get_destination_count(), navit_get_destinations(), and navit_set_destinations().
Referenced by button_visit_clicked(), and popup_show_visitbefore().