navit: support/gettext_intl/printf.c File Reference
printf.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "printf-args.c"
#include "printf-parse.c"
#include "vasnprintf.c"
Macros
#define DLL_EXPORTED
#define STATIC static
#define vasnprintf libintl_vasnprintf
Functions
char * alloca ()
DLL_EXPORTED int libintl_vfprintf (FILE *stream, const char *format, va_list args)
DLL_EXPORTED int libintl_fprintf (FILE *stream, const char *format,...)
DLL_EXPORTED int libintl_vprintf (const char *format, va_list args)
DLL_EXPORTED int libintl_printf (const char *format,...)
DLL_EXPORTED int libintl_vsprintf (char *resultbuf, const char *format, va_list args)
DLL_EXPORTED int libintl_sprintf (char *resultbuf, const char *format,...)
Macro Definition Documentation
#define DLL_EXPORTED
#define STATIC static
#define vasnprintf libintl_vasnprintf
Function Documentation
char* alloca ()
DLL_EXPORTED int libintl_fprintf (FILE * stream, const char * format, ...)
References libintl_vfprintf().
DLL_EXPORTED int libintl_printf (const char * format, ...)
References libintl_vprintf().
DLL_EXPORTED int libintl_sprintf (char * resultbuf, const char * format, ...)
References libintl_vsprintf().
DLL_EXPORTED int libintl_vfprintf (FILE * stream, const char * format, va_list args)
References length, NULL, and vfprintf().
Referenced by libintl_fprintf(), and libintl_vprintf().
DLL_EXPORTED int libintl_vprintf (const char * format, va_list args)
References libintl_vfprintf().
Referenced by libintl_printf().
DLL_EXPORTED int libintl_vsprintf (char * resultbuf, const char * format, va_list args)
References length, NULL, and vsprintf().
Referenced by libintl_sprintf().