navit: profile_option.c File Reference
profile_option.c File Reference
#include <glib.h>
#include "item.h"
#include "debug.h"
#include "xmlconfig.h"
Data Structures
struct profile_option
Functions
static struct profile_option * profile_option_new (struct attr *parent, struct attr **attrs)
static void profile_option_destroy (struct profile_option *po)
Variables
struct object_func profile_option_func
Function Documentation
static void profile_option_destroy (struct profile_option * po) static
References attr_list_free(), and g_free().
static struct profile_option* profile_option_new (struct attr * parent, struct attr ** attrs) static
References attr_list_dup(), dbg, g_new0, lvl_debug, navit_object_ref(), and profile_option_func.
Variable Documentation
struct object_func profile_option_func
Initial value:
= {
        attr_profile_option,
        (object_func_new)profile_option_new,
        (object_func_get_attr)navit_object_get_attr,
        (object_func_iter_new)navit_object_attr_iter_new,
        (object_func_iter_destroy)navit_object_attr_iter_destroy,
        (object_func_set_attr)navit_object_set_attr,
        (object_func_add_attr)navit_object_add_attr,
        (object_func_remove_attr)navit_object_remove_attr,
        (object_func_init)NULL,
        (object_func_destroy)profile_option_destroy,
        (object_func_dup)NULL,
        (object_func_ref)navit_object_ref,
        (object_func_unref)navit_object_unref,
}
Referenced by object_func_lookup(), and profile_option_new().