navit: projection.h File Reference
projection.h File Reference
Enumerations
enum projection {
projection_none, projection_mg, projection_garmin, projection_screen,
projection_utm
}
enum map_datum { map_datum_none, map_datum_wgs84, map_datum_dhdn }
Functions
enum projection projection_from_name (const char *name, struct coord *offset)
char * projection_to_name (enum projection proj)
Enumeration Type Documentation
enum map_datum
Enumerator
map_datum_none
map_datum_wgs84
map_datum_dhdn
enum projection
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
You should have received a copy of the GNU Library General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Enumerator
projection_none
No projection or unknown projection
projection_mg
Mercator projection
projection_garmin
Garmin projection
projection_screen
Screen projection
projection_utm
UTM projection
Function Documentation
enum projection projection_from_name (const char * name, struct coord * utm_offset)
Look up a projection by name.
Parameters
name name of projection to look up (values from projection_names, and UTM projections) Only for UTM projections: Used to return the offset for the UTM projection
Returns
projection, or projection_none if no projection could be determined
References dbg, i, lvl_debug, lvl_error, projection_names, projection_none, projection_utm, utmref_letter(), coord::x, and coord::y.
Referenced by coord_parse(), and map_new_shapefile().
char* projection_to_name (enum projection proj)
References i, projection_name::name, NULL, and projection_names.
Referenced by bookmarks_store_bookmarks_to_file(), coord_print(), and write_former_destinations().