navit: maptool/google/protobuf-c/protobuf-c.c File Reference
protobuf-c.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "protobuf-c.h"
Data Structures
struct _ScannedMember
Macros
#define PRINT_UNPACK_ERRORS 1
#define MAX_UINT64_ENCODED_SIZE 10
#define TMPALLOC(allocator, size) ((allocator)->tmp_alloc ((allocator)->allocator_data, (size)))
#define FREE(allocator, ptr) do { if ((ptr) != NULL) ((allocator)->free ((allocator)->allocator_data, (ptr))); } while(0)
#define UNALIGNED_ALLOC(allocator, size) ALLOC (allocator, size) /* placeholder */
#define STRUCT_MEMBER_P(struct_p, struct_offset) ((void *) ((uint8_t*) (struct_p) + (struct_offset)))
#define STRUCT_MEMBER(member_type, struct_p, struct_offset) (*(member_type*) STRUCT_MEMBER_P ((struct_p), (struct_offset)))
#define STRUCT_MEMBER_PTR(member_type, struct_p, struct_offset) ((member_type*) STRUCT_MEMBER_P ((struct_p), (struct_offset)))
#define TRUE 1
#define FALSE 0
#define DO_ALLOC(dst, allocator, size, fail_code)
#define DO_UNALIGNED_ALLOC DO_ALLOC /* placeholder */
#define ASSERT_IS_ENUM_DESCRIPTOR(desc) assert((desc)->magic == PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC)
#define ASSERT_IS_MESSAGE_DESCRIPTOR(desc) assert((desc)->magic == PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC)
#define ASSERT_IS_MESSAGE(message) ASSERT_IS_MESSAGE_DESCRIPTOR((message)->descriptor)
#define ASSERT_IS_SERVICE_DESCRIPTOR(desc) assert((desc)->magic == PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC)
#define UNPACK_ERROR(args) do { printf args;printf("\n"); }while(0)
#define BOUND_SIZEOF_SCANNED_MEMBER_LOG2 5
#define FIRST_SCANNED_MEMBER_SLAB_SIZE_LOG2 4
#define MAX_SCANNED_MEMBER_SLAB
#define CLEAR_REMAINING_N_PTRS()
Typedefs
typedef struct _ScannedMember ScannedMember
typedef void(* GenericHandler)(void *service, const ProtobufCMessage *input, ProtobufCClosure closure, void *closure_data)
Functions
static void alloc_failed_warning (unsigned size, const char *filename, unsigned line)
static void protobuf_c_out_of_memory_default (void)
static void * system_alloc (void *allocator_data, size_t size)
static void system_free (void *allocator_data, void *data)
void protobuf_c_buffer_simple_append (ProtobufCBuffer *buffer, size_t len, const uint8_t *data)
static size_t get_tag_size (unsigned number)
static size_t uint32_size (uint32_t v)
static size_t int32_size (int32_t v)
static uint32_t zigzag32 (int32_t v)
static size_t sint32_size (int32_t v)
static size_t uint64_size (uint64_t v)
static uint64_t zigzag64 (int64_t v)
static size_t sint64_size (int64_t v)
static size_t required_field_get_packed_size (const ProtobufCFieldDescriptor *field, const void *member)
static size_t optional_field_get_packed_size (const ProtobufCFieldDescriptor *field, const protobuf_c_boolean *has, const void *member)
static size_t repeated_field_get_packed_size (const ProtobufCFieldDescriptor *field, size_t count, const void *member)
static size_t unknown_field_get_packed_size (const ProtobufCMessageUnknownField *field)
size_t protobuf_c_message_get_packed_size (const ProtobufCMessage *message)
static size_t uint32_pack (uint32_t value, uint8_t *out)
static size_t int32_pack (int32_t value, uint8_t *out)
static size_t sint32_pack (int32_t value, uint8_t *out)
static size_t uint64_pack (uint64_t value, uint8_t *out)
static size_t sint64_pack (int64_t value, uint8_t *out)
static size_t fixed32_pack (uint32_t value, uint8_t *out)
static size_t fixed64_pack (uint64_t value, uint8_t *out)
static size_t boolean_pack (protobuf_c_boolean value, uint8_t *out)
static size_t string_pack (const char *str, uint8_t *out)
static size_t binary_data_pack (const ProtobufCBinaryData *bd, uint8_t *out)
static size_t prefixed_message_pack (const ProtobufCMessage *message, uint8_t *out)
static size_t tag_pack (uint32_t id, uint8_t *out)
static size_t required_field_pack (const ProtobufCFieldDescriptor *field, const void *member, uint8_t *out)
static size_t optional_field_pack (const ProtobufCFieldDescriptor *field, const protobuf_c_boolean *has, const void *member, uint8_t *out)
static size_t sizeof_elt_in_repeated_array (ProtobufCType type)
static void copy_to_little_endian_32 (void *out, const void *in, unsigned N)
static void copy_to_little_endian_64 (void *out, const void *in, unsigned N)
static unsigned get_type_min_size (ProtobufCType type)
static size_t repeated_field_pack (const ProtobufCFieldDescriptor *field, size_t count, const void *member, uint8_t *out)
static size_t unknown_field_pack (const ProtobufCMessageUnknownField *field, uint8_t *out)
size_t protobuf_c_message_pack (const ProtobufCMessage *message, uint8_t *out)
static size_t required_field_pack_to_buffer (const ProtobufCFieldDescriptor *field, const void *member, ProtobufCBuffer *buffer)
static size_t optional_field_pack_to_buffer (const ProtobufCFieldDescriptor *field, const protobuf_c_boolean *has, const void *member, ProtobufCBuffer *buffer)
static size_t get_packed_payload_length (const ProtobufCFieldDescriptor *field, unsigned count, const void *array)
static size_t pack_buffer_packed_payload (const ProtobufCFieldDescriptor *field, unsigned count, const void *array, ProtobufCBuffer *buffer)
static size_t repeated_field_pack_to_buffer (const ProtobufCFieldDescriptor *field, unsigned count, const void *member, ProtobufCBuffer *buffer)
static size_t unknown_field_pack_to_buffer (const ProtobufCMessageUnknownField *field, ProtobufCBuffer *buffer)
size_t protobuf_c_message_pack_to_buffer (const ProtobufCMessage *message, ProtobufCBuffer *buffer)
static int int_range_lookup (unsigned n_ranges, const ProtobufCIntRange *ranges, int value)
static size_t parse_tag_and_wiretype (size_t len, const uint8_t *data, uint32_t *tag_out, ProtobufCWireType *wiretype_out)
static uint32_t scan_length_prefixed_data (size_t len, const uint8_t *data, size_t *prefix_len_out)
static size_t max_b128_numbers (size_t len, const uint8_t *data)
static protobuf_c_boolean count_packed_elements (ProtobufCType type, size_t len, const uint8_t *data, size_t *count_out)
static uint32_t parse_uint32 (unsigned len, const uint8_t *data)
static uint32_t parse_int32 (unsigned len, const uint8_t *data)
static int32_t unzigzag32 (uint32_t v)
static uint32_t parse_fixed_uint32 (const uint8_t *data)
static uint64_t parse_uint64 (unsigned len, const uint8_t *data)
static int64_t unzigzag64 (uint64_t v)
static uint64_t parse_fixed_uint64 (const uint8_t *data)
static protobuf_c_boolean parse_boolean (unsigned len, const uint8_t *data)
static protobuf_c_boolean parse_required_member (ScannedMember *scanned_member, void *member, ProtobufCAllocator *allocator, protobuf_c_boolean maybe_clear)
static protobuf_c_boolean parse_optional_member (ScannedMember *scanned_member, void *member, ProtobufCMessage *message, ProtobufCAllocator *allocator)
static protobuf_c_boolean parse_repeated_member (ScannedMember *scanned_member, void *member, ProtobufCMessage *message, ProtobufCAllocator *allocator)
static unsigned scan_varint (unsigned len, const uint8_t *data)
static protobuf_c_boolean parse_packed_repeated_member (ScannedMember *scanned_member, void *member, ProtobufCMessage *message)
static protobuf_c_boolean parse_member (ScannedMember *scanned_member, ProtobufCMessage *message, ProtobufCAllocator *allocator)
static void protobuf_c_message_init_generic (const ProtobufCMessageDescriptor *desc, ProtobufCMessage *message)
ProtobufCMessage * protobuf_c_message_unpack (const ProtobufCMessageDescriptor *desc, ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void protobuf_c_message_free_unpacked (ProtobufCMessage *message, ProtobufCAllocator *allocator)
void protobuf_c_service_invoke_internal (ProtobufCService *service, unsigned method_index, const ProtobufCMessage *input, ProtobufCClosure closure, void *closure_data)
void protobuf_c_service_generated_init (ProtobufCService *service, const ProtobufCServiceDescriptor *descriptor, ProtobufCServiceDestroy destroy)
void protobuf_c_service_destroy (ProtobufCService *service)
const ProtobufCEnumValue * protobuf_c_enum_descriptor_get_value_by_name (const ProtobufCEnumDescriptor *desc, const char *name)
const ProtobufCEnumValue * protobuf_c_enum_descriptor_get_value (const ProtobufCEnumDescriptor *desc, int value)
const ProtobufCFieldDescriptor * protobuf_c_message_descriptor_get_field_by_name (const ProtobufCMessageDescriptor *desc, const char *name)
const ProtobufCFieldDescriptor * protobuf_c_message_descriptor_get_field (const ProtobufCMessageDescriptor *desc, unsigned value)
const ProtobufCMethodDescriptor * protobuf_c_service_descriptor_get_method_by_name (const ProtobufCServiceDescriptor *desc, const char *name)
Variables
void(* protobuf_c_out_of_memory)(void) = protobuf_c_out_of_memory_default
ProtobufCAllocator protobuf_c_default_allocator
ProtobufCAllocator protobuf_c_system_allocator
Macro Definition Documentation
#define ASSERT_IS_ENUM_DESCRIPTOR (desc) assert((desc)->magic == PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC)
#define ASSERT_IS_MESSAGE (message) ASSERT_IS_MESSAGE_DESCRIPTOR((message)->descriptor)
Referenced by protobuf_c_message_free_unpacked(), protobuf_c_message_get_packed_size(), protobuf_c_message_pack(), and protobuf_c_message_pack_to_buffer().
#define ASSERT_IS_MESSAGE_DESCRIPTOR (desc) assert((desc)->magic == PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC)
Referenced by protobuf_c_message_unpack().
#define ASSERT_IS_SERVICE_DESCRIPTOR (desc) assert((desc)->magic == PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC)
Referenced by protobuf_c_service_generated_init().
#define BOUND_SIZEOF_SCANNED_MEMBER_LOG2 5
#define CLEAR_REMAINING_N_PTRS ()
Value:
for(f++;f < desc->n_fields; f++)                                \
              {                                                             \
                field = desc->fields + f;                                   \
                if (field->label == PROTOBUF_C_LABEL_REPEATED)              \
                  STRUCT_MEMBER (size_t, rv, field->quantifier_offset) = 0; \
              }
Referenced by protobuf_c_message_unpack().
#define DO_ALLOC (dst, allocator, size, fail_code)
Value:
{ size_t da__allocation_size = (size);                                      \
  if (da__allocation_size == 0)                                             \
    dst = NULL;                                                             \
  else if ((dst=((allocator)->alloc ((allocator)->allocator_data,           \
                                     da__allocation_size))) == NULL)        \
    {                                                                       \
      alloc_failed_warning (da__allocation_size, __FILE__, __LINE__);       \
      fail_code;                                                            \
    }                                                                       \
}
Referenced by parse_required_member(), protobuf_c_buffer_simple_append(), and protobuf_c_message_unpack().
#define DO_UNALIGNED_ALLOC DO_ALLOC /* placeholder */
Referenced by parse_member().
#define FALSE 0
Referenced by add_menu(), bookmarks_copy_bookmark(), bookmarks_cut_bookmark(), bookmarks_delete_bookmark(), bookmarks_paste_bookmark(), bookmarks_rename_bookmark(), bookmarks_store_bookmarks_to_file(), button_press(), button_release(), CeEnableBacklight(), changed(), config_load(), coord_equal(), count_packed_elements(), destination_address(), destination_equal(), draw_drag(), draw_mode(), event_glib_call_timeout_single(), expose(), fullscreen(), g_atomic_int_compare_and_exchange(), g_atomic_pointer_compare_and_exchange(), g_hash_table_foreach_steal(), g_hash_table_insert(), g_hash_table_iter_init(), g_hash_table_iter_next(), g_hash_table_iter_steal(), g_hash_table_lookup_extended(), g_hash_table_remove_internal(), g_hash_table_steal(), g_hash_table_steal_all(), g_mem_profile(), g_mutex_lock_a(), g_parse_long_long(), g_utf8_validate(), graphics_sdl_idle(), gtk_gui_poi(), gui_gtk_add_bookmark(), gui_gtk_add_menu(), gui_gtk_add_radio_menu(), gui_gtk_add_toggle_menu(), gui_gtk_datawindow_delete(), gui_gtk_new(), gui_gtk_statusbar_new(), gui_gtk_ui_new(), gui_internal_cmd2_route_height_profile(), init_lv_columns(), initBth(), initialise(), item_hash_equal(), keypress(), line_intersection(), LoadMbrolaTable(), message_handler(), motion_notify(), navigation_update_done(), navit_cmd_switch_layout_day_night(), navit_former_destinations_active(), navit_init(), navit_layout_switch(), navit_window_roadbook_update(), osd_odometer_new(), osso_cb_hw_state_idle(), parse_file(), parse_packed_repeated_member(), parse_repeated_member(), pngdecode(), profile_print_locked(), profiler_calloc(), profiler_free(), profiler_try_malloc(), profiler_try_realloc(), read_former_destinations_from_file(), register_destination_window(), scroll(), search_item_hash_equal(), smc_tree_lookup(), smc_tree_remove(), statusbar_route_update(), treeview_poi_reload(), vehicle_file_enable_watch_timer(), vehicle_gpsd_try_open(), vehicle_gypsy_course_changed(), vehicle_gypsy_position_changed(), vehicle_gypsy_try_open(), win32_gui_new(), win32_gui_popup_new(), and xpmdecode().
#define FIRST_SCANNED_MEMBER_SLAB_SIZE_LOG2 4
Referenced by protobuf_c_message_unpack().
#define FREE (allocator, ptr) do { if ((ptr) != NULL) ((allocator)->free ((allocator)->allocator_data, (ptr))); } while(0)
Referenced by parse_required_member(), protobuf_c_buffer_simple_append(), protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
#define MAX_SCANNED_MEMBER_SLAB
Value:
(sizeof(void*)*8 - 1                                   \
   - BOUND_SIZEOF_SCANNED_MEMBER_LOG2                    \
   - FIRST_SCANNED_MEMBER_SLAB_SIZE_LOG2)
Referenced by protobuf_c_message_unpack().
#define MAX_UINT64_ENCODED_SIZE 10
Referenced by repeated_field_pack_to_buffer(), required_field_pack_to_buffer(), and unknown_field_pack_to_buffer().
#define PRINT_UNPACK_ERRORS 1
#define STRUCT_MEMBER (member_type, struct_p, struct_offset) (*(member_type*) STRUCT_MEMBER_P ((struct_p), (struct_offset)))
Referenced by parse_optional_member(), protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
#define STRUCT_MEMBER_P (struct_p, struct_offset) ((void *) ((uint8_t*) (struct_p) + (struct_offset)))
Referenced by protobuf_c_message_init_generic().
#define STRUCT_MEMBER_PTR (member_type, struct_p, struct_offset) ((member_type*) STRUCT_MEMBER_P ((struct_p), (struct_offset)))
Referenced by parse_packed_repeated_member(), parse_repeated_member(), and protobuf_c_message_unpack().
#define TMPALLOC (allocator, size) ((allocator)->tmp_alloc ((allocator)->allocator_data, (size)))
Referenced by protobuf_c_message_unpack().
#define TRUE 1
Referenced by bookmarks_add_bookmark(), bookmarks_copy_bookmark(), bookmarks_new(), CeEnableBacklight(), changed(), configure(), coord_equal(), count_packed_elements(), create_destination_window(), CreateWin32Window(), delete(), destination_address(), destination_equal(), draw_drag(), draw_mode(), draw_text(), event_glib_call_idle(), event_glib_call_timeout_multi(), event_glib_call_watch(), event_glib_main_loop_run(), font_freetype_text_new(), g_allocator_new(), g_atomic_int_compare_and_exchange(), g_atomic_pointer_compare_and_exchange(), g_hash_table_foreach_remove(), g_hash_table_iter_next(), g_hash_table_iter_remove(), g_hash_table_lookup_extended(), g_hash_table_remove(), g_hash_table_remove_all(), g_hash_table_remove_internal(), g_hash_table_replace(), g_hash_table_unref(), g_mem_init_nomessage(), g_mem_profile(), g_mem_set_vtable(), g_mutex_lock_a(), g_parse_long_long(), g_utf8_prev_char(), g_utf8_validate(), get_data_window(), graphics_opengl_idle(), graphics_sdl_idle(), gtk_gui_poi(), gui_gtk_add_bookmark(), gui_gtk_delete(), gui_gtk_set_graphics(), gui_gtk_statusbar_new(), gui_internal_cmd2_route_height_profile(), gui_internal_set(), gui_internal_setup(), init_lv_columns(), initBth(), initialise(), item_hash_equal(), iter_remove_or_steal(), keypress(), line_intersection(), message_handler(), navit_add_destination_description(), navit_cmd_switch_layout_day_night(), navit_destroy(), navit_layout_switch(), navit_new(), navit_set_destination(), navit_set_destinations(), navit_vehicle_update_position(), navit_window_roadbook_update(), notify_size(), osd_odometer_save(), osso_navit(), overlay_disable(), parse_member(), parse_optional_member(), parse_packed_repeated_member(), pngdecode(), popup_traffic_distortion(), profile_print_locked(), profiler_calloc(), profiler_free(), profiler_try_malloc(), profiler_try_realloc(), qt5_espeak_init_espeak(), redraw_screen(), register_destination_window(), search_item_hash_equal(), slice_config_init(), smc_tree_lookup(), smc_tree_remove(), speech_message_handler(), statusbar_route_update(), treeview_poi_changed(), vehicle_gpsd_try_open(), vehicle_gypsy_course_changed(), vehicle_gypsy_position_changed(), vehicle_gypsy_try_open(), win32_gui_popup_new(), wince_reader_thread(), window_layout(), and xpmdecode().
#define UNALIGNED_ALLOC (allocator, size) ALLOC (allocator, size) /* placeholder */
#define UNPACK_ERROR (args) do { printf args;printf("\n"); }while(0)
Referenced by count_packed_elements(), parse_packed_repeated_member(), protobuf_c_message_unpack(), and scan_length_prefixed_data().
Typedef Documentation
typedef void(* GenericHandler)(void *service, const ProtobufCMessage *input, ProtobufCClosure closure, void *closure_data)
typedef struct _ScannedMember ScannedMember
Function Documentation
static void alloc_failed_warning (unsigned size, const char * filename, unsigned line) static
References fprintf().
static size_t binary_data_pack (const ProtobufCBinaryData * bd, uint8_t * out) inline static
References _ProtobufCBinaryData::data, _ProtobufCBinaryData::len, and uint32_pack().
Referenced by required_field_pack().
static size_t boolean_pack (protobuf_c_boolean value, uint8_t * out) inline static
Referenced by pack_buffer_packed_payload(), repeated_field_pack(), required_field_pack(), and required_field_pack_to_buffer().
static void copy_to_little_endian_32 (void * out, const void * in, unsigned N) static
References fixed32_pack(), i, and N.
Referenced by repeated_field_pack().
static void copy_to_little_endian_64 (void * out, const void * in, unsigned N) static
References fixed64_pack(), i, and N.
Referenced by repeated_field_pack().
static protobuf_c_boolean count_packed_elements (ProtobufCType type, size_t len, const uint8_t * data, size_t * count_out) static
References FALSE, max_b128_numbers(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, TRUE, and UNPACK_ERROR.
Referenced by protobuf_c_message_unpack().
static size_t fixed32_pack (uint32_t value, uint8_t * out) inline static
References value.
Referenced by copy_to_little_endian_32(), fixed64_pack(), pack_buffer_packed_payload(), required_field_pack(), and required_field_pack_to_buffer().
static size_t fixed64_pack (uint64_t value, uint8_t * out) inline static
References fixed32_pack().
Referenced by copy_to_little_endian_64(), pack_buffer_packed_payload(), required_field_pack(), and required_field_pack_to_buffer().
static size_t get_packed_payload_length (const ProtobufCFieldDescriptor * field, unsigned count, const void * array) static
References i, int32_size(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, sint32_size(), sint64_size(), _ProtobufCFieldDescriptor::type, uint32_size(), and uint64_size().
Referenced by repeated_field_pack_to_buffer().
static size_t get_tag_size (unsigned number) inline static
Referenced by repeated_field_get_packed_size(), required_field_get_packed_size(), and unknown_field_get_packed_size().
static unsigned get_type_min_size (ProtobufCType type) static
References PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_SFIXED32, and PROTOBUF_C_TYPE_SFIXED64.
Referenced by repeated_field_pack().
static size_t int32_pack (int32_t value, uint8_t * out) inline static
References uint32_pack().
Referenced by pack_buffer_packed_payload(), repeated_field_pack(), required_field_pack(), and required_field_pack_to_buffer().
static size_t int32_size (int32_t v) inline static
Referenced by get_packed_payload_length(), repeated_field_get_packed_size(), and required_field_get_packed_size().
static int int_range_lookup (unsigned n_ranges, const ProtobufCIntRange * ranges, int value) inline static
References _ProtobufCIntRange::orig_index, and start.
Referenced by protobuf_c_enum_descriptor_get_value(), protobuf_c_message_descriptor_get_field(), and protobuf_c_message_unpack().
static size_t max_b128_numbers (size_t len, const uint8_t * data) static
Referenced by count_packed_elements().
static size_t optional_field_get_packed_size (const ProtobufCFieldDescriptor * field, const protobuf_c_boolean * has, const void * member) static
References _ProtobufCFieldDescriptor::default_value, NULL, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_STRING, ptr, required_field_get_packed_size(), and _ProtobufCFieldDescriptor::type.
Referenced by protobuf_c_message_get_packed_size().
static size_t optional_field_pack (const ProtobufCFieldDescriptor * field, const protobuf_c_boolean * has, const void * member, uint8_t * out) static
References _ProtobufCFieldDescriptor::default_value, NULL, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_STRING, ptr, required_field_pack(), and _ProtobufCFieldDescriptor::type.
Referenced by protobuf_c_message_pack().
static size_t optional_field_pack_to_buffer (const ProtobufCFieldDescriptor * field, const protobuf_c_boolean * has, const void * member, ProtobufCBuffer * buffer) static
References _ProtobufCFieldDescriptor::default_value, NULL, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_STRING, ptr, required_field_pack_to_buffer(), and _ProtobufCFieldDescriptor::type.
Referenced by protobuf_c_message_pack_to_buffer().
static size_t pack_buffer_packed_payload (const ProtobufCFieldDescriptor * field, unsigned count, const void * array, ProtobufCBuffer * buffer) static
References _ProtobufCBuffer::append, boolean_pack(), fixed32_pack(), fixed64_pack(), i, int32_pack(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, sint32_pack(), sint64_pack(), _ProtobufCFieldDescriptor::type, uint32_pack(), and uint64_pack().
Referenced by repeated_field_pack_to_buffer().
static protobuf_c_boolean parse_boolean (unsigned len, const uint8_t * data) static
References i.
Referenced by parse_required_member().
static uint32_t parse_fixed_uint32 (const uint8_t * data) inline static
Referenced by parse_fixed_uint64(), parse_packed_repeated_member(), and parse_required_member().
static uint64_t parse_fixed_uint64 (const uint8_t * data) inline static
References parse_fixed_uint32().
Referenced by parse_packed_repeated_member(), and parse_required_member().
static uint32_t parse_int32 (unsigned len, const uint8_t * data) inline static
References parse_uint32().
Referenced by parse_packed_repeated_member(), and parse_required_member().
static protobuf_c_boolean parse_member (ScannedMember * scanned_member, ProtobufCMessage * message, ProtobufCAllocator * allocator) static
References _ProtobufCMessageUnknownField::data, _ScannedMember::data, DO_UNALIGNED_ALLOC, _ScannedMember::field, _ProtobufCFieldDescriptor::label, _ProtobufCMessageUnknownField::len, _ScannedMember::len, _ProtobufCMessage::n_unknown_fields, NULL, _ProtobufCFieldDescriptor::offset, _ProtobufCFieldDescriptor::packed, parse_optional_member(), parse_packed_repeated_member(), parse_repeated_member(), parse_required_member(), PROTOBUF_C_ASSERT_NOT_REACHED, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, _ProtobufCMessageUnknownField::tag, _ScannedMember::tag, TRUE, _ProtobufCMessage::unknown_fields, _ProtobufCMessageUnknownField::wire_type, and _ScannedMember::wire_type.
Referenced by protobuf_c_message_unpack().
static protobuf_c_boolean parse_optional_member (ScannedMember * scanned_member, void * member, ProtobufCMessage * message, ProtobufCAllocator * allocator) static
References _ScannedMember::field, parse_required_member(), _ProtobufCFieldDescriptor::quantifier_offset, STRUCT_MEMBER, and TRUE.
Referenced by parse_member().
static protobuf_c_boolean parse_packed_repeated_member (ScannedMember * scanned_member, void * member, ProtobufCMessage * message) static
References _ScannedMember::data, FALSE, _ScannedMember::field, i, _ScannedMember::len, _ScannedMember::length_prefix_len, parse_fixed_uint32(), parse_fixed_uint64(), parse_int32(), parse_uint32(), parse_uint64(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, _ProtobufCFieldDescriptor::quantifier_offset, scan_varint(), sizeof_elt_in_repeated_array(), STRUCT_MEMBER_PTR, TRUE, _ProtobufCFieldDescriptor::type, UNPACK_ERROR, unzigzag32(), and unzigzag64().
Referenced by parse_member().
static protobuf_c_boolean parse_repeated_member (ScannedMember * scanned_member, void * member, ProtobufCMessage * message, ProtobufCAllocator * allocator) static
References FALSE, _ScannedMember::field, parse_required_member(), _ProtobufCFieldDescriptor::quantifier_offset, sizeof_elt_in_repeated_array(), STRUCT_MEMBER_PTR, and _ProtobufCFieldDescriptor::type.
Referenced by parse_member().
static protobuf_c_boolean parse_required_member (ScannedMember * scanned_member, void * member, ProtobufCAllocator * allocator, protobuf_c_boolean maybe_clear) static
References _ProtobufCBinaryData::data, data, _ScannedMember::data, _ProtobufCFieldDescriptor::default_value, _ProtobufCFieldDescriptor::descriptor, DO_ALLOC, _ScannedMember::field, FREE, _ProtobufCBinaryData::len, _ScannedMember::len, _ScannedMember::length_prefix_len, NULL, parse_boolean(), parse_fixed_uint32(), parse_fixed_uint64(), parse_int32(), parse_uint32(), parse_uint64(), protobuf_c_message_free_unpacked(), protobuf_c_message_unpack(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, PROTOBUF_C_WIRE_TYPE_32BIT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_VARINT, _ProtobufCFieldDescriptor::type, unzigzag32(), unzigzag64(), and _ScannedMember::wire_type.
Referenced by parse_member(), parse_optional_member(), and parse_repeated_member().
static size_t parse_tag_and_wiretype (size_t len, const uint8_t * data, uint32_t * tag_out, ProtobufCWireType * wiretype_out) static
References shift.
Referenced by protobuf_c_message_unpack().
static uint32_t parse_uint32 (unsigned len, const uint8_t * data) inline static
Referenced by parse_int32(), parse_packed_repeated_member(), parse_required_member(), and parse_uint64().
static uint64_t parse_uint64 (unsigned len, const uint8_t * data) static
References i, parse_uint32(), and shift.
Referenced by parse_packed_repeated_member(), and parse_required_member().
static size_t prefixed_message_pack (const ProtobufCMessage * message, uint8_t * out) inline static
References NULL, protobuf_c_message_pack(), uint32_pack(), and uint32_size().
Referenced by required_field_pack().
void protobuf_c_buffer_simple_append (ProtobufCBuffer * buffer, size_t len, const uint8_t * data)
References _ProtobufCBufferSimple::alloced, _ProtobufCBufferSimple::data, DO_ALLOC, FREE, _ProtobufCBufferSimple::len, and _ProtobufCBufferSimple::must_free_data.
const ProtobufCEnumValue* protobuf_c_enum_descriptor_get_value (const ProtobufCEnumDescriptor * desc, int value)
References int_range_lookup(), _ProtobufCEnumDescriptor::n_value_ranges, NULL, _ProtobufCEnumDescriptor::value_ranges, and _ProtobufCEnumDescriptor::values.
const ProtobufCEnumValue* protobuf_c_enum_descriptor_get_value_by_name (const ProtobufCEnumDescriptor * desc, const char * name)
References _ProtobufCEnumValueIndex::index, _ProtobufCEnumDescriptor::n_value_names, _ProtobufCEnumValueIndex::name, NULL, start, _ProtobufCEnumDescriptor::values, and _ProtobufCEnumDescriptor::values_by_name.
const ProtobufCFieldDescriptor* protobuf_c_message_descriptor_get_field (const ProtobufCMessageDescriptor * desc, unsigned value)
References _ProtobufCMessageDescriptor::field_ranges, _ProtobufCMessageDescriptor::fields, int_range_lookup(), _ProtobufCMessageDescriptor::n_field_ranges, and NULL.
const ProtobufCFieldDescriptor* protobuf_c_message_descriptor_get_field_by_name (const ProtobufCMessageDescriptor * desc, const char * name)
References _ProtobufCMessageDescriptor::fields, _ProtobufCMessageDescriptor::fields_sorted_by_name, _ProtobufCMessageDescriptor::n_fields, _ProtobufCFieldDescriptor::name, NULL, and start.
void protobuf_c_message_free_unpacked (ProtobufCMessage * message, ProtobufCAllocator * allocator)
References ASSERT_IS_MESSAGE, _ProtobufCBinaryData::data, data, _ProtobufCMessageUnknownField::data, _ProtobufCFieldDescriptor::default_value, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, FREE, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, NULL, _ProtobufCFieldDescriptor::offset, protobuf_c_default_allocator, PROTOBUF_C_LABEL_REPEATED, protobuf_c_message_free_unpacked(), PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_STRING, _ProtobufCFieldDescriptor::quantifier_offset, STRUCT_MEMBER, _ProtobufCFieldDescriptor::type, and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__free_unpacked(), osmpbf__blob_header__free_unpacked(), osmpbf__change_set__free_unpacked(), osmpbf__dense_info__free_unpacked(), osmpbf__dense_nodes__free_unpacked(), osmpbf__header_bbox__free_unpacked(), osmpbf__header_block__free_unpacked(), osmpbf__info__free_unpacked(), osmpbf__node__free_unpacked(), osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_group__free_unpacked(), osmpbf__relation__free_unpacked(), osmpbf__string_table__free_unpacked(), osmpbf__way__free_unpacked(), parse_required_member(), protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
size_t protobuf_c_message_get_packed_size (const ProtobufCMessage * message)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_get_packed_size(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_get_packed_size(), required_field_get_packed_size(), unknown_field_get_packed_size(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__get_packed_size(), osmpbf__blob_header__get_packed_size(), osmpbf__change_set__get_packed_size(), osmpbf__dense_info__get_packed_size(), osmpbf__dense_nodes__get_packed_size(), osmpbf__header_bbox__get_packed_size(), osmpbf__header_block__get_packed_size(), osmpbf__info__get_packed_size(), osmpbf__node__get_packed_size(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_group__get_packed_size(), osmpbf__relation__get_packed_size(), osmpbf__string_table__get_packed_size(), osmpbf__way__get_packed_size(), repeated_field_get_packed_size(), and required_field_get_packed_size().
static void protobuf_c_message_init_generic (const ProtobufCMessageDescriptor * desc, ProtobufCMessage * message) static
References _ProtobufCFieldDescriptor::default_value, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, NULL, _ProtobufCFieldDescriptor::offset, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, _ProtobufCMessageDescriptor::sizeof_message, STRUCT_MEMBER_P, and _ProtobufCFieldDescriptor::type.
Referenced by protobuf_c_message_unpack().
size_t protobuf_c_message_pack (const ProtobufCMessage * message, uint8_t * out)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_pack(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_pack(), required_field_pack(), unknown_field_pack(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__pack(), osmpbf__blob_header__pack(), osmpbf__change_set__pack(), osmpbf__dense_info__pack(), osmpbf__dense_nodes__pack(), osmpbf__header_bbox__pack(), osmpbf__header_block__pack(), osmpbf__info__pack(), osmpbf__node__pack(), osmpbf__primitive_block__pack(), osmpbf__primitive_group__pack(), osmpbf__relation__pack(), osmpbf__string_table__pack(), osmpbf__way__pack(), and prefixed_message_pack().
size_t protobuf_c_message_pack_to_buffer (const ProtobufCMessage * message, ProtobufCBuffer * buffer)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_pack_to_buffer(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_pack_to_buffer(), required_field_pack_to_buffer(), unknown_field_pack_to_buffer(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__pack_to_buffer(), osmpbf__blob_header__pack_to_buffer(), osmpbf__change_set__pack_to_buffer(), osmpbf__dense_info__pack_to_buffer(), osmpbf__dense_nodes__pack_to_buffer(), osmpbf__header_bbox__pack_to_buffer(), osmpbf__header_block__pack_to_buffer(), osmpbf__info__pack_to_buffer(), osmpbf__node__pack_to_buffer(), osmpbf__primitive_block__pack_to_buffer(), osmpbf__primitive_group__pack_to_buffer(), osmpbf__relation__pack_to_buffer(), osmpbf__string_table__pack_to_buffer(), osmpbf__way__pack_to_buffer(), and required_field_pack_to_buffer().
ProtobufCMessage* protobuf_c_message_unpack (const ProtobufCMessageDescriptor * desc, ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References alloca, ASSERT_IS_MESSAGE_DESCRIPTOR, CLEAR_REMAINING_N_PTRS, count_packed_elements(), data, _ScannedMember::data, _ProtobufCFieldDescriptor::default_value, _ProtobufCMessage::descriptor, DO_ALLOC, _ScannedMember::field, _ProtobufCMessageDescriptor::field_ranges, _ProtobufCMessageDescriptor::fields, FIRST_SCANNED_MEMBER_SLAB_SIZE_LOG2, FREE, i, _ProtobufCFieldDescriptor::id, int_range_lookup(), _ProtobufCFieldDescriptor::label, _ScannedMember::len, _ScannedMember::length_prefix_len, long, max, MAX_SCANNED_MEMBER_SLAB, _ProtobufCMessageDescriptor::message_init, _ProtobufCMessageDescriptor::n_field_ranges, _ProtobufCMessageDescriptor::n_fields, _ProtobufCFieldDescriptor::name, _ProtobufCMessageDescriptor::name, NULL, _ProtobufCFieldDescriptor::offset, _ProtobufCFieldDescriptor::packed, parse_member(), parse_tag_and_wiretype(), protobuf_c_default_allocator, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_LABEL_REQUIRED, protobuf_c_message_free_unpacked(), protobuf_c_message_init, protobuf_c_message_init_generic(), PROTOBUF_C_WIRE_TYPE_32BIT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_VARINT, _ProtobufCFieldDescriptor::quantifier_offset, scan_length_prefixed_data(), size, sizeof_elt_in_repeated_array(), _ProtobufCMessageDescriptor::sizeof_message, STRUCT_MEMBER, STRUCT_MEMBER_PTR, _ScannedMember::tag, _ProtobufCAllocator::tmp_alloc, TMPALLOC, _ProtobufCFieldDescriptor::type, _ProtobufCMessage::unknown_fields, UNPACK_ERROR, and _ScannedMember::wire_type.
Referenced by osmpbf__blob__unpack(), osmpbf__blob_header__unpack(), osmpbf__change_set__unpack(), osmpbf__dense_info__unpack(), osmpbf__dense_nodes__unpack(), osmpbf__header_bbox__unpack(), osmpbf__header_block__unpack(), osmpbf__info__unpack(), osmpbf__node__unpack(), osmpbf__primitive_block__unpack(), osmpbf__primitive_group__unpack(), osmpbf__relation__unpack(), osmpbf__string_table__unpack(), osmpbf__way__unpack(), and parse_required_member().
static void protobuf_c_out_of_memory_default (void) static
References abort(), and fprintf().
const ProtobufCMethodDescriptor* protobuf_c_service_descriptor_get_method_by_name (const ProtobufCServiceDescriptor * desc, const char * name)
References _ProtobufCServiceDescriptor::method_indices_by_name, _ProtobufCServiceDescriptor::methods, _ProtobufCServiceDescriptor::n_methods, _ProtobufCMethodDescriptor::name, NULL, and start.
void protobuf_c_service_destroy (ProtobufCService * service)
References _ProtobufCService::destroy.
void protobuf_c_service_generated_init (ProtobufCService * service, const ProtobufCServiceDescriptor * descriptor, ProtobufCServiceDestroy destroy)
References ASSERT_IS_SERVICE_DESCRIPTOR, _ProtobufCService::descriptor, _ProtobufCService::destroy, _ProtobufCService::invoke, _ProtobufCServiceDescriptor::n_methods, and protobuf_c_service_invoke_internal().
void protobuf_c_service_invoke_internal (ProtobufCService * service, unsigned method_index, const ProtobufCMessage * input, ProtobufCClosure closure, void * closure_data)
References PROTOBUF_C_ASSERT.
Referenced by protobuf_c_service_generated_init().
static size_t repeated_field_get_packed_size (const ProtobufCFieldDescriptor * field, size_t count, const void * member) static
References get_tag_size(), i, _ProtobufCFieldDescriptor::id, int32_size(), _ProtobufCFieldDescriptor::packed, protobuf_c_message_get_packed_size(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, sint32_size(), sint64_size(), _ProtobufCFieldDescriptor::type, uint32_size(), and uint64_size().
Referenced by protobuf_c_message_get_packed_size().
static size_t repeated_field_pack (const ProtobufCFieldDescriptor * field, size_t count, const void * member, uint8_t * out) static
References boolean_pack(), copy_to_little_endian_32(), copy_to_little_endian_64(), get_type_min_size(), header_len, i, _ProtobufCFieldDescriptor::id, int32_pack(), _ProtobufCFieldDescriptor::packed, PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, required_field_pack(), sint32_pack(), sint64_pack(), sizeof_elt_in_repeated_array(), tag_pack(), _ProtobufCFieldDescriptor::type, uint32_pack(), uint32_size(), and uint64_pack().
Referenced by protobuf_c_message_pack().
static size_t repeated_field_pack_to_buffer (const ProtobufCFieldDescriptor * field, unsigned count, const void * member, ProtobufCBuffer * buffer) static
References abort(), _ProtobufCBuffer::append, fprintf(), get_packed_payload_length(), i, _ProtobufCFieldDescriptor::id, MAX_UINT64_ENCODED_SIZE, pack_buffer_packed_payload(), _ProtobufCFieldDescriptor::packed, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, required_field_pack_to_buffer(), sizeof_elt_in_repeated_array(), tag_pack(), _ProtobufCFieldDescriptor::type, and uint32_pack().
Referenced by protobuf_c_message_pack_to_buffer().
static size_t required_field_get_packed_size (const ProtobufCFieldDescriptor * field, const void * member) static
References get_tag_size(), _ProtobufCFieldDescriptor::id, int32_size(), PROTOBUF_C_ASSERT_NOT_REACHED, protobuf_c_message_get_packed_size(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, sint32_size(), sint64_size(), _ProtobufCFieldDescriptor::type, uint32_size(), and uint64_size().
Referenced by optional_field_get_packed_size(), and protobuf_c_message_get_packed_size().
static size_t required_field_pack (const ProtobufCFieldDescriptor * field, const void * member, uint8_t * out) static
References binary_data_pack(), boolean_pack(), fixed32_pack(), fixed64_pack(), _ProtobufCFieldDescriptor::id, int32_pack(), prefixed_message_pack(), PROTOBUF_C_ASSERT_NOT_REACHED, PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, PROTOBUF_C_WIRE_TYPE_32BIT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_VARINT, sint32_pack(), sint64_pack(), string_pack(), tag_pack(), _ProtobufCFieldDescriptor::type, uint32_pack(), and uint64_pack().
Referenced by optional_field_pack(), protobuf_c_message_pack(), and repeated_field_pack().
static size_t required_field_pack_to_buffer (const ProtobufCFieldDescriptor * field, const void * member, ProtobufCBuffer * buffer) static
References _ProtobufCBuffer::append, _ProtobufCBufferSimple::base, boolean_pack(), _ProtobufCBinaryData::data, _ProtobufCBufferSimple::data, fixed32_pack(), fixed64_pack(), _ProtobufCFieldDescriptor::id, int32_pack(), _ProtobufCBinaryData::len, MAX_UINT64_ENCODED_SIZE, NULL, PROTOBUF_C_ASSERT_NOT_REACHED, PROTOBUF_C_BUFFER_SIMPLE_CLEAR, PROTOBUF_C_BUFFER_SIMPLE_INIT, protobuf_c_message_pack_to_buffer(), PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_UINT64, PROTOBUF_C_WIRE_TYPE_32BIT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_VARINT, sint32_pack(), sint64_pack(), tag_pack(), _ProtobufCFieldDescriptor::type, uint32_pack(), and uint64_pack().
Referenced by optional_field_pack_to_buffer(), protobuf_c_message_pack_to_buffer(), and repeated_field_pack_to_buffer().
static uint32_t scan_length_prefixed_data (size_t len, const uint8_t * data, size_t * prefix_len_out) inline static
References i, shift, and UNPACK_ERROR.
Referenced by protobuf_c_message_unpack().
static unsigned scan_varint (unsigned len, const uint8_t * data) static
References i.
Referenced by parse_packed_repeated_member().
static size_t sint32_pack (int32_t value, uint8_t * out) inline static
References uint32_pack(), and zigzag32().
Referenced by pack_buffer_packed_payload(), repeated_field_pack(), required_field_pack(), and required_field_pack_to_buffer().
static size_t sint32_size (int32_t v) inline static
References uint32_size(), and zigzag32().
Referenced by get_packed_payload_length(), repeated_field_get_packed_size(), and required_field_get_packed_size().
static size_t sint64_pack (int64_t value, uint8_t * out) inline static
References uint64_pack(), and zigzag64().
Referenced by pack_buffer_packed_payload(), repeated_field_pack(), required_field_pack(), and required_field_pack_to_buffer().
static size_t sint64_size (int64_t v) inline static
References uint64_size(), and zigzag64().
Referenced by get_packed_payload_length(), repeated_field_get_packed_size(), and required_field_get_packed_size().
static size_t sizeof_elt_in_repeated_array (ProtobufCType type) inline static
References PROTOBUF_C_ASSERT_NOT_REACHED, PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_DOUBLE, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_FIXED32, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_INT64, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_UINT32, and PROTOBUF_C_TYPE_UINT64.
Referenced by parse_packed_repeated_member(), parse_repeated_member(), protobuf_c_message_unpack(), repeated_field_pack(), and repeated_field_pack_to_buffer().
static size_t string_pack (const char * str, uint8_t * out) inline static
References NULL, and uint32_pack().
Referenced by required_field_pack().
static void* system_alloc (void * allocator_data, size_t size) static
References NULL, protobuf_c_out_of_memory, and void().
static void system_free (void * allocator_data, void * data) static
References void().
static size_t tag_pack (uint32_t id, uint8_t * out) static
References uint32_pack(), and uint64_pack().
Referenced by repeated_field_pack(), repeated_field_pack_to_buffer(), required_field_pack(), required_field_pack_to_buffer(), unknown_field_pack(), and unknown_field_pack_to_buffer().
static size_t uint32_pack (uint32_t value, uint8_t * out) inline static
References value.
Referenced by binary_data_pack(), int32_pack(), pack_buffer_packed_payload(), prefixed_message_pack(), repeated_field_pack(), repeated_field_pack_to_buffer(), required_field_pack(), required_field_pack_to_buffer(), sint32_pack(), string_pack(), tag_pack(), and uint64_pack().
static size_t uint32_size (uint32_t v) inline static
Referenced by get_packed_payload_length(), prefixed_message_pack(), repeated_field_get_packed_size(), repeated_field_pack(), required_field_get_packed_size(), sint32_size(), and uint64_size().
static size_t uint64_pack (uint64_t value, uint8_t * out) static
References uint32_pack(), and value.
Referenced by pack_buffer_packed_payload(), repeated_field_pack(), required_field_pack(), required_field_pack_to_buffer(), sint64_pack(), and tag_pack().
static size_t uint64_size (uint64_t v) inline static
References uint32_size().
Referenced by get_packed_payload_length(), repeated_field_get_packed_size(), required_field_get_packed_size(), and sint64_size().
static size_t unknown_field_get_packed_size (const ProtobufCMessageUnknownField * field) inline static
References get_tag_size(), _ProtobufCMessageUnknownField::len, and _ProtobufCMessageUnknownField::tag.
Referenced by protobuf_c_message_get_packed_size().
static size_t unknown_field_pack (const ProtobufCMessageUnknownField * field, uint8_t * out) static
References _ProtobufCMessageUnknownField::data, _ProtobufCMessageUnknownField::len, _ProtobufCMessageUnknownField::tag, tag_pack(), and _ProtobufCMessageUnknownField::wire_type.
Referenced by protobuf_c_message_pack().
static size_t unknown_field_pack_to_buffer (const ProtobufCMessageUnknownField * field, ProtobufCBuffer * buffer) static
References _ProtobufCBuffer::append, _ProtobufCMessageUnknownField::data, _ProtobufCMessageUnknownField::len, MAX_UINT64_ENCODED_SIZE, _ProtobufCMessageUnknownField::tag, tag_pack(), and _ProtobufCMessageUnknownField::wire_type.
Referenced by protobuf_c_message_pack_to_buffer().
static int32_t unzigzag32 (uint32_t v) inline static
Referenced by parse_packed_repeated_member(), and parse_required_member().
static int64_t unzigzag64 (uint64_t v) inline static
Referenced by parse_packed_repeated_member(), and parse_required_member().
static uint32_t zigzag32 (int32_t v) inline static
Referenced by sint32_pack(), and sint32_size().
static uint64_t zigzag64 (int64_t v) inline static
Referenced by sint64_pack(), and sint64_size().
Variable Documentation
ProtobufCAllocator protobuf_c_default_allocator
Initial value:
=
{
  system_alloc,
  system_free,
  NULL,
  8192,
  NULL
}
Referenced by protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
void(* protobuf_c_out_of_memory)(void) = protobuf_c_out_of_memory_default
Referenced by system_alloc().
ProtobufCAllocator protobuf_c_system_allocator
Initial value:
=
{
  system_alloc,
  system_free,
  NULL,
  8192,
  NULL
}
Referenced by map_collect_data_osm_protobuf(), osm_protobufdb_finish_block(), osm_protobufdb_modify_node(), osm_protobufdb_modify_relation(), osm_protobufdb_modify_way(), process_osmdata(), process_osmheader(), read_blob(), and read_header().