navit: maptool/google/protobuf-c/protobuf-c.h File Reference
protobuf-c.h File Reference
#include <stddef.h>
#include <assert.h>
#include <inttypes.h>
#include "protobuf-c-private.h"
Data Structures
struct _ProtobufCBinaryData
struct _ProtobufCAllocator
struct _ProtobufCBuffer
struct _ProtobufCEnumValue
struct _ProtobufCEnumDescriptor
struct _ProtobufCFieldDescriptor
struct _ProtobufCMessageDescriptor
struct _ProtobufCMessage
struct _ProtobufCMethodDescriptor
struct _ProtobufCServiceDescriptor
struct _ProtobufCService
struct _ProtobufCMessageUnknownField
struct _ProtobufCBufferSimple
Macros
#define PROTOBUF_C_BEGIN_DECLS
#define PROTOBUF_C_END_DECLS
#define PROTOBUF_C_DEPRECATED
#define PROTOBUF_C_OFFSETOF(struct, member) offsetof(struct, member)
#define PROTOBUF_C_ASSERT(condition) assert(condition)
#define PROTOBUF_C_ASSERT_NOT_REACHED() assert(0)
#define PROTOBUF_C_MESSAGE_INIT(descriptor) { descriptor, 0, NULL }
#define protobuf_c_message_init(descriptor, message) ((descriptor)->message_init((ProtobufCMessage*) (message)))
#define PROTOBUF_C_BUFFER_SIMPLE_INIT(array_of_bytes)
#define PROTOBUF_C_BUFFER_SIMPLE_CLEAR(simp_buf)
Typedefs
typedef int protobuf_c_boolean
typedef struct _ProtobufCBinaryData ProtobufCBinaryData
typedef struct _ProtobufCIntRange ProtobufCIntRange
typedef struct _ProtobufCAllocator ProtobufCAllocator
typedef struct _ProtobufCBuffer ProtobufCBuffer
typedef struct _ProtobufCEnumValue ProtobufCEnumValue
typedef struct
_ProtobufCEnumValueIndex ProtobufCEnumValueIndex
typedef struct
_ProtobufCEnumDescriptor ProtobufCEnumDescriptor
typedef struct
_ProtobufCMessageDescriptor ProtobufCMessageDescriptor
typedef struct
_ProtobufCFieldDescriptor ProtobufCFieldDescriptor
typedef struct _ProtobufCMessage ProtobufCMessage
typedef void(* ProtobufCMessageInit)(ProtobufCMessage *)
typedef struct
_ProtobufCMessageUnknownField ProtobufCMessageUnknownField
typedef struct
_ProtobufCMethodDescriptor ProtobufCMethodDescriptor
typedef struct
_ProtobufCServiceDescriptor ProtobufCServiceDescriptor
typedef struct _ProtobufCService ProtobufCService
typedef void(* ProtobufCClosure)(const ProtobufCMessage *message, void *closure_data)
typedef struct
_ProtobufCBufferSimple ProtobufCBufferSimple
Enumerations
enum ProtobufCLabel { PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REPEATED }
enum ProtobufCType {
PROTOBUF_C_TYPE_INT32, PROTOBUF_C_TYPE_SINT32, PROTOBUF_C_TYPE_SFIXED32, PROTOBUF_C_TYPE_INT64,
PROTOBUF_C_TYPE_SINT64, PROTOBUF_C_TYPE_SFIXED64, PROTOBUF_C_TYPE_UINT32, PROTOBUF_C_TYPE_FIXED32,
PROTOBUF_C_TYPE_UINT64, PROTOBUF_C_TYPE_FIXED64, PROTOBUF_C_TYPE_FLOAT, PROTOBUF_C_TYPE_DOUBLE,
PROTOBUF_C_TYPE_BOOL, PROTOBUF_C_TYPE_ENUM, PROTOBUF_C_TYPE_STRING, PROTOBUF_C_TYPE_BYTES,
PROTOBUF_C_TYPE_MESSAGE
}
enum ProtobufCWireType {
PROTOBUF_C_WIRE_TYPE_VARINT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_START_GROUP,
PROTOBUF_C_WIRE_TYPE_END_GROUP, PROTOBUF_C_WIRE_TYPE_32BIT
}
Functions
size_t protobuf_c_message_get_packed_size (const ProtobufCMessage *message)
size_t protobuf_c_message_pack (const ProtobufCMessage *message, uint8_t *out)
size_t protobuf_c_message_pack_to_buffer (const ProtobufCMessage *message, ProtobufCBuffer *buffer)
ProtobufCMessage * protobuf_c_message_unpack (const ProtobufCMessageDescriptor *, ProtobufCAllocator *allocator, size_t len, const uint8_t *data)
void protobuf_c_message_free_unpacked (ProtobufCMessage *message, ProtobufCAllocator *allocator)
void protobuf_c_service_destroy (ProtobufCService *)
const ProtobufCEnumValue * protobuf_c_enum_descriptor_get_value_by_name (const ProtobufCEnumDescriptor *desc, const char *name)
const ProtobufCEnumValue * protobuf_c_enum_descriptor_get_value (const ProtobufCEnumDescriptor *desc, int value)
const ProtobufCFieldDescriptor * protobuf_c_message_descriptor_get_field_by_name (const ProtobufCMessageDescriptor *desc, const char *name)
const ProtobufCFieldDescriptor * protobuf_c_message_descriptor_get_field (const ProtobufCMessageDescriptor *desc, unsigned value)
const ProtobufCMethodDescriptor * protobuf_c_service_descriptor_get_method_by_name (const ProtobufCServiceDescriptor *desc, const char *name)
Variables
ProtobufCAllocator protobuf_c_default_allocator
ProtobufCAllocator protobuf_c_system_allocator
void(* protobuf_c_out_of_memory)(void)
Macro Definition Documentation
#define PROTOBUF_C_ASSERT (condition) assert(condition)
Referenced by osmpbf__blob__free_unpacked(), osmpbf__blob__get_packed_size(), osmpbf__blob__pack(), osmpbf__blob__pack_to_buffer(), osmpbf__blob_header__free_unpacked(), osmpbf__blob_header__get_packed_size(), osmpbf__blob_header__pack(), osmpbf__blob_header__pack_to_buffer(), osmpbf__change_set__free_unpacked(), osmpbf__change_set__get_packed_size(), osmpbf__change_set__pack(), osmpbf__change_set__pack_to_buffer(), osmpbf__dense_info__free_unpacked(), osmpbf__dense_info__get_packed_size(), osmpbf__dense_info__pack(), osmpbf__dense_info__pack_to_buffer(), osmpbf__dense_nodes__free_unpacked(), osmpbf__dense_nodes__get_packed_size(), osmpbf__dense_nodes__pack(), osmpbf__dense_nodes__pack_to_buffer(), osmpbf__header_bbox__free_unpacked(), osmpbf__header_bbox__get_packed_size(), osmpbf__header_bbox__pack(), osmpbf__header_bbox__pack_to_buffer(), osmpbf__header_block__free_unpacked(), osmpbf__header_block__get_packed_size(), osmpbf__header_block__pack(), osmpbf__header_block__pack_to_buffer(), osmpbf__info__free_unpacked(), osmpbf__info__get_packed_size(), osmpbf__info__pack(), osmpbf__info__pack_to_buffer(), osmpbf__node__free_unpacked(), osmpbf__node__get_packed_size(), osmpbf__node__pack(), osmpbf__node__pack_to_buffer(), osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_block__pack(), osmpbf__primitive_block__pack_to_buffer(), osmpbf__primitive_group__free_unpacked(), osmpbf__primitive_group__get_packed_size(), osmpbf__primitive_group__pack(), osmpbf__primitive_group__pack_to_buffer(), osmpbf__relation__free_unpacked(), osmpbf__relation__get_packed_size(), osmpbf__relation__pack(), osmpbf__relation__pack_to_buffer(), osmpbf__string_table__free_unpacked(), osmpbf__string_table__get_packed_size(), osmpbf__string_table__pack(), osmpbf__string_table__pack_to_buffer(), osmpbf__way__free_unpacked(), osmpbf__way__get_packed_size(), osmpbf__way__pack(), osmpbf__way__pack_to_buffer(), and protobuf_c_service_invoke_internal().
#define PROTOBUF_C_ASSERT_NOT_REACHED () assert(0)
Referenced by parse_member(), required_field_get_packed_size(), required_field_pack(), required_field_pack_to_buffer(), and sizeof_elt_in_repeated_array().
#define PROTOBUF_C_BEGIN_DECLS
#define PROTOBUF_C_BUFFER_SIMPLE_CLEAR (simp_buf)
Value:
do { if ((simp_buf)->must_free_data) \
         protobuf_c_default_allocator.free (&protobuf_c_default_allocator.allocator_data, (simp_buf)->data); } while (0)
Referenced by required_field_pack_to_buffer().
#define PROTOBUF_C_BUFFER_SIMPLE_INIT (array_of_bytes)
Value:
{ { protobuf_c_buffer_simple_append }, \
  sizeof(array_of_bytes), 0, (array_of_bytes), 0 }
Referenced by required_field_pack_to_buffer().
#define PROTOBUF_C_DEPRECATED
#define PROTOBUF_C_END_DECLS
#define PROTOBUF_C_MESSAGE_INIT (descriptor) { descriptor, 0, NULL }
#define protobuf_c_message_init (descriptor, message) ((descriptor)->message_init((ProtobufCMessage*) (message)))
Referenced by protobuf_c_message_unpack().
#define PROTOBUF_C_OFFSETOF (struct, member) offsetof(struct, member)
Typedef Documentation
typedef int protobuf_c_boolean
typedef struct _ProtobufCAllocator ProtobufCAllocator
typedef struct _ProtobufCBinaryData ProtobufCBinaryData
typedef struct _ProtobufCBuffer ProtobufCBuffer
typedef struct _ProtobufCBufferSimple ProtobufCBufferSimple
typedef void(* ProtobufCClosure)(const ProtobufCMessage *message, void *closure_data)
typedef struct _ProtobufCEnumDescriptor ProtobufCEnumDescriptor
typedef struct _ProtobufCEnumValue ProtobufCEnumValue
typedef struct _ProtobufCEnumValueIndex ProtobufCEnumValueIndex
typedef struct _ProtobufCFieldDescriptor ProtobufCFieldDescriptor
typedef struct _ProtobufCIntRange ProtobufCIntRange
typedef struct _ProtobufCMessage ProtobufCMessage
typedef struct _ProtobufCMessageDescriptor ProtobufCMessageDescriptor
typedef void(* ProtobufCMessageInit)(ProtobufCMessage *)
typedef struct _ProtobufCMessageUnknownField ProtobufCMessageUnknownField
typedef struct _ProtobufCMethodDescriptor ProtobufCMethodDescriptor
typedef struct _ProtobufCService ProtobufCService
typedef struct _ProtobufCServiceDescriptor ProtobufCServiceDescriptor
Enumeration Type Documentation
enum ProtobufCLabel
Enumerator
PROTOBUF_C_LABEL_REQUIRED
PROTOBUF_C_LABEL_OPTIONAL
PROTOBUF_C_LABEL_REPEATED
enum ProtobufCType
Enumerator
PROTOBUF_C_TYPE_INT32
PROTOBUF_C_TYPE_SINT32
PROTOBUF_C_TYPE_SFIXED32
PROTOBUF_C_TYPE_INT64
PROTOBUF_C_TYPE_SINT64
PROTOBUF_C_TYPE_SFIXED64
PROTOBUF_C_TYPE_UINT32
PROTOBUF_C_TYPE_FIXED32
PROTOBUF_C_TYPE_UINT64
PROTOBUF_C_TYPE_FIXED64
PROTOBUF_C_TYPE_FLOAT
PROTOBUF_C_TYPE_DOUBLE
PROTOBUF_C_TYPE_BOOL
PROTOBUF_C_TYPE_ENUM
PROTOBUF_C_TYPE_STRING
PROTOBUF_C_TYPE_BYTES
PROTOBUF_C_TYPE_MESSAGE
enum ProtobufCWireType
Enumerator
PROTOBUF_C_WIRE_TYPE_VARINT
PROTOBUF_C_WIRE_TYPE_64BIT
PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED
PROTOBUF_C_WIRE_TYPE_START_GROUP
PROTOBUF_C_WIRE_TYPE_END_GROUP
PROTOBUF_C_WIRE_TYPE_32BIT
Function Documentation
const ProtobufCEnumValue* protobuf_c_enum_descriptor_get_value (const ProtobufCEnumDescriptor * desc, int value)
References int_range_lookup(), _ProtobufCEnumDescriptor::n_value_ranges, NULL, _ProtobufCEnumDescriptor::value_ranges, and _ProtobufCEnumDescriptor::values.
const ProtobufCEnumValue* protobuf_c_enum_descriptor_get_value_by_name (const ProtobufCEnumDescriptor * desc, const char * name)
References _ProtobufCEnumValueIndex::index, _ProtobufCEnumDescriptor::n_value_names, _ProtobufCEnumValueIndex::name, NULL, start, _ProtobufCEnumDescriptor::values, and _ProtobufCEnumDescriptor::values_by_name.
const ProtobufCFieldDescriptor* protobuf_c_message_descriptor_get_field (const ProtobufCMessageDescriptor * desc, unsigned value)
References _ProtobufCMessageDescriptor::field_ranges, _ProtobufCMessageDescriptor::fields, int_range_lookup(), _ProtobufCMessageDescriptor::n_field_ranges, and NULL.
const ProtobufCFieldDescriptor* protobuf_c_message_descriptor_get_field_by_name (const ProtobufCMessageDescriptor * desc, const char * name)
References _ProtobufCMessageDescriptor::fields, _ProtobufCMessageDescriptor::fields_sorted_by_name, _ProtobufCMessageDescriptor::n_fields, _ProtobufCFieldDescriptor::name, NULL, and start.
void protobuf_c_message_free_unpacked (ProtobufCMessage * message, ProtobufCAllocator * allocator)
References ASSERT_IS_MESSAGE, _ProtobufCBinaryData::data, data, _ProtobufCMessageUnknownField::data, _ProtobufCFieldDescriptor::default_value, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, FREE, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, NULL, _ProtobufCFieldDescriptor::offset, protobuf_c_default_allocator, PROTOBUF_C_LABEL_REPEATED, protobuf_c_message_free_unpacked(), PROTOBUF_C_TYPE_BYTES, PROTOBUF_C_TYPE_MESSAGE, PROTOBUF_C_TYPE_STRING, _ProtobufCFieldDescriptor::quantifier_offset, STRUCT_MEMBER, _ProtobufCFieldDescriptor::type, and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__free_unpacked(), osmpbf__blob_header__free_unpacked(), osmpbf__change_set__free_unpacked(), osmpbf__dense_info__free_unpacked(), osmpbf__dense_nodes__free_unpacked(), osmpbf__header_bbox__free_unpacked(), osmpbf__header_block__free_unpacked(), osmpbf__info__free_unpacked(), osmpbf__node__free_unpacked(), osmpbf__primitive_block__free_unpacked(), osmpbf__primitive_group__free_unpacked(), osmpbf__relation__free_unpacked(), osmpbf__string_table__free_unpacked(), osmpbf__way__free_unpacked(), parse_required_member(), protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
size_t protobuf_c_message_get_packed_size (const ProtobufCMessage * message)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_get_packed_size(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_get_packed_size(), required_field_get_packed_size(), unknown_field_get_packed_size(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__get_packed_size(), osmpbf__blob_header__get_packed_size(), osmpbf__change_set__get_packed_size(), osmpbf__dense_info__get_packed_size(), osmpbf__dense_nodes__get_packed_size(), osmpbf__header_bbox__get_packed_size(), osmpbf__header_block__get_packed_size(), osmpbf__info__get_packed_size(), osmpbf__node__get_packed_size(), osmpbf__primitive_block__get_packed_size(), osmpbf__primitive_group__get_packed_size(), osmpbf__relation__get_packed_size(), osmpbf__string_table__get_packed_size(), osmpbf__way__get_packed_size(), repeated_field_get_packed_size(), and required_field_get_packed_size().
size_t protobuf_c_message_pack (const ProtobufCMessage * message, uint8_t * out)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_pack(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_pack(), required_field_pack(), unknown_field_pack(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__pack(), osmpbf__blob_header__pack(), osmpbf__change_set__pack(), osmpbf__dense_info__pack(), osmpbf__dense_nodes__pack(), osmpbf__header_bbox__pack(), osmpbf__header_block__pack(), osmpbf__info__pack(), osmpbf__node__pack(), osmpbf__primitive_block__pack(), osmpbf__primitive_group__pack(), osmpbf__relation__pack(), osmpbf__string_table__pack(), osmpbf__way__pack(), and prefixed_message_pack().
size_t protobuf_c_message_pack_to_buffer (const ProtobufCMessage * message, ProtobufCBuffer * buffer)
References ASSERT_IS_MESSAGE, _ProtobufCMessage::descriptor, _ProtobufCMessageDescriptor::fields, i, _ProtobufCFieldDescriptor::label, _ProtobufCMessageDescriptor::n_fields, _ProtobufCMessage::n_unknown_fields, _ProtobufCFieldDescriptor::offset, optional_field_pack_to_buffer(), PROTOBUF_C_LABEL_OPTIONAL, PROTOBUF_C_LABEL_REQUIRED, _ProtobufCFieldDescriptor::quantifier_offset, repeated_field_pack_to_buffer(), required_field_pack_to_buffer(), unknown_field_pack_to_buffer(), and _ProtobufCMessage::unknown_fields.
Referenced by osmpbf__blob__pack_to_buffer(), osmpbf__blob_header__pack_to_buffer(), osmpbf__change_set__pack_to_buffer(), osmpbf__dense_info__pack_to_buffer(), osmpbf__dense_nodes__pack_to_buffer(), osmpbf__header_bbox__pack_to_buffer(), osmpbf__header_block__pack_to_buffer(), osmpbf__info__pack_to_buffer(), osmpbf__node__pack_to_buffer(), osmpbf__primitive_block__pack_to_buffer(), osmpbf__primitive_group__pack_to_buffer(), osmpbf__relation__pack_to_buffer(), osmpbf__string_table__pack_to_buffer(), osmpbf__way__pack_to_buffer(), and required_field_pack_to_buffer().
ProtobufCMessage* protobuf_c_message_unpack (const ProtobufCMessageDescriptor * , ProtobufCAllocator * allocator, size_t len, const uint8_t * data)
References alloca, ASSERT_IS_MESSAGE_DESCRIPTOR, CLEAR_REMAINING_N_PTRS, count_packed_elements(), data, _ScannedMember::data, _ProtobufCFieldDescriptor::default_value, _ProtobufCMessage::descriptor, DO_ALLOC, _ScannedMember::field, _ProtobufCMessageDescriptor::field_ranges, _ProtobufCMessageDescriptor::fields, FIRST_SCANNED_MEMBER_SLAB_SIZE_LOG2, FREE, i, _ProtobufCFieldDescriptor::id, int_range_lookup(), _ProtobufCFieldDescriptor::label, _ScannedMember::len, _ScannedMember::length_prefix_len, long, max, MAX_SCANNED_MEMBER_SLAB, _ProtobufCMessageDescriptor::message_init, _ProtobufCMessageDescriptor::n_field_ranges, _ProtobufCMessageDescriptor::n_fields, _ProtobufCFieldDescriptor::name, _ProtobufCMessageDescriptor::name, NULL, _ProtobufCFieldDescriptor::offset, _ProtobufCFieldDescriptor::packed, parse_member(), parse_tag_and_wiretype(), protobuf_c_default_allocator, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_LABEL_REQUIRED, protobuf_c_message_free_unpacked(), protobuf_c_message_init, protobuf_c_message_init_generic(), PROTOBUF_C_WIRE_TYPE_32BIT, PROTOBUF_C_WIRE_TYPE_64BIT, PROTOBUF_C_WIRE_TYPE_LENGTH_PREFIXED, PROTOBUF_C_WIRE_TYPE_VARINT, _ProtobufCFieldDescriptor::quantifier_offset, scan_length_prefixed_data(), size, sizeof_elt_in_repeated_array(), _ProtobufCMessageDescriptor::sizeof_message, STRUCT_MEMBER, STRUCT_MEMBER_PTR, _ScannedMember::tag, _ProtobufCAllocator::tmp_alloc, TMPALLOC, _ProtobufCFieldDescriptor::type, _ProtobufCMessage::unknown_fields, UNPACK_ERROR, and _ScannedMember::wire_type.
Referenced by osmpbf__blob__unpack(), osmpbf__blob_header__unpack(), osmpbf__change_set__unpack(), osmpbf__dense_info__unpack(), osmpbf__dense_nodes__unpack(), osmpbf__header_bbox__unpack(), osmpbf__header_block__unpack(), osmpbf__info__unpack(), osmpbf__node__unpack(), osmpbf__primitive_block__unpack(), osmpbf__primitive_group__unpack(), osmpbf__relation__unpack(), osmpbf__string_table__unpack(), osmpbf__way__unpack(), and parse_required_member().
const ProtobufCMethodDescriptor* protobuf_c_service_descriptor_get_method_by_name (const ProtobufCServiceDescriptor * desc, const char * name)
References _ProtobufCServiceDescriptor::method_indices_by_name, _ProtobufCServiceDescriptor::methods, _ProtobufCServiceDescriptor::n_methods, _ProtobufCMethodDescriptor::name, NULL, and start.
void protobuf_c_service_destroy (ProtobufCService *)
References _ProtobufCService::destroy.
Variable Documentation
ProtobufCAllocator protobuf_c_default_allocator
Referenced by protobuf_c_message_free_unpacked(), and protobuf_c_message_unpack().
void(* protobuf_c_out_of_memory)(void)
Referenced by system_alloc().
ProtobufCAllocator protobuf_c_system_allocator
Referenced by map_collect_data_osm_protobuf(), osm_protobufdb_finish_block(), osm_protobufdb_modify_node(), osm_protobufdb_modify_relation(), osm_protobufdb_modify_way(), process_osmdata(), process_osmheader(), read_blob(), and read_header().