navit: gui/qt5_qml/proxy.c File Reference
proxy.c File Reference
#include <glib.h>
#include "item.h"
#include "attr.h"
#include "navit.h"
#include "xmlconfig.h"
#include "layout.h"
#include "map.h"
#include "transform.h"
#include "debug.h"
#include "search.h"
Functions
char * get_icon (struct navit *nav, struct item *item)
Function Documentation
char* get_icon (struct navit * nav, struct item * item)
References _GList::data, element::element_icon, g_free(), g_list_next, g_strdup(), g_strdup_printf(), element::icon, item::id_hi, item::id_lo, item_attr_get(), item_is_custom_poi, attr::layer, layout::layers, attr::layout, item::map, map_convert_string_tmp(), map_rect_get_item_byid(), map_rect_new(), navit_get_attr(), NULL, element::src, attr::str, element::type, item::type, types, element::u, and attr::u.
Referenced by Backend::get_pois().