navit: graphics/qt5/QNavitQuick.cpp File Reference
QNavitQuick.cpp File Reference
#include <glib.h>
#include "config.h"
#include "item.h"
#include "callback.h"
#include "color.h"
#include "debug.h"
#include "event.h"
#include "point.h"
#include "graphics.h"
#include "keys.h"
#include "plugin.h"
#include "window.h"
#include "QNavitQuick.h"
#include "graphics_qt5.h"
#include <QPainter>
Functions
static void paintOverlays (QPainter *painter, struct graphics_priv *gp, QPaintEvent *event)
Function Documentation
static void paintOverlays (QPainter * painter, struct graphics_priv * gp, QPaintEvent * event) static
References dbg, graphics_priv::disable, g_hash_table_iter_init(), g_hash_table_iter_next(), eval::iter, key, lvl_debug, graphics_priv::overlays, graphics_priv::pixmap, graphics_priv::scroll_x, graphics_priv::scroll_y, value, graphics_priv::x, and graphics_priv::y.
Referenced by QNavitQuick::paint().