navit: gui/qt5_qml/proxy.h File Reference
proxy.h File Reference
Functions
char * get_icon (struct navit *nav, struct item *item)
Function Documentation
char* get_icon (struct navit * nav, struct item * item)
References element::element_icon, element::icon, item::id_hi, item::id_lo, item_attr_get(), item_is_custom_poi, attr::layer, layout::layers, attr::layout, item::map, map_convert_string_tmp(), map_rect_get_item_byid(), map_rect_new(), navit_get_attr(), element::src, attr::str, element::type, item::type, types, element::u, and attr::u.
Referenced by Backend::get_pois().