navit: speech/qt5_espeak/qt5_espeak.cpp File Reference
qt5_espeak.cpp File Reference
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <glib.h>
#include "item.h"
#include "attr.h"
#include "debug.h"
#include "file.h"
#include "plugin.h"
#include "speech.h"
#include "util.h"
#include <espeak/speak_lib.h>
#include "Qt5EspeakAudioOut.h"
Data Structures
struct speech_priv
Macros
#define INTERNAL_ESPEAK 0
#define BUFFERLENGTH 1000
#define SAMPLE_SIZE 16
Functions
int qt5_espeak_SynthCallback (short *wav, int numsamples, espeak_EVENT *events)
static bool qt5_espeak_init_espeak (struct speech_priv *sr, struct attr **attrs)
static bool qt5_espeak_init_language (struct speech_priv *pr, struct attr **attrs)
static bool qt5_espeak_init_audio (struct speech_priv *sr, const char *category)
static int qt5_espeak_say (struct speech_priv *sr, const char *text)
static void qt5_espeak_destroy (struct speech_priv *sr)
static struct speech_priv * qt5_espeak_new (struct speech_methods *meth, struct attr **attrs, struct attr *parent)
void plugin_init (void)
The plugin entry point.
Variables
static struct speech_methods qt5_espeak_meth
Macro Definition Documentation
#define BUFFERLENGTH 1000
Referenced by qt5_espeak_init_espeak().
#define INTERNAL_ESPEAK 0
Navit, a modular navigation system. Copyright (C) 2017-2017 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#define SAMPLE_SIZE 16
Function Documentation
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
References dbg, lvl_debug, and qt5_espeak_new().
static void qt5_espeak_destroy (struct speech_priv * sr) static
References dbg, g_free(), lvl_debug, NULL, and speech_priv::path_home.
static bool qt5_espeak_init_audio (struct speech_priv * sr, const char * category) static
References speech_priv::audio, dbg, lvl_error, and speech_priv::sample_rate.
Referenced by qt5_espeak_new().
static bool qt5_espeak_init_espeak (struct speech_priv * sr, struct attr ** attrs) static
References attr_search(), AUDIO_OUTPUT_SYNCHRONOUS, BUFFERLENGTH, dbg, EE_INTERNAL_ERROR, espeak_Initialize(), espeak_SetSynthCallback(), g_strdup(), g_strdup_printf(), getenv, lvl_debug, lvl_error, NULL, speech_priv::path_home, qt5_espeak_SynthCallback(), speech_priv::sample_rate, attr::str, TRUE, and attr::u.
Referenced by qt5_espeak_new().
static bool qt5_espeak_init_language (struct speech_priv * pr, struct attr ** attrs) static
References espeak_VOICE::age, attr_search(), country, dbg, EE_OK, espeak_SetVoiceByProperties(), g_free(), g_strdup(), gchar, espeak_VOICE::gender, getenv, espeak_VOICE::languages, lvl_debug, lvl_error, espeak_VOICE::name, NULL, attr::str, strtolower(), attr::u, and espeak_VOICE::variant.
Referenced by qt5_espeak_new().
static struct speech_priv* qt5_espeak_new (struct speech_methods * meth, struct attr ** attrs, struct attr * parent) static
References speech_priv::audio, speech_priv::audio_ok, dbg, speech_priv::espeak_ok, g_new0, lvl_debug, lvl_error, NULL, speech_priv::path_home, qt5_espeak_init_audio(), qt5_espeak_init_espeak(), qt5_espeak_init_language(), qt5_espeak_meth, and speech_priv::sample_rate.
Referenced by plugin_init().
static int qt5_espeak_say (struct speech_priv * sr, const char * text) static
References dbg, EE_OK, espeak_Synth(), espeakCHARS_UTF8, lvl_debug, lvl_error, NULL, and POS_CHARACTER.
int qt5_espeak_SynthCallback (short * wav, int numsamples, espeak_EVENT * events)
References Qt5EspeakAudioOut::addSamples(), speech_priv::audio, dbg, if(), lvl_debug, NULL, and espeak_EVENT::user_data.
Referenced by qt5_espeak_init_espeak().
Variable Documentation
struct speech_methods qt5_espeak_meth static
Initial value:
= {
    qt5_espeak_destroy, qt5_espeak_say,
}
Referenced by qt5_espeak_new().