navit: support/espeak/readclause.c File Reference
readclause.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>
#include <wchar.h>
#include <math.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
#include <locale.h>
Data Structures
struct SSML_STACK
Macros
#define N_XML_BUF 256
#define double(x) ((double)(x))
#define N_SSML_STACK 20
#define N_PARAM_STACK 20
#define SSML_SPEAK 1
#define SSML_VOICE 2
#define SSML_PROSODY 3
#define SSML_SAYAS 4
#define SSML_MARK 5
#define SSML_SENTENCE 6
#define SSML_PARAGRAPH 7
#define SSML_PHONEME 8
#define SSML_SUB 9
#define SSML_STYLE 10
#define SSML_AUDIO 11
#define SSML_EMPHASIS 12
#define SSML_BREAK 13
#define SSML_IGNORE_TEXT 14
#define HTML_BREAK 15
#define SSML_CLOSE 0x10
#define N_XML_BUF2 20
Functions
int towlower2 (unsigned int c)
static void GetC_unget (int c)
int Eof (void)
static int GetC_get (void)
static int GetC (void)
static void UngetC (int c)
static const char * WordToString2 (unsigned int word)
static const char * LookupSpecial (Translator *tr, const char *string, char *text_out)
static const char * LookupCharName (Translator *tr, int c)
int Read4Bytes (FILE *f)
static int LoadSoundFile (const char *fname, int index)
static int LookupSoundicon (int c)
static int LoadSoundFile2 (const char *fname)
static int AnnouncePunctuation (Translator *tr, int c1, int c2, char *buf, int bufix)
static const char * VoiceFromStack ()
static void ProcessParamStack (char *outbuf, int *outix)
static PARAM_STACK * PushParamStack (int tag_type)
static void PopParamStack (int tag_type, char *outbuf, int *outix)
static wchar_t * GetSsmlAttribute (wchar_t *pw, const char *name)
static int attrcmp (const wchar_t *string1, const char *string2)
static int attrlookup (const wchar_t *string1, const MNEM_TAB *mtab)
static int attrnumber (const wchar_t *pw, int default_value, int type)
static int attrcopy_utf8 (char *buf, const wchar_t *pw, int len)
static int attr_prosody_value (int param_type, const wchar_t *pw, int *value_out)
int AddNameData (const char *name, int wide)
void SetVoiceStack (espeak_VOICE *v)
static int GetVoiceAttributes (wchar_t *pw, int tag_type)
static void SetProsodyParameter (int param_type, wchar_t *attr1, PARAM_STACK *sp)
static int ProcessSsmlTag (wchar_t *xml_buf, char *outbuf, int *outix, int n_outbuf, int self_closing)
int ReadClause (Translator *tr, FILE *f_in, char *buf, short *charix, int *charix_top, int n_buf, int *tone_type)
void InitNamedata (void)
void InitText2 (void)
Variables
static const char * xmlbase = ""
static int namedata_ix =0
static int n_namedata = 0
char * namedata = NULL
static FILE * f_input = NULL
static int ungot_char2 = 0
unsigned char * p_textinput
wchar_t * p_wchar_input
static int ungot_char
static const char * ungot_word = NULL
static int end_of_input
static int ignore_text =0
static int clear_skipping_text = 0
int count_characters = 0
static int sayas_mode
static int ssml_ignore_l_angle = 0
static const char * punct_stop = ".:!?"
static const char * punct_close = ")]}>;'\""
static const char * tone_punct_on = "\0016T"
static const char * tone_punct_off = "\001T"
static const unsigned short punct_chars []
static const unsigned int punct_attributes []
static int n_ssml_stack
static SSML_STACK ssml_stack [N_SSML_STACK]
static char current_voice_id [40] = {0}
static int n_param_stack
PARAM_STACK param_stack [N_PARAM_STACK]
static int speech_parameters [N_SPEECH_PARAM]
const int param_defaults [N_SPEECH_PARAM]
static char ignore_if_self_closing [] = {0,1,1,1,1,0,0,0,0,1,1,0,1,0,1,0,0}
static MNEM_TAB ssmltags []
static MNEM_TAB xml_char_mnemonics []
Macro Definition Documentation
#define double (x) ((double)(x))
Referenced by get_distance_str(), if(), MarkerEvent(), navit_autozoom(), osd_odometer_click(), osd_odometer_draw(), osd_route_guard_draw(), png_build_gamma_table(), png_get_cHRM(), png_get_gAMA(), png_init_read_transformations(), rand_str(), route_get_coord_dist(), showStats(), SHPGetSubNodeOffset(), and SHPReallocObjectBufIfNecessary().
#define HTML_BREAK 15
Referenced by ProcessSsmlTag().
#define N_PARAM_STACK 20
Referenced by PushParamStack().
#define N_SSML_STACK 20
#define N_XML_BUF 256
Referenced by ReadClause().
#define N_XML_BUF2 20
Referenced by ReadClause().
#define SSML_AUDIO 11
Referenced by ProcessSsmlTag().
#define SSML_BREAK 13
Referenced by ProcessSsmlTag().
#define SSML_CLOSE 0x10
Referenced by GetVoiceAttributes(), PopParamStack(), and ProcessSsmlTag().
#define SSML_EMPHASIS 12
Referenced by ProcessSsmlTag().
#define SSML_IGNORE_TEXT 14
Referenced by ProcessSsmlTag().
#define SSML_MARK 5
Referenced by ProcessSsmlTag().
#define SSML_PARAGRAPH 7
Referenced by ProcessSsmlTag().
#define SSML_PHONEME 8
#define SSML_PROSODY 3
Referenced by ProcessSsmlTag().
#define SSML_SAYAS 4
Referenced by ProcessSsmlTag().
#define SSML_SENTENCE 6
Referenced by ProcessSsmlTag().
#define SSML_SPEAK 1
Referenced by ProcessSsmlTag().
#define SSML_STYLE 10
Referenced by ProcessSsmlTag().
#define SSML_SUB 9
Referenced by ProcessSsmlTag().
#define SSML_VOICE 2
Referenced by GetVoiceAttributes(), and ProcessSsmlTag().
Function Documentation
int AddNameData (const char * name, int wide)
References n_namedata, namedata, namedata_ix, and NULL.
Referenced by ProcessSsmlTag().
static int AnnouncePunctuation (Translator * tr, int c1, int c2, char * buf, int bufix) static
References c1, CLAUSE_COMMA, CLAUSE_NONE, CLAUSE_SHORTCOMMA, CLAUSE_SHORTFALL, GetC(), LookupCharName(), LookupSoundicon(), lookupwchar(), NULL, option_ssml, p, punct_attributes, punct_chars, punct_close, punct_stop, sprintf(), ssml_ignore_l_angle, strchr_w(), tone_punct_off, tone_punct_on, UngetC(), and ungot_char2.
Referenced by ReadClause().
static int attr_prosody_value (int param_type, const wchar_t * pw, int * value_out) static
References espeakRATE, int, and value.
Referenced by SetProsodyParameter().
static int attrcmp (const wchar_t * string1, const char * string2) static
References NULL.
Referenced by attrlookup(), and ProcessSsmlTag().
static int attrcopy_utf8 (char * buf, const wchar_t * pw, int len) static
References c, NULL, and utf8_out().
Referenced by GetVoiceAttributes(), and ProcessSsmlTag().
static int attrlookup (const wchar_t * string1, const MNEM_TAB * mtab) static
References attrcmp(), MNEM_TAB::mnem, NULL, and value.
Referenced by GetVoiceAttributes(), ProcessSsmlTag(), and SetProsodyParameter().
static int attrnumber (const wchar_t * pw, int default_value, int type) static
References NULL, and value.
Referenced by GetVoiceAttributes(), and ProcessSsmlTag().
int Eof (void)
References end_of_input, f_input, and ungot_char.
Referenced by GetC(), ReadClause(), and TranslateClause().
static int GetC (void) static
References c, c1, c2, Translator::charset_a0, count_characters, Eof(), espeakCHARS_16BIT, espeakCHARS_8BIT, espeakCHARS_AUTO, espeakCHARS_WCHAR, GetC_get(), GetC_unget(), mask, option_multibyte, translator, and ungot_char.
Referenced by AnnouncePunctuation(), and ReadClause().
static int GetC_get (void) static
References c, c2, end_of_input, espeakCHARS_16BIT, espeakCHARS_WCHAR, f_input, NULL, option_multibyte, p_textinput, and p_wchar_input.
Referenced by GetC().
static void GetC_unget (int c) static
References c, end_of_input, f_input, NULL, and p_textinput.
Referenced by GetC().
static wchar_t* GetSsmlAttribute (wchar_t * pw, const char * name) static
References NULL.
Referenced by GetVoiceAttributes(), and ProcessSsmlTag().
static int GetVoiceAttributes (wchar_t * pw, int tag_type) static
References attrcopy_utf8(), attrlookup(), attrnumber(), CLAUSE_BIT_VOICE, current_voice_id, GetSsmlAttribute(), SSML_STACK::language, n_ssml_stack, name, NULL, SSML_CLOSE, SSML_VOICE, SSML_STACK::tag_type, SSML_STACK::voice_age, SSML_STACK::voice_gender, SSML_STACK::voice_name, SSML_STACK::voice_variant, and VoiceFromStack().
Referenced by ProcessSsmlTag().
void InitNamedata (void)
References n_namedata, namedata, namedata_ix, and NULL.
Referenced by initialise(), and InitText().
void InitText2 (void)
References clear_skipping_text, count_characters, current_voice_id, espeakCAPITALS, espeakPUNCTUATION, ignore_text, n_param_stack, N_SPEECH_PARAM, n_ssml_stack, NULL, option_capitals, option_punctuation, sayas_mode, speech_parameters, SSML_STACK::tag_type, ungot_char, and xmlbase.
Referenced by InitText().
static int LoadSoundFile (const char * fname, int index) static
References close(), command(), SOUND_ICON::data, data, SOUND_ICON::filename, fprintf(), GetFileLength(), length, SOUND_ICON::length, NULL, p, path_home, PATHSEP, Read4Bytes(), samplerate, SEEK_SET, soundicon_tab, and sprintf().
Referenced by LoadSoundFile2(), and LookupSoundicon().
static int LoadSoundFile2 (const char * fname) static
References filename, SOUND_ICON::filename, LoadSoundFile(), N_SOUNDICON_SLOTS, n_soundicon_tab, NULL, and soundicon_tab.
Referenced by ProcessSsmlTag().
static const char* LookupCharName (Translator * tr, int c) static
References DecodePhonemes(), L, LookupDictList(), NULL, option_phoneme_input, voice_t::phoneme_tab_ix, SelectPhonemeTable(), SetTranslator2(), SetWordStress(), sprintf(), TranslateRules(), translator2, Translator::translator_name, utf8_out(), voice, and WordToString2().
Referenced by AnnouncePunctuation().
static int LookupSoundicon (int c) static
References length, LoadSoundFile(), N_SOUNDICON_SLOTS, n_soundicon_tab, name, NULL, and soundicon_tab.
Referenced by AnnouncePunctuation().
static const char* LookupSpecial (Translator * tr, const char * string, char * text_out) static
References DecodePhonemes(), LookupDictList(), NULL, option_phoneme_input, SetWordStress(), and sprintf().
Referenced by ReadClause().
static void PopParamStack (int tag_type, char * outbuf, int * outix) static
References n_param_stack, ProcessParamStack(), SSML_CLOSE, and type.
Referenced by ProcessSsmlTag().
static void ProcessParamStack (char * outbuf, int * outix) static
References CTRL_EMBEDDED, espeakCAPITALS, espeakEMPHASIS, espeakPITCH, espeakPUNCTUATION, espeakRANGE, espeakRATE, espeakVOLUME, n_param_stack, N_SPEECH_PARAM, option_capitals, option_punctuation, PARAM_STACK::parameter, speech_parameters, sprintf(), and value.
Referenced by PopParamStack(), and ProcessSsmlTag().
static int ProcessSsmlTag (wchar_t * xml_buf, char * outbuf, int * outix, int n_outbuf, int self_closing) static
References AddNameData(), attrcmp(), attrcopy_utf8(), attrlookup(), attrnumber(), c, CLAUSE_COLON, CLAUSE_NONE, CLAUSE_PARAGRAPH, CLAUSE_PERIOD, CLAUSE_VOICE, clear_skipping_text, CTRL_EMBEDDED, espeakCAPITALS, espeakEMPHASIS, espeakPUNCTUATION, espeakRANGE, espeakRATE, espeakSILENCE, espeakVOLUME, GetSsmlAttribute(), GetVoiceAttributes(), HTML_BREAK, ignore_text, Translator::langopts, LoadSoundFile2(), LookupMnem(), n_ssml_stack, namedata, NULL, PARAM_STACK::parameter, PopParamStack(), ProcessParamStack(), PushParamStack(), SAYAS_CHARS, SAYAS_DIGITS, SAYAS_DIGITS1, SAYAS_GLYPHS, SAYAS_KEY, sayas_mode, SAYAS_SINGLE_CHARS, SetProsodyParameter(), skip_marker, speed, SPEED_FACTORS::speed_factor1, sprintf(), SSML_AUDIO, SSML_BREAK, SSML_CLOSE, SSML_EMPHASIS, SSML_IGNORE_TEXT, SSML_MARK, SSML_PARAGRAPH, SSML_PROSODY, SSML_SAYAS, SSML_SENTENCE, SSML_SPEAK, SSML_STYLE, SSML_SUB, SSML_VOICE, SSML_STACK::tag_type, LANGUAGE_OPTIONS::tone_language, translator, uri_callback, value, and xmlbase.
Referenced by ReadClause().
static PARAM_STACK* PushParamStack (int tag_type) static
References N_PARAM_STACK, n_param_stack, N_SPEECH_PARAM, PARAM_STACK::parameter, and PARAM_STACK::type.
Referenced by ProcessSsmlTag().
int Read4Bytes (FILE * f)
References c.
Referenced by LoadMbrolaTable(), and LoadSoundFile().
int ReadClause (Translator * tr, FILE * f_in, char * buf, short * charix, int * charix_top, int n_buf, int * tone_type)
References AnnouncePunctuation(), c1, c2, CHAR_EMPHASIS, CLAUSE_BIT_VOICE, CLAUSE_COLON, CLAUSE_EOF, CLAUSE_EXCLAMATION, Translator::clause_lower_count, CLAUSE_NONE, CLAUSE_PARAGRAPH, CLAUSE_PERIOD, CLAUSE_QUESTION, clause_start_char, Translator::clause_upper_count, CLAUSE_VOICE, clear_skipping_text, count_characters, CTRL_EMBEDDED, ctrl_embedded, current_voice_id, end_character_position, end_of_input, Eof(), espeakSILENCE, f_input, GetC(), ignore_text, IsAlpha(), IsBracket(), Translator::langopts, LookupMnem(), LookupSpecial(), lookupwchar(), N_XML_BUF, N_XML_BUF2, NULL, LANGUAGE_OPTIONS::numbers, option_capitals, option_linelength, option_phoneme_input, option_punctlist, option_punctuation, option_ssml, p, ProcessSsmlTag(), punct_attributes, punct_chars, PUNCT_IN_WORD, SAYAS_KEY, sayas_mode, SAYAS_SINGLE_CHARS, skip_characters, skipping_text, speech_parameters, sprintf(), ssml_ignore_l_angle, tone_punct_off, tone_punct_on, Translator::translator_name, UngetC(), ungot_char, ungot_char2, ungot_word, and utf8_out().
Referenced by TranslateClause().
static void SetProsodyParameter (int param_type, wchar_t * attr1, PARAM_STACK * sp) static
References attr_prosody_value(), attrlookup(), NULL, PARAM_STACK::parameter, speech_parameters, and value.
Referenced by ProcessSsmlTag().
void SetVoiceStack (espeak_VOICE * v)
References espeak_VOICE::age, espeak_VOICE::gender, SSML_STACK::language, espeak_VOICE::languages, espeak_VOICE::name, NULL, espeak_VOICE::variant, SSML_STACK::voice_age, SSML_STACK::voice_gender, SSML_STACK::voice_name, and SSML_STACK::voice_variant.
Referenced by initialise(), SetVoiceByName(), and SetVoiceByProperties().
int towlower2 (unsigned int c)
References L, translator, and Translator::translator_name.
Referenced by TranslateClause(), and TranslateLetter().
static void UngetC (int c) static
References c, and ungot_char.
Referenced by AnnouncePunctuation(), and ReadClause().
static const char* VoiceFromStack () static
References espeak_VOICE::age, espeak_VOICE::gender, espeak_VOICE::identifier, SSML_STACK::language, espeak_VOICE::languages, n_ssml_stack, espeak_VOICE::name, NULL, SelectVoice(), SelectVoiceByName(), espeak_VOICE::variant, SSML_STACK::voice_age, SSML_STACK::voice_gender, SSML_STACK::voice_name, and SSML_STACK::voice_variant.
Referenced by GetVoiceAttributes().
static const char* WordToString2 (unsigned int word) static
References buf, and p.
Referenced by LookupCharName().
Variable Documentation
int clear_skipping_text = 0 static
Referenced by InitText2(), ProcessSsmlTag(), and ReadClause().
int count_characters = 0
Referenced by DoEmbedded(), Generate(), GetC(), InitText2(), ReadClause(), and TranslateClause().
char current_voice_id[40] = {0} static
Referenced by GetVoiceAttributes(), InitText2(), and ReadClause().
int end_of_input static
Referenced by Eof(), GetC_get(), GetC_unget(), and ReadClause().
FILE* f_input = NULL static
Referenced by Eof(), GetC_get(), GetC_unget(), and ReadClause().
char ignore_if_self_closing[] = {0,1,1,1,1,0,0,0,0,1,1,0,1,0,1,0,0} static
int ignore_text =0 static
Referenced by InitText2(), ProcessSsmlTag(), and ReadClause().
int n_namedata = 0 static
Referenced by AddNameData(), and InitNamedata().
int n_param_stack static
Referenced by InitText2(), PopParamStack(), ProcessParamStack(), and PushParamStack().
int n_ssml_stack static
Referenced by GetVoiceAttributes(), InitText2(), ProcessSsmlTag(), and VoiceFromStack().
char* namedata = NULL
Referenced by AddNameData(), InitNamedata(), MarkerEvent(), and ProcessSsmlTag().
int namedata_ix =0 static
Referenced by AddNameData(), and InitNamedata().
unsigned char* p_textinput
Referenced by GetC_get(), GetC_unget(), and TranslateClause().
wchar_t* p_wchar_input
Referenced by GetC_get(), and TranslateClause().
const int param_defaults[N_SPEECH_PARAM]
Initial value:
= {
   0,
  170,
  100,
   50,
   50,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
}
Referenced by espeak_GetParameter(), espeak_Initialize(), initialise(), and SetParameter().
PARAM_STACK param_stack[N_PARAM_STACK]
Referenced by espeak_GetParameter(), espeak_Initialize(), initialise(), and SetParameter().
const unsigned int punct_attributes[] static
Referenced by AnnouncePunctuation(), and ReadClause().
const unsigned short punct_chars[] static
Referenced by AnnouncePunctuation(), and ReadClause().
const char* punct_close = ")]}>;'\"" static
Referenced by AnnouncePunctuation().
const char* punct_stop = ".:!?" static
Referenced by AnnouncePunctuation().
int sayas_mode static
Referenced by InitText2(), ProcessSsmlTag(), and ReadClause().
int speech_parameters[N_SPEECH_PARAM] static
Referenced by InitText2(), ProcessParamStack(), ReadClause(), and SetProsodyParameter().
int ssml_ignore_l_angle = 0 static
Referenced by AnnouncePunctuation(), and ReadClause().
SSML_STACK ssml_stack[N_SSML_STACK] static
MNEM_TAB ssmltags[] static
Initial value:
= {
        {"speak", SSML_SPEAK},
        {"voice", SSML_VOICE},
        {"prosody", SSML_PROSODY},
        {"say-as", SSML_SAYAS},
        {"mark", SSML_MARK},
        {"s", SSML_SENTENCE},
        {"p", SSML_PARAGRAPH},
        {"phoneme", SSML_PHONEME},
        {"sub", SSML_SUB},
        {"tts:style", SSML_STYLE},
        {"audio", SSML_AUDIO},
        {"emphasis", SSML_EMPHASIS},
        {"break", SSML_BREAK},
        {"metadata", SSML_IGNORE_TEXT},
        {"br", HTML_BREAK},
        {"li", HTML_BREAK},
        {"img", HTML_BREAK},
        {"td", HTML_BREAK},
        {"h1", SSML_PARAGRAPH},
        {"h2", SSML_PARAGRAPH},
        {"h3", SSML_PARAGRAPH},
        {"h4", SSML_PARAGRAPH},
        {"hr", SSML_PARAGRAPH},
        {"script", SSML_IGNORE_TEXT},
        {"style", SSML_IGNORE_TEXT},
        {NULL,0}}
const char* tone_punct_off = "\001T" static
Referenced by AnnouncePunctuation(), and ReadClause().
const char* tone_punct_on = "\0016T" static
Referenced by AnnouncePunctuation(), and ReadClause().
int ungot_char static
Referenced by Eof(), GetC(), InitText2(), ReadClause(), and UngetC().
int ungot_char2 = 0 static
Referenced by AnnouncePunctuation(), and ReadClause().
const char* ungot_word = NULL static
Referenced by ReadClause().
MNEM_TAB xml_char_mnemonics[] static
Initial value:
= {
        {"gt",'>'},
        {"lt",'<'},
        {"amp", '&'},
        {"quot", '"'},
        {"nbsp", ' '},
        {"apos", '\''},
        {NULL,-1}}
const char* xmlbase = "" static
Referenced by InitText2(), and ProcessSsmlTag().