navit: support/libc/read.c File Reference
read.c File Reference
#include <windows.h>
#include <unistd.h>
Functions
int _read (int fildes, void *buf, unsigned int bufsize)
int read (int fildes, void *buf, unsigned int bufsize)
Function Documentation
int _read (int fildes, void * buf, unsigned int bufsize)
References NULL.
Referenced by read().
int read (int fildes, void * buf, unsigned int bufsize)
References _read().
Referenced by _nl_load_domain(), command_interpreter(), ezxml_parse_fd(), file_data_read(), file_data_read_compressed(), file_data_read_special(), j1850_idle(), pedestrian_read_tilt(), pedestrian_setup_tilt(), plugin_init(), process_boundaries_setup(), send_and_read(), spawn_xkbd(), and vehicle_file_io().