navit: support/libc/rename.c File Reference
rename.c File Reference
#include <windows.h>
Functions
int rename (const char *from, const char *to)
Function Documentation
int rename (const char * from, const char * to)
Referenced by bookmarks_store_bookmarks_to_file(), draw_mode(), gui_internal_set(), save_map_csv(), and tempfile_rename().