navit: roadprofile.h File Reference
roadprofile.h File Reference
#include "navit.h"
Data Structures
struct roadprofile
Functions
struct roadprofile * roadprofile_new (struct attr *parent, struct attr **attrs)
int roadprofile_get_attr (struct roadprofile *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int roadprofile_set_attr (struct roadprofile *this_, struct attr *attr)
int roadprofile_add_attr (struct roadprofile *this_, struct attr *attr)
int roadprofile_remove_attr (struct roadprofile *this_, struct attr *attr)
struct attr_iter * roadprofile_attr_iter_new (void *unused)
void roadprofile_attr_iter_destroy (struct attr_iter *iter)
Function Documentation
roadprofile_add_attr()
int roadprofile_add_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_add_attr().
roadprofile_attr_iter_destroy()
void roadprofile_attr_iter_destroy (struct attr_iter * iter)
References attr_iter::iter.
Referenced by request_roadprofile_attr_iter_destroy().
roadprofile_attr_iter_new()
struct attr_iter * roadprofile_attr_iter_new (void * unused)
Referenced by request_roadprofile_attr_iter().
roadprofile_get_attr()
int roadprofile_get_attr (struct roadprofile * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), and type.
Referenced by request_roadprofile_get_attr().
roadprofile_new()
struct roadprofile * roadprofile_new (struct attr * parent, struct attr ** attrs)
References attr_list_dup(), attr::attrs, navit_object_ref(), roadprofile_func, and roadprofile_set_attr_do().
roadprofile_remove_attr()
int roadprofile_remove_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_remove_attr().
roadprofile_set_attr()
int roadprofile_set_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_set_attr(), and roadprofile_set_attr_do().
Referenced by request_roadprofile_set_attr().