navit: roadprofile.c File Reference
roadprofile.c File Reference
#include <glib.h>
#include "debug.h"
#include "item.h"
#include "xmlconfig.h"
#include "roadprofile.h"
Functions
static void roadprofile_set_attr_do (struct roadprofile *this, struct attr *attr)
struct roadprofile * roadprofile_new (struct attr *parent, struct attr **attrs)
int roadprofile_get_attr (struct roadprofile *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int roadprofile_set_attr (struct roadprofile *this_, struct attr *attr)
int roadprofile_add_attr (struct roadprofile *this_, struct attr *attr)
int roadprofile_remove_attr (struct roadprofile *this_, struct attr *attr)
struct attr_iter * roadprofile_attr_iter_new (void *unused)
void roadprofile_attr_iter_destroy (struct attr_iter *iter)
static struct roadprofile * roadprofile_dup (struct roadprofile *this_)
static void roadprofile_destroy (struct roadprofile *this_)
Variables
struct object_func roadprofile_func
Function Documentation
roadprofile_add_attr()
int roadprofile_add_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_add_attr().
roadprofile_attr_iter_destroy()
void roadprofile_attr_iter_destroy (struct attr_iter * iter)
References attr_iter::iter.
Referenced by request_roadprofile_attr_iter_destroy().
roadprofile_attr_iter_new()
struct attr_iter* roadprofile_attr_iter_new (void * unused)
Referenced by request_roadprofile_attr_iter().
roadprofile_destroy()
static void roadprofile_destroy (struct roadprofile * this_) static
References attr_list_free().
roadprofile_dup()
static struct roadprofile* roadprofile_dup (struct roadprofile * this_) static
References attr_list_dup().
roadprofile_get_attr()
int roadprofile_get_attr (struct roadprofile * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), and type.
Referenced by request_roadprofile_get_attr().
roadprofile_new()
struct roadprofile* roadprofile_new (struct attr * parent, struct attr ** attrs)
References attr_list_dup(), attr::attrs, navit_object_ref(), roadprofile_func, and roadprofile_set_attr_do().
roadprofile_remove_attr()
int roadprofile_remove_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_remove_attr().
roadprofile_set_attr()
int roadprofile_set_attr (struct roadprofile * this_, struct attr * attr)
References attr_generic_set_attr(), and roadprofile_set_attr_do().
Referenced by request_roadprofile_set_attr().
roadprofile_set_attr_do()
static void roadprofile_set_attr_do (struct roadprofile * this, struct attr * attr) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References attr::num, attr::type, and attr::u.
Referenced by roadprofile_new(), and roadprofile_set_attr().
Variable Documentation
roadprofile_func
struct object_func roadprofile_func
Initial value:
= {
    attr_roadprofile,
    (object_func_new)roadprofile_new,
    (object_func_get_attr)roadprofile_get_attr,
    (object_func_iter_new)roadprofile_attr_iter_new,
    (object_func_iter_destroy)roadprofile_attr_iter_destroy,
    (object_func_set_attr)roadprofile_set_attr,
    (object_func_add_attr)roadprofile_add_attr,
    (object_func_remove_attr)roadprofile_remove_attr,
    (object_func_init)NULL,
    (object_func_destroy)roadprofile_destroy,
    (object_func_dup)roadprofile_dup,
    (object_func_ref)navit_object_ref,
    (object_func_unref)navit_object_unref,
}
Referenced by object_func_lookup(), and roadprofile_new().