navit: route.c File Reference
route.c File Reference
Contains code related to finding a route from a position to a destination.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "navit_nls.h"
#include "glib_slice.h"
#include "config.h"
#include "point.h"
#include "graphics.h"
#include "profile.h"
#include "coord.h"
#include "projection.h"
#include "item.h"
#include "xmlconfig.h"
#include "map.h"
#include "mapset.h"
#include "route.h"
#include "track.h"
#include "transform.h"
#include "plugin.h"
#include "fib.h"
#include "event.h"
#include "callback.h"
#include "vehicle.h"
#include "vehicleprofile.h"
#include "roadprofile.h"
#include "debug.h"
Data Structures
struct map_priv
Represents the map from a single binfile.
struct route_graph_point
A point in the route graph.
struct route_segment_data
A segment in the route graph or path.
struct size_weight_limit
struct route_graph_segment_data
struct route_graph_segment
A segment in the route graph.
struct route_traffic_distortion
A traffic distortion.
struct route_path_segment
A segment in the route path.
struct route_info
Usually represents a destination or position.
struct route_path
A complete route path.
struct route
A complete route.
struct route_graph
A complete route graph.
struct route_graph_point_iterator
Iterator to iterate through all route graph segments in a route graph point.
struct attr_iter
struct map_rect_priv
Functions
static struct route_info * route_find_nearest_street (struct vehicleprofile *vehicleprofile, struct mapset *ms, struct pcoord *pc)
Finds the nearest street to a given coordinate.
static struct route_graph_point * route_graph_get_point (struct route_graph *this, struct coord *c)
Gets the first route_graph_point with the specified coordinates.
static void route_graph_update (struct route *this, struct callback *cb, int async)
Updates the route graph.
static void route_graph_build_done (struct route_graph *rg, int cancel)
Releases all resources needed to build the route graph.
static struct route_path * route_path_new (struct route_graph *this, struct route_path *oldpath, struct route_info *pos, struct route_info *dst, struct vehicleprofile *profile)
Creates a new route path.
static void route_process_street_graph (struct route_graph *this, struct item *item, struct vehicleprofile *profile)
Adds an item to the route graph.
static void route_graph_destroy (struct route_graph *this)
Destroys a route graph.
static void route_path_update (struct route *this, int cancel, int async)
Updates the route graph and the route path if something changed with the route.
static int route_time_seg (struct vehicleprofile *profile, struct route_segment_data *over, struct route_traffic_distortion *dist)
Returns the time needed to travel along a segment, or.
static void route_graph_flood (struct route_graph *this, struct route_info *dst, struct vehicleprofile *profile, struct callback *cb)
Calculates the routing costs for each point.
static void route_graph_reset (struct route_graph *this)
Resets all nodes.
static enum projection route_projection (struct route *route)
Returns the projection used for this route.
static struct
route_graph_point_iterator rp_iterator_new (struct route_graph_point *p)
Creates a new graph point iterator.
static struct route_graph_segment * rp_iterator_next (struct route_graph_point_iterator *it)
Gets the next segment connected to a route graph point from an iterator.
static int rp_iterator_end (struct route_graph_point_iterator *it)
Checks if the last segment returned from a route_graph_point_iterator comes from the end.
static void route_path_get_distances (struct route_path *path, struct coord *c, int count, int *distances)
void route_get_distances (struct route *this, struct coord *c, int count, int *distances)
static void route_path_destroy (struct route_path *this, int recurse)
Destroys a route_path.
struct route * route_new (struct attr *parent, struct attr **attrs)
Creates a completely new route structure.
struct route * route_dup (struct route *orig)
Duplicates a route object.
static int route_check_roundabout (struct route_graph_segment *seg, int level, int direction, struct route_graph_segment *origin)
Checks if a segment is part of a roundabout.
void route_set_mapset (struct route *this, struct mapset *ms)
Sets the mapset of the route passwd.
void route_set_profile (struct route *this, struct vehicleprofile *prof)
Sets the vehicle profile of a route.
struct mapset * route_get_mapset (struct route *this)
Returns the mapset of the route passed.
struct route_info * route_get_pos (struct route *this)
Returns the current position within the route passed.
struct route_info * route_get_dst (struct route *this)
Returns the destination of the route passed.
int route_get_path_set (struct route *this)
Checks if the path is calculated for the route passed.
int route_contains (struct route *this, struct item *item)
Checks if the route passed contains a certain item within the route path.
static struct route_info * route_next_destination (struct route *this)
int route_destination_reached (struct route *this)
Checks if a route has reached its destination.
static struct route_info * route_previous_destination (struct route *this)
Returns the position from which to route to the current destination of the route.
static void route_path_update_done (struct route *this, int new_graph)
Updates or recreates the route graph.
static void route_path_update_flags (struct route *this, enum route_path_flags flags)
Updates the route graph and the route path if something changed with the route.
static void route_info_distances (struct route_info *ri, enum projection pro)
This will calculate all the distances stored in a route_info.
static int route_set_position_flags (struct route *this, struct pcoord *pos, enum route_path_flags flags)
This sets the current position of the route passed.
void route_set_position (struct route *this, struct pcoord *pos)
This sets the current position of the route passed.
void route_set_position_from_tracking (struct route *this, struct tracking *tracking, enum projection pro)
Sets a route's current position based on coordinates from tracking.
struct map_selection * route_rect (int order, struct coord *c1, struct coord *c2, int rel, int abs)
Returns a single map selection.
static struct map_selection * route_rect_add (struct map_selection *sel, int order, struct coord *c1, struct coord *c2, int rel, int abs)
Appends a map selection to the selection list. Selection list may be NULL.
static struct map_selection * route_calc_selection (struct coord *c, int count, struct vehicleprofile *profile)
Returns a list of map selections useable to create a route graph.
static void route_free_selection (struct map_selection *sel)
Destroys a list of map selections.
static void route_clear_destinations (struct route *this_)
void route_set_destinations (struct route *this, struct pcoord *dst, int count, int async)
Sets the destination of a route.
int route_get_destinations (struct route *this, struct pcoord *pc, int count)
int route_get_destination_count (struct route *this)
Get the destinations count for the route.
char * route_get_destination_description (struct route *this, int n)
Returns a description for a waypoint as (type or street_name_systematic) + (label or WayID[osm_wayid])
void route_set_destination (struct route *this, struct pcoord *dst, int async)
Start a route given set of coordinates.
void route_append_destination (struct route *this, struct pcoord *dst, int async)
Append a waypoint to the route.
void route_remove_nth_waypoint (struct route *this, int n)
Remove the nth waypoint of the route.
void route_remove_waypoint (struct route *this)
static struct route_graph_point * route_graph_get_point_next (struct route_graph *this, struct coord *c, struct route_graph_point *last)
Gets the next route_graph_point with the specified coordinates.
static struct route_graph_point * route_graph_get_point_last (struct route_graph *this, struct coord *c)
Gets the last route_graph_point with the specified coordinates.
static struct route_graph_point * route_graph_point_new (struct route_graph *this, struct coord *f)
Create a new point for the route graph with the specified coordinates.
static struct route_graph_point * route_graph_add_point (struct route_graph *this, struct coord *f)
Inserts a point into the route graph at the specified coordinates.
static void route_graph_free_points (struct route_graph *this)
Frees all the memory used for points in the route graph passed.
static void * route_segment_data_field_pos (struct route_segment_data *seg, enum attr_type type)
Returns the position of a certain field appended to a route graph segment.
static int route_segment_data_size (int flags)
Calculates the size of a route_segment_data struct with given flags.
static int route_graph_segment_is_duplicate (struct route_graph_point *start, struct route_graph_segment_data *data)
static void route_graph_add_segment (struct route_graph *this, struct route_graph_point *start, struct route_graph_point *end, struct route_graph_segment_data *data)
Inserts a new segment into the route graph.
static int get_item_seg_coords (struct item *i, struct coord *c, int max, struct coord *start, struct coord *end)
Gets all the coordinates of an item.
static struct route_path_segment * route_extract_segment_from_path (struct route_path *path, struct item *item, int offset)
Returns and removes one segment from a path.
static void route_path_add_segment (struct route_path *this, struct route_path_segment *segment)
Adds a segment and the end of a path.
static void route_path_add_line (struct route_path *this, struct coord *start, struct coord *end, int len)
Adds a two coordinate line to a path.
static int route_path_add_item_from_graph (struct route_path *this, struct route_path *oldpath, struct route_graph_segment *rgs, int dir, struct route_info *pos, struct route_info *dst)
Inserts a new item into the path.
static void route_graph_free_segments (struct route_graph *this)
Destroys all segments of a route graph.
static int route_seg_speed (struct vehicleprofile *profile, struct route_segment_data *over, struct route_traffic_distortion *dist)
Returns the estimated speed on a segment, or 0 for an impassable segment.
static int route_get_traffic_distortion (struct route_graph_segment *seg, struct route_traffic_distortion *ret)
Returns the traffic distortion for a segment.
static int route_through_traffic_allowed (struct vehicleprofile *profile, struct route_graph_segment *seg)
static int route_value_seg (struct vehicleprofile *profile, struct route_graph_point *from, struct route_graph_segment *over, int dir)
Returns the "cost" of driving from point.
static int route_graph_segment_match (struct route_graph_segment *s1, struct route_graph_segment *s2)
static void route_graph_set_traffic_distortion (struct route_graph *this, struct route_graph_segment *seg, int delay)
Sets or clears a traffic distortion for a segment.
static void route_process_traffic_distortion (struct route_graph *this, struct item *item)
Adds a route distortion item to the route graph.
static void route_process_turn_restriction (struct route_graph *this, struct item *item)
Adds a turn restriction item to the route graph.
static struct route_graph_segment * route_graph_get_segment (struct route_graph *graph, struct street_data *sd, struct route_graph_segment *last)
Gets the next route_graph_segment belonging to the specified street.
static struct route_path * route_path_new_offroad (struct route_graph *this, struct route_info *pos, struct route_info *dst)
Starts an "offroad" path.
struct coord route_get_coord_dist (struct route *this_, int dist)
Returns a coordinate at a given distance.
static int route_graph_build_next_map (struct route_graph *rg)
static int is_turn_allowed (struct route_graph_point *p, struct route_graph_segment *from, struct route_graph_segment *to)
static void route_graph_clone_segment (struct route_graph *this, struct route_graph_segment *s, struct route_graph_point *start, struct route_graph_point *end, int flags)
static void route_graph_process_restriction_segment (struct route_graph *this, struct route_graph_point *p, struct route_graph_segment *s, int dir)
static void route_graph_process_restriction_point (struct route_graph *this, struct route_graph_point *p)
static void route_graph_process_restrictions (struct route_graph *this)
static void route_graph_build_idle (struct route_graph *rg, struct vehicleprofile *profile)
static struct route_graph * route_graph_build (struct mapset *ms, struct coord *c, int count, struct callback *done_cb, int async, struct vehicleprofile *profile)
Builds a new route graph from a mapset.
static void route_graph_update_done (struct route *this, struct callback *cb)
struct street_data * street_get_data (struct item *item)
Gets street data for an item.
struct street_data * street_data_dup (struct street_data *orig)
Copies street data.
void street_data_free (struct street_data *sd)
Frees street data.
void route_info_free (struct route_info *inf)
Destroys a route_info.
struct street_data * route_info_street (struct route_info *rinf)
Returns street data for a route info.
struct route_crossings * route_crossings_get (struct route *this, struct coord *c)
static void rm_coord_rewind (void *priv_data)
static void rm_attr_rewind (void *priv_data)
static int rm_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int rm_coord_get (void *priv_data, struct coord *c, int count)
static void rp_attr_rewind (void *priv_data)
static int rp_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static int rp_coord_get (void *priv_data, struct coord *c, int count)
Returns the coordinates of a route graph item.
static void rp_destroy (struct map_priv *priv)
static void rm_destroy (struct map_priv *priv)
static struct map_rect_priv * rm_rect_new (struct map_priv *priv, struct map_selection *sel)
static struct map_rect_priv * rp_rect_new (struct map_priv *priv, struct map_selection *sel)
Opens a new map rectangle on the route graph's map.
static void rm_rect_destroy (struct map_rect_priv *mr)
static struct item * rp_get_item (struct map_rect_priv *mr)
static struct item * rp_get_item_byid (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct item * rm_get_item (struct map_rect_priv *mr)
static struct item * rm_get_item_byid (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct map_priv * route_map_new_helper (struct map_methods *meth, struct attr **attrs, int graph)
static struct map_priv * route_map_new (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
static struct map_priv * route_graph_map_new (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
static struct map * route_get_map_helper (struct route *this_, struct map **map, char *type, char *description)
struct map * route_get_map (struct route *this_)
Returns a new map containing the route path.
struct map * route_get_graph_map (struct route *this_)
Returns a new map containing the route graph.
enum route_path_flags route_get_flags (struct route *this_)
Returns the flags for the route.
int route_has_graph (struct route *this_)
Whether the route has a valid graph.
void route_set_projection (struct route *this_, enum projection pro)
int route_set_attr (struct route *this_, struct attr *attr)
int route_add_attr (struct route *this_, struct attr *attr)
int route_remove_attr (struct route *this_, struct attr *attr)
int route_get_attr (struct route *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
struct attr_iter * route_attr_iter_new (void)
void route_attr_iter_destroy (struct attr_iter *iter)
void route_init (void)
void route_destroy (struct route *this_)
Variables
int debug_route =0
struct map_selection * route_selection
static struct item_methods methods_route_item
static struct item_methods methods_point_item
static struct map_methods route_meth
static struct map_methods route_graph_meth
struct object_func route_func
Detailed Description
Contains code related to finding a route from a position to a destination.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. Routing uses segments, points and items. Items are items from the map: Streets, highways, etc. Segments represent such items, or parts of it. Generally, a segment is a driveable path. An item can be represented by more than one segment - in that case it is "segmented". Each segment has an "offset" associated, that indicates at which position in a segmented item this segment is - a segment representing a not-segmented item always has the offset 1. A point is located at the end of segments, often connecting several segments.
The code in this file will make navit find a route between a position and a destination. It accomplishes this by first building a "route graph". This graph contains segments and points.
After building this graph in route_graph_build(), the function route_graph_flood() assigns every point and segment a "value" which represents the "costs" of traveling from this point to the destination. This is done by Dijkstra's algorithm.
When the graph is built a "route path" is created, which is a path in this graph from a given position to the destination determined at time of building the graph.
Function Documentation
static int get_item_seg_coords (struct item * i, struct coord * c, int max, struct coord * start, struct coord * end) static
Gets all the coordinates of an item.
This will get all the coordinates of the item i and return them in c, up to max coordinates. Additionally it is possible to limit the coordinates returned to all the coordinates of the item between the two coordinates start end end.
Make sure that whatever c points to has enough memory allocated to hold max coordinates!
Parameters
i The item to get the coordinates of
c Pointer to memory allocated for holding the coordinates
max Maximum number of coordinates to return
start First coordinate to get
end Last coordinate to get
Returns
The number of coordinates returned
References c1, item::id_hi, item::id_lo, item, item_coord_get(), item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), NULL, p, coord::x, and coord::y.
Referenced by route_path_add_item_from_graph().
static int is_turn_allowed (struct route_graph_point * p, struct route_graph_segment * from, struct route_graph_segment * to) static
References route_graph_point::c, route_graph_segment::data, dbg, route_graph_point::end, route_graph_segment::end, route_graph_segment::end_next, item::id_hi, item::id_lo, route_segment_data::item, item_is_equal, item_to_name(), lvl_debug, next, route_graph_point::start, route_graph_segment::start, route_graph_segment::start_next, item::type, coord::x, and coord::y.
Referenced by route_graph_process_restriction_segment().
static int rm_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References AF_SPEED_LIMIT, map_rect_priv::attr_next, route_path_segment::data, map_rect_priv::dest, route::destinations, route_path_segment::direction, route_segment_data::flags, g_free(), g_list_position(), g_strdup_printf(), route_segment_data::item, map_rect_priv::item, attr::item, route_segment_data::len, item::map, map_rect_priv::mpriv, NULL, attr::num, route::reached_destinations_count, map_priv::route, attr::route, route_seg_speed(), route_time_seg(), map_rect_priv::seg, map_rect_priv::str, attr::str, item::type, attr::type, attr::u, and route::vehicleprofile.
static void rm_attr_rewind (void * priv_data) static
References map_rect_priv::attr_next.
Referenced by rm_get_item().
static int rm_coord_get (void * priv_data, struct coord * c, int count) static
References route_info::c, route_path_segment::c, _GList::data, dbg, map_rect_priv::dest, i, map_rect_priv::item, map_rect_priv::last_coord, lvl_debug, map_rect_priv::mpriv, route_path_segment::ncoords, route::pos, projection_mg, projection_none, map_priv::route, route_get_dst(), route_projection(), map_rect_priv::seg, transform_from_to(), and item::type.
static void rm_coord_rewind (void * priv_data) static
References map_rect_priv::last_coord.
Referenced by rp_get_item().
static void rm_destroy (struct map_priv * priv) static
References g_free().
static struct item* rm_get_item (struct map_rect_priv * mr) static
References map_rect_priv::dest, route::destinations, route_info::dir, g_free(), g_list_next, route_path::in_use, map_rect_priv::item, item_id_from_ptr(), map_rect_priv::last_coord, map_rect_priv::mpriv, route_path_segment::next, route_path::next, NULL, p, route_path::path, map_rect_priv::path, route::pos, rm_attr_rewind(), map_priv::route, map_rect_priv::seg, map_rect_priv::seg_next, route_info::street_direction, and item::type.
Referenced by rm_get_item_byid().
static struct item* rm_get_item_byid (struct map_rect_priv * mr, int id_hi, int id_lo) static
References item::id_hi, item::id_lo, NULL, and rm_get_item().
static void rm_rect_destroy (struct map_rect_priv * mr) static
References map_rect_priv::coord_sel, g_free(), route_path::in_use, map_rect_priv::mpriv, map_rect_priv::path, map_priv::route, route_path_update_done(), route::route_status, route_status_destination_set, map_rect_priv::str, and route_path::update_required.
static struct map_rect_priv* rm_rect_new (struct map_priv * priv, struct map_selection * sel) static
References dbg, g_new0, route_path::in_use, map_rect_priv::item, lvl_debug, item::meth, methods_route_item, map_rect_priv::mpriv, NULL, route_path::path, map_rect_priv::path, route::path2, item::priv_data, map_priv::route, route_get_dst(), route_get_pos(), map_rect_priv::seg_next, and item::type.
int route_add_attr (struct route * this_, struct attr * attr)
References attr::callback, callback_list_add(), route::cbl2, attr::type, and attr::u.
Referenced by gui_gtk_init(), navigation_set_route(), navit_init(), and request_route_add_attr().
void route_append_destination (struct route * this, struct pcoord * dst, int async)
Append a waypoint to the route.
This appends a waypoint to the current route, targetting the street nearest to the coordinates passed, and updates the route.
Parameters
this The route to set the destination for
dst Coordinates of the new waypoint
async If set, do routing asynchronously
References g_list_append(), NULL, pcoord::pro, route_find_nearest_street(), route_get_dst(), route_graph_destroy(), route_info_distances(), route_path_update(), and route_set_destinations().
Referenced by navit_set_destination().
void route_attr_iter_destroy (struct attr_iter * iter)
References g_free().
Referenced by NGQProxyRoute::dropIterFunc().
struct attr_iter* route_attr_iter_new (void)
References g_new0.
Referenced by NGQProxyRoute::getIterFunc().
static struct map_selection* route_calc_selection (struct coord * c, int count, struct vehicleprofile * profile) static
Returns a list of map selections useable to create a route graph.
Returns a list of map selections useable to get a map rect from which items can be retrieved to build a route graph.
Parameters
c Array containing route points, including start, intermediate and destination ones.
count number of route points
proifle vehicleprofile
References coord_rect_extend(), g_free(), g_strdup(), i, coord_rect::lu, NULL, coord_rect::rl, vehicleprofile::route_depth, and route_rect_add().
Referenced by route_graph_build().
static int route_check_roundabout (struct route_graph_segment * seg, int level, int direction, struct route_graph_segment * origin) static
Checks if a segment is part of a roundabout.
This function checks if a segment is part of a roundabout.
Parameters
seg The segment to be checked
level How deep to scan the route graph
direction Set this to 1 if we're entering the segment through its end, to 0 otherwise
origin Used internally, set to NULL
Returns
1 If a roundabout was detected, 0 otherwise
References AF_ONEWAY, AF_ONEWAYREV, AF_ROUNDABOUT, AF_ROUNDABOUT_VALID, route_graph_segment::data, route_graph_segment::end, route_segment_data::flags, route_segment_data::item, rp_iterator_end(), rp_iterator_new(), rp_iterator_next(), route_graph_segment::start, and item::type.
Referenced by route_path_add_item_from_graph().
static void route_clear_destinations (struct route * this_) static
References route::destinations, g_list_foreach(), g_list_free(), NULL, and route_info_free().
Referenced by route_destroy(), and route_set_destinations().
int route_contains (struct route * this, struct item * item)
Checks if the route passed contains a certain item within the route path.
This function checks if a certain items exists in the path that navit will guide the user to his destination. It does not check if this item exists in the route graph!
Parameters
this The route to check for this item
item The item to search for
Returns
True if the item was found, false if the item was not found or the route was not calculated
References item_hash_lookup(), item_is_equal, and startup::pos.
Referenced by tracking_is_on_route().
struct route_crossings* route_crossings_get (struct route * this, struct coord * c)
References route_crossings::count, g_malloc(), printf(), and route_graph_get_point().
int route_destination_reached (struct route * this)
Checks if a route has reached its destination.
Parameters
this The route to be checked
Returns
True if the destination is "reached", false otherwise.
References AF_ONEWAY, AF_ONEWAYREV, street_data::flags, g_list_next, street_data::item, item_is_equal, route_info::lenneg, route_info::lenpos, route_info::lp, NULL, startup::pos, projection_none, route_next_destination(), route_projection(), route_info::street, and transform_distance().
Referenced by navit_vehicle_update_position().
void route_destroy (struct route * this_)
References g_free(), route::graph, route::graph_map, route::map, map_destroy(), route::path2, route::pos, route_clear_destinations(), route_graph_destroy(), route_info_free(), and route_path_destroy().
Referenced by navit_destroy(), and request_route_destroy().
struct route* route_dup (struct route * orig)
Duplicates a route object.
Returns
The duplicated route
References callback_list_new(), route::cbl2, route::destination_distance, route::flags, g_new0, route::ms, navit_object_ref(), route_func, and route::vehicleprofile.
Referenced by request_route_dup().
static struct route_path_segment* route_extract_segment_from_path (struct route_path * path, struct item * item, int offset) static
Returns and removes one segment from a path.
Parameters
path The path to take the segment from
item The item whose segment to remove
offset Offset of the segment within the item to remove. If the item is not segmented this should be 1.
Returns
The segment removed
References AF_SEGMENTED, item_hash_remove(), item_is_equal, route_path_segment::next, NULL, route_path::path, and route_path::path_hash.
Referenced by route_path_add_item_from_graph().
static struct route_info * route_find_nearest_street (struct vehicleprofile * vehicleprofile, struct mapset * ms, struct pcoord * pc) static
Finds the nearest street to a given coordinate.
Parameters
ms The mapset to search in for the street
pc The coordinate to find a street nearby
Returns
The nearest street
References street_data::c, route_info::c, c, street_data::count, dbg, vehicleprofile::flags, street_data::flags, vehicleprofile::flags_forward_mask, vehicleprofile::flags_reverse_mask, g_free(), g_new0, item::id_hi, item::id_lo, item, item_get_default_flags(), route_info::lp, lvl_debug, map_projection(), map_rect_destroy(), map_rect_get_item(), map_rect_new(), map_selection_destroy(), mapset_close(), mapset_next(), mapset_open(), NULL, startup::pos, route_info::pos, pcoord::pro, route_rect(), route_info::street, street_data_free(), street_get_data(), transform_distance_polyline_sq(), transform_from_geo(), transform_to_geo(), item::type, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by route_append_destination(), route_set_destinations(), and route_set_position_flags().
static void route_free_selection (struct map_selection * sel) static
Destroys a list of map selections.
Parameters
sel Start of the list to be destroyed
References g_free(), map_selection::next, and next.
Referenced by route_graph_build_done().
int route_get_attr (struct route * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References route_info::c, _GList::data, dbg, route::destinations, g_list_next, attr_iter::list, lvl_debug, attr::map, route_path::next, NULL, attr::num, route_path::path, route::path2, route_path::path_len, route_path::path_time, route::pc, attr::pcoord, pcoord::pro, projection_mg, route_get_dst(), route_get_map(), route::route_status, route_status_path_done_incremental, route_status_path_done_new, type, attr::type, attr_iter::u, attr::u, route::v, attr::vehicle, attr::vehicleprofile, route::vehicleprofile, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by NGQProxyRoute::getAttrFunc(), gui_gtk_route_callback(), gui_internal_cmd_pois(), gui_internal_populate_route_table(), map_route_occluded_rect_new(), navigation_set_route(), navigation_update(), pedestrian_draw_arrows(), pedestrian_navit_init(), and request_route_get_attr().
struct coord route_get_coord_dist (struct route * this_, int dist)
Returns a coordinate at a given distance.
This function returns the coordinate, where the user will be if he follows the current route for a certain distance.
Parameters
this_ The route we're driving upon
dist The distance in meters
Returns
The coordinate where the user will be in that distance
References route_path_segment::c, route_info::c, route_path_segment::data, double, i, int, route_segment_data::len, route_path_segment::ncoords, route_path_segment::next, projection_none, route_get_dst(), route_projection(), transform_polyline_length(), coord::x, and coord::y.
int route_get_destination_count (struct route * this)
Get the destinations count for the route.
Parameters
this The route instance
Returns
destination count for the route
References g_list_length().
Referenced by navit_get_destination_count(), navit_remove_nth_waypoint(), navit_remove_waypoint(), navit_set_destination(), and navit_vehicle_update_position().
char* route_get_destination_description (struct route * this, int n)
Returns a description for a waypoint as (type or street_name_systematic) + (label or WayID[osm_wayid])
Parameters
this The route instance
n The nth waypoint
Returns
The description
References _, attr_to_text(), g_free(), g_list_nth_data(), g_strdup(), g_strdup_printf(), item::id_hi, item::id_lo, item, street_data::item, item_attr_get(), item_to_name(), label, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), NULL, route_info::street, item::type, type, and attr::type.
Referenced by navit_get_destination_description(), and navit_vehicle_update_position().
int route_get_destinations (struct route * this, struct pcoord * pc, int count)
References route_info::c, _GList::data, g_list_next, pcoord::pro, projection_mg, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by navit_get_destinations(), navit_set_destination(), navit_vehicle_update_position(), and route_set_profile().
void route_get_distances (struct route * this, struct coord * c, int count, int * distances)
References route_path_get_distances().
Referenced by gui_internal_cmd_pois_item().
struct route_info* route_get_dst (struct route * this)
Returns the destination of the route passed.
Parameters
this The route to get the destination for
Returns
The destination of the route passed
References _GList::data, g_list_last(), and NULL.
Referenced by rm_coord_get(), rm_rect_new(), route_append_destination(), route_get_attr(), route_get_coord_dist(), route_projection(), route_remove_nth_waypoint(), and route_set_destinations().
enum route_path_flags route_get_flags (struct route * this_)
Returns the flags for the route.
References route::flags.
Referenced by navigation_update().
struct map* route_get_graph_map (struct route * this_)
Returns a new map containing the route graph.
This function returns a new map containing the route graph.
Do not map_destroy() this!
Parameters
this_ The route to get the map of
Returns
A new map containing the route graph
References route::graph_map, and route_get_map_helper().
Referenced by navigation_itm_new(), and navit_init().
struct map* route_get_map (struct route * this_)
Returns a new map containing the route path.
This function returns a new map containing the route path.
Do not map_destroy() this!
Parameters
this_ The route to get the map of
Returns
A new map containing the route path
References route::map, and route_get_map_helper().
Referenced by gui_internal_cmd2_route_height_profile(), gui_internal_select_waypoint(), navigation_update(), navit_init(), navit_zoom_to_route(), route_get_attr(), route_get_map_py(), and vehicle_demo_timer().
static struct map* route_get_map_helper (struct route * this_, struct map ** map, char * type, char * description) static
References attr::attrs, data, description(), attr::map, map_new(), attr::navigation, navit_object_ref(), NULL, attr::route, attr::str, type, attr::type, and attr::u.
Referenced by route_get_graph_map(), and route_get_map().
struct mapset* route_get_mapset (struct route * this)
Returns the mapset of the route passed.
Parameters
this The route to get the mapset of
Returns
The mapset of the route passed
int route_get_path_set (struct route * this)
Checks if the path is calculated for the route passed.
Parameters
this The route to check
Returns
True if the path is calculated, false if not
References NULL.
Referenced by navit_check_route().
struct route_info* route_get_pos (struct route * this)
Returns the current position within the route passed.
Parameters
this The route to get the position for
Returns
The position within the route passed
References startup::pos.
Referenced by rm_rect_new().
static int route_get_traffic_distortion (struct route_graph_segment * seg, struct route_traffic_distortion * ret) static
Returns the traffic distortion for a segment.
Parameters
seg The segment for which the traffic distortion is to be returned
ret Points to a
struct route_traffic_distortion
, whose members will be filled
Returns
true if a traffic distortion was found, 0 if not
References AF_SPEED_LIMIT, route_graph_segment::data, route_traffic_distortion::delay, route_graph_point::end, route_graph_segment::end, route_graph_segment::end_next, route_segment_data::flags, route_segment_data::item, route_segment_data::len, route_traffic_distortion::maxspeed, NULL, route_graph_point::start, route_graph_segment::start, start, route_graph_segment::start_next, and item::type.
Referenced by route_value_seg().
static struct route_graph_point* route_graph_add_point (struct route_graph * this, struct coord * f) static
Inserts a point into the route graph at the specified coordinates.
This will insert a point into the route graph at the coordinates passed in f. Note that the point is not yet linked to any segments.
If the route graph already contains a point at the specified coordinates, the existing point will be returned.
Parameters
this The route graph to insert the point into
f The coordinates at which the point should be inserted
Returns
The point inserted or NULL on failure
References p, route_graph_get_point(), and route_graph_point_new().
Referenced by route_process_street_graph(), route_process_traffic_distortion(), and route_process_turn_restriction().
static void route_graph_add_segment (struct route_graph * this, struct route_graph_point * start, struct route_graph_point * end, struct route_graph_segment_data * data) static
Inserts a new segment into the route graph.
This function performs a check if a segment for the item specified already exists, and inserts a new segment representing this item if it does not.
Parameters
this The route graph to insert the segment into
start The graph point which should be connected to the start of this segment
end The graph point which should be connected to the end of this segment
len The length of this segment
item The item that is represented by this segment
flags Flags for this segment
offset If the item passed in "item" is segmented (i.e. divided into several segments), this indicates the position of this segment within the item
maxspeed The maximum speed allowed on this segment in km/h. -1 if not known.
References AF_DANGEROUS_GOODS, AF_SEGMENTED, AF_SIZE_OR_WEIGHT_LIMIT, AF_SPEED_LIMIT, route_graph_point::c, route_graph_segment::data, dbg_assert, debug_route, route_graph_point::end, route_graph_segment::end, route_segment_data::flags, g_slice_alloc0(), route_segment_data::item, route_graph_segment::next, printf(), size, route_graph_point::start, start, coord::x, and coord::y.
Referenced by route_graph_clone_segment(), route_graph_set_traffic_distortion(), route_process_street_graph(), route_process_traffic_distortion(), and route_process_turn_restriction().
static struct route_graph* route_graph_build (struct mapset * ms, struct coord * c, int count, struct callback * done_cb, int async, struct vehicleprofile * profile) static
Builds a new route graph from a mapset.
This function builds a new route graph from a map. Please note that this function does not add any routing information to the route graph - this has to be done via the route_graph_flood() function.
The function does not create a graph covering the whole map, but only covering the rectangle between c1 and c2.
Parameters
ms The mapset to build the route graph from
c The coordinates of the destination or next waypoint
c1 Corner 1 of the rectangle to use from the map
c2 Corner 2 of the rectangle to use from the map
done_cb The callback which will be called when graph is complete
Returns
The new route graph.
References route_graph::busy, callback_cast, callback_new_2, dbg, route_graph::done_cb, event_add_idle(), g_new0, route_graph::h, route_graph::idle_cb, route_graph::idle_ev, lvl_debug, mapset_open(), route_calc_selection(), route_graph_build_done(), route_graph_build_idle(), route_graph_build_next_map(), and route_graph::sel.
Referenced by route_graph_update().
static void route_graph_build_done (struct route_graph * rg, int cancel) static
Releases all resources needed to build the route graph.
If
cancel
is false, this function will start processing restrictions and ultimately call the route graph's
done_cb
callback.
Parameters
rg Points to the route graph
cancel True if the process was aborted before completing, false if it completed normally
References route_graph::busy, callback_call_0, callback_destroy(), dbg, route_graph::done_cb, event_remove_idle(), route_graph::h, route_graph::idle_cb, route_graph::idle_ev, lvl_debug, map_rect_destroy(), mapset_close(), route_graph::mr, NULL, route_free_selection(), route_graph_process_restrictions(), and route_graph::sel.
Referenced by route_graph_build(), route_graph_build_idle(), and route_graph_destroy().
static void route_graph_build_idle (struct route_graph * rg, struct vehicleprofile * profile) static
References item, map_rect_get_item(), route_graph::mr, route_graph_build_done(), route_graph_build_next_map(), route_process_street_graph(), route_process_traffic_distortion(), route_process_turn_restriction(), and item::type.
Referenced by route_graph_build(), and route_graph_update().
static int route_graph_build_next_map (struct route_graph * rg) static
References route_graph::h, route_graph::m, map_rect_destroy(), map_rect_new(), mapset_next(), route_graph::mr, and route_graph::sel.
Referenced by route_graph_build(), and route_graph_build_idle().
static void route_graph_clone_segment (struct route_graph * this, struct route_graph_segment * s, struct route_graph_point * start, struct route_graph_point * end, int flags) static
References AF_SEGMENTED, AF_SPEED_LIMIT, route_graph_point::c, route_graph_segment_data::dangerous_goods, route_graph_segment::data, dbg, route_segment_data::flags, route_graph_segment_data::flags, route_segment_data::item, route_graph_segment_data::item, route_segment_data::len, route_graph_segment_data::len, lvl_debug, route_graph_segment_data::maxspeed, route_graph_segment_data::offset, route_graph_add_segment(), coord::x, and coord::y.
Referenced by route_graph_process_restriction_segment().
static void route_graph_destroy (struct route_graph * this) static
Destroys a route graph.
Parameters
this The route graph to be destroyed
References g_free(), route_graph_build_done(), route_graph_free_points(), and route_graph_free_segments().
Referenced by route_append_destination(), route_destroy(), route_graph_update(), route_path_update_flags(), route_remove_nth_waypoint(), and route_set_destinations().
static void route_graph_flood (struct route_graph * this, struct route_info * dst, struct vehicleprofile * profile, struct callback * cb) static
Calculates the routing costs for each point.
This function is the heart of routing. It assigns each point in the route graph a cost at which one can reach the destination from this point on. Additionally it assigns each point a segment one should follow from this point on to reach the destination at the stated costs.
This function uses Dijkstra's algorithm to do the routing. To understand it you should have a look at this algorithm.
References to elements of the route graph which were obtained prior to calling this function remain valid after it returns.
Parameters
this_ The route graph to flood
dst The destination of the route
profile The vehicle profile to use for routing. This determines which ways are passable and how their costs are calculated.
cb The callback function to call when flooding is complete
References route_graph_point::c, callback_call_0, route_graph_segment::data, dbg, debug_route, route_graph_point::el, route_graph_point::end, route_graph_segment::end, route_graph_segment::end_next, fh_deleteheap(), fh_extractmin(), fh_insertkey(), fh_makekeyheap(), fh_replacekey(), route_segment_data::item, item_is_equal, lvl_debug, NULL, route_info::percent, printf(), route_graph_get_segment(), route_value_seg(), route_graph_point::seg, route_graph_point::start, route_graph_segment::start, start, route_graph_segment::start_next, route_info::street, vehicleprofile::turn_around_penalty2, route_graph_point::value, coord::x, and coord::y.
Referenced by route_graph_update_done(), route_path_new(), route_path_update_done(), and route_remove_waypoint().
static void route_graph_free_points (struct route_graph * this) static
Frees all the memory used for points in the route graph passed.
Parameters
this The route graph to delete all points from
References g_slice_free, route_graph_point::hash_next, HASH_SIZE, i, next, and NULL.
Referenced by route_graph_destroy().
static void route_graph_free_segments (struct route_graph * this) static
Destroys all segments of a route graph.
Parameters
this The graph to destroy all segments from
References g_slice_free1(), route_graph_segment::next, next, NULL, and size.
Referenced by route_graph_destroy().
static struct route_graph_point * route_graph_get_point (struct route_graph * this, struct coord * c) static
Gets the first route_graph_point with the specified coordinates.
Parameters
this The route in which to search
c Coordinates to search for
Returns
The point at the specified coordinates or NULL if not found
References NULL, and route_graph_get_point_next().
Referenced by route_crossings_get(), and route_graph_add_point().
static struct route_graph_point* route_graph_get_point_last (struct route_graph * this, struct coord * c) static
Gets the last route_graph_point with the specified coordinates.
Parameters
this The route in which to search
c Coordinates to search for
Returns
The point at the specified coordinates or NULL if not found
References route_graph_point::c, route_graph_point::hash_next, NULL, p, coord::x, and coord::y.
Referenced by rp_get_item().
static struct route_graph_point* route_graph_get_point_next (struct route_graph * this, struct coord * c, struct route_graph_point * last) static
Gets the next route_graph_point with the specified coordinates.
Parameters
this The route in which to search
c Coordinates to search for
last The last route graph point returned to iterate over multiple points with the same coordinates, or
NULL
to return the first point
Returns
The point at the specified coordinates or NULL if not found
References route_graph_point::c, route_graph_point::hash_next, NULL, p, coord::x, and coord::y.
Referenced by route_graph_get_point(), route_graph_get_segment(), and route_graph_set_traffic_distortion().
static struct route_graph_segment* route_graph_get_segment (struct route_graph * graph, struct street_data * sd, struct route_graph_segment * last) static
Gets the next route_graph_segment belonging to the specified street.
Parameters
graph The route graph in which to search
sd The street to search for
last The last route graph segment returned to iterate over multiple segments of the same item. If
NULL
, the first matching segment will be returned.
Returns
The route graph segment, or
NULL
if none was found.
References street_data::c, route_graph_segment::data, street_data::item, route_segment_data::item, item_is_equal, NULL, route_graph_get_point_next(), route_graph_point::start, start, and route_graph_segment::start_next.
Referenced by route_graph_flood(), and route_path_new().
static struct map_priv* route_graph_map_new (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References route_map_new_helper().
Referenced by route_init().
static struct route_graph_point* route_graph_point_new (struct route_graph * this, struct coord * f) static
Create a new point for the route graph with the specified coordinates.
Parameters
this The route to insert the point into
f The coordinates at which the point should be created
Returns
The point created
References route_graph_point::c, debug_route, g_slice_new0, route_graph_point::hash_next, p, printf(), route_graph_point::value, coord::x, and coord::y.
Referenced by route_graph_add_point(), and route_graph_process_restriction_segment().
static void route_graph_process_restriction_point (struct route_graph * this, struct route_graph_point * p) static
References route_graph_point::c, route_graph_segment::data, dbg, route_graph_point::end, route_graph_segment::end_next, route_graph_point::flags, route_segment_data::item, lvl_debug, route_graph_process_restriction_segment(), route_graph_point::start, route_graph_segment::start_next, item::type, coord::x, and coord::y.
Referenced by route_graph_process_restrictions().
static void route_graph_process_restriction_segment (struct route_graph * this, struct route_graph_point * p, struct route_graph_segment * s, int dir) static
References AF_ONEWAY, AF_ONEWAYREV, route_graph_point::c, route_graph_segment::data, dbg, route_graph_point::end, route_graph_segment::end, route_graph_segment::end_next, route_segment_data::flags, is_turn_allowed(), route_segment_data::item, item_to_name(), lvl_debug, route_graph_clone_segment(), route_graph_point_new(), route_graph_point::start, route_graph_segment::start, route_graph_segment::start_next, item::type, coord::x, and coord::y.
Referenced by route_graph_process_restriction_point().
static void route_graph_process_restrictions (struct route_graph * this) static
References dbg, route_graph_point::flags, route_graph_point::hash_next, HASH_SIZE, i, lvl_debug, and route_graph_process_restriction_point().
Referenced by route_graph_build_done().
static void route_graph_reset (struct route_graph * this) static
Resets all nodes.
This iterates through all the points in the route graph, resetting them to their initial state. The
value
member of each point (cost to reach the destination) is reset to
INT_MAX
, the
seg
member (cheapest way to destination) is reset to
NULL
and the
el
member (pointer to element in Fibonacci heap) is also reset to
NULL
.
References to elements of the route graph which were obtained prior to calling this function remain valid after it returns.
Parameters
this The route graph to reset
References route_graph_point::el, route_graph_point::hash_next, HASH_SIZE, i, NULL, route_graph_point::seg, and route_graph_point::value.
Referenced by route_path_new(), route_path_update_done(), and route_remove_waypoint().
static int route_graph_segment_is_duplicate (struct route_graph_point * start, struct route_graph_segment_data * data) static
References AF_SEGMENTED, route_graph_segment::data, route_graph_segment_data::flags, route_segment_data::item, route_graph_segment_data::item, item_is_equal, route_graph_segment_data::offset, route_graph_point::start, and route_graph_segment::start_next.
Referenced by route_process_street_graph().
static int route_graph_segment_match (struct route_graph_segment * s1, struct route_graph_segment * s2) static
References route_graph_point::c, route_graph_segment::end, route_graph_segment::start, coord::x, and coord::y.
Referenced by route_graph_set_traffic_distortion(), and route_path_new().
static void route_graph_set_traffic_distortion (struct route_graph * this, struct route_graph_segment * seg, int delay) static
Sets or clears a traffic distortion for a segment.
This sets or clears a delay. It cannot be used to set speed.
Parameters
this The route graph
seg The segment to which the traffic distortion applies
delay Delay in tenths of a second
References route_graph_point::c, route_graph_segment::data, route_graph_segment::end, route_graph_point::flags, item, route_segment_data::item, route_graph_segment_data::item, route_graph_segment_data::len, NULL, route_graph_add_segment(), route_graph_get_point_next(), route_graph_segment_match(), route_graph_point::start, route_graph_segment::start, start, route_graph_segment::start_next, and item::type.
Referenced by route_path_new().
static void route_graph_update (struct route * this, struct callback * cb, int async) static
Updates the route graph.
This updates the route graph after settings in the route have changed. It also adds routing information afterwards by calling route_graph_flood().
Parameters
this The route to update the graph for
cb The callback function to call when the route graph update is complete (used only in asynchronous mode)
async Set to nonzero in order to update the route graph asynchronously
References route_info::c, c, callback_cast, callback_destroy(), callback_new_2, _GList::data, g_alloca, g_list_length(), g_list_next, i, NULL, attr::num, startup::pos, route_graph_build(), route_graph_build_idle(), route_graph_destroy(), route_graph_update_done(), route_set_attr(), route_status_building_graph, attr::type, and attr::u.
Referenced by route_path_update_flags().
static void route_graph_update_done (struct route * this, struct callback * cb) static
References route_graph_flood().
Referenced by route_graph_update().
int route_has_graph (struct route * this_)
Whether the route has a valid graph.
Returns
True if the route has a graph, false if not.
References route::graph, and NULL.
Referenced by navigation_update_idle().
static void route_info_distances (struct route_info * ri, enum projection pro) static
This will calculate all the distances stored in a route_info.
Parameters
ri The route_info to calculate the distances for
pro The projection used for this route
References street_data::c, route_info::c, street_data::count, route_info::lenextra, route_info::lenneg, route_info::lenpos, route_info::lp, route_info::percent, route_info::pos, route_info::street, transform_distance(), and transform_polyline_length().
Referenced by route_append_destination(), route_set_destinations(), route_set_position_flags(), and route_set_position_from_tracking().
void route_info_free (struct route_info * inf)
Destroys a route_info.
Parameters
info The route info to be destroyed
References g_free(), route_info::street, and street_data_free().
Referenced by route_clear_destinations(), route_destroy(), route_remove_nth_waypoint(), route_remove_waypoint(), route_set_position_flags(), and route_set_position_from_tracking().
struct street_data* route_info_street (struct route_info * rinf)
Returns street data for a route info.
Parameters
rinf The route info to return the street data for
Returns
Street data for the route info
References route_info::street.
void route_init (void)
References route_graph_map_new(), and route_map_new().
Referenced by main_real().
static struct map_priv* route_map_new (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References route_map_new_helper().
Referenced by route_init().
static struct map_priv* route_map_new_helper (struct map_methods * meth, struct attr ** attrs, int graph) static
References attr_search(), g_new0, NULL, map_priv::route, attr::route, route_graph_meth, route_meth, and attr::u.
Referenced by route_graph_map_new(), and route_map_new().
struct route* route_new (struct attr * parent, struct attr ** attrs)
Creates a completely new route structure.
Parameters
attrs Not used
Returns
The newly created route
References attr_generic_get_attr(), callback_list_new(), g_new0, navit_object_ref(), NULL, attr::num, route_func, and attr::u.
static struct route_info* route_next_destination (struct route * this) static
References NULL.
Referenced by route_destination_reached().
static int route_path_add_item_from_graph (struct route_path * this, struct route_path * oldpath, struct route_graph_segment * rgs, int dir, struct route_info * pos, struct route_info * dst) static
Inserts a new item into the path.
This function does almost the same as "route_path_add_item()", but identifies the item to add by a segment from the route graph. Another difference is that it "copies" the segment from the route graph, i.e. if the item is segmented, only the segment passed in rgs will be added to the route path, not all segments of the item.
The function can be sped up by passing an old path already containing this segment in oldpath - the segment will then be extracted from this old path. Please note that in this case the direction parameter has no effect.
Parameters
this The path to add the item to
oldpath Old path containing the segment to be added. Speeds up the function, but can be NULL.
rgs Segment of the route graph that should be "copied" to the route path
dir Order in which to add the coordinates. See route_path_add_item()
pos Information about start point if this is the first segment
dst Information about end point if this is the last segment
References AF_ROUNDABOUT, AF_SEGMENTED, street_data::c, route_graph_point::c, route_path_segment::c, c, street_data::count, route_graph_segment::data, route_path_segment::data, dbg, route_info::dir, route_path_segment::direction, route_graph_segment::end, route_segment_data::flags, g_free(), g_malloc0(), get_item_seg_coords(), i, item::id_hi, item::id_lo, if(), route_segment_data::item, item_hash_insert(), item_hash_lookup(), route_segment_data::len, route_info::lenneg, route_info::lenpos, route_info::lp, lvl_debug, route_path_segment::ncoords, route_path_segment::next, NULL, offset, route_path::path_hash, route_info::pos, route_check_roundabout(), route_extract_segment_from_path(), route_path_add_segment(), route_segment_data_size(), route_graph_segment::start, route_info::street, coord::x, and coord::y.
Referenced by route_path_new().
static void route_path_add_line (struct route_path * this, struct coord * start, struct coord * end, int len) static
Adds a two coordinate line to a path.
This adds a new line to a path, creating a new segment for it.
Parameters
this The path to add the item to
start coordinate to add to the start of the item. If none should be added, make this NULL.
end coordinate to add to the end of the item. If none should be added, make this NULL.
len The length of the item
References route_path_segment::c, route_path_segment::data, dbg, route_path_segment::direction, g_malloc0(), route_segment_data::len, lvl_debug, route_path_segment::ncoords, route_path_add_segment(), start, coord::x, and coord::y.
Referenced by route_path_new(), and route_path_new_offroad().
static void route_path_add_segment (struct route_path * this, struct route_path_segment * segment) static
Adds a segment and the end of a path.
Parameters
this The path to add the segment to
segment The segment to add
References route_path_segment::next.
Referenced by route_path_add_item_from_graph(), and route_path_add_line().
static void route_path_destroy (struct route_path * this, int recurse) static
Destroys a route_path.
Parameters
this The route_path to be destroyed
References c, g_free(), route_path::in_use, item_hash_destroy(), route_path_segment::next, next, NULL, route_path::path, and route_path::path_hash.
Referenced by route_destroy(), route_path_update_done(), route_path_update_flags(), and route_remove_waypoint().
static void route_path_get_distances (struct route_path * path, struct coord * c, int count, int * distances) static
References route_path_segment::c, i, route_path_segment::ncoords, route_path_segment::next, route_path::next, NULL, route_path::path, and transform_distance_polyline_sq().
Referenced by route_get_distances().
static struct route_path * route_path_new (struct route_graph * this, struct route_path * oldpath, struct route_info * pos, struct route_info * dst, struct vehicleprofile * profile) static
Creates a new route path.
This creates a new non-trivial route. It therefore needs the routing information created by route_graph_flood, so make sure to run route_graph_flood() after changing the destination before using this function.
Parameters
this The route graph to create the route from
oldpath (Optional) old path which may contain parts of the new part - this speeds things up a bit. May be NULL.
pos The starting position of the route
dst The destination of the route
preferences The routing preferences
Returns
The new route path
References route_graph_point::c, route_info::c, route_graph_segment::data, dbg, route_info::dir, route_graph_point::end, route_graph_segment::end, g_new0, route_path::in_use, street_data::item, route_segment_data::item, item_hash_new(), item_is_equal, route_info::lenextra, route_info::lp, lvl_debug, lvl_error, item::map, map_projection(), vehicleprofile::mode, NULL, route_path::path_hash, route_info::percent, startup::pos, printf(), route_graph_flood(), route_graph_get_segment(), route_graph_reset(), route_graph_segment_match(), route_graph_set_traffic_distortion(), route_path_add_item_from_graph(), route_path_add_line(), route_path_new_offroad(), route_value_seg(), s1, s2, route_graph_point::seg, route_graph_point::start, route_graph_segment::start, start, route_info::street, route_info::street_direction, transform_distance(), vehicleprofile::turn_around_penalty, route_path::updated, route_graph_point::value, coord::x, and coord::y.
Referenced by route_path_update_done().
static struct route_path* route_path_new_offroad (struct route_graph * this, struct route_info * pos, struct route_info * dst) static
Starts an "offroad" path.
This starts a path that is not located on a street. It creates a new route path adding only one segment, that leads from pos to dest, and which is not associated with an item.
Parameters
this Not used
pos The starting position for the new path
dst The destination of the new path
dir Not used
Returns
The new path
References route_info::c, g_new0, route_path::in_use, item_hash_new(), route_info::lenextra, route_path::path_hash, route_path_add_line(), and route_path::updated.
Referenced by route_path_new().
static void route_path_update (struct route * this, int cancel, int async) static
Updates the route graph and the route path if something changed with the route.
This function is a wrapper around route_path_update_flags(route *, enum route_path).
Parameters
this The route to update
cancel If true, cancel navigation, clear route graph and route path
async If true, perform processing asynchronously
References route_path_flag_async, route_path_flag_cancel, and route_path_update_flags().
Referenced by route_append_destination(), route_remove_nth_waypoint(), route_set_destinations(), and route_set_position_from_tracking().
static void route_path_update_done (struct route * this, int new_graph) static
Updates or recreates the route graph.
This function is called after the route graph has been changed or rebuilt and flooding has completed. It then updates the route path to reflect these changes.
If multiple destinations are set, this function will reset and re-flood the route graph for each destination, thus recursively calling itself for each destination.
Parameters
this The route object
new_graph FIXME Whether the route graph has been rebuilt from scratch
References route_path_segment::data, dbg, route_segment_data::len, lvl_debug, route_path_segment::next, route_path::next, NULL, attr::num, startup::pos, route_graph_flood(), route_graph_reset(), route_path_destroy(), route_path_new(), route_previous_destination(), route_set_attr(), route_status_building_path, route_status_not_found, route_status_path_done_incremental, route_status_path_done_new, route_time_seg(), attr::type, and attr::u.
Referenced by rm_rect_destroy(), and route_path_update_flags().
static void route_path_update_flags (struct route * this, enum route_path_flags flags) static
Updates the route graph and the route path if something changed with the route.
This will update the route graph and the route path of the route if some of the route's settings (destination, position) have changed.
The behavior of this function can be controlled via flags:
route_path_flag_cancel
: Cancel navigation, clear route graph and route path
route_path_flag_async
: Perform operations asynchronously
route_path_flag_no_rebuild
: Do not rebuild the route graph
These flags will be stored in the
flags
member of the route object.
Attention
For this to work the route graph has to be destroyed if the route's
destination is changed somewhere!
Parameters
this The route to update
flags Flags to control the behavior of this function, see description
References callback_cast, callback_new_2, dbg, lvl_debug, NULL, startup::pos, route_graph_destroy(), route_graph_update(), route_path_destroy(), route_path_flag_async, route_path_flag_cancel, route_path_flag_no_rebuild, and route_path_update_done().
Referenced by route_path_update(), and route_set_position_flags().
static struct route_info* route_previous_destination (struct route * this) static
Returns the position from which to route to the current destination of the route.
This function examines the destination list of the route. If present, it returns the destination which precedes the one indicated by the
current_dst
member of the route. Failing that, the current position of the route is returned.
Parameters
this The route object
Returns
The previous destination or current position, see description
References _GList::data, g_list_find(), g_list_previous, and startup::pos.
Referenced by route_path_update_done().
static void route_process_street_graph (struct route_graph * this, struct item * item, struct vehicleprofile * profile) static
Adds an item to the route graph.
This adds an item (e.g. a street) to the route graph, creating as many segments as needed for a segmented item.
Parameters
this The route graph to add to
item The item to add
profile The vehicle profile currently in use
References AF_ALL, AF_DANGEROUS_GOODS, AF_SEGMENTED, AF_SIZE_OR_WEIGHT_LIMIT, AF_SPEED_LIMIT, size_weight_limit::axle_weight, c, route_graph_segment_data::dangerous_goods, dbg_assert, default_flags, route_graph_segment_data::flags, size_weight_limit::height, item, route_graph_segment_data::item, item_attr_get(), item_coord_get(), item_coord_is_node(), item_get_default_flags(), route_graph_segment_data::len, size_weight_limit::length, item::map, map_projection(), route_graph_segment_data::maxspeed, attr::num, route_graph_segment_data::offset, route_graph_add_point(), route_graph_add_segment(), route_graph_segment_is_duplicate(), route_graph_segment_data::size_weight, transform_distance(), item::type, attr::u, vehicleprofile_get_roadprofile(), size_weight_limit::weight, and size_weight_limit::width.
Referenced by route_graph_build_idle().
static void route_process_traffic_distortion (struct route_graph * this, struct item * item) static
Adds a route distortion item to the route graph.
Parameters
this The route graph to add to
item The item to add
References AF_SPEED_LIMIT, c, route_graph_point::flags, route_graph_segment_data::flags, item, route_graph_segment_data::item, item_attr_get(), item_coord_get(), route_graph_segment_data::len, route_graph_segment_data::maxspeed, attr::num, route_graph_segment_data::offset, route_graph_add_point(), route_graph_add_segment(), and attr::u.
Referenced by route_graph_build_idle().
static void route_process_turn_restriction (struct route_graph * this, struct item * item) static
Adds a turn restriction item to the route graph.
Parameters
this The route graph to add to
item The item to add
References dbg, route_graph_point::flags, route_graph_segment_data::flags, i, item, route_graph_segment_data::item, item_coord_get(), item_to_name(), route_graph_segment_data::len, lvl_debug, route_graph_add_point(), route_graph_add_segment(), item::type, coord::x, and coord::y.
Referenced by route_graph_build_idle().
static enum projection route_projection (struct route * route) static
Returns the projection used for this route.
Parameters
route The route to return the projection for
Returns
The projection used for this route
References street_data::item, item::map, map_projection(), route::pos, projection_none, route_get_dst(), and route_info::street.
Referenced by rm_coord_get(), route_destination_reached(), route_get_coord_dist(), and rp_coord_get().
struct map_selection* route_rect (int order, struct coord * c1, struct coord * c2, int rel, int abs)
Returns a single map selection.
References map_selection::c_rect, dbg, g_new, coord_rect::lu, lvl_debug, item_range::max, map_selection::next, NULL, map_selection::order, printf(), map_selection::range, coord_rect::rl, route_item_first, route_item_last, map_selection::u, coord::x, and coord::y.
Referenced by route_find_nearest_street(), route_rect_add(), and tracking_doupdate_lines().
static struct map_selection* route_rect_add (struct map_selection * sel, int order, struct coord * c1, struct coord * c2, int rel, int abs) static
Appends a map selection to the selection list. Selection list may be NULL.
References map_selection::next, and route_rect().
Referenced by route_calc_selection().
int route_remove_attr (struct route * this_, struct attr * attr)
References attr::callback, callback_list_remove(), route::cbl2, dbg, lvl_debug, NULL, attr::type, attr::u, and route::v.
Referenced by navigation_set_route(), and request_route_remove_attr().
void route_remove_nth_waypoint (struct route * this, int n)
Remove the nth waypoint of the route.
Parameters
this The route instance
n The waypoint to remove
Returns
nothing
References g_list_nth_data(), g_list_remove(), NULL, route_get_dst(), route_graph_destroy(), route_info_free(), and route_path_update().
Referenced by navit_remove_nth_waypoint().
void route_remove_waypoint (struct route * this)
References g_list_remove(), route_path::path, route_graph_flood(), route_graph_reset(), route_info_free(), route_path_destroy(), and route_status_no_destination.
Referenced by navit_remove_waypoint(), and navit_vehicle_update_position().
static int route_seg_speed (struct vehicleprofile * profile, struct route_segment_data * over, struct route_traffic_distortion * dist) static
Returns the estimated speed on a segment, or 0 for an impassable segment.
This function returns the estimated speed to be driven on a segment, calculated as follows:
Initially the route weight of the vehicle profile for the given item type is used. If the item type does not have a route weight in the vehicle profile given, it is considered impassable and 0 is returned.
If the
maxspeed
attribute of the segment's item is set, either it or the previous speed estimate for the segment is used, as governed by the vehicle profile's
maxspeed_handling
attribute.
If a traffic distortion is present, its
maxspeed
is taken into account in a similar manner. Unlike the regular
maxspeed
, a
maxspeed
resulting from a traffic distortion is always considered if it limits the speed, regardless of
maxspeed_handling
.
Access restrictions for dangerous goods, size or weight are evaluated, and 0 is returned if the given vehicle profile violates one of them.
Parameters
profile The routing preferences
over The segment which is passed
dist A traffic distortion if applicable, or
NULL
Returns
The estimated speed in km/h, or 0 if the segment is impassable
References AF_DANGEROUS_GOODS, AF_SIZE_OR_WEIGHT_LIMIT, AF_SPEED_LIMIT, vehicleprofile::axle_weight, size_weight_limit::axle_weight, vehicleprofile::dangerous_goods, route_segment_data::flags, vehicleprofile::height, size_weight_limit::height, route_segment_data::item, vehicleprofile::length, size_weight_limit::length, roadprofile::maxspeed, route_traffic_distortion::maxspeed, maxspeed_enforce, vehicleprofile::maxspeed_handling, maxspeed_ignore, maxspeed_restrict, roadprofile::route_weight, speed, item::type, vehicleprofile_get_roadprofile(), vehicleprofile::weight, size_weight_limit::weight, vehicleprofile::width, and size_weight_limit::width.
Referenced by rm_attr_get(), route_time_seg(), and rp_attr_get().
static void* route_segment_data_field_pos (struct route_segment_data * seg, enum attr_type type) static
Returns the position of a certain field appended to a route graph segment.
This function returns a pointer to a field that is appended to a route graph segment.
Parameters
seg The route graph segment the field is appended to
type Type of the field that should be returned
Returns
A pointer to a field of a certain type, or NULL if no such field is present
References AF_DANGEROUS_GOODS, AF_SEGMENTED, AF_SIZE_OR_WEIGHT_LIMIT, AF_SPEED_LIMIT, route_segment_data::flags, int, NULL, and ptr.
static int route_segment_data_size (int flags) static
Calculates the size of a route_segment_data struct with given flags.
Parameters
flags The flags of the route_segment_data
References AF_DANGEROUS_GOODS, AF_SEGMENTED, AF_SIZE_OR_WEIGHT_LIMIT, AF_SPEED_LIMIT, and int.
Referenced by route_path_add_item_from_graph().
int route_set_attr (struct route * this_, struct attr * attr)
References attr_to_name(), callback_list_call_attr_2, route::cbl2, attr::coord_geo, dbg, lvl_error, NULL, attr::num, attr::pcoord, pcoord::pro, projection_mg, route_path_flag_async, route_path_flag_no_rebuild, route_set_destination(), route_set_position(), route_set_position_flags(), route::route_status, transform_from_geo(), attr::type, attr::u, route::v, attr::vehicle, vehicle_get_attr(), coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by request_route_set_attr(), route_graph_update(), route_path_update_done(), route_set_destinations(), and NGQProxyRoute::setAttrFunc().
void route_set_destination (struct route * this, struct pcoord * dst, int async)
Start a route given set of coordinates.
Parameters
this The route instance
dst The coordinate to start routing to
async Set to 1 to do route calculation asynchronously
Returns
nothing
References route_set_destinations().
Referenced by navit_add_former_destinations_from_file(), navit_set_destination(), and route_set_attr().
void route_set_destinations (struct route * this, struct pcoord * dst, int count, int async)
Sets the destination of a route.
This sets the destination of a route to the street nearest to the coordinates passed and updates the route.
Parameters
this The route to set the destination for
dst Points to an array of coordinates to set as destinations, which will be visited in the order in which they appear in the array (the last one is the final destination)
count Number of items in
dst
, 0 to clear all destinations
async If set, do routing asynchronously
References callback_list_call_attr_1, g_list_append(), i, NULL, attr::num, pcoord::pro, profile, route_clear_destinations(), route_find_nearest_street(), route_get_dst(), route_graph_destroy(), route_info_distances(), route_path_update(), route_set_attr(), route_status_destination_set, route_status_no_destination, attr::type, and attr::u.
Referenced by NGQProxyRoute::addDestination(), navit_add_former_destinations_from_file(), navit_set_destinations(), route_append_destination(), route_set_destination(), and route_set_profile().
void route_set_mapset (struct route * this, struct mapset * ms)
Sets the mapset of the route passwd.
Parameters
this The route to set the mapset for
ms The mapset to set for this route
Referenced by navit_init().
void route_set_position (struct route * this, struct pcoord * pos)
This sets the current position of the route passed.
This will set the current position of the route passed to the street that is nearest to the passed coordinates. It also automatically updates the route.
Parameters
this The route to set the position of
pos Coordinates to set as position
References route_path_flag_async, and route_set_position_flags().
Referenced by navit_set_position(), navit_vehicle_update_position(), and route_set_attr().
static int route_set_position_flags (struct route * this, struct pcoord * pos, enum route_path_flags flags) static
This sets the current position of the route passed.
This will set the current position of the route passed to the street that is nearest to the passed coordinates. It also automatically updates the route.
Parameters
this The route to set the position of
pos Coordinates to set as position
flags Flags to use for building the graph
References dbg, lvl_debug, NULL, pcoord::pro, route_find_nearest_street(), route_info_distances(), route_info_free(), and route_path_update_flags().
Referenced by route_set_attr(), and route_set_position().
void route_set_position_from_tracking (struct route * this, struct tracking * tracking, enum projection pro)
Sets a route's current position based on coordinates from tracking.
Parameters
this The route to set the current position of
tracking The tracking to get the coordinates from
References street_data::c, route_info::c, c, street_data::count, dbg, g_new0, item::id_hi, item::id_lo, street_data::item, route_info::lenneg, route_info::lenpos, route_info::lp, lvl_debug, lvl_info, NULL, startup::pos, route_info::pos, printf(), route_info_distances(), route_info_free(), route_path_update(), route_info::street, street_data_dup(), route_info::street_direction, tracking_get_pos(), tracking_get_segment_pos(), tracking_get_street_data(), tracking_get_street_direction(), coord::x, and coord::y.
Referenced by navit_vehicle_update_position().
void route_set_profile (struct route * this, struct vehicleprofile * prof)
Sets the vehicle profile of a route.
Parameters
this The route to set the profile for
prof The vehicle profile
References g_alloca, g_list_length(), route_get_destinations(), and route_set_destinations().
Referenced by navit_set_vehicle(), and navit_set_vehicleprofile().
void route_set_projection (struct route * this_, enum projection pro)
Referenced by navit_init().
static int route_through_traffic_allowed (struct vehicleprofile * profile, struct route_graph_segment * seg) static
References AF_THROUGH_TRAFFIC_LIMIT, route_graph_segment::data, and route_segment_data::flags.
Referenced by route_value_seg().
static int route_time_seg (struct vehicleprofile * profile, struct route_segment_data * over, struct route_traffic_distortion * dist) static
Returns the time needed to travel along a segment, or.
INT_MAX
if the segment is impassable.
This function returns the time needed to travel along the entire length of
over
in tenths of seconds. Restrictions for dangerous goods, weight or size are taken into account. Traffic distortions are also taken into account if a valid
dist
argument is given.
Parameters
profile The vehicle profile (routing preferences)
over The segment which is passed
dist A traffic distortion if applicable, or
NULL
Returns
The time needed in tenths of seconds
References route_traffic_distortion::delay, route_segment_data::len, route_seg_speed(), and speed.
Referenced by rm_attr_get(), route_path_update_done(), route_value_seg(), and rp_attr_get().
static int route_value_seg (struct vehicleprofile * profile, struct route_graph_point * from, struct route_graph_segment * over, int dir) static
Returns the "cost" of driving from point.
from
along segment
over
in direction
dir
Cost is relative to time, indicated in tenths of seconds.
This function considers traffic distortions as well as penalties. If the segment is impassable due to traffic distortions or restrictions,
INT_MAX
is returned in order to prevent use of this segment for routing.
Parameters
profile The routing preferences
from The point where we are starting
over The segment we are using
dir The direction of segment which we are driving. Positive values indicate we are traveling in the direction of the segment, negative values indicate we are traveling against that direction. Values of +2 or -2 cause the function to ignore traffic distortions.
Returns
The "cost" needed to travel along the segment
References route_graph_segment::data, dbg, route_graph_segment::end, vehicleprofile::flags, route_graph_point::flags, route_segment_data::flags, vehicleprofile::flags_forward_mask, vehicleprofile::flags_reverse_mask, lvl_debug, NULL, route_get_traffic_distortion(), route_through_traffic_allowed(), route_time_seg(), route_graph_point::seg, route_graph_segment::start, and vehicleprofile::through_traffic_penalty.
Referenced by route_graph_flood(), and route_path_new().
static int rp_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References AF_SPEED_LIMIT, map_rect_priv::attr_next, attr_to_name(), route_graph_point::c, map_rect_priv::coord_sel, route_graph_segment::data, dbg, route_graph_point::end, route_graph_segment::end, route_graph_segment::end_next, route_segment_data::flags, g_free(), g_strdup(), g_strdup_printf(), route_segment_data::item, map_rect_priv::item, attr::item, route_segment_data::len, lvl_debug, item::map, map_rect_priv::mpriv, NULL, attr::num, p, map_rect_priv::point, map_priv::route, route_seg_speed(), route_time_seg(), map_rect_priv::rseg, speed, route_graph_point::start, route_graph_segment::start, start, route_graph_segment::start_next, map_rect_priv::str, attr::str, time(), item::type, attr::type, attr::u, route_graph_point::value, route::vehicleprofile, coord::x, and coord::y.
static void rp_attr_rewind (void * priv_data) static
References map_rect_priv::attr_next.
Referenced by rp_get_item().
static int rp_coord_get (void * priv_data, struct coord * c, int count) static
Returns the coordinates of a route graph item.
Parameters
priv_data The route graph item's private data
c Pointer where to store the coordinates
count How many coordinates to get at a max?
Returns
The number of coordinates retrieved
References route_graph_point::c, route_graph_segment::end, i, map_rect_priv::item, map_rect_priv::last_coord, map_rect_priv::mpriv, p, map_rect_priv::point, projection_mg, projection_none, map_priv::route, route_projection(), map_rect_priv::rseg, route_graph_point::seg, route_graph_segment::start, transform_from_to(), and item::type.
static void rp_destroy (struct map_priv * priv) static
References g_free().
static struct item* rp_get_item (struct map_rect_priv * mr) static
References map_rect_priv::coord_sel, route::graph, route_graph::hash, map_rect_priv::hash_bucket, route_graph_point::hash_next, HASH_SIZE, item::id_lo, map_rect_priv::it, map_rect_priv::item, map_rect_priv::mpriv, route_graph_segment::next, NULL, p, map_rect_priv::point, rm_coord_rewind(), map_priv::route, route_graph_get_point_last(), route_graph::route_segments, rp_attr_rewind(), rp_iterator_new(), rp_iterator_next(), map_rect_priv::rseg, and item::type.
Referenced by rp_get_item_byid().
static struct item* rp_get_item_byid (struct map_rect_priv * mr, int id_hi, int id_lo) static
References NULL, and rp_get_item().
static int rp_iterator_end (struct route_graph_point_iterator * it) static
Checks if the last segment returned from a route_graph_point_iterator comes from the end.
Parameters
it The route graph point iterator to be checked
Returns
1 if the last segment returned comes from the end of the route graph point, 0 otherwise
References route_graph_point::end, route_graph_point_iterator::end, route_graph_point_iterator::next, and route_graph_point_iterator::p.
Referenced by route_check_roundabout().
static struct route_graph_point_iterator rp_iterator_new (struct route_graph_point * p) static
Creates a new graph point iterator.
This function creates a new route graph point iterator, that can be used to iterate through all segments connected to the point.
Parameters
p The route graph point to create the iterator from
Returns
A new iterator.
References route_graph_point_iterator::end, route_graph_point_iterator::next, p, and route_graph_point_iterator::p.
Referenced by route_check_roundabout(), and rp_get_item().
static struct route_graph_segment* rp_iterator_next (struct route_graph_point_iterator * it) static
Gets the next segment connected to a route graph point from an iterator.
Parameters
it The route graph point iterator to get the segment from
Returns
The next segment or NULL if there are no more segments
References route_graph_point::end, route_graph_point_iterator::end, route_graph_segment::end_next, route_graph_point_iterator::next, NULL, route_graph_point_iterator::p, and route_graph_segment::start_next.
Referenced by route_check_roundabout(), and rp_get_item().
static struct map_rect_priv* rp_rect_new (struct map_priv * priv, struct map_selection * sel) static
Opens a new map rectangle on the route graph's map.
This function opens a new map rectangle on the route graph's map. The "sel" parameter enables you to only search for a single route graph point on this map (or exactly: open a map rectangle that only contains this one point). To do this, pass here a single map selection, whose c_rect has both coordinates set to the same point. Otherwise this parameter has no effect.
Parameters
priv The route graph map's private data
sel Here it's possible to specify a point for which to search. Please read the function's description.
Returns
A new map rect's private data
References map_selection::c_rect, map_rect_priv::coord_sel, dbg, g_malloc(), g_new0, route::graph, map_rect_priv::item, coord_rect::lu, lvl_debug, item::meth, methods_point_item, map_rect_priv::mpriv, NULL, item::priv_data, coord_rect::rl, map_priv::route, item::type, map_selection::u, coord::x, and coord::y.
struct street_data* street_data_dup (struct street_data * orig)
Copies street data.
Parameters
orig The street data to copy
Returns
The copied street data
References g_malloc(), and size.
Referenced by route_set_position_from_tracking().
void street_data_free (struct street_data * sd)
Frees street data.
Parameters
sd Street data to be freed
References g_free().
Referenced by NGQPoint::_coordName(), item_get_heightline(), map_route_occluded_buildings_free(), map_route_occluded_get_item(), map_route_occluded_rect_destroy(), route_find_nearest_street(), route_info_free(), tracking_doupdate_lines(), and tracking_flush().
struct street_data* street_get_data (struct item * item)
Gets street data for an item.
Parameters
item The item to get the data for
Returns
Street data for the item
References AF_SPEED_LIMIT, street_data::c, c, street_data::count, street_data::flags, g_free(), g_realloc(), item, street_data::item, item_attr_get(), item_coord_get(), item_get_default_flags(), street_data::maxspeed, NULL, attr::num, item::type, and attr::u.
Referenced by route_find_nearest_street().
Variable Documentation
int debug_route =0
Referenced by route_graph_add_segment(), route_graph_flood(), and route_graph_point_new().
struct item_methods methods_point_item static
Initial value:
= {
        rm_coord_rewind,
        rp_coord_get,
        rp_attr_rewind,
        rp_attr_get,
}
Referenced by rp_rect_new().
struct item_methods methods_route_item static
Initial value:
= {
        rm_coord_rewind,
        rm_coord_get,
        rm_attr_rewind,
        rm_attr_get,
}
Referenced by rm_rect_new().
struct object_func route_func
Initial value:
= {
        attr_route,
        (object_func_new)route_new,
        (object_func_get_attr)route_get_attr,
        (object_func_iter_new)NULL,
        (object_func_iter_destroy)NULL,
        (object_func_set_attr)route_set_attr,
        (object_func_add_attr)route_add_attr,
        (object_func_remove_attr)route_remove_attr,
        (object_func_init)NULL,
        (object_func_destroy)route_destroy,
        (object_func_dup)route_dup,
        (object_func_ref)navit_object_ref,
        (object_func_unref)navit_object_unref,
}
Referenced by object_func_lookup(), route_dup(), and route_new().
struct map_methods route_graph_meth static
Initial value:
= {
        projection_mg,
        "utf-8",
        rp_destroy,
        rp_rect_new,
        rm_rect_destroy,
        rp_get_item,
        rp_get_item_byid,
        NULL,
        NULL,
        NULL,
}
Referenced by route_map_new_helper().
struct map_methods route_meth static
Initial value:
= {
        projection_mg,
        "utf-8",
        rm_destroy,
        rm_rect_new,
        rm_rect_destroy,
        rm_get_item,
        rm_get_item_byid,
        NULL,
        NULL,
        NULL,
}
Referenced by route_map_new_helper().
struct map_selection* route_selection
FIXME
Parameters
<>
Returns
<>
Author
Martin Schaller (04/2008)
Referenced by do_draw().