navit: script.c File Reference
script.c File Reference
#include <glib.h>
#include "item.h"
#include "debug.h"
#include "event.h"
#include "callback.h"
#include "command.h"
#include "xmlconfig.h"
Data Structures
struct script
Functions
static void script_run (struct script *scr)
static int script_set_attr_int (struct script *scr, struct attr *attr)
static struct script * script_new (struct attr *parent, struct attr **attrs)
static void script_destroy (struct script *scr)
Variables
struct object_func script_func
Function Documentation
static void script_destroy (struct script * scr) static
References attr_list_free(), callback_destroy(), script::cb, command_saved_destroy(), script::cs, dbg, event_remove_timeout(), g_free(), lvl_debug, and script::timeout.
static struct script* script_new (struct attr * parent, struct attr ** attrs) static
References attr_list_dup(), callback_cast, callback_new_1, script::cb, dbg, g_new0, lvl_debug, navit_object_ref(), script::parent, script_func, script_run(), and script_set_attr_int().
static void script_run (struct script * scr) static
References attr_search(), command_evaluate_to_void(), dbg, lvl_debug, lvl_error, NULL, script::parent, attr::str, and attr::u.
Referenced by script_new().
static int script_set_attr_int (struct script * scr, struct attr * attr) static
References script::cb, command_saved_attr_new(), command_saved_destroy(), script::cs, dbg, event_add_timeout(), event_remove_timeout(), lvl_debug, attr::num, script::parent, attr::str, script::timeout, attr::type, and attr::u.
Referenced by script_new().
Variable Documentation
struct object_func script_func
Initial value:
= {
        attr_script,
        (object_func_new)script_new,
        (object_func_get_attr)navit_object_get_attr,
        (object_func_iter_new)navit_object_attr_iter_new,
        (object_func_iter_destroy)navit_object_attr_iter_destroy,
        (object_func_set_attr)navit_object_set_attr,
        (object_func_add_attr)navit_object_add_attr,
        (object_func_remove_attr)navit_object_remove_attr,
        (object_func_init)NULL,
        (object_func_destroy)script_destroy,
        (object_func_dup)NULL,
        (object_func_ref)navit_object_ref,
        (object_func_unref)navit_object_unref,
}
Referenced by object_func_lookup(), and script_new().