navit: search_houseno_interpol.h File Reference
search_houseno_interpol.h File Reference
Data Structures
struct house_number_interpolation
Enumerations
enum include_end_nodes { end_nodes_yes, end_nodes_no }
Functions
void house_number_interpolation_clear_current (struct house_number_interpolation *inter)
void house_number_interpolation_clear_all (struct house_number_interpolation *inter)
char * search_next_interpolated_house_number (struct item *item, struct house_number_interpolation *inter, char *inter_match, int inter_partial)
struct pcoord * search_house_number_coordinate (struct item *item, struct house_number_interpolation *inter)
Enumeration Type Documentation
enum include_end_nodes
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
Boston, MA 02110-1301, USA.
Enumerator
end_nodes_yes
end_nodes_no
Function Documentation
void house_number_interpolation_clear_all (struct house_number_interpolation * inter)
References house_number_interpolation::curr_interpol_attr_idx, and house_number_interpolation_clear_current().
Referenced by search_list_get_result(), and search_list_search().
void house_number_interpolation_clear_current (struct house_number_interpolation * inter)
References house_number_interpolation::curr, house_number_interpolation::first, g_free(), house_number_interpolation::include_end_nodes, house_number_interpolation::increment, house_number_interpolation::last, and NULL.
Referenced by house_number_interpolation_clear_all(), and search_next_interpolated_house_number().
struct pcoord* search_house_number_coordinate (struct item * item, struct house_number_interpolation * inter)
References c, house_number_interpolation::curr, dbg, distances, house_number_interpolation::first, g_alloca, g_free(), g_new, i, house_number_interpolation::increment, item_coord_get(), item_coord_rewind(), item_to_name(), house_number_interpolation::last, lvl_debug, lvl_error, item::map, map_projection(), max, navit_sqrt, NULL, pcoord::pro, house_number_interpolation::rev, transform_distance_sq(), item::type, coord::x, pcoord::x, coord::y, and pcoord::y.
Referenced by search_list_house_number_new().
char* search_next_interpolated_house_number (struct item * item, struct house_number_interpolation * inter, char * inter_match, int inter_partial)
References house_number_interpolation::curr_interpol_attr_idx, hn_interpol_attr::house_number_interpol_attr, house_number_interpol_attr_END, house_number_interpolation_clear_current(), house_number_interpolation::include_end_nodes, hn_interpol_attr::include_end_nodes, house_number_interpolation::increment, hn_interpol_attr::interpol_increment, item_attr_get(), item::map, map_convert_string(), NULL, search_house_number_interpolation_split(), search_match(), search_next_house_number_curr_interpol(), attr::str, and attr::u.
Referenced by search_list_house_number_new().