navit: search.h File Reference
search.h File Reference
Data Structures
struct search_list_common
struct search_list_country
struct search_list_town
struct search_list_street
struct search_list_house_number
struct search_list_result
Functions
struct search_list * search_list_new (struct mapset *ms)
Create new instance of search_list to run a search.
int search_list_level (enum attr_type attr_type)
Determine search list level for given attr_type.
void search_list_search (struct search_list *this_, struct attr *search_attr, int partial)
Start a search.
char * search_postal_merge (char *mask, char *new_)
char * search_postal_merge_replace (char *mask, char *new_)
struct search_list_common * search_list_select (struct search_list *this_, enum attr_type attr_type, int id, int mode)
char * search_list_get_unique (struct search_list *this_, char *unique)
struct search_list_result * search_list_get_result (struct search_list *this_)
Get (next) result from a search.
void search_list_destroy (struct search_list *this_)
void search_init (void)
Function Documentation
void search_init (void)
Referenced by main_real().
void search_list_destroy (struct search_list * this_)
References g_free(), and search_list::postal.
Referenced by android_search_end(), gui_internal_search_list_destroy(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), notify_destroy(), request_search_list_destroy(), search_by_address(), and NGQProxySearch::~NGQProxySearch().
struct search_list_result* search_list_get_result (struct search_list * this_)
Get (next) result from a search.
Parameters
this_ search_list representing the search
Returns
next result
References search_list::address_results_pos, search_list_level::attr, search_list_common::c, search_list_result::c, search_list_country::common, search_list_town::common, search_list_street::common, search_list_house_number::common, search_list_result::country, search_list_level::curr, _GList::data, dbg, g_hash_table_destroy(), g_hash_table_new(), g_list_next, search_list_level::hash, search_list_result::house_number, search_list_house_number::house_number_interpolation, house_number_interpolation_clear_all(), search_list_result::id, search_list::inter, search_list_common::item, search_list::item, item_attr_get(), search_list_level::last, search_list::level, level, search_list::levels, lvl_debug, mapset_search_destroy(), mapset_search_get_item(), mapset_search_new(), search_list::ms, search_list_street::name, navit_utf8_strcasecmp(), NULL, p, search_list_common::parent, search_list_level::parent, search_list_level::partial, search_list::postal, postal_match(), search_list::result, search_list_level::search, search_add_result(), search_item_hash_equal(), search_item_hash_hash(), search_list_country_new(), search_list_house_number_destroy(), search_list_house_number_new(), search_list_result_destroy(), search_list_street_new(), search_list_town_new(), search_list_common::selected, search_list_level::selected, attr::str, search_list_result::street, search_list_result::town, attr::u, and search_list::use_address_results.
Referenced by android_search_idle(), changed(), gui_internal_search_idle(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), NGQProxySearch::NGQProxySearch(), notify_apply(), notify_textchange(), request_search_list_get_result(), search_by_address_attr(), NGQProxySearch::searchXml(), NGQProxySearch::setCountryName(), NGQProxySearch::setPointToResult(), and Backend::updateSearch().
char* search_list_get_unique (struct search_list * this_, char * unique)
int search_list_level (enum attr_type attr_type)
Determine search list level for given attr_type.
Parameters
attr_type attribute value
Returns
corresponding search list level (country=0, town=1, ...)
References attr_to_name(), dbg, and lvl_error.
Referenced by android_search_idle(), search_list_search(), and search_list_select().
struct search_list* search_list_new (struct mapset * ms)
Create new instance of search_list to run a search.
Parameters
ms mapset that is to be searched
Returns
new search_list
References g_new0, and search_list::ms.
Referenced by create_destination_window(), destination_address(), gui_internal_search_list_new(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), NGQProxySearch::NGQProxySearch(), request_search_list_new(), search_by_address(), and Backend::updateSearch().
void search_list_search (struct search_list * this_, struct attr * search_attr, int partial)
Start a search.
Parameters
this search_list to use for the search
search_attr attributes to use for the search
partial do partial search? (1=yes,0=no)
References search_list_level::attr, attr_dup(), attr_to_name(), search_list_level::curr, dbg, g_free(), g_strdup(), house_number_interpolation_clear_all(), search_list_result::id, search_list::inter, search_list::item, search_list::level, level, search_list::levels, search_list_level::list, lvl_info, NULL, search_list_level::partial, search_list::postal, search_list::result, search_address_results_free(), search_by_address(), search_list_level(), search_list_search_free(), attr::str, attr::type, attr::u, and search_list::use_address_results.
Referenced by android_search_idle(), changed(), gui_internal_search_changed(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), Java_org_navitproject_navit_NavitGraphics_GetAllCountries(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), NGQProxySearch::NGQProxySearch(), notify_apply(), notify_textchange(), request_search_list_search(), search_by_address_attr(), NGQProxySearch::searchXml(), NGQProxySearch::setCountryName(), NGQProxySearch::setPointToResult(), NGQProxySearch::setStreetName(), NGQProxySearch::setTownName(), start_search(), and Backend::updateSearch().
struct search_list_common* search_list_select (struct search_list * this_, enum attr_type attr_type, int id, int mode)
References _GList::data, g_list_next, search_list_level::last, level, search_list::levels, search_list_level::list, NULL, num, search_list_level(), search_list_common::selected, and search_list_level::selected.
Referenced by gui_internal_cmd2_town(), gui_internal_search_house_number(), gui_internal_search_house_number_in_street(), gui_internal_search_street(), gui_internal_search_street_in_town(), gui_internal_search_town(), gui_internal_search_town_in_country(), and request_search_list_select().
char* search_postal_merge (char * mask, char * new_)
References dbg, g_strdup(), i, lvl_debug, and NULL.
Referenced by search_add_result(), and search_postal_merge_replace().
char* search_postal_merge_replace (char * mask, char * new_)
References g_free(), mask, and search_postal_merge().