navit: support/win32/serial_io.c File Reference
serial_io.c File Reference
#include <stdio.h>
#include <windows.h>
#include <glib.h>
#include "serial_io.h"
#include "debug.h"
Functions
int serial_io_init (const char *port, const char *strsettings)
int serial_io_read (int fd, char *buffer, int buffer_size)
int serial_io_write (int fd, const char *buffer)
void serial_io_shutdown (int fd)
Function Documentation
int serial_io_init (const char * port, const char * strsettings)
Description: initialise a serial port communication
Parameters
port : port name example 'COM7'
strsettings : port settings example ; 'baud=115200 parity=N data=8 stop=1'
Returns
file descriptor -1 if error
References dbg, g_snprintf(), lvl_debug, lvl_warning, and NULL.
Referenced by vehicle_file_open().
int serial_io_read (int fd, char * buffer, int buffer_size)
Description: Read bytes on the serial port
Parameters
fd : file descriptor
buffer : buffer for data
buffer_size : size in byte of the buffer
Returns
number of bytes read
Remarks
buffer must be allocated by the caller
References dbg, lvl_debug, lvl_info, and NULL.
void serial_io_shutdown (int fd)
Description: Terminate serial communication
Parameters
fd : file descriptor
References dbg, and lvl_debug.
Referenced by vehicle_file_close().
int serial_io_write (int fd, const char * buffer)
Description: Write bytes on the serial port
Parameters
fd : file descriptor
buffer : data buffer (null terminated)
Returns
number of bytes written
References dbg, lvl_debug, and NULL.