navit: support/espeak/setlengths.c File Reference
setlengths.c File Reference
#include "StdAfx.h"
#include <stdlib.h>
#include <stdio.h>
#include <wctype.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Functions
int GetAmplitude (void)
void SetSpeed (int control)
void SetParameter (int parameter, int value, int relative)
static void DoEmbedded2 (int *embix)
void CalcLengths (Translator *tr)
Variables
static unsigned char speed_lookup [290]
static unsigned char faster []
static int speed1 = 130
static int speed2 = 121
static int speed3 = 118
Function Documentation
void CalcLengths (Translator * tr)
References PHONEME_LIST::amp, PHONEME_TAB::code, DoEmbedded2(), embedded_ix, PHONEME_LIST::env, envelope_data, Translator::langopts, PHONEME_LIST::length, PHONEME_TAB::length_mod, LANGUAGE_OPTIONS::length_mods, LANGUAGE_OPTIONS::length_mods0, LANGUAGE_OPTIONS::long_stop, LookupEnvelope(), LOPT_MAXAMP_EOC, min_drop, PHONEME_TAB::mnemonic, n_phoneme_list, PHONEME_LIST::newword, next, NULL, p, LANGUAGE_OPTIONS::param, PHONEME_LIST::ph, phBRKAFTER, PHONEME_TAB::phflags, phFORTIS, phFRICATIVE, phLENGTHENSTOP, phLIQUID, phNASAL, phNONSYLLABIC, phoneme_list, phoneme_tab, phonPAUSE_CLAUSE, phonPAUSE_VSHORT, phPAUSE, phSIBILANT, phSTOP, phVFRICATIVE, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PITCHfall, PITCHrise, PHONEME_LIST::prepause, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_SEQCONTINUE, SFLAG_SYLLABLE, PHONEME_TAB::spect, speed1, speed2, speed3, PHONEME_TAB::std_length, Translator::stress_amps, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, PHONEME_LIST::stresslevel, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, type, PHONEME_LIST::type, and LANGUAGE_OPTIONS::word_gap.
Referenced by SpeakNextClause().
static void DoEmbedded2 (int * embix) static
References EMBED_S, embedded_list, SetEmbedded(), and SetSpeed().
Referenced by CalcLengths().
int GetAmplitude (void)
References EMBED_A, EMBED_F, embedded_value, and general_amplitude.
Referenced by SetEmbedded(), SetParameter(), and WavegenSetEcho().
void SetParameter (int parameter, int value, int relative)
References EMBED_A, EMBED_P, EMBED_R, EMBED_S, EMBED_S2, embedded_value, espeakINTONATION, espeakLINELENGTH, espeakPITCH, espeakRANGE, espeakRATE, espeakVOLUME, espeakWORDGAP, GetAmplitude(), LANGUAGE_OPTIONS::intonation_group, Translator::langopts, option_linelength, option_tone_flags, option_wordgap, param_defaults, param_stack, PARAM_STACK::parameter, SetSpeed(), translator, and value.
Referenced by espeak_Initialize(), espeak_new(), espeak_SetParameter(), LoadMbrolaTable(), and main().
void SetSpeed (int control)
References EMBED_S, EMBED_S2, embedded_value, SPEED_FACTORS::fast_settings, faster, SPEED_FACTORS::min_sample_len, s1, speed, speed1, speed2, speed3, SPEED_FACTORS::speed_factor1, SPEED_FACTORS::speed_factor2, SPEED_FACTORS::speed_factor3, speed_lookup, voice_t::speedf1, voice_t::speedf2, voice_t::speedf3, and voice.
Referenced by DoEmbedded(), DoEmbedded2(), LoadVoice(), and SetParameter().
Variable Documentation
unsigned char faster[] static
Initial value:
= {
114,112,110,109,107,105,104,102,100,98,
96,94,92,90,88,85,83,80,78,75,72 }
Referenced by SetSpeed().
int speed1 = 130 static
Referenced by CalcLengths(), and SetSpeed().
int speed2 = 121 static
Referenced by CalcLengths(), and SetSpeed().
int speed3 = 118 static
Referenced by CalcLengths(), and SetSpeed().
unsigned char speed_lookup[290] static
Referenced by SetSpeed().