navit: tools/gpx2navit_txt/src/setpath.c File Reference
setpath.c File Reference
#include "gpx2navit_txt.h"
Functions
void initPathAttr (pathattr *pattr, g2sattr *attr)
void setEdge (parsedata *pdata, double _x, double _y, double _z, double length, double interval, double speed)
void setPathInterval (parsedata *pdata)
void setPathData (pathattr *pattr, g2sattr *attr)
void countUnconverted (parsedata *pdata)
void countPath (parsedata *pdata)
int checkPath (parsedata *pdata)
void setPath (parsedata *pdata)
Function Documentation
int checkPath (parsedata * pdata)
References pathattr::count, countUnconverted(), fprintf(), pathattr::interval, pathattr::length, g2sprop::length2meter, g2sprop::minlength, g2sprop::minpoints, g2sprop::mintime, g2sprop::nospeedcheck, parsedata::parser, parsedata::pattr, parsedata::prop, g2sprop::sourcefile, pathattr::speed, and g2sprop::time2sec.
Referenced by setPath().
void countPath (parsedata * pdata)
counts paths
References pathattr::count, parsedata::current, pathattr::length, parent::name, parsedata::pattr, parsedata::prop, g2sstats::rtecount, g2sstats::rtelength, g2sstats::rtepoints, g2sprop::stats, g2sstats::trkcount, g2sstats::trklength, and g2sstats::trkpoints.
Referenced by setPath().
void countUnconverted (parsedata * pdata)
counts paths that wasn't converted
References parsedata::current, parent::name, parsedata::prop, g2sstats::rteunconverted, g2sprop::stats, and g2sstats::trkunconverted.
Referenced by checkPath().
void initPathAttr (pathattr * pattr, g2sattr * attr)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
initialize a path attribute
References pathattr::cmt, g2sattr::cmt, pathattr::count, pathattr::desc, g2sattr::desc, pathattr::interval, pathattr::length, pathattr::link, g2sattr::link, pathattr::name, g2sattr::name, NULL, pathattr::number, g2sattr::number, pathattr::point, pathattr::speed, pathattr::src, g2sattr::src, pathattr::type, and g2sattr::type.
Referenced by startElementControl().
void setEdge (parsedata * pdata, double _x, double _y, double _z, double length, double interval, double speed)
set edge data and store it
References parsedata::attr, parsedata::current, g2sattr::ele, pathattr::interval, g2sprop::is3d, g2sattr::lat, length, pathattr::length, g2sattr::lon, parent::name, parsedata::pattr, parsedata::prop, speed, and pathattr::speed.
Referenced by setPathInterval().
void setPath (parsedata * pdata)
saves path data into files.
References checkPath(), pathattr::count, countPath(), pathattr::desc, parsedata::fp, fprintf(), getSpeed(), i, pathattr::interval, g2sprop::is3d, g2sprop::isFast, pathattr::length, pathattr::name, parsedata::pattr, pathattr::point, parsedata::prop, pathattr::speed, g2sprop::speed2meter, g2sprop::speed2sec, and pathattr::type.
Referenced by endElementControl().
void setPathData (pathattr * pattr, g2sattr * attr)
sets each track point data in array.
References pathattr::count, g2sattr::ele, g2sattr::lat, g2sattr::lon, and pathattr::point.
Referenced by endElementControl().
void setPathInterval (parsedata * pdata)
sets interval data between two track points
References parsedata::attr, pathattr::count, g2sattr::ele, getDistance(), getSpeed(), getTimeInterval(), pathattr::interval, g2sprop::isEdge, g2sattr::lat, pathattr::length, g2sattr::lon, parsedata::pattr, parsedata::prop, setEdge(), g2sprop::speed2meter, g2sprop::speed2sec, g2sattr::time, and TIMELENGTH.
Referenced by endElementControl().