navit: support/shapefile/shapefil.h File Reference
shapefil.h File Reference
#include <stdio.h>
Data Structures
struct SAHooks
struct SHPInfo
struct tagSHPObject
struct shape_tree_node
struct SHPTree
struct DBFInfo
Macros
#define TRIM_DBF_WHITESPACE
#define DISABLE_MULTIPATCH_MEASURE
#define SHPAPI_CALL
#define SHPAPI_CALL1(x) x SHPAPI_CALL
#define SHP_CVSID(string)
#define SHPT_NULL 0
#define SHPT_POINT 1
#define SHPT_ARC 3
#define SHPT_POLYGON 5
#define SHPT_MULTIPOINT 8
#define SHPT_POINTZ 11
#define SHPT_ARCZ 13
#define SHPT_POLYGONZ 15
#define SHPT_MULTIPOINTZ 18
#define SHPT_POINTM 21
#define SHPT_ARCM 23
#define SHPT_POLYGONM 25
#define SHPT_MULTIPOINTM 28
#define SHPT_MULTIPATCH 31
#define SHPP_TRISTRIP 0
#define SHPP_TRIFAN 1
#define SHPP_OUTERRING 2
#define SHPP_INNERRING 3
#define SHPP_FIRSTRING 4
#define SHPP_RING 5
#define MAX_SUBNODE 4
#define MAX_DEFAULT_TREE_DEPTH 12
#define XBASE_FLDHDR_SZ 32
#define XBASE_FLDNAME_LEN_READ 11
#define XBASE_FLDNAME_LEN_WRITE 10
#define XBASE_FLD_MAX_WIDTH 255
Typedefs
typedef int * SAFile
typedef unsigned long SAOffset
typedef struct tagSHPObject SHPObject
typedef SHPInfo * SHPHandle
typedef struct shape_tree_node SHPTreeNode
typedef struct SBNSearchInfo * SBNSearchHandle
typedef DBFInfo * DBFHandle
Enumerations
enum DBFFieldType {
FTString, FTInteger, FTDouble, FTLogical,
FTInvalid
}
Functions
void SHPAPI_CALL SASetupDefaultHooks (SAHooks *psHooks)
SHPHandle SHPAPI_CALL SHPOpen (const char *pszShapeFile, const char *pszAccess)
SHPHandle SHPAPI_CALL SHPOpenLL (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks)
SHPHandle SHPAPI_CALL SHPOpenLLEx (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks, int bRestoreSHX)
int SHPAPI_CALL SHPRestoreSHX (const char *pszShapeFile, const char *pszAccess, SAHooks *psHooks)
void SHPAPI_CALL SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
SHPHandle SHPAPI_CALL SHPCreate (const char *pszShapeFile, int nShapeType)
SHPHandle SHPAPI_CALL SHPCreateLL (const char *pszShapeFile, int nShapeType, SAHooks *psHooks)
void SHPAPI_CALL SHPGetInfo (SHPHandle hSHP, int *pnEntities, int *pnShapeType, double *padfMinBound, double *padfMaxBound)
SHPObject SHPAPI_CALL1 * SHPReadObject (SHPHandle hSHP, int iShape);int SHPAPI_CALLSHPWriteObject(SHPHandle hSHP, int iShape, SHPObject *psObject
void SHPAPI_CALL SHPDestroyObject (SHPObject *psObject)
void SHPAPI_CALL SHPComputeExtents (SHPObject *psObject)
SHPObject SHPAPI_CALL1 * SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int *panPartStart, const int *panPartType, int nVertices, const double *padfX, const double *padfY, const double *padfZ, const double *padfM);SHPObject SHPAPI_CALL1(*) SHPCreateSimpleObject(int nSHPType, int nVertices, const double *padfX, const double *padfY, const double *padfZ
int SHPAPI_CALL SHPRewindObject (SHPHandle hSHP, SHPObject *psObject)
void SHPAPI_CALL SHPClose (SHPHandle hSHP)
void SHPAPI_CALL SHPWriteHeader (SHPHandle hSHP)
const char SHPAPI_CALL1 * SHPTypeName (int nSHPType);const char SHPAPI_CALL1(*) SHPPartTypeName(int nPartType
SHPTree SHPAPI_CALL1 * SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double *padfBoundsMin, double *padfBoundsMax);void SHPAPI_CALLSHPDestroyTree(SHPTree *hTree
int SHPAPI_CALL SHPWriteTree (SHPTree *hTree, const char *pszFilename)
int SHPAPI_CALL SHPTreeAddShapeId (SHPTree *hTree, SHPObject *psObject)
int SHPAPI_CALL SHPTreeRemoveShapeId (SHPTree *hTree, int nShapeId)
void SHPAPI_CALL SHPTreeTrimExtraNodes (SHPTree *hTree)
int SHPAPI_CALL1 * SHPTreeFindLikelyShapes (SHPTree *hTree, double *padfBoundsMin, double *padfBoundsMax, int *);int SHPAPI_CALLSHPCheckBoundsOverlap(double *, double *, double *, double *, int
int SHPAPI_CALL1 * SHPSearchDiskTree (FILE *fp, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount);typedef struct SHPDiskTreeInfo *SHPTreeDiskHandle;SHPTreeDiskHandle SHPAPI_CALLSHPOpenDiskTree(const char *pszQIXFilename, SAHooks *psHooks
void SHPAPI_CALL SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
int SHPAPI_CALL1 * SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount);int SHPAPI_CALLSHPWriteTreeLL(SHPTree *hTree, const char *pszFilename, SAHooks *psHooks
SBNSearchHandle SHPAPI_CALL SBNOpenDiskTree (const char *pszSBNFilename, SAHooks *psHooks)
void SHPAPI_CALL SBNCloseDiskTree (SBNSearchHandle hSBN)
int SHPAPI_CALL1 * SBNSearchDiskTree (SBNSearchHandle hSBN, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount);int SHPAPI_CALL1(*) SBNSearchDiskTreeInteger(SBNSearchHandle hSBN, int bMinX, int bMinY, int bMaxX, int bMaxY, int *pnShapeCount
void SHPAPI_CALL SBNSearchFreeIds (int *panShapeId)
DBFHandle SHPAPI_CALL DBFOpen (const char *pszDBFFile, const char *pszAccess)
DBFHandle SHPAPI_CALL DBFOpenLL (const char *pszDBFFile, const char *pszAccess, SAHooks *psHooks)
DBFHandle SHPAPI_CALL DBFCreate (const char *pszDBFFile)
DBFHandle SHPAPI_CALL DBFCreateEx (const char *pszDBFFile, const char *pszCodePage)
DBFHandle SHPAPI_CALL DBFCreateLL (const char *pszDBFFile, const char *pszCodePage, SAHooks *psHooks)
int SHPAPI_CALL DBFGetFieldCount (DBFHandle psDBF)
int SHPAPI_CALL DBFGetRecordCount (DBFHandle psDBF)
int SHPAPI_CALL DBFAddField (DBFHandle hDBF, const char *pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
int SHPAPI_CALL DBFAddNativeFieldType (DBFHandle hDBF, const char *pszFieldName, char chType, int nWidth, int nDecimals)
int SHPAPI_CALL DBFDeleteField (DBFHandle hDBF, int iField)
int SHPAPI_CALL DBFReorderFields (DBFHandle psDBF, int *panMap)
int SHPAPI_CALL DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char *pszFieldName, char chType, int nWidth, int nDecimals)
DBFFieldType SHPAPI_CALL DBFGetFieldInfo (DBFHandle psDBF, int iField, char *pszFieldName, int *pnWidth, int *pnDecimals)
int SHPAPI_CALL DBFGetFieldIndex (DBFHandle psDBF, const char *pszFieldName)
int SHPAPI_CALL DBFReadIntegerAttribute (DBFHandle hDBF, int iShape, int iField)
double SHPAPI_CALL DBFReadDoubleAttribute (DBFHandle hDBF, int iShape, int iField)
const char SHPAPI_CALL1 * DBFReadStringAttribute (DBFHandle hDBF, int iShape, int iField);const char SHPAPI_CALL1(*) DBFReadLogicalAttribute(DBFHandle hDBF, int iShape, int iField
int SHPAPI_CALL DBFIsAttributeNULL (DBFHandle hDBF, int iShape, int iField)
int SHPAPI_CALL DBFWriteIntegerAttribute (DBFHandle hDBF, int iShape, int iField, int nFieldValue)
int SHPAPI_CALL DBFWriteDoubleAttribute (DBFHandle hDBF, int iShape, int iField, double dFieldValue)
int SHPAPI_CALL DBFWriteStringAttribute (DBFHandle hDBF, int iShape, int iField, const char *pszFieldValue)
int SHPAPI_CALL DBFWriteNULLAttribute (DBFHandle hDBF, int iShape, int iField)
int SHPAPI_CALL DBFWriteLogicalAttribute (DBFHandle hDBF, int iShape, int iField, const char lFieldValue)
int SHPAPI_CALL DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void *pValue)
const char SHPAPI_CALL1 * DBFReadTuple (DBFHandle psDBF, int hEntity);int SHPAPI_CALLDBFWriteTuple(DBFHandle psDBF, int hEntity, void *pRawTuple
int SHPAPI_CALL DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
int SHPAPI_CALL DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
DBFHandle SHPAPI_CALL DBFCloneEmpty (DBFHandle psDBF, const char *pszFilename)
void SHPAPI_CALL DBFClose (DBFHandle hDBF)
void SHPAPI_CALL DBFUpdateHeader (DBFHandle hDBF)
char SHPAPI_CALL DBFGetNativeFieldType (DBFHandle hDBF, int iField)
const char SHPAPI_CALL1 * DBFGetCodePage (DBFHandle psDBF);void SHPAPI_CALLDBFSetLastModifiedDate(DBFHandle psDBF, int nYYSince1900, int nMM, int nDD
void SHPAPI_CALL DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
Macro Definition Documentation
#define DISABLE_MULTIPATCH_MEASURE
Referenced by SHPWriteObject().
#define MAX_DEFAULT_TREE_DEPTH 12
Referenced by if().
#define MAX_SUBNODE 4
#define SHP_CVSID (string)
Value:
static const char cpl_cvsid[] = string; \
static const char *cvsid_aw() { return(cvsid_aw() ? NULL : cpl_cvsid); }
#define SHPAPI_CALL
#define SHPAPI_CALL1 (x) x SHPAPI_CALL
#define SHPP_FIRSTRING 4
Referenced by SHPPartTypeName().
#define SHPP_INNERRING 3
Referenced by SHPPartTypeName().
#define SHPP_OUTERRING 2
Referenced by SHPPartTypeName().
#define SHPP_RING 5
Referenced by if(), and SHPPartTypeName().
#define SHPP_TRIFAN 1
Referenced by SHPPartTypeName().
#define SHPP_TRISTRIP 0
Referenced by SHPPartTypeName().
#define SHPT_ARC 3
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_ARCM 23
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_ARCZ 13
Referenced by if(), SHPTypeName(), and SHPWriteObject().
#define SHPT_MULTIPATCH 31
Referenced by if(), SHPTypeName(), and SHPWriteObject().
#define SHPT_MULTIPOINT 8
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_MULTIPOINTM 28
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_MULTIPOINTZ 18
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_NULL 0
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_POINT 1
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_POINTM 21
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_POINTZ 11
Referenced by SHPTypeName(), and SHPWriteObject().
#define SHPT_POLYGON 5
Referenced by SHPRewindObject(), SHPTypeName(), and SHPWriteObject().
#define SHPT_POLYGONM 25
Referenced by SHPRewindObject(), SHPTypeName(), and SHPWriteObject().
#define SHPT_POLYGONZ 15
Referenced by if(), SHPRewindObject(), SHPTypeName(), and SHPWriteObject().
#define TRIM_DBF_WHITESPACE
#define XBASE_FLD_MAX_WIDTH 255
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), and DBFWriteAttribute().
#define XBASE_FLDHDR_SZ 32
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFGetFieldInfo(), DBFOpenLL(), DBFReorderFields(), and DBFWriteHeader().
#define XBASE_FLDNAME_LEN_READ 11
Referenced by DBFGetFieldIndex(), and DBFGetFieldInfo().
#define XBASE_FLDNAME_LEN_WRITE 10
Referenced by DBFAddNativeFieldType(), and DBFAlterFieldDefn().
Typedef Documentation
typedef DBFInfo* DBFHandle
typedef int* SAFile
typedef unsigned long SAOffset
typedef struct SBNSearchInfo* SBNSearchHandle
typedef SHPInfo* SHPHandle
typedef struct tagSHPObject SHPObject
typedef struct shape_tree_node SHPTreeNode
Enumeration Type Documentation
enum DBFFieldType
Enumerator
FTString
FTInteger
FTDouble
FTLogical
FTInvalid
Function Documentation
int SHPAPI_CALL DBFAddField (DBFHandle hDBF, const char * pszFieldName, DBFFieldType eType, int nWidth, int nDecimals)
References DBFAddNativeFieldType(), FTLogical, and FTString.
int SHPAPI_CALL DBFAddNativeFieldType (DBFHandle hDBF, const char * pszFieldName, char chType, int nWidth, int nDecimals)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, SAHooks::Error, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
Referenced by DBFAddField().
int SHPAPI_CALL DBFAlterFieldDefn (DBFHandle psDBF, int iField, const char * pszFieldName, char chType, int nWidth, int nDecimals)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, DBFInfo::bWriteEndOfFileChar, DBFFlushRecord(), DBFGetNullCharacter(), DBFIsValueNULL(), DBFUpdateHeader(), END_OF_FILE_CHARACTER, FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FLD_MAX_WIDTH, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_WRITE.
DBFHandle SHPAPI_CALL DBFCloneEmpty (DBFHandle psDBF, const char * pszFilename)
void SHPAPI_CALL DBFClose (DBFHandle hDBF)
References DBFInfo::bNoHeader, DBFInfo::bUpdated, CPL_IGNORE_RET_VAL_INT, DBFFlushRecord(), DBFUpdateHeader(), DBFWriteHeader(), SAHooks::FClose, DBFInfo::fp, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, DBFInfo::pszWorkField, and DBFInfo::sHooks.
DBFHandle SHPAPI_CALL DBFCreate (const char * pszDBFFile)
References DBFCreateEx().
DBFHandle SHPAPI_CALL DBFCreateEx (const char * pszDBFFile, const char * pszCodePage)
References DBFCreateLL(), and SASetupDefaultHooks().
Referenced by DBFCreate().
DBFHandle SHPAPI_CALL DBFCreateLL (const char * pszDBFFile, const char * pszCodePage, SAHooks * psHooks)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, calloc(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, fp, SAHooks::FWrite, i, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SAHooks::Remove, DBFInfo::sHooks, TRUE, and XBASE_FILEHDR_SZ.
Referenced by DBFCreateEx().
int SHPAPI_CALL DBFDeleteField (DBFHandle hDBF, int iField)
const char SHPAPI_CALL1* DBFGetCodePage (DBFHandle psDBF)
References NULL.
int SHPAPI_CALL DBFGetFieldCount (DBFHandle psDBF)
References DBFInfo::nFields.
Referenced by DBFGetFieldIndex(), and map_new_shapefile().
int SHPAPI_CALL DBFGetFieldIndex (DBFHandle psDBF, const char * pszFieldName)
References DBFGetFieldCount(), DBFGetFieldInfo(), i, name, NULL, str_to_upper(), and XBASE_FLDNAME_LEN_READ.
DBFFieldType SHPAPI_CALL DBFGetFieldInfo (DBFHandle psDBF, int iField, char * pszFieldName, int * pnWidth, int * pnDecimals)
References FTDouble, FTInteger, FTInvalid, FTLogical, FTString, i, DBFInfo::nFields, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldSize, DBFInfo::pszHeader, XBASE_FLDHDR_SZ, and XBASE_FLDNAME_LEN_READ.
Referenced by attr_resolve(), DBFGetFieldIndex(), process_fields(), and shapefile_attr_get().
char SHPAPI_CALL DBFGetNativeFieldType (DBFHandle hDBF, int iField)
References DBFInfo::pachFieldType.
int SHPAPI_CALL DBFGetRecordCount (DBFHandle psDBF)
References DBFInfo::nRecords.
int SHPAPI_CALL DBFIsAttributeNULL (DBFHandle hDBF, int iShape, int iField)
References DBFIsValueNULL(), DBFReadStringAttribute(), NULL, DBFInfo::pachFieldType, and TRUE.
int SHPAPI_CALL DBFIsRecordDeleted (DBFHandle psDBF, int iShape)
References DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
int SHPAPI_CALL DBFMarkRecordDeleted (DBFHandle psDBF, int iShape, int bIsDeleted)
References DBFInfo::bCurrentRecordModified, DBFInfo::bUpdated, DBFLoadRecord(), FALSE, DBFInfo::nRecords, DBFInfo::pszCurrentRecord, and TRUE.
DBFHandle SHPAPI_CALL DBFOpen (const char * pszDBFFile, const char * pszAccess)
References DBFOpenLL(), and SASetupDefaultHooks().
Referenced by map_new_shapefile().
DBFHandle SHPAPI_CALL DBFOpenLL (const char * pszDBFFile, const char * pszAccess, SAHooks * psHooks)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, calloc(), DBFSetLastModifiedDate(), DBFSetWriteEndOfFileChar(), FALSE, SAHooks::FClose, SAHooks::FOpen, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, i, DBFInfo::iLanguageDriver, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, NULL, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszCodePage, DBFInfo::pszCurrentRecord, DBFInfo::pszHeader, SfRealloc(), DBFInfo::sHooks, TRUE, XBASE_FILEHDR_SZ, and XBASE_FLDHDR_SZ.
Referenced by DBFOpen().
double SHPAPI_CALL DBFReadDoubleAttribute (DBFHandle hDBF, int iShape, int iField)
References DBFReadAttribute(), and NULL.
Referenced by process_fields(), and shapefile_attr_get().
int SHPAPI_CALL DBFReadIntegerAttribute (DBFHandle hDBF, int iShape, int iField)
References DBFReadAttribute(), and NULL.
Referenced by process_fields(), and shapefile_attr_get().
const char SHPAPI_CALL1* DBFReadStringAttribute (DBFHandle hDBF, int iShape, int iField) const
const char SHPAPI_CALL1* DBFReadTuple (DBFHandle psDBF, int hEntity)
int SHPAPI_CALL DBFReorderFields (DBFHandle psDBF, int * panMap)
References DBFInfo::bCurrentRecordModified, DBFInfo::bNoHeader, DBFInfo::bUpdated, calloc(), DBFFlushRecord(), DBFUpdateHeader(), FALSE, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, DBFInfo::nCurrentRecord, DBFInfo::nFields, DBFInfo::nHeaderLength, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::pachFieldType, DBFInfo::panFieldDecimals, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, DBFInfo::pszHeader, DBFInfo::sHooks, TRUE, and XBASE_FLDHDR_SZ.
void SHPAPI_CALL DBFSetWriteEndOfFileChar (DBFHandle psDBF, int bWriteFlag)
References DBFInfo::bWriteEndOfFileChar.
Referenced by DBFCreateLL(), and DBFOpenLL().
void SHPAPI_CALL DBFUpdateHeader (DBFHandle hDBF)
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFWriteHeader(), SAHooks::FFlush, DBFInfo::fp, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, DBFInfo::nRecords, DBFInfo::nUpdateDay, DBFInfo::nUpdateMonth, DBFInfo::nUpdateYearSince1900, DBFInfo::sHooks, and XBASE_FILEHDR_SZ.
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFClose(), and DBFReorderFields().
int SHPAPI_CALL DBFWriteAttributeDirectly (DBFHandle psDBF, int hEntity, int iField, void * pValue)
References DBFInfo::bNoHeader, DBFFlushRecord(), DBFLoadRecord(), DBFWriteHeader(), FALSE, i, int, DBFInfo::nCurrentRecord, DBFInfo::nRecordLength, DBFInfo::nRecords, DBFInfo::panFieldOffset, DBFInfo::panFieldSize, and DBFInfo::pszCurrentRecord.
int SHPAPI_CALL DBFWriteDoubleAttribute (DBFHandle hDBF, int iShape, int iField, double dFieldValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteIntegerAttribute (DBFHandle hDBF, int iShape, int iField, int nFieldValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteLogicalAttribute (DBFHandle hDBF, int iShape, int iField, const char lFieldValue)
References DBFWriteAttribute().
int SHPAPI_CALL DBFWriteNULLAttribute (DBFHandle hDBF, int iShape, int iField)
References DBFWriteAttribute(), and NULL.
int SHPAPI_CALL DBFWriteStringAttribute (DBFHandle hDBF, int iShape, int iField, const char * pszFieldValue)
References DBFWriteAttribute().
void SHPAPI_CALL SASetupDefaultHooks (SAHooks * psHooks)
References SAHooks::Atof, SAHooks::Error, SAHooks::FClose, SAHooks::FFlush, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, SAHooks::FWrite, SAHooks::Remove, VSI_SHP_Close(), VSI_SHP_Error(), VSI_SHP_Flush(), VSI_SHP_Open(), VSI_SHP_Read(), VSI_SHP_Remove(), VSI_SHP_Seek(), VSI_SHP_Tell(), and VSI_SHP_Write().
Referenced by DBFCreateEx(), DBFOpen(), SHPCreate(), SHPOpen(), SHPOpenDiskTree(), SHPWriteTree(), and SHPWriteTreeLL().
void SHPAPI_CALL SBNCloseDiskTree (SBNSearchHandle hSBN)
SBNSearchHandle SHPAPI_CALL SBNOpenDiskTree (const char * pszSBNFilename, SAHooks * psHooks)
int SHPAPI_CALL1* SBNSearchDiskTree (SBNSearchHandle hSBN, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
void SHPAPI_CALL SBNSearchFreeIds (int * panShapeId)
void SHPAPI_CALL SHPClose (SHPHandle hSHP)
References SHPInfo::bUpdated, SAHooks::FClose, SHPInfo::fpSHP, SHPInfo::fpSHX, NULL, SHPInfo::pabyObjectBuf, SHPInfo::pabyRec, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::psCachedObject, SHPInfo::sHooks, and SHPWriteHeader().
Referenced by SHPOpenLL().
void SHPAPI_CALL SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
References NULL.
void SHPAPI_CALL SHPComputeExtents (SHPObject * psObject)
References tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, i, MAX, MIN, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, and tagSHPObject::padfZ.
SHPHandle SHPAPI_CALL SHPCreate (const char * pszShapeFile, int nShapeType)
References SASetupDefaultHooks(), and SHPCreateLL().
SHPHandle SHPAPI_CALL SHPCreateLL (const char * pszShapeFile, int nShapeType, SAHooks * psHooks)
References ByteCopy, errno, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FWrite, i, NULL, SHPOpenLL(), strerror(), SwapWord(), and TRUE.
Referenced by SHPCreate().
SHPObject SHPAPI_CALL1* SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int * panPartStart, const int * panPartType, int nVertices, const double * padfX, const double * padfY, const double * padfZ, const double * padfM) const
SHPTree SHPAPI_CALL1* SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double * padfBoundsMin, double * padfBoundsMax)
void SHPAPI_CALL SHPDestroyObject (SHPObject * psObject)
References tagSHPObject::bFastModeReadObject, FALSE, NULL, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, and tagSHPObject::panPartType.
Referenced by if(), map_rect_destroy_shapefile(), map_rect_get_item_shapefile(), and SHPDestroyTreeNode().
void SHPAPI_CALL SHPGetInfo (SHPHandle hSHP, int * pnEntities, int * pnShapeType, double * padfMinBound, double * padfMaxBound)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, i, SHPInfo::nRecords, SHPInfo::nShapeType, and NULL.
Referenced by if(), and map_new_shapefile().
SHPHandle SHPAPI_CALL SHPOpen (const char * pszShapeFile, const char * pszAccess)
References SASetupDefaultHooks(), and SHPOpenLL().
Referenced by map_new_shapefile().
SHPHandle SHPAPI_CALL SHPOpenLL (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, SHPInfo::bUpdated, calloc(), errno, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, i, int, MAX, SHPInfo::nFileSize, SHPInfo::nMaxRecords, SHPInfo::nRecords, SHPInfo::nShapeType, NULL, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, SHPClose(), strerror(), SwapWord(), and TRUE.
Referenced by SHPCreateLL(), SHPOpen(), and SHPOpenLLEx().
SHPHandle SHPAPI_CALL SHPOpenLLEx (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks, int bRestoreSHX)
References NULL, SHPOpenLL(), and SHPRestoreSHX().
SHPObject SHPAPI_CALL1* SHPReadObject (SHPHandle hSHP, int iShape)
Referenced by if(), and map_rect_get_item_shapefile().
int SHPAPI_CALL SHPRestoreSHX (const char * pszShapeFile, const char * pszAccess, SAHooks * psHooks)
References SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, int, NULL, SwapWord(), and TRUE.
Referenced by SHPOpenLLEx().
int SHPAPI_CALL SHPRewindObject (SHPHandle hSHP, SHPObject * psObject)
int SHPAPI_CALL1* SHPSearchDiskTree (FILE * fp, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount) const
int SHPAPI_CALL1* SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount) const
References calloc(), compare_ints(), FALSE, i, NULL, SEEK_SET, SHPSearchDiskTreeNode(), and TRUE.
void SHPAPI_CALL SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
References SHPInfo::bFastModeReadObject, calloc(), NULL, and SHPInfo::psCachedObject.
int SHPAPI_CALL SHPTreeAddShapeId (SHPTree * hTree, SHPObject * psObject)
References SHPTree::nDimension, SHPTree::nMaxDepth, SHPTree::nTotalCount, SHPTree::psRoot, and SHPTreeNodeAddShapeId().
Referenced by if().
int SHPAPI_CALL1* SHPTreeFindLikelyShapes (SHPTree * hTree, double * padfBoundsMin, double * padfBoundsMax, int *)
int SHPAPI_CALL SHPTreeRemoveShapeId (SHPTree * hTree, int nShapeId)
void SHPAPI_CALL SHPTreeTrimExtraNodes (SHPTree * hTree)
References SHPTree::psRoot.
const char SHPAPI_CALL1* SHPTypeName (int nSHPType) const
References SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_NULL, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, and SHPT_POLYGONZ.
void SHPAPI_CALL SHPWriteHeader (SHPHandle hSHP)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, ByteCopy, errno, SAHooks::Error, SAHooks::FFlush, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FSeek, SAHooks::FWrite, i, SHPInfo::nFileSize, SHPInfo::nRecords, SHPInfo::nShapeType, NULL, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, strerror(), and SwapWord().
Referenced by SHPClose().
int SHPAPI_CALL SHPWriteTree (SHPTree * hTree, const char * pszFilename)
References SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, and SHPWriteTreeLL().