navit: support/shapefile/shpopen.c File Reference
shpopen.c File Reference
#include "shapefil.h"
#include <math.h>
#include <limits.h>
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
Macros
#define FALSE 0
#define TRUE 1
#define ByteCopy(a, b, c) memcpy(b, a, c)
#define MIN(a, b) ((a<b) ? a : b)
#define MAX(a, b) ((a>b) ? a : b)
#define CPL_UNUSED
Typedefs
typedef unsigned char uchar
typedef unsigned int int32
Functions
static void SwapWord (int length, void *wordP)
static void * SfRealloc (void *pMem, int nNewSize)
void SHPAPI_CALL SHPWriteHeader (SHPHandle psSHP)
SHPHandle SHPAPI_CALL SHPOpen (const char *pszLayer, const char *pszAccess)
SHPHandle SHPAPI_CALL SHPOpenLL (const char *pszLayer, const char *pszAccess, SAHooks *psHooks)
SHPHandle SHPAPI_CALL SHPOpenLLEx (const char *pszLayer, const char *pszAccess, SAHooks *psHooks, int bRestoreSHX)
int SHPAPI_CALL SHPRestoreSHX (const char *pszLayer, const char *pszAccess, SAHooks *psHooks)
void SHPAPI_CALL SHPClose (SHPHandle psSHP)
void SHPAPI_CALL SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
void SHPAPI_CALL SHPGetInfo (SHPHandle psSHP, int *pnEntities, int *pnShapeType, double *padfMinBound, double *padfMaxBound)
SHPHandle SHPAPI_CALL SHPCreate (const char *pszLayer, int nShapeType)
SHPHandle SHPAPI_CALL SHPCreateLL (const char *pszLayer, int nShapeType, SAHooks *psHooks)
static void _SHPSetBounds (uchar *pabyRec, SHPObject *psShape)
void SHPAPI_CALL SHPComputeExtents (SHPObject *psObject)
SHPObject SHPAPI_CALL1 * SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int *panPartStart, const int *panPartType, int nVertices, const double *padfX, const double *padfY, const double *padfZ, const double *padfM){SHPObject *psObject;inti, bHasM, bHasZ;psObject=(SHPObject *) calloc(1, sizeof(SHPObject)
if (nSHPType==SHPT_ARCM||nSHPType==SHPT_POINTM||nSHPType==SHPT_POLYGONM||nSHPType==SHPT_MULTIPOINTM)
if (nVertices > 0)
SHPComputeExtents (psObject)
return (psObject)
SHPObject SHPAPI_CALL1 * SHPCreateSimpleObject (int nSHPType, int nVertices, const double *padfX, const double *padfY, const double *padfZ){return(SHPCreateObject(nSHPType,-1, 0, NULL, NULL, nVertices, padfX, padfY, padfZ, NULL)
int SHPAPI_CALL SHPWriteObject (SHPHandle psSHP, int nShapeId, SHPObject *psObject)
static void * SHPAllocBuffer (unsigned char **pBuffer, int nSize)
static unsigned char * SHPReallocObjectBufIfNecessary (SHPHandle psSHP, int nObjectBufSize)
SHPObject SHPAPI_CALL1 * SHPReadObject (SHPHandle psSHP, int hEntity){intnEntitySize, nRequiredSize;SHPObject *psShape;charszErrorMsg[128];intnSHPType;intnBytesRead;if(hEntity< 0||hEntity >=psSHP->nRecords) return(NULL
if (psSHP->panRecOffset[hEntity]==0 &&psSHP->fpSHX!=NULL)
if (nEntitySize > psSHP->nBufSize)
if (psSHP->pabyRec==NULL)
if (psSHP->sHooks.FSeek(psSHP->fpSHP, psSHP->panRecOffset[hEntity], 0)!=0)
if (nBytesRead >=8 &&nBytesRead==nEntitySize-8)
else if (nBytesRead!=nEntitySize)
if (8+4 > nEntitySize)
if (bBigEndian)
if (psShape->nSHPType==SHPT_POLYGON||psShape->nSHPType==SHPT_ARC||psShape->nSHPType==SHPT_POLYGONZ||psShape->nSHPType==SHPT_POLYGONM||psShape->nSHPType==SHPT_ARCZ||psShape->nSHPType==SHPT_ARCM||psShape->nSHPType==SHPT_MULTIPATCH)
return (psShape)
const char SHPAPI_CALL1 * SHPTypeName (int nSHPType){switch(nSHPType
const char SHPAPI_CALL1 * SHPPartTypeName (int nPartType){switch(nPartType
void SHPAPI_CALL SHPDestroyObject (SHPObject *psShape)
int SHPAPI_CALL SHPRewindObject (CPL_UNUSED SHPHandle hSHP, SHPObject *psObject)
Variables
static int bBigEndian
psObject nSHPType = nSHPType
psObject nShapeId = nShapeId
psObject bMeasureIsUsed = FALSE
else
bHasZ = FALSE
psObject nVertices = nVertices
nEntitySize = psSHP->panRecSize[hEntity]+8
nBytesRead = (int)psSHP->sHooks.FRead(psSHP->pabyRec, 1, nEntitySize, psSHP->fpSHP)
else psShape = (SHPObject *) calloc(1,sizeof(SHPObject))
psShape bFastModeReadObject = psSHP->bFastModeReadObject
Macro Definition Documentation
#define ByteCopy (a, b, c) memcpy(b, a, c)
Referenced by _SHPSetBounds(), SHPCreateLL(), SHPWriteHeader(), and SHPWriteObject().
#define CPL_UNUSED
#define FALSE 0
Referenced by if(), SHPCreateLL(), SHPDestroyObject(), SHPOpenLL(), SHPRestoreSHX(), SHPRewindObject(), and SHPWriteObject().
#define MAX (a, b) ((a>b) ? a : b)
Referenced by SHPComputeExtents(), SHPOpenLL(), and SHPWriteObject().
#define MIN (a, b) ((a<b) ? a : b)
Referenced by SHPComputeExtents(), and SHPWriteObject().
#define TRUE 1
Referenced by if(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), and SHPWriteObject().
Typedef Documentation
typedef unsigned int int32
typedef unsigned char uchar
Function Documentation
static void _SHPSetBounds (uchar * pabyRec, SHPObject * psShape) static
References ByteCopy, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, and SwapWord().
Referenced by SHPWriteObject().
if (nSHPType = = SHPT_ARCM || nSHPType == SHPT_POINTM || nSHPType == SHPT_POLYGONM || nSHPType == SHPT_MULTIPOINTM)
References FALSE, and TRUE.
if (nVertices , 0)
References tagSHPObject::bMeasureIsUsed, calloc(), i, NULL, nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, and TRUE.
if (psSHP-> panRecOffset[hEntity] = = 0 && psSHP->fpSHX != NULL)
References NULL, and SwapWord().
if (nEntitySize , psSHP-> nBufSize)
References int, nEntitySize, NULL, and SfRealloc().
if (psSHP-> pabyRec = = NULL)
References NULL.
if (psSHP->sHooks.FSeek(psSHP->fpSHP, psSHP->panRecOffset[hEntity], 0)! = 0)
References NULL.
if (nBytesRead >=8 && nBytesRead = = nEntitySize - 8)
References NULL, and SwapWord().
else if (nBytesRead! = nEntitySize)
References NULL.
if (8+ 4, nEntitySize)
References NULL.
if (bBigEndian)
else if (psShape-> nSHPType = = SHPT_POLYGON || psShape->nSHPType == SHPT_ARC || psShape->nSHPType == SHPT_POLYGONZ || psShape->nSHPType == SHPT_POLYGONM || psShape->nSHPType == SHPT_ARCZ || psShape->nSHPType == SHPT_ARCM || psShape->nSHPType == SHPT_MULTIPATCH)
References tagSHPObject::bFastModeReadObject, tagSHPObject::bMeasureIsUsed, tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, double, i, tagSHPObject::nParts, tagSHPObject::nSHPType, NULL, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, SHPAllocBuffer(), SHPDestroyObject(), SHPP_RING, SHPReallocObjectBufIfNecessary(), SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_POLYGONZ, SwapWord(), and TRUE.
return (psObject)
return (psShape)
static void* SfRealloc (void * pMem, int nNewSize) static
References NULL.
Referenced by if(), and SHPWriteObject().
static void* SHPAllocBuffer (unsigned char ** pBuffer, int nSize) static
References calloc(), and NULL.
Referenced by if().
void SHPAPI_CALL SHPClose (SHPHandle psSHP)
References SHPInfo::bUpdated, SAHooks::FClose, SHPInfo::fpSHP, SHPInfo::fpSHX, NULL, SHPInfo::pabyObjectBuf, SHPInfo::pabyRec, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::psCachedObject, SHPInfo::sHooks, and SHPWriteHeader().
Referenced by SHPOpenLL().
void SHPAPI_CALL SHPComputeExtents (SHPObject * psObject)
References tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, i, MAX, MIN, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, and tagSHPObject::padfZ.
SHPComputeExtents (psObject)
SHPHandle SHPAPI_CALL SHPCreate (const char * pszLayer, int nShapeType)
References SASetupDefaultHooks(), and SHPCreateLL().
SHPHandle SHPAPI_CALL SHPCreateLL (const char * pszLayer, int nShapeType, SAHooks * psHooks)
References ByteCopy, errno, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FWrite, i, NULL, SHPOpenLL(), strerror(), SwapWord(), and TRUE.
Referenced by SHPCreate().
SHPObject SHPAPI_CALL1* SHPCreateObject (int nSHPType, int nShapeId, int nParts, const int * panPartStart, const int * panPartType, int nVertices, const double * padfX, const double * padfY, const double * padfZ, const double * padfM)
SHPObject SHPAPI_CALL1* SHPCreateSimpleObject (int nSHPType, int nVertices, const double * padfX, const double * padfY, const double * padfZ)
void SHPAPI_CALL SHPDestroyObject (SHPObject * psShape)
References tagSHPObject::bFastModeReadObject, FALSE, NULL, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, and tagSHPObject::panPartType.
Referenced by if(), map_rect_destroy_shapefile(), map_rect_get_item_shapefile(), and SHPDestroyTreeNode().
void SHPAPI_CALL SHPGetInfo (SHPHandle psSHP, int * pnEntities, int * pnShapeType, double * padfMinBound, double * padfMaxBound)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, i, SHPInfo::nRecords, SHPInfo::nShapeType, and NULL.
Referenced by if(), and map_new_shapefile().
SHPHandle SHPAPI_CALL SHPOpen (const char * pszLayer, const char * pszAccess)
References SASetupDefaultHooks(), and SHPOpenLL().
Referenced by map_new_shapefile().
SHPHandle SHPAPI_CALL SHPOpenLL (const char * pszLayer, const char * pszAccess, SAHooks * psHooks)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, SHPInfo::bUpdated, calloc(), errno, SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FRead, SAHooks::FSeek, SAHooks::FTell, i, int, MAX, SHPInfo::nFileSize, SHPInfo::nMaxRecords, SHPInfo::nRecords, SHPInfo::nShapeType, NULL, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, SHPClose(), strerror(), SwapWord(), and TRUE.
Referenced by SHPCreateLL(), SHPOpen(), and SHPOpenLLEx().
SHPHandle SHPAPI_CALL SHPOpenLLEx (const char * pszLayer, const char * pszAccess, SAHooks * psHooks, int bRestoreSHX)
References NULL, SHPOpenLL(), and SHPRestoreSHX().
const char SHPAPI_CALL1* SHPPartTypeName (int nPartType)
References SHPP_FIRSTRING, SHPP_INNERRING, SHPP_OUTERRING, SHPP_RING, SHPP_TRIFAN, and SHPP_TRISTRIP.
SHPObject SHPAPI_CALL1* SHPReadObject (SHPHandle psSHP, int hEntity) -> nRecords) return(NULL
static unsigned char* SHPReallocObjectBufIfNecessary (SHPHandle psSHP, int nObjectBufSize) static
References double, SHPInfo::nObjectBufSize, NULL, and SHPInfo::pabyObjectBuf.
Referenced by if().
int SHPAPI_CALL SHPRestoreSHX (const char * pszLayer, const char * pszAccess, SAHooks * psHooks)
References SAHooks::Error, FALSE, SAHooks::FClose, SAHooks::FOpen, SAHooks::FRead, SAHooks::FSeek, SAHooks::FWrite, i, int, NULL, SwapWord(), and TRUE.
Referenced by SHPOpenLLEx().
int SHPAPI_CALL SHPRewindObject (CPL_UNUSED SHPHandle hSHP, SHPObject * psObject)
References FALSE, i, intersect(), tagSHPObject::nParts, tagSHPObject::nSHPType, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, SHPT_POLYGON, SHPT_POLYGONM, and SHPT_POLYGONZ.
void SHPAPI_CALL SHPSetFastModeReadObject (SHPHandle hSHP, int bFastMode)
References SHPInfo::bFastModeReadObject, calloc(), NULL, and SHPInfo::psCachedObject.
const char SHPAPI_CALL1* SHPTypeName (int nSHPType)
References SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_NULL, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, and SHPT_POLYGONZ.
void SHPAPI_CALL SHPWriteHeader (SHPHandle psSHP)
References SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, ByteCopy, errno, SAHooks::Error, SAHooks::FFlush, SHPInfo::fpSHP, SHPInfo::fpSHX, SAHooks::FSeek, SAHooks::FWrite, i, SHPInfo::nFileSize, SHPInfo::nRecords, SHPInfo::nShapeType, NULL, SHPInfo::panRecOffset, SHPInfo::panRecSize, SHPInfo::sHooks, strerror(), and SwapWord().
Referenced by SHPClose().
int SHPAPI_CALL SHPWriteObject (SHPHandle psSHP, int nShapeId, SHPObject * psObject)
References _SHPSetBounds(), SHPInfo::adBoundsMax, SHPInfo::adBoundsMin, tagSHPObject::bMeasureIsUsed, SHPInfo::bUpdated, ByteCopy, tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, DISABLE_MULTIPATCH_MEASURE, errno, SAHooks::Error, FALSE, SHPInfo::fpSHP, SAHooks::FSeek, SAHooks::FWrite, i, MAX, MIN, SHPInfo::nFileSize, SHPInfo::nMaxRecords, tagSHPObject::nParts, SHPInfo::nRecords, nShapeId, SHPInfo::nShapeType, tagSHPObject::nSHPType, NULL, tagSHPObject::nVertices, tagSHPObject::padfM, tagSHPObject::padfX, tagSHPObject::padfY, tagSHPObject::padfZ, tagSHPObject::panPartStart, tagSHPObject::panPartType, SHPInfo::panRecOffset, SHPInfo::panRecSize, SfRealloc(), SHPInfo::sHooks, SHPT_ARC, SHPT_ARCM, SHPT_ARCZ, SHPT_MULTIPATCH, SHPT_MULTIPOINT, SHPT_MULTIPOINTM, SHPT_MULTIPOINTZ, SHPT_NULL, SHPT_POINT, SHPT_POINTM, SHPT_POINTZ, SHPT_POLYGON, SHPT_POLYGONM, SHPT_POLYGONZ, strerror(), SwapWord(), and TRUE.
static void SwapWord (int length, void * wordP) static
References i.
Referenced by _SHPSetBounds(), if(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), SHPWriteHeader(), and SHPWriteObject().
Variable Documentation
int bBigEndian static
psShape bFastModeReadObject = psSHP->bFastModeReadObject
bHasZ = FALSE
psShape bMeasureIsUsed = FALSE
else
Initial value:
{
        bHasM = FALSE
nBytesRead = (int)psSHP->sHooks.FRead(psSHP->pabyRec, 1, nEntitySize, psSHP->fpSHP)
nEntitySize = psSHP->panRecSize[hEntity]+8
Referenced by if().
psShape nShapeId = nShapeId
Referenced by SHPWriteObject().
psShape nSHPType = nSHPType
psObject nVertices = nVertices
Referenced by if().
else psShape = (SHPObject *) calloc(1,sizeof(SHPObject))
Referenced by if(), shapefile_coord(), and shapefile_coord_get().