navit: support/shapefile/shptree.c File Reference
shptree.c File Reference
#include "shapefil.h"
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
Data Structures
struct SHPDiskTreeInfo
Macros
#define TRUE 1
#define FALSE 0
#define SHP_SPLIT_RATIO 0.55
Functions
static void * SfRealloc (void *pMem, int nNewSize)
static SHPTreeNode * SHPTreeNodeCreate (double *padfBoundsMin, double *padfBoundsMax)
SHPTree SHPAPI_CALL1 * SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double *padfBoundsMin, double *padfBoundsMax){SHPTree *psTree;if(padfBoundsMin==NULL &&hSHP==NULL) return NULL;psTree=(SHPTree *) malloc(sizeof(SHPTree)
if (NULL==psTree)
if (psTree->nMaxDepth==0 &&hSHP!=NULL)
if (padfBoundsMin==NULL)
if (hSHP!=NULL)
static void SHPDestroyTreeNode (SHPTreeNode *psTreeNode)
void SHPAPI_CALL SHPDestroyTree (SHPTree *psTree)
int SHPAPI_CALL SHPCheckBoundsOverlap (double *padfBox1Min, double *padfBox1Max, double *padfBox2Min, double *padfBox2Max, int nDimension)
static int SHPCheckObjectContained (SHPObject *psObject, int nDimension, double *padfBoundsMin, double *padfBoundsMax)
static void SHPTreeSplitBounds (double *padfBoundsMinIn, double *padfBoundsMaxIn, double *padfBoundsMin1, double *padfBoundsMax1, double *padfBoundsMin2, double *padfBoundsMax2)
static int SHPTreeNodeAddShapeId (SHPTreeNode *psTreeNode, SHPObject *psObject, int nMaxDepth, int nDimension)
int SHPAPI_CALL SHPTreeAddShapeId (SHPTree *psTree, SHPObject *psObject)
static void SHPTreeCollectShapeIds (SHPTree *hTree, SHPTreeNode *psTreeNode, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount, int *pnMaxShapes, int **ppanShapeList)
static int compare_ints (const void *a, const void *b)
int SHPAPI_CALL1 * SHPTreeFindLikelyShapes (SHPTree *hTree, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount){int *panShapeList=NULL, nMaxShapes=0;*pnShapeCount=0;SHPTreeCollectShapeIds(hTree, hTree->psRoot, padfBoundsMin, padfBoundsMax, pnShapeCount,&nMaxShapes,&panShapeList
if (panShapeList!=NULL)
void SHPAPI_CALL SHPTreeTrimExtraNodes (SHPTree *hTree)
static void SwapWord (int length, void *wordP)
SHPTreeDiskHandle SHPOpenDiskTree (const char *pszQIXFilename, SAHooks *psHooks)
void SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
static int SHPSearchDiskTreeNode (SHPTreeDiskHandle hDiskTree, double *padfBoundsMin, double *padfBoundsMax, int **ppanResultBuffer, int *pnBufferMax, int *pnResultCount, int bNeedSwap, int nRecLevel)
static SAOffset SHPTreeReadLibc (void *p, SAOffset size, SAOffset nmemb, SAFile file)
static SAOffset SHPTreeSeekLibc (SAFile file, SAOffset offset, int whence)
int SHPAPI_CALL1 * SHPSearchDiskTree (FILE *fp, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount){struct SHPDiskTreeInfo sDiskTree;memset(&sDiskTree.sHooks, 0, sizeof(sDiskTree.sHooks)
int * SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double *padfBoundsMin, double *padfBoundsMax, int *pnShapeCount)
static int SHPGetSubNodeOffset (SHPTreeNode *node)
static void SHPWriteTreeNode (SAFile fp, SHPTreeNode *node, SAHooks *psHooks)
int SHPAPI_CALL SHPWriteTree (SHPTree *tree, const char *filename)
int SHPWriteTreeLL (SHPTree *tree, const char *filename, SAHooks *psHooks)
Variables
static int bBigEndian = 0
psTree hSHP = hSHP
psTree nMaxDepth = nMaxDepth
psTree nDimension = nDimension
psTree nTotalCount = 0
psTree psRoot = SHPTreeNodeCreate(padfBoundsMin, padfBoundsMax)
return psTree
sDiskTree sHooks FSeek = SHPTreeSeekLibc
sDiskTree sHooks FRead = SHPTreeReadLibc
sDiskTree fpQIX = (SAFile)fp
return SHPSearchDiskTreeEx & sDiskTree
Macro Definition Documentation
#define FALSE 0
Referenced by SHPCheckBoundsOverlap(), SHPCheckObjectContained(), SHPSearchDiskTreeEx(), SHPSearchDiskTreeNode(), and SHPWriteTreeLL().
#define SHP_SPLIT_RATIO 0.55
Referenced by SHPTreeSplitBounds().
#define TRUE 1
Referenced by SHPCheckBoundsOverlap(), SHPCheckObjectContained(), SHPSearchDiskTreeEx(), SHPSearchDiskTreeNode(), SHPTreeNodeAddShapeId(), and SHPWriteTreeLL().
Function Documentation
static int compare_ints (const void * a, const void * b) static
Referenced by SHPSearchDiskTreeEx().
if (NULL = = psTree)
References NULL.
if (psTree-> nMaxDepth = = 0 && hSHP != NULL)
References MAX_DEFAULT_TREE_DEPTH, SHPTree::nMaxDepth, shape_tree_node::nShapeCount, NULL, and SHPGetInfo().
if (padfBoundsMin = = NULL)
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, NULL, SHPTree::psRoot, and SHPGetInfo().
if (hSHP! = NULL)
References shape_tree_node::nShapeCount, NULL, psShape, SHPDestroyObject(), SHPGetInfo(), SHPReadObject(), and SHPTreeAddShapeId().
if (panShapeList! = NULL)
static void* SfRealloc (void * pMem, int nNewSize) static
References NULL.
Referenced by SHPSearchDiskTreeNode(), SHPTreeCollectShapeIds(), and SHPTreeNodeAddShapeId().
int SHPAPI_CALL SHPCheckBoundsOverlap (double * padfBox1Min, double * padfBox1Max, double * padfBox2Min, double * padfBox2Max, int nDimension)
References FALSE, nDimension, and TRUE.
Referenced by SHPSearchDiskTreeNode(), and SHPTreeCollectShapeIds().
static int SHPCheckObjectContained (SHPObject * psObject, int nDimension, double * padfBoundsMin, double * padfBoundsMax) static
References tagSHPObject::dfMMax, tagSHPObject::dfMMin, tagSHPObject::dfXMax, tagSHPObject::dfXMin, tagSHPObject::dfYMax, tagSHPObject::dfYMin, tagSHPObject::dfZMax, tagSHPObject::dfZMin, FALSE, and TRUE.
Referenced by SHPTreeNodeAddShapeId().
void SHPCloseDiskTree (SHPTreeDiskHandle hDiskTree)
References NULL.
SHPTree SHPAPI_CALL1* SHPCreateTree (SHPHandle hSHP, int nDimension, int nMaxDepth, double * padfBoundsMin, double * padfBoundsMax)
void SHPAPI_CALL SHPDestroyTree (SHPTree * psTree)
References SHPTree::psRoot, and SHPDestroyTreeNode().
static void SHPDestroyTreeNode (SHPTreeNode * psTreeNode) static
References shape_tree_node::apsSubNode, i, shape_tree_node::nShapeCount, shape_tree_node::nSubNodes, NULL, shape_tree_node::panShapeIds, shape_tree_node::papsShapeObj, and SHPDestroyObject().
Referenced by SHPDestroyTree().
static int SHPGetSubNodeOffset (SHPTreeNode * node) static
References shape_tree_node::apsSubNode, double, i, int, shape_tree_node::nShapeCount, shape_tree_node::nSubNodes, and offset.
Referenced by SHPWriteTreeNode().
SHPTreeDiskHandle SHPOpenDiskTree (const char * pszQIXFilename, SAHooks * psHooks)
References calloc(), NULL, and SASetupDefaultHooks().
int SHPAPI_CALL1* SHPSearchDiskTree (FILE * fp, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
int* SHPSearchDiskTreeEx (SHPTreeDiskHandle hDiskTree, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount)
References calloc(), compare_ints(), FALSE, i, NULL, SEEK_SET, SHPSearchDiskTreeNode(), and TRUE.
static int SHPSearchDiskTreeNode (SHPTreeDiskHandle hDiskTree, double * padfBoundsMin, double * padfBoundsMax, int ** ppanResultBuffer, int * pnBufferMax, int * pnResultCount, int bNeedSwap, int nRecLevel) static
References FALSE, i, int, NULL, offset, SEEK_CUR, SfRealloc(), SHPCheckBoundsOverlap(), SwapWord(), and TRUE.
Referenced by SHPSearchDiskTreeEx().
int SHPAPI_CALL SHPTreeAddShapeId (SHPTree * psTree, SHPObject * psObject)
References SHPTree::nDimension, SHPTree::nMaxDepth, SHPTree::nTotalCount, SHPTree::psRoot, and SHPTreeNodeAddShapeId().
Referenced by if().
static void SHPTreeCollectShapeIds (SHPTree * hTree, SHPTreeNode * psTreeNode, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount, int * pnMaxShapes, int ** ppanShapeList) static
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, shape_tree_node::apsSubNode, i, SHPTree::nDimension, shape_tree_node::nShapeCount, shape_tree_node::nSubNodes, NULL, shape_tree_node::panShapeIds, SfRealloc(), and SHPCheckBoundsOverlap().
int SHPAPI_CALL1* SHPTreeFindLikelyShapes (SHPTree * hTree, double * padfBoundsMin, double * padfBoundsMax, int * pnShapeCount) -> psRoot, padfBoundsMin, padfBoundsMax, pnShapeCount,&nMaxShapes,&panShapeList
static int SHPTreeNodeAddShapeId (SHPTreeNode * psTreeNode, SHPObject * psObject, int nMaxDepth, int nDimension) static
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, shape_tree_node::apsSubNode, i, shape_tree_node::nShapeCount, tagSHPObject::nShapeId, shape_tree_node::nSubNodes, NULL, shape_tree_node::panShapeIds, shape_tree_node::papsShapeObj, SfRealloc(), SHPCheckObjectContained(), SHPTreeNodeCreate(), SHPTreeSplitBounds(), and TRUE.
Referenced by SHPTreeAddShapeId().
static SHPTreeNode* SHPTreeNodeCreate (double * padfBoundsMin, double * padfBoundsMax) static
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, shape_tree_node::nShapeCount, shape_tree_node::nSubNodes, NULL, shape_tree_node::panShapeIds, and shape_tree_node::papsShapeObj.
Referenced by SHPTreeNodeAddShapeId().
static SAOffset SHPTreeReadLibc (void * p, SAOffset size, SAOffset nmemb, SAFile file) static
static SAOffset SHPTreeSeekLibc (SAFile file, SAOffset offset, int whence) static
static void SHPTreeSplitBounds (double * padfBoundsMinIn, double * padfBoundsMaxIn, double * padfBoundsMin1, double * padfBoundsMax1, double * padfBoundsMin2, double * padfBoundsMax2) static
References SHP_SPLIT_RATIO.
Referenced by SHPTreeNodeAddShapeId().
void SHPAPI_CALL SHPTreeTrimExtraNodes (SHPTree * hTree)
References SHPTree::psRoot.
int SHPAPI_CALL SHPWriteTree (SHPTree * tree, const char * filename)
References SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, and SHPWriteTreeLL().
int SHPWriteTreeLL (SHPTree * tree, const char * filename, SAHooks * psHooks)
References FALSE, SAHooks::FClose, SAHooks::FOpen, fp, SAHooks::FWrite, i, SHPTree::nMaxDepth, SHPTree::nTotalCount, NULL, SHPTree::psRoot, SASetupDefaultHooks(), SHPDiskTreeInfo::sHooks, SHPWriteTreeNode(), signature, and TRUE.
Referenced by SHPWriteTree().
static void SHPWriteTreeNode (SAFile fp, SHPTreeNode * node, SAHooks * psHooks) static
References shape_tree_node::adfBoundsMax, shape_tree_node::adfBoundsMin, shape_tree_node::apsSubNode, SAHooks::FWrite, i, int, shape_tree_node::nShapeCount, shape_tree_node::nSubNodes, NULL, offset, shape_tree_node::panShapeIds, and SHPGetSubNodeOffset().
Referenced by SHPWriteTreeLL().
static void SwapWord (int length, void * wordP) static
References i.
Referenced by SHPSearchDiskTreeNode().
Variable Documentation
int bBigEndian = 0 static
sDiskTree fpQIX = (SAFile)fp
sDiskTree sHooks FRead = SHPTreeReadLibc
sDiskTree sHooks FSeek = SHPTreeSeekLibc
psTree hSHP = hSHP
psTree nDimension = nDimension
Referenced by SHPCheckBoundsOverlap().
psTree nMaxDepth = nMaxDepth
psTree nTotalCount = 0
psTree psRoot = SHPTreeNodeCreate(padfBoundsMin, padfBoundsMax)
return psTree
return SHPSearchDiskTreeEx & sDiskTree