navit: maptool/sourcesink.c File Reference
sourcesink.c File Reference
#include <stdio.h>
#include <glib.h>
#include <string.h>
#include "coord.h"
#include "item.h"
#include "attr.h"
#include "maptool.h"
Functions
struct item_bin_sink * item_bin_sink_new (void)
struct item_bin_sink_func * item_bin_sink_func_new (int(*func)(struct item_bin_sink_func *func, struct item_bin *ib, struct tile_data *tile_data))
void item_bin_sink_func_destroy (struct item_bin_sink_func *func)
void item_bin_sink_add_func (struct item_bin_sink *sink, struct item_bin_sink_func *func)
void item_bin_sink_destroy (struct item_bin_sink *sink)
int item_bin_write_to_sink (struct item_bin *ib, struct item_bin_sink *sink, struct tile_data *tile_data)
struct item_bin_sink * file_reader_new (FILE *in, int limit, int offset)
int file_reader_finish (struct item_bin_sink *sink)
int file_writer_process (struct item_bin_sink_func *func, struct item_bin *ib, struct tile_data *tile_data)
struct item_bin_sink_func * file_writer_new (FILE *out)
int file_writer_finish (struct item_bin_sink_func *file_writer)
int tile_collector_process (struct item_bin_sink_func *tile_collector, struct item_bin *ib, struct tile_data *tile_data)
struct item_bin_sink_func * tile_collector_new (struct item_bin_sink *out)
Function Documentation
file_reader_finish()
int file_reader_finish (struct item_bin_sink * sink)
References item_bin_sink_destroy(), item_bin_write_to_sink(), limit, offset, item_bin_sink::priv_data, and read_item().
Referenced by process_coastlines().
file_reader_new()
struct item_bin_sink* file_reader_new (FILE * in, int limit, int offset)
References item_bin_sink_new(), limit, offset, and item_bin_sink::priv_data.
Referenced by process_coastlines().
file_writer_finish()
int file_writer_finish (struct item_bin_sink_func * file_writer)
References item_bin_sink_func_destroy().
Referenced by process_coastlines().
file_writer_new()
struct item_bin_sink_func* file_writer_new (FILE * out)
References file_writer_process(), item_bin_sink_func_new(), and item_bin_sink_func::priv_data.
Referenced by process_coastlines().
file_writer_process()
int file_writer_process (struct item_bin_sink_func * func, struct item_bin * ib, struct tile_data * tile_data)
References item_bin_write(), and item_bin_sink_func::priv_data.
Referenced by file_writer_new().
item_bin_sink_add_func()
void item_bin_sink_add_func (struct item_bin_sink * sink, struct item_bin_sink_func * func)
References item_bin_sink::sink_funcs.
Referenced by coastline_processor_new(), and process_coastlines().
item_bin_sink_destroy()
void item_bin_sink_destroy (struct item_bin_sink * sink)
References item_bin_sink::sink_funcs.
Referenced by coastline_processor_finish(), file_reader_finish(), and process_coastlines().
item_bin_sink_func_destroy()
void item_bin_sink_func_destroy (struct item_bin_sink_func * func)
Referenced by coastline_processor_finish(), file_writer_finish(), and tile_collector_finish().
item_bin_sink_func_new()
struct item_bin_sink_func* item_bin_sink_func_new (int(*)(struct item_bin_sink_func *func, struct item_bin *ib, struct tile_data *tile_data) func)
References item_bin_sink_func::func.
Referenced by coastline_processor_new(), file_writer_new(), and tile_collector_new().
item_bin_sink_new()
struct item_bin_sink* item_bin_sink_new (void)
Navit, a modular navigation system. Copyright (C) 2005-2011 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by coastline_processor_new(), file_reader_new(), and process_coastlines().
item_bin_write_to_sink()
int item_bin_write_to_sink (struct item_bin * ib, struct item_bin_sink * sink, struct tile_data * tile_data)
References item_bin_sink_func::func, and item_bin_sink::sink_funcs.
Referenced by file_reader_finish(), item_bin_write_clipped(), ocean_tile(), tile_collector_process_tile(), and tile_sibling_edges().
tile_collector_new()
struct item_bin_sink_func* tile_collector_new (struct item_bin_sink * out)
References item_bin_sink_func_new(), item_bin_sink_func::priv_data, and tile_collector_process().
Referenced by coastline_processor_new().
tile_collector_process()
int tile_collector_process (struct item_bin_sink_func * tile_collector, struct item_bin * ib, struct tile_data * tile_data)
References tile_data::buffer, item_bin::len, and item_bin_sink_func::priv_data.
Referenced by tile_collector_new().