navit: support/espeak/speak_lib.h File Reference
speak_lib.h File Reference
#include <stdio.h>
#include <wchar.h>
Data Structures
struct espeak_EVENT
struct espeak_VOICE
Macros
#define ESPEAK_API_REVISION 5
#define espeakCHARS_AUTO 0
#define espeakCHARS_UTF8 1
#define espeakCHARS_8BIT 2
#define espeakCHARS_WCHAR 3
#define espeakCHARS_16BIT 4
#define espeakSSML 0x10
#define espeakPHONEMES 0x100
#define espeakENDPAUSE 0x1000
#define espeakKEEP_NAMEDATA 0x2000
Typedefs
typedef int(t_espeak_callback)(short *, int, espeak_EVENT *)
Enumerations
enum espeak_EVENT_TYPE {
espeakEVENT_LIST_TERMINATED = 0, espeakEVENT_WORD = 1, espeakEVENT_SENTENCE, espeakEVENT_MARK,
espeakEVENT_PLAY, espeakEVENT_END, espeakEVENT_MSG_TERMINATED, espeakEVENT_PHONEME
}
enum espeak_POSITION_TYPE { POS_CHARACTER = 1, POS_WORD, POS_SENTENCE }
enum espeak_AUDIO_OUTPUT { AUDIO_OUTPUT_PLAYBACK, AUDIO_OUTPUT_RETRIEVAL, AUDIO_OUTPUT_SYNCHRONOUS, AUDIO_OUTPUT_SYNCH_PLAYBACK }
enum espeak_ERROR { EE_OK =0, EE_INTERNAL_ERROR =-1, EE_BUFFER_FULL =1, EE_NOT_FOUND =2 }
enum espeak_PARAMETER {
espeakSILENCE =0, espeakRATE =1, espeakVOLUME =2, espeakPITCH =3,
espeakRANGE =4, espeakPUNCTUATION =5, espeakCAPITALS =6, espeakWORDGAP =7,
espeakOPTIONS =8, espeakINTONATION =9, espeakRESERVED1 =10, espeakRESERVED2 =11,
espeakEMPHASIS, espeakLINELENGTH, espeakVOICETYPE, N_SPEECH_PARAM
}
enum espeak_PUNCT_TYPE { espeakPUNCT_NONE =0, espeakPUNCT_ALL =1, espeakPUNCT_SOME =2 }
Functions
int espeak_Initialize (espeak_AUDIO_OUTPUT output, int buflength, const char *path, int options)
void espeak_SetSynthCallback (t_espeak_callback *SynthCallback)
void espeak_SetUriCallback (int(*UriCallback)(int, const char *, const char *))
espeak_ERROR espeak_Synth (const void *text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, unsigned int *unique_identifier, void *user_data)
espeak_ERROR espeak_Synth_Mark (const void *text, size_t size, const char *index_mark, unsigned int end_position, unsigned int flags, unsigned int *unique_identifier, void *user_data)
espeak_ERROR espeak_Key (const char *key_name)
espeak_ERROR espeak_Char (wchar_t character)
espeak_ERROR espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
int espeak_GetParameter (espeak_PARAMETER parameter, int current)
espeak_ERROR espeak_SetPunctuationList (const wchar_t *punctlist)
void espeak_SetPhonemeTrace (int value, FILE *stream)
void espeak_CompileDictionary (const char *path, FILE *log, int flags)
const espeak_VOICE ** espeak_ListVoices (espeak_VOICE *voice_spec)
espeak_ERROR espeak_SetVoiceByName (const char *name)
espeak_ERROR espeak_SetVoiceByProperties (espeak_VOICE *voice_spec)
espeak_VOICE * espeak_GetCurrentVoice (void)
espeak_ERROR espeak_Cancel (void)
int espeak_IsPlaying (void)
espeak_ERROR espeak_Synchronize (void)
espeak_ERROR espeak_Terminate (void)
const char * espeak_Info (void)
Macro Definition Documentation
#define ESPEAK_API_REVISION 5
#define espeakCHARS_16BIT 4
Referenced by GetC(), and GetC_get().
#define espeakCHARS_8BIT 2
Referenced by GetC(), and main().
#define espeakCHARS_AUTO 0
Referenced by GetC(), and main().
#define espeakCHARS_UTF8 1
Referenced by qt5_espeak_say().
#define espeakCHARS_WCHAR 3
Referenced by GetC(), GetC_get(), and TranslateClause().
#define espeakENDPAUSE 0x1000
Referenced by main(), and Synthesize().
#define espeakKEEP_NAMEDATA 0x2000
Referenced by InitText().
#define espeakPHONEMES 0x100
Referenced by main(), and Synthesize().
#define espeakSSML 0x10
Referenced by main(), sync_espeak_Char(), sync_espeak_Synth_Mark(), and Synthesize().
Typedef Documentation
typedef int(t_espeak_callback)(short *, int, espeak_EVENT *)
Enumeration Type Documentation
enum espeak_AUDIO_OUTPUT
Enumerator
AUDIO_OUTPUT_PLAYBACK
AUDIO_OUTPUT_RETRIEVAL
AUDIO_OUTPUT_SYNCHRONOUS
AUDIO_OUTPUT_SYNCH_PLAYBACK
enum espeak_ERROR
Enumerator
EE_OK
EE_INTERNAL_ERROR
EE_BUFFER_FULL
EE_NOT_FOUND
enum espeak_EVENT_TYPE
Enumerator
espeakEVENT_LIST_TERMINATED
espeakEVENT_WORD
espeakEVENT_SENTENCE
espeakEVENT_MARK
espeakEVENT_PLAY
espeakEVENT_END
espeakEVENT_MSG_TERMINATED
espeakEVENT_PHONEME
enum espeak_PARAMETER
Enumerator
espeakSILENCE
espeakRATE
espeakVOLUME
espeakPITCH
espeakRANGE
espeakPUNCTUATION
espeakCAPITALS
espeakWORDGAP
espeakOPTIONS
espeakINTONATION
espeakRESERVED1
espeakRESERVED2
espeakEMPHASIS
espeakLINELENGTH
espeakVOICETYPE
N_SPEECH_PARAM
enum espeak_POSITION_TYPE
Enumerator
POS_CHARACTER
POS_WORD
POS_SENTENCE
enum espeak_PUNCT_TYPE
Enumerator
espeakPUNCT_NONE
espeakPUNCT_ALL
espeakPUNCT_SOME
Function Documentation
espeak_ERROR espeak_Cancel (void)
References AUDIO_OUTPUT_PLAYBACK, EE_OK, EMBED_T, embedded_value, ENTER, event_clear_all(), fifo_stop(), my_audio, my_mode, SHOW_TIME, and wave_close().
espeak_ERROR espeak_Char (wchar_t character)
References c, create_espeak_char(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), NULL, sync_espeak_Char(), and synchronous_mode.
void espeak_CompileDictionary (const char * path, FILE * log, int flags)
References CompileDictionary(), dictionary_name, ENTER, and NULL.
Referenced by main().
espeak_VOICE* espeak_GetCurrentVoice (void)
int espeak_GetParameter (espeak_PARAMETER parameter, int current)
References ENTER, param_defaults, and param_stack.
const char* espeak_Info (void)
References version_string.
Referenced by main().
int espeak_Initialize (espeak_AUDIO_OUTPUT output, int buflength, const char * path, int options)
References DoVoiceChange(), EE_INTERNAL_ERROR, ENTER, espeakCAPITALS, espeakPUNCTUATION, espeakRATE, espeakVOLUME, espeakWORDGAP, fifo_init(), init_path(), initialise(), n_event_list, N_SPEECH_PARAM, NULL, option_capitals, option_phoneme_events, option_phonemes, option_punctuation, out_start, outbuf_size, param_defaults, param_stack, samplerate, select_output(), setlocale(), SetParameter(), SetVoiceByName(), and voice.
Referenced by main(), and qt5_espeak_init_espeak().
int espeak_IsPlaying (void)
References AUDIO_OUTPUT_PLAYBACK, fifo_is_busy(), my_audio, my_mode, and wave_is_busy().
Referenced by espeak_Synchronize().
espeak_ERROR espeak_Key (const char * key_name)
References c, create_espeak_key(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), NULL, sync_espeak_Key(), and synchronous_mode.
const espeak_VOICE** espeak_ListVoices (espeak_VOICE * voice_spec)
References GetVoices(), espeak_VOICE::identifier, espeak_VOICE::languages, len_path_voices, N_VOICES_LIST, n_voices_list, NULL, path_home, PATHSEP, SetVoiceScores(), sprintf(), VoiceNameSorter(), and voices_list.
Referenced by DisplayVoices(), SelectVoice(), SelectVoiceByName(), and SetVoiceByName().
espeak_ERROR espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
References c, create_espeak_parameter(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetParameter(), and synchronous_mode.
Referenced by main().
void espeak_SetPhonemeTrace (int value, FILE * stream)
References ENTER, f_trans, NULL, option_phonemes, and value.
Referenced by main().
espeak_ERROR espeak_SetPunctuationList (const wchar_t * punctlist)
References c, create_espeak_punctuation_list(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), sync_espeak_SetPunctuationList(), and synchronous_mode.
Referenced by main().
void espeak_SetSynthCallback (t_espeak_callback * SynthCallback)
References ENTER, event_set_callback(), synth_callback, and SynthCallback().
Referenced by main(), and qt5_espeak_init_espeak().
void espeak_SetUriCallback (int(*)(int, const char *, const char *) UriCallback)
References ENTER, and uri_callback.
espeak_ERROR espeak_SetVoiceByName (const char * name)
References c, create_espeak_voice_name(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetVoiceByName(), and synchronous_mode.
Referenced by main().
espeak_ERROR espeak_SetVoiceByProperties (espeak_VOICE * voice_spec)
References c, create_espeak_voice_spec(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetVoiceByProperties(), and synchronous_mode.
Referenced by main(), and qt5_espeak_init_language().
espeak_ERROR espeak_Synchronize (void)
References EE_OK, espeak_IsPlaying(), SHOW_TIME, and usleep().
Referenced by main().
espeak_ERROR espeak_Synth (const void * text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, unsigned int * unique_identifier, void * user_data)
References c1, c2, create_espeak_terminated_msg(), create_espeak_text(), delete_espeak_command(), EE_INTERNAL_ERROR, EE_OK, ENTER, fifo_add_commands(), t_espeak_command::command::my_text, NULL, SHOW, sync_espeak_Synth(), synchronous_mode, t_espeak_command::u, and t_espeak_text::unique_identifier.
Referenced by main(), and qt5_espeak_say().
espeak_ERROR espeak_Synth_Mark (const void * text, size_t size, const char * index_mark, unsigned int end_position, unsigned int flags, unsigned int * unique_identifier, void * user_data)
References c1, c2, create_espeak_mark(), create_espeak_terminated_msg(), delete_espeak_command(), EE_OK, ENTER, fifo_add_commands(), t_espeak_command::command::my_mark, NULL, SHOW, sync_espeak_Synth_Mark(), synchronous_mode, t_espeak_command::u, and t_espeak_mark::unique_identifier.
espeak_ERROR espeak_Terminate (void)
References AUDIO_OUTPUT_PLAYBACK, EE_OK, ENTER, event_terminate(), fifo_stop(), fifo_terminate(), Free(), FreePhData(), my_audio, my_mode, NULL, wave_close(), and wave_terminate().