navit: support/espeak/speak_lib.c File Reference
speak_lib.c File Reference
#include "StdAfx.h"
#include "stdio.h"
#include "ctype.h"
#include "string.h"
#include "stdlib.h"
#include "wchar.h"
#include "locale.h"
#include <assert.h>
#include <time.h>
#include "speech.h"
#include <sys/stat.h>
#include <unistd.h>
#include "speak_lib.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
#include "debug.h"
#include "fifo.h"
#include "event.h"
#include "wave.h"
Functions
static void select_output (espeak_AUDIO_OUTPUT output_type)
int GetFileLength (const char *filename)
char * Alloc (int size)
void Free (void *ptr)
static void init_path (const char *path)
static int initialise (void)
static espeak_ERROR Synthesize (unsigned int unique_identifier, const void *text, int flags)
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char *out_ptr)
espeak_ERROR sync_espeak_Synth (unsigned int unique_identifier, const void *text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void *user_data)
espeak_ERROR sync_espeak_Synth_Mark (unsigned int unique_identifier, const void *text, size_t size, const char *index_mark, unsigned int end_position, unsigned int flags, void *user_data)
void sync_espeak_Key (const char *key)
void sync_espeak_Char (wchar_t character)
void sync_espeak_SetPunctuationList (const wchar_t *punctlist)
ESPEAK_API void espeak_SetSynthCallback (t_espeak_callback *SynthCallback)
ESPEAK_API void espeak_SetUriCallback (int(*UriCallback)(int, const char *, const char *))
ESPEAK_API void espeak_SetPhonemeCallback (int(*PhonemeCallback)(const char *))
ESPEAK_API int espeak_Initialize (espeak_AUDIO_OUTPUT output_type, int buf_length, const char *path, int options)
ESPEAK_API espeak_ERROR espeak_Synth (const void *text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, unsigned int *unique_identifier, void *user_data)
ESPEAK_API espeak_ERROR espeak_Synth_Mark (const void *text, size_t size, const char *index_mark, unsigned int end_position, unsigned int flags, unsigned int *unique_identifier, void *user_data)
ESPEAK_API espeak_ERROR espeak_Key (const char *key)
ESPEAK_API espeak_ERROR espeak_Char (wchar_t character)
ESPEAK_API espeak_ERROR espeak_SetVoiceByName (const char *name)
ESPEAK_API espeak_ERROR espeak_SetVoiceByProperties (espeak_VOICE *voice_selector)
ESPEAK_API int espeak_GetParameter (espeak_PARAMETER parameter, int current)
ESPEAK_API espeak_ERROR espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
ESPEAK_API espeak_ERROR espeak_SetPunctuationList (const wchar_t *punctlist)
ESPEAK_API void espeak_SetPhonemeTrace (int value, FILE *stream)
ESPEAK_API void espeak_CompileDictionary (const char *path, FILE *log, int flags)
ESPEAK_API espeak_ERROR espeak_Cancel (void)
ESPEAK_API int espeak_IsPlaying (void)
ESPEAK_API espeak_ERROR espeak_Synchronize (void)
void FreePhData (void)
ESPEAK_API espeak_ERROR espeak_Terminate (void)
ESPEAK_API const char * espeak_Info (void)
Variables
unsigned char * outbuf =NULL
espeak_VOICE voice_selected
espeak_EVENT * event_list =NULL
int event_list_ix =0
int n_event_list
long count_samples
void * my_audio =NULL
static unsigned int my_unique_identifier =0
static void * my_user_data =NULL
static espeak_AUDIO_OUTPUT my_mode =AUDIO_OUTPUT_SYNCHRONOUS
static int synchronous_mode = 1
t_espeak_callback * synth_callback = NULL
int(* uri_callback)(int, const char *, const char *) = NULL
int(* phoneme_callback)(const char *) = NULL
char path_home [N_PATH_HOME]
Function Documentation
char* Alloc (int size)
References fprintf(), g_malloc(), NULL, and p.
ESPEAK_API espeak_ERROR espeak_Cancel (void)
References AUDIO_OUTPUT_PLAYBACK, EE_OK, EMBED_T, embedded_value, ENTER, event_clear_all(), fifo_stop(), my_audio, my_mode, SHOW_TIME, and wave_close().
ESPEAK_API espeak_ERROR espeak_Char (wchar_t character)
References c, create_espeak_char(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), NULL, sync_espeak_Char(), and synchronous_mode.
ESPEAK_API void espeak_CompileDictionary (const char * path, FILE * log, int flags)
References CompileDictionary(), dictionary_name, ENTER, and NULL.
Referenced by main().
ESPEAK_API int espeak_GetParameter (espeak_PARAMETER parameter, int current)
References ENTER, param_defaults, and param_stack.
ESPEAK_API const char* espeak_Info (void)
References version_string.
Referenced by main().
ESPEAK_API int espeak_Initialize (espeak_AUDIO_OUTPUT output_type, int buf_length, const char * path, int options)
References DoVoiceChange(), EE_INTERNAL_ERROR, ENTER, espeakCAPITALS, espeakPUNCTUATION, espeakRATE, espeakVOLUME, espeakWORDGAP, fifo_init(), init_path(), initialise(), n_event_list, N_SPEECH_PARAM, NULL, option_capitals, option_phoneme_events, option_phonemes, option_punctuation, out_start, outbuf_size, param_defaults, param_stack, samplerate, select_output(), setlocale(), SetParameter(), SetVoiceByName(), and voice.
Referenced by main(), and qt5_espeak_init_espeak().
ESPEAK_API int espeak_IsPlaying (void)
References AUDIO_OUTPUT_PLAYBACK, fifo_is_busy(), my_audio, my_mode, and wave_is_busy().
Referenced by espeak_Synchronize().
ESPEAK_API espeak_ERROR espeak_Key (const char * key)
References c, create_espeak_key(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), NULL, sync_espeak_Key(), and synchronous_mode.
ESPEAK_API espeak_ERROR espeak_SetParameter (espeak_PARAMETER parameter, int value, int relative)
References c, create_espeak_parameter(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetParameter(), and synchronous_mode.
Referenced by main().
ESPEAK_API void espeak_SetPhonemeCallback (int(*)(const char *) PhonemeCallback)
References phoneme_callback.
ESPEAK_API void espeak_SetPhonemeTrace (int value, FILE * stream)
References ENTER, f_trans, NULL, option_phonemes, and value.
Referenced by main().
ESPEAK_API espeak_ERROR espeak_SetPunctuationList (const wchar_t * punctlist)
References c, create_espeak_punctuation_list(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), sync_espeak_SetPunctuationList(), and synchronous_mode.
Referenced by main().
ESPEAK_API void espeak_SetSynthCallback (t_espeak_callback * SynthCallback)
References ENTER, event_set_callback(), synth_callback, and SynthCallback().
Referenced by main(), and qt5_espeak_init_espeak().
ESPEAK_API void espeak_SetUriCallback (int(*)(int, const char *, const char *) UriCallback)
References ENTER, and uri_callback.
ESPEAK_API espeak_ERROR espeak_SetVoiceByName (const char * name)
References c, create_espeak_voice_name(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetVoiceByName(), and synchronous_mode.
Referenced by main().
ESPEAK_API espeak_ERROR espeak_SetVoiceByProperties (espeak_VOICE * voice_selector)
References c, create_espeak_voice_spec(), delete_espeak_command(), EE_OK, ENTER, fifo_add_command(), SetVoiceByProperties(), and synchronous_mode.
Referenced by main(), and qt5_espeak_init_language().
ESPEAK_API espeak_ERROR espeak_Synchronize (void)
References EE_OK, espeak_IsPlaying(), SHOW_TIME, and usleep().
Referenced by main().
ESPEAK_API espeak_ERROR espeak_Synth (const void * text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, unsigned int * unique_identifier, void * user_data)
References c1, c2, create_espeak_terminated_msg(), create_espeak_text(), delete_espeak_command(), EE_INTERNAL_ERROR, EE_OK, ENTER, fifo_add_commands(), t_espeak_command::command::my_text, NULL, SHOW, sync_espeak_Synth(), synchronous_mode, t_espeak_command::u, and t_espeak_text::unique_identifier.
Referenced by main(), and qt5_espeak_say().
ESPEAK_API espeak_ERROR espeak_Synth_Mark (const void * text, size_t size, const char * index_mark, unsigned int end_position, unsigned int flags, unsigned int * unique_identifier, void * user_data)
References c1, c2, create_espeak_mark(), create_espeak_terminated_msg(), delete_espeak_command(), EE_OK, ENTER, fifo_add_commands(), t_espeak_command::command::my_mark, NULL, SHOW, sync_espeak_Synth_Mark(), synchronous_mode, t_espeak_command::u, and t_espeak_mark::unique_identifier.
ESPEAK_API espeak_ERROR espeak_Terminate (void)
References AUDIO_OUTPUT_PLAYBACK, EE_OK, ENTER, event_terminate(), fifo_stop(), fifo_terminate(), Free(), FreePhData(), my_audio, my_mode, NULL, wave_close(), and wave_terminate().
void Free (void * ptr)
References g_free(), and NULL.
Referenced by espeak_Terminate().
void FreePhData (void)
References Free(), NULL, phoneme_index, phoneme_tab_data, and spects_data.
Referenced by espeak_Terminate().
int GetFileLength (const char * filename)
References S_IFDIR, S_IFMT, stat::st_mode, stat::st_size, and stat().
Referenced by init_path().
static void init_path (const char * path) static
References access(), buf, getenv, GetFileLength(), NULL, PATH_ESPEAK_DATA, path_home, R_OK, size, and sprintf().
Referenced by espeak_Initialize().
static int initialise (void) static
References exit, fprintf(), InitNamedata(), LoadConfig(), LoadPhData(), N_SPEECH_PARAM, NULL, param_defaults, param_stack, path_home, SetVoiceStack(), SynthesizeInit(), version_phdata, and WavegenInit().
Referenced by espeak_Initialize().
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char * out_ptr)
References espeak_EVENT::audio_position, count_samples, double, ENTER, ep, espeakEVENT_MARK, espeakEVENT_PLAY, event_list_ix, espeak_EVENT::id, int, espeak_EVENT::length, mbrola_delay, my_unique_identifier, my_user_data, n_event_list, espeak_EVENT::name, namedata, NULL, espeak_EVENT::number, out_start, espeak_EVENT::sample, samplerate, SHOW, espeak_EVENT::text_position, time(), espeak_EVENT::type, espeak_EVENT::unique_identifier, espeak_EVENT::user_data, and value.
static void select_output (espeak_AUDIO_OUTPUT output_type) static
References AUDIO_OUTPUT_PLAYBACK, AUDIO_OUTPUT_RETRIEVAL, AUDIO_OUTPUT_SYNCH_PLAYBACK, AUDIO_OUTPUT_SYNCHRONOUS, event_init(), fifo_is_command_enabled(), my_audio, my_mode, NULL, option_waveout, synchronous_mode, wave_init(), wave_open(), wave_set_callback_is_output_enabled(), and WavegenInitSound().
Referenced by espeak_Initialize().
void sync_espeak_Char (wchar_t character)
References buf, espeakSSML, my_unique_identifier, my_user_data, NULL, sprintf(), and Synthesize().
Referenced by espeak_Char(), and sync_espeak_Key().
void sync_espeak_Key (const char * key)
References my_unique_identifier, my_user_data, NULL, sync_espeak_Char(), Synthesize(), and utf8_in().
Referenced by espeak_Key().
void sync_espeak_SetPunctuationList (const wchar_t * punctlist)
References my_unique_identifier, my_user_data, N_PUNCTLIST, NULL, and option_punctlist.
Referenced by espeak_SetPunctuationList().
espeak_ERROR sync_espeak_Synth (unsigned int unique_identifier, const void * text, size_t size, unsigned int position, espeak_POSITION_TYPE position_type, unsigned int end_position, unsigned int flags, void * user_data)
References end_character_position, ENTER, InitText(), my_audio, my_unique_identifier, my_user_data, POS_CHARACTER, POS_SENTENCE, POS_WORD, SHOW, SHOW_TIME, skip_characters, skip_sentences, skip_words, skipping_text, Synthesize(), and wave_flush().
Referenced by espeak_Synth().
espeak_ERROR sync_espeak_Synth_Mark (unsigned int unique_identifier, const void * text, size_t size, const char * index_mark, unsigned int end_position, unsigned int flags, void * user_data)
References end_character_position, espeakSSML, InitText(), my_unique_identifier, my_user_data, NULL, SHOW_TIME, skip_marker, skipping_text, strncpy0(), and Synthesize().
Referenced by espeak_Synth_Mark().
static espeak_ERROR Synthesize (unsigned int unique_identifier, const void * text, int flags) static
References AUDIO_OUTPUT_PLAYBACK, AUDIO_OUTPUT_SYNCH_PLAYBACK, count_samples, EE_INTERNAL_ERROR, EE_OK, ENTER, espeakENDPAUSE, espeakEVENT_LIST_TERMINATED, espeakPHONEMES, espeakSSML, event_list_ix, Generate(), length, my_audio, my_mode, my_unique_identifier, my_user_data, n_phoneme_list, NULL, option_endpause, option_multibyte, option_phoneme_input, option_ssml, out_end, out_ptr, outbuf, outbuf_size, phoneme_list, SetVoiceByName(), SHOW, SpeakNextClause(), synth_callback, SynthOnTimer(), translator, espeak_EVENT::type, espeak_EVENT::unique_identifier, espeak_EVENT::user_data, wave_get_write_position(), WavegenFill(), and WcmdqUsed().
Referenced by sync_espeak_Char(), sync_espeak_Key(), sync_espeak_Synth(), and sync_espeak_Synth_Mark().
Variable Documentation
long count_samples
Referenced by MarkerEvent(), and Synthesize().
espeak_EVENT* event_list =NULL
int event_list_ix =0
Referenced by MarkerEvent(), MbrolaTranslate(), and Synthesize().
void* my_audio =NULL
Referenced by espeak_Cancel(), espeak_IsPlaying(), espeak_Terminate(), select_output(), sync_espeak_Synth(), and Synthesize().
espeak_AUDIO_OUTPUT my_mode =AUDIO_OUTPUT_SYNCHRONOUS static
Referenced by espeak_Cancel(), espeak_IsPlaying(), espeak_Terminate(), select_output(), and Synthesize().
unsigned int my_unique_identifier =0 static
Referenced by MarkerEvent(), sync_espeak_Char(), sync_espeak_Key(), sync_espeak_SetPunctuationList(), sync_espeak_Synth(), sync_espeak_Synth_Mark(), and Synthesize().
void* my_user_data =NULL static
Referenced by MarkerEvent(), sync_espeak_Char(), sync_espeak_Key(), sync_espeak_SetPunctuationList(), sync_espeak_Synth(), sync_espeak_Synth_Mark(), and Synthesize().
int n_event_list
Referenced by espeak_Initialize(), and MarkerEvent().
unsigned char* outbuf =NULL
Referenced by _nl_find_msg(), copy_rule_string(), MbrolaTranslate(), and Synthesize().
char path_home[N_PATH_HOME]
Referenced by init_path(), and initialise().
int(* phoneme_callback)(const char *) = NULL
Referenced by espeak_SetPhonemeCallback().
int synchronous_mode = 1 static
Referenced by espeak_Char(), espeak_Key(), espeak_SetParameter(), espeak_SetPunctuationList(), espeak_SetVoiceByName(), espeak_SetVoiceByProperties(), espeak_Synth(), espeak_Synth_Mark(), and select_output().
t_espeak_callback* synth_callback = NULL
Referenced by espeak_SetSynthCallback(), and Synthesize().
int(* uri_callback)(int, const char *, const char *) = NULL
Referenced by espeak_SetUriCallback().
espeak_VOICE voice_selected