navit: speech/iphone/speech_iphone.m File Reference
speech_iphone.m File Reference
#include <stdlib.h>
#include <glib.h>
#include "config.h"
#include "item.h"
#include "debug.h"
#include "plugin.h"
#include "speech.h"
#import "VSSpeechSynthesizer.h"
Data Structures
struct speech_priv
Functions
static int speech_iphone_say (struct speech_priv *this, const char *text)
static void speech_iphone_destroy (struct speech_priv *this)
static struct speech_priv * speech_iphone_new (struct speech_methods *meth, struct attr **attrs, struct attr *parent)
void plugin_init (void)
The plugin entry point.
Variables
static struct speech_methods speech_iphone_meth
Function Documentation
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
References dbg, and speech_iphone_new().
static void speech_iphone_destroy (struct speech_priv * this) static
References g_free().
static struct speech_priv* speech_iphone_new (struct speech_methods * meth, struct attr ** attrs, struct attr * parent) static
References dbg, g_new0, and speech_iphone_meth.
Referenced by plugin_init().
static int speech_iphone_say (struct speech_priv * this, const char * text) static
References dbg.
Variable Documentation
struct speech_methods speech_iphone_meth static
Initial value:
= {
        speech_iphone_destroy,
        speech_iphone_say,
}
Referenced by speech_iphone_new().