navit: speech/android/speech_android.c File Reference
speech_android.c File Reference
#include <stdlib.h>
#include <glib.h>
#include "config.h"
#include "item.h"
#include "debug.h"
#include "plugin.h"
#include "android.h"
#include "speech.h"
Data Structures
struct speech_priv
Functions
static int speech_android_say (struct speech_priv *this, const char *text)
static void speech_android_destroy (struct speech_priv *this)
static int speech_android_init (struct speech_priv *ret)
static struct speech_priv * speech_android_new (struct speech_methods *meth, struct attr **attrs, struct attr *parent)
void plugin_init (void)
The plugin entry point.
Variables
static struct speech_methods speech_android_meth
Function Documentation
plugin_init()
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
References speech_android_new().
speech_android_destroy()
static void speech_android_destroy (struct speech_priv * this) static
speech_android_init()
static int speech_android_init (struct speech_priv * ret) static
References android_activity, android_find_class_global(), android_find_method(), dbg, jnienv, lvl_debug, lvl_error, speech_priv::NavitSpeech, speech_priv::NavitSpeech_say, and speech_priv::NavitSpeechClass.
Referenced by speech_android_new().
speech_android_new()
static struct speech_priv* speech_android_new (struct speech_methods * meth, struct attr ** attrs, struct attr * parent) static
References android_version, attr_search(), dbg, speech_priv::flags, lvl_error, speech_priv::NavitSpeechClass, attr::num, speech_android_init(), speech_android_meth, and attr::u.
Referenced by plugin_init().
speech_android_say()
static int speech_android_say (struct speech_priv * this, const char * text) static
References dbg, jnienv, lvl_debug, speech_priv::NavitSpeech, and speech_priv::NavitSpeech_say.
Variable Documentation
speech_android_meth
struct speech_methods speech_android_meth static
Initial value:
= {
    speech_android_destroy,
    speech_android_say,
}
Referenced by speech_android_new().