navit: speech/speech_dispatcher/speech_speech_dispatcher.c File Reference
speech_speech_dispatcher.c File Reference
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include <stdarg.h>
#include "config.h"
#include <libspeechd.h>
#include "plugin.h"
#include "speech.h"
Data Structures
struct speech_priv
Functions
static int speechd_say (struct speech_priv *this, const char *text)
static void speechd_destroy (struct speech_priv *this)
static struct speech_priv * speechd_new (struct speech_methods *meth, struct attr **attrs, struct attr *attr)
void plugin_init (void)
register vehicle_gypsy
Variables
static struct speech_methods speechd_meth
Function Documentation
plugin_init()
void plugin_init (void)
register vehicle_gypsy
Returns
nothing
register vehicle_gypsy
Returns
nothing
The plugin entry point
References speechd_new().
speechd_destroy()
static void speechd_destroy (struct speech_priv * this) static
References speech_priv::conn.
speechd_new()
static struct speech_priv* speechd_new (struct speech_methods * meth, struct attr ** attrs, struct attr * attr) static
References speech_priv::conn, and speechd_meth.
Referenced by plugin_init().
speechd_say()
static int speechd_say (struct speech_priv * this, const char * text) static
References speech_priv::conn, and err().
Variable Documentation
speechd_meth
struct speech_methods speechd_meth static
Initial value:
= {
    speechd_destroy,
    speechd_say,
}
Referenced by speechd_new().