navit: speech/cmdline/speech_cmdline.c File Reference
speech_cmdline.c File Reference
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <glib.h>
#include "config.h"
#include "debug.h"
#include "item.h"
#include "plugin.h"
#include "file.h"
#include "speech.h"
#include "util.h"
Data Structures
struct speech_priv
Functions
static char * urldecode (char *str)
static GList * speech_cmdline_search (GList *samples, int suffix_len, const char *text, int decode)
static int speechd_say (struct speech_priv *this, const char *text)
static void speechd_destroy (struct speech_priv *this)
static struct speech_priv * speechd_new (struct speech_methods *meth, struct attr **attrs, struct attr *parent)
void plugin_init (void)
The plugin entry point.
Variables
static struct speech_methods speechd_meth
Function Documentation
void plugin_init (void)
The plugin entry point.
Description: Initialisation of vehicle_file plugin
Returns
nothing
The plugin entry point
References speechd_new().
static GList* speech_cmdline_search (GList * samples, int suffix_len, const char * text, int decode) static
References _GList::data, dbg, g_ascii_strncasecmp(), g_free(), g_list_free(), g_list_length(), g_list_next, g_list_prepend(), lvl_debug, NULL, and urldecode().
Referenced by speechd_say().
static void speechd_destroy (struct speech_priv * this) static
References _GList::data, g_free(), g_list_free(), and spawn_process_info_free().
static struct speech_priv* speechd_new (struct speech_methods * meth, struct attr ** attrs, struct attr * parent) static
References attr_search(), dbg, file_closedir(), file_opendir(), file_readdir(), g_list_prepend(), g_new0, g_strdup(), handle(), lvl_debug, lvl_error, name, NULL, attr::num, speechd_meth, attr::str, and attr::u.
Referenced by plugin_init().
static int speechd_say (struct speech_priv * this, const char * text) static
References argc, argv, _GList::data, dbg, g_free(), g_list_free(), g_list_length(), g_list_next, g_new, g_strdup(), g_strdup_printf(), g_strfreev(), g_strsplit(), g_strv_length(), i, lvl_debug, lvl_error, NULL, spawn_process(), spawn_process_check_status(), spawn_process_info_free(), and speech_cmdline_search().
static char* urldecode (char * str) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References g_strdup().
Referenced by speech_cmdline_search().
Variable Documentation
struct speech_methods speechd_meth static
Initial value:
= {
        speechd_destroy,
        speechd_say,
}
Referenced by speechd_new().