navit: speech/dbus/speech_dbus.c File Reference
speech_dbus.c File Reference
#include <stdlib.h>
#include <glib.h>
#include "config.h"
#include "item.h"
#include "plugin.h"
#include "navit.h"
#include "attr.h"
#include "callback.h"
#include "speech.h"
Data Structures
struct speech_priv
Functions
static int speech_dbus_say (struct speech_priv *this, const char *text)
static void speech_dbus_destroy (struct speech_priv *this)
static struct speech_priv * speech_dbus_new (struct speech_methods *meth, struct attr **attrs, struct attr *parent)
void plugin_init (void)
register vehicle_gypsy
Variables
static struct speech_methods speech_dbus_meth
Function Documentation
plugin_init()
void plugin_init (void)
register vehicle_gypsy
Returns
nothing
register vehicle_gypsy
Returns
nothing
The plugin entry point
References speech_dbus_new().
speech_dbus_destroy()
static void speech_dbus_destroy (struct speech_priv * this) static
speech_dbus_new()
static struct speech_priv* speech_dbus_new (struct speech_methods * meth, struct attr ** attrs, struct attr * parent) static
References speech_priv::nav, attr::navit, speech_dbus_meth, attr::type, and attr::u.
Referenced by plugin_init().
speech_dbus_say()
static int speech_dbus_say (struct speech_priv * this, const char * text) static
References attr::callback_list, callback_list_call_attr_4, speech_priv::nav, navit_get_attr(), attr::str, attr::type, and attr::u.
Variable Documentation
speech_dbus_meth
struct speech_methods speech_dbus_meth static
Initial value:
= {
    speech_dbus_destroy,
    speech_dbus_say,
}
Referenced by speech_dbus_new().