navit: start_real.h File Reference
start_real.h File Reference
Functions
int main_real (int argc, char *const *argv)
Function Documentation
int main_real (int argc, char *const * argv)
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References _, _g_slice_thread_init_nomessage(), argc, argv, atom_init(), builtin_init(), command(), command_evaluate(), config, attr::config, config_get_attr(), config_load(), dbg, debug_finished(), debug_init(), debug_set_global_level(), debug_set_logfile(), event_glib_init(), event_main_loop_run(), exit, file_exists(), file_init(), fprintf(), g_free(), g_list_append(), g_list_free(), g_list_next, g_strdup(), g_strjoin(), geom_init(), getenv, getopt(), linguistics_free(), linguistics_init(), lvl_debug, lvl_error, lvl_info, main_argc, main_argv, main_init(), navigation_init(), navit_nls_main_init(), NULL, optarg, opterr, optind, optopt, print_usage(), printf(), route_init(), search_init(), tracking_init(), attr::type, attr::u, and version.
Referenced by Java_org_navitproject_navit_Navit_NavitMain(), main(), and NPP_New().