navit: start_real.c File Reference
start_real.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include "config.h"
#include <XGetopt.h>
#include "config_.h"
#include "version.h"
#include "item.h"
#include "coord.h"
#include "main.h"
#include "route.h"
#include "navigation.h"
#include "track.h"
#include "debug.h"
#include "event.h"
#include "event_glib.h"
#include "xmlconfig.h"
#include "file.h"
#include "search.h"
#include "start_real.h"
#include "linguistics.h"
#include "navit_nls.h"
#include "atom.h"
#include "command.h"
#include "geom.h"
Functions
static void print_usage (void)
void builtin_init (void)
int main_real (int argc, char *const *argv)
Variables
char * version =PACKAGE_VERSION"+git:"GIT_VERSION""NAVIT_VARIANT
int main_argc
char *const * main_argv
Function Documentation
void builtin_init (void)
Referenced by main_real().
int main_real (int argc, char *const * argv)
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References _, argc, argv, atom_init(), builtin_init(), command(), command_evaluate(), config, attr::config, config_get_attr(), config_load(), dbg, debug_finished(), debug_init(), debug_set_global_level(), debug_set_logfile(), event_glib_init(), event_main_loop_run(), exit, file_exists(), file_init(), geom_init(), linguistics_free(), linguistics_init(), lvl_debug, lvl_error, lvl_info, main_argc, main_argv, main_init(), navigation_init(), navit_nls_main_init(), print_usage(), route_init(), search_init(), tracking_init(), attr::type, attr::u, and version.
Referenced by Java_org_navitproject_navit_Navit_NavitMain(), main(), and NPP_New().
static void print_usage (void) static
References _.
Referenced by main_real().
Variable Documentation
int main_argc
Referenced by event_cocoa_main_loop_run(), and main_real().
char* const* main_argv
Referenced by event_cocoa_main_loop_run(), and main_real().
char* version =PACKAGE_VERSION"+git:"GIT_VERSION""NAVIT_VARIANT
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by binfile_check_version(), gui_internal_cmd2_about(), gui_internal_top_bar(), index_init(), Java_org_navitproject_navit_Navit_NavitMain(), main_real(), mapExtract::mapExtract(), osm_protobufdb_parse_info(), and osso_navit().