navit: support/libc/stat.c File Reference
stat.c File Reference
#include <windows.h>
#include <time.h>
#include <fcntl.h>
#include <io.h>
#include <sys/stat.h>
#include <stdio.h>
#include "debug.h"
#include "timeutil.h"
Data Structures
struct stat_file_info_t
Macros
#define COPY_MEMBER(DEST, SRC, MEMBER)
#define TO_STAT_FILE_INFO(DEST, SRC)
Functions
static int __stat_by_file_info (struct stat_file_info_t *fi, struct _stat *st, int exec)
int _fstat (int fd, struct _stat *st)
int fstat (int fd, struct stat *st)
int _stat (const char *path, struct _stat *st)
int stat (const char *path, struct stat *st)
Macro Definition Documentation
#define COPY_MEMBER (DEST, SRC, MEMBER)
Value:
do {                                            \
    (DEST)->MEMBER = (SRC)->MEMBER;             \
  } while (0)
#define TO_STAT_FILE_INFO (DEST, SRC)
Value:
do {                                            \
    COPY_MEMBER (DEST, SRC, dwFileAttributes);  \
    COPY_MEMBER (DEST, SRC, ftLastWriteTime);   \
    COPY_MEMBER (DEST, SRC, ftCreationTime);    \
    COPY_MEMBER (DEST, SRC, ftLastAccessTime);  \
    COPY_MEMBER (DEST, SRC, nFileSizeLow);      \
  } while (0)
Referenced by _fstat(), and _stat().
Function Documentation
static int __stat_by_file_info (struct stat_file_info_t * fi, struct _stat * st, int exec) static
References __FILETIME_to_time_t(), _S_IEXEC, _S_IFDIR, _S_IFREG, _S_IREAD, _S_IWRITE, stat_file_info_t::dwFileAttributes, stat_file_info_t::ftCreationTime, stat_file_info_t::ftLastAccessTime, stat_file_info_t::ftLastWriteTime, stat_file_info_t::nFileSizeLow, _stat::st_atime, _stat::st_ctime, _stat::st_ino, _stat::st_mode, _stat::st_mtime, _stat::st_nlink, _stat::st_rdev, and _stat::st_size.
Referenced by _fstat(), and _stat().
int _fstat (int fd, struct _stat * st)
References __stat_by_file_info(), and TO_STAT_FILE_INFO.
Referenced by fstat().
int _stat (const char * path, struct _stat * st)
References __stat_by_file_info(), dbg, lvl_debug, lvl_error, strcasecmp(), and TO_STAT_FILE_INFO.
Referenced by stat().
int fstat (int fd, struct stat * st)
References _fstat().
Referenced by _nl_load_domain(), ezxml_parse_fd(), and file_version().
int stat (const char * path, struct stat * st)
References _stat().
Referenced by file_exists(), file_is_dir(), file_is_reg(), file_version(), GetFileLength(), and gmap_new().