navit: support/libc/strcasecmp.c File Reference
strcasecmp.c File Reference
#include <string.h>
Functions
int strcasecmp (const char *sz1, const char *sz2)
Function Documentation
int strcasecmp (const char * sz1, const char * sz2)
Referenced by _stat(), alias_compare(), g_strcasecmp(), gui_internal_html_text(), housenumber_search_get_item(), html_image(), osm_add_tag(), town_search_compare(), and vehicle_maemo_open().