navit: map/mg/street.c File Reference
street.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "debug.h"
#include "mg.h"
Data Structures
struct street_name_index
Functions
static void street_name_get (struct street_name *name, unsigned char **p)
static int street_name_eod (struct street_name *name)
static void street_name_numbers_get (struct street_name_numbers *name_numbers, unsigned char **p)
static int street_name_numbers_eod (struct street_name_numbers *name_numbers)
static void street_name_number_get (struct street_name_number *name_number, unsigned char **p)
static void street_name_get_by_id (struct street_name *name, struct file *file, unsigned long id)
static int street_get_bytes (struct coord_rect *r)
static int street_get_coord (unsigned char **pos, int bytes, struct coord_rect *ref, struct coord *f)
static void street_coord_get_begin (unsigned char **p)
static void street_coord_rewind (void *priv_data)
static int street_coord_get_helper (struct street_priv *street, struct coord *c)
static int street_coord_get (void *priv_data, struct coord *c, int count)
static void street_attr_rewind (void *priv_data)
static int street_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static void street_get_data (struct street_priv *street, unsigned char **p)
int street_get (struct map_rect_priv *mr, struct street_priv *street, struct item *item)
int street_get_byid (struct map_rect_priv *mr, struct street_priv *street, int id_hi, int id_lo, struct item *item)
struct street_name_index __attribute__ ((packed))
static unsigned char latin1_tolower (unsigned char c)
static unsigned char latin1_tolower_ascii (unsigned char c)
static int strncasecmp_latin1 (char *str1, char *str2, int len)
static int strncasecmp_latin1_ascii (char *str1, char *str2, int len)
static int street_search_compare_do (struct map_rect_priv *mr, int country, int town_assoc, char *name)
static int street_search_compare (unsigned char **p, struct map_rect_priv *mr)
static void street_name_coord_rewind (void *priv_data)
static void street_name_attr_rewind (void *priv_data)
static int street_name_coord_get (void *priv_data, struct coord *c, int count)
static int street_name_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
int street_name_get_byid (struct map_rect_priv *mr, struct street_priv *street, int id_hi, int id_lo, struct item *item)
static struct item * street_search_get_item_street_name (struct map_rect_priv *mr)
struct item * street_search_get_item (struct map_rect_priv *mr)
static int street_name_numbers_next (struct map_rect_priv *mr)
static int street_name_number_next (struct map_rect_priv *mr)
static void housenumber_coord_rewind (void *priv_data)
static void housenumber_attr_rewind (void *priv_data)
static int housenumber_coord_get (void *priv_data, struct coord *c, int count)
static int housenumber_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
int housenumber_search_setup (struct map_rect_priv *mr)
static int house_number_next (char *number, char *first, char *last, int interpolation, int *percentage)
struct item * housenumber_search_get_item (struct map_rect_priv *mr)
Variables
int coord_debug
static struct item_methods street_meth
static unsigned char limit [] = {0,0,1,1,1,2,2,4,6,6,12,13,14,20,20,20,20,20,20}
int block
unsigned short country
int town_assoc
char name [0]
static struct item_methods street_name_meth
static struct item_methods housenumber_meth
Function Documentation
__attribute__()
struct street_name_index __attribute__ ((packed))
References block_priv::b, map_rect_priv::b, block_get_byindex(), block_get_r(), street_priv::bytes, street_priv::coord_begin, map_rect_priv::current_file, dbg, map_priv::dirname, street_priv::end, block_priv::end, map_priv::file, file_strname_stn, lvl_debug, map_rect_priv::m, item::meth, street_priv::name_file, street_priv::p, block_priv::p, item::priv_data, street_priv::ref, street_priv::str, street_priv::str_start, street_coord_get_begin(), street_get(), street_get_bytes(), street_get_data(), street_meth, street_str_get_segid(), tree_search_hv(), and street_priv::type.
house_number_next()
static int house_number_next (char * number, char * first, char * last, int interpolation, int * percentage) static
Referenced by housenumber_search_get_item().
housenumber_attr_get()
static int housenumber_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References attr_to_name(), street_name_numbers::country, street_priv::current_number, dbg, street_name_numbers::dist, file_town_twn, item_attr_get(), lvl_error, map_rect_get_item_byid_mg(), street_priv::name_numbers, map_rect_priv::search_item_tmp, map_rect_priv::search_mr_tmp, attr::str, map_rect_priv::street, attr::type, and attr::u.
housenumber_attr_rewind()
static void housenumber_attr_rewind (void * priv_data) static
housenumber_coord_get()
static int housenumber_coord_get (void * priv_data, struct coord * c, int count) static
housenumber_coord_rewind()
static void housenumber_coord_rewind (void * priv_data) static
housenumber_search_get_item()
struct item* housenumber_search_get_item (struct map_rect_priv * mr)
References street_priv::current_number, dbg, street_priv::first_number, house_number_next(), map_rect_priv::item, street_priv::last_number, lvl_debug, map_rect_priv::search_item_tmp, map_rect_priv::search_partial, map_rect_priv::search_str, map_rect_priv::street, and street_name_number_next().
housenumber_search_setup()
int housenumber_search_setup (struct map_rect_priv * mr)
References street_name_numbers::aux_data, street_name_numbers::aux_len, map_rect_priv::b, file::begin, map_rect_priv::current_file, dbg, map_priv::file, file_strname_stn, housenumber_meth, item::id_hi, item::id_lo, map_rect_priv::item, lvl_debug, map_rect_priv::m, item::meth, street_priv::name, street_priv::name_file, street_priv::name_numbers, block_priv::p, item::priv_data, map_rect_priv::search_attr, map_rect_priv::search_item, map_rect_priv::search_str, attr::str, map_rect_priv::street, street_name_get(), street_name_number_next(), street_name_numbers_next(), street_name_numbers::tmp_data, item::type, and attr::u.
Referenced by map_search_setup().
latin1_tolower()
static unsigned char latin1_tolower (unsigned char c) static
References c.
Referenced by latin1_tolower_ascii(), and strncasecmp_latin1().
latin1_tolower_ascii()
static unsigned char latin1_tolower_ascii (unsigned char c) static
References c, dbg, latin1_tolower(), and lvl_debug.
Referenced by strncasecmp_latin1_ascii().
street_attr_get()
static int street_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References street_priv::attr_next, street_name::country, dbg, street_priv::debug, street_priv::flags, street_priv::header, street_name::len, lvl_debug, mg_country_to_isonum(), street_priv::name, street_name::name1, street_name::name2, street_priv::name_file, attr::num, attr::str, street_priv::str, street_header_get_order(), street_name_get_by_id(), street_str_get_limit(), street_str_get_nameid(), street_str_get_segid(), street_str_get_type(), street_str_get_unknown2(), street_str_get_unknown3(), street_name::townassoc, attr::type, and attr::u.
street_attr_rewind()
static void street_attr_rewind (void * priv_data) static
street_coord_get()
static int street_coord_get (void * priv_data, struct coord * c, int count) static
References c, street_priv::coord_begin, dbg, debug, lvl_debug, street_priv::more, street_priv::next, street_priv::p, street_priv::status, street_priv::status_rewind, street_priv::str, street_priv::str_start, street_coord_get_helper(), street_str_get_segid(), pcoord::x, and pcoord::y.
Referenced by street_get().
street_coord_get_begin()
static void street_coord_get_begin (unsigned char ** p) static
References p, and street_str_get_segid().
Referenced by __attribute__(), and street_get().
street_coord_get_helper()
static int street_coord_get_helper (struct street_priv * street, struct coord * c) static
References street_priv::bytes, c, street_priv::end, street_priv::next, street_priv::p, street_priv::ref, street_priv::status, and street_get_coord().
Referenced by street_coord_get().
street_coord_rewind()
static void street_coord_rewind (void * priv_data) static
References street_priv::next, street_priv::p, street_priv::status, and street_priv::status_rewind.
street_get()
int street_get (struct map_rect_priv * mr, struct street_priv * street, struct item * item)
References AF_ONEWAY, AF_ONEWAYREV, street_priv::attr_next, block_priv::b, map_rect_priv::b, block_get_r(), street_priv::bytes, c, street_priv::coord_begin, map_rect_priv::cur_sel, map_rect_priv::current_file, dbg, street_priv::end, block_priv::end, map_priv::file, file_strname_stn, street_priv::flags, street_priv::header, street_priv::hn_count, street_priv::housenumber, item::id_hi, item::id_lo, item_get_default_flags(), street_name::len, limit, lvl_error, map_rect_priv::m, map_selection_contains_item(), item::meth, street_priv::more, street_priv::name, street_priv::name_file, street_priv::next, map_selection::order, street_priv::p, block_priv::p, street_priv::p_rewind, block_priv::p_start, item::priv_data, street_priv::ref, street_priv::status, street_priv::status_rewind, street_priv::str, street_priv::str_start, street_coord_get(), street_coord_get_begin(), street_get_bytes(), street_get_data(), street_header_get_order(), street_meth, street_str_get_limit(), street_str_get_segid(), street_str_get_type(), street_type_get_country(), item::type, and street_priv::type.
Referenced by __attribute__(), and map_rect_get_item_mg().
street_get_byid()
int street_get_byid (struct map_rect_priv * mr, struct street_priv * street, int id_hi, int id_lo, struct item * item)
Referenced by map_rect_get_item_byid_mg().
street_get_bytes()
static int street_get_bytes (struct coord_rect * r) static
References dbg_assert, coord_rect::lu, coord_rect::rl, coord::x, and coord::y.
Referenced by __attribute__(), and street_get().
street_get_coord()
static int street_get_coord (unsigned char ** pos, int bytes, struct coord_rect * ref, struct coord * f) static
References dbg, coord_rect::lu, lvl_debug, p, startup::pos, coord_rect::rl, coord::x, and coord::y.
Referenced by street_coord_get_helper().
street_get_data()
static void street_get_data (struct street_priv * street, unsigned char ** p) static
References street_priv::header, p, street_header_get_count(), street_priv::type, and street_priv::type_count.
Referenced by __attribute__(), NGQPoint::_coordName(), item_get_heightline(), map_route_occluded_get_buildings(), map_route_occluded_get_item(), street_get(), and tracking_doupdate_lines().
street_name_attr_get()
static int street_name_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References attr_to_name(), street_name_numbers::country, dbg, street_name_numbers::dist, file_town_twn, item_attr_get(), lvl_error, map_rect_get_item_byid_mg(), street_priv::name, street_name::name1, street_name::name2, street_priv::name_numbers, map_rect_priv::search_item_tmp, map_rect_priv::search_mr_tmp, attr::str, map_rect_priv::street, attr::type, and attr::u.
street_name_attr_rewind()
static void street_name_attr_rewind (void * priv_data) static
street_name_coord_get()
static int street_name_coord_get (void * priv_data, struct coord * c, int count) static
References street_name::aux_data, c, dbg, lvl_debug, street_priv::name, p, map_rect_priv::street, street_name_numbers_get(), and street_name_numbers_get_coord().
street_name_coord_rewind()
static void street_name_coord_rewind (void * priv_data) static
street_name_eod()
static int street_name_eod (struct street_name * name) static
References name.
Referenced by street_name_numbers_next(), and street_search_get_item().
street_name_get()
static void street_name_get (struct street_name * name, unsigned char ** p) static
References get_string(), get_u16_unal(), get_u32_unal(), name, and p.
Referenced by housenumber_search_setup(), street_name_get_by_id(), street_name_get_byid(), and street_search_get_item_street_name().
street_name_get_by_id()
static void street_name_get_by_id (struct street_name * name, struct file * file, unsigned long id) static
References file::begin, name, p, and street_name_get().
Referenced by street_attr_get().
street_name_get_byid()
int street_name_get_byid (struct map_rect_priv * mr, struct street_priv * street, int id_hi, int id_lo, struct item * item)
References map_rect_priv::b, file::begin, map_rect_priv::current_file, dbg, map_priv::file, item::id_hi, item::id_lo, lvl_debug, map_rect_priv::m, item::map, item::meth, street_priv::name, street_priv::name_file, block_priv::p, item::priv_data, street_name_get(), street_name_meth, and item::type.
Referenced by map_rect_get_item_byid_mg().
street_name_number_get()
static void street_name_number_get (struct street_name_number * name_number, unsigned char ** p) static
References street_name_number::c, coord_get(), street_name_number::first, get_string(), get_u16_unal(), get_u8(), street_name_number::last, street_name_number::len, housenumber::number, p, street_name_number::segment, housenumber::suffix, and street_name_number::tag.
Referenced by street_name_number_next().
street_name_number_next()
static int street_name_number_next (struct map_rect_priv * mr) static
References street_priv::current_number, street_name_number::first, street_priv::first_number, street_name_number::last, street_priv::last_number, street_priv::name_number, street_priv::name_numbers, housenumber::number, map_rect_priv::street, street_name_number_get(), street_name_numbers_eod(), housenumber::suffix, and street_name_numbers::tmp_data.
Referenced by housenumber_search_get_item(), and housenumber_search_setup().
street_name_numbers_eod()
static int street_name_numbers_eod (struct street_name_numbers * name_numbers) static
References street_name_numbers::aux_data, street_name_numbers::aux_len, and street_name_numbers::tmp_data.
Referenced by street_name_number_next().
street_name_numbers_get()
static void street_name_numbers_get (struct street_name_numbers * name_numbers, unsigned char ** p) static
References street_name_numbers::aux_data, street_name_numbers::aux_len, street_name_numbers::c, coord_get(), street_name_numbers::country, street_name_numbers::dist, street_name_numbers::first, get_string(), get_u16_unal(), get_u32_unal(), get_u8(), street_name_numbers::last, street_name_numbers::len, housenumber::number, p, street_name_numbers::segment_count, street_name_numbers::segments, housenumber::suffix, street_name_numbers::tag, street_name_numbers::tmp_data, and street_name_numbers::tmp_len.
Referenced by street_name_coord_get(), street_name_numbers_next(), and street_search_get_item().
street_name_numbers_next()
static int street_name_numbers_next (struct map_rect_priv * mr) static
References street_name::aux_data, dbg, lvl_debug, street_priv::name, street_priv::name_numbers, map_rect_priv::street, street_name_eod(), street_name_numbers_get(), and street_name::tmp_data.
Referenced by housenumber_search_setup().
street_search_compare()
static int street_search_compare (unsigned char ** p, struct map_rect_priv * mr) static
References street_name_index::block, street_name_index::country, dbg, lvl_debug, street_name_index::name, p, map_rect_priv::search_block, street_search_compare_do(), and street_name_index::town_assoc.
Referenced by street_search_get_item_street_name().
street_search_compare_do()
static int street_search_compare_do (struct map_rect_priv * mr, int country, int town_assoc, char * name) static
References dbg, item::id_hi, item::id_lo, lvl_debug, name, map_rect_priv::search_item, map_rect_priv::search_partial, map_rect_priv::search_str, strncasecmp_latin1(), strncasecmp_latin1_ascii(), and town_assoc.
Referenced by street_search_compare(), and street_search_get_item_street_name().
street_search_get_item()
struct item* street_search_get_item (struct map_rect_priv * mr)
References street_name::aux_len, item::id_hi, map_rect_priv::item, item, street_priv::name, street_priv::name_numbers, map_rect_priv::search_item_tmp, map_rect_priv::street, street_name_eod(), street_name_numbers_get(), street_search_get_item_street_name(), and street_name::tmp_data.
street_search_get_item_street_name()
static struct item* street_search_get_item_street_name (struct map_rect_priv * mr) static
References street_name::aux_data, street_name::aux_len, map_rect_priv::b, file::begin, block_get_byindex(), block_next_lin(), block_priv::block_start, street_name::country, map_rect_priv::current_file, dbg, file::end, block_priv::end, map_priv::file, file_strname_stn, item::id_hi, item::id_lo, map_rect_priv::item, lvl_debug, map_rect_priv::m, item::map, item::meth, street_priv::name, street_name::name1, street_name::name2, block_priv::p, item::priv_data, map_rect_priv::search_blk_count, map_rect_priv::search_block, map_rect_priv::search_linear, map_rect_priv::search_p, map_rect_priv::search_str, map_rect_priv::street, town_priv::street_assoc, street_name_get(), street_name_meth, street_search_compare(), street_search_compare_do(), map_rect_priv::town, street_name::townassoc, tree_search_next(), map_rect_priv::ts, and item::type.
Referenced by street_search_get_item().
strncasecmp_latin1()
static int strncasecmp_latin1 (char * str1, char * str2, int len) static
References latin1_tolower().
Referenced by street_search_compare_do().
strncasecmp_latin1_ascii()
static int strncasecmp_latin1_ascii (char * str1, char * str2, int len) static
References latin1_tolower_ascii().
Referenced by street_search_compare_do().
Variable Documentation
block
int block
coord_debug
int coord_debug
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
country
unsigned short country
housenumber_meth
struct item_methods housenumber_meth static
Initial value:
= {
    housenumber_coord_rewind,
    housenumber_coord_get,
    housenumber_attr_rewind,
    housenumber_attr_get,
}
Referenced by housenumber_search_setup().
limit
unsigned char limit[] = {0,0,1,1,1,2,2,4,6,6,12,13,14,20,20,20,20,20,20} static
Referenced by bookmarks_append_destinations(), bookmarks_store_bookmarks_to_file(), displayitem_draw(), file_reader_finish(), file_reader_new(), map_rect_new_garmin_img(), street_get(), and vehicle_log_binfile().
name
char name[0]
Referenced by add_aux_tile(), add_aux_tiles(), add_menu(), android_find_class_global(), android_find_method(), android_find_static_method(), atom(), atom_lookup(), attr_create_hash(), attr_from_line(), attr_getattr_py(), attr_new_from_text(), attr_new_py(), attr_resolve(), binfile_search_cd(), bookmarks_move_down(), ch_copy_to_tiles(), ch_create_tempfiles(), config_getattr_py(), contains_suffix(), convert_to_attrs(), org.navitproject.navit.Navit::createNotificationChannel(), cursor_new(), debug_level_set(), debug_new(), encode_attr(), file_create(), file_create_caseinsensitive(), file_exists(), file_get_contents(), file_is_dir(), file_is_reg(), file_mkdir(), find_attr(), find_attr_dup(), find_by_name(), find_class_global(), find_method(), find_static_method(), font_freetype_font_new(), geod_set(), get_tag(), geticon(), getProperty(), graphics_image_new_scaled_rotated(), gui_datawindow_new(), gui_gtk_add_toggle_menu(), gui_gtk_bookmarks_update(), gui_gtk_datawindow_add(), gui_gtk_datawindow_new(), gui_gtk_destinations_update(), gui_gtk_layouts_init(), gui_gtk_maps_init(), gui_gtk_vehicles_update(), gui_internal_add_vehicle_profile(), gui_internal_cmd2_position(), gui_internal_cmd_add_bookmark2(), gui_internal_cmd_add_bookmark_folder2(), gui_internal_cmd_insert_destination_do(), gui_internal_cmd_pois_item(), gui_internal_cmd_position_do(), gui_internal_cmd_rename_bookmark(), gui_internal_cmd_set_destination(), gui_internal_menu_vehicle_settings(), hasMethod(), hasProperty(), image_new(), image_new_helper(), image_new_l(), image_new_s(), image_new_scaled(), image_new_xs(), invoke(), org.navitproject.navit.Navit::invokeCallbackOnGeo(), item_create_hash(), Java_org_navitproject_navit_NavitCallbackHandler_callbackMessageChannel(), layout_get_cursor(), map_getattr_py(), mapset_getattr_py(), maptype_get(), maptype_register(), match(), menu_add(), navigation_getattr_py(), navigation_item_destination(), navit_get_attr_py(), navit_getattr_py(), navit_set_cursors(), navit_set_layout_by_name(), navit_set_vehicle_by_name(), navit_set_vehicleprofile_name(), osd_nav_next_turn_draw(), osd_odometer_new(), osm_process_town_by_boundary_update_attrs(), osm_process_towns(), osm_protobufdb_start_file(), param_add_dec(), param_add_hex(), param_add_hex_sig(), param_add_string(), pcoord_getattr_py(), pedestrian_draw_arrow(), plugin_get_category(), plugin_new(), pngdecode(), printIdentifier(), process_associated_street_member(), process_associated_streets_setup(), process_boundaries_finish(), replace_suffix(), route_getattr_py(), speechd_new(), street_name_eod(), street_name_get(), street_name_get_by_id(), street_search_compare_do(), tempfile(), tempfile_name(), tempfile_unlink(), template_getattr_py(), tile_write_item_to_tile(), town_search_compare(), traffic_message_restore_segments(), vehicle_file_open(), vehicleprofile_update(), write_zipmember(), and xpmdecode().
street_meth
struct item_methods street_meth static
Initial value:
= {
    street_coord_rewind,
    street_coord_get,
    street_attr_rewind,
    street_attr_get,
}
Referenced by __attribute__(), and street_get().
street_name_meth
struct item_methods street_name_meth static
Initial value:
= {
    street_name_coord_rewind,
    street_name_coord_get,
    street_name_attr_rewind,
    street_name_attr_get,
}
Referenced by street_name_get_byid(), and street_search_get_item_street_name().
town_assoc
int town_assoc
Referenced by street_search_compare_do().