navit: datawindow_methods Struct Reference
datawindow_methods Struct Reference
#include <data_window.h>
Data Fields
void(* destroy)(struct datawindow_priv *win)
void(* add)(struct datawindow_priv *win, struct param_list *param, int count)
void(* mode)(struct datawindow_priv *win, int start)
Field Documentation
add
void(* datawindow_methods::add) (struct datawindow_priv *win, struct param_list *param, int count)
Referenced by datawindow_add().
destroy
void(* datawindow_methods::destroy) (struct datawindow_priv *win)
Referenced by datawindow_destroy().
mode
void(* datawindow_methods::mode) (struct datawindow_priv *win, int start)
Referenced by datawindow_mode().
The documentation for this struct was generated from the following file:
data_window.h