navit: osd_methods Struct Reference
osd_methods Struct Reference
#include <osd.h>
Data Fields
void(* osd_destroy)(struct osd_priv *osd)
int(* set_attr)(struct osd_priv *osd, struct attr *attr)
void(* destroy)(struct osd_priv *osd)
int(* get_attr)(struct osd_priv *osd, enum attr_type type, struct attr *attr)
Field Documentation
destroy
void(* osd_methods::destroy) (struct osd_priv *osd)
Referenced by osd_destroy().
get_attr
int(* osd_methods::get_attr) (struct osd_priv *osd, enum attr_type type, struct attr *attr)
Referenced by osd_get_attr().
osd_destroy
void(* osd_methods::osd_destroy) (struct osd_priv *osd)
set_attr
int(* osd_methods::set_attr) (struct osd_priv *osd, struct attr *attr)
Referenced by osd_auxmap_new(), osd_button_new(), osd_cmd_interface_new(), osd_compass_new(), osd_gps_status_new(), osd_image_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_odometer_new(), osd_route_guard_new(), osd_scale_new(), osd_set_attr(), osd_speed_cam_new(), osd_speed_warner_new(), osd_stopwatch_new(), osd_text_new(), and osd_volume_new().
The documentation for this struct was generated from the following file:
osd.h