navit: window Struct Reference
window Struct Reference
#include <window.h>
Data Fields
void * priv
int(* fullscreen)(struct window *win, int on)
void(* disable_suspend)(struct window *win)
Detailed Description
Navit, a modular navigation system. Copyright (C) 2005-2009 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. Describes the Navit application window or equivalent.
Field Documentation
disable_suspend
void(* window::disable_suspend) (struct window *win)
Method to disable suspend mode or screen savers
Referenced by get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), graphics_android_new(), graphics_svg_debug_disable_suspend(), and svg_debug_get_data().
fullscreen
int(* window::fullscreen) (struct window *win, int on)
Method to toggle fullscreen mode
Referenced by get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), graphics_android_new(), graphics_svg_debug_fullscreen(), gui_internal_set_graphics(), and svg_debug_get_data().
priv
void* window::priv
Private data of the graphics implementation
Referenced by disable_suspend(), disable_suspend(), fullscreen(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), get_data(), graphics_android_new(), graphics_svg_debug_fullscreen(), graphics_win32_new(), image_free(), image_free(), svg_debug_get_data(), window_fullscreen(), and WndProc().
The documentation for this struct was generated from the following file:
window.h