navit: gui_methods Struct Reference
gui_methods Struct Reference
#include <gui.h>
Data Fields
struct menu_priv *(* menubar_new)(struct gui_priv *priv, struct menu_methods *meth)
struct menu_priv *(* popup_new)(struct gui_priv *priv, struct menu_methods *meth)
int(* set_graphics)(struct gui_priv *priv, struct graphics *gra)
int(* run_main_loop)(struct gui_priv *priv)
struct datawindow_priv *(* datawindow_new)(struct gui_priv *priv, const char *name, struct callback *click, struct callback *close, struct datawindow_methods *meth)
int(* add_bookmark)(struct gui_priv *priv, struct pcoord *c, char *description)
void(* disable_suspend)(struct gui_priv *priv)
int(* get_attr)(struct gui_priv *priv, enum attr_type type, struct attr *attr)
int(* add_attr)(struct gui_priv *priv, struct attr *attr)
int(* set_attr)(struct gui_priv *priv, struct attr *attr)
Field Documentation
add_attr
int(* gui_methods::add_attr) (struct gui_priv *priv, struct attr *attr)
Referenced by gui_add_attr().
add_bookmark
int(* gui_methods::add_bookmark) (struct gui_priv *priv, struct pcoord *c, char *description)
Referenced by gui_add_bookmark().
datawindow_new
struct datawindow_priv *(* gui_methods::datawindow_new) (struct gui_priv *priv, const char *name, struct callback *click, struct callback *close, struct datawindow_methods *meth)
Referenced by gui_datawindow_new().
disable_suspend
void(* gui_methods::disable_suspend) (struct gui_priv *priv)
Referenced by gui_disable_suspend().
get_attr
int(* gui_methods::get_attr) (struct gui_priv *priv, enum attr_type type, struct attr *attr)
Referenced by gui_get_attr().
menubar_new
struct menu_priv *(* gui_methods::menubar_new) (struct gui_priv *priv, struct menu_methods *meth)
Referenced by gui_menubar_new().
popup_new
struct menu_priv *(* gui_methods::popup_new) (struct gui_priv *priv, struct menu_methods *meth)
Referenced by gui_popup_new().
run_main_loop
int(* gui_methods::run_main_loop) (struct gui_priv *priv)
Referenced by gui_has_main_loop(), and gui_run_main_loop().
set_attr
int(* gui_methods::set_attr) (struct gui_priv *priv, struct attr *attr)
Referenced by gui_set_attr().
set_graphics
int(* gui_methods::set_graphics) (struct gui_priv *priv, struct graphics *gra)
Referenced by gui_set_graphics().
The documentation for this struct was generated from the following file:
gui.h