navit: item_methods Struct Reference
item_methods Struct Reference
#include <item.h>
Data Fields
void(* item_coord_rewind)(void *priv_data)
int(* item_coord_get)(void *priv_data, struct coord *c, int count)
void(* item_attr_rewind)(void *priv_data)
int(* item_attr_get)(void *priv_data, enum attr_type attr_type, struct attr *attr)
int(* item_coord_is_node)(void *priv_data)
int(* item_attr_set)(void *priv_data, struct attr *attr, enum change_mode mode)
int(* item_coord_set)(void *priv_data, struct coord *c, int count, enum change_mode mode)
int(* item_type_set)(void *priv_data, enum item_type type)
Field Documentation
item_attr_get
int(* item_methods::item_attr_get) (void *priv_data, enum attr_type attr_type, struct attr *attr)
Referenced by item_attr_get().
item_attr_rewind
void(* item_methods::item_attr_rewind) (void *priv_data)
Referenced by item_attr_rewind().
item_attr_set
int(* item_methods::item_attr_set) (void *priv_data, struct attr *attr, enum change_mode mode)
Referenced by item_attr_set().
item_coord_get
int(* item_methods::item_coord_get) (void *priv_data, struct coord *c, int count)
Referenced by item_coord_get(), and item_coord_get_within_selection().
item_coord_is_node
int(* item_methods::item_coord_is_node) (void *priv_data)
Referenced by item_coord_is_node().
item_coord_rewind
void(* item_methods::item_coord_rewind) (void *priv_data)
Referenced by item_coord_rewind().
item_coord_set
int(* item_methods::item_coord_set) (void *priv_data, struct coord *c, int count, enum change_mode mode)
Referenced by item_coord_set().
item_type_set
int(* item_methods::item_type_set) (void *priv_data, enum item_type type)
Referenced by item_type_set().
The documentation for this struct was generated from the following file:
item.h