navit: event_methods Struct Reference
event_methods Struct Reference
#include <event.h>
Data Fields
void(* main_loop_run)(void)
void(* main_loop_quit)(void)
struct event_watch *(* add_watch)(int fd, enum event_watch_cond cond, struct callback *cb)
void(* remove_watch)(struct event_watch *ev)
struct event_timeout *(* add_timeout)(int timeout, int multi, struct callback *cb)
void(* remove_timeout)(struct event_timeout *ev)
struct event_idle *(* add_idle)(int priority, struct callback *cb)
void(* remove_idle)(struct event_idle *ev)
void(* call_callback)(struct callback_list *cb)
Field Documentation
add_idle
struct event_idle *(* event_methods::add_idle) (int priority, struct callback *cb)
Referenced by event_add_idle().
add_timeout
struct event_timeout *(* event_methods::add_timeout) (int timeout, int multi, struct callback *cb)
Referenced by event_add_timeout().
add_watch
struct event_watch *(* event_methods::add_watch) (int fd, enum event_watch_cond cond, struct callback *cb)
Referenced by event_add_watch().
call_callback
void(* event_methods::call_callback) (struct callback_list *cb)
Referenced by event_call_callback().
main_loop_quit
void(* event_methods::main_loop_quit) (void)
Referenced by event_main_loop_quit().
main_loop_run
void(* event_methods::main_loop_run) (void)
Referenced by event_main_loop_run(), and graphics_sdl_new().
remove_idle
void(* event_methods::remove_idle) (struct event_idle *ev)
Referenced by event_remove_idle().
remove_timeout
void(* event_methods::remove_timeout) (struct event_timeout *ev)
Referenced by event_remove_timeout().
remove_watch
void(* event_methods::remove_watch) (struct event_watch *ev)
Referenced by event_remove_watch().
The documentation for this struct was generated from the following file:
event.h