navit: SAHooks Struct Reference
SAHooks Struct Reference
#include <shapefil.h>
Data Fields
SAFile(* FOpen)(const char *filename, const char *access)
SAOffset(* FRead)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset(* FWrite)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
SAOffset(* FSeek)(SAFile file, SAOffset offset, int whence)
SAOffset(* FTell)(SAFile file)
int(* FFlush)(SAFile file)
int(* FClose)(SAFile file)
int(* Remove)(const char *filename)
void(* Error)(const char *message)
double(* Atof)(const char *str)
Field Documentation
double(* SAHooks::Atof)(const char *str)
Referenced by DBFReadAttribute(), and SASetupDefaultHooks().
void(* SAHooks::Error)(const char *message)
Referenced by DBFAddNativeFieldType(), DBFFlushRecord(), DBFLoadRecord(), SASetupDefaultHooks(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), SHPWriteHeader(), and SHPWriteObject().
int(* SAHooks::FClose)(SAFile file)
Referenced by DBFClose(), DBFCreateLL(), DBFOpenLL(), SASetupDefaultHooks(), SHPClose(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), and SHPWriteTreeLL().
int(* SAHooks::FFlush)(SAFile file)
Referenced by DBFUpdateHeader(), SASetupDefaultHooks(), and SHPWriteHeader().
SAFile(* SAHooks::FOpen)(const char *filename, const char *access)
Referenced by DBFCreateLL(), DBFOpenLL(), SASetupDefaultHooks(), SHPCreateLL(), SHPOpenLL(), SHPRestoreSHX(), and SHPWriteTreeLL().
SAOffset(* SAHooks::FRead)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFLoadRecord(), DBFOpenLL(), DBFReorderFields(), DBFUpdateHeader(), SASetupDefaultHooks(), SHPOpenLL(), and SHPRestoreSHX().
SAOffset(* SAHooks::FSeek)(SAFile file, SAOffset offset, int whence)
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFFlushRecord(), DBFLoadRecord(), DBFOpenLL(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteHeader(), SASetupDefaultHooks(), SHPOpenLL(), SHPRestoreSHX(), SHPWriteHeader(), and SHPWriteObject().
SAOffset(* SAHooks::FTell)(SAFile file)
Referenced by SASetupDefaultHooks(), and SHPOpenLL().
SAOffset(* SAHooks::FWrite)(void *p, SAOffset size, SAOffset nmemb, SAFile file)
Referenced by DBFAddNativeFieldType(), DBFAlterFieldDefn(), DBFCreateLL(), DBFFlushRecord(), DBFReorderFields(), DBFUpdateHeader(), DBFWriteHeader(), SASetupDefaultHooks(), SHPCreateLL(), SHPRestoreSHX(), SHPWriteHeader(), SHPWriteObject(), SHPWriteTreeLL(), and SHPWriteTreeNode().
int(* SAHooks::Remove)(const char *filename)
Referenced by DBFCreateLL(), and SASetupDefaultHooks().
The documentation for this struct was generated from the following file:
support/shapefile/shapefil.h