navit: osd_item_methods Struct Reference
osd_item_methods Struct Reference
#include <osd.h>
Data Fields
void(* draw)(struct osd_priv *osd, struct navit *navit, struct vehicle *v)
Field Documentation
void(* osd_item_methods::draw)(struct osd_priv *osd, struct navit *navit, struct vehicle *v)
Referenced by osd_button_new(), osd_cmd_interface_new(), osd_compass_new(), osd_gps_status_new(), osd_image_new(), osd_j1850_new(), osd_nav_next_turn_new(), osd_nav_toggle_announcer_new(), osd_navigation_status_new(), osd_odometer_new(), osd_route_guard_new(), osd_scale_new(), osd_speed_cam_new(), osd_speed_warner_new(), osd_std_calculate_sizes_and_redraw(), osd_stopwatch_new(), osd_text_new(), and osd_volume_new().
The documentation for this struct was generated from the following file:
osd.h