navit: graphics_gc_methods Struct Reference
graphics_gc_methods Struct Reference
#include <graphics.h>
Data Fields
void(* gc_destroy)(struct graphics_gc_priv *gc)
void(* gc_set_linewidth)(struct graphics_gc_priv *gc, int width)
void(* gc_set_dashes)(struct graphics_gc_priv *gc, int width, int offset, unsigned char dash_list[], int n)
void(* gc_set_foreground)(struct graphics_gc_priv *gc, struct color *c)
void(* gc_set_background)(struct graphics_gc_priv *gc, struct color *c)
void(* gc_set_texture)(struct graphics_gc_priv *gc, struct graphics_image_priv *img)
Field Documentation
gc_destroy
void(* graphics_gc_methods::gc_destroy) (struct graphics_gc_priv *gc)
Referenced by graphics_gc_destroy(), and svg_debug_gc_destroy().
gc_set_background
void(* graphics_gc_methods::gc_set_background) (struct graphics_gc_priv *gc, struct color *c)
Referenced by graphics_gc_set_background().
gc_set_dashes
void(* graphics_gc_methods::gc_set_dashes) (struct graphics_gc_priv *gc, int width, int offset, unsigned char dash_list[], int n)
Referenced by graphics_gc_set_dashes(), and svg_debug_gc_set_dashes().
gc_set_foreground
void(* graphics_gc_methods::gc_set_foreground) (struct graphics_gc_priv *gc, struct color *c)
Referenced by graphics_gc_set_foreground(), svg_debug_gc_set_background(), and svg_debug_gc_set_foreground().
gc_set_linewidth
void(* graphics_gc_methods::gc_set_linewidth) (struct graphics_gc_priv *gc, int width)
Referenced by graphics_gc_set_linewidth(), and svg_debug_gc_set_linewidth().
gc_set_texture
void(* graphics_gc_methods::gc_set_texture) (struct graphics_gc_priv *gc, struct graphics_image_priv *img)
Referenced by graphics_gc_has_texture(), and graphics_gc_set_texture().
The documentation for this struct was generated from the following file:
graphics.h