navit: graphics_methods Struct Reference
graphics_methods Struct Reference
#include <graphics.h>
Data Fields
void(* graphics_destroy)(struct graphics_priv *gr)
void(* draw_mode)(struct graphics_priv *gr, enum draw_mode_num mode)
void(* draw_lines)(struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
void(* draw_polygon)(struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
void(* draw_rectangle)(struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
void(* draw_circle)(struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
void(* draw_text)(struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
void(* draw_image)(struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
void(* draw_image_warp)(struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, int count, struct graphics_image_priv *img)
void(* draw_drag)(struct graphics_priv *gr, struct point *p)
struct graphics_font_priv *(* font_new)(struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
struct graphics_gc_priv *(* gc_new)(struct graphics_priv *gr, struct graphics_gc_methods *meth)
void(* background_gc)(struct graphics_priv *gr, struct graphics_gc_priv *gc)
struct graphics_priv *(* overlay_new)(struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
struct graphics_image_priv *(* image_new)(struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
Load an image from a file.
void *(* get_data)(struct graphics_priv *gr, const char *type)
void(* image_free)(struct graphics_priv *gr, struct graphics_image_priv *priv)
void(* get_text_bbox)(struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
void(* overlay_disable)(struct graphics_priv *gr, int disable)
void(* overlay_resize)(struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
int(* set_attr)(struct graphics_priv *gr, struct attr *attr)
int(* show_native_keyboard)(struct graphics_keyboard *kbd)
void(* hide_native_keyboard)(struct graphics_keyboard *kbd)
navit_float(* get_dpi)(struct graphics_priv *gr)
void(* draw_polygon_with_holes)(struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count, int hole_count, int *ccount, struct point **holes)
Field Documentation
background_gc
void(* graphics_methods::background_gc) (struct graphics_priv *gr, struct graphics_gc_priv *gc)
Referenced by graphics_background_gc(), graphics_svg_debug_new(), and svg_debug_background_gc().
draw_circle
void(* graphics_methods::draw_circle) (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int r)
Referenced by graphics_draw_circle(), graphics_svg_debug_new(), and svg_debug_draw_circle().
draw_drag
void(* graphics_methods::draw_drag) (struct graphics_priv *gr, struct point *p)
Referenced by graphics_draw_drag(), graphics_svg_debug_new(), and svg_debug_draw_drag().
draw_image
void(* graphics_methods::draw_image) (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, struct graphics_image_priv *img)
Referenced by graphics_draw_image(), graphics_svg_debug_new(), and svg_debug_draw_image().
draw_image_warp
void(* graphics_methods::draw_image_warp) (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct point *p, int count, struct graphics_image_priv *img)
Referenced by displayitem_draw_image(), graphics_draw_image_warp(), and graphics_svg_debug_new().
draw_lines
void(* graphics_methods::draw_lines) (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
Referenced by graphics_draw_lines(), graphics_svg_debug_new(), and svg_debug_draw_lines().
draw_mode
void(* graphics_methods::draw_mode) (struct graphics_priv *gr, enum draw_mode_num mode)
Referenced by graphics_draw_mode(), graphics_svg_debug_overlay_new(), and svg_debug_draw_mode().
draw_polygon
void(* graphics_methods::draw_polygon) (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count)
Referenced by graphics_draw_polygon(), graphics_svg_debug_new(), and svg_debug_draw_polygon().
draw_polygon_with_holes
void(* graphics_methods::draw_polygon_with_holes) (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int count, int hole_count, int *ccount, struct point **holes)
Referenced by graphics_draw_polygon_with_holes(), and graphics_svg_debug_new().
draw_rectangle
void(* graphics_methods::draw_rectangle) (struct graphics_priv *gr, struct graphics_gc_priv *gc, struct point *p, int w, int h)
Referenced by graphics_draw_rectangle(), graphics_svg_debug_new(), and svg_debug_draw_rectangle().
draw_text
void(* graphics_methods::draw_text) (struct graphics_priv *gr, struct graphics_gc_priv *fg, struct graphics_gc_priv *bg, struct graphics_font_priv *font, char *text, struct point *p, int dx, int dy)
Referenced by graphics_draw_text(), graphics_svg_debug_new(), and svg_debug_draw_text().
font_new
struct graphics_font_priv*(* graphics_methods::font_new) (struct graphics_priv *gr, struct graphics_font_methods *meth, char *font, int size, int flags)
Referenced by graphics_gd_new(), graphics_gtk_drawing_area_new_helper(), graphics_named_font_new(), graphics_opengl_new_helper(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_svg_debug_new(), overlay_new(), and svg_debug_font_new().
gc_new
struct graphics_gc_priv*(* graphics_methods::gc_new) (struct graphics_priv *gr, struct graphics_gc_methods *meth)
Referenced by graphics_gc_new(), graphics_svg_debug_new(), and svg_debug_gc_new().
get_data
void*(* graphics_methods::get_data) (struct graphics_priv *gr, const char *type)
Referenced by graphics_get_data(), graphics_svg_debug_disable_suspend(), graphics_svg_debug_fullscreen(), and svg_debug_get_data().
get_dpi
navit_float(* graphics_methods::get_dpi) (struct graphics_priv *gr)
Referenced by graphics_get_dpi(), and graphics_svg_debug_new().
get_text_bbox
void(* graphics_methods::get_text_bbox) (struct graphics_priv *gr, struct graphics_font_priv *font, char *text, int dx, int dy, struct point *ret, int estimate)
Referenced by graphics_gd_new(), graphics_get_text_bbox(), graphics_gtk_drawing_area_new_helper(), graphics_opengl_new_helper(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), graphics_svg_debug_new(), label_line(), overlay_new(), and svg_debug_get_text_bbox().
graphics_destroy
void(* graphics_methods::graphics_destroy) (struct graphics_priv *gr)
Referenced by graphics_free(), and graphics_svg_debug_new().
hide_native_keyboard
void(* graphics_methods::hide_native_keyboard) (struct graphics_keyboard *kbd)
Referenced by graphics_hide_native_keyboard(), and graphics_svg_debug_new().
image_free
void(* graphics_methods::image_free) (struct graphics_priv *gr, struct graphics_image_priv *priv)
Referenced by graphics_free(), graphics_svg_debug_new(), and svg_debug_image_free().
image_new
struct graphics_image_priv*(* graphics_methods::image_new) (struct graphics_priv *gr, struct graphics_image_methods *meth, char *path, int *w, int *h, struct point *hot, int rotation)
Load an image from a file.
Parameters
gr graphics object
meth output parameter for graphics methods object
path file name/path of image to load
w In: width to scale image to, or IMAGE_W_H_UNSET for original width. Out: Actual width of returned image.
h heigth; see w
hot output parameter for image hotspot
rotate angle to rotate the image, in 90 degree steps (not supported by all plugins).
Returns
pointer to allocated image, to be freed by image_free()
See also
image_free()
Referenced by graphics_svg_debug_new(), image_new_helper(), and svg_debug_image_new().
overlay_disable
void(* graphics_methods::overlay_disable) (struct graphics_priv *gr, int disable)
Referenced by graphics_overlay_disable(), and graphics_svg_debug_new().
overlay_new
struct graphics_priv*(* graphics_methods::overlay_new) (struct graphics_priv *gr, struct graphics_methods *meth, struct point *p, int w, int h, int wraparound)
Referenced by graphics_overlay_new(), and graphics_svg_debug_new().
overlay_resize
void(* graphics_methods::overlay_resize) (struct graphics_priv *gr, struct point *p, int w, int h, int wraparound)
Referenced by graphics_overlay_resize(), and graphics_svg_debug_new().
set_attr
int(* graphics_methods::set_attr) (struct graphics_priv *gr, struct attr *attr)
Referenced by graphics_set_attr(), and graphics_svg_debug_new().
show_native_keyboard
int(* graphics_methods::show_native_keyboard) (struct graphics_keyboard *kbd)
Referenced by graphics_show_native_keyboard(), and graphics_svg_debug_new().
The documentation for this struct was generated from the following file:
graphics.h