navit: callback Struct Reference
callback Struct Reference
Data Fields
void(* func)(void)
int pcount
enum attr_type type
void * p [0]
Detailed Description
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Field Documentation
void(* callback::func)(void)
Referenced by callback_call(), callback_list_add_new(), callback_new(), callback_new_args(), callback_new_attr(), and callback_new_attr_args().
void* callback::p[0]
Referenced by callback_call(), callback_new_attr(), and callback_set_arg().
int callback::pcount
Referenced by callback_call(), callback_new_attr(), and callback_set_arg().
enum attr_type callback::type
Referenced by callback_list_call_attr(), callback_new_attr(), event_sdl_watch_thread(), graphics_sdl_new(), and sdl_timer_callback().
The documentation for this struct was generated from the following file:
callback.c