navit: _ProtobufCService Struct Reference
_ProtobufCService Struct Reference
#include <protobuf-c.h>
Data Fields
const ProtobufCServiceDescriptor * descriptor
void(* invoke)(ProtobufCService *service, unsigned method_index, const ProtobufCMessage *input, ProtobufCClosure closure, void *closure_data)
void(* destroy)(ProtobufCService *service)
Field Documentation
const ProtobufCServiceDescriptor* _ProtobufCService::descriptor
Referenced by protobuf_c_service_generated_init().
void(* _ProtobufCService::destroy)(ProtobufCService *service)
Referenced by protobuf_c_service_destroy(), and protobuf_c_service_generated_init().
void(* _ProtobufCService::invoke)(ProtobufCService *service, unsigned method_index, const ProtobufCMessage *input, ProtobufCClosure closure, void *closure_data)
Referenced by protobuf_c_service_generated_init().
The documentation for this struct was generated from the following file:
maptool/google/protobuf-c/protobuf-c.h