navit: vehicle_methods Struct Reference
vehicle_methods Struct Reference
#include <vehicle.h>
Data Fields
void(* destroy)(struct vehicle_priv *priv)
int(* position_attr_get)(struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
int(* set_attr)(struct vehicle_priv *priv, struct attr *attr)
Field Documentation
void(* vehicle_methods::destroy)(struct vehicle_priv *priv)
Referenced by vehicle_destroy().
int(* vehicle_methods::position_attr_get)(struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Referenced by vehicle_get_attr(), vehicle_log_binfile(), vehicle_log_gpx(), vehicle_log_nmea(), and vehicle_log_textfile().
int(* vehicle_methods::set_attr)(struct vehicle_priv *priv, struct attr *attr)
Referenced by vehicle_set_attr().
The documentation for this struct was generated from the following file:
vehicle.h