navit: _ProtobufCBuffer Struct Reference
_ProtobufCBuffer Struct Reference
#include <protobuf-c.h>
Data Fields
void(* append)(ProtobufCBuffer *buffer, size_t len, const uint8_t *data)
Field Documentation
void(* _ProtobufCBuffer::append)(ProtobufCBuffer *buffer, size_t len, const uint8_t *data)
Referenced by pack_buffer_packed_payload(), repeated_field_pack_to_buffer(), required_field_pack_to_buffer(), and unknown_field_pack_to_buffer().
The documentation for this struct was generated from the following file:
maptool/google/protobuf-c/protobuf-c.h