navit: menu_methods Struct Reference
menu_methods Struct Reference
#include <menu.h>
Data Fields
struct menu_priv *(* add)(struct menu_priv *menu, struct menu_methods *meth, char *name, enum menu_type type, struct callback *cb)
void(* set_toggle)(struct menu_priv *menu, int active)
int(* get_toggle)(struct menu_priv *menu)
void(* popup)(struct menu_priv *menu)
Field Documentation
add
struct menu_priv*(* menu_methods::add) (struct menu_priv *menu, struct menu_methods *meth, char *name, enum menu_type type, struct callback *cb)
Referenced by menu_add().
get_toggle
int(* menu_methods::get_toggle) (struct menu_priv *menu)
popup
void(* menu_methods::popup) (struct menu_priv *menu)
Referenced by gui_gtk_ui_new(), and menu_popup().
set_toggle
void(* menu_methods::set_toggle) (struct menu_priv *menu, int active)
The documentation for this struct was generated from the following file:
menu.h