navit: sunriset.c File Reference
sunriset.c File Reference
#include <stdio.h>
#include <math.h>
#include "sunriset.h"
Macros
#define INV360 (1.0 / 360.0)
Functions
int __sunriset__ (int year, int month, int day, double lon, double lat, double altit, int upper_limb, double *trise, double *tset)
double __daylen__ (int year, int month, int day, double lon, double lat, double altit, int upper_limb)
void sunpos (double d, double *lon, double *r)
void sun_RA_dec (double d, double *RA, double *dec, double *r)
double revolution (double x)
double rev180 (double x)
double GMST0 (double d)
Macro Definition Documentation
INV360
#define INV360 (1.0 / 360.0)
Function Documentation
__daylen__()
double __daylen__ (int year, int month, int day, double lon, double lat, double altit, int upper_limb)
References acosd, cosd, days_since_2000_Jan_0, lat, sind, and sunpos().
__sunriset__()
int __sunriset__ (int year, int month, int day, double lon, double lat, double altit, int upper_limb, double * trise, double * tset)
References acosd, cosd, days_since_2000_Jan_0, GMST0(), lat, rev180(), revolution(), sind, and sun_RA_dec().
Referenced by navit_layout_switch().
GMST0()
double GMST0 (double d)
References revolution().
Referenced by __sunriset__().
rev180()
double rev180 (double x)
References INV360.
Referenced by __sunriset__().
revolution()
double revolution (double x)
References INV360.
Referenced by __sunriset__(), GMST0(), and sunpos().
sun_RA_dec()
void sun_RA_dec (double d, double * RA, double * dec, double * r)
References atan2d, cosd, sind, and sunpos().
Referenced by __sunriset__().
sunpos()
void sunpos (double d, double * lon, double * r)
References atan2d, cosd, M, RADEG, revolution(), and sind.
Referenced by __daylen__(), and sun_RA_dec().