navit: support/gettext_intl/log.c File Reference
log.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
static void print_escaped (FILE *stream, const char *str)
void _nl_log_untranslated (const char *logfilename, const char *domainname, const char *msgid1, const char *msgid2, int plural)
Function Documentation
void _nl_log_untranslated (const char * logfilename, const char * domainname, const char * msgid1, const char * msgid2, int plural)
References fprintf(), NULL, and print_escaped().
static void print_escaped (FILE * stream, const char * str) static
Referenced by _nl_log_untranslated().