navit: support/espeak/speak.c File Reference
speak.c File Reference
#include "StdAfx.h"
#include "speech.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <time.h>
#include <signal.h>
#include <locale.h>
#include <sys/stat.h>
#include "speak_lib.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Functions
void Write4Bytes (FILE *f, int value)
void DisplayVoices (FILE *f_out, char *language)
int GetFileLength (const char *filename)
char * Alloc (int size)
void Free (void *ptr)
static int OpenWaveFile (const char *path, int rate)
static void CloseWaveFile ()
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char *out_ptr)
static int WavegenFile (void)
static void init_path (char *argv0, char *path_specified)
static int initialise (void)
static void StopSpeak (int unused)
int main (int argc, char **argv)
Variables
char path_home [N_PATH_HOME]
char filetype [5]
char wavefile [200]
int(* uri_callback)(int, const char *, const char *) = NULL
int(* phoneme_callback)(const char *) = NULL
FILE * f_wave = NULL
int quiet = 0
unsigned int samples_total = 0
unsigned int samples_split = 0
unsigned int wavefile_count = 0
int end_of_sentence = 0
static const char * help_text
USHORT voice_pcnt [N_PEAKS+1][3]
Function Documentation
char* Alloc (int size)
References fprintf(), NULL, and p.
static void CloseWaveFile () static
References f_wave, NULL, startup::pos, SEEK_SET, and Write4Bytes().
Referenced by main(), and WavegenFile().
void DisplayVoices (FILE * f_out, char * language)
References espeak_VOICE::age, espeak_ListVoices(), fprintf(), espeak_VOICE::gender, genders, espeak_VOICE::identifier, espeak_VOICE::languages, espeak_VOICE::name, NULL, p, and sprintf().
Referenced by main().
void Free (void * ptr)
References NULL.
int GetFileLength (const char * filename)
References S_IFDIR, S_IFMT, stat::st_mode, stat::st_size, and stat().
static void init_path (char * argv0, char * path_specified) static
References access(), buf, getenv, GetFileLength(), NULL, p, PATH_ESPEAK_DATA, path_home, R_OK, size, and sprintf().
Referenced by main().
static int initialise (void) static
References exit, fprintf(), LoadConfig(), LoadPhData(), N_SPEECH_PARAM, NULL, param_defaults, param_stack, path_home, setlocale(), SetVoiceStack(), SynthesizeInit(), version_phdata, and WavegenInit().
Referenced by main().
int main (int argc, char ** argv)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References c, CloseWaveFile(), CompileDictionary(), dictionary_name, DisplayVoices(), DoVoiceChange(), EE_OK, espeakCAPITALS, espeakCHARS_8BIT, espeakCHARS_AUTO, espeakPITCH, espeakPUNCTUATION, espeakRATE, espeakVOLUME, espeakWORDGAP, exit, f_trans, filename, filetype, fprintf(), Generate(), getopt_long(), option::has_arg, help_text, init_path(), initialise(), InitText(), espeak_VOICE::languages, LoadVoice(), mbrola_name, n_phoneme_list, N_PUNCTLIST, name, no_argument, NULL, OpenWaveFile(), optarg, optind, option_capitals, option_endpause, option_linelength, option_multibyte, option_phoneme_input, option_phonemes, option_punctlist, option_punctuation, option_quiet, option_ssml, option_waveout, option_wordgap, optional_argument, p, path_home, phoneme_list, printf(), quiet, required_argument, samplerate, samples_split, SetParameter(), SetVoiceByName(), SetVoiceByProperties(), SpeakNextClause(), speed, strncpy0(), SynthOnTimer(), option::val, value, version_string, voice, wavefile, WavegenFile(), and WavegenInitSound().
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char * out_ptr)
References end_of_sentence.
static int OpenWaveFile (const char * path, int rate) static
References f_wave, NULL, and Write4Bytes().
Referenced by main(), and WavegenFile().
static void StopSpeak (int unused) static
References NULL, and SpeakNextClause().
static int WavegenFile (void) static
References CloseWaveFile(), end_of_sentence, f_wave, filetype, NULL, OpenWaveFile(), out_end, out_ptr, out_start, quiet, samplerate, samples_split, samples_total, sprintf(), wavefile, wavefile_count, and WavegenFill().
Referenced by main().
void Write4Bytes (FILE * f, int value)
Referenced by CloseWaveFile(), and OpenWaveFile().
Variable Documentation
int end_of_sentence = 0
Referenced by MarkerEvent(), and WavegenFile().
FILE* f_wave = NULL
char filetype[5]
Referenced by main(), and WavegenFile().
const char* help_text static
Referenced by main().
char path_home[N_PATH_HOME]
int(* phoneme_callback)(const char *) = NULL
int quiet = 0
Referenced by main(), and WavegenFile().
unsigned int samples_split = 0
Referenced by main(), and WavegenFile().
unsigned int samples_total = 0
Referenced by WavegenFile().
int(* uri_callback)(int, const char *, const char *) = NULL
USHORT voice_pcnt[N_PEAKS+1][3]
char wavefile[200]
Referenced by main(), and WavegenFile().
unsigned int wavefile_count = 0
Referenced by WavegenFile().