navit: support/espeak/event.h File Reference
event.h File Reference
#include "speak_lib.h"
Functions
void event_init (void)
void event_set_callback (t_espeak_callback *cb)
espeak_ERROR event_clear_all ()
espeak_ERROR event_declare (espeak_EVENT *event)
void event_terminate ()
Function Documentation
espeak_ERROR event_clear_all ()
Referenced by espeak_Cancel().
espeak_ERROR event_declare (espeak_EVENT * event)
void event_init (void)
Referenced by select_output().
void event_set_callback (t_espeak_callback * cb)
Referenced by espeak_SetSynthCallback().
void event_terminate ()
Referenced by espeak_Terminate().