navit: support/espeak/speech.h File Reference
speech.h File Reference
#include <sys/types.h>
Data Structures
struct MNEM_TAB
Macros
#define INCLUDE_KLATT
#define PATHSEP '/'
#define USE_NANOSLEEP
#define PATH_ESPEAK_DATA "/usr/share/espeak-data"
#define N_PATH_HOME 150
#define ESPEAK_API
Typedefs
typedef unsigned short USHORT
typedef unsigned char UCHAR
typedef double DOUBLEX
Functions
int LookupMnem (MNEM_TAB *table, char *string)
void strncpy0 (char *to, const char *from, int size)
int GetFileLength (const char *filename)
char * Alloc (int size)
void Free (void *ptr)
Variables
char path_home [N_PATH_HOME]
Macro Definition Documentation
#define ESPEAK_API
#define INCLUDE_KLATT
#define N_PATH_HOME 150
#define PATH_ESPEAK_DATA "/usr/share/espeak-data"
Referenced by init_path().
#define PATHSEP '/'
Referenced by CompileDictionary(), espeak_ListVoices(), ExtractVoiceVariantName(), GetVoices(), LoadConfig(), LoadDictionary(), LoadSoundFile(), LoadVoice(), ReadPhFile(), and SelectVoiceByName().
#define USE_NANOSLEEP
Typedef Documentation
typedef double DOUBLEX
typedef unsigned char UCHAR
typedef unsigned short USHORT
Function Documentation
char* Alloc (int size)
References fprintf(), g_malloc(), NULL, and p.
Referenced by LoadConfig(), LoadDictionary(), NewTranslator(), and ReadPhFile().
void Free (void * ptr)
References g_free(), and NULL.
Referenced by DeleteTranslator(), espeak_Terminate(), FreePhData(), LoadDictionary(), and ReadPhFile().
int GetFileLength (const char * filename)
References S_IFDIR, S_IFMT, stat::st_mode, stat::st_size, and stat().
Referenced by GetVoices(), init_path(), LoadDictionary(), LoadMbrolaTable(), LoadSoundFile(), LoadVoice(), main(), ReadPhFile(), and ReadVoiceFile().
int LookupMnem (MNEM_TAB * table, char * string)
References MNEM_TAB::mnem, NULL, and MNEM_TAB::value.
Referenced by compile_line(), LoadVoice(), ProcessSsmlTag(), ReadClause(), and ReadVoiceFile().
void strncpy0 (char * to, const char * from, int size)
References NULL.
Referenced by compile_line(), ExtractVoiceVariantName(), LoadVoice(), LoadVoiceVariant(), LookupDictList(), main(), ReadVoiceFile(), SelectVoice(), SetVoiceByName(), sync_espeak_Synth_Mark(), and TranslateWord().
Variable Documentation
char path_home[N_PATH_HOME]
Referenced by compile_dictlist_file(), CompileDictionary(), espeak_ListVoices(), espeak_new(), GetVoices(), init_path(), initialise(), LoadConfig(), LoadDictionary(), LoadMbrolaTable(), LoadSoundFile(), LoadVoice(), main(), ReadPhFile(), and ReadVoiceFile().