navit: support/espeak/synthesize.h File Reference
synthesize.h File Reference
Data Structures
struct frame_t
struct frame_t2
struct wavegen_peaks_t
struct WGEN_DATA
struct RESONATOR
struct SPECT_SEQ
struct SPECT_SEQK
struct frameref_t
struct PHONEME_LIST
struct SOUND_ICON
struct MBROLA_TAB
struct SPEED_FACTORS
Macros
#define N_PHONEME_LIST 1000
#define MAX_HARMONIC 400
#define N_SEQ_FRAMES 25
#define STEPSIZE 64
#define PITCHfall 0
#define PITCHrise 1
#define FRFLAG_KLATT 0x01
#define FRFLAG_VOWEL_CENTRE 0x02
#define FRFLAG_LEN_MOD 0x04
#define FRFLAG_BREAK_LF 0x08
#define FRFLAG_BREAK 0x10
#define FRFLAG_BREAK_2 0x18
#define FRFLAG_FORMANT_RATE 0x20
#define FRFLAG_MODULATE 0x40
#define FRFLAG_DEFER_WAV 0x80
#define FRFLAG_COPIED 0x8000
#define SFLAG_SEQCONTINUE 0x01
#define SFLAG_EMBEDDED 0x02
#define SFLAG_SYLLABLE 0x04
#define SFLAG_LENGTHEN 0x08
#define SFLAG_DICTIONARY 0x10
#define SFLAG_SWITCHED_LANG 0x20
#define SFLAG_PROMOTE_STRESS 0x40
#define EMBED_P 1
#define EMBED_S 2
#define EMBED_A 3
#define EMBED_R 4
#define EMBED_H 5
#define EMBED_T 6
#define EMBED_I 7
#define EMBED_S2 8
#define EMBED_Y 9
#define EMBED_M 10
#define EMBED_U 11
#define EMBED_B 12
#define EMBED_F 13
#define N_EMBEDDED_VALUES 14
#define N_PEAKS 9
#define N_MARKERS 8
#define N_KLATTP 10
#define N_KLATTP2 14
#define KLATT_AV 0
#define KLATT_FNZ 1
#define KLATT_Tilt 2
#define KLATT_Aspr 3
#define KLATT_Skew 4
#define KLATT_Kopen 5
#define KLATT_AVp 6
#define KLATT_Fric 7
#define KLATT_FricBP 8
#define KLATT_Turb 9
#define MAX_PITCH_VALUE 101
#define WCMD_KLATT 1
#define WCMD_KLATT2 2
#define WCMD_SPECT 3
#define WCMD_SPECT2 4
#define WCMD_PAUSE 5
#define WCMD_WAVE 6
#define WCMD_WAVE2 7
#define WCMD_AMPLITUDE 8
#define WCMD_PITCH 9
#define WCMD_MARKER 10
#define WCMD_VOICE 11
#define WCMD_EMBEDDED 12
#define N_WCMDQ 160
#define MIN_WCMDQ 22
#define N_SOUNDICON_TAB 80
#define N_SOUNDICON_SLOTS 4
Functions
int WcmdqFree ()
void WcmdqStop ()
int WcmdqUsed ()
void WcmdqInc ()
int WavegenOpenSound ()
int WavegenCloseSound ()
int WavegenInitSound ()
void WavegenInit (int rate, int wavemult_fact)
float polint (float xa[], float ya[], int n, float x)
int WavegenFill (int fill_zeros)
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char *out_ptr)
unsigned int LookupSound (PHONEME_TAB *ph1, PHONEME_TAB *ph2, int which, int *match_level, int control)
frameref_t * LookupSpect (PHONEME_TAB *ph1, PHONEME_TAB *prev_ph, PHONEME_TAB *next_ph, int which, int *match_level, int *n_frames, PHONEME_LIST *plist)
unsigned char * LookupEnvelope (int ix)
int LoadPhData ()
void SynthesizeInit (void)
int Generate (PHONEME_LIST *phoneme_list, int *n_ph, int resume)
void MakeWave2 (PHONEME_LIST *p, int n_ph)
int SynthOnTimer (void)
int SpeakNextClause (FILE *f_text, const void *text_in, int control)
int SynthStatus (void)
void SetSpeed (int control)
void SetEmbedded (int control, int value)
void SelectPhonemeTable (int number)
int SelectPhonemeTableName (const char *name)
void Write4Bytes (FILE *f, int value)
int Read4Bytes (FILE *f)
int CompileDictionary (const char *dsource, const char *dict_name, FILE *log, char *err_name, int flags)
espeak_ERROR SetVoiceByName (const char *name)
espeak_ERROR SetVoiceByProperties (espeak_VOICE *voice_selector)
espeak_ERROR LoadMbrolaTable (const char *mbrola_voice, const char *phtrans, int srate)
void SetParameter (int parameter, int value, int relative)
void MbrolaTranslate (PHONEME_LIST *plist, int n_phonemes, FILE *f_mbrola)
int DoSample (PHONEME_TAB *ph1, PHONEME_TAB *ph2, int which, int length_mod, int amp)
int DoSpect (PHONEME_TAB *this_ph, PHONEME_TAB *prev_ph, PHONEME_TAB *next_ph, int which, PHONEME_LIST *plist, int modulation)
int PauseLength (int pause, int control)
int LookupPhonemeTable (const char *name)
void InitBreath (void)
void KlattInit ()
int Wavegen_Klatt2 (int length, int modulation, int resume, frame_t *fr1, frame_t *fr2)
Variables
int embedded_value [N_EMBEDDED_VALUES]
int embedded_default [N_EMBEDDED_VALUES]
PHONEME_TAB * phoneme_tab [N_PHONEME_TAB]
int n_phoneme_list
PHONEME_LIST phoneme_list [N_PHONEME_LIST]
unsigned int embedded_list []
unsigned char env_fall [128]
unsigned char env_rise [128]
unsigned char env_frise [128]
unsigned char pitch_adjust_tab [MAX_PITCH_VALUE+1]
long wcmdq [N_WCMDQ][4]
int wcmdq_head
int wcmdq_tail
unsigned char * wavefile_data
int samplerate
int samplerate_native
int wavefile_ix
int wavefile_amp
int wavefile_ix2
int wavefile_amp2
int vowel_transition [4]
int vowel_transition0
int vowel_transition1
int mbrola_delay
char mbrola_name [20]
unsigned char * envelope_data [18]
int formant_rate []
SPEED_FACTORS speed
long count_samples
int outbuf_size
unsigned char * out_ptr
unsigned char * out_start
unsigned char * out_end
int event_list_ix
espeak_EVENT * event_list
t_espeak_callback * synth_callback
int option_log_frames
const char * version_string
const int version_phdata
int n_soundicon_tab
SOUND_ICON soundicon_tab [N_SOUNDICON_TAB]
Macro Definition Documentation
#define EMBED_A 3
Referenced by GetAmplitude(), SetEmbedded(), and SetParameter().
#define EMBED_B 12
Referenced by TranslateWord2().
#define EMBED_F 13
Referenced by EmbeddedCommand(), GetAmplitude(), SetEmbedded(), and TranslateWord2().
#define EMBED_H 5
Referenced by SetEmbedded(), and WavegenSetEcho().
#define EMBED_I 7
Referenced by DoEmbedded().
#define EMBED_M 10
Referenced by DoEmbedded().
#define EMBED_P 1
Referenced by SetEmbedded(), SetParameter(), SetPitch2(), and TranslateWord2().
#define EMBED_R 4
Referenced by SetParameter(), and SetPitch2().
#define EMBED_S 2
Referenced by DoEmbedded(), DoEmbedded2(), SetParameter(), and SetSpeed().
#define EMBED_S2 8
Referenced by DoEmbedded(), SetParameter(), and SetSpeed().
#define EMBED_T 6
Referenced by espeak_Cancel(), SetEmbedded(), SetPitch2(), SpeakNextClause(), and WavegenSetEcho().
#define EMBED_U 11
Referenced by DoEmbedded().
#define EMBED_Y 9
Referenced by EmbeddedCommand(), and TranslateWord2().
#define FRFLAG_BREAK 0x10
Referenced by DoSpect(), FormantTransition2(), LookupSpect(), and SmoothSpect().
#define FRFLAG_BREAK_2 0x18
#define FRFLAG_BREAK_LF 0x08
Referenced by DoSpect(), and SmoothSpect().
#define FRFLAG_COPIED 0x8000
Referenced by CopyFrame().
#define FRFLAG_DEFER_WAV 0x80
Referenced by DoSpect().
#define FRFLAG_FORMANT_RATE 0x20
Referenced by FormantTransition2(), and SmoothSpect().
#define FRFLAG_KLATT 0x01
Referenced by LookupSpect().
#define FRFLAG_LEN_MOD 0x04
Referenced by DoSpect(), and FormantTransition2().
#define FRFLAG_MODULATE 0x40
Referenced by DoSpect().
#define FRFLAG_VOWEL_CENTRE 0x02
Referenced by DoSpect(), and LookupSpect().
#define KLATT_Aspr 3
#define KLATT_AV 0
Referenced by FormantTransition2(), and set_frame_rms().
#define KLATT_AVp 6
#define KLATT_FNZ 1
#define KLATT_Fric 7
#define KLATT_FricBP 8
#define KLATT_Kopen 5
Referenced by LoadVoice().
#define KLATT_Skew 4
#define KLATT_Tilt 2
#define KLATT_Turb 9
#define MAX_HARMONIC 400
Referenced by PeaksToHarmspect().
#define MAX_PITCH_VALUE 101
Referenced by SetEmbedded(), and SetPitch2().
#define MIN_WCMDQ 22
Referenced by Generate().
#define N_EMBEDDED_VALUES 14
Referenced by SetEmbedded(), and WavegenInit().
#define N_KLATTP 10
#define N_KLATTP2 14
#define N_MARKERS 8
#define N_PEAKS 9
Referenced by ApplyBreath(), InitBreath(), LoadVoice(), PeaksToHarmspect(), SetBreath(), VoiceReset(), and Wavegen().
#define N_PHONEME_LIST 1000
Referenced by CalcPitches(), MakePhonemeList(), SubstitutePhonemes(), TranslateClause(), and TranslateWord2().
#define N_SEQ_FRAMES 25
Referenced by LookupSpect().
#define N_SOUNDICON_SLOTS 4
Referenced by LoadConfig(), LoadSoundFile2(), and LookupSoundicon().
#define N_SOUNDICON_TAB 80
#define N_WCMDQ 160
Referenced by SetSynth(), SmoothSpect(), WcmdqFree(), WcmdqInc(), WcmdqIncHead(), and WcmdqUsed().
#define PITCHfall 0
#define PITCHrise 1
#define SFLAG_DICTIONARY 0x10
Referenced by MakePhonemeList(), SubstitutePhonemes(), and TranslateWord2().
#define SFLAG_EMBEDDED 0x02
Referenced by CalcLengths(), Generate(), MakePhonemeList(), MbrolaTranslate(), TranslateClause(), and TranslateWord2().
#define SFLAG_LENGTHEN 0x08
Referenced by CalcLengths(), Generate(), GetMbrName(), GetTranslatedPhonemeString(), LookupSpect(), MakePhonemeList(), MbrolaTranslate(), and TranslateWord2().
#define SFLAG_PROMOTE_STRESS 0x40
Referenced by MakePhonemeList(), and TranslateWord2().
#define SFLAG_SEQCONTINUE 0x01
Referenced by CalcLengths(), and Generate().
#define SFLAG_SWITCHED_LANG 0x20
Referenced by MakePhonemeList().
#define SFLAG_SYLLABLE 0x04
Referenced by CalcLengths(), CalcPitches(), CalcPitches_Tone(), GetTranslatedPhonemeString(), MakePhonemeList(), and TranslateWord2().
#define STEPSIZE 64
Referenced by SetAmplitude(), SetPitch(), and SetSynth().
#define WCMD_AMPLITUDE 8
Referenced by DoAmplitude(), and WavegenFill().
#define WCMD_EMBEDDED 12
Referenced by DoEmbedded(), and WavegenFill().
#define WCMD_KLATT 1
Referenced by DoSpect(), and WavegenFill().
#define WCMD_KLATT2 2
Referenced by DoSpect(), and WavegenFill().
#define WCMD_MARKER 10
Referenced by DoMarker(), and WavegenFill().
#define WCMD_PAUSE 5
Referenced by DoPause(), SetSynth(), SmoothSpect(), and WavegenFill().
#define WCMD_PITCH 9
Referenced by DoPitch(), and WavegenFill().
#define WCMD_SPECT 3
Referenced by DoSpect(), SetSynth(), and WavegenFill().
#define WCMD_SPECT2 4
Referenced by DoSpect(), SmoothSpect(), and WavegenFill().
#define WCMD_VOICE 11
Referenced by DoVoiceChange(), and WavegenFill().
#define WCMD_WAVE 6
Referenced by DoEmbedded(), DoSample2(), SetSynth(), SmoothSpect(), and WavegenFill().
#define WCMD_WAVE2 7
Referenced by DoSample2(), and WavegenFill().
Function Documentation
int CompileDictionary (const char * dsource, const char * dict_name, FILE * log, char * err_name, int flags)
References compile_dictlist_end(), compile_dictlist_file(), compile_dictlist_start(), compile_dictrules(), debug_flag, error_count, f_log, fopen_log(), fprintf(), Translator::langopts, letterGroupsDefined, LANGUAGE_OPTIONS::listx, LoadDictionary(), N_HASH_DICT, NULL, path_home, PATHSEP, phoneme_tab_list, phoneme_tab_number, SEEK_SET, sprintf(), translator, transpose_max, transpose_min, transpose_offset, value, and Write4Bytes().
Referenced by espeak_CompileDictionary(), and main().
int DoSample (PHONEME_TAB * ph1, PHONEME_TAB * ph2, int which, int length_mod, int amp)
References DoSample2(), EndPitch(), LookupSound(), NULL, and wavefile_amp.
Referenced by Generate(), and MbrolaTranslate().
int DoSpect (PHONEME_TAB * this_ph, PHONEME_TAB * prev_ph, PHONEME_TAB * next_ph, int which, PHONEME_LIST * plist, int modulation)
References amp_length, CopyFrame(), DoSample2(), frame_t::ffreq, frame_t::fheight, frameref_t::frame, FRFLAG_BREAK, FRFLAG_BREAK_LF, FRFLAG_DEFER_WAV, FRFLAG_LEN_MOD, FRFLAG_MODULATE, FRFLAG_VOWEL_CENTRE, frame_t::frflags, voice_t::klattv, Translator::langopts, last_wcmdq, frame_t::length, frameref_t::length, PHONEME_LIST::length, long, LookupSpect(), LOPT_SONORANT_MIN, modn_flags, NULL, LANGUAGE_OPTIONS::param, phLIQUID, phNASAL, phVOWEL, pitch_length, samplerate, seq_len_adjust, SmoothSpect(), SPEED_FACTORS::speed_factor3, syllable_centre, translator, PHONEME_TAB::type, voice, wavefile_amp, wavefile_ix, WCMD_KLATT, WCMD_KLATT2, WCMD_SPECT, WCMD_SPECT2, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by Generate(), and MbrolaTranslate().
int Generate (PHONEME_LIST * phoneme_list, int * n_ph, int resume)
References PHONEME_TAB::after, PHONEME_LIST::amp, amp_length, clause_start_char, clause_start_word, count_characters, count_sentences, DoAmplitude(), DoEmbedded(), DoMarker(), DoPause(), DoPitch(), DoSample(), DoSpect(), embedded_ix, EndAmplitude(), EndPitch(), PHONEME_LIST::env, envelope_data, espeakEVENT_END, espeakEVENT_PHONEME, espeakEVENT_SENTENCE, espeakEVENT_WORD, Translator::langopts, last_pitch_cmd, last_wcmdq, PHONEME_LIST::length, LookupEnvelope(), LOPT_WORD_MERGE, mbrola_name, MIN_WCMDQ, PHONEME_TAB::mnemonic, PHONEME_LIST::newword, next, NULL, option_phoneme_events, option_quiet, p, LANGUAGE_OPTIONS::param, PHONEME_LIST::ph, PHONEME_TAB::phflags, phFRICATIVE, phLIQUID, phNASAL, phoneme_tab, phonPAUSE, phonSCHWA, phonSONORANT, phPAUSE, phSTOP, phTRILL, phVFRICATIVE, phVOWEL, phVOWEL2, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, pitch_length, PHONEME_LIST::prepause, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_SEQCONTINUE, PHONEME_LIST::sourceix, PHONEME_TAB::spect, StartSyllable(), PHONEME_LIST::stresslevel, syllable_centre, syllable_end, syllable_start, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, translator, PHONEME_LIST::type, vowel_transition, vowel_transition0, vowel_transition1, wcmdq_tail, and WcmdqFree().
Referenced by fill_buffer(), main(), SpeakNextClause(), Synthesize(), and SynthOnTimer().
void InitBreath (void)
References minus_pi_t, N_PEAKS, PI, samplerate, setresonator(), and two_pi_t.
Referenced by VoiceReset().
void KlattInit ()
Referenced by WavegenInit().
espeak_ERROR LoadMbrolaTable (const char * mbrola_voice, const char * phtrans, int srate)
References EE_INTERNAL_ERROR, EE_NOT_FOUND, EE_OK, espeakVOICETYPE, FALSE, GetFileLength(), mbrolib_parameter::ignore_error, mbrola_delay, mbrola_name, mbrolib_get_parameter(), mbrolib_init(), MBROLIB_OK, mbrolib_set_parameter(), mbrolib_set_voice(), NULL, option_quiet, path_home, Read4Bytes(), samplerate, samplerate_native, SetParameter(), size, sprintf(), and mbrolib_parameter::volume_ratio.
Referenced by LoadVoice(), and VoiceReset().
int LoadPhData ()
References PHONEME_TAB_LIST::includes, N_PHONEME_TAB_NAME, n_phoneme_tables, PHONEME_TAB_LIST::n_phonemes, name, NULL, p, phoneme_index, phoneme_tab_data, phoneme_tab_number, PHONEME_TAB_LIST::phoneme_tab_ptr, ReadPhFile(), spects_data, version, version_phdata, and wavefile_data.
Referenced by initialise().
unsigned char* LookupEnvelope (int ix)
References NULL, phoneme_index, and spects_data.
Referenced by CalcLengths(), and Generate().
int LookupPhonemeTable (const char * name)
References n_phoneme_tables, and phoneme_tab_number.
Referenced by SelectPhonemeTableName(), and TranslateWord2().
unsigned int LookupSound (PHONEME_TAB * ph1, PHONEME_TAB * ph2, int which, int * match_level, int control)
References PHONEME_TAB::after, PHONEME_TAB::before, PHONEME_TAB::code, PHONEME_TAB::end_type, level, LookupSound2(), NULL, phonPAUSE, phonPAUSE_SHORT, phPAUSE, seq_len_adjust, PHONEME_TAB::spect, PHONEME_TAB::start_type, type, vowel_transition, wavefile_amp, and wavefile_ix.
Referenced by DoSample(), and LookupSpect().
frameref_t* LookupSpect (PHONEME_TAB * ph1, PHONEME_TAB * prev_ph, PHONEME_TAB * next_ph, int which, int * match_level, int * n_frames, PHONEME_LIST * plist)
References FormantTransition2(), SPECT_SEQ::frame, SPECT_SEQK::frame, frameref_t::frame, FRFLAG_BREAK, FRFLAG_KLATT, FRFLAG_VOWEL_CENTRE, frame_t::frflags, frame_t2::frflags, frameref_t::frflags, length, frame_t::length, frameref_t::length, LookupSound(), SPECT_SEQ::n_frames, N_SEQ_FRAMES, NULL, PHONEME_LIST::ph, PHONEME_TAB::phflags, phNASAL, phonLENGTHEN, phVOWEL, phVOWEL2, seq_len_adjust, SFLAG_LENGTHEN, spects_data, PHONEME_TAB::std_length, PHONEME_LIST::synthflags, PHONEME_TAB::type, vowel_transition, vowel_transition0, vowel_transition1, and wavefile_ix.
Referenced by DoSpect().
void MakeWave2 (PHONEME_LIST * p, int n_ph)
void MarkerEvent (int type, unsigned int char_position, int value, unsigned char * out_ptr)
References espeak_EVENT::audio_position, count_samples, double, end_of_sentence, ENTER, ep, espeakEVENT_MARK, espeakEVENT_PLAY, event_list_ix, espeak_EVENT::id, int, espeak_EVENT::length, mbrola_delay, my_unique_identifier, my_user_data, n_event_list, espeak_EVENT::name, namedata, NULL, espeak_EVENT::number, out_start, espeak_EVENT::sample, samplerate, SHOW, espeak_EVENT::text_position, time(), espeak_EVENT::type, espeak_EVENT::unique_identifier, espeak_EVENT::user_data, and value.
Referenced by WavegenFill().
void MbrolaTranslate (PHONEME_LIST * plist, int n_phonemes, FILE * f_mbrola)
References buf, clause_start_char, clause_start_word, count_sentences, DoSample(), DoSpect(), embedded_ix, PHONEME_LIST::env, espeakEVENT_PHONEME, espeakEVENT_SENTENCE, espeakEVENT_WORD, event_list_ix, GetMbrName(), PHONEME_LIST::length, PHONEME_TAB::mnemonic, name, PHONEME_LIST::newword, next, NULL, out_ptr, outbuf, p, PauseLength(), PHONEME_LIST::ph, phFRICATIVE, phLIQUID, phNASAL, phoneme_tab, phonLENGTHEN, phonPAUSE, phPAUSE, phSTOP, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PHONEME_LIST::prepause, samplerate, SFLAG_EMBEDDED, SFLAG_LENGTHEN, PHONEME_LIST::sourceix, speed, SPEED_FACTORS::speed_factor1, SPEED_FACTORS::speed_factor2, sprintf(), PHONEME_TAB::std_length, PHONEME_LIST::synthflags, PHONEME_TAB::type, PHONEME_LIST::type, WordToString(), and WritePitch().
Referenced by SpeakNextClause().
int PauseLength (int pause, int control)
References SPEED_FACTORS::speed_factor1, and SPEED_FACTORS::speed_factor2.
Referenced by DoPause(), and MbrolaTranslate().
float polint (float xa[], float ya[], int n, float x)
Referenced by WavegenInitPkData().
int Read4Bytes (FILE * f)
References c.
Referenced by LoadSoundFile().
void SelectPhonemeTable (int number)
References current_phoneme_table, n_phoneme_tab, and SetUpPhonemeTable().
Referenced by LookupCharName(), LookupLetter(), MakePhonemeList(), SelectPhonemeTableName(), SetTranslator2(), SpeakNextClause(), TranslateLetter(), and TranslateWord2().
int SelectPhonemeTableName (const char * name)
References LookupPhonemeTable(), and SelectPhonemeTable().
Referenced by LoadVoice(), and SetTranslator2().
void SetEmbedded (int control, int value)
References command(), EMBED_A, EMBED_F, EMBED_H, EMBED_P, EMBED_T, embedded_max, embedded_value, voice_t::freq, voice_t::freq2, general_amplitude, GetAmplitude(), voice_t::height, voice_t::height2, MAX_PITCH_VALUE, N_EMBEDDED_VALUES, SetWithRange0(), value, and WavegenSetEcho().
Referenced by DoEmbedded(), DoEmbedded2(), and WavegenFill().
void SetParameter (int parameter, int value, int relative)
References EMBED_A, EMBED_P, EMBED_R, EMBED_S, EMBED_S2, embedded_value, espeakINTONATION, espeakLINELENGTH, espeakPITCH, espeakRANGE, espeakRATE, espeakVOLUME, espeakWORDGAP, GetAmplitude(), LANGUAGE_OPTIONS::intonation_group, Translator::langopts, option_linelength, option_tone_flags, option_wordgap, param_defaults, param_stack, PARAM_STACK::parameter, SetSpeed(), translator, and value.
void SetSpeed (int control)
References EMBED_S, EMBED_S2, embedded_value, SPEED_FACTORS::fast_settings, faster, SPEED_FACTORS::min_sample_len, s1, speed, speed1, speed2, speed3, SPEED_FACTORS::speed_factor1, SPEED_FACTORS::speed_factor2, SPEED_FACTORS::speed_factor3, speed_lookup, voice_t::speedf1, voice_t::speedf2, voice_t::speedf3, and voice.
Referenced by DoEmbedded(), DoEmbedded2(), LoadVoice(), and SetParameter().
espeak_ERROR SetVoiceByName (const char * name)
References buf, DoVoiceChange(), EE_INTERNAL_ERROR, EE_OK, espeak_ListVoices(), ExtractVoiceVariantName(), espeak_VOICE::identifier, LoadVoice(), n_voices_list, espeak_VOICE::name, NULL, SelectVoiceByName(), SetVoiceStack(), and strncpy0().
espeak_ERROR SetVoiceByProperties (espeak_VOICE * voice_selector)
References DoVoiceChange(), EE_NOT_FOUND, EE_OK, LoadVoiceVariant(), SelectVoice(), and SetVoiceStack().
int SpeakNextClause (FILE * f_text, const void * text_in, int control)
References CalcLengths(), CalcPitches(), current_phoneme_table, DoVoiceChange(), EMBED_T, embedded_value, f_trans, fprintf(), Generate(), GetTranslatedPhonemeString(), LoadVoiceVariant(), mbrola_name, MbrolaTranslate(), n_phoneme_list, NULL, option_phonemes, paused, Translator::phon_out, phoneme_callback, voice_t::phoneme_tab_ix, SelectPhonemeTable(), skipping_text, timer_on, TranslateClause(), translator, voice, WavegenOpenSound(), and WcmdqStop().
Referenced by fill_buffer(), main(), start_speaking(), StopSpeak(), Synthesize(), and SynthOnTimer().
void SynthesizeInit (void)
References last_amp_cmd, last_pitch_cmd, PHONEME_LIST::newword, NULL, phPAUSE, syllable_centre, and PHONEME_LIST::type.
Referenced by initialise().
int SynthOnTimer (void)
References Generate(), n_phoneme_list, NULL, skipping_text, SpeakNextClause(), timer_on, WavegenCloseSound(), WavegenOpenSound(), and WcmdqUsed().
Referenced by main(), and Synthesize().
int SynthStatus (void)
References paused, and timer_on.
int Wavegen_Klatt2 (int length, int modulation, int resume, frame_t * fr1, frame_t * fr2)
Referenced by WavegenFill().
int WavegenCloseSound ()
Referenced by SynthOnTimer().
int WavegenFill (int fill_zeros)
References current_source_index, echo_length, length, MarkerEvent(), mbrola_name, WGEN_DATA::mix_wave_amp, WGEN_DATA::mix_wave_scale, WGEN_DATA::mix_wavefile, WGEN_DATA::mix_wavefile_ix, WGEN_DATA::n_mix_wavefile, out_end, out_ptr, PlaySilence(), PlayWave(), WGEN_DATA::prev_was_synth, SetAmplitude(), SetEmbedded(), SetPitch(), Wavegen2(), Wavegen_Klatt2(), WavegenSetVoice(), WCMD_AMPLITUDE, WCMD_EMBEDDED, WCMD_KLATT, WCMD_KLATT2, WCMD_MARKER, WCMD_PAUSE, WCMD_PITCH, WCMD_SPECT, WCMD_SPECT2, WCMD_VOICE, WCMD_WAVE, WCMD_WAVE2, wcmdq, wcmdq_head, WcmdqIncHead(), and WcmdqUsed().
Referenced by Synthesize(), wave_out(), and WavegenFile().
void WavegenInit (int rate, int wavemult_fact)
References WGEN_DATA::amplitude, embedded_default, embedded_value, Flutter_inc, int, KlattInit(), max_hval, N_EMBEDDED_VALUES, N_WAVEMULT, nsamples, NULL, PHASE_INC_FACTOR, PI2, pk_shape2, WGEN_DATA::prev_was_synth, samplecount, samplerate, samplerate_native, WavegenInitPkData(), wavemult, wavemult_max, wavemult_offset, and wavephase.
Referenced by initialise().
int WavegenInitSound ()
Referenced by main(), and select_output().
int WavegenOpenSound ()
Referenced by SpeakNextClause(), and SynthOnTimer().
int WcmdqFree ()
References i, N_WCMDQ, wcmdq_head, and wcmdq_tail.
Referenced by Generate(), and WcmdqUsed().
void WcmdqInc ()
References N_WCMDQ, and wcmdq_tail.
Referenced by DoAmplitude(), DoEmbedded(), DoMarker(), DoPause(), DoPitch(), DoSample2(), DoSpect(), and DoVoiceChange().
void WcmdqStop ()
References Pa_AbortStream(), wcmdq_head, and wcmdq_tail.
Referenced by SpeakNextClause().
int WcmdqUsed ()
References N_WCMDQ, and WcmdqFree().
Referenced by Synthesize(), SynthOnTimer(), and WavegenFill().
void Write4Bytes (FILE * f, int value)
Variable Documentation
long count_samples
Referenced by MarkerEvent(), and Synthesize().
int embedded_default[N_EMBEDDED_VALUES]
Referenced by EmbeddedCommand(), and WavegenInit().
unsigned int embedded_list[]
Referenced by DoEmbedded(), DoEmbedded2(), EmbeddedCommand(), TranslateClause(), and TranslateWord2().
int embedded_value[N_EMBEDDED_VALUES]
Referenced by espeak_Cancel(), GetAmplitude(), SetEmbedded(), SetParameter(), SetPitch2(), SetSpeed(), SpeakNextClause(), WavegenInit(), and WavegenSetEcho().
unsigned char env_fall[128]
Referenced by SetPitch().
unsigned char env_frise[128]
unsigned char env_rise[128]
unsigned char* envelope_data[18]
Referenced by CalcLengths(), DoPitch(), Generate(), and WritePitch().
espeak_EVENT* event_list
int event_list_ix
Referenced by MarkerEvent(), MbrolaTranslate(), and Synthesize().
int formant_rate[]
Referenced by SmoothSpect(), and VoiceReset().
int mbrola_delay
Referenced by LoadMbrolaTable(), and MarkerEvent().
char mbrola_name[20]
Referenced by Generate(), LoadMbrolaTable(), main(), SpeakNextClause(), and WavegenFill().
int n_phoneme_list
Referenced by CalcLengths(), CalcPitches(), CalcPitches_Tone(), fill_buffer(), GetTranslatedPhonemeString(), main(), MakePhonemeList(), SpeakNextClause(), Synthesize(), SynthOnTimer(), and TranslateClause().
int n_soundicon_tab
Referenced by DoEmbedded(), LoadConfig(), LoadSoundFile2(), and LookupSoundicon().
int option_log_frames
Referenced by SetPitch(), and SetSynth().
unsigned char* out_end
Referenced by PlaySilence(), PlayWave(), Synthesize(), wave_out(), Wavegen(), WavegenFile(), and WavegenFill().
unsigned char* out_ptr
Referenced by MbrolaTranslate(), PlaySilence(), PlayWave(), Synthesize(), wave_out(), Wavegen(), WavegenFile(), and WavegenFill().
unsigned char* out_start
Referenced by espeak_Initialize(), MarkerEvent(), wave_out(), and WavegenFile().
int outbuf_size
Referenced by espeak_Initialize(), and Synthesize().
PHONEME_LIST phoneme_list[N_PHONEME_LIST]
Referenced by CalcLengths(), CalcPitches(), CalcPitches_Tone(), fill_buffer(), GetTranslatedPhonemeString(), main(), MakePhonemeList(), Synthesize(), and TranslateClause().
PHONEME_TAB* phoneme_tab[N_PHONEME_TAB]
unsigned char pitch_adjust_tab[MAX_PITCH_VALUE+1]
Referenced by SetPitch2().
int samplerate
Referenced by DoPause(), DoSample2(), DoSpect(), espeak_Initialize(), InitBreath(), LoadMbrolaTable(), LoadSoundFile(), main(), MarkerEvent(), MbrolaTranslate(), SynthCallback(), VoiceReset(), WavegenFile(), WavegenInit(), and WavegenSetEcho().
int samplerate_native
Referenced by LoadMbrolaTable(), and WavegenInit().
SOUND_ICON soundicon_tab[N_SOUNDICON_TAB]
Referenced by LoadConfig(), LoadSoundFile(), LoadSoundFile2(), and LookupSoundicon().
SPEED_FACTORS speed
Referenced by ch_generate_ddsg(), getSpeed(), LoadVoice(), main(), MbrolaTranslate(), osd_speed_cam_draw(), ProcessSsmlTag(), roadprofile_set_attr_do(), route_seg_speed(), route_time_seg(), rp_attr_get(), setEdge(), SetSpeed(), tracking_update(), vehicle_draw(), vehicle_draw_do(), vehicle_get_cursor_data(), vehicle_gpsd_dbus_filter(), vehicle_iphone_new(), and VoiceReset().
t_espeak_callback* synth_callback
Referenced by espeak_SetSynthCallback(), and Synthesize().
const int version_phdata
Referenced by initialise(), and LoadPhData().
const char* version_string
Referenced by espeak_Info(), and main().
int vowel_transition[4]
Referenced by EndPitch(), Generate(), LookupSound(), LookupSound2(), and LookupSpect().
int vowel_transition0
Referenced by Generate(), and LookupSpect().
int vowel_transition1
Referenced by Generate(), and LookupSpect().
int wavefile_amp
Referenced by DoSample(), DoSpect(), LookupSound(), and LookupSound2().
int wavefile_amp2
unsigned char* wavefile_data
Referenced by DoSample2(), and LoadPhData().
int wavefile_ix
Referenced by DoSpect(), LookupSound(), LookupSound2(), and LookupSpect().
int wavefile_ix2
long wcmdq[N_WCMDQ][4]
Referenced by DoAmplitude(), DoEmbedded(), DoMarker(), DoPause(), DoPitch(), DoSample2(), DoSpect(), DoVoiceChange(), EndAmplitude(), EndPitch(), SetSynth(), SmoothSpect(), and WavegenFill().
int wcmdq_head
Referenced by SetSynth(), WavegenFill(), WcmdqFree(), WcmdqIncHead(), and WcmdqStop().
int wcmdq_tail
Referenced by DoAmplitude(), DoEmbedded(), DoMarker(), DoPause(), DoPitch(), DoSample2(), DoSpect(), DoVoiceChange(), EndPitch(), Generate(), SetSynth(), StartSyllable(), WcmdqFree(), WcmdqInc(), and WcmdqStop().