navit: support/espeak/synthesize.c File Reference
synthesize.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <wctype.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Macros
#define RMS_GLOTTAL1 35
#define RMS_START 28
#define VOWEL_FRONT_LENGTH 50
#define long(x) ((long)(x))
#define N_FRAME_POOL N_WCMDQ
#define N_VCOLOUR 2
Functions
static void SmoothSpect (void)
const char * WordToString (unsigned int word)
void SynthesizeInit ()
static void EndAmplitude (void)
static void EndPitch (int voice_break)
static void DoAmplitude (int amp, unsigned char *amp_env)
static void DoPitch (unsigned char *env, int pitch1, int pitch2)
int PauseLength (int pause, int control)
static void DoPause (int length, int control)
static int DoSample2 (int index, int which, int length_mod, int amp)
int DoSample (PHONEME_TAB *ph1, PHONEME_TAB *ph2, int which, int length_mod, int amp)
static frame_t * AllocFrame ()
static void set_frame_rms (frame_t *fr, int new_rms)
static void formants_reduce_hf (frame_t *fr, int level)
static frame_t * CopyFrame (frame_t *frame1, int copy)
static frame_t * DuplicateLastFrame (frameref_t *seq, int n_frames, int length)
static void AdjustFormants (frame_t *fr, int target, int min, int max, int f1_adj, int f3_adj, int hf_reduce, int flags)
static int VowelCloseness (frame_t *fr)
int FormantTransition2 (frameref_t *seq, int *n_frames, unsigned int data1, unsigned int data2, PHONEME_TAB *other_ph, int which)
static void StartSyllable (void)
int DoSpect (PHONEME_TAB *this_ph, PHONEME_TAB *prev_ph, PHONEME_TAB *next_ph, int which, PHONEME_LIST *plist, int modulation)
static void DoMarker (int type, int char_posn, int length, int value)
void DoVoiceChange (voice_t *v)
static void DoEmbedded (int *embix, int sourceix)
int Generate (PHONEME_LIST *phoneme_list, int *n_ph, int resume)
int SynthOnTimer ()
int SynthStatus ()
int SpeakNextClause (FILE *f_in, const void *text_in, int control)
Variables
FILE * f_log
int n_phoneme_list =0
PHONEME_LIST phoneme_list [N_PHONEME_LIST]
int mbrola_delay
char mbrola_name [20]
SPEED_FACTORS speed
static int last_pitch_cmd
static int last_amp_cmd
static frame_t * last_frame
static int last_wcmdq
static int pitch_length
static int amp_length
static int modn_flags
static int syllable_start
static int syllable_end
static int syllable_centre
static voice_t * new_voice =NULL
int n_soundicon_tab =N_SOUNDICON_SLOTS
SOUND_ICON soundicon_tab [N_SOUNDICON_TAB]
static PHONEME_LIST next_pause
int seq_len_adjust
static int timer_on = 0
static int paused = 0
Macro Definition Documentation
#define long (x) ((long)(x))
Referenced by __FILETIME_to_ll(), CreateBitmapFromXpm(), DoAmplitude(), DoEmbedded(), DoPitch(), DoSample2(), DoSpect(), DoVoiceChange(), event_qt5_add_timeout(), file_create(), geom_poly_area(), get_sval(), get_uval(), org.navitproject.navit.FileBrowserActivity::getFreeSpace(), gui_internal_gesture_ring_add(), inflate_fast(), item_id_from_ptr(), j1850_idle(), Java_org_navitproject_navit_NavitAddressSearchActivity_CallbackStartAddressSearch(), main(), maptool_load_node_table(), mmap_readonly_win32(), node_buffer_to_hash(), png2pnm(), png_64bit_product(), PRINTF_PARSE(), process_boundaries_member(), process_turn_restrictions_member(), progress_memory(), protobuf_c_message_unpack(), SmoothSpect(), qt5_navit_timer::timerEvent(), transform_project_onto_view_plane(), and Wavegen().
#define N_FRAME_POOL N_WCMDQ
Referenced by AllocFrame().
#define N_VCOLOUR 2
Referenced by FormantTransition2().
#define RMS_GLOTTAL1 35
Referenced by FormantTransition2().
#define RMS_START 28
Referenced by FormantTransition2().
#define VOWEL_FRONT_LENGTH 50
Referenced by FormantTransition2().
Function Documentation
static void AdjustFormants (frame_t * fr, int target, int min, int max, int f1_adj, int f3_adj, int hf_reduce, int flags) static
References frame_t::ffreq, voice_t::formant_factor, formants_reduce_hf(), max, and voice.
Referenced by FormantTransition2().
static frame_t* AllocFrame () static
References N_FRAME_POOL.
Referenced by CopyFrame().
static frame_t* CopyFrame (frame_t * frame1, int copy) static
References AllocFrame(), FRFLAG_COPIED, frame_t::frflags, frame_t::length, and NULL.
Referenced by DoSpect(), DuplicateLastFrame(), FormantTransition2(), and SmoothSpect().
static void DoAmplitude (int amp, unsigned char * amp_env) static
References amp_length, last_amp_cmd, long, WCMD_AMPLITUDE, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by Generate().
static void DoEmbedded (int * embix, int sourceix) static
References clause_start_char, command(), count_characters, data, DoMarker(), DoPause(), EMBED_I, EMBED_M, EMBED_S, EMBED_S2, EMBED_U, embedded_list, espeakEVENT_MARK, espeakEVENT_PLAY, length, SOUND_ICON::length, long, n_soundicon_tab, SetEmbedded(), SetSpeed(), value, WCMD_EMBEDDED, WCMD_WAVE, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by Generate().
static void DoMarker (int type, int char_posn, int length, int value) static
References type, value, WCMD_MARKER, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by DoEmbedded(), and Generate().
static void DoPause (int length, int control) static
References EndPitch(), NULL, PauseLength(), samplerate, WCMD_PAUSE, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by DoEmbedded(), FormantTransition2(), and Generate().
static void DoPitch (unsigned char * env, int pitch1, int pitch2) static
References EndPitch(), envelope_data, last_pitch_cmd, long, pitch_length, PITCHfall, WCMD_PITCH, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by Generate().
int DoSample (PHONEME_TAB * ph1, PHONEME_TAB * ph2, int which, int length_mod, int amp)
References DoSample2(), EndPitch(), LookupSound(), NULL, and wavefile_amp.
Referenced by Generate(), and MbrolaTranslate().
static int DoSample2 (int index, int which, int length_mod, int amp) static
References last_wcmdq, length, long, SPEED_FACTORS::min_sample_len, p, samplerate, seq_len_adjust, SPEED_FACTORS::speed_factor2, start, wavefile_data, WCMD_WAVE, WCMD_WAVE2, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by DoSample(), and DoSpect().
int DoSpect (PHONEME_TAB * this_ph, PHONEME_TAB * prev_ph, PHONEME_TAB * next_ph, int which, PHONEME_LIST * plist, int modulation)
References amp_length, CopyFrame(), DoSample2(), frame_t::ffreq, frame_t::fheight, frameref_t::frame, FRFLAG_BREAK, FRFLAG_BREAK_LF, FRFLAG_DEFER_WAV, FRFLAG_LEN_MOD, FRFLAG_MODULATE, FRFLAG_VOWEL_CENTRE, frame_t::frflags, voice_t::klattv, Translator::langopts, last_wcmdq, frame_t::length, frameref_t::length, PHONEME_LIST::length, long, LookupSpect(), LOPT_SONORANT_MIN, modn_flags, NULL, LANGUAGE_OPTIONS::param, phLIQUID, phNASAL, phVOWEL, pitch_length, samplerate, seq_len_adjust, SmoothSpect(), SPEED_FACTORS::speed_factor3, syllable_centre, translator, PHONEME_TAB::type, voice, wavefile_amp, wavefile_ix, WCMD_KLATT, WCMD_KLATT2, WCMD_SPECT, WCMD_SPECT2, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by Generate(), and MbrolaTranslate().
void DoVoiceChange (voice_t * v)
References long, WCMD_VOICE, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by espeak_Initialize(), espeak_new(), main(), SetVoiceByName(), SetVoiceByProperties(), and SpeakNextClause().
static frame_t* DuplicateLastFrame (frameref_t * seq, int n_frames, int length) static
References CopyFrame(), frameref_t::frame, length, and frameref_t::length.
Referenced by FormantTransition2().
static void EndAmplitude (void) static
References amp_length, last_amp_cmd, and wcmdq.
Referenced by Generate().
static void EndPitch (int voice_break) static
References last_pitch_cmd, last_wcmdq, NULL, pitch_length, SmoothSpect(), syllable_centre, syllable_end, vowel_transition, wcmdq, and wcmdq_tail.
Referenced by DoPause(), DoPitch(), DoSample(), and Generate().
static void formants_reduce_hf (frame_t * fr, int level) static
References frame_t::fheight, voice_t::klattv, level, and voice.
Referenced by AdjustFormants().
int FormantTransition2 (frameref_t * seq, int * n_frames, unsigned int data1, unsigned int data2, PHONEME_TAB * other_ph, int which)
References AdjustFormants(), CopyFrame(), DoPause(), DuplicateLastFrame(), f2, frame_t::ffreq, frameref_t::frame, FRFLAG_BREAK, FRFLAG_FORMANT_RATE, FRFLAG_LEN_MOD, frame_t::frflags, frameref_t::frflags, KLATT_AV, frame_t::klattp, voice_t::klattv, frameref_t::length, PHONEME_TAB::mnemonic, modn_flags, N_VCOLOUR, NULL, frame_t::rms, RMS_GLOTTAL1, RMS_START, seq_len_adjust, set_frame_rms(), voice, VOWEL_FRONT_LENGTH, and VowelCloseness().
Referenced by LookupSpect().
int Generate (PHONEME_LIST * phoneme_list, int * n_ph, int resume)
References PHONEME_TAB::after, PHONEME_LIST::amp, amp_length, clause_start_char, clause_start_word, count_characters, count_sentences, DoAmplitude(), DoEmbedded(), DoMarker(), DoPause(), DoPitch(), DoSample(), DoSpect(), embedded_ix, EndAmplitude(), EndPitch(), PHONEME_LIST::env, envelope_data, espeakEVENT_END, espeakEVENT_PHONEME, espeakEVENT_SENTENCE, espeakEVENT_WORD, Translator::langopts, last_pitch_cmd, last_wcmdq, PHONEME_LIST::length, LookupEnvelope(), LOPT_WORD_MERGE, mbrola_name, MIN_WCMDQ, PHONEME_TAB::mnemonic, PHONEME_LIST::newword, next, NULL, option_phoneme_events, option_quiet, p, LANGUAGE_OPTIONS::param, PHONEME_LIST::ph, PHONEME_TAB::phflags, phFRICATIVE, phLIQUID, phNASAL, phoneme_tab, phonPAUSE, phonSCHWA, phonSONORANT, phPAUSE, phSTOP, phTRILL, phVFRICATIVE, phVOWEL, phVOWEL2, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, pitch_length, PHONEME_LIST::prepause, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_SEQCONTINUE, PHONEME_LIST::sourceix, PHONEME_TAB::spect, StartSyllable(), PHONEME_LIST::stresslevel, syllable_centre, syllable_end, syllable_start, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, translator, PHONEME_LIST::type, vowel_transition, vowel_transition0, vowel_transition1, wcmdq_tail, and WcmdqFree().
Referenced by fill_buffer(), main(), SpeakNextClause(), Synthesize(), and SynthOnTimer().
int PauseLength (int pause, int control)
References SPEED_FACTORS::speed_factor1, and SPEED_FACTORS::speed_factor2.
Referenced by DoPause(), and MbrolaTranslate().
static void set_frame_rms (frame_t * fr, int new_rms) static
References frame_t::fheight, KLATT_AV, frame_t::klattp, voice_t::klattv, frame_t::rms, and voice.
Referenced by FormantTransition2().
static void SmoothSpect (void) static
References CopyFrame(), f2, frame_t::ffreq, formant_rate, FRFLAG_BREAK, FRFLAG_BREAK_LF, FRFLAG_FORMANT_RATE, frame_t::frflags, long, modified, N_WCMDQ, NULL, syllable_centre, syllable_end, syllable_start, WCMD_PAUSE, WCMD_SPECT2, WCMD_WAVE, and wcmdq.
Referenced by DoSpect(), and EndPitch().
int SpeakNextClause (FILE * f_in, const void * text_in, int control)
References CalcLengths(), CalcPitches(), current_phoneme_table, DoVoiceChange(), EMBED_T, embedded_value, f_trans, fprintf(), Generate(), GetTranslatedPhonemeString(), LoadVoiceVariant(), mbrola_name, MbrolaTranslate(), n_phoneme_list, NULL, option_phonemes, paused, Translator::phon_out, phoneme_callback, voice_t::phoneme_tab_ix, SelectPhonemeTable(), skipping_text, timer_on, TranslateClause(), translator, voice, WavegenOpenSound(), and WcmdqStop().
Referenced by fill_buffer(), main(), start_speaking(), StopSpeak(), Synthesize(), and SynthOnTimer().
static void StartSyllable (void) static
References syllable_end, syllable_start, and wcmdq_tail.
Referenced by Generate().
void SynthesizeInit (void)
References last_amp_cmd, last_pitch_cmd, PHONEME_LIST::newword, NULL, phPAUSE, syllable_centre, and PHONEME_LIST::type.
Referenced by initialise().
int SynthOnTimer (void)
References Generate(), n_phoneme_list, NULL, skipping_text, SpeakNextClause(), timer_on, WavegenCloseSound(), WavegenOpenSound(), and WcmdqUsed().
Referenced by main(), and Synthesize().
int SynthStatus (void)
References paused, and timer_on.
static int VowelCloseness (frame_t * fr) static
References frame_t::ffreq.
Referenced by FormantTransition2().
const char* WordToString (unsigned int word)
References buf.
Referenced by MbrolaTranslate().
Variable Documentation
int amp_length static
Referenced by DoAmplitude(), DoSpect(), EndAmplitude(), and Generate().
FILE* f_log
Referenced by SetPitch(), and SetSynth().
int last_amp_cmd static
Referenced by DoAmplitude(), EndAmplitude(), and SynthesizeInit().
frame_t* last_frame static
int last_pitch_cmd static
Referenced by DoPitch(), EndPitch(), Generate(), and SynthesizeInit().
int last_wcmdq static
Referenced by DoSample2(), DoSpect(), EndPitch(), and Generate().
int mbrola_delay
Referenced by LoadMbrolaTable(), and MarkerEvent().
char mbrola_name[20]
Referenced by Generate(), LoadMbrolaTable(), main(), SpeakNextClause(), and WavegenFill().
int modn_flags static
Referenced by DoSpect(), and FormantTransition2().
int n_phoneme_list =0
Referenced by CalcLengths(), CalcPitches(), CalcPitches_Tone(), fill_buffer(), GetTranslatedPhonemeString(), main(), MakePhonemeList(), SpeakNextClause(), Synthesize(), SynthOnTimer(), and TranslateClause().
int n_soundicon_tab =N_SOUNDICON_SLOTS
Referenced by DoEmbedded(), LoadConfig(), LoadSoundFile2(), and LookupSoundicon().
voice_t* new_voice =NULL static
PHONEME_LIST next_pause static
int paused = 0 static
Referenced by SpeakNextClause(), and SynthStatus().
PHONEME_LIST phoneme_list[N_PHONEME_LIST]
Referenced by CalcLengths(), CalcPitches(), CalcPitches_Tone(), fill_buffer(), GetTranslatedPhonemeString(), main(), MakePhonemeList(), Synthesize(), and TranslateClause().
int pitch_length static
Referenced by DoPitch(), DoSpect(), EndPitch(), and Generate().
int seq_len_adjust
Referenced by DoSample2(), DoSpect(), FormantTransition2(), LookupSound(), LookupSound2(), and LookupSpect().
SOUND_ICON soundicon_tab[N_SOUNDICON_TAB]
Referenced by LoadConfig(), LoadSoundFile(), LoadSoundFile2(), and LookupSoundicon().
SPEED_FACTORS speed
Referenced by ch_generate_ddsg(), getSpeed(), LoadVoice(), main(), MbrolaTranslate(), osd_speed_cam_draw(), ProcessSsmlTag(), roadprofile_set_attr_do(), route_seg_speed(), route_time_seg(), rp_attr_get(), setEdge(), SetSpeed(), tracking_update(), vehicle_draw(), vehicle_draw_do(), vehicle_get_cursor_data(), vehicle_gpsd_dbus_filter(), vehicle_iphone_new(), and VoiceReset().
int syllable_centre static
Referenced by DoSpect(), EndPitch(), Generate(), SmoothSpect(), and SynthesizeInit().
int syllable_end static
Referenced by EndPitch(), Generate(), SmoothSpect(), and StartSyllable().
int syllable_start static
Referenced by Generate(), SmoothSpect(), and StartSyllable().
int timer_on = 0 static
Referenced by SpeakNextClause(), SynthOnTimer(), and SynthStatus().