navit: support/espeak/synthdata.c File Reference
synthdata.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <wctype.h>
#include <string.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
#include "wave.h"
Functions
int FormantTransition2 (frameref_t *seq, int *n_frames, unsigned int data1, unsigned int data2, PHONEME_TAB *other_ph, int which)
static char * ReadPhFile (void *ptr, const char *fname)
int LoadPhData ()
void FreePhData (void)
int PhonemeCode (unsigned int mnem)
int LookupPhonemeString (const char *string)
static unsigned int LookupSound2 (int index, unsigned int other_phcode, int control)
unsigned int LookupSound (PHONEME_TAB *this_ph, PHONEME_TAB *other_ph, int which, int *match_level, int control)
frameref_t * LookupSpect (PHONEME_TAB *this_ph, PHONEME_TAB *prev_ph, PHONEME_TAB *next_ph, int which, int *match_level, int *n_frames, PHONEME_LIST *plist)
unsigned char * LookupEnvelope (int ix)
static void SetUpPhonemeTable (int number, int recursing)
void SelectPhonemeTable (int number)
int LookupPhonemeTable (const char *name)
int SelectPhonemeTableName (const char *name)
void LoadConfig (void)
Variables
const char * version_string = "1.41.01 25.Aug.09"
const int version_phdata = 0x014100
int option_device_number = -1
int n_phoneme_tab
int current_phoneme_table
PHONEME_TAB * phoneme_tab [N_PHONEME_TAB]
unsigned char phoneme_tab_flags [N_PHONEME_TAB]
static unsigned int * phoneme_index =NULL
char * spects_data =NULL
unsigned char * wavefile_data =NULL
static unsigned char * phoneme_tab_data = NULL
int n_phoneme_tables
PHONEME_TAB_LIST phoneme_tab_list [N_PHONEME_TABS]
int phoneme_tab_number = 0
int wavefile_ix
int wavefile_amp
int wavefile_ix2
int wavefile_amp2
int seq_len_adjust
int vowel_transition [4]
int vowel_transition0
int vowel_transition1
Function Documentation
int FormantTransition2 (frameref_t * seq, int * n_frames, unsigned int data1, unsigned int data2, PHONEME_TAB * other_ph, int which)
References AdjustFormants(), CopyFrame(), DoPause(), DuplicateLastFrame(), f2, frame_t::ffreq, frameref_t::frame, FRFLAG_BREAK, FRFLAG_FORMANT_RATE, FRFLAG_LEN_MOD, frame_t::frflags, frameref_t::frflags, KLATT_AV, frame_t::klattp, voice_t::klattv, frameref_t::length, PHONEME_TAB::mnemonic, modn_flags, N_VCOLOUR, NULL, frame_t::rms, RMS_GLOTTAL1, RMS_START, seq_len_adjust, set_frame_rms(), voice, VOWEL_FRONT_LENGTH, and VowelCloseness().
Referenced by LookupSpect().
void FreePhData (void)
References Free(), NULL, phoneme_index, phoneme_tab_data, and spects_data.
Referenced by espeak_Terminate().
void LoadConfig (void)
References Alloc(), buf, c1, SOUND_ICON::data, SOUND_ICON::filename, SOUND_ICON::length, N_SOUNDICON_SLOTS, n_soundicon_tab, SOUND_ICON::name, NULL, option_device_number, p, path_home, PATHSEP, ReadTonePoints(), soundicon_tab, sprintf(), and tone_points.
Referenced by initialise().
int LoadPhData ()
References PHONEME_TAB_LIST::includes, N_PHONEME_TAB_NAME, n_phoneme_tables, PHONEME_TAB_LIST::n_phonemes, name, NULL, p, phoneme_index, phoneme_tab_data, phoneme_tab_number, PHONEME_TAB_LIST::phoneme_tab_ptr, ReadPhFile(), spects_data, version, version_phdata, and wavefile_data.
Referenced by initialise().
unsigned char* LookupEnvelope (int ix)
References NULL, phoneme_index, and spects_data.
Referenced by CalcLengths(), and Generate().
int LookupPhonemeString (const char * string)
References c, and PhonemeCode().
Referenced by PhonemeReplacement().
int LookupPhonemeTable (const char * name)
References n_phoneme_tables, and phoneme_tab_number.
Referenced by SelectPhonemeTableName(), and TranslateWord2().
unsigned int LookupSound (PHONEME_TAB * this_ph, PHONEME_TAB * other_ph, int which, int * match_level, int control)
References PHONEME_TAB::after, PHONEME_TAB::before, PHONEME_TAB::code, PHONEME_TAB::end_type, level, LookupSound2(), NULL, phonPAUSE, phonPAUSE_SHORT, phPAUSE, seq_len_adjust, PHONEME_TAB::spect, PHONEME_TAB::start_type, type, vowel_transition, wavefile_amp, and wavefile_ix.
Referenced by DoSample(), and LookupSpect().
static unsigned int LookupSound2 (int index, unsigned int other_phcode, int control) static
References phoneme_index, seq_len_adjust, value, vowel_transition, wavefile_amp, and wavefile_ix.
Referenced by LookupSound().
frameref_t* LookupSpect (PHONEME_TAB * this_ph, PHONEME_TAB * prev_ph, PHONEME_TAB * next_ph, int which, int * match_level, int * n_frames, PHONEME_LIST * plist)
References FormantTransition2(), SPECT_SEQ::frame, SPECT_SEQK::frame, frameref_t::frame, FRFLAG_BREAK, FRFLAG_KLATT, FRFLAG_VOWEL_CENTRE, frame_t::frflags, frame_t2::frflags, frameref_t::frflags, length, frame_t::length, frameref_t::length, LookupSound(), SPECT_SEQ::n_frames, N_SEQ_FRAMES, NULL, PHONEME_LIST::ph, PHONEME_TAB::phflags, phNASAL, phonLENGTHEN, phVOWEL, phVOWEL2, seq_len_adjust, SFLAG_LENGTHEN, spects_data, PHONEME_TAB::std_length, PHONEME_LIST::synthflags, PHONEME_TAB::type, vowel_transition, vowel_transition0, vowel_transition1, and wavefile_ix.
Referenced by DoSpect().
int PhonemeCode (unsigned int mnem)
References n_phoneme_tab, and NULL.
Referenced by ApplySpecialAttribute(), ApplySpecialAttribute2(), CalcPitches_Tone(), ChangePhonemes_ru(), and LookupPhonemeString().
static char* ReadPhFile (void * ptr, const char * fname) static
References Alloc(), buf, fprintf(), Free(), GetFileLength(), length, NULL, p, path_home, PATHSEP, and sprintf().
Referenced by LoadPhData().
void SelectPhonemeTable (int number)
References current_phoneme_table, n_phoneme_tab, and SetUpPhonemeTable().
Referenced by LookupCharName(), LookupLetter(), MakePhonemeList(), SelectPhonemeTableName(), SetTranslator2(), SpeakNextClause(), TranslateLetter(), and TranslateWord2().
int SelectPhonemeTableName (const char * name)
References LookupPhonemeTable(), and SelectPhonemeTable().
Referenced by LoadVoice(), and SetTranslator2().
static void SetUpPhonemeTable (int number, int recursing) static
References PHONEME_TAB::code, n_phoneme_tab, PHONEME_TAB_LIST::n_phonemes, phoneme_tab_flags, and PHONEME_TAB_LIST::phoneme_tab_ptr.
Referenced by SelectPhonemeTable().
Variable Documentation
int current_phoneme_table
Referenced by SelectPhonemeTable(), and SpeakNextClause().
int n_phoneme_tab
Referenced by AppendPhonemes(), EncodePhonemes(), PhonemeCode(), SelectPhonemeTable(), SetUpPhonemeTable(), and SetWordStress().
int n_phoneme_tables
Referenced by LoadPhData(), and LookupPhonemeTable().
int option_device_number = -1
Referenced by LoadConfig().
unsigned int* phoneme_index =NULL static
Referenced by FreePhData(), LoadPhData(), LookupEnvelope(), and LookupSound2().
PHONEME_TAB* phoneme_tab[N_PHONEME_TAB]
Referenced by AppendPhonemes(), CalcLengths(), CalcPitches(), CalcPitches_Tone(), ChangePhonemes_ru(), ChangeWordStress(), CountSyllables(), DecodePhonemes(), EncodePhonemes(), Generate(), GetMbrName(), GetTranslatedPhonemeString(), GetVowelStress(), LookupLetter(), LookupNum2(), MakePhonemeList(), MbrolaTranslate(), SetWordStress(), SubstitutePhonemes(), and TranslateWord2().
unsigned char* phoneme_tab_data = NULL static
Referenced by FreePhData(), and LoadPhData().
unsigned char phoneme_tab_flags[N_PHONEME_TAB]
Referenced by SetUpPhonemeTable().
PHONEME_TAB_LIST phoneme_tab_list[N_PHONEME_TABS]
Referenced by CompileDictionary(), and GetTranslatedPhonemeString().
int phoneme_tab_number = 0
Referenced by CompileDictionary(), LoadPhData(), and LookupPhonemeTable().
int seq_len_adjust
Referenced by DoSample2(), DoSpect(), FormantTransition2(), LookupSound(), LookupSound2(), and LookupSpect().
char* spects_data =NULL
Referenced by FreePhData(), LoadPhData(), LookupEnvelope(), and LookupSpect().
const int version_phdata = 0x014100
Referenced by initialise(), and LoadPhData().
const char* version_string = "1.41.01 25.Aug.09"
Referenced by espeak_Info(), and main().
int vowel_transition[4]
Referenced by EndPitch(), Generate(), LookupSound(), LookupSound2(), and LookupSpect().
int vowel_transition0
Referenced by Generate(), and LookupSpect().
int vowel_transition1
Referenced by Generate(), and LookupSpect().
int wavefile_amp
Referenced by DoSample(), DoSpect(), LookupSound(), and LookupSound2().
int wavefile_amp2
unsigned char* wavefile_data =NULL
Referenced by DoSample2(), and LoadPhData().
int wavefile_ix
Referenced by DoSpect(), LookupSound(), LookupSound2(), and LookupSpect().
int wavefile_ix2