navit: support/espeak/synth_mbrola.c File Reference
synth_mbrola.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <wctype.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "translate.h"
#include "voice.h"
Functions
int Read4Bytes (FILE *f)
void SetPitch2 (voice_t *voice, int pitch1, int pitch2, int *pitch_base, int *pitch_range)
espeak_ERROR LoadMbrolaTable (const char *mbrola_voice, const char *phtrans, int srate)
static int GetMbrName (PHONEME_LIST *plist, PHONEME_TAB *ph, PHONEME_TAB *ph_prev, PHONEME_TAB *ph_next, int *name2, int *split, int *control)
static char * WritePitch (int env, int pitch1, int pitch2, int split, int final)
void MbrolaTranslate (PHONEME_LIST *plist, int n_phonemes, FILE *f_mbrola)
Variables
static MBROLA_TAB * mbrola_tab = NULL
static int mbrola_control = 0
Function Documentation
static int GetMbrName (PHONEME_LIST * plist, PHONEME_TAB * ph, PHONEME_TAB * ph_prev, PHONEME_TAB * ph_next, int * name2, int * split, int * control) static
References MBROLA_TAB::control, MBROLA_TAB::mbr_name, MBROLA_TAB::mbr_name2, mbrola_tab, PHONEME_TAB::mnemonic, MBROLA_TAB::name, PHONEME_LIST::newword, MBROLA_TAB::next_phoneme, MBROLA_TAB::percent, phoneme_tab, phPAUSE, phVOWEL, SFLAG_LENGTHEN, PHONEME_LIST::synthflags, and PHONEME_TAB::type.
Referenced by MbrolaTranslate().
espeak_ERROR LoadMbrolaTable (const char * mbrola_voice, const char * phtrans, int srate)
References EE_INTERNAL_ERROR, EE_NOT_FOUND, EE_OK, espeakVOICETYPE, FALSE, GetFileLength(), mbrolib_parameter::ignore_error, mbrola_delay, mbrola_name, mbrolib_get_parameter(), mbrolib_init(), MBROLIB_OK, mbrolib_set_parameter(), mbrolib_set_voice(), NULL, option_quiet, path_home, Read4Bytes(), samplerate, samplerate_native, SetParameter(), size, sprintf(), and mbrolib_parameter::volume_ratio.
Referenced by LoadVoice(), and VoiceReset().
void MbrolaTranslate (PHONEME_LIST * plist, int n_phonemes, FILE * f_mbrola)
References buf, clause_start_char, clause_start_word, count_sentences, DoSample(), DoSpect(), embedded_ix, PHONEME_LIST::env, espeakEVENT_PHONEME, espeakEVENT_SENTENCE, espeakEVENT_WORD, event_list_ix, GetMbrName(), PHONEME_LIST::length, PHONEME_TAB::mnemonic, name, PHONEME_LIST::newword, next, NULL, out_ptr, outbuf, p, PauseLength(), PHONEME_LIST::ph, phFRICATIVE, phLIQUID, phNASAL, phoneme_tab, phonLENGTHEN, phonPAUSE, phPAUSE, phSTOP, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PHONEME_LIST::prepause, samplerate, SFLAG_EMBEDDED, SFLAG_LENGTHEN, PHONEME_LIST::sourceix, speed, SPEED_FACTORS::speed_factor1, SPEED_FACTORS::speed_factor2, sprintf(), PHONEME_TAB::std_length, PHONEME_LIST::synthflags, PHONEME_TAB::type, PHONEME_LIST::type, WordToString(), and WritePitch().
Referenced by SpeakNextClause().
int Read4Bytes (FILE * f)
Referenced by LoadMbrolaTable().
void SetPitch2 (voice_t * voice, int pitch1, int pitch2, int * pitch_base, int * pitch_range)
References EMBED_P, EMBED_R, EMBED_T, embedded_value, MAX_PITCH_VALUE, pitch_adjust_tab, voice_t::pitch_base, and voice_t::pitch_range.
Referenced by SetPitch(), and WritePitch().
static char* WritePitch (int env, int pitch1, int pitch2, int split, int final) static
References buf, envelope_data, max, SetPitch2(), sprintf(), and voice.
Referenced by MbrolaTranslate().
Variable Documentation
int mbrola_control = 0 static
MBROLA_TAB* mbrola_tab = NULL static
Referenced by GetMbrName().