navit: binding/win32/tell_navit.c File Reference
tell_navit.c File Reference
#include "config.h"
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <XGetopt.h>
#include <glib.h>
#include "binding_win32.h"
Functions
static LRESULT CALLBACK message_handler (HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
void err (char *fmt,...)
void print_usage (void)
int main (int argc, char **argv)
Variables
int errormode =1
Function Documentation
void err (char * fmt, ...)
References buf, errormode, fprintf(), and NULL.
Referenced by allocator_memalign(), command_evaluate(), invoke(), main(), mlPDL_ServiceCall_callback(), mlPDL_ServiceCallWithCallback_callback(), NP_Initialize(), osd_std_config(), osd_std_reconfigure(), osso_display_on(), print_usage(), speechd_say(), uncompress_int(), vehicle_gpsd_close(), vehicle_webos_bt_gap_callback(), vehicle_webos_bt_open(), vehicle_webos_callback(), vehicle_webos_init_bt_gps(), vehicle_webos_init_pdl_locationtracking_callback(), vehicle_webos_open(), and vehicle_webos_spp_init_read().
int main (int argc, char ** argv)
static LRESULT CALLBACK message_handler (HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References TRUE.
Referenced by main(), and register_destination_window().
void print_usage (void)
References err().
Referenced by main().
Variable Documentation
int errormode =1
Referenced by err(), and main().