navit: maptool/tempfile.c File Reference
tempfile.c File Reference
#include "debug.h"
#include "maptool.h"
#include <glib.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <unistd.h>
Macros
#define tmpfile_prefix_size 64
Functions
char * tempfile_obtain_prefix ()
void tempfile_cleanup ()
char * tempfile_name (char *suffix, char *name)
FILE * tempfile (char *suffix, char *name, int mode)
void tempfile_unlink (char *suffix, char *name)
void tempfile_rename (char *suffix, char *from, char *to)
Macro Definition Documentation
tmpfile_prefix_size
#define tmpfile_prefix_size 64
Function Documentation
tempfile()
FILE * tempfile (char * suffix, char * name, int mode)
References name, and tempfile_name().
Referenced by ch_assemble_map(), ch_copy_to_tiles(), ch_create_tempfiles(), ch_generate_tiles(), files_relation_processing_new(), main(), maptool_assemble_map(), maptool_dump(), maptool_generate_tiles(), maptool_load_tilesdir(), osm_count_references(), osm_process_coastlines(), osm_process_multipolygons(), osm_process_towns(), osm_process_turn_restrictions(), osm_process_way2poi(), osm_read_input_data(), osm_resolve_coords_and_split_at_intersections(), process_boundaries_finish(), and write_countrydir().
tempfile_cleanup()
void tempfile_cleanup (void)
References tempfile_obtain_prefix().
Referenced by main().
tempfile_name()
char * tempfile_name (char * suffix, char * name)
References name, and tempfile_obtain_prefix().
Referenced by ch_setup(), maptool_assemble_map(), tempfile(), and write_countrydir().
tempfile_obtain_prefix()
char * tempfile_obtain_prefix (void)
References exit, and tmpfile_prefix_size.
Referenced by flush_nodes(), load_countries(), main(), osm_process_towns(), remove_countryfiles(), sort_countries(), tempfile_cleanup(), tempfile_name(), tempfile_rename(), tempfile_unlink(), and write_countrydir().
tempfile_rename()
void tempfile_rename (char * suffix, char * from, char * to)
References dbg_assert, and tempfile_obtain_prefix().
Referenced by files_relation_processing_destroy(), osm_count_references(), and osm_resolve_coords_and_split_at_intersections().
tempfile_unlink()
void tempfile_unlink (char * suffix, char * name)
References name, and tempfile_obtain_prefix().
Referenced by main(), maptool_assemble_map(), osm_count_references(), osm_process_multipolygons(), osm_process_turn_restrictions(), osm_resolve_coords_and_split_at_intersections(), and remove_countryfiles().