navit: map/textfile/textfile.c File Reference
textfile.c File Reference
#include <glib.h>
#include <stdlib.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <math.h>
#include "config.h"
#include "debug.h"
#include "plugin.h"
#include "projection.h"
#include "item.h"
#include "map.h"
#include "maptype.h"
#include "attr.h"
#include "transform.h"
#include "file.h"
#include "textfile.h"
Functions
static void remove_comment_line (char *line)
static void get_line (struct map_rect_priv *mr)
static void map_destroy_textfile (struct map_priv *m)
static void textfile_coord_rewind (void *priv_data)
static int parse_line (struct map_rect_priv *mr, int attr)
static int textfile_coord_get (void *priv_data, struct coord *c, int count)
static void textfile_attr_rewind (void *priv_data)
static void textfile_encode_attr (char *attr_val, enum attr_type attr_type, struct attr *attr)
static int textfile_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static struct map_rect_priv * map_rect_new_textfile (struct map_priv *map, struct map_selection *sel)
static void map_rect_destroy_textfile (struct map_rect_priv *mr)
static struct item * map_rect_get_item_textfile (struct map_rect_priv *mr)
static struct item * map_rect_get_item_byid_textfile (struct map_rect_priv *mr, int id_hi, int id_lo)
static struct map_priv * map_new_textfile (struct map_methods *meth, struct attr **attrs, struct callback_list *cbl)
void plugin_init (void)
register vehicle_gypsy
Variables
static int map_id
static struct item_methods methods_textfile
static struct map_methods map_methods_textfile
Function Documentation
get_line()
static void get_line (struct map_rect_priv * mr) static
References dbg, map_rect_priv::f, map_priv::is_pipe, map_rect_priv::lastlen, map_rect_priv::line, lvl_debug, lvl_error, map_rect_priv::m, map_rect_priv::pos, remove_comment_line(), and TEXTFILE_LINE_SIZE.
Referenced by map_rect_get_item_byid_textfile(), map_rect_get_item_textfile(), map_rect_new_textfile(), and textfile_coord_get().
map_destroy_textfile()
static void map_destroy_textfile (struct map_priv * m) static
References map_priv::charset, and map_priv::filename.
map_new_textfile()
static struct map_priv* map_new_textfile (struct map_methods * meth, struct attr ** attrs, struct callback_list * cbl) static
References attr_search(), map_priv::charset, map_methods::charset, data, dbg, file_wordexp_destroy(), file_wordexp_get_array(), file_wordexp_new(), map_priv::filename, map_priv::flags, map_priv::id, map_priv::is_pipe, lvl_debug, map_id, map_methods_textfile, map_priv::no_warning_if_map_file_missing, attr::num, attr::str, and attr::u.
Referenced by plugin_init().
map_rect_destroy_textfile()
static void map_rect_destroy_textfile (struct map_rect_priv * mr) static
References map_rect_priv::f, map_priv::is_pipe, and map_rect_priv::m.
map_rect_get_item_byid_textfile()
static struct item* map_rect_get_item_byid_textfile (struct map_rect_priv * mr, int id_hi, int id_lo) static
References map_rect_priv::args, map_rect_priv::f, get_line(), item::id_hi, map_priv::is_pipe, map_rect_priv::item, map_rect_priv::lastlen, map_rect_priv::m, map_rect_get_item_textfile(), and map_rect_priv::pos.
map_rect_get_item_textfile()
static struct item* map_rect_get_item_textfile (struct map_rect_priv * mr) static
References map_rect_priv::args, attr_from_line(), map_rect_priv::attr_last, map_rect_priv::attrs, dbg, map_rect_priv::eoc, map_rect_priv::f, map_priv::flags, get_line(), item::id_hi, item::id_lo, map_priv::is_pipe, map_rect_priv::item, item_from_name(), map_rect_priv::lastlen, map_rect_priv::line, lvl_debug, lvl_error, map_rect_priv::m, map_rect_priv::more, p, parse_line(), map_rect_priv::pos, textfile_coord_get(), TEXTFILE_LINE_SIZE, item::type, and type.
Referenced by map_rect_get_item_byid_textfile().
map_rect_new_textfile()
static struct map_rect_priv* map_rect_new_textfile (struct map_priv * map, struct map_selection * sel) static
References map_rect_priv::args, map_selection::c_rect, dbg, map_rect_priv::f, map_priv::filename, map_priv::flags, get_line(), item::id_hi, item::id_lo, map_priv::is_pipe, map_rect_priv::item, map_rect_priv::lastlen, layer_end, layer_town, coord_rect::lu, lvl_debug, lvl_error, map_rect_priv::m, item::meth, methods_textfile, map_selection::next, map_priv::no_warning_if_map_file_missing, map_selection::order, map_rect_priv::pos, item::priv_data, coord_rect::rl, map_rect_priv::sel, map_selection::u, coord::x, and coord::y.
parse_line()
static int parse_line (struct map_rect_priv * mr, int attr) static
References map_rect_priv::attrs, map_rect_priv::c, coord_parse(), map_rect_priv::line, startup::pos, and projection_mg.
Referenced by map_rect_get_item_textfile(), and textfile_coord_get().
plugin_init()
void plugin_init (void)
register vehicle_gypsy
Returns
nothing
References dbg, lvl_debug, and map_new_textfile().
remove_comment_line()
static void remove_comment_line (char * line) static
References TEXTFILE_COMMENT_CHAR.
Referenced by get_line().
textfile_attr_get()
static int textfile_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References map_rect_priv::attr, attr_from_line(), attr_from_name(), map_rect_priv::attr_last, map_rect_priv::attr_name, map_rect_priv::attr_pos, attr_to_name(), map_rect_priv::attrs, dbg, lvl_debug, map_rect_priv::str, textfile_encode_attr(), and attr::type.
textfile_attr_rewind()
static void textfile_attr_rewind (void * priv_data) static
References map_rect_priv::attr_last, and map_rect_priv::attr_pos.
textfile_coord_get()
static int textfile_coord_get (void * priv_data, struct coord * c, int count) static
References map_rect_priv::c, dbg, map_rect_priv::eoc, map_rect_priv::f, get_line(), item::id_hi, map_rect_priv::item, lvl_debug, lvl_warning, map_rect_priv::more, parse_line(), coord::x, and coord::y.
Referenced by map_rect_get_item_textfile().
textfile_coord_rewind()
static void textfile_coord_rewind (void * priv_data) static
textfile_encode_attr()
static void textfile_encode_attr (char * attr_val, enum attr_type attr_type, struct attr * attr) static
References attr::num, attr::str, and attr::u.
Referenced by textfile_attr_get().
Variable Documentation
map_id
int map_id static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by map_new_textfile().
map_methods_textfile
struct map_methods map_methods_textfile static
Initial value:
= {
    projection_mg,
    "utf-8",
    map_destroy_textfile,
    map_rect_new_textfile,
    map_rect_destroy_textfile,
    map_rect_get_item_textfile,
    map_rect_get_item_byid_textfile,
}
Referenced by map_new_textfile().
methods_textfile
struct item_methods methods_textfile static
Initial value:
= {
    textfile_coord_rewind,
    textfile_coord_get,
    textfile_attr_rewind,
    textfile_attr_get,
}
Referenced by map_rect_new_textfile().