navit: maptool/tile.c File Reference
tile.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <assert.h>
#include <string.h>
#include <signal.h>
#include <stdio.h>
#include <math.h>
#include <getopt.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <zlib.h>
#include "file.h"
#include "item.h"
#include "map.h"
#include "zipfile.h"
#include "main.h"
#include "config.h"
#include "linguistics.h"
#include "plugin.h"
#include "maptool.h"
Macros
#define _FILE_OFFSET_BITS 64
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
Functions
static char * string_hash_lookup (const char *key)
static char ** th_get_subtile (const struct tile_head *th, int idx)
int tile (struct rect *r, char *suffix, char *ret, int max, int overlap, struct rect *tr)
void tile_bbox (char *tile, struct rect *r, int overlap)
int tile_len (char *tile)
static void tile_extend (char *tile, struct item_bin *ib, GList **tiles_list)
static int tile_data_size (char *tile)
static int merge_tile (char *base, char *sub)
static gint get_tiles_list_cmp (gconstpointer s1, gconstpointer s2)
static void get_tiles_list_func (char *key, struct tile_head *th, GList **list)
static GList * get_tiles_list (void)
static void write_item (char *tile, struct item_bin *ib, FILE *reference)
void tile_write_item_to_tile (struct tile_info *info, struct item_bin *ib, FILE *reference, char *name)
void tile_write_item_minmax (struct tile_info *info, struct item_bin *ib, FILE *reference, int min, int max)
int add_aux_tile (struct zip_info *zip_info, char *name, char *filename, int size)
int write_aux_tiles (struct zip_info *zip_info)
static int add_tile_hash (struct tile_head *th)
int create_tile_hash (void)
static void create_tile_hash_list (GList *list)
void load_tilesdir (FILE *in)
void write_tilesdir (struct tile_info *info, struct zip_info *zip_info, FILE *out)
void merge_tiles (struct tile_info *info)
void index_init (struct zip_info *info, int version)
void index_submap_add (struct tile_info *info, struct tile_head *th)
Variables
GList * aux_tile_list
struct tile_head * tile_head_root
GHashTable * strings_hash
GHashTable * tile_hash
GHashTable * tile_hash2
struct attr map_information_attrs [32]
Macro Definition Documentation
#define _FILE_OFFSET_BITS 64
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#define _LARGEFILE64_SOURCE
#define _LARGEFILE_SOURCE
Function Documentation
int add_aux_tile (struct zip_info * zip_info, char * name, char * filename, int size)
References aux_tile_list, _GList::data, aux_tile::filename, fprintf(), g_list_append(), g_list_next, g_new0, g_strdup(), aux_tile::name, size, aux_tile::size, and zip_add_member().
Referenced by add_aux_tiles(), and index_country_add().
static int add_tile_hash (struct tile_head * th) static
References data, debug_tile, fprintf(), g_hash_table_insert(), tile_head::name, tile_head::num_subtiles, string_hash_lookup(), th_get_subtile(), and tile_hash2.
Referenced by create_tile_hash(), create_tile_hash_list(), and load_tilesdir().
int create_tile_hash (void)
References add_tile_hash(), g_hash_table_new(), g_str_equal(), g_str_hash(), tile_head::next, tile_hash2, and tile_head_root.
Referenced by ch_assemble_map(), load_tilesdir(), and phase5().
static void create_tile_hash_list (GList * list) static
References add_tile_hash(), _GList::data, fprintf(), g_hash_table_lookup(), g_hash_table_new(), g_list_first(), g_list_next, g_str_equal(), g_str_hash(), next, tile_hash, and tile_hash2.
Referenced by write_tilesdir().
static GList* get_tiles_list (void) static
References g_hash_table_foreach(), g_list_sort(), get_tiles_list_cmp(), get_tiles_list_func(), NULL, and tile_hash.
Referenced by merge_tiles(), and write_tilesdir().
static gint get_tiles_list_cmp (gconstpointer s1, gconstpointer s2) static
Referenced by get_tiles_list().
static void get_tiles_list_func (char * key, struct tile_head * th, GList ** list) static
References g_list_prepend().
Referenced by get_tiles_list().
void index_init (struct zip_info * info, int version)
References i, init_item(), item_bin_add_attr(), item_bin_write(), map_information_attrs, attr::num, type, attr::type, attr::u, version, and zip_get_index().
Referenced by maptool_assemble_map().
void index_submap_add (struct tile_info * info, struct tile_head * th)
References g_alloca, init_item(), item_bin_add_attr_int(), item_bin_add_attr_range(), item_bin_add_coord_rect(), item_bin::len, tile_head::name, NULL, overlap, tile_info::suffix, tile_bbox(), tile_len(), tile_write_item_to_tile(), and tile_head::zipnum.
Referenced by write_tilesdir().
void load_tilesdir (FILE * in)
References add_tile_hash(), c, create_tile_hash(), g_hash_table_insert(), g_hash_table_new(), g_str_equal(), g_str_hash(), tile_head::name, tile_head::next, NULL, tile_head::num_subtiles, printf(), size, string_hash_lookup(), th_get_subtile(), tile_hash, tile_head_root, tile_head::total_size, tile_head::total_size_used, tile_head::zip_data, and tile_head::zipnum.
Referenced by maptool_load_tilesdir().
static int merge_tile (char * base, char * sub) static
References debug_tile, fprintf(), g_free(), g_hash_table_insert(), g_hash_table_lookup(), g_hash_table_remove(), tile_head::name, NULL, tile_head::num_subtiles, string_hash_lookup(), th_get_subtile(), tile_hash, and tile_head::total_size.
Referenced by merge_tiles().
void merge_tiles (struct tile_info * info)
References _GList::data, fprintf(), g_hash_table_lookup(), g_list_free(), g_list_last(), g_list_length(), g_list_previous, g_list_sort(), get_tiles_list(), i, merge_tile(), processed_tiles, size, tile_info::suffix, tile_data_size(), tile_hash, tile_len(), and tile_head::total_size.
Referenced by ch_generate_tiles(), and phase34().
static char* string_hash_lookup (const char * key) static
References g_hash_table_insert(), g_hash_table_lookup(), g_hash_table_new(), g_str_equal(), g_str_hash(), g_strdup(), NULL, and strings_hash.
Referenced by add_tile_hash(), load_tilesdir(), merge_tile(), and tile_extend().
static char** th_get_subtile (const struct tile_head * th, int idx) static
References NULL.
Referenced by add_tile_hash(), load_tilesdir(), merge_tile(), tile_extend(), and write_tilesdir().
int tile (struct rect * r, char * suffix, char * ret, int max, int overlap, struct rect * tr)
References contains_bbox(), rect::h, i, max, world_bbox, coord::x, and coord::y.
Referenced by item_bin_write_clipped(), item_bin_write_match(), process_turn_restrictions_finish(), tile_write_item_minmax(), and write_countrydir().
void tile_bbox (char * tile, struct rect * r, int overlap)
References rect::h, world_bbox, coord::x, and coord::y.
Referenced by index_submap_add().
static int tile_data_size (char * tile) static
References g_hash_table_lookup(), tile_hash, and tile_head::total_size.
Referenced by merge_tiles().
static void tile_extend (char * tile, struct item_bin * ib, GList ** tiles_list) static
References debug_tile, fprintf(), g_hash_table_insert(), g_hash_table_lookup(), g_list_append(), item_bin_get_id(), item_bin::len, LONGLONG_FMT, tile_head::name, NULL, tile_head::num_subtiles, processed_tiles, string_hash_lookup(), th_get_subtile(), tile_hash, tile_hash2, tile_head::total_size, tile_head::total_size_used, item_bin::type, tile_head::zip_data, and tile_head::zipnum.
Referenced by tile_write_item_to_tile().
int tile_len (char * tile)
Referenced by index_submap_add(), and merge_tiles().
void tile_write_item_minmax (struct tile_info * info, struct item_bin * ib, FILE * reference, int min, int max)
References bbox(), item_bin::clen, NULL, overlap, tile_info::suffix, tile(), and tile_write_item_to_tile().
Referenced by ch_copy_to_tiles(), phase34_process_file(), and phase34_process_file_range().
void tile_write_item_to_tile (struct tile_info * info, struct item_bin * ib, FILE * reference, char * name)
References tile_extend(), tile_info::tiles_list, tile_info::write, and write_item().
Referenced by index_submap_add(), and tile_write_item_minmax().
int write_aux_tiles (struct zip_info * zip_info)
References aux_tile_list, buffer, _GList::data, aux_tile::filename, g_list_next, aux_tile::name, NULL, aux_tile::size, write_zipmember(), zip_add_member(), and zip_get_maxnamelen().
Referenced by maptool_assemble_map().
static void write_item (char * tile, struct item_bin * ib, FILE * reference) static
References abort(), dbg_assert, debug_itembin, debug_tile, dump_itembin(), exit, fprintf(), g_hash_table_lookup(), item_bin::len, tile_head::name, NULL, offset, tile_head::process, SEEK_CUR, size, tile_hash, tile_hash2, tile_head::total_size, tile_head::total_size_used, item_bin::type, tile_head::zip_data, and tile_head::zipnum.
Referenced by tile_write_item_to_tile().
void write_tilesdir (struct tile_info * info, struct zip_info * zip_info, FILE * out)
References create_tile_hash_list(), _GList::data, data, fprintf(), g_hash_table_lookup(), g_list_first(), g_list_free(), g_list_next, get_tiles_list(), index_submap_add(), init_item(), item_bin_add_attr_int(), item_bin_add_attr_range(), item_bin_add_coord_rect(), item_bin_write(), tile_info::maxlen, tile_head::name, tile_head::next, next, NULL, tile_head::num_subtiles, processed_tiles, tile_info::suffix, th_get_subtile(), tile_hash, tile_head_root, tile_info::tiles_list, tile_head::total_size, world_bbox, tile_info::write, zip_add_member(), zip_get_index(), zip_get_zipnum(), and tile_head::zipnum.
Referenced by ch_assemble_map(), ch_generate_tiles(), and phase34().
Variable Documentation
GList* aux_tile_list
Referenced by add_aux_tile(), and write_aux_tiles().
struct attr map_information_attrs[32]
Referenced by index_init().
GHashTable* strings_hash
Referenced by string_hash_lookup().
GHashTable * tile_hash
Referenced by ch_generate_tiles(), create_tile_hash_list(), get_tiles_list(), load_tilesdir(), merge_tile(), merge_tiles(), phase34(), tile_data_size(), tile_extend(), write_item(), and write_tilesdir().
GHashTable * tile_hash2
Referenced by add_tile_hash(), create_tile_hash(), create_tile_hash_list(), tile_extend(), and write_item().
struct tile_head* tile_head_root
Referenced by create_tile_hash(), load_tilesdir(), and write_tilesdir().