navit: support/libc/time.c File Reference
time.c File Reference
#include "timeutil.h"
Functions
time_t time (time_t *timer)
Function Documentation
time_t time (time_t * timer)
References __FILETIME_to_time_t(), and NULL.
Referenced by __time_t_to_FILETIME(), calculate_dest_distance(), current_to_iso8601(), gui_internal_populate_route_table(), gui_internal_time_help(), main(), mapExtract::mapExtract(), MarkerEvent(), message_cleanup(), message_new(), osd_j1850_new(), osd_odometer_new(), osd_stopwatch_click(), osd_stopwatch_draw(), osd_text_format_attr(), rp_attr_get(), statusbar_route_update(), strftime_localtime(), tracking_update(), vehicle_file_new_file(), vehicle_gpsd_dbus_filter(), vehicle_webos_parse_nmea(), and vehicle_wince_new().