navit: support/libc/sys/time.h File Reference
time.h File Reference
#include <time.h>
Data Structures
struct timeval
struct timezone
Macros
#define _TIMEVAL_DEFINED
#define timerisset(tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
#define timercmp(tvp, uvp, cmp)
#define timerclear(tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
#define _TIMEZONE_DEFINED
Functions
int gettimeofday (struct timeval *, void *)
Macro Definition Documentation
#define _TIMEVAL_DEFINED
#define _TIMEZONE_DEFINED
#define timerclear (tvp) (tvp)->tv_sec = (tvp)->tv_usec = 0
#define timercmp (tvp, uvp, cmp)
Value:
(((tvp)->tv_sec != (uvp)->tv_sec) ? \
        ((tvp)->tv_sec cmp (uvp)->tv_sec) : \
        ((tvp)->tv_usec cmp (uvp)->tv_usec))
#define timerisset (tvp) ((tvp)->tv_sec || (tvp)->tv_usec)
Function Documentation
int gettimeofday (struct timeval * , void *)
Referenced by button_press(), button_release(), debug_timestamp(), g_get_current_time(), gui_internal_gesture_ring_add(), j1850_idle(), log_set_last_flush(), log_timer(), main(), osd_odometer_click(), osd_odometer_draw(), osd_route_guard_draw(), profile_timer(), progress_time(), vehicle_webos_gps_update(), and vehicle_webos_timeout_callback().