navit: support/libc/timeutil.h File Reference
timeutil.h File Reference
#include <windows.h>
#include <sys/time.h>
#include <_mingw.h>
Macros
#define _onesec_in100ns 10000000LL
Functions
long long __FILETIME_to_ll (const FILETIME *f)
void __ll_to_FILETIME (long long t, FILETIME *f)
void __tm_to_SYSTEMTIME (struct tm *, SYSTEMTIME *)
void __SYSTEMTIME_to_tm (SYSTEMTIME *, struct tm *)
time_t __FILETIME_to_time_t (const FILETIME *)
void __time_t_to_FILETIME (time_t, FILETIME *)
Macro Definition Documentation
#define _onesec_in100ns 10000000LL
Referenced by __FILETIME_to_time_t(), __time_t_to_FILETIME(), __Yday_from_SYSTEMTIME(), and mktime().
Function Documentation
long long __FILETIME_to_ll (const FILETIME * f)
References long.
Referenced by __FILETIME_to_time_t(), __Yday_from_SYSTEMTIME(), localtime(), and mktime().
time_t __FILETIME_to_time_t (const FILETIME *)
References __FILETIME_to_ll(), _onesec_in100ns, and DELTA_EPOCH.
Referenced by __stat_by_file_info(), mktime(), and time().
void __ll_to_FILETIME (long long t, FILETIME * f)
Referenced by __time_t_to_FILETIME(), and localtime().
void __SYSTEMTIME_to_tm (SYSTEMTIME * , struct tm *)
References __Yday_from_SYSTEMTIME().
Referenced by gmtime(), and localtime().
void __time_t_to_FILETIME (time_t , FILETIME *)
References __ll_to_FILETIME(), _onesec_in100ns, DELTA_EPOCH, and time().
Referenced by gmtime(), and localtime().
void __tm_to_SYSTEMTIME (struct tm * , SYSTEMTIME *)
Referenced by mktime().