navit: tools/gpx2navit_txt/src/main.c File Reference
main.c File Reference
#include "gpx2navit_txt.h"
#include "geodesic.h"
Functions
void version (void)
void usage (char **argv)
void setDefault (g2sprop *prop)
void setOptions (int argc, char **argv, g2sprop *prop)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Main
References closeProp(), createProp(), g2sprop::needsStats, parseMain(), setOptions(), and showStats().
void setDefault (g2sprop * prop)
Sets default values to the properties when there is no user setting.
References checkEllpsUnit(), checkLengthUnit(), checkTimeUnit(), g2sprop::ellipsoid, ERR_ISNOTGPX, exit, fprintf(), geod_set(), g2sprop::length2meter, g2sprop::lengthUnit, NULL, g2sprop::output, g2sprop::parseRte, g2sprop::parseTrk, g2sprop::parseWpt, printf(), g2sprop::sourcefile, g2sprop::speed2meter, g2sprop::speed2sec, g2sprop::speedLengthUnit, g2sprop::speedTimeUnit, g2sprop::time2sec, g2sprop::timeUnit, and g2sprop::verbose.
Referenced by setOptions().
void setOptions (int argc, char ** argv, g2sprop * prop)
Set options from command arguments
Note
needs to change here to support a several files convertion
References g2scolumns::ageofdgpsdata, g2sprop::cols, g2scolumns::desc, g2scolumns::dgpsid, g2sprop::ellipsoid, ERR_NOARGS, ERR_OPTIONCONFRICT, ERR_WRONGOPTION, exit, fprintf(), g2scolumns::geoidheight, getopt_long(), g2scolumns::gpxline, g2scolumns::hdop, g2scolumns::interval, g2sprop::is3d, g2sprop::isEdge, g2sprop::isFast, g2sprop::isPoint, g2scolumns::length, g2sprop::lengthUnit, g2scolumns::link, g2scolumns::magvar, g2sprop::minlength, g2sprop::minpoints, g2sprop::mintime, g2sprop::needsStats, no_argument, g2sprop::nospeedcheck, NULL, optarg, optind, g2sprop::output, g2sprop::parseRte, g2sprop::parseTrk, g2sprop::parseWpt, g2scolumns::pdop, required_argument, g2scolumns::sat, setDefault(), g2sprop::sourcefile, g2scolumns::speed, g2sprop::speedLengthUnit, g2sprop::speedTimeUnit, g2scolumns::src, g2sprop::timeUnit, usage(), g2scolumns::vdop, g2sprop::verbose, and version().
Referenced by main().
void usage (char ** argv)
Shows a usage message
References fprintf().
Referenced by setOptions().
void version (void)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Shows a version
References fprintf().
Referenced by setOptions().