navit: tools/gpx2navit_txt/src/misc.c File Reference
misc.c File Reference
#include "gpx2navit_txt.h"
Functions
void failToWriteAttrRep (int iShape, int col, char *file, int line)
void showStats (g2sprop *prop)
void wipePathAttr (pathattr *pattr)
pathattr * createPathAttr (void)
void wipeAttr (g2sattr *attr)
void setColsDefault (g2scolumns *cols)
g2scolumns * createCols (void)
g2sattr * createAttr (void)
g2sprop * createProp (void)
void closeProp (g2sprop *prop)
parsedata * createParsedata (XML_Parser parser, g2sprop *prop)
void closeParsedata (parsedata *pdata)
Function Documentation
void closeParsedata (parsedata * pdata)
References parsedata::attr, parsedata::current, parsedata::databuf, parsedata::parent, and parsedata::pattr.
Referenced by parseMain().
void closeProp (g2sprop * prop)
close and free a propertires structure
References g2sprop::cols, g2sprop::ellipsoid, g2sprop::lengthUnit, g2sprop::output, g2sprop::sourcefile, g2sprop::speedLengthUnit, g2sprop::speedTimeUnit, g2sprop::stats, and g2sprop::timeUnit.
Referenced by main().
g2sattr* createAttr (void)
creates a element attribute structure.
References wipeAttr().
Referenced by createParsedata().
g2scolumns* createCols (void)
creates a column structure
References setColsDefault().
Referenced by createProp().
parsedata* createParsedata (XML_Parser parser, g2sprop * prop)
creates a shapehandles structure creates a dbfhandles structure creates a parse structure
References parsedata::attr, parsedata::bufptr, c, createAttr(), createPathAttr(), parsedata::current, parsedata::databuf, DATABUFSIZE, parsedata::depth, parsedata::failed, parsedata::failedid, parsedata::fp, parent::name, NULL, p, parsedata::parent, parent::parentptr, parsedata::parser, parser, parsedata::pattr, and parsedata::prop.
Referenced by parseMain().
pathattr* createPathAttr (void)
creates a new path attribute
References wipePathAttr().
Referenced by createParsedata().
g2sprop* createProp (void)
creates a properties structure for gpx2shp
References g2sprop::cols, createCols(), g2sprop::ellipsoid, g2sprop::is3d, g2sprop::isEdge, g2sprop::isFast, g2sprop::isPoint, g2sprop::lengthUnit, g2sprop::minlength, g2sprop::minpoints, g2sprop::mintime, g2sprop::needsStats, NULL, g2sprop::output, g2sprop::parseRte, g2sprop::parseTrk, g2sprop::parseWpt, g2sstats::rtecount, g2sstats::rtelength, g2sstats::rtepoints, g2sstats::rteunconverted, g2sprop::speedLengthUnit, g2sprop::speedTimeUnit, g2sprop::stats, g2sprop::timeUnit, g2sstats::trkcount, g2sstats::trklength, g2sstats::trkpoints, g2sstats::trkunconverted, g2sprop::verbose, and g2sstats::wptpoints.
Referenced by main().
void failToWriteAttrRep (int iShape, int col, char * file, int line)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
message when fail to write attribute
References printf().
void setColsDefault (g2scolumns * cols)
sets default values to a column properties.
References g2scolumns::ageofdgpsdata, g2scolumns::cmt, g2scolumns::desc, g2scolumns::dgpsid, g2scolumns::ele, g2scolumns::fix, g2scolumns::geoidheight, g2scolumns::gpxline, g2scolumns::hdop, g2scolumns::interval, g2scolumns::length, g2scolumns::link, g2scolumns::magvar, g2scolumns::name, g2scolumns::number, g2scolumns::pdop, g2scolumns::points, g2scolumns::sat, g2scolumns::speed, g2scolumns::src, g2scolumns::sym, g2scolumns::time, g2scolumns::type, and g2scolumns::vdop.
Referenced by createCols().
void showStats (g2sprop * prop)
shows short statistics
References double, g2sprop::isFast, g2sprop::needsStats, g2sprop::parseRte, g2sprop::parseTrk, g2sprop::parseWpt, printf(), g2sstats::rtecount, g2sstats::rtelength, g2sstats::rtepoints, g2sstats::rteunconverted, g2sprop::stats, g2sstats::trkcount, g2sstats::trklength, g2sstats::trkpoints, g2sstats::trkunconverted, and g2sstats::wptpoints.
Referenced by main().
void wipeAttr (g2sattr * attr)
clears a element attribute structure
References g2sattr::ageofdgpsdata, g2sattr::author, g2sattr::cmt, g2sattr::copyright, g2sattr::desc, g2sattr::dgpsid, g2sattr::ele, g2sattr::fix, g2sattr::geoidheight, g2sattr::hdop, g2sattr::keywords, g2sattr::lat, g2sattr::license, g2sattr::link, g2sattr::lon, g2sattr::magvar, g2sattr::maxlat, g2sattr::maxlon, g2sattr::minlat, g2sattr::minlon, g2sattr::name, g2sattr::number, g2sattr::pdop, g2sattr::sat, g2sattr::src, g2sattr::sym, g2sattr::time, g2sattr::type, g2sattr::vdop, and g2sattr::year.
Referenced by createAttr(), and endElementControl().
void wipePathAttr (pathattr * pattr)
clears a path attribute structure
References pathattr::cmt, pathattr::count, pathattr::desc, pathattr::interval, pathattr::length, pathattr::link, pathattr::name, pathattr::number, pathattr::speed, pathattr::src, and pathattr::type.
Referenced by createPathAttr().