navit: map/mg/town.c File Reference
town.c File Reference
#include <stdio.h>
#include <string.h>
#include "debug.h"
#include "mg.h"
Functions
static void town_coord_rewind (void *priv_data)
static int town_coord_get (void *priv_data, struct coord *c, int count)
static void town_attr_rewind (void *priv_data)
static int town_attr_get (void *priv_data, enum attr_type attr_type, struct attr *attr)
static void town_get_data (struct town_priv *twn, unsigned char **p)
int town_get (struct map_rect_priv *mr, struct town_priv *twn, struct item *item)
int town_get_byid (struct map_rect_priv *mr, struct town_priv *twn, int id_hi, int id_lo, struct item *item)
static int town_search_compare (unsigned char **p, struct map_rect_priv *mr)
struct item * town_search_get_item (struct map_rect_priv *mr)
Variables
static struct item_methods town_meth
static unsigned char limit [] ={0,1,2,2,4,6,8,10,11,13,14,14,14,20,20,20,20,20,20}
static enum item_type town_item [] ={type_town_label_5e1, type_town_label_1e2, type_town_label_2e2, type_town_label_5e2, type_town_label_1e3, type_town_label_1e3, type_town_label_2e3, type_town_label_5e3, type_town_label_1e4, type_town_label_2e4, type_town_label_5e4, type_town_label_1e5, type_town_label_1e5, type_town_label_2e5, type_town_label_5e5, type_town_label_1e6, type_town_label_2e6}
static enum item_type district_item [] ={type_district_label_5e1, type_district_label_1e2, type_district_label_2e2, type_district_label_5e2, type_district_label_1e3, type_district_label_1e3, type_district_label_2e3, type_district_label_5e3, type_district_label_1e4, type_district_label_2e4, type_district_label_5e4, type_district_label_1e5, type_district_label_1e5, type_district_label_2e5, type_district_label_5e5, type_district_label_1e6, type_district_label_2e6}
Function Documentation
static int town_attr_get (void * priv_data, enum attr_type attr_type, struct attr * attr) static
References town_priv::attr_next, attr_to_name(), town_priv::country, dbg, town_priv::debug, town_priv::district, file_town_twn, item::id_hi, item::id_lo, attr::item, lvl_warning, mg_country_postal_len(), town_priv::name, town_priv::order, town_priv::postal, town_priv::postal_code1, town_priv::size, sprintf(), attr::str, town_priv::street_assoc, town_priv::town_attr_item, item::type, attr::type, and attr::u.
static void town_attr_rewind (void * priv_data) static
References town_priv::aidx, and town_priv::attr_next.
static int town_coord_get (void * priv_data, struct coord * c, int count) static
References town_priv::c, and town_priv::cidx.
static void town_coord_rewind (void * priv_data) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References town_priv::cidx.
int town_get (struct map_rect_priv * mr, struct town_priv * twn, struct item * item)
References town_priv::aidx, town_priv::attr_next, map_rect_priv::b, town_priv::c, map_selection::c_rect, town_priv::cidx, coord_rect_contains(), town_priv::country, map_rect_priv::cur_sel, map_rect_priv::current_file, town_priv::district, district_item, block_priv::end, town_priv::id, item::id_hi, item::id_lo, limit, map_selection_contains_item(), item::meth, town_priv::name, town_priv::order, map_selection::order, block_priv::p, printf(), item::priv_data, town_priv::size, size, town_get_data(), town_item, town_meth, town_priv::type, item::type, map_selection::u, coord::x, and coord::y.
Referenced by map_rect_get_item_mg(), town_get_byid(), and town_search_get_item().
int town_get_byid (struct map_rect_priv * mr, struct town_priv * twn, int id_hi, int id_lo, struct item * item)
References map_rect_priv::b, block_get_byindex(), block_priv::block_start, map_rect_priv::current_file, map_priv::dirname, map_priv::file, map_rect_priv::m, block_priv::p, town_get(), and tree_search_hv().
Referenced by map_rect_get_item_byid_mg().
static void town_get_data (struct town_priv * twn, unsigned char ** p) static
References town_priv::c, town_priv::country, town_priv::district, get_string(), get_u16_unal(), get_u32_unal(), get_u8(), town_priv::id, town_priv::name, town_priv::order, town_priv::postal_code1, town_priv::postal_code2, printf(), town_priv::size, town_priv::street_assoc, town_priv::type, town_priv::unknown2, town_priv::unknown3, town_priv::unknown4, coord::x, and coord::y.
Referenced by town_get().
static int town_search_compare (unsigned char ** p, struct map_rect_priv * mr) static
References country, dbg, get_string(), get_u16_unal(), get_u32_unal(), lvl_debug, name, map_rect_priv::search_blk_count, map_rect_priv::search_blk_off, map_rect_priv::search_country, map_rect_priv::search_partial, map_rect_priv::search_str, strcasecmp(), and strncasecmp.
Referenced by town_search_get_item().
struct item* town_search_get_item (struct map_rect_priv * mr)
References map_rect_priv::b, block_get_byindex(), block_offset_get_block(), block_offset_get_offset(), block_priv::block_start, map_rect_priv::current_file, dbg, map_priv::file, map_rect_priv::item, lvl_debug, lvl_warning, map_rect_priv::m, NULL, block_priv::p, map_rect_priv::search_blk_count, map_rect_priv::search_blk_off, map_rect_priv::search_country, map_rect_priv::search_linear, map_rect_priv::search_p, map_rect_priv::search_partial, map_rect_priv::search_str, map_rect_priv::town, town_get(), town_search_compare(), tree_search_next(), tree_search_next_lin(), and map_rect_priv::ts.
Referenced by map_search_get_item_mg().
Variable Documentation
enum item_type district_item[] ={type_district_label_5e1, type_district_label_1e2, type_district_label_2e2, type_district_label_5e2, type_district_label_1e3, type_district_label_1e3, type_district_label_2e3, type_district_label_5e3, type_district_label_1e4, type_district_label_2e4, type_district_label_5e4, type_district_label_1e5, type_district_label_1e5, type_district_label_2e5, type_district_label_5e5, type_district_label_1e6, type_district_label_2e6} static
Referenced by town_get().
unsigned char limit[] ={0,1,2,2,4,6,8,10,11,13,14,14,14,20,20,20,20,20,20} static
Referenced by town_get().
enum item_type town_item[] ={type_town_label_5e1, type_town_label_1e2, type_town_label_2e2, type_town_label_5e2, type_town_label_1e3, type_town_label_1e3, type_town_label_2e3, type_town_label_5e3, type_town_label_1e4, type_town_label_2e4, type_town_label_5e4, type_town_label_1e5, type_town_label_1e5, type_town_label_2e5, type_town_label_5e5, type_town_label_1e6, type_town_label_2e6} static
Referenced by town_get().
struct item_methods town_meth static
Initial value:
= {
        town_coord_rewind,
        town_coord_get,
        town_attr_rewind,
        town_attr_get,
}
Referenced by town_get().