navit: support/espeak/tr_languages.c File Reference
tr_languages.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <wctype.h>
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "translate.h"
Macros
#define L_qa 0x716100
#define L_grc 0x677263
#define L_jbo 0x6a626f
#define L_pap 0x706170
#define L_zhy 0x7a6879
#define OFFSET_GREEK 0x380
#define OFFSET_CYRILLIC 0x420
#define OFFSET_ARMENIAN 0x530
#define OFFSET_DEVANAGARI 0x900
#define OFFSET_BENGALI 0x980
#define OFFSET_TAMIL 0xb80
#define OFFSET_KANNADA 0xc80
#define OFFSET_MALAYALAM 0xd00
#define OFFSET_KOREAN 0x1100
#define RUSSIAN2
#define N_VOWELS_RU 11
Functions
static void Translator_Russian (Translator *tr)
static void SetLetterVowel (Translator *tr, int c)
static void ResetLetterBits (Translator *tr, int groups)
static void SetLetterBits (Translator *tr, int group, const char *string)
static void SetLetterBitsRange (Translator *tr, int group, int first, int last)
static Translator * NewTranslator (void)
void SetIndicLetters (Translator *tr)
void SetupTranslator (Translator *tr, const short *lengths, const unsigned char *amps)
Translator * SelectTranslator (const char *name)
int ChangePhonemes_ru (Translator *tr, PHONEME_LIST2 *phlist, int n_ph, int index, PHONEME_TAB *ph, CHANGEPH *ch)
Variables
static const unsigned int replace_cyrillic_latin []
Macro Definition Documentation
#define L_grc 0x677263
Referenced by SelectTranslator().
#define L_jbo 0x6a626f
Referenced by SelectTranslator().
#define L_pap 0x706170
Referenced by SelectTranslator().
#define L_qa 0x716100
#define L_zhy 0x7a6879
Referenced by SelectTranslator().
#define N_VOWELS_RU 11
Referenced by ChangePhonemes_ru().
#define OFFSET_ARMENIAN 0x530
Referenced by SelectTranslator().
#define OFFSET_BENGALI 0x980
Referenced by SelectTranslator().
#define OFFSET_CYRILLIC 0x420
Referenced by Translator_Russian().
#define OFFSET_DEVANAGARI 0x900
Referenced by SelectTranslator().
#define OFFSET_GREEK 0x380
Referenced by SelectTranslator().
#define OFFSET_KANNADA 0xc80
Referenced by SelectTranslator().
#define OFFSET_KOREAN 0x1100
Referenced by SelectTranslator().
#define OFFSET_MALAYALAM 0xd00
Referenced by SelectTranslator().
#define OFFSET_TAMIL 0xb80
Referenced by SelectTranslator().
#define RUSSIAN2
Function Documentation
int ChangePhonemes_ru (Translator * tr, PHONEME_LIST2 * phlist, int n_ph, int index, PHONEME_TAB * ph, CHANGEPH * ch)
References CHANGEPH::flags, PHONEME_TAB::mnemonic, N_VOWELS_RU, next, PH, PHONEME_LIST2::phcode, PHONEME_TAB::phflags, phoneme_tab, PhonemeCode(), phPALATAL, phVOWEL, PHONEME_TAB::type, CHANGEPH::vowel_stressed, and CHANGEPH::vowel_this.
Referenced by ChangePhonemes().
static Translator* NewTranslator (void) static
References Alloc(), LANGUAGE_OPTIONS::ascii_language, Translator::char_plus_apostrophe, Translator::charset_a0, charsets, Translator::data_dictlist, Translator::data_dictrules, LANGUAGE_OPTIONS::decimal_sep, Translator::dict_condition, dictionary_name, Translator::langopts, Translator::letter_bits, Translator::letter_bits_offset, Translator::letter_groups, LANGUAGE_OPTIONS::long_stop, LOPT_MAXAMP_EOC, LOPT_SONORANT_MIN, LOPT_UNPRONOUNCABLE, LANGUAGE_OPTIONS::max_initial_consonants, LANGUAGE_OPTIONS::max_roman, NULL, LANGUAGE_OPTIONS::param, Translator::punct_to_tone, Translator::punct_within_word, punctuation_to_tone, LANGUAGE_OPTIONS::replace_chars, SetLengthMods(), SetLetterBits(), Translator::stress_amps, Translator::stress_amps_r, Translator::stress_lengths, LANGUAGE_OPTIONS::stress_rule, LANGUAGE_OPTIONS::thousands_sep, Translator::transpose_offset, LANGUAGE_OPTIONS::unstressed_wd1, and LANGUAGE_OPTIONS::unstressed_wd2.
Referenced by SelectTranslator().
static void ResetLetterBits (Translator * tr, int groups) static
References Translator::letter_bits, and mask.
Referenced by SelectTranslator().
Translator* SelectTranslator (const char * name)
References LANGUAGE_OPTIONS::accents, Translator::char_plus_apostrophe, Translator::charset_a0, charsets, LANGUAGE_OPTIONS::decimal_sep, LANGUAGE_OPTIONS::ideographs, LANGUAGE_OPTIONS::intonation_group, L, L_grc, L_jbo, L_pap, L_zhy, Translator::langopts, LANGUAGE_OPTIONS::length_mods, LANGUAGE_OPTIONS::length_mods0, Translator::letter_bits, Translator::letter_bits_offset, Translator::letter_groups, LETTERGP_A, LETTERGP_B, LETTERGP_C, LETTERGP_F, LETTERGP_G, LETTERGP_Y, LANGUAGE_OPTIONS::listx, LANGUAGE_OPTIONS::long_stop, LOPT_ALT, LOPT_CAPS_IN_WORD, LOPT_COMBINE_WORDS, LOPT_DIERESES, LOPT_IT_DOUBLING, LOPT_IT_LENGTHEN, LOPT_PREFIXES, LOPT_REDUCE, LOPT_REGRESSIVE_VOICING, LOPT_SONORANT_MIN, LOPT_UNPRONOUNCABLE, LOPT_WORD_MERGE, LANGUAGE_OPTIONS::max_initial_consonants, LANGUAGE_OPTIONS::max_roman, NewTranslator(), NULL, NUM2_100000, NUM2_100000a, NUM_NOPAUSE, NUM_ROMAN, NUM_ROMAN_AFTER, NUM_ROMAN_UC, NUM_VIGESIMAL, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, OFFSET_ARMENIAN, OFFSET_BENGALI, OFFSET_DEVANAGARI, OFFSET_GREEK, OFFSET_KANNADA, OFFSET_KOREAN, OFFSET_MALAYALAM, OFFSET_TAMIL, LANGUAGE_OPTIONS::param, Translator::punct_within_word, LANGUAGE_OPTIONS::replace_chars, replace_cyrillic_latin, ResetLetterBits(), SetIndicLetters(), SetLengthMods(), SetLetterBits(), SetLetterBitsRange(), SetLetterVowel(), SetupTranslator(), LANGUAGE_OPTIONS::spelling_stress, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, LANGUAGE_OPTIONS::stress_rule, LANGUAGE_OPTIONS::textmode, LANGUAGE_OPTIONS::thousands_sep, LANGUAGE_OPTIONS::tone_language, LANGUAGE_OPTIONS::tone_numbers, Translator::translator_name, Translator_Russian(), LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by LoadVoice(), and SetTranslator2().
void SetIndicLetters (Translator * tr)
References Translator::langopts, Translator::letter_bits, LETTERGP_A, LETTERGP_B, LETTERGP_C, LETTERGP_Y, LOPT_UNPRONOUNCABLE, LANGUAGE_OPTIONS::param, SetLetterBits(), and SetLetterBitsRange().
Referenced by SelectTranslator().
static void SetLetterBits (Translator * tr, int group, const char * string) static
References c, L, and Translator::letter_bits.
Referenced by NewTranslator(), SelectTranslator(), SetIndicLetters(), and Translator_Russian().
static void SetLetterBitsRange (Translator * tr, int group, int first, int last) static
References L, and Translator::letter_bits.
Referenced by SelectTranslator(), and SetIndicLetters().
static void SetLetterVowel (Translator * tr, int c) static
References c, and Translator::letter_bits.
Referenced by SelectTranslator().
void SetupTranslator (Translator * tr, const short * lengths, const unsigned char * amps)
References NULL, Translator::stress_amps, and Translator::stress_lengths.
Referenced by SelectTranslator(), and Translator_Russian().
static void Translator_Russian (Translator * tr) static
References Translator::charset_a0, charsets, Translator::langopts, Translator::letter_bits, Translator::letter_bits_offset, LOPT_REDUCE, LOPT_REGRESSIVE_VOICING, LOPT_UNPRONOUNCABLE, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, OFFSET_CYRILLIC, LANGUAGE_OPTIONS::param, LANGUAGE_OPTIONS::phoneme_change, SetLetterBits(), SetupTranslator(), LANGUAGE_OPTIONS::stress_flags, LANGUAGE_OPTIONS::stress_rule, LANGUAGE_OPTIONS::testing, Translator::transpose_max, Translator::transpose_min, and Translator::transpose_offset.
Referenced by SelectTranslator().
Variable Documentation
const unsigned int replace_cyrillic_latin[] static
Referenced by SelectTranslator().