navit: track.h File Reference
track.h File Reference
#include <time.h>
Functions
int tracking_get_angle (struct tracking *tr)
struct coord * tracking_get_pos (struct tracking *tr)
int tracking_get_street_direction (struct tracking *tr)
int tracking_get_segment_pos (struct tracking *tr)
struct street_data * tracking_get_street_data (struct tracking *tr)
int tracking_get_attr (struct tracking *_this, enum attr_type type, struct attr *attr, struct attr_iter *attr_iter)
struct item * tracking_get_current_item (struct tracking *_this)
int * tracking_get_current_flags (struct tracking *_this)
void tracking_flush (struct tracking *tr)
void tracking_update (struct tracking *tr, struct vehicle *v, struct vehicleprofile *vehicleprofile, enum projection pro)
Processes a position update.
int tracking_set_attr (struct tracking *tr, struct attr *attr)
struct tracking * tracking_new (struct attr *parent, struct attr **attrs)
void tracking_set_mapset (struct tracking *this_, struct mapset *ms)
void tracking_set_route (struct tracking *this_, struct route *rt)
void tracking_destroy (struct tracking *tr)
struct map * tracking_get_map (struct tracking *this_)
int tracking_add_attr (struct tracking *this_, struct attr *attr)
int tracking_remove_attr (struct tracking *this_, struct attr *attr)
struct tracking * tracking_ref (struct tracking *this_)
void tracking_unref (struct tracking *this_)
void tracking_init (void)
Function Documentation
int tracking_add_attr (struct tracking * this_, struct attr * attr)
References attr::callback, tracking::callback_list, callback_list_add(), attr::type, and attr::u.
void tracking_destroy (struct tracking * tr)
References tracking::attr, attr_free(), tracking::callback_list, callback_list_destroy(), g_free(), and tracking_flush().
void tracking_flush (struct tracking * tr)
References tracking::curr_line, dbg, g_free(), tracking::lines, lvl_debug, tracking_line::next, next, NULL, tracking_line::street, and street_data_free().
Referenced by tracking_destroy(), and tracking_update().
int tracking_get_angle (struct tracking * tr)
References tracking::curr_angle.
Referenced by navit_get_cursor_pnt().
int tracking_get_attr (struct tracking * _this, enum attr_type type, struct attr * attr, struct attr_iter * attr_iter)
References tracking::attr, attr_dup(), attr_free(), attr_to_name(), tracking::coord_geo, attr::coord_geo, tracking::coord_geo_valid, tracking::curr_line, tracking::curr_out, dbg, tracking::direction, tracking::direction_matched, item::id_hi, item::id_lo, item, street_data::item, attr::item, item_attr_get(), tracking::lines, lvl_debug, item::map, map_rect_destroy(), map_rect_get_item_byid(), map_rect_new(), tracking_line::next, NULL, attr::num, attr::numd, tracking::pro, tracking::speed, tracking_line::street, tracking::street_direction, transform_to_geo(), type, attr::type, attr::u, tracking::valid, coord::x, and coord::y.
Referenced by destination_address(), gui_internal_search_list_set_default_country(), Java_org_navitproject_navit_NavitGraphics_GetDefaultCountry(), navit_vehicle_update_position(), NGQProxySearch::NGQProxySearch(), osd_speed_warner_draw(), osd_text_draw(), and request_tracking_get_attr().
int* tracking_get_current_flags (struct tracking * _this)
References tracking::curr_line, street_data::flags, NULL, and tracking_line::street.
Referenced by osd_speed_warner_draw(), and osd_text_draw().
struct item* tracking_get_current_item (struct tracking * _this)
References tracking::curr_line, street_data::item, NULL, and tracking_line::street.
Referenced by osd_speed_warner_draw(), and osd_text_draw().
struct map* tracking_get_map (struct tracking * this_)
References attr::attrs, data, description(), tracking::map, map_new(), attr::navigation, NULL, attr::str, attr::tracking, type, attr::type, and attr::u.
Referenced by navit_init().
struct coord* tracking_get_pos (struct tracking * tr)
References tracking::curr_out.
Referenced by route_set_position_from_tracking().
int tracking_get_segment_pos (struct tracking * tr)
References tracking::pos.
Referenced by route_set_position_from_tracking().
struct street_data* tracking_get_street_data (struct tracking * tr)
References tracking::curr_line, NULL, and tracking_line::street.
Referenced by route_set_position_from_tracking().
int tracking_get_street_direction (struct tracking * tr)
References tracking::street_direction.
Referenced by route_set_position_from_tracking().
void tracking_init (void)
References tracking_map_new().
Referenced by main_real().
struct tracking* tracking_new (struct attr * parent, struct attr ** attrs)
References attr_generic_get_attr(), attr::attrs, callback_list_new(), g_new0, navit_object_ref(), attr::num, tracking_func, tracking_init_cdf(), tracking_set_attr_do(), and attr::u.
struct tracking* tracking_ref (struct tracking * this_)
int tracking_remove_attr (struct tracking * this_, struct attr * attr)
References attr::callback, tracking::callback_list, callback_list_remove(), attr::type, and attr::u.
int tracking_set_attr (struct tracking * tr, struct attr * attr)
References tracking_set_attr_do().
void tracking_set_mapset (struct tracking * this_, struct mapset * ms)
Referenced by navit_init().
void tracking_set_route (struct tracking * this_, struct route * rt)
Referenced by navit_init().
void tracking_unref (struct tracking * this_)
void tracking_update (struct tracking * tr, struct vehicle * v, struct vehicleprofile * vehicleprofile, enum projection pro)
Processes a position update.
Parameters
tr The
struct tracking
which will receive the position update
v The vehicle whose position has changed
vehicleprofile The vehicle profile to use
pro The projection to use for transformations
References AF_UNDERGROUND, tracking_line::angle, angle_delta(), tracking::angle_pref, attr_position_valid_invalid, attr_position_valid_static, attr_position_valid_valid, street_data::c, tracking::callback_list, callback_list_call_attr_0, tracking::cdf, tracking::connected_pref, attr::coord_geo, tracking::coord_geo_valid, street_data::count, tracking::curr, tracking::curr_angle, tracking::curr_in, tracking::curr_line, tracking::curr_out, dbg, tracking::direction, tracking::direction_matched, street_data::flags, i, iso8601_to_secs(), tracking::last, tracking::last_in, tracking::last_out, tracking::last_updated, tracking::lines, lvl_debug, lvl_error, lvl_info, tracking_line::next, tracking::no_gps, tracking::nostop_pref, NULL, attr::num, attr::numd, tracking::offroad_limit_pref, tracking::pos, tracking::pro, speed, tracking::speed, attr::str, tracking_line::street, tracking::street_direction, time(), tracking::time, tracking_angle_abs_diff(), tracking_angle_delta(), tracking_angle_diff(), tracking_doupdate_lines(), tracking_flush(), tracking_is_connected(), tracking_value(), transform_distance(), transform_distance_line_sq(), transform_from_geo(), transform_project(), tracking::tunnel, tracking::tunnel_extrapolation, attr::u, tracking::valid, value, tracking::vehicle, vehicle_get_attr(), tracking::vehicleprofile, attr::vehicleprofile, vehicleprofile_get_attr(), coord::x, and coord::y.
Referenced by navit_vehicle_update_position().