navit: support/espeak/translate.h File Reference
translate.h File Reference
Data Structures
struct MatchRecord
struct WORD_TAB
struct PHONEME_LIST2
struct PARAM_STACK
struct LANGUAGE_OPTIONS
struct CHANGEPH
struct Translator
Macros
#define L(c1, c2) (c1<<8)+c2
#define CTRL_EMBEDDED 0x01
#define REPLACED_E 'E'
#define N_WORD_PHONEMES 160
#define N_WORD_BYTES 160
#define N_CLAUSE_WORDS 300
#define N_RULE_GROUP2 120
#define N_HASH_DICT 1024
#define N_CHARSETS 20
#define N_LETTER_GROUPS 26
#define FLAG_SKIPWORDS 0x80
#define FLAG_PREPAUSE 0x100
#define FLAG_ONLY 0x200
#define FLAG_ONLY_S 0x400
#define BITNUM_FLAG_ONLY 9
#define BITNUM_FLAG_ONLY_S 10
#define FLAG_STRESS_END 0x800 /* full stress if at end of clause */
#define FLAG_STRESS_END2 0x1000 /* full stress if at end of clause, or only followed by unstressed */
#define FLAG_UNSTRESS_END 0x2000 /* reduce stress at end of clause */
#define FLAG_ATEND 0x4000 /* use this pronunciation if at end of clause */
#define FLAG_SPELLWORD 0x8000
#define FLAG_DOT 0x10000 /* ignore '.' after word (abbreviation) */
#define FLAG_ABBREV 0x20000
#define FLAG_STEM 0x40000
#define FLAG_DOUBLING 0x80000
#define FLAG_ALT_TRANS 0x100000
#define FLAG_ALT2_TRANS 0x200000
#define FLAG_MAX3 0x08000000
#define FLAG_PAUSE1 0x10000000
#define FLAG_TEXTMODE 0x20000000
#define BITNUM_FLAG_TEXTMODE 29
#define FLAG_FOUND_ATTRIBUTES 0x40000000
#define FLAG_FOUND 0x80000000
#define FLAG_VERBF 0x1 /* verb follows */
#define FLAG_VERBSF 0x2 /* verb follows, may have -s suffix */
#define FLAG_NOUNF 0x4 /* noun follows */
#define FLAG_PASTF 0x8 /* past tense follows */
#define FLAG_VERB 0x10 /* pronunciation for verb */
#define FLAG_NOUN 0x20 /* pronunciation for noun */
#define FLAG_PAST 0x40 /* pronunciation for past tense */
#define FLAG_VERB_EXT 0x100 /* extend the 'verb follows' */
#define FLAG_CAPITAL 0x200 /* pronunciation if initial letter is upper case */
#define FLAG_ALLCAPS 0x400
#define BITNUM_FLAG_ALLCAPS 0x2a
#define FLAG_ACCENT 0x800
#define FLAG_HYPHENATED 0x1000
#define BITNUM_FLAG_HYPHENATED 0x2c
#define FLAG_ALL_UPPER 0x1 /* no lower case letters in the word */
#define FLAG_FIRST_UPPER 0x2 /* first letter is upper case */
#define FLAG_UPPERS 0x3
#define FLAG_HAS_PLURAL 0x4 /* upper-case word with s or 's lower-case ending */
#define FLAG_PHONEMES 0x8 /* word is phonemes */
#define FLAG_LAST_WORD 0x10 /* last word in clause */
#define FLAG_EMBEDDED 0x40 /* word is preceded by embedded commands */
#define FLAG_HYPHEN 0x80
#define FLAG_NOSPACE 0x100
#define FLAG_FIRST_WORD 0x200
#define FLAG_FOCUS 0x400
#define FLAG_EMPHASIZED 0x800
#define FLAG_EMPHASIZED2 0xc00
#define FLAG_DONT_SWITCH_TRANSLATOR 0x1000
#define FLAG_SUFFIX_REMOVED 0x2000
#define FLAG_HYPHEN_AFTER 0x4000
#define FLAG_NO_TRACE 0x10000
#define FLAG_NO_PREFIX 0x20000
#define SUFX_E 0x0100
#define SUFX_I 0x0200
#define SUFX_P 0x0400
#define SUFX_V 0x0800
#define SUFX_D 0x1000
#define SUFX_F 0x2000
#define SUFX_Q 0x4000
#define SUFX_T 0x10000
#define SUFX_B 0x20000
#define FLAG_ALLOW_TEXTMODE 0x02
#define FLAG_SUFX 0x04
#define FLAG_SUFX_S 0x08
#define FLAG_SUFX_E_ADDED 0x10
#define RULE_PRE 1
#define RULE_POST 2
#define RULE_PHONEMES 3
#define RULE_PH_COMMON 4
#define RULE_CONDITION 5
#define RULE_GROUP_START 6
#define RULE_GROUP_END 7
#define RULE_LINENUM 8
#define RULE_SPACE 32
#define RULE_SYLLABLE 9
#define RULE_STRESSED 10
#define RULE_DOUBLE 11
#define RULE_INC_SCORE 12
#define RULE_DEL_FWD 13
#define RULE_ENDING 14
#define RULE_DIGIT 15
#define RULE_NONALPHA 16
#define RULE_LETTERGP 17
#define RULE_LETTERGP2 18
#define RULE_CAPITAL 19
#define RULE_REPLACEMENTS 20
#define RULE_NO_SUFFIX 24
#define RULE_NOTVOWEL 25
#define RULE_IFVERB 26
#define RULE_ALT1 28
#define RULE_NOVOWELS 29
#define RULE_SPELLING 31
#define RULE_LAST_RULE 31
#define LETTERGP_A 0
#define LETTERGP_B 1
#define LETTERGP_C 2
#define LETTERGP_H 3
#define LETTERGP_F 4
#define LETTERGP_G 5
#define LETTERGP_Y 6
#define LETTERGP_VOWEL2 7
#define CLAUSE_BIT_SENTENCE 0x80000
#define CLAUSE_BIT_VOICE 0x20000
#define PUNCT_IN_WORD 0x100000
#define CLAUSE_NONE 0 + 0x04000
#define CLAUSE_PARAGRAPH 70 + 0x80000
#define CLAUSE_EOF 35 + 0x90000
#define CLAUSE_VOICE 0 + 0x24000
#define CLAUSE_PERIOD 35 + 0x80000
#define CLAUSE_COMMA 20 + 0x41000
#define CLAUSE_SHORTCOMMA 4 + 0x41000
#define CLAUSE_SHORTFALL 4 + 0x40000
#define CLAUSE_QUESTION 35 + 0x82000
#define CLAUSE_EXCLAMATION 40 + 0x83000
#define CLAUSE_COLON 30 + 0x40000
#define CLAUSE_SEMICOLON 30 + 0x41000
#define SAYAS_CHARS 0x12
#define SAYAS_GLYPHS 0x13
#define SAYAS_SINGLE_CHARS 0x14
#define SAYAS_KEY 0x24
#define SAYAS_DIGITS 0x40
#define SAYAS_DIGITS1 0xc1
#define CHAR_EMPHASIS 0x0530
#define N_LOPTS 16
#define LOPT_DIERESES 1
#define LOPT_IT_LENGTHEN 2
#define LOPT_PREFIXES 3
#define LOPT_REGRESSIVE_VOICING 4
#define LOPT_UNPRONOUNCABLE 5
#define LOPT_LENGTH_MODS 6
#define LOPT_SONORANT_MIN 7
#define LOPT_WORD_MERGE 8
#define LOPT_MAXAMP_EOC 9
#define LOPT_REDUCE 10
#define LOPT_COMBINE_WORDS 11
#define LOPT_REDUCE_T 12
#define LOPT_CAPS_IN_WORD 13
#define LOPT_IT_DOUBLING 14
#define LOPT_ALT 15
#define NUM_ROMAN 0x20000
#define NUM_ROMAN_UC 0x40000
#define NUM_NOPAUSE 0x80000
#define NUM_ROMAN_AFTER 0x200000
#define NUM_VIGESIMAL 0x400000
#define NUM2_100000 0x800
#define NUM2_100000a 0xc00
#define NUM_SEP_DOT 0x0008
#define NUM_SEP_SPACE 0x1000
#define NUM_DEC_IT 0x2000
#define INTONATION_TYPES 8
#define PUNCT_INTONATIONS 6
#define OPTION_EMPHASIZE_ALLCAPS 0x100
#define OPTION_EMPHASIZE_PENULTIMATE 0x200
#define N_MARKER_LENGTH 50
#define N_PUNCTLIST 60
Typedefs
typedef const char * constcharptr
typedef struct Translator Translator
Functions
void SetLengthMods (struct Translator *tr, int value)
void LoadConfig (void)
int TransposeAlphabet (char *text, int offset, int min, int max)
int utf8_in (int *c, const char *buf)
int utf8_in2 (int *c, const char *buf, int backwards)
int utf8_out (unsigned int c, char *buf)
int utf8_nbytes (const char *buf)
int lookupwchar (const unsigned short *list, int c)
int Eof (void)
char * strchr_w (const char *s, int c)
int IsBracket (int c)
void InitNamedata (void)
void InitText (int flags)
void InitText2 (void)
int IsDigit (unsigned int c)
int IsAlpha (unsigned int c)
int isspace2 (unsigned int c)
int towlower2 (unsigned int c)
void GetTranslatedPhonemeString (char *phon_out, int n_phon_out)
struct Translator * SelectTranslator (const char *name)
int SetTranslator2 (const char *name)
void DeleteTranslator (struct Translator *tr)
int Lookup (struct Translator *tr, const char *word, char *ph_out)
int TranslateNumber (Translator *tr, char *word1, char *ph_out, unsigned int *flags, int wflags)
int TranslateRoman (Translator *tr, char *word, char *ph_out)
void ChangeWordStress (Translator *tr, char *word, int new_stress)
void SetSpellingStress (Translator *tr, char *phonemes, int control, int n_chars)
int TranslateLetter (Translator *tr, char *letter, char *phonemes, int control, int word_length)
void LookupLetter (Translator *tr, unsigned int letter, int next_byte, char *ph_buf)
void LookupAccentedLetter (Translator *tr, unsigned int letter, char *ph_buf)
int LoadDictionary (Translator *tr, const char *name, int no_error)
int LookupDictList (Translator *tr, char **wordptr, char *ph_out, unsigned int *flags, int end_flags, WORD_TAB *wtab)
void MakePhonemeList (Translator *tr, int post_pause, int new_sentence)
int ChangePhonemes_ru (Translator *tr, PHONEME_LIST2 *phlist, int n_ph, int index, PHONEME_TAB *ph, CHANGEPH *ch)
void ApplySpecialAttribute (Translator *tr, char *phonemes, int dict_flags)
void ApplySpecialAttribute2 (Translator *tr, char *phonemes, int dict_flags)
void AppendPhonemes (Translator *tr, char *string, int size, const char *ph)
void CalcLengths (Translator *tr)
void CalcPitches (Translator *tr, int clause_tone)
int RemoveEnding (Translator *tr, char *word, int end_type, char *word_copy)
int Unpronouncable (Translator *tr, char *word)
void SetWordStress (Translator *tr, char *output, unsigned int *dictionary_flags, int tonic, int prev_stress)
int TranslateRules (Translator *tr, char *p, char *phonemes, int size, char *end_phonemes, int end_flags, unsigned int *dict_flags)
int TranslateWord (Translator *tr, char *word1, int next_pause, WORD_TAB *wtab)
void * TranslateClause (Translator *tr, FILE *f_text, const void *vp_input, int *tone, char **voice_change)
int ReadClause (Translator *tr, FILE *f_in, char *buf, short *charix, int *charix_top, int n_buf, int *tone_type)
void SetVoiceStack (espeak_VOICE *v)
Variables
PARAM_STACK param_stack []
const int param_defaults [N_SPEECH_PARAM]
int option_tone2
int option_tone_flags
int option_waveout
int option_quiet
int option_phonemes
int option_phoneme_events
int option_linelength
int option_multibyte
int option_capitals
int option_punctuation
int option_endpause
int option_ssml
int option_phoneme_input
int option_phoneme_variants
int option_sayas
int option_wordgap
int count_characters
int count_words
int count_sentences
int skip_characters
int skip_words
int skip_sentences
int skipping_text
int end_character_position
int clause_start_char
int clause_start_word
char * namedata
int pre_pause
char skip_marker [N_MARKER_LENGTH]
wchar_t option_punctlist [N_PUNCTLIST]
unsigned char punctuation_to_tone [INTONATION_TYPES][PUNCT_INTONATIONS]
struct Translator * translator
struct Translator * translator2
const unsigned short * charsets [N_CHARSETS]
char dictionary_name [40]
char ctrl_embedded
unsigned char * p_textinput
wchar_t * p_wchar_input
int dictionary_skipwords
int(* uri_callback)(int, const char *, const char *)
int(* phoneme_callback)(const char *)
FILE * f_trans
Macro Definition Documentation
#define BITNUM_FLAG_ALLCAPS 0x2a
Referenced by compile_line().
#define BITNUM_FLAG_HYPHENATED 0x2c
Referenced by compile_line().
#define BITNUM_FLAG_ONLY 9
#define BITNUM_FLAG_ONLY_S 10
Referenced by compile_line().
#define BITNUM_FLAG_TEXTMODE 29
Referenced by compile_line().
#define CHAR_EMPHASIS 0x0530
Referenced by ReadClause(), and TranslateClause().
#define CLAUSE_BIT_SENTENCE 0x80000
Referenced by TranslateClause().
#define CLAUSE_BIT_VOICE 0x20000
Referenced by GetVoiceAttributes(), ReadClause(), and TranslateClause().
#define CLAUSE_COLON 30 + 0x40000
Referenced by ProcessSsmlTag(), and ReadClause().
#define CLAUSE_COMMA 20 + 0x41000
Referenced by AnnouncePunctuation().
#define CLAUSE_EOF 35 + 0x90000
Referenced by ReadClause().
#define CLAUSE_EXCLAMATION 40 + 0x83000
Referenced by ReadClause().
#define CLAUSE_NONE 0 + 0x04000
Referenced by AnnouncePunctuation(), ProcessSsmlTag(), and ReadClause().
#define CLAUSE_PARAGRAPH 70 + 0x80000
Referenced by ProcessSsmlTag(), and ReadClause().
#define CLAUSE_PERIOD 35 + 0x80000
Referenced by ProcessSsmlTag(), ReadClause(), and TranslateClause().
#define CLAUSE_QUESTION 35 + 0x82000
Referenced by ReadClause().
#define CLAUSE_SEMICOLON 30 + 0x41000
#define CLAUSE_SHORTCOMMA 4 + 0x41000
Referenced by AnnouncePunctuation().
#define CLAUSE_SHORTFALL 4 + 0x40000
Referenced by AnnouncePunctuation().
#define CLAUSE_VOICE 0 + 0x24000
Referenced by ProcessSsmlTag(), and ReadClause().
#define CTRL_EMBEDDED 0x01
Referenced by ProcessParamStack(), ProcessSsmlTag(), ReadClause(), and TranslateClause().
#define FLAG_ABBREV 0x20000
Referenced by TranslateWord().
#define FLAG_ACCENT 0x800
Referenced by LookupDictList().
#define FLAG_ALL_UPPER 0x1 /* no lower case letters in the word */
Referenced by LookupDict2(), TranslateClause(), TranslateWord(), and TranslateWord2().
#define FLAG_ALLCAPS 0x400
Referenced by LookupDict2().
#define FLAG_ALLOW_TEXTMODE 0x02
Referenced by LookupDictList(), and TranslateWord().
#define FLAG_ALT2_TRANS 0x200000
Referenced by ApplySpecialAttribute(), ApplySpecialAttribute2(), TranslateWord(), and TranslateWord2().
#define FLAG_ALT_TRANS 0x100000
Referenced by ApplySpecialAttribute(), MatchRule(), TranslateWord(), and TranslateWord2().
#define FLAG_ATEND 0x4000 /* use this pronunciation if at end of clause */
Referenced by LookupDict2().
#define FLAG_CAPITAL 0x200 /* pronunciation if initial letter is upper case */
Referenced by LookupDict2().
#define FLAG_DONT_SWITCH_TRANSLATOR 0x1000
Referenced by TranslateRules().
#define FLAG_DOT 0x10000 /* ignore '.' after word (abbreviation) */
Referenced by TranslateClause(), and TranslateWord().
#define FLAG_DOUBLING 0x80000
Referenced by TranslateWord2().
#define FLAG_EMBEDDED 0x40 /* word is preceded by embedded commands */
Referenced by TranslateClause(), and TranslateWord2().
#define FLAG_EMPHASIZED 0x800
Referenced by EmbeddedCommand(), and TranslateWord().
#define FLAG_EMPHASIZED2 0xc00
Referenced by LookupDict2(), and TranslateWord().
#define FLAG_FIRST_UPPER 0x2 /* first letter is upper case */
Referenced by LookupDict2(), MatchRule(), TranslateClause(), TranslateWord(), and TranslateWord2().
#define FLAG_FIRST_WORD 0x200
Referenced by TranslateClause(), and TranslateWord2().
#define FLAG_FOCUS 0x400
Referenced by TranslateClause().
#define FLAG_FOUND 0x80000000
Referenced by LookupDict2(), TranslateNumber_1(), and TranslateWord2().
#define FLAG_FOUND_ATTRIBUTES 0x40000000
Referenced by LookupDict2().
#define FLAG_HAS_PLURAL 0x4 /* upper-case word with s or 's lower-case ending */
Referenced by TranslateClause(), and TranslateWord().
#define FLAG_HYPHEN 0x80
Referenced by MatchRule(), TranslateClause(), and TranslateWord2().
#define FLAG_HYPHEN_AFTER 0x4000
Referenced by LookupDict2(), MatchRule(), and TranslateClause().
#define FLAG_HYPHENATED 0x1000
Referenced by LookupDict2().
#define FLAG_LAST_WORD 0x10 /* last word in clause */
Referenced by TranslateClause(), TranslateWord(), and TranslateWord2().
#define FLAG_MAX3 0x08000000
Referenced by LookupDictList().
#define FLAG_NO_PREFIX 0x20000
Referenced by TranslateRules(), and TranslateWord().
#define FLAG_NO_TRACE 0x10000
Referenced by LookupLetter(), MatchRule(), TranslateRules(), and TranslateWord().
#define FLAG_NOSPACE 0x100
Referenced by TranslateClause().
#define FLAG_NOUN 0x20 /* pronunciation for noun */
Referenced by LookupDict2().
#define FLAG_NOUNF 0x4 /* noun follows */
Referenced by TranslateWord().
#define FLAG_ONLY 0x200
Referenced by LookupDict2().
#define FLAG_ONLY_S 0x400
Referenced by LookupDict2().
#define FLAG_PAST 0x40 /* pronunciation for past tense */
Referenced by LookupDict2().
#define FLAG_PASTF 0x8 /* past tense follows */
Referenced by TranslateWord().
#define FLAG_PAUSE1 0x10000000
Referenced by TranslateWord(), and TranslateWord2().
#define FLAG_PHONEMES 0x8 /* word is phonemes */
Referenced by TranslateClause(), and TranslateWord2().
#define FLAG_PREPAUSE 0x100
Referenced by TranslateWord2().
#define FLAG_SKIPWORDS 0x80
Referenced by LookupDict2(), LookupDictList(), TranslateClause(), TranslateNumber_1(), TranslateWord(), and TranslateWord2().
#define FLAG_SPELLWORD 0x8000
Referenced by TranslateClause(), TranslateRules(), TranslateWord(), and TranslateWord2().
#define FLAG_STEM 0x40000
Referenced by LookupDict2().
#define FLAG_STRESS_END 0x800 /* full stress if at end of clause */
Referenced by LookupDict2(), and TranslateWord().
#define FLAG_STRESS_END2 0x1000 /* full stress if at end of clause, or only followed by unstressed */
Referenced by SetWordStress(), TranslateWord(), and TranslateWord2().
#define FLAG_SUFFIX_REMOVED 0x2000
Referenced by MatchRule(), and TranslateWord().
#define FLAG_SUFX 0x04
Referenced by LookupDict2(), RemoveEnding(), and TranslateWord().
#define FLAG_SUFX_E_ADDED 0x10
Referenced by LookupDictList(), and RemoveEnding().
#define FLAG_SUFX_S 0x08
Referenced by LookupDict2(), and RemoveEnding().
#define FLAG_TEXTMODE 0x20000000
Referenced by LookupDict2(), LookupDictList(), and TranslateWord().
#define FLAG_UNSTRESS_END 0x2000 /* reduce stress at end of clause */
Referenced by TranslateWord().
#define FLAG_UPPERS 0x3
Referenced by TranslateWord().
#define FLAG_VERB 0x10 /* pronunciation for verb */
Referenced by LookupDict2().
#define FLAG_VERB_EXT 0x100 /* extend the 'verb follows' */
Referenced by TranslateWord().
#define FLAG_VERBF 0x1 /* verb follows */
Referenced by TranslateWord().
#define FLAG_VERBSF 0x2 /* verb follows, may have -s suffix */
Referenced by TranslateWord().
#define INTONATION_TYPES 8
Referenced by CalcPitches().
#define L (c1, c2) (c1<<8)+c2
#define LETTERGP_A 0
Referenced by copy_rule_string(), SelectTranslator(), and SetIndicLetters().
#define LETTERGP_B 1
Referenced by copy_rule_string(), SelectTranslator(), and SetIndicLetters().
#define LETTERGP_C 2
Referenced by copy_rule_string(), SelectTranslator(), and SetIndicLetters().
#define LETTERGP_F 4
Referenced by copy_rule_string(), and SelectTranslator().
#define LETTERGP_G 5
Referenced by copy_rule_string(), and SelectTranslator().
#define LETTERGP_H 3
Referenced by copy_rule_string().
#define LETTERGP_VOWEL2 7
Referenced by MatchRule(), and RemoveEnding().
#define LETTERGP_Y 6
Referenced by copy_rule_string(), SelectTranslator(), and SetIndicLetters().
#define LOPT_ALT 15
Referenced by SelectTranslator(), and TranslateWord().
#define LOPT_CAPS_IN_WORD 13
Referenced by SelectTranslator(), and TranslateClause().
#define LOPT_COMBINE_WORDS 11
Referenced by SelectTranslator(), and TranslateWord2().
#define LOPT_DIERESES 1
Referenced by SelectTranslator(), and TranslateRules().
#define LOPT_IT_DOUBLING 14
Referenced by SelectTranslator(), and TranslateWord2().
#define LOPT_IT_LENGTHEN 2
Referenced by SelectTranslator(), and SetWordStress().
#define LOPT_LENGTH_MODS 6
Referenced by LoadVoice().
#define LOPT_MAXAMP_EOC 9
Referenced by CalcLengths(), and NewTranslator().
#define LOPT_PREFIXES 3
Referenced by SelectTranslator(), and TranslateWord().
#define LOPT_REDUCE 10
Referenced by MakePhonemeList(), SelectTranslator(), and Translator_Russian().
#define LOPT_REDUCE_T 12
Referenced by MakePhonemeList().
#define LOPT_REGRESSIVE_VOICING 4
Referenced by MakePhonemeList(), SelectTranslator(), and Translator_Russian().
#define LOPT_SONORANT_MIN 7
Referenced by DoSpect(), NewTranslator(), and SelectTranslator().
#define LOPT_UNPRONOUNCABLE 5
Referenced by NewTranslator(), SelectTranslator(), SetIndicLetters(), Translator_Russian(), and Unpronouncable().
#define LOPT_WORD_MERGE 8
Referenced by Generate(), and SelectTranslator().
#define N_CHARSETS 20
Referenced by LoadVoice().
#define N_CLAUSE_WORDS 300
Referenced by TranslateClause().
#define N_HASH_DICT 1024
Referenced by compile_dictlist_end(), compile_dictlist_start(), CompileDictionary(), and LoadDictionary().
#define N_LETTER_GROUPS 26
Referenced by compile_lettergroup(), copy_rule_string(), and InitGroups().
#define N_LOPTS 16
Referenced by LoadVoice().
#define N_MARKER_LENGTH 50
#define N_PUNCTLIST 60
#define N_RULE_GROUP2 120
Referenced by compile_dictrules().
#define N_WORD_BYTES 160
Referenced by compile_line(), LookupDict2(), LookupDictList(), TranslateRoman(), TranslateRules(), TranslateWord(), and TranslateWord2().
#define N_WORD_PHONEMES 160
Referenced by ChangeWordStress(), GetVowelStress(), LookupDict2(), SetSpellingStress(), SetWordStress(), TranslateLetter(), TranslateNumber_1(), TranslateWord(), and TranslateWord2().
#define NUM2_100000 0x800
Referenced by SelectTranslator(), and TranslateClause().
#define NUM2_100000a 0xc00
Referenced by SelectTranslator(), and TranslateClause().
#define NUM_DEC_IT 0x2000
#define NUM_NOPAUSE 0x80000
Referenced by SelectTranslator(), and TranslateNumber_1().
#define NUM_ROMAN 0x20000
Referenced by SelectTranslator(), and TranslateWord().
#define NUM_ROMAN_AFTER 0x200000
Referenced by SelectTranslator(), and TranslateRoman().
#define NUM_ROMAN_UC 0x40000
Referenced by SelectTranslator(), and TranslateWord().
#define NUM_SEP_DOT 0x0008
#define NUM_SEP_SPACE 0x1000
#define NUM_VIGESIMAL 0x400000
Referenced by LookupNum2(), and SelectTranslator().
#define OPTION_EMPHASIZE_ALLCAPS 0x100
Referenced by TranslateWord().
#define OPTION_EMPHASIZE_PENULTIMATE 0x200
Referenced by calc_pitches().
#define PUNCT_IN_WORD 0x100000
Referenced by ReadClause().
#define PUNCT_INTONATIONS 6
#define REPLACED_E 'E'
Referenced by MatchRule(), RemoveEnding(), and TranslateRules().
#define RULE_ALT1 28
Referenced by copy_rule_string(), and MatchRule().
#define RULE_CAPITAL 19
Referenced by copy_rule_string(), and MatchRule().
#define RULE_CONDITION 5
Referenced by compile_rule(), DecodeRule(), and MatchRule().
#define RULE_DEL_FWD 13
Referenced by copy_rule_string(), and MatchRule().
#define RULE_DIGIT 15
Referenced by copy_rule_string(), and MatchRule().
#define RULE_DOUBLE 11
Referenced by copy_rule_string(), and MatchRule().
#define RULE_ENDING 14
Referenced by copy_rule_string(), DecodeRule(), and MatchRule().
#define RULE_GROUP_END 7
Referenced by compile_dictrules(), compile_lettergroup(), InitGroups(), IsLetterGroup(), and MatchRule().
#define RULE_GROUP_START 6
Referenced by compile_dictrules(), compile_lettergroup(), and InitGroups().
#define RULE_IFVERB 26
Referenced by copy_rule_string(), and MatchRule().
#define RULE_INC_SCORE 12
Referenced by copy_rule_string(), and MatchRule().
#define RULE_LAST_RULE 31
Referenced by DecodeRule().
#define RULE_LETTERGP 17
Referenced by copy_rule_string(), DecodeRule(), and MatchRule().
#define RULE_LETTERGP2 18
Referenced by compile_lettergroup(), copy_rule_string(), DecodeRule(), InitGroups(), and MatchRule().
#define RULE_LINENUM 8
Referenced by compile_rule(), DecodeRule(), and MatchRule().
#define RULE_NO_SUFFIX 24
Referenced by copy_rule_string(), and MatchRule().
#define RULE_NONALPHA 16
Referenced by copy_rule_string(), and MatchRule().
#define RULE_NOTVOWEL 25
Referenced by copy_rule_string(), and MatchRule().
#define RULE_NOVOWELS 29
Referenced by copy_rule_string(), and MatchRule().
#define RULE_PH_COMMON 4
Referenced by DecodeRule(), MatchRule(), and output_rule_group().
#define RULE_PHONEMES 3
Referenced by DecodeRule(), MatchRule(), and output_rule_group().
#define RULE_POST 2
Referenced by compile_rule(), DecodeRule(), and MatchRule().
#define RULE_PRE 1
Referenced by compile_rule(), DecodeRule(), and MatchRule().
#define RULE_REPLACEMENTS 20
Referenced by compile_dictrules(), and InitGroups().
#define RULE_SPACE 32
Referenced by copy_rule_string(), DecodeRule(), and MatchRule().
#define RULE_SPELLING 31
Referenced by copy_rule_string(), and LookupLetter().
#define RULE_STRESSED 10
Referenced by copy_rule_string(), and MatchRule().
#define RULE_SYLLABLE 9
Referenced by copy_rule_string(), and MatchRule().
#define SAYAS_CHARS 0x12
Referenced by ProcessSsmlTag().
#define SAYAS_DIGITS 0x40
Referenced by ProcessSsmlTag(), and TranslateClause().
#define SAYAS_DIGITS1 0xc1
Referenced by ProcessSsmlTag(), and TranslateNumber().
#define SAYAS_GLYPHS 0x13
Referenced by ProcessSsmlTag().
#define SAYAS_KEY 0x24
Referenced by ProcessSsmlTag(), ReadClause(), TranslateClause(), and TranslateWord().
#define SAYAS_SINGLE_CHARS 0x14
Referenced by ProcessSsmlTag(), and ReadClause().
#define SUFX_B 0x20000
Referenced by copy_rule_string(), and TranslateWord().
#define SUFX_D 0x1000
Referenced by copy_rule_string(), and LookupDictList().
#define SUFX_E 0x0100
Referenced by copy_rule_string(), and RemoveEnding().
#define SUFX_F 0x2000
Referenced by copy_rule_string(), and TranslateWord().
#define SUFX_I 0x0200
Referenced by copy_rule_string(), and RemoveEnding().
#define SUFX_P 0x0400
Referenced by copy_rule_string(), DecodeRule(), LookupDict2(), TranslateRules(), and TranslateWord().
#define SUFX_Q 0x4000
Referenced by copy_rule_string(), and TranslateWord().
#define SUFX_T 0x10000
Referenced by copy_rule_string(), and TranslateWord().
#define SUFX_V 0x0800
Referenced by copy_rule_string(), RemoveEnding(), and TranslateWord().
Typedef Documentation
typedef const char* constcharptr
typedef struct Translator Translator
Function Documentation
void AppendPhonemes (Translator * tr, char * string, int size, const char * ph)
References c, length, n_phoneme_tab, NULL, p, phoneme_tab, phSTRESS, phUNSTRESSED, phVOWEL, type, Translator::word_stressed_count, and Translator::word_vowel_count.
Referenced by TranslateRules(), and TranslateWord().
void ApplySpecialAttribute (Translator * tr, char * phonemes, int dict_flags)
References FLAG_ALT2_TRANS, FLAG_ALT_TRANS, L, PhonemeCode(), PhonemeCode2, phonSCHWA, phonSTRESS_P, phonSTRESS_PREV, and Translator::translator_name.
Referenced by TranslateRules(), and TranslateWord().
void ApplySpecialAttribute2 (Translator * tr, char * phonemes, int dict_flags)
References FLAG_ALT2_TRANS, L, p, PhonemeCode(), phonSTRESS_P, and Translator::translator_name.
Referenced by TranslateWord().
void CalcLengths (Translator * tr)
References PHONEME_LIST::amp, PHONEME_TAB::code, DoEmbedded2(), embedded_ix, PHONEME_LIST::env, envelope_data, Translator::langopts, PHONEME_LIST::length, PHONEME_TAB::length_mod, LANGUAGE_OPTIONS::length_mods, LANGUAGE_OPTIONS::length_mods0, LANGUAGE_OPTIONS::long_stop, LookupEnvelope(), LOPT_MAXAMP_EOC, min_drop, PHONEME_TAB::mnemonic, n_phoneme_list, PHONEME_LIST::newword, next, NULL, p, LANGUAGE_OPTIONS::param, PHONEME_LIST::ph, phBRKAFTER, PHONEME_TAB::phflags, phFORTIS, phFRICATIVE, phLENGTHENSTOP, phLIQUID, phNASAL, phNONSYLLABIC, phoneme_list, phoneme_tab, phonPAUSE_CLAUSE, phonPAUSE_VSHORT, phPAUSE, phSIBILANT, phSTOP, phVFRICATIVE, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PITCHfall, PITCHrise, PHONEME_LIST::prepause, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_SEQCONTINUE, SFLAG_SYLLABLE, PHONEME_TAB::spect, speed1, speed2, speed3, PHONEME_TAB::std_length, Translator::stress_amps, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, PHONEME_LIST::stresslevel, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, type, PHONEME_LIST::type, and LANGUAGE_OPTIONS::word_gap.
Referenced by SpeakNextClause().
void CalcPitches (Translator * tr, int clause_tone)
References calc_pitches(), CalcPitches_Tone(), PHONEME_TAB::code, count_pitch_vowels(), PHONEME_TAB::end_type, SYLLABLE::env, PHONEME_LIST::env, SYLLABLE::flags, LANGUAGE_OPTIONS::intonation_group, INTONATION_TYPES, Translator::langopts, N_PHONEME_LIST, n_phoneme_list, SYLLABLE::nextph_type, no_tonic, p, PHONEME_LIST::ph, phoneme_list, phoneme_tab, phonPAUSE_CLAUSE, SYLLABLE::pitch1, PHONEME_LIST::pitch1, SYLLABLE::pitch2, PHONEME_LIST::pitch2, PITCHfall, PITCHrise, Translator::punct_to_tone, SFLAG_SYLLABLE, PHONEME_TAB::start_type, SYLLABLE::stress, PHONEME_LIST::stresslevel, SYL_EMPHASIS, SYL_END_CLAUSE, SYL_RISE, PHONEME_LIST::synthflags, LANGUAGE_OPTIONS::tone_language, PHONEME_LIST::tone_ph, and PHONEME_LIST::type.
Referenced by SpeakNextClause().
int ChangePhonemes_ru (Translator * tr, PHONEME_LIST2 * phlist, int n_ph, int index, PHONEME_TAB * ph, CHANGEPH * ch)
References CHANGEPH::flags, PHONEME_TAB::mnemonic, N_VOWELS_RU, next, PH, PHONEME_LIST2::phcode, PHONEME_TAB::phflags, phoneme_tab, PhonemeCode(), phPALATAL, phVOWEL, PHONEME_TAB::type, CHANGEPH::vowel_stressed, and CHANGEPH::vowel_this.
Referenced by ChangePhonemes().
void ChangeWordStress (Translator * tr, char * word, int new_stress)
References GetVowelStress(), N_WORD_PHONEMES, p, phNONSYLLABIC, phoneme_tab, phVOWEL, stress_phonemes, and type.
Referenced by TranslateWord().
void DeleteTranslator (struct Translator * tr)
References Translator::data_dictlist, Free(), and NULL.
Referenced by LoadVoice(), and SetTranslator2().
int Eof (void)
References end_of_input, f_input, and ungot_char.
Referenced by GetC(), ReadClause(), and TranslateClause().
void GetTranslatedPhonemeString (char * phon_out, int n_phon_out)
References PHONEME_TAB::code, PHONEME_TAB::mnemonic, n_phoneme_list, PHONEME_TAB_LIST::name, PHONEME_LIST::newword, NULL, p, PHONEME_LIST::ph, phoneme_list, phoneme_tab, phoneme_tab_list, phonLENGTHEN, phonSWITCH, phonSYLLABIC, phVOWEL, SFLAG_LENGTHEN, SFLAG_SYLLABLE, PHONEME_LIST::stresslevel, PHONEME_LIST::synthflags, PHONEME_LIST::tone_ph, PHONEME_LIST::type, and WriteMnemonic().
Referenced by SpeakNextClause().
void InitNamedata (void)
References n_namedata, namedata, namedata_ix, and NULL.
Referenced by initialise(), and InitText().
void InitText (int flags)
References count_sentences, count_words, embedded_flag, end_character_position, espeakKEEP_NAMEDATA, InitNamedata(), InitText2(), new_sentence, option_emphasis, option_sayas, option_sayas2, prev_clause_pause, skip_characters, skip_marker, skip_sentences, skip_words, skipping_text, and word_emphasis.
Referenced by main(), sync_espeak_Synth(), and sync_espeak_Synth_Mark().
void InitText2 (void)
References clear_skipping_text, count_characters, current_voice_id, espeakCAPITALS, espeakPUNCTUATION, ignore_text, n_param_stack, N_SPEECH_PARAM, n_ssml_stack, NULL, option_capitals, option_punctuation, sayas_mode, speech_parameters, SSML_STACK::tag_type, ungot_char, and xmlbase.
Referenced by InitText().
int IsAlpha (unsigned int c)
Referenced by ReadClause(), TranslateClause(), TranslateRules(), TranslateWord(), TranslateWord2(), and Unpronouncable_en().
int IsBracket (int c)
References brackets, and lookupwchar().
Referenced by ReadClause(), TranslateClause(), and TranslateRules().
int IsDigit (unsigned int c)
Referenced by compile_rule(), MatchRule(), TranslateClause(), and TranslateRules().
int isspace2 (unsigned int c)
References c2.
Referenced by compile_dictrules(), compile_lettergroup(), compile_line(), copy_rule_string(), and TranslateClause().
void LoadConfig (void)
References Alloc(), buf, c1, SOUND_ICON::data, SOUND_ICON::filename, SOUND_ICON::length, N_SOUNDICON_SLOTS, n_soundicon_tab, SOUND_ICON::name, NULL, option_device_number, p, path_home, PATHSEP, ReadTonePoints(), soundicon_tab, sprintf(), and tone_points.
Referenced by initialise().
int LoadDictionary (Translator * tr, const char * name, int no_error)
References Alloc(), Translator::data_dictlist, Translator::data_dictrules, Translator::dict_hashtab, dictionary_name, fprintf(), Free(), GetFileLength(), Translator::groups1, InitGroups(), length, N_HASH_DICT, NULL, p, path_home, PATHSEP, reverse_word_bytes(), size, and sprintf().
Referenced by CompileDictionary(), LoadVoice(), and SetTranslator2().
int Lookup (struct Translator * tr, const char * word, char * ph_out)
References LookupDictList(), and NULL.
Referenced by LookupAccentedLetter(), LookupLetter(), LookupLetter2(), LookupNum2(), LookupNum3(), LookupThousands(), TranslateLetter(), TranslateNumber_1(), TranslateRoman(), TranslateRules(), and TranslateWord().
void LookupAccentedLetter (Translator * tr, unsigned int letter, char * ph_buf)
References LANGUAGE_OPTIONS::accents, ACCENTS::flags, Translator::langopts, letter_accents_0e0, letter_accents_250, Lookup(), LookupLetter2(), name, non_ascii_tab, phonPAUSE_VSHORT, phonSTRESS_2, phonSTRESS_P, and sprintf().
Referenced by LookupDictList(), and LookupLetter().
int LookupDictList (Translator * tr, char ** wordptr, char * ph_out, unsigned int * flags, int end_flags, WORD_TAB * wtab)
References c, dictionary_skipwords, f_trans, FLAG_ACCENT, FLAG_ALLOW_TEXTMODE, FLAG_MAX3, FLAG_SKIPWORDS, FLAG_SUFX_E_ADDED, FLAG_TEXTMODE, fprintf(), Translator::langopts, length, LookupAccentedLetter(), LookupDict2(), N_WORD_BYTES, option_phonemes, Translator::phonemes_repeat, Translator::phonemes_repeat_count, sprintf(), strncpy0(), SUFX_D, LANGUAGE_OPTIONS::textmode, utf8_in(), and utf8_nbytes().
Referenced by Lookup(), LookupCharName(), LookupSpecial(), and TranslateWord().
void LookupLetter (Translator * tr, unsigned int letter, int next_byte, char * ph_buf)
References FLAG_NO_TRACE, L, Lookup(), LookupAccentedLetter(), NULL, p, phoneme_tab, voice_t::phoneme_tab_ix, phonSTRESS_P, phonSWITCH, phSTRESS, ptr, RULE_SPELLING, SelectPhonemeTable(), SetTranslator2(), sprintf(), TranslateRules(), translator2, Translator::translator_name, type, utf8_out(), and voice.
Referenced by TranslateLetter(), and TranslateRules().
int lookupwchar (const unsigned short * list, int c)
Referenced by AnnouncePunctuation(), IsBracket(), ReadClause(), TranslateClause(), and TranslateRules().
void MakePhonemeList (Translator * tr, int post_pause, int new_sentence)
References PHONEME_TAB::alternative_ph, PHONEME_LIST::amp, PHONEME_TAB::code, PHONEME_LIST::env, Translator::langopts, PHONEME_LIST::length, PHONEME_TAB::link_out, LOPT_REDUCE, LOPT_REDUCE_T, LOPT_REGRESSIVE_VOICING, PHONEME_TAB::mnemonic, n_ph_list2, N_PHONEME_LIST, n_phoneme_list, PHONEME_LIST::newword, next, NULL, option_wordgap, LANGUAGE_OPTIONS::param, pause_phonemes, PHONEME_LIST::ph, ph_list2, phALTERNATIVE, phAPPENDPH, phBEFORE_R, phBEFORENOTVOWEL, phBEFORENOTVOWEL2, phBEFOREPAUSE, phBEFOREVOWEL, phBEFOREVOWELPAUSE, PHONEME_LIST2::phcode, PHONEME_TAB::phflags, phFRICATIVE, phLIQUID, phNASAL, phoneme_list, phoneme_tab, phonPAUSE, phonPAUSE_LONG, phonPAUSE_NOLINK, phonPAUSE_SHORT, phonPAUSE_VSHORT, phonSWITCH, phonT_REDUCED, phPAUSE, phRHOTIC, phSTOP, phSWITCHVOICING, phVFRICATIVE, phVOICED, phVOWEL, phVSTOP, PHONEME_LIST::pitch1, PHONEME_LIST::pitch2, PITCHfall, PHONEME_LIST::prepause, PHONEME_TAB::reduce_to, SelectPhonemeTable(), SFLAG_DICTIONARY, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_PROMOTE_STRESS, SFLAG_SWITCHED_LANG, SFLAG_SYLLABLE, PHONEME_LIST::sourceix, PHONEME_LIST2::sourceix, PHONEME_TAB::std_length, PHONEME_LIST2::stress, LANGUAGE_OPTIONS::stress_flags, PHONEME_LIST::stresslevel, SubstitutePhonemes(), PHONEME_LIST::synthflags, PHONEME_LIST2::synthflags, PHONEME_LIST2::tone_number, PHONEME_LIST::tone_ph, PHONEME_TAB::type, type, PHONEME_LIST::type, voicing, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by TranslateClause().
int ReadClause (Translator * tr, FILE * f_in, char * buf, short * charix, int * charix_top, int n_buf, int * tone_type)
References AnnouncePunctuation(), c1, c2, CHAR_EMPHASIS, CLAUSE_BIT_VOICE, CLAUSE_COLON, CLAUSE_EOF, CLAUSE_EXCLAMATION, Translator::clause_lower_count, CLAUSE_NONE, CLAUSE_PARAGRAPH, CLAUSE_PERIOD, CLAUSE_QUESTION, clause_start_char, Translator::clause_upper_count, CLAUSE_VOICE, clear_skipping_text, count_characters, CTRL_EMBEDDED, ctrl_embedded, current_voice_id, end_character_position, end_of_input, Eof(), espeakSILENCE, f_input, GetC(), ignore_text, IsAlpha(), IsBracket(), Translator::langopts, LookupMnem(), LookupSpecial(), lookupwchar(), N_XML_BUF, N_XML_BUF2, NULL, LANGUAGE_OPTIONS::numbers, option_capitals, option_linelength, option_phoneme_input, option_punctlist, option_punctuation, option_ssml, p, ProcessSsmlTag(), punct_attributes, punct_chars, PUNCT_IN_WORD, SAYAS_KEY, sayas_mode, SAYAS_SINGLE_CHARS, skip_characters, skipping_text, speech_parameters, sprintf(), ssml_ignore_l_angle, tone_punct_off, tone_punct_on, Translator::translator_name, UngetC(), ungot_char, ungot_char2, ungot_word, and utf8_out().
Referenced by TranslateClause().
int RemoveEnding (Translator * tr, char * word, int end_type, char * word_copy)
References Translator::expect_verb, f_trans, FLAG_SUFX, FLAG_SUFX_E_ADDED, FLAG_SUFX_S, fprintf(), i, IsLetter(), LETTERGP_VOWEL2, NULL, option_phonemes, p, REPLACED_E, SUFX_E, SUFX_I, and SUFX_V.
Referenced by TranslateWord().
struct Translator* SelectTranslator (const char * name)
References LANGUAGE_OPTIONS::accents, Translator::char_plus_apostrophe, Translator::charset_a0, charsets, LANGUAGE_OPTIONS::decimal_sep, LANGUAGE_OPTIONS::ideographs, LANGUAGE_OPTIONS::intonation_group, L, L_grc, L_jbo, L_pap, L_zhy, Translator::langopts, LANGUAGE_OPTIONS::length_mods, LANGUAGE_OPTIONS::length_mods0, Translator::letter_bits, Translator::letter_bits_offset, Translator::letter_groups, LETTERGP_A, LETTERGP_B, LETTERGP_C, LETTERGP_F, LETTERGP_G, LETTERGP_Y, LANGUAGE_OPTIONS::listx, LANGUAGE_OPTIONS::long_stop, LOPT_ALT, LOPT_CAPS_IN_WORD, LOPT_COMBINE_WORDS, LOPT_DIERESES, LOPT_IT_DOUBLING, LOPT_IT_LENGTHEN, LOPT_PREFIXES, LOPT_REDUCE, LOPT_REGRESSIVE_VOICING, LOPT_SONORANT_MIN, LOPT_UNPRONOUNCABLE, LOPT_WORD_MERGE, LANGUAGE_OPTIONS::max_initial_consonants, LANGUAGE_OPTIONS::max_roman, NewTranslator(), NULL, NUM2_100000, NUM2_100000a, NUM_NOPAUSE, NUM_ROMAN, NUM_ROMAN_AFTER, NUM_ROMAN_UC, NUM_VIGESIMAL, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, OFFSET_ARMENIAN, OFFSET_BENGALI, OFFSET_DEVANAGARI, OFFSET_GREEK, OFFSET_KANNADA, OFFSET_KOREAN, OFFSET_MALAYALAM, OFFSET_TAMIL, LANGUAGE_OPTIONS::param, Translator::punct_within_word, LANGUAGE_OPTIONS::replace_chars, replace_cyrillic_latin, ResetLetterBits(), SetIndicLetters(), SetLengthMods(), SetLetterBits(), SetLetterBitsRange(), SetLetterVowel(), SetupTranslator(), LANGUAGE_OPTIONS::spelling_stress, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, LANGUAGE_OPTIONS::stress_rule, LANGUAGE_OPTIONS::textmode, LANGUAGE_OPTIONS::thousands_sep, LANGUAGE_OPTIONS::tone_language, LANGUAGE_OPTIONS::tone_numbers, Translator::translator_name, Translator_Russian(), LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by LoadVoice(), and SetTranslator2().
void SetLengthMods (struct Translator * tr, int value)
References Translator::langopts, length_mod_tabs, LANGUAGE_OPTIONS::length_mods, and LANGUAGE_OPTIONS::length_mods0.
Referenced by LoadVoice(), NewTranslator(), and SelectTranslator().
void SetSpellingStress (Translator * tr, char * phonemes, int control, int n_chars)
References buf, c, Translator::langopts, N_WORD_PHONEMES, phonPAUSE, phonPAUSE_NOLINK, phonPAUSE_SHORT, phonSTRESS_3, phonSTRESS_P, and LANGUAGE_OPTIONS::spelling_stress.
Referenced by TranslateWord().
int SetTranslator2 (const char * name)
References DeleteTranslator(), LoadDictionary(), NULL, voice_t::phoneme_tab_ix, SelectPhonemeTable(), SelectPhonemeTableName(), SelectTranslator(), translator2_language, and voice.
Referenced by LookupCharName(), LookupLetter(), TranslateLetter(), and TranslateWord2().
void SetVoiceStack (espeak_VOICE * v)
References espeak_VOICE::age, espeak_VOICE::gender, SSML_STACK::language, espeak_VOICE::languages, espeak_VOICE::name, NULL, espeak_VOICE::variant, SSML_STACK::voice_age, SSML_STACK::voice_gender, SSML_STACK::voice_name, and SSML_STACK::voice_variant.
Referenced by initialise(), SetVoiceByName(), and SetVoiceByProperties().
void SetWordStress (Translator * tr, char * output, unsigned int * dictionary_flags, int tonic, int prev_stress)
References FLAG_STRESS_END2, GetVowelStress(), Translator::langopts, LOPT_IT_LENGTHEN, PHONEME_TAB::mnemonic, n_phoneme_tab, N_WORD_PHONEMES, NULL, p, LANGUAGE_OPTIONS::param, pause_phonemes, PHONEME_TAB::phflags, phLONG, phNONSYLLABIC, phoneme_tab, phonLENGTHEN, phonPAUSE_NOLINK, phonPAUSE_VSHORT, phonSCHWA, phonSYLLABIC, phPAUSE, phSTOP, phSTRESS, phVOWEL, Translator::prev_last_stress, LANGUAGE_OPTIONS::stress_flags, stress_phonemes, LANGUAGE_OPTIONS::stress_rule, PHONEME_TAB::type, type, LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, LANGUAGE_OPTIONS::vowel_pause, and LANGUAGE_OPTIONS::word_gap.
Referenced by LookupCharName(), LookupSpecial(), and TranslateWord().
char* strchr_w (const char * s, int c)
References NULL.
Referenced by AnnouncePunctuation(), EmbeddedCommand(), and TranslateWord().
int towlower2 (unsigned int c)
References L, translator, and Translator::translator_name.
Referenced by TranslateClause(), and TranslateLetter().
void* TranslateClause (Translator * tr, FILE * f_text, const void * vp_input, int * tone, char ** voice_change)
References breaks, c, CHAR_EMPHASIS, Translator::char_plus_apostrophe, CLAUSE_BIT_SENTENCE, CLAUSE_BIT_VOICE, Translator::clause_end, CLAUSE_PERIOD, clause_start_char, clause_start_word, count_characters, count_sayas_digits, count_sentences, count_words, CTRL_EMBEDDED, ctrl_embedded, LANGUAGE_OPTIONS::decimal_sep, dictionary_skipwords, embedded_ix, embedded_list, embedded_read, EmbeddedCommand(), Translator::end_stressed_vowel, Eof(), espeakCHARS_WCHAR, Translator::expect_noun, Translator::expect_past, Translator::expect_verb, Translator::expect_verb_s, FLAG_ALL_UPPER, FLAG_DOT, FLAG_EMBEDDED, FLAG_FIRST_UPPER, FLAG_FIRST_WORD, FLAG_FOCUS, FLAG_HAS_PLURAL, FLAG_HYPHEN, FLAG_HYPHEN_AFTER, FLAG_LAST_WORD, FLAG_NOSPACE, FLAG_PHONEMES, FLAG_SKIPWORDS, FLAG_SPELLWORD, WORD_TAB::flags, LANGUAGE_OPTIONS::ideographs, IsAlpha(), IsBracket(), IsDigit(), IsDigit09(), IsSpace(), isspace2(), Translator::langopts, WORD_TAB::length, lookupwchar(), LOPT_CAPS_IN_WORD, MakePhonemeList(), max_clause_pause, N_CLAUSE_WORDS, n_ph_list2, N_PHONEME_LIST, n_phoneme_list, N_TR_SOURCE, new_sentence, NULL, NUM2_100000, NUM2_100000a, LANGUAGE_OPTIONS::numbers2, option_endpause, option_multibyte, option_phoneme_input, option_sayas2, p, p_textinput, p_wchar_input, LANGUAGE_OPTIONS::param, PHONEME_LIST2::phcode, phoneme_list, Translator::phonemes_repeat_count, phonPAUSE, phonPAUSE_SHORT, pre_pause, WORD_TAB::pre_pause, Translator::prepause_timeout, prev_clause_pause, Translator::prev_dict_flags, Translator::prev_last_stress, Translator::punct_within_word, ReadClause(), SAYAS_DIGITS, SAYAS_KEY, SFLAG_EMBEDDED, skip_sentences, skip_words, skipping_text, source, WORD_TAB::sourceix, PHONEME_LIST2::sourceix, WORD_TAB::start, start, PHONEME_LIST2::stress, PHONEME_LIST::synthflags, PHONEME_LIST2::synthflags, LANGUAGE_OPTIONS::testing, LANGUAGE_OPTIONS::thousands_sep, LANGUAGE_OPTIONS::tone_numbers, towlower2(), TranslateChar(), TranslateWord2(), utf8_in(), utf8_in2(), utf8_out(), WORD_TAB::wmark, and word_emphasis.
Referenced by SpeakNextClause().
int TranslateLetter (Translator * tr, char * letter, char * phonemes, int control, int word_length)
References LANGUAGE_OPTIONS::accents, L, Translator::langopts, Lookup(), LookupLetter(), N_WORD_PHONEMES, option_phonemes, voice_t::phoneme_tab_ix, phonPAUSE_VSHORT, phonSWITCH, SelectPhonemeTable(), SetTranslator2(), sprintf(), towlower2(), translator2, Translator::translator_name, utf8_in(), and voice.
Referenced by TranslateWord().
int TranslateNumber (Translator * tr, char * word1, char * ph_out, unsigned int * flags, int wflags)
References Translator::langopts, LANGUAGE_OPTIONS::numbers, option_sayas, SAYAS_DIGITS1, and TranslateNumber_1().
Referenced by TranslateRoman(), and TranslateWord().
int TranslateRoman (Translator * tr, char * word, char * ph_out)
References c, Translator::langopts, Lookup(), LANGUAGE_OPTIONS::max_roman, N_WORD_BYTES, NULL, NUM_ROMAN_AFTER, LANGUAGE_OPTIONS::numbers, p, sprintf(), TranslateNumber(), and value.
Referenced by TranslateWord().
int TranslateRules (Translator * tr, char * p, char * phonemes, int size, char * end_phonemes, int end_flags, unsigned int * dict_flags)
References AppendPhonemes(), ApplySpecialAttribute(), LANGUAGE_OPTIONS::ascii_language, buf, c, c2, Translator::data_dictrules, MatchRecord::del_fwd, diereses_list, MatchRecord::end_type, f_trans, FLAG_DONT_SWITCH_TRANSLATOR, FLAG_NO_PREFIX, FLAG_NO_TRACE, FLAG_SPELLWORD, fprintf(), group_name, Translator::groups1, Translator::groups2, Translator::groups2_count, Translator::groups2_name, Translator::groups2_start, LANGUAGE_OPTIONS::ideographs, IsAlpha(), IsBracket(), IsDigit(), Translator::langopts, Translator::letter_bits_offset, Lookup(), LookupLetter(), lookupwchar(), LOPT_DIERESES, MatchRule(), N_WORD_BYTES, NULL, option_phonemes, option_sayas, p, LANGUAGE_OPTIONS::param, MatchRecord::phonemes, Translator::phonemes_repeat_count, phonPAUSE_NOLINK, phonSWITCH, MatchRecord::points, pre_pause, remove_accent, REPLACED_E, sprintf(), SUFX_P, LANGUAGE_OPTIONS::tone_numbers, utf8_in(), Translator::word_stressed_count, and Translator::word_vowel_count.
Referenced by LookupCharName(), LookupLetter(), LookupLetter2(), and TranslateWord().
int TranslateWord (Translator * tr, char * word1, int next_pause, WORD_TAB * wtab)
References AppendPhonemes(), ApplySpecialAttribute(), ApplySpecialAttribute2(), ChangeWordStress(), Translator::clause_lower_count, Translator::clause_upper_count, DecodePhonemes(), dictionary_skipwords, Translator::expect_noun, Translator::expect_past, Translator::expect_verb, Translator::expect_verb_s, f_trans, FLAG_ABBREV, FLAG_ALL_UPPER, FLAG_ALLOW_TEXTMODE, FLAG_ALT2_TRANS, FLAG_ALT_TRANS, FLAG_DOT, FLAG_EMPHASIZED, FLAG_EMPHASIZED2, FLAG_FIRST_UPPER, FLAG_HAS_PLURAL, FLAG_LAST_WORD, FLAG_NO_PREFIX, FLAG_NO_TRACE, FLAG_NOUNF, FLAG_PASTF, FLAG_PAUSE1, FLAG_SKIPWORDS, FLAG_SPELLWORD, FLAG_STRESS_END, FLAG_STRESS_END2, FLAG_SUFFIX_REMOVED, FLAG_SUFX, FLAG_TEXTMODE, FLAG_UNSTRESS_END, FLAG_UPPERS, FLAG_VERB_EXT, FLAG_VERBF, FLAG_VERBSF, WORD_TAB::flags, fprintf(), IsAlpha(), Translator::langopts, length, Lookup(), LookupDictList(), LOPT_ALT, LOPT_PREFIXES, N_WORD_BYTES, N_WORD_PHONEMES, NULL, NUM_ROMAN, NUM_ROMAN_UC, LANGUAGE_OPTIONS::numbers, OPTION_EMPHASIZE_ALLCAPS, option_phonemes, option_sayas, option_tone_flags, p, LANGUAGE_OPTIONS::param, phonSTRESS_3, phonSTRESS_P, phonSWITCH, Translator::prev_last_stress, RemoveEnding(), SAYAS_KEY, SetSpellingStress(), SetWordStress(), sprintf(), strchr_w(), strncpy0(), SUFX_B, SUFX_F, SUFX_P, SUFX_Q, SUFX_T, SUFX_V, TranslateLetter(), TranslateNumber(), TranslateRoman(), TranslateRules(), Unpronouncable(), utf8_in(), WORD_TAB::wmark, and word_phonemes.
Referenced by TranslateWord2().
int TransposeAlphabet (char * text, int offset, int min, int max)
References c, c2, offset, p, pairs_ru, utf8_in(), and utf8_out().
Referenced by compile_line(), and LookupDict2().
int Unpronouncable (Translator * tr, char * word)
References c, c1, IsVowel(), L, Translator::langopts, Translator::letter_bits_offset, LOPT_UNPRONOUNCABLE, LANGUAGE_OPTIONS::max_initial_consonants, LANGUAGE_OPTIONS::param, Translator::translator_name, Unpronouncable_en(), and utf8_in().
Referenced by TranslateWord().
int utf8_in (int * c, const char * buf)
References utf8_in2().
Referenced by compile_dictrules(), compile_line(), compile_rule(), LookupDictList(), MatchRule(), sync_espeak_Key(), TranslateChar(), TranslateClause(), TranslateLetter(), TranslateNumber_1(), TranslateRules(), TranslateWord(), TranslateWord2(), TransposeAlphabet(), Unpronouncable(), and Unpronouncable_en().
int utf8_in2 (int * c, const char * buf, int backwards)
References c1, and mask.
Referenced by MatchRule(), TranslateClause(), and utf8_in().
int utf8_nbytes (const char * buf)
References c.
Referenced by LookupDictList().
int utf8_out (unsigned int c, char * buf)
References c, and shift.
Referenced by attrcopy_utf8(), compile_line(), LookupCharName(), LookupLetter(), LookupLetter2(), ReadClause(), TranslateClause(), and TransposeAlphabet().
Variable Documentation
const unsigned short* charsets[N_CHARSETS]
Referenced by LoadVoice(), NewTranslator(), SelectTranslator(), and Translator_Russian().
int clause_start_char
Referenced by DoEmbedded(), Generate(), MbrolaTranslate(), ReadClause(), and TranslateClause().
int clause_start_word
Referenced by Generate(), MbrolaTranslate(), and TranslateClause().
int count_characters
Referenced by DoEmbedded(), Generate(), GetC(), InitText2(), ReadClause(), and TranslateClause().
int count_sentences
Referenced by Generate(), InitText(), MbrolaTranslate(), and TranslateClause().
int count_words
Referenced by InitText(), and TranslateClause().
char ctrl_embedded
Referenced by ReadClause(), and TranslateClause().
char dictionary_name[40]
Referenced by espeak_CompileDictionary(), InitGroups(), LoadDictionary(), LoadVoice(), main(), and NewTranslator().
int dictionary_skipwords
Referenced by LookupDict2(), LookupDictList(), TranslateClause(), TranslateNumber_1(), TranslateWord(), and TranslateWord2().
int end_character_position
Referenced by InitText(), ReadClause(), sync_espeak_Synth(), and sync_espeak_Synth_Mark().
FILE* f_trans
Referenced by espeak_SetPhonemeTrace(), LookupDict2(), LookupDictList(), main(), MatchRule(), RemoveEnding(), SpeakNextClause(), TranslateRules(), and TranslateWord().
char* namedata
Referenced by AddNameData(), InitNamedata(), MarkerEvent(), and ProcessSsmlTag().
int option_capitals
Referenced by espeak_Initialize(), espeak_new(), InitText2(), main(), ProcessParamStack(), ReadClause(), and TranslateWord2().
int option_endpause
Referenced by main(), Synthesize(), and TranslateClause().
int option_linelength
Referenced by main(), ReadClause(), and SetParameter().
int option_multibyte
Referenced by GetC(), GetC_get(), main(), Synthesize(), and TranslateClause().
int option_phoneme_events
Referenced by espeak_Initialize(), and Generate().
int option_phoneme_input
Referenced by LookupCharName(), LookupSpecial(), main(), ReadClause(), Synthesize(), and TranslateClause().
int option_phoneme_variants
Referenced by WriteMnemonic().
int option_phonemes
Referenced by espeak_Initialize(), espeak_SetPhonemeTrace(), LookupDict2(), LookupDictList(), main(), MatchRule(), RemoveEnding(), SpeakNextClause(), TranslateLetter(), TranslateRules(), and TranslateWord().
wchar_t option_punctlist[N_PUNCTLIST]
Referenced by main(), ReadClause(), and sync_espeak_SetPunctuationList().
int option_punctuation
Referenced by espeak_Initialize(), espeak_new(), InitText2(), main(), ProcessParamStack(), and ReadClause().
int option_quiet
int option_sayas
Referenced by InitText(), TranslateNumber(), TranslateRules(), TranslateWord(), and TranslateWord2().
int option_ssml
Referenced by AnnouncePunctuation(), main(), ReadClause(), and Synthesize().
int option_tone2
Referenced by LoadVoice().
int option_tone_flags
Referenced by calc_pitches(), LoadVoice(), SetParameter(), and TranslateWord().
int option_waveout
Referenced by main(), and select_output().
int option_wordgap
Referenced by main(), MakePhonemeList(), and SetParameter().
unsigned char* p_textinput
Referenced by GetC_get(), GetC_unget(), and TranslateClause().
wchar_t* p_wchar_input
Referenced by GetC_get(), and TranslateClause().
const int param_defaults[N_SPEECH_PARAM]
Referenced by espeak_GetParameter(), espeak_Initialize(), initialise(), and SetParameter().
PARAM_STACK param_stack[]
Referenced by espeak_GetParameter(), espeak_Initialize(), initialise(), and SetParameter().
int(* phoneme_callback)(const char *)
Referenced by espeak_SetPhonemeCallback(), and SpeakNextClause().
int pre_pause
Referenced by TranslateClause(), and TranslateRules().
unsigned char punctuation_to_tone[INTONATION_TYPES][PUNCT_INTONATIONS]
Referenced by NewTranslator().
int skip_characters
Referenced by InitText(), ReadClause(), and sync_espeak_Synth().
char skip_marker[N_MARKER_LENGTH]
Referenced by InitText(), ProcessSsmlTag(), and sync_espeak_Synth_Mark().
int skip_sentences
Referenced by InitText(), sync_espeak_Synth(), and TranslateClause().
int skip_words
Referenced by InitText(), sync_espeak_Synth(), and TranslateClause().
int skipping_text
Referenced by InitText(), ReadClause(), SpeakNextClause(), sync_espeak_Synth(), sync_espeak_Synth_Mark(), SynthOnTimer(), and TranslateClause().
struct Translator* translator
Referenced by compile_line(), CompileDictionary(), DoSpect(), Generate(), GetC(), LoadVoice(), LookupDict2(), M_Variant(), ProcessSsmlTag(), SetParameter(), SpeakNextClause(), Synthesize(), and towlower2().
struct Translator* translator2
Referenced by LookupCharName(), LookupLetter(), and TranslateLetter().
int(* uri_callback)(int, const char *, const char *)
Referenced by espeak_SetUriCallback(), and ProcessSsmlTag().