navit: support/espeak/translate.c File Reference
translate.c File Reference
#include "StdAfx.h"
#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <wctype.h>
#include <wchar.h>
#include "speak_lib.h"
#include "speech.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Macros
#define WORD_STRESS_CHAR '*'
#define N_EMBEDDED_LIST 250
#define N_TR_SOURCE 700
Functions
void SetLengthMods (Translator *tr, int value)
int IsAlpha (unsigned int c)
static int IsDigit09 (unsigned int c)
int IsDigit (unsigned int c)
int IsSpace (unsigned int c)
void DeleteTranslator (Translator *tr)
int lookupwchar (const unsigned short *list, int c)
int IsBracket (int c)
int utf8_out (unsigned int c, char *buf)
int utf8_nbytes (const char *buf)
int utf8_in2 (int *c, const char *buf, int backwards)
int utf8_in (int *c, const char *buf)
char * strchr_w (const char *s, int c)
int TranslateWord (Translator *tr, char *word1, int next_pause, WORD_TAB *wtab)
static void SetPlist2 (PHONEME_LIST2 *p, unsigned char phcode)
static int CountSyllables (unsigned char *phonemes)
int SetTranslator2 (const char *new_language)
static int TranslateWord2 (Translator *tr, char *word, WORD_TAB *wtab, int pre_pause, int next_pause)
static int EmbeddedCommand (unsigned int *source_index)
static int SubstituteChar (Translator *tr, unsigned int c, unsigned int next_in, int *insert)
static int TranslateChar (Translator *tr, char *ptr, int prev_in, unsigned int c, unsigned int next_in, int *insert)
void * TranslateClause (Translator *tr, FILE *f_text, const void *vp_input, int *tone_out, char **voice_change)
void InitText (int control)
Variables
Translator * translator = NULL
Translator * translator2 = NULL
static char translator2_language [20] = {0}
FILE * f_trans = NULL
int option_tone2 = 0
int option_tone_flags = 0
int option_phonemes = 0
int option_phoneme_events = 0
int option_quiet = 0
int option_endpause = 0
int option_capitals = 0
int option_punctuation = 0
int option_sayas = 0
static int option_sayas2 = 0
static int option_emphasis = 0
int option_ssml = 0
int option_phoneme_input = 0
int option_phoneme_variants = 0
int option_wordgap = 0
static int count_sayas_digits
int skip_sentences
int skip_words
int skip_characters
char skip_marker [N_MARKER_LENGTH]
int skipping_text
int end_character_position
int count_sentences
int count_words
int clause_start_char
int clause_start_word
int new_sentence
static int word_emphasis = 0
static int embedded_flag = 0
static int prev_clause_pause =0
static int max_clause_pause = 0
int pre_pause
char word_phonemes [N_WORD_PHONEMES]
int n_ph_list2
PHONEME_LIST2 ph_list2 [N_PHONEME_LIST]
wchar_t option_punctlist [N_PUNCTLIST] ={0}
char ctrl_embedded = '\001'
int option_multibyte =espeakCHARS_AUTO
int option_linelength = 0
static int embedded_ix
static int embedded_read
unsigned int embedded_list [N_EMBEDDED_LIST]
static char source [N_TR_SOURCE+40]
int n_replace_phonemes
REPLACE_PHONEMES replace_phonemes [N_REPLACE_PHONEMES]
static const unsigned short brackets []
static const unsigned short breaks [] = {'_', 0}
static const wchar_t chars_space [] = {0x2500,0}
static const unsigned short ISO_8859_1 [0x60]
static const unsigned short ISO_8859_2 [0x60]
static const unsigned short ISO_8859_3 [0x60]
static const unsigned short ISO_8859_4 [0x60]
static const unsigned short ISO_8859_5 [0x60]
static const unsigned short ISO_8859_7 [0x60]
static const unsigned short ISO_8859_9 [0x60]
static const unsigned short ISO_8859_14 [0x60]
static const unsigned short KOI8_R [0x60]
static const unsigned short ISCII [0x60]
const unsigned short * charsets [N_CHARSETS]
static unsigned char length_mods_en [100]
static unsigned char length_mods_en0 [100]
static unsigned char length_mods_equal [100]
static unsigned char * length_mod_tabs [6]
Macro Definition Documentation
#define N_EMBEDDED_LIST 250
Referenced by EmbeddedCommand(), and TranslateWord2().
#define N_TR_SOURCE 700
Referenced by TranslateClause().
#define WORD_STRESS_CHAR '*'
Function Documentation
static int CountSyllables (unsigned char * phonemes) static
References phoneme_tab, phVOWEL, and type.
Referenced by TranslateWord2().
void DeleteTranslator (Translator * tr)
References Translator::data_dictlist, Free(), and NULL.
Referenced by LoadVoice(), and SetTranslator2().
static int EmbeddedCommand (unsigned int * source_index) static
References c, commands, count_sayas_digits, EMBED_F, EMBED_Y, embedded_default, embedded_ix, embedded_list, FLAG_EMPHASIZED, N_EMBEDDED_LIST, NULL, option_sayas2, p, source, strchr_w(), value, and word_emphasis.
Referenced by TranslateClause().
void InitText (int control)
References count_sentences, count_words, embedded_flag, end_character_position, espeakKEEP_NAMEDATA, InitNamedata(), InitText2(), new_sentence, option_emphasis, option_sayas, option_sayas2, prev_clause_pause, skip_characters, skip_marker, skip_sentences, skip_words, skipping_text, and word_emphasis.
Referenced by main(), sync_espeak_Synth(), and sync_espeak_Synth_Mark().
int IsAlpha (unsigned int c)
Referenced by ReadClause(), TranslateClause(), TranslateRules(), TranslateWord(), TranslateWord2(), and Unpronouncable_en().
int IsBracket (int c)
References brackets, and lookupwchar().
Referenced by ReadClause(), TranslateClause(), and TranslateRules().
int IsDigit (unsigned int c)
Referenced by compile_rule(), MatchRule(), TranslateClause(), and TranslateRules().
static int IsDigit09 (unsigned int c) static
Referenced by TranslateClause().
int IsSpace (unsigned int c)
References chars_space.
Referenced by TranslateChar(), and TranslateClause().
int lookupwchar (const unsigned short * list, int c)
Referenced by AnnouncePunctuation(), IsBracket(), ReadClause(), TranslateClause(), and TranslateRules().
void SetLengthMods (Translator * tr, int value)
References Translator::langopts, length_mod_tabs, LANGUAGE_OPTIONS::length_mods, and LANGUAGE_OPTIONS::length_mods0.
Referenced by LoadVoice(), NewTranslator(), and SelectTranslator().
static void SetPlist2 (PHONEME_LIST2 * p, unsigned char phcode) static
References embedded_flag, PHONEME_LIST2::phcode, PHONEME_LIST2::sourceix, PHONEME_LIST2::stress, PHONEME_LIST2::synthflags, and PHONEME_LIST2::tone_number.
Referenced by TranslateWord2().
int SetTranslator2 (const char * new_language)
References DeleteTranslator(), LoadDictionary(), NULL, voice_t::phoneme_tab_ix, SelectPhonemeTable(), SelectPhonemeTableName(), SelectTranslator(), translator2_language, and voice.
Referenced by LookupCharName(), LookupLetter(), TranslateLetter(), and TranslateWord2().
char* strchr_w (const char * s, int c)
References NULL.
Referenced by AnnouncePunctuation(), EmbeddedCommand(), and TranslateWord().
static int SubstituteChar (Translator * tr, unsigned int c, unsigned int next_in, int * insert) static
References c2, int, Translator::langopts, NULL, and LANGUAGE_OPTIONS::replace_chars.
Referenced by TranslateChar().
static int TranslateChar (Translator * tr, char * ptr, int prev_in, unsigned int c, unsigned int next_in, int * insert) static
References IsSpace(), L, SubstituteChar(), Translator::translator_name, and utf8_in().
Referenced by TranslateClause().
void* TranslateClause (Translator * tr, FILE * f_text, const void * vp_input, int * tone_out, char ** voice_change)
References breaks, c, CHAR_EMPHASIS, Translator::char_plus_apostrophe, CLAUSE_BIT_SENTENCE, CLAUSE_BIT_VOICE, Translator::clause_end, CLAUSE_PERIOD, clause_start_char, clause_start_word, count_characters, count_sayas_digits, count_sentences, count_words, CTRL_EMBEDDED, ctrl_embedded, LANGUAGE_OPTIONS::decimal_sep, dictionary_skipwords, embedded_ix, embedded_list, embedded_read, EmbeddedCommand(), Translator::end_stressed_vowel, Eof(), espeakCHARS_WCHAR, Translator::expect_noun, Translator::expect_past, Translator::expect_verb, Translator::expect_verb_s, FLAG_ALL_UPPER, FLAG_DOT, FLAG_EMBEDDED, FLAG_FIRST_UPPER, FLAG_FIRST_WORD, FLAG_FOCUS, FLAG_HAS_PLURAL, FLAG_HYPHEN, FLAG_HYPHEN_AFTER, FLAG_LAST_WORD, FLAG_NOSPACE, FLAG_PHONEMES, FLAG_SKIPWORDS, FLAG_SPELLWORD, WORD_TAB::flags, LANGUAGE_OPTIONS::ideographs, IsAlpha(), IsBracket(), IsDigit(), IsDigit09(), IsSpace(), isspace2(), Translator::langopts, WORD_TAB::length, lookupwchar(), LOPT_CAPS_IN_WORD, MakePhonemeList(), max_clause_pause, N_CLAUSE_WORDS, n_ph_list2, N_PHONEME_LIST, n_phoneme_list, N_TR_SOURCE, new_sentence, NULL, NUM2_100000, NUM2_100000a, LANGUAGE_OPTIONS::numbers2, option_endpause, option_multibyte, option_phoneme_input, option_sayas2, p, p_textinput, p_wchar_input, LANGUAGE_OPTIONS::param, PHONEME_LIST2::phcode, phoneme_list, Translator::phonemes_repeat_count, phonPAUSE, phonPAUSE_SHORT, pre_pause, WORD_TAB::pre_pause, Translator::prepause_timeout, prev_clause_pause, Translator::prev_dict_flags, Translator::prev_last_stress, Translator::punct_within_word, ReadClause(), SAYAS_DIGITS, SAYAS_KEY, SFLAG_EMBEDDED, skip_sentences, skip_words, skipping_text, source, WORD_TAB::sourceix, PHONEME_LIST2::sourceix, WORD_TAB::start, start, PHONEME_LIST2::stress, PHONEME_LIST::synthflags, PHONEME_LIST2::synthflags, LANGUAGE_OPTIONS::testing, LANGUAGE_OPTIONS::thousands_sep, LANGUAGE_OPTIONS::tone_numbers, towlower2(), TranslateChar(), TranslateWord2(), utf8_in(), utf8_in2(), utf8_out(), WORD_TAB::wmark, and word_emphasis.
Referenced by SpeakNextClause().
int TranslateWord (Translator * tr, char * word1, int next_pause, WORD_TAB * wtab)
References AppendPhonemes(), ApplySpecialAttribute(), ApplySpecialAttribute2(), ChangeWordStress(), Translator::clause_lower_count, Translator::clause_upper_count, DecodePhonemes(), dictionary_skipwords, Translator::expect_noun, Translator::expect_past, Translator::expect_verb, Translator::expect_verb_s, f_trans, FLAG_ABBREV, FLAG_ALL_UPPER, FLAG_ALLOW_TEXTMODE, FLAG_ALT2_TRANS, FLAG_ALT_TRANS, FLAG_DOT, FLAG_EMPHASIZED, FLAG_EMPHASIZED2, FLAG_FIRST_UPPER, FLAG_HAS_PLURAL, FLAG_LAST_WORD, FLAG_NO_PREFIX, FLAG_NO_TRACE, FLAG_NOUNF, FLAG_PASTF, FLAG_PAUSE1, FLAG_SKIPWORDS, FLAG_SPELLWORD, FLAG_STRESS_END, FLAG_STRESS_END2, FLAG_SUFFIX_REMOVED, FLAG_SUFX, FLAG_TEXTMODE, FLAG_UNSTRESS_END, FLAG_UPPERS, FLAG_VERB_EXT, FLAG_VERBF, FLAG_VERBSF, WORD_TAB::flags, fprintf(), IsAlpha(), Translator::langopts, length, Lookup(), LookupDictList(), LOPT_ALT, LOPT_PREFIXES, N_WORD_BYTES, N_WORD_PHONEMES, NULL, NUM_ROMAN, NUM_ROMAN_UC, LANGUAGE_OPTIONS::numbers, OPTION_EMPHASIZE_ALLCAPS, option_phonemes, option_sayas, option_tone_flags, p, LANGUAGE_OPTIONS::param, phonSTRESS_3, phonSTRESS_P, phonSWITCH, Translator::prev_last_stress, RemoveEnding(), SAYAS_KEY, SetSpellingStress(), SetWordStress(), sprintf(), strchr_w(), strncpy0(), SUFX_B, SUFX_F, SUFX_P, SUFX_Q, SUFX_T, SUFX_V, TranslateLetter(), TranslateNumber(), TranslateRoman(), TranslateRules(), Unpronouncable(), utf8_in(), WORD_TAB::wmark, and word_phonemes.
Referenced by TranslateWord2().
static int TranslateWord2 (Translator * tr, char * word, WORD_TAB * wtab, int pre_pause, int next_pause) static
References c1, c2, CountSyllables(), dictionary_skipwords, EMBED_B, EMBED_F, EMBED_P, EMBED_Y, embedded_flag, embedded_ix, embedded_list, embedded_read, EncodePhonemes(), Translator::end_stressed_vowel, FLAG_ALL_UPPER, FLAG_ALT2_TRANS, FLAG_ALT_TRANS, FLAG_DOUBLING, FLAG_EMBEDDED, FLAG_FIRST_UPPER, FLAG_FIRST_WORD, FLAG_FOUND, FLAG_HYPHEN, FLAG_LAST_WORD, FLAG_PAUSE1, FLAG_PHONEMES, FLAG_PREPAUSE, FLAG_SKIPWORDS, FLAG_SPELLWORD, FLAG_STRESS_END2, WORD_TAB::flags, IsAlpha(), Translator::langopts, WORD_TAB::length, LookupPhonemeTable(), LOPT_COMBINE_WORDS, LOPT_IT_DOUBLING, N_EMBEDDED_LIST, n_ph_list2, N_PHONEME_LIST, N_WORD_BYTES, N_WORD_PHONEMES, option_capitals, option_emphasis, option_sayas, p, LANGUAGE_OPTIONS::param, PHONEME_LIST2::phcode, phonCAPITAL, phoneme_tab, voice_t::phoneme_tab_ix, phonEND_WORD, phonLENGTHEN, phonPAUSE, phonPAUSE_NOLINK, phonPAUSE_SHORT, phonSCHWA, phonSWITCH, phonSYLLABIC, phonX1, phPAUSE, phSTRESS, phVOWEL, Translator::prepause_timeout, Translator::prev_dict_flags, SelectPhonemeTable(), SetPlist2(), SetTranslator2(), SFLAG_DICTIONARY, SFLAG_EMBEDDED, SFLAG_LENGTHEN, SFLAG_PROMOTE_STRESS, SFLAG_SYLLABLE, WORD_TAB::sourceix, PHONEME_LIST2::sourceix, PHONEME_TAB::spect, PHONEME_TAB::std_length, PHONEME_LIST2::stress, PHONEME_LIST2::synthflags, PHONEME_LIST2::tone_number, TranslateWord(), PHONEME_TAB::type, type, utf8_in(), value, voice, and word_phonemes.
Referenced by TranslateClause().
int utf8_in (int * c, const char * buf)
References utf8_in2().
Referenced by compile_dictrules(), compile_line(), compile_rule(), LookupDictList(), MatchRule(), sync_espeak_Key(), TranslateChar(), TranslateClause(), TranslateLetter(), TranslateNumber_1(), TranslateRules(), TranslateWord(), TranslateWord2(), TransposeAlphabet(), Unpronouncable(), and Unpronouncable_en().
int utf8_in2 (int * c, const char * buf, int backwards)
References c1, and mask.
Referenced by MatchRule(), TranslateClause(), and utf8_in().
int utf8_nbytes (const char * buf)
References c.
Referenced by LookupDictList().
int utf8_out (unsigned int c, char * buf)
References c, and shift.
Referenced by attrcopy_utf8(), compile_line(), LookupCharName(), LookupLetter(), LookupLetter2(), ReadClause(), TranslateClause(), and TransposeAlphabet().
Variable Documentation
const unsigned short brackets[] static
Initial value:
= {
'(',')','[',']','{','}','<','>','"','\'','`',
0xab,0xbb,
0x300a,0x300b,
0}
Referenced by IsBracket().
const unsigned short breaks[] = {'_', 0} static
Referenced by TranslateClause().
const wchar_t chars_space[] = {0x2500,0} static
Referenced by IsSpace().
const unsigned short* charsets[N_CHARSETS]
Initial value:
= {
        ISO_8859_1,
        ISO_8859_1,
        ISO_8859_2,
        ISO_8859_3,
        ISO_8859_4,
        ISO_8859_5,
        ISO_8859_1,
        ISO_8859_7,
        ISO_8859_1,
        ISO_8859_9,
        ISO_8859_1,
        ISO_8859_1,
        ISO_8859_1,
        ISO_8859_1,
        ISO_8859_14,
        ISO_8859_1,
        ISO_8859_1,
        ISO_8859_1,
        KOI8_R,
        ISCII }
Referenced by LoadVoice(), NewTranslator(), SelectTranslator(), and Translator_Russian().
int clause_start_char
Referenced by DoEmbedded(), Generate(), MbrolaTranslate(), ReadClause(), and TranslateClause().
int clause_start_word
Referenced by Generate(), MbrolaTranslate(), and TranslateClause().
int count_sayas_digits static
Referenced by EmbeddedCommand(), and TranslateClause().
int count_sentences
Referenced by Generate(), InitText(), MbrolaTranslate(), and TranslateClause().
int count_words
Referenced by InitText(), and TranslateClause().
char ctrl_embedded = '\001'
Referenced by ReadClause(), and TranslateClause().
int embedded_flag = 0 static
Referenced by InitText(), SetPlist2(), and TranslateWord2().
int embedded_ix static
Referenced by CalcLengths(), EmbeddedCommand(), Generate(), MbrolaTranslate(), TranslateClause(), and TranslateWord2().
unsigned int embedded_list[N_EMBEDDED_LIST]
Referenced by DoEmbedded(), DoEmbedded2(), EmbeddedCommand(), TranslateClause(), and TranslateWord2().
int embedded_read static
Referenced by TranslateClause(), and TranslateWord2().
int end_character_position
Referenced by InitText(), ReadClause(), sync_espeak_Synth(), and sync_espeak_Synth_Mark().
FILE* f_trans = NULL
Referenced by espeak_SetPhonemeTrace(), LookupDict2(), LookupDictList(), main(), MatchRule(), RemoveEnding(), SpeakNextClause(), TranslateRules(), and TranslateWord().
const unsigned short ISCII[0x60] static
Initial value:
= {
   0x0020, 0x0901, 0x0902, 0x0903, 0x0905, 0x0906, 0x0907, 0x0908,
   0x0909, 0x090a, 0x090b, 0x090e, 0x090f, 0x0910, 0x090d, 0x0912,
   0x0913, 0x0914, 0x0911, 0x0915, 0x0916, 0x0917, 0x0918, 0x0919,
   0x091a, 0x091b, 0x091c, 0x091d, 0x091e, 0x091f, 0x0920, 0x0921,
   0x0922, 0x0923, 0x0924, 0x0925, 0x0926, 0x0927, 0x0928, 0x0929,
   0x092a, 0x092b, 0x092c, 0x092d, 0x092e, 0x092f, 0x095f, 0x0930,
   0x0931, 0x0932, 0x0933, 0x0934, 0x0935, 0x0936, 0x0937, 0x0938,
   0x0939, 0x0020, 0x093e, 0x093f, 0x0940, 0x0941, 0x0942, 0x0943,
   0x0946, 0x0947, 0x0948, 0x0945, 0x094a, 0x094b, 0x094c, 0x0949,
   0x094d, 0x093c, 0x0964, 0x0020, 0x0020, 0x0020, 0x0020, 0x0020,
   0x0020, 0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036,
   0x0037, 0x0038, 0x0039, 0x20,   0x20,   0x20,   0x20,   0x20,
}
const unsigned short ISO_8859_1[0x60] static
Initial value:
= {
   0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a4, 0x00a5, 0x00a6, 0x00a7,
   0x00a8, 0x00a9, 0x00aa, 0x00ab, 0x00ac, 0x00ad, 0x00ae, 0x00af,
   0x00b0, 0x00b1, 0x00b2, 0x00b3, 0x00b4, 0x00b5, 0x00b6, 0x00b7,
   0x00b8, 0x00b9, 0x00ba, 0x00bb, 0x00bc, 0x00bd, 0x00be, 0x00bf,
   0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c4, 0x00c5, 0x00c6, 0x00c7,
   0x00c8, 0x00c9, 0x00ca, 0x00cb, 0x00cc, 0x00cd, 0x00ce, 0x00cf,
   0x00d0, 0x00d1, 0x00d2, 0x00d3, 0x00d4, 0x00d5, 0x00d6, 0x00d7,
   0x00d8, 0x00d9, 0x00da, 0x00db, 0x00dc, 0x00dd, 0x00de, 0x00df,
   0x00e0, 0x00e1, 0x00e2, 0x00e3, 0x00e4, 0x00e5, 0x00e6, 0x00e7,
   0x00e8, 0x00e9, 0x00ea, 0x00eb, 0x00ec, 0x00ed, 0x00ee, 0x00ef,
   0x00f0, 0x00f1, 0x00f2, 0x00f3, 0x00f4, 0x00f5, 0x00f6, 0x00f7,
   0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x00fe, 0x00ff,
}
const unsigned short ISO_8859_14[0x60] static
Initial value:
= {
   0x00a0, 0x1e02, 0x1e03, 0x00a3, 0x010a, 0x010b, 0x1e0a, 0x00a7,
   0x1e80, 0x00a9, 0x1e82, 0x1e0b, 0x1ef2, 0x00ad, 0x00ae, 0x0178,
   0x1e1e, 0x1e1f, 0x0120, 0x0121, 0x1e40, 0x1e41, 0x00b6, 0x1e56,
   0x1e81, 0x1e57, 0x1e83, 0x1e60, 0x1ef3, 0x1e84, 0x1e85, 0x1e61,
   0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c4, 0x00c5, 0x00c6, 0x00c7,
   0x00c8, 0x00c9, 0x00ca, 0x00cb, 0x00cc, 0x00cd, 0x00ce, 0x00cf,
   0x0174, 0x00d1, 0x00d2, 0x00d3, 0x00d4, 0x00d5, 0x00d6, 0x1e6a,
   0x00d8, 0x00d9, 0x00da, 0x00db, 0x00dc, 0x00dd, 0x0176, 0x00df,
   0x00e0, 0x00e1, 0x00e2, 0x00e3, 0x00e4, 0x00e5, 0x00e6, 0x00e7,
   0x00e8, 0x00e9, 0x00ea, 0x00eb, 0x00ec, 0x00ed, 0x00ee, 0x00ef,
   0x0175, 0x00f1, 0x00f2, 0x00f3, 0x00f4, 0x00f5, 0x00f6, 0x1e6b,
   0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x00fd, 0x0177, 0x00ff,
}
const unsigned short ISO_8859_2[0x60] static
Initial value:
= {
   0x00a0, 0x0104, 0x02d8, 0x0141, 0x00a4, 0x013d, 0x015a, 0x00a7,
   0x00a8, 0x0160, 0x015e, 0x0164, 0x0179, 0x00ad, 0x017d, 0x017b,
   0x00b0, 0x0105, 0x02db, 0x0142, 0x00b4, 0x013e, 0x015b, 0x02c7,
   0x00b8, 0x0161, 0x015f, 0x0165, 0x017a, 0x02dd, 0x017e, 0x017c,
   0x0154, 0x00c1, 0x00c2, 0x0102, 0x00c4, 0x0139, 0x0106, 0x00c7,
   0x010c, 0x00c9, 0x0118, 0x00cb, 0x011a, 0x00cd, 0x00ce, 0x010e,
   0x0110, 0x0143, 0x0147, 0x00d3, 0x00d4, 0x0150, 0x00d6, 0x00d7,
   0x0158, 0x016e, 0x00da, 0x0170, 0x00dc, 0x00dd, 0x0162, 0x00df,
   0x0155, 0x00e1, 0x00e2, 0x0103, 0x00e4, 0x013a, 0x0107, 0x00e7,
   0x010d, 0x00e9, 0x0119, 0x00eb, 0x011b, 0x00ed, 0x00ee, 0x010f,
   0x0111, 0x0144, 0x0148, 0x00f3, 0x00f4, 0x0151, 0x00f6, 0x00f7,
   0x0159, 0x016f, 0x00fa, 0x0171, 0x00fc, 0x00fd, 0x0163, 0x02d9,
}
const unsigned short ISO_8859_3[0x60] static
Initial value:
= {
   0x00a0, 0x0126, 0x02d8, 0x00a3, 0x00a4, 0x0000, 0x0124, 0x00a7,
   0x00a8, 0x0130, 0x015e, 0x011e, 0x0134, 0x00ad, 0x0000, 0x017b,
   0x00b0, 0x0127, 0x00b2, 0x00b3, 0x00b4, 0x00b5, 0x0125, 0x00b7,
   0x00b8, 0x0131, 0x015f, 0x011f, 0x0135, 0x00bd, 0x0000, 0x017c,
   0x00c0, 0x00c1, 0x00c2, 0x0000, 0x00c4, 0x010a, 0x0108, 0x00c7,
   0x00c8, 0x00c9, 0x00ca, 0x00cb, 0x00cc, 0x00cd, 0x00ce, 0x00cf,
   0x0000, 0x00d1, 0x00d2, 0x00d3, 0x00d4, 0x0120, 0x00d6, 0x00d7,
   0x011c, 0x00d9, 0x00da, 0x00db, 0x00dc, 0x016c, 0x015c, 0x00df,
   0x00e0, 0x00e1, 0x00e2, 0x0000, 0x00e4, 0x010b, 0x0109, 0x00e7,
   0x00e8, 0x00e9, 0x00ea, 0x00eb, 0x00ec, 0x00ed, 0x00ee, 0x00ef,
   0x0000, 0x00f1, 0x00f2, 0x00f3, 0x00f4, 0x0121, 0x00f6, 0x00f7,
   0x011d, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x016d, 0x015d, 0x02d9,
}
const unsigned short ISO_8859_4[0x60] static
Initial value:
= {
   0x00a0, 0x0104, 0x0138, 0x0156, 0x00a4, 0x0128, 0x013b, 0x00a7,
   0x00a8, 0x0160, 0x0112, 0x0122, 0x0166, 0x00ad, 0x017d, 0x00af,
   0x00b0, 0x0105, 0x02db, 0x0157, 0x00b4, 0x0129, 0x013c, 0x02c7,
   0x00b8, 0x0161, 0x0113, 0x0123, 0x0167, 0x014a, 0x017e, 0x014b,
   0x0100, 0x00c1, 0x00c2, 0x00c3, 0x00c4, 0x00c5, 0x00c6, 0x012e,
   0x010c, 0x00c9, 0x0118, 0x00cb, 0x0116, 0x00cd, 0x00ce, 0x012a,
   0x0110, 0x0145, 0x014c, 0x0136, 0x00d4, 0x00d5, 0x00d6, 0x00d7,
   0x00d8, 0x0172, 0x00da, 0x00db, 0x00dc, 0x0168, 0x016a, 0x00df,
   0x0101, 0x00e1, 0x00e2, 0x00e3, 0x00e4, 0x00e5, 0x00e6, 0x012f,
   0x010d, 0x00e9, 0x0119, 0x00eb, 0x0117, 0x00ed, 0x00ee, 0x012b,
   0x0111, 0x0146, 0x014d, 0x0137, 0x00f4, 0x00f5, 0x00f6, 0x00f7,
   0x00f8, 0x0173, 0x00fa, 0x00fb, 0x00fc, 0x0169, 0x016b, 0x02d9,
}
const unsigned short ISO_8859_5[0x60] static
Initial value:
= {
   0x00a0, 0x0401, 0x0402, 0x0403, 0x0404, 0x0405, 0x0406, 0x0407,
   0x0408, 0x0409, 0x040a, 0x040b, 0x040c, 0x00ad, 0x040e, 0x040f,
   0x0410, 0x0411, 0x0412, 0x0413, 0x0414, 0x0415, 0x0416, 0x0417,
   0x0418, 0x0419, 0x041a, 0x041b, 0x041c, 0x041d, 0x041e, 0x041f,
   0x0420, 0x0421, 0x0422, 0x0423, 0x0424, 0x0425, 0x0426, 0x0427,
   0x0428, 0x0429, 0x042a, 0x042b, 0x042c, 0x042d, 0x042e, 0x042f,
   0x0430, 0x0431, 0x0432, 0x0433, 0x0434, 0x0435, 0x0436, 0x0437,
   0x0438, 0x0439, 0x043a, 0x043b, 0x043c, 0x043d, 0x043e, 0x043f,
   0x0440, 0x0441, 0x0442, 0x0443, 0x0444, 0x0445, 0x0446, 0x0447,
   0x0448, 0x0449, 0x044a, 0x044b, 0x044c, 0x044d, 0x044e, 0x044f,
   0x2116, 0x0451, 0x0452, 0x0453, 0x0454, 0x0455, 0x0456, 0x0457,
   0x0458, 0x0459, 0x045a, 0x045b, 0x045c, 0x00a7, 0x045e, 0x045f,
}
const unsigned short ISO_8859_7[0x60] static
Initial value:
= {
   0x00a0, 0x2018, 0x2019, 0x00a3, 0x20ac, 0x20af, 0x00a6, 0x00a7,
   0x00a8, 0x00a9, 0x037a, 0x00ab, 0x00ac, 0x00ad, 0x0000, 0x2015,
   0x00b0, 0x00b1, 0x00b2, 0x00b3, 0x0384, 0x0385, 0x0386, 0x00b7,
   0x0388, 0x0389, 0x038a, 0x00bb, 0x038c, 0x00bd, 0x038e, 0x038f,
   0x0390, 0x0391, 0x0392, 0x0393, 0x0394, 0x0395, 0x0396, 0x0397,
   0x0398, 0x0399, 0x039a, 0x039b, 0x039c, 0x039d, 0x039e, 0x039f,
   0x03a0, 0x03a1, 0x0000, 0x03a3, 0x03a4, 0x03a5, 0x03a6, 0x03a7,
   0x03a8, 0x03a9, 0x03aa, 0x03ab, 0x03ac, 0x03ad, 0x03ae, 0x03af,
   0x03b0, 0x03b1, 0x03b2, 0x03b3, 0x03b4, 0x03b5, 0x03b6, 0x03b7,
   0x03b8, 0x03b9, 0x03ba, 0x03bb, 0x03bc, 0x03bd, 0x03be, 0x03bf,
   0x03c0, 0x03c1, 0x03c2, 0x03c3, 0x03c4, 0x03c5, 0x03c6, 0x03c7,
   0x03c8, 0x03c9, 0x03ca, 0x03cb, 0x03cc, 0x03cd, 0x03ce, 0x0000,
}
const unsigned short ISO_8859_9[0x60] static
Initial value:
= {
   0x00a0, 0x00a1, 0x00a2, 0x00a3, 0x00a4, 0x00a5, 0x00a6, 0x00a7,
   0x00a8, 0x00a9, 0x00aa, 0x00ab, 0x00ac, 0x00ad, 0x00ae, 0x00af,
   0x00b0, 0x00b1, 0x00b2, 0x00b3, 0x00b4, 0x00b5, 0x00b6, 0x00b7,
   0x00b8, 0x00b9, 0x00ba, 0x00bb, 0x00bc, 0x00bd, 0x00be, 0x00bf,
   0x00c0, 0x00c1, 0x00c2, 0x00c3, 0x00c4, 0x00c5, 0x00c6, 0x00c7,
   0x00c8, 0x00c9, 0x00ca, 0x00cb, 0x00cc, 0x00cd, 0x00ce, 0x00cf,
   0x011e, 0x00d1, 0x00d2, 0x00d3, 0x00d4, 0x00d5, 0x00d6, 0x00d7,
   0x00d8, 0x00d9, 0x00da, 0x00db, 0x00dc, 0x0130, 0x015e, 0x00df,
   0x00e0, 0x00e1, 0x00e2, 0x00e3, 0x00e4, 0x00e5, 0x00e6, 0x00e7,
   0x00e8, 0x00e9, 0x00ea, 0x00eb, 0x00ec, 0x00ed, 0x00ee, 0x00ef,
   0x011f, 0x00f1, 0x00f2, 0x00f3, 0x00f4, 0x00f5, 0x00f6, 0x00f7,
   0x00f8, 0x00f9, 0x00fa, 0x00fb, 0x00fc, 0x0131, 0x015f, 0x00ff,
}
const unsigned short KOI8_R[0x60] static
Initial value:
= {
   0x2550, 0x2551, 0x2552, 0x0451, 0x2553, 0x2554, 0x2555, 0x2556,
   0x2557, 0x2558, 0x2559, 0x255a, 0x255b, 0x255c, 0x255d, 0x255e,
   0x255f, 0x2560, 0x2561, 0x0401, 0x2562, 0x2563, 0x2564, 0x2565,
   0x2566, 0x2567, 0x2568, 0x2569, 0x256a, 0x256b, 0x256c, 0x00a9,
   0x044e, 0x0430, 0x0431, 0x0446, 0x0434, 0x0435, 0x0444, 0x0433,
   0x0445, 0x0438, 0x0439, 0x043a, 0x043b, 0x043c, 0x043d, 0x043e,
   0x043f, 0x044f, 0x0440, 0x0441, 0x0442, 0x0443, 0x0436, 0x0432,
   0x044c, 0x044b, 0x0437, 0x0448, 0x044d, 0x0449, 0x0447, 0x044a,
   0x042e, 0x0410, 0x0411, 0x0426, 0x0414, 0x0415, 0x0424, 0x0413,
   0x0425, 0x0418, 0x0419, 0x041a, 0x041b, 0x041c, 0x041d, 0x041e,
   0x041f, 0x042f, 0x0420, 0x0421, 0x0422, 0x0423, 0x0416, 0x0412,
   0x042c, 0x042b, 0x0417, 0x0428, 0x042d, 0x0429, 0x0427, 0x042a,
}
unsigned char* length_mod_tabs[6] static
Initial value:
= {
  length_mods_en,
  length_mods_en,
  length_mods_en0,
  length_mods_equal,
  length_mods_equal,
  length_mods_equal
 }
Referenced by SetLengthMods().
unsigned char length_mods_en[100] static
Initial value:
= {
        100,120,100,105,100,110,110,100, 95, 100,
        105,120,105,110,125,130,135,115,125, 100,
        105,120, 75,100, 75,105,120, 85, 75, 100,
        105,120, 85,105, 95,115,120,100, 95, 100,
        110,120, 95,105,100,115,120,100,100, 100,
        105,120,100,105, 95,115,120,110, 95, 100,
        105,120,100,105,105,122,125,110,105, 100,
        105,120,100,105,105,122,125,110,105, 100,
        105,120, 95,105,100,115,120,110,100, 100,
        100,120,100,100,100,100,100,100,100, 100 }
unsigned char length_mods_en0[100] static
Initial value:
= {
        100,150,100,105,110,115,110,110,110, 100,
        105,150,105,110,125,135,140,115,135, 100,
        105,150, 90,105, 90,122,135,100, 90, 100,
        105,150,100,105,100,122,135,100,100, 100,
        105,150,100,105,105,115,135,110,105, 100,
        105,150,100,105,105,122,130,120,125, 100,
        105,150,100,105,110,122,125,115,110, 100,
        105,150,100,105,105,122,135,120,105, 100,
        105,150,100,105,105,115,135,110,105, 100,
        100,100,100,100,100,100,100,100,100, 100 }
unsigned char length_mods_equal[100] static
Initial value:
= {
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110,
        110,110,110,110,110,110,110,110,110, 110 }
int max_clause_pause = 0 static
Referenced by TranslateClause().
int n_ph_list2
Referenced by MakePhonemeList(), SubstitutePhonemes(), TranslateClause(), and TranslateWord2().
int n_replace_phonemes
Referenced by PhonemeReplacement(), SubstitutePhonemes(), and VoiceReset().
int new_sentence
Referenced by InitText(), and TranslateClause().
int option_capitals = 0
Referenced by espeak_Initialize(), espeak_new(), InitText2(), main(), ProcessParamStack(), ReadClause(), and TranslateWord2().
int option_emphasis = 0 static
Referenced by InitText(), and TranslateWord2().
int option_endpause = 0
Referenced by main(), Synthesize(), and TranslateClause().
int option_linelength = 0
Referenced by main(), ReadClause(), and SetParameter().
int option_multibyte =espeakCHARS_AUTO
Referenced by GetC(), GetC_get(), main(), Synthesize(), and TranslateClause().
int option_phoneme_events = 0
Referenced by espeak_Initialize(), and Generate().
int option_phoneme_input = 0
Referenced by LookupCharName(), LookupSpecial(), main(), ReadClause(), Synthesize(), and TranslateClause().
int option_phoneme_variants = 0
Referenced by WriteMnemonic().
int option_phonemes = 0
Referenced by espeak_Initialize(), espeak_SetPhonemeTrace(), LookupDict2(), LookupDictList(), main(), MatchRule(), RemoveEnding(), SpeakNextClause(), TranslateLetter(), TranslateRules(), and TranslateWord().
wchar_t option_punctlist[N_PUNCTLIST] ={0}
Referenced by main(), ReadClause(), and sync_espeak_SetPunctuationList().
int option_punctuation = 0
Referenced by espeak_Initialize(), espeak_new(), InitText2(), main(), ProcessParamStack(), and ReadClause().
int option_quiet = 0
Referenced by Generate(), LoadMbrolaTable(), main(), and VoiceReset().
int option_sayas = 0
Referenced by InitText(), TranslateNumber(), TranslateRules(), TranslateWord(), and TranslateWord2().
int option_sayas2 = 0 static
Referenced by EmbeddedCommand(), InitText(), and TranslateClause().
int option_ssml = 0
Referenced by AnnouncePunctuation(), main(), ReadClause(), and Synthesize().
int option_tone2 = 0
Referenced by LoadVoice().
int option_tone_flags = 0
Referenced by calc_pitches(), LoadVoice(), SetParameter(), and TranslateWord().
int option_wordgap = 0
Referenced by main(), MakePhonemeList(), and SetParameter().
PHONEME_LIST2 ph_list2[N_PHONEME_LIST]
Referenced by MakePhonemeList().
int pre_pause
Referenced by TranslateClause(), and TranslateRules().
int prev_clause_pause =0 static
Referenced by InitText(), and TranslateClause().
REPLACE_PHONEMES replace_phonemes[N_REPLACE_PHONEMES]
Referenced by PhonemeReplacement(), and SubstitutePhonemes().
int skip_characters
Referenced by InitText(), ReadClause(), and sync_espeak_Synth().
char skip_marker[N_MARKER_LENGTH]
Referenced by InitText(), ProcessSsmlTag(), and sync_espeak_Synth_Mark().
int skip_sentences
Referenced by InitText(), sync_espeak_Synth(), and TranslateClause().
int skip_words
Referenced by InitText(), sync_espeak_Synth(), and TranslateClause().
int skipping_text
Referenced by InitText(), ReadClause(), SpeakNextClause(), sync_espeak_Synth(), sync_espeak_Synth_Mark(), SynthOnTimer(), and TranslateClause().
char source[N_TR_SOURCE+40] static
Referenced by ConvertUTF16toUTF32(), ConvertUTF16toUTF8(), ConvertUTF32toUTF16(), ConvertUTF32toUTF8(), ConvertUTF8toUTF16(), ConvertUTF8toUTF32(), org.navitproject.navit.Navit::copyFileIfExists(), EmbeddedCommand(), g_strcompress(), isLegalUTF8Sequence(), TranslateClause(), vehicle_file_new_file(), vehicle_gpsd_new_gpsd(), vehicle_gpsd_try_open(), vehicle_gypsy_new_gypsy(), vehicle_gypsy_try_open(), vehicle_maemo_new_maemo(), vehicle_new(), and vehicle_wince_new().
Translator* translator = NULL
Referenced by compile_line(), CompileDictionary(), DoSpect(), Generate(), GetC(), LoadVoice(), LookupDict2(), M_Variant(), ProcessSsmlTag(), SetParameter(), SpeakNextClause(), Synthesize(), and towlower2().
Translator* translator2 = NULL
Referenced by LookupCharName(), LookupLetter(), and TranslateLetter().
char translator2_language[20] = {0} static
Referenced by SetTranslator2().
int word_emphasis = 0 static
Referenced by EmbeddedCommand(), InitText(), and TranslateClause().
char word_phonemes[N_WORD_PHONEMES]
Referenced by TranslateWord(), and TranslateWord2().