navit: map/mg/tree.c File Reference
tree.c File Reference
#include <stdio.h>
#include <string.h>
#include "debug.h"
#include "mg.h"
Data Structures
struct tree_hdr
struct tree_hdr_h
struct tree_leaf_h
struct tree_hdr_v
struct tree_leaf_v
Functions
static unsigned int tree_hdr_get_addr (struct tree_hdr *tree)
static unsigned int tree_hdr_get_size (struct tree_hdr *tree)
static unsigned int tree_hdr_get_low (struct tree_hdr *tree)
static unsigned int tree_hdr_h_get_addr (struct tree_hdr_h *tree)
static unsigned int tree_hdr_h_get_size (struct tree_hdr_h *tree)
static unsigned int tree_leaf_h_get_lower (struct tree_leaf_h *tree)
static unsigned int tree_leaf_h_get_higher (struct tree_leaf_h *tree)
static unsigned int tree_leaf_h_get_match (struct tree_leaf_h *tree)
static unsigned int tree_leaf_h_get_value (struct tree_leaf_h *tree)
static unsigned int tree_hdr_v_get_count (struct tree_hdr_v *tree)
static unsigned int tree_hdr_v_get_next (struct tree_hdr_v *tree)
static unsigned int tree_hdr_v_get_unknown (struct tree_hdr_v *tree)
struct tree_leaf_v __attribute__ ((packed))
static int tree_leaf_v_get_value (struct tree_leaf_v *tree)
static int tree_search_h (struct file *file, unsigned int search)
static int tree_search_v (struct file *file, int offset, int search)
int tree_search_hv (char *dirname, char *filename, unsigned int search_h, unsigned int search_v, int *result)
static struct tree_search_node * tree_search_enter (struct tree_search *ts, int offset)
int tree_search_next (struct tree_search *ts, unsigned char **p, int dir)
int tree_search_next_lin (struct tree_search *ts, unsigned char **p)
void tree_search_init (char *dirname, char *filename, struct tree_search *ts, int offset)
void tree_search_free (struct tree_search *ts)
Variables
struct tree_hdr __attribute__
unsigned char key
unsigned char p [4]
Function Documentation
struct tree_leaf_v __attribute__ ((packed))
static unsigned int tree_hdr_get_addr (struct tree_hdr * tree) inline static
References get_u32(), tree_hdr::p, and p.
Referenced by tree_search_enter().
static unsigned int tree_hdr_get_low (struct tree_hdr * tree) inline static
References get_u32(), tree_hdr::p, and p.
Referenced by tree_search_enter().
static unsigned int tree_hdr_get_size (struct tree_hdr * tree) inline static
References get_u32(), tree_hdr::p, and p.
Referenced by tree_search_enter().
static unsigned int tree_hdr_h_get_addr (struct tree_hdr_h * tree) inline static
References get_u32(), tree_hdr_h::p, and p.
static unsigned int tree_hdr_h_get_size (struct tree_hdr_h * tree) inline static
References get_u32(), tree_hdr_h::p, and p.
Referenced by tree_search_h().
static unsigned int tree_hdr_v_get_count (struct tree_hdr_v * tree) inline static
References get_u32_unal(), tree_hdr_v::p, and p.
Referenced by tree_search_v().
static unsigned int tree_hdr_v_get_next (struct tree_hdr_v * tree) inline static
References get_u32_unal(), tree_hdr_v::p, and p.
Referenced by tree_search_v().
static unsigned int tree_hdr_v_get_unknown (struct tree_hdr_v * tree) inline static
References get_u32_unal(), tree_hdr_v::p, and p.
static unsigned int tree_leaf_h_get_higher (struct tree_leaf_h * tree) inline static
References get_u32(), tree_leaf_h::p, and p.
Referenced by tree_search_h().
static unsigned int tree_leaf_h_get_lower (struct tree_leaf_h * tree) inline static
References get_u32(), tree_leaf_h::p, and p.
Referenced by tree_search_h().
static unsigned int tree_leaf_h_get_match (struct tree_leaf_h * tree) inline static
References get_u32(), tree_leaf_h::p, and p.
Referenced by tree_search_h().
static unsigned int tree_leaf_h_get_value (struct tree_leaf_h * tree) inline static
References get_u32(), tree_leaf_h::p, and p.
Referenced by tree_search_h().
static int tree_leaf_v_get_value (struct tree_leaf_v * tree) inline static
References get_u32_unal(), p, and tree_leaf_v::p.
Referenced by tree_search_v().
static struct tree_search_node* tree_search_enter (struct tree_search * ts, int offset) static
References file::begin, tree_search::curr_node, dbg, tree_search_node::end, tree_search::f, tree_search_node::hdr, tree_search_node::high, tree_search_node::last, tree_search_node::low, lvl_debug, tree_search::nodes, offset, p, tree_search_node::p, tree_hdr_get_addr(), tree_hdr_get_low(), and tree_hdr_get_size().
Referenced by tree_search_init(), tree_search_next(), and tree_search_next_lin().
void tree_search_free (struct tree_search * ts)
References tree_search::f, and file_destroy().
Referenced by map_search_cleanup().
static int tree_search_h (struct file * file, unsigned int search) static
References file::begin, dbg, i, lvl_debug, p, tree_hdr_h_get_size(), tree_leaf_h_get_higher(), tree_leaf_h_get_lower(), tree_leaf_h_get_match(), tree_leaf_h_get_value(), and value.
Referenced by tree_search_hv().
int tree_search_hv (char * dirname, char * filename, unsigned int search_h, unsigned int search_v, int * result)
References dbg, file_create_caseinsensitive(), file_destroy(), file_mmap(), lvl_debug, sprintf(), tree_search_h(), and tree_search_v().
Referenced by town_get_byid().
void tree_search_init (char * dirname, char * filename, struct tree_search * ts, int offset)
References tree_search::curr_node, tree_search::f, file_create_caseinsensitive(), file_mmap(), sprintf(), and tree_search_enter().
Referenced by map_search_setup().
int tree_search_next (struct tree_search * ts, unsigned char ** p, int dir)
References file::begin, tree_search::curr_node, dbg, tree_search_node::end, tree_search::f, get_u32(), get_u32_unal(), tree_search_node::high, tree_search_node::last, tree_search::last_node, tree_search_node::low, lvl_debug, tree_search::nodes, p, tree_search_node::p, and tree_search_enter().
Referenced by street_search_get_item_street_name(), and town_search_get_item().
int tree_search_next_lin (struct tree_search * ts, unsigned char ** p)
References file::begin, tree_search::curr_node, dbg, tree_search_node::end, tree_search::f, get_u32_unal(), tree_search_node::high, tree_search_node::last, tree_search::last_node, tree_search_node::low, lvl_debug, tree_search::nodes, p, and tree_search_enter().
Referenced by town_search_get_item().
static int tree_search_v (struct file * file, int offset, int search) static
References file::begin, dbg, i, tree_leaf_v::key, lvl_debug, next, offset, p, tree_hdr_v_get_count(), tree_hdr_v_get_next(), and tree_leaf_v_get_value().
Referenced by tree_search_hv().
Variable Documentation
struct tree_hdr __attribute__
unsigned char key
Referenced by binfile_hash_entry_hash(), bsearch(), coord_hash(), org.navitproject.navit.NavitRestoreTask::doInBackground(), duplicate_hash(), edge_hash_hash(), fh_comparedata(), fh_deleteel(), fh_insertkey(), fh_replacekeydata(), g_hash_table_insert_internal(), g_private_new_navit(), gui_internal_cmd_pois(), HandleKeyChar(), HandleKeyDown(), image_new(), item_hash_hash(), item_id_hash(), keypress(), QNavitQuick::keyPressEvent(), QNavitWidget::keyPressEvent(), LoadVoice(), navit_cmd_set_attr_var(), navit_cmd_set_int_var(), osd_text_prepare(), overlay_disable(), org.navitproject.navit.NavitTextTranslations::p(), paintOverlays(), png_handle_tEXt(), png_set_text_2(), ProcessNormalKeys(), ProcessSpecialKeys(), relations_member_hash(), search_item_hash_hash(), smc_tree_insert(), write_changes_do(), write_countrydir(), and xmlconfig_announce().
unsigned char p[4]
Referenced by tree_hdr_get_addr(), tree_hdr_get_low(), tree_hdr_get_size(), tree_hdr_h_get_addr(), tree_hdr_h_get_size(), tree_hdr_v_get_count(), tree_hdr_v_get_next(), tree_hdr_v_get_unknown(), tree_leaf_h_get_higher(), tree_leaf_h_get_lower(), tree_leaf_h_get_match(), tree_leaf_h_get_value(), tree_leaf_v_get_value(), tree_search_enter(), tree_search_h(), tree_search_next(), tree_search_next_lin(), and tree_search_v().