navit: support/libc/unlink.c File Reference
unlink.c File Reference
#include <stdio.h>
#include <windows.h>
Functions
int _unlink (const char *file)
int unlink (const char *file)
Function Documentation
int _unlink (const char * file)
Referenced by unlink().
int unlink (const char * file)
References _unlink().
Referenced by bookmarks_store_bookmarks_to_file(), gui_internal_set(), main(), maptool_assemble_map(), osm_read_input_data(), remove_countryfiles(), save_map_csv(), sort_countries(), tempfile_unlink(), and VSI_SHP_Remove().