navit: fib-1.1/use.c File Reference
use.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "fib.h"
Macros
#define TESTCASE 1
#define COUNT 100000
#define DIF 1000
#define MAXEXT 10
#define VERBOSE 1
Functions
int cmp (void *, void *)
int main (void)
Macro Definition Documentation
#define COUNT 100000
Referenced by main().
#define DIF 1000
Referenced by main().
#define MAXEXT 10
Referenced by main().
#define TESTCASE 1
#define VERBOSE 1
Function Documentation
int cmp (void * x, void * y)
References int.
Referenced by bsearch(), g_list_insert_sorted_real(), g_list_sort_merge(), main(), parse_pixel_line_values(), and smc_tree_branch_lookup_nearest_L().
int main (void)
References cmp(), COUNT, DIF, exit, fh_delete(), fh_deleteheap(), fh_extractmin(), fh_insert(), fh_makeheap(), fh_setcmp(), i, MAXEXT, NULL, printf(), and time().