navit: tools/gpx2navit_txt/src/utils.c File Reference
utils.c File Reference
#include "gpx2navit_txt.h"
#include "projects.h"
#include "geodesic.h"
Functions
double getDistanceCore (char *p1, char *l1, char *p2, char *l2)
void checkEllpsUnit (char *unit)
double checkLengthUnit (char *unit)
int checkTimeUnit (char *unit)
double getTimeInterval (char *_t, char *t)
double getSpeed (double length, double ti, double to_meter, int to_sec)
double getDistance (double _x, double _y, double x, double y)
void * myMallocRep (size_t size, const char *fileName, int line)
Function Documentation
void checkEllpsUnit (char * unit)
References ERR_ELLPSUNIT, exit, and printf().
Referenced by setDefault().
double checkLengthUnit (char * unit)
References ERR_LENGTHUNIT, exit, printf(), and to_meter.
Referenced by setDefault().
int checkTimeUnit (char * unit)
References ERR_TIMEUNIT, exit, i, and p.
Referenced by setDefault().
double getDistance (double _x, double _y, double x, double y)
References getDistanceCore(), length, and sprintf().
Referenced by setPathInterval().
double getDistanceCore (char * p1, char * l1, char * p2, char * l2)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References geod_inv(), geod_S, lam1, lam2, phi1, and phi2.
Referenced by getDistance().
double getSpeed (double length, double ti, double to_meter, int to_sec)
References speed, and to_meter.
Referenced by setPath(), and setPathInterval().
double getTimeInterval (char * _t, char * t)
References mktime().
Referenced by setPathInterval().
void* myMallocRep (size_t size, const char * fileName, int line)