navit: support/gettext_intl/vasnprintf.c File Reference
vasnprintf.c File Reference
#include <alloca.h>
#include "vasnprintf.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <limits.h>
#include <float.h>
#include "printf-parse.h"
#include "xsize.h"
Macros
#define _GNU_SOURCE 1
#define VASNPRINTF vasnprintf
#define CHAR_T char
#define DIRECTIVE char_directive
#define DIRECTIVES char_directives
#define PRINTF_PARSE printf_parse
#define USE_SNPRINTF (HAVE_DECL__SNPRINTF || HAVE_SNPRINTF)
#define SNPRINTF snprintf
#define CLEANUP()
#define ENSURE_ALLOCATION(needed)
#define SNPRINTF_BUF(arg)
Functions
CHAR_T * VASNPRINTF (CHAR_T *resultbuf, size_t *lengthp, const CHAR_T *format, va_list args)
Macro Definition Documentation
#define _GNU_SOURCE 1
#define CHAR_T char
Referenced by VASNPRINTF().
#define CLEANUP ()
Value:
free (d.dir);                                                           \
  if (a.arg)                                                            \
    free (a.arg);
Referenced by VASNPRINTF().
#define DIRECTIVE char_directive
Referenced by VASNPRINTF().
#define DIRECTIVES char_directives
Referenced by VASNPRINTF().
#define ENSURE_ALLOCATION (needed)
Value:
if ((needed) > allocated)                                                    \
      {                                                                      \
        size_t memory_size;                                                  \
    CHAR_T *memory;                                                             \
                                                                             \
        allocated = (allocated > 0 ? xtimes (allocated, 2) : 12);            \
    if ((needed) > allocated)                                           \
          allocated = (needed);                                              \
        memory_size = xtimes (allocated, sizeof (CHAR_T));                   \
    if (size_overflow_p (memory_size))                                  \
          goto out_of_memory;                                                \
    if (result == resultbuf || result == NULL)                          \
          memory = (CHAR_T *) malloc (memory_size);                          \
        else                                                                 \
          memory = (CHAR_T *) realloc (result, memory_size);                 \
    if (memory == NULL)                                                 \
          goto out_of_memory;                                                \
    if (result == resultbuf && length > 0)                              \
          memcpy (memory, result, length * sizeof (CHAR_T));                 \
        result = memory;                                                     \
      }
Referenced by VASNPRINTF().
#define PRINTF_PARSE printf_parse
Referenced by VASNPRINTF().
#define SNPRINTF snprintf
#define SNPRINTF_BUF (arg)
Value:
switch (prefix_count)                               \
                      {                                                     \
                      case 0:                                               \
                        count = sprintf (tmp, buf, arg);                    \
                        break;                                              \
                      case 1:                                               \
                        count = sprintf (tmp, buf, prefixes[0], arg);       \
                        break;                                              \
                      case 2:                                               \
                        count = sprintf (tmp, buf, prefixes[0], prefixes[1],\
                                         arg);                              \
                        break;                                              \
                      default:                                              \
            abort ();                                        \
                      }
Referenced by VASNPRINTF().
#define USE_SNPRINTF (HAVE_DECL__SNPRINTF || HAVE_SNPRINTF)
#define VASNPRINTF vasnprintf
Function Documentation
CHAR_T* VASNPRINTF (CHAR_T * resultbuf, size_t * lengthp, const CHAR_T * format, va_list args)
References argument::a, argument::a_char, argument::a_count_int_pointer, argument::a_count_longint_pointer, argument::a_count_schar_pointer, argument::a_count_short_pointer, argument::a_double, argument::a_int, argument::a_longint, argument::a_pointer, argument::a_schar, argument::a_short, argument::a_string, argument::a_uchar, argument::a_uint, argument::a_ulongint, argument::a_ushort, abort(), alloca, arguments::arg, ARG_NONE, buf, CHAR_T, CLEANUP, parse_args::cp, DIRECTIVE, DIRECTIVES, EINVAL, ENOMEM, ENSURE_ALLOCATION, errno, FLAG_ALT, FLAG_GROUP, FLAG_LEFT, FLAG_SHOWSIGN, FLAG_SPACE, FLAG_ZERO, i, int, length, NULL, p, printf_fetchargs(), PRINTF_PARSE, size_overflow_p, SNPRINTF_BUF, argument::type, type, TYPE_CHAR, TYPE_COUNT_INT_POINTER, TYPE_COUNT_LONGINT_POINTER, TYPE_COUNT_SCHAR_POINTER, TYPE_COUNT_SHORT_POINTER, TYPE_DOUBLE, TYPE_INT, TYPE_LONGINT, TYPE_POINTER, TYPE_SCHAR, TYPE_SHORT, TYPE_STRING, TYPE_UCHAR, TYPE_UINT, TYPE_ULONGINT, TYPE_USHORT, width, xmax(), xsum(), xsum4(), and xtimes.