navit: vehicle/demo/vehicle_demo.c File Reference
vehicle_demo.c File Reference
#include <glib.h>
#include <string.h>
#include <math.h>
#include "config.h"
#include "debug.h"
#include "coord.h"
#include "item.h"
#include "navit.h"
#include "map.h"
#include "route.h"
#include "callback.h"
#include "transform.h"
#include "plugin.h"
#include "vehicle.h"
#include "event.h"
#include "util.h"
Data Structures
struct vehicle_priv
Functions
static void vehicle_demo_destroy (struct vehicle_priv *priv)
static void nmea_chksum (char *nmea)
static int vehicle_demo_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_demo_set_attr_do (struct vehicle_priv *priv, struct attr *attr)
static int vehicle_demo_set_attr (struct vehicle_priv *priv, struct attr *attr)
static void vehicle_demo_timer (struct vehicle_priv *priv)
static struct vehicle_priv * vehicle_demo_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
struct vehicle_methods vehicle_demo_methods
Function Documentation
static void nmea_chksum (char * nmea) static
References i, and sprintf().
Referenced by vehicle_demo_position_attr_get().
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_demo_new().
static void vehicle_demo_destroy (struct vehicle_priv * priv) static
References callback_destroy(), event_remove_timeout(), g_free(), vehicle_priv::timep, vehicle_priv::timer, and vehicle_priv::timer_callback.
static struct vehicle_priv* vehicle_demo_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References attr_position_valid_invalid, callback_cast, callback_new_1, vehicle_priv::cbl, cbl, vehicle_priv::config_speed, dbg, event_add_timeout(), g_new0, vehicle_priv::interval, lvl_debug, vehicle_priv::timer, vehicle_priv::timer_callback, vehicle_priv::valid, vehicle_demo_methods, vehicle_demo_set_attr_do(), and vehicle_demo_timer().
Referenced by plugin_init().
static int vehicle_demo_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References attr::coord_geo, current_to_iso8601(), vehicle_priv::direction, g_free(), g_strdup_printf(), vehicle_priv::geo, coord_geo::lat, lat, coord_geo::lng, vehicle_priv::nmea, nmea_chksum(), attr::num, attr::numd, vehicle_priv::speed, attr::str, vehicle_priv::timep, type, attr::type, attr::u, and vehicle_priv::valid.
static int vehicle_demo_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References vehicle_demo_set_attr_do().
static int vehicle_demo_set_attr_do (struct vehicle_priv * priv, struct attr * attr) static
References attr_position_valid_valid, attr_to_name(), callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::config_speed, attr::coord_geo, dbg, event_add_timeout(), event_remove_timeout(), vehicle_priv::geo, vehicle_priv::interval, coord_geo::lat, coord_geo::lng, lvl_debug, lvl_error, vehicle_priv::navit, attr::navit, attr::num, vehicle_priv::position_set, vehicle_priv::route, attr::route, vehicle_priv::timer, vehicle_priv::timer_callback, attr::type, attr::u, and vehicle_priv::valid.
Referenced by vehicle_demo_new(), and vehicle_demo_set_attr().
static void vehicle_demo_timer (struct vehicle_priv * priv) static
References attr_position_valid_valid, c, callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::config_speed, dbg, vehicle_priv::direction, vehicle_priv::geo, vehicle_priv::interval, item_coord_get(), vehicle_priv::last, lvl_debug, lvl_warning, map_rect_destroy(), map_rect_get_item(), map_rect_new(), vehicle_priv::navit, navit_get_route(), NULL, startup::pos, vehicle_priv::position_set, projection_mg, vehicle_priv::route, route_get_map(), vehicle_priv::speed, transform_distance(), transform_get_angle_delta(), transform_to_geo(), item::type, vehicle_priv::valid, coord::x, and coord::y.
Referenced by vehicle_demo_new().
Variable Documentation
struct vehicle_methods vehicle_demo_methods
Initial value:
= {
        vehicle_demo_destroy,
        vehicle_demo_position_attr_get,
        vehicle_demo_set_attr,
}
Referenced by vehicle_demo_new().