navit: vehicleprofile.h File Reference
vehicleprofile.h File Reference
#include "callback.h"
#include "navit.h"
Data Structures
struct vehicleprofile
Enumerations
enum maxspeed_handling { maxspeed_enforce = 0 , maxspeed_restrict = 1 , maxspeed_ignore = 2 }
Functions
struct vehicleprofile * vehicleprofile_new (struct attr *parent, struct attr **attrs)
struct attr_iter * vehicleprofile_attr_iter_new (void *unused)
void vehicleprofile_attr_iter_destroy (struct attr_iter *iter)
int vehicleprofile_get_attr (struct vehicleprofile *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int vehicleprofile_set_attr (struct vehicleprofile *this_, struct attr *attr)
int vehicleprofile_add_attr (struct vehicleprofile *this_, struct attr *attr)
int vehicleprofile_remove_attr (struct vehicleprofile *this_, struct attr *attr)
struct roadprofile * vehicleprofile_get_roadprofile (struct vehicleprofile *this_, enum item_type type)
char * vehicleprofile_get_name (struct vehicleprofile *this_)
Returns the vehicle profile's name.
Enumeration Type Documentation
maxspeed_handling
enum maxspeed_handling
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Enumerator
maxspeed_enforce
Always enforce maxspeed of segment
maxspeed_restrict
Enforce maxspeed of segment only if it restricts the speed
maxspeed_ignore
Ignore maxspeed of segment, always use route_weight of road profile
Function Documentation
vehicleprofile_add_attr()
int vehicleprofile_add_attr (struct vehicleprofile * this_, struct attr * attr)
References vehicleprofile::active_callback, attr_generic_add_attr(), attr::navit_object, attr::type, attr::u, and vehicleprofile_apply_roadprofile().
vehicleprofile_attr_iter_destroy()
void vehicleprofile_attr_iter_destroy (struct attr_iter * iter)
References attr_iter::iter.
Referenced by request_vehicleprofile_attr_iter_destroy(), and vehicleprofile_update().
vehicleprofile_attr_iter_new()
struct attr_iter * vehicleprofile_attr_iter_new (void * unused)
Referenced by request_vehicleprofile_attr_iter(), and vehicleprofile_update().
vehicleprofile_get_attr()
int vehicleprofile_get_attr (struct vehicleprofile * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), attr_iter::iter, and type.
Referenced by navit_set_vehicleprofile_name(), request_vehicleprofile_get_attr(), tracking_update(), and vehicleprofile_update().
vehicleprofile_get_name()
char * vehicleprofile_get_name (struct vehicleprofile * this_)
Returns the vehicle profile's name.
References vehicleprofile::name.
vehicleprofile_get_roadprofile()
struct roadprofile * vehicleprofile_get_roadprofile (struct vehicleprofile * this_, enum item_type type)
References vehicleprofile::roadprofile_hash, and type.
Referenced by osd_speed_warner_draw(), osd_text_draw(), route_graph_add_street(), and route_seg_speed().
vehicleprofile_new()
struct vehicleprofile * vehicleprofile_new (struct attr * parent, struct attr ** attrs)
References vehicleprofile::active_callback, attr_list_dup(), attr_search(), attrs, attr::callback, callback_cast, callback_new_attr_1, navit_object_ref(), attr::type, attr::u, vehicleprofile_clear(), vehicleprofile_func, vehicleprofile_set_attr_do(), and vehicleprofile_update().
vehicleprofile_remove_attr()
int vehicleprofile_remove_attr (struct vehicleprofile * this_, struct attr * attr)
References attr_generic_remove_attr().
vehicleprofile_set_attr()
int vehicleprofile_set_attr (struct vehicleprofile * this_, struct attr * attr)
References attr_generic_set_attr(), and vehicleprofile_set_attr_do().
Referenced by request_vehicleprofile_set_attr().