navit: vehicle/webos/vehicle_webos.c File Reference
vehicle_webos.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <errno.h>
#include <sys/time.h>
#include <PDL.h>
#include <SDL.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "vehicle.h"
#include "event.h"
#include "vehicle_webos.h"
#include "bluetooth.h"
Functions
static void vehicle_webos_callback (PDL_ServiceParameters *params, void *priv)
static void vehicle_webos_gps_update (struct vehicle_priv *priv, PDL_Location *location)
static void vehicle_webos_timeout_callback (struct vehicle_priv *priv)
void vehicle_webos_close (struct vehicle_priv *priv)
static int vehicle_webos_open (struct vehicle_priv *priv)
static void vehicle_webos_destroy (struct vehicle_priv *priv)
static int vehicle_webos_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_webos_set_attr_do (struct vehicle_priv *priv, struct attr *attr, int init)
static int vehicle_webos_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_webos_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
static char * vehicle_webos_prefix ="webos:"
struct vehicle_methods vehicle_webos_methods
Function Documentation
void plugin_init (void)
The plugin entry point.
Description: Initialisation of vehicle_file plugin
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, lvl_debug, and vehicle_webos_new().
static void vehicle_webos_callback (PDL_ServiceParameters * params, void * priv) static
References dbg, err(), g_new0, location, lvl_error, and NULL.
Referenced by vehicle_webos_close(), and vehicle_webos_open().
void vehicle_webos_close (struct vehicle_priv * priv)
References callback_destroy(), vehicle_priv::ev_timeout, event_remove_timeout(), NULL, vehicle_priv::pdk_version, vehicle_priv::timeout_cb, vehicle_webos_bt_close(), and vehicle_webos_callback().
Referenced by vehicle_webos_bt_open(), vehicle_webos_destroy(), vehicle_webos_init_bt_gps(), vehicle_webos_open(), vehicle_webos_set_attr_do(), and vehicle_webos_spp_init_read().
static void vehicle_webos_destroy (struct vehicle_priv * priv) static
References g_free(), vehicle_priv::source, and vehicle_webos_close().
static void vehicle_webos_gps_update (struct vehicle_priv * priv, PDL_Location * location) static
References vehicle_priv::altitude, callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::delta, vehicle_priv::fix_time, g_free(), vehicle_priv::geo, gettimeofday(), int, coord_geo::lat, coord_geo::lng, lvl_info, NULL, vehicle_priv::pdk_version, vehicle_priv::radius, vehicle_priv::speed, vehicle_priv::track, and timeval::tv_sec.
Referenced by vehicle_webos_set_attr_do().
static struct vehicle_priv* vehicle_webos_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References vehicle_priv::attrs, callback_cast, callback_new_1, vehicle_priv::cbl, cbl, g_new0, vehicle_priv::timeout_cb, vehicle_webos_methods, vehicle_webos_open(), vehicle_webos_set_attr_do(), and vehicle_webos_timeout_callback().
Referenced by plugin_init().
static int vehicle_webos_open (struct vehicle_priv * priv) static
References dbg, err(), vehicle_priv::ev_timeout, event_add_timeout(), vehicle_priv::gps_type, GPS_TYPE_INT, lvl_debug, lvl_error, vehicle_priv::pdk_version, vehicle_priv::timeout_cb, vehicle_webos_bt_open(), vehicle_webos_callback(), and vehicle_webos_close().
Referenced by vehicle_webos_new(), and vehicle_webos_set_attr_do().
static int vehicle_webos_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References vehicle_priv::altitude, attr::coord_geo, dbg, vehicle_priv::delta, vehicle_priv::fix_time, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::gps_type, GPS_TYPE_BT, GPS_TYPE_INT, vehicle_priv::hdop, coord_geo::lat, coord_geo::lng, lvl_info, vehicle_priv::magnetic_direction, attr::num, attr::numd, vehicle_priv::radius, vehicle_priv::sats_used, vehicle_priv::speed, vehicle_priv::status, attr::str, vehicle_priv::track, type, attr::type, and attr::u.
static int vehicle_webos_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References vehicle_webos_set_attr_do().
static int vehicle_webos_set_attr_do (struct vehicle_priv * priv, struct attr * attr, int init) static
References vehicle_priv::address, attr::data, dbg, g_free(), g_strdup(), lvl_warning, NULL, vehicle_priv::source, attr::str, attr::type, attr::u, vehicle_webos_close(), vehicle_webos_gps_update(), vehicle_webos_open(), and vehicle_webos_prefix.
Referenced by vehicle_webos_new(), and vehicle_webos_set_attr().
static void vehicle_webos_timeout_callback (struct vehicle_priv * priv) static
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::delta, vehicle_priv::fix_time, gettimeofday(), int, lvl_warning, NULL, vehicle_priv::timeout_cb, and timeval::tv_sec.
Referenced by vehicle_webos_new().
Variable Documentation
struct vehicle_methods vehicle_webos_methods
Initial value:
= {
        vehicle_webos_destroy,
        vehicle_webos_position_attr_get,
        vehicle_webos_set_attr,
}
Referenced by vehicle_webos_new().
char* vehicle_webos_prefix ="webos:" static
vim: sw=3 ts=3
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by vehicle_webos_set_attr_do().