navit: vehicleprofile.c File Reference
vehicleprofile.c File Reference
#include <stdlib.h>
#include <glib.h>
#include <string.h>
#include "debug.h"
#include "item.h"
#include "xmlconfig.h"
#include "roadprofile.h"
#include "vehicleprofile.h"
#include "callback.h"
Functions
static void vehicleprofile_set_attr_do (struct vehicleprofile *this_, struct attr *attr)
static void vehicleprofile_free_hash_item (gpointer key, gpointer value, gpointer user_data)
static void vehicleprofile_free_hash (struct vehicleprofile *this_)
static void vehicleprofile_clear (struct vehicleprofile *this_)
static void vehicleprofile_apply_roadprofile (struct vehicleprofile *this_, struct navit_object *rp, int is_option)
static void vehicleprofile_apply_attrs (struct vehicleprofile *this_, struct navit_object *obj, int is_option)
static void vehicleprofile_debug_roadprofile (gpointer key, gpointer value, gpointer user_data)
static void vehicleprofile_update (struct vehicleprofile *this_)
struct vehicleprofile * vehicleprofile_new (struct attr *parent, struct attr **attrs)
struct attr_iter * vehicleprofile_attr_iter_new (void)
void vehicleprofile_attr_iter_destroy (struct attr_iter *iter)
int vehicleprofile_get_attr (struct vehicleprofile *this_, enum attr_type type, struct attr *attr, struct attr_iter *iter)
int vehicleprofile_set_attr (struct vehicleprofile *this_, struct attr *attr)
int vehicleprofile_add_attr (struct vehicleprofile *this_, struct attr *attr)
int vehicleprofile_remove_attr (struct vehicleprofile *this_, struct attr *attr)
struct roadprofile * vehicleprofile_get_roadprofile (struct vehicleprofile *this_, enum item_type type)
char * vehicleprofile_get_name (struct vehicleprofile *this_)
Returns the vehicle profile's name.
static void vehicleprofile_init (struct vehicleprofile *this_)
Variables
struct object_func vehicleprofile_func
Function Documentation
int vehicleprofile_add_attr (struct vehicleprofile * this_, struct attr * attr)
References vehicleprofile::active_callback, attr_generic_add_attr(), attr::navit_object, attr::type, attr::u, and vehicleprofile_apply_roadprofile().
static void vehicleprofile_apply_attrs (struct vehicleprofile * this_, struct navit_object * obj, int is_option) static
References attr_to_name(), dbg, eval::iter, lvl_debug, attr::navit_object, NULL, attr::type, attr::u, vehicleprofile_apply_roadprofile(), and vehicleprofile_set_attr_do().
Referenced by vehicleprofile_update().
static void vehicleprofile_apply_roadprofile (struct vehicleprofile * this_, struct navit_object * rp, int is_option) static
References dbg, g_hash_table_insert(), g_hash_table_lookup(), item_get_default_flags(), item_to_name(), attr::item_types, eval::iter, lvl_debug, lvl_error, vehicleprofile::name, NULL, vehicleprofile::roadprofile_hash, types, and attr::u.
Referenced by vehicleprofile_add_attr(), and vehicleprofile_apply_attrs().
void vehicleprofile_attr_iter_destroy (struct attr_iter * iter)
References g_free().
Referenced by request_vehicleprofile_attr_iter_destroy(), and vehicleprofile_update().
struct attr_iter* vehicleprofile_attr_iter_new (void)
References g_new0.
Referenced by request_vehicleprofile_attr_iter(), and vehicleprofile_update().
static void vehicleprofile_clear (struct vehicleprofile * this_) static
References vehicleprofile::axle_weight, vehicleprofile::dangerous_goods, vehicleprofile::flags, vehicleprofile::flags_forward_mask, vehicleprofile::flags_reverse_mask, g_free(), g_hash_table_new(), vehicleprofile::height, vehicleprofile::length, maxspeed_enforce, vehicleprofile::maxspeed_handling, vehicleprofile::mode, vehicleprofile::name, NULL, vehicleprofile::roadprofile_hash, vehicleprofile::route_depth, vehicleprofile::static_distance, vehicleprofile::static_speed, vehicleprofile::through_traffic_penalty, vehicleprofile_free_hash(), vehicleprofile::weight, and vehicleprofile::width.
Referenced by vehicleprofile_new(), and vehicleprofile_update().
static void vehicleprofile_debug_roadprofile (gpointer key, gpointer value, gpointer user_data) static
References dbg, item_to_name(), lvl_debug, roadprofile::maxspeed, roadprofile::route_weight, roadprofile::speed, and value.
Referenced by vehicleprofile_update().
static void vehicleprofile_free_hash (struct vehicleprofile * this_) static
References g_hash_table_destroy(), g_hash_table_foreach(), NULL, vehicleprofile::roadprofile_hash, and vehicleprofile_free_hash_item().
Referenced by vehicleprofile_clear().
static void vehicleprofile_free_hash_item (gpointer key, gpointer value, gpointer user_data) static
References value.
Referenced by vehicleprofile_free_hash().
int vehicleprofile_get_attr (struct vehicleprofile * this_, enum attr_type type, struct attr * attr, struct attr_iter * iter)
References attr_generic_get_attr(), and NULL.
Referenced by navit_set_vehicleprofile_name(), request_vehicleprofile_get_attr(), tracking_update(), and vehicleprofile_update().
char* vehicleprofile_get_name (struct vehicleprofile * this_)
Returns the vehicle profile's name.
References vehicleprofile::name.
struct roadprofile* vehicleprofile_get_roadprofile (struct vehicleprofile * this_, enum item_type type)
References g_hash_table_lookup(), and vehicleprofile::roadprofile_hash.
Referenced by osd_speed_warner_draw(), osd_text_draw(), route_process_street_graph(), and route_seg_speed().
static void vehicleprofile_init (struct vehicleprofile * this_) static
References vehicleprofile_update().
struct vehicleprofile* vehicleprofile_new (struct attr * parent, struct attr ** attrs)
References vehicleprofile::active_callback, attr_list_dup(), attr_search(), attr::callback, callback_cast, callback_new_attr_1, g_new0, navit_object_ref(), NULL, attr::type, attr::u, vehicleprofile_clear(), vehicleprofile_func, vehicleprofile_set_attr_do(), and vehicleprofile_update().
int vehicleprofile_remove_attr (struct vehicleprofile * this_, struct attr * attr)
References attr_generic_remove_attr().
int vehicleprofile_set_attr (struct vehicleprofile * this_, struct attr * attr)
References attr_generic_set_attr(), and vehicleprofile_set_attr_do().
Referenced by request_vehicleprofile_set_attr().
static void vehicleprofile_set_attr_do (struct vehicleprofile * this_, struct attr * attr) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References attr_to_name(), vehicleprofile::axle_weight, vehicleprofile::dangerous_goods, dbg, vehicleprofile::flags, vehicleprofile::flags_forward_mask, vehicleprofile::flags_reverse_mask, g_free(), g_strdup(), vehicleprofile::height, vehicleprofile::length, lvl_debug, vehicleprofile::maxspeed_handling, vehicleprofile::mode, vehicleprofile::name, attr::num, vehicleprofile::route_depth, vehicleprofile::static_distance, vehicleprofile::static_speed, attr::str, vehicleprofile::through_traffic_penalty, vehicleprofile::turn_around_penalty, vehicleprofile::turn_around_penalty2, attr::type, attr::u, vehicleprofile::weight, and vehicleprofile::width.
Referenced by vehicleprofile_apply_attrs(), vehicleprofile_new(), and vehicleprofile_set_attr().
static void vehicleprofile_update (struct vehicleprofile * this_) static
References vehicleprofile::axle_weight, vehicleprofile::dangerous_goods, dbg, vehicleprofile::flags, vehicleprofile::flags_forward_mask, vehicleprofile::flags_reverse_mask, g_hash_table_foreach(), vehicleprofile::height, if(), eval::iter, vehicleprofile::length, lvl_debug, vehicleprofile::maxspeed_handling, vehicleprofile::mode, attr::navit_object, NULL, attr::num, vehicleprofile::roadprofile_hash, vehicleprofile::static_distance, vehicleprofile::static_speed, attr::str, vehicleprofile::through_traffic_penalty, attr::u, vehicleprofile_apply_attrs(), vehicleprofile_attr_iter_destroy(), vehicleprofile_attr_iter_new(), vehicleprofile_clear(), vehicleprofile_debug_roadprofile(), vehicleprofile_get_attr(), vehicleprofile::weight, and vehicleprofile::width.
Referenced by vehicleprofile_init(), and vehicleprofile_new().
Variable Documentation
struct object_func vehicleprofile_func
Initial value:
= {
        attr_vehicleprofile,
        (object_func_new)vehicleprofile_new,
        (object_func_get_attr)vehicleprofile_get_attr,
        (object_func_iter_new)vehicleprofile_attr_iter_new,
        (object_func_iter_destroy)vehicleprofile_attr_iter_destroy,
        (object_func_set_attr)vehicleprofile_set_attr,
        (object_func_add_attr)vehicleprofile_add_attr,
        (object_func_remove_attr)vehicleprofile_remove_attr,
        (object_func_init)vehicleprofile_init,
        (object_func_destroy)NULL,
        (object_func_dup)NULL,
        (object_func_ref)navit_object_ref,
        (object_func_unref)navit_object_unref,
}
Referenced by object_func_lookup(), and vehicleprofile_new().