navit: vehicle/android/vehicle_android.c File Reference
vehicle_android.c File Reference
android uses dbus signals
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <time.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "android.h"
#include "vehicle.h"
Data Structures
struct vehicle_priv
Functions
static void vehicle_android_destroy (struct vehicle_priv *priv)
Free the android_vehicle.
static int vehicle_android_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Retrieves a vehicle attribute.
static void vehicle_android_position_callback (struct vehicle_priv *v, jobject location)
Called when a new position has been reported.
static void vehicle_android_status_callback (struct vehicle_priv *v, int sats_in_view, int sats_used)
Called when a new GPS status has been reported.
static void vehicle_android_fix_callback (struct vehicle_priv *v, int fix_type)
Called when a change in GPS fix status has been reported.
static int vehicle_android_init (struct vehicle_priv *ret)
Initializes an Android vehicle.
static struct vehicle_priv * vehicle_android_new_android (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Create android_vehicle.
void plugin_init (void)
register vehicle_android
Variables
struct vehicle_methods vehicle_android_methods
Detailed Description
android uses dbus signals
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Tim Niemeyer reddo.nosp@m.g@ma.nosp@m.sters.nosp@m.word.nosp@m..de
Date
2008-2009
Function Documentation
void plugin_init (void)
register vehicle_android
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_android_new_android().
static void vehicle_android_destroy (struct vehicle_priv * priv) static
Free the android_vehicle.
Parameters
priv vehicle_priv structure for the vehicle
Returns
nothing
References dbg, g_free(), and lvl_debug.
static void vehicle_android_fix_callback (struct vehicle_priv * v, int fix_type) static
Called when a change in GPS fix status has been reported.
This function is called by
NavitLocationListener
upon receiving a new
android.location.GPS_FIX_CHANGE
broadcast.
Parameters
v The
struct_vehicle_priv
for the vehicle
fix_type The fix type (1 = valid, 0 = invalid)
References attr_position_valid_extrapolated_time, attr_position_valid_valid, callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::fix_type, and vehicle_priv::valid.
Referenced by vehicle_android_new_android().
static int vehicle_android_init (struct vehicle_priv * ret) static
Initializes an Android vehicle.
Returns
True on success, false on failure
References android_activity, android_find_class_global(), android_find_method(), dbg, vehicle_priv::fcb, jnienv, vehicle_priv::Location_getAccuracy, vehicle_priv::Location_getAltitude, vehicle_priv::Location_getBearing, vehicle_priv::Location_getLatitude, vehicle_priv::Location_getLongitude, vehicle_priv::Location_getSpeed, vehicle_priv::Location_getTime, vehicle_priv::LocationClass, lvl_debug, lvl_error, vehicle_priv::NavitVehicle, vehicle_priv::NavitVehicleClass, NULL, vehicle_priv::pcb, and vehicle_priv::scb.
Referenced by vehicle_android_new_android().
static struct vehicle_priv* vehicle_android_new_android (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Create android_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References attr_position_valid_invalid, callback_cast, callback_new_1, vehicle_priv::cbl, cbl, dbg, vehicle_priv::fcb, g_new0, lvl_debug, vehicle_priv::pcb, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::scb, vehicle_priv::valid, vehicle_android_fix_callback(), vehicle_android_init(), vehicle_android_methods, vehicle_android_position_callback(), and vehicle_android_status_callback().
Referenced by plugin_init().
static int vehicle_android_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Retrieves a vehicle attribute.
Parameters
priv vehicle_priv structure for the vehicle
type The attribute type to retrieve
attr Points to an attr structure that will receive the attribute data
Returns
True for success, false for failure
References attr_position_valid_invalid, attr_to_name(), attr::coord_geo, dbg, vehicle_priv::direction, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::height, lvl_debug, attr::num, attr::numd, vehicle_priv::radius, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, attr::u, and vehicle_priv::valid.
static void vehicle_android_position_callback (struct vehicle_priv * v, jobject location) static
Called when a new position has been reported.
This function is called by
NavitLocationListener
upon receiving a new
Location
.
Parameters
v The
struct_vehicle_priv
for the vehicle
location A
Location
object describing the new position
References attr_position_valid_valid, callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::fixiso8601, vehicle_priv::geo, gmtime(), vehicle_priv::height, jnienv, coord_geo::lat, coord_geo::lng, vehicle_priv::Location_getAccuracy, vehicle_priv::Location_getAltitude, vehicle_priv::Location_getBearing, vehicle_priv::Location_getLatitude, vehicle_priv::Location_getLongitude, vehicle_priv::Location_getSpeed, vehicle_priv::Location_getTime, lvl_debug, vehicle_priv::radius, vehicle_priv::speed, and vehicle_priv::valid.
Referenced by vehicle_android_new_android().
static void vehicle_android_status_callback (struct vehicle_priv * v, int sats_in_view, int sats_used) static
Called when a new GPS status has been reported.
This function is called by
NavitLocationListener
upon receiving a new
GpsStatus
.
Note that
sats_used
should not be used to determine whether the vehicle's position is valid: some devices report non-zero numbers even when they do not have a fix. Position validity should be determined in
vehicle_android_fix_callback
(an invalid fix type means we have lost the fix) and
vehicle_android_position_callback
(receiving a position means we have a fix).
Parameters
v The
struct_vehicle_priv
for the vehicle
sats_in_view The number of satellites in view
sats_used The number of satellites currently used to determine the position
References callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::sats, and vehicle_priv::sats_used.
Referenced by vehicle_android_new_android().
Variable Documentation
struct vehicle_methods vehicle_android_methods
Initial value:
= {
        vehicle_android_destroy,
        vehicle_android_position_attr_get,
}
Referenced by vehicle_android_new_android().