navit: vehicle/maemo/vehicle_maemo.c File Reference
vehicle_maemo.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <location/location-gps-device.h>
#include <location/location-gpsd-control.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "vehicle.h"
#include "event.h"
Data Structures
struct vehicle_priv
Functions
static void vehicle_maemo_callback (LocationGPSDevice *device, gpointer user_data)
static void vehicle_maemo_error (LocationGPSDControl *control, LocationGPSDControlError error, gpointer user_data)
static void vehicle_maemo_open (struct vehicle_priv *priv)
static void vehicle_maemo_destroy (struct vehicle_priv *priv)
static int vehicle_maemo_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static struct vehicle_priv * vehicle_maemo_new_maemo (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
struct vehicle_methods vehicle_maemo_methods
Function Documentation
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, lvl_debug, and vehicle_maemo_new_maemo().
static void vehicle_maemo_callback (LocationGPSDevice * device, gpointer user_data) static
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, coord_geo::lat, coord_geo::lng, lvl_debug, vehicle_priv::sats, vehicle_priv::sats_used, and vehicle_priv::speed.
Referenced by vehicle_maemo_open().
static void vehicle_maemo_destroy (struct vehicle_priv * priv) static
References vehicle_priv::control, and vehicle_priv::device.
static void vehicle_maemo_error (LocationGPSDControl * control, LocationGPSDControlError error, gpointer user_data) static
References dbg, and lvl_error.
Referenced by vehicle_maemo_open().
static struct vehicle_priv* vehicle_maemo_new_maemo (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References attr_search(), vehicle_priv::attrs, attr::attrs, vehicle_priv::cbl, cbl, dbg, g_new0, g_strdup(), lvl_debug, lvl_error, NULL, attr::num, vehicle_priv::retry_interval, vehicle_priv::source, source, attr::str, attr::u, vehicle_maemo_methods, and vehicle_maemo_open().
Referenced by plugin_init().
static void vehicle_maemo_open (struct vehicle_priv * priv) static
Instantiate liblocation objects
References vehicle_priv::control, dbg, vehicle_priv::device, lvl_debug, NULL, vehicle_priv::retry_interval, vehicle_priv::source, strcasecmp(), vehicle_maemo_callback(), and vehicle_maemo_error().
Referenced by vehicle_maemo_new_maemo().
static int vehicle_maemo_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References active, attr_search(), vehicle_priv::attrs, attr::coord_geo, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, lvl_debug, NULL, attr::num, attr::numd, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
Variable Documentation
struct vehicle_methods vehicle_maemo_methods
Initial value:
= {
        vehicle_maemo_destroy,
        vehicle_maemo_position_attr_get,
}
Referenced by vehicle_maemo_new_maemo().