navit: vehicle/webos/vehicle_webos.h File Reference
vehicle_webos.h File Reference
#include "coord.h"
Data Structures
struct vehicle_priv
Macros
#define GPS_TYPE_NONE 0
#define GPS_TYPE_INT 1
#define GPS_TYPE_BT 2
Functions
void vehicle_webos_close (struct vehicle_priv *priv)
Macro Definition Documentation
#define GPS_TYPE_BT 2
Referenced by vehicle_webos_position_attr_get(), and vehicle_webos_spp_handle_open().
#define GPS_TYPE_INT 1
Referenced by vehicle_webos_init_pdl_locationtracking_callback(), vehicle_webos_open(), and vehicle_webos_position_attr_get().
#define GPS_TYPE_NONE 0
Referenced by vehicle_webos_init_pdl_locationtracking_callback(), and vehicle_webos_spp_notify().
Function Documentation
void vehicle_webos_close (struct vehicle_priv * priv)
References callback_destroy(), vehicle_priv::ev_timeout, event_remove_timeout(), NULL, vehicle_priv::pdk_version, vehicle_priv::timeout_cb, vehicle_webos_bt_close(), and vehicle_webos_callback().
Referenced by vehicle_webos_bt_open(), vehicle_webos_destroy(), vehicle_webos_init_bt_gps(), vehicle_webos_open(), vehicle_webos_set_attr_do(), and vehicle_webos_spp_init_read().