navit: vehicle/wince/vehicle_wince.c File Reference
vehicle_wince.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include <glib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <math.h>
#include "config.h"
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "event.h"
#include "vehicle.h"
#include <windows.h>
#include <windowsx.h>
#include <io.h>
#include <winioctl.h>
#include <winbase.h>
#include <wchar.h>
#include "support/win32/ConvertUTF.h"
Data Structures
struct gps_sat
struct vehicle_priv
Macros
#define SwitchToThread() Sleep(0)
#define W2A(lpw)
#define A2W(lpa)
#define IOCTL_SERVICE_REFRESH 0x4100000C
#define IOCTL_SERVICE_START 0x41000004
Typedefs
typedef int(WINAPI * PFN_BthSetMode)(DWORD pBthMode)
typedef int(WINAPI * PFN_BthGetMode)(DWORD *pBthMode)
Enumerations
enum file_type {
file_type_pipe = 1, file_type_device, file_type_file, file_type_socket,
file_type_serial, file_type_pipe = 1, file_type_device, file_type_file,
file_type_socket
}
Functions
static void vehicle_wince_disable_watch (struct vehicle_priv *priv)
static void vehicle_wince_enable_watch (struct vehicle_priv *priv)
static int vehicle_wince_parse (struct vehicle_priv *priv, char *buffer)
static int vehicle_wince_open (struct vehicle_priv *priv)
static void vehicle_wince_close (struct vehicle_priv *priv)
static void initBth (struct vehicle_priv *priv)
static int initDevice (struct vehicle_priv *priv)
static int read_win32 (struct vehicle_priv *priv, char *buffer, size_t size)
static DWORD WINAPI wince_reader_thread (LPVOID lParam)
static int vehicle_wince_available_ports (void)
static void vehicle_wince_io (struct vehicle_priv *priv)
static void vehicle_wince_destroy (struct vehicle_priv *priv)
Frees the wince_vehicle.
static int vehicle_wince_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Retrieves a vehicle attribute.
static int vehicle_wince_sat_attr_get (void *priv_data, enum attr_type type, struct attr *attr)
static struct vehicle_priv * vehicle_wince_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Creates a new wince_vehicle.
void plugin_init (void)
Registers the vehicle_wince plugin.
Variables
char * _convert = NULL
wchar_t * _wconvert = NULL
static int buffer_size = 1024
static struct item_methods vehicle_wince_sat_methods
struct vehicle_methods vehicle_wince_methods
Macro Definition Documentation
#define A2W (lpa)
Value:
(\
        ((LPCSTR)lpa == NULL) ? NULL : (\
        _wconvert = alloca(strlen(lpa)*2+1),  mbstowcs(_wconvert, lpa, strlen(lpa) * 2 + 1), _wconvert) )
Referenced by initDevice().
#define IOCTL_SERVICE_REFRESH 0x4100000C
Referenced by initDevice().
#define IOCTL_SERVICE_START 0x41000004
Referenced by initDevice().
#define SwitchToThread () Sleep(0)
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Referenced by vehicle_wince_disable_watch().
#define W2A (lpw)
Value:
(\
        ((LPCSTR)lpw == NULL) ? NULL : (\
        _convert = alloca(wcslen(lpw)+1),  wcstombs(_convert, lpw, wcslen(lpw) + 1), _convert) )
Referenced by vehicle_wince_available_ports().
Typedef Documentation
typedef int(WINAPI * PFN_BthGetMode)(DWORD *pBthMode)
typedef int(WINAPI * PFN_BthSetMode)(DWORD pBthMode)
Enumeration Type Documentation
enum file_type
Enumerator
file_type_pipe
file_type_device
file_type_file
file_type_socket
file_type_serial
file_type_pipe
file_type_device
file_type_file
file_type_socket
Function Documentation
static void initBth (struct vehicle_priv * priv) static
References BOOL(), vehicle_priv::BthSetMode, dbg, FALSE, vehicle_priv::hBthDll, lvl_debug, lvl_error, lvl_warning, NULL, and TRUE.
Referenced by vehicle_wince_new().
static int initDevice (struct vehicle_priv * priv) static
References A2W, vehicle_priv::baudrate, dbg, vehicle_priv::file_type, file_type_device, IOCTL_SERVICE_REFRESH, IOCTL_SERVICE_START, vehicle_priv::is_running, L, lvl_debug, lvl_error, vehicle_priv::m_hGPSDevice, NULL, vehicle_priv::source, and vehicle_priv::thread_up.
Referenced by wince_reader_thread().
void plugin_init (void)
Registers the vehicle_wince plugin.
The plugin entry point.
References attr::callback, callback_cast, callback_new_attr_0, config_add_attr(), dbg, lvl_debug, lvl_info, osso_navit(), attr::u, and vehicle_wince_new().
static int read_win32 (struct vehicle_priv * priv, char * buffer, size_t size) static
References buffer_size, g_mutex_lock, g_mutex_unlock, vehicle_priv::has_data, vehicle_priv::lock, MIN, vehicle_priv::read_buffer, and vehicle_priv::read_buffer_pos.
Referenced by vehicle_wince_io().
static int vehicle_wince_available_ports (void) static
References dbg, L, lvl_debug, NULL, and W2A.
Referenced by vehicle_wince_open().
static void vehicle_wince_close (struct vehicle_priv * priv) static
References dbg, and lvl_debug.
Referenced by vehicle_wince_destroy(), and vehicle_wince_io().
static void vehicle_wince_destroy (struct vehicle_priv * priv) static
Frees the wince_vehicle.
Parameters
priv vehicle_priv structure for the vehicle
References vehicle_priv::BthSetMode, vehicle_priv::buffer, g_free(), vehicle_priv::hBthDll, vehicle_priv::read_buffer, vehicle_priv::source, vehicle_wince_close(), vehicle_wince_disable_watch(), and void().
Referenced by vehicle_wince_new().
static void vehicle_wince_disable_watch (struct vehicle_priv * priv) static
References dbg, vehicle_priv::is_running, lvl_debug, vehicle_priv::m_hGPSThread, SwitchToThread, and vehicle_priv::thread_up.
Referenced by vehicle_wince_destroy(), vehicle_wince_enable_watch(), and vehicle_wince_io().
static void vehicle_wince_enable_watch (struct vehicle_priv * priv) static
References dbg, vehicle_priv::is_running, vehicle_priv::lock, lvl_debug, vehicle_priv::m_dwGPSThread, vehicle_priv::m_hGPSThread, NULL, vehicle_wince_disable_watch(), and wince_reader_thread().
Referenced by vehicle_wince_new().
static void vehicle_wince_io (struct vehicle_priv * priv) static
References vehicle_priv::buffer, vehicle_priv::buffer_pos, buffer_size, callback_list_call_attr_0, vehicle_priv::cbl, dbg, exit, vehicle_priv::file_type, file_type_file, lvl_debug, lvl_error, lvl_info, vehicle_priv::on_eof, read_win32(), size, vehicle_wince_close(), vehicle_wince_disable_watch(), vehicle_wince_open(), and vehicle_wince_parse().
Referenced by vehicle_wince_new().
static struct vehicle_priv* vehicle_wince_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Creates a new wince_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References attr_search(), vehicle_priv::attrs, attr::attrs, vehicle_priv::baudrate, vehicle_priv::buffer, buffer_size, callback_cast, callback_list_add(), callback_list_new(), callback_new_1, vehicle_priv::cbl, cbl, vehicle_priv::checksum_ignore, dbg, vehicle_priv::fd, vehicle_priv::file_type, file_type_device, file_type_file, g_malloc(), g_new0, g_strcasecmp(), g_strdup(), item::id_hi, item::id_lo, initBth(), lvl_debug, lvl_error, item::meth, NULL, attr::num, vehicle_priv::on_eof, vehicle_priv::priv_cbl, item::priv_data, vehicle_priv::read_buffer, vehicle_priv::sat_item, vehicle_priv::source, source, attr::str, time(), vehicle_priv::time, item::type, attr::u, vehicle_wince_destroy(), vehicle_wince_enable_watch(), vehicle_wince_io(), vehicle_wince_methods, vehicle_wince_open(), and vehicle_wince_sat_methods.
Referenced by plugin_init().
static int vehicle_wince_open (struct vehicle_priv * priv) static
References dbg, g_free(), g_strdup(), lvl_debug, vehicle_priv::source, and vehicle_wince_available_ports().
Referenced by vehicle_wince_io(), and vehicle_wince_new().
static int vehicle_wince_parse (struct vehicle_priv * priv, char * buffer) static
References attr_position_valid_invalid, attr_position_valid_valid, gps_sat::azimuth, buffer, vehicle_priv::checksum_ignore, vehicle_priv::current, vehicle_priv::current_count, dbg, vehicle_priv::direction, gps_sat::elevation, vehicle_priv::fixday, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, g_ascii_strtod(), g_free(), g_strcasecmp(), g_strconcat(), vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, i, coord_geo::lat, lat, coord_geo::lng, lvl_debug, lvl_error, lvl_info, vehicle_priv::magnetic_direction, vehicle_priv::next, vehicle_priv::next_count, vehicle_priv::nmea_data, vehicle_priv::nmea_data_buf, NULL, p, gps_sat::prn, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, gps_sat::snr, vehicle_priv::speed, vehicle_priv::status, and vehicle_priv::valid.
Referenced by vehicle_wince_io().
static int vehicle_wince_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Retrieves a vehicle attribute.
Parameters
priv vehicle_priv structure for the vehicle
type The attribute type to retrieve
attr Points to an attr structure that will receive the attribute data
Returns
True for success, false for failure
References attr::coord_geo, vehicle_priv::current_count, dbg, vehicle_priv::direction, vehicle_priv::fixday, vehicle_priv::fixiso8601, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, item::id_lo, attr::item, lvl_debug, vehicle_priv::magnetic_direction, vehicle_priv::nmea_data, attr::num, attr::numd, vehicle_priv::sat_item, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, vehicle_priv::speed, sprintf(), vehicle_priv::status, attr::str, type, attr::type, attr::u, and vehicle_priv::valid.
static int vehicle_wince_sat_attr_get (void * priv_data, enum attr_type type, struct attr * attr) static
References gps_sat::azimuth, vehicle_priv::current, vehicle_priv::current_count, gps_sat::elevation, item::id_lo, attr::num, gps_sat::prn, vehicle_priv::sat_item, gps_sat::snr, type, attr::type, and attr::u.
static DWORD WINAPI wince_reader_thread (LPVOID lParam) static
References BOOL(), buffer_size, bytes_read, dbg, event_call_callback(), vehicle_priv::file_type, file_type_file, g_mutex_lock, g_mutex_unlock, vehicle_priv::has_data, initDevice(), vehicle_priv::is_running, vehicle_priv::lock, lvl_debug, lvl_error, vehicle_priv::m_hGPSDevice, NULL, vehicle_priv::priv_cbl, vehicle_priv::read_buffer, vehicle_priv::read_buffer_pos, vehicle_priv::source, vehicle_priv::status, vehicle_priv::thread_up, and TRUE.
Referenced by vehicle_wince_enable_watch().
Variable Documentation
char* _convert = NULL
wchar_t* _wconvert = NULL
int buffer_size = 1024 static
Referenced by read_win32(), vehicle_wince_io(), vehicle_wince_new(), and wince_reader_thread().
struct vehicle_methods vehicle_wince_methods
Initial value:
= {
        vehicle_wince_destroy,
        vehicle_wince_position_attr_get,
        NULL,
}
Referenced by vehicle_wince_new().
struct item_methods vehicle_wince_sat_methods static
Initial value:
= {
        NULL,
        NULL,
        NULL,
        vehicle_wince_sat_attr_get,
        NULL,
        NULL,
        NULL,
        NULL,
}
Referenced by vehicle_wince_new().