navit: vehicle/file/vehicle_file.c File Reference
vehicle_file.c File Reference
#include "config.h"
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <string.h>
#include <glib.h>
#include <sys/stat.h>
#include <termios.h>
#include <math.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "event.h"
#include "vehicle.h"
#include "file.h"
Data Structures
struct gps_sat
struct vehicle_priv
Enumerations
enum file_type {
file_type_pipe = 1, file_type_device, file_type_file, file_type_socket,
file_type_serial, file_type_pipe = 1, file_type_device, file_type_file,
file_type_socket
}
Functions
static void vehicle_file_disable_watch (struct vehicle_priv *priv)
static void vehicle_file_enable_watch (struct vehicle_priv *priv)
static int vehicle_file_parse (struct vehicle_priv *priv, char *buffer)
static int vehicle_file_open (struct vehicle_priv *priv)
static void vehicle_file_close (struct vehicle_priv *priv)
static int vehicle_file_enable_watch_timer (struct vehicle_priv *priv)
static void vehicle_file_io (struct vehicle_priv *priv)
static void vehicle_file_destroy (struct vehicle_priv *priv)
static int vehicle_file_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_file_sat_attr_get (void *priv_data, enum attr_type type, struct attr *attr)
static struct vehicle_priv * vehicle_file_new_file (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
static int buffer_size = 1024
static struct item_methods vehicle_file_sat_methods
static struct vehicle_methods vehicle_file_methods
Enumeration Type Documentation
enum file_type
Enumerator
file_type_pipe
file_type_device
file_type_file
file_type_socket
file_type_serial
file_type_pipe
file_type_device
file_type_file
file_type_socket
Function Documentation
void plugin_init (void)
The plugin entry point.
Description: Initialisation of vehicle_file plugin
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_file_new_file().
static void vehicle_file_close (struct vehicle_priv * priv) static
Description: close dialogue with the GPS
Parameters
priv : pointer on the private data of the plugin
References callback_destroy(), close(), dbg, vehicle_priv::fd, vehicle_priv::file, vehicle_priv::file_type, file_type_serial, lvl_debug, NULL, pclose(), serial_io_shutdown(), and vehicle_file_disable_watch().
Referenced by vehicle_file_destroy(), and vehicle_file_io().
static void vehicle_priv vehicle_file_destroy (struct vehicle_priv * priv) static
Description: Function called to uninitialize the plugin
Parameters
priv : pointer on the private data of the plugin
Remarks
private data is freed by this function (g_free)
References attr::attrs, vehicle_priv::buffer, callback_destroy(), vehicle_priv::cb, vehicle_priv::cbt, file::f, file_create(), file_data_write(), file_destroy(), file_fsync(), g_free(), vehicle_priv::nmea_data, NULL, attr::num, vehicle_priv::source, vehicle_priv::statefile, attr::u, and vehicle_file_close().
static void vehicle_file_disable_watch (struct vehicle_priv * priv) static
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Description: Disable watch
Parameters
priv : pointer on the private data of the plugin
_WIN32
References dbg, event_remove_timeout(), event_remove_watch(), vehicle_priv::file_type, file_type_serial, lvl_debug, NULL, and vehicle_priv::watch.
Referenced by vehicle_file_close(), vehicle_file_io(), vehicle_file_parse(), and vehicle_webos_parse_nmea().
static void vehicle_file_enable_watch (struct vehicle_priv * priv) static
Description: Enable watch
Parameters
priv : pointer on the private data of the plugin
References vehicle_priv::cb, dbg, event_add_timeout(), event_add_watch(), event_watch_cond_read, vehicle_priv::fd, vehicle_priv::file_type, file_type_serial, lvl_debug, lvl_warning, NULL, and vehicle_priv::watch.
Referenced by vehicle_file_enable_watch_timer(), and vehicle_file_new_file().
static int vehicle_file_enable_watch_timer (struct vehicle_priv * priv) static
Description: Enable watch timer to get GPS data
Parameters
priv : pointer on the private data of the plugin
Returns
always 0
References dbg, FALSE, lvl_debug, and vehicle_file_enable_watch().
Referenced by vehicle_file_new_file().
static void vehicle_file_io (struct vehicle_priv * priv) static
Description: function to get data from GPS
Parameters
priv : pointer on the private data of the plugin
Remarks
References vehicle_priv::buffer, vehicle_priv::buffer_pos, buffer_size, callback_list_call_attr_0, vehicle_priv::cbl, data, dbg, exit, vehicle_priv::fd, file_get_contents(), vehicle_priv::file_type, file_type_file, g_free(), lvl_debug, vehicle_priv::on_eof, vehicle_priv::process_statefile, read(), size, vehicle_priv::statefile, vehicle_file_close(), vehicle_file_disable_watch(), vehicle_file_open(), and vehicle_file_parse().
Referenced by vehicle_file_new_file().
static struct vehicle_priv * vehicle_file_new_file (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Description: Function called to initialize the plugin
Parameters
meth : ?
cbl : ?
attrs : ?
Returns
pointer on the private data of the plugin
Remarks
private data is allocated by this function (g_new0)
References attr_search(), vehicle_priv::attrs, attr::attrs, B115200, B19200, B38400, B4800, B57600, B9600, vehicle_priv::baudrate, vehicle_priv::buffer, buffer_size, callback_cast, callback_new_1, vehicle_priv::cb, vehicle_priv::cbl, cbl, vehicle_priv::cbt, vehicle_priv::checksum_ignore, dbg, event_add_timeout(), vehicle_priv::fd, file_exists(), g_ascii_strcasecmp(), g_malloc(), g_new0, g_strdup(), item::id_hi, item::id_lo, lvl_debug, lvl_error, item::meth, NULL, attr::num, vehicle_priv::on_eof, item::priv_data, vehicle_priv::process_statefile, vehicle_priv::sat_item, vehicle_priv::source, source, vehicle_priv::statefile, attr::str, time(), vehicle_priv::time, item::type, attr::u, vehicle_file_enable_watch(), vehicle_file_enable_watch_timer(), vehicle_file_io(), vehicle_file_methods, vehicle_file_open(), and vehicle_file_sat_methods.
Referenced by plugin_init().
static int vehicle_file_open (struct vehicle_priv * priv) static
Description: open dialogue with the GPS
Parameters
priv : pointer on the private data of the plugin
Returns
1 if ok 0 if error
_WIN32
_WIN32
References vehicle_priv::baudrate, callback_cast, callback_new_1, dbg, vehicle_priv::fd, vehicle_priv::file, file_is_reg(), vehicle_priv::file_type, file_type_device, file_type_file, file_type_pipe, file_type_serial, file_type_socket, g_free(), g_strdup(), inet_aton(), lvl_error, lvl_info, name, O_RDONLY, open(), p, popen(), serial_io_init(), vehicle_priv::source, and write().
Referenced by vehicle_file_io(), and vehicle_file_new_file().
static int vehicle_file_parse (struct vehicle_priv * priv, char * buffer) static
Description: Parse the buffer
Parameters
priv : pointer on the private data of the plugin
buffer : data buffer (null terminated)
Returns
1 if The GPRMC Sentence is found 0 if not found
References attr_position_valid_invalid, attr_position_valid_valid, gps_sat::azimuth, buffer, vehicle_priv::cbt, vehicle_priv::checksum_ignore, vehicle_priv::current, vehicle_priv::current_count, dbg, vehicle_priv::direction, gps_sat::elevation, event_add_timeout(), vehicle_priv::file_type, file_type_file, vehicle_priv::fixday, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, g_ascii_strcasecmp(), g_ascii_strtod(), g_free(), g_strconcat(), vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, i, coord_geo::lat, lat, coord_geo::lng, lvl_debug, lvl_error, lvl_info, vehicle_priv::magnetic_direction, vehicle_priv::next, vehicle_priv::next_count, vehicle_priv::nmea_data, vehicle_priv::nmea_data_buf, NULL, p, gps_sat::prn, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, gps_sat::snr, vehicle_priv::speed, vehicle_priv::status, vehicle_priv::time, vehicle_priv::valid, vehicle_file_disable_watch(), and vehicle_priv::watch.
Referenced by vehicle_file_io().
static int vehicle_file_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Description: Function called to get attribute
Parameters
priv : pointer on the private data of the plugin
type : attribute type called
attr : structure to return the attribute value
Returns
1 if ok 0 for unkown or invalid attribute
References attr::coord_geo, vehicle_priv::current_count, dbg, vehicle_priv::direction, vehicle_priv::fixday, vehicle_priv::fixiso8601, vehicle_priv::fixmonth, vehicle_priv::fixtime, vehicle_priv::fixyear, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, item::id_lo, attr::item, lvl_debug, vehicle_priv::magnetic_direction, vehicle_priv::nmea_data, attr::num, attr::numd, vehicle_priv::sat_item, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::sats_visible, vehicle_priv::speed, sprintf(), vehicle_priv::status, attr::str, type, attr::type, attr::u, and vehicle_priv::valid.
static int vehicle_file_sat_attr_get (void * priv_data, enum attr_type type, struct attr * attr) static
References gps_sat::azimuth, vehicle_priv::current, vehicle_priv::current_count, gps_sat::elevation, item::id_lo, attr::num, gps_sat::prn, vehicle_priv::sat_item, gps_sat::snr, type, attr::type, and attr::u.
Variable Documentation
int buffer_size = 1024 static
Referenced by vehicle_file_io(), and vehicle_file_new_file().
struct vehicle_methods vehicle_file_methods static
Initial value:
= {
        vehicle_file_destroy,
        vehicle_file_position_attr_get,
}
Referenced by vehicle_file_new_file().
struct item_methods vehicle_file_sat_methods static
Initial value:
= {
        NULL,
        NULL,
        NULL,
        vehicle_file_sat_attr_get,
}
Referenced by vehicle_file_new_file().