navit: vehicle/gpsd_dbus/vehicle_gpsd_dbus.c File Reference
vehicle_gpsd_dbus.c File Reference
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <dbus/dbus.h>
#include <dbus/dbus-glib.h>
#include <dbus/dbus-glib-lowlevel.h>
#include <errno.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "vehicle.h"
#include "event.h"
Data Structures
struct vehicle_priv
Macros
#define DBUS_API_SUBJECT_TO_CHANGE
Functions
static void vehicle_gpsd_dbus_close (struct vehicle_priv *priv)
static DBusHandlerResult vehicle_gpsd_dbus_filter (DBusConnection *connection, DBusMessage *message, void *user_data)
static int vehicle_gpsd_dbus_open (struct vehicle_priv *priv)
static void vehicle_gpsd_dbus_destroy (struct vehicle_priv *priv)
static int vehicle_gpsd_dbus_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_gpsd_dbus_set_attr_do (struct vehicle_priv *priv, struct attr *attr, int init)
static int vehicle_gpsd_dbus_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_gpsd_dbus_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
static char * vehicle_gpsd_dbus_prefix ="gpsd_dbus:"
static struct vehicle_methods vehicle_gpsd_methods
Macro Definition Documentation
#define DBUS_API_SUBJECT_TO_CHANGE
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Function Documentation
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, lvl_debug, and vehicle_gpsd_dbus_new().
static void vehicle_gpsd_dbus_close (struct vehicle_priv * priv) static
References vehicle_priv::connection, and NULL.
Referenced by vehicle_gpsd_dbus_destroy(), vehicle_gpsd_dbus_open(), and vehicle_gpsd_dbus_set_attr_do().
static void vehicle_gpsd_dbus_destroy (struct vehicle_priv * priv) static
References g_free(), vehicle_priv::source, and vehicle_gpsd_dbus_close().
static DBusHandlerResult vehicle_gpsd_dbus_filter (DBusConnection * connection, DBusMessage * message, void * user_data) static
References vehicle_priv::altitude, callback_list_call_attr_0, vehicle_priv::cbl, vehicle_priv::fix_time, vehicle_priv::flags, vehicle_priv::geo, coord_geo::lat, coord_geo::lng, NULL, vehicle_priv::speed, speed, time(), vehicle_priv::time, and vehicle_priv::track.
Referenced by vehicle_gpsd_dbus_open().
static struct vehicle_priv* vehicle_gpsd_dbus_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References vehicle_priv::attrs, vehicle_priv::cbl, cbl, g_new0, vehicle_gpsd_dbus_open(), vehicle_gpsd_dbus_set_attr_do(), and vehicle_gpsd_methods.
Referenced by plugin_init().
static int vehicle_gpsd_dbus_open (struct vehicle_priv * priv) static
References vehicle_priv::address, vehicle_priv::connection, dbg, lvl_error, NULL, vehicle_gpsd_dbus_close(), and vehicle_gpsd_dbus_filter().
Referenced by vehicle_gpsd_dbus_new(), and vehicle_gpsd_dbus_set_attr_do().
static int vehicle_gpsd_dbus_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References vehicle_priv::altitude, attr::coord_geo, vehicle_priv::fix_time, vehicle_priv::fixiso8601, vehicle_priv::geo, attr::numd, vehicle_priv::speed, attr::str, vehicle_priv::track, type, attr::type, and attr::u.
static int vehicle_gpsd_dbus_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References vehicle_gpsd_dbus_set_attr_do().
static int vehicle_gpsd_dbus_set_attr_do (struct vehicle_priv * priv, struct attr * attr, int init) static
References vehicle_priv::address, dbg, vehicle_priv::flags, g_free(), g_strdup(), lvl_error, NULL, attr::num, vehicle_priv::source, attr::str, attr::type, attr::u, vehicle_gpsd_dbus_close(), vehicle_gpsd_dbus_open(), and vehicle_gpsd_dbus_prefix.
Referenced by vehicle_gpsd_dbus_new(), and vehicle_gpsd_dbus_set_attr().
Variable Documentation
char* vehicle_gpsd_dbus_prefix ="gpsd_dbus:" static
Referenced by vehicle_gpsd_dbus_set_attr_do().
struct vehicle_methods vehicle_gpsd_methods static
Initial value:
= {
        vehicle_gpsd_dbus_destroy,
        vehicle_gpsd_dbus_position_attr_get,
        vehicle_gpsd_dbus_set_attr,
}
Referenced by vehicle_gpsd_dbus_new().