navit: vehicle/iphone/vehicle_iphone.c File Reference
vehicle_iphone.c File Reference
#include <glib.h>
#include <string.h>
#include "config.h"
#include "debug.h"
#include "coord.h"
#include "item.h"
#include "navit.h"
#include "map.h"
#include "route.h"
#include "callback.h"
#include "transform.h"
#include "plugin.h"
#include "vehicle.h"
#include "event.h"
#include "corelocation.h"
Data Structures
struct vehicle_priv
Functions
static void vehicle_iphone_destroy (struct vehicle_priv *priv)
static int vehicle_iphone_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static int vehicle_iphone_set_attr (struct vehicle_priv *priv, struct attr *attr)
void vehicle_iphone_update (void *arg, double lat, double lng, double dir, double spd, char *str_time, double radius)
static struct vehicle_priv * vehicle_iphone_new (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
struct vehicle_methods vehicle_iphone_methods
Function Documentation
void plugin_init (void)
The plugin entry point.
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
The plugin entry point.
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, lvl_debug, and vehicle_iphone_new().
static void vehicle_iphone_destroy (struct vehicle_priv * priv) static
References corelocation_exit(), and g_free().
static struct vehicle_priv* vehicle_iphone_new (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Initialize corelocation
References attr_search(), vehicle_priv::cbl, cbl, vehicle_priv::config_speed, attr::coord_geo, corelocation_init(), dbg, g_new0, vehicle_priv::geo, vehicle_priv::interval, coord_geo::lat, coord_geo::lng, lvl_debug, NULL, attr::num, vehicle_priv::position_set, speed, vehicle_priv::str_time, attr::u, vehicle_iphone_methods, and vehicle_iphone_update().
Referenced by plugin_init().
static int vehicle_iphone_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References attr::coord_geo, vehicle_priv::direction, vehicle_priv::geo, attr::numd, vehicle_priv::radius, vehicle_priv::speed, attr::str, vehicle_priv::str_time, type, attr::type, and attr::u.
static int vehicle_iphone_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References vehicle_priv::navit, attr::navit, attr::type, and attr::u.
void vehicle_iphone_update (void * arg, double lat, double lng, double dir, double spd, char * str_time, double radius)
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::geo, coord_geo::lat, lat, coord_geo::lng, lvl_debug, vehicle_priv::radius, vehicle_priv::speed, and vehicle_priv::str_time.
Referenced by vehicle_iphone_new().
Variable Documentation
struct vehicle_methods vehicle_iphone_methods
Initial value:
= {
        vehicle_iphone_destroy,
        vehicle_iphone_position_attr_get,
        vehicle_iphone_set_attr,
}
Referenced by vehicle_iphone_new().