navit: vehicle/null/vehicle_null.c File Reference
vehicle_null.c File Reference
null uses dbus signals
#include <config.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include <time.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "vehicle.h"
Data Structures
struct vehicle_priv
Functions
static void vehicle_null_destroy (struct vehicle_priv *priv)
Free the null_vehicle.
static int vehicle_null_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
Provide the outside with information.
static int vehicle_null_set_attr (struct vehicle_priv *priv, struct attr *attr)
static struct vehicle_priv * vehicle_null_new_null (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
Create null_vehicle.
void plugin_init (void)
register vehicle_null
Variables
struct vehicle_methods vehicle_null_methods
Detailed Description
null uses dbus signals
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Tim Niemeyer reddo.nosp@m.g@ma.nosp@m.sters.nosp@m.word.nosp@m..de
Date
2008-2009
Navit, a modular navigation system. Copyright (C) 2005-2017 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Tim Niemeyer reddo.nosp@m.g@ma.nosp@m.sters.nosp@m.word.nosp@m..de
Date
2008-2009
Function Documentation
void plugin_init (void)
register vehicle_null
The plugin entry point.
Returns
nothing
References dbg, lvl_debug, and vehicle_null_new_null().
static void vehicle_null_destroy (struct vehicle_priv * priv) static
Free the null_vehicle.
Parameters
priv
Returns
nothing
References dbg, g_free(), and lvl_debug.
static struct vehicle_priv* vehicle_null_new_null (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
Create null_vehicle.
Parameters
meth
cbl
attrs
Returns
vehicle_priv
References vehicle_priv::cbl, cbl, dbg, g_new0, lvl_debug, and vehicle_null_methods.
Referenced by plugin_init().
static int vehicle_null_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
Provide the outside with information.
Parameters
priv
type TODO: What can this be?
attr
Returns
true/false
References attr_to_name(), attr::coord_geo, dbg, vehicle_priv::direction, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::have_coords, vehicle_priv::height, lvl_debug, attr::num, attr::numd, vehicle_priv::radius, vehicle_priv::sats, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
static int vehicle_null_set_attr (struct vehicle_priv * priv, struct attr * attr) static
References callback_list_call_attr_0, vehicle_priv::cbl, attr::coord_geo, vehicle_priv::direction, vehicle_priv::geo, vehicle_priv::have_coords, attr::numd, vehicle_priv::speed, attr::type, and attr::u.
Variable Documentation
struct vehicle_methods vehicle_null_methods
Initial value:
= {
        vehicle_null_destroy,
        vehicle_null_position_attr_get,
        vehicle_null_set_attr,
}
Referenced by vehicle_null_new_null().