navit: vehicle/gpsd/vehicle_gpsd.c File Reference
vehicle_gpsd.c File Reference
#include <config.h>
#include <gps.h>
#include <string.h>
#include <glib.h>
#include <math.h>
#include "debug.h"
#include "callback.h"
#include "plugin.h"
#include "coord.h"
#include "item.h"
#include "vehicle.h"
#include "event.h"
#include "types.h"
Data Structures
struct vehicle_priv
Macros
#define DEFAULT_RETRY_INTERVAL 10
#define MIN_RETRY_INTERVAL 1
Functions
static void vehicle_gpsd_io (struct vehicle_priv *priv)
static void vehicle_gpsd_callback (struct gps_data_t *data, const char *buf, size_t len, int level)
static int vehicle_gpsd_try_open (struct vehicle_priv *priv)
static void vehicle_gpsd_open (struct vehicle_priv *priv)
static void vehicle_gpsd_close (struct vehicle_priv *priv)
static void vehicle_gpsd_destroy (struct vehicle_priv *priv)
static int vehicle_gpsd_position_attr_get (struct vehicle_priv *priv, enum attr_type type, struct attr *attr)
static struct vehicle_priv * vehicle_gpsd_new_gpsd (struct vehicle_methods *meth, struct callback_list *cbl, struct attr **attrs)
void plugin_init (void)
The plugin entry point.
Variables
static struct vehicle_priv * vehicle_last
static struct vehicle_methods vehicle_gpsd_methods
Macro Definition Documentation
#define DEFAULT_RETRY_INTERVAL 10
Referenced by vehicle_gpsd_new_gpsd().
#define MIN_RETRY_INTERVAL 1
Referenced by vehicle_gpsd_new_gpsd().
Function Documentation
void plugin_init (void)
The plugin entry point.
Description: Initialisation of vehicle_file plugin
Returns
nothing
The plugin entry point
The plugin entry point.
Returns
nothing
Navit, a modular navigation system. Copyright (C) 2005-2008 Navit Team
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
References dbg, lvl_debug, and vehicle_gpsd_new_gpsd().
static void vehicle_gpsd_callback (struct gps_data_t * data, const char * buf, size_t len, int level) static
References callback_list_call_attr_0, vehicle_priv::cbl, dbg, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, g_free(), g_strconcat(), vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, i, coord_geo::lat, coord_geo::lng, LONGLONG_HEX_FMT, lvl_debug, lvl_error, lvl_info, MPS_TO_KPH, vehicle_priv::nmea_data, vehicle_priv::nmea_data_buf, NULL, startup::pos, vehicle_priv::sats, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::speed, vehicle_priv::status, and vehicle_last.
Referenced by vehicle_gpsd_io(), and vehicle_gpsd_try_open().
static void vehicle_gpsd_close (struct vehicle_priv * priv) static
References callback_destroy(), vehicle_priv::cb, vehicle_priv::cbt, dbg, err(), event_remove_timeout(), event_remove_watch(), vehicle_priv::evwatch, g_free(), vehicle_priv::gps, lvl_debug, lvl_error, NULL, and vehicle_priv::retry_timer2.
Referenced by vehicle_gpsd_destroy(), and vehicle_gpsd_io().
static void vehicle_gpsd_destroy (struct vehicle_priv * priv) static
References g_free(), vehicle_priv::gps, vehicle_priv::gpsd_query, vehicle_priv::source, and vehicle_gpsd_close().
static void vehicle_gpsd_io (struct vehicle_priv * priv) static
References buf, dbg, vehicle_priv::gps, lvl_debug, lvl_error, vehicle_gpsd_callback(), vehicle_gpsd_close(), vehicle_gpsd_open(), and vehicle_last.
Referenced by vehicle_gpsd_try_open().
static struct vehicle_priv* vehicle_gpsd_new_gpsd (struct vehicle_methods * meth, struct callback_list * cbl, struct attr ** attrs) static
References attr_search(), vehicle_priv::attrs, attr::attrs, vehicle_priv::cbl, cbl, dbg, DEFAULT_RETRY_INTERVAL, g_new0, g_strconcat(), g_strdup(), vehicle_priv::gps, vehicle_priv::gpsd_query, lvl_debug, lvl_error, MIN_RETRY_INTERVAL, NULL, attr::num, vehicle_priv::retry_interval, vehicle_priv::source, source, attr::str, attr::u, vehicle_gpsd_methods, and vehicle_gpsd_open().
Referenced by plugin_init().
static void vehicle_gpsd_open (struct vehicle_priv * priv) static
Open a connection to gpsd. Will re-try the connection if it fails
References vehicle_priv::cbt, dbg, errno, event_add_timeout(), lvl_debug, lvl_error, NULL, vehicle_priv::retry_interval, vehicle_priv::retry_timer2, strerror(), and vehicle_gpsd_try_open().
Referenced by vehicle_gpsd_io(), and vehicle_gpsd_new_gpsd().
static int vehicle_gpsd_position_attr_get (struct vehicle_priv * priv, enum attr_type type, struct attr * attr) static
References active, attr_search(), vehicle_priv::attrs, attr::coord_geo, vehicle_priv::direction, vehicle_priv::fix_time, vehicle_priv::fix_type, vehicle_priv::fixiso8601, vehicle_priv::geo, vehicle_priv::hdop, vehicle_priv::height, vehicle_priv::nmea_data, NULL, attr::num, attr::numd, vehicle_priv::sats, vehicle_priv::sats_signal, vehicle_priv::sats_used, vehicle_priv::speed, attr::str, type, attr::type, and attr::u.
static int vehicle_gpsd_try_open (struct vehicle_priv * priv) static
Attempt to open the gps device. Return FALSE if retry not required Return TRUE to try again
References callback_cast, callback_new_1, vehicle_priv::cb, vehicle_priv::cbt, dbg, event_add_watch(), event_remove_timeout(), event_watch_cond_read, vehicle_priv::evwatch, FALSE, g_free(), g_strdup(), vehicle_priv::gps, vehicle_priv::gpsd_query, lvl_debug, lvl_error, NULL, vehicle_priv::retry_interval, vehicle_priv::retry_timer2, vehicle_priv::source, source, TRUE, vehicle_gpsd_callback(), and vehicle_gpsd_io().
Referenced by vehicle_gpsd_open().
Variable Documentation
struct vehicle_methods vehicle_gpsd_methods static
Initial value:
= {
        vehicle_gpsd_destroy,
        vehicle_gpsd_position_attr_get,
}
Referenced by vehicle_gpsd_new_gpsd().
struct vehicle_priv * vehicle_last static
Referenced by vehicle_gpsd_callback(), and vehicle_gpsd_io().