navit: support/espeak/voices.c File Reference
voices.c File Reference
#include "StdAfx.h"
#include "stdio.h"
#include "ctype.h"
#include "wctype.h"
#include "string.h"
#include "stdlib.h"
#include "speech.h"
#include "dirent.h"
#include "speak_lib.h"
#include "phoneme.h"
#include "synthesize.h"
#include "voice.h"
#include "translate.h"
Data Structures
struct keywtab_t
Macros
#define int(x) ((int)(x))
#define double(x) ((double)(x))
#define __cdecl
#define DEFAULT_LANGUAGE_PRIORITY 5
#define N_VOICES_LIST 150
#define N_VOICE_VARIANTS 12
#define AGE_OLD 60
Enumerations
enum {
V_NAME = 1, V_LANGUAGE, V_GENDER, V_TRANSLATOR,
V_PHONEMES, V_DICTIONARY, V_FORMANT, V_PITCH,
V_ECHO, V_FLUTTER, V_ROUGHNESS, V_CLARITY,
V_TONE, V_VOICING, V_BREATH, V_BREATHW,
V_WORDGAP, V_INTONATION, V_STRESSLENGTH, V_STRESSAMP,
V_STRESSADD, V_DICTRULES, V_STRESSRULE, V_CHARSET,
V_NUMBERS, V_OPTION, V_MBROLA, V_KLATT,
V_FAST, V_REPLACE, V_CONSONANTS
}
Functions
static char * fgets_strip (char *buf, int size, FILE *f_in)
static void SetToneAdjust (voice_t *voice, int *tone_pts)
void ReadTonePoints (char *string, int *tone_pts)
static espeak_VOICE * ReadVoiceFile (FILE *f_in, const char *fname, const char *leafname)
void VoiceReset (int tone_only)
static void VoiceFormant (char *p)
static void PhonemeReplacement (int type, char *p)
static int Read8Numbers (char *data_in, int *data)
voice_t * LoadVoice (const char *vname, int control)
static char * ExtractVoiceVariantName (char *vname, int variant_num)
voice_t * LoadVoiceVariant (const char *vname, int variant_num)
static int __cdecl VoiceNameSorter (const void *p1, const void *p2)
static int __cdecl VoiceScoreSorter (const void *p1, const void *p2)
static int ScoreVoice (espeak_VOICE *voice_spec, const char *spec_language, int spec_n_parts, int spec_lang_len, espeak_VOICE *voice)
static int SetVoiceScores (espeak_VOICE *voice_select, espeak_VOICE **voices, int control)
espeak_VOICE * SelectVoiceByName (espeak_VOICE **voices, const char *name)
char const * SelectVoice (espeak_VOICE *voice_select, int *found)
static void GetVoices (const char *path)
espeak_ERROR SetVoiceByName (const char *name)
espeak_ERROR SetVoiceByProperties (espeak_VOICE *voice_selector)
const espeak_VOICE ** espeak_ListVoices (espeak_VOICE *voice_spec)
espeak_VOICE * espeak_GetCurrentVoice (void)
Variables
MNEM_TAB genders []
int tone_points [12] = {600,170, 1200,135, 2000,110, 3000,110, -1,0}
static int formant_rate_22050 [9] = {240, 170, 170, 170, 170, 170, 170, 170, 170}
int formant_rate [9]
static int n_voices_list = 0
static espeak_VOICE * voices_list [N_VOICES_LIST]
static int len_path_voices
espeak_VOICE voice_selected
static keywtab_t keyword_tab []
const char variants_either [N_VOICE_VARIANTS] = {1,2,12,3,13,4,14,5,11,0}
const char variants_male [N_VOICE_VARIANTS] = {1,2,3,4,5,0}
const char variants_female [N_VOICE_VARIANTS] = {11,12,13,14,0}
const char * variant_lists [3] = {variants_either, variants_male, variants_female}
static voice_t voicedata
voice_t * voice = &voicedata
Macro Definition Documentation
#define __cdecl
#define AGE_OLD 60
Referenced by SelectVoice().
#define DEFAULT_LANGUAGE_PRIORITY 5
Referenced by LoadVoice(), and ReadVoiceFile().
#define double (x) ((double)(x))
Referenced by LoadVoice(), and SetToneAdjust().
#define int (x) ((int)(x))
Referenced by _nl_expand_alias(), _nl_load_domain(), attr_prosody_value(), cache_new(), callback_call(), ch_setup(), cJSON_CreateNumber(), cmp(), compile_dictlist_end(), org.navitproject.navit.FileBrowserActivity::createFileListAdapter(), DBFWriteAttribute(), DBFWriteAttributeDirectly(), DCIGETTEXT(), file_reader_finish(), get_u32(), getopt_long(), GetVoices(), graphics_gd_new(), graphics_gtk_drawing_area_new_helper(), graphics_opengl_new_helper(), graphics_qt5_new(), graphics_qt_qpainter_new(), graphics_sdl_new(), gui_internal_button_map_attr_new(), gui_internal_button_navit_attr_new(), hash_string(), if(), image_create(), inflate(), inflate_table(), item_bin_to_poly_segment(), item_id_from_ptr(), j1850_idle(), label_line(), LoadVoice(), LookupNum2(), MarkerEvent(), navit_vehicle_update_position(), org.navitproject.navit.Navit::onCreate(), org.navitproject.navit.NavitGraphics.NavitView::onMenuItemClick(), org.navitproject.navit.NavitGraphics.NavitView::onTouchEvent(), osd_odometer_draw(), osm_add_tag(), overlay_new(), org.navitproject.navit.NavitTextTranslations::p(), parse_number(), parseMain(), pedestrian_graphics_resize(), png_build_gamma_table(), png_do_chop(), png_do_expand(), png_do_expand_palette(), png_do_gamma(), png_do_read_interlace(), png_do_unpack(), png_free_data(), png_get_iCCP(), png_get_oFFs(), png_get_pCAL(), png_get_pHYs(), png_get_sRGB(), png_handle_pCAL(), png_handle_PLTE(), png_init_read_transformations(), png_read_filter_row(), png_read_png(), png_set_dither(), png_set_gAMA(), png_set_rgb_to_gray(), png_set_tRNS(), poly_get_data(), PRINTF_PARSE(), raster_AAFilledEllipse(), raster_hline(), raster_line(), raster_rect_inline(), route_get_coord_dist(), route_segment_data_field_pos(), route_segment_data_size(), org.navitproject.navit.NavitAddressSearchActivity::setCountryButtonImage(), SetToneAdjust(), SHPGetSubNodeOffset(), SHPOpenLL(), SHPRestoreSHX(), SHPSearchDiskTreeNode(), SHPWriteTreeNode(), str_to_upper(), SubstituteChar(), org.navitproject.navit.NavitMapDownloader::updateProgress(), VASNPRINTF(), vehicle_webos_gps_update(), vehicle_webos_timeout_callback(), VoiceFormant(), and yyparse().
#define N_VOICE_VARIANTS 12
Referenced by SelectVoice().
#define N_VOICES_LIST 150
Referenced by espeak_ListVoices(), GetVoices(), and SelectVoice().
Enumeration Type Documentation
anonymous enum
Enumerator
V_NAME
V_LANGUAGE
V_GENDER
V_TRANSLATOR
V_PHONEMES
V_DICTIONARY
V_FORMANT
V_PITCH
V_ECHO
V_FLUTTER
V_ROUGHNESS
V_CLARITY
V_TONE
V_VOICING
V_BREATH
V_BREATHW
V_WORDGAP
V_INTONATION
V_STRESSLENGTH
V_STRESSAMP
V_STRESSADD
V_DICTRULES
V_STRESSRULE
V_CHARSET
V_NUMBERS
V_OPTION
V_MBROLA
V_KLATT
V_FAST
V_REPLACE
V_CONSONANTS
Function Documentation
espeak_VOICE* espeak_GetCurrentVoice (void)
const espeak_VOICE** espeak_ListVoices (espeak_VOICE * voice_spec)
References GetVoices(), espeak_VOICE::identifier, espeak_VOICE::languages, len_path_voices, N_VOICES_LIST, n_voices_list, NULL, path_home, PATHSEP, SetVoiceScores(), sprintf(), VoiceNameSorter(), and voices_list.
Referenced by DisplayVoices(), SelectVoice(), SelectVoiceByName(), and SetVoiceByName().
static char* ExtractVoiceVariantName (char * vname, int variant_num) static
References NULL, p, PATHSEP, sprintf(), and strncpy0().
Referenced by LoadVoiceVariant(), SelectVoice(), and SetVoiceByName().
static char* fgets_strip (char * buf, int size, FILE * f_in) static
References NULL, and p.
Referenced by LoadVoice(), and ReadVoiceFile().
static void GetVoices (const char * path) static
References buf, GetFileLength(), int, len_path_voices, N_VOICES_LIST, n_voices_list, NULL, p, path_home, PATHSEP, ReadVoiceFile(), sprintf(), and type.
Referenced by espeak_ListVoices().
voice_t* LoadVoice (const char * vname, int control)
References espeak_VOICE::age, voice_t::breath, voice_t::breathw, buf, Translator::charset_a0, charsets, voice_t::consonant_amp, voice_t::consonant_ampv, keywtab_t::data, DEFAULT_LANGUAGE_PRIORITY, DeleteTranslator(), Translator::dict_condition, dictionary_name, double, voice_t::echo_amp, voice_t::echo_delay, SPEED_FACTORS::fast_settings, fgets_strip(), voice_t::flutter, voice_t::formant_factor, fprintf(), voice_t::freq, voice_t::freq2, espeak_VOICE::gender, GetFileLength(), voice_t::height, voice_t::height2, espeak_VOICE::identifier, int, LANGUAGE_OPTIONS::intonation_group, key, KLATT_Kopen, voice_t::klattv, Translator::langopts, espeak_VOICE::languages, LoadDictionary(), LoadMbrolaTable(), LookupMnem(), LOPT_LENGTH_MODS, keywtab_t::mnem, N_CHARSETS, voice_t::n_harmonic_peaks, N_LOPTS, N_PEAKS, espeak_VOICE::name, name, NULL, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, option_tone2, option_tone_flags, p, LANGUAGE_OPTIONS::param, path_home, PATHSEP, voice_t::peak_shape, voice_t::phoneme_tab_ix, PhonemeReplacement(), voice_t::pitch_base, voice_t::pitch_range, Read8Numbers(), ReadTonePoints(), voice_t::roughness, SelectPhonemeTableName(), SelectTranslator(), SetLengthMods(), SetSpeed(), SetToneAdjust(), speed, sprintf(), Translator::stress_amps, Translator::stress_amps_r, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, LANGUAGE_OPTIONS::stress_rule, strncpy0(), translator, LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, V_BREATH, V_BREATHW, V_CHARSET, V_CLARITY, V_CONSONANTS, V_DICTIONARY, V_DICTRULES, V_ECHO, V_FAST, V_FLUTTER, V_FORMANT, V_GENDER, V_INTONATION, V_KLATT, V_LANGUAGE, V_MBROLA, V_NAME, V_NUMBERS, V_OPTION, V_PHONEMES, V_PITCH, V_REPLACE, V_ROUGHNESS, V_STRESSADD, V_STRESSAMP, V_STRESSLENGTH, V_STRESSRULE, V_TONE, V_TRANSLATOR, V_VOICING, V_WORDGAP, value, voicedata, VoiceFormant(), VoiceReset(), voice_t::voicing, LANGUAGE_OPTIONS::vowel_pause, voice_t::width, voice_t::width2, and LANGUAGE_OPTIONS::word_gap.
Referenced by LoadVoiceVariant(), main(), and SetVoiceByName().
voice_t* LoadVoiceVariant (const char * vname, int variant_num)
References buf, ExtractVoiceVariantName(), LoadVoice(), NULL, and strncpy0().
Referenced by SetVoiceByProperties(), and SpeakNextClause().
static void PhonemeReplacement (int type, char * p) static
References LookupPhonemeString(), N_REPLACE_PHONEMES, n_replace_phonemes, REPLACE_PHONEMES::new_ph, REPLACE_PHONEMES::old_ph, replace_phonemes, and REPLACE_PHONEMES::type.
Referenced by LoadVoice().
static int Read8Numbers (char * data_in, int * data) static
Referenced by LoadVoice().
void ReadTonePoints (char * string, int * tone_pts)
Referenced by LoadConfig(), and LoadVoice().
static espeak_VOICE* ReadVoiceFile (FILE * f_in, const char * fname, const char * leafname) static
References espeak_VOICE::age, calloc(), DEFAULT_LANGUAGE_PRIORITY, fgets_strip(), espeak_VOICE::gender, GetFileLength(), espeak_VOICE::identifier, espeak_VOICE::languages, LookupMnem(), espeak_VOICE::name, NULL, p, path_home, sprintf(), strncpy0(), espeak_VOICE::variant, and espeak_VOICE::xx1.
Referenced by GetVoices().
static int ScoreVoice (espeak_VOICE * voice_spec, const char * spec_language, int spec_n_parts, int spec_lang_len, espeak_VOICE * voice) static
References espeak_VOICE::age, c1, c2, espeak_VOICE::gender, espeak_VOICE::identifier, espeak_VOICE::languages, espeak_VOICE::name, NULL, and p.
Referenced by SetVoiceScores().
char const* SelectVoice (espeak_VOICE * voice_select, int * found)
References espeak_VOICE::age, AGE_OLD, buf, espeak_ListVoices(), ExtractVoiceVariantName(), espeak_VOICE::gender, espeak_VOICE::identifier, espeak_VOICE::languages, N_VOICE_VARIANTS, N_VOICES_LIST, n_voices_list, espeak_VOICE::name, NULL, p, SelectVoiceByName(), SetVoiceScores(), skip(), sprintf(), strncpy0(), espeak_VOICE::variant, variant_lists, and espeak_VOICE::xx1.
Referenced by SetVoiceByProperties(), and VoiceFromStack().
espeak_VOICE* SelectVoiceByName (espeak_VOICE ** voices, const char * name)
References espeak_ListVoices(), n_voices_list, NULL, PATHSEP, sprintf(), and voices_list.
Referenced by SelectVoice(), SetVoiceByName(), and VoiceFromStack().
static void SetToneAdjust (voice_t * voice, int * tone_pts) static
References double, int, N_TONE_ADJUST, and voice_t::tone_adjust.
Referenced by LoadVoice(), and VoiceReset().
espeak_ERROR SetVoiceByName (const char * name)
References buf, DoVoiceChange(), EE_INTERNAL_ERROR, EE_OK, espeak_ListVoices(), ExtractVoiceVariantName(), espeak_VOICE::identifier, LoadVoice(), n_voices_list, espeak_VOICE::name, NULL, SelectVoiceByName(), SetVoiceStack(), and strncpy0().
Referenced by espeak_Initialize(), espeak_new(), espeak_SetVoiceByName(), main(), and Synthesize().
espeak_ERROR SetVoiceByProperties (espeak_VOICE * voice_selector)
References DoVoiceChange(), EE_NOT_FOUND, EE_OK, LoadVoiceVariant(), SelectVoice(), and SetVoiceStack().
Referenced by espeak_SetVoiceByProperties(), and main().
static int SetVoiceScores (espeak_VOICE * voice_select, espeak_VOICE ** voices, int control) static
References espeak_VOICE::identifier, espeak_VOICE::languages, n_voices_list, NULL, espeak_VOICE::score, ScoreVoice(), and VoiceScoreSorter().
Referenced by espeak_ListVoices(), and SelectVoice().
static void VoiceFormant (char * p) static
References voice_t::freq, voice_t::freqadd, voice_t::height, height, int, voice_t::width, and width.
Referenced by LoadVoice().
static int __cdecl VoiceNameSorter (const void * p1, const void * p2) static
References espeak_VOICE::languages, and espeak_VOICE::name.
Referenced by espeak_ListVoices().
void VoiceReset (int tone_only)
References voice_t::breath, voice_t::breathw, voice_t::consonant_amp, voice_t::consonant_ampv, voice_t::echo_amp, voice_t::echo_delay, SPEED_FACTORS::fast_settings, voice_t::flutter, voice_t::formant_factor, formant_rate, formant_rate_22050, voice_t::freq, voice_t::freqadd, voice_t::height, InitBreath(), voice_t::klattv, LoadMbrolaTable(), voice_t::n_harmonic_peaks, N_PEAKS, n_replace_phonemes, NULL, option_quiet, voice_t::peak_shape, voice_t::pitch_base, voice_t::pitch_range, voice_t::roughness, samplerate, SetToneAdjust(), speed, voice_t::speedf1, voice_t::speedf2, voice_t::speedf3, tone_points, voice_t::voicing, and voice_t::width.
Referenced by LoadVoice().
static int __cdecl VoiceScoreSorter (const void * p1, const void * p2) static
References espeak_VOICE::name, and espeak_VOICE::score.
Referenced by SetVoiceScores().
Variable Documentation
int formant_rate[9]
Referenced by SmoothSpect(), and VoiceReset().
int formant_rate_22050[9] = {240, 170, 170, 170, 170, 170, 170, 170, 170} static
Referenced by VoiceReset().
MNEM_TAB genders[]
Initial value:
= {
        {"unknown", 0},
        {"male", 1},
        {"female", 2},
        {NULL, 0 }}
Referenced by DisplayVoices().
keywtab_t keyword_tab[] static
int len_path_voices static
Referenced by espeak_ListVoices(), and GetVoices().
int n_voices_list = 0 static
Referenced by espeak_ListVoices(), GetVoices(), SelectVoice(), SelectVoiceByName(), SetVoiceByName(), and SetVoiceScores().
int tone_points[12] = {600,170, 1200,135, 2000,110, 3000,110, -1,0}
Referenced by LoadConfig(), and VoiceReset().
const char* variant_lists[3] = {variants_either, variants_male, variants_female}
Referenced by SelectVoice().
const char variants_either[N_VOICE_VARIANTS] = {1,2,12,3,13,4,14,5,11,0}
const char variants_female[N_VOICE_VARIANTS] = {11,12,13,14,0}
const char variants_male[N_VOICE_VARIANTS] = {1,2,3,4,5,0}
voice_t* voice = &voicedata
Referenced by AdjustFormants(), DoSpect(), espeak_Initialize(), espeak_new(), formants_reduce_hf(), FormantTransition2(), LookupCharName(), LookupLetter(), main(), set_frame_rms(), SetSpeed(), SetTranslator2(), SpeakNextClause(), TranslateLetter(), TranslateWord2(), Wavegen(), and WritePitch().
espeak_VOICE voice_selected
voice_t voicedata static
Referenced by LoadVoice().
espeak_VOICE* voices_list[N_VOICES_LIST] static
Referenced by espeak_ListVoices(), and SelectVoiceByName().