navit: support/espeak/voice.h File Reference
voice.h File Reference
Data Structures
struct voice_t
Macros
#define N_TONE_ADJUST 1000
Functions
const char * SelectVoice (espeak_VOICE *voice_select, int *found)
espeak_VOICE * SelectVoiceByName (espeak_VOICE **voices, const char *name)
voice_t * LoadVoice (const char *voice_name, int control)
voice_t * LoadVoiceVariant (const char *voice_name, int variant)
void DoVoiceChange (voice_t *v)
void WavegenSetVoice (voice_t *v)
void ReadTonePoints (char *string, int *tone_pts)
Variables
USHORT voice_pcnt [N_PEAKS+1][3]
voice_t * voice
int tone_points [12]
Macro Definition Documentation
#define N_TONE_ADJUST 1000
Referenced by PeaksToHarmspect(), and SetToneAdjust().
Function Documentation
void DoVoiceChange (voice_t * v)
References long, WCMD_VOICE, wcmdq, wcmdq_tail, and WcmdqInc().
Referenced by espeak_Initialize(), espeak_new(), main(), SetVoiceByName(), SetVoiceByProperties(), and SpeakNextClause().
voice_t* LoadVoice (const char * voice_name, int control)
References espeak_VOICE::age, voice_t::breath, voice_t::breathw, buf, Translator::charset_a0, charsets, voice_t::consonant_amp, voice_t::consonant_ampv, keywtab_t::data, DEFAULT_LANGUAGE_PRIORITY, DeleteTranslator(), Translator::dict_condition, dictionary_name, double, voice_t::echo_amp, voice_t::echo_delay, SPEED_FACTORS::fast_settings, fgets_strip(), voice_t::flutter, voice_t::formant_factor, fprintf(), voice_t::freq, voice_t::freq2, espeak_VOICE::gender, GetFileLength(), voice_t::height, voice_t::height2, espeak_VOICE::identifier, int, LANGUAGE_OPTIONS::intonation_group, key, KLATT_Kopen, voice_t::klattv, Translator::langopts, espeak_VOICE::languages, LoadDictionary(), LoadMbrolaTable(), LookupMnem(), LOPT_LENGTH_MODS, keywtab_t::mnem, N_CHARSETS, voice_t::n_harmonic_peaks, N_LOPTS, N_PEAKS, espeak_VOICE::name, name, NULL, LANGUAGE_OPTIONS::numbers, LANGUAGE_OPTIONS::numbers2, option_tone2, option_tone_flags, p, LANGUAGE_OPTIONS::param, path_home, PATHSEP, voice_t::peak_shape, voice_t::phoneme_tab_ix, PhonemeReplacement(), voice_t::pitch_base, voice_t::pitch_range, Read8Numbers(), ReadTonePoints(), voice_t::roughness, SelectPhonemeTableName(), SelectTranslator(), SetLengthMods(), SetSpeed(), SetToneAdjust(), speed, sprintf(), Translator::stress_amps, Translator::stress_amps_r, LANGUAGE_OPTIONS::stress_flags, Translator::stress_lengths, LANGUAGE_OPTIONS::stress_rule, strncpy0(), translator, LANGUAGE_OPTIONS::unstressed_wd1, LANGUAGE_OPTIONS::unstressed_wd2, V_BREATH, V_BREATHW, V_CHARSET, V_CLARITY, V_CONSONANTS, V_DICTIONARY, V_DICTRULES, V_ECHO, V_FAST, V_FLUTTER, V_FORMANT, V_GENDER, V_INTONATION, V_KLATT, V_LANGUAGE, V_MBROLA, V_NAME, V_NUMBERS, V_OPTION, V_PHONEMES, V_PITCH, V_REPLACE, V_ROUGHNESS, V_STRESSADD, V_STRESSAMP, V_STRESSLENGTH, V_STRESSRULE, V_TONE, V_TRANSLATOR, V_VOICING, V_WORDGAP, value, voicedata, VoiceFormant(), VoiceReset(), voice_t::voicing, LANGUAGE_OPTIONS::vowel_pause, voice_t::width, voice_t::width2, and LANGUAGE_OPTIONS::word_gap.
Referenced by LoadVoiceVariant(), main(), and SetVoiceByName().
voice_t* LoadVoiceVariant (const char * voice_name, int variant)
References buf, ExtractVoiceVariantName(), LoadVoice(), NULL, and strncpy0().
Referenced by SetVoiceByProperties(), and SpeakNextClause().
void ReadTonePoints (char * string, int * tone_pts)
Referenced by LoadConfig(), and LoadVoice().
const char* SelectVoice (espeak_VOICE * voice_select, int * found)
References espeak_VOICE::age, AGE_OLD, buf, espeak_ListVoices(), ExtractVoiceVariantName(), espeak_VOICE::gender, espeak_VOICE::identifier, espeak_VOICE::languages, N_VOICE_VARIANTS, N_VOICES_LIST, n_voices_list, espeak_VOICE::name, NULL, p, SelectVoiceByName(), SetVoiceScores(), skip(), sprintf(), strncpy0(), espeak_VOICE::variant, variant_lists, and espeak_VOICE::xx1.
Referenced by SetVoiceByProperties(), and VoiceFromStack().
espeak_VOICE* SelectVoiceByName (espeak_VOICE ** voices, const char * name)
References espeak_ListVoices(), n_voices_list, NULL, PATHSEP, sprintf(), and voices_list.
Referenced by SelectVoice(), SetVoiceByName(), and VoiceFromStack().
void WavegenSetVoice (voice_t * v)
References voice_t::consonant_amp, consonant_amp, option_harmonic1, voice_t::peak_shape, pk_shape1, pk_shape2, and WavegenSetEcho().
Referenced by WavegenFill().
Variable Documentation
int tone_points[12]
Referenced by LoadConfig(), and VoiceReset().
voice_t* voice
Referenced by AdjustFormants(), DoSpect(), espeak_Initialize(), espeak_new(), formants_reduce_hf(), FormantTransition2(), LookupCharName(), LookupLetter(), main(), set_frame_rms(), SetSpeed(), SetTranslator2(), SpeakNextClause(), TranslateLetter(), TranslateWord2(), Wavegen(), and WritePitch().
USHORT voice_pcnt[N_PEAKS+1][3]