navit: support/espeak/wave.h File Reference
wave.h File Reference
#include "stdint.h"
Typedefs
typedef int(t_wave_callback)(void)
Functions
void wave_init ()
void * wave_open (const char *the_api)
size_t wave_write (void *theHandler, char *theMono16BitsWaveBuffer, size_t theSize)
int wave_close (void *theHandler)
void wave_flush (void *theHandler)
int wave_is_busy (void *theHandler)
void wave_terminate ()
uint32_t wave_get_read_position (void *theHandler)
uint32_t wave_get_write_position (void *theHandler)
int wave_get_remaining_time (uint32_t sample, uint32_t *time)
void wave_set_callback_is_output_enabled (t_wave_callback *cb)
void clock_gettime2 (struct timespec *ts)
void add_time_in_ms (struct timespec *ts, int time_in_ms)
void * wave_test_get_write_buffer ()
Variables
int option_device_number
Typedef Documentation
typedef int(t_wave_callback)(void)
Function Documentation
void add_time_in_ms (struct timespec * ts, int time_in_ms)
void clock_gettime2 (struct timespec * ts)
int wave_close (void * theHandler)
Referenced by espeak_Cancel(), and espeak_Terminate().
void wave_flush (void * theHandler)
Referenced by sync_espeak_Synth().
uint32_t wave_get_read_position (void * theHandler)
int wave_get_remaining_time (uint32_t sample, uint32_t * time)
uint32_t wave_get_write_position (void * theHandler)
Referenced by Synthesize().
void wave_init ()
Referenced by select_output().
int wave_is_busy (void * theHandler)
Referenced by espeak_IsPlaying().
void* wave_open (const char * the_api)
Referenced by select_output().
void wave_set_callback_is_output_enabled (t_wave_callback * cb)
Referenced by select_output().
void wave_terminate ()
Referenced by espeak_Terminate().
void* wave_test_get_write_buffer ()
size_t wave_write (void * theHandler, char * theMono16BitsWaveBuffer, size_t theSize)
Variable Documentation
int option_device_number