navit: gui/win32/win32_gui_destination.c File Reference
win32_gui_destination.c File Reference
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <glib.h>
#include "item.h"
#include "attr.h"
#include "navit.h"
#include "search.h"
#include "debug.h"
#include "util.h"
#include "win32_gui_notify.h"
#include "resources/resource.h"
Data Structures
struct datawindow_priv
Functions
static void setlayout (struct datawindow_priv *datawindow)
static void notify_apply (struct datawindow_priv *datawindow, int index, int param2)
static void notify_back (struct datawindow_priv *datawindow, int param1, int param2)
static void notify_textchange (struct datawindow_priv *datawindow, int param1, int param2)
static void notify_destroy (struct datawindow_priv *datawindow, int param1, int param2)
static void notify_size (struct datawindow_priv *datawindow, int width, int height)
static BOOL init_lv_columns (HWND hWndListView)
BOOL register_destination_window ()
HANDLE create_destination_window (struct navit *nav)
Variables
static const TCHAR g_szDestinationClassName [] = TEXT("navit_gui_destinationwindow_class")
Function Documentation
create_destination_window()
HANDLE create_destination_window (struct navit * nav)
References BUTTON_CLICK, CHANGE, datawindow_priv::currentSearchState, dbg, DBLCLICK, g_szDestinationClassName, datawindow_priv::hwnd, datawindow_priv::hwndButtonNext, datawindow_priv::hwndButtonPrev, datawindow_priv::hwndEdit, datawindow_priv::hwndLabel, datawindow_priv::hwndList, init_lv_columns(), lvl_error, datawindow_priv::nav, navit_get_mapset(), datawindow_priv::notifications, notify_apply(), notify_back(), notify_destroy(), notify_size(), notify_textchange(), search_list_new(), datawindow_priv::sl, win32_gui_notify(), win32_gui_notify_new(), WINDOW_DESTROY, and WINDOW_SIZE.
init_lv_columns()
static BOOL init_lv_columns (HWND hWndListView) static
Referenced by create_destination_window().
notify_apply()
static void notify_apply (struct datawindow_priv * datawindow, int index, int param2) static
References search_list_result::c, datawindow_priv::currentSearchState, datawindow_priv::hwnd, datawindow_priv::hwndList, datawindow_priv::nav, navit_set_destination(), search_list_get_result(), search_list_search(), setlayout(), datawindow_priv::sl, attr::str, attr::type, and attr::u.
Referenced by create_destination_window().
notify_back()
static void notify_back (struct datawindow_priv * datawindow, int param1, int param2) static
References datawindow_priv::currentSearchState, and setlayout().
Referenced by create_destination_window().
notify_destroy()
static void notify_destroy (struct datawindow_priv * datawindow, int param1, int param2) static
References search_list_destroy(), and datawindow_priv::sl.
Referenced by create_destination_window().
notify_size()
static void notify_size (struct datawindow_priv * datawindow, int width, int height) static
References datawindow_priv::hwndButtonNext, datawindow_priv::hwndButtonPrev, datawindow_priv::hwndEdit, datawindow_priv::hwndLabel, datawindow_priv::hwndList, and setlayout().
Referenced by create_destination_window().
notify_textchange()
static void notify_textchange (struct datawindow_priv * datawindow, int param1, int param2) static
References search_list_town::common, search_list_result::country, datawindow_priv::currentSearchState, dbg, datawindow_priv::hwndEdit, datawindow_priv::hwndList, search_list_country::iso2, lvl_debug, lvl_error, search_list_country::name, search_list_street::name, search_list_get_result(), search_list_search(), datawindow_priv::sl, attr::str, search_list_result::street, search_list_result::town, search_list_common::town_name, attr::type, and attr::u.
Referenced by create_destination_window().
register_destination_window()
BOOL register_destination_window ()
References dbg, g_szDestinationClassName, IDI_NAVIT, lvl_error, and message_handler().
setlayout()
static void setlayout (struct datawindow_priv * datawindow) static
References datawindow_priv::currentSearchState, datawindow_priv::hwndEdit, datawindow_priv::hwndLabel, and datawindow_priv::hwndList.
Referenced by notify_apply(), notify_back(), and notify_size().
Variable Documentation
g_szDestinationClassName
const TCHAR g_szDestinationClassName[] = TEXT("navit_gui_destinationwindow_class") static
Referenced by create_destination_window(), and register_destination_window().