navit: gui/win32/win32_gui_notify.c File Reference
win32_gui_notify.c File Reference
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <glib.h>
#include "win32_gui_notify.h"
Data Structures
struct window_data
struct notify_priv
Functions
void win32_gui_notify (struct notify_priv *notify, HWND hwnd, int message_id, void(*func)(struct datawindow_priv *parent, int param1, int param2))
struct notify_priv * win32_gui_notify_new (struct datawindow_priv *parent)
LRESULT CALLBACK message_handler (HWND hwnd, UINT win_message, WPARAM wParam, LPARAM lParam)
Function Documentation
LRESULT CALLBACK message_handler (HWND hwnd, UINT win_message, WPARAM wParam, LPARAM lParam)
References BUTTON_CLICK, CHANGE, CLICK, _GList::data, DBLCLICK, FALSE, window_data::func, g_list_first(), g_list_next, window_data::hwnd, INVALID, window_data::message, NULL, notify_priv::parent, WINDOW_CREATE, WINDOW_DESTROY, notify_priv::window_list, and WINDOW_SIZE.
void win32_gui_notify (struct notify_priv * notify, HWND hwnd, int message_id, void(*)(struct datawindow_priv *parent, int param1, int param2) func)
References window_data::func, g_list_append(), g_new, window_data::hwnd, window_data::message, and notify_priv::window_list.
Referenced by create_destination_window().
struct notify_priv* win32_gui_notify_new (struct datawindow_priv * parent)
References g_new0, and notify_priv::parent.
Referenced by create_destination_window().