navit: gui/win32/win32_gui_notify.h File Reference
win32_gui_notify.h File Reference
Enumerations
enum message_id {
WINDOW_CREATE, WINDOW_SIZE, WINDOW_DESTROY, DBLCLICK,
CLICK, CHANGE, BUTTON_CLICK, INVALID
}
Functions
struct notify_priv * win32_gui_notify_new ()
void win32_gui_notify (struct notify_priv *notify, HWND hwnd, int message_id, void(*func)(struct datawindow_priv *parent, int param1, int param2))
LRESULT CALLBACK message_handler (HWND hwnd, UINT win_message, WPARAM wParam, LPARAM lParam)
Enumeration Type Documentation
enum message_id
Enumerator
WINDOW_CREATE
WINDOW_SIZE
WINDOW_DESTROY
DBLCLICK
CLICK
CHANGE
BUTTON_CLICK
INVALID
Function Documentation
LRESULT CALLBACK message_handler (HWND hwnd, UINT win_message, WPARAM wParam, LPARAM lParam)
References BUTTON_CLICK, CHANGE, CLICK, _GList::data, DBLCLICK, FALSE, window_data::func, g_list_first(), g_list_next, window_data::hwnd, INVALID, window_data::message, NULL, notify_priv::parent, WINDOW_CREATE, WINDOW_DESTROY, notify_priv::window_list, and WINDOW_SIZE.
void win32_gui_notify (struct notify_priv * notify, HWND hwnd, int message_id, void(*)(struct datawindow_priv *parent, int param1, int param2) func)
References window_data::func, g_list_append(), g_new, window_data::hwnd, window_data::message, and notify_priv::window_list.
Referenced by create_destination_window().
struct notify_priv* win32_gui_notify_new ()