navit: support/wordexp/wordexp.h File Reference
wordexp.h File Reference
Data Structures
struct wordexp_t
Macros
#define WRDE_APPEND 0x1 /* append to previously generated */
#define WRDE_DOOFFS 0x2 /* we_offs member is valid */
#define WRDE_NOCMD 0x4 /* disallow command substitution */
#define WRDE_REUSE 0x8 /* reuse wordexp_t */
#define WRDE_SHOWERR 0x10 /* don't redirect stderr to /dev/null */
#define WRDE_UNDEF 0x20 /* disallow undefined shell vars */
#define WRDE_BADCHAR 1 /* unquoted special character */
#define WRDE_BADVAL 2 /* undefined variable */
#define WRDE_CMDSUB 3 /* command substitution not allowed */
#define WRDE_NOSPACE 4 /* no memory for result */
#define WRDE_SYNTAX 6 /* shell syntax error */
#define WRDE_ERRNO 7 /* other errors see errno */
Functions
void wordfree (wordexp_t *)
int wordexp (const char *words, wordexp_t *we, int flags)
Macro Definition Documentation
#define WRDE_APPEND 0x1 /* append to previously generated */
#define WRDE_BADCHAR 1 /* unquoted special character */
#define WRDE_BADVAL 2 /* undefined variable */
#define WRDE_CMDSUB 3 /* command substitution not allowed */
#define WRDE_DOOFFS 0x2 /* we_offs member is valid */
#define WRDE_ERRNO 7 /* other errors see errno */
#define WRDE_NOCMD 0x4 /* disallow command substitution */
#define WRDE_NOSPACE 4 /* no memory for result */
#define WRDE_REUSE 0x8 /* reuse wordexp_t */
#define WRDE_SHOWERR 0x10 /* don't redirect stderr to /dev/null */
#define WRDE_SYNTAX 6 /* shell syntax error */
#define WRDE_UNDEF 0x20 /* disallow undefined shell vars */
Function Documentation
int wordexp (const char * words, wordexp_t * we, int flags)
References expand_variables(), g_strdup(), glob_t::gl_offs, glob_t::gl_pathc, glob_t::gl_pathv, glob(), globfree(), i, NULL, wordexp_t::we_offs, wordexp_t::we_wordc, and wordexp_t::we_wordv.
Referenced by file_wordexp_new(), and graphics_icon_path().
void wordfree (wordexp_t *)
References i, wordexp_t::we_wordc, and wordexp_t::we_wordv.
Referenced by file_wordexp_destroy().