navit: support/libc/write.c File Reference
write.c File Reference
#include <windows.h>
#include <unistd.h>
Functions
int _write (int fildes, const void *buf, unsigned int bufsize)
int write (int fildes, const void *buf, unsigned int bufsize)
Function Documentation
int _write (int fildes, const void * buf, unsigned int bufsize)
References NULL.
Referenced by write().
int write (int fildes, const void * buf, unsigned int bufsize)
References _write().
Referenced by draw_mode(), file_data_write(), inflate_fast(), pedestrian_write_tilt(), progress_memory(), progress_time(), send_and_read(), sig_alrm_do(), vehicle_file_open(), and write_to_serial_port().