navit: graphics/win32/xpm2bmp.c File Reference
xpm2bmp.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
#include <wingdi.h>
#include <glib/glib.h>
#include "xpm2bmp.h"
Functions
static int CreateBitmapFromXpm (const char *filename, PXPM2BMP pXpm2bmp)
PXPM2BMP Xpm2bmp_new (void)
int Xpm2bmp_load (PXPM2BMP pXpm2bmp, const char *filename)
int Xpm2bmp_paint (PXPM2BMP pXpm2bmp, HDC hdc, int x1, int y1)
static int parse_line_values (const char *line, PXPM2BMP pXpm2bmp)
static int hex2int (char c)
static DWORD string2hex16 (const char *str)
static int parse_color_values (const char *line, PXPM2BMP pXpm2bmp)
static int parse_pixel_line_values (const char *line, PXPM2BMP pXpm2bmp, unsigned char *pixel_data, unsigned char *pixel_data_trans)
Variables
static XPMCOLORENTRY theRGBRecords []
static int vv = 0
Function Documentation
CreateBitmapFromXpm()
static int CreateBitmapFromXpm (const char * filename, PXPM2BMP pXpm2bmp) static
References XPM2BMP_TAG::bmih, XPM2BMP_TAG::bmih_trans, XPM2BMP_TAG::chars_per_pixel, XPM2BMP_TAG::color_entires, XPM2BMP_TAG::color_entires_size, XPMCOLORENTRY_TAG::color_str, XPM2BMP_TAG::colors, XPM2BMP_TAG::dib, XPM2BMP_TAG::dib_trans, graphics_priv::padding, parse_color_values(), parse_line_values(), parse_pixel_line_values(), phase, XPM2BMP_TAG::size_x, XPM2BMP_TAG::size_y, XPM2BMP_TAG::wimage_data, and XPM2BMP_TAG::wimage_data_trans.
Referenced by Xpm2bmp_load().
hex2int()
static int hex2int (char c) static
Referenced by string2hex16().
parse_color_values()
static int parse_color_values (const char * line, PXPM2BMP pXpm2bmp) static
References XPMCOLORENTRY_TAG::b, XPM2BMP_TAG::chars_per_pixel, XPM2BMP_TAG::color_entires, XPM2BMP_TAG::color_entires_size, XPMCOLORENTRY_TAG::color_str, XPMCOLORENTRY_TAG::g, XPMCOLORENTRY_TAG::r, string2hex16(), and theRGBRecords.
Referenced by CreateBitmapFromXpm().
parse_line_values()
static int parse_line_values (const char * line, PXPM2BMP pXpm2bmp) static
References XPM2BMP_TAG::chars_per_pixel, XPM2BMP_TAG::colors, XPM2BMP_TAG::hotspot_x, XPM2BMP_TAG::hotspot_y, parse_line(), XPM2BMP_TAG::size_x, and XPM2BMP_TAG::size_y.
Referenced by CreateBitmapFromXpm().
parse_pixel_line_values()
static int parse_pixel_line_values (const char * line, PXPM2BMP pXpm2bmp, unsigned char * pixel_data, unsigned char * pixel_data_trans) static
References XPMCOLORENTRY_TAG::b, XPM2BMP_TAG::chars_per_pixel, cmp(), XPM2BMP_TAG::color_entires, XPMCOLORENTRY_TAG::color_str, XPMCOLORENTRY_TAG::g, XPMCOLORENTRY_TAG::r, XPM2BMP_TAG::size_x, and vv.
Referenced by CreateBitmapFromXpm().
string2hex16()
static DWORD string2hex16 (const char * str) static
References hex2int().
Referenced by parse_color_values().
Xpm2bmp_load()
int Xpm2bmp_load (PXPM2BMP pXpm2bmp, const char * filename)
References CreateBitmapFromXpm().
Referenced by xpmdecode().
Xpm2bmp_new()
PXPM2BMP Xpm2bmp_new (void)
Referenced by xpmdecode().
Xpm2bmp_paint()
int Xpm2bmp_paint (PXPM2BMP pXpm2bmp, HDC hdc, int x1, int y1)
References XPM2BMP_TAG::bmih, XPM2BMP_TAG::bmih_trans, XPM2BMP_TAG::size_x, XPM2BMP_TAG::size_y, XPM2BMP_TAG::wimage_data, and XPM2BMP_TAG::wimage_data_trans.
Referenced by draw_image().
Variable Documentation
theRGBRecords
XPMCOLORENTRY theRGBRecords[] static
Referenced by parse_color_values().
vv
int vv = 0 static
Referenced by parse_pixel_line_values().