navit: graphics/win32/xpm2bmp.h File Reference
xpm2bmp.h File Reference
#include <windows.h>
#include "wingdi.h"
Data Structures
struct XPMCOLORENTRY_TAG
struct XPM2BMP_TAG
Typedefs
typedef struct XPMCOLORENTRY_TAG XPMCOLORENTRY
typedef struct XPMCOLORENTRY_TAG * PXPMCOLORENTRY
typedef struct XPM2BMP_TAG XPM2BMP
typedef struct XPM2BMP_TAG * PXPM2BMP
Functions
PXPM2BMP Xpm2bmp_new (void)
int Xpm2bmp_load (PXPM2BMP pXpm2bmp, const char *filename)
int Xpm2bmp_paint (PXPM2BMP pXpm2bmp, HDC hdc, int x1, int y1)
Typedef Documentation
PXPM2BMP
typedef struct XPM2BMP_TAG * PXPM2BMP
PXPMCOLORENTRY
typedef struct XPMCOLORENTRY_TAG * PXPMCOLORENTRY
XPM2BMP
typedef struct XPM2BMP_TAG XPM2BMP
XPMCOLORENTRY
typedef struct XPMCOLORENTRY_TAG XPMCOLORENTRY
Function Documentation
Xpm2bmp_load()
int Xpm2bmp_load (PXPM2BMP pXpm2bmp, const char * filename)
References CreateBitmapFromXpm(), and filename.
Referenced by xpmdecode().
Xpm2bmp_new()
PXPM2BMP Xpm2bmp_new (void)
Referenced by xpmdecode().
Xpm2bmp_paint()
int Xpm2bmp_paint (PXPM2BMP pXpm2bmp, HDC hdc, int x1, int y1)
References XPM2BMP_TAG::bmih, XPM2BMP_TAG::bmih_trans, XPM2BMP_TAG::size_x, XPM2BMP_TAG::size_y, XPM2BMP_TAG::wimage_data, and XPM2BMP_TAG::wimage_data_trans.
Referenced by draw_image().