navit: support/gettext_intl/xsize.h File Reference
xsize.h File Reference
#include <stddef.h>
#include <limits.h>
Macros
#define xcast_size_t(N) ((N) <= SIZE_MAX ? (size_t) (N) : SIZE_MAX)
#define xtimes(N, ELSIZE) ((N) <= SIZE_MAX / (ELSIZE) ? (size_t) (N) * (ELSIZE) : SIZE_MAX)
#define size_overflow_p(SIZE) ((SIZE) == SIZE_MAX)
#define size_in_bounds_p(SIZE) ((SIZE) != SIZE_MAX)
Functions
static size_t xsum (size_t size1, size_t size2)
static size_t xsum3 (size_t size1, size_t size2, size_t size3)
static size_t xsum4 (size_t size1, size_t size2, size_t size3, size_t size4)
static size_t xmax (size_t size1, size_t size2)
Macro Definition Documentation
#define size_in_bounds_p (SIZE) ((SIZE) != SIZE_MAX)
#define size_overflow_p (SIZE) ((SIZE) == SIZE_MAX)
Referenced by PRINTF_PARSE(), and VASNPRINTF().
#define xcast_size_t (N) ((N) <= SIZE_MAX ? (size_t) (N) : SIZE_MAX)
#define xtimes (N, ELSIZE) ((N) <= SIZE_MAX / (ELSIZE) ? (size_t) (N) * (ELSIZE) : SIZE_MAX)
Referenced by PRINTF_PARSE(), and VASNPRINTF().
Function Documentation
static size_t xmax (size_t size1, size_t size2) static
Referenced by quadtree_find_nearest_flood(), quadtree_find_rect_items(), quadtree_item_next(), quadtree_node_new(), and VASNPRINTF().
static size_t xsum (size_t size1, size_t size2) static
Referenced by PRINTF_PARSE(), VASNPRINTF(), xsum3(), and xsum4().
static size_t xsum3 (size_t size1, size_t size2, size_t size3) static
References xsum().
static size_t xsum4 (size_t size1, size_t size2, size_t size3, size_t size4) static
References xsum().
Referenced by VASNPRINTF().