navit: maptool/zip.c File Reference
zip.c File Reference
#include <zlib.h>
#include <string.h>
#include <stdlib.h>
#include "debug.h"
#include "maptool.h"
#include "config.h"
#include "zipfile.h"
Data Structures
struct zip_info
Functions
static int zip_write (struct zip_info *info, void *data, int len)
void write_zipmember (struct zip_info *zip_info, char *name, int filelen, char *data, int data_size)
int zip_write_index (struct zip_info *info)
static void zip_write_file_data (struct zip_info *info, FILE *in)
int zip_write_directory (struct zip_info *info)
struct zip_info * zip_new (void)
void zip_set_zip64 (struct zip_info *info, int on)
void zip_set_compression_level (struct zip_info *info, int level)
void zip_set_maxnamelen (struct zip_info *info, int max)
int zip_get_maxnamelen (struct zip_info *info)
int zip_add_member (struct zip_info *info)
int zip_set_timestamp (struct zip_info *info, char *timestamp)
int zip_open (struct zip_info *info, char *out, char *dir, char *index)
FILE * zip_get_index (struct zip_info *info)
int zip_get_zipnum (struct zip_info *info)
void zip_set_zipnum (struct zip_info *info, int num)
void zip_close (struct zip_info *info)
void zip_destroy (struct zip_info *info)
Function Documentation
write_zipmember()
void write_zipmember (struct zip_info * zip_info, char * name, int filelen, char * data, int data_size)
References zip_info::compression_level, zip_info::date, dbg_assert, zip_info::dir, zip_info::dir_size, filename, zip_info::offset, zip_info::time, zip_info::zip64, zip_write(), zip_cd::zipccrc, zip_cd::zipcmthd, zip_lfh::zipcrc, zip_cd::zipcsiz, zip_cd::zipcunc, zip_cd::zipcxtl, zip_lfh::zipmthd, zip_cd::zipofst, zip_lfh::zipsize, and zip_lfh::zipuncmp.
Referenced by ch_assemble_map(), process_slice(), write_aux_tiles(), and zip_write_index().
zip_add_member()
int zip_add_member (struct zip_info * info)
References zip_info::zipnum.
Referenced by add_aux_tile(), write_aux_tiles(), and write_tilesdir().
zip_close()
void zip_close (struct zip_info * info)
References zip_info::dir, zip_info::index, and zip_info::res2.
Referenced by maptool_assemble_map().
zip_destroy()
void zip_destroy (struct zip_info * info)
Referenced by maptool_assemble_map().
zip_get_index()
FILE* zip_get_index (struct zip_info * info)
References zip_info::index.
Referenced by ch_assemble_map(), index_init(), process_slice(), write_countrydir(), and write_tilesdir().
zip_get_maxnamelen()
int zip_get_maxnamelen (struct zip_info * info)
References zip_info::maxnamelen.
Referenced by ch_assemble_map(), process_slice(), and write_aux_tiles().
zip_get_zipnum()
int zip_get_zipnum (struct zip_info * info)
References zip_info::zipnum.
Referenced by maptool_assemble_map(), maptool_generate_tiles(), phase5(), and write_tilesdir().
zip_new()
struct zip_info* zip_new (void)
Referenced by maptool_assemble_map(), and maptool_generate_tiles().
zip_open()
int zip_open (struct zip_info * info, char * out, char * dir, char * index)
References zip_info::dir, zip_info::index, and zip_info::res2.
Referenced by maptool_assemble_map().
zip_set_compression_level()
void zip_set_compression_level (struct zip_info * info, int level)
References zip_info::compression_level.
Referenced by maptool_assemble_map().
zip_set_maxnamelen()
void zip_set_maxnamelen (struct zip_info * info, int max)
References max, and zip_info::maxnamelen.
Referenced by maptool_assemble_map().
zip_set_timestamp()
int zip_set_timestamp (struct zip_info * info, char * timestamp)
References zip_info::date, and zip_info::time.
Referenced by maptool_assemble_map(), and maptool_generate_tiles().
zip_set_zip64()
void zip_set_zip64 (struct zip_info * info, int on)
References zip_info::zip64.
Referenced by maptool_assemble_map(), and maptool_generate_tiles().
zip_set_zipnum()
void zip_set_zipnum (struct zip_info * info, int num)
References zip_info::zipnum.
Referenced by maptool_assemble_map(), maptool_generate_tiles(), and phase5().
zip_write()
static int zip_write (struct zip_info * info, void * data, int len) static
References startup::dest, err(), and zip_info::res2.
Referenced by write_zipmember(), zip_write_directory(), and zip_write_file_data().
zip_write_directory()
int zip_write_directory (struct zip_info * info)
References zip_info::dir, zip_info::dir_size, zip_info::offset, sig_alrm(), zip_info::zip64, zip64_eoc::zip64ecenn, zip64_eoc::zip64ecsz, zip64_eoc::zip64eneed, zip64_eoc::zip64enum, zip64_eoc::zip64eofst, zip64_eoc::zip64esize, zip64_eoc::zip64ever, zip64_eocl::zip64lofst, zip64_eocl::zip74lnum, zip_write(), zip_write_file_data(), zip_eoc::zipecenn, zip_eoc::zipecsz, zip_eoc::zipenum, zip_eoc::zipeofst, and zip_info::zipnum.
Referenced by maptool_assemble_map().
zip_write_file_data()
static void zip_write_file_data (struct zip_info * info, FILE * in) static
References size, and zip_write().
Referenced by zip_write_directory().
zip_write_index()
int zip_write_index (struct zip_info * info)
References dbg, zip_info::index, lvl_warning, size, write_zipmember(), and zip_info::zipnum.
Referenced by maptool_assemble_map().