/* prototypes */

/* common */
ATTR2(none,0x00000000)
ATTR(any)

ATTR2(type_item_begin,0x00010000)
ATTR(town_streets_item)
ATTR(street_name_item)
ATTR(street_name_numbers_item)
ATTR(street_item)
ATTR(street_number_item)
ATTR(item_type)
ATTR2(type_item_end,0x0001ffff)

ATTR2(type_int_begin,0x00020000)
ATTR(h)
ATTR(id)
ATTR(limit)
ATTR(w)
ATTR(x)
ATTR(y)
ATTR2(type_int_end,0x0002ffff)

ATTR2(type_string_begin,0x00030000)
ATTR(skin)
ATTR(label)
ATTR(data)
ATTR(charset)
ATTR(country_all)
ATTR(country_iso3)
ATTR(country_iso2)
ATTR(country_car)
ATTR(country_name)
ATTR(town_name)
ATTR(town_postal)
ATTR(district_name)
ATTR(street_name)
ATTR(street_name_systematic)
ATTR(street_number)
ATTR(debug)
ATTR(address)
ATTR(phone)
ATTR(entry_fee)
ATTR(open_hours)
/* poi */
ATTR(icon)
ATTR(info_html)
ATTR(price_html)
ATTR2(type_string_end,0x0003ffff)
