.TH FH_MAKEHEAP 3 "29 Mar 2000" "libfib"
.SH NAME
fh_makeheap \- make a Fibonacci Heap
.SH SYNOPSIS
.nf
#include <fib.h>
.PP
struct fibheap *
.BR fh_makeheap (void)
.fi
.SH DESCRIPTION
.SH RETURN VALUES
.SH FILES
.SH SEE ALSO
.SH AUTHORS
This library and man page was writen by John-Mark Gurney <gurney_j@efn.org>.
.SH BUGS
