version: 2
defaults: &defaults
  docker:
    - image: debian:latest
jobs:
  sanity_check:
    docker:
      - image: ghcr.io/navit-gps/sanity_check:master
    steps:
      - checkout
      - run:
          name: run sanity check script
          command: bash scripts/ci_sanity_checks.sh
      #- run:
      #    name: Run CheckStyle Test
      #    command: ./gradlew checkstyleMain
      #- store_artifacts:
      #    name: Store checkstyle report
      #    path: navit/android/checkstyle
      #    destination: reports
  run_doxygen:
    <<: *defaults
    steps:
      - checkout
      - run: if scripts/check_need_build.sh; then circleci step halt; fi
      - run:
          name: Install doxygen and other essentials
          command: apt-get update && apt-get -y install doxygen ca-certificates git rsync
      - run:
          name: Run doxygen
          command: cd navit && doxygen
      - run:
          name: Update results to Github
          command: bash scripts/update_doxygen.sh
      - store_artifacts:
          path: /root/project/doc
  build_sailfish:
    machine: true
    steps:
      - checkout
      - run: if scripts/check_need_build.sh; then circleci step halt; fi
      - run:
          name: make build dir
          command:  mkdir ../rpmbuild && chmod 777 ../rpmbuild
      - run:
          name: run build
          command: ls -lah ../rpmbuild && docker run -e VERSION_ID=5.0.0.43 -v `pwd`/../rpmbuild:/home/nemo/rpmbuild:rw -v `pwd`:/home/nemo/navit coderus/sailfishos-platform-sdk:5.0.0.43 /bin/bash -x /home/nemo/navit/contrib/sailfish/build_sailfish_ci.sh
      - store_artifacts:
          name: Store rpm
          path: ../rpmbuild/RPMS/
          destination: rpmbuild
  merge_trunk_in_master:
    docker:
      - image: cimg/base:2026.04
    steps:
      - checkout
      - run:
          name: configure ssh git
          command: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "58:42:73:90:cc:68:f7:34:7e:37:37:fa:b3:26:1f:a5"
      - run:
          name: Update results to Github
          command: export GIT_TERMINAL_PROMPT=0 && git push origin $CIRCLE_SHA1:refs/heads/master
  check_spelling:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install curl
          command: apt-get update && apt-get -y install curl
      - run:
          name: Install misspell
          command: |
              curl -L -o ./install-misspell.sh https://git.io/misspell
              sh ./install-misspell.sh -b /usr/local/bin/
      - run:
          name: Check docs folder for misspells
          command: |
              misspell docs/ > typos.txt
              if [[ $( wc -l < typos.txt ) -gt 0 ]]; then
                echo "Typos/mispells found, please fix them";
                cat typos.txt
                exit -1
              fi


workflows:
  version: 2
  build_all:
    jobs:
      - sanity_check
      - build_sailfish:
          requires:
            - sanity_check
      - run_doxygen:
          filters:
            branches:
              only: /^trunk$/
      - check_spelling:
          filters:
            branches:
              only: /^readthedocs$/
