#! /bin/bash
ulimit -t 5
png=$1
if [[ "$png" = *_[1-9]*_[1-9]*.png ]]; 
then
        svg=${png%_*_*.png};
	h=${png##*_}
	w=${png%_$h}
	h=${h%.png}
	w=${w##*_}
else
	svg=${png%.png}
fi
if [ ! -f $svg.svg -a ! -f $svg.svgz ]
then
	svg="$SRCDIR/$svg"
fi
if [ -f $png -a ! -f $svg.svg ]
then
	touch $png
else
	if [ -f $svg.svg ]
	then
		if [ -z "$w" ]
		then
			w=$(grep 'width="[0-9px.]*"' $svg.svg | head -n 1 | sed -e 's/^[^"]*"//' -e 's/[px]*".*//')
		fi
		if [ -z "$h" ]
		then
			h=$(grep 'height="[0-9px.]*"' $svg.svg | head -n 1 | sed -e 's/^[^"]*"//' -e 's/[px]*".*//')
		fi
		ksvgtopng $w $h $svg.svg $png
	elif [ -f $svg.svgz ]
	then
		gzip -dc <$svg.svgz >$svg.svg
		ksvgtopng $w $h $svg.svg $png
		rm -f $svg.svg
	fi
fi
exit 0
