/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define map_COMMON
#include "map.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_map
void
_ORBIT_skel_small_Mappel_Test(POA_Mappel * _o_servant, gpointer _o_retval,
			      gpointer * _o_args, CORBA_Context _o_ctx,
			      CORBA_Environment * _o_ev,
			      void (*_impl_Test) (PortableServer_Servant
						  _servant,
						  CORBA_Environment * ev))
{
   _impl_Test(_o_servant, _o_ev);
}

void
_ORBIT_skel_small_Map_mapString(POA_Map * _o_servant, gpointer _o_retval,
				gpointer * _o_args, CORBA_Context _o_ctx,
				CORBA_Environment * _o_ev,
				Map(*_impl_mapString) (PortableServer_Servant
						       _servant,
						       const CORBA_char *
						       astring,
						       CORBA_double * anum,
						       CORBA_Environment *
						       ev))
{
   *(Map *) _o_retval =
      _impl_mapString(_o_servant, *(const CORBA_char * *) _o_args[0],
		      *(CORBA_double * *)_o_args[1], _o_ev);
}

void
_ORBIT_skel_small_Map_doNothing(POA_Map * _o_servant, gpointer _o_retval,
				gpointer * _o_args, CORBA_Context _o_ctx,
				CORBA_Environment * _o_ev,
				void (*_impl_doNothing)
				(PortableServer_Servant _servant,
				 CORBA_Environment * ev))
{
   _impl_doNothing(_o_servant, _o_ev);
}

void
_ORBIT_skel_small_Map_doOneWay(POA_Map * _o_servant, gpointer _o_retval,
			       gpointer * _o_args, CORBA_Context _o_ctx,
			       CORBA_Environment * _o_ev,
			       void (*_impl_doOneWay) (PortableServer_Servant
						       _servant,
						       const CORBA_char *
						       ignore,
						       CORBA_Environment *
						       ev))
{
   _impl_doOneWay(_o_servant, *(const CORBA_char * *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_Map_PlaceFlag(POA_Map * _o_servant, gpointer _o_retval,
				gpointer * _o_args, CORBA_Context _o_ctx,
				CORBA_Environment * _o_ev,
				void (*_impl_PlaceFlag)
				(PortableServer_Servant _servant,
				 CORBA_Environment * ev))
{
   _impl_PlaceFlag(_o_servant, _o_ev);
}

void
_ORBIT_skel_small_Map_PointFromCoord(POA_Map * _o_servant, gpointer _o_retval,
				     gpointer * _o_args, CORBA_Context _o_ctx,
				     CORBA_Environment * _o_ev,
				     PointObj(*_impl_PointFromCoord)
				     (PortableServer_Servant _servant,
				      const CORBA_char * coord,
				      CORBA_Environment * ev))
{
   *(PointObj *) _o_retval =
      _impl_PointFromCoord(_o_servant, *(const CORBA_char * *) _o_args[0],
			   _o_ev);
}

void
_ORBIT_skel_small_Map_View(POA_Map * _o_servant, gpointer _o_retval,
			   gpointer * _o_args, CORBA_Context _o_ctx,
			   CORBA_Environment * _o_ev,
			   void (*_impl_View) (PortableServer_Servant
					       _servant,
					       const PointObj * where,
					       CORBA_Environment * ev))
{
   _impl_View(_o_servant, (const PointObj *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_Map_ViewAll(POA_Map * _o_servant, gpointer _o_retval,
			      gpointer * _o_args, CORBA_Context _o_ctx,
			      CORBA_Environment * _o_ev,
			      void (*_impl_ViewAll) (PortableServer_Servant
						     _servant,
						     const PointObjSequence *
						     where,
						     CORBA_Environment * ev))
{
   _impl_ViewAll(_o_servant, (const CORBA_sequence_PointObj *) _o_args[0],
		 _o_ev);
}

void
_ORBIT_skel_small_Map_Route(POA_Map * _o_servant, gpointer _o_retval,
			    gpointer * _o_args, CORBA_Context _o_ctx,
			    CORBA_Environment * _o_ev,
			    void (*_impl_Route) (PortableServer_Servant
						 _servant,
						 const PointObj * src,
						 const PointObj * dst,
						 CORBA_Environment * ev))
{
   _impl_Route(_o_servant, (const PointObj *) _o_args[0],
	       (const PointObj *) _o_args[1], _o_ev);
}

void
_ORBIT_skel_small_Map_Get(POA_Map * _o_servant, gpointer _o_retval,
			  gpointer * _o_args, CORBA_Context _o_ctx,
			  CORBA_Environment * _o_ev,
			  Mappel(*_impl_Get) (PortableServer_Servant _servant,
					      CORBA_Environment * ev))
{
   *(Mappel *) _o_retval = _impl_Get(_o_servant, _o_ev);
}

#endif
#if ( (TC_IMPL_TC_PointObj_0 == 'm') \
&& (TC_IMPL_TC_PointObj_1 == 'a') \
&& (TC_IMPL_TC_PointObj_2 == 'p') \
) && !defined(TC_DEF_TC_PointObj)
#define TC_DEF_TC_PointObj 1
static const char *anon_subnames_array0[] = { "lng", "lat", "height" };
static const CORBA_TypeCode anon_subtypes_array1[] =
   { (CORBA_TypeCode) & TC_CORBA_float_struct,
(CORBA_TypeCode) & TC_CORBA_float_struct, (CORBA_TypeCode) & TC_CORBA_float_struct };
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_PointObj_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_struct,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_FLOAT,
   0,
   3,
   (CORBA_TypeCode *) anon_subtypes_array1,
   CORBA_OBJECT_NIL,
   "PointObj",
   "IDL:PointObj:1.0",
   (char **) anon_subnames_array0,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_PointObj_0 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_PointObj_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_PointObj_2 == 'p') \
) && !defined(TC_DEF_TC_CORBA_sequence_PointObj)
#define TC_DEF_TC_CORBA_sequence_PointObj 1
static const CORBA_TypeCode anon_subtypes_array4[] =
   { (CORBA_TypeCode) & TC_PointObj_struct };
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_PointObj_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array4,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_CORBA_sequence_PointObj_0 == 'm') \
&& (TC_IMPL_TC_CORBA_sequence_PointObj_1 == 'a') \
&& (TC_IMPL_TC_CORBA_sequence_PointObj_2 == 'p') \
) && !defined(TC_DEF_TC_CORBA_sequence_PointObj)
#define TC_DEF_TC_CORBA_sequence_PointObj 1
static const CORBA_TypeCode anon_subtypes_array11[] =
   { (CORBA_TypeCode) & TC_PointObj_struct };
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_CORBA_sequence_PointObj_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_sequence,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array11,
   CORBA_OBJECT_NIL,
   NULL,
   NULL,
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_PointObjSequence_0 == 'm') \
&& (TC_IMPL_TC_PointObjSequence_1 == 'a') \
&& (TC_IMPL_TC_PointObjSequence_2 == 'p') \
) && !defined(TC_DEF_TC_PointObjSequence)
#define TC_DEF_TC_PointObjSequence 1
static const CORBA_TypeCode anon_subtypes_array14[] =
   { (CORBA_TypeCode) & TC_CORBA_sequence_PointObj_struct };
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_PointObjSequence_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_alias,
   0,
   0,
   MAX(ORBIT_ALIGNOF_CORBA_POINTER,
       MAX(ORBIT_ALIGNOF_CORBA_LONG, MAX(ORBIT_ALIGNOF_CORBA_STRUCT, 1))),
   0,
   1,
   (CORBA_TypeCode *) anon_subtypes_array14,
   CORBA_OBJECT_NIL,
   "PointObjSequence",
   "IDL:PointObjSequence:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_Mappel_0 == 'm') \
&& (TC_IMPL_TC_Mappel_1 == 'a') \
&& (TC_IMPL_TC_Mappel_2 == 'p') \
) && !defined(TC_DEF_TC_Mappel)
#define TC_DEF_TC_Mappel 1
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_Mappel_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Mappel",
   "IDL:Mappel:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif
#if ( (TC_IMPL_TC_Map_0 == 'm') \
&& (TC_IMPL_TC_Map_1 == 'a') \
&& (TC_IMPL_TC_Map_2 == 'p') \
) && !defined(TC_DEF_TC_Map)
#define TC_DEF_TC_Map 1
#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
const struct CORBA_TypeCode_struct TC_Map_struct = {
   {&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
   CORBA_tk_objref,
   0,
   0,
   ORBIT_ALIGNOF_CORBA_POINTER,
   0,
   0,
   NULL,
   CORBA_OBJECT_NIL,
   "Map",
   "IDL:Map:1.0",
   NULL,
   NULL,
   -1,
   0,
   0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_map
CORBA_unsigned_long Mappel__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_map
CORBA_unsigned_long Map__classid = 0;
#endif

/* Interface type data */

#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
ORBit_IMethod Mappel__imethods[] = {
   {
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_void, "Test", 4,
    0}
};
static CORBA_string Mappel__base_itypes[] = {
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
ORBit_IInterface Mappel__iinterface = {
   TC_Mappel, {1, 1, Mappel__imethods, FALSE},
   {1, 1, Mappel__base_itypes, FALSE}
};

static ORBit_IArg Map_mapString__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "astring"},
   {TC_CORBA_double, ORBit_I_ARG_OUT | ORBit_I_COMMON_FIXED_SIZE, "anum"}
};
static ORBit_IArg Map_doOneWay__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "ignore"}
};
static ORBit_IArg Map_PointFromCoord__arginfo[] = {
   {TC_CORBA_string, ORBit_I_ARG_IN, "coord"}
};
static ORBit_IArg Map_View__arginfo[] = {
   {TC_PointObj, ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, "where"}
};
static ORBit_IArg Map_ViewAll__arginfo[] = {
   {TC_PointObjSequence, ORBit_I_ARG_IN, "where"}
};
static ORBit_IArg Map_Route__arginfo[] = {
   {TC_PointObj, ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, "src"},
   {TC_PointObj, ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, "dst"}
};

#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
ORBit_IMethod Map__imethods[] = {
   {
    {2, 2, Map_mapString__arginfo, FALSE},
    {0, 0, NULL, FALSE},
    {0, 0, NULL, FALSE},
    TC_Map, "mapString", 9,
    0}
   , {
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "doNothing", 9,
      0}
   , {
      {1, 1, Map_doOneWay__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "doOneWay", 8,
      0 | ORBit_I_METHOD_1_WAY}
   , {
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "PlaceFlag", 9,
      0}
   , {
      {1, 1, Map_PointFromCoord__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_PointObj, "PointFromCoord", 14,
      0 | ORBit_I_COMMON_FIXED_SIZE}
   , {
      {1, 1, Map_View__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "View", 4,
      0}
   , {
      {1, 1, Map_ViewAll__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "ViewAll", 7,
      0}
   , {
      {2, 2, Map_Route__arginfo, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_void, "Route", 5,
      0}
   , {
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      {0, 0, NULL, FALSE},
      TC_Mappel, "Get", 3,
      0}
};
static CORBA_string Map__base_itypes[] = {
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_map
static
#endif
ORBit_IInterface Map__iinterface = {
   TC_Map, {9, 9, Map__imethods, FALSE},
   {1, 1, Map__base_itypes, FALSE}
};
