message("Copy '${GLOB_EXP}' to '${DST}'")

file(GLOB SRC_FILES ${GLOB_EXP})

if ( SRC_FILES )
   foreach (FILE ${SRC_FILES})
      if ( LOWER )
         get_filename_component(FILEN_NAME ${FILE} NAME)
         string(TOLOWER ${FILEN_NAME} FILEN_NAME_LOWER)
         execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${FILE} ${DST}/${FILEN_NAME_LOWER})
      else()
         execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${FILE} ${DST}/)
      endif( LOWER )
   endforeach()
endif()
