file(READ "${SRC}" OUTPUT_LINES)
if (PREFIX)
	set(OUTPUT_LINES "<html>" "${OUTPUT_LINES}")
endif()
string(REGEX REPLACE "vehicleprofile" "atkaction" OUTPUT_LINES "${OUTPUT_LINES}")
string(REGEX REPLACE "name=" "description=" OUTPUT_LINES "${OUTPUT_LINES}")
string(REGEX REPLACE "...CDATA" " " OUTPUT_LINES "${OUTPUT_LINES}")
string(REGEX REPLACE "\\]\\]" "" OUTPUT_LINES "${OUTPUT_LINES}")
if (SUFFIX)
	set(OUTPUT_LINES "${OUTPUT_LINES}" "</html>")
endif()
file(WRITE ${DST} ${OUTPUT_LINES})
