#! /bin/sh
function print_defs
{
	type=$1
	while read line
	do
		case $line in
		*2\(*)
			id=${line%%,*}
			id=${id#*(}
			id=$(($id))
			name=${line%%)*}
			name=${name#*,}
			printf "%s%s 0x%x\n" $type $name $id
			id=$((id+1))
			;;
		*)
			name=${line%%)*}
			name=${name#*(}
			printf "%s%s 0x%x\n" $type $name $id
			id=$((id+1))
		esac
	done
}
dir=$0
dir=${dir%/*}
dir=$dir/../
id=0
grep ^ITEM $dir/item_def.h | print_defs type_
id=0
grep ^ATTR $dir/attr_def.h | print_defs attr_
