SET(CMAKE_SYSTEM_NAME WINCE)

# specify the cross compiler
FIND_PROGRAM(CMAKE_C_COMPILER NAMES i386-mingw32ce-gcc )
FIND_PROGRAM(CMAKE_CXX_COMPILER NAMES i386-mingw32ce-g++ )
FIND_PROGRAM(CMAKE_RC_COMPILER_INIT NAMES i386-mingw32ce-windres )
SET(PKG_CONFIG_EXECUTABLE "i386-mingw32ce-pkg-config")
SET(WINCE TRUE)
