SET(CMAKE_C_COMPILER ${TARGET_ARCH}-gcc)
SET(CMAKE_CXX_COMPILER ${TARGET_ARCH}-g++)
SET(CMAKE_RC_COMPILER_INIT ${TARGET_ARCH}-windres)
SET(PKG_CONFIG_EXECUTABLE ${TARGET_ARCH}-pkg-config)

# unecessary according to https://cmake.org/cmake/help/v3.4/variable/WINCE.html
# TODO: plateform wince change too much things for now, fix later.
# WindowsCETest -> WindowsCE
if (CMAKE_SYSTEM_NAME STREQUAL "WindowsCETest")
  SET(CMAKE_EXECUTABLE_SUFFIX ".exe")
  SET(WINCE TRUE)
endif()

if(WINCE)
  # MINGW32CE_PATH is set in dockerfile
  message(STATUS "Wince toolchain in $ENV{MINGW32CE_PATH}")

  #SET(CMAKE_FIND_ROOT_PATH $ENV{MINGW32CE_PATH})
  #SET(CMAKE_INSTALL_PREFIX $ENV{MINGW32CE_PATH})
endif(WINCE)

if(WIN32)
  message(STATUS "WIN32 case")
  #SET(CMAKE_FIND_ROOT_PATH ${MINGW_INSTALL_PREFIX})
  #SET(QT_MOC_EXECUTABLE bin/moc)
  #SET(QT_RCC_EXECUTABLE ${MINGW_INSTALL_PREFIX}/bin/rcc)
  #SET(QT_UIC_EXECUTABLE ${MINGW_INSTALL_PREFIX}/bin/uic)
  SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

  SET(CMAKE_FIND_ROOT_PATH ${MINGW_INSTALL_PREFIX})
  SET(CMAKE_INSTALL_PREFIX ${MINGW_INSTALL_PREFIX})
endif()
